## Make labels using an LLM for each feature in a model
For now, use gpt-4o-mini with a template derived from https://arxiv.org/pdf/2408.00657v1

We want to provide maximum activating examples, as well as "control" samples that dont activate the feature. Instead of using random sample lets try to pull from similar features.
TODO: double check my similarity search because the similar features don't seem to give similar samples at all.

In [1]:
import pandas as pd
from latentsae import Sae
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

/Users/enjalot/code/latent-taxonomy/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Triton not installed, using eager implementation of SAE decoder.

In [29]:
sae = "64_32"
model = Sae.load_from_hub("enjalot/sae-nomic-text-v1.5-FineWeb-edu-100BT", sae)
name = f"NOMIC_FWEDU_{round(model.num_latents/1000)}k"

Fetching 2 files: 100%|██████████| 2/2 [00:00<00:00, 40920.04it/s]
Dropping extra args {'signed': False}

In [3]:
features = range(model.num_latents)

In [4]:
top10_df = pd.read_parquet(f"data/top10_{sae}.parquet")

In [5]:
top10_df.head()

,chunk_index,chunk_text,chunk_token_count,id,url,score,dump,embedding,top_acts,top_indices,feature,activation
0,0,"2019 Study Abstract\nGenomic imprinting, the m...",191,<urn:uuid:d45d32f3-aee4-464b-a7a7-4659ca6f95a5>,https://desdaughter.com/2019/01/21/genomic-imp...,2.859375,CC-MAIN-2019-18,"[0.070664756, 0.04058804, -0.1678945, -0.04720...","[0.29729074239730835, 0.23520702123641968, 0.1...","[0.0, 19961.0, 19487.0, 3596.0, 9132.0, 16563....",0,0.297291
4973,1,biological function and regulation of imprinte...,500,<urn:uuid:6492a5df-795c-4afc-8b96-adda43d374fe>,http://www.biomedcentral.com/1471-2164/10/144,2.640625,CC-MAIN-2015-11,"[0.08591175, 0.05282476, -0.1623837, -0.038760...","[0.2801821529865265, 0.21019425988197327, 0.11...","[0.0, 19961.0, 12474.0, 18618.0, 5676.0, 18178...",0,0.280182
2426,0,Molecular imprinting is a technique used to cr...,277,<urn:uuid:c4cec9f7-a221-4bac-8872-ad938bbe3b9c>,https://www.advancedsciencenews.com/new-trends...,2.796875,CC-MAIN-2021-04,"[0.06389447, 0.054419804, -0.1866366, -0.05261...","[0.27958399057388306, 0.15807494521141052, 0.1...","[0.0, 21919.0, 18672.0, 3614.0, 13226.0, 15727...",0,0.279584
44507,0,[CLS] imprinting / do not go where the path ma...,500,<urn:uuid:fd9748b7-ad11-4d51-b7d9-b5681c579e36>,https://www.windermeresun.com/2017/08/05/impri...,3.218750,CC-MAIN-2023-40,"[0.045871254, 0.0841982, -0.20583852, -0.07991...","[0.27171218395233154, 0.24269740283489227, 0.1...","[0.0, 6864.0, 8104.0, 3020.0, 15020.0, 8543.0,...",0,0.271712
7496,0,There have been a number of recent insights in...,212,<urn:uuid:40c30498-bed6-4b01-a37e-a2a1b70d80fd>,https://pure.ulster.ac.uk/en/publications/impr...,3.078125,CC-MAIN-2021-10,"[0.06898261, 0.04841869, -0.16367012, -0.05253...","[0.2717033922672272, 0.2493799477815628, 0.117...","[0.0, 19961.0, 21919.0, 14900.0, 22498.0, 1514...",0,0.271703

In [6]:
wtop10_df = pd.read_parquet(f"data/wikipedia_top10_{sae}.parquet")

In [7]:
wtop10_df.head()

,chunk_index,chunk_text,chunk_tokens,chunk_token_count,id,url,title,feature,activation,top_indices,top_acts
7187,0,Imprint or imprinting may refer to:\n\nEnterta...,"[101, 15738, 2030, 15738, 2075, 2089, 6523, 20...",381,13233439,https://en.wikipedia.org/wiki/Imprint,Imprint,0,0.319003,"[323.0, 9207.0, 17432.0, 22998.0, 1309.0, 8990...","[0.20592115819454193, 0.18189126253128052, 0.1..."
68637,0,An imprinter may mean:\n\n Credit card imprint...,"[101, 2019, 15738, 2121, 2089, 2812, 1024, 492...",52,3741617,https://en.wikipedia.org/wiki/Imprinter,Imprinter,0,0.257223,"[18027.0, 21878.0, 5937.0, 10153.0, 668.0, 132...","[0.26385897397994995, 0.16845473647117615, 0.1..."
0,6,"of higher order chromatin structure, non - cod...","[1997, 3020, 2344, 10381, 21716, 20363, 3252, ...",500,46697210,https://en.wikipedia.org/wiki/Epigenetics%20of...,Epigenetics of human development,0,0.249096,"[22208.0, 8733.0, 6650.0, 7287.0, 18467.0, 132...","[0.17569296061992645, 0.14475393295288086, 0.1..."
215316,0,[CLS] molecular imprinting is a technique to c...,"[101, 8382, 15738, 2075, 2003, 1037, 6028, 200...",500,1938226,https://en.wikipedia.org/wiki/Molecular%20impr...,Molecular imprinting,0,0.244627,"[8.0, 14532.0, 17432.0, 6981.0, 9934.0, 13226....","[0.18811044096946716, 0.18796460330486298, 0.1..."
176292,17,imprinters. men in a position of power or futu...,"[15738, 2545, 1012, 2273, 1999, 1037, 2597, 19...",500,100626,https://en.wikipedia.org/wiki/Bene%20Gesserit,Bene Gesserit,0,0.244431,"[1851.0, 1381.0, 15146.0, 2596.0, 21469.0, 232...","[0.20756396651268005, 0.20743057131767273, 0.1..."

In [8]:
wtop10_df.columns

Index(['chunk_index', 'chunk_text', 'chunk_tokens', 'chunk_token_count', 'id',
       'url', 'title', 'feature', 'activation', 'top_indices', 'top_acts'],
      dtype='object')

In [9]:
weights = [model.W_dec[i].detach().cpu().numpy() for i in range(model.W_dec.size(0))]
def get_similar_features(feature):
    # Get the weight vector for the given feature
    feature_weight = weights[feature].reshape(1, -1)
    # Calculate cosine similarity between the feature weight and all weights
    similarities = cosine_similarity(feature_weight, weights)
    sorted = np.argsort(similarities[0])[::-1]
    # print("similarities", sorted)
    # print("similarities", similarities[0][sorted])
    # Get the indices of the top 5 most similar weights (excluding the feature itself)
    similar_indices = np.argsort(similarities[0])[-6:-1][::-1]  # Get top 5, excluding the feature itself
    return similar_indices.tolist()

In [10]:
# get_similar_features(5)

In [11]:
def get_samples(df, feature):
  # get top 10 activations
  top = df[df.feature == feature]["chunk_text"].tolist()
  # get 5 similar features
  similar_features = get_similar_features(feature)
  similar = df[df.feature.isin(similar_features)]
  similar = similar[~similar.top_indices.isin([feature])]
  
  control = similar.sample(10)["chunk_text"].tolist()
  # grab 2 samples for each of those features
  return { "top": top, "control": control, "similar_features": similar_features}

In [12]:
f0 = get_samples(top10_df, 0)
w0 = get_samples(wtop10_df, 0)

In [13]:
f0["top"]

['2019 Study Abstract\nGenomic imprinting, the monoallelic and parent-of-origin-dependent expression of a subset of genes, is required for normal development, and its disruption leads to human disease.\nImprinting defects can involve isolated or multilocus epigenetic changes that may have no evident genetic cause, or imprinting disruption can be traced back to alterations of cis-acting elements or trans-acting factors that control the establishment, maintenance and erasure of germline epigenetic imprints.\nRecent insights into the dynamics of the epigenome, including the effect of environmental factors, suggest that the developmental outcomes and heritability of imprinting disorders are influenced by interactions between the genome, the epigenome and the environment in germ cells and early embryos.\nThis review focuses on imprints that effect essentially permanent and ubiquitous changes on gene expression potential at affected loci, as opposed to tissue-specific or transient changes.',
 "biological function and regulation of imprinted genes. to date, approximately 100 genes with evidence for imprinting effects in either human or mouse are described. based on recent predictions, the number of mammalian imprinted genes may range between 100 and 600 genes [ 1 - 4 ], i. e. a substantial number of imprinted genes are already identified. the imprinted expression of genes appears to be a rather conserved phenomenon in mammals ; i. e., genes that are found to be imprinted in one species are most likely imprinted in the other. this tenet, however, is not always fixed, as has been shown for the two orthologous man and mouse genes l3mbtl and l3mbtl. these genes each encode a polycomb protein. in human, the gene is frequently absent in patients with myeloid malignancies. human l3mbtl has been shown to be paternally expressed due to monoallelic methylation [ 5, 6 ] whereas mouse l3mbtl is not imprinted nor are its cpg islands differentially methylated. orthologous genes that are imprinted in human and mouse are most likely either maternally or paternally expressed in both organisms. rarely, genes are oppositely imprinted such as the zim2 / zim2 genes : human zim2 is paternally expressed while mouse zim2 is maternally expressed. this phenomenon might be explained by the fact that the human zim2 gene shares 5'exons and a promoter with the likewise paternally expressed peg3 gene, while mouse zim2 appears not to do so. imprinted genes have been hypothesized to play a major role in the regulation of embryonic growth [ 8 - 10 ], to control placental function and to modulate the transport of nutrients from mother to embryo. indeed, a number of imprinted genes, such as ascl2, phlda2, peg10, are indispensable for proper placental morphology and function while others are involved in nutrient supply regulation [ 11 - 14 ]. additionally, there is strong evidence that imprinted genes control neurological development and function as well as energy homeostasis in postnatal stages of development and the adult [ 9, 15, 16 ]. based on these various observations it seems likely that imprinted genes are tightly regulated in a developmental and tissue specific manner. while tissue specific expression profiles have been examined for some selected genes",
 'Molecular imprinting is a technique used to create ‘customized’ binding cavities that possesses the specific shape and polarity needed to capture only target species, in a “key to lock” process. The technique is valuable in separations, biosensors and biodiagnostics (e.g. as “artificial antibodies”).\nBecause of the importance of molecularly imprinted materials, improved methods to create more efficient and more specific binding cavities, so that target species can be captured more easily and quickly, are being sought.\nIn their recently published Review, Xiaochu Ding and Patricia A. Heiden (Michigan Technological University, Houghton) discuss how surface imprinting techniques are designed and performed to give specific binding cavities on the surface of various nanoparticles to produce molecularly imprinted polymeric nanoparticles (MIPNPs) with high capture efficiency to target species. Their review also describes applications and new trends to design multi-functional MIPNPs, which combine specific capturing, separation and detection all-in-one for high throughput applications.\nIt is expected that efforts to improve specificity and impart multiple capability to MIPNPs will continue, along with efforts to allow these MIPNPs to be mass produced using cost-effective methods to provide high throughput analyses to meet market requirements.',
 '[CLS] imprinting / do not go where the path may lead …. dear friends & neighbors, pet of the week, 8 / 5 / 2017, below : ever heard of imprinting? information on imprinting, gathered from wikipedia, in italics, below : in psychology and ethology, imprinting is any kind of phase - sensitive learning ( learning occurring at a particular age or a particular life stage ) that is rapid and apparently independent of the consequences of behavior. it was first used to describe situations in which an animal or person learns the characteristics of some stimulus, which is therefore said to be “ imprinted ” onto the subject. imprinting is hypothesized to have a critical period. the best - known form of imprinting is filial imprinting, in which a young animal acquires several of its behavioral characteristics from its parent. it is most obvious in nidifugous birds, which imprint on their parents and then follow them around. it was first reported in domestic chickens, by the 19th - century amateur biologist douglas spalding. it was rediscovered by the early ethologist oskar heinroth, and studied extensively and popularized by his disciple konrad lorenz working with greylag geese. lorenz demonstrated how incubator - hatched geese would imprint on the first suitable moving stimulus they saw within what he called a “ critical period ” between 13 – 16 hours shortly after hatching. for example, the goslings would imprint on lorenz himself ( to be more specific, on his wading boots ), and he is often depicted being followed by a gaggle of geese who had imprinted on him. lorenz also found that the geese could imprint on inanimate objects. in one experiment, they followed a box placed on a model train in circles around the track. filial imprinting is not restricted to non - human animals that are able to follow their parents, however. the filial imprinting of birds was a primary technique used to create the movie winged migration ( le peuple migrateur ), which contains a great deal of footage of migratory birds in flight. the birds imprinted on handlers, who wore yellow jackets and honked horns constantly. the birds were then trained to fly along with a variety of aircraft, primarily ultralights. sexual imprinting is the process by which a young animal learns the characteristics of a desirable mate. for example, male zebra finches appear to prefer mates with the appearance',
 'There have been a number of recent insights in the area of genomic imprinting, the phenomenon whereby one of two autosomal alleles is selected for expression based on the parent of origin. This is due in part to a proliferation of new techniques for interrogating the genome that are leading researchers working on organisms other than mouse and human, where imprinting has been most studied, to become interested in looking for potential imprinting effects. Here, we recap what is known about the importance of imprints for growth and body size, as well as the main types of locus control. Interestingly, work from a number of labs has now shown that maintenance of the imprint post implantation appears to be a more crucial step than previously appreciated. We ask whether imprints can be reprogrammed somatically, how many loci there are and how conserved imprinted regions are in other species. Finally, we survey some of the methods available for examining DNA methylation genome-wide and look to the future of this burgeoning field.',
 '##2 - 8674 ( 91 ) 90513 - x. bartolomei ms, ferguson - smith ac : mammalian genomic imprinting. cold spring harb perspect biol 2011, 3. doi : 10. 1101 / cshperspect. a002592., kobayashi s, wagatsuma h, ono r, ichikawa h, yamazaki m, tashiro h, aisaka k, miyoshi n, kohda t, ogura a, ohki m, kaneko - ishino t, ishino f : mouse peg9 / dlk1 and human peg9 / dlk1 are paternally expressed imprinted genes closely located to the maternally expressed imprinted genes : mouse meg3 / gtl2 and human meg3. genes cells. 2000, 5 : 1029 - 1037. 10. 1046 / j. 1365 - 2443. 2000. 00390. x. bartolomei ms, zemel s, tilghman sm : parental imprinting of the mouse h19 gene. nature. 1991, 351 : 153 - 155. 10. 1038 / 351153a0. ferguson - smith ac, sasaki h, cattanach bm, surani ma : parental - origin - specific epigenetic modification of the mouse h19 gene. nature. 1993, 362 : 751 - 755. 10. 1038 / 362751a0. blagitko n, mergenthaler s, schulz u, wollmann ha, craigen w, eggermann t, ropers hh, kalscheuer vm : human grb10 is imprinted and expressed from the paternal and maternal allele in a highly tissue - and isoform - specific fashion. hum mol genet. 2000, 9 : 1587 - 1595. 10. 1093 / hmg / 9. 11. 1587. garfield as, cowley m, smith fm, moorwood k, stewart - cox je, gilroy k, baker s, xia j, dalley jw, hurst ld, wilkinson ls, isles ar, ward a : distinct physiological and behavioural functions for parental alleles of imprinted grb10. nature. 2011, 469 : 534 - 538. 10. 1038 / nature09651. willson',
 '[CLS] an imprint is a memory, or recording, of an event, experience, or environment, which is stored in both your physical and energy body ’ s – your body - system. your physical and energy bodies are integral. imprints are your way of storing experiences, some of which may have been traumatic, stressful, or difficult. you may have no conscious awareness of these imprints, but they are profoundly present in your life in many ways. you have a stored body memory of the environment in which you grew, and all that happened there in your first 9 months. prenatal and birth experiences in particular are recorded in this way because they are preverbal, and are stored in your body - system, remaining there until you consciously connect with your young self and bring support to her / him. however, many later stages of your life experiences, after birth, infancy and early childhood are also stored this way in your body - system. this kind of memory is often referred to as implicit memory, which refers to your emotional brain. anything stored in the emotional brain has its physiological and energetic expression in your mind - body - soul system, this is just another way of talking about the same thing. imprints can express themselves through : physical symptoms, emotions, relationship choices and dynamics, attachment dynamics, parenting, over - emotional reactions to certain situations, movement patterns, postures, tactile sensitivity, illness, nervous system regulation and dysregulation, how safe you feel, your resilience levels, whether you are calm and resourced or not, and more. imprints from the past feel real when they come up, and as if they are happening right now, in present time. often you will have no idea that this is what is happening, and it can be confusing. one of the skills i teach people is how to recognize when they are in an imprint from the past. they also learn how to resource themselves so they can have the choice to do something different about it now. you don ’ t have to keep repeating painful, difficult, or traumatic imprints. they can be healed and re - patterned. your little one within is often having a reaction to life, as s / he perceived it to be in the womb, and acting out of responses learned in the womb that are no longer serving you as an adult. imprints remain in your body - system, affecting you on all levels. if you had a bad knee, you would change',
 '##al stages of development and the adult [ 9, 15, 16 ]. based on these various observations it seems likely that imprinted genes are tightly regulated in a developmental and tissue specific manner. while tissue specific expression profiles have been examined for some selected genes, no study on the entire class of imprinted genes has been performed so far. furthermore little is known about the expression status in adult tissues compared to embryonic states. in this study we performed a computational expression analysis of human and mouse imprinted genes in a variety of non - cancerous tissues using a set of existing systematic transcriptional profiling data. in particular, we ( 1 ) compared the profiles of individual genes across tissues, ( 2 ) analysed the correlations of expression patterns in human and mouse, and ( 3 ) explored the role of predicted transcription factor binding sites in correlation to tissue specific expression. our data provide new insights into the range and extend of expression, the tissue specific function and the regulation of imprinted genes in two mammalian species. sets of imprinted genes selected for analysis the imprinted gene catalogue ( igc ) [ 1, 18 ] reports imprinted genes in various species, including human and mouse. we gathered information from the igc on 62 genes for which solid experimental data on allele - specific expression was available [ see additional file 1 ] ( see methods for definition of exclusion criteria ). among these 62 genes, only 30 had been analysed in human as well as in mouse revealing that 26 of these are imprinted in both species. for one of these genes the status was only confirmed in human, for 3 genes only in mouse. thus, of the genes analysed in both species 87 % showed conservation of imprinting. for the additional 23 imprinted genes the imprinting status had only been analysed in mouse, and for additional 9 genes only in human. additional file 1. genomic localization, imprinting status, availability of expression data of 62 imprinted genes from imprinted genes catalogue ( igc ). a gene names of imprinted genes in human and mouse ( in brackets ). b genomic localization of imprinted genes in human and mouse ( in brackets ). c imprinting status : tick = imprinting status confirmed,? = questionable imprinting status, n = not imprinted, no = no orthologous, as = antisense. d expressed allele : m = maternal, p = paternal, p / m = opposite',
 ', in both the embryo and endosperm, seem to be imprinted allele - specifically rather than locus - specifically and / or imprinting could be specific to a given developmental stage. in addition, different statistical procedures to select potentially imprinted genes may also contribute to the discrepancies. analyzing the datasets prior to stringent filtering increases the overlap, as well as treating two different datasets with the same statistical pipeline. taken together, the recent rapid development of high - throughput transcriptome sequencing allows large - scale identification of imprinted genes in different organisms and tissues. yet, the obvious discrepancy between different datasets shows that in - depth analyses and substantial validation of imprinted candidate genes using alternative methods is necessary. in conclusion, we show that at least nine megs and one peg are regulated by genomic imprinting in the embryo and, in addition, two megs display steady - state monoallelic expression in the embryo. likely, the list of megs and pegs in plant embryos will expand in the future by validating additional candidates or by high - throughput sequencing of additional embryonic samples. delayed paternal gene activation in the embryo is distinct from embryonic imprinting in a former study, we have shown that the embryo transcriptome of intraspecific ( ler x col - 0 ) hybrids showed an overall maternal dominance, albeit 66 % of the genes were biparentally expressed,. although this wide - spread maternal dominance was recently challenged by a study using different accessions and amplification techniques,, our genetic analyses further demonstrated that the underrepresentation of paternal transcripts is regulated by a maternal sirna - based silencing mechanism. however, dna methylation and prc2 - mediated repression, two epigenetic pathways often associated with imprinting, were not involved. in addition, the vast majority of genes that were maternally dominant at the 2 – 4 cell stage have a higher paternal contribution at the globular stage. the biallelic control gene used in this study, at1g02780, is a good example for a gene showing biased expression in 2 – 4 cell embryos but an equal parental contribution at the globular stage, a pattern that we confirmed using allele - specific expression analysis ( figure s1a, ). in contrast, for all potentially imprinted genes identified in this study exclusively reads from one parent only were found in all stages and replicate',
 'to matter, leaving the shape - shifter with a deep need to do anything to please and protect his … what are some examples of imprinting? imprinting is important for raising the young, as it encourages them to follow their parents. this is referred to as “ filial imprinting. ” for example, in the wild, animals learn to hunt while watching their parents hunt. in humans, babies learn to speak by mimicking their parents ’ speech. many birds “ sing ” by imitating those around them. what is the importance of genomic imprinting? more importantly, that “ label ” of methyl groups on the specific gene will be passed on to the subsequent chromosomes following gametogenesis, ensuring that the gene remains imprinted. genomic imprinting is our dna ’ s method of regulating transcription, and essentially keeping genes turned on or off across multiple generations. what is an imprinted gene? imprinted genes are those in which the copy from one parent is silenced through epigenetic modifications, which are changes to dna that affect the function of genes but not the underlying dna sequence. “ although imprinted genes represent a small portion of the mammalian genome, … what is dna imprinting? researchers believe genetic imprinting is a mechanism intended to prevent damaging mutations from propagating ( extending themselves ). genetic imprinting appears to affect only certain chromosomes and, when it causes a disease state, results in related though differing symptoms, depending on the deletion. [SEP]']

In [14]:
w0["top"]

['Imprint or imprinting may refer to:\n\nEntertainment\n Imprint (TV series), Canadian television series\n "Imprint" (Masters of Horror), episode of TV show Masters of Horror\n Imprint (film), a 2007 independent drama/thriller film\n Imprint Entertainment, film and TV production and management company\n Imprint Records, American country music record label\n Imprint (John Patitucci album), jazz album\n Imprint (Vision of Disorder album), 1998 album\n ”Imprint”, a song by Zayn from his 2018 album Icarus Falls\n Imprint label, a recording trade name\n\nPublishing and journalism\n Imprint, British term comparable to American masthead\n Imprint (trade name), publisher\'s trade name under which works are published\n Imprint (typeface), typeface commissioned from Monotype by the London publishers of The Imprint\n Imprinted stamp, a stamp printed onto a piece of postal stationery\n The Imprint (printing trade periodical), printed in London in 9 issues in 1913\n Imprint (newspaper), a student newspaper of the University of Waterloo, in Ontario, Canada\n Imprint, a part of Macmillan Publishers Children’s Publishing Group.\n\nScience\n Molecular imprinting, in polymer chemistry\n Imprinting (psychology), in psychology and ethology\n  Video imprint, in video content analysis of computer vision\n High-level human behavior\n IMPRINT (Improved Performance Research Integration Tool), human performance modeling tool based on MANPRINT, developed by U.S. Army\n Imprinting (organizational theory), in organizational theory and organizational behavior\n Unconscious physiological processes:\n Genomic imprinting (genetic imprinting), mechanism of regulating gene expression\n Limbic imprint, process by which prenatal, perinatal, and post-natal experiences imprint on limbic system\n Metabolic imprinting, phenomenon by which the metabolism of a developing fetus may be "programmed" during gestation\n\nOther uses\n Imprint (sculpture), a glass sculpture made by Luciano Fabro\n\nSee also\n \n \n \n \n Impr.\n Imprimatur',
 "An imprinter may mean:\n\n Credit card imprinter, a mechanical device for transfer of payment card details to paper\n Imprinter (Dune), a type of fictional character in Frank Herbert's  Dune universe\n\nSee also\n Imprint (disambiguation)",
 'of higher order chromatin structure, non - coding rnas, and interfering rnas. function a single evolutionary purpose of imprinting is still unknown, since the mechanisms and effects seem to be so diverse. one hypothesis states that imprinting occurs in order to carry out the evolutionary goal of the parent, that being the differential partition of resources. the male seeks to provide maximum resources for his offspring so that his genes may be passed on successfully to the next generation, whereas the female must partition resources between all her offspring, and so must limit resources given. another hypothesis states that imprinting may help protect the female from ovarian trophoblastic disease and parthenogenesis. trophoblastic disease occurs when a sperm fertilizes an egg with no nucleus and a cancer - like mass forms in the placenta. parthenogenesis occurs when an unfertilized egg develops into a fully functional organism that is genetically identical to the parent, who is female in the case of animals or both sexes, in the case of plants. this does not occur naturally in mammals. in most animals, especially mammals, uniparental inheritance of chromosomes is often lethal or results in developmental abnormalities, sometimes physically but often cognitively. other hypotheses point to the function of imprinting as a way of establishing the proper amount of expression or functional haploidy, much like silencing the extra x - chromosome in females ( see section on barr bodies ). imprinting may help in the differentiation of cells by silencing pluripotency genes or other developmental genes. supporting this hypothesis, imprinted genes have been shown to differ in their expression between tissue types in the same organism, pointing to divergent outcomes as a result of developmental events during embryogenesis. regardless of whether there is a single purpose for imprinting, numerous studies have shown that a normal and functional organism cannot be made without the various imprinting mechanisms. igf2 and h19 in mammals, imprinted genes are often clustered in the genome, probably because they share transcriptional regulators or regulatory regions that impact the expression of multiple genes. it is easier for a lncrna to silence multiple genes if they are closer together, making silencing more efficient. in some cases, when a gene is transcribed it overlaps another region nearby or opposite ( antisense ) to it, often silencing it. in the case of the ifg2 and h19 genes, ct',
 '[CLS] molecular imprinting is a technique to create template - shaped cavities in polymer matrices with predetermined selectivity and high affinity. this technique is based on the system used by enzymes for substrate recognition, which is called the " lock and key " model. the active binding site of an enzyme has a shape specific to a substrate. substrates with a complementary shape to the binding site selectively bind to the enzyme ; alternative shapes that do not fit the binding site are not recognized. molecularly imprinted materials are prepared using a template molecule and functional monomers that assemble around the template and subsequently get cross - linked to each other. the monomers, which are self - assembled around the template molecule by interaction between functional groups on both the template and monomers, are polymerized to form an imprinted matrix ( commonly known in the scientific community as a molecular imprinted polymer ( mip ) ). the template is subsequently removed in part or entirely, leaving behind a cavity complementary in size and shape to the template. the obtained cavity can work as a selective binding site for the templated molecule. in recent decades, the molecular imprinting technique has been developed for use in drug delivery, separations, biological and chemical sensing, and more. taking advantage of the shape selectivity of the cavity, use in catalysis for certain reactions has also been facilitated. history the first example of molecular imprinting is attributed to m. v. polyakov in 1931 with his studies in the polymerization of sodium silicate with ammonium carbonate. when the polymerization process was accompanied by an additive such as benzene, the resulting silica showed a higher uptake of this additive. by 1949, the concept of instructional theory molecular imprinting was used by dickey ; his research precipitated silica gels in the presence of organic dyes and showed imprinted silica had high selectivity towards the template dye. following dickey ’ s observations, patrikeev published a paper of his ‘ imprinted ’ silica with the method of incubating bacteria with gel silica. the process of drying and heating the silica promoted growth of bacteria better than other reference silicas and exhibited enantioselectivity. he later used this imprinted silica method in further applications such as thin layer chromatography ( tlc ) and high performance liquid chromatography ( hplc ). in 1972, wulff and klotz introduced',
 'imprinters. men in a position of power or future power, or those with specific qualities that the order wishes to incorporate into their breeding program, are typical targets of a bene gesserit imprinter. men seduced by an imprinter are permanently affected ( imprinted ) by the intense sexual experience and are thereafter consciously or subconsciously favorable to the sisterhood. an imprinter can be successfully resisted if the subject has been psychologically pre - conditioned to do so, and the subject\'s automatic defensive response may even be entirely subconscious. in dune, lady fenring is instructed by the bene gesserit to seduce feyd - rautha harkonnen in order to " preserve the bloodline " by retrieving his genetic material through conception. she also intends to " plant deep in his deepest self the necessary prana - bindu phrases to bend him ", which she later refers to as the " hypno - ligation of that feyd - rautha\'s psyche ". when paul later fights feyd to the death, jessica advises her son to temporarily stun him using the word - sound uroshnor, typically implanted in a dangerous person who has been prepared by the bene gesserit. paul, however, refuses to use this advantage. in heretics of dune, reverend mother and imprinter lucilla is charged with the seduction - imprinting of the duncan idaho ghola so that the sisterhood may assert some control over him ; he ultimately avoids her. lucilla also mentions the hundreds of sexual positions and variations she knows. in heretics, the honored matres have themselves refined this ability to such an intense level that the targeted male becomes completely enslaved. the captured honored matre murbella attempts this on duncan ; his own imprinting ability, secretly conditioned into him by his tleilaxu creators, suddenly manifests itself. murbella and duncan imprint each other, neither having complete control over the other. in chapterhouse dune the order has learned the honored matre method from murbella and use it for their own purposes, specifically to awaken the memories within the miles teg ghola. weaknesses addiction to melange reverend mothers are dependent on melange to give them their abilities. any person who consumes melange regularly becomes addicted to it and requires it for survival ; however, one who has gone through the agony has a far greater need. though the effects of melange are',
 "appear to have no effect, or if the gene is clearly related to function the imprinted expression of the gene does not. as with intrauterine conflict, genomic imprinting is believed to be highly related to placentation, because evidence of genomic imprinting is found only in placental mammals, leading to the hypothesis that genomic imprinting and placentation are evolutionarily linked. imprinted gene expression is shown to be integral to normal development and functioning of the placenta. furthermore, the web of signaling which is expressed between fetus, placenta, and maternal hypothalamus is likely the result of co - adaptations of gene expression related to fetal growth and brain development. disorders of imprinting the discovery of the genomic imprinting phenomenon helped researchers to understand the basis for several disorders with otherwise unclear inheritance patterns including prader - willi / angelman syndromes, beckwith - wiedemann syndrome, and silver - russell syndrome. disorders of imprinting are thought to be related to abnormal dna methylation, which may involve multiple imprinted loci. evidence that assistive - reproductive technology and peri - conceptional environmental factors such as maternal diet are implicated in imprinting - related disorders draws a link between oocyte health and proper imprinting development. prader - willi syndrome and angelman syndrome prader - willi and angelman syndromes are genetic disorders which are caused when the only copy of an imprinted gene is the'silent'copy and the active copy is absent, either due to a deletion or to uniparental disomy. both are due to the absence of gene expression at 15q11 – q13, wherein prader - willi is believed to reflect the absence of the paternally derived gene, and angelman syndrome reflects the absence of the maternal copy. in the case of prader - willi syndrome, the paternal copy is absent while the maternal'silent'copy is present. prader - willi syndrome is characterized by low birth weight, hypersomnolence, low appetite and poor suckling. the child typically develops a voracious appetite around 1 - 2 years of age which typically leads to early onset obesity. children with prader - willi syndrome typically have reduced height throughout childhood and absence of pubertal growth. kinship theory a paradigm used to study genomic imprinting is kinship theory. kinship theory argues that imprinting evolves due to",
 '[CLS] in organizational theory and organizational behavior, imprinting is a core concept describing how the past affects the present. imprinting is generally defined as a process whereby, during a brief period of susceptibility, a focal entity or actor ( such as an industry, organization, or an individual ) develops characteristics that reflect prominent features of the environment, and these characteristics continue to persist despite significant environmental changes in subsequent periods. this definition emphasizes three key elements of imprinting : brief sensitive periods of transition during which the focal entity exhibits high susceptibility to external influences ; a process whereby the focal entity comes to reflect elements of its environment during a sensitive period ; and the persistence of imprints despite subsequent environmental changes. organizational research on imprinting the use of the imprinting concept ( although not the term itself ) in organizational theory dates back to arthur stinchcombe ’ s 1965 paper entitled " social structure and organizations. " this essay focused on understanding why organizations and industries that were founded in the same period were so similar even today. according to this essay, external environmental forces powerfully shaped firms ’ initial structures during the founding period, and these structures persisted in the long run, well beyond the time of founding. for example, as most university fraternities emerged in three different waves, their current organizational features still reflect the imprint of one of these three periods. the first wave of foundings reflected the secularization of northern liberal arts colleges in the 1840s ; the second wave began in the south in the latter half of the 1860s ; and the third wave came between 1900 and 1920, when marginalized populations of black, catholic, and jewish students established fraternities emphasizing anti - discrimination goals. in subsequent periods, each of these three different types carried the legacy of their founding environment. even though stinchcombe did not specifically use the term " imprinting, " the term soon became associated with his essay. stinchcombe ’ s primary focus was at the industry level, but most subsequent studies have examined how individual organizations bear a lasting imprint of founding conditions. for instance, in a series of studies on silicon valley high - tech start - ups, scholars have measured founders ’ mental models and initial decisions and then tracked how these founding conditions influenced subsequent organizational trajectories. the results suggest that the organizational patterns set by a founder have persistent effects on a wide array of outcomes even after the founder leaves the firm. imprinting at other levels of analysis even though the organization has been the dominant level',
 '[CLS] imprint is a serif typeface created by monotype, commonly used for body text. originally called imprint old face, it is a sturdy, amiable design with a large x - height, caslon - like but with more regularity in its letterforms. it was commissioned by the london publishers of the imprint, a short - lived printing trade periodical published during 1913. imprint has remained popular and is sold digitally by monotype. a " shadowed " or inline version, with a cut taken out of the letters, has been widely released with microsoft software, and is often used, especially in desktop publishing, for mastheads and titles. history imprint was produced for the magazine ( on a non - exclusive basis ) in 1912 by the monotype company as series 101 for automatic composition on the monotype caster. when delivered to the journal\'s printers on december 31, 1912, it was still incomplete — the accents had not yet been made — so the editors asked in the first issue : “ will readers kindly insert them for themselves, if they find their omission harsh? for ourselves, we rather like the fine careless flavour, which their omission gives, after we have recovered from the first shock inevitable to us typographical precisians ”. its design was carried out by the monotype engineering team in salfords, surrey, led by engineer frank hinman pierpont and draughtsman fritz stelzer. james mosley describes imprint as " an intelligent updating of caslon " and has credited the monotype team for crafting a " re - draw [ done ] in a manner that suited modern machine printing while keeping as much as possible of the spirit of the original. " contemporary type designer kris sowersby has praised it for its " subtle, gentle stress and its restrained detailing ". perhaps the most notable use since then has been for the entire setting of the second edition of the oxford english dictionary ( 1989 ), 22, 000 pages of precisely structured typography in 20 volumes. digital versions it is available today as a digital opentype font from monotype\'s successor, monotype imaging, in regular, italic, bold and bold italic styles, as well as shadowed and shadowed italic styles ( matching the bold weight ). the current pro release features text figures and small caps, the latter in the roman or regular style only. sowersby\'s untitled serif is also loosely inspired by imprint. references monotype',
 '[CLS] in psychology and ethology, imprinting is any kind of phase - sensitive learning ( learning occurring at a particular age or a particular life stage ) that is rapid and apparently independent of the consequences of behaviour. it was first used to describe situations in which an animal or person learns the characteristics of some stimulus, which is therefore said to be " imprinted " onto the subject. imprinting is hypothesized to have a critical period. filial imprinting the best - known form of imprinting is filial imprinting, in which a young animal narrows its social preferences to an object ( typically a parent ) as a result of exposure to that object. it is most obvious in nidifugous birds, which imprint on their parents and then follow them around. it was first reported in domestic chickens, by sir thomas more in 1516 as described in his treatise utopia, 350years earlier than by the 19th - century amateur biologist douglas spalding. it was rediscovered by the early ethologist oskar heinroth, and studied extensively and popularized by his disciple konrad lorenz working with greylag geese. lorenz demonstrated how incubator - hatched geese would imprint on the first suitable moving stimulus they saw within what he called a " critical period " between 13 and 16 hours shortly after hatching. for example, the goslings would imprint on lorenz himself ( to be more specific, on his wading boots ), and he is often depicted being followed by a gaggle of geese who had imprinted on him. lorenz also found that the geese could imprint on inanimate objects. in one notable experiment, they followed a box placed on a model train in circles around the track. filial imprinting is not restricted to non - human animals that are able to follow their parents, however. the filial imprinting of birds was a primary technique used to create the movie winged migration ( le peuple migrateur ), which contains a great deal of footage of migratory birds in flight. the birds imprinted on handlers, who wore yellow jackets and honked horns constantly. the birds were then trained to fly along with a variety of aircraft, primarily ultralights. the italian hang - glider pilot angelo d\'arrigo extended this technique. d\'arrigo noted that the flight of a non - motorised hang - glider is very similar to the flight patterns of migratory birds ; both use updra',

In [15]:
f0["control"]

['[CLS] what is a carbon footprint? what should be my carbon footprint? how to reduce my carbon footprint? let ’ s find out. carbon footprint simple definition by youmatter a carbon footprint corresponds to the whole amount of greenhouse gases ( ghg ) produced to, directly and indirectly, support a person ’ s lifestyle and activities. carbon footprints are usually measured in equivalent tons of co2, during the period of a year, and they can be associated with an individual, an organization, a product or an event, among others. the ghgs whose sum results in a carbon footprint can come from the production and consumption of fossil fuels, food, manufactured goods, materials, roads or transportation. and despite its importance, carbon footprints are difficult to calculate exactly due to poor knowledge and short data regarding the complex interactions between contributing processes – including the influence of natural processes that store or release carbon dioxide. carbon footprint official definition by the world health organization according to who, a carbon footprint is a measure of the impact your activities have on the amount of carbon dioxide ( co2 ) produced through the burning of fossil fuels and is expressed as a weight of co2 emissions produced in tonnes. “ how to measure my personal carbon footprint? ” the carbon footprint is a very important means to understand the impact of a person ’ s behavior on global warming. this is why someone who effectively wants to contribute to stopping global warming, at least on an individual scale, needs to measure and keep track of their personal carbon footprint. and here is where online calculators come in. for instance, by using the carbon footprint calculators from wwf, terrapass ( includes calculator for companies and events ) or the un you ’ ll be asked to provide pieces of information such as : how you commute to work, what your usual diet is, how much you drive or fly, the size of your household, or what type of electricity the grid provides you. the result you ’ ll get won ’ t be perfect or very much accurate – and there are several reasons why. first, because carbon footprint calculators use standard values that aren ’ t always right for a multiple of possible situations. for instance, when you type how many miles you drive on average, a certain reference value for the co2 / emissions / mile will be multiplied by your miles and then by 12 months. however, both numbers are estimations : sometimes you drive more than you actually told the calculator, and perhaps you drive a',
 '( the marks are on the top edges ), table legs ( the marks are on the top of the legs ), panel glue - ups ( the mark is a big triangle across the top face that spans all the pieces ), and more. and i always leave the marks in place until after glue - up, unless it truly isn ’ t possible, in which case i replicate them on blue tape and stick ’ em in place. and because i studied shakespeare in my non - woodworking life, i couldn ’ t help but turn to his sonnet 116 ( “ let me not to the marriage of true minds admit impediments … ” ) as inspiration for a woodworking poem : let me not to the marriage of two boards admit impediments. marks are not marks which alter when the marker ignores or tries with the eraser to remove. o no! they are ever - fixed marks that look on singular systems and scoff ; they are the guide to all board arrangement, to all dovetail transfer and assembly. marriage marks are not time ’ s fool, though new ideas within the mind of makers may come ; marks alter not in any woodworking project, but save the maker from assemblies of doom. if this be error upon me prov ’ d i never mark ’ d, nor no wood ever glu ’ d. what can i say … we have to keep ourselves amused right now, eh? [SEP]',
 '[CLS] water footprint refers to the amount of freshwater that is used in the production of goods and services. it includes not only the water used directly in the production process, but also the water used to grow or produce the materials used in the process. the water footprint of an individual or organization can be measured and managed to reduce water usage and promote sustainability. understanding water footprint water footprint refers to the volume of water needed to produce a particular product, including agricultural commodities, industrial goods, and services. it is a comprehensive indicator that measures the impact of human activities on water resources, including both the direct and indirect use of water. the concept of water footprint was first introduced in 2002 by arjen hoekstra, a professor of water management at the university of twente in the netherlands. the three components of water footprint water footprint is made up of three components, including : - blue water footprint : this refers to the volume of surface and groundwater used to produce a product or service. - green water footprint : this is the volume of rainwater used to produce a product or service. - grey water footprint : this is the volume of water required to dilute pollutants to an acceptable level. the importance of water footprint water is a precious resource that is essential for human survival, and its scarcity is becoming an increasingly significant global issue. water footprint is an essential tool for assessing the impact of human activities on water resources, and it helps to identify areas where water conservation efforts can be improved. by understanding the water footprint of a particular product or service, individuals and organizations can take steps to reduce their water usage and minimize their environmental impact. the impact of water footprint on society water footprint has significant implications for society, including environmental, social, and economic impacts. water footprint has a significant impact on the environment, including the depletion of water resources, the degradation of water quality, and the loss of biodiversity. the overuse of water resources can lead to the depletion of aquifers, rivers, and lakes, which can have devastating consequences for the ecosystem, including the loss of habitat for aquatic plants and animals. additionally, the discharge of pollutants into water bodies can lead to the degradation of water quality, which can have severe impacts on human health and the environment. water footprint has a significant social impact, particularly in regions where water scarcity is an issue. in such areas, water is a precious resource that is often the subject of conflict, with different stakeholders competing for',
 'there are human footprints found in numerous places in the world ( see the article : human fossil footprints found below ice age deposits ) and my book, “ evolution & human fossil footprints ”. other sources have written about preserved footprints many times and discussed how they challenge the accepted evolutionary geology. the preservation of footprints, just like all other fossils is a very rare event and does require a fortuitous set of circumstances to occur. a recent discovery shows just how such a fortuitous circumstance has occurred. near tucson arizona construction of a new road revealed an archaeological discovery. dozens of human footprints were found preserved in what was a field more than 2500 years ago ( local story link ). the footprints reveal that several adults and a young infant were working a small field. a dog was also accompanying them. they left their footprints in the thick mud of the field. it appears that soon after leaving the field, it was flooded by a nearby creek which brought in a layer of sediment with a different composition of material. at that point the field may have been abandoned and more layers of sediments deposited over the years. while the sediments have not been fully converted rock, the process of cementation has already begun producing layers that resists erosion and separate from other layers with different compositions. thus they were able to remove the layer above the footprints revealing the field as it was before they were preserved. this is not unlike what we see in thousands of other locations that footprints are found and this is exactly what we see with the glen rose fossil footprints. “ facts are stubborn things ; and whatever may be our wishes, our inclinations, or the dictates of our passion, they cannot alter the state of facts and evidence. ” – john adams [SEP]',
 '[CLS] freshwater resources – the increasing demand for, and increasing uncertainty of availability, have given rise to strong questions around water risks across agricultural value chains. the concept of water footprinting provides an effective platform from which to address and discuss these questions. but what does a water footprint actually entail? water footprinting is a relatively new concept, initially coined by arjen hoekstra in 2002. while it has parallels with carbon footprinting, because of the localised context of water resources, there is more complexity embodied in its calculation. since the concept was initially established, two chief guidance standards have been developed in recent years : ( 1 ) the water footprint assessment manual, developed by hoekstra et al. ( 2011 ) ; and ( 2 ) iso 14046, developed by the international organisation for standardisation ( iso ). the water footprint assessment manual entails the calculation of a total water footprint according to the sum of three component footprints : green ; blue ; and grey water footprints : - the green water footprint refers to the ‘ consumptive ’ use of precipitation ( before it becomes surface water ). this water use is predominantly taken up by crop production, and its calculation is based on plant and soil evapotranspiration rates and historical precipitation across a plant ’ s growth cycle. - the blue water footprint refers to the consumptive use of surface water – water existing in rivers ; dams ; reservoirs ; or groundwater bodies. at the farm level, the calculation of a blue water footprint is also based on plant and soil evapotranspiration rates. for processes different from that of agricultural production, the blue water footprint is a far simpler calculation. - the grey water footprint is calculated according to the volume of clean freshwater that would be required to dilute waste water ( based on the volume, concentration and characteristics of the chief contaminant ) to acceptable ambient levels ( i. e. the assimilative capacity of local water bodies ). more recently, a water footprinting guidance standard has also been developed by the international organization for standardization – iso 14046 : water footprint – principles, requirements and guidelines. although both guidance standards follow similar steps of assessment ( defining the goal and scope of the study ; building an inventory of water inputs and outputs ; and assessing the impact of this water use on water resources ), their methodologies differ considerably ( iso 2014 ). firstly, and most importantly, the iso 14046 guidance standard is based on a water scarcity - weighted',
 'What can be trademarked?\nWhat is a Trademark?\nA trademark is a word, phrase or design that identifies and distinguishes a product from goods or services developed by other companies. A product need not even exist to have a trademark. Trademarks may be filed before a product is introduced.\nRequirements for a Trademark\nA. It must be distinctive\nThe more distinctive a trademark, the stronger its legal protection will usually be. Trademark distinctiveness is described in four categories:\n1. Arbitrary or Fanciful\n- Arbitrary of Fanciful means that it has no relationship to the underlying product. For example, the words "Lexus," "Kodak," and "Apple" have no direct relationship to their underlying products (respectively, automobiles, cameras, or computers).\n- Suggestive Trademarks indirectly describe a characteristic of the underlying product/service. For example, the word "Coppertone" is suggestive of suntan lotion, but this does not directly describe the product. Like arbitrary or fanciful marks, suggestive marks are distinctive and will be given a high degree of protection.\n- Descriptive Trademarks directly describe a characteristic or quality of the underlying product. For example, "Holiday Inn" is the trademark of a hotel company catering to vacationers. "Holiday Inn," in itself, could not be a trademark. However, since "Holiday Inn" is recognizable from years of advertisement and use, it is now a legally strong trademark.\n- Generic Trademarks are the weakest trademarks and will often fail to be approved. You cannot trademark "Bicycle, Inc." as the name for a bicycle manufacturer. To get your trademark approved, you should aim for a more distinctive name.\nB. No Infringement with Existing Marks\nYour trademark should not infringe on any existing trademarks. Courts use two theories to determine infringement:\nSend your potential trademark name through our Trademark Services Form for a search and application.\n- Confusion means that your trademark name will create consumer confusion relating to your product and an existing product. A major factor in confusion is how similar the industries are. "Apple Tech" would not be an acceptable name for a computer manufacturer, but would be acceptable for an unrelated industry, such as automobiles.\n- Dilution is diminishing or damaging the value of a famous trademark. For example, using "Macy\'s" as the name of a flea market company could potentially be rejected as a legal trademark since it devalues an existing company\'s brand.',
 'animal bones tell us that the footprints were created between 5100 and 3400 years ago, from the late neolithic to the middle bronze age, in intertidal muds the footprints at formby are very very special and we have employed a huge range of archaeological expertise and techniques to bring the story they tell alive. the people who made the footprints were doing everyday tasks and cannot have known the importance of the tracks they left behind in the mud. who knows what people in 4, 000 years from now will make of the products we will leave behind us? [SEP]',
 '[CLS] this page uses content from wikipedia and is licensed under cc by - sa. in computer science, a fingerprinting algorithm is a procedure that maps an arbitrarily large data item ( such as a computer file ) to a much shorter bit string, its fingerprint, that uniquely identifies the original data for all practical purposes just as human fingerprints uniquely identify people for practical purposes. this fingerprint may be used for data deduplication purposes. this is also referred to as file fingerprinting, data fingerprinting, or structured data fingerprinting. fingerprints are typically used to avoid the comparison and transmission of bulky data. for instance, a web browser or proxy server can efficiently check whether a remote file has been modified, by fetching only its fingerprint and comparing it with that of the previously fetched copy. fingerprint functions may be seen as high - performance hash functions used to uniquely identify substantial blocks of data where cryptographic hash functions may be unnecessary. audio fingerprint algorithms should not be confused with this type of fingerprint function. to serve its intended purposes, a fingerprinting algorithm must be able to capture the identity of a file with virtual certainty. in other words, the probability of a collision — two files yielding the same fingerprint — must be negligible, compared to the probability of other unavoidable causes of fatal errors ( such as the system being destroyed by war or by a meteorite ) : say, 10−20 or less. this requirement is somewhat similar to that of a checksum function, but is much more stringent. to detect accidental data corruption or transmission errors, it is sufficient that the checksums of the original file and any corrupted version will differ with near certainty, given some statistical model for the errors. in typical situations, this goal is easily achieved with 16 - or 32 - bit checksums. in contrast, file fingerprints need to be at least 64 - bit long to guarantee virtual uniqueness in large file systems ( see birthday attack ). when proving the above requirement, one must take into account that files are generated by highly non - random processes that create complicated dependencies among files. for instance, in a typical business network, one usually finds many pairs or clusters of documents that differ only by minor edits or other slight modifications. a good fingerprinting algorithm must ensure that such " natural " processes generate distinct fingerprints, with the desired level of certainty. computer files are often combined in various ways, such as con',
 "An image of a fngerprint.\nThe definition of a fingerprint is the mark made on the surface of something by the curves and indentations of the finger tips.\nTypes of Fingerprints\n- Latent - When a person touches some sort of object, some of the moisture from their hand is deposited onto that object.\n- Plastic - If an individual touches materials such as clay, tar, or paint, their fingerprints will be retained in these substances.\n- Patent - The person gets oil, blood, paint, and so forth on his or her hands. Once the hands touch some other sort of material, the fingerprint is translated onto that material.\nAn example of a fingerprint is the mark left on a glass used by someone after they have eaten greasy french fries.\n- Fingerprint is defined as to capture an impression of the marks left by the raised curves of a person's finger tips.\nAn example of fingerprint is someone being arrested and having ink put on their finger tips and then pressed onto paper.\n- an impression of the lines and whorls on the inner surface of the end joint of the finger, used as by the police in the identification of a person\n- any characteristic or set of characteristics that distinguishes or unambiguously identifies a person or thing; signature\n- a. A mark left on a surface by a person's fingertip.b. An inked impression made of a person's fingertip and used for identification.\n- A distinctive or identifying mark or characteristic: “We can, from his retelling [of the incident], with its particular fingerprint of stresses and omissions, learn a great deal about him” (Mark Slouka).\n- a. A DNA fingerprint.b. A chemical fingerprint.\ntransitive verbfin·ger·print·ed, fin·ger·print·ing, fin·ger·prints\n(third-person singular simple present fingerprints, present participle fingerprinting, simple past and past participle fingerprinted)\n- To take somebody's fingerprints.\n- The jail staff fingerprints its 'guests' routinely",

In [16]:
w0["control"]

['trademark owners are not responsible for producing the products, but instead ( and this may be equally important ) for selecting those that meet their quality standards and requirements. even where trademark owners are the manufacturers of a particular product, they may use parts they have selected but not produced. promote the marketing and sale of products, and the marketing and provision of services. trademarks are not only used to distinguish or refer to a particular company or quality, but also to stimulate sales. a trademark used in this way must be carefully selected. it must appeal to the consumer, create interest and inspire a feeling of confidence. this is sometimes called the communication function. the owner of a registered trademark has an exclusive right in respect of the mark : the right to use the mark and to prevent unauthorized third parties from using it, or a confusingly similar mark, so as to prevent consumers and the public in general from being misled. the period of protection varies, but a trademark can be renewed indefinitely on payment of the necessary fees and on condition that the mark is used. trademark protection is enforced by the courts which, in most systems, have the authority to block trademark infringement. trade names another category of industrial property covers commercial names and designations. a commercial or trade name is the name or designation that identifies a company. in most countries, trade names may be registered with a government authority. however, under article 8 of the paris convention, a trade name must be protected without the obligation of filing or registration, whether or not it forms part of a trademark. protection generally means that the trade name of one company may not be used by another company, either as a trade name or a trade or service mark – and that a name or designation similar to the trade name may not be used by another company if it is likely to mislead the public. geographical indications a geographical indication is a sign used on goods that have a specific geographical origin and possess qualities or a reputation due to that place of origin. agricultural products typically have qualities deriving from their place of production and that are influenced by specific local factors, such as climate and soil. whether a sign functions as an indication is a matter of national law and consumer perception. geographical indications may be used for a wide variety of agricultural products, such as “ tuscany ” for olive oil produced in a specific area of italy, or “ roquefort ” for cheese produced in a certain region of france. the use of geographical indications is not limited to agricultural products. they may also',
 'trademark owner to demonstrate its trademark rights and to enforce these rights through an infringement action. unauthorized use of a registered trademark need not be intentional for infringement to occur, although damages in an infringement lawsuit will generally be greater if there was an intention to deceive. for trademarks that are considered to be well known, infringing use may occur where the use occurs about products or services which are not the same as or similar to the products or services about which the owner\'s mark is registered. a growing area of law relating to the enforcement of trademark rights is secondary liability, which allows for the imputation of liability to one who has not acted directly to infringe a trademark but whose legal responsibility may arise under the doctrines of either contributory or vicarious liability. limits and defenses to claims of infringement trademark is subject to various defenses, such as abandonment, limitations on geographic scope, and fair use. in the united states, the fair use defense protects many of the interests in free expression related to those protected by the first amendment. fair use may be asserted on two grounds, either that the alleged infringer is using the mark to describe accurately an aspect of its products, or that the alleged infringer is using the mark to identify the mark owner. one of the most visible proofs that trademarks provide a limited right in the u. s. comes from the comparative advertising that is seen throughout u. s. media. an example of the first type is that although maytag owns the trademark " whisper quiet " for its dishwashers, makers of other products may describe their goods as being " whisper quiet " so long as these products do not fall under the same category of goods the trademark is protected under. an example of the second type is that audi can run advertisements saying that a trade publication has rated an audi model higher than a bmw model since they are only using " bmw " to identify the competitor. in a related sense, an auto mechanic can truthfully advertise that he services volkswagens, and a former playboy playmate of the year can identify herself as such on her website. wrongful or groundless threats of infringement various jurisdictions have laws that are designed to prevent trademark owners from making wrongful threats of a trademark infringement action against other parties. these laws are intended to prevent large or powerful companies from intimidating or harassing smaller companies. where one party makes a threat to sue another for trademark infringement, but does not have a genuine basis or intention to carry',
 'footprints were reported in late jurassic rocks at cabo mondego, portugal. these may have been the first european late jurassic dinosaur footprints to be documented in the scientific literature. ~ 152 ~ w. p. blake reported the fossil footprints discovered at the prison in carson city, nevada to the scientific literature. mark twain wrote the satirical " the carson fossil footprints " attributing the purported giant tracks discovered there to primitive members of the territorial legislature. 1886 a mr. c. pooley discovered a small five toed fossil footprint in oxfordshire, england, which preserved in a middle jurassic stratigraphic unit called the stonesfield slate. john eyerman discovered two slabs of rock preserving fossil dinosaur footprints near milford, new jersey. the trackmaker was probably a small, quadrupedal ornithischian dinosaur. 1889 addison coffin drew up a map of a large portion of the pleistocene carson city tracks. dinosaur footprints were discovered near goldsboro, pennsylvania. these tracks are now classified in the ichnogenus atreipus. 1890s 1890s middle jurassic dinosaur tracks were discovered on the yorkshire coast of england. 1894 othniel charles marsh described the new ichnogenus limnopus for carboniferous tracks from the coal beds of kansas. 1895 a geology professor named james a. mitchell discovered some small grallator tracks in the late triassic gettysburg formation of maryland. these are the first and only known dinosaur tracks in the state. see also history of paleontology timeline of paleontology timeline of ichnology 20th century in ichnology footnotes references external links * 19th century in paleontology ichnology ichnology [SEP]',
 'A trademark is a word, phrase, symbol, design or combination thereof that uniquely identifies a product or service.\n\nTrademark may also refer to:\n Trademark symbol, the typographical ™ symbol which is used to identify a trademark.\n\nSenses of "trademark symbol" \n Brand, sometimes used interchangeably with "trademark"\n Collective trade mark\n Colour trademark \n Community Trade Mark\n Genericized trademark \n Hologram trademark \n International Trademark Association \n Logo, sometimes used interchangeably with "trademark"\n Patent and Trademark Office (disambiguation) \n Registered trademark symbol\n Trademark attorney \n Trade-Mark Cases \n Trademark classification \n Trademark dilution \n Trademark distinctiveness \n Trademark examiner \n Trademark infringement \n Trademark of Quality \n Trademark Official Gazette \n Trademark Trial and Appeal Board \n Trademark troll \n Unregistered trademark\n\nOther senses of "trademark" \n Trademark look\n Trademark argument \n Trademark (computer security)\n TradeMark, a skyscraper\n Trademark (band), an electropop band\n Trademark (group), German male vocal trio\n "Trademark", later "My Trade Mark", a song by Cardiacs from Toy World\n "Trademark", a song by Relient K from Two Lefts Don\'t Make a Right...but Three Do\n "My Trademark", a song by Bug Prentice from Leader of the Starry Skies – A Loyal Companion\n\nSee also\n\n \n \n \n \n Copyright symbol\n Service mark symbol\n Service mark\n Copyright\n Patent',
 '[CLS] a fingerprint is a mark made by the pattern of ridges on the pad of a human finger. fingerprint may also refer to : science and technology genetic fingerprint, distinguishing two individuals of the same species using only samples of their dna peptide mass fingerprinting, in biochemistry, identification of proteins fingerprint ( computing ), uniquely identifying data by extracting from it a small key known as a fingerprint public key fingerprint, a string of bytes identifying a cryptographic public key acoustic fingerprint, in audio technology, unique code generated from audio samples, allowing computer identification of music digital video fingerprinting, generates unique codes from digital video samples, and is used for automated copyright enforcement tcp / ip stack fingerprinting, identifying computer operating systems from network packets device fingerprint, harvesting of software and hardware settings from a remote computing device canvas fingerprinting, a browser fingerprinting technique for tracking users rabin fingerprint ballistic fingerprinting, a set of forensic techniques that to match a bullet to the gun it was fired with radio fingerprinting, characteristic signature from minute variations of frequencies emitted by a radio frequency device isotopic fingerprint, characteristic ratios of isotopes in material fingerprint, in the forensic identification of a typewriter fingerprint, in the forensic identification of a paper shredder arts fingerprints ( comics ), the southland tales graphic novel finger prints ( book ), a book published by francis galton in 1892 finger prints ( film ), a lost 1927 silent film directed by lloyd bacon finger prints ( serial ), a lost 1931 universal serial directed by ray taylor fingerprints ( film ), 2006 fingerprint ( album ), by mark heard fingerprints ( peter frampton album ), 2006 fingerprints ( amelia lily album ) fingerprints ( eli young band album ), 2017 " fingerprint ", a song by leona lewis from her 2012 album glassheart " fingerprints ", a song by the black heart procession from their 2002 album amore del tropico " fingerprints ", a series of songs by they might be giants from their 1992 album apollo 18 " fingerprints ", a song by katy perry from her 2008 album one of the boys " fingerprints ", a song by chick corea from his 2013 album trilogy " fingerprints ", a song by minipop from their 2007 album a new hope see also glove prints, a mark made by the pattern of a glove that is worn over the human hand dermatoglyphics, the scientific study of fingerprints multiple intelligences the',
 'Digital fingerprint may refer to:\n\n Message digest, the output of a one-way function when applied to a stream of data\n Public key fingerprint, short sequence of bytes used to identify a longer public key\n Fingerprint (computing)\n Acoustic fingerprint, a condensed digital summary generated from an audio signal\n Device fingerprint, a compact summary of software and hardware settings collected from a remote device, for example a computer or a web browser\n Digital video fingerprinting, a technique to summarize characteristic components of a video recording\n TCP/IP stack fingerprinting, the remote detection of the characteristics of a TCP/IP stack\n Content ID (algorithm), a Google technology used on YouTube to identify content protected by copyright',
 'Black mark or blackmark may refer to:\n\n Blackmark, 1971 Gil Kane graphic novel\n Black Mark Production, Swedish record production company\n Under the Sign of the Black Mark, a 1987 album by Bathory, a seminal release on the label\n\nSee also \n \n \n \n Black Spot (disambiguation)\n Black Market (disambiguation)',
 'Walter Marks may refer to:\n\n Wally Marks (1905–1992), American football, basketball, and baseball player, coach and college athletics administrator\n Walter Marks (composer) (born 1934), American songwriter, playwright, screenwriter, and novelist\n Walter Marks (politician) (1875–1951), Australian lawyer, yachtsman, and politician',
 'Jack Marks may refer to:\nJack Marks (performer) (1895–1987), English performer and screenwriter\nJack Marks (ice hockey) (1882–1945), Canadian ice hockey player\nJack Marks (police officer) (1927–2007), Canadian police officer\nJack Marks (politician) (1924–1998), Australian politician and trade union official\n\nSee also\nJohn Marks (disambiguation)',
 '[CLS] footprints are the impressions or images left behind by a person walking or running. hoofprints and pawprints are those left by animals with hooves or paws rather than feet, while " shoeprints " is the specific term for prints made by shoes. they may either be indentations in the ground or something placed onto the surface that was stuck to the bottom of the foot. a " trackway " is a set of footprints in soft earth left by a life - form ; animal tracks are the footprints, hoofprints, or pawprints of an animal. footprints can be followed when tracking during a hunt or can provide evidence of activities. some footprints remain unexplained, with several famous stories from mythology and legend. others have provided evidence of prehistoric life and behaviours. footprints in detective work the print left behind at a crime scene can give vital evidence to the perpetrator of the crime. shoes have many different prints based on the sole design and the wear that it has received – this can help to identify suspects. photographs or castings of footprints can be taken to preserve the finding. analysis of footprints and shoeprints is a specialist part of forensic science. some detective work is relatively immediate, with criminals being tracked by the footprints they left in the snow leading from the crime scene to their home or hiding place. this is usually reported as a humorous story in news publications. footprints can also allow the detective to find the approximate height from, footprint and shoeprint. the foot tends to be approximately 15 % of the person\'s average height. individualistic characteristics of the footprints like numerous creases, flatfoot character, horizontal and vertical ridges, corns, deformities etc. can help the forensic scientist in cases pertaining to criminal identification. in some forensic cases, the need may also arise to estimate body weight from the size of the footprints. footprints have been shown to have determine the height and the sex of the individual. ridge patterns friction ridge skin present on the soles of the feet and toes ( plantar surfaces ) is as unique in its ridge detail as are the fingers and palms ( palmar surfaces ). when recovered at crime scenes or on items of evidence, sole and toe impressions can be used in the same manner as finger and palm prints to effect identifications. footprint ( toe and sole friction ridge skin ) evidence has been admitted in courts in the united states since 1934. the footprints of infants, along with the thumb']

In [17]:
f0["similar_features"]

[1202, 24308, 482, 6869, 20316]

In [348]:
# let's embed the text of the sample and get the activations for each token for a given feature
import torch
import transformers
from transformers import AutoTokenizer, AutoModel
emb_model_name = "nomic-ai/nomic-embed-text-v1.5"
emb_model = AutoModel.from_pretrained(emb_model_name, trust_remote_code=True)
# emb_tokenizer = AutoTokenizer.from_pretrained(emb_model_name)
def mean_pooling(token_embeddings, attention_mask):
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

!!!!!!!!!!!!megablocks not available, using torch.matmul instead
<All keys matched successfully>

In [349]:

def calc_embedding(query: str):
    text = [query]

    # emb_model = AutoModel.from_pretrained(emb_model_name, trust_remote_code=True)
    emb_tokenizer = AutoTokenizer.from_pretrained(emb_model_name)
    

    # Tokenize the text and move to GPU if available
    inputs = emb_tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)
    tokens = emb_tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    # Get token spans to preserve boundaries
    encoding = emb_tokenizer(text, return_offsets_mapping=True)
    token_spans = encoding.offset_mapping

    # print("tokens", tokens)
    # print("token_spans", token_spans)
    # print("tokens", tokens)
    # print("DECODED",emb_tokenizer.decode(inputs["input_ids"][0]))
    inputs = {k: v for k, v in inputs.items()}
    
    # Get hidden states
    with torch.no_grad():
        outputs = emb_model(**inputs)
        
    # Get the last hidden state
    embedding = mean_pooling(outputs[0], inputs["attention_mask"])
    normalized_embeddings = torch.nn.functional.normalize(embedding, p=2, dim=1)
    normalized_hidden_states = torch.nn.functional.normalize(outputs[0], p=2, dim=1)

    # encode with the SAE   
    hidden_states_features = model.encode(normalized_hidden_states)
    embedding_features = model.encode(normalized_embeddings)

    return { 
        "text": text,
        "token_ids": inputs["input_ids"].cpu().numpy().tolist()[0],
        "tokens": tokens,
        "token_spans": token_spans,
        "hidden_states": normalized_hidden_states.cpu().numpy().tolist(), 
        "hidden_states_features": {
            "top_acts": hidden_states_features.top_acts.tolist(),
            "top_indices": hidden_states_features.top_indices.tolist(),
        },
        "embedding_features": {
            "top_acts": embedding_features.top_acts.tolist(),
            "top_indices": embedding_features.top_indices.tolist(),
        },
        # "hidden_states": outputs[0].cpu().numpy().tolist(),
        "attention_mask": inputs["attention_mask"].cpu().numpy().tolist()[0],
        "embedding": normalized_embeddings.cpu().numpy().tolist()[0],  # we only embed one query at a time
        "embedding_raw": embedding.cpu().numpy().tolist()[0]
    }

In [350]:
emb = calc_embedding(w0["top"][0])

In [351]:
len(emb["hidden_states_features"]["top_indices"][0])

381

In [251]:
import numpy as np
import nltk
from nltk.corpus import stopwords
import string

# Download the stopwords from nltk
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)
special = set(["[SEP]", "[CLS]", "[PAD]", "[MASK]"])


def calculate_zscore_and_filter(feature_index, emb, threshold):
    all_top_indices = emb["hidden_states_features"]["top_indices"][0]
    all_top_acts = emb["hidden_states_features"]["top_acts"][0]
    
    all_activations = []
    for top_indices, top_acts in zip(all_top_indices, all_top_acts):
        if feature_index in top_indices:
            index = top_indices.index(feature_index)
            all_activations.append(top_acts[index])
        else:
            all_activations.append(0)

    # Step 2: Calculate mean and standard deviation
    mean_activation = np.mean(all_activations)
    std_activation = np.std(all_activations)

    # Step 3: Calculate z-scores and accumulate tokens
    token_scores = []
    for token, activation in zip(emb["tokens"], all_activations):
        if std_activation == 0:
            z_score = 0
        else:
            z_score = (activation - mean_activation) / std_activation
        if z_score > threshold:
            token_scores.append((token, z_score))

    # Step 4: Sort tokens by z-score in descending order
    token_scores.sort(key=lambda x: x[1], reverse=True)

    # Step 5: Remove duplicates and keep the highest scoring instance
    seen_tokens = set()
    sorted_unique_tokens = []
    for token, score in token_scores:
        if token not in stop_words and token not in punctuation and token not in special and token not in seen_tokens:
            sorted_unique_tokens.append(token)
            seen_tokens.add(token)

    # Step 6: Return the sorted and unique tokens
    return sorted_unique_tokens

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/enjalot/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [255]:
import re # Import re for word boundary finding

def find_word_boundaries(text, start, end):
    # Expand start backwards to the nearest whitespace or beginning of string
    while start > 0 and not text[start - 1].isspace():
        start -= 1
    # Expand end forwards to the nearest whitespace or end of string
    while end < len(text) and not text[end].isspace():
        end += 1
    return start, end

def calculate_word_zscore_and_filter(feature_index, emb, threshold):
    text = emb["text"][0] # Assuming batch size of 1 for emb
    tokens = emb["tokens"]
    token_spans = emb["token_spans"][0] # offset_mapping adds batch dimension

    all_top_indices = emb["hidden_states_features"]["top_indices"][0]
    all_top_acts = emb["hidden_states_features"]["top_acts"][0]

    # Step 1: Calculate activations per token
    all_activations = []
    for idx, (top_indices, top_acts) in enumerate(zip(all_top_indices, all_top_acts)):
        # Skip special tokens like [CLS], [SEP] which have span (0, 0)
        if token_spans[idx] == (0, 0):
             all_activations.append(0)
             continue
        if feature_index in top_indices:
            try:
                index = top_indices.index(feature_index)
                all_activations.append(top_acts[index])
            except ValueError: # Should not happen if feature_index in top_indices, but good practice
                 all_activations.append(0)
        else:
            all_activations.append(0)

    # Step 2: Calculate mean and standard deviation of token activations
    mean_activation = np.mean(all_activations)
    std_activation = np.std(all_activations)

    # Step 3: Calculate z-scores per token and map to words
    word_scores = {}
    # Ensure tokens, all_activations, and token_spans align, skipping initial/final special tokens if necessary
    # The original code zipped emb["tokens"] and all_activations directly.
    # Let's assume they correspond index-wise.
    # Need to handle the case where len(tokens) might differ slightly from len(all_activations) if special tokens were handled differently in embedding calculation.
    # Let's assume len(tokens) == len(all_activations) == len(token_spans) for now.

    for i, token in enumerate(tokens):
        # Skip special tokens
        span = token_spans[i]
        if span == (0, 0):
            continue

        activation = all_activations[i]
        if std_activation == 0:
            z_score = 0
        else:
            z_score = (activation - mean_activation) / std_activation

        # Find word boundaries
        token_start, token_end = span
        word_start, word_end = find_word_boundaries(text, token_start, token_end)
        word = text[word_start:word_end]

        # Clean word: lowercase and remove leading/trailing punctuation
        cleaned_word = word.strip(string.punctuation).lower()

        if not cleaned_word: # Skip if word is only punctuation or empty
             continue

        # Keep the maximum z-score for the word
        if cleaned_word not in word_scores or z_score > word_scores[cleaned_word]:
            word_scores[cleaned_word] = z_score

    # Step 4: Filter words by z-score threshold
    filtered_word_scores = [(word, score) for word, score in word_scores.items() if score > threshold]

    # Step 5: Sort words by z-score in descending order
    filtered_word_scores.sort(key=lambda x: x[1], reverse=True)

    # Step 6: Remove duplicates (already handled by dict and sorting) and filter stop words/punctuation
    seen_words = set()
    sorted_unique_words = []
    for word, score in filtered_word_scores:
        # Basic check for stop words and punctuation (whole word)
        # The word is already lowercased and stripped.
        if word not in stop_words and word not in punctuation and word not in seen_words:
             # Check if the word consists only of punctuation after stripping (e.g. '--')
             # This check might be redundant due to cleaned_word check earlier
             is_only_punctuation = all(char in string.punctuation for char in word)
             if not is_only_punctuation:
                sorted_unique_words.append(word)
                seen_words.add(word)


    # Step 7: Return the sorted and unique words
    return sorted_unique_words

In [252]:
calculate_zscore_and_filter(0, emb, 1.5)

['imprint',
 '9',
 '1913',
 'metabolic',
 'molecular',
 'genetic',
 'improved',
 'mast',
 'london',
 '##ic']

In [256]:
calculate_word_zscore_and_filter(0, emb, 1.5)

['imprinting',
 'imprint',
 '9',
 '1913',
 'metabolic',
 'u.s',
 'molecular',
 'genetic',
 'improved',
 'masthead',
 'london',
 'limbic']

In [253]:
calculate_zscore_and_filter(0, calc_embedding(w0["top"][5]), 1.5)

['imprint', 'proper', '##ing', 'multiple', '##omic', '##ed', 'gen']

In [257]:
calculate_word_zscore_and_filter(0, calc_embedding(w0["top"][5]), 1.5)

['imprinted', 'imprinting', 'linked', 'proper', 'multiple', 'genomic']

In [260]:
# calculate zscore and top tokens for each of the samples["top"]
def get_top_tokens(samples, feature):
    top_tokens = []
    for i in range(len(samples)):
        emb = calc_embedding(samples[i])
        top_tokens.append(calculate_word_zscore_and_filter(feature, emb, 1.5))
    return top_tokens
get_top_tokens(f0["top"], 0)
get_top_tokens(w0["top"], 0)

[['imprinting',
  'imprint',
  '9',
  '1913',
  'metabolic',
  'u.s',
  'molecular',
  'genetic',
  'improved',
  'masthead',
  'london',
  'limbic'],
 ['imprint', 'disambiguation', 'dune', 'imprinter'],
 ['imprinted',
  'imprinting',
  'various',
  'hypothesis',
  'mammals',
  'genes',
  'occurs',
  'like'],
 ['imprinted',
  'imprinting',
  'molecularly',
  'molecular',
  'used',
  'recognized',
  '‘',
  'showed',
  'fit',
  'groups',
  'affinity',
  'cls'],
 ['imprinting',
  'imprint',
  'imprinter',
  'imprinted',
  'imprinters',
  'sisterhood',
  'mother',
  'later',
  'deepest',
  'duncan',
  'harkonnen'],
 ['imprinted', 'imprinting', 'linked', 'proper', 'multiple', 'genomic'],
 ['firm',
  'imprinting',
  'present',
  'organization',
  'northern',
  'imprint',
  'term',
  'reflect',
  'behavior',
  'imprints',
  'stinchcombe',
  'still',
  'environment',
  'focal',
  'black',
  'susceptibility'],
 ['imprint',
  '1912',
  '1913',
  'released',
  'delivered',
  'widely',
  'titles',
  'describes',
  'inspired',
  'precisians',
  'called',
  'history',
  'periodical',
  '—',
  'trade',
  "journal's",
  'magazine',
  'regularity',
  'cls'],
 ['imprinted',
  'imprinting',
  'imprint',
  'subject',
  'would',
  'filial',
  'could',
  '19th',
  'nidifugous',
  'birds',
  'ethology',
  'parents'],
 ['imprinted', 'imprinting', 'faulty', 'life', 'hormonal']]

In [262]:
fcat = get_samples(top10_df, 13557)
wcat = get_samples(wtop10_df, 13557)
print(fcat["top"][0])
get_top_tokens(fcat["top"], 13557)
get_top_tokens(wcat["top"], 13557)

Cats are very popular pets, adaptable to high survivability. Currently, the status of kittens is neglected, in part because of the loss of sterilization.
A lot of you want to adopt a kitten but don’t know how to take care of it, especially an abandoned cat.
If a kitten loses its mother, who takes care of the babies, there are many things you should know:
- Newborn cats are very soft, baby, wet hair sticking to the body.
- Cats born 2 to 3 days have not opened their eyes, droopy ears, big bellies, dry but soft fur, hugging the cat’s body.
- Between 5 and 10 days, kittens begin to open their eyes, ears are cropped, their bellies are big, the belly is little or no. The cat’s body was smaller than an adult’s hand, and started to crawl.
- After 13 days, the cat’s eyes were mostly open but cloudy, his ears began to prick. A young kitten can lift its body.
- At 3 weeks of age, kittens can stand up and play with people or other cats.
- After 4 weeks of age the cat runs and jumps.
- After 5 weeks of age, your cat will begin scratching your cat’s claws.
- Cats aged 6 weeks to 10 weeks have enough teeth, stand upright, run and jump well. Green or yellow eye color for green or yellow/orange eyes. Light blue for cats with blue eyes.
- Cats from 3 to 6 months of age, their eyes become clearer, no longer opaque, they will change their eye color at this stage again and then keep that eye color permanently. The fangs are small and clear.
- Cats over 6 months of age have very clear eyes, pupils and black color and clear iris, very white teeth, big fangs.
- Cats aged two and older are like a 6-month-old cat, but their paws begin to turn yellow, the older their teeth become. Some cats that have been given tarting will have less yellow teeth or remain white. Cats are now mature, very difficult to be friendly, it is best not to change owners after two years old.
These are the characteristics of cats for age beginners that the article just shared. Hopefully, the above information will be helpful to you!

[['cat',
  'cats',
  "cat's",
  'consume',
  'although',
  'density',
  'effects',
  'birth',
  'weight'],
 ['cats', 'cat', 'kitten', 'feline', 'necessary'],
 ['cats', 'cat', "cat's", 'kittens', 'kitten', 'bearing'],
 ['cat', 'cats', 'kitten', 'bond', 'week'],
 ['cats', 'cat', "cat's", 'feline', 'habits'],
 ['cat', 'cats', "cat's", 'relaxed', 'comfort', 'standing'],
 ['cat', 'cats', "cat's", 'allergens'],
 ['cats', 'cat', 'inc', 'therapy', 'technology', 'tribunal'],
 ['cat',
  'cats',
  'kittens',
  'affection',
  'kneading',
  'rest',
  'sleeping',
  'nursing',
  'adulthood'],
 ['cat',
  'cats',
  "cats'searches",
  'kittens',
  'kitten',
  'humans',
  'life',
  'roles']]

In [97]:
system_prompt = f"""You are a meticulous researcher conducting an important investigation into a certain
direction in the latent space of a language model. Your task is to figure out what sort of concept this direction represents and provide a short label for it.
Here's how you'll complete the task:

INPUT DESCRIPTION: You will be given two inputs: 1) Max Activating Examples and 2)
Zero Activating Examples.
1. You will be given several examples of text that activate the neuron, along with a list of tokens that activated strongly for that example. This means there is some feature, theme,
methodology, topic or concept in this text that coincides with this direction in the latent space.
2. You will also be given several examples of text that don't align with this direction at all. This
means the feature, topic or concept is not present in these texts. The Zero Activating examples are chosen
from text that does align with similar directions in the latent space, so discriminating between what makes a sample
Max Activating vs Zero Activating is important.

OUTPUT DESCRIPTION: Given the inputs provided, complete the following tasks.
1. Based on the MAX ACTIVATING EXAMPLES provided, write down potential topics,
concepts, themes, methodologies and features that they share in common. You may need to look at different
levels of granularity (i.e. subsets of a more general topic). List as many as you can
think of. Give higher weight to concepts more present/prominent in examples with
higher activations.
2. Based on the zero activating examples, rule out any of the topics/concepts/features
listed above that are in the zero-activating examples. Systematically go through your
list above.
3. Based on the above two steps, perform a thorough analysis of which feature, concept
or topic, at what level of granularity, is likely to align with this direction in the latent space. Use Occam's
razor, as long as it fits the provided evidence. Be highly rational and analytical here. If you lack confidence
in your answer be less specific and more general in your label.
4. Based on step 4, summarise this concept in 1-6 words, in the form FINAL:
<explanation>. Do NOT return anything after these 1-6 words.

You should choose a label that best summarizes the theme of the list so that someone browsing the labels will have a good idea of what is in the list. 
Do not use punctuation, Do not explain yourself, respond with only a few words that summarize the list."""

In [480]:
def get_sample_prompt(feature):
  fsamples = get_samples(top10_df, feature)
  wsamples = get_samples(wtop10_df, feature)
  samples = fsamples["top"] + wsamples["top"]
  # samples = wsamples["top"]
  # control = fsamples["control"] + wsamples["control"]
  control = fsamples["control"] + wsamples["control"]
  top_tokens = get_top_tokens(samples, feature)
  print("TOP TOKENS", top_tokens)

  toptext = "\n".join([f"<TopTokens>{tokens}</TopTokens><Text>{sample}</Text>" for sample,tokens in zip(samples, top_tokens)])
  # toptext = "\n".join([f"<TopTokens>{tokens}</TopTokens>" for sample,tokens in zip(samples, top_tokens)])
  controltext = "\n".join([f"<Text>{sample}</Text>" for sample in control])

  prompt = f"""Here is a list of maximum activating samples and the top tokens that align with the direciton. 
  Please pay extra attention to the top tokens:
  <Samples>
  {toptext}
  </Samples>
  Here is a list of zero activating samples:
  <ControlSamples>
  {controltext}
  </ControlSamples>
  Please summarise this concept with a label in 1-6 words by primarily considering the TopTokens. Use lower-case letters unless you are using proper nouns. Return the label in the form FINAL:
<explanation>. Do NOT return anything after these 1-6 words
  """
  return prompt

In [481]:
from openai import AsyncOpenAI
import os
import dotenv
dotenv.load_dotenv()

True

In [482]:
client = AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"])
async def chat(messages):
  response = await client.chat.completions.create(
    # model="gpt-4o-mini",
    model="gpt-4.1-nano",
    messages=messages
  )
  return response.choices[0].message.content

In [486]:
# feature = 0
# feature = 6864
# feature = 12119
# feature = 16145
# feature = 13557
# feature = 17469
# feature = 5676
# feature = 4567
feature = 13226
messages=[
    {"role":"system", "content": system_prompt}, 
    {"role":"user", "content": get_sample_prompt(feature)}
]

TOP TOKENS [['298', '67', '302'], ['11c11', '17728', 'h03k19', '17796', '17736', '177h3', '177d2'], ['7', 'b32b7', 'c09b67'], ['142606a1', '262t', '010256', 'classification'], ['classification', 'filed', 'number', '20050081080', '013', '15', '20060101', 'g06f', '20060129741'], ['b33', '44', '07', 'f02m25', '0406', 'f02b47'], ['classification', 'number', 'filed'], ['classification', 'number', '848', '892', 'filed'], ['60', 'r', '932', 'p', '0000'], ['898417'], ['9', 'part', 'iso', 'data'], ['source', 'results', 'kim', 'rosters', 'ji', 'qiu', 'jang', 'knut'], ['thebius', 'g', 'c'], ['5749', '1', 'idd4', '2', 'al663042', 'al596185', 'al596111'], ['otecnum', 'g', 'c', 'b', '2008', 'li', 'fasheng'], ['source', 'schedule', 'results', 'uca'], ['–', 'lavl', 'lbkl', 'bezmer', 'cls', 'lbbr', 'lbls'], ['c', 'aenodes', 'g', 'conjugatus', 'connatus'], ['sheng', 'g', 'c', '2007', 'tenuispinum', 'yoshizawa'], ['source', 'schedule', 'results', 'references', 'uca']]

In [487]:
label = await chat(messages)

In [489]:
label

In [490]:
labels_df = pd.read_parquet(f"data/labels-4.1-{name}.parquet").reset_index(drop=True)

In [491]:
labels_df.loc[feature, "label"] = label

In [492]:
labels_df.shape

(24576, 2)

In [493]:
labels_df.iloc[feature]

feature                            13226
label      FINAL: numbers and repetition
Name: 13226, dtype: object

In [494]:
labels_df.to_parquet(f"data/labels-4.1-{name}.parquet")

In [434]:
features

range(0, 24576)

In [335]:
import asyncio
import time
from tqdm import tqdm
import nest_asyncio

In [356]:
label_file = f"data/labels-4.1-{name}.parquet"
if os.path.exists(label_file):
    labels_df = pd.read_parquet(label_file)
else:
    labels_df = pd.DataFrame(columns=['feature', 'label'])
features_to_label = [feature for feature in features if feature not in labels_df['feature'].values]

In [357]:
print("features to label", len(features_to_label), "done with", len(labels_df))
print(features_to_label)

features to label 1176 done with 23400
[23400, 23401, 23402, 23403, 23404, 23405, 23406, 23407, 23408, 23409, 23410, 23411, 23412, 23413, 23414, 23415, 23416, 23417, 23418, 23419, 23420, 23421, 23422, 23423, 23424, 23425, 23426, 23427, 23428, 23429, 23430, 23431, 23432, 23433, 23434, 23435, 23436, 23437, 23438, 23439, 23440, 23441, 23442, 23443, 23444, 23445, 23446, 23447, 23448, 23449, 23450, 23451, 23452, 23453, 23454, 23455, 23456, 23457, 23458, 23459, 23460, 23461, 23462, 23463, 23464, 23465, 23466, 23467, 23468, 23469, 23470, 23471, 23472, 23473, 23474, 23475, 23476, 23477, 23478, 23479, 23480, 23481, 23482, 23483, 23484, 23485, 23486, 23487, 23488, 23489, 23490, 23491, 23492, 23493, 23494, 23495, 23496, 23497, 23498, 23499, 23500, 23501, 23502, 23503, 23504, 23505, 23506, 23507, 23508, 23509, 23510, 23511, 23512, 23513, 23514, 23515, 23516, 23517, 23518, 23519, 23520, 23521, 23522, 23523, 23524, 23525, 23526, 23527, 23528, 23529, 23530, 23531, 23532, 23533, 23534, 23535, 23536, 23537, 23538, 23539, 23540, 23541, 23542, 23543, 23544, 23545, 23546, 23547, 23548, 23549, 23550, 23551, 23552, 23553, 23554, 23555, 23556, 23557, 23558, 23559, 23560, 23561, 23562, 23563, 23564, 23565, 23566, 23567, 23568, 23569, 23570, 23571, 23572, 23573, 23574, 23575, 23576, 23577, 23578, 23579, 23580, 23581, 23582, 23583, 23584, 23585, 23586, 23587, 23588, 23589, 23590, 23591, 23592, 23593, 23594, 23595, 23596, 23597, 23598, 23599, 23600, 23601, 23602, 23603, 23604, 23605, 23606, 23607, 23608, 23609, 23610, 23611, 23612, 23613, 23614, 23615, 23616, 23617, 23618, 23619, 23620, 23621, 23622, 23623, 23624, 23625, 23626, 23627, 23628, 23629, 23630, 23631, 23632, 23633, 23634, 23635, 23636, 23637, 23638, 23639, 23640, 23641, 23642, 23643, 23644, 23645, 23646, 23647, 23648, 23649, 23650, 23651, 23652, 23653, 23654, 23655, 23656, 23657, 23658, 23659, 23660, 23661, 23662, 23663, 23664, 23665, 23666, 23667, 23668, 23669, 23670, 23671, 23672, 23673, 23674, 23675, 23676, 23677, 23678, 23679, 23680, 23681, 23682, 23683, 23684, 23685, 23686, 23687, 23688, 23689, 23690, 23691, 23692, 23693, 23694, 23695, 23696, 23697, 23698, 23699, 23700, 23701, 23702, 23703, 23704, 23705, 23706, 23707, 23708, 23709, 23710, 23711, 23712, 23713, 23714, 23715, 23716, 23717, 23718, 23719, 23720, 23721, 23722, 23723, 23724, 23725, 23726, 23727, 23728, 23729, 23730, 23731, 23732, 23733, 23734, 23735, 23736, 23737, 23738, 23739, 23740, 23741, 23742, 23743, 23744, 23745, 23746, 23747, 23748, 23749, 23750, 23751, 23752, 23753, 23754, 23755, 23756, 23757, 23758, 23759, 23760, 23761, 23762, 23763, 23764, 23765, 23766, 23767, 23768, 23769, 23770, 23771, 23772, 23773, 23774, 23775, 23776, 23777, 23778, 23779, 23780, 23781, 23782, 23783, 23784, 23785, 23786, 23787, 23788, 23789, 23790, 23791, 23792, 23793, 23794, 23795, 23796, 23797, 23798, 23799, 23800, 23801, 23802, 23803, 23804, 23805, 23806, 23807, 23808, 23809, 23810, 23811, 23812, 23813, 23814, 23815, 23816, 23817, 23818, 23819, 23820, 23821, 23822, 23823, 23824, 23825, 23826, 23827, 23828, 23829, 23830, 23831, 23832, 23833, 23834, 23835, 23836, 23837, 23838, 23839, 23840, 23841, 23842, 23843, 23844, 23845, 23846, 23847, 23848, 23849, 23850, 23851, 23852, 23853, 23854, 23855, 23856, 23857, 23858, 23859, 23860, 23861, 23862, 23863, 23864, 23865, 23866, 23867, 23868, 23869, 23870, 23871, 23872, 23873, 23874, 23875, 23876, 23877, 23878, 23879, 23880, 23881, 23882, 23883, 23884, 23885, 23886, 23887, 23888, 23889, 23890, 23891, 23892, 23893, 23894, 23895, 23896, 23897, 23898, 23899, 23900, 23901, 23902, 23903, 23904, 23905, 23906, 23907, 23908, 23909, 23910, 23911, 23912, 23913, 23914, 23915, 23916, 23917, 23918, 23919, 23920, 23921, 23922, 23923, 23924, 23925, 23926, 23927, 23928, 23929, 23930, 23931, 23932, 23933, 23934, 23935, 23936, 23937, 23938, 23939, 23940, 23941, 23942, 23943, 23944, 23945, 23946, 23947, 23948, 23949, 23950, 23951, 23952, 23953, 23954, 23955, 23956, 23957, 23958, 23959, 23960, 23961, 23962, 23963, 23964, 23965, 23966, 23967, 23968, 23969, 23970, 23971, 23972, 23973, 23974, 23975, 23976, 23977, 23978, 23979, 23980, 23981, 23982, 23983, 23984, 23985, 23986, 23987, 23988, 23989, 23990, 23991, 23992, 23993, 23994, 23995, 23996, 23997, 23998, 23999, 24000, 24001, 24002, 24003, 24004, 24005, 24006, 24007, 24008, 24009, 24010, 24011, 24012, 24013, 24014, 24015, 24016, 24017, 24018, 24019, 24020, 24021, 24022, 24023, 24024, 24025, 24026, 24027, 24028, 24029, 24030, 24031, 24032, 24033, 24034, 24035, 24036, 24037, 24038, 24039, 24040, 24041, 24042, 24043, 24044, 24045, 24046, 24047, 24048, 24049, 24050, 24051, 24052, 24053, 24054, 24055, 24056, 24057, 24058, 24059, 24060, 24061, 24062, 24063, 24064, 24065, 24066, 24067, 24068, 24069, 24070, 24071, 24072, 24073, 24074, 24075, 24076, 24077, 24078, 24079, 24080, 24081, 24082, 24083, 24084, 24085, 24086, 24087, 24088, 24089, 24090, 24091, 24092, 24093, 24094, 24095, 24096, 24097, 24098, 24099, 24100, 24101, 24102, 24103, 24104, 24105, 24106, 24107, 24108, 24109, 24110, 24111, 24112, 24113, 24114, 24115, 24116, 24117, 24118, 24119, 24120, 24121, 24122, 24123, 24124, 24125, 24126, 24127, 24128, 24129, 24130, 24131, 24132, 24133, 24134, 24135, 24136, 24137, 24138, 24139, 24140, 24141, 24142, 24143, 24144, 24145, 24146, 24147, 24148, 24149, 24150, 24151, 24152, 24153, 24154, 24155, 24156, 24157, 24158, 24159, 24160, 24161, 24162, 24163, 24164, 24165, 24166, 24167, 24168, 24169, 24170, 24171, 24172, 24173, 24174, 24175, 24176, 24177, 24178, 24179, 24180, 24181, 24182, 24183, 24184, 24185, 24186, 24187, 24188, 24189, 24190, 24191, 24192, 24193, 24194, 24195, 24196, 24197, 24198, 24199, 24200, 24201, 24202, 24203, 24204, 24205, 24206, 24207, 24208, 24209, 24210, 24211, 24212, 24213, 24214, 24215, 24216, 24217, 24218, 24219, 24220, 24221, 24222, 24223, 24224, 24225, 24226, 24227, 24228, 24229, 24230, 24231, 24232, 24233, 24234, 24235, 24236, 24237, 24238, 24239, 24240, 24241, 24242, 24243, 24244, 24245, 24246, 24247, 24248, 24249, 24250, 24251, 24252, 24253, 24254, 24255, 24256, 24257, 24258, 24259, 24260, 24261, 24262, 24263, 24264, 24265, 24266, 24267, 24268, 24269, 24270, 24271, 24272, 24273, 24274, 24275, 24276, 24277, 24278, 24279, 24280, 24281, 24282, 24283, 24284, 24285, 24286, 24287, 24288, 24289, 24290, 24291, 24292, 24293, 24294, 24295, 24296, 24297, 24298, 24299, 24300, 24301, 24302, 24303, 24304, 24305, 24306, 24307, 24308, 24309, 24310, 24311, 24312, 24313, 24314, 24315, 24316, 24317, 24318, 24319, 24320, 24321, 24322, 24323, 24324, 24325, 24326, 24327, 24328, 24329, 24330, 24331, 24332, 24333, 24334, 24335, 24336, 24337, 24338, 24339, 24340, 24341, 24342, 24343, 24344, 24345, 24346, 24347, 24348, 24349, 24350, 24351, 24352, 24353, 24354, 24355, 24356, 24357, 24358, 24359, 24360, 24361, 24362, 24363, 24364, 24365, 24366, 24367, 24368, 24369, 24370, 24371, 24372, 24373, 24374, 24375, 24376, 24377, 24378, 24379, 24380, 24381, 24382, 24383, 24384, 24385, 24386, 24387, 24388, 24389, 24390, 24391, 24392, 24393, 24394, 24395, 24396, 24397, 24398, 24399, 24400, 24401, 24402, 24403, 24404, 24405, 24406, 24407, 24408, 24409, 24410, 24411, 24412, 24413, 24414, 24415, 24416, 24417, 24418, 24419, 24420, 24421, 24422, 24423, 24424, 24425, 24426, 24427, 24428, 24429, 24430, 24431, 24432, 24433, 24434, 24435, 24436, 24437, 24438, 24439, 24440, 24441, 24442, 24443, 24444, 24445, 24446, 24447, 24448, 24449, 24450, 24451, 24452, 24453, 24454, 24455, 24456, 24457, 24458, 24459, 24460, 24461, 24462, 24463, 24464, 24465, 24466, 24467, 24468, 24469, 24470, 24471, 24472, 24473, 24474, 24475, 24476, 24477, 24478, 24479, 24480, 24481, 24482, 24483, 24484, 24485, 24486, 24487, 24488, 24489, 24490, 24491, 24492, 24493, 24494, 24495, 24496, 24497, 24498, 24499, 24500, 24501, 24502, 24503, 24504, 24505, 24506, 24507, 24508, 24509, 24510, 24511, 24512, 24513, 24514, 24515, 24516, 24517, 24518, 24519, 24520, 24521, 24522, 24523, 24524, 24525, 24526, 24527, 24528, 24529, 24530, 24531, 24532, 24533, 24534, 24535, 24536, 24537, 24538, 24539, 24540, 24541, 24542, 24543, 24544, 24545, 24546, 24547, 24548, 24549, 24550, 24551, 24552, 24553, 24554, 24555, 24556, 24557, 24558, 24559, 24560, 24561, 24562, 24563, 24564, 24565, 24566, 24567, 24568, 24569, 24570, 24571, 24572, 24573, 24574, 24575]

In [354]:
os.cpu_count()

12

In [358]:
import nest_asyncio
import asyncio
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor

nest_asyncio.apply()
limit = 1000
batch_size = os.cpu_count()
# Create a thread pool for CPU-bound operations
thread_pool = ThreadPoolExecutor(max_workers=os.cpu_count())

def get_sample_prompt_threaded(feature):
    # This moves the CPU-intensive operation to a separate thread
    print("getting sample prompt for", feature)
    return get_sample_prompt(feature)

async def chat_with_feature(feature):
    # Run the CPU-intensive function in a thread pool
    prompt = await asyncio.get_event_loop().run_in_executor(
        thread_pool, get_sample_prompt_threaded, feature)
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]
    response = await chat(messages)
    return {"feature": feature, "label": response}

async def process_batch(features_batch):
    tasks = [chat_with_feature(feature) for feature in features_batch]
    return await asyncio.gather(*tasks)

async def main(features, labels_df):
    results = []
    for i in tqdm(range(0, len(features), batch_size), desc="Processing features", leave=True):
        batch = features[i:i + batch_size]
        batch_results = await process_batch(batch)
        results.extend(batch_results)
        
        # Save progress every 100 features
        if len(results) % 100 == 0:
            labels_df = pd.concat([labels_df, pd.DataFrame(results)])
            labels_df.to_parquet(label_file)
            results = []
        
        # Respect rate limit
        if len(results) % limit == 0:
            await asyncio.sleep(10)  # Wait to respect rate limit
    
    # Save any remaining results
    labels_df = pd.concat([labels_df, pd.DataFrame(results)])
    labels_df.to_parquet(label_file)

# Optional: You can control the maximum number of threads
# thread_pool = ThreadPoolExecutor(max_workers=os.cpu_count())

# Clean up the thread pool when finished
try:
    asyncio.run(main(features_to_label, labels_df))
finally:
    thread_pool.shutdown()

Processing features:   0%|          | 0/98 [00:00<?, ?it/s]

getting sample prompt for 23400
getting sample prompt for 23401
getting sample prompt for 23402
getting sample prompt for 23403
getting sample prompt for 23404
getting sample prompt for 23405
getting sample prompt for 23406
getting sample prompt for 23407
getting sample prompt for 23408
getting sample prompt for 23409
getting sample prompt for 23410
getting sample prompt for 23411
TOP TOKENS [['billionaires', 'millionaires', 'billionaire'], ['billionaire', 'billionaires', 'millionaire', "world's", 'become', 'richest'], ['billionaires', 'billionaire', "world's"], ['billionaire', 'billionaires', '’', 'becoming'], ['billionaire', 'billionaires', 'millionaire', 'lot'], ['billionaire', 'billionaires', 'millionaire', 'lot'], ['billionaires', 'billionaire'], ['billionaires'], ['billionaires'], ['billionaires', 'therefore'], ['billionaire', 'billionaire(s'], ['billionaires', 'billionaire'], ['billionaires', 'billionaire'], ['billionaires', 'millionaires', 'billionaire', 'ultra'], ['billionaires', 'billionaire', 'became'], ['billionaires', 'millionaires'], ['billionaires', 'billionaire', 'millionaires', 'millionaire'], ['billionaire', 'billionaires', "world's", 'magnate', 'richest', '826'], ['billionaires', "world's", 'people', 'wealth', 'whose', 'year', 'businessman'], ['billionaires', 'billionaire', "2017's", "world's", 'richest', '826']]
TOP TOKENS [['quit', 'verb'], ['quitting', 'quit', 'smoking', 'healthier', 'better', 'way'], ['quit', 'can’t', 'quits.”'], ['quit'], ['quit', 'quitting', 'situations', 'consider', 'case', 'benefits', 'must', 'using', 'individual'], ['quit', 'quitting', 'situations', 'consider', 'case', 'benefits', 'must', 'using', 'individual'], ['quit', 'quitting', 'using', 'successfully', 'quittxt', 'quitcoach', 'quitline', 'courses', 'quality'], ['quit', 'quitting', 'help', 'way', 'important', 'successfully', 'breath', 'good'], ['quitting', 'quit', 'benefits', 'successfully', 'day', 'researchers', 'actively'], ['quitting', 'quit', 'using', 'smoking'], ['quit', 'susumu', 'hirasawa', 'quitting', "one's"], ['quit'], ['http://acsh.org/news/2015/09/14/quit-lit-academics-discover-theres-real-science-outside-universities'], ['quitzdorf', 'germany'], ['quit'], ['quits'], ['quit', 'aalborg', 'university', 'teens', 'ts', 'early', 'rubio', 'explores'], ['quitting', 'quit', 'rate', 'entirely'], ['quittet', 'claude'], ['quitandinha']]
TOP TOKENS [['sol', 'sôl', 'sōl', 'sols', 'solmization'], ["sol's", 'sol', 'virginiasol.com'], ['sol', 'sols', 'soli', 'solmization', 'sola', 'word'], ['sol', 'sols', 'soli', 'solmization', 'sola', 'word'], ['sol', 'sōl', 'sol(ve', 'solfrench', 'solmiddle', 'solclassical', 'solspanish', 'solfrom', 'sol(ution', 'solutiopharmacy', 'solsp', 'solum', 'unverified', 'sun'], ['sol', 'sols', 'sol2.3'], ['sol', 'sòl', 'sól', 'sole', 'soll', 'soli'], ['sols', 'sol', 'sol–gel', 'message'], ['sol'], ['sol', '7', 'cls', 'game', 'however', '43', 'systemedit', 'spice', 'humanity', 'core'], ['sol', 'badguy'], ['sól', 'sol', 'disambiguation'], ['sol', 'translator', 'lawyer', 'american'], ['sol', 'solana', 'sols', 'solano'], ['sol', 'soľ', '5-9', '1626'], ['sól', 'biłgoraj', 'poland', 'lublin'], ['sol'], ['sol', "sol's"], ['sól', 'north-east'], ['sol', "sol's"]]
TOP TOKENS [['vacuum', 'generators/vacuum', 'generator/vacuum'], ['vacuum-formed', 'vacuum'], ['vacuum', 'slurry', 'safely', 'option', 'excavator'], ['vacuum', 'time,vacuum', 'saving.vacuum', 'pre-defined'], ['vacuum', 'vacuum—even', 'vacuums', 'one', 'term'], ['vacuum', 'forming'], ['vacuum', 'technology'], ['vacuum', 'fertilizer', 'short'], ['vacuum', 'vacuum-coated', 'better', 'addition', 'coating', 'hence'], ['vacuum', 'loss', 'insulation', 'installing', 'average', 'unheard', 'environment', '’'], ['vacuum', 'simple:vacuum'], ['vacuum'], ['vacuum'], ['vacuum', 'intricate'], ['vacuum'], ['vacuum'], ['vacuum', 'elastomers'], ['vacuum'], ['vacuum', '“', 'word', '”'], ['vacuum', 'furnaces', 'high', 'furnace', 'materials']]
TOP TOKENS [['applications', 'countless', 'cameras', 'computers'], ['applications', 'include'], ['applications', 'application'], ['applications', 'uses', 'new', 'including', 'science', 'various'], ['applications'], ['applications'], ['applications', 'uses'], ['applications', 'metallurgical', 'durability', 'used'], ['applications', 'metallurgical', 'durability', 'used'], ['applications', 'following', '•', 'marine', 'use'], ['applications', 'including', 'used', 'diodes', 'cells', 'oelectronic'], ['applications', 'uses', 'formulations', 'detergents', 'also', 'usages', 'synergists', 'help', 'application'], ['purpose', 'applications', 'include', 'specific', 'uses', 'used', 'etc'], ['application', 'applications', 'used', 'unique', 'provide', 'perform', 'deconvolution'], ['applications', 'g', 'used', 'liners', 'various', 'environmental', 'geotechnical', 'hydraulic'], ['applications', 'many', 'extruded', 'used', 'polishing', 'hardening'], ['applications', 'application', 'used', 'g', 'include', 'bolometer', 'accelerators', 'including', 'technological', 'trains', 'ultra'], ['include', 'applications', 'potential', 'synthesis', 'endoscopy', 'printer', 'rangefinding', 'shows', 'devices', 'important', 'diagnostics', 'communication', 'within', 'sensors', 'telecommunications', 'computers', 'welding', 'economically', 'radiative', 'rescue', 'surgery', 'tattoo'], ['applications', 'range'], ['applications', 'physical', 'places', 'indexed', 'among', 'published', 'contents', 'according', 'abstracted']]
TOP TOKENS [['miriam', 'nazareth', 'magdala'], ['miriam', '“', 'well', 'way', 'boldly'], ['miriam', 'domingo'], ['miriam', 'nile', 'desert', 'celebration'], ['miriam', 'consciousness', '1960', 'exile', 'whose', 'kennedy', 'african'], ['miriam', '“', 'exalted', 'involving', '20', 'dances'], ['miriam.”', 'miriam', 'miriam,”', 'miriam’s', 'brother'], ['miriam', "miriam's", 'days', 'sing', 'though', 'even', 'agreed', "pharaoh's"], ["miriam's", 'miriam', 'brothers', 'redemption', 'water', 'ex', 'e'], ['miriam', "miriam's", 'character'], ['míriam', 'level', 'included', 'people', 'players', 'spanish', 'living', 'gloriosas', 'sant'], ['miriam', "women's"], ['miriam', 'born'], ['miriam', 'man', 'finnish', 'hans', 'anta', 'kaisu'], ['miriam', 'joan–miriam', '1957', 'finnish', 'film', 'rhode'], ['miriam', 'filmmaker'], ['miriam', 'external', 'links', 'spanish', 'references', 'living', 'biography'], ['miriam', '2016', 'https://cpd.org.au/author/miriam-lyons', 'since'], ['miriam', 'oliveira', "jol'inkomo", 'baião'], ['miriam', 'life', 'personal', 'ari', 'beth', 'magazine', 'girls', 'references', 'living', 'jacob', 'park', 'lyricists', 'marriage']]
TOP TOKENS [['magnesium'], ['magnesium', 'mgo', 'mg', 'mgco3·3h2o', 'mg(oh)2'], ['magnesium', 'mg', '”', '–', '“', 'pure', '2008', 'az91', '10', 'vol', '2015'], ['magnesium', 'processes', 'power', 'temperatures'], ['magnesium', 'mg', 'consumption', 'mg2si', 'alloys', 'well', 'consolidating', '1', 'however'], ['magnesium', 'mg', 'az31', 'mg17al12'], ['magnesium', "magnesium's", 'speeds', 'three', 'two', 'stability', 'addition'], ['magnesium', 'mg', 'even'], ['magnesium'], ['magnesium', 'creep-resistant', 'magnesium-intensive', 'alloys', 'existing'], ['magnesium', 'mg', 'ample', 'az81', 'however', 'az63', 'az91', 'provide'], ['magnesium', 'mg', 'grained', 'results', 'stabilizing'], ['magnesium', 'az31', 'az80', 'az61', 'az91', 'cls', 'wide', 'az92', 'az81'], ['magnesium', 'mg', '–', 'cathode', 'alloys'], ['magnesium', 'mg2al3', 'mgal', 'magnesium-aluminium', 'mg17al12', 'aluminium-magnesium'], ['magnesium'], ['mg'], ['magnesium', 'although', 'popular', 'conveys', 'machinability', 'metal', 'purpose', 'manufactured', '40'], ['magnesium–aluminium', 'mg', 'magnesium', 'mn'], ['magnesium', 'mgar', 'mg', '1281', '75', '1295', 'cm−1', 'exist', 'corresponding', '3']]
TOP TOKENS [['thessalonians', 'thessalonica'], ['thessalonians', 'noticed'], ['thessalonians', 'thessalonian', 'thessalonica'], ['thessalonians', 'thessalonian', '1'], ['thessalonians', 'thessalonica'], ['thessalonians'], ['thessalonians', 'thessalonica', 'thessalia', 'thessalians', '1', 'byzantinus', 'zonaras'], ['thessalonica', 'thessalonians', 'b', 'first', 'thes'], ['thessalonica', 'thessalonians', 'b', 'first', 'thes'], ['thessalonian', 'thessalonians', 'thessalonica'], ['thessalonians'], ['thessalonike', 'thessalonike,(θεσσαλονίκη'], ['thessalonica'], ['thessalus'], ['thessalonians', 'thessalonica', 'claromontanus', '1'], ['thessalonians', 'thessalonica', 'freerianus', 'alexandrinus', 'jesus', '1'], ['thessalonica', 'thessalonians', 'freerianus', 'c', '–', 'vaticanus'], ['thessalonians', 'thessalonian'], ['thessalonica', 'thessaly', 'preljubovic', 'constans', 'tocco'], ['thessalonians', 'thess']]
TOP TOKENS [['whaling', 'cls', 'although'], ['whaling', 'whalers'], ['whaling', 'attacks', 'targets', 'successful', 'attack', 'cfos'], ['whaling', 'commission'], ['whaling'], ['whaling', 'attacks', 'threats', 'someone', 'block', 'expedition', 'true', 'targets', 'bite'], ['whaling', 'whalinghistory', 'whalemen'], ['whaling', 'industry', 'feed'], ['whaling', 'whalings', 'p', 'wain'], ['whaling'], ['whaling'], ['whaling', 'iwc', 'germany', 'japan', 'icrw'], ['whaling', 'also', 'career', '1926', 'seattle', 'spent', 'turks'], ['whaling', 'whales'], ['whaling', 'commercial', 'cause', 'whale'], ['whaling', 'stance', 'anti', 'countries', 'iwc', 'pro', 'japan'], ['whaling', 'whalers', 'industry', 'sealers', 'vessels', 'bowhead', 'although'], ['whaling', '2012', 'career'], ['whaling', 'commercial', 'countries', 'whale', 'iwc'], ['whaling', 'nations', 'pro', 'commercial', 'history', 'dues', '1986']]
TOP TOKENS [['representing/on', 'another'], ['1', 'likes', 'rest', '0,0', 'put', 'certain', 'takes', 'working', 'explain', '64', 'points', 'town', '0'], ['things', 'would', 'together', 'learn', 'able', 'like', 'associated', 'time', 'yet', 'symmetrically', "cousin's"], ['something', 'means', 'way', '2', 'that’s', 'let’s', 'could', 'ear', 'i’m', 'instinctively'], ['die'], ['something', 'ways', 'come'], ['ride', 'create', 'going', 'immortalize', 'things', 'let', 'bunch', 'use', 'invent', 'able', 'piece', 'want', 'go'], ['use', 'could', 'make', 'activity', 'making', 'webs', 'troys', 'june', 'help', 'maybe'], ['make'], ['show', 'say', 'fluently', 'use', 'using', 'go', 'together', 'e', 'g', '4', '“'], ['event', 'til'], [], ['bifas'], ['like', 'example', 'work', 'music', 'others'], ['–'], [], ['rhamlee', 'december', 'peter', 'pasadena', '–', 'keyboards', 'vocals'], ['used', 'possible', 'allow'], ['included'], ['capturing', '30']]
TOP TOKENS [['fort', 'worth', 'museum'], ['worth', 'fort', 'care'], ['worth', 'fort'], ['fort', 'worth', 'worth’s', 'location', 'it’s'], ['fort', 'worth', "worth's", 'beaches'], ['worth', 'fort', '45', '6', '7', 'heterosexual', '05', '538', '721', '676', 'placed', '8', '28', '827'], ['fort', 'worth', '1949', 'also', 'resulting', 'u'], ['fort', 'worth', 'guides', "worth's", 'fortworth', 'fortworthgov', 'worthology'], ['worth', 'fort', 'worthians', 'region'], ['fort', 'worth'], ['fort', 'worth', "worth's", '7', '41'], ['worth', 'fort', '2010', '8'], ['fort', 'worth', "worth's", 'kahn', 'cls', 'u'], ['fort', 'worth', 'around', '200', '10', 'government', 'tarrant'], ['fort', 'worth', '–', 'fences', 'lake', 'city', 'bars'], ['worth', 'fort', 'links', 'genre', 'friend', 'external'], ['fort', 'worth'], ['fort', 'worth', "worth's", 'throughout'], ['worth', 'fort', 'greater', "worth's", 'dallas–fort', 'co-founder'], ['fort', 'worth', 'along']]
TOP TOKENS [['keel', 'centerboard', 'masts', 'vessel', 'sloop', 'sailboats', 'advantage', 'boats', 'mast', 'sailboat', 'sail', 'vessels', 'ship', 'headsails', 'masted', 'headsail', 'warships'], ['mast', 'starboard', 'one', 'sail', 'stern', 'hold'], ['brigs', 'masted', 'shorthanded', 'sailboat', 'offers', 'sloop', 'sailboats', 'sails', 'sailed', 'yawls', 'mainmast', 'one', 'two', 'rear', 'mainsail', 'schooners'], ['boats', 'sails', 'sail', 'masts', 'either', 'sloops', 'carries', 'mast', 'sloop', 'allows', 'also', 'rigs', 'mainmast', 'masted', 'advantage', 'gives'], ['brigs', 'sloops', 'masts', 'mainsail', 'topsails', 'schooners', 'also', 'mainmast', 'sail', 'masted', 'mizzenmast', 'sloop', 'foremast'], ['sloped', 'pitch', 'sloping', 'planes', 'ridge'], ['described', 'masted', 'catamarans', 'headsails', 'masts', '—', 'staysail', 'schooners', 'aka', 'sailboat', 'trimarans', 'sail', 'sloops', 'mainsail', 'sloop'], ['masts', 'masted', 'cutters', 'sloops', 'headsails', 'mainmast', 'either', 'also', 'sail', 'aft', 'mast', 'mizzenmast', 'one', 'sails'], ['masts', 'sails', 'sail', 'booms', 'one', 'mast', "stuns'ls", '–', 'vessel'], ['bilge', 'keel', 'sail', 'headsail', 'hull', 'sails', 'sailboats', 'mast', 'leads', 'catamarans', 'trimarans', 'water'], ['pitched', 'single-pitched', 'multiple-pitched', 'roof', 'pitch'], ['platform', 'sailboat', 'makes', 'external', 'yachts', 'proves', 'convenient', 'dock', 'designs', 'type'], ['crossjack', 'bowsprit', 'going', 'sail', 'mast', 'sloop', 'topsails', 'yachts', 'one', 'may', 'foresail', 'especially', 'used', 'craft', 'usually', 'range'], ['pitched', 'slope', 'gablet', 'ridged', 'gabled', 'detailed', 'roof', 'gable', 'pitch', 'stepped', 'together', 'slightly', 'roofs', 'available'], ['also', 'designers', 'foresails', 'staysails', 'squarely', 'sail', 'one', 'sails', 'achieves', 'jibs', 'allows', 'aft', 'minimizes', 'may', 'genoas', 'sailboat', 'mainsail', "sloop's", 'mast', "cutter's", 'towards'], ['mainmast', 'sail', 'sails', 'sloop', 'topsails', 'mast', 'masts', 'trimarans', 'simple', 'foremast', 'hulls', 'allowing', 'schooners', 'topmasts', 'catamarans', 'stance', 'point', 'backstay', 'features', 'mainsail'], ['subordinate', 'sails', 'commanding', 'skiff', 'cockboat', 'pinnace', 'oars', 'carrying', 'sail', 'boats', 'one', 'transfer', '4', 'belonging', 'boat', '6', '2', 'transporting', '1', 'officers', 'whaleboat', "ship's"], ['pitched', 'slope', 'sloped', 'windows', 'pitch', 'simplest', 'roof', 'together', 'type', 'forms', 'g', 'hip', '–', 'obtuse', 'usually'], ["fisherman's", 'masts', 'schooners', 'masted', 'sails', 'designs', 'also', 'wawona', 'schooner', 'one', 'known', 'includes', 'topsails', 'speed', 'america', 'although', 'built', 'safety'], ['heads', 'sailboat', 'external', 'yachts', 'links', 'type', 'designs', 'one', 'references', 'see', 'berth']]

Processing features:   1%|          | 1/98 [00:29<47:05, 29.13s/it]

getting sample prompt forgetting sample prompt for 23413
 23412
getting sample prompt for 23414
getting sample prompt for 23415
getting sample prompt for 23416
getting sample prompt for 23417
getting sample prompt for 23418
getting sample prompt for 23419
getting sample prompt for 23420
getting sample prompt for 23421
getting sample prompt for 23422
getting sample prompt for 23423
TOP TOKENS [['fruit', 'however', 'overall', 'may', '2', 'ungainly', 'breeding', '7', 'nature', 'found', '3', 'mystery', '11', 'although', 'birds', '10'], ['past', 'chains', 'experiments', 'industry', 'forces', 'along', 'emerge', 'activity'], [], ['post', 'parking', 'well', 'please', 'today', 'try', 'site', 'button'], ['elasmobranchs', 'however', 'dwelling', 'reported', 'full', 'individuals', '80', 'like', 'al', 'fertilization', 'total', 'cusps', 'approximately', 'shortly', 'size', 'caudal', '69', 'birth', 'sawfish', 'limited', 'simpfendorfer', '2008', '1', 'schools', '81', '27', 'slashing'], ['sir', 'sciences', 'medicine', 'congratulate', 'congratulating', 'receive', 'presented', 'celebration', 'ably', 'sep'], ['periodic', 'high', 'wavelength', 'us', 'demonstrates', 'please', 'naturally', 'underlie', 'inferring', 'successful', 'diagnostic', 'time', 'suggest', 'results', 'improvement', 'within', 'first', 'margins', 'reliant', 'imagery', 'attempted', '1997', 'al', '2011', 'numerous'], ['air-borne', 'ship-borne', 'two-dimensional', 'breaking', 'up-to-date', 'attendant', 'aspects', 'sea', 'air-sea', 'oceanography', 'spatio-temporal', 'flows', 'breakings', 'clouds', '7', 'findings', '6', 'numerous', 'life-time', 'introduction', 'atmosphere-ocean', 'whitecappings', 'system'], ['wave-follower', 'complete', 'wave-following', 'low-level', 'frequency-dependent', 'hot-film', 'surface', 'george', 'shift', 'waves', 'probes', 'finite-depth', 'provides', 'conducted', 'florida'], ['long-range', 'short-range', 'over-snow', 'ground-based', 'studies', '1980s/1990s', 'ice-covered', 'establishment', 'extensive', 'investigate', 'utilised', '1960s/1970s', 'developments', 'parameters', 'aircraft'], ['seasons', 'references', 'f.c', 'fixtures', 'results'], ['table', 'results', 'seasons', 'scoring', 'statistics', 'season', 'scorers', 'links'], ['bahawalpur’s', 'first-class', '72', '1969-70', 'occasional', 'middle-order', 'made', 'moderately', 'season', 'quaid-e-azam', 'final', '56.00'], [], ['seasons', 'd1', 'links', 'summarizes', 'results', 'onlyinclude', 'info', 'external', '2011-12'], ['runners-up', 'table', 'seasons', 'awards', 'links', 'external', 'winner', 'goalscorers', 'news', 'third-place', 'results', 'references', 'see', 'also'], ['conclusion', 'website', '2011', 'standings', 'official', 'links', 'named', 'external', 'references', 'tournament', 'goalscorers'], ['awards', 'results', 'statistics', 'table', 'external', 'references', 'seasons', 'goalscorers', 'links', 'sep'], ['scorers', 'footnotes', 'references', 'results', 'table', 'seasons', 'first', 'division', 'officially', 'premier', 'statistics', 'began', 'stars'], ['awards', 'personnel', 'references', 'external', 'links', 'scoring', 'scorers', 'locations', 'league', 'top', 'note', 'results', 'statistics', 'annual', 'goals', '4', 'notes', 'seasons', "season's", 'managerial', 'players', 'season', 'table', 'bless', 'time', 'goals5', 'presence', 'flight', 'nike', '–', 'additionally', 'ever']]
TOP TOKENS [['hacket', 'haggett', 'haget', 'haket', 'splendid', 'chief', 'slipped', 'proper', 'olde', 'hakes', 'hali', 'hake', 'byname', '1086', 'recorded'], ['millet', 'manganese', 'protein', 'red', 'back', 'flavour'], ['millet', 'animals', 'salads', 'risks'], ['boneset', 'cold', 'properties', 'intended', 'problems', 'across', 'muscle', 'catarrhal', 'promotes'], ['millet', 'delicious', 'course', 'yet', 'consists', 'iron', 'flavor', 'said', 'higher', 'world'], ['boneset', 'states', 'traced', 'studies', 'back', 'asteraceae', 'around', 'thickets', 'traditionally', 'problems', '½', 'united', 'measuring', 'according', 'plant', 'influenza', 'vegetable'], ['tenet', 'ten’it', 'medicine'], ['crotchet', 'crocket', 'mr', "crotchet's", 'mrs', "that's"], ['hacket', 'vols', "walker's"], ['billet'], ['1976', '1979', 'historian', '1953', 'gillet', '1840-1908'], ['mallet', 'stick', 'surname', 'fa:کوبه', 'crater', 'computer', 'mallett', 'hammer', 'janeiro'], ['basset', 'scenthound', 'clarinet', 'petit', 'horn'], ['automobile', '1950s', "world's", 'india', '35mm', 'signet', "majesty's", 'kodak', 'disambiguation', 'kbc'], [], ['d.c', 'u-shaped', 'becket', 'fastener'], ['heavy', 'band'], ['comics', 'cable', 'painter', 'monetdb', 'monet', 'multiwavelength', 'maria'], ['basset'], ['europe', 'genus', 'burnet', 'six-spot', 'texas', 'minor', 'filipendulae', 'species']]
TOP TOKENS [['whose', 'track', 'individuals', 'recent', 'attributable', 'recently', 'number', 'ones', 'taking', 'past', 'member', 'long', 'associated'], ['among', 'received', 'receive', 'assigned', 'actually', 'b', 'instead', 'subjects', '1', 'example', 'originally'], ['stopped'], ['under-identifying', 'over-identifying', 'identified', 'evaluate', 'related', 'consider', 'thus'], ['count', 'walk', 'percentage', 'number', 'unintentional', 'gets', 'baserunners', 'amount', 'thrown', 'many', 'caught', 'balls', 'result', 'times', '–', 'results', 'batters'], ['obtained', 'players', 'player', 'balls', 'number', '3', 'simply', '12', 'given', 'one', 'even'], ['one', 'someone', 'effective', 'person', 'effectiveness', 'using', 'people', 'else', 'example', 'job', 'assigned', 'done', 'attempting', 'impact', 'certain', 'usually'], ['done', 'simply', 'accomplished', 'something', 'know'], ['reassigned', 'unassigned'], ['importanceupdatingagent', 'mindagent', 'rentcollectionagent', 'every', 'would', 'class', 'importancespreadingagent', 'wageagent', 'importancediffusionagent', 'mindagents', "mindagent's", 'hebbianlinkupdatingagent', 'forgettingagent', 'done', 'also', 'based'], ['result', 'statistic', 'player', 'walk-to-strikeout', 'hitters', 'statistics'], ['number'], ['based'], ['2018–2019', 'players', 'sciver', '2016–2019', 'player', 'lizelle'], ['individuals', 'dates', 'served'], ['colspan', 'cellspacing', 'text', '0', 'style', '1'], ['cricketers', 'list', 'number', 'database'], ['–', 'olb', '2013', '2007', 'watson', 'williams', 'washington', 'young', 'weaver', '2015', 'wells'], ['reduction', 'associated', 'receiving', 'eligible', 'untreated', 'relates', 'levels', 'reflect'], ['applying', 'apply', 'tutored', 'applies', 'application', 'knowledge', 'knowing', 'tracing', "learner's", 'makes', 'demonstrating', "student's", 'bayesian', 'model', 'known', 'represented', 'problem/step', 'models', 'common']]
TOP TOKENS [['ira', 'nationalism', 'pearse', "pearse's", 'century', 'closely', '1969', 'unhistorical', 'real', 'wrote'], ['district', 'peary', "peary's", 'south', 'commandeered', 'furthermore', 'bear', 'although', 'properly', 'purely', 'carried', 'means', 'describing', '…', 'asked'], ['invasion', "pearse's", 'pearse', 'insane', 'learners', 'seemingly', 'land', 'must', 'books', 'knew', 'long', 'achieve', 'mainly', 'armed'], ['’', 'peary', 'decades', 'inughuit', 'e', 'two', 'several', 'foods', 'upon', 'drive'], ['1904', "peary's", 'greenland', 'relationship', 'peary', 'dc', '1944', 'never', 'certified', 'first', 'later', 'false', '1907', 'pioneered', 'employees', 'also', 'moved', 'upon'], ['peary', 'northern', 'death', '1905', 'parcticipated', "peary's", 'several', 'mother', 'activities', 'fryeburg', 'although', 'nicaragua', 'u', 'project', 'american', 'made', 'worked', 'engineer', 'many', 'greenland'], ['pearse', 'imprisoned'], ['peary', 'made', '1898-1905', '9:30am', '1886', '1911', 'several'], ["peary's", 'peary', 'e', 'recognized', 'ahnighito', 'j', 'w', 'substantiate', '1955'], ['peary', "peary's"], [], ['level', '1927', 'habitats'], ['30', '15', 'starter', 'guard', 'hendersonville', '1941', 'three'], ['1856–1920', 'peary', 'antarctic', '1908–1985', '1944', '1906–1989', 'benjamin'], ['pearsall', '2007', 'issues', '1980', 'numerous', '2000', 'u', '1976', '1983', '1985', 'herrick', 'patch', 'life', '1986', "pearsall's", 'charter'], ['mabel', 'environmentalist', '1853-1926', 'australian', 'writer', 'soldier'], ['road', '37'], ['1956'], ['pearkes', 'r', '14', "pearkes'name", '1931', 'sidney', 'port', 'june', '1968', "hudson's", 'island', 'penticton', "children's", '1970', 'north', 'coast', 'alexandra'], ['shortly', '1920', 'jr']]
TOP TOKENS [['mail', 'mails', 'internet'], ['mail'], ['mail', 'sendmail', 'mailbox', 'cls'], ['mail', 'mailhost', 'hypermail'], ['mail', 'mails', 'mailbody', 'maildir', 'send'], ['mail', 'mails', 'outgoing', 'receiving', 'sent', 'writing', 'popular', 'messages', 'programs', 'retrieve'], ['mail', 'sendmail', 'mailer', 'mailers', 'mailboxes', 'gets', 'handles', 'mailbox', 'servers'], ['mail', 'sendmail', 'mailer', 'mailers', 'mailboxes', 'gets', 'handles', 'mailbox', 'servers'], ['var/mail', 'mail', 'mailhost.domain-name', 'etc/mail/sendmail.cf', 'etc/mail/aliases', 'connection', 'mailbox'], ['mail', 'mails', 'created', 'one', 'mailboxes', 'using', 'server', 'servers', 'another', 'carefully'], ['mail', 'parcels', 'mail.ru'], ['mail', 'mailutils', 'mailx', 'mailboxes'], ['mail', 'mailman', 'style', 'qmail', 'mailing', 'sendmail', 'email', 'maillist', 'pipermail', 'exim', 'electronic', 'raj'], ['mail', 'mail-in-a-box', 'host', "server's", 'imap/smtp'], ['maílton', 'brasileiro', 'simply', 'campeonato', 'known'], ['mailheaders', 'mail', 'mail.app', 'gnumail', 'outgoing', 'maildir', 'nextmail', 'e-mail', 'protocols', 'gnumail.app'], ['mail', 'home', 'links', 'corp', 'would'], ['mail', "getmail's", 'maildir', 'getmail', 'getmail6', 'mailboxes', 'fetchmail'], ['mail', 'mailu', 'e-mail', 'mailcow', 'iredmail', 'identifying', 'mail-in-a-box'], ['mail', 'mailboxes', 'maildirs', 'webmail', 'mailing', 'qmail', 'maildrop', 'mailbox', 'managed']]
TOP TOKENS [['psalm', 'psalms', 'psalmed', 'psalming', 'worship'], ['psalms', 'psalm'], ['psalms', 'psalm', 'cls'], ['psalm', 'psalms'], ['psalm', 'psalms', '“'], ['psalms', 'psalm', 'cls', 'book'], ['psalms', 'psalm'], ['psalms', 'psalm'], ['psalm', 'psalms', 'book'], ['psalms', 'psalm', 'word'], ['psalms', 'psalm', 'album'], ['psalms', 'billboard'], ['psalms', 'psalm', 'psalmist', 'verses', 'impossible', 'lord', '16', 'verse', '25', 'part'], ['psalm', 'psalms', "psalmist's", 'book', 'verses', 'hymn'], ['psalm', 'psalmist', 'finally', 'mine', 'yea', 'sea'], ['psalms', 'psalm', 'book', 'psalmody', 'text'], ['psalms', 'psalm', 'book'], ['psalm', 'psalmist', 'psalms', 'god', 'paraphrasing', 'sees', 'done', 'texte'], ['psalms', 'psalm', 'hymn', 'book', 'one'], ['psalm', 'psalmum', 'psalms', 'psalmica', 'text', 'psalmographus', 'interpretation', 'orationum', 'latter']]
TOP TOKENS [['maiandros', 'meandrous', 'high', 'flows', 'mountainside', 'porch', 'home', 'strolling', 'road', 'path', 'phrygia', 'word', 'front', 'leading', 'atop', 'meandering', "lake's", 'turns', 'meen'], ['fruits', 'luxure', 'luxuriation', 'luxuria', 'indulge', 'pride', 'lycanthrope', 'noun', 'luxury', 'luxuriate', 'verbal', 'luxuriatus', 'lust', 'luxurist', 'luxuriari', 'luxuriates', 'luxuries', 'rarity', 'herds', 'furniture', 'corn', 'luxuriating', 'luxurious', 'luxuriance', 'delicacy', 'ice', 'furnished', 'luxuriosus', 'exuberantly', 'food', 'tastes', 'jewels', 'luxurieux', 'sensuality', 'drunkenness', 'luxuriously', 'silks', 'anything', 'cities', 'appetites', 'garden', 'burton'], ['boodled', 'mansion', 'put', 'comes', 'drove', 'clothes', 'pair', "there's", 'hush', 'owned'], ['roads', 'keynes', "keynes's", 'milton', 'sections', 'time', 'bowl', 'c', 'summer', 'cold', 'racing', 'pools', 'place', 'canal', 'artists'], ['boodled', 'mansion', 'put', 'comes', 'drove', 'clothes', 'pair', "there's", 'owned', 'hush'], ['trunk', 'grille', 'topped', 'top', 'front', 'behind', 'begins', '1963', 'lights', 'surrounding', '“', 'motif', '”', 'distance', 'centre', 'bulge', 'ones'], ['vibrant', 'colors', 'produce', 'food', 'bustling', 'indulge', 'markets', 'offer'], ['road', 'sweeping', 'occasionally'], ['world'], ['build', 'bp', 'rpm', "rpm's", 'executed', 'environment', 'stage'], ['clarkson', 'eaton', 'gt', 'car', 'grand', 'motor1', 'race', 'racing', 'lap', 'motoring', 'episode', 'sport', 'matter', 'tour'], ['eaton', "eaton's", 'gtr', 'gt', 'car', 'episode', "itv's", 'bmw', 'cup', 'racing', 'starting', 'years', 'period', 'gt3', 'finishes', 'race', 'round', 'season', 'cars', '2016', 'places', 'champion', 'positions', 'races', 'record', 'time', 'series', 'hoggarth', 'position'], ['grille', 'interiors', 'grilles', 'deck', 'upholstery', 'richer', 'fenders', 'bumper', 'carburetor', 'leather', 'hood', 'parking', 'washers', 'cadillac', 'gm', 'padded', 'car', 'separated', 'slightly', 'combinations', 'year', 'standard', 'panel', 'operation', 'mounts'], [], ['wheel', 'grille', 'oil', 'heater', 'cadillac', 'deck', 'parking', "cadillac's", 'exhausts', 'look', 'front', 'housings', 'defroster', 'wipers', 'door', 'windshield', 'sedan', 'sales', 'fender', 'behind', 'swept', 'skirts', 'lamps', 'units', 'bolder', 'quietness', 'sedans', 'fenders', '1963', 'mirror', 'cornering', 'housed', 'hatched', '1962', 'redesigned', 'washer', 'appeared'], ['sunroof', 'exterior', 'panoramic', 'tailgate', 'heated', 'high', 'front', 'ambient', 'vibrant', 'interior', 'ecoguide', 'headlamps', 'colours', 'exhausts', 'smartgauge', 'wipers', 'colour', 'electric', 'applied', 'braking', 'battery', 'seats', 'variants', 'detection', 'developing', 'sportiness'], ['street', 'clarkson', 'toyota', 'gt86', 'elephant', 'drive', 'subaru', 'cars', 'word', 'takes', 'exception', 'use', 'epithet', 'transmitted'], [], ['sunroof', 'heated', 'cylinder', 'perforated', 'bucket', 'pane', 'interior', 'luxury', 'leather', 'front', 'wheel', 'ventilated', 'audio', 'options', 'touchscreen', 'steering', 'auto', 'inch', 'system', 'automatic', "driver's", '4', 'wheels'], []]
TOP TOKENS [['electrolyte', 'electrolytes', 'yes'], ['electrolytes', 'electrolyte', 'term', 'simply', 'salt'], ['electrolytes', 'electrolyte', 'child’s'], ['electrolyte', 'electrolytes', 'high'], ['electrolytes', 'electrolyte'], ['electrolytes', 'electrolyte', 'soups', 'page', 'difficult', 'cells'], ['electrolytes', 'electrolyte-rich', 'electrolyte'], ['electrolyte', 'electrolytes', 'tandem', 'heard'], ['electrolytes', 'electrolyte'], ['electrolytes', 'electrolyte', 'cls'], ['electrolytes', 'electrolyte', 'word', 'e', 'cls'], ['electrolytes', 'electrolyte'], ['electrolytes', 'electrolyte'], ['electrolytes', 'electrolyte'], ['electrolyte', 'word', 'λυτος', 'formation', 'ηλεκτρο', 'throughout', "arrhenius's", 'mentions', 'electro', 'able', 'well'], ['electrolytes', 'electrolyte', 'ions', 'use', 'consume'], ['electrolytes', 'electrolyte', '9.3', '7'], ['electrolyte', 'electrolytes', 'also', 'hbro3', 'one', 'fluoroantimonic', 'carborane'], ['electrolyte', 'electrolytes', "electrolyte's", 'electrolytic', 'ions'], ['electrolyte', 'electrolytes']]
TOP TOKENS [['heating', 'contaminants', 'pollutants', 'fixtures', 'windows', 'conditioner', 'smoke', 'dehumidifier', 'household', 'allergens', 'ducts', 'dust', 'irritants'], ['furniture', 'heater', 'home', 'dust', 'ducts', 'mattresses'], ['wall', 'smoke', 'hangings', 'furniture', 'home', 'knickknacks', 'countertops', 'dust', 'quilts'], ['pollutants', 'furniture', 'home', 'heat', 'windows', 'germs', 'dust', 'heating', 'mildew', 'appliances', 'mites', 'dehumidifier', 'vented', 'building'], ['home', 'basements', "home's", 'walls', 'cabinets', 'ventilation', 'cords', 'attics', 'bookshelves', 'heating', 'homes', 'sofas', 'appliances'], ['home', 'dust', 'allergens', 'rooms', 'mites', 'house'], ['dehumidifier', 'steam', 'windowsills', 'humid', 'conditioners', 'heaters', 'ducts', 'closets', 'vent', 'smoke', 'drawers', 'damp', 'curtains', 'bookshelves', 'window', 'lampshades', 'home', 'bathrooms', 'dust', 'bedrooms', 'room', 'areas', 'humidity', 'indoor', 'allergen'], ['conditioner', 'furniture', 'bedcovers', 'home', 'room', 'house', 'humidity', 'tabletop', 'blankets', 'damp', 'allergens', 'dry', 'dehumidifier', 'dust', 'allergen'], ['conditioner', 'furniture', 'bedcovers', 'home', 'room', 'house', 'humidity', 'tabletop', 'blankets', 'damp', 'allergens', 'dry', 'dehumidifier', 'dust', 'allergen'], ['furniture', 'kitchens', 'mites', 'home', 'dust', 'bathrooms', 'bedding', 'items', 'smoke', 'curtains', 'rugs', 'smoking', 'cleaning', 'windows'], ['furniture', 'rooms', 'house', 'dusting', 'household', 'allergies', 'pollutants', 'burning', 'headache', 'conditioner', 'dust', 'headaches', 'eyes', 'ducts', 'odor', 'stale', 'appliances', 'cleaning', 'sinus', 'sick', 'furnace', '1'], ['home', 'homes', 'moisture', 'ducts', 'building', 'walls', 'ceilings', 'mold', 'vapor', 'humidity', 'order', 'health', 'kitchens', 'spaces', 'infestation', 'indoor', 'water', 'decrease', 'deterioration', 'exists', 'air', 'space'], ['piping', 'pipes', 'cabinetry', 'plumbing', 'dust', 'walls', 'ceiling', 'house', 'ventilation', 'flooring', 'paneling', 'wood', 'wallpaper', 'building', 'homes', 'carpentry', 'smell', 'mold', 'carpets', 'carpet', 'behind', 'buildings', 'conditions', 'humidity', 'moisture', 'condensation'], ['ventilation', 'ductwork', 'wallpaper', 'pipes', 'paneling', 'house', 'heating', 'dust', 'behind', 'odors', 'cavities', 'mold', 'area', 'homes', 'vapor', 'living', 'condenses', 'water', 'conditioning', 'furniture', 'moisture', 'indoor', 'bacterial', 'air', 'humidity'], ['furniture', 'dust', 'mites', 'dustbunny', 'house', 'flakes', 'electrostatic', 'cleaning', 'dead', 'dustbunnies', 'rubbish', 'debris', 'shortening'], ['flames', 'daemons', 'heresy', 'library', '2005'], ['dust', 'mites', 'cleaning', 'mold', 'contaminates', 'heating', 'evaporation', 'buildings', 'ventilating', 'indoor', 'building', 'burn', 'inventories', 'airborne', 'showering', 'ventilation', 'elimination', 'flooring', 'mitigate', 'floor', 'combustion', 'filtration', 'dehumidification', 'well'], ['dimmers', 'wattage', 'wood', 'windows', 'pollutants', 'residue', 'soot', 'cleaning', 'curtains', 'source', 'materials', 'heat', 'fabric', 'discolor', 'moisture', 'staining', 'compounds', 'bulbs', 'dyes', 'impregnation', 'efflorescence', 'discoloration'], ['furniture', 'mold', 'basements', 'surrounding', 'cleaned', 'areas', 'room', 'water', 'vapor', 'walls', 'ducts', 'building', 'affected', 'ventilation', 'desiccants', 'spores', 'drying', 'air', 'health', 'damp', 'contractors', 'bleach', 'humidity', 'shelves', 'risk', 'spread', 'containers', 'items', 'preventing', 'materials', 'removes'], ['dust', 'mites', 'residue', 'bacteria', 'dirt', 'disinfect', 'mold', 'remove', 'scents', 'hypoallergenic', 'contamination', 'carpets', 'floor', 'contaminants', 'detergent', 'clean', 'cleaning', 'floors', 'vapor', 'steam', 'celsius', 'leave']]

Processing features:   2%|▏         | 2/98 [00:56<45:14, 28.27s/it]

getting sample prompt for 23424
getting sample prompt for 23425
getting sample prompt for 23426
getting sample prompt for 23427
getting sample prompt for 23428
getting sample prompt for 23429
getting sample prompt for 23430
getting sample prompt for 23431
getting sample prompt for 23432
getting sample prompt for 23433
getting sample prompt for 23434
getting sample prompt for 23435
TOP TOKENS [['marang', '1991', 'food', 'california', 'full', '6', '1891', 'directions'], ['marang', '1991', 'food', 'california', 'full', '6', '1891', 'directions'], ['marasmus', 'marathas', 'maraudeur', 'marauded', 'marauder', 'maraud', 'marault', 'maraschino', 'maranatha', 'marasca', 'maranta', 'marauding', 'gujarati', 'participle', 'intransitive', 'peoples', 'noun'], ['maracas', 'today'], ['marauder', '11993', 'radiation'], ['maraviroc', 'throat', 'body', 'aids', 'jaundice', 'sure', 'severe', 'immunodeficiency', 'upper', 'medicines'], ['maran', 'maranshahn', 'white', 'covered', 'kupferrot', 'jpgthe', 'association', '001', 'birchen', 'grey', 'first', 'dark', 'head', 'depth', '19', '25', 'wikimedia'], ['maracuya', 'give', '2', 'type', '5', 'p', 'main', 'passion', 'f', 'flavicarpa', 'certainly', 'long', 'fruit', 'two', 'wide'], ['maraviroc', 'drugs', 'throat', 'use', 'unprotected', '1088', 'taking', '800', 'take'], ['maracas', 'beads'], ['1832–1899', 'c', 'hill', 'mařák'], ['marani', 'marano', 'river', 'bo', 'principato'], ['maranhão', 'footballer', 'marañón'], ['marakān', 'marakan', 'marākān'], ['marau', 'general', 'brazil', 'battle'], ['marans', 'maran', 'title'], ['marang'], ['marāng'], ['marant', 'france'], ['marān', 'maran']]
TOP TOKENS [['country', 'manners', 'tries'], ['country'], ['country', 'bible', 'definitions'], ['country', '‘', 'use', 'cls', 'yet', '’', '…', 'ציון'], ['country', 'countrycoun', 'cls'], ['country', 'countryman', 'paris', "country's", 'countries', '1', 'interchangeably', 'use'], ['country'], ['country', '“', 'word', 'term', 'inconclusive', 'divisions', '”', 'pages'], ['country', "country''s"], ['country', "country''s"], ['country', 'see', 'film'], ['country', 'town-and-country'], ['country'], ['country'], ['country', 'country99tv', 'tv', '99'], ['country', '2021', 'services', 'capitalized', 'bloomington–normal'], ['country'], ['country', 'album'], ['countryman', 'nation'], ['countrytime']]
TOP TOKENS [['century', 'testa', 'arguably', 'architecture', 'footsteps', '’', 'first', 'forced', 'remain', '‘', 'embodied', 'years'], ['teston', 'tester', 'tester3', 'tester1', 'testa', 'tester2', 'testerium', 'testera', 'tester—and', "tester's", 'fewer', 'tester.the'], ['testimonials', 'testimonial', 'say', 'exploited', 'e', 'cases', 'type', 'instill', 'personality'], ['testimonials', 'item', 'testimonial', 'http', 'common', 'v4hqego', 'person', 'action', 'toward', 'fr', 'watch'], ['testimonials', 'testimonial', 'business'], ['testudines', 'testudo', 'generally', '1957', 'typica'], ['testudines', 'testudo', 'generally', '1957', 'typica'], ['testudo', 'concern'], ['testudo', 'concern'], ['testnet', '“testnet”', 'testnets', 'also', 'bitcoin’s'], ['speleologist', 'testa', 'roman', 'dante', 'catholic'], ['england'], ['testery', 'testar'], ['testerian', 'testerman'], ['testa', 'testarossa', 'botany'], ['december', 'teste'], ['fear', 'testi', 'onward', 'yanez', '2013', 'fell', 'life', 'also', '2000s', 'predominantly', 'contraband'], ['gloaming', 'testro', 'appeared'], ['narrator', 'testo'], ['1971', 'testud']]
TOP TOKENS [['ballard', 'mutli', 'buildings', 'area', 'halt'], ["ballard's", 'ballard', 'robert', 'reader', 'list', 'time', 'shows', 'ocean', 'authentic', 'drabelle', 'chronicled', "what's", 'september'], ['ballard', 'dr', 'also', 'tele'], ['ballard', 'dr', 'also', 'tele'], ['ballard', 'honeycutt'], ['ballard', 'ballards', 'ballarde', 'ballardi', 'nickname', 'state', 'counties', 'northamptonshire', 'oxfordshire', 'cathedral'], ['ballard', 'dr', 'valor', 'site', 'dreams', 'documentary', 'historian', 'would', '’', 'military'], ['ballard', 'heart', 'found', 'hybrid', 'giving', '’', 'school', 'extolled', 'death', '—', 'england', 'exorcised'], ['ballard', "ballard's", 'dr', 'also', 'dream', 'education', 'robert'], ['ballard', "ballard's", 'dr', 'also', 'dream', 'education', 'robert'], ["ballard's", 'ballard', 'year', '2021', 'playoffs', 'record', 'two'], ['ballard', 'career', '2021', 'school', '12', 'people'], ['ballard', "ballard's", 'c', 'october', '1989', 'ward', 'minutes', 'foley', 'earle'], ['ballard', 'conference', 'career', 'leading', 'first-team', 'fame', 'winner'], ['ballard'], ['ballard', '2023', 'press', '2021', '2018', 'life', 'personal'], ['ballard', 'storekeeper'], ['ballard'], ['ballard', 'today', 'announced', "can't", 'ones', 'stated'], ["ballard's", 'ballard', 'enforcement', 'labor', 'children', 'session', 'law', 'also', 'apostles']]
TOP TOKENS [['screws', 'screw', 'screwdrivers', 'common', 'hardness'], ['screw', 'screws'], ['screw', 'screws', "screw's", 'screwdrivers', 'cls', 'turned', 'peak'], ['screw', 'screws', 'screwdriver', 'cls'], ['screws', 'screw', 'cls'], ['screws', 'screw', 'materials', 'reason'], ['screw', 'screws'], ['screws', 'screw', 'screwdriver', 'screwdrivers', 'screw-cutting'], ['screw', 'screws', 'nail'], ['screws', 'screw', 'know'], ['screw', 'screws', 'fastener', 'motion', 'series'], ['screws', "screw's", 'screw', "archimedes'screw", 'outside', 'threads', 'corkscrew', 'cls'], ['screw-cutting', 'screw'], ['screw', "screw's", 'screws', "archimedes'screw", 'threads'], ['screws', 'screw', 'screwdriver'], ['screws', 'screw', "screw's", "archimedes'screw", 'jack'], ['screw', 'screws', "archimedes'screw", 'threads'], ['screw', 'release', '2011', 'typeset', 'chart', 'one-man', '2013', 'titled', 'kei'], ['screw'], ["screw'configurations", 'screw', 'screws', "screws'spindles", "term'screw", "screw's", "archimedes'screw"]]
TOP TOKENS [['binary', 'vice', 'binaries'], ['binary', '“', 'raw'], ['“binary', 'binary', '“binary”', 'binary”'], ['binary', 'computing'], ['binary', '“', '”'], ['binary'], ['binary', 'words', 'mathematics'], ['binary', '2008'], ['binary', 'hand', '‘', 'word', '’'], ['binary'], ['binary', 'binary-coded'], ['binary', 'pt:binário'], ['binary'], ['binary', 'binaries', 'cls', 'object'], ['binary', 'shooting', 'binding', 'private-letter'], ['binary', 'various', 'ancient', 'use', 'gates'], ['binary'], ['binary', 'mechanical'], ['binary', 'weeks'], ['binary', 'binaries', 'static', '200', 'emulators']]
TOP TOKENS [['parathyroid', 'hyperparathyroidism'], ['parathyroid', 'parathyroidectomy', 'hyperparathyroidism'], ['parathyroid', 'parathyroidectomy', 'hyperparathyroidism'], ['parathyroid', 'parathyroidectomy', 'hyperparathyroidism'], ['hyperparathyroidism', 'parathyroidectomy'], ['parathyroid', 'parathyroidectomy', 'hyperparathyroidism'], ['hyperparathyroidism', 'parathyroid'], ['hyperparathyroidism', 'parathyroid'], ['parathyroid', 'parathyroidectomy', 'hyperparathyroidism'], ['parathyroidectomy', 'parathyroid', 'hyperparathyroidism', 'patients'], ['parathyroid', 'parathyroiditis', 'hyperparathyroidism'], ['parathyroidectomy', 'parathyroid', 'hyperparathyroidism'], ['parathyroid'], ['parathyroid', 'hyperparathyroidism'], ['parathyroid', 'parathyroids', 'parathyroidectomy', 'hyperparathyroidism', 'pth'], ['parathyroid', 'parathyroideae', 'hyperparathyroidism'], ['parathyroid', 'hyperparathyroidism'], ['parathyroid', 'hyperparathyroidism'], ['parathyroid', 'hyperparathyroidism', 'parathymic'], ['parathyroid', 'hyperparathyroidism', 'cls']]
TOP TOKENS [['type', 'ab', 'group', 'blood'], ['type', 'group', 'blood'], ['type', 'ab', 'group', 'blood'], ['type', 'ab', 'group', 'blood'], ['type', 'group', 'types', 'blood', '”'], ["child's", 'group', 'blood', 'type', 'ab'], ['group', 'blood', 'type', 'groups', 'faster', 'ab', 'belonging'], ['type', 'groups', 'blood'], ['type', 'group', 'groups', 'blood', 'ab'], ['type', 'factor', 'blood', 'factors', 'typeisdone', 'youyour', 'b'], ['abo', 'groups', 'blood', 'group', 'type', 'a−', 'types', 'ab', 'rh'], ['type', 'ab', 'group', 'groups', 'abo', "individual's", "someone's", 'blood', 'types', 'b'], ['group', 'groups', 'type', 'types', 'blood', 'connecting', 'hangovers'], [], ['groups', 'type', 'specific', 'types', 'blood', 'group'], ['group', 'blood', 'abo', 'type', 'groups', 'ab'], ['type', 'group', 'blood', 'ab', 'types'], ['type', 'group', 'abo', 'blood', 'ab', 'individuals', 'east'], ['group', 'type', 'blood', 'types', 'ab', 'antigen', 'groups', 'rh', 'abo', 'hypothesized', 'system', 'zero'], ['group', 'blood', 'type', "one's", 'ab', 'abo', 'theory', '‘']]
TOP TOKENS [['gcses', 'gcse', 'levels'], ['gcses', 'gcse', 'levels', 'level'], ['gcse', 'gcses'], ['gcses', 'gcse'], ['gcse', 'gcses'], ['gcses', 'gcse', 'levels'], ['gcses', 'gce'], ['gcse', 'gcses'], ['gcses', 'gcse'], ['gcses', 'gcse', 'levels'], ['gcse', 'chosen'], ['gcse', 'education'], ['gcse', 'aqa'], ['gcses', 'gcse', 'offers', 'year', 'level', 'aqa', 'pupils'], ['gcse', 'gcses'], ['gcse', 'gcses', 'aqa'], ['gcse', 'gcses', 'gce', 'levels'], ['gcse', 'gcses', 'body', 'c', 'marks', 'boundaries', 'content', 'religious', 'qualifications', "student's"], ['gcse', 'grades', 'marks', 'one', 'indeed', '50', 'due', '11', 'level', 'manufacture', 'previous', '–', 'student', 'new'], ['gcse', 'gcses']]
TOP TOKENS [['supply', 'hydrogen', 'produced', 'economy', '2'], ['hydrogen', 'market', 'injecting', 'trade', 'production', 'green'], ['hydrogen', 'green', 'economy', 'production', 'distribution', 'producing', 'market'], ['hydrogen', '£2', 'innovation', 'envisages', 'projects', 'regarding', 'roadmaps', 'green', 'economy'], ['hydrogen', 'green', 'world'], ['hydrogen', 'large-scale', 'market', 'commission’s', 'supply', 'transport', 'pan-european'], ['hydrogen', 'national', 'economy', 'interlinked'], ['per', 'hydrogen', 'projects', 'producer', 'supply', 'manufacturing', 'produces', '0', 'one', 'production', 'year', 'beyond'], ['hydrogen', 'economy', 'sector', 'production'], ['production', 'green', 'hydrogen', 'economy'], ['production', 'produce', 'hydrogen', 'producer', 'network', 'china', 'project', 'projects', 'document', 'green'], ['hydrogen', 'funding', 'green', 'production', 'luxembourg'], ['green', 'hydrogen', 'projects', 'production', 'qonik', "nujio'qonik", 'gigawatts', 'producer', "chile's"], ['market', 'hydrogen', 'green', 'projects', 'global', 'kfw', 'cheapest', 'production', '“'], ['hydrogen', 'economy', 'technology', 'regions', 'technologies', 'francisco', 'events', 'competitiveness', 'provides'], ['hydrogen', 'production', 'programme', 'green', 'include', 'strategy', 'subsidized', 'unveiled'], ['hydrogen', 'highway', 'also', 'transportpolitical', 'economy', 'industrial', 'infrastructure'], ['hydrogen', 'hydrogenics', 'phoenix', 'available', 'arizona', 'station', 'publicly', '2018', 'air', 'located', 'one', 'network'], ['production', 'distribution', 'produced', "world's", 'hydrogen', 'march', 'transport', 'industrial', 'supply'], ['supply', "florida's", 'infrastructure', 'economy', 'produced', 'hydrogen', 'non-public', 'costs', 'suppliers', 'pre-requisite']]
TOP TOKENS [[], ['metric'], ['adopt', 'metrication', 'metric', "britain's", 'opposed'], ['metrication', 'metric', 'full', 'foreign', "britain's"], ['metrication', 'metric', 'full', 'foreign', 'adopting'], ['metric', 'things', 'units'], ['metric', 'time', 'weights'], ['nation', 'metrication', 'become', 'metric'], ['metrication', 'metric', 'system', 'u', 'example'], ['metricating', 'metric', 'units', 'metrication', 'ones', 'wholly', 'brexit', 'anti', 'ounces', 'began', 'ever'], ['metric', 'imperial', 'metrication', "stone's", 'answers'], ['metrication', 'metric', 'official', "country's", 'conversion', 'officially', 'odometers'], ['metrication', 'metric', 'cls', 'measurement'], ['metrication', 'metric', 'metricated', 'measurements'], ['metrication', 'metricated', 'metric', 'metricating', 'beer'], ['metrication', 'entirely', 'metric', 'use', 'metricated', 'measurements', 'wholly', "ukma's", 'led'], ['metrication', 'metric', 'measurement', 'colloquial', 'odometers', 'became', 'cls', 'imperial', 'system', 'speedometers', 'measure'], ['metrication', 'metric', 'adopt', 'diameters', 'mm', 'measurements', 'measurement', '50', "hoses'are", 'meter', '×'], ['metrication', '82'], ['metrication', 'metric', 'customary']]
TOP TOKENS [['fodmaps', 'fodmap', '’'], ['fodmap', 'fodmaps', 'term', 'i.e'], ['fodmap'], ['fodmaps', 'fodmap', 'monosaccharides', 'carbohydrates', 'others', 'rye', 'spelt'], ['fodmap', 'fodmaps', 'plant-based', 'soybeans', 'sugars'], ['fodmap-friendly', 'fodmap', 'fodmaps', 'even', 'enjoy', 'mannitol', 'single', 'fopmap'], ['fodmaps', 'fodmap', 'fodma', 'contain', 'inulin'], ['fodmaps', 'fodmap', 'scientifically', 'poor', 'low'], ['fodmap', 'fodmaps', 'disaccharides'], ['fodmap', 'fodmaps', 'get', 'unabsorbed', 'constipation'], ['fodmap', 'fodmaps', 'low', 'although', 'ibs'], ['fodmaps', 'fodmap', 'although', 'cls', 'intestine', 'artificially', 'avert', 'monosaccharides'], ['fodmap', 'fodmaps', 'help'], ['fodmaps', 'fodmap', 'cashews', 'silken', 'molecule', 'free'], ['fodmaps', 'fodmap', 'low', 'although'], ['fodmap', 'fodmaps', 'galactooligosaccharides', 'silken', 'barley', 'moderate'], ['fodmap', 'fodmaps', 'low', "crohn's", 'gluten', 'favism', 'blinded', 'consequent', 'cancer', 'diagnosis'], ['fodmaps', 'fodmap'], ['fodmap', 'fodmaps', 'directions', 'colon', 'low', 'although', 'needed', 'research'], ['fodor', "fodor's", 'gábor', 'lemma', 'travel', 'staff', 'american']]

Processing features:   3%|▎         | 3/98 [01:25<45:10, 28.53s/it]

getting sample prompt for 23436
getting sample prompt for 23437
getting sample prompt for 23438
getting sample prompt for 23439
getting sample prompt for 23440
getting sample prompt for 23441
getting sample prompt for 23442
getting sample prompt for 23443
getting sample prompt for 23444
getting sample prompt for 23445
getting sample prompt for 23446
getting sample prompt for 23447
TOP TOKENS [['ecology'], ['ecology'], ['ecology', 'ecologythe', 'ecologyvery', 'ecological', 'nature'], ['ecology'], ['ecology'], ['ecology'], ['ecology', 'paleoecology', 'study', 'macroecology', 'ecological'], ['ecology', 'cls'], ['ecology'], ['ecology', 'cls', 'internet', 'ecological'], ['ecology'], ['ecology'], ['ecology'], ['ecology', 'field'], ['ecology'], ['ecology'], ['ecology', "ecology's", 'science', 'ecological'], ['ecology'], ['ecology'], ['ecology', 'science', 'epidemiology', 'researchers', 'economics']]
TOP TOKENS [[], ['offers'], ['files'], ['unk', 'аbоut', 'оnlу', 'рrоduсtіоn', 'bоdу', 'whаt', 'оut', 'уоu', 'mоmеnt', 'аt', 'еxреrіеnсіng', 'рrеvеntаtіvе'], ['stasi'], [], [], [], [], [], ['400,000', 'expatriates', 'victims', 'subscribed', 'month'], [], ['disease', 'playing', 'actors'], [], [], [], [], [], ['share'], ['born']]
TOP TOKENS [['mannitol', 'bleeding', 'edema', 'therefore', 'convulsions', '1', 'period', 'hyponatremia', 'cases', '3', 'provided', 'thrombophlebitis', 'hyperkalemia', 'dizziness', 'myasthenia'], ['manna', 'mannitol', '169°celsius', 'conclusion', 'remains', 'getting', 'filtration', 'e', 'gum', 'deeper', 'via', 'synthesis', 'chemicals', 'appropriate', 'simplifying', 'whenever', 'yes', 'worry'], ['manna', 'every', 'comes', 'gratify', 'provided', 'alone'], ['manna', 'raw', 'canaan', 'bible', 'narrative', 'mann', 'گزانگبین', 'prior'], ['manna', 'heaven', '’', 'exodus', 'whole', '‘', '16', 'israel'], ['mannitol', 'failure', '1131', 'l', 'introduction', 'immediately', 'cls'], ['manna', "the'manna'which", '11', 'cakes', 'baked', 'color', 'fine', 'raw', 'bible', 'sun', 'overnight', 'resulting'], ['mannitol', 'vitamins', 'formation', 'feel', 'actives', 'fructose', 'sugars', 'form', 'sucrose', 'makes', 'mouth-feel', 'inertness'], ['d-mannose', 'mannose'], ['manna', 'action', 'concerning', 'context', 'gradually', 'expectorant', 'extension', 'medicinal'], ['manna', 'exodus', 'war', 'mannaz', 'world', 'mannaeans', 'animals'], ['manni'], ['mannan', 'gazipur', '1956–2020', '1948', 'abdul', 'polysaccharide', 'nationalist', '1930–1990', 'director'], ['manni'], ['mannone', '1942', 'mannan', 'mannen', 'mannon'], ['manna', 'mannah'], ['mannō', 'manno'], ['mannia', 'frib'], ['manna'], ['manni']]
TOP TOKENS [['said'], ['said'], ['said'], ['said', 'asked', 'answered'], ['went', 'says', 'got'], ['asked', 'told', 'wants', 'got', 'hurried', 'said'], ['said', '“', 'went', '”', 'moneylender', 'please', 'oh'], ['said', '“', 'moment', 'hiccuped'], ['said', 'continued', 'answered', 'replied'], ['said', 'replied', 'presently'], ['said', 'happily', 'wow', 'replied', 'went', 'thought'], ['said', 'asked', 'replied', 'told', 'piteously', 'went'], ['responds', 'obliges', 'next', 'assures', 'soon', 'decides'], ['replied', '“', 'said', 'asked', 'hissed', 'went', 'ran', 'tell', 'door', 'snapped', 'really', 'demanded'], ['ordering', 'asks', 'accuses', 'tells', 'said', 'says', 'calling', 'brings', 'purse', 'saying', 'monk', 'answers', 'orders'], ['“', 'well', 'said', 'replied', '”', 'oh', 'trouble', 'sir', 'sure', 'agitation'], ['demanded', 'said', 'replied', 'well', 'sorry', 'man', 'live', 'window', 'answered'], ['replied', 'asked', 'said', 'yes', 'told'], ['turns', 'telling', 'happens', 'employee', 'suddenly'], ['asked', 'said', 'replied', 'found', 'breath', 'relented', 'went']]
TOP TOKENS [['get', 'difficult', '•', 'powerful', 'give', 'allows', 'achievable'], ['respectively', 'always', 'depending', 'since', 'give', 'indicate', 'idea', 'reason'], ['first', 'like', '4', '8', 'one', '2', '1'], ['like', 'attacks', 'lot', 'idea', 'means', 'explain', 'cantabile', 'found', 'also', 'explained'], ['total', 'foci', 'free', 'distance', 'also'], ['vulnerabilities', 'possesses', 'iii-4', 'advance', 'references', 'depend', 'upon', 'type', 'effect', 'respective', 'delete', 'effectiveness', 'discusses', 'first', 'iii-6', 'rest'], ['intensities'], ['effect', '‘heaven', 'describe', 'times', 'every', 'moreover', '‘where’'], ['effect', '‘heaven', 'describe', 'times', 'every', 'moreover', '‘where’'], ['three', 'first', 'several', '1/16', '1/4', 'also', 'two', 'means', '1/2', 'imagine', 'could', 'didn’t', '1', '1/32', 'really', '1/8', 'right', 'something', 'mean', 'whole', 'rectangle', 'one', 'quite', 'inferred', 'it’s', 'totally'], ['show', 'due', 'could', 'screen', 'time', 'also', 'inclusion', 'much', "game's", 'one', 'featuring', 'long', 'took', 'allowing', 'would', "3ds's", 'go', 'meant', "sakurai's", 'came', 'opened'], ['also', 'involving', 'likely', 'depending', 'may', 'present'], ['refer', 'also', 'disambiguation', 'refers', 'may', 'generally', 'various', 'independence', 'nation', 'cls', 'album', 'number', 'music', 'connectedness'], ['resilience', 'disambiguation', 'one'], ['case', 'well', 'e', 'means', "dermatologist's", "jackson's", 'get', "been'exquisitely", 'affected', 'one', 'would', 'shortly', 'many', 'confirm', 'however', 'occurs', 'mid', '1980s', 'also', 'refute', 'areas', 'states'], ['first', 'one', 'outscored', 'south', 'two', 'success', '–', 'years', 'carolina', '16', 'also', 'large', '5', "georgia's", 'onside', 'state', '1904', 'season', 'see', 'team'], [], ['terms', 'directly', 'always', 'including', 'regard', 'either', 'differ', 'pluractionality', 'never', 'ungrammatical', 'predicates', 'verb', 'prepositions', 'consist'], ['refer', 'features', 'surrounding', 'brig', 'rapids', 'service', 'iowa', 'disambiguation', 'fc', 'county', 'romanian', 'cuyahoga', 'south', 'states', 'tributary', 'rapid(s', 'san', 'rapid', 'brought', 'deployment', 'today', 'would', 'wien', 'partnership', 'also', 'several'], ['also', 'terms', 'lists', 'placed', 'either']]
TOP TOKENS [['chatham', 'communities—chatham', 'chathams', 'day'], ['chatham'], ['chatham', "chatham's", "40'17"], ['chatham', 'chathams', 'electorates', 'island', 'christchurch', 'pitt', 'islands'], ['chatham'], ['chatham'], ['chatham', 'chathams'], ['chatham', 'earl', 'state', '591', 'sachem'], ['chatham', 'earl', 'state', '591', 'sachem'], ['chatham', "chatham's", 'center', '1712'], ['chatham', 'east'], ['chatham', 'city'], ['chatham'], ['chatham', 'town'], ['chatham', 'u'], ['chatham'], ['chatham', 'states'], ['chatham', '1986'], ['chatham', 'ghent', 'farmhouse', '12', 'households', 'shows', 'asian'], ['chatham', 'chatham-kent']]
TOP TOKENS [['usenet', '1992', 'could', 'somewhat', 'https'], ['usenet', 'ways', 'person', 'represents', 'happen', '—', 'specific', '’', 'posting'], ['usenet', 'reason'], ['usenet', 'primarily', 'data'], ['usenet', 'appropriate', 'appearing'], ['usenet', 'none', 'enough', 'usenets', 'combination', 'provided', 'day', 'everyone', 'launched'], ['usenix', 'usenet', '1980', 'commonly', 'anyone', 'another', 'may', 'one', 'needing', 'server', 'sequentially', 'newsgroups', 'administrator', 'affordable', 'via'], ['usenet', 'university', 'although', 'posts', 'propagating', 'feed'], ["usepa's", 'usepa', 'posted', 'since', 'may', 'gleaned', 'large'], ['usenix', 'usenet', 'administrator', 'general', 'today', '4', 'commercial', '1980', 'university', 'still', 'links', 'posts'], ['usenet', 'way', 'users', 'usenetexplorer.com', 'posts', 'links'], ['useu'], ['usenet', 'want', 'provider', 'usually', 'one', 'newsgroups', 'may', 'cls', 'threaded', 'local'], ['usenet', 'usenetters', 'influential', 'rec', 'became', 'comp', 'original'], ['usenet', 'posts', 'usefor', 'including', 'newsgroup', 'supernews', 'administrators', 'service', 'based'], ['usenet', 'web-based', 'dating', 'normally'], ['usens', 'announced', 'physics', 'backers', 'smartphones', '2017', 'reality', 'iresearch', 'earned', 'china', 'need', 'inc', 'human–computer'], ['continued', '23', 'led', 'december', 'back', '14', 'went', 'usenko', 'defeat', 'sidelined', 'considerable', 'armed', 'men'], ["useni's", 'inec', 'useni', 'ran', 'appealed', '813', 'elections', 'challenged', 'led', '582', '595', "people's", 'halima'], ['usea']]
TOP TOKENS [['ways', 'degrees', 'paper', 'opposed', 'waived', 'dissertation', 'arguments', 'strong', 'first', 'second', 'field', 'sense', 'form', 'professionalism', 'typical'], ['reader', 'cues', 'place', 'paper', 'effective', 'purpose', 'twenties', 'thesis', 'qualifies', 'subject'], ['directly', 'women', 'objectives', 'original', 'thesis', 'ideas', 'two', 'question', 'tangents', 'childhood', 'bloodbath', 'early', 'second', 'arguable', 'loosely'], ['regardless', 'rebuttal', 'stand', 'willing', 'important', 'illness', 'idea', 'thees-eez', 'specific', 'ago', 'connect'], ['facts', 'disagree', 'everything', 'asserts', 'dearly', 'leads', 'adequately', 'present', 'strong', 'must', 'likely', 'continue', '“', 'information', 'essential', '•'], ['bliss', 'presentation', 'beginning', 'existence', 'interesting', 'informative', 'thesis', 'good', 'strong', 'expectation', 'reader'], ['help', 'skills', 'community', 'deadline', 'scholarship', 'statement', 'research', 'prove', 'thesis', 'knowledge', 'peculiarities', 'believe', 'numerous', 'form', 'successfully', 'work', 'sure', 'particular'], ['thesis', 'others', 'field', 'proved', 'student', 'stand', 'great', 'disagree', 'discipline', 'regardless', 'proposition'], ['reader', 'degree', 'dissertations', 'previous', 'list', 'thesis', 'implies', 'successful', 'courseworks', 'though', '’', 'overcome', 'basic'], ['income', 'thesis', 'important'], ['essay', 'put', 'hypothesis', 'antithesis', 'typeface', 'dissertation', 'album', 'measure', 'body', 'tithemi', 'dialectic', 'τίθημι', 'guiffre', 'thesis'], ['opinion', 'dissertations', 'english', 'contradiction', 'required', 'course', 'vary', 'true', 'reverse', 'degree', 'thesis', "a'thesis'is", 'within', 'forth'], ['bodies', 'germany', 'eurodoc'], ['manuscripts', 'essays', 'thesis', 'medical', 'monograph', 'another', 'chapters', 'essay', 'funding', 'known', 'chosen', 'intends', 'e'], ['countries', 'publication', 'process', 'members', 'rationale', 'want', 'thesis', 'part', 'consultation', 'voce', 'dissertation', 'multimodal'], ['4:44', '4:37', '2:44', "giuffre's", 'sonic', "that's", 'said', '0:44', '3', 'remastered', 'jenkins', '4:54', 'august', 'unissued'], ['prove', 'piece', 'first', 'purpose', 'types', 'structure', 'claim', 'reasons', 'evidence', 'rationales', 'culler', 'sentence', 'clubs', 'paper', 'opinion', 'expressed', 'elsewhere', 'indirect'], ['outside', 'award', "bachelor's"], ["huntington's", 'thesis', 'inevitability', "chandler's"], []]
TOP TOKENS [['shock', 'toxic', 'syndrome', 'tts', 'tss'], ['shock', 'toxic', 'syndrome'], ['shock', 'toxic', 'syndrome', 'tss', 'cls'], ['shock', 'toxic', 'syndrome', 'cls'], ['shock', 'toxic', 'syndrome', 'cls', 'tss'], ['shock', 'toxic', 'syndrome', 'cls', 'tss', 'dangerous', '“'], ['shock', 'toxic', 'syndrome'], ['shock', 'syndrome', 'toxic', 'tss', 'away', 'super', 'cls'], ['shock', 'toxic', 'syndrome'], ['shock', 'toxic', 'syndrome'], ['shock', 'toxic', 'syndrome', 'cls', 'tss', 'streptococcal', 'staphylococcus'], ['shock', 'toxic', 'syndrome', 'staphylococcal', 'tss', 'tampons', 'diarrhea', 'hyperemia', 'soles', 'previously', 'normal', 'causes', 'miscarriage', 'oral', 'desquamation', '2011', 'super', '90', 'temperature', 'skin', '2', 'using', 'systolic', '100', 'inflammation'], ['shock', 'toxic', 'syndrome', 'developed', 'cls', 'tss', 'toxin', 'causes', 'tsst', 'characteristics', 'menstruating', 'menstrual'], ['shock', 'toxic', 'syndrome', 'old', 'tss', 'term', 'menstruation', 'cases', 'staphylococcal', 'toxin', 'todd', 'menstruate'], ['shock', 'toxic', 'syndrome', 'l', 'streptococcal', 'tss', 'streptss', 'myalgia', 'e', 'soft', 'bacteria', 'tissue', 'set', 'pouring', 'agar', 'less', 'production', 'monokines'], ['shock', 'toxic', 'syndrome', 'encoding', 'toxin', 'causes', 'tss', 'g', 'time', 'antigen', 'tsst', 'mhc', 'e', 'stss', 'disease', 'storm', 'streptococcal', 'followed', 'molecule', 'chain'], ['shock', 'toxic', 'syndrome', 'staphylococcal', 'tss', 'well', 'year', 'women', '1980s', 'menstruating', 'pus', 'touch', 'due', 'tampon', '2004', 'septic', 'tampons', '000', '100', 'hours', 'allowed'], ['shock', 'syndrome', 'toxic', 'tss'], ['shock', 'toxic'], ['shock', 'toxic', 'syndrome', 'tss', 'myalgia', 'toxin', 'behind', 'menstrual', 'tsst', 'associated', 'mtss', '1980s', 'tampons']]
TOP TOKENS [['consent'], ['consent', 'comfortably', 'permission', 'cls', 'yes', 'imply'], ['consent', 'comes', 'giving'], ['consent', 'consented', 'giving', 'involve', 'forced'], ['consent', 'obtains'], ['consent', 'consent’', '‘consent', 'gives', 'give', 'given', 'perfectly'], ['consent', 'give', 'agreement', 'want'], ['consent', 'give', 'lack', 'involuntarily'], ['consent', 'consenter', 'consenting', 'consented', 'cls', 'corresponding'], ['consented', 'consent', 'consenting', 'constitutes', 'permission'], ['consent', 'another', '2023'], ['consent', 'consensual'], ['consent', 'cls', 'individuals', 'relationships', 'threshold'], ['consent'], ['consent'], ['consents', 'consent', 'consented', 'preferences', 'agreement', 'decisions'], ['consent', 'consents', 'standard', 'due', 'given', 'particular'], ['consent', 'consents', "users'consent", 'given', 'implies', 'agreement', 'proves', 'express', 'law', 'plays', 'exists', 'explicit', 'lawful'], ['consent', 'consenting', 'surrounding', 'permission', 'sexual'], ['consent', "of'consent'should", 'given', 'systems', 'purely', 'whether', 'holistically', 'solely', 'determining', 'agreement', 'particularly']]
TOP TOKENS [['hammond'], ['hammond’s', 'hammond', 'clock', 'musician', 'states'], ['hammond', 'hugh', '6'], ['hammond', 'john', 'william'], ['hammond', "hammond's", 'hammonds', 'jane'], ['hammond', "hammond's", 'vicksburg', 'sun', 'ear'], ['hammond', "hammond's", 'vicksburg', 'sun', 'ear'], ['hammond', "hammond's", 'fashion', '1910', 'child', 'forgotten', 'ironically', 'ocean', 'millionaire', 'crewmates', 'got'], ['hammond||metropolitan', 'hammond', 'e', 'images', 'hispanic'], ['hammond', 'hammonds', 'window', 'unlike', 'breeze', 'instead', 'distinct', '–', 'simply', 'two', '’', '”'], ['hammond', 'disambiguation', 'hammonds'], ['hammond'], ['hammond', 'canucks', 'season', '1992', 'seasons', 'points'], ['hammond'], ['hammond', 'system', 'century'], ['hammond', "hammond's", 'nine', 'brighton'], ['hammonds', "hammonds'older", 'leagues', 'san', 'major', 'development', 'national', 'injury', 'negotiations'], ['hammond', '1989', 'also', 'death'], ['hammond', 'episodes', 'bolton', 'worked', '’', 'juliet'], ['hammond']]
TOP TOKENS [['donation', 'transplant', 'transplantation', 'organ', 'donors', 'u.s'], ['transplant', 'transplants', 'organ', 'donation'], ['transplant', 'organ', 'transplants', 'donor', '000', 'transplantation', '’', 'donation'], ['transplant', 'transplants', 'organ', 'donation', 'donor', 'donors'], ['transplant', 'transplants', 'organ', 'donation', 'donor', 'donors'], ['transplant', 'organ', 'donation'], ['transplants', 'transplant', 'organ', 'donation', 'transplantation'], ['transplantation', 'organ', 'donation', 'transplant', 'donor'], ['transplant', 'transplants', 'transplantation', 'organ', 'donation', 'donor'], ['transplant', 'transplantation', 'donor', 'organ', 'transplants', 'donation', 'transplanted', 'transplantable'], ['transplant', 'organ', 'transplantation', 'donation', 'donor'], ['transplant', 'donation', 'organ', 'transplantation'], ['transplantation', 'organ', 'transplant', 'transplants', '000', 'donation', '33', 'list', 'donors'], ['transplant', 'transplantation', 'organ', 'donation'], ['transplantation', 'transplants', 'transplant', 'organ', 'donation', 'donor', "uk's", 'recipients', 'organs'], ['donation', 'transplantation', 'organ', 'transplant'], ['organ', 'transplantation', 'transplanting', 'donation', 'transplant', 'donors', 'harvesting'], ['transplantation', 'organ', 'transplant', 'transplanting', 'transplants', 'donation'], ['organ', 'transplant', 'transplants', 'american', 'player', 'born', 'actor'], ['transplant', 'organ']]

Processing features:   4%|▍         | 4/98 [01:52<43:45, 27.93s/it]

getting sample prompt forgetting sample prompt for 23449
 23448
getting sample prompt for 23450
getting sample prompt for 23451
getting sample prompt for 23452
getting sample prompt for 23453
getting sample prompt for 23454
getting sample prompt for 23455
getting sample prompt for 23456
getting sample prompt for 23457
getting sample prompt for 23458
getting sample prompt for 23459
TOP TOKENS [['wangari', 'communities', '2004', '1977'], ['wangari', '’', 'prof'], ['wangari', 'world’', 'wangari’s', 'maathai', 'regime', 'international', 'kenya', 'exacerbated', 'inseparable', '‘tame’', 'using', 'first', 'sayers’'], ['wangari', '2005', '’', 'things', 'quotes', 'ok', 'maathai'], ['wangari', 'run', 'put', 'became', 'maathai', 'ill'], ['wangari', 'bringing', '’'], ['wangari', 'issues', 'water', 'poverty', 'maathai', 'development', 'maathai”', 'soil', 'central'], ['wangari'], ['wangari', 'maathai', '7', '6', '10', '1943', 'two', 'nyeri', 'see'], ['wangari'], [], [], [], ['wangari', 'maathai'], [], ['wanga'], ['disambiguation', 'togo'], ['wangen-brüttisellen', 'zh', 'wangen'], ['birgitta'], ['isewangan', 'ise', 'wangan', 'wannigan']]
TOP TOKENS [['ddclient', 'dde', 'free', 'stands', 'common'], ['ddd', 'tight', 'however', 'solution', 'hard', 'great', 'domain', 'relatively'], ['ddp', 'dissemination', 'raw', 'datasets', 'resources', 'giving', 'introduction', 'changer', 'various'], ['dde', 'uses', 'unspecified', 'play'], ['ddl', '200', 'full', 'database', 'example', 'datatype2', 'form'], ['dde', 'ddeml'], ['ddefile', 'dde23', 'ddes', 'dde', 'use', 'ylag1', 'specifically'], ['ddgs', 'moisture'], ['ddl'], ['ddl'], ['ddp', '1918–1930', 'ddp-316', 'ddp-716', 'partners', 'plans', 'guests', 'non-profit', 'party', 'dodonpachi', 'political', '2005–2009', 'ddp-116', '1997', 'ddp-516', 'querying', 'whose', 'design', 'former', 'plaza', 'systems', 'protein/gene', 'video', 'deutsche'], ['ddps', 'de'], ['ddpp', 'consortium'], ['ddm', 'iso', 'town', 'greek', 'steam', 'monsters', 'motor', 'deutsches', 'membrane'], ['networks', 'ddn', 'digital', 'news'], ['ddl', 'compression', 'drop-down', 'digital', 'link'], ['zh:ddk', 'ddk', 'navy', 'dennis'], ['“ddf”', 'ddf', 'n,n-dimethyl-amino)-benzenediazonium-fluoroborate', 'free', "4,4'-dinitro-3,3'-diazenofuroxan", 'terminates', 'fund'], ['ddd', 'ddx', 'chemistry', 'd/dx'], ['ddw', 'iso']]
TOP TOKENS [['limit'], ['limits', 'limit', 'greisen', 'direct'], ['limits', "using'limits", '“', 'beyond', 'mentioned', '”'], ['limit', 'price(redirected', 'price', 'prices'], ['limit', 'beyond', 'ascertaining', 'history', 'within', 'maximum'], ['limit', 'limits.h', 'límits', 'limits'], ['limits', 'limit', 'greisen', 'direct'], ['limit', 'limits', 'central'], ['limits', 'limit', 'using', 'restricted'], ['limit', 'limits'], ['limit', 'limitations', 'also', 'limitation'], ['limits', 'limit', 'first', 'value'], ['limit', 'limits', 'limitations', 'limiting', 'requirement', 'refer', 'bdsm', 'terminology', 'set'], ['limitstate:geo', 'limitstate:slab', 'limit', 'limits'], ['limit', 'price'], ['limit', 'límite'], ['limiting', 'limit'], ['over-the-limit', 'limit', 'based', 'credit'], ['limit'], ['limit', 'limiting', 'mathematics', 'two']]
TOP TOKENS [['“lincoln”', 'lincolnposted', 'lincoln’s', 'lincoln', 'abraham', 'centuries', 'untended', '1860', 'president'], ['“lincoln”', 'lincolnposted', 'lincoln’s', 'lincoln', 'abraham', 'centuries', 'untended', '1860', 'president'], ['edition/lincoln', 'lincoln', 'abraham', '3'], ['lincoln', 'abraham', 'melancholy', 'unknown', 'friday'], ['lincoln', 'abraham', 'room', 'judge', 'line', 'solved'], ['lincoln', 'notes', 'best', 'denominational', 'mrs', 'sep', 'departed', 'dream', 'religious', 'governance', 'day', 'writer', 'words'], ['lincoln', 'unveiled', 'growth', 'lincolnshire', 'due', '50ad', '1840'], ['lincoln', 'lincoln’s', '“lincoln', 'abraham', 'pontiac-ford'], ['lincoln', 'abraham', 'milk', 'generals', 'casserole'], ['lincoln', 'abraham', '1954', 'ed', 'repr'], ['lincoln', '1953'], ['lincoln', 'area'], ['lincoln', 'also'], ['lincoln'], ["lincoln's", 'lincoln', '18-hole'], ['lincoln', 'simply', 'links', 'external', 'says'], ['lincoln', 'companies', 'manufacturing'], ['lincoln', 'jr'], ['lincoln', "lincoln's", 'controversy', '2000', 'addition'], ['lincoln', '1876', 'township', '285']]
TOP TOKENS [['penicillin', 'doctors'], ['penicillin', 'penicillins', 'penicillium', 'body'], ['penicillin', 'sickness'], ['penicillin', 'penicillins', 'penicillium', 'ampicillin', 'amoxicillin', 'phenoxymethylpenicillin'], ['penicillin', 'penicillins', 'penicillium', 'ampicillin', 'amoxicillin', 'phenoxymethylpenicillin'], ['penicillin'], ['penicillin', 'amoxicillin', 'ampicillin'], ['penicillin', 'recorded'], ['penicillin', 'penicillins', 'ampicillin', 'orally', 'respectively'], ['penicillin', 'reactions'], ['penicillin', 'medicines'], ['penicillin', 'anti-aircraft'], ['penicillin', 'penicillus', 'penicillium'], ['penicillin', 'penicillins', 'penicilloyl', 'amoxicillin'], ['penicillins', 'penicillium', 'penicillin', 'almecillin'], ['penicillin'], ['penicillins'], ['penicillins', 'ampicillin', 'penicillin', 'penicilloic', 'pivampicillin', 'therefore'], ['penicillin', 'ampicillin', 'penicillins', 'aminopenicillin', 'mouth', 'classifies', 'safe', 'example'], ['penicillin', 'penicillium', '50']]
TOP TOKENS [['sedna', "sedna's", 'cloud', 'although', 'cls', 'expected', "object's", 'sun'], ['sedna', "sedna's", '2010', 'simply'], ['sedna', 'mars', 'favorite', 'conjectured', 'much'], ['sedna', "sedna's", 'places', 'contested', '90377', 'cls', 'currently', '524', '0'], ['sedna', "sedna's", 'takes', 'surface', 'well', 'cls'], ['sedna', "sedna's", 'classifies', 'found'], ['sedna', '2014', 'found'], ['sedna', "sedna's", 'discovered', '6', 'perihelion'], ['sedna', 'classifies', 'although', 'orbit', 'planet', 'epoch', 'one', '12', 'e'], ['sedna', 'color', 'discovery', 'system', 'time'], ['sedna', 'trans-neptunian'], ['sedna', "sedna's", 'aphelion', 'km', 'perihelion', 'cls', 'space'], ['sedna', "sedna's", 'detailing', 'found', 'objects', 'call'], ['sedna', "sedna's", 'object', 'quaoar', 'cerro', 'name', 'discovery', 'digitized', '6'], ['sedna', "sedna's", 'consider', 'designates', 'neighbourhoods', 'detailing', 'classification'], [], ['gadna'], ['500/600', 'single', 'graphics'], ['sedna', 'object', 'differ', 'size', 'positions', 'tenth-most-distant', 'original', '0.04', 'distant', 'several', 'axis', 'hypotheses', 'unlikely', 'closest', "sun's", 'however'], ['sedna', 'legend', 'walruses', 'nerrivik', 'arnapkapfaaluk']]
TOP TOKENS [['hypoglycemic', 'hypoglycemia'], ['hypoglycemia', 'hypoglycemic'], ['hypoglycemia'], ['hypoglycemia'], ['hypoglycemia'], ['hypoglycemia'], ['hypoglycemia', 'hypoglycaemia', 'hypoglycaemia.”'], ['hypoglycemia'], ['hypoglycemia', 'hypoglycemic'], ['hypoglycemia', 'hypoglycemic'], ['hypoglycemia', 'hypoglycemic'], ['hypoglycemia', 'hyperglycemia', 'carbohydrate'], ['hypoglycemia', 'hypoglycemic'], ['hypoglycemia', 'diabetes/hypoglycemia'], ['hypoglycemia', 'hyperglycemia'], ['hypoglycemia'], ['hypoglycemia', 'hypoglycaemia'], ['hypoglycin'], ['hypoglycemia'], ['hypoglycemia']]
TOP TOKENS [['providers', 'provider', 'need', '0', 'yum', 'another', 'takes'], ['provider', 'content', 'providers', 'cls', 'granturipermissions', 'guide', "provider's", 'define', 'identifies'], ['provider', 'content', 'providers', 'cls', 'granturipermissions', 'guide', "provider's", 'define', 'identifies'], ['providers', 'provider', 'find', 'capable', 'medicine', 'normally', 'healthcare', 'finding'], ['provider', 'providers', 'inclusive', 'medical', 'organization', 'healthcare'], ['“provider”', 'provider”', 'term', 'care', 'others', 'entities', 'hospitals'], ['provider', 'providers', 'serve', 'treating', 'hypothetical', 'reasons', 'ensure', 'nature', 'like', 'factor', 'service', '’', 'learning'], ['providers', 'provider', 'retrieved', 'aspects', 'necessary', 'resource', 'resources', 'used', 'return', 'dpkg'], ['provider', 'providers', 'content', 'every', 'using'], ['providers', 'provider', 'change', 'considered', 'healthcare', 'one'], ['provider', 'providers'], ['providers', 'members', "chancellor's", 'london', "guy's", 'nhs'], [], ['provider', 'providers', 'identity', 'provides', 'applications', 'better', 'network', 're-authenticate', 'service', 'associated'], ['providers', 'providerbase', 'approach', 'provider', 'runtime', 'msdn', 'extensible', 'example', 'follow'], ['provider', 'messaging', 'providers', 'providerconnection', 'service'], ['provider', 'providers', 'practice', 'secretary', 'rendered', 'institutional', 'care', 'individual', 'healthcare', 'business', 'authorized'], ['providers', 'provider', 'identity', 'service', 'shared', 'recognized', 'management', 'third-party'], ['provider', 'mix', 'radio', 'loop', 'head'], ['providers', 'vs', 'moreover', 'form', 'germany', 'website', 'majid', 'weeks', 'tracklisten', 'velkommen', 'mig']]
TOP TOKENS [['bezoars', 'bezoar', 'trichobezoars'], ['bezoars', 'bezoar', 'phytobezoar', 'trichobezoars', 'trichobezoar', 'phytobezoars', 'lithobezoar', 'lactobezoar', 'counterpoison', 'urge', 'bezehr', "one's", 'specificity'], ['bezoars', 'fibrous'], ['bezoars', 'bezoar', 'phytobezoars', 'trichobezoars', 'pharmacobezoars', 'diospyrobezoars', 'phytobezoar', 'lactobezoars', 'phytobozoars', 'cellulose'], ['bezoars', 'bezoar', 'phytobezoars', 'trichobezoars', 'pharmacobezoars', 'diospyrobezoars', 'phytobezoar', 'lactobezoars', 'phytobozoars', 'cellulose'], ['bezoars', 'bezoar', 'trichobezoars', 'phytobezoar', 'lactobezoars', 'gastric', 'following', 'people', 'underdeveloped', 'form', 'unexplained', 'reduction'], ['bezoars', 'pharmacobezoars', 'trichobezoars', 'phytobezoar', 'lactobezoars', '‘', 'cellulose', 'celery', 'either', 'raisins'], ['bezoars', 'bezoar', 'trichobezoar', 'phytobezoar', 'pharmacobezoar', 'lactobezoar', 'diospyrobezoar', 'cellulose', 'special', '3'], ['bezoar', 'bezoars', 'trichobezoar', 'pharmacobezoar', 'phytobezoar', 'lactobezoar', 'special', 'pharmacopeias', '3', 'e', 'gastric', 'cellulose', 'kind', 'g'], ['bezoar', 'bezoars', 'trichobezoar', 'pharmacobezoar', 'phytobezoar', 'lactobezoar', 'special', 'pharmacopeias', '3', 'e', 'gastric', 'cellulose', 'kind', 'g'], ['bezoar', 'bezoars', 'phytobezoars', 'pharmacobezoars', 'trichobezoar', 'lactobezoars', 'phytobezoar', 'pseudobezoar', 'diospyrobezoar', 'tracheobezoar', 'cellulose', 'semiliquid'], ['bezoars', 'bezoar', 'esophageal'], ['bezoar', 'bezoars', 'diospyrobezoar', 'phytobezoar', 'phytobezoars', 'diospyrobezoars', 'polymerizes', 'stomach', 'cellulose', 'coagulative', 'fibres'], ['bezoar', 'bezoars', 'phytobezoars', 'diospyrobezoars', 'phytobezoar', 'generally', '84', 'hemicellulose', '90', 'less', '6'], ['flexagon', 'flexagons', 'constructed', 'binder', 'flexed', 'cut', 'hexagonal', 'transformed', 'flexing', 'pinches', 'committee', 'trihexaflexagon', 'display', 'formed', 'hexahexaflexagon', 'ways', 'example', 'would', 'front', 'hexaflexagon', 'geometry', 'hexaflexagons', 'began', 'one', 'including'], ['1928', 'hazo', 'town', '1966', 'minor', 'born'], ['bezoar', 'bezoardicum', 'gentle', 'powdered', 'insipid'], ['bezoar', 'bezoars', 'phytobezoars', 'bezoardicum', '90', 'component', 'others', 'fj', '3', 'collections', 'removal', 'mainly'], ['tozo', 'wrestler'], ['gazo', 'sistan', 'iran', '1230–1294', 'nicaraguan', 'literary', '1992', 'treasure', 'also', 'born', 'contains', 'disambiguation', 'village']]
TOP TOKENS [['stewardship', 'stewards', 'steward', 'another', 'changed', 'us'], ['stewardship', 'cls', 'steward'], ['stewardship', 'steward', 'practice', '–', '“', 'actively', 'heck', 'direction', 'say'], ['stewardship', 'steward', 'steward’s', 'think', 'instead', 'housekeeping'], ['stewardship', 'testament', 'practice', 'hands', 'god', 'embrace', 'word'], ['stewardship', 'steward', 'stewards', 'talents', 'owns', 'living', 'fruitful'], ['stewardship', 'stewardships', 'steward'], ['stewardship', '“stewardship”', 'stewards', '“steward”', 'congregation', 'steward', 'faithful', 'care', 'term', 'slave', '4:1-2', 'priorities'], ['stewardship', 'steward', 'responsibly', 'trustees/stewards', 'god', 'practice', 'creator', 'response'], ['stewardship', 'stewards', 'submissive', '“', 'cls', 'steward', '26', 'faithful', 'course'], ['stewardship', 'resources', 'steward', "castle's", 'eticae-stewardship'], ['steward', 'stewardship'], ['stewardship', 'disambiguation', 'steward', 'stewards', 'district', "steward's", 'office', 'elements', 'local'], ['stewardson'], ['steward', 'j'], ['stewardship', 'eternity', 'cls', 'within', 'believers', 'traditions'], ['stewardship', 'steward', 'stewards', 'responsible', 'constitution'], ['steward', 'ernest', 'dean', 'brad', '1946', 'author', 'gould', 'campion', 'executive', 'slave', 'lewis', 'canoer', 'gabriel', 'theophilus', 'business'], ['stewardship', 'stewards', 'steward', 'duties', 'local', 'historically', 'chapel', 'links', "steward's", 'methodism', 'historic'], ['steward', 'stewards', 'steadward', 'vicegerent', 'cls', "lord's", 'keeper', 'corresponding', 'middle', 'high']]
TOP TOKENS [['arts', 'martial', 'kung', 'practiced', 'art'], ['arts'], ['arts', 'martial', 'chinese', 'shaolin'], ['arts', 'martial', 'art', 'kungfu', 'wushu', "sengchou's", 'kung', 'practiced'], ['arts', '“', 'art'], ['arts', 'kungfu', 'martial', 'style', 'characterize', 'art', 'ancestors', 'chinese'], ['art', 'martial', 'styles', 'arts', 'cls', '“', 'techniques'], ['art', 'martial', 'styles', 'arts', 'cls', '“', 'techniques'], ['art', 'martial', 'arts'], ['okinawan', 'arts', 'martial', 'artists', 'art', '“', 'grappling', 'kung'], ['arts', 'martial', 'art', "sengchou's", 'styles'], ['martial', 'art', 'arts', 'practiced', 'kung', 'style', 'artists', 'techniques', 'fu', 'practitioners'], ['arts', 'art'], ['kung', 'arts', 'styles', 'chinese', 'martial', 'shaolin', 'mok', 'wushu'], ['arts', 'martial', 'korea', "japan's", 'chinese', 'shaolin', 'traditions', 'kung', 'lineages', 'japan'], ['arts', 'martial', 'art', 'kung', 'chinese', 'described', 'shaolin'], ['art', 'arts', 'artist', 'martial', 'learned', 'styles', 'unk', 'different'], ['arts', 'kung', 'martial', 'shaolin', 'fu', 'chinese', 'ga'], ['arts', 'martial', 'okinawan', 'kung', 'styles'], ['arts', 'kungfu', 'kung', 'martial', 'styles', 'shaolin']]
TOP TOKENS [['harbor', 'harbors', 'vessels', 'conditions'], ['harbor', 'police', 'boat', 'harbormiddle', 'women', 'harbors', 'anchor', 'esp'], ['harbors', 'harbor', 'harbour', 'cls', 'trincomalee'], ['harbor', 'harbours', 'harbors', 'harbour', 'see', 'stored'], ['harbour', 'harbor', 'harbours'], ['harbor', 'harbour', 'harbors', 'use', 'cls', 'artificial', 'created', 'beach'], ['harbor', 'harborers', 'harboring', 'see', 'harbored', 'harborers.the', 'n', 'herbergen', 'synonyms'], ['harbour', 'beach', 'one', 'important', 'disparate', 'seasons', 'years', 'unfortunately', "that's", 'tribes'], ['harbor', 'safe', 'program', '1111', '24', 'school', '2019', 'grantees'], ['harbor', 'bar', 'interior', 'bart', 'rooms', 'acadia'], ['harbor', 'harbour', 'david', 'nadu'], ['harbor', 'harbor#air', 'harbour', 'ayrshire', 'states', 'folkestone', 'united', 'fishguard', 'los'], ['harbor'], ['harbour', 'harbor'], ['harbor', 'publishing', 'harbour'], ['harbor'], ['harbor'], ['harbor', 'harbour', 'county'], ['harbour'], ['harbor', 'geography']]

Processing features:   5%|▌         | 5/98 [02:19<42:36, 27.49s/it]

getting sample prompt forgetting sample prompt for 23461
getting sample prompt for 23462
 23460
getting sample prompt for 23463
getting sample prompt for 23464
getting sample prompt for 23465
getting sample prompt for 23466
getting sample prompt for 23467
getting sample prompt for 23468
getting sample prompt for 23469
getting sample prompt for 23470
getting sample prompt for 23471
TOP TOKENS [['globe', 'globes', 'using'], ['globe'], ['globe', 'globes', 'meter', 'cls', 'elevation', 'since'], ['globes', 'globe', 'surface'], ['globe', 'globes'], ['globe', 'globes', 'world', 'continents', 'accuracy', 'size'], ['globe', 'globes'], ['globe', 'brass', 'typical', 'years'], ['globe', 'brass', 'typical', 'years'], ['globe', 'globes', 'world', 'size', 'continents', 'accuracy'], ['globe', 'body', 'wisconsin', 'oregon', 'international'], ['globe'], ['globe', 'marion/globe', 'trail', 'built', "town's", 'people', 'maps', 'dwindle'], ['globe', 'states'], ['globe', "globe's", 'blair', 'internationally', 'japanese', '1991', 'africa', 'japan'], ['globe', '2017'], ['globe'], ['globe', 'globes'], ['globe', '2013', '2003', 'brian', '1972'], ['globe', 'globe-democrat']]
TOP TOKENS [['since'], [], [], [], [], [], [], ['damages', 'addition', 'including'], [], [], [], [], ['well'], [], [], [], [], [], ['delivery', 'provides', 'related'], []]
TOP TOKENS [['egan', 'press', 'piatkus'], ['egan', 'survivor', 'messines', 'dardanelles', 'joseph', '1917', 'bade', 'gerald', 'william', 'canterbury', 'private', 'sustained', 'therein'], ['egan', 'educated', 'course', '’', 'impregnable', 'failed', 'golf', '–', '“', '”', 'ended', 'success'], ['egan', "egan's", "egan's'folk", 'egans', 'brainiacom', 'gerard', 'one'], ['egan', '”', 'dimensions', 'ones', '’', 'understanding', 'humor', 'knowledge', 'ergon', 'way', 'reality', 'writes', 'rabbit', 'clothed', '“', 'inflected', 'animal', 'meaning', 'important', '15', 'correlates'], ['egan', 'nevertheless', '’', '”', 'studies', 'classrooms', 'also', 'observes'], ['egan', 'trials', 'states', 'irish', 'balmaceda', 'nebr', 'reform', 'also', 'u.s', 'lincoln', 'davitt', 'strenuously', 'ēˈgən'], ['egan', '1962', 'switchboard', 'conquests', 'willis', '’', 'richard', 'began', 'career', 'northwestern', '1939', 'avenue', 'fr', 'eventually', 'one', 'talent'], ['egan', 'roles', 'community'], ['egan', 'roles', 'community'], ['egan', 'newspaper', 'hides'], ['egan', 'would', 'give', 'j.p'], ['egan', 'america', '12,000', 'hero', 'contributed'], ['egan', '–', 'whitehead', 'lennox', 'dr', 'garven', 'pictures', 'apache', 'johnson', 'cowhand', 'herbie', 'sgt'], ['egan', '1986', 'hamlyn', '1985', 'australian'], ['egan', 'career'], ["egan's", 'egan', 'day', 'season', 'base', '30', 'd.c'], ['egan', 'canadian', 'canada'], ['egan', "egan's", 'entitled', 'nypd', 'detailing', 'career', 'playing'], ['egan', "egan's", 'injuries', 'laced', '1968', 'links', 'external', 'springfield', '–', '1942', 'went']]
TOP TOKENS [['many', 'n', 'number', 'different'], ['many', 'k', 'possible', '32,896', 'combinations'], ['many', 'number', 'different', 'n', 'ways', 'combinations', '4'], ['many', 'number', 'different', '11', '6', 'combinations', 'ways'], ['number', 'possible', 'numbers', 'ways'], ['many', 'different', 'ways'], ['many', 'number', 'different'], ['many', 'number', 'k'], ['n', 'n-1', 'number'], ['n', 'n-1', 'number'], ['n', 'many', 'number', 'combinations', 'xn', 'total'], ['number', 'n', '960', 'k', '598', 'however', 'combinations', 'occurs', '2', '3'], ['n', 'k', 'number', 'combinations', 'permutations', 'combinatorics', 'multiplicity', 'arrangements'], ['number', '12', 'involve', 'n', '24', 'x', 'possible', '3', '4', 'would', 'combinatorics'], ['n', 'subsets', '1', 'number', 'enumerates', 'possible', 'k', 'formally'], ['n', 'number', 'k', '≥', 'combinatorics'], ['many', 'n', 'number', 'permutations', 'contains', 'place', 'k'], ['number', 'arrangements', 'possible', 'combinations', 'total', '2', '25'], ['n', 'number', '12', '1', 'possible', 'arrangements', '−'], ['number', 'n', 'ways', 'combinations']]
TOP TOKENS [['go', "go's", 'goroutines', 'application'], ['go', 'inconsistencies', 'leaks', 'asynchronously'], ['go'], ['go', 'source—go', 'go’s', 'goroutines', 'block', 'gofmt', 'reaching'], ['go', 'early', 'faster', 'cheaper'], ['go', 'golang', 'know', 'using', 'second', 'consequential'], ['go'], ['go', 'golang', 'goimports', 'working'], ['go', 'gomobile', 'around', 'using', 'practice', '–'], ['go'], ['go', 'city', 'previously', 'q&as'], ['go', 'gossaum'], ['go', 'android', 'officially', 'edition'], ['go', 'links', 'external', 'parts', 'references'], ['go', "go's", "c's", 'except', 'syntax', 'though', 'languages', 'via', 'values'], ['go', 'also'], ['go', 'references'], ['go', 'go-u.s.a'], ['go', 'golang', 'goias'], ['go', 'usb-c', 'system', 'links', 'pre-installed', 'external', '6', 'laptops', '3:2', 'select', 'hello', 'surface']]
TOP TOKENS [['glues', 'uvglue'], ['cgp', 'example', '2', '3', 'gives'], ['around'], ['github', 'time', 'using'], ['whole', 'normally', 'earth', 'often', 'time', 'question', '’', 'new', 'like', 'something', 'hassle', 'especially'], ['whole', 'normally', 'earth', 'often', 'time', 'question', '’', 'new', 'like', 'something', 'hassle', 'especially'], ['sure', 'problem', 'time', 'works', 'lot'], ['solidify'], ['whole', 'normally', 'earth', 'often', 'time', 'new', "there's", 'something', 'especially', 'like'], ['existing', 'solution'], [], ['interrelated', 'cohesive'], [], [], [], ['character', 'example', 'used', 'following', 'also', 'particular', 'bold', 'may'], ['another', 'also'], ['moreno', 'stephens', 'gasnter', 'effects', 'stylist', '—'], ['together', 'technologies', 'technology', 'usage', '562', 'interchangeable', 'one', 'durability', 'reconfigure'], ['along', 'changes', 'interferometrically', "the'writing'of", 'fringes', 'moves', "to'write'the"]]
TOP TOKENS [['put', 'resting', 'room', 'time', 'get', 'spring', 'find', 'though', 'list', 'flat', 'right', 'also', 'since', 'tires', 'ride', 'often', 'wagon'], ['several', 'one', 'room', 'appear', 'smoke', 'months', '“', 'heat', 'also', 'airtight', 'suffice', '’', '”', 'box', 'another', 'tunneling', 'fragrance', 'might', 'mishandled', 'candle', 'burning', 'melts', 'corners', 'cover', 'relighting', 'preserved'], ['addition', 'typically', 'unit', 'hours', 'increasingly', 'alternatively', 'becoming', 'disposed', 'fact', 'choice', 'toilets', 'however', 'situations', 'including', 'may', 'making', 'work'], ['like', 'balloons', 'durable', 'factors', 'balloon', 'place', 'possible', 'type', 'days', '’', 'cool'], ['temporarily', 'puddles', 'ground', 'getting', 'puddle', 'hours', 'sort', 'though', 'particularly', 'immediately', 'time'], ['temporary', 'initially', 'arrival', 'w', 'later', 'twin', '1', '911', '1869340418', 'shortly'], ['temporarily', 'puddles', 'ground', 'getting', 'puddle', 'hours', 'though', 'sort', 'immediately', 'even'], ['take', 'often', 'lines', 'placed', 'relatively', 'time', 'toilet', 'tend', 'almost', 'second', 'first', 'course', 'need', 'pump', 'little', 'toilets', 'make', 'finally', 'install', '’', 'big', 'means', 'another', 'friendly', 'including', 'one'], ['quite', 'ferrying', 'way', 'recently', 'cozy', 'made', 'things', 'likely', 'making'], ['put', 'time', 'never', 'taken', 'submerged'], ['temporary', 'housing', 'flat', 'interim', 'public', 'demolished', 'estates'], ['aitulagi', '3-person', 'moved', 'heard', 'operating', 'alava', 'small-market', 'english', 'serves', 'channel', 'olotele', 'near', 'telecast', 'translators', 'called', 'sia', '93khj', 'features', 'samoa', '2017', 'radio', 'miller', 'changed', 'longtime', 'callsign', 'lutu', 'station', '2-person', 'sunrise', 'callsigns', 'rather', 'wvuv-fm', 'mt', 'also', 'k229bg', 'translator'], ['mentioning', 'went', 'volume', 'currently', 'fanbase', 'certainly', 'felt', 'adding', "track's", 'market', "newspaper's", "dubz'sound", 'deemed', 'mention', 'opining', "song's", 'right', 'writing'], ['saved', 'undergo', 'preservation', 'enter', 'condition', 'disrepair', 'converted', 'happens', 'scrapped', 'quite', 'relatively', "bus's", 'larger', 'time', 'change', 'little', 'great', 'either', 'many', 'number', 'form', 'often', 'rescued', 'original', 'additionally', 'specific', 'others', 'cases', 'also', 'even', 'vintage'], ['puddle', 'endemic', 'hong', 'sub-saharan', 'found', 'frog'], ['overlooking', 'surprising', 'overall', 'said', 'deferred', 'intentioned'], ['played', 'entitled', 'venue', 'home', 'first', 'drawn', 'ranked', 'superettan', 'place', 'draw', 'play', 'winners', 'competing', 'took'], ['four', 'formatted', 'kzht', "station's", 'contemporary', '1961-198', '2003', 'klub-am', 'format', '198?-2000', '22', 'station', 'stations', 'six', 'partially', 'opted', 'music', 'least', "quinn's", 'airing', 'home', 'radio', 'one', 'chr', 'december', '2000-2003', 'airstaff', 'iheartmedia', 'frequency'], ['onto', 'several', 'heat', 'two', 'three', 'humor', 'four', 'gave', 'also', 'contained', 'critics', 'already', 'consisting', 'held', '31', 'stating', 'culminated', 'respectively'], ['former', 'princetown', 'victoria', 'caerphilly']]
TOP TOKENS [['content', 'contained', 'contents', 'contain', 'levels', 'concentrations', 'fluoride', 'also', 'found', 'higher', 'high', 'mg'], ['content', 'contained', 'contents', 'contain', 'levels', 'concentrations', 'fluoride', 'also', 'found', 'higher', 'high', 'mg'], ['content', 'concentrations', 'contained', 'levels', 'mg', 'contains', 'present', 'per', 'found', 'possess', 'higher', 'amounts'], ['contained', 'much', 'per', 'found', 'also', 'caffeine'], ['content', 'contain', 'levels', 'amount', 'contains', 'may', 'roughly', 'much', 'iodine', 'traces', 'vary'], ['contents', 'concentration', 'content', 'levels', 'presence', 'detected', 'amounts', 'carotenoid', 'variation', 'lower'], ['content', 'high', 'varies', 'times', 'iodine', 'µg', 'averaged', '3.1', 'machines—the', 'low'], ['“contains”', 'contained', 'contains', 'return'], ['contents', 'content', 'containing', 'contained', 'levels', 'less', 'value', 'caffeine', 'mg', 'different', 'analyzed'], ['content', 'contain', 'levels', 'contains', 'found', 'containing', 'mg', 'much'], ['concentrations', 'contain', 'contained', 'detected', 'levels', 'found', 'amounts', 'maximum', 'trace'], ['contains', 'usually', 'mg', '130', '–'], ['contain', 'contained', 'content', 'containing', 'levels', 'level', 'per', 'testing', 'amount', 'cadmium', 'found'], ['concentration', '0', '0009', 'detection'], ['contains', 'concentration', 'contain', 'amount', 'mg', 'nicotine', '0', '6', '–', 'strengths'], ['levels', 'concentrations', 'concentration', 'contain', 'contained', 'found', 'content', 'amounts', 'variable', 'filled', 'contents', 'denote', 'low', 'quantities', "as'no", 'including', 'greater', 'nicotine'], ['contained', '32', 'amounts', 'found', 'impurity', 'levels', 'diphenylamine', '0', 'purified', 'presence', 'samples', '91071', 'one', 'whose', 'hydroxyl', "epa's"], ['content', 'respectively', 'amounts'], ['concentrations', 'amounts', 'found', 'levels', 'differing', 'contain', 'normally', 'lesser', 'quantities', 'lower', 'solvents', 'traces'], ['contain', 'found', 'containing', 'contained', 'amounts', 'levels', 'amount', 'composition', 'trace', 'identified', 'seem', 'less', 'methylglyoxal', 'lower', 'chemical', 'vapor']]
TOP TOKENS [['islamic'], ['islamic'], ['islamic', 'notes'], ['islamic', 'notes'], ['islamic'], ['islamic'], ['islamic'], ['islamic', '‘'], ['islamic', 'oic'], ['islamic', 'cls', 'unsuccessful'], ['islamic', 'ones', '–', 'fund'], ['islamic'], ['islamic', 'setters'], ['islamic', 'rotterdam'], ['islamic', 'financial', 'direction'], ['islamic'], ['islamic'], ['islamic', 'government', 'nordic', 'muslim'], ['islamic', 'sufficient', 'banks'], ['islamic', 'cls', 'although', 'banking']]
TOP TOKENS [['nation’s', 'space', 'national', 'union'], ['program', 'space', 'privatizing', 'privatized'], ['national', 'space', 'program', 'activities'], ['program', 'space', "world's", 'manned'], ['spaceflight', 'space', 'program'], ['space', "america's", 'program', 'agenda'], ['program', 'spaceflight'], ['space', 'national', 'companies'], [], ['program', 'space', 'national', 'activities'], ['space', 'spaceflight', 'national'], ['national', 'space', 'program', 'constituted'], [], ['space', 'program'], ['national', "russia's"], ["india's", 'space', 'program', 'programs', 'federal', 'budget'], ["china's", 'space', 'program', 'programs', 'race', 'agendas', 'uk', "britain's", 'sector', 'soviet', 'government'], ['national', 'space', "australia's", 'agency'], ['program', 'space', "turkey's", 'programs', 'agency'], ['space', "kingdom's", 'agency', 'civil', 'authority', 'uk']]
TOP TOKENS [['want', 'shared', 'even', 'relaying', 'thing', 'case'], ['always', 'it’s', 'documents', 'formatting”', 'file', 'advanced', 'isn’t', 'cases', 'would', 'says', 'example', '“pasting', 'want', 'don’t', 'conflicts', 'also', 'however', 'tells'], ['pantone', 'represent', 'official', 'communications', 'render', 'materials', 'never', 'especially', 'maroon', 'blue', 'historic', 'university'], ['still', "late'90s", 'bios', 'ancestral', 'direction'], ['past', '’', 'much', 'made', '—', 'songs', 'dances', 'identity', 'cuisine', 'cultural', 'deeds', 'family', 'thus', 'could', 'activities', 'lucinekasbarian', 'annihilation', 'memory', 'yet', 'treasures', 'belonging', 'crafts'], ['default', 'href', '6', 'style', 'browsers', 'emulate', 'otherwise', 'css', 'per', 'validator', '’', 'attempts', 'outputting', '“', 'w3'], ['’', 'undercoats', 'recessive', 'fluffiness', 'length', 'thickness', 'short', 'also', 'years', 'preen', 'sphynx', 'weaker', 'breeds'], ['would', '’', 'dacey', 'day', '”', 'always', 'instance', 'often', 'long', 'like', 'also'], ['’', 'often', 'time', 'gouache'], ['u.s', 'heraldic', 'past', 'em·bla·zon·ing', "heroine's", 'resplendent'], ['horses', 'animals', 'symphonic', 'band', 'land', 'falcons', 'matter', "listener's", 'subject', 'queens', 'templars', 'rigid', 'also', 'tho', 'kings', 'strangling', 'time', 'conviction', 'us', 'a−', 'enough', 'conversation'], ['never', 'feathered', 'always', 'uxmal', 'otherwise', 'tchitchin', 'ethnic', 'version', 'aztec', 'dmsguild', 'archaeology', 'thing', 'racial', 'time', 'commonplace', 'strive', "mexico's"], ['americans', "clannad's", 'unwieldy', 'non-stop', 'story', '1845/46', 'generally', "mccann's", 'intertwined', "novel's", 'also', 'lyrical', "douglass's", 'well', 'transatlantic'], ['band', "beatport's", 'dirtyphonics', 'nero', "group's", 'year', 'us', "act's", 'europe', 'fluke', 'borgore', 'also', 'aptly'], ['would'], ["team's", '27', 'club', '25', 'game', 'however', 'basketball', "gods'88", 'basket', 'nation', '2', '29', 'also', '3'], ['right'], ['later', 'year', 'soaks', 'actual', 'several', 'office', 'also', 'principal', "broccoli's", 'buckinghamshire', 'usual', 'studios', 'however', 'expressed', 'eastwards', "script's"], ['newsweek', 'africa', 'famously', 'published', 'mid', '2007', 'color', 'region'], ['music', 'parlophone']]
TOP TOKENS [['amount'], ['inflows', 'amounts', 'really', 'things', 'water'], ['–', 'acre'], ['–', 'acre'], ['lows', 'shorelines', 'amount', 'snowpack', 'water', 'farmlands'], ['amount', 'evaporates', 'water'], ['water', 'amount', 'levels', 'dramatically', 'allotment', 'due', 'river', '7'], ['lake', 'powell', '‘', 'water', 'acre', '“', '’'], ['much', 'water', 'dearth', "reservoir's", 'flows', 'dwindling', 'river', '1', 'according'], ['amount', 'water', 'means', 'going', 'western'], ['levels', 'depletion', 'allocations', 'deltas', 'amount', 'jeopardize', 'around'], ['values', 'hydrologic', 'dwindling', 'particular', 'amount', 'water'], ['evaporation', 'either', 'levels', 'benefiting', 'water', 'inflow', 'level', 'since'], ['water', "nevada's", 'levels', 'level', 'winters', '1937', 'filled', 'lake'], ['levels', 'water', 'lake', 'acre', 'unusually', 'river', 'would', 'allocations', 'also', 'rainy', 'weather', '000', 'enough'], ['amount', 'water', 'however', 'continued', 'levels', 'order', '8'], ['nearly', 'water', 'amount', 'levels', '23', 'level', '8', 'lake', 'largely', 'unanticipated', 'continued', '7', 'saw', 'reached'], ['acre', 'water', 'river', 'flows', 'allocations', 'level', 'increase', 'states', '20', 'amid'], ['depletion', 'levels', 'water', "state's", 'acre', 'since', 'due'], ['salinity', 'water', 'quantification', 'land', '60', 'upon', 'due', '9', 'however', 'management', 'across', '−1', '2003', '28', 'temperature', 'seasonally', 'within', 'years']]

Processing features:   6%|▌         | 6/98 [02:48<42:46, 27.90s/it]

getting sample prompt forgetting sample prompt for 23473
 23472
getting sample prompt for 23474
getting sample prompt for 23475
getting sample prompt for 23476
getting sample prompt for 23477
getting sample prompt for 23478
getting sample prompt for 23479
getting sample prompt for 23480
getting sample prompt for 23481
getting sample prompt for 23482
getting sample prompt for 23483
TOP TOKENS [[], [], [], [], [], ['plenty'], ['knows', 'enemy', 'hold', '’', "odin's", 'defends', 'mythology', 'society'], [], [], [], [], [], [], [], [], ['undercutting', 'therefore', 'example', 'give', 'undermines'], [], [], [], []]
TOP TOKENS [['post', 'posted', 'posts', 'verb)bfpostsgpostsprpostingprepost', 'in-the'], ['posts', 'post', 'one', 'following', 'cls', 'standard'], ['posts', 'post', 'websites', '“posts”', 'first', 'unl', 'conclusion', 'post’s', 'links', 'website', 'organize', 'used', 'enter', 'new”', 'easy'], ['post', 'area', 'player', 'shots'], ['post', 'posts', 'including', '…'], ['post', 'posted', 'use'], ['post', 'however', 'anti-christ', 'heart', '4'], ['post', 'posts', 'finding', 'read', 'page', 'locate', 'consists', 'captured', 'changed', 'appears'], ['posts', 'sep'], ['post', 'spacetimes', 'radiation', 'worlds', 'explosive', 'galaxy', 'exploring', 'aren’t', 'today', 'fuss'], ['posts'], ['richard', 'post'], ['newspaper', 'magazine', 'post-gazette', 'post', 'morning'], ['posts', 'post', 'original', 'copied', 'first', 'narrow', 'always', 'multiple'], ['post', 'wright', 'william', 'victor', 'ted', 'johnny', 'von', 'wally', 'executive', '1766', 'wiley'], ['post', 'posting', 'key', 'w', 'edward', 'letters', 'work', 'lamppost', 'guardpost', 'technology', 'music', 'magazine', 'communications', '1995', 'people', 'entertainment'], ['post'], ['post'], ['post', 'people', 'https://www.bu.edu/questrom/faculty-research/faculty-directory/james-post'], ['post', 'disambiguation', 'fence']]
TOP TOKENS [['livelihood', 'livelihoods', '‘', 'theory', 'define', 'words', '’', 'definition', 'understand', 'lives', 'meaning'], ['livelihood', "person's", 'life', "fisherman's"], ['livelihoods', 'livelihood', 'cls', 'carried', 'meeting', 'defined', 'activities', 'moment', 'activity'], ['livelihoods', 'livelihood', 'supporting', 'implementing', 'programs', 'support', 'iv', 'concept', 'activities', 'means'], ['livelihoods', 'livelihood', 'secure', 'opportunities'], ['livelihood', 'livelihoods', 'cls', 'desired', 'comprises', 'outcomes', 'means', 'achieving', 'levels', 'capabilities', 'interventions'], ['livelihoods', 'livelihood', 'approach', 'one', 'either', 'sustainable', 'outcome'], ['livelihood', 'classification', 'strategies', 'lifestyles', 'outcomes', 'households’'], ['livelihood', 'projects', 'sources', 'means', 'activities', 'way', 'enhanced', 'even', 'communication'], ['livelihoods', 'livelihood', 'considers'], ['livelihood', 'extends'], ['livelihood', "person's", 'livelihoods', "individual's", 'activities', 'satisfy', 'living', 'extends'], ['livelihood', 'livelihoods', 'living', 'approach', 'sustainable', 'opportunities', 'efforts', 'provide', 'annually', 'means'], ['livelihood'], ['livelihood', 'livelihoods', 'cls', 'approach', 'emerges', 'activity', 'provide', 'sustainable', 'comprises', 'activities', "one's"], ['livelihood', 'livelihoods', 'programs', 'income'], ['livelihoods', 'livelihood', 'across', 'groups', 'communities', 'support', 'income', 'sectors', 'discrimination', 'responses', 'homes', 'approaches', 'also', 'funding'], ['livelihoods', 'livelihood', 'variety', 'sustain', 'services', 'employment', 'support', 'mission', 'national', 'options', 'rural', 'promoting', 'expanding', 'supported', 'activities', 'existing', 'productivity', 'shgs', 'entrepreneurs', 'tools', 'antyodaya', 'offer', 'self', 'skills', 'improve'], ['livelihood', 'also', 'see'], ['livelihoods', 'nurturing', 'centred', 'destroying', 'supporting', 'achievements', 'ways', 'supported', 'articulate', 'organizations', 'people', 'provision', 'actions', 'material', 'support', 'processes', 'envision']]
TOP TOKENS [['come', 'coaster', 'hypothetic', 'thrill', 'humanely', 'neither', 'eventually'], ['coasters', 'ride'], ['away', 'chest', 'sacrificial', 'cartilages', 'take', 'heart', 'lie', 'laid'], ['nyack'], ['8', 'godfather', 'mark31415926', '21', 'chest', 'heart', "can't", '3', '188', '36', '171', 'away', 'one'], ['lock', 'cave', 'moves', 'asocial', 'lull'], ['extends', 'entered', 'gaps', 'upward', 'descended', 'exiting', 'cage', 'standing', 'used', 'caves', 'covering', 'entrance', 'years', 'fall', 'roost', 'simply', 'deciding'], ['extends', 'entered', 'gaps', 'upward', 'descended', 'exiting', 'cage', 'standing', 'used', 'caves', 'covering', 'entrance', 'years', 'fall', 'roost', 'simply', 'deciding'], [], ['lithologic', 'nonalluvial', 'rivers', '50%–90', 'chiefly', 'along', 'key', 'contrast', 'morphologic', 'exert', 'far-reaching', '2', '1', 'oregon', 'bedrock', 'network'], ['york', 'stone', 'times', 'film', 'films', 'angeles', 'cinéma', "wallace's"], ['lives', 'life', 'level', 'levels', 'mission', 'wracketeer', 'points', 'kill', 'pickup', 'kain', 'armor', 'earn', 'reload', 'picking'], [], ['huneckia', 'apothecia', 'huneck', 'hemisphere', 'kärnefelt', 'tissue', 'cell', 'ingvar', 'taxa', 'fungal', 'paraplectenchymatous', 'german', 'quite', 'chrysophanal', 'biatorine', 'rheinigera', 'poles', 'arne', 'many', 'lichenologist', 'made', 'named', 'continuous'], ['characters', 'thriller', 'siskel', 'film', 'cinefantastique', "there's", 'mine'], ['maynard', 'desolate', "horwitz's", 'hills', 'movies', 'benefactor', 'eventually'], ['churel', 'grasp', 'imprisons', 'leave', 'lead'], ['films', 'film', 'later'], ['champignons', 'pulverulentus', 'countries', 'france', 'agaricales', 'limitrophes', 'maublanc', 'de'], []]
TOP TOKENS [['grimes', "grimes's", 'clumsily', '—', 'complains'], ['giles'], ['grimes', 'neck', 'people', 'wants', 'outside'], ['grimes', 'analytical', 'synthesizes'], ['giles'], ['grimes', 'governor', 'days', 'mckinley', 'c'], ['grimes', 'governor', 'days', 'mckinley', 'c'], ['farm||giles||1869', 'giles', 'farm||giles||1818', 'farms||giles||1841', 'farmstead||giles||1889||african', 'place||giles||1834', 'william'], ['grimes', 'people', 'describe', 'government', '55', 'temperance', 'senator', '’', 'tirelessly', 'seated', 'health'], ['grimes', "grimes's", 'mrs', 'grimesland', 'general', 'conversation', 'family', 'followed', 'men', 'bryan', 'raleigh', 'three'], ['giles', 'richard', 'iii', 'based'], ['grimes', "grimes's", '25', 'partnerships', '1909', '9'], ['grimes', 'season', 'people'], ['grimes', "grimes'third", 'week', '2017', 'season', '2016', 'defensed', 'six', 'recorded'], ['grimes', '2023', '4'], ['grimes', 'products', '2019', '2018', '2013', '20', 'org', 'character', 'canadian', 'dating', 'citizenship', 'life'], ['grimes', '1657'], ['grimes', 'states'], ['grimes', 'baseball'], ['grimes']]
TOP TOKENS [['chamomile', 'chamomilla', 'best'], ['chamomile', 'released'], ['chamomile', 'right'], ['chamomile', '“chamomile”'], ['chamomile', 'chamaemelum', 'combine', 'unk'], ['chamomile', 'homeostasis', 'chamazulene'], ['chamomile', 'scar', 'nonexistent', 'one', 'using', 'possible'], ['chamomile', 'chamomilla', 'activities', 'matricaria'], ['chamomile', 'topically'], ['chamomile', "chamomile's", 'bath', 'specifically', 'substances', 'mildly', 'irritable', 'show', 'complaints', 'inflammations', 'may'], ['chamomile', 'chamomilla', 'limited', 'chamaemelum'], ["chamomile's", 'chamomile', 'vitamins', 'chamaemelum', 'interaction'], ['chamomile'], ['chamomile', 'χαμαιμηλον', 'chamomilla', 'word', 'used', 'known', 'downy'], ["chamomile's", 'chamomile', 'chamomel', 'concurrently'], ['chamomile'], ['chamole', 'also'], ['chamomile', 'poland', 'albania', 'netherlands', 'bosnia', 'canary'], ['chamomile', 'sleep', 'consuming', 'may', 'irritations', 'use', 'drugs', 'chamazulene', 'tea', 'fragrant'], ['chamoy', 'condiment', 'chamois']]
TOP TOKENS [['yorkshire', 'leeds'], ['yorkshire', "yorkshire's", 'leeds', 'region', 'palace', 'exteriors', 'international'], ["yorkshire's", 'leeds', 'yorkshire', "wakefield's", 'bradford'], ['yorkshire', "yorkshire's", 'leeds', 'wakefield', 'company'], ['yorkshire', 'leeds', 'section', 'coastline', 'countryside'], ['yorkshire', 'leeds'], ['yorkshire', 'west', '1834'], ['yorkshire', "yorkshire's", 'leeds', 'capital', 'complex', 'uninterestingly', "sayin'morley", 'road', 'people'], ['yorkshire', "and'50s", 'pans', 'slot', '1', "the'40s", 'england', 'floods', 'military'], ['yorkshire', "yorkshire's", 'wakefield', 'leeds', 'south'], ['england', 'yorkshire', 'town', 'shire', 'county'], ['yorkshire'], ['yorkshire', 'leeds', 'east', 'wakefield', 'west', 'north'], ['yorkshire', 'moors'], ['yorkshire'], ['yorkshire', 'leeds', 'wakefield', 'sharlston', 'sheffield', '3', '1990s'], ['yorkshire', 'leeds', 'non-yorkshire', 'wakefield', 'sheffield', 'non-metropolitan'], ["yorkshire's", 'yorkshire', 'leeds', 'west', 'wakefield', "leeds'traditional", 'well', 'areas', 'bradford'], ['yorkshire', 'leeds', 'tempest', 'england', 'yorkshire-icons.com', 'varna', 'k', 'dracula', 'century', 'bard', 'kingdom'], ['yorkshire', 'leeds', 'wakefield', 'sep', 'sheffield', 'moor', 'pages', 'bradford', 'argus']]
TOP TOKENS [[], ['worksheets', 'curriculums', '’', 'homeschooling', 'worksheet'], ['worksheets', 'worksheet'], ['worksheets'], ['worksheets', 'worksheet', 'one', 'words', 'goal'], ['worksheets', 'worksheet'], ['worksheets', 'curriculums', 'homeschooling', 'like', 'also', 'worksheet'], ['worksheets', 'ones', 'worksheet', 'another', 'one', '”'], ['worksheets', 'worksheet', '’', 'one', 'lot'], ['worksheets', 'one', 'plainly', 'trainees', 'well'], ['worksheets', 'one', 'worksheet', 'tool', "microsoft's", "or'worksheets", 'time'], ['worksheets', 'presents', 'instrument', 'problems', 'setting', 'degree'], ['texas'], ['worksheets', 'worksheet', 'first', 'one', 'two', 'usefulness', 'almost'], ['deferred', 'buildings', "sheriff's", 'undressed', 'jumpsuits', '30', 'states', 'jail'], ['1986(2a', '2022(3a', '2015', '1997(2a', 'county'], ["the'pioneer"], [], ['2020'], []]
TOP TOKENS [['kuwait', 'kuwaiti', "kuwait's"], ['kuwait', 'kuwaiti'], ['kuwait', 'kuwait’s'], ['kuwait', 'kuwaitis', 'kuwaiti', 'beach', 'million', 'kw'], ["kuwait's", 'kuwait', 'kuwaitis', 'kuwaiti', 'parsi', 'biryani'], ["kuwait's", 'kuwait'], ["kuwait's", 'kuwait', 'kuwaiti', '1', '2', '29', 'coastline'], ['kuwait', 'vehicles', 'level', 'prevail'], ['kuwait', "kuwait's", 'kuwait–najd', 'kuwaitis'], ['kuwait', "kuwait's", 'busy', 'sep', 'destinations', 'capita'], ['kuwaiti', 'kuwait', 'gulf', 'persian'], ['kuwait', 'kuwaiti', '222'], ['kuwait', "kuwait's", 'kuwaiti'], ["kuwait's", 'kuwait'], ['kuwait', "kuwait's", 'kuwaiti', '2009', '2022', 'world'], ['kuwait', "kuwait's", 'kuwaiti', 'within', 'coastline'], ['kuwait'], ['kuwait'], ['kuwait', 'kuwaiti'], ["kuwait's", 'kuwait', 'kuwaiti', 'kuwaitis', 'across']]
TOP TOKENS [['hematozoa', 'avian', '607x', 'f', 'j', 'l', '1904', 'parasitol', 'family', 'sp', '6', 'k', 'crane', 'res', 'e', 'haemosporida', 'peirce', '2008152105', 'c', 'g', '110', '18642502'], ['haemoproteus', 'aves', '1992', 'kruse', '1890', 'experimentally', '161', 'areas', 'bl', 'g', 'danilewskyi', 'haemoproteidae', '9', 'culicoides'], ['manure', '2011', 'nutrient', '1983', 'cattle', 'number', '91g', '36g', '58g', '1kg', 'reason', 'g', 'presence', 'poultry', 'dense', 'pig', 'byproducts', 'content', 'respectively', 'al', 'e', 'vegetables', 'offal', 'also'], ['would', 'batak', 'hours', 'till', 'else', 'mixed', 'asked', 'bows', 'way', 'shirt', 'talking', 'language', 'hunted'], ['haemosporida', 'ecology', 'haemosporidians', 'little', 'species', 'haemosporidian', 'last', 'still', 'detailed', 'taxonomy', 'avian', 'vectors', 'evolution', 'plasmodium', 'sources', 'insufficient', 'systematics', 'identified', "parasite's", 'hindering', 'furthermore', 'uncommon', 'vertebrates', 'paucity', 'regions', 'years', 'present', 'complete'], ['big', 'one', 'ornithopod', 'today', 'three', 'eight', 'seen', 'much', 'put', 'animals', 'e', 'animal', 'camptosaurus', 'jumble', 'end', 'like', 'special', 'died', 'though', 'least', 'around', 'rhinoceros'], ['agricultural', 'pests', 'biodiversity', 'herbivorous', 'arthropods'], ['modern', 'day', 'together', '–', 'catacombs', 'wild', 'line', 'africa', 'one', 'sep', 'university', 'egypt', 'study', 'catacomb', 'year', 'fact', 'well'], ['mass', 'hours', 'next', 'rhinoceros', 'nest', 'large', 'catacombs', 'whale', 'cranial', 'days', 'frogs', 'mother', 'sinus', 'bullfrogs', 'burdened', 'shearwater', 'dime', 'bones', 'tern', 'bats', 'allowed', 'ask', '—', 'goose', 'except', 'beetles', 'lives', 'sharks', 'trays', 'boxes', 'light', 'birds', 'home', 'spent', 'score'], ['gmelin', 'sufficiently', 'l', '4th', '1963', 'testudo', '31', 'turtles', '1758', 'far', 'zarudnyi', 'former', 'goes', 'calif', 'anderson', 'races', 'also', 'series', 'sci', 'species', 'latter', 'baluchistan'], ['priabonian', 'paraphyletic', '48', 'long', '30', 'pests', '†', 'academiae', 'amber', 'slowly'], ['stratiomyidae'], ['type_species', 'familia', 'type_species_authority', 'platylimnobia', 'alexander', 'pumila'], ['native', 'household', 'male', 'racial', '8', '39', 'living', 'two', 'households', 'templeville', 'together', '20', 'temple', 'races', 'families', '12', '10', 'today', '0', '1', 'householder', '47', '6', 'individuals', 'someone', 'mid', 'legible', '25', 'american', '5', 'found', 'still', '1700s', 'white', 'present', 'people', '30', 'family'], ['one'], ['specific', 'taxon', '3', 'example', 'game', 'birds', 'deer'], ['two', 'form', 'bulk', 'around', 'initially', 'one', 'eight', 'dozens', 'also', 'long', 'consist', 'spoonbills', 'along', '40', '700', 'later', 'storks', 'darters', 'flocks', 'temples', 'often', 'eventually', 'truth', 'people', 'egypt', 'hatching', 'annually', 'knowledge', 'days', 'ibis'], ['de', '54', 'terrestris', '354', '356', 'amastigote', 'biol', 'c', 'compt', 'like', "crithidia'''is", 'soc', 'maculipennis', 'euglenozoa'], ['found', 'several', 'netted', 'hundreds', 'struggling', 'even', 'membrane', 'fishermen', 'bottom'], ['ones', '58', 'another', 'additionally']]
TOP TOKENS [['water', 'ground-water', 'rivers'], ['water', 'rivers', 'river', 'streams', 'lakes'], ['water', 'rivers', 'streams'], ['water', 'rivers', 'freshwater', 'streams', 'lakes', 'wetlands', 'permeable'], ['water', 'freshwater', 'hydrological', 'aquatic', 'lake'], ['water', 'waters', 'rivers', 'streams', 'hydrological', 'lagoons', 'rainwater', 'aquatic'], ['water', 'freshwater', 'effluents', 'rivers', 'rainwater'], ['water', 'freshwater', 'river', 'rivers', 'lakes', 'streams', 'saltwater', 'depressions'], ['water', 'freshwater', 'rivers', 'hydrologic', 'saltwater'], ['water'], ['water', 'waters', 'waterholes', 'seawater', 'rivers', 'streams', 'waterbodies', 'lakes', 'freshwater', 'infrastructures', 'ponds'], ['water', 'surface-water', 'rivers', 'hydrology'], ['water', 'freshwater', 'waterfowl'], ['water', 'hydrological', 'surface', 'freshwater', 'land', 'rainwater'], ['water', 'river', 'seawater', 'land', 'freshwater', 'evapotranspiration', 'lake', 'recharge', 'stream'], ['water', 'rivers'], ['water', 'freshwater'], ['water', 'freshwater', 'hydrology', 'environmental', 'land', 'furthermore'], ['water', 'waters', 'lakes', 'waterways', 'stormwater', 'river', 'songs', 'song', 'cls', 'oceans'], ['water', 'whitewater', 'watermills', 'river', 'aquatic', 'irrigation', 'wet', 'rivers', 'wastes', 'bed', 'world', 'lake']]
TOP TOKENS [['honorable', 'regard', 'though', 'receive'], ['“', '’', '”'], ['concentrates', 'g', 'subsequently', 'although', 'kibbutzim', 'however', 'otherwise', 'dissociated', 'terms'], ['instead', 'programs', 'hence', 'even'], ['poetry'], ['either', 'assessments', 'differentiated', 'honors', 'large', 'depth'], ['full', 'even', 'utmost', 'arriving', 'everything', 'brilliancy', 'special', 'nowhere', 'view', 'one', 'except'], ['abridgment', 'abridged', 'abridgmentmiddle', 'omitting', 'important'], ['first'], ['objective', 'objectivus', 'considered', 'object', 'factually', 'adj', 'reflecting'], ['take', 'even'], [], ['season'], ['entire', 'cls', 'favor', 'anywhere', 'goes', 'make', 'fall'], ['–', 'magnificat'], [], [], ['justus'], ['align', 'rowspan', 'colspan', '5', 'd0d0d0'], []]

Processing features:   7%|▋         | 7/98 [03:16<42:23, 27.95s/it]

getting sample prompt forgetting sample prompt for 23485
 23484
getting sample prompt for 23486
getting sample prompt for 23487
getting sample prompt for 23488
getting sample prompt for 23489
getting sample prompt for 23490
getting sample prompt for 23491
getting sample prompt for 23492
getting sample prompt for 23493
getting sample prompt for 23494
getting sample prompt for 23495
TOP TOKENS [['jem', "jem's", 'lastly'], ['jem'], ['jem', 'jemmy'], ['jemas', 'hosility', 'well', 'condescending'], ['jemas', 'hosility', 'well', 'condescending'], ['jem', 'overall', 'scout', '’', 'matures'], ["jem's", 'jem', 'individuals'], ["jem's", 'jem', 'sure', 'case'], ["jem's", 'jem', 'tact', 'story', 'bleakly', 'many', 'atticus', 'shows'], ['jem', '’', 'know', '‘', 'dominates'], ['jemjem', 'jem', 'alevism', 'may', 'novel'], ['jem', 'jemma', 'jemima', 'costello', 'blythe'], ['jemez', 'jémez'], ['jemma', "jema'a"], ['jemmingen', 'jemgum', 'leer'], ['jemna', 'wrocław'], ['jemimah', 'jemima', 'sumgong', 'beatrix', 'fishguard'], ['jemjem'], ['jemmy'], ['jem', '1988', 'year', 'including', 'partially', 'booth', 'began', '13', 'october']]
TOP TOKENS [['backdoors', 'backdoor'], ['fact', 'backdoor', 'backdoors', 'want', 'application'], ['techopedia', 'backdoors', 'use', 'used', 'backdoor', 'official', 'program'], ['backdoors', 'backdoor'], ['backdoors', 'backdoor', 'often', 'typical', 'giving', 'compromised', 'undocumented', 'system'], ['2013', 'secured', 'sha-0', 'computer', "rivest's", 'backdoor', 'otherwise', 'ron', 'backdoors', 'rfc6150'], ['backdoor', 'backdoors', 'patterns', 'user', 'installed', 'pc', 'manages', 'almost', 'exploiting', 'enables', 'compromised'], ['co-authors', 'secured', 'backdoor', "rivest's", 'deliberately', 'standards[change', 'otherwise', 'vincent', 'backdoors', '2005', 'sha-0', 'often'], ['contain', 'backdoors', 'backdoor', 'pages', 'convenience', 'don’t', 'allows'], ['backlinks', 'backlink', 'cast', 'trusted', 'masterclass', 'rather', 'engines'], ['backfire', 'daily', '10.03', 'back-fire'], ['2–1', 'games', 'scored', '2007', 'backman', 'two'], ['backfire', 'dedicated', 'stranger', 'released', 'man', 'horrible', 'affluent'], ['building', 'recorded', 'easy', 'backdoor', 'stray', 'written', 'song', '1970', 'progression'], ['inhabitants', 'north-west', 'havlíčkův'], ["sportsman's", 'backtalk', 'birdstone', 'references', 'pedigree'], ['backlin', 'actress', 'sunday', 'made', '1947', 'march', '1952', 'holiday'], ['expatriate', 'first', 'sons-in-law', 'goal', 'born', '1983', 'however', "backman's", 'three'], ['backdoor', 'autoschediastic', 'backdoors', 'found', 'e', "backdoors'triggers", 'may', 'manufacturer', 'g', 'delete', 'create'], ['bačkov']]
TOP TOKENS [['tim', 'example', 'define', 'based', 'judging', 'somewhat'], ['tim', '”', 'couches', 'appeal', 'realized', 'clarity', 'aspirational', 'sanitation', 'experiences', 'thing', 'understood', 'time', 'even', 'connect'], ['tim', "tim's", '48', '45', 'cubes', 'initiated', "simon's", 'interesting', 'helped'], ['tim', 'see', 'timmy', 'saw', 'encompass', 'rip', 'one'], ['tim', "tim's", 'kids', 'immediately', 'going', "jan's"], ['tim', 'two', '”', 'scurrying', 'recently', 'us', 'something', '’', 'said', 'later', '“'], ['tim', 'timmy', 'bob', '…', 'lived'], ['tim', 'system', 'berners'], ['tim', 'however', 'objections', 'denies', '61', '58', 'section'], ['tim', 'timjacksonind', 'hear', '19h', 'seems', '’', 'thread', 'strikes', 'bodies', '“'], ['tim', "tim's", 'matches', 'century', 'living', 'perfectly', 'great', 'response'], ['tim', 'musician'], ['tim', 'timοtheos', 'timothy', 'american'], ['tim', 'timothy', 'timmy', 'fl', '2000s–2010s'], ['tim', 'timothy', '1840–1904'], ['tim', 'timothy'], ['tim', 'timothy', 'timmy', 'newspaper', 'businessman', 'american'], ['tim'], ['tim', 'timothy'], ['tim', 'timothy', 'chairman', 'cyclist']]
TOP TOKENS [['goddard', 'space', 'also', 'p', '’', 'recognition', 'mars'], ['goddard', 'h', 'massachusetts', '3', '1', '5'], ['goddard', 'war', '1925', '1926', 'funds'], ['goddard', 'war', '1925', '1926', 'funds'], ['goddard', 'h', 'year'], ['goddard', '1934', '1939', 'h', '1945'], ['goddard', '1926', 'massachusetts', 'insight', 'expense', 'cls'], ['goddard', 'manages'], ['goddard', 'published', 'inventors', 'university', 'clearly', '”', 'wood', '’'], ['goddard', 'hutchings'], ['goddard', 'goddard–thorn'], ['goddard'], ['goddard', 'disambiguation'], ['goddard', "men's", 'mother', '2022', 'nationality', 'people', 'see', 'serie', 'also', 'japanese', 'england', 'expatriate', 'descent'], ['goddard', 'life'], ['goddard'], ['goddard', '1955', "john's", 'bennett'], ['goddard', '80', '35', '67', '24', '26', '3'], ['goddard', "goddard's", '2009', 'memoir', 'death'], ['goddard', 'paulette', 'gary']]
TOP TOKENS [['fuel', 'cell', 'cells'], ['fuel', 'cell', 'cells', 'salary'], ['cell', 'fuel'], ['cells', 'cell', 'fuel', 'ºc)||50-200||50-100||60-120||180-220||~650||500-1000', 'electrolyte', 'transportation)||electric'], ['fuel', 'cells', 'cell', 'cls', 'fuelcells'], ['fuel', 'cell', 'cells'], ['cell', 'fuel', 'cells', 'fuels'], ['fuel', 'cell', 'cells'], ['fuel', 'cell', 'cells', 'fueling'], ['fuel', 'cells', 'cell'], ['fuel', 'cell', 'cells'], ['fuel', 'cell'], ['cell', 'fuel', 'cells'], ['fuel'], ['cells', 'cell', 'fuel', 'sofc', 'pem'], ['cell', 'fuel', 'cells', 'sofcs', 'pemfc', 'sofc'], ['cell', 'fuel', 'cells', 'vehicles', '1970s', 'vehicle', 'pem'], ['cell', 'fuel', 'black', 'fyk', '2007', 'a2h2', '1', 'f07', 'engineering', 'fcev', 'fchv', 'vehicles', 'mb100'], ['fuel', 'cells—from', 'cell', 'electromobility', 'engineering'], ['cell', 'fuel', 'cells']]
TOP TOKENS [['massacre', 'famous', 'e', 'kind', 'day', 'term', 'massacres', "bartholomew's", 'boston', 'g', 'historiography', 'began'], ['massacre', 'pursuant', 'res', 'forest', 'pt', 'org'], ['massacre', 'massacred', 'word'], ['massacre', 'massacres', 'lived'], ['massacre', 'famous', 'indiscriminate', 'macacre', 'dubious', 'failed', 'stag', 'though'], ['massacre', 'famous', 'century', 'butchery', 'killing', '1698', 'people', 'murder'], ['massacre', '“', 'f', 'ludlow', '”', 'day', 'fester', 'born', 'sure', 'politics', 'one', 'among', 'brothers'], ['massacre', 'massacres', 'forest', 'named', 'click', 'wartime', 'less', 'defenseless', 'cls', 'events', 'excluded', '29', 'numbers', 'relatively'], ['massacre', '“', '”', 'boston', 'information'], ['massacre', 'ago', 'sept', '’', 'perspective', 'fought', 'knew', 'concerning', 'area', 'books', 'creek'], ['massacres', 'starring', 'film', 'massacre', 'massacro', 'andrea', 'toll', 'band', 'franchise'], ["joe's", 'massacre', 'bed', 'authenticity', 'long', 'people', 'chicago', 'muse', 'take', 'travel'], ['massacre', 'application', 'fight', 'massacres', 'war', 'group'], ['massacre', 'massacres'], ['massacre', 'links', 'external', 'amongst', 'harron', "stephen's"], ['following', 'massacre', 'massacred'], ['massacre', 'jamie', 'macario', 'roth', 'ferrusquilla', 'location', 'mexico', 'genre', 'references'], ['massacre'], ['massacres', 'massacre', 'list', 'torreón'], ['massacres', 'massacre']]
TOP TOKENS [['snowmobile', 'snowmobiles', 'snowmobiler', 'snowmobiling'], ['snowmobile', 'snowmobiles', 'dogsled', 'although'], ['snowmobile'], ['snowmobile'], ["snowmobile's", 'snowmobile', 'snowmobilers'], ['snowmobile', 'snowmobiles', 'snowmobile-like', 'snowmobiling', 'snow'], ['snowmobiles', 'snowmobile', 'risk'], ['snowmobiles', 'snowmobile', 'risk'], ['snowmobile', 'snowmobiles', 'riding'], ['snowmobile', 'snowmobiles', "snowmobile's"], ['snowmobile', 'snowmobiles', "snowmobiles'tracks", 'snowmobilers', 'skimobile', 'specific'], ['immobilizer', 'immobile'], ['bootmobile', 'wienermobile', 'bootmobiles', 'nutmobile'], ['snowmobile', 'snowmobilers', 'snowmobiles', '7'], ['snowmobiles', 'snowmobile', 'found', 'communities', 'local', 'foresters', 'also'], ['snowmobiles', 'snowmobile', 'snowmobilers', 'snowmobiling', 'found', 'association'], ['snowmobiles', 'snowmobile', 'historically'], ['snowmobile', 'snowmobiles', 'contemporary', 'resistant', 'minimized', 'garment(neck'], ['batmobile'], ['snowmobiles', 'snowmobile', 'state', 'registrations']]
TOP TOKENS [['apocalypse', 'apocalypses', 'word', 'definitions', 'n'], ['apocalypse', 'apocalyptic', 'apocalypses', 'symbolism', 'eschatology', 'wikipedia', 'weber', 'term', 'elements', 'bible', 'əpok'], ['apocalypse', 'apocalyptic', 'apocalypses', 'weber', 'əpŏk´əlĭps', 'eschatology', 'symbolism', 'elements', 'bible'], ['apocalypse', 'apocalyptic', 'genre', 'animals', '“', 'characteristics'], ['apocalypses', 'apocalyptic', 'material', 'many', 'agenda', 'outlook', 'literature', 'imagery'], ['apocalypse', '“apocalypse”', 'apocalyptic', 'https://tbp.xyz/apocalypticpod', 'https://tbp.xyz/apocalypseblog', 'https://tbp.xyz/apocalypticsrg', 'it’s', 'https://tbp.xyz/apocalypticvn', 'word'], ['apocalypse', '“'], ['apocalypse', 'cls', 'work', 'apocryphal', 'hist', 'tradition'], ['apocalypse', 'apocalyptic', 'word', '”', 'literature', 'era'], ['apocalypse', 'apocalyptic', 'apocalypses', 'cls', '“', 'myth', '–'], ['apocalypse', 'apocalyptic', 'word'], ['apocalypse', 'superman', 'cls', 'shin', 'event'], ['apocalypse'], ['apocalypse', 'apocalyptic', 'cls', 'eschatology', 'considered', 'faithful'], ['apocalypse', 'emerick', 'albums', '–'], ['apocalypse', 'aka'], ['apocalypse', 'apocalyptic'], ['apocalypse', 'band', 'derek', 'caçador', 'william', 'luzes', 'sozinho'], ['apocalypse', 'links', 'placed', 'external', 'references', 'record'], ['apocalypse', 'apocalyptic', 'apocalypticism', "god's", 'fiction', 'end', 'mythologized', 'supernatural', 'post-apocalyptic']]
TOP TOKENS [['megara', 'corinth', 'megaris', "megara's", 'megarians', '–', 'plataea', "megarians'desecration", 'megarian', '18'], ['megara', 'sicily', 'megarians', 'poleis', 'athens', 'neighboring', 'fought'], ['process', 'megacam', 'megapipe', 'single', 'attractive', 'pipeline', 'fraction', 'chunks', 'taking', 'small'], ['megarians', 'megara', 'open', 'even', 'city-state', 'city-states'], ['megara', 'megarian', 'fought', 'alongside', 'poleis'], ['mega', 'megaprojects', 'megaproject', 'legislature', '“', 'highways', 'offer', 'criticisms', 'stability', 'substantial'], ['megaloblastic', 'megas', 'hematology', 'able', '150', 'megalo', '“megaloblast”', 'megaloblast', 'somewhat', 'enlargement', 'full'], ['megabates', 'herodotus', 'four-month-long'], ['mega', '2005', 'http://dictionary.oed.com/cgi/entry/00304790', 'megahertz', 'megaword', 'cgpm', 'megapixel', 'look', 'megametre', '1000000m', 'megabyte', 'm3', 'megatonne', 'example', 'weapons', '1960'], ['limits', 'megacoins', 'megacoin', 'mega', 'receive', 'world'], ['mega', 'megaera'], ['megas-tu', 'mega', 'megas', '1945', 'logothetēs', 'singer'], ['mega', 'megasport'], ['megaplex', 'sports'], ['mega', 'york', 'wskq', 'politician', 'power', '106', 'megaupload', 'megawati', '1947'], ['megabyte', 'megabites', 'column', 'megabite', 'disambiguation'], ['megagames', 'day', 'megagame', 'desires', 'members'], ['megabus', 'mega', 'megatall', 'esports', 'mega64'], ['megabates', 'megabazus', 'siege', 'megabyzus', 'people', 'herodotus'], ['megacity', 'mega', 'megalopolis', 'mega-city', 'aixam-mega']]
TOP TOKENS [['edom'], ['edomites', 'edom', 'edomite', '9:26', 'wisdom', 'israelites'], ['edom', 'edomites', 'bc'], ['edom', 'edomites', 'bc'], ['edomites', 'edom', 'edoms', 'river'], ['edom', 'edomites', 'edomite'], ["edom's", 'edom', 'edomites', 'plunder', 'invulnerable'], ['edom', 'edomites', 'edomite', '3', 'jordan', '20'], ['edom', 'edomites', 'edomite', '3', 'jordan', '20'], ['edom', 'edomites', 'd54', 'loathe', 'fact', 'udumi'], ['edom', 'bible'], ['edom', 'edomites', 'edomite', 'nation', 'levant', 'jordan', 'bc', '8th', 'first', 'negev'], ['1967', '1992', 'edon', 'édon', '1994'], ['edom', 'farm', 'village', 'glen', 'january'], ['edom', "edom's", 'neosho', 'ozark', 'fulcrum', 'rhinehart', 'w', 'missouri'], ["edom's", 'edomites', 'edomite', 'edom', 'geber', 'farming', 'literature', 'astride'], ['edo', '1946', '1959', 'croatian', 'american', '1906–1993', 'baseball'], ['edom', 'edomites', 'nation', 'bc', 'history'], ['edom', 'edomites', 'edomite', 'prophets'], ['edo', 'edogawa']]
TOP TOKENS [['would', 'reserved', 'if(redirected', '2002', 'suppose'], ['would', 'rivers', 'operated', 'planes', 'play', 'water', 'live', 'wear', 'trees', 'ground'], ['would', 'market', 'bridges', 'including', 'receiving', 'race', 'give'], ['would', 'scenario', 'probably', 'xxiii'], ['colour', 'would', 'v', 'store', 'event', 'evening', 'rules', 'dark', 'home', 'choose'], ['might', 'would', 'given', 'likely'], ['would', 'wish', '…', '“'], ['would', '…', '’', '“', 'unless', '”', 'nonsense'], ['would'], ['imagine', 'would', 'might', 'perhaps', 'maybe', 'even'], ['daredevil', 'thor', 'men'], ['anthology', 'questions', 'episode', 'album', 'dregs'], ['cosmonauts'], ['lived', '1998', 'since', '…', '1', '3'], ['might', 'imagine'], ['man', 'bishop'], ['might', "world's"], ['would'], ['avengers', 'annihilus', 'four', 'universe', 'powers', 'lived', '44'], ['would', 'alive', 'release', 'form', 'initially', 'november']]
TOP TOKENS [['ausf', 'placed'], ['increased', 'part', 'filler', 'featured', 'fitted', 'protection', 'increase', 'insufficiently', 'glacis'], ['refinements', 'changes', 'addition', '7'], ['fitted', 'improvements', '7mm', 'gun', '40mm', '46mm', '97mm', '12', "driver's", 'ejection', '79mm'], ['thickening', 'g', 'equipped', 'modification', 'unaltered', 'mm', 'mantlet'], ['modifications', 'raised', 'received', 'additional', 'addition', 'mantlet', 'superstructures', 'mm'], ['backfitting', 'mm', 'additional', 'receiving', 'piece', 'protection', 'parts', 'ausf', 'introduction', 'mantlet', 'sprocket', 'protected'], ['new', '5', 'added', 'increased', '6', 'make', 'fighting', 'received', '11', 'hatches', 'changed', "tank's", 'reached'], ['installed', 'hatches', 'armament', 'received', 'machineguns', 'plate', 'increased', 'added', 'ausf', 'behind', 'reduced', 'sprockets', 'changed', 'redesigned', 'coaxial'], ['retrofitted', 'increased', 'change', '7', 'plate', 'added', 'front'], ['installing', 'glacis', 'installed', 'mantlet', 'carried', 'greater', '92×57mm', 'modification', 'protection', 'giving'], ['hatches', 'improved', 'equipped', "turret's", 'fitted'], ['fitted', "commander's", "tank's", 'kfz', 'installed', 'modifications'], ['mountings', 'modified', 'replaced', '12', '7', 'fitted', '62', 'tested', 'reduced', 'one', 'provisions', 'removed', 'standardised'], ['foremast', 'mainmast', 'replacing', 'replaced', 'installed', 'mm', 'back', 'fit', 'refitted', 'removing'], ['modifications', 'bulged', 'using', 'replaced', 'placed', 'received', 'increased', 'including', 'added', 'positions'], ['mountings', 'fitted', 'mainmast', 'mounted', 'mark', 'barbettes', 'elevate'], ['mountings', 'installed', 'disarmed', 'plated', '8', 'place', 'adding'], ["sherman's", 'ausf', "g's", 'increased', "m4's", 'calibers', '56º', 'mantlet', 'mm', 'glacis'], ['mountings', '5', 'guns', '5guns', '12', 'elevate', 'gun']]

Processing features:   8%|▊         | 8/98 [03:45<42:46, 28.52s/it]

getting sample prompt forgetting sample prompt for 23497
 23496
getting sample prompt for 23498
getting sample prompt for 23499
getting sample prompt for 23500
getting sample prompt for 23501
getting sample prompt for 23502
getting sample prompt for 23503
getting sample prompt for 23504
getting sample prompt for 23505
getting sample prompt for 23506
getting sample prompt for 23507
TOP TOKENS [['element', 'elements', 'hinduism', 'discretiva', 'elementti', 'elementu', 'meaning', 'lehrer', 'elemento'], ['element', 'matter', 'fishes', 'elements'], ['element', 'http://lists.w3.org/archives/public/public-qt-comments/2002oct/0060.html', 'http://lists.w3.org/archives/public/public-qt-comments/2002oct/0045.html'], ['element', 'word'], ['element', 'elements', 'translate', 'environment:for', 'earth', 'set', 'quality:it', 'kinds'], ['elements', 'element', 'relationship', 'habitat'], ['element'], ['element'], ['element', 'elements', 'hence', 'example'], ['element', 'elements', 'forms', 'noun', 'cannot', 'one'], ['element'], ['element'], ['element', '2017', 'element.com', 'july', 'history', '2022', 'uk', 'external', 'links', 'bought', 'laboratories', 'group', '2021', 'analytical', 'top', 'provision'], ['elements', 'element'], ['elements'], ['element'], ['elements', 'element', 'album'], ['elements', "euclid's", 'mathematicians', 'lines', 'written', 'cls', 'read', 'knowledge', 'students', 'irrefragable', 'seven', 'century', '19th'], ['éléments', "d'élements", '1990s', '2022', 'bar-on', '1983', 'elemente', 'well-educated', "magazine's", 'audience', 'khaki', 'initially', 'serving', 'scholar', 'students', 'september', 'president'], ['elements', 'majik', 'backing', 'vocals']]
TOP TOKENS [['apexes', 'events', 'triangle', 'juan', 'misconceptions', 'beings', 'cls', 'things', 'although', 'natural', 'lost', 'matter'], ['ships', 'saturate', 'ship', 'salvaged', '2', 'hour', 'airport', 'well', 'absurdly', 'triangle', 'becoming', 'misadventures'], ['disappearances'], ['triangle', 'disappear', 'ships', 'events', 'airplanes', 'without', 'atlantic', 'anomalies', 'natural', 'one', 'forms', 'ocean', 'region'], ['supernatural', 'triangle', 'hydrates', 'events', 'point', 'lose', 'responsible', 'cyclops', 'cls', 'occurred', 'stream', '19', 'irrespective'], ['however'], ['events', 'providing', 'ships', 'admiralty', 'captains', 'compasses', 'triangle', 'disappearers', 'pilots', 'found', 'hypothesized', 'u', 'navel', 'without', 'cls', 'officers', 'sailors', 'northwested', 'sites'], ['isthmus', 'isthmuses', 'isthmos', 'connects', 'quetrihue'], ['triangle', 'happened', 'degrees', 'w', 'km', 'due', 'florida', '900', 'unconscious', 'catalysts'], ['ships', 'disappearances', 'supernatural', 'unexplained', 'area', 'triangle', 'landslides', 'make', 'result', 'sure', 'huge'], ['paranormal', 'anomalies', 'disappear', 'triangles', 'hydrate', 'ship', 'hydrates', 'came', 'apparently', 'area', 'leaving', 'buoyancy', 'loss', 'com', 'encyclopedia', 'triangle', 'clathrates', 'ships', 'due', 'story', 'interrupt'], ['isthmus', 'isthmuses', 'sechelt', 'connects', 'chubut', 'connecting', 'across', 'quetrihue', 'huapi', 'sea', 'chignecto'], ['isthmuses', 'isthmus'], ['connecting', 'land', 'isthmus', 'connected', 'isthmuses', 'tube', 'isthmi', 'bodies', 'cos', 'tubae', 'uterinae', 'anatomically', 'deletion'], ['woldingham', 'warlingham', 'railway', 'purley', 'external', "residents'association", 'station', 'stations', 'riddlesdown'], ['km', 'route', 'intermunicipal', 'crimea', 'airport', '2.5', 'ivanino'], ["the'triangle'however", 'roundhay', 'gledhow', 'ley', 'area', 'history', 'delivered', 'horsforth'], ['isthmus', 'connecting', 'svyatoy'], ['triangle', 'ships'], ['05am', '10am', 'carnivore', 'came']]
TOP TOKENS [['prawn', 'prawns', '2'], ['prawn', 'trawled', 'prawns'], ['prawn', 'prawns', 'trawl', 'trawlers', 'trawls'], ['prawn', 'prawns', 'trawlers', 'trawl'], ['trawls', 'prawns', 'prawn', 'annual'], ['prawn', 'prawns', 'flavor', 'cls', 'veined'], ['prawn', 'prawns', 'water'], ['prawns', "prawns'are", "famous'prawn"], ['prawns', 'prawn'], ['prawns', 'prawn', 'example'], ["prawn's", 'prawn'], ['traw'], ['trawl', 'trawling', 'trawls', 'trawlers', 'cls', 'trawler', 'hp', 'trolling', '000'], ['prawn'], ['trawler', 'trawlers', 'trawler-style'], ['prawle'], ['prawns', 'prawn'], ['prawn', 'operation'], ['craw'], ['grawn', 'pfas', 'community', 'blair']]
TOP TOKENS [['polyglutarimide', 'imide', 'imides', 'ethylsuccinimide', 'anhydrides', 'intermediates', 'cycloheximide', 'acid', 'known', 'phthalic'], ['alkylimides', 'bromosuccinimide', 'chlorosuccinimide', 'imides', 'imide', '085', 'certain', '253', 'observed', 'polyimides', '14356007'], ['cupricide', 'algicide', 'aglicides', 'sulphate', 'algae', 'works', 'algicidal', 'form'], ['deuteride', 'heard', 'hydride'], ['ceramides', 'ceramide', 'phytoceramides', 'urea', 'soy', 'd&c'], ['icide', 'silicide', 'zrsi2', 'ceramics', 'disilicide', 'etc', 'customized', 'send', 'film', 'chemicals', 'cost', 'enamel', 'zirconium'], ['azides', 'azide', 'aryl', 'amine', 'exist', 'nitrophenyl', '254nm', 'phenyl', '365nm', 'hydroxyphenyl', 'close', 'dominates', 'literature', 'intended', 'e', 'homobifunctional', 'directly'], ['ceramide', 'niacinamide', 'ceramides', 'editors', 'amounts'], ['zeide', '†', 'yiddish', 'ze-ide', 'd.ey', 'ey.t'], ['azide', '1', 'nh3', 'amine'], ['disambiguation', 'schleswig-holstein', 'grouping', 'victoria'], ['fratricide', 'fratricides', 'killing', 'sororicide'], ['garside', '1898–1964', '1979', 'bettis', 'jeannine', '1818–1876', 'garside-wight'], ['vermont', '1982', 'brookside', 'county', 'tulsa', 'ohio', 'nrhp', 'wheaton', 'new'], ['whitesides', 'district', 'nova', 'county'], ['north', 'cambridge', 'lanarkshire', 'barrow-in-furness', 'parkside', 'zealand', 'durham', 'isa'], ['hesperides'], ['saint-placide', 'placide', '1929–2003', '1938'], ['burnside', 'south', 'county', 'nova', 'labrador', 'victoria', 'mcgill', 'illinois', 'dartmouth', 'hamlet', 'sydney', 'lanarkshire', 'hall', 'suburb', 'adelaide', 'kentucky', 'arizona'], ['omnicide', 'neaera']]
TOP TOKENS [['dillinger', '“', 'arts', 'indiana', 'bloomington', '12th', 'kendalynn', 'stuck', 'slajus', 'wohlfiel', 'makaila', 'grade', 'school', 'marrison', 'plonke', 'ms', '”', 'south', 'lapalm', 'r', 'promises'], [], [], ['bloomington', 'arts', 'indiana', 'central', 'grade', 'hills', 'kendalynn', 'school', 'ms', 'janel', 'lapalm', 'south', 'mr', 'shines', 'high', '“', 'horsemen', 'teacher', 'barone', 'cary', 'brand', 'buhle', 'michigan', 'king', 'wisconsin', 'kramer'], [], [], ['kaye', 'miller', 'davies', 'lynne', 'persons', 'chomsky', 'horgan', 'jill', 'jerry', 'martin', 'tienson', 'fodor', 'smolensky', 'terence', 'semantics', 'laurence'], ["episode.'who'versus'whom'in", "complicated.'whoever'versus'whomever'if", '“', 'whoever', 'whomever'], ['stacey', 'gaylyn', 'jackie', 'bloomington', 'indiana', 'silverman', 'studlar', 'cs1', 'television', 'willis', 'pp', 'lynne', 'smelik', 'university', 'williams', 'sharon', 'rogers', 'press', '1998', 'linda', 'bechdel', 'xvii', "malick's"], ['lyn', 'cs1', 'advanced', "lyn's", 'thus', 'towards', "julie's", 'valsiner', 'practice', 'primarily', 'center', "sarah's", 'ages', 'sarah', "nina's", 'nina', "daughter's", 'adult'], ['jones'], ['daughter', 'comics', 'television', 'tv', 'hindi'], ['films'], ['ru:дрекслер', 'people', 'operator', 'surnames', 'regime', '1908–1945', 'drechsler', 'lv:drekslers', 'occupation', 'crewman', 'lathe', '1931–2003', 'u-boat', 'born', 'ss-aufseherin', 'hanno', 'nozīmju', 'karl', 'include'], ['meister', 'manhunter', 'supergirl', 'kara', '15', 'occurred', '1', 'r', "kara's", 'downs', 'january', 'ramon', "j'onn", 'cisco', 'february', 'additionally', 'cavanagh', 'lonsdale', 'roles', 'garber', '2017', 'l', 'west', 'vibe', 'along', 'iris', 'wells', 'el', 'respectively'], ['watching', 'full', 'ages', 'television', '31', 'angeles', 'year', 'characters', 'olds', 'among', 'saul', 'sunday', '18', 'also', 'script', 'direction', "brandt's", 'performance', 'marie', '49', 'praised', 'rock', 'said', 'work', 'time', 'ratings', 'character', 'dubstep', "show's", 'aired'], [], ['scully', 'mulder', 'shalhoub', 'television', 'gunmen', 'feels', 'v', 'fox', 'files', 'people', '13', 'conspiratorial', 'nielsen', "banton's", 'households', "there's", 'properly', 'coming', 'watching', 'breaking', 'stars', 'features', 'wrote', 'chair', 'get', 'saul'], ['anyone', 'sara', "sara's", "sister's", 'roberts', 'cuddles', 'disarms', 'stabs', 'disguises', 'angeles', 'unconscious', 'choking', 'briefly', 'alarmed', 'stephen', 'help', 'cutter', 'irene', 'room'], ['hero', 'families']]
TOP TOKENS [['kindness', 'kind', 'act', 'practising', 'acts', 'bit'], ['kindness', '“kindness', 'kind', 'kindliness', '–'], ['kindness', 'kindnesses', 'act', 'kind', 'acts', 'co', 'recently'], ['kindness', 'kind', 'act', 'exactly', 'acts'], ['kindness', 'kind', 'every'], ['kindness', 'kind', 'kindness”', 'kind”', 'acts', 'act'], ['kindness', 'kind'], ['kindness', 'kind', 'revolution', 'mind', '’'], ['kindness', 'kind', 'act', 'gentle', 'mind'], ['kindness', 'kind', '“', 'acts', 'us', 'traffic', 'quotes', 'means', 'day', 'nice', 'flat'], ['kindness'], ['kindness', 'kind', 'acts', 'return', 'word', 'cls'], ['kindness', 'acts'], ['kindness', 'kind', 'act', 'day', 'found', 'making'], ['kindness', "nations'kindness", 'kind', 'act', 'us', 'day', 'location', 'founded'], ['kindness'], ['kindness', "kindness's", 'cls', 'debut', 'tour', 'limited', '2013', 'released', 'printemps', 'band', 'edition', 'b', 'academy', 'red'], ['kindness', 'location', 'act'], ['kindness'], ["kindness's", 'kindness', 'john', 'typical', 'dawson', 'way', 'yellow', 'london', 'northern', 'arts', '2012']]
TOP TOKENS [['jogging', 'joggers', 'jog', 'cls'], ['jog', 'jogging', 'cls'], ['jogging', 'jog', 'joggers', 'regularly'], ['jogging', 'jog', 'going', 'body', 'impact'], ['jogging', 'jog'], ['jogging', 'joggers', 'jog', 'jogger', 'jogs', 'world', '–', 'enjoy', 'anticipated', 'exhaustion', 'clad'], ['jogging', 'jog', 'high', 'walking', 'cls'], ['jogging', 'examinations', 'person'], ['jogging', 'jog', 'joggers'], ['jogging', 'joggers', 'jog'], ['jogging', 'jogger', 'joggers', 'jog', 'states', "joggers'club", 'cls'], ['jogging', 'jogger', "joggers'club", 'mile'], ['joggers'], ['jogging', 'jog'], ['jogging', 'joggers', 'jog', 'jogs', 'jogged', 'several', 'schoolwork', 'shoes'], ['jogging', 'pace', 'juggling', 'jogglers', 'joggling', 'joggle', 'joggler', 'races', '90', 'competitors'], ['jogging', "jogger's", 'joggers', 'lokhandwalas', 'seaside', 'lokhandwala', 'track', 'cls', 'go', 'sundays', 'students', 'plaque'], ['jog-a-thons', 'jog-a-thon', 'jog', 'jogged', 'participants'], ['jog', "jog's"], ['jog', 'gharanas', 'hallmarks', 'g', 'kalidas', 'layakari', 'pandit', 'ragas', 'sangeet', 'crispness', 'gayaki', 'folk', 'samman', 'bhuwalka']]
TOP TOKENS [['describing', 'yoga', 'yoga-practices'], ['yoga', 'yogic', 'sutras'], ['yoga', 'presence', 'though'], ['yoga'], ['yoga', 'cls', 'word', 'yogic', 'patanjali', 'veda'], ['yoga', 'patanjali'], ['patanjali', 'yoga', 'today’s', '‘yoga’', 'sacred', 'word', 'patanjali’s'], ['describing', 'yoga', 'sutras', 'unclear'], ['describing', 'yoga', 'sutras', 'unclear'], ['yoga', 'upanishads', 'bc'], ['sutras', 'yoga', "patajali's", "patanjali's", 'localized', 'patanjali', 'practices', 'yogic', 'part', 'tattvavaisaradi'], ['also', "patanjali's", 'yoga', 'yogasutras', '1', 'see', 'yogatattva', '–', 'dx', '2', 'philosophy', 'doi', 'patanjali'], ["patanjali's", 'yoga', 'yogasutras', 'samkhya', 'ad', 'soul', 'larson', 'sutras', '2', '1', 'thought', '27', 'patanjali'], ['yoga', 'sampradaya', 'yogas', 'practice', 'patanjali', 'sutras', 'shlokas', 'yogatattva'], ['yoga', 'yogatattva', 'patanjali'], ['yoga', 'gurus', "yoga's", 'siddha', 'considered', "gurus'approaches", 'span', 'kripalvananda', 'kripalu'], ['yoga', "patanjali's", 'shaivism', 'sutras', 'patanjali', 'buddhist', 'indian', 'tantric'], ['yoga', 'range', 'cls', 'yogins', "yoga's", 'philosophy', 'practices', 'various'], ['yoga', 'yogasutras', "patanjali's", 'treatises', 'yogic', 'philosophy', 'also', 'jainism', 'press', 'west'], ['yoga', 'philosophy', 'yogas', 'yōga', 'den-en-toshi', 'hindu', 'india', 'ancient']]
TOP TOKENS [['impetigo'], ['impetigo', 'cause'], ['impetigo'], ['impetigo', 'suppl):25-6', 'pract'], ['impetigo'], ['impetigo'], ['impetigo', 'mouth', 'streptococcus'], ['impetigo', 'impetiginization', 'antiseptic'], ['impetigo', 'impeti'], ['impetigo'], ['impetigo', 'found', 'less', 'commonly', 'often', 'streptococcus', 'eczema', 'cls', 'swollen'], ['impetigo', 'may', 'therefore', 'either', 'bullous', 'antibiotics', 'potassium', 'cases', 'although', 'antimicrobials', 'skin'], ['impetigo', '7', 'official', 'artwork', '1987', 'impaled', 'links', 'cls', '1999', 'two', 'machetazo', 'gore', 'split', 'also'], ['impetigo', 'also', 'involved', 'see', 'may', 'although', 'much'], ['impetigo', 'globally', 'word', 'individuals'], ['impetigo', 'symptoms', 'skin', 'antibiotics', 'infected', 'comes', 'slightly', 'usually', 'give', 'may', 'gladiatorial'], ['impetigo', 'diagnosis', 'causes', 'lesions', 'form', 'factors', 'incubation', 'bullous', 'ulcers', 'area', 'especially'], ['impetigo', 'pyogenes', 'globally', 'form', 'nonbullous', 'bullous', 'estimated', 'given', 'staphylococcal', 'even'], ['impetigo', 'settings', 'skin', 'bullous', 'usually', 'region', 'toes', 'staphylococcal', '70', 'epidermis'], ['impetigo', 'official', 'links']]
TOP TOKENS [['eucharist', '“eucharist”', 'eucharista', 'communion/eucharist'], ['eucharistic', 'eucharist'], ['eucharist', 'eucharist’', '‘eucharist’', 'eucharistic', 'eucharistein'], ['eucharist', 'eucharistic'], ['eucharist', 'eucharistic', 'lord'], ['eucharist', "name'eucharist'would", 'eucharistic', 'eschatology', 'cls'], ['eucharist'], ['eucharist', 'eucharistic', 'eucharistia', 'cls'], ['eucharist', 'eucharistic'], ['eucharist', 'eucharist—from'], ['eucharist'], ['eucharist', 'eucharistia', 'eucharistic', 'cls', '23', 'act', 'corinthians11', '24'], ['eucharist', 'eucharistia', 'eschatological'], ['eucharist', 'eucharistic'], ['eucharist', 'eucharistic', 'said', 'mentions', 'eschatology'], ['eucharist', "eucharist's", 'gustaffsson', 'cls', 'vocals', 'fare', 'worked', 'establishing', 'particularly', 'enemy', 'records'], ['eucharist', 'eucharistic'], ['eucharist', 'eucharists', 'eucharistia', 'christian', 'years'], ['eucharist', 'eucharistic', 'word'], ['eucharist', 'eucharistic', 'death', 'rite', 'good', 'follows', 'may']]
TOP TOKENS [['salmonella', 'delivered', 'world'], ['salmonella', 'unwashed', '42', 'digestive', 'usually'], ['salmonella', 'salmonellosis'], ['salmonella', 'salmonellosis', 'easier', 'infection', '’'], ['salmonella', 'salmonellosis', 'infections', 'infection'], ['salmonella', 'salmonellosis', 'infection', 'preventing', 'diarrhea', 'infections', 'may'], ['salmonella', 'salmonellosis', 'disease', 'carry', 'countries', 'properly', 'usually', 'organs', 'infect'], ['salmonella', 'sick', '1-800-439-8550', '1-800-222-1222', 'vermont', '20', 'least'], ['salmonella', 'borne', 'contracting', 'precautions', '19'], ['salmonella', 'salmonellosis', 'part', 'cls'], ['salmonella', 'salmonellosis', 'due', '1', 'surgeon', 'available', 'serotypes', 'american', 'cls', '1850', 'reactions', 'fermentation', 'anaerobes'], ['salmonella', 'infection', 'due', 'infections', 'february'], ['salmonella', 'salmonellae', 'e', 'four', 'karl', 'typhimurium', 'arizonae', 'years', 'clinically', 'spleens', 'example', 'white', 'host', 'states', 'species'], ['salmonella', 'salmonellosis', 'recommended', '178', 'fever', 'dogs', 'may', 'cls', 'nontyphoidal'], ['salmonella', 'salmonellosis', 'one', 'bacteria', 'pet', 'developing', 'enterica', 'zoonotic', 'united', 'origination'], ['salmonellosis', 'salmonella', 'thus', 'humans', 'bacteria', 'developing', 'infection', 'took', 'illness', 'outbreak', 'deaths'], ['salmonellosis', 'salmonella', '627', 'j', 'jantsch', 'coli', 'infect', '2004', '477', '5323', '2052', 'hensel', 'pathogenicity', '468'], ['salmonella', 'salmonellosis', '7', 'identifying', 'due'], ['salmonella', 'salmonellosis', '1', '316', 'enteritidis', 'infections', '23', 'typhoidal', 'human', 'ceftriaxone'], ['salmonella', 'salmonellosis', 'three', 'stemming', "people's", 'withheld']]
TOP TOKENS [['securities', 'sec', '“', 'certificates'], ['securities', 'act', 'sec'], ['securities', 'sec'], ['securities', 'act', 'law', 'sec', 'laws'], ['securities', 'sec', 'cls', 'industry', 'companies', 'definition'], ['securities', 'sec'], ['securities', 'sec', 'industry', "company's"], ['securities', 'sec', 'act', 'law'], ['securities', 'laws', 'sec’s', 'trade', 'sec', 'industry'], ['securities', 'sec', 'act'], ['securities', 'laws', 'sec', 'act', 'exchange'], ['securities', 'sec', 'act', "sec's", 'laws'], ['securities', 'laws', 'act', 'sec', 'violators', 'exchange'], ['securities', 'sec', 'laws'], ['securities', 'sec', 'act', 'laws', 'investor'], ['securities', 'sec', 'act', 'laws'], ['securities'], ['securities', 'sec', "sec's", 'exempting', "issuer's"], ['securities', 'sec', "countries'securities", 'laws', 'act', 'commissions', 'traded', 'exchange', 'law'], ['securities', 'sec', 'industry', 'act']]

Processing features:   9%|▉         | 9/98 [04:14<42:23, 28.58s/it]

getting sample prompt for 23508
getting sample prompt for 23509
getting sample prompt for 23510
getting sample prompt for 23511
getting sample prompt for 23512
getting sample prompt for 23513
getting sample prompt for 23514
getting sample prompt for 23515
getting sample prompt for 23516
getting sample prompt for 23517
getting sample prompt for 23518
getting sample prompt for 23519
TOP TOKENS [['artist', 'artistdaily'], ['artist', 'artistdaily'], ['artist', 'artists', 'artiste'], ['artist', 'artists', 'artiste'], ['artist', 'mine', 'artists', 'cvs'], ['artists'], ['artists', 'artist'], ['artist', 'artists', 'artiste'], ['artist', 'artists', '“', '‘', 'cls', '’'], ['artist', 'word', 'identifying', 'artists', '“', 'comes'], ['music', 'artists', 'artist', 'artistes', 'l.e.s'], ['artist', 'artiste', 'film'], ['artists', 'films', 'directed'], ['artists', 'authorization', 'sub-national'], ['artist', 'artiste', 'manual', 'common', 'context', 'term', 'one', 'cls'], ['artists', 'artist'], ['artist', 'artists', 'film'], ['artists', 'artist'], ['artists', 'artist', 'poet'], ['artists', 'artist', "hamnett's", 'careers']]
TOP TOKENS [['philanthropy', 'philanthropist', 'learn', 'philanthropists'], ['philanthropist'], ['philanthropist', 'philanthropy', 'philanthropists', 'period', 'individuals'], ['philanthropy', 'philanthropists', 'philanthropic', '2.0', 'definition'], ['philanthropy', 'philanthropist', 'core', 'today', 'definition'], ["of'philanthropy'philanthropy", 'philanthropy', "down'philanthropy'billionaire", 'scale', 'one', 'involves', 'cls', 'education', '347', 'come'], ['philanthropy', 'context', 'include'], ['philanthropist', 'philanthropy', 'philanthropy…', 'attempts', 'problem'], ['philanthropist', 'philanthropy', 'philanthropy…', 'attempts', 'problem'], ['philanthropy', 'states', '‘the', 'found', 'involves', 'anything', 'well', 'fulfil', 'philanthropic', 'however', 'actions’', 'definitions'], ['philanthropy'], ['philanthropist', 'philanthropists', 'alagappa', 'cls', 'philanthropy', 'adar'], ['philanthropist', 'philanthropy', 'cls', 'word', 'defined', 'notable'], ['philanthropy'], ['philanthropy', 'philanthropist', 'philanthropic', 'perpetuates', 'criticism', "smith's", 'puts', 'various'], ['philanthropy', 'educates'], ['philanthropy', 'philanthropists', 'philanthropic', 'healthcare', 'approaches', 'utilize'], ['philanthropist', 'art', 'academy'], ['philanthropy', 'urgently', 'social', 'capitalism', 'much'], ['cls', 'philanthropy', 'institutions', 'philanthropists', 'arts', 'prominent', 'school', 'foundation', 'u', 'abolitionism', 'fulfilling']]
TOP TOKENS [["mencken's", 'mencken', 'l', 'h.l', 'primarily'], ['mencken', 'l', 'september'], ['mencken', "mencken's", 'l', 'scholar', 'library', 'louis', 'economics', 'sr'], ["mencken's", 'mencken', '1924', 'q.v'], ['mencken', "mencken's", 'babies', 'gullible', 'wishes', 'tombstone', 'editor', 'small', 'death'], ['mencken', 'l', 'louis', 'h', 'vice', 'sages', '65', 'sacerdotalism'], ['mencken', 'allies', 'evaded', '’'], ['mencken', 'h.l'], ['mencken', "mencken's", 'l', 'mutilated', 'individuals', 'also', 'h', 'died'], ['mencken', 'hl', 'l'], ['mencken', 'jr'], ['married', 'wicken', 'wickens'], ['bracken', 'zealand', 'e', 'co-founder'], ['mencken', "mencken's", 'menckenian', 'l', 'economics', 'pertaining', 'louis'], ['bracken', 'september', 'april', 'james'], ['bracken'], ['hicken'], ['mencken', "mencken's", 'l', 'h'], ['bracken', 'rape'], ["bracken's", 'bracken', 'reviews', 'oxford', 'activism', '1956', 'nijhoff', 'mcfarland', 'ct', '1957–62']]
TOP TOKENS [['practice', 'practicing', 'word', 'future', 'start', 'happen', 'reciting', 'another', 'conscious', 'engrained'], ['practice', 'practices', 'cls', 'done', 'something', 'better', 'actual', 'n', 'taking', 'religion'], ['practice', 'improve', 'become', 'going', 'practicing', 'purpose', 'marching', 'cls', 'refers', 'practicemiddle', 'example', 'means'], ['practice', '“practice', 'deliberate', 'speaking'], ['practice', '‘', 'improve', 'practise', 'says', 'correct', 'deliberately', 'english', 'ones'], ['practice', 'instinctively', 'practicing', 'say', 'confidence.but', 'well', 'gradually', 'practise'], ['practice', 'need', '‘', 'sufficient', 'without', 'use', '’', 'practise', 'proficiency', 'telling'], ['practice', 'takes'], ['practice', '“', '2', 'act', 'rehearsal', 'session', 'subject', '1', 'time', 'day', 'questions', 'done', 'show', 'stage'], ['practice', '‘', 'practise', 'use', 'english'], ['practice', 'entertainment'], ['practice', 'england'], ['practice', 'deliberate', 'practices', 'cls', 'others', 'ways', 'practised', 'practise', 'common', 'therefore', 'teams', 'english', 'much'], ['practice', 'situations', 'theorization', 'interest', 'social', 'occurs', 'cls', 'settings', 'regardless', 'practices', 'gender', 'race'], ['practice', 'routledge'], ['practice', 'academic', 'medicus/medline/pubmed'], ['practice', 'contexts', 'practices', 'engaged', 'implicated', 'audiences'], ['practice', 'practiced', 'identifiable'], ['practice', 'time'], ['practice', 'practices', 'according', 'social', 'wrote', 'cls', 'agency', 'actions', 'outlined', 'outline', 'bourdieu', 'reaction']]
TOP TOKENS [['embroidery', 'embroidering', 'groundwork', 'clothing'], ['embroidery', 'slightly', 'shirts'], ['embroidery', 'needle.embroidery'], ['embroidery', 'printing', 'items', 'embroidered'], ['embroidery', 'century', 'appearance', 'shirts', 'back', 'sequins', 'yarn', 'stitch—remain'], ['embroidery', 'embroider', 'embroidered', 'cls', 'pattern', 'among', 'also', 'embroidering'], ['embroidery', 'embroideries', 'coordinator', 'in-charge'], ['embroidery', 'hand'], ['embroidery', 'yarn', 'today', 'thread', 'days', 'embroidered'], ['embroidered', 'embroidery', 'embroider', 'embroidering'], ['embroidery'], ['embroidery', 'embroiders'], ['embroidery'], ['embroidery', 'embroideries', 'crafted', 'comes', 'created'], ['embroidery'], ['embroidery', 'embroider', 'creating'], ['embroidery'], ['embroidery', 'hand', 'glossy', 'cls'], ['embroidery', 'based', 'computerized', 'machine', 'machines'], ['embroidery', 'region', 'embroidered', 'exist', 'ukraine']]
TOP TOKENS [['when-clause', 'time'], ['slightly', 'even', 'rephrased', 'whether'], ['11:36', 'time', '05-oct-2009'], ['2006', 'question'], ['“', 'question', 'part', 'going', 'scorching', 'probably', 'cls'], ['right', 'time', 'point', 'less', 'precise', 'knowing', 'seem', 'school'], ['cls', 'time', 'ultimately', 'decide', 'however'], ['complicated', 'two'], ['right', 'time', 'trusted'], ['‘', '2003', 'juxtaposed', 'instances', 'cases', '2'], [], [], [], ['subtlety', 'keast', 'plinking', '7.3', 'occasionally', '4.5', 'undeniably'], ['heforshe', 'emma', 'starry', 'night', 'motels', 'king'], [], ['april', 'say', '3', 'freestyle', '7', 'pain', '2020', 'skelton', 'erik', 'american', '9', 'chicago', 'video'], ['daniel', '1950', 'xi', '1997', 'worlds'], ['times', 'actually', 'sometimes', 'play', 'first'], []]
TOP TOKENS [['trespass', 'trespasser', 'trespasstres·pass·er', 'use', 'trespasser.the', 'trespassed'], ['trespass', 'trespassers', 'trespassing', 'trespasses', 'property', 'trespassed'], ['trespasser', 'trespass', 'term'], ['trespass', 'trespasser', 'trespassing', 'absolute'], ["term'trespass'is", 'trespass', 'trespasses', 'trespassing', 'prevent', 'called', 'although'], ['trespass', '‘trespass’', 'trespasser', 'trespass’'], ['trespasser', 'trespassing', 'trespass', 'trespasser’s'], ["term'trespass'is", 'trespass', 'trespasses', 'trespassing', 'prevent', 'called', 'although'], ['trespasser', 'trespass', 'trespasses', 'occupier'], ['trespass', 'even', 'generally'], ['trespass', 'land'], ['trespassers', 'd.h', 'trespasser'], ['trespass', 'pits', 'canada', 'u'], ['trespass', 'release', 'korea', 'everywhere', 'total', 'debuted', 'also'], ['trespassers', 'trespass', 'trespasser', 'trespassing', 'b'], ['trespass', 'also', 'see', 'elam', 'film', 'pizarro', 'picture', 'motion', '7', '–', 'tony', '8', "hill's", 'bona', '5', 'track', '9'], ['trespasser', 'name', 'service', '26', 'p311', '6073'], ['trespass', 'trespasser', 'activity', 'trespasses', 'term', 'intermeddling'], [], ['trespass', 'original']]
TOP TOKENS [['string', 'theory', 'strings', 'whether'], ['string', 'theory', 'physics'], ['string-theory', 'string', 'theory', 'anti-string', 'among', 'pursue', 'theorists', 'make'], ['string', 'theory', 'theories'], ['string', 'theory', 'theorists', 'approaches'], ['string', 'theory', 'show'], ['string', 'theory', 'physics'], ['string', 'theory', 'strings'], ['string', 'strings', 'theory', 'universe'], ['string', 'theory', 'strings'], ['string', 'physics'], ['stringer', 'stringers', 'continues'], ['string', 'theory', 'strings', 'corresponding', 'describe', 'branes', 'within'], ['stringer', "stringer's", 'lincoln', 'uja', 'string', 'entertainment', 'u', 'unable', 'speech', 'first', 'hall', 'december', 'science', '1978'], ['string', 'ascension', 'may', 'charlie', 'theory', '20', 'lead'], ['string', 'theory'], ['string', '12', 'jusaan', '4', 'theory', 'formerly', 'links', 'wobbly', 'aviv', 'external', 'wobblyhead', 'block'], ['stringtown', '4:14', '7:00', '4:23', '6:00', '4:20', '4:24'], ['string', 'theory', 'theorists'], ['es:stringbean', 'stringbeans', 'stringbean', 'string']]
TOP TOKENS [['perennial', 'perennials'], ['perennial', 'perennials', 'biennial', 'biennials', 'annuals', 'annual'], ['perennials', 'perennial', 'biennials', 'winters', 'annuals'], ['perennials', 'perennial', 'mature', 'classic'], ['perennials', 'perennial', 'biennials', 'annuals', 'annual', 'flowering', 'colors'], ['perennials', 'perennial', 'biennials', 'annuals', 'native', 'cls'], ['perennial', '‘perennial’', 'perennials', 'annuals'], ['perennials', 'perennial', 'biennials', 'annuals', 'annual', 'flowering', 'colors'], ['perennial', 'perennials', 'biennials', 'annual'], ['perennials', 'perennial', 'time', 'cls', 'annuals', 'gorgeous'], ['perennial', 'perennials'], ['perennials', 'perennial', 'perennializing', 'perennialize', 'naturally', 'e', 'cls', 'tillage', 'annual'], ['perennial', 'perennials', 'medium', 'term', 'terminology', 'people'], ['perenniality', 'perennial', 'perennials', 'herbaceous', 'biennial', 'see', 'annual'], ['perennial', 'critical', 'style', 'finds', 'band', 'reception', 'loops', 'vibraphone', 'received', "band's"], ['perennial', 'perennials', 'annuals', 'annual', 'commercial', 'cultivated', 'lived'], ['perennial', 'time', 'perpetual', 'status', 'drought', 'stagnant', 'associated', 'intermittent', 'cls'], ['perennial', 'american', 'local', 'statewide', '1986', 'long', 'time', '1990', "massachusetts's", 'retired', '16'], ['perennial', 'steve', 'contemporary', 'cls', '–', 'track', '2', '6', 'backing', '5', 'tranquil', 'harmonium', '9', 'mark'], ['perennial', 'perennialism', 'traditionalist', 'renaissance', '19th', 'perennis', 'ages', '1499', 'early', 'neo', 'idea', 'grown', 'esoteric']]
TOP TOKENS [['durability'], ['durability', 'electronics'], ['durability', 'various', 'columns', 'cls', 'kind', '’', 'optimisation', 'files', 'lot', 'sits', 'basic'], ['durability', '“durability”'], ['durability', 'however'], ['durability'], ['durability', 'durable', 'maintain', '–', 'adequate', 'cls', 'resealing'], ['durability', '“', 'word', 'excellent', '”', 'toughness'], ['durability', 'durable', 'maximise'], ['durability', 'comes', 'compromise', 'ensuring', 'markets', 'sole'], ['durability'], ['durability', 'technically', 'estimating', 'model'], ['durability', 'durable', 'assure', 'address', 'includes'], ['durability', 'consumption', 'durable', 'wear'], ['durability', 'stated', 'concept', '’'], ['durability', 'durable', 'perceived', 'considered', 'less', 'inconvenience', 'version', 'physical', 'latest', 'using', 'produced', 'disposable'], ['durability', "product's", 'wear', 'last', 'breakage', 'obsolescence', 'contrived'], ['durability', 'due', 'integrity', 'heavier', 'produce', 'allow'], ['durability', 'g', 'series', 'pertinence', 'november', 'medef', 'atlantique', 'marsan', 'kyoto', 'january', 'etienne', '9', '29', 'democracy', '42', 'september', 'p', 'kervegan', 'changes', 'industry', '26', 'publication'], ['durability', 'implement', 'within', 'rather', 'ongoing', "d'eclairage", 'whenever', 'caption1', 'des', 'rapporteurs', 'though', 'requirement', 'standard', 'including', 'image1']]
TOP TOKENS [['fried', 'frying', 'fry', 'goodies', 'foods'], ['fried', 'fry', 'cook', 'point', 'oily', 'healthier', 'eating', 'healthy', 'food', 'comfortable'], ['fried', 'fry', 'frying', 'popular', 'weight', 'unfortunately', 'consuming', 'non-fried', 'deep'], ['fried', 'frying', 'eating', 'eat', 'deep'], ['fried', 'frying', 'consuming', 'foods', 'concluded'], ['fried', 'common', 'frying', 'foods', 'deep', 'limiting', 'eat', 'disease'], ['fried', 'frying', 'however', 'deep', 'choice', 'eating', 'cls', 'foods', 'food'], ['fried', 'generally', 'frying', 'foods', 'deep', 'contain', 'counterparts'], ['fried', 'frying', 'eat', 'generally', 'cook', 'deep', 'foods'], ['fried', 'frying', 'eat', 'concluded', 'foods', 'food'], ['fried', 'may', 'revenue'], ['fried', 'fry', 'frying', 'foods'], ['fried', 'frying', 'methods', 'fry', 'classic', 'cultures', 'pan-fries', 'dishes', 'deep-fries', 'stir-fries'], ['fried', "fried's", 'l', 'bankman-fried', 'golda', 'american', 'david', 'politician', 'frid', 'party', 'ferdinand'], ['fried', 'frying', 'industry', 'products'], ['fried', 'fry', 'pan-fried', 'frying', 'involves', 'however'], ['fried', 'frying', 'foods', 'deep', 'eating'], ['fried', 'frying'], ['fried', 'frying', 'cls', 'foods', 'pan', 'stir'], ["frito'fried", "egypt,'fried", 'fried', 'snack', 'frying', 'dipping', 'hungary', 'cls']]
TOP TOKENS [['skin', "skin's", 'bacteria'], ['skin', 'organisms', "skin's", 'ones', 'bacteria'], ['skin', 'skins'], ['skin'], ['skin'], ['skin', 'bacteria', 'pathogens'], ['skin', 'sags', 'ailments', 'germinativum'], ['skin', 'pathogens'], ['skin', 'skinned'], ['skin', 'however', 'dehydrated', 'melanin'], ['skin', 'skins', 'sex', 'class', 'flesh'], ['skin', 'synthesizer', 'utiliz[ing', 'music', 'drums', 'band', 'called', 'art', 'sampler', 'programming', 'bass'], ['skin', 'disorders', 'diseases', 'controversy', 'included', 'skinhead', 'reprinted'], ['skin', "mammals'skin", 'physiological', 'organ', 'organs', 'dermal', 'anatomical', 'melanin', 'try', 'depigmented', 'pathogens', 'patterns', 'epidermal', 'range'], ['skin', 'skins', 'skinning', 'ski', 'skis', 'surfaces', 'snow', 'skiers', 'sealskin', 'region', 'slopes', 'use', 'maximizing', 'attuned', 'harsher'], ['skin', "skin's", 'days', 'anansie', 'silvio', '2000', 'arts', 'hons', 'southside', 'outing', "nicole's", '2020', 'techno', 'rock', 'october', '2015', 'personal', 'ed', 'performed', 'europe', 'also', '2013', 'going'], ['skin', 'striptease', 'coolidge', 'nudity', 'loken', '64', 'film', 'score', 'appearance', 'showgirls', 'mr', 'vixen', 'riffel', 'films', '100', 'number'], ['skins', 'skin', 'supremacy'], ['skin', "skin's", 'sound', "anansie's", 'artist'], ["can't", 'skin', 'meat', '2016', 'thoneick', 'impoverishment', "hell's", 'sinking', 'said', 'announced', "ain't", '2021', '2000', '2013', 'taratata', 'bisexual', 'terms', '2020', 'ost', 'september']]

Processing features:  10%|█         | 10/98 [04:41<41:22, 28.21s/it]

getting sample prompt forgetting sample prompt for 23521
 23520
getting sample prompt for 23522
getting sample prompt for 23523
getting sample prompt for 23524
getting sample prompt for 23525
getting sample prompt for 23526
getting sample prompt for 23527
getting sample prompt for 23528
getting sample prompt for 23529
getting sample prompt for 23530
getting sample prompt for 23531
TOP TOKENS [['cabinets', 'found', 'together', 'escalator', 'thing', 'common', 'family', 'received', 'inducted', 'turns', 'item', 'cabinet', 'talk'], ['etc', 'basic', 'one', 'area', 'yet', 'happened', 'set', 'always', 'priority', 'course', 'clearly', 'another', 'surprisingly', 'occasional', 'problem', 'quite', 'would', 'known', 'show', 'decided', 'though', 'seems', 'example', 'bring', 'fact', 'addition', 'never', 'especially', 'usually', 'extent', '1973', 'coming', 'tell', 'despite', 'layout'], ['“', 'reliable', 'engaging', 'iterations', 'went', 'sometimes', 'appears', 'several', 'gaining', 'note', 'recently'], ['”', 'story', 'strength', 'every', 'well', 'even', 'powerful', 'would', 'makes', 'may', '“', 'enough', 'inevitability'], ['generally', 'wrote', 'credited', '“', 'asking', 'reported', 'would', 'knew', 'around', 'according', 'even', 'carried', 'confidante', 'bringing', 'helped', 'rest', 'adroit', 'lobbyists', '”', 'messenger', 'gathering', 'package', 'known', 'replied', 'explained'], ['year', 'jan', "washington's", 'visited', '11'], ['managed', 'knew', 'officials', 'history', 'road', 'long', 'still', 'multidisciplinary', 'based', 'simple', 'ultimately', 'many', 'push', 'received', 'years', 'scrappy', '—', 'e', 'rest', 'pull', 'cobble', 'never', 'doors', 'able', 'could', 'says', '“', "let's", 'p', 'attending', 'though', 'local', 'help', '’', 'scale', 'transportation'], ['unplanned', 'likelihood', 'sections', 'according', 'tripping', 'permitted', 'fenced', 'inrunning', 'etc', 'predetermined', 'inadvertent', 'means', 'nature', 'location', 'action', 'otherwise', 'provides', 'conveyor', 'guards', 'specified', 'device', 'slipping', 'railings', 'called', 'guarded', 'speed', 'belts', 'shifter', 'pulleys', 'parts'], ['etc', 'hyderabad', 'threaten', 'death', 'might', 'house', 'stated', 'society', 'recently', 'e'], ['wide', 'circulation', 'copy'], ['omnipotence', 'idiom', 'almighty', 'hi-nrg', 'power', 'self-titled', 'street', 'based', 'active', 'general', 'oh', '1988', 'goddess', '2000', 'often', 'unlimited', '2009'], ['exists', 'doolittle', 'archive', 'part', 'w', 'stepping', 'booking', '1', '1920s', 'external', 'offices', 'brinsley', 'films', 'links', 'cnc(bois', 'action', 'munden', 'le', 'states', 'press'], ['published', 'approached', 'page', 'news', 'continued', 'behind', 'hit', 'section', 'shoppernewsnow', 'front', 'officiate', '19', 'http', 'pittsburgh', 'another', 'onto', 'com'], ['honest', 'unlucky', '500-559', 'pp213–216', 'habbitrot', 'type', 'stillborn', "miller's", 'local', 'habetrot', 'convinced'], ['dastardly', 'part-time', 'count', 'lord', 'must', 'adversary', 'smith', 'external', 'scrummy', 'films', 'mcgillicuddy', "harrison's", 'stated', 'von', 'cameos', 'pell-mell', 'sets', 'references', 'pilot', 'tongs', 'bruno'], ['courier', 'became', 'later', 'took', 'secretary', 'dallas', 'even', 'year', 'came', 'part', 'every', 'nevertheless', "amateurism'and", 'blair', "abuse'in", 'fitted', 'walls', 'recollections'], ['others', 'something', 'peaking', 'realized', 'put', 'rotation', 'may', 'special', 'placed', "z'nuff's", 'along'], ['role', 'called', 'slam-associated', 'plays', 'often', 'part', 'refers', 'slam', 'domain–containing', 'function', '32', 'implicated', 'associated', 'putative', 'leading', 'adaptor'], ['served', 'members', 'listed', 'also', 'county', 'september', 'washington', 'wisconsin', 'known', '30'], ['corresponding']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], ['hosted', 'streamers', 'guests', 'host', 'show', 'alongside', 'saying', "g4's", 'later', 'announced', '3', 'twitchcon', 'days', '2020', 'disorder', 'vegas', 'even'], ['one', 'young', 'new', 'performer', 'duo', "wing's", 'also', 'entertainment', 'revue', 'using', 'clowns', 'berrent', 'combination', '2007'], ['angel', 'served', 'one', 'company', 'inc', 'conceptualized', 'focused', "viaduct's"], ['births', 'people'], ['speaks', 'one', 'although', 'fundraisers'], [], ['serving'], ['events', "asmongold's", '2022'], ['presented', 'best'], ['notable', 'media', 'hosting', 'appeared', 'pokimane', 'youtuber', 'shows', 'various', 'include', 'unscripted', 'format', 'known', 'royale', 'nature', "austin's", 'one', 'twitch', 'broadcasts', 'number']]
TOP TOKENS [['stew', 'stewing', 'stews'], ['stew', 'stewing', 'stews', 'stewed', '“', '”'], ['stews', 'stew', 'cls', 'lid'], ['stew', 'stewing', 'bloom', 'シチュー'], ['stew', 'stews', 'stewing', 'shorter'], ['stews', 'stew', 'stewed', 'cls', 'cream', '”', 'garnished', 'mushrooms'], ['stew', 'stews', 'easier', 'ingredients', 'part', 'periods'], ['stews', 'stew', 'lid', '“', '…', 'enclose'], ['stew', 'stews'], ['stewing', 'stew', 'stews', 'casserole', 'added'], ['stew', '1944', '1952', 'liquid', '1902-1969', '1939', '1956', 'yippies'], ['stews', 'stew'], ['stew'], ['stews', 'stew'], ['stews', 'stew'], ['stews', 'stew', 'publications', 'living', '1933', 'term'], ['stews', 'stew', 'ages'], ['stews', 'stew', 'american', '1941', 'list'], ['stews', 'stew', 'cuisine'], ['stews', 'stew']]
TOP TOKENS [['coroners', 'coroner', '000'], ['coroners', 'coroner', 'deaths', 'violent', 'online'], ['coroner', 'coroners', 'cls'], ['coroner', "coroner's"], ['coroners', 'coroner', 'coroner’s', '2009', 'jurisdiction', 'results'], ['coroners', 'coroner', 'cls', 'personnel'], ['coroner', 'coroners'], ['coroner'], ['coroner', 'coroners', 'cls', 'whatdotheyknow'], ['coroner', "coroner's", 'coroners'], ['coroner'], ['coroner', 'coroners', "coroner's", 'cls'], ['coroners', 'coroner'], ['coroner', 'coroners'], ['coroner', 'coroners', "coroner's"], ['coroner', 'coroners'], ['coroners', 'coroner', "coroner's"], ['coroner', 'coroners', 'coronerscourt'], ["coroner's", 'coroners', 'coroner'], ['coroner']]
TOP TOKENS [['http://www.liasa-new.org.za/survey', 'something'], ['done', 'quality', 'survey', 'ask', 'short', 'regularly', 'decisions', 'way', 'first', 'phenomena', 'surveys', 'participants', 'starters', 'good', 'always', 'sex'], ['discipline', 'sample', 'study', 'surveys', 'survey', 'use', 'tool', 'conducting'], ['surveys', 'academics', 'population', 'appreciate', 'used', 'survey', 'intention', 'descriptive', 'face'], ['well', 'majority', 'something', 'time', 'common', 'survey', 'correspondence', 'conduct', 'observed', 'opinions', 'many', 'respondents', 'come'], ['survey', 'midterms', 'surveymonkey', 'half', '11', 'hand', 'recent', 'graceful', 'quick', 'among', '16', 'propublica'], ['survey', 'based', 'surveys', 'editor', 'b', 'christian', '2nd', 'method', 'j', 'entire', 'l', 'edition'], ['etc', 'participants', 'feedback', 'individuals', 'diagrams', 'survey', 'number', 'potential', 'documents', 'rates', 'often', 'appropriate', 'short', 'surveys', 'thoughtful', 'photos', 'post'], ['survey', 'surveys'], ['issue', 'taken', 'nature', 'form', 'evaluate', 'survey'], ['ownership', 'plats', 'prior', 'survey', 'system', 'mines', 'states', 'commerce', 'safety', 'former', 'geodetic', 'departure', 'united', 'township', 'cls', 'polls', 'line', 'great', 'six'], ['people', 'organizations', 'internet', 'directors', 'others', 'enrolled', 'goals', 'larger', 'physicians', 'include', 'malls', 'diseases', 'feelings', 'demographics', 'corners', 'surveys', 'survey', 'often', 'employed', 'behavior', 'use', 'specific'], ['survey', 'online', 'course', 'thinking', 'complete', 'surveys', 'answer', 'align', '1998', 'instruction', 'knowledge', 'questions', 'consists', 'learner', 'may', 'confidence'], ['survey', 'participants', 'incentivized', 'demographic', 'references'], ['techniques', 'purpose', 'represent', 'surveys', 'answered', 'employers', 'survey', 'interviewers', 'made', 'since', 'collection', 'accuracy', 'important', 'follow', 'random', 'uses'], ['survey', 'states'], ['employee', 'line', 'surveys', 'early', 'advent', 'conducting', 'board', 'survey', 'anonymously', 'advisory', 'commonly', 'similar'], ['choice', 'consideration'], ['survey', 'represent', 'quality', 'errors', 'employers', 'connection', 'framed', 'profession', 'complement', 'data', 'sometimes', 'create', 'random', 'surveys', 'population', 'administering', 'features', 'focus', 'correct', 'interest', 'constraints'], []]
TOP TOKENS [['supposed', 'going', 'one', 'complying', '2004'], ['d2c550efaecc2bed137f7e40255177fe', 'e0d123e5f316bef78bfdf5a008837577', 'similar', '02', 'identifiers', 'md2', 'one', 'isbn0596002815', '5', 'hashes', 'sha1', 'also', 'md5', 'sha512', '160', 'sha384', 'example'], ['‘', 'arrangement', 'people', 'dedicated', 'existing', 'complicated', 'support', 'focussed', 'emphasise', 'working', 'upon', 'archiving'], ['organised', 'rigidly', 'geographic', 'caused', 'uniformity', 'centralised', 'astronomy', 'reasoning', 'imparted', 'throughout', 'standards', 'custodians', 'geometry', 'err', 'many', 'wood', 'measures', 'stone', 'regarded', 'principally'], ['forumreplies', 'forumsreplies'], ['used', 'going', 'working', 'exercise', 'pockets', 'must', 'suppose', 'either', '1', "who's", 'cause', 'somebody', 'first'], ['allocate', 'think', 'take', 'know'], ['allocate', 'think', 'take', 'know'], [], ['based', '5/16'], [], [], [], [], [], [], ['commission', 'board'], [], [], []]
TOP TOKENS [['command', 'expunge', 'night', 'mother', 'missed', 'carefully', 'live', 'en', 'child', 'neglect', 'plot', 'meaning', 'even', 'loving', 'violent', 'noon'], ['away', 'abandoning', 'sorry', 'done', 'would', 'different', 'left', 'alone', 'knit', 'leave', 'family', 'go', 'came', 'may'], ['molester', 'living', 'spiritual', 'day', 'fetus', 'sacrosanct', "mother's", 'politeness', 'solemn', 'within', 'children', 'prepared'], ['rude', 'subjunctive', 'taught', 'thread'], ['ready'], ['compulsive', 'behavior', 'papa', 'mama', 'ritualized', 'automatized', 'normality', "momik's", 'camps'], ['compulsive', 'behavior', 'papa', 'mama', 'ritualized', 'automatized', 'normality', "momik's", 'camps'], ['reflexively', 'reflex', 'away', 'driver', 'driven', 'premeditated', 'let', 'driverless', 'behave', 'paralyze', 'soul', 'run', 'thing', 'intelligence', 'inc', "that's", 'car', 'whatever'], [], ['utilized', 'reflexes', 'away', 'fired', 'bannister', 'harry', 'eyes', 'button', 'ride'], ['ranger', 'ninja', 'pilots', 'ninjazord', 'wields', 'sabertooth', 'shogunzord', 'sword', 'pterodactyl'], ["who's", "publishing's", 'obscura', "harper's", 'action', 'special', 'reprising', 'acimovic', 'timeslot', 'accommodate', 'month', "show's", '2023', 'grown', 'first', 'narratives', 'role', 'present', "role's", "episodes'first", "chapter's", 'system', 'immersion', 'requires', '31', 'playing', 'pt'], ['composition', 'series', 'mori', 'memento'], ['combat', 'played', "game's"], ['preemptive', 'strike', 'generation', 'timeslot', "kira's", 'experienced'], ['appropriate', 'appropriateaccessed', 'cassidy', 'son', 'next', '09', '50s', 'ainsley', 'premiered', 'sibling', "franz's"], ['television', 'albany', 'sorceress', 'media', 'bill'], ['8', 'scott', "max's", 'unique', 'broadcast', 'aired', 'park', 'course', 'names', 'bill', 'companion', 'vietnam', 'episodes', 'debut'], ['gypsy', 'nanny', 'lost', 'regions', 'added', 'paranormal', 'cruising', '45am', 'go', 'hunters', 'lockdown', 'scorned', 'early', 'apart', 'broadcast', 'approximately', 'also', '1', 'schedule', 'brides', '10am', 'march'], ['appropriate']]
TOP TOKENS [['ab', 'bc', 'eb', 'aeb', 'bxfc', 'abe', 'ac'], ['b', 'x/b', 'bc', 'bd', 'ab', '√ab', 'ad'], ['ab', 'bc', 'eb', 'bd', 'bf', 'ad', 'bde', 'abc', 'db'], ['2ab2', 'ab2', 'bd2', 'bd', 'bc', 'ab²', 'bd²', 'bc2', 'δabc', 'cb', '∆abc', 'c', 'ca', 'ac', '7ab', 'ac2', '2ac2', 'db'], ['ab', 'bc', 'adb', 'eab', 'bcd', 'bd', 'eba', 'cdb', 'ad'], ['ab,ac', 'ab,bc', 'bc', 'ba=bc', 'ab', 'bc/2', 'a-e-c'], ['ab,ac', 'ab,bc', 'bc', 'ba=bc', 'ab', 'bc/2', 'a-e-c'], ['bc', 'ab2', 'bd2', '2bd2', 'bd', 'adb', 'ab', 'abd'], ['ab', 'hb', 'c', 'de'], ['bd', 'ab', 'b', 'bl', 'bh', 'lb', 'ad', 'bk', 'ak', 'ap'], ['ab', 'bc', 'ac', 'ob', 'rb', 'bo', 'aq', 'ar', 'qc'], ['ab', 'b0', 'bc', 'a0', 'ac', 'c0'], ['bc', 'bm', 'bf', 'ngb', 'blm', 'bd', 'bl', 'bmn', 'c', 'ac', 'blin', 'ae', '2be', 'abe', 'bac', 'cd', 'bn', 'cg', 'f', 'abec'], ['ab⋅cd', 'bc⋅da', 'bd', 'ac⋅bd', "a'b", "b'and", 'ck⋅bd', "b'c", 'ak⋅bd', 'ac', '±ac', 'ak', "c'form", '·'], ['b', 'ab', 'bd', 'ad', 'acb', 'cb', 'c', 'cd', 'bo2', 'ac', 'db', 'ba', 'aq', 'ae', 'bp'], ['ab', 'b', 'c', 'a−2', 'ac', 'a−1', 'a2', 'ec', 'β'], ['ab', 'eb', 'b8', 'b', 'bc', 'bd', 'b3', 'ad', 'b0', 'b7', 'aa', 'bb', 'b6', 'fb', 'b2', 'b1', 'd6', 'ac', 'ba', 'a0', 'd2', 'a8', 'a6', 'bf', 'a3', 'd5', 'a7', 'b9', 'a5', 'ae', 'df', 'bgcolor', 'e6', 'e8', 'a4'], ['b', 'c'], ['ab', 'bd', 'cb', 'bc', 'bq', 'b', 'c', 'ac', 'cd', 'pa', 'bn'], ['b', 'ab', "a'b'c'is", 'bc', 'b2', 'zpb', "a'b'c'be", "a'b'c'which", 'xpb', '2b2', '3b2c2', 'pb', 'bzx', 'gbpb', 'abc', 'bp', 'a2b2', 'c', 'cp', 'a6', 'b4']]
TOP TOKENS [['metamorphism', 'metamorphic'], ['metamorphic'], ['metamorphic', 'metamorphism', 'rock'], ['metamorphism'], ['metamorphism'], ['metamorphism', 'metamorphic', 'metamorphismchemical', 'undergoes'], ['metamorphism', 'metamorphic', 'rocks', 'usgs'], ['metamorphic', 'metamorphism', 'cls', 'rocks', 'grade'], ['metamorphic', 'metamorphism', 'takes', 'rocks', 'rock'], ['metamorphism', 'metamorphic'], ['metamorphic', 'metamorphism'], ['metamorphism'], ['metamorphism', 'metamorphic', 'cls'], ['metamorphism', 'metamorphic', 'occurs', 'takes', 'produce', 'transforms'], ['metamorphism', 'metamorphic'], ['metamorphism', 'metamorphic', 'distortion', 'rocks', 'cls', 'rock', 'called'], ['metamorphism', 'metamorphic', 'takes'], ['metamorphic', 'metamorphism', 'rocks'], ['metamorphism', 'metamorphic', 'history', 'many', 'reveal', 'formed'], ['metamorphism', 'metamorphic', 'rocks']]
TOP TOKENS [['reliving', 'astrologer', 'forgotten', 'people'], ['kilogram', 'nationalities', 'hallowed'], ['kilogram', 'international', 'object', 'standard', 'si', 'physical'], ['kilograms', 'kilogram'], ['“a”', 'world', 'kilogram', 'people'], [], ['kilogram', 'kilograms', 'people', 'iridium', 'quantum', 'night', 'small', 'single', 'one'], ['kilogram', 'homes', 'ascertaining', 'object', 'inanimate', 'combination', '“'], ['kilogram', 'throwback', 'it’s', 'set', 'international', 'man’s', 'quaint', 'people', 'copies', 'object', 'physical'], ['kilogram', 'kilo', 'speak', 'international', 'industry'], [], [], ['starrer', 'nikhil', 'siddhartha', 'india', 'indian', '2023', '5', 'abhilasha', 'awes'], ['nikon'], ['aeronaut'], ["men's", 'cyclo-cross', '1st'], ['nikon', '1', 'spain'], ['nikon', '35mm'], ['city', 'esbjerg', 'jannik', 'central'], ['nikon', 'ascetic', "nikon's", 'itinerant', 'nikephoros']]
TOP TOKENS [['born'], ['born'], ['born'], ['born', '19', 'becoming'], ['born', 'birthdate', 'would', 'changed', "asimov's", "that's", 'get'], ['raised', 'born', '1893', '3', 'parents', 'feudenheim'], ['born', 'detail', 'education', '1918', 'parents', 'feliks', 'study', 'living'], ['born', '‘', 'schooling', 'attending', 'received', 'graduated', '1946', '6', 'connecticut', 'started', 'academy', 'july', 'life', '–', 'marvin', 'due'], ['born', 'family', 'studied'], ['born'], ['born', 'life', 'early', 'ridge', '20', 'parents', 'enrolled', 'lived', 'education', 'jr', 'field', "army's", 'became'], ['born', 'grew', 'attended', 'raised', 'went', '14', 'june', 'whose', 'enrolled', 'queens', 'school', 'parents', '13', 'age'], ['born', 'educated', 'attended', 'growing', 'life', 'early', '6', 'november', '1988', 'school', 'grandfather', 'nee', 'also', 'grade'], ['born', 'raised', '19', "gyllenhaal's", 'descent', 'angeles', 'december', 'nee', 'birthday', 'grandfather', 'gyllenhaal'], ['raised', 'born', '12', 'attended', 'february', 'roscommon', 'earned', "kavanaugh's", 'school', '1965'], ['born', 'b', '8', 'life', 'october', 'early', 'attended', 'descent', 'cambridge', '1970', 'education', '1946', '–', 'years', 'ancestry'], ['grew', 'raised', 'born', 'educated', '20', 'life', 'mother', 'tyre', '1964', 'early', 'joined', 'baghdad', 'april', 'including', 'school'], ['born', 'birth', 'grew', 'life', 'early', 'raised', 'attended', 'chiltern', 'mountnorris', 'birthday'], ['birth', 'born', 'attended', "lewis's", 'moved', '29', 'descent', 'ballintubbert', 'lived'], ['born', 'raised', 'early', 'attended', 'life', 'graduated', '26', 'education', 'pursuing', 'descent', 'march', 'school', 'encouraged', 'immigrated', 'nee', 'go', 'career', 'hamilton', '–', 'crossmaglen']]

Processing features:  11%|█         | 11/98 [05:10<41:09, 28.39s/it]

getting sample prompt forgetting sample prompt for 23533
 23532
getting sample prompt for 23534
getting sample prompt for 23535
getting sample prompt for 23536
getting sample prompt for 23537
getting sample prompt for 23538
getting sample prompt for 23539
getting sample prompt for 23540
getting sample prompt for 23541
getting sample prompt for 23542
getting sample prompt for 23543
TOP TOKENS [['gogh', 'gogh’s', 'van', 'money', 'france', 'name', 'friendship', 'wasn’t', 'paris'], ['gogh', "gogh's", 'gogh´s', 'van'], ['gogh', 'van', 'sending', '1880', 'overwhelming'], ['gogh', "gogh's", 'van', 'vincent', 'sunflowers', 'willem', 'art', 'hague'], ['gogh', "gogh's", 'van', '1888', '1887', 'france', 'condition', 'colleagues', 'remy', 'productivity', 'late'], ['gogh', 'van', '1889', 'vincent', 'portraits', 'early'], ['gogh', 'vincent', 'van', 'man'], ['gogh', "gogh's", 'van', 'london', 'paris', 'cls', '1888', '1880', 'brabant', 'translated', 'period', 'time', 'destitute'], ['gogh', 'van', 'vincent', 'poverty'], ['gogh', 'van', 'later', '1890', 'today', '’', 'world'], ['gogh', 'london'], ['gogh', "gogh's", 'gogh-kaulbach', 'gogh-bonger', 'van', 'director', 'dutch', 'lothar', '1862–1941', 'born', '1817–1885', '2007', 'film', '1974'], ['gogh'], ['gogh', 'van', 'links', 'đorđe', '1990', 'milisavljević', 'references', 'se'], ['gogh', 'van', '’', 'summer', 'undeterred'], ['gogh', 'van', 'fields', 'vangoghgallery'], ['gogh'], ['gogh', "gogh's", 'van', 'vincent', 'terminated', '”', 'cie', 'however'], ['gogh', 'van', '1885', 'spirit', 'art', "one's", 'portrait', "d'orsay", 'one'], ['gogh', "gogh's", '1890', 'van', 'vincent', 'suffered', 'co', 'exacerbated', 'involved', 'time']]
TOP TOKENS [['one'], ['looked', 'profile', 'stand', 'u', 'around', 'scourge', 'believer', 'values', 'seen', 'showed', 'surrounded', 'us', 'people', 'wonderful', 'many', 'inspire', '’', 'could', 'involved', 'entered', 'allowed', 'going'], [], ['guest', 'actors'], ['vatican', 'francis.pope-shooter', 'see', "caesar's", 'successor', '2944', 'succeeds', '2992.beowulf', 'it’s', 'person', 'tell.chicago’s', 'november', 'get', 'one', '8', '11', 'taught', 'obscurely'], ['annually', 'preceptorships', "patients'presence", '31', 'participate', 'invited', 'permitted', 'conducting', 'conducted', 'preclinical', 'residents', 'interviews', 'study', 'summer', 'receive', 'approximately', 'selected', 'held', 'completed', 'across', 'piloted', 'year', 'addresses', "faculty's", 'include', 'faculty', 'preclerkship', 'devote', 'time'], ['standing', 'leading', 'consulting', 'faculty', 'followership', 'practice', 'visioning', 'professor', 'avolio', 'author', '01', 'patricia', 'associates', 'organizations', 'social', 'president', '05', 'management', 'executive', 'j'], [], ['upstanders', 'peers', 'defend', 'peer', 'intervene', 'come', 'social', 'witness', 'bullied', 'bullies', 'often', 'respond', '4'], ['house', 'fifty', 'decorated', 'historical', 'families', 'white', 'event', 'power', 'houses', 'influential', 'houseperhaps', 'observance', 'wa', 'underwent', '1800', 'every', 'memorable', 'since', '1981'], ['stars', 'appears', 'role', 'guest', 'recurs', 'appear', 'plays', 'sees', 'appearances', 'portrayer', "serkis'acting", 'known', 'characters', 'played', 'cast', 'actress', 'sympathise', 'involved', 'personally', 'crowley', 'earn', 'oyelowo', 'celebrity', 'two', 'day', 'likeness', 'though', 'recurring', 'approached'], ['polson', 'siena', 'grace', 'elchaar', 'jacinta', 'role', 'shostak', 'poletti', 'avital', 'hall', 'levett', 'dearth'], [], ['appearances', 'actor', 'appears', 'guest', 'joined', 'stars', 'appeared', 'cast', 'portraying', 'appear', 'appearance', 'philippa', 'actress', 'role', 'series', 'roles', 'exploring', 'returns', 'recurring', 'backstory', "louis'backstory", 'since', 'walkinshaw', 'show', 'character', 'characters', 'gallagher', 'writers', 'makes', 'coleman', 'one', 'features', 'episodes', 'continuing', 'introduced'], ['dynasty', 'driscoll'], ['celebrities', 'appearances', 'regulars', 'parsons', 'included', 'bremner', 'howard'], ['actor', 'costume'], ['cast', 'celebrities', 'current', 'member', 'british', 'appeared', 'celebrity', 'participating', '2022', 'kershaw', 'aired', 'former', '2023', 'announced', 'season', 'members', 'commissioned', 'show', 'seasons', 'series', '25', '2015', 'illness'], ['appearance', 'stars', 'appears', 'appeared', 'appear', 'guest', 'recurring', 'features', 'actress', 'role', 'cast', 'jordon', 'mcgerry', 'reprised', 'howe', 'made', 'favourite', 'joined', 'reappearing', 'character', 'introduced', 'actor', 'series'], ['starring', 'guest']]
TOP TOKENS [['swelling', 'body', 'swollen', 'slight', 'widespread', 'cause', 'unexplainable', 'fluid'], ['swelling', 'swollen', 'unexplained', 'visible', 'widespread', 'illness', 'essence', 'cls', 'external'], ['swelling', 'prevent', 'body', 'swells', 'slight'], ['swelling', 'causes', 'cases', 'severe', 'face', 'caused', 'eyelids', 'experience'], ['swelling', 'others', 'result', 'swell', 'swells', 'cause', 'decrease'], ['swelling', 'cause', 'may', 'swollen', 'joint', 'makes', 'better', 'include', 'make', 'always', 'worse', 'go', 'fever', 'injury'], ['systems', 'temperature', 'upon', 'unlimited', 'montmorillonites', 'swelling', 'referencestager', 'polymers', 'limited', 'life'], ['swelling', 'cause', 'causing', 'reducing', 'body'], ['swelling', 'pressure', 'brain', 'noticed'], ['swelling'], ['capacity', 'neutron-induced', 'absorbed', 'cross-sectional', 'swelling'], ['swelling', 'neutron-induced', 'energy'], ['swelling', 'resolve', 'gland', 'parotid', 'usually', 'develops', 'vomiting', 'help'], ['shrink–swell', 'swelling', 'capacity', 'free', 'assay'], ['swelling', 'swollen', 'w1', 'filter', 'capacity', 'min', 'superabsorbent'], ['swelling', 'parish', 'english', 'gum', 'band', '1923–1999', '1970s', 'fop', 'england', '1960–2009', 'educator'], ['swelling', 'often'], ['swelling', 'cause', 'growing', 'onset', 'result', 'may', 'slowly', 'painful', 'nodes', 'particularly', 'term', 'leukemia', 'enlargement', 'inflammation', 'include', 'part', 'due', 'node', 'area'], ['swelling', 'eliminated', 'cytoplasmic', 'severity', 'cellular', 'form', 'reversible', 'clear', 'cloudy', 'within', 'nucleus', 'ible', 'irreversible', 'many', 'may', 'occur', 'organ', 'due'], ['swelling', 'swollen', 'becomes', 'pain', 'inflammation', 'testis', 'sometimes', 'testicles', 'issues', 'infants']]
TOP TOKENS [['hairs', 'hair', 'bald', 'comes', 'scalp', 'heads', 'society'], ['hair', 'hairthe', 'haira', 'hairhair', 'hairs', 'scalp', 'bald', 'hairgeneral'], ['hair', '13', 'strands'], ['hair', 'scalp', 'protein', 'causes', 'ceased', 'loss', 'lost'], ['hair', 'locks', 'grows', 'baldness', 'including', 'keratin', '–', 'cells'], ['hair', 'hairs', 'baldness', 'growth', 'disappearance', 'stage', 'scalp', 'hairline'], ['hair', 'hairs', 'baldness', 'hairstyles', 'hairline', 'scalp', 'people', 'locks', 'bald'], ['hair', 'hairs', 'scalp'], ['hair', 'hairs', 'cls', 'scalp', '2', '3', '–', 'us'], ['hair', 'hairs', 'scalp'], ['hair'], ['hair', 'mechanic', 'pleasure', 'scholar', 'length', "hair's", 'hairy'], ['hair'], ['hair'], ['hair', 'revealed'], ['hairs', 'hair', 'scalp', 'growth', 'miniaturization'], ['hair', 'baldness', 'hairs', "hair's", 'hairline', 'causing', 'scalp', 'alopecia'], ['hairs', 'hair', 'haired', 'scalp', "women's", "one's", 'people'], ['hair', 'hairs', 'baldness', 'balding', 'scalp', 'alopecia'], ['hair', 'unkempt', 'length', 'shave']]
TOP TOKENS [['pastoral', 'pastoral."—ann-maria'], ['pastoral', 'pastoralists', 'ancient', 'rustic'], ['pastoral', 'bucolic', '‘'], ['pastoral', 'pastorala'], ['pastoralists', 'pastoralism', 'pastoralist', 'pastoralistst', 'soil'], ['pastoralism', 'pastoral', 'pastoralists'], ['pastoralists', 'pastoralism', 'pastoral', 'pastoralist', 'citizenry', 'sharing', 'time', 'zation'], ['pastoral'], ['pastoral'], ['pastoral', 'elaborate', 'literature'], ['pastoral', 'pastorale', 'disambiguation'], ['pastoral', 'pastorale'], ['pastorale', 'pastoral'], ['pastoral', 'rustic', 'else'], ['pastoral', 'pastorals', 'defines'], ['pastoral', 'subtlety'], ['pastoralists', 'pastoral', 'pastoralism', 'cls', 'expenses', 'regional'], ['pastoral', 'originally', 'reviews', 'shawn', 'early', 'universal', 'joseph'], ['pastoral', 'simply', 'called'], ['pastorales', 'pastorale', 'pastoral', 'common', 'gesù', 'epistles', 'op.6', 'piffero', 'several', 'rossini', "bellman's"]]
TOP TOKENS [['urdu'], ['urdu'], ['urdu', 'hindi-urdu', 'urdū', 'ˈʊərduː'], ['urdu'], ['urdu'], ['urdu', 'کرنا', 'contexts'], ['urdu', 'hindi-urdu', 'communities', 'propriety', 'asia', 'pakistani'], ['urdu', 'rate'], ['urdu', 'english/urdu', 'amazon.com'], ['urdu', 'hindi-urdu', 'world', 'https://uwmadison.zoom.us/j/98831909403?pwd=nvq0autiylbtqkh4ajbuenr0cmfydz09'], ['urdu', 'urdu-language'], ['urdu-language', 'urdu'], ['urdu', 'united'], ['urdu', '1311', 'deccan', 'language', 'territory', 'century', 'words', 'descent', 'نظم'], ['urdu'], ['urdu', 'prospects', '4'], ['urdu', 'aiwan-e-urdu'], ['urdu', '000', 'society'], ['urdu', 'language', 'kashmir', '2001', 'total'], ['urdu']]
TOP TOKENS [['developers', 'developer', 'development', 'worked', 'ins'], ['developer', 'developers', 'development', 'job', '2000s', 'components', 'websites', 'layouts', 'backend'], ['developers', 'developer', 'development', 'level'], ['developers', 'developer', 'market', 'development', 'software', 'develop'], ['developer', 'developers', 'development', 'language', 'call', '3', 'code'], ['developers', 'developer', 'development', 'it’s', 'appear', 'what’s'], ['developer', 'developers', 'many', '10', 'indeed'], ['developer', 'developers', 'development', 'projects', 'traditionally'], ['developer', 'developers', 'development', 'projects', 'traditionally'], ['developers', 'developer', 'must', 'development'], ['developers', 'developer'], ['developer', 'developers', 'dev', 'software', 'developing', 'devrel'], ['developers', 'developer', 'development', 'frameworks', 'software', 'however'], ['developers', 'developer', "developers'attention", 'dev', 'development', 'software', 'model', 'aka', 'products', 'coding'], ['developer', 'developer(s', 'company', 'website', 'team'], ['developers', "developers'use", 'developer', "developers'needs", 'popularizing', 'develop', 'party', 'supporting', 'including', 'desires', 'aka', 'understanding', 'dx', 'community', 'retain', 'potential'], ['developers', 'developer', 'software'], ['developers', 'developer', 'technical', 'engine'], ['developers', 'developer', 'date', 'development', 'becomes', 'work', 'game', 'project', 'point', 'may', 'hours'], ['developers', 'development', 'software', 'xd', 'asp', 'web', 'end', '–', 'inkscape', 'stack', 'html', 'deal']]
TOP TOKENS [['idea', 'know', 'even', 'competent', 'sandtrap', 'coins', 'knew', 'finally', 'learn', 'order', "people's", 'well', 'matter'], ['us', 'learned', 'step'], ['skills', 'agencies', '’', 'responders', 'get', 'understanding', 'involved', '“', 'went', 'course', 'guard', 'canada', 'resources', 'acting', 'many', 'others', 'rcmp', '”', 'throughout', 'day'], ['elon', 'melts'], [], ['using', 'get'], ["runners'up", 'cls', 'sexual', 'gammon', 'harrassment', 'toxic', 'workplace', 'energy', '‘', 'techlash', 'gaslighting', 'health', 'incel', '’', 'contexts', 'crucibles', 'along', 'senses', "adjective'toxic'reflects", 'cakeism', 'google', 'even', 'workloads'], ['works', 'aaw'], ['boyfriend', 'later', 'crossing', 'comes', 'weather', '—', 'night', 'site', "leutze's", 'thing', 'triumphantly', 'boarded', 'plus', "that's"], ['’', 'people', 'experience', 'somebody', 'flows', 'dealing', 'okay', 'know', 'arise'], ['unenthusiastic', 'performer', 'clearly', 'however', 'chanie', 'passes', 'get', 'reversing', 'attempts', 'adept', 'whatsoever', 'go', 'experience', 'tyler', 'passed', 'though', 'graduate', 'erratic', 'ends', 'driving', 'challenge', 'jason'], [], ["game's", 'week', 'followed', 'finding', 'catch', 'carlson', 'completing', 'john', "hartley's", "hasselbeck's", 'pass', 'punishing', 'back', 'threw', 'new', 'tried', 'making', 'delivered', 'duel'], ['english-language', 'directed', 'films', 'russian-language', 'written', 'spy'], ['2010–11', 'lists', 'external', 'people', 'links', 'american', '2012–13', '2011–12', 'overview', '9', '27', 'recruits', '18', '11', '22', '17', '2010'], ['english', 'american', 'debauchery', 'cross', 'lgbt', "bearer's", 'films'], ['sprint', 'christian', 'member', 'across', 'detour', "andersen's", 'complete', "season's", 'completing', 'operated', 'chek', 'roundabouts', "leg's", "confectioner's", 'unk', 'denmark', 'obstacle', 'roadblock', 'copenhagen', 'kok'], [], ['though', 'nailing', 'falcons', "brees'54", 'back', 'even', 'hooking', "porter's", 'coming', 'yet', 'quarter', 'would', 'panthers', 'afterwards'], ['michael', 'vs', 'back', 'booting', 'game', 'however', 'week', 'started', 'booted', 'completed', 'pass', "turner's", 'followed', 'streak', 'took', 'redskins', 'yet']]
TOP TOKENS [['mrna', 'messenger', 'sneak', 'technology'], ['mrna', '25', 'vaccines'], ['mrna', 'technology'], ['mrna', 'mrnas'], ['mrna', 'develop', 'vaccines'], ['mrna', 'cls', 'says', 'technology', 'get', 'cells'], ['mrna', 'mrnas', 'technology'], ['mrna', 'technology', 'vaccines', 'vaccine', 'cls', 'personalized', 'cells'], ['mrna', 'technologies', 'track', 'cls', 'therapies', 'brought', 'vaccines', 'therapeutics', 'component', 'presents'], ['mrna', 'protein', 'cls', 'vaccine'], ['mrna', 'protein'], ['mrna', 'made'], ['mrna', 'prior', 'vaccines', 'percent'], ['mrna', 'vaccines', 'immunity', 'antigens'], ['mrna', 'development', 'develop', 'technology', 'encapsulated', 'made', 'vaccines', 'designed', 'biotechnologies', 'packaged', 'amplifying', 'year', 'started'], ['mrna', 'moreover', 'gene'], ['mrna', 'messenger', 'molecules', 'molecule', 'cytoplasm', 'rna'], ['mrna', "mrna's", 'fragments'], ['mrna', 'sequences', 'mediated', 'containing'], ['mrna', 'mrnas', 'localization', 'transcripts', 'rnas', 'level', 'player', 'cytoplasm']]
TOP TOKENS [['pituitary', 'hypopituitarism'], ['pituitary', 'hypopituitarism'], ['pituitary', 'pituitaritis', 'etiopathogenetically', 'infundibuloneirohypophysitis'], ['pituitary', 'hypopituitarism', 'sellar', 'sella', 'size', 'cls'], ['pituitary', 'menstrual'], ['pituitary', '05/08/2014'], ['pituitary', '05/08/2014'], ['pituitary', 'pituitaritis', 'hypopituitarism', '8', 'cls', '1'], ['pituitary', 'common', 'menstrual', 'hormones', 'irregular'], ['pituitary'], ['pituitary', 'hyperpituitarism', 'hypopituitarism', '22', '14', 'well', 'fernandez'], ['pituitary'], ['pituitary', 'hypopituitarism'], ['pituitary'], ['pituitary', 'tumors', 'cells', 'research', 'frequently', 'acromegaly'], ['pituitary', 'tissue', 'hormone', 'adenohypophyseal', '30', 'hyperpituitarism', 'hypothalamus'], ['pituitary', 'symptoms', 'hypopituitarism', 'gland', 'sella'], ['pituitary', 'hypothalamus'], ['pituitary'], ['pituitary', 'previously', 'cls', 'well', 'occasionally']]
TOP TOKENS [['sumo'], ['sumo', 'years'], ['sumo', 'title', 'period', 'history', 'times', 'years'], ['sumo', 'tokyo', 'りすきの'], ['sumo', 'tokyo', 'りすきの'], ['sumo'], ['sumo', 'action', 'sport', 'slip', 'fukuoka', 'ring', 'falls', 'popular'], ['sumo', 'attention', 'technique'], ['sumo', 'match', 'annual', 'sand', 'cls', 'years'], ['sumo', '2007'], ['sumo', 'sumocode', 'sumopaint', 'album', 'sumovideo', 'sumotunes', 'sumophoto', 'tata', 'comics', 'wrestling'], ['sumo', 'sumoylation', 'sumo1', 'sumo2', 'occurs'], ['sumo', 'sumoylated', 'sumoylation', 'sumo1', 'sumo2'], ['sumoylation', 'sumo1', 'sumo', 'sumoplot', 'sumosp', 'cs'], ['sumoylated', 'sumo', 'sumo-1', 'sumoylation', 'ligases', 'modifier'], ['sumoylation', 'sumo2', 'sumo', 'sumo1'], ['sumo', 'sumo.app', 'sumopaint', 'called'], ['sumoylation', 'sumo', 'sumo1', 'sumo2', 'sumo3', 'sumosp', 'sumoplot', 'sumo4', 'links', 'peptidase'], ['sumo', '2021', '2019'], ["sumo's", 'sumo', 'setback', 'word', 'heya', 'association', 'japan']]
TOP TOKENS [['11ac', '802', '11n'], ['802', '11b', '11n', '11ac', '11a'], ['11n', '11ac', '802', 'one'], ['11n', '11ac', '802', '11b'], ['11ac', '802', '11n', '11b', 'mimo'], ['802', '11ac', '11n', '11b'], ['802', '11ac', '11n', '2', '11ax'], ['802', '11ac', '11n', '11b', '11a'], ['802', '11n', '11ac', '11b', '11a', '11g', '2'], ['802', '11ac', '11', '11b', '11ax', 'also', 'terminals'], ['802', '11n', '11ac', '11ax', '1', 'cf', 'year'], ['11ac', '11a', '11b', '11n', '802', '11ax', '11', '11g'], ['11ac', '802', '11b', '11g', '11a', '11n', '11ax', 'throughput'], ['802', '11n', '11a', '11g', '11', 'available', '2', 'increased', 'techniques'], ['802', '11n', '11', 'information', '2', 'band', 'however', '7', 'fi', 'mhz', 'america', 'one'], ['11a', '802', '11b', '11h', 'areas', 'advantage', 'give', 'countries', 'environment'], ['802', '11b', '11g', '11a', '11', '22mhz', '13', '9', '20mhz', '16', '5', '6'], ['802', '11a', '11b', '11g', '0', 'rate', '16', '11', 'correspondingly', '2', 'microseconds', '5'], ['11b', '802', '11a', '11g', '0', 'however', 'correspondingly', 'g', 'bandwidth', 'technology'], ['11n', '11ay', '11ax', '11ad', '802', '11ac', '2x', '80mhz', '3', 'spectrum', '1', '160mhz', '2', 'vs', 'higher']]

Processing features:  12%|█▏        | 12/98 [05:40<41:08, 28.70s/it]

getting sample prompt for 23544
getting sample prompt for 23545
getting sample prompt for 23546
getting sample prompt for 23547
getting sample prompt for 23548
getting sample prompt for 23549
getting sample prompt for 23550
getting sample prompt for 23551
getting sample prompt for 23552
getting sample prompt for 23553
getting sample prompt for 23554
getting sample prompt for 23555
TOP TOKENS [['linux', 'requirement', 'i.e', 'etc', 'let’s', 'strengthen', 'determined', 'run', 'anyone', 'provides', 'kivy', 'pip', 'must', 'necessary', 'windows', 'size', 'contain', 'particular', 'either', 'row_default_heightproperties', 'make', 'automatically'], ['someone', 'kiva'], ['kier-an', 'kieran.see', 'u.s', 'kirwan', 'sixth', 'kilian', 'kilean', 'kieran', 'kiean', 'kierna', 'kiernan', 'kirone', 'kienen', '1573', 'kirwen', 'kieron', 'kierni', 'curran', '34', '1388', 'kienan', 'mean'], ['takes', 'smudge', 'point', '–', 'underline', 'kieron', 'men', 'seems', 'singlehandedly', 'utterly', 'rising', 'huddling', 'williamson'], ['oblast', 'definition', 'kirov', '480,411', 'kirovˈkɪər'], ['playing', 'kivy', 'shows', 'use', 'transform', 'audio', "kivy's", 'internals', 'little', 'issues', 'reading', 'used', '2022', 'architecturelast', 'helps'], ['kicad', 'shift', 'ran', 'one', 'orange', 'straightforward', 'professional', 'impressions', 'new', 'systems', 'file', '’', '“', 'begin', 'use', 'since'], ['kicad', 'shift', 'ran', 'one', 'orange', 'straightforward', 'professional', 'impressions', 'new', 'systems', 'file', '’', '“', 'begin', 'use', 'since'], ['n', '1897', 'also', 'entry', 'kir', 'm.a', '1:5', 'found', 'illustrated'], ['albuquerque', 'world', 'kiva', 'kivazip', 'countries', 'rituals', 'institutions', 'loans', "kiva's", '99', 'social', 'california', 'operates', 'former', '98', 'level', 'area', 'public', 'collect', '2005'], ['379', 'antonio', 'january', '450', 'bottom', 'end', '3', '330', 'look', 'hit', 'american', 'inning', 'appeared', 'bobby', 'force'], ['1903–1942', 'southeast'], [], ['soltanpour'], ['kibioctet', 'racism', 'kio', 'keep', 'kin', 'code', 'architecture'], [], ['official'], ['debut', 'p300-cbp', 'country', 'nicknamed', 'osaka', '1981', 'narrowcast', 'kyōto', '1980s', 'kixtart', 'family', 'kixx', 'radio', 'british'], ['kirchhoff', '1963', 'kip', 'kipps', 'heidelberg', 'kip-up', 'laos', 'kipp', 'disambiguation', 'body', 'cip/kip', 'aceh', 'artistic', 'election', 'kips'], ['series']]
TOP TOKENS [['cut', 'force', 'girth', 'society', '978-1-55092-421-3', 'new', 'flat', 'rob', 'notch', 'plural', 'posts'], ['entirety', 'lies/is', 'allow', '“the', '“thanks', 'voluminous', 'recalled', 'gist'], ['gitops', '’', 'git', 'produce', 'parts', 'maybe', 'well', 'chance', 'term', 'broadly', 'effective', 'actually', 'taking', 'whatever', 'brand'], ['denouement', 'languages', 'evolved', 'toit', 'cast', 'generously', 'carefully', 'tougher', 'time', 'added', 'giono', 'known', 'aside', '1954', "giono's", 'wrote', 'sylvie', 'francaise', 'ever', 'war', 'innocent', 'died', 'invention', "l'academie", '1955', 'end'], ['sheer', 'gimmick', 'versions', 'intellect', 'human'], ['gitops', 'comfortable', 'organizational', 'platform', 'applications', 'solutions', 'management', '’', 'experience', 'case', 'teams'], ['quality', 'giclée', 'embellished', 'result', 'giclee', 'right', 'name', 'hand', 'mb', '“digital”', 'printed'], ['github', 'use', 'means', 'local', 'io', 'listing', 'access'], ['space', 'files', 'disk', 'working', 'program', 'among', 'gidzip'], ['650', 'b', 'brown', 'last', 'ostentatiousness', 'hillsborough', '725', 'never', 'contoured', 'survived', 'impressed'], ['case', '2010', '1999', 'vision', 'award'], ['born', 'defined'], ['charles'], ['1302', 'satellite', 'started', 'gieten', 'lies', '1804', 'part', '14', 'contained', 'hunze', '1768', 'built', 'least', 'tower'], ['giso', 'gieze', 'kerzen', '1872–1956', 'gies'], ['living', 'based', 'head'], [], ['june', 'former', 'individualized', 'new', 'original', 'contractor', 'bros', 'back', 'announced', '2020'], ['itthihaad', 'national', 'groupe', 'icao', 'primary', 'disambiguation', 'investment', 'express', 'south', 'innocence', 'pool'], ['1938']]
TOP TOKENS [['tollbooth', 'milo', 'phantom', 'well-dressed', 'kingdom', 'bored-with-life', 'humbug', 'different', 'say'], ['tollbooth', "milo's", 'www.homeschoolshare.com/phantom_tollbooth.php', 'milo', 'phantom', 'humbug', 'digitopolis', 'dictionopolis', 'homeschoolers', 'sight', '3-6', 'whimsical', 'bananagrams', 'valley', 'sound', 'doldrums'], ['tollbooth', 'milo', 'unappreciative', "milo's", 'phantom', 'toys', 'learned', 'beyond', 'cls', 'one', 'sight', 'certain', 'princesses', 'without', 'situations', 'beauty'], ['tollbooth', 'phantom', 'macrabe', 'milo', 'faintly', 'reality', 'beyond', 'rhyme', 'everyone', 'dictionopolis', 'sight', 'humbug', 'doldrums', 'onward', '’', 'great'], ['tollbooth', 'milo', 'milo’s', 'phantom', '“get', '“grown-down”', 'ignorance', 'whirlwind', 'conclusions'], ['tollbooth', 'milo', 'tollbooth</em', "milo's", 'em>the', 'phantom', 'nevertheless', 'well-rounded', 'real-word'], ['tollbooth', 'milo', 'phantom', 'named', 'bizarre', "film's", 'enters', 'classic', 'one', 'back-story', 'memorable', 'urban', 'tock', "children's"], ['milo', 'tollbooth', 'befriends', 'attention', 'rhyme', 'pompous', 'reason'], ['milo', 'tollbooth', 'tollbooth</em', "tollbooth's", "milo's", 'phantom', 'em>the', 'beyond', 'quest', 'rhyme', 'em>"real'], ['phantom', "milo's", 'tollbooth', 'milo', 'quiet', 'shimmering', 'daydreaming'], ['milo', 'trivium', 'body', 'phantom', 'foray', 'tollbooth', 'adventures', 'candido', 'mathemagician', 'goldwyn', "tollbooth's", 'faintly', 'dictionopolis'], ['one', 'tollbooth', 'milo', "milo's", 'phantom', 'rooftops', '1970', 'beyond', 'us', 'spain', 'hearts', "book's", 'get', 'hebrew', 'spirit', "people's"], ['bedtime', 'alastair', 'elspeth', 'frequent', "duck's", "bertie's", 'exclaiming', 'escapade', "children's", 'fine', 'gets', '1908', 'toad', 'mole', 'ratty', 'old', 'riverbank', "ratty's", "grahame's", 'release'], ['milo', "milo's", 'tollbooth', 'phantom', 'care', 'rhyme', 'dictionopolis', 'tock', 'pompous', 'braggart', 'insect', 'tremayne', 'air', 'mathemagician', '—', 'trustworthy', 'adaptations', 'joins'], ['fables', '1950s', 'travels', "children's", 'carol', 'american', 'deaths', 'wonderland', 'institute', "gulliver's", '1913', 'births', 'company', 'nights', 'early', 'august', '1956'], ['tollbooth', 'phantom'], ['lüssow', 'vorpommern-greifswald', 'vorpommern-rügen', 'gützkow'], ['mouse', 'fancy', 'loopy', 'simple', 'cute', 'easy', 'school', 'protest', 'nice', 'aloud'], [], ['paravoor', 'karingamthuruth']]
TOP TOKENS [['namibia', 'namibian', 'sep', 'analysis'], ['namibia', 'namibian', 'nations', 'century', '1990'], ['namibia', 'namibians', 'others'], ['namibia', 'namibian'], ['namibia', 'namibian'], ['namibia', 'namibia’s', 'professions', 'areas', 'workers', '3-pin', 'distributed', 'cloudless'], ['namibia', 'namibian', 'trumpets'], ['namibia', 'namibians', 'namibian', 'language', 'thimbukushu'], ['namibia', 'jungle'], ['namibia', 'namibians', 'staff', '”', '’', 'surface', 'beginners', 'trade', 'wilderness', 'bank'], ['namibia'], ['namibian', "namibia's", 'namibia'], ['namibia', "namibia's", 'namibians'], ['namibia', '16.9', '59.1'], ['namibia', 'namibian', 'sadc', 'countries'], ['namibia', '074', 'namibian', '2'], ['namibia', 'namibian'], ['namibia'], ["namibia's", 'namibia', 'namibian'], ['namibia', 'representing']]
TOP TOKENS [['river', 'rivers', 'earth', 'wrong'], ['river', 'rivers', 'fowl', 'river.transitive'], ['rivers', 'river', 'waste', 'beautiful'], ['rivers', 'river', 'waste', 'beautiful'], ['river'], ['river', 'rivers', 'river-related', 'appreciating', 'make', 'great'], ['river', 'word', 'definitions'], ['river', 'rivers'], ['river', 'rivers', 'riverboat', 'cls', 'spectacular', 'cultural'], ['river', 'rivers', 'potential', 'many'], ['river', 'krystian', 'water'], ['river', 'francisco', 'san', 'indiana', 'ohio', 'indian', 'zealand', 'colorado'], ['river'], [], ['river', 'cornwall', 'iowa', 'rivers', 'ontario'], ['river', 'tributary', 'washington', 'cocheco'], ['rivers', 'river'], ['river', 'rivers', '1967', 'watercourses', 'rivers-class', 'disambiguation'], ['river', 'sturgeon', 'michigan', 'generating', 'seminary'], ['river', 'prosser']]
TOP TOKENS [['temples', 'temple', 'deity', 'rather', 'modem', 'rock', 'altar', 'b.c', 'often', 'rabbis', 'shrine', 'portion'], ['temple', 'common', "of'temple'very", 'english', "for'temple'british", "of'temple'©", 'temples', 'religions', "containing'temple'these"], ['temple', 'etc', 'temples', '’', 'world', 'caves', 'buddhist', 'around', 'rituals', 'nineteenth', 'cls'], ['temple', 'gods', 'definition', 'croatian', 'buddhist', '신전', 'religions', 'tapınak', 'english', 'hindu'], ['temple', 'temples', 'church', 'anytime', 'mosquethese'], ['temple', '1977', 'temples', 'cls', 'sacrifice', 'used', 'even', 'mankhim', 'gods'], ['temple', 'time', 'stone', 'consecrate', 'new', 'rejected'], ['temple', '”', '–', '“', 'temples', 'nebuchadnezzar', 'word', 'seeking', 'particular', 'buildings'], ['temple', 'era', 'cls', 'time', 'word', 'took', '360', 'babylon'], ['temple', '“', 'temples', 'word', 'term', 'храм', 'parlance', 'church'], ['israel', 'activities', '1633', 'temple', 'herbert', 'head', '1920', 'sky', '1996'], ['1940', 'l', 'geography', 'temple', 'states'], ['temple', 'education', 'residents', "solomon's"], ['temple', 'bassist', 'conservative', '1731–1798', '1910–1994', '1976'], ['temple'], ["temple's", 'railway', 'located', 'temple', 'geography', 'house', 'known', 'dangerous', 'caved-in'], ['disambiguation', 'temple', 'nrhp', 'texas', 'w', 'g', 'also', 'iowa', 'arkansas', 'tecumseh', 'templehouse'], ['temple-poole', 'temple', 'public'], ['temple', 'census', 'boulevard', 'dwellings', '18.7', 'e', 'councillor', 'alberta'], ['massachusetts', 'toronto', 'disambiguation', 'temple', 'york']]
TOP TOKENS [['discussion', 'discussions', 'dictionary.com', 'discussing', 'im'], ['discussion', 'discussions', 'posts', 'desired', 'created', 'threads'], ['discussions', 'discuss'], ['discussion', 'one', 'leaders', 'using', 'question', 'principal'], ['discussion', 'discussions', 'using', 'offer', 'use'], ['discussions', 'discussion', 'https://en-us.help.blackboard.com/learn/instructor/interact/discussions/010_about_discussions_forums_threads', 'main', 'around', '“about', 'online'], ['discussion', 'discussions', 'however', 'come', 'issue'], ['discussion', 'section', 'flow', '–', 'writing', 'e', 'elaborates'], ['discussions', 'discussion', 'vesley', 'cls', 'allow', 'study', 'post', 'course', 'discuss', 'class', 'create'], ['discussion-based', 'discussions', '‘discussion-based', 'discussion', 'discussion-led', 'environments', 'includes', 'around', 'introduced', 'introducing', 'lecturing'], ['discussion', 'image', 'discuss', 'form', 'calls', 'brief', 'comments', 'online', 'history', 'using', 'emphasised', 'cls', 'problems', 'provide', 'ideas', 'internet'], ['discussion', 'wiki'], ['discussion', 'discussions', 'discussants', 'questions', 'leaders', 'facilitators', 'ask'], ['discussion', 'discussed', "as'how", 'controversial', "weather'might", 'supportive', 'according', 'competitive', 'example', 'facts', 'theology'], ['discussion', "discussion's", 'online', 'discussions', 'significant', 'participate', 'requirements', 'part', '—', 'formulas'], ['discussion', 'occurs', 'discussions', 'explores', 'style', 'subject', 'meta', 'means', 'setting', 'topics'], ['discussion', 'panel', 'feature', 'buzzcocks', 'discuss', 'questions', 'running', 'larry', 'typically', 'english', 'diego', 'involves'], ['discussion', 'discussions', 'based', 'may', 'exploration'], ['discussion'], ['discussion', 'discussions', 'texts', 'discussants', 'explore', 'interpretive', 'effective', 'grade']]
TOP TOKENS [['tautology', 'tautologies', 'totally', 'take', 'may'], ['tautology', 'tautologies', 'tautologous', '15:27:35', 'every'], ['tautology', 'tautologies', 'matter'], ['tautology', 'tautological', 'humorous', 'tautologies', 'words', 'tauto', 'without', 'plenty', 'repeated'], ['tautology', 'tauto', 'wikipedia', 'fun', 'taw-tol-uh-jee'], ['tautology', 'tauto', 'wikipedia', 'fun', 'taw-tol-uh-jee'], ['tautology', 'tauto', 'wikipedia', 'fun', 'taw-tol-uh-jee'], ['tautology', 'tautologies', 'continues', 'symbolism', 'thus', 'first'], ['tautology', 'tautologies', 'clear'], ['like', 'tautology', 'cases', 'present'], ['tautológia', 'tautonym', 'tautology'], ['tautological', 'grammar'], ['tautology', 'tautologies', 'sometimes', 'may'], ['tautological', 'tautology', 'birth', 'nicht', 'tautologies', '16th', 'heute', 'wittgenstein', 'always', 'und', 'stand', 'century'], ['tautology', 'tautological', 'tautologically', 'tautologousness', 'every', 'one'], ['consequently', 'tautology', 'given', 'tautologies', 'also', 'fact', 'unlimited'], ['tautomerism', 'tautomers', 'tautomeric', 'tautomerization', 'resonance', '–', 'desmotropism', 'pervasive', 'confuse', 'called', 'common', 'cls', 'taken'], ['tautology'], ['tautologous', 'tautology', 'tautologies', 'tautological', 'term', 'word', 'began', 'c'], ['tautomycetin', 'tautomycin', 'pp2a', 'inhibition', 'called', 'differs', 'groups', 'immunosuppression']]
TOP TOKENS [['resultant', 'find'], ['resultant'], ['resultant', 'starting'], ['resultant', 'produce', 'calculating', 'including', 'since'], ['resultant'], ['resultant', 'problem', 'really'], ['resultant', 'calculating', 'calculate', 'finding', 'called', 'find', 'vector'], ['resultant', 'represents', 'finding', 'calculate'], ['resultant', "macaulay's", 'usual'], ['resultant', 'resultants', 'yields', 'immediately', 'vectors', 'vector', 'example', 'apparent', 'yield', 'per'], ['resultant'], ['resultant', 'computing'], ['resultant', 'term', 'becomes', 'engineering'], ['resultant', 'resultants', 'computing', 'computation', 'may'], ['resultant', 'resultants', 'compute', 'algorithms', 'computation'], ['resultant', 'resultants', 'directions', 'v2', 'stress'], ['resultant', 'distinguish', 'force', 'free'], ['resultant', 'defining', 'usual', 'essentially', 'polynomials', 'resulting'], ['resultants', 'resultant', 'computing', 'seems', 'systems', 'polynomial', 'containing', 'may'], ['resultant', 'becomes', 's2', 'force', 'free', 'addition']]
TOP TOKENS [[], ['1.8–2.5'], [], [], [], ['stirred', 'doubtful'], [], [], [], [], ['1904–05', 'players', 'played', 'years'], ['heart'], [], ['5', 'variation', '2'], [], [], ["3'5", 'contains'], ['c'], [], []]
TOP TOKENS [['2', 'mouthpiece', 'stabile', 'dispalay', '10', 'user', '4500', 'part', 'prompts', 'started', 'however', 'sensor', '”'], ['2', '5', 'blank', 'inserting', 'isopropyl', 'copies', 'toner', '–', 'smudges', 'dust', 'make', 'areas', 'clips', 'clean', 'envelopes'], ['volume', 'long', 'applications', 'use', 'deg', 'pressure', '”', '0', '5'], ['output', 'reproducer', 'slightest', 'stylus', 'embossed', 'tube', 'point', 'diaphragm', 'use', 'strike', 'laterally', 'phonograph', 'problem', 'bring', 'linked', 'adjust', 'damaged', 'causing', 'except', 'machines'], ['stylus', 'stylus-groove', 'area'], ['areas', '“', '”', 'polyethylene', 'lubricant', 'excipients', 'small', 'adherent', 'size', 'soften', 'embossing', 'hygroscopic', 'polishing', 'debossing', 'sorbitol', 'obtain', 'pickingadherence', 'possible'], ['areas', '“', '”', 'polyethylene', 'lubricant', 'excipients', 'small', 'adherent', 'size', 'soften', 'embossing', 'hygroscopic', 'polishing', 'debossing', 'sorbitol', 'obtain', 'pickingadherence', 'possible'], ['product', 'ingredient', 'lubricant', 'impart', 'within', 'peninsulas', 'adhesive', 'fixes', 'single'], ['period', 'nnp', 'µm', 'μm', 'much', 'cases'], [], ['coating', 'digital', 'z580m', 'filter', 'z5600m', 'see', 'z5900m', 'z581m', 'z5670m', '2', 'z573m'], ['scanner', 'create', 'scanners', 'enhances'], ['v70', 's60', 'aspirated', 'v50', '2', 'rpm', 'b5244s6', 'badged', '5100', '5800'], [], [], ['products', 'ingredient', 'plasticizers', 'make'], ['indentations', 'functionality', 'sample', 'fixing', 'test', 'adhesive', 'e'], ['sample'], ['volume', 'instrument', 'like', 'specific'], ['make', 'indenter', 'indentation', 'nanoindentation', 'indent', 'indented', 'area', 'one']]
TOP TOKENS [['simple', '140', 'systems', 'emergent', 'width', 'finitely', 'known', 'loop', 'static', 'cls', 'yet', 'tree', 'narrow', 'branches', '704', 'inputs'], ['components', 'conditions', 'second', '—', '100', 'energy', 'molecules', 'clockwise', 'way', 'assembles', 'atoms', 'sometimes', 'vanishingly', 'first', 'becomes'], ['unassembled', 'components', 'superlattices', 'single', 'systems', 'composed', 'thermodynamically'], ['–', 'difference', 'doubled/tripled/etc', 'example'], ['unlabeled', '08', 'upon', 'preview', 'done', 'boxes', 'depends', 'whether', 'forumlas'], ['b', 'configurations', 'oscillators'], ['boxes', 'suppose', 'problem', 'therefore', 'color', 'ways', 'balls', 'colors', 'say', 'possible', 'cls', 'first', 'next', 'distinct', 'one'], ['rulestring', 'replicator', 'rule', 'neighbors', 'survives', 'replicates', 'although', 'pattern'], ['3', 'one', 'divisors', '2', '1'], ['grids', 'chapter', 'lattice', 'instead', 'possible—as', 'lattices', 'grid', 'one'], ['environment', 'rules'], ['cannot', 'one', 'rosenblueth', 'r', 'psoup', '1991', 'demonstrations', '967', 'wolfram', 'durrett'], ['nitride', 'de:konformation', 'anti', 'e.g', 'also', 'cubic/hexagonal', 'see', 'sp3-hybridised'], ['e', 'whereas', 'conventionally', 'net', 'see'], ['components', 'unassembled', 'single', 'systems', 'composed', 'thermodynamically', '—', 'properties', 'rearrangements'], ['system', 'figure', 'systems', 'irreversible', 'one', 'ultrasensitive', "equation's", 'bifurcations', '2', 'increases', 'instance', '–', 'functions'], ['particular', 'behaves', 'vanish', 'however'], ['nondeterministic', 'rectangles', 'net', '1', 'time', 'similarly', '2', 'conventionally'], [], ['bitonic', 'compare', 'sequence', 'subsequences', 'merges', 'combine', 'vice', 'box']]

Processing features:  13%|█▎        | 13/98 [06:06<39:51, 28.14s/it]

getting sample prompt forgetting sample prompt for 23557
 23556
getting sample prompt for 23558
getting sample prompt for 23559
getting sample prompt for 23560
getting sample prompt for 23561
getting sample prompt for 23562
getting sample prompt for 23563
getting sample prompt for 23564
getting sample prompt for 23565
getting sample prompt for 23566
getting sample prompt for 23567
TOP TOKENS [[], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['fade', 'fading', 'faded', 'effect', 'give', 'want'], ['fade', 'fading', 'faded'], ['fade', 'fader', 'faderabrader', 'faders', 'want', 'loudspeakers'], ['fade-ins', 'fade-in', 'guidelines', 'two'], ['fade', 'fading', 'filters', 'effect', 'without', 'uses', 'easy', 'emily01', 'one', 'way', 'method', 'onclick'], ['fade', 'fading', 'filters', 'effect', 'without', 'uses', 'easy', 'emily01', 'one', 'way', 'method', 'onclick'], ['fade', 'fading', 'filters', 'effect', 'without', 'uses', 'easy', 'emily01', 'one', 'way', 'method', 'onclick'], ['fade-in/fade-out', 'fade-in', 'fade-out', 'in-out', 'fade'], ['fade', 'fades'], ['fader', 'level', 'strip', 'producers'], ['1988', 'fade', 'alternative', '2007', 'fading', '2008', 'british'], ['fade'], ['faded', 'fade', 'fader'], ['production', 'fade', "in's", 'formats', 'similar', 'linux', 'devices'], ['fade', 'twenty-six', '3.5'], ['fading', 'ins', 'audio', 'fade', 'faders', 'fades', 'almost', 'beginning'], [], ['fade', 'website'], ['fade', 'fadeout', 'brubaker'], ['fader', 'it:fader', '2010', 'off-air', 'go', 'leading', 'reached', 'already', 'act', 'currently']]
TOP TOKENS [['gingerbread', 'man', 'horn', 'men', 'decorated', 'small', 'pull'], ['gingerbread', 'gingerbread.”', 'either', 'malaysia', 'house', 'since', 'soft', '1800’s', '1950’s', 'well', 'houses'], ['gingerbread', 'man', 'inanimate', 'threshers'], ['gingerbread', 'man', 'inanimate', 'threshers'], ['gingerbread', 'gingerbreadfun', 'sure', 'men', 'long', 'small', 'http', 'pull', 'man'], ['gingerbread'], ['gingerbread'], ['gingerbread', 'man'], ['gingerbread', 'man', 'astronaut', 'cls', 'cowboy', 'truly', 'much', 'states'], ['gingerbread', 'fun'], ['gingerbread', 'shape', 'gingerbreadman', 'diarrhea', 'rankin'], ['gingerbread', 'rewarding'], ['gingerbread', 'tree'], ['gingerbread', 'crazy', 'owns', 'followed', 'worked', 'runs', 'shop', "cyd's", 'josh', "man's", 'ira', 'novel'], ['gingerbread', 'every', 'executive', 'year'], ['gingerbread', 'gone', 'man'], ["and'gingerbread'look", 'gingerbread', 'elaborate', 'farmers', 'sized', 'vertical', 'country', 'board'], ['gingerbread', 'traditions', 'flavor', 'century', 'house', 'icing', 'myrrh', 'crisp', 'man', 'pithiviers', 'elaborates', "matthew's", 'custom', 'years', 'covered', 'foodstuffs', 'magus', 'shaped'], ['gingerbread', 'links', 'also', 'village', "chefs'gingerbread"], ['gingerbread', 'misadventures']]
TOP TOKENS [['barry'], ['barry', '“', 'times', 'indeed', 'consider', 'figure', 'understand', 'brandon'], ['barry', 'definition'], ['barry', 'barrys', 'barrie', 'william', 'name', 'barrymore'], ['barry', 'occupation', 'dictionary'], ['barry'], ['barry', "barry's", 'war', 'formed'], ['barry', "barry's", 'also'], ['barry', "barry's", '1768', 'alliance'], ['barry', 'barry’s', '–', '1810'], ["barry's", 'barry', 'university'], ['barry', "barry's"], ['barry', "barry's", 'career', 'seasons', 'league', 'major'], ["barry's", 'barry', '1981', 'atlanta', 'star', "women's"], ['barry', '49ers', 'camryn', 'life', 'personal'], ["barry's", 'barry', 'links', 'external', '2019', '2008', 'also', '2002', 'references', 'life', 'century'], ['barry’s', 'barry', "barry's", '2017', 'd.c', '2020', '2015', 'jay'], ['barry', 'songwriter'], ['barry', '41', '2', '64', '86', '50', '4', '24', 'households', '2000', '12', 'city', 'families', 'living'], ['barry', 'death', 'appointed', 'memberships', 'daughter', '19']]
TOP TOKENS [['dana', 'danavir', 'danas'], ['dana', 'niyamas', 'self-study'], ['dana', 'exclusive', 'statecraft', '1a', 'gift', 'thing', 'one', 'nitiprakasika', 'vaishnavism'], ['dana', "dana's", 'life'], ['dana', 'states', 'became'], ['dana', 'word', 'sikhism'], ['dana', 'edited'], ['dana', 'edited'], ['dana', 'diseased', "one's"], ['dana', 'view', '’'], ['dana', '20th-century', 'early', 'gina', 'references', '1998', 'screenwriters', 'writer/producer', 'also', 'american', 'uncredited', 'life', 'then-husband'], ['dana', '1st', 'california', '–'], ['dana'], ['dana', 'danann'], ['dana', 'links', 'english', 'external'], ['dana', 'singer'], ['dana'], ['dana'], ['dana', "dana's", 'links', 'song', 'danalda', 'external', 'star', '2018', 'official', 'births'], ['dana', 'dr']]
TOP TOKENS [['vivo', 'antitumor', 'mechanism', 'possessed', 'exert', 'activity', 'inhibit', 'however'], ['proliferation', 'effects', 'mutagenesis', 'growth', 'viability', 'potential', 'line', 'cell', 'carcinoma', 'lines', 'decrease', 'damage', 'using', 'tumour', 'oxidative'], ['proliferation', 'stimulate', 'affect', 'decreased', 'demonstrated', 'enhanced', 'μmol', 'inhibition', 'growth', 'anticancer', 'cell', 'cellular', 'carcinoma'], ['growth', 'suppressed', 'vitro', 'anticancer', 'caspase', 'cytotoxicity', 'cytotoxic', 'lines', 'viability', '0', '6', 'cleavage', 'resveratrol', 'damage'], ['growth', 'apoptosis', 'cell', 'suppress', 'inhibited', 'lines', 'cells', 'activity', 'adenocarcinoma', 'manner'], ['activity', 'vitro', 'shows', 'antiapoptotic', 'antitumor', 'inhibit', 'metastases', 'setting', 'metastasis', 'growth', 'carcinogenesis', 'apoptosis'], ['proliferation', 'genotoxic', 'cytotoxic', 'genotoxicity', 'carcinoma', 'cell', 'genomic', 'cytotoxicity', 'zsuzsanna', 'viability', 'exert', 'observed', 'induction', 'decrease', 'studied', 'instability', 'increase'], ['effect', 'property', 'anticancer', 'antitumor', 'properties', 'prevention', 'performed', 'anticarcinogenic', 'exhibit'], ['viability', 'cytotoxicity', 'lines', 'variety', 'cleavages', 'arrests', 'cultures', 'cultured', 'induce', 'even', 'apoptosis'], ['proliferation', 'mutagenesis', 'growth', 'inhibited', 'cell', 'reduction', 'vivo', 'pplgm-induced', 'studies', 'death', 'vitro', 'deadly', 'rate', 'mortality', 'damage', 'causing'], ['genotoxic', 'mutagenicity', 'mutagenic', 'genotoxicity', 'stage', 'damaging', 'cycle', 'cultured', 'hepatocarcinoma', 'damage', 'effect', 'lymphocytes', 'increased', 'using', 'death', 'apoptosis', 'dna', 'fibroblasts', 'cells', 'vivo'], ['proliferation', 'various', 'lines', 'adenocarcinoma', 'expression', 'cell', 'inhibit', 'found', 'suppressor', 'constitutively', 'inhibiting', 'caspase', 'cleavage', 'glcnacylation'], ['suppress', 'formation', 'impair', 'samples', 'progression', 'inactivation', 'survival', 'stage', 'vitro', 'renewing', 'mediates', 'largely', 'metastasis', 'stages'], ['trihalomethanes', 'damage', 'inducing', 'potency', 'risks', 'byproducts', 'increased', '3-chloro-4-(dichloromethyl)-5-hydroxy-5h-furan-2-one', 'mutagen', 'dna', 'reaction', '2b', 'alcohols', 'types', 'humans', 'enough', 'carcinogenic'], ['genotoxic', 'effect', 'nucleophilic', 'attributed', 'treatment', 'n', 'toxicity', 'via', 'isocyanic', 'alkylate', 'gastrointestinal'], ['proliferation', 'mutagenesis', 'development', 'damage', 'vitro', 'number', 'metastasis', 'induce', 'treatment', 'may', 'studies'], ['genotoxic', 'activity', 'vitro', 'shown', 'effects'], ['mutagenic', 'mutagenicity', 'genotoxicity', 'properties', 'affect', 'thymines', 'division', 'direct', 'remodelling', 'nucleotides', 'guanines'], ['reduced', 'metastasis', 'uninary', 'compared', 'ability', 'synthesis', 'division', 'pretreatment', 'forming', 'vitro', 'inhibit', 'actions', 'assay', 'malignant', 'urinary', 'activity', 'cell', 'aggressiveness'], ['genotoxic', 'proliferation', 'carcinogenicity', 'hepatocellular', 'suppressing', 'potent', 'development', 'carcinoma', 'cellular', 'hepatocarcinogen', 'mechanism', 'urinary', 'intercalates', 'carcinomas', 'controls', 'cleavage', 'tumors', 'oxidative', 'exo']]
TOP TOKENS [['oppenheimer', 'oppenheimerˈɒp', 'oppenheimer(noun'], ['oppenheimer', 'saw', '’', 'misgivings', 'contributed', 'nature'], ['oppenheimer', "oppenheimer's", 'writings', '1954', 'discoveries', '1950s'], ['oppenheimer', 'along', 'r'], ['oppenheimer', 'pp', 'decrying', 'union', '837', 'sided', 'said', 'stern'], ['oppenheimer', 'press', 'albuquerque', 'reappraising', 'robert', '3783', 'j', 'new', '23', '5946652', '–', '65637244', '64385611'], ['oppenheimer', 'life', '’', '“'], ['oppenheimer', "oppenheimer's", 'attitudes', 'incident', 'despite'], ['oppenheimer', 'importing', 'robert', 'j', 'technology', 'harvard', 'work', 'gogh', '—'], ['oppenheimer', 'organizer', '8', 'new', 'smith', 'alice', 'york'], ['oppenheim', 'oppenheimer'], ['oppenheimer', 'oppenheim'], ['oppenheimer', 'oppenheim', 'stephen'], ['oppenheimer'], ['oppenheimer', 'hempel-oppenheim', 'oppenheim'], ['oppenheim'], ["oppenheimer's", 'oppenheimer', 'committees', 'scholar', '2002', 'c', 'iau', 'ny', 'early'], ['oppenheimer', 'voyager', 'acting', 'played', 'actor', 'also', 'took', 'introduction'], ['oppenheimer', "oppenheimer's", 'j', 'retirement', 'settled', 'walla'], ['oppenheimer', 'ii', '–', "t'ai", 'thug', 'amn', 'brotherhood', 'ghoul', 'ivanovich', 'ogrok', '1', 'piotr', '2004']]
TOP TOKENS [['redshifts', 'redshift', "redshift's", 'recent', 'law', 'karlsson', '0625'], ['redshift', 'blueshift'], ['redshifts', 'redshift', 'measured', 'et', '1', 'al'], ['redshift', 'redshifted', 'blueshift'], ['redshift', 'expect', 'since'], ['redshift', 'velocity', '56'], ['redshift', 'redshifted', 'blueshift'], ['redshift', 'redshifts', 'blueshifts'], ['redshift', 'redshifts', 'higher', 'example', 'also'], ['redshift', 'redshifted', 'blueshift', 'terms'], ['redshift', 'claim'], ['redshift', 'redshifts', 'cosmological', 'widely'], ['redshift', 'redshifts'], ['redshift', 'redshifts', 'defined', 'limit'], ['redshift', 'redshifted', 'thus', 'velocities'], ['redshifts', 'redshift', 'wavelengths', 'small', 'spectroscopic'], ['redshift', "redshift's", 'migrations', 'workloads', 'terabytes', 'principle', 'listed', 'cluster', 'release', 'makes'], ['redshift', 'redshifts', 'whether', 'far'], ['redshift', "command'redshift", "redshift's", '5500', 'cls', 'preferred'], ['redshift', 'redshifts', 'blueshift', 'inwards', 'god', 'space', 'expansion', 'fall', 'cls', 'previous']]
TOP TOKENS [['subsidence'], ['subsidence1'], ['subsidence1'], ['subsidence'], ['subsidence'], ['subsidence'], ['subsidence', 'suspect'], ['subsidence'], ['subsidence'], ['subsidence'], ['subsidence'], ['subsidence'], ['subsidence', 'subsides', 'isostatic'], ['subsidence', 'subsiding', 'monitor'], ['subsidence'], ['subsidence', 'subsides', 'scale', 'causes', 'rises'], ['subsidence', 'anthropogenic'], ['subsidence', 'subside', 'induced', '0', 'significant'], ['subsidence', '1300s', 'suffering', 'however'], ['subsidence', 'increasing', 'sinking', 'upward', 'rapidly']]
TOP TOKENS [['anomaly', 'anomalies', 'cls', 'expected'], ['anomaly', 'anomalies', 'trend', 'global', 'arise'], ['anomaly', 'anomalous', 'within', 'mean'], ['anomalies', 'anomaly', 'anomalous'], ['anomaly', 'anomalies'], ['anomaly', 'anomalies', 'anomalous'], ['anomaly', 'anomalies', 'anomalous'], ['anomalies', 'anomaly', 'anomalous', '“', 'although', '”', 'cls'], ['anomalies', 'anomaly', 'anomalous', 'cls'], ['anomalies', 'anomaly', 'cls', 'data'], ['anomaly', 'cls', 'anomalous', 'anomalon', 'classical', 'anomalies', 'global', 'region'], ['anomaly', 'anomalies', 'value', 'standard', 'forming'], ['anomaly', 'anomalies', 'pioneer'], ['anomaly', 'anomalies', 'anomalous', 'first', 'occur'], ['anomaly', 'anomalies', 'physics', 'links', 'external'], ['anomaly', "anomaly's", 'established', 'history', 'founded', 'unilever', 'additionally', 'american', 'mashies'], ['anomaly', 'anomalies', 'standardized', 'global', 'cls', 'hemispheric', 'called', 'temperature', 'allows', 'temperatures', 'series'], ['anomaly', 'anomalies'], ['anomaly', 'anomalies', 'anomalous', 'analysis', 'mechanism'], ['anomalies', 'anomaly', 'references', 'type']]
TOP TOKENS [['thyristors', 'thyristor'], ['thyristor', 'thyristors', "thyristor's"], ['thyristors', 'thyristor', 'cls', 'bothmembers', 'isdesigned', 'isapplied', 'unidirectionaldevices', 'triggered', 'kind'], ['thyristors', 'thyristor', 'inverter', 'latter'], ['thyristors', 'thyristor', 'device', 'modified:||23', '2007', 'cathode', 'ideally', 'repository', 'i.e'], ['thyristors', 'thyristor'], ['thyristor', 'thyristors'], ['thyristor', "thyristor's", 'thyristors'], ['thyristor', "thyristor's", 'thyristors'], ['thyristor', 'thyristors', 'current'], ['thyristors', 'thyristor', 'applications'], ['thyristor', 'thyristors', 'e'], ['thyristor', 'thyristors', 'photothyristors'], ['thyristors', 'thyristor', 'although', 'choice', 'applications', 'circuits', 'like', 'however', 'though', 'one'], ['thyristors', 'thyristor', 'nature', 'device', 'said', 'asymmetrical'], ['thyristors', 'thyristor', 'behaves', 'using', 'application', 'lead', 'fully', 'scr'], ['thyristors', 'thyristor', 'without'], ['thyristor', '180', '40', 'cls', 'works', 'undesired', '°', 'power', 'unproblematic'], ['thyristors', 'thyristor', 'ac', '5'], ['thyristors', 'thyristor', 'scrs', 'heaters', 'differ', 'analogous', 'scr', 'triode']]
TOP TOKENS [['coffee', 'cup', 'beans', 'caffeine', 'brewed', 'flavor', 'brewing'], ['coffees', 'coffee', 'roasts', 'beans', 'types', 'drinkable', 'roasted'], ['coffee', 'coffees', 'flavor', 'ones', 'flavors', 'aroma', 'roasts', 'roast', 'sugars'], ['coffee', 'drink', 'coffees', 'drinks', 'flavorful', 'brewing', 'caffeine', 'flavor'], ['coffee', 'coffee,salvador', 'coffee,zimbabwe', 'flavor', 'bean'], ['coffee', 'drinks', 'brewed', 'brew', 'solubles', 'water', 'cup'], ['coffee', 'drinks', 'brewed', 'brew', 'solubles', 'water', 'cup'], ['coffee', 'brewed', 'brew', 'flavors'], ['coffee', 'drink', 'flavor'], ['coffees', 'coffee', 'caffeine', 'flavor', 'beans', 'fruity', 'flavors', 'brewing'], ['coffee', 'drinks', 'drinkers', 'brewed', 'brew', 'brewing', 'food', 'flavor'], ['coffee', 'brewed', 'beverage', 'brewing', 'flavor', 'beans', 'aroma', 'frothed', 'surface'], ['coffee', "coffee's", 'drinkers', 'caffeine', 'roasts', 'beans', 'flavors'], ['coffee', 'beverage', 'coffea', 'bean', 'coffeescript', 'equity', 'bitter', 'literate'], ['beverage', 'coffee', 'rehydrated', 'brewed', 'beans', 'espresso', 'streptomycin', 'dehydrated', 'processes'], ['coffee', 'brewed', 'espresso', 'flavor', 'beans', 'beverage', 'drinking', 'caffe', 'drinks', 'food', 'latte', 'cup', 'acidic', 'colored'], ['coffee', 'beverage', 'brewed', 'brew', 'flavorings', 'brewing', 'compounds', 'flavor'], ['beverage', 'coffee', 'brew', 'flavors', 'acidity', "drinker's", 'press'], ['coffee', 'beverage', 'drinker', 'brew', 'beans', 'brewed', 'brewing', 'drinking'], ['coffee', 'coffees', 'caffeine', "coffee's", 'flavor', 'roasts', 'roast', 'food', 'beans']]

Processing features:  14%|█▍        | 14/98 [06:35<39:40, 28.33s/it]

getting sample prompt forgetting sample prompt for 23569
 23568
getting sample prompt for 23570
getting sample prompt for 23571
getting sample prompt for 23572
getting sample prompt for 23573
getting sample prompt for 23574
getting sample prompt for 23575
getting sample prompt for 23576
getting sample prompt for 23577
getting sample prompt for 23578
getting sample prompt for 23579
TOP TOKENS [['supervisor', 'supervisors', 'supervisory', 'student', 'supervises', 'committing'], ['supervisors', 'supervisor', 'supervises'], ['supervisor', 'supervisors', 'start', 'well', 'manager'], ['supervisor', 'supervisors', 'colleagues'], ['supervisors', 'cls', '88', 'extremes', '000', 'education', '67'], ['supervisor', 'supervisors', 'supervision', 'subordinates', 'situations', 'word'], ['supervisor', 'supervisors', 'supervisory', 'success', 'objectives', "what's", 'management', 'supervision', 'direct', 'managers', 'rules', 'supervising', 'strategy', 'issue'], ['supervisor', 'supervisors', 'supervision', 'supervisee', 'supervisees', 'concerns'], ['supervisor', 'supervisors', 'supervision', 'managers', 'cls', 'way', 'period'], ['supervisor', 'cls', 'class', 'processes', 'modules', 'utilties'], ['supervisor', 'supervision', 'oversight', 'management'], ['supervisor', 'supervision', 'guidance', 'management', 'contexts', 'supervisee'], ['supervisor', 'supervision', 'supervisors', 'dissertation', 'workplace', 'constraints', "supervisor's", 'cls', 'authority'], ['supervisor', 'supervisory', 'processing', 'abstracted', 'systems'], ['supervisor', 'supervisors', "supervisor's", 'supervisory', 'followed', 'may', 'academia', 'job', 'student', 'group', 'training'], ['supervisor', "supervisor's", 'supervisors', 'music', 'supervision', 'directors'], ['supervisors', 'supervisor'], ['supervisors', 'supervisor', 'supervision', 'music', 'qualification', 'also', 'manage', 'hiring'], ['supervisors', "supervisor's", "supervision's", 'supervision', 'supervisees', "supervisees'competence", "supervisee's", 'patients', 'people', 'approved', 'component', 'cls', 'supervised'], ['supervisor', 'supervisory', 'processing', 'abstracted', 'program', 'mellon', 'system', 'systems', 'regulates']]
TOP TOKENS [['rugs', 'rug', 'precautions'], ['rug', 'rugs', 'benchmark'], ['rug', 'rugs'], ['rug', 'rugs', 'involved', 'shape', 'design'], ['rug', 'rugs'], ['rug', 'rugs', 'effective'], ['rug', 'rugs', 'effective'], ['rugs', 'rug', 'best'], ['rug', 'rugs', 'generations', 'road', 'anatolia', 'making'], ['rug', "rugg'ruffled", "rugga'coverlet", 'rugs', 'actually', 'disappointed'], ['rug', 'groningen'], ['rugs', 'rug', 'feet', "4'rug", 'braided', 'linen', 'side'], ['ruge', '1956', 'c.1866/1870–1955', '1846-1926', 'gerd'], ['caraş-severin', 'turcinești', 'rugi'], ['rugs', 'rug', 'rugging', 'makes', 'rugger'], ['rüger', 'ruger', '1949', '1833–1907', 'disambiguation'], ['2,467'], ['ruge', 'boris', 'october'], ['rugova', 'rugovo'], ['damm-rüger', 'ruger', 'rüger']]
TOP TOKENS [['compact', 'mathematics'], ['compact', 'look', 'quasi-compact'], ['compactum', 'compact', 'compactness', 'compacta', 'term'], ['compacts', 'compact', 'compacting'], ['compacted', 'compaction', 'improving'], ['compacting', 'compact', 'know'], ['compāctus', 'compact'], ['compaction', 'compacting'], ['compactum', 'compacted', 'compacting', 'compact', 'compactus', 'related'], ['compactness', 'compact', 'highly', 'use', 'incorporating', 'optimal'], ['compact', 'compactification', 'compaction', 'compactor'], ['compacta'], ['compacta'], ['compacta'], ['compacta', 'nigrolinealis'], ['compacta'], ['compactum', 'compacta', 'compact'], ['compactus'], ['compact', 'compactness'], ['compact', 'concerns', 'launched', 'ahmari', 'nina']]
TOP TOKENS [['1946', '’', '“'], ['in1946', '1946', '1947', 'moon', 'capra’s', 'well'], ['45th', '1945', '1947', 'rest', '46', 'training', 'moved', '1944', 'brief', 'distributor', 'november', '15'], ['cd45', 'cd45r', 'cd45r0', 'cd45ra', 'cd45rb', 'cd45rc', 'cd45rab', 'cd45rac', 'cd45rbc', 'leukemia', 'addition'], ['46', '46/1'], ['cd45ra', 'cd45', 'ml', 'cd4+t-cells'], ['cd44', 't-cells', 'expression', 'upregulation'], ['45a', '45s', '45as', '45b', '45', '45c', '45n', '47'], ['45'], ['cd44', 'targeting', 'protrusions', 'role', 'dangerous', 'tumorigenic', 'study', 'brain'], ['1945', '1946', '1945–46', '1945/46', 'july'], ['1946', 'party', '2005', 'references'], ['45', 'a45', '45w', '45b', '45e', '45a', 'herkimer', 'm45', 'e45', 'g45', 'route'], ['1946–47'], ['1945', '1945–46', '1946', 'july'], ['1946'], ['1946', 'system'], ['1946', '1947', '1946–47', '1946/47'], ['45', '45a', 'a45'], ['1946', '1945', '1945–46']]
TOP TOKENS [['nightjars', 'tips', 'yellow', 'blotches', 'distraction', 'shrub', '10', 'markings', 'white'], ['nightjar', 'medium-sized'], ['nightjars', 'female', 'mostly', 'blotches', 'also', 'via', 'around', 'like', 'facilitates'], ['nightjars', 'find', 'season', 'go'], ['nightjars', 'nightjar', 'sounds', '9', '0', 'winged', '1', '28', 'often', '14', 'simply', 'one'], ['cajal', '’', 'slides', 'innovations', 'lobe', 'structures', 'details', 'ii'], ['nightjars'], ['nightjars', 'nightjar', 'probably', 'male'], ['nightjars', 'nightjar', 'means', 'africa', 'help', 'well'], ['brinjal'], ['véjar'], ['banjar', 'part', 'area'], ['anjar'], ['nightjar', "nightjar's", 'collared', 'larger', 'one', 'though', 'least'], ['nightjar', "nightjar's", 'nightjars', 'range', 'family', 'band'], ['nightjars', 'nightjar', 'links', 'ground', 'collection', 'moniker', 'locating', 'surveys', 'many', "vaurie's", 'times'], ['nightjar', 'nightjars', 'cheeked', 'spot', 'watch', 'territory'], ['nightjar', 'nightjars', 'generally', 'flushed', 'finely', 'spotted', 'brooding', 'usually', 'followed', 'may', 'involves', 'ground', 'hissing', '–', 'sun', 'also', 'upwardly', 'mottled', 'becoming', 'flocks', 'campfires'], ['disambiguation', 'al', 'hajjar', 'khatoon', 'hajar'], ['nightjar', "nightjar's", 'pygmy']]
TOP TOKENS [['geocaching', 'geocacher', 'geocache', 'geocachers', 'geaocaching', '‘geocaches’', '‘geocaching’'], ['geocaching', 'geocacher', 'geocache', 'geocachers', 'geaocaching', '‘geocaches’', '‘geocaching’'], ['geocaching', 'geocachers', 'www.geocaching.com'], ['geocaching', 'earthcache', 'geocache', 'geocaches', 'geocaching.com'], ['geocachers', 'geocaching', 'geocaches', 'geocache', 'earthcache', 'geocaching.com'], ['geocaching', 'geocachers'], ['geocaching', 'geocache', 'geocaches', 'geocachers'], ['geocaching', 'geocaches', 'geocache', 'earthcaching', 'earthcache', 'earthcaches', 'earthcachers'], ['geocaching', 'geocachers', 'geocache'], ['geocachers', 'geocaching', 'geocaching.com', 'geocache', 'geocaches'], ['geocaching', 'listed', 'firefox', 'chrome', 'users', 'e', 'g', 'well'], ['geocaching'], ['geocaching', 'geocachers', 'geocacher', 'geocache', 'geocaches', 'cache', 'activity', 'furthermore', 'location'], ['geocaching', 'features', 'trip'], ['lease', 'aboriginal'], ['geocaching', 'database', 'com', 'like', 'u', 'forest'], ['orienteering'], ['geocaching', 'geokrety'], ['geocaches', 'located'], ['geocaching', "geocacher's", 'geocachers', 'microcaches', 'caching', 'geocoin', "cacher's", 'e']]
TOP TOKENS [['parthians'], ['parthians', 'parthian', 'parthia', 'herodian', 'hyparchy'], ['parthians', 'parthian', 'back', 'c'], ['parthian', 'parthians', 'battles', 'caesar', 'archers', 'army'], ['parthian', 'parthia', 'ad', 'jobseeker.co.uk'], ['parthian', 'former', 'eventually'], ['parthian', 'europos', 'pahlavi', 'empire'], ['parthians', 'parthian', 'parthia'], ['parthian', 'parthia', 'ad'], ['parthians', 'parthian', 'parthia', 'administration'], ['parthian'], ['parthians', 'parthian', 'parthia'], ['parthian', 'parthians', 'parthia', 'xiongnu'], ['parthians', 'parthian'], ['parthian', 'roman–parthian'], ['parthian', 'parthians'], ['parthians', 'parthian'], ['parthians', 'parthian', 'parther', 'altheim', 'addition'], ['parthian', 'parthia', 'times'], ['parthian', 'parthi']]
TOP TOKENS [[], ['butterfly', 'cls'], ['butterfly', 'valve'], ['butterfly'], ['butterfly', 'flanged'], ['butterfly'], ['butterfly', 'flow', 'valve', 'operations'], ['butterfly', 'media'], ['butterfly', 'operation', 'connections', 'valves', 'types', 'take', 'valve', 'manual'], ['butterfly', 'industrial', 'valves'], ['butterfly', 'doors', 'prototypes', 'top', 'via', 'a-pillar', 'fap', 'aerodynamic', 'gullwing', 'commonly', 'along', 'exclusively', 'scissor', 'straight', 'shape', 'gtp'], ['butterfly', 'valve', 'include', 'ingenuity', 'ball', 'valves'], ['butterfly'], ['butterfly', 'valve', 'valves', 'around', 'spool', 'actuated', '–', 'cls', 'exposes', 'slots'], ['butterfly', 'include', 'valve', 'flat', 'even', 'either', 'valves', 'use', "valve's", 'often', 'direction', 'lies', 'ball', 'point', 'closed', 'cls', 'applications'], ['71000', 'valve', 'andre', 'valves', 'chapelon', 'poppet', 'lner', 'chuffing', 'commonly', 'stanier', 'engines', 'br', 'operated', 'standard', 'locomotives', 'sep'], ['butterfly', 'valve', 'ball'], ['forms', 'actuator', 'action', 'separated', 'operated', 'rather', 'come', 'line', 'typically', 'onto', 'valve', 'across', 'valves', 'fluid', 'generally', 'use', 'many'], ['butterfly', 'ball', 'actuated', 'valve', 'actuator', 'construction', 'air', 'diaphragm', 'retracts', 'website', 'types', 'however', 'exist'], ['unseated', 'making', 'schrader', 'open', 'drilled', '7.75×0.794', 'easily', 'without', 'air', 'korea', 'valve', "dunlop's", 'spring-loaded']]
TOP TOKENS [['electromagnets', 'electromagnet', 'ferromagnetic', 'corkscrew', 'magnetized'], ['electromagnet', 'electromagnets', 'ferrimagnetic', '18', 'loudspeakers', 'spaced', 'insulated', 'electromechanical'], ['electromagnet', 'electromagnets', 'bare', '3', '1'], ['electromagnets', 'electromagnet'], ['electromagnet', 'electromagnets', 'electric'], ['electromagnet', 'electromagnets', 'ferromagnetic'], ['electromagnet', 'electromagnets'], ['electromagnets', 'electromagnet'], ['electromagnet', 'electromagnetedit'], ['electromagnets', 'electromagnet'], ['electromagnet', 'electromagnets', 'loudspeakers', 'ferrimagnetic', 'ørsted', 'ferromagnetic', '18', 'electromechanical'], ['electromagnets', 'electromagnet', 'buzzers', 'electromechanical', 'ferromagnetism', 'something', 'ferromagnetic', 'actuators', 'coil', 'nonmagnetic'], ['electromagnetism', 'cls', 'mass', 'electrodynamics', 'electrostatics', 'magnetism'], ['electromagnetism', 'electrodynamics', "jackson's", 'physics'], ['electromagnets', 'electromagnetism', 'electromagnet'], ['electromagnet', 'electro', 'magnet', 'electronics', 'coil', 'mechanical'], ['electromagnetism', 'electrodynamics'], ['electromagnets', 'electromagnet', 'reason'], ['electromechanical', 'electromechanics', 'troubleshooting', 'electromagnetic', 'electro', 'michajlow', 'mechanical', '04', 'paulo', 'pregowska', 'device', '118', 'another', 'coupling', 'john'], ['electromagnetism', 'electroweak', 'supersymmetry', 'z', 'second-order', 'additional', 'remain']]
TOP TOKENS [['indigestion'], ['indigestion'], ['indigestion'], ['indigestion'], ['indigestion', 'cls'], ['indigestion'], ['indigestion', 'cases'], ['indigestion', 'cls', 'one'], ['indigestion'], ['indigestion', 'gastroesophageal', 'cls'], ['indigestion', 'cls', 'experiencing', 'eating', 'also'], ['indigestion', 'patients', 'onset', 'e', 'antiflatulents', 'regardless', 'symptoms', 'help', 'dyspepsia', 'especially', 'lastly', 'everyone'], ['indigestion', 'onset', 'pathophysiology', 'noninvasively', 'imbalance', 'often', 'contribute'], ['indigetes', 'undikesken', 'perhaps', 'empuries', 'indigetae', 'stephanus', 'lloret', 'could', 'massaliotan', 'clodianus', 'still', 'jonquera', 'unidentified', 'though', 'cls'], ['indiges', 'indige', 'indigetes', 'indigetem', 'indigetibus', 'est', '556', 'dis', '1', '9', 'livy', '10', 'apellatusque'], ['indiges', 'indigetes', 'simply', 'notes', 'presents', 'also', 'term'], [], ['january', 'indichova', 'october'], [], ['indigetes', 'indiges', 'frosinone', "wissowa's", 'epithet', 'indicites', 'divinities', 'pertaining']]
TOP TOKENS [['station', 'stations', 'historythe', 'platforms', 'line', 'underground', 'london', 'platform'], ['station', 'passengers', 'using', 'terminal'], ['station', 'wittenbergplatz', 'stations', 'platforms', 'alexanderplatz', "today's", 'line', 'building'], ['tube', 'line', 'station', 'stations', 'passenger', 'deep-tube', 'underground||following', 'platforms||2', 'underground', 'london'], ['station', 'platforms', 'railway', 'line', 'new', 'terminal', 'platform'], ['stations', 'station', 'line', 'tube', 'following', 'platform'], ['station', 'stations', 'building', 'train', 'platform', 'escalators', 'trains', 'peterstrasse'], ['station', 'stations', 'line', 'platform', 'platforms', 'superfluous', 'knightsbridge', 'mainline', 'island', 'kensington'], ['station', 'central', 'stations', 'train'], ['platforms', 'train', 'station', 'stations', 'central', 'online', 'passenger'], ['station'], ['station'], ['stations', 'railway', 'station'], ['platforms', 'stations', 'railway', 'line', 'station', 'tube', 'serve', 'london', 'underground', 'platform'], ['stations', 'station', 'railway', 'tube', 'line'], ['station', 'railway', 'stations'], ['station', 'stations', 'railway', 'references'], ['station', 'stations'], ['stations', 'station', "station's", 'railway', 'serve', 'tube', 'entrance', 'line', 'platforms'], ['station', 'line', 'platforms', 'stations', 'tube']]
TOP TOKENS [['leptospirosis', 'leptospira', 'leptospiral'], ['leptospirosis', 'leptospira', 'neuroleptospirosis', 'infection'], ['leptospirosis'], ['leptospirosis', 'leptospira', 'leptospires'], ['leptospirosis'], ['leptospirosis'], ['leptospirae', 'leptospiral', 'leptospira', 'haemorrhage', 'lepto'], ['leptospirosis'], ['leptospirosis', 'leptospira'], ['leptospirosis', 'leptospira'], ['leptospira', 'leptospirosis', 'leptospiraceae'], ['leptospira'], ['leptospira', 'leptospiral'], ['leptospira', 'leptospirosis', 'leptospiral'], ['leptospirosis', 'leptospira', 'opportunistic'], ['leptospirosis', 'leptospira'], ['leptospira', 'leptospiraceae', 'long-term'], ['leptospira', 'leptospiraceae'], ['leptospirosis', 'leptospira', 'leptospiral'], ['leptospira', 'leptospirosis', 'pretibial', 'cerebrospinal']]

Processing features:  15%|█▌        | 15/98 [07:03<38:59, 28.18s/it]

getting sample prompt forgetting sample prompt for 23581
 23580
getting sample prompt for 23582
getting sample prompt for 23583
getting sample prompt for 23584
getting sample prompt for 23585
getting sample prompt for 23586
getting sample prompt for 23587
getting sample prompt for 23588
getting sample prompt for 23589
getting sample prompt for 23590
getting sample prompt for 23591
TOP TOKENS [['popular'], ['popular', 'popularity', 'vulgar', 'read'], ['popular', '“', 'popularity', '”', 'unpopular', 'think', 'choice', 'much'], ['popular', 'entertaining'], ['popular', 'popularis', 'popularly', 'adj', 'related'], ['popular', '«', 'science', 'combo', '»'], ['popular', 'popularizations', 'popularization', 'popularisation', 'dominant', 'collect', 'special', 'continuum', 'works', 'science', '1011', 'real', 'market'], ['popular', 'abstracted', 'history', 'approach', 'increasingly', 'thus'], ['popular', 'education'], ['popular', 'popularly', 'called', 'popularize', 'science', 'one', 'respects', 'way'], ['popular'], ['popular'], ['popular', 'popularity', 'song', 'group'], ['popular', 'disambiguation', 'pop'], ['popular', 'democracy'], ['popular', 'popularity', 'election', 'national'], ['popular', 'co-editor', 'march'], ['populär', 'popular', 'magazine', 'majority', 'profile', 'monthly'], ['popular', 'modern', 'photography', 'rainbows', 'december', 'early', 'lifetime', 'one', 'editor-in-chief', 'issue'], ['popular', 'march', 'october', 'professional', 'reviews', 'january', 'around', 'july', 'jargon', 'july–1964', 'look', 'astronomy', 'september', 'junior']]
TOP TOKENS [['marked', 'intense'], ['political', '’', 'por', 'ocupa', 'de', 'anos', 'en', 'corridos', 'corrido', 'un', 'sufrido', 'estafas', 'endured', '‘', 'circulates', 'el', 'element', 'next', 'que', 'machinations'], ['importance', 'confirmative', 'corroborative', 'equidistant', 'verificatory', 'corroboratory', 'validatory', 'de', 'corroborate', '1', 'substantiative', 'verifying', 'concomitant', 'substantiating'], ['matadors', 'matador', 'bullfighting', 'act'], ['blocky'], ['even', 'satisfactorily', 'sentence', 'advances', 'prove', 'organizing', 'stop', 'one', 'following', 'ideology', 'writing', '4'], ['overhanging'], [], ['pronunciation', "kôr'dn", 'b'], ['like'], ['spanish-language', 'benicio', 'ulises', '1917–1996', 'pous', 'del', 'toro', 'mario', '1900–c.1970'], ['surnames'], ['center', 'style', 'align', 'text', '—'], ['szabolcs'], ['documentary', 'producer'], ['politician'], ['r', 'fear', 'frogs', 'ground', '–', 'b', 'dead', 'stories', 'p', 'flame', 'warning', 'goddess', '2012'], ['short', 'defend', 'documentary', 'international', '1986', 'mckennirey', 'director', 'writer'], ['el', 'cronos', 'toro', 'directed', 'coronel', 'del', 'antonio', 'la', 'manuel', 'ciriaco', 'eusebio', 'luis', 'jesus', '1993', 'otono', 'guillermo', 'adolfo', 'argentino', 'borradas', 'de', 'hablara', '2002', 'gabriel', '2004', '1999', '1996', 'hayamos', '1997', 'nosotras', 'opcion', 'dr', 'muerto'], ['cuarón', 'spanish', 'screenwriter']]
TOP TOKENS [['new'], ['earlier'], [], [], ['cdfid'], [], ['new'], [], [], [], ['particular'], [], [], [], [], [], [], [], [], ['noxious']]
TOP TOKENS [['dew', '80'], ['dew', 'significance', 'life', 'contain', "that's", '100', '80'], ['dew', 'regarding'], ['dew'], ['dew', 'called', 'darn', 'water', 'surface'], ['dew', 'form', 'causes', 'accompanies', 'supremacy', 'night', 'sensible'], ['dew', 'put', 'oppressive', 'development', 'speaking'], ['dew', 'temperature', 'cls'], ['dew', 'humidity', 'sep', 'point', 'website'], ['dew'], ['form', 'dew', 'droplets', 'disambiguation', 'film'], ['dew', '1966', '1909–1972', '1946–2020', 'cricketer', 'walter', '1943–2008', 'director', '1944'], ['dew'], ['dew', '2017', '2021', '2019', 'fools', 'links'], ['dew', 'renamed', 'authorities', 'today'], ['dew', 'bullock-dew'], ["dew's", 'dew', 'designs'], ['dew', "dew's", "renamed'dew", 'famous', 'retirement', 'court', 'links', 'external', 'somewhat', 'many', 'internationally'], ['dew', '2009', 'osnabrück', 'nazis', 'hanover', 'mannheim', "roussel's", 'minden', 'kenegunde', 'premiere', 'biography', 'walter', 'entartete', 'padmâvatî', 'ulm'], ['dew']]
TOP TOKENS [['housing'], ['housing', '‘', 'affordable', '’'], ['housing', 'related', 'issues'], ['housing', 'affordable', 'america'], ['housing', 'affordable', 'households', 'bedroom'], ['housing', 'inadequate', 'quality', 'subsidized', 'health', 'affordable'], ['housing', 'affordable'], ['housing', 'development'], ['housing', 'affordable', 'put'], ['housing', 'affordable'], ['housing'], ['housing', 'affordable', 'cls'], ['housing', 'affordable', 'crisis'], ['housing', 'adequate'], ['housing'], ['housing', 'programme'], ['housing', 'made', 'bedrooms', 'renting', 'home', 'apartments', '1'], ['housing', 'affordable', 'adequate', 'overcrowded', 'providing', 'homes', 'households'], ['housing', 'program', 'provides', 'dwelling', 'affordable', 'home'], ['programs', 'housing', 'program', 'quality', 'depression', 'income', 'public', 'inexpensive', 'projects']]
TOP TOKENS [['eritrea', 'eritrean', 'kilometers', 'asmara'], ['eritrea', 'eritreans', 'eritrean'], ['eritrea', 'eritrean', 'asmara', 'site', 'plain'], ['eritrea', 'others', 'asmara', 'people', 'archipelago', 'west'], ['eritrea', 'eritreans', 'eritrean'], ['eritrea1', 'eritreaarticle', 'eritrea', '78.7', '2011', 'literate||male', '2012', 'mi)||46,774'], ['eritrea', 'eritrean', 'eritrea’s', 'asmara', '1993', '63.51', 'rate'], ['eritrea’s', 'eritrea', 'eritreans', 'poverty'], ['eritrean', 'eritrea', 'equally', 'full'], ['eritrea', 'eritrean'], ['disambiguation'], ['eritrea', 'international'], ['eritrea'], ['eritrea', 'eritrean', 'islands'], ['eritrea', 'eritreans', 'eritrean'], ['country', 'eritrea', 'descent', 'disambiguation'], ['eritrean', 'eritrea', '1993'], ['eritrea', 'eritrean', 'eritreans'], ['eritrea', 'eritrean'], ['eritrea', "eritrea's", 'eritrean']]
TOP TOKENS [['vance', "vance's", 'serve', 'vanceboro', 'b'], ['vance', 'life', 'year', 'put', 'carolina', 'north'], ['vance', 'baird', 'https'], ['vance', 'baird', 'https'], ['vance', 'visceral', 'elementary', '–', 'things', 'real', 'wave', '’', 'care'], ['vance', 'union', 'confederate', 'matters', 'cls'], ['vance', 'union', 'confederate', 'matters', 'cls'], ['vance', 'union', 'confederate', 'matters', 'cls'], ['vance', 'secessionists', '25', '”', 'upon'], ['vance'], ['vance', 'vancé'], ['vance', "vance's", 'chilukuri', '2021'], ['vance', 'states'], ['vance', 'california', 'institute', "trump's"], ['vance', '1892–1980', '1872–1946', 'vanče', '1985'], ['vance', 'chief', 'current'], ['vance'], ['vance'], ["vance's", 'vance', '2001', 'states', 'ga'], ['vance', '2021', '2017', '2015', '2006', '2022', 'today', 'earlier']]
TOP TOKENS [['drone', 'quadcopter', 'drones'], ['drone', 'flying', 'fly', 'flight', '2'], ['drone', 'drones', 'dji', 'fpv', 'fly'], ['drone'], ['drone', 'quadcopter', 'fly'], ['drone', 'quadcopter', 'drones'], ['drone', 'drones', 'flying', 'fpv', 'fly'], ['drone', 'flying', 'drones'], ['drone', 'quadcopter'], ['drone', 'dji', 'flying'], ['drone', "drone's", 'drones', 'aircraft'], ['drone', 'uav', 'drones', 'mavic', 'dji', '1080p', "phantom's"], ['drone', "drone's", 'dji', 'drones', 'attached', 'mavic', 'flight'], ['drone', 'dji', "dji's", 'mavic', 'flight', 'camera', '2', '7k'], ['drone', 'dji', 'mavic', 'camera', 'rk3399', 'rc1a'], ['drone', 'drones', 'dji', "that'the", 'uavs', 'aircraft', 'flying', 'flight', 'users', 'one', 'phantom', "pro's", 'fc6310r', 'camera'], ['drone', 'drones', 'quadcopters', 'rotorcraft', 'pilot', 'aircraft', 'camera', 'fpv', '5', 'ghz'], ['drone', 'pro', 'flight', "dji's", 'planes', 'mavic', 'fps', 'helicopters', 'one', 'dji', 'camera'], ['flight', 'insulated', 'camera', "aircraft's", 'enclosed', '920kv', 'dji', 'flexible', 'spin', 'motor', '960kv', 'aircraft', 'internals', 'vibration', 'stator', 'cooling', 'shot', 'wifi'], ['uav', 'drone', 'uavs', 'multirotors', 'drones', 'military', 'planes', 'payload', 'flight', 'rotors', 'wing']]
TOP TOKENS [['truncation', 'truncate'], ['truncate', 'truncates', 'characters'], ['truncation', 'truncate', 'truncating', 'truncations', 'customers.truncations', 'contexts', 'omit', 'truncated'], ['truncate', 'truncating', '“', 'use'], ['truncate', 'truncātus'], ['truncation', 'truncate', 'using'], ['truncate'], ['truncate', 'truncates', 'truncation', 'truncating', 'truncated'], ['truncate', 'truncates', 'truncation', 'truncating', 'truncated'], ['truncation', 'truncate', 'using'], ['truncation', 'truncated', 'protein', 'truncate', 'small'], ['truncation', 'truncations', 'truncated', 'science'], ['truncation', 'truncated', 'regular'], ['truncation', 'truncated', 'statistics', 'omitted'], ['trun', 'truncation', 'truncations', 'truncating', 'truncated'], ['truncation', 'may'], ['truncation', 'truncated', 'truncations', 'edges', 'outwards', 'faces', 'lengths', 'regular'], ['truncate', 'truncated', 'allow', 'since', 'preceded'], ['truncation', 'truncnorm', 'truncations', 'normal', 'truncated', 'let'], ['truncata', 'truncatus']]
TOP TOKENS [['neruda', "neruda's", 'pablo', 'negra', 'nəˈruːdə'], ['neruda', 'veinte'], ["neruda's", 'neruda', 'pablo', 'release', 'veinte', 'de', 'gusta'], ['neruda', "neruda's", 'pablo', 'veinte', 'centres', 'una', 'de'], ["neruda's", 'neruda', 'mentioned', 'caso', 'pablo', 'veinte'], ['neruda', 'neruda’s'], ['neruda’s', 'neruda', 'neruda”', 'pablo', 'included'], ['neruda', 'left'], ['neruda', "neruda's", 'become', 'service', 'writings', 'chile', 'period', '1936'], ['neruda', "neruda's", 'pablo', 'century', 'lifetime'], ['neruda'], ['neruda', 'tr:neruda', 'cs:neruda', 'pt:neruda', 'lv:neruda', 'es:neruda', 'sk:neruda', 'it:neruda', 'eo:neruda', 'de:neruda', 'fr:neruda'], ['neruda', "neruda's", 'using', 'e-flat', 'staatskapelle', 'jiří'], ['neruda', 'oslavou'], ['magruder', "magruder's"], ["neruda's", 'neruda', 'parral', 'tolra', 'manana', 'entusiasmo', 'neftali', 'career', '1914', 'included'], ['magruder', 'first', 'collection', 'school', 'geffen', 'six-time'], ['nerudia', 'neruda', 'huber'], ['garuda', 'garudas', 'garudamon', 'garud'], ['neruda', 'neruda-arlberg', 'arlberg-neruda', 'empire']]
TOP TOKENS [['512', 'used', '4096', '512e'], ['annihilation', 'aspects', 'things', 'emission', 'conceptual', 'aspect', 'place', 'take', 'lot', 'something', 'many'], ['powered', 'due', 'emission'], ['01793', 'annual', '252', '414694', 'support', '0116', 'helping', 'meet', 'people', 'funded'], ['ties', 'close', 'think', 'means', 'good', 'mind'], ['idea', 'someone', 'television', 'people', '’', 'becomes', 'talk', 'long', 'surmised', 'often', 'story'], ['know', 'collect', 'significant', 'keep', 'trying', 'helps', 'us', 'put', 'using'], ['around', 'make', 'operation', 'done', 'think', 'order'], ['art', 'area'], ['help', 'produce', 'empowers', 'enables', 'understand', 'providing', 'isotopes'], ['help', 'involved', 'prevent', 'made', '11', 'allow', 'scientist', 'prominent', 'role', 'informants', 'remained', "organisation's", "jack's", "michael's", 'organisation'], ['helped', 'prevent', 'area', 'massive', 'agents', 'virus', 'city', 'sep', 'using'], ['herbert', 'working', 'diseases', 'drama', 'alongside', 'cast', 'leonard', 'reports', 'specialist', 'conspiracy', 'follows', 'lex', 'truthlighter', 'cannerts', 'richard', 'high', 'mayfield', '2016', 'works', 'dr', 'co', "leanne's", "mother's", 'within', 'main', 'vlogger', 'lives', 'charge', 'lommers', '19', 'directly', "lex's", "teresa's", 'leaving'], ['drama', 'american', 'network', 'addict', 'films', 'overdoses', 'television', 'jr', 'sep'], ['1980s', 'academic', 'broadened', 'staff', 'added', 'laid', 'time', 'sciences'], ['ian', 'centre', 'j', 'management'], ['helping', 'personnel', 'provides', 'information'], ['drug', 'life', 'overdose', 'supposed'], ['helping', 'agent', 'agents', 'learned'], []]
TOP TOKENS [['ethan', 'ethans', 'culture', '1989', 'states', 'made', 'world'], ['ethan', 'times', 'think'], ['ethane', 'temperature', '0'], ['ethane', 'ethanemethane'], ['ethane', 'temperature', 'recently', 'liquid'], ['ethane', 'hydrocarbons'], ['ethan', 'like', 'years', '’', 'confused', 'someone', 'find', 'way', '”'], ['ethan', 'organizations', 'currently'], ['ethan', '“', '’', 'humour', 'way', 'humanity', 'relative', 'insight', 'indigo'], ['ethan', 'morning', 'life', 'appearance', 'end', 'way', '1789', 'astir', 'presents'], ['ethane', 'ethan'], ['ethan', 'born', 'panizza'], ['ethan', 'see', 'b'], ['ethan', 'c', 'born', 'corson'], ['ethan', 'born'], ['ethan', 'mcsweeny', 'born'], ['ethan'], ['ethan'], ['ethan', 'first', 'lead', '2014', 'games'], ["ethan's", 'ethan', 'included', 'capcom', 'world', 'due']]

Processing features:  16%|█▋        | 16/98 [07:30<38:00, 27.81s/it]

getting sample prompt forgetting sample prompt for 23593
getting sample prompt for 23594
 23592
getting sample prompt for 23595
getting sample prompt for 23596
getting sample prompt for 23597
getting sample prompt for 23598
getting sample prompt for 23599
getting sample prompt for 23600
getting sample prompt for 23601
getting sample prompt for 23602
getting sample prompt for 23603
TOP TOKENS [['stuck', 'nagging', 'change', 'get', 'perspective', 'unstuck', 'start', '“what’s', 'keep'], ['confusing', 'mess', '1', 'difficult', 'situation', 'get', 'scandal', 'anything', 'try', 'possible', 'toward', 'excitement'], ['understand', 'stuck', 'bit', 'defensive', 'disengagement', '’', 'purposes', 'releasing', '‘', 'literally', 'move', 'caught', 'signs', 'circles', 'ness', 'deadlines', 'forward', 'underlying', 'forth', 'back', 'help', 'deadlocked', 'pressure', 'restate', 'occur', 'going', 'pattern', 'especially', 'really'], ['stuck', 'cls', '’', '“', 'reconceive', 'implies', '—', 'white', '”', 'could', 'turns', 'asking', 'stick', 'seems', 'swapping', 'shades', 'one'], ['ˈdailemə', 'diˈlemə', 'dilemma', 'dilemmadilemma', 'valþrong', 'das', 'διλημμαdilema', 'ددوو', 'عاجز', 'vanskelig', 'دى', 'ناخوشایند', 'दविधा', 'unk', 'two', 'use', 'word', 'дилема', 'ogongur', '،', 'ทางเลอกทยงยาก', 'valg', 'дилемма', 'تنگنا', 'مازق'], ['think', 'trapped', 'feel', 'escape'], ['english', "of'trapped'example", 'think', 'trapped', 'times', "containing'trapped'these", "for'trapped'british", 'feel', "of'trapped'in", 'free', 'goose', 'inside', 'escape', 'sunday', 'fissures', 'talking', 'longing', 'behind', '2010', 'cls', 'nerves', 'coping', 'hundreds', 'instead'], ['conflicting', '’', 'either', 'high', 'cls', 'faced', '”', 'three', 'courses', 'advance', 'asylum', 'words', 'must', 'involved', 'moral', '“', '—', 'dilemmas', 'action', 'dismissal', 'roles', 'panetta', 'included', 'made', 'instead', 'u', 'weeks', 'also', 'necessitates', 'americans', '2012', 'servants', 'established'], ["“i'm", 'understand', 'fence', 'stick', 'fence.”', 'kind', 'stay', 'know'], ['3', 'on(redirected', '2', 'something', '1', 'time', 'tom', 'hollered', 'hey', 'safety', 'mid-1800s', "on—that's", 'late', 'hold'], ['stuck', 'middle', 'tv'], ['halliday', 'geyser', 'apink', 'dilemma', '1962', '1900–1976', 'cleary', 'song'], ['stuck', 'album', 'film', 'csi', 'starring'], ['halo', 'stereophonics', '2011', 'stuck', 'taxi', '1994', 'keep', 'trapped'], ['janibekyan', '2002', 'peg', 'abrams', 'starrett', '2001', 'iron', 'koontz', 'chastity', 'indian', 'cls', 'trapped', 'hearne', 'brolin', '2013', 'alexandra', '1982', '1937', 'indus', 'alan', 'sos', 'vivica', 'silva', 'haitian', 'retrievin'], ['stuck', '2017–18', 'episodes', '2016', 'deal', 'three', 'episode', 'gadgets', 'quinceañera'], ['say'], ['stuck', 'middle', 'a-side', 'radio', 'reminisce', 'hit', 'surrender'], [], []]
TOP TOKENS [['000', 'refinery', 'eight', 'transportation', '790', 'school', 'brewery', 'programs', 'plants', 'construction', 'schools', 'building', 'heights', 'dairy', 'areas', 'plus', 'francophone'], ['gins'], ['sex', 'age', 'hair', 'hairs', 'among', 'ensure', 'island', 'time', 'joyita', 'years'], ['khufu', 'tura'], ['ones'], ['get'], ['wallnutt', 'seven', 'fine', 'age', 'driver', "constable's", 'man', 'force', "wade's", 'strength', 'wade', 'pukekohe', 'cook'], ['hauls', 'north', 'stone', 'khufu', 'ur', 'day'], [], ['‘', 'valley', 'large'], ['district', 'chendār', '31'], ['1963', 'areas', '1,648', 'mixed-commune', 'within', 'endis', '1,386', '1956', 'water', 'calcareous', 'aîn', 'river', 'hence', 'boumedienne', 'region'], [], [], ['carlos', 'schwager', 'tercera', 'name', 'ninth', 'year', 'named', 'secondgontier', 'lota', 'división', 'top-division', 'teams', 'season', 'de', 'coronel-based', 'years', "limenza's", 'fourth-tier', 'campaign', 'runner-up', 'nova', 'ñublense'], [], [], [], [], []]
TOP TOKENS [['acidity', 'acid', 'sour'], ['acidity', 'acid', 'sour'], ['acidity', 'acidic', 'acid', 'ph'], ['acidity', 'ph', '1', 'week'], ['acid', 'acidic', 'acidity', 'acids', '“', 'ph', 'word'], ['acidity', 'acid', 'acids', 'health'], ['acidity', 'acids', 'acidic', 'acid', 'person'], ['acidity', 'aciditycauses', 'acid'], ['acid', 'acidity'], ['acidic', 'acid', 'acidophilus', 'acidimetry', 'acidity', '“acidus”', 'acidosis', 'acidogenic', 'acidophil', 'acidize', 'acidify', 'acidolysis', 'acido+genic', 'acidophilic', 'acido', 'word'], ['acid', 'acid-test', 'acid1', 'acid3', 'acid2'], ['acidophile', 'acidic', 'acidofilia', 'acid', 'acidophilus', 'highly', 'acidophobe'], ['acidus', 'acidum', 'acida', 'acid', 'disambiguation'], ['acidic', 'acid'], ['acid', 'acida'], ['webbläsartester#acid1', 'acid1', 'acid3', 'acid2', 'de:acid', 'acid', 'browsertests)#acid', 'sv:acid'], ['acid', 'acidus', 'acida', 'acidum', 'disambiguation'], ['acid', 'acidophobic', 'acidity', 'acidifying', 'acidic', 'acidophile', 'acidophobes', 'acidophile/acidophobe', 'acidophobe', 'acidophoby', 'ph', 'acidophobia'], ['acidophila', 'acid', 'acidianus', 'acidophile', 'acidophilus', 'acidified', 'acidic', 'acidophiles', 'acidithiobacillales', 'acidophilic', 'acidiphilum', 'acidobacteriota', 'ph', 'highly', 'conditions', 'facultatively', 'cls', 'environments'], ['acidity', 'acid', 'acidifiers', 'acidifier', 'ph', 'acids']]
TOP TOKENS [[], ['9521745', 'august', '7'], [], [], ['purpura', 'unk'], [], ['21'], [], [], [], [], [], ['95', '1520609186398'], [], [], [], [], [], [], []]
TOP TOKENS [['currently', 'note'], [], [], [], [], [], [], ['configure'], [], [], [], [], [], ['known'], [], [], [], [], [], []]
TOP TOKENS [["girard's", 'girard', 'b'], ["girard's", 'girard', 'girardville', 'avenue', 'richland', 'chisholm', 'area', 'thoroughfare', 'gentilly'], ['girard', 'vrije', 'numero', 'tubingen', 'francaise', 'doctor', 'envie', 'anvers', 'italy', '2013', 'rene', 'padova', '1990', 'univeritat', 'austria', 'universite', 'humility', 'honors', 'philosophie'], ['girard', 'vrije', 'numero', 'tubingen', 'francaise', 'doctor', 'envie', 'anvers', 'italy', '2013', 'rene', 'padova', '1990', 'univeritat', 'austria', 'universite', 'humility', 'honors', 'philosophie'], ['girard', 'jr', 'christopher', 'upper', 'carlton', 'area'], ["girard's", 'called', 'second', 'formula', 'triangle', 'emphasizes', 'finally', "t'have", 'fact'], ["girard's", 'called', 'second', 'formula', 'triangle', 'emphasizes', 'finally', "t'have", 'fact'], ['girard', 'route', 'hopkins', 'mechanism', 'francaise', 'accomplishing', 'access', '–', 'shoes', 'power', 'explanatory', '’', 'rene', 'purportedly'], ['girard', 'shullenberger', 'supplant', 'philosophical', '’', 'overtone', 'extrinsic', 'merits', 'severity', 'thinker', 'passing', 'account', 'desire', 'bourgeoisie', 'miłosz', 'conventionally'], ['girard', 'mechanism', '70s', '’', 'imitativeness', 'furthermore', 'items', 'aristotle', 'theorized', 'rene', 'mimesis', 'fact', 'relative', '2015', 'narrowly', 'world', 'came'], ['girard', 'township', 'market-frankford', 'avenue', 'line', 'mathematician', 'girard-perregaux', 'gerard', 'girardville', 'giraud', 'count'], ['girard', '1815–1890'], ['girard', '1765–1836', 'geoffrey', 'serge', 'patrick', 'samuel', 'canadian'], ['girard', 'sophomore', 'touchdowns', 'career', 'football', 'text', 'college', 'points', '18', 'prospect', 'left'], ['vienna', 'girardi', 'cerodrillia', 'suchosaurus', '1952', 'notropis'], ['girard', 'ligue', 'jean-luc', 'footballers', 'profile', 'became', 'football', 'managers', 'links', "men's", 'f.c'], ['girard', 'education', 'links', 'external', '64', 'references', 'including', 'census'], ['girard', 'network', '2019', 'event', 'portion', 'skating'], ['girard', '500', 'households', '56', 'education', 'southeast', '250'], ['girard', 'career', 'jimmer', 'gatorade', 'nysswa', 'prospect', 'sophomore', 'fredette', 'joseph', 'senior', 'fifth', 'focus', 'points', '4']]
TOP TOKENS [["davidson's", 'davidson', 'quine', 'others', '1986', '1994', '1991', 'ed', 'evnine'], ["davidson's", 'davidson', 'presents', 'coherence', 'book', 'individually'], ['davidson', 'level', 'system', 'u', 'example', 'password', 'guardian', 'username', 'states', 'eligibility'], ['davidson', '’', 'hintikka'], ['davidson', '’', 'nevertheless', 'us', 'aspect', 'work', 'intelligence', 'avatars'], ['davidsons', 'davidson', 'however', 'general', 'events', 'amused', '1971', 'novato', 'story', 'detail', 'happen', 'avalanches', 'works', 'among', 'style', '1972', 'hidden'], ["davidson's", 'davidson', 'observes', 'robbins', 'palace', 'sober', 'even', 'comments', '1911'], ['davidson', 'general', 'nomination', 'service', 'war', 'w', 'b', 'shortly', 'army', 'john', 'later', 'u'], ['davidsons', "davidson,'son", 'davidson', "duncan's", 'john', 'member', 'duncan', 'times'], ['davidson', 'davidsongifted'], ['davidson', "davidson's", 'also', 'coincidentally', '1991', 'career', 'bay', 'child', 'entertainment'], ['davidson', '2010', 'life'], ['davidson', '2023', 'time', 'edition', '2010', 'notes'], ['davidson', "davidson's", 'agency'], ['davidson', 'century', 'american', 'musician', '2009', 'family', 'online', 'life', 'death', 'recognition'], ["davidson's", 'davidson', 'menswear', 'development', 'disambiguation', 'fort', 'cincinnati', 'college', 'north'], ['davidson', 'offseason', 'wife', 'also', 'sportspeople', '1981', 'well', 'years', 'ohio'], ['davidson', 'stine', 'stories', 'born', 'links', 'campaign', '2012', '2014'], ["davidson's", 'davidson', 'arts', 'life', 'also'], ['davidson', 'acting', '06', '1', "zoey's", '1994', '2']]
TOP TOKENS [[], ['caps', 'letters', 'font', 'position', 'shouting', 'bit'], [], [], ['chamber', 'cardinal'], [], [], [], [], [], [], [], [], ['twd'], [], ['polyeder', 'cell', 'polytope', 'dimensions', 'surface'], ['scaling', 'text', 'inappropriate', 'caps', 'readability', 'features'], [], ['state', 'chain', 'dynamics'], []]
TOP TOKENS [['fpga', 'subsystems', 'fpgas', 'devices', 'components', 'fpga-based'], ['vlsi', 'circuit', 'circuits'], ['vlsi', 'asic', 'transistor', 'transistors', 'sram', 'circuit', 'architecture', 'gate', 'nmos', 'gates', 'submicron', 'cmos', 'multiplexer'], ['microelectronics', 'circuits', 'devices', 'transistors', 'circuit', 'ic', 'device', 'technologies', 'semiconductor', 'cmos'], ['chip', 'device', 'architecture', 'cmos', 'features'], ['pci', 'card', 'motherboard', 'initiator', 'cards', 'motherboards', 'bit', 'resistors', "slot's", 'one'], ['circuit', 'fpgas', 'chip3', 'chip2', 'chip1', 'chips', 'chip', 'busa', "is'0'the", 'bit', 'transceivers', 'signal', 'signals'], ['circuit', 'device', 'chip', 'devices', 'pci', 'capacitance', "bus's", 'ram'], ['ics', 'ic', 'en', 'int', 'pb', 'signal'], ['transistors', 'sram', 'chip', 'circuit', 'transistor', 'ic', 'circuits', 'circuitry'], ['transistor', 'circuits', 'circuit', 'devices', 'semiconductor', 'fpga', 'chip', 'microprocessors', 'vhdl', 'device', 'chips', 'interconnects', 'ic', 'hardware', 'fpgas', 'asic', 'eeprom', 'diode', 'asics'], ['device', 'semiconductor', 'semiconductors', 'chip', 'chips', 'multifunctional', 'signal', 'example', 'board'], ['ics', 'circuits', 'chip', 'transistors', 'capacitors', 'microprocessor', 'processor', 'circuit', 'devices', 'circuitry', 'coils', 'electronics', 'ic', 'semiconductor', 'diodes', 'widths'], ['fpga', 'circuit', 'processors', 'fpgas', 'devices', 'signal', 'system', 'multiplexing', 'flops', 'architecture', 'signals'], ['ics', 'transistors', 'circuits', 'circuit', 'circuitry', 'cmos', 'vhdl', 'chips', 'asics', 'chip', 'arrays', 'fpgas', 'signal', 'ams', 'technology', 'devices', 'gate'], ['stmicroelectronics', 'ics', 'circuit', 'transistors', 'capacitors', 'microprocessor', 'chip', 'semiconductor', 'circuits', 'chips', 'electronic', 'cmos', 'systems', 'system', 'resistors', 'inductors', 'applications'], ['circuit', 'device', 'chip', 'pci', 'chips', 'capacitance', 'devices', "bus's", 'signals', 'i²c', 'bus', 'ram', 'leds'], ['semiconductor', 'microprocessors', 'transistors', 'microprocessor', 'transistor', 'device', 'lsi'], ['transistors', 'ics', 'circuits', 'circuitry', 'chip', 'ic', 'device', 'interconnect', 'circuit', 'subblocks', 'devices', 'vhdl', 'vias', 'architectural', 'interconnections', 'wafer', 'silicon', 'processing'], ['microprocessors', 'semiconductor', 'circuitry']]
TOP TOKENS [['cortisone', 'corticosteroids', 'glucocorticoid', 'dexamethasone', 'prednisolone', 'prednisolo', 'methylprednisolone', 'mineralocorticoid'], ['corticosteroids', 'dexamethasone'], ['corticosteroids', 'cortisone', 'dexamethasone', 'prednisolone', 'prednisone', 'fluticasone'], ['glucocorticoids', 'glucocorticoid', 'cortisone', 'corticosteroids', 'prednisolone', 'prednisone'], ['cortisone', 'corticosteroid', 'corticosteroids', 'prednisone', 'prednisolone'], ['glucocorticoid', 'glucocorticoids', 'beclomethasone', 'fluticasone', 'budesonide'], ['glucocorticoids', 'prednisolone', 'prednisone', 'cortisone', 'dexamethasone'], ['corticosteroid', 'prednisolone', 'dexamethasone', 'corticosteroids', 'prednisone', 'corticosteroids2', 'budesonide', 'mineralocorticoid', '9', 'hydrocortisone'], ['dexamethasone', 'corticoster', 'corticosteroids', 'corticosteroid', 'methylprednisolone', 'prednisolone', '60'], ['corticosteroids', 'glucocorticoid', 'prednisolone'], ['glucocorticoid', 'glucocorticoids', 'dexamethasone', 'fludrocortisone', 'mineralocorticoid'], ['glucocorticoids', 'dexamethasone', 'acetonide', 'shock', 'triamcinolone'], ['dexamethasone', 'corticosteroids', 'corticosteroid', 'methylhydrocortisone', 'corticosterone', 'methylprednisolone'], ['glucocorticoids', 'glucocorticoid', 'corticosteroid', 'corticosteroids', 'glucocorticosteroids'], ['corticosteroids', 'glucocorticoid', 'prednisolone', 'corticosteroid'], ['glucocorticoid', 'corticosteroid', 'prednisolone', 'prednisone', 'mineralocorticoid', 'rheumatoid', 'sclerosis'], ['dexamethasone', 'corticosteroids'], ['corticosteroids', 'corticosteroid', 'glucocorticoid', 'cortisone', 'prednisone'], ['glucocorticoids', 'dexamethasone', 'corticosteroids'], ['glucocorticoids', 'dexamethasone', 'fluticasone', 'lipocortin']]
TOP TOKENS [['died', '1787', 'winifred'], ['marriage', 'license', 'listed', 'death', 'living'], ['j', 'c', 'h', 'january', 'jane', 'p', 'elizabeth'], ['march', 'listed', 'august'], ['listed', 'b', '“', 'certificate', 'howell', 'guy', 'one', 'moved', 'woman'], ['listed', 'b', '“', 'certificate', 'howell', 'guy', 'one', 'moved', 'woman'], ['included', 'wm', 'listed'], ['law', '1787', 'b', 'listed', 'died', 'tithable', '4', 'death', '5', 'intermarried', '31'], ['b', 'mrs', '1787', 'm2', 'm3', 'married'], ['lived', 'moved', 'b', 'living', 'john', '11', 'married', 'w'], ['died', 'married', "parents'marriage", 'march', '1642', 'january', 'aug', 'living', 'richard', 'c'], ['–', 'c', '1843', 'january', '1791'], ['13', 'september', 'zachariah', 'february', 'peter', 'recorded', 'grandson', '1803', "abigail's"], ['law', 'married', 'joseph', 'john', 'surrey', 'co', 'died', 'elizabeth', 'third', 'dorking', 'second', 'born', 'sarah', 'jonathan', 'abigail', 'everill', '1627', 'braintree', '1655', 'november', 'may', '23'], ['died', 'born', '20', '5', 'married', '28', '1653', '7', 'samuel', '30', '13'], ['–', 'died', 'living', 'b', 'born', 'area', 'abt', '1830', 'samuel', '1792'], ['nee', 'married', 'sr', 'b', 'william', 'jr', 'mother'], ['mary', 'died', 'wilton', 'frisby', 'active', '1786', 'lived', 'samuel', '1781', '1806', 'jacob', 'catharine', 'charles', '–', '1856', 'franck', 'married', '1832', 'mrs', 'william'], ['b', 'lawrence', 'gent', 'july', 'october', 'feb', 'miss', 'april', 'married', '1776', 'joseph', '1839'], ["cattle'he", 'hoxton', 'listed', 'wrington', 'children', "1627'division", 'january', 'one', 'available', 'born', 'died']]
TOP TOKENS [[], [], [], ['library'], [], [], ['65'], [], [], [], [], [], [], [], [], [], [], [], [], []]

Processing features:  17%|█▋        | 17/98 [08:01<38:44, 28.69s/it]

getting sample prompt forgetting sample prompt for 23605
 23604
getting sample prompt for 23606
getting sample prompt for 23607
getting sample prompt for 23608
getting sample prompt for 23609
getting sample prompt for 23610
getting sample prompt for 23611
getting sample prompt for 23612
getting sample prompt for 23613
getting sample prompt for 23614
getting sample prompt for 23615
TOP TOKENS [['scapulars', 'scapular'], ['scapular', 'scapulars', 'scapolare', 'scapula', 'spiritual'], ['scapular', 'esteemed'], ['scapular', 'scapula'], ['scapulae', 'scapular', 'scapula'], ['scapular'], ['scapular', 'scapulars', 'https://en.wikipedia.org/wiki/scapular'], ['scapular', 'scapulars'], ['scapular', 'scapulars', 'laypeople', 'front', 'medical'], ['scapula', 'scapular', 'scapulae'], ['scapular', 'scapulars'], ['scapular', 'scapulars'], ['scapula', 'scapular', 'name'], ['scapular', 'scapulars'], ['scapular', 'scapulars', 'scapulae', 'front', 'square'], ['scapular', "scapular's"], ['scapular', 'scaption'], ['scapular', 'scapulars'], ['scapy', 'scapy3k', '2.4.0', 'gnuplot'], ['scapular', 'scapulars', 'devotional']]
TOP TOKENS [['permit', 'permits', 'issuance', 'term'], ['permit', 'permits', 'issuance', 'term'], ['permit', 'permitpermit', 'permitting', 'word', 'allow', 'written', 'becomes', 'permitted', 'implication', 'meaning', 'permitteth'], ['permits', 'permit', 'building'], ['permit', 'permits', 'getting', 'proper', 'construction', 'secure', 'building', 'required', 'serious', 'obtain', 'fees'], ['permits', 'permit', 'obtain', 'millions', 'importance', 'paperwork', 'permitting', 'impose'], ['permit', 'permits', 'get', 'permitting', 'getting', 'obtaining', 'lastly', 'property', 'knowing', 'sure', 'requirements'], ['permit', 'permits', 'proper', 'permitting', '330', 'runs', 'building', 'forward', '1'], ['permit', 'permits', 'permittee', 'authorized', 'issuing', 'requirement', 'statement', 'permitting', 'authorizing', 'application', 'issues'], ['permit', 'permits', 'getting', 'get', 'need', 'requires', 'needs', 'building'], ['permit', 'one-way', 'international', 'restricted', 'driving', 'demonstration', 'adding', 'allows'], ['permits', 'permitting', 'obtain', 'permit', 'zones', 'elaborate', 'gaining', 'perceive', 'time', 'granted', 'denied'], ['permits', 'permit', 'allows', 'required'], ['permit', 'permits', 'obtain', 'obtaining', 'comprehensive', 'governing', 'different', 'given', 'multiplicity', 'requesting', 'permission', 'seeking', 'worker'], ['permits', 'permit', 'recognizes', 'nonresident', 'recognize'], ['permit', 'permits', 'special', 'apply', 'issuing', 'regarding', 'given', 'issuance'], ['issued', 'permit', 'advantages'], ['permit', 'permits', 'march', 'area', 'february', 'commissioning', 'shakedown', 'later', 'november', '13', '29', 'war', 'humphreys', 'ii', '1937', 'uss', 'pre', '1939'], ['permits', 'permitting', 'prior', 'manager', 'issued'], ['permit']]
TOP TOKENS [['pongal', 'margazhi', 'capricorn', '14th', 'duration'], ['pongal', 'named', 'word'], ['pongal', "today's", "manickavachakar's", 'rise', 'january-february', 'veeraraghava', 'although', 'i.e', 'era', 'margazhi'], ['pongal', 'sakranti', 'katya', '15', 'main'], ['pongal', 'celebrate', '“', 'turmeric', 'term', 'traditional'], ['pongala', 'pongal', 'kanakathur', 'palakunnu', 'puthiyakavu', 'although', 'annual', 'bhagavathy', 'form', 'ethirealppu', "of'thai", 'mulluthara', 'kshetram', 'navarthri'], ['pongal', 'pngal', 'form', 'celebrate'], ['pongal', 'kolam', 'bengal', 'cooking', 'symbolically', 'sankranthi', 'maghe', 'specifically', 'dawn', 'cardamom', 'preceding', 'thai'], ['pongal', 'prepare', 'calendar', 'houses', 'also', 'celebrated'], ['pongal', 'date', 'elaborate', 'festival', 'india'], ['pongal'], ['weingartner', 'weingarten', "weingarten's"], ['mungar', 'north-east'], ['aangan', 'khadija', 'digital'], ['mungana'], ['pongal', 'pongalo', 'mung'], ['warangal', "al-din's", 'al-din', 'tughluq'], ['amangal', 'devarakonda'], ['pongani', '2/6th', 'towards'], ['xingang', '2020']]
TOP TOKENS [['asterisk', 'asterisk-based'], ['asterisk'], ['asterisk'], ['asterisk', 'http://www.asterisk.org/support/about'], ['asterisk', 'etc/asterisk'], ['asterisk', 'asterisknow', 'host', 'process'], ['basilisk', 'basilisks'], ['basilisk', 'basilisks'], ['basilisk', 'mind', 'would', 'symbolic', 'example'], ['asterisk'], ['basilisk', "d'erlanger", 'software', 'cassowary'], ['asterisk'], ['frisk', 'frisking'], ['basilisk', 'locality'], ['asterisk', 'asterisks', 'also'], ["basilisk's", 'basilisk', 'basilisks', "roko's"], ['frisk'], ['basilisk', 'also', 'war', 'hms', 'exploratory', 'initially'], ['asterisk', 'asterisks', 'asteriskos', 'time'], ['basilisk', "basilisk's", 'basiliskos', 'basileus', 'βασιλευς', 'lethal', 'hole']]
TOP TOKENS [['bourbon'], ['bourbon', 'bourbons', 'nowadays', 'duchies'], ['bourbons', 'bourbon', 'bourbonnais', 'clermont'], ['bourbon', 'today', 'states'], ['bourbon', 'bourbons', 'bourbon-sicilies', 'bourbon-vendômes', 'bourbon-condé', 'bourbon-conti', 'spanish'], ['bourbon', 'despite'], ['bourbon', 'bourbons', 'water', 'temperature', 'abcs', 'science', 'containers'], ['bourbon', 'bourbon’s', 'bourbon,”', 'world', 'family'], ['bourbon', 'bourbons'], ['bourbon', 'bourbons'], ['bourbon', 'bourbon-lancy', 'disambiguation', 'democrat', 'kentucky', 'horse', 'bourbonnais', 'vanilla'], ['bourbon', 'stem', 'pests'], ['bourbon', 'pronounced'], ['bourbon', 'older', 'census', '8', '51', 'town', '10'], ['bourbon', "bourbon's", '1538', 'time', '5', '1535'], ['bourbon', 'bourbons', 'france'], ["bourbon's", 'bourbon'], ['bourbons’', 'bourbon-two', 'bourbons', 'bourbon'], ['bourbon', 'year', 'august', 'october', 'may', 'yorkshire', 'hunmanby', 'named', 'pedigree', 'heats'], ['bourbon', 'kentucky', 'disambiguation']]
TOP TOKENS [['belonging', 'belong'], ['belonging', 'belong', 'better'], ['belonging', 'experience', 'belongingapr', 'sense', 'deem', 'starting', 'disease'], ['belonging', 'belong', 'chocolat', 'sense', 'benefit', 'lasse', 'practice', 'amazing', 'related'], ['belong', 'belongs', 'part'], ['belonging', 'belong', 'israel', 'allowed', 'ways', 'let', 'showers', 'really', 'people'], ['belonging', 'industry', 'belong', 'sense', 'also', 'feeling', 'support', 'approach', 'feel'], ['belonging', 'belong', 'belongingness', 'sense', '”', '“', 'wiley', 'fulfil', 'us', 'something'], ['belonging', 'brains'], ['belonging', 'sense', 'belong', 'create'], ['belong', 'belonging', 'belongingness'], ['belonging', 'belongingness', 'belong', 'album'], ['belongingness', 'belong', 'belonging', 'feeling', 'sense', 'familiarity'], ['two', 'belonging', 'wales', 'environment'], ['belong', 'belonging', 'sense', 'improving', 'ultimately', 'especially', 'foster', 'depicted', 'fit'], ['belonging', "students'feelings", 'within', 'identify', 'meaningful', "students'school", 'greater', "students'sense"], ['belong', '23', 'day', 'december', '10', 'fortuna', 'march', 'continued', "jerome's", 'website'], ['belonging', 'guise', 'george', 'winifred', 'gruyter', 'lady', 'de'], ['belongingness', 'belonging', 'belong', 'feelings', "students'sense", 'sense', 'strong', 'participation', 'significant', 'within'], ['belong', 'fan', 'offered', 'free', 'directly', 'sound', 'various', '2006']]
TOP TOKENS [['earl', 'earls', 'lord', 'viscount', 'viscounts', 'peerage', 'created', 'sir', 'baronet', 'caufield', 'acheson'], ['earl', 'lord', 'earldom', 'earldoms', 'earls', 'lords', 'became', 'baron'], ['became', 'earl', 'created', 'lord', 'peerage', 'baron'], ['baron', 'earl', 'baroness', 'created', 'howard', 'barons', 'viscounts', 'viscount', 'beaumont'], ['baron'], ['made', 'baron', 'earl', 'earldom', 'created', 'marquess', 'lord', "earl's", 'duke', 'peerage'], ['douglas', 'earls', 'peerage', 'peerages', "the'marquess"], ['earl'], ['baron', 'earl', 'peerage', 'marquess', 'sir', 'duke', 'william', 'hon', 'created', '1st', 'lady'], ['earl', 'countess', 'marquess', 'earldom', 'earls', 'lords', 'lord', 'peerage', 'created', 'cls'], ['baron', 'lord', 'earl', 'earldoms', 'howard', 'peerage', 'viscount', 'dukedom'], ['earl', 'earldoms', 'countess', 'gower', 'lord', 'peerage'], ['earl', 'see', 'earldoms', 'also'], ['earl', 'baron', 'created', 'viscount', 'earldom', 'earls', 'viscounts', 'also', 'earldoms'], ['peerage', 'peerages', 'viscount'], ['baron', 'earl', 'lord', 'viscount', 'howard', 'barons', 'peerage', 'created', 'creation'], ['earl', 'marquess', 'baron', 'peerage'], ['earl', 'baron', 'lord', 'earldoms', 'countess', 'peerage', 'titles', 'created', 'greville'], ['earl', 'earldom', 'peerages', 'duke', 'peerage', 'lord', 'earldoms', "earl's"], ['earl', 'baron', 'created', 'marquess', 'lord', 'duke']]
TOP TOKENS [['groove', 'grooves', 'record', 'grooved', 'surface', 'furrow', 'needle', 'tool', 'song', 'depression', 'well', 'organ', 'groovemiddle'], ['grooves', 'groove', 'making'], ['groove', 'grooves', 'resolve'], ['groove', 'oesophageal', 'initiate', 'oseophageal'], ['groove', 'player', 'dynamic', 'nuance', 'anatomy', 'core', 'harmony'], ['grooves', 'grooved', 'spirally', 'sure', 'muskets', 'bore', 'musket', 'would'], ['grooves', 'groove', 'deep', 'tongues', 'well', 'tongue'], ['grooves', 'groove', 'music', 'important', '”', '“', 'embrace', '14', 'syntax', 'making', 'performance', 'involves', 'cls', 'emphasis'], ['groove', 'grooves', 'interesting', 'feel', 'asking', 'like', 'yes', 'need', 'question', 'minute', 'currently', 'bar', 'fit', 'learning'], ['groove', 'grooves', "the'groove", 'mean', 'cool', 'dunbar', 'note'], ['groove', 'grooves', 'xm', 'album', 'joinery', 'band'], ['grooves', 'groove', 'depression', 'wheel', 'rail', 'gasket', 'grooved', 'metal', 'material'], ['groove', 'grooves', 'grain', 'flooring', 'fields', 'construction', 'drawers'], ['groove', 'grooves', 'piece', 'drummer', 'breakdowns', 'kit'], ['groove', '2001', '2006', 'platforms', 'skillground'], ['groove', 'variations'], ['groove', 'intertubercular'], ['groove', 'intertubercular', 'bicipital'], ['groove', 'grooves', '1999', 'release', 'tunes', 'awards', 'premiered', 'bedrock', 'plot', '6.1/10', 'china', 'tells', 'brother'], ['groove', '1950s', 'perspective', 'guitar', 'fusion', 'enjoyably']]
TOP TOKENS [[], [], [], ['boileau'], ['conservative', 'conservatives'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [[], ['take', 'character', 'social', 'overseas', 'spend', 'sister', 'exhibits', 'state', 'put', 'join', 'get'], ['something', 'spend', 'ideas', 'go', 'get', 'explore', 'make', 'activity', 'bake', 'buy', 'ride', 'door'], ['81', 'ideas', 'visit', 'hold', '82', 'monday', '78', '79', 'buy', 'run', 'make', 'ride', '102'], ['go', 'something', 'today'], ['put', 'sit', 'find'], ['take', 'make', 'ride', '19', '17', '26', '18', 'camp', 'part', '20', '28'], ['hit', 'visit', 'try'], ['enjoy', 'get', 'grab', 'popcorn', 'leisurely', 'programs'], ['ball', 'ride', 'walk', 'make', 'jog', 'dance', 'bike'], ['activities', 'event', 'includes', 'series', 'stylings', "nature's", 'hosts', 'raise', 'allows', 'concerts', 'musical', 'also'], ['organizing', 'projects', 'taking', 'drive', 'sell', 'fundraising', 'trick', 'include', 'collecting', 'help', 'decorate', 'treat', 'performing', 'creating', 'drives', "unicef's", 'care', 'beautification', 'soup', 'ministries', 'tickets', 'raise'], ['program', 'potluck', 'events', 'show', 'one', 'hosts', 'reception', 'concert', 'included', 'event', 'free', 'multi', 'sculpture', 'various', 'tourism', 'center', 'walk', 'run', '473', 'purposes', 'rodeo', 'pride'], ['activities', 'canoeing', 'tubing', 'kayaking', 'pond', 'include', 'playgrounds', 'geocaching', 'sightseeing', 'watching', 'boating', 'walking', 'diabetes', 'meetings', 'studying', 'services', 'sunfish', 'swimming', 'photography', 'painting', 'marathons', 'walk', 'sail', 'jet', 'also', 'events', 'putting'], ['rumblemelee', 'frat', 'sportsnacue', 'play', 'pokemon', 'sports', 'puzzlepokers', 'billiardspalcue', 'pong', 'mezase', 'games', 'party'], [], ['hoody', 'wanna', 'song', 'make', 'comfort'], ['takes', '5k', 'holds', 'england', '–', 'place', 'stop', "kid's", 'fundraiser', 'free', "baldrick's", 'also', "mother's", 'attend', 'held', 'films', 'run', 'annual', 'chocolate', 'hall', 'get'], ["lizzy's", 'tourism', 'golfing', 'provides', 'store', 'include', 'angling', 'place', 'round', 'industries', 'tourists', 'site', 'shipbuilding', '2019', 'also', 'specializing', 'port', 'experience'], ['pack', 'missions', 'redeemed', 'packs', 'renegade', 'outfit', 'pass', 'dlc', 'bonus', '2013', 'costume', 'downloadable', 'unlocks', 'gives', "assassin's", 'furthermore', 'given']]
TOP TOKENS [['fungi', 'fungus', 'part', 'cls'], ['fungi', 'cls', 'bacteria', 'heterotrophs', 'flora', '–', 'matter'], ['fungi', 'bacteria', 'microscopic', 'fungus'], ['fungi', 'fungus', 'fungal', "environment's"], ['fungi'], ['fungi', 'half-fungus', 'noun', 'fungus”'], ['fungi', 'fungal'], ['fungi', 'bacteria', 'cls'], ['fungi', 'bacteria', 'cls', 'fungal', 'plant'], ['fungi', 'bacteria'], ['fungi'], ['fungi', 'bacteria', 'microorganisms', 'fungus', 'matter', 'fungal'], ['fungi', 'fungus', 'bacteria', 'microorganisms', 'spores'], ['fungi', 'fungal', 'cls', 'mycologists', 'artworks', 'art', 'mycophobes', 'mycophiles', 'text', 'mycologist'], ['fungi', 'bacteria', 'spores', 'organisms', 'abundant', 'soils', 'microorganisms', 'organism', 'actinomycetes', 'symbiotic', 'plants'], ['fungi', 'macroorganism', 'basidiomycetes', 'fungal', 'ascomycetes', 'saprobic', 'taxonomic', 'commensals', 'spores'], ['fungi', 'fungus', 'fungal', 'bacteriomes', 'oral', 'mycobiomes', 'nonfungal', 'pathogens', 'mycobiome', 'pathogen', 'microbiome'], ['fungi', 'fungus', 'commission', 'mycological', 'nutrient', 'cls', 'plant', 'carbon', 'mushroom', 'mycelium', 'plants', 'taxon', 'various', 'species', 'mutualistic', 'cycle', 'decomposition', 'zygomycete'], ['fungi', 'fungivores', 'fungivory', 'bacteria', 'leaves', 'phylomicus', 'lichens', 'diprotodont'], ['fungi', 'records', 'mastigomycetes', 'fungal', 'fungus', 'mostly', 'microscopic', 'bacterioplankton', 'ascomycetes', 'basidiomycetes', 'play', 'heterotrophic', 'hyphomycetes', 'phytoplankton', 'mm', 'ascomycete', 'oomycetes', 'ascomycetous', 'yeasts', 'date', 'chytridiomycetes', 'cells', 'availability']]
TOP TOKENS [['codex', 'decisions', 'result'], ['codex', 'decisions', 'result'], ['codex', 'codex(redirected'], ['codex', 'resources', 'architecture', 'unlike'], ['codex', 'dictionary', 'printing', 'look', 'martial', 'century', 'record', 'unlike', 'centuries'], ['codex', 'like', 'said', 'looks', 'internet', 'humans', 'extends', 'prose', 'programs', 'computers'], ['codex', 'figures', 'deaths', 'country'], ['codex', 'bodies'], ['codex', 'specifications', 'came', 'today', 'produced'], ['codex'], ['codex', '40,000', 'disambiguation', 'horse', 'law', '2005', 'scroll', 'artificial', 'novel'], ["codex's", 'codex', 'euthanized', 'conditions', 'starts', 'trainer', 'lukas', 'feet', 'weiner'], ['codex', 'however', 'book', 'scholars', 'could'], ["codex'is", 'codex', 'codexes', 'edition', 'datasheets', 'game', 'environment', 'cls', 'new', 'instead', 'solely'], ['codex', 'management', 'camera', '2010', 'systems', 'media', '2014', 'cls', '2019', 'used', 'performance'], ['codex', 'press', 'materials', 'contents', 'world', 'bookbinding', 'centuries', 'western'], ["codex's", 'codex', 'blog', 'neovim', 'text', 'case', 'course'], ['codex', 'armageddon', 'others', 'order', 'two', 'bearers', 'encrusted', 'going', 'even', 'fair', 'entities', 'romantically'], ['codex', 'known', 'codexians', 'writers', '2004', 'award', 'cls'], ['codex', "codex's", 'uses', 'sometimes', 'microsoft', 'behavior', 'issues']]

Processing features:  18%|█▊        | 18/98 [08:28<37:38, 28.23s/it]

getting sample prompt forgetting sample prompt for 23617
 23616
getting sample prompt for 23618
getting sample prompt for 23619
getting sample prompt for 23620
getting sample prompt for 23621
getting sample prompt for 23622
getting sample prompt for 23623
getting sample prompt for 23624
getting sample prompt for 23625
getting sample prompt for 23626
getting sample prompt for 23627
TOP TOKENS [['mcdaniel', "there's", 'humanity', 'vaudeville', 'mcduffie', 'wind', '2006', '2', 'role', 'distinction', 'infuse'], ['branson', 'taubman', 'mccauley'], ['people', 'person', 'lectern', 'someone'], ['fame', 'mcdaniel', 'people', 'walk', 'mcdaniel’s', 'film’s', 'entertainers', 'wind', '1952', 'father’s', 'sadly', 'minstrel', 'radio', 'many', 'actors', 'eventually', 'played', 'gigs'], ["people's", 'thiels', 'see', 'name'], ['lectern', 'speaker’s', 'eye-contact', 'audience', 'lecterns', 'falcon', 'people', 'place', 'read'], ['personal', 'vital', 'new'], ['phonetic', 'pronouncing', 'pronounce', 'snuggles', 'snuggle', 'cuddler', 'snuggly'], ['person', 'people', 'maltese', 'cls', 'nicknames', 'personal', 'individual', 'surnames', 'surname', 'register', 'one'], ['lectern', 'members', 'desks', 'latter', 'portable', 'pulpit'], ['players', 'following'], ['st', 'fame', 'actors', 'people', 'births', 'walk', 'male', 'links', 'emmy', 'football', 'external', 'award', 'university', 'louis', 'references', 'american'], ['players', 'active'], ['following', 'season', 'players'], [], ['references', 'warsaw'], ['players', 'following'], ['references'], ['following', 'players'], []]
TOP TOKENS [['building', 'sealants', 'even', 'stays', 'air', 'almost', 'sealant', '”', '’', 'fall', 'weak'], ['sealants', 'sealant', 'teeth', 'toothaches', 'absolutely', 'benefit', 'normally', 'impossible'], ['sealant', 'acts'], ['erupted', 'sealant', 'sealants', 'much', 'reach', 'powerful', 'get'], ['sealants'], ['harden', 'reach', 'sealants', 'sealant', 'cannot', 'set'], ['sealant', 'sealants', 'decay'], ['sealants', 'sealant', 'effective', 'supply', 'determined', 'lost', 'covered', 'fingernails'], ['sealants', 'needed', 'sealant', 'mouth', 'you’d', 'we’ll'], ['sealant', 'sealants', 'prevent', 'occurring', 'little', 'teeth', 'today', 'wait'], ['environments', 'sealant', 'well', 'sealants', 'based', 'transmission', 'temporary', 'silicone', 'polyurethane'], [], [], ['elongation', 'required', 'sealants', 'sealant'], ['sealant'], ['forced', 'ideal', 'coolant', 'insulator', 'coolants', 'either', 'soluble', 'chemically', 'convective', 'low', 'synthetic', 'gases', 'refrigerants', 'therefore'], [], [], [], []]
TOP TOKENS [['hummus', 'today'], ['hummus', 'dips'], ['litmus', 'also', '’', 'might', 'nonacidic', 'century', 'cls', 'refers'], ['hummus', '‘'], ['hummus', 'potassium', 'time', '‘'], ['hummuses', 'hummus', 'chocolate-flavored', 'countries'], ['hummus', 'various'], ['hummus', 'instance', 'savoring'], ['hummus', 'hummus’', '7,000', 'snow', 'index', 'century', 'complementing', 'makes'], ['hummus'], ['remus', 'war', 'remüs', 'world', 'rome', 'south'], ['litmus', 'medjugorje'], ['remus', 'woyrsch'], ['cadmus', "cadmus'genetics", 'superman'], ['cadmus', 'river', '1844-1902', 'comics', 'europa', 'states', 'scythes', 'confederate', 'jersey', 'businessman', 'mount'], ['asmus', 'ferdinandovich', 'british', 'ehrenreich', 'book', 'friis'], ['rasmus', 'astrid', 'klump'], ['nicodemus', 'nikodim', 'nicodemo', 'archbishop', 'rusnak', 'c', '–', 'american'], ['cadmus', "cadmus's", 'furthermore', 'betrays', 'flash', 'notably', 'season', 'one', 'earth', 'u', 'acquired', 'batman'], ['cadmus', 'reading']]
TOP TOKENS [['“', 'horror', 'word', 'fiction', 'chilling', '”'], ['horror', 'conclusion', 'horrors', 'thrillers', 'name'], ['horror', 'wikipedia', 'shelley', 'themes', 'films'], ['horror', 'wikipedia', 'shelley', 'themes', 'films'], ['horror', 'century', 'cls', 'essence'], ['horror', 'movies', 'films', 'film', 'best'], ['horror', 'shelley'], ['horror', 'cls', 'movies', 'among', 'eventually', 'scream', 'devil'], ['“', 'horror', 'word', 'cls', 'suspense', 'terror'], ['horror'], ['films', 'horror', '2002', 'ep'], ['horror', "movie's", 'gave', 'creepy', 'marisa', 'movie'], ['horror', 'video', 'games', '2010s'], ['horror'], ['horror', 'gameplay', 'cls', 'game'], ['horror'], ['horror', '2005', 'contrast', 'considered'], ['horror', 'video', 'games'], ['horror'], ['horror']]
TOP TOKENS [['tarzan', 'years', '5', 'abate', 'c', 'germany'], ['tarzan', 'greystoke', 'beasts', 'men', 'son', 'j', 'jacket', 'akut', 'genre', 'ape'], ['tarzan', "tarzan's", '2012', 'chief'], ['tarzan', "tarzan's", 'group', 'summary', 'jack', 'wikipedia', 'bereft', 'band', 'son', 'island', 'jane'], ['archie', 'archibald', 'archie:||diminutive'], ['archie', 'engine', '—', 'saturday', '1', 'called', '2000', 'rfc1635', 'internet', '4236', 'june', 'forecasts', 'emtage'], ['tarzan', 'civilization', 'simply', 'loves', 'father', 'along'], ['tarzan', 'subjects', '’', 'race', 'wide', '5'], ['tarzan', 'tarzans', '’', 'educated'], ['tarzan', 'tarzana', '1928', 'children', 'australia', 'declined', '30', 'inc', 'farki', '–', 'africa', 'intents', 'world'], ['tarzan', 'oh', "disney's"], ['tarzan', '1990'], ['tarzan', 'taylor', 'home', 'cls', "said,'uh", "uncle's", 'clayton', 'sam', 'donald', "story?'so", 'ingram', 'detective', 'way', 'fulvio', 'guinee'], ['tarzan', "tarzan's", "burroughs'tarzan", 'ralph', '8', 'capture', 'n', 'terrible', 'pal', 'vs', 'e'], ['tarzan'], ['tarzan', 'eurocom', 'boy', 'vast', '5.4', 'based', 'game', 'poachers', 'handhelds', 'arrows'], ['tarzan', 'german', 'name', 'gentlemen', 'europe', 'including', 'issue', 'kane', '2016', 'pablo', 'beckoning', "comics'illustrator"], ['tarzan', "tarzan's", 'erbzine.com'], ['tarzan', 'sun', 'la', 'european', 'mighty', 'cls', 'achmet'], ['tarzan', "tarzan's", 'cult', 'germans', 'yet', "cathne's", 'however', 'first', 'belthar', 'thenar']]
TOP TOKENS [['altostratus...more', 'altocumulus', 'altostratus', 'cirrocumulus', 'cirrocumulus...more'], ['altostratus...more', 'altocumulus', 'altostratus', 'cirrocumulus', 'cirrocumulus...more'], ['altostratus', 'cirrocumulus'], ['altostratus', 'altocumulus'], ['altocumulus', 'altostratus', 'alto', 'cirrostratus', 'cirrocumulus'], ['altostratus', 'altocumulus', 'nimbostratus'], ['altostratus', 'altocumulus', 'cirrocumulus'], ['altocumulus', 'altostratus'], ['altostratus', 'altocumulus'], ['altostratus', 'altocumulus', 'cirrocumulus', 'nimbostratus'], ['altostratus'], ['altostratus', 'altocumulus'], ['altostratus', 'altocumulus', 'altostratomutatus', 'altocumulogenitus'], ['altostratus', 'altocumulus', 'cirrostratus'], ['altostratus', 'altocumulus', 'waves', 'opaque', 'cirrocumulus', 'shading', 'usually', 'areas'], ['altocumulus', 'nimbostratus'], ['altocumulus', 'cirrocumulus'], ['altocumulus'], ['altocumulus', 'mid-altitude', 'meteorology'], ['altocumulus', 'altostratus', 'alto', 'cirrocumulus', 'cirrostratus', 'prefix']]
TOP TOKENS [['provisioning', 'provisioned', 'provider', 'provisionto', 'final', 'self-provisioning', 'telecommunications', 'provision(redirected', 'network-related', 'medical'], ['lodgings', 'ˈhɑɹbɪndʒəɹ', 'ˈhɑːbɪndʒə', 'harbingers', 'preceded', 'plural', 'foreshadows', 'heriberga', '“lodging', 'us', 'enpr', 'inn”', '“army”', 'hébergeur'], ['reckoned', 'reckon', 'reckoningplay', 'sentence', 'narrate', 'ˈre-kə-niŋ', 'building', 'simple', 'something', 'recenian', 'please', 'ˈrek-niŋ'], ['possets', 'coagulate', 'posset', 'pamper', 'plural', 'third-person', 'turn', 'curdle'], ['entourage', 'retinue', 'entouragefrench', 'attendants', 'tour', 'see', 'circuit'], ['əˈzin', 'limousineˈlɪm', 'unk', 'eðalvagnicelandic', 'chauffeur', 'limousin', 'chauffeurs', 'cls', 'limousine', 'coachbuilder', 'weddings', "passengers'compartment", 'glæsivagn', 'even', 'prm', 'occasions', 'driver', 'meanings', "driver's", 'conveniences'], ['rendezvous', 'hotel', 'meaning', 'costs', '–', 'apprentices', 'seo', 'one'], ['reckonings', 'reckoning'], ['spokeo', 'pages', 'manufacturers', 'subsequent', 'louder', 'likely', 'complement', 'listings', 'information', 'address'], ['reckon', 'hence', 'erroneously', 'upon', 'conclude', 'cls', 'followed', 'also', 'word'], ['seattle'], ['springsteen', '1977', "c'etait", 'vous', 'duke', 'film', 'tv', 'television', 'rendezvous', "heart'n'soul", 'denny', 'cano'], ['entourage'], ['passenger', 'buick', 'sitcom', 'encore', 'westjet', 'airline', 'real', 'gm', 'television', 'company', "amtrak's", 'ship', 'kid', 'transportation', 'microcontroller', 'reality', 'z8'], [], ['hinton', 'order', 'italian', 'religious', 'england', 'financial', 'municipalities', 'town', 'f.c', 'charterhouse', 'disambiguation', 'mendip', 'coventry', 'charterhouse-on-mendip', 'uk-based', 'locations', 'eashing'], ['television', 'reckoning', 'killing', 'live', 'kingdoms', 'album', 'disambiguation', 'sg-1', 'justified'], [], [], ['people', 'organisations', 'watkins', 'instruments', 'music', 'builder', 'electric', 'u.s']]
TOP TOKENS [['transition', 'transitions', 'transitional', 'day', 'dynamism', 'another', 'handout', 'components', 'used'], ['transitions', 'incorporating', 'transitional', 'effective', 'transition', 'magoosh', 'transitionstransitions', 'teaching', 'common', 'definedwriters', 'writing', 'within', 'dictionary'], ['transitional', 'transition', 'transitions', 'ideas', 'another', 'coordinating', 'use', 'specific', 'using', 'good'], ['transition', 'transitional', 'transitions', 'phrases', 'argument', '2', 'writing', 'use', 'descriptive', 'used'], ['transitions', 'transitional', 'transition', 'incorporating', 'meaningful', 'within', 'use', 'recommendations', 'create', 'specific', 'develops'], ['transitions', 'transition', 'transitional', 'ab/bc”out', 'essay', 'samples', 'use', 'include', 'write', 'good', 'put', 'writing', 'select'], ['transitions', 'transition', 'top', 'appropriately', 'use', 'transitional', 'words', 'overuse', '20', 'two', 'sentences', '70', 'used'], ['transitioning', 'transitions', 'transition', 'using', 'transitional', 'use', 'managing', 'words', 'struggle', 'common', 'practice', 'show', 'sentences', 'used', 'filling', 'refugee', 'desks'], ['transition', '“transition”—as', '“transition”'], ['transitions', 'transitional', 'transition', 'ins', 'using', 'writing', 'professor', 'usage', 'match', 'turn'], ['transitions', 'transition'], ['transition', 'transitional', 'transitions', 'laminar', 'turbulent', 'phase', 'nucleotide', 'another', 'atom'], ['transitions', 'transitioning', 'transition', '2013', 'gradual', 'management', '2016', 'explicit'], ['transition', 'transitions', 'straight', 'middle', 'another', 'without'], ['transition', '2013', 'transitions', 'elect'], ['transition', 'specific', 'gamma-re', 'employed', 'model', 'modeling', 'simulation', 'models'], ['transitioning', 'transition', 'help', 'bid–offer', 'transitioned', 'seeking', 'two', 'perform', 'companies'], ['state-transition', 'transition', 'later', 'product'], ['transition', 'transitions'], ['transition', '–']]
TOP TOKENS [['simultaneously', 'maven', 'maven’s', 'packed', 'help', '“maven”', 'wasted', 'existing'], ['ulcers', 'also', 'makoi', 'makoy', 'problems', '•', 'cheeks', 'dieresis', 'helping', 'treated', 'referred', 'many'], ['maven', 'module', 'practices', 'projects', 'almost', 'also', 'following'], ['makovsky', 'petersburg', 'size', '’', 'clearly', 'happy', '1915', 'born', 'spend', 'tells'], ['maven', 'https://maven.apache.org', 'usr/share/maven', 'os', 'package'], ['mahone', 'portion', 'accepted', 'lost', 'years', 'founded', 'norfolk', 'graduated', 'social', 'monroe'], ['maven', 'languages', 'part'], ['maven', 'local', 'automatically', 'template', 'syntax', 'object', 'fully', 'poms', 'default'], ['velázquez', 'maffei', 'liss', 'brief', 'maffei’s', 'key', 'colour', 'assumed', 'vicenza', 'padua', 'artificiality', 'foscarini', 'dell’accademia'], ['velázquez', 'maffei', 'liss', 'brief', 'maffei’s', 'key', 'colour', 'assumed', 'vicenza', 'padua', 'artificiality', 'foscarini', 'dell’accademia'], ['macs'], ['khl', 'makarov', 'hc'], ['bon', 'variant', 'israeli', 'formerly', 'mako', 'keshet', 'device', 'common', 'indigenous', 'agustawestland', 'blanco'], ['josé'], ['three'], [], ['fifth-round', 'two-year', 'makarov', 'khl', 'yulaev', '2018–19', 'two', 'neftekhimik', 'august', 'november', 'moscow', 'players', 'ahl', 'petersburg', '2011', 'hc'], [], ["l'autonomie", 'maksutov', 'british', 'member', 'kardzhali', 'mahk', 'disambiguation'], ['win', 'pyeongchang', 'draft', 'makar', "makar's", 'seventh', 'finished', "men's", "father's", 'reportedly', 'selected', 'gold', 'three', 'rochester', 'eight']]
TOP TOKENS [['holmes', 'doyle', 'chivalry', 'far', 'imagination', 'conan', 'enchanting', 'magic'], ['holmes', "holmes's", "doyle's", 'many'], ['holmes', 'friendship', 'unmoved', 'life', '—', 'silence', 'summer', 'work', 'moment', 'note', 'one'], ['holmes', 'wendell', 'reading', 'oliver', 'case', 'would', 'limits', 'states', 'panic', 'way', '1919', 'like'], ['holmes'], ['holmes'], ['holmes', 'centuries'], ['holmes', 'doyle', 'far', 'conan', 'imagination', 'component', 'magic', 'wonder', 'improbable', 'surprise', 'vexed', 'hound', 'adventure', 'world'], ['holmes', 'dixwell', 'government', 'yet', '1861', 'europe', '1866', 'march', 'thayer', '1864', 'onward', 'boston'], ['holmes', 'employer', 'indeed', 'predilections', 'laws', 'propagandists', '”', 'struck', 'drool'], ['holmes', 'iowa', 'pennsylvania', 'crater', '17p/holmes', 'county', 'washington', 'territory', 'mackinac', '1863–1928', 'kentucky', 'northern'], ['holmes', '1957', 'america', 'reading'], ['holmes'], ['holmes', 'delaware', '2007', 'hardcover', 'harris', 'books', 'paperback', '2019', '21st-century', '2020'], ['holmes', 'flagg'], ['holmes', 'operations'], ['holmes', "holmes's", 'murdock', 'works'], ['holmes'], ['holmes', 'roxbury', '1961', 'neighborhood'], ['holmes']]
TOP TOKENS [['affirmative', 'action', 'cls'], ['affirmative', 'action', 'corner'], ['affirmative', 'action'], ['affirmative', 'action'], ['affirmative', 'action', 'cls', 'exeter', 'business'], ['affirmative', "of'affirmative", 'action', 'cls'], ['affirmative', 'action', 'bar', 'say'], ['affirmative', 'action'], ['affirmative', 'affirmativeaction', 'action', 'definition', '85', 'end'], ['affirmative', 'action', 'since', 'color'], ['affirmative', 'states', 'action', 'cls', 'nature', 'opponents'], ['affirmative', 'action', 'states', '2003', 'consists', '1978', 'barred', 'race'], ['affirmative', 'hypothesis', 'action'], ['affirmative', 'however', 'action', 'term', 'executive', 'argue', '”', 'take'], ['affirmative', 'action', 'book'], ['affirmative', 'action', 'resolution'], ['affirmative', 'action', 'supported', 'support', 'thought', 'offer'], ['affirmative', 'cls', 'action', 'executive', 'refers', 'opportunities', 'history'], ['affirmative', 'action', 'operates', 'beneficiary'], ['affirmative', 'action', 'americans', 'also', 'felt', 'see', 'toward', 'history']]
TOP TOKENS [['accord'], ['accord', 'classification', 'honda'], ['accord', 'accords', 'noun'], ['accord', 'word', 'accordare', 'verb', 'geneva', 'pact', 'cls', 'lawsuit', 'accordəˈkɔrd', 'english', 'concord', "webster's", 'suit'], ['word', 'accord', 'act', 'concede', 'words', 'definitions'], ['word', 'accord', 'act', 'concede', 'words', 'definitions'], ['accord', 'strategic', 'agreement', 'committing', 'visit'], ["accord's", 'accord', 'honda', 'stereo', 'tachometer', 'sedan', '000', 'fm', 'radio', 'also'], ['accord', 'accords', "world's", 'america', 'coupe', 'wagon', 'sedan', 'generation'], ['accord', "accord's", 'honda', 'trip', 'drive', 'tachometer'], ['accord'], ['accord', 'technical'], ['accord', 'motorsport', 'links'], ['accord', 'households', '10', 'geography', 'joachim', 'listed', 'next', 'cls'], [], ['accord', '1989', 'sedan'], ['accord', 'accords'], ['accord', 'parties', 'house', 'political', 'establishment', 'party', 'election', 'references'], ['accord', 'accords', 'american', 'sedan', 'roof', 'european', 'equaliser', 'north', 'year', 'antenna'], ['accord', 'see', 'polish', 'disque']]

Processing features:  19%|█▉        | 19/98 [08:54<36:22, 27.62s/it]

getting sample prompt forgetting sample prompt for 23629
 23628
getting sample prompt for 23630
getting sample prompt for 23631
getting sample prompt for 23632
getting sample prompt for 23633
getting sample prompt for 23634
getting sample prompt for 23635
getting sample prompt for 23636
getting sample prompt for 23637
getting sample prompt for 23638
getting sample prompt for 23639
TOP TOKENS [[], [], [], [], [], [], [], [], ['multicompartment'], [], [], [], [], [], ['all-american', "men's"], [], [], [], [], []]
TOP TOKENS [['none', 'respect', 'recognise', 'less', 'shall', 'staunch'], ['none', 'respect', 'recognise', 'less', 'shall', 'staunch'], ["m'kay", 'specifically', 'immediately', 'neither', 'moderately', 'manner', 'quite', 'logically', 'even', 'however', 'eventually'], ['content', 'remaining'], ['another', 'churchill', 'librarians', 'mark', 'daft', 'regularly', 'features', "book's"], ['frequent', 'region', 'followed', 'contain', 'becoming', 'information', 'california', 'numerous'], ['anew', 'demonstrated'], ['usa', '1080', '–', '25667144', 'paula', 'directory', '77', '551', '10', '1973'], ['ever', 'quickly'], ['base'], ["boss'rear", 'content', 'de', "comic's", 'ample', 'aniversario', '–', 'course', 'eavesdroppers', 'universidad', 'miguel', 'cuenca', 'la', 'soto', 'advantage', 'ediciones', 'side', '2008'], ['even', "mortadelo's", 'already', "filemon's", '2008', 'de', 'precaution', 'la', 'universidad', '–'], ['ability', 'vital', 'even', 'supplied', 'important', 'refusal', 'small', 'especially', 'anywhere', 'dynamic'], ['common', 'instructions', 'agree', 'effort', 'names', 'following', 'lack', 'far', 'believes', 'three', 'builds', 'handyman', 'administers', 'tries', 'mismeasuring', 'even', 'cause', 'short', 'strip', "bathtub's", 'snags', 'makes'], ["team's", 'club', 'based', 'culture', 'copies', 'account', 'disciplined', 'f', 'satirical', 'nod', 'c', 'twitter', 'acknowledged', 'official', 'one', 'ever', 'coffee', 'nary'], ['always', 'famous', 'iconic', "blu's", "monica's", 'secretary', "fog's", 'carrying', 'mostly', 'character', 'especially', 'assistant', 'main', 'comes', 'brazil', "manfred's", 'appears', 'gang'], ['local', 'central', "hearst's", 'town', 'snowmobiling', 'algoma', 'hunting'], ['freundeskreis', 'neuseeland', 'p', 'feb', 'languishing', 'w', 'york', '3', 'anzeiger'], ['baudelaire', 'mr', 'f', 'forced', 'unwelcoming', 'quagmire', 'baudelaires', 'seem', 'goes', 'respectively', 'cave'], []]
TOP TOKENS [['1648', 'james', 'parliamentary', 'george', 'normanby', 'lord', 'royalists', 'iii', 'july', 'march', 'royal'], ['1650', '1653', '1648', '1651', '1652'], ['1648', '1613', '1615'], ['1650', '1645', '1653', '1642', '1648', '1660s', '1660', '1647', '1640', '1639', '1644', '1691', '1638', '1676', '1641', '1674', '1613', '1643', '1610', '1649', '1635', '1637', '1658', '1670', '1606', '–', 'c', '1663'], ['1643', '1645', '1644'], ['1643', '1645', '1644'], ['1643', '1645', '1644'], ['1645', '1644', '1643', '1653', '1641', '1640', '1642', 'parliamentary', 'february', "charles'loss", 'civil'], ['1645', '1644', '1643', '1653', '1641', '1640', '1642', 'parliamentary', 'february', "charles'loss", 'civil'], ['1650s', '1661', '1668', '1660s', '1660', '1660-1663', '1664', '1663–1665', '1669', '1670s', '1664–1667', "king's", '1666', 'may', 'c'], ['1648', '1640s', 'year'], ['1645', '1641', '1640s', "lirenda's", '1682'], ['1641', '1640s', '1645', 'year'], ['1640s', 'year', '1643', '17th'], ['1641', 'october', "argyll's"], ['1640s', '1644'], ['1640s', '1648', 'early', 'year', 'florin', 'baptist'], ['1613', '1640s', '1619', 'regent'], ['1644', '1640s'], ['1678', 'late-baroque', '1640s', '1717', '17th', 'baroque', '1697', 'veneto', 'sir', 'gherardi', '1643']]
TOP TOKENS [["grouse'susceptibility", 'grouse', "grouse's"], ['grouse', 'grouses', 'galliformes'], ['grouse', 'grouses', 'galliformes'], ['grouse', 'sport', 'survive'], ['grouse', "grouse's"], ['grouse', 'cls', 'alike'], ['grouse', 'cls', 'sandgrouse', '15', 'called', '22', 'spruce', 'male', 'occurs'], ['grouse', 'cls', 'range', 'family', 'ptarmigan'], ['grouse', 'cls', 'range', 'family', 'ptarmigan'], ['grouse', 'cls', 'ground'], ['grouse', 'grouses', 'galliformes', 'county', 'california'], ['grouse'], ['grouse'], ['perouse', 'pérouse'], ['grouse', 'sage-grouse', 'sage', 'horses'], ['grouse'], ['grouse', 'south', 'southwest'], ['grouse', 'many', 'others', 'phasianidae', 'cls', 'galliformes'], ['grouse', 'california', 'district', 'uss'], ['grouse', 'hazel']]
TOP TOKENS [['teen', 'teens', 'teenagers', 'worsen', 'depression'], ['teenager', 'teens', 'adolescents', 'teen', 'teenagers', 'helping', 'unfortunately', 'juvenile', 'avoidable', 'treatments', 'result', 'sure', 'help'], ['teens', 'teenagers', 'teen', 'teenage', 'adolescents', 'aged', 'million', 'less', 'furthermore'], ['teens', 'teenagers', 'teenage', 'teen', 'teenager'], ['teens', 'teenagers', 'teen', 'teenager', 'teenage', 'filled', 'serious', 'cases', 'many', 'unfortunately', 'however'], ['teens', "teen's", 'teen', 'designed'], ['teenagers', 'teens', 'teenage'], ['teenagers', 'teens', 'teenage'], ['teenagers', 'teenager', 'teen', 'teenage', 'many', 'us', 'especially', 'declare', 'actions'], ['teen', 'teens', 'teenager', 'teenagers', 'behaviour', 'peers', 'could'], ['teenager', 'teenagers', 'teen', 'teenage', 'teens', 'téén'], ['teen', 'teenagers', 'teenager', 'teenage', 'adolescent'], ['teen', '2013', 'eps', 'carpark', 'links', 'external', 'records', '2015', 'artists', 'musical', 'kristina', 'teeny'], ['teens', 'teenagers', 'teen', 'teenage', 'actual', 'seventeen', 'teenmag'], ['adolescent', 'teenage', 'teen', 'teenager', "among'teen", 'adolescence', 'adolescente', 'preteens', 'usage', 'adjective'], ['teenagers'], ['teenage', 'teen'], ['adolescents', 'teens', 'adolescence', 'teen', 'adolescent', 'fulfilment'], ['teenagers', 'teenage', 'adolescent', 'pregnancies', 'pregnant', 'adolescence', 'teens', 'many', '16', '15', 'pregnancy', 'care', '65', '19'], ['teens', 'teenagers', 'adolescents', 'teenage', 'teen', 'pregnant', 'adolescent', '15', '2008', 'pregnancies', 'younger', 'pregnancy', '700', 'tend']]
TOP TOKENS [['happen', 'issues', 'phenomenon', 'leaves', 'issue', 'kind'], ['problem', 'clogs', 'occurs'], [], ['occurs', 'issue', 'appear', 'usually', 'problem', 'reduce', 'issues', 'like', 'generated', 'resulting', 'presence', 'discoloration', 'think'], ['happens', 'make', 'happen', 'smoothness', 'happening', 'example'], ['things', 'also', 'cause'], ['happens', 'manner', 'buildup', 'freezes'], ['problem', 'result', 'like', 'otherwise', 'results', 'presence', 'caused', 'prevent', 'effect', 'warping'], ['thing', 'happen', 'happens', 'notice', 'prevent', 'result', 'coming', 'brazing', 'thus'], ['causing', 'oxides', '116', 'called', '‘', '11', 'solderbridging'], ['causes', 'occur', 'create', 'occurs', 'loss', 'due', 'cannot', 'introduce', 'particularly', 'since', 'hence', 'blocks', 'components'], ['caused', 'process', 'depletion', 'turns', 'globules', 'nucleate'], ['causing', 'defect', 'impression', 'leaves', 'drain-like'], ['throw', 'causes', 'rearrange', 'near', 'develop', 'look', 'occurs', 'g', 'due', 'like', 'instead', 'tendency', 'place', 'including'], ['defect', 'caused', 'cases', 'tailing'], ['defects', 'effect', 'structure', 'caused', 'problem'], ['unwanted', 'caused', 'blooming', 'due'], ['issues', 'thickens', 'hardens', 'cause', 'issue', 'problem', 'buildup', 'becoming', 'causing', 'becomes', 'begin', 'block', 'clog', 'soot', 'congeal', 'poor', 'whilst'], ['effect', 'unwanted', 'occur', 'undercuts', 'problem', 'due'], ['occurs', 'also', 'penetrates', 'happens', 'defect', 'causes', 'gives', 'drops', 'result', 'defects', 'part', 'scabs', 'caused']]
TOP TOKENS [['maths', 'sunk/ships'], ['measuremnets'], ['2380', 'soc', 'meteor', 'thuburn'], ['jarrett', 'adversities', 'insecurity', 'also', 'education', 'scd'], [], ['fats', 'environmental', 'cells', 'naturally', 'dermatology'], [], ['world', '12/03/2018', 'order'], [], ['world', 'payment||this', 'individuals'], ['bluffs'], [], [], ['gabriel', 'due', 'collecta', 'elephant', 'fahraeus', 'handl', 'caffrariae', 'treasury'], ['banked', 'biometrical'], [], [], [], ['mangrum', 'nyc'], ['tectonics']]
TOP TOKENS [['descriptor'], [], [], [], ['acknowledgments'], [], ['known'], [], ['db', 'ukulele', 'string', 'top'], [], [], ['english', 'american', 'contraltos', 'discography'], ['fun', 'things', 'recoil', 'recovers', 'adds', 'dislikes', 'billed', 'brenda', 'states', 'reluctant', 'interrupts', 'characterisation', 'affirms', 'family', 'upset', 'says'], ['performance', 'kalamandalam', 'exponent'], [], [], [], [], [], ['british']]
TOP TOKENS [['fly', 'addition', 'ash'], ['fly', 'ash', 'using'], ['fly'], ['fly', 'products', 'ash', 'made', '3'], ['fly', 'blends', 'ash', 'well', 'also'], ['fly', 'ash', 'ashes'], ['fly', 'ash'], ['fly', 'https://saturnmaterials.com/what-is-fly-ash', 'ash'], ['fly', 'ash'], ['fly', 'ash'], ['fly', 'mixtures', 'ash', 'well'], ['fly', 'recently', 'ash', 'kingdom', 'unsightly', 'contents', 'india'], ['fly', 'ash', 'opc'], ['fly', 'ash', 'lime', 'construction', 'new', 'large'], ['fly', 'ash', 'necessary'], ['fly', "name'fly", 'ash', '35', 'include', '0', 'due', 'mpa'], ['fly', 'therefore', 'ash', 'addition', 'composites', 'presence', 'uses', 'cenospheres', 'whereas'], ['fly', 'bricks', 'ash'], ['fly', 'ash'], ['fly', 'ash', 'contain', 'reclamation', '12', 'also', 'u', '4', 'pavements', 'almost', 'flue']]
TOP TOKENS [['colombia', 'colombian', 'colombians', 'budhhism', 'sep', '2'], ['colombia', '2', '11', 'slots'], ['colombia', 'colombians', "colombia's", 'colombian', 'bogota'], ['colombian', 'colombia', '435', '5'], ['colombia', 'colombians', 'colombian'], ['colombia', "colombia's", 'colombians', 'colombian'], ['colombia', 'colombians', "colombia's", 'colombian', 'century', '54', '79', 'ancestry', 'people', 'area'], ["colombia's", 'colombia', 'colombian', 'area', '2006', 'notably', 'country'], ['colombia', 'colombians', 'colombian', '1499', 'southern'], ['colombia', 'colombian'], ['colombia', 'disambiguation', 'title'], ['disambiguation', 'beauty', 'colombia', 'metro', 'republic', 'colombian'], ['colombia', 'colombian', "colombia's", 'colombians', 'bogota', 'unexplored'], ['colombia', 'colombians', 'colombian', 'rastafari', '8', 'hoyos', '1845', 'countries', 'actively', '1991'], ['colombia', 'colombian', "colombia's", 'debut', '9'], ['colombia', '1933', 'galeano', '1928', '1958', 'librettist', 'colombian'], ['colombia', "colombia's", 'colombian', 'dollars', 'billion', '2016'], ['colombia', 'colombian', 'territory', 'second', 'oceans', 'world', 'deserts', 'partner', 'islands', 'development'], ["colombia's", 'colombia', '11th', 'semifinals', 'group'], ['colombian', 'colombia', 'forces']]
TOP TOKENS [['honda', 'honda’s', 'hondajet', 'engines'], ['honda', 'decade', 'costs'], ['honda', 'hybrid', 'cls', 'mpg', 'act', 'producers'], ['honda', "1980's", 'mechanic'], ['honda', 'requirements', 'enabled', 'order', 'cost', 'products'], ['honda', 'motorcycles', 'consumers', 'world'], ["honda's", 'honda', 'robotics', '1963'], ['honda', '“', 'civic', 'trucks', 'time', 'manufacturers', '’', 'mpg', 'insight', 'drummer'], ['honda', "honda's", 'competitors', 'eu6500isa', 'series'], ['honda', 'sales', 'research', 'business', 'case', 'scooter'], ['honda', 'surname'], ['honda', '2001', '2022', "women's", 'football'], ['honda', '2015', 'births', 'kobe'], ['honda', 'tournament', '2022', 'league', 'championship', '14', 'block', 'edition', 'sportspeople'], ['honda', "honda's", 'match'], ['honda', '2016', '2022', 'wilson'], ['japanese', 'association', 'playing', 'season'], ['honda', '1995', 'players', 'footballers', 'championship', "men's"], ['88th', "men's", 'hollyhock', 'japanese', 'playing'], ['honda', 'gainax', '8', 'ep', 'director', 'animator', '2004', '19', 'games']]
TOP TOKENS [['monism'], ['monism', 'monisms', 'cls', 'multivarious'], ['monism', 'monistic', 'hegel', 'reserved', 'substance'], ['monism', 'monistic', 'hegel', 'substance', 'opposites', '6th'], ['monism', 'monist', 'impersonal', 'expressed'], ['monism', 'monistic', 'cls', 'neoplatonism', 'religious', 'ontologically', 'advaita'], ['monism', 'monists', 'one', 'neo', 'heraclitus', 'well', 'anaximenes', 'worldview', 'socratic'], ['monism', 'heterogeneity'], ['monism', 'reflexive-monist', 'monistic'], ['monism', 'monistic', 'consit'], ['monism'], ['mon'], ['mone', 'mones', '1796–1871', 'moné', 'baroness', 'lollard'], ['moni', 'monnett', 'kelimutu'], ['monism', "manilal's", 'puranas', 'cls', 'former'], ['monism', 'monists', 'monist', 'form', 'dictates', 'civil'], ['monist', 'ernst', 'binet', 'haeckel', 'hegeler', 'gadamer', 'gottlob', '1918–19', 'cassirer', 'originally', '1992–2016', 'lombroso', 'john', 'academic', 'mach', 'peirce', 'professionalize', 'prominent'], ['mony', 'moni', '1966'], ['mon', 'aos', 'almost'], ['mon', 'national', 'occasion']]

Processing features:  20%|██        | 20/98 [09:22<36:11, 27.83s/it]

getting sample prompt forgetting sample prompt for 23641
getting sample prompt for 23642
 23640
getting sample prompt for 23643
getting sample prompt for 23644
getting sample prompt for 23645
getting sample prompt for 23646
getting sample prompt for 23647
getting sample prompt for 23648
getting sample prompt for 23649
getting sample prompt for 23650
getting sample prompt for 23651
TOP TOKENS [['cathari', 'katharoí', 'cathar′sis', 'catharism', 'catharī', 'katharezein', 'cathar', 'katharoi', 'cathars', 'cathar′tin', 'catharist', 'greek', 'hoi'], ['cathars', 'katharoi', 'catharos', 'cathari', 'cathar', 'catharsis', 'katharsis', 'catharism', 'word', 'stark', 'title'], ['cathars', 'katharoi', 'catharos', 'cathari', 'cathar', 'catharsis', 'katharsis', 'catharism', 'word', 'stark', 'title'], ['lahar', 'lahars', 'meters', 'ad', 'clay', 'centimeters'], ['lahars', 'lahar', 'mi', 'volcanic', 'wide', 'feet', '460', 'word'], ['azhari', 'azhary', 'azhar', 'azharazharan', 'azharuddln', 'azhars', 'azhare', 'azhdari'], ['cathari', "cathars'beliefs", 'catharism', 'called', 'cathar', 'salamis', 'epiphanius', 'ad', 'bogomilism', 'see', 'nicaea'], ['cathars', 'katharos', 'cathari', 'cathar', 'greek', 'made', 'spelled', 'religious'], ['amharic', 'amhara', 'amharas', 'amharanize', 'amharanization', 'people', 'wolloye'], ['wchar_t', '1', 'supported', 'xpg4/4.2/5', 'msvc', 'abi', 'knowledge', 'instance', 'things', '1.52', 'dealing'], ['lahari', 'lahar'], ['ghari'], ['cathar'], ['johar', 'jawhar', 'johari', 'al-jawhari', 'johari-goldstein', 'ali', 'khir'], ['vehari'], ['azhar', 'azhari', 'al-azhari'], [], ['bhiwani', 'kohar'], ['khara', 'khar', 'disambiguation'], ['sehar', 'loharu']]
TOP TOKENS [['zeroth'], ['oauth', 'oh-auth'], ["thoth,'you", 'thoth', "gods.'thoth", "thoth's", "him,'he", 'generation'], ['oauth', 'oh-auth'], ['oauth', 'client', 'toon', 'agent', 'case', 'oauth2', 'applications', 'access', 'party'], ['oauth', 'account'], ['thoth', 'cls', 'seshat', 'goddess', 'mythology', 'anubis', 'also'], ['thoth', 'toth', '’', '—', 'tehuti', 'mus', 'communicator', 'material', 'space'], ['thoth', 'tahuti', 'also', 'seshat'], ['oauth', 'companies', 'internet', 'ietf'], ['toth', 'thoth', 'lazlo', 'fr:tóth', "na'toth", 'tóth'], ['koth', 'köth'], ['orth', 'maren', 'marisa'], ['mcraith', 'raith', 'ráith', '1960', 'prelate', 'sissy'], ['thoth'], ['donath', 'donáth'], ['0th', 'zeroth'], ['koth'], ['warth'], ['freeth', 'author', 'english', '1846–1911']]
TOP TOKENS [['ama', "ama's", 'trustworthy', 'emergency', 'catastrophes', 'article', 'governments', 'jama', 'care', 'ensure', 'addressed', 'adequate', 'covering', 'patients', 'feature', 'insurers', 'pharmacies', 'resolves', 'enact'], ['ama', 'adopts', 'editor', 'advisability', 'year', 'published', 'doubtful', 'governments', 'source', 'enlighten', 'begins', 'summarizes', 'establishes', 'provide', 'regularly', 'issues', 'states', 'established', 'appoints', 'sanitariums', 'public', 'fostering', 'strongly', 'establishing', 'regard', 'control', 'deal'], ['edit', 'help', 'like', 'improved'], ['edit', 'airstrips', 'cleaned', 'dikes', 'wild', 'lakes', 'company', 'people', 'affected', 'time', 'major', 'station', 'livelihoods', 'thousand', 'large', 'several', 'everyone', 'depended', 'water', 'called', 'weir', 'also', 'immediately', 'farm', 'area', 'mats', 'factory'], ['sufficient', 'get', 'dry', 'coverage', 'rather', 'unpacking', 'spends', 'parts', 'e'], [], ['super', 'f-r-o-g', 'friends', 'help', 'leaving', 'whose', 'dash', 'read', 'story', 'water'], ['ama', 'requires', 'conversant', 'worry', 'technology', 'several', 'business', 'quality', 'additionally', 'marketing', 'style', 'many', 'school', 'citation', 'engineering', 'among'], ['underfunded', 'thus', "scientist's", 'super', 'slumber', 'save', 'aneb', "nation's", 'dropped', 'battle', 'however', 'site', 'besieges', 'turning', 'arrives', 'retarding', 'properly', 'japan', "godzilla's", 'devastation', 'lies', 'detonates'], ['innovation', 'domestication', 'magnons', 'occupied', 'part', 'main', 'except'], ['erupts', 'intrigued', 'expansion', 'due', 'see', 'consumes', 'whose', "lizbert's", 'grumpus', 'disappearance', 'attacked', 'grumpuses', 'however', 'scattered', 'grandmother', 'interpersonal', "island's", "triffany's", 'bugsnax', 'anyone'], ['university', 'ama', 'de', 'fort', 'province', 'trade', 'academia', 'defiance', 'places', 'supercross', 'autoridad', 'safata', 'administrative', 'people', 'town', 'title', 'authority', 'metropolitana', 'incompletely', 'manageability', 'academy', 'gaiole', 'canada', 'american', 'technology', 'metropolitan', 'museum', 'association', 'assembly', 'americas', 'estonia', 'advanced', 'autobuses', 'tuscany', 'atlantic', 'motorcyclist', 'arquitectura', 'virginia', 'washington'], ['ama'], ['see', 'populated'], ['takes', 'along', 'place', 'upon', 'completed', 'humanoids', 'update', 'island', "player's", 'also', 'circumstances', 'motivations', 'part'], ['reshot', 'ma.ama', 'external', 'one', 'films', "india's"], [], ['ochobot', 'bora', 'boboiboy', 'follows', 'co', 'positive', 'zola', 'predates', 'plot', 'abdul', 'region', 'turns', 'received', 'robbers', 'camp', 'instead', 'day', 'spots', 'sequel', 'yoyo', 'next', 'eventually', 'adu', 'cls', 'aba', 'manages'], ['ama', 'higher', 'contexts', "clarity's", 'sake'], ['external', 'ama', 'references', '700th', 'links', 'history', 'commercial', 'february', 'populated', '19', 'raised', 'based', 'ever', 'january', '1239', 'geography', '6,986', '1981', 'established', 'called', 'also', '1969', 'primarily', 'built', '1904', 'jōkyū', 'much', 'along', 'death', 'restoration']]
TOP TOKENS [['die', 'dies'], ['die', 'dies'], ['die'], ['die', 'dies'], ['dies', 'die'], ['dies', 'die', 'cls'], ['die', 'die-cast'], ['die', 'die-cast'], ['die'], ['die'], ['die', 'dié', 'dies'], ['dies', 'die'], ['dies', 'die'], ['die'], ['saint-dié', 'die', 'dié'], ['die'], ['die', 'die-deterioration', 'dies'], ['die', 'dies', 'part', 'terminal', 'working'], ['die', 'dies', 'cls'], ['die', 'dies']]
TOP TOKENS [['prospect', '“prospect', 'outcomes', 'utility', 'theory'], ['prospect', 'prospectus', 'great', 'first'], ['prospect', 'perceived', 'pleasure-attracted', 'theory'], ['prospect', 'rules', 'theory', 'prospects', 'life', 'cls', 'many', 'insurance', 'feature', 'million'], ['prospect', 'theory', 'information'], ['prospect', 'theory', 'punishments', 'make'], ['prospect', 'communities', 'northern', 'slope', 'historic', 'mount', 'eastern'], ['prospect', '’', 'newsletter'], ['prospect', 'theory', 'cls'], ['prospect', 'cls', '“'], ['prospect', 'prospects', 'surrounding', 'suburb'], ['prospect', 'system', 'september', 'unincorporated'], ['prospect', 'timberlea-prospect', 'links', 'external', 'since', 'mt'], ['prospect', 'early'], ['prospect', 'trinway'], ['prospect-gaylord', 'prospect', 'mill-prospect'], ['prospect', 'december', '31'], ['prospect'], ['prospect', 'city'], ['prospect']]
TOP TOKENS [['goddess', 'goddesses', 'cls', 'regions', 'wisdom', 'cultural', 'cultures', 'noun'], ['goddess', 'goddesses', 'cls', 'preceding', 'neopaganism', 'cultures'], ['goddess', "goddess'is", 'goddesses', "spirituality'the", 'religion', 'well', "am,'and", "one's"], ['goddess', 'goddesses'], ['goddess', 'mistress', 'meet'], ['goddess', 'goddesses', 'level'], ['goddesses', 'goddess', 'priestesses', 'know', 'maiden'], ['goddess', '‘', 'culturally'], ['goddess', '‘', 'culturally'], ['goddesses', 'goddess', 'mythological', 'brockway'], ['goddess', 'neopaganism', 'pentagram', 'category:goddesses'], ['goddess', "spirituality.'goddess", 'goddessing', "goddess'it", 'goddesses', 'priestess', "goddessing'as"], ['goddess', 'links', 'band', 'metal'], ['goddess', 'anchovies', 'japanese-english'], ['goddess'], ['goddess', '2014', 'weekend', 'woman', 'morrison', 'production', 'phoenix', 'cassandra', 'peruvian', 'wolfe', 'celia', 'cherry', 'corinne'], ['goddess', 'goddesses', 'priestess', 'ordination', 'deity', '1970s'], ['goddess', 'stars', "t'aime", 'b.b', '28'], ['goddess'], ['goddess']]
TOP TOKENS [['rochester', '’', 'though', 'fireside', 'even', 'burden', 'fire', 'bertha', 'child', 'genuine', 'mistaken', 'eyes', '27', 'sets', 'mr'], ["rochester's", 'rochester', '1850', '1961', 'citizen', 'park', 'buffalo', 'river', '1812', '1857'], ['rochester', 'hospital', 'several', 'times,when', 'one', 'activities', 'site', 'gandolf', 'britain', 'old'], ['rochester', '’', 'said', 'home', 'else', 'child', 'green', 'seems', 'hoped', 'control', 'side', 'england', 'childhood'], ['rochester', 'gundulf', 'experienced', 'st', 'fort', 'around', '’'], ['rochester', 'gundulf', 'experienced', 'st', 'fort', 'around', '’'], ['rochester', "rochester's", 'area'], ['rochester', 'year', 'areas'], ["rochester's", 'rochester', 'father', 'bunches', 'maims', 'imprisonment', 'thornfield'], ['rochester', '”', 'tells', 'died', 'way', 'jane', 'right', 'secrecy', 'go', 'instead', 'love'], ['rochester', '1907', 'company', 'yaguez', '1917', '1898'], ['rochester', 'today', 'chicago', '1849', 'census'], ['rochester', 'cfb'], ['rochester'], ['rochester', 'u', '–'], ['rochester', 'downtown', 'stores', 'works', '1875', 'shoes'], ['rochester', 'rochester-upon-medway', '1974', '1835', 'st', 'civil'], ["rochester's", 'rochester', '1810s', 'years', 'person', 'ultimately'], ['rochester', '4', '8', '6', '0', '35', '1912', 'present', 'name', 'wisconsin', '97', 'routes'], ['rochester', '84', '650', '33', 'present', 'district', 'older', '8', '1853', '1', '4', '211']]
TOP TOKENS [['carter', 'ingraham', 'service', '2019', 'h', 'although', 'church', 'disasters'], ['carter', "carter's", 'campaign', 'days', 'conference', 'day', 'president', 'presidency'], ['carter', "carter's", '2019', 'primary', 'however', '2008'], ['carter', 'carlton', '19', 'president'], ['carter', 'carlton', '19', 'president'], ['carter', '2004', '2001', "clinton's", 'accords', 'security', 'humanity', 'lecture', 'father'], ['carter', '2004', '2001', "clinton's", 'accords', 'security', 'humanity', 'lecture', 'father'], ['carter', "carter's", 'nations', 'presidents', 'election', 'evaders'], ['carter', '1945', 'southerners', '2002', 'nicaragua', 'one'], ['carter', 'shot', 'people', 'left'], ['carter', 'season', "carter's", '4ppg', 'page', 'injury', '1rpg', 'sportspeople', '11', '10', '6ppg', 'bucaramanga', 'talent', 'players'], ['carter', '2', '2017', '2014', '2018', '2016', '2021', '2015', 'b', '30', '26', 'game'], ['carter', '2013', '2014', 'american', '4', '17', '15', 'players', 'people', 'profile', 'c', 'expatriate', 'b'], ['carter', '2', 'expatriate', '2017', "men's", 'redshirt', 'descent'], ['carter', '27', '2018', '2020', '2014', '2013', '2021', '2017', '4', '13', 'american', '6', '11', 'expatriate', '8', 'players', '–'], ['carter', 'carter-campbell'], ['carter', 'grandchildren'], ['carter', '2020', '2022', '2021', '2023', 'roster'], ['carter', 'press', 'prairies', 'people', '7', 'work', 'birth', 'links', 'hildebrandt', '2023'], ['carter', "carter's", '10', 'belatedly', '2016', '2011', '18', 'wild', 'season', '2017']]
TOP TOKENS [['workers', 'worker', 'health', 'community', 'care', 'cls'], ['workers', 'workers—including', 'health', 'community', 'frontline', 'pharmacists', 'enough'], ['workers', 'health', 'community', 'care'], ['worker', 'workers', 'health', 'community', 'self-sufficiency'], ['workers', 'health', 'community'], ['workers', 'health', 'community', 'chws', 'individuals'], ['worker', 'workers', 'health', 'community', 'without', '“frontline'], ['workers', 'health', 'community', 'community-based', 'years', 'chws'], ['worker', 'health', 'workers', 'community', 'care', 'delivery', 'people'], ['workers', 'health', 'community', 'programs', 'serve', 'line', 'front', 'verity'], ['workers', 'health', 'community', 'worker', 'care', 'workforce', 'differences', 'may', 'far', 'lady'], ['workers', 'health', 'incentivizing', 'community', 'worker', 'programs', 'measures', '1977', 'program'], ['worker', 'reality', 'workers', 'film'], ['care', 'workers', 'health', 'community', 'workforce', 'use', 'play', 'areas', 'number', 'worker', 'yearly', 'philippines'], ['workers', 'worker', 'health', 'community', 'workercommunity', 'u', 'healthcare', 'village'], ['workers', 'worker', 'care', 'health', 'village', 'respective', 'skills'], ['worker', 'workers', 'medical', 'state', 'healthcare', 'care', 'society', 'taking'], ['workers', 'community', 'established', 'following', 'centers', 'early', 'youth', 'become', 'work', 'kingdom', 'scouts', 'community-based'], ['care', 'worker', 'workers', 'health', 'healthcare', 'infected', 'redistribute', 'migrant', 'trained', 'workforce'], ['workers', 'health', 'care', 'officers', 'extension', 'underserved', 'community', 'workforce', 'providers', 'patients', 'bachelor', 'areas', 'physician', 'program']]
TOP TOKENS [['dominic', 'book', 'faith'], ['dominic', 'dominic’s', 'saint'], ['dominica', 'dominicabeaker'], ['dominic', "dominic's", 'injuries', 'occurred', 'told', '8'], ['dominic'], ['dominic', 'dominick', 'dominicus', 'dominic1', 'dominic2', 'dominical', 'dominik', 'bezeichneter'], ['dominic', 'however', 'second', 'thesaurus', 'intrigue', 'blemish', 'preaching'], ['dominic', 'good', 'extend', 'encapsulate', 'due', 'would', 'gladly'], ['dominic', 'good', 'extend', 'encapsulate', 'due', 'would', 'gladly'], ['dominic', 'ages', 'retinue', 'parents', 'st', 'home', 'adherents', 'appears', 'day'], ['dominick', 'dominica', 'dominic'], ['dominic'], ['dominic', 'dominick', 'dominik', '–', 'two'], ['dominic'], ['dominic', 'festival', 'began', 'television', 'florida'], ['dominic', 'dominick', 'felix', 'dom'], ['dominic', 'dominicus', 'dominica', 'dominick', 'domenico', 'dominiq', 'dominique'], ['dominice'], ['dominici'], ['dominic', 'u.s', 'quickly', 'tacit', 'operation', 'long']]
TOP TOKENS [['europe', 'european', 'throughout'], ['europe', 'spain', 'isles', 'zverev', 'across', 'kaimuk', '2005', 'ciscaucasus', 'zolotuhin', 'eastern', 'nupponen', 'izerskiy', 'florenz', 'fiorini'], ['europe', 'however', 'european', '1', 'reaching', 'superficially', 'either'], ['europe', '1', 'great', 'although', 'amurensis', 'sedentary'], ['within', 'europe', 'ostojá-starzewski', 'vulgaris', '1982a', 'communis', '1969a', '1957a', '1999a', 'europaea', 'tanacetum', 'nodosum', '2002a', 'arvensis', 'huber', 'elatior', 'locusta', 'nudicaulis', 'salvia', 'gnaphalium', 'olusatrum', 'almost', 'erigeron', 'repens', 'silene', 'umbilicus', 'perennis', 'isles', 'pannonicum'], [], ['europe', 'cerris', 'oxfordshire', 'alnus', 'rosa', 'pers', 'betula', "62°30'n", 'cotoneaster', 'lucas', 'fraxinus', 'spain', "brown'skin'which", 'malus', 'tutt', 'vi', 'barrett', 'comm', 'dubatolov', 'newman', 'crataegus', 'tinus'], ['europe', 'sequentially', 'eastwards'], ['within', 'britain', 'pyrenees', 'europe', 'bengtsson', 'europaea', '1989a'], ['europe'], ['–', 'ukraine', 'russia', 'poland', 'charitonov', 'tanasevitch', 'italy', 'melitensis', 'insignis', 'germany', 'greece', 'p', 'istrianus', 'austria', 'kulczynski', 'slovakia', 'denis', 'europe', 'bosmans', 'cambridge', 'turkey', 'wunderlich', 'caporiacco'], ['europe', 'meridionalis', '—', 'narbonensis', 'mallorcensis', 'africa', 'simplicior', 'spain', 'turkey', 'iran', 'huangyangjieensis', 'north', 'mainland', 'lutulenta', 'france', 'caucasus', 'l', 'teideensis'], ['europe'], ['simoni', 'schmidti', 'europe', '—', 'sokhondoensis', 'tridentina', 'roeweri', 'restricta', 'palmae', 'kulczynski', 'sibirica'], ['europe'], ['norway', 'east', 'particularly', '–'], ['europe', 'depending', 'however', 'palearctic', 'june/july'], ['europe', 'islands', 'possibly', 'isles'], ['–', 'portugal', 'britain', 'spain', 'europe', 'hungary', 'georgia', '2001', 'armenia', 'france', 'isaiai', 'bosenberg', 'cambridge', 'c', 'canada', 'russia', 'laziensis', 'algeria'], ['europe', 'angulobulbis', '—', 'africa']]
TOP TOKENS [['race', 'racial', 'ethnicity', 'ethnic', 'among', 'whites', 'g'], ['race', 'ethnicity', 'black', 'white', 'women', 'hispanic', 'ethnicities'], ['whites', 'ethnicity', 'race', 'non', 'lf', 'asians', 'cls', 'whereby', '11', 'ethnic', '8'], ['–', 'caucasian', 'caucasians', 'different', '9', 'ethnical', 'ethnicity', 'deliveries', 'regardless', 'americans', 'ethnicities', 'subjects', 'african', 'ethnic'], ['et', 'minorities', 'studies', 'americans', 'al', 'racial', 'white', '83', 'non'], ['races', 'ethnicities', 'among', 'race', 'ethnicity', 'white', 'groups', 'blacks', 'stroke', 'african'], ['–'], ['ethnicity', 'races', 'caucasian'], ['et', 'white', 'al', 'cases', 'non', '2009', 'racial', '53', 'women'], ['caucasians', 'caucasian', 'african', 'women', 'among', 'american'], ['ethnicities', 'races', 'race', 'ethnicity', 'white', 'ethnic', 'african'], ['ethnic', 'whites', 'minorities', 'racial', 'americans', 'individuals', 'atherosclerotic', 'african', 'result', 'differences', 'diversity', 'whereas'], ['ethnicity', 'black', 'different', 'attainment', 'white', 'ethnic', 'groups', '–', 'united', 'age', 'breastfeeding', 'states'], ['interracial', 'white', 'black', 'latina', 'women', 'activity', 'lives', 'african', 'one', 'asian', '37'], ['ethnic', 'among', 'including', 'racial', 'minorities', 'american', 'americans', 'white', 'also', 'black', 'groups', 'however', 'women', 'african', 'internalization'], ['white', 'screening', 'race', 'diagnosis', 'indicating', 'recent', 'african', 'black', 'even'], ['ethnic', 'among', 'groups', 'americans', 'asian', 'african', 'births', 'whites', 'ricans', 'families', 'varies', '0', '20', '1', '50', 'world'], ['white', 'black', 'women', 'old', 'racial', 'cardiomyopathy', 'similarly', 'asian', 'births', 'hispanic', 'dystocia', 'morbidity', 'postpartum', 'thrombotic', 'race', 'hemorrhage', 'groups', 'embolism'], ['us', 'ethnic', 'shown', 'ethnicity', 'study', 'different', '–', 'u', 'communities', 'et', 'recent', 'minority', 'black', 'preventive', 'may', '20', 'treatment', 'illness'], ['white', 'non', 'racial', 'life', 'postpartum', 'coronary', 'hispanic', 'trend', 'economic', 'subjective', '2010', 'black', 'although', 'rate', 'well', 'prenatal', 'disturbing']]

Processing features:  21%|██▏       | 21/98 [09:50<35:30, 27.67s/it]

getting sample prompt forgetting sample prompt for 23653
 23652
getting sample prompt for 23654
getting sample prompt for 23655
getting sample prompt for 23656
getting sample prompt for 23657
getting sample prompt for 23658
getting sample prompt for 23659
getting sample prompt for 23660
getting sample prompt for 23661
getting sample prompt for 23662
getting sample prompt for 23663
TOP TOKENS [['slags', 'slag'], ['stag', 'stags', 'domain'], ['stag', 'crag', 'cragbag', 'crags', 'slag', 'swag', 'quag', 'sprag'], ['crag', 'rock'], ['slag', 'slags'], ['slag', 'material'], ['slag', 'obtained'], ['slag', 'slags'], ['ctag', 'ctags', 'instructs', 'fo', 'tagfile'], ['prag', 'already', 'soul'], ['stag', 'stagg', 'stags', 'stag-moose', 'football', 'chicago'], ['crag', 'cragg'], ['haag'], ['hoag'], ['hoag', 'football', "hoag's", '1857–1875'], ['hoag', 'oliver', 'life', 'sox', '1939', 'deaths', '295'], ['hoag', 'massachusetts', '1901', 'football'], ['hoag', 'hoagland'], ['stag'], ['kaag', 'buitenkaag', 'kaghe', 'braassem']]
TOP TOKENS [['smishing', 'vishing', 'phishing'], ['smishing', 'attackers', 'phishing', 'discerning'], ['smishing', 'phishing', 'become'], ['smishing'], ['smishing', "cls]'smishing'is", 'smishers', 'phishing', 'hidden', 'aadhaar', 'expiring', 'cybercriminals'], ['smishing', 'phishing', 'attacker', 'attacks'], ['smishing', '“'], ['smishing', 'customize', 'attacks'], ['smishing', 'smishers', 'attacks', 'e'], ['smishing'], [], ['nera', '1989', 'born', 'smajic', '1984', 'smajić', '1910–1985', '1960', '1999', 'armin', 'smajli', '1971', 'petar', '1964', 'surname'], ['smiljanić', 'likar-smiljanic', '1936–2018', 'živorad', 'descent', 'politician', 'serbian'], ['talish'], ['耳', 'fricative', 'instead', 'luxembourgish', 'dot', 'kantenji', 'unk', 'e', 'braille'], ['dot', 'kantenji', 'fricative', 'unk', '囗', 'instead', 'し', '0123467', 'luxembourgish', '2', '1234578', '⺩', 'top', '123467', 'correspond', 'braille', '012346'], ["devic's", 'religions', '1888-1944', 'united', 'culture', 'serb', 'devics', 'orthodox', 'angeles', 'described', 'states', 'optica'], ['ze', 'letter', 'palato-alveolar', 'ʒ', 'vini'], ['serbian', 'dević', '1963', 'b', '1984', 'footballer', 'devič', 'serbian-ukrainian', 'borislav', 'kosovo'], []]
TOP TOKENS [['joshua', 'josh', 'joshuah', 'joshwa', 'joshuwa'], ['joshua', 'joshuas', 'josh'], ['joshua', 'joshuaˈdʒɒʃ', 'whose'], ['joshua', 'dream', 'ease', 'honest', 'planned'], ['joshua', 'joshua’s'], ['joshua', 'josh', 'joshy'], ['joshua', 'look'], ['joshua', 'him’', 'formation', 'access'], ['joshua', 'josh', '24:1–27'], ['joshua', 'joshue'], ['joshua'], ['joshua', 'josh', '1942', '1977'], ['joshua'], ['joshua', 'josh'], ['joshua', 'josh'], ['joshua', 'josh', 'ashes', '1763–1845'], ['joshua', 'city'], ['joshua', 'living', 'players', 'people', 'simply', 'spanish', 'segunda', 'footballers'], ['joshua', 'josh', '2002'], ['joshua', 'josh']]
TOP TOKENS [['barefoot', 'measure', 'running', 'see', 'bare', 'used'], ['barefoot'], ['barefoot', '“barefoot', 'decades', 'term', '70', 'shoe', 'foot', 'line', 'accordingly'], ['barefoot', 'walking'], ['barefoot'], ['barefoot', 'walking'], ['barefoot', 'months', 'cls', 'unprotected', 'forefoot', 'running'], ['barefoot', 'around', 'unconsciously', 'problems', 'stomped', 'soles', 'walking', 'veins', 'shoes', 'regulated', 'various'], ['barefoot', 'shoes', 'running'], ['barefoot', 'dwellers', 'behind', 'going', 'posture', 'moment', 'body'], ['barefoot', 'barefooted', 'barefooting', 'lanka', 'barefoot—without'], ['barefoot'], ['barefoot'], ['barefoot'], ["barefoot's", 'barefoot', 'career', 'season', 'broodmares', 'old', 'later', 'august', 'pedigree', 'racing'], ['barefoot', 'barefoot’s', 'name', 'mainly', 'impoverished', 'also', '2011', 'home', 'sri', '1967'], ['barefoot', 'barefooting', 'barefootin'], ['barefoot'], ['barefoot'], ['barefoot', 'barefooter', 'barefooting', 'barefooters', 'first', "skier's"]]
TOP TOKENS [['dracaena', 'dracaenas', 'dracena', 'completely'], ['dracaena', 'cutting', 'double-headed', 'etc', '2-3'], ['dracaena', 'dracaenas'], ['dracaena', 'dracaenas', 'colours||bloom', '80â°f'], ['dracaena', 'dracaenas'], ['dracaena', 'dracaenas', 'due', 'sides', 'quite'], ['dracaena', 'home', 'height'], ['dracaena', 'fertilizer', 'margined'], ['dracaena', 'dracaenas', 'foliage', 'hassle', 'elegant', 'height'], ['dracaena', 'indoors', '80', 'fertilizer', 'controlled-release', 'grow'], ['dracaena'], ['dracaena'], ['dracaenas', 'dracaena', 'dracaenoid', 'dracaenaceae', 'acutissima', 'system', 'mildbr'], ['dracaena', 'flora'], ['dracaena', 'dracaenas', 'description', 'distribution', 'sessile', 'long', 'foliage'], ['dracaena', 'dracaenoid', 'isobilateral', '1–9cm', 'shaped', 'tetracytic', 'ecology'], ['dracaenaceae', 'dracaena', 'berry-like', 'placed', 'also', 'family', 'otherwise', 'base', 'genus', 'stem/s', 'two-lobed', 'system', 'ruscaceae'], ['dracaena', 'l', 'engl', 'g', 'varians', 'f', 'jacq', 'christenh', 'mabb', 'hook', 'n', 'forst'], ['dracaena', 'south'], ['dracaena', 'gerome', 'ridl', 'christenh']]
TOP TOKENS [['brahman', "the'brahman'is", 'everything'], ['brahman', 'brahma', 'universe', 'hinduism'], ['brahman', 'brahma', 'brahmin', 'brahmins', "a'brahmin"], ['brahman', 'however', 'vital'], ['brahman', 'brahmanda', 'brahma'], ['brahman', 'brahma', 'indistinguishable', 'cls', 'abiding'], ['brahman', "brahman.'the"], ['brahmana', 'brahmanas', 'brahma', 'mukhabahurupajjanam', 'बराहमण', 'brahmin', 'cls'], ['brahman', 'brahmani', 'brahma', 'indeed'], ['brahman', 'gratification'], ['brahmana', 'brahman', 'brahma', '2014'], ['brahman', 'reality', '2001', 'stylized', 'hope', '2008'], ['rehman', 'rehmann', 'saleema'], ['eshman-e', 'eshman'], ['lohman'], ['mehman'], ['brahman', 'brahma', 'hinduism', 'changes'], ['brahman', 'brahmin'], ['brahman', 'bahman', 'bahmān', 'brahmin'], ['lahman', 'dahman']]
TOP TOKENS [['goldenrod', 'silverrod', 'solidago', 'disguished', 'ser', 'white', '×'], ['goldenrod', 'goldenrods', 'solidago', 'subsp', 'genus'], ['goldenrod', 'connotes', 'urinary', 'solidago', 'triple-nerved'], ['goldenrod', '“solidago', 'solidago', 'distinguish', 'you’re', 'though', 'called', 'fact', '“s.rugosa”', 'aster'], ['goldenrod', 'goldenrods'], ['goldenrod', 'goldenrods', 'solidago', '–'], ['goldenrod', 'solidago'], ['goldenrod', 'solidago'], ['goldenrod', 'solidago', 'across', 'inch', '1/16', 'hairy', 'zigzag', '3-veined'], ['goldenrod', 'goldenrods', 'goldenrod1', 'solidago', 'ornamental', 'may', 'genus'], ['goldenrod', 'solidago'], ['goldenrod', 'description', 'southeast'], ['goldenrod', 'goldenrods', 'solidago'], ['goldenrod', '150', 'long', 'states', 'solidago', 'lab'], ['goldenrod', 'well', 'dakotas', '200'], ['goldenrod', 'solidago'], ['goldenrod', 'solidago'], ['goldenrod', 'silverrod', 'prefers', 'roadsides', 'wiry'], ['goldenrod', 'solidago', "curtis'goldenrod", 'turcz', 'silverrod'], ['goldenrod', 'canada', "elliott's", 'large', 'many']]
TOP TOKENS [['gdansk', 'danzig', 'country', 'imports', '“'], ['danzig', 'gdansk', 'gdańsk', '1945', 'centre'], ['gdansk', "gdansk's", 'danzig', 'ii', 'century', 'well'], ['danzig', 'gdańsk'], ['gdansk', 'danzigians', 'i.e', 'however'], ['danzig', 'gdansk', 'centuries', 'corridor', 'together', 'city'], ['gdansk', 'nowadays', 'merchants', '–', 'also', 'galleries', 'adorn'], ['gdansk', "gdansk's", 'gyddanzyc', 'jewel'], ['danzig', 'gdansk', 'introductionalthough'], ['danzig', 'gdansk', 'introductionalthough'], ['danzig', 'gdansk', 'botanist', 'historian', '1667', '1485', '1631', '1714', 'daniel', 'astronomer', 'johannes', '1615'], ['gdansk', 'danzig'], ['gdańsk', 'danzig'], ['gdańsk', 'gdansk'], ['gdansk', 'gdańsk', 'danzig', 'danzigs', '1849', 'used'], ['danzig', '2014', '1994', '2008', 'laboratory', 'ourpublicservice', 'board', 'also', 'based', 'system', '1997', 'affairs', 'came'], ['gdańsk', 'danzig', 'młynarczyk', 'kaczyński', 'dulkiewicz'], ['gdańsk', 'danzig'], ['gdansk', 'danzig', '1346', 'rights', '1360', 'przymorze', '1410', 'st', 'pomerania', "catherine's", '1350'], ['gdańsk', 'danzig']]
TOP TOKENS [['borough', 'boroughs'], ['borough', 'boroughs', 'sovereign'], ['borough', 'boroughs'], ['borough', 'boroughs', 'word', 'ireland', 'queenscliffe', '6', '3', 'alaska'], ['borough', 'boroughitis', 'boroughs', 'term', 'bronx', 'township', '3534'], ['borough', 'boroughmiddle', 'place', 'city', 'various', 'unincorporated'], ['borough', 'boroughs', 'richmond'], ['borough', 'boroughs', 'boroughitis'], ['borough', 'boroughs', '273', 'english', 'sep'], ['borough', 'boroughs', '‘', 'onwards', '’', 'clear', 'one', 'lord'], ['borough', 'boroughs'], ['borough', 'boroughs', 'cls'], ['borough', 'holstocke'], ['borough', 'london', 'twice'], ['borough', 'boroughs', 'also', 'united', 'pennsylvania'], ['borough', '1557', 'navigation', "albacar's"], ['borough', 'boroughs', 'iv'], ['borough'], ['borough', 'cls', 'design', 'kennington', '2022', 'would', '1985', 'carried'], ['borough', '1557', 'confidentia', 'dvina']]
TOP TOKENS [['maint', '–', 'berthon', 'file', '002200949102600305', '0', '4', '978', 'isbn', '72471', 'churchill', 'stalin', 'beevor', 'life', 'bradley', '10', '0160', '86197774', '8', '431'], ['maint', '978', 'headline', 'isbn', 'clark', '0', 'quill', 'montgomery'], ['eds', 'pp', 'isbn', 'battle', 'mawdsley', 'hardcover', 'joachim', '599', 'glantz', 'history', 'farrell'], ['isbn', 'melvyn', '2007', 'gunston', '978', 'airlife', 'jonathan', 'bill', 'military', 'william', 'publishing', '2006', 'hiscock', 'artem', 'gordon', 'gleed', '–', '1987', '2008', 'pp', 'ian', 'press', 'ltd', 'holmes', '84415', '1989', 'biography', 'four', 'trust', 'w', '1991', '6', 'house', 'tom', 'bailey', '3', '1984', 'yorkshire', '84354', '872922'], ['9', '5', '0', 'и', 'maint', '978', 'союз', 'упущенныи', '0141011929', 'вече', '0313395925', 'miller', 'борьба', 'kansas', '0590', 'советскии', 'mercatante', 'praeger'], ['account', 'pp', 'rys', 'comprehensive', '60', 'isbn', 'marek', 'ramsay', 'neulen', '–', 'ed', 'shacklady', '2010', 'hugh', '2006', 'morgan', 'shambles', 'edward', 'hurricane', '1989', 'aviation', '978', '1', 'first', 'limited', 'mk', '65', 'postan', '203', 'pacific', 'werner', '86126', '6'], ['978', '578338', 'isbn', 'authoritative', '10', 'account', 'international', '226', '002200948702200202', 'publishing', 'unwin', '0', 'eds', '1', '1080', 'press', 'jstor', '151203', 'engagements', '620', '09668138608411636', '–', '86508', 's0018246x00', 'head', '1177'], ['isbn', 'weinberg', 'anstalt', '2', 'b0000cmau7', '978', 'press', '2191', '1941', 'dutton', 'littlefield', 'asin', 'stumpf', 'und'], ['0700618286', '978', '0300084597', '0', 'hitler', 'isbn', '101', 'maint', 'house', '3879980383', '30681', '966078', 'kansas', '0752460703', 'handrack', '8', 'books', 'cambridge', '698', 'der'], ['p', 'cape', 'hitler', '1941', 'wells', 'c', 'james', 'j', 'levine', 'k', 'glantz', 'r', 'u', 'house', 'n', 'l', 'pacific', 'e', 'howard', 'hart'], ['morgan', 'marek', 'leo', '2010', 'werner', 'hugh', 'ramsay', 'account', 'pacco', 'postan', 'murray', 'edward', 'ramsbury', 'rys', 'comprehensive', 'pp', 'yuriy', 'mckinstry', '2006', '65', 'aartselaar', '–', 'winston', 'hurricane', 'prins', 'publications', 'limited', 'ed', '1950', '1999', 'shacklady'], ['barossa', '2007', 'margaret', '1981', 'fisher', 'christer', 'allan', 'brittain', '1984', 'incorporated', 'cooper', 'bergstrom', 'schuster', 'vera', 'clayton', '2004', 'paperback', 'gaskin', '2010', 'j', 'hour', 'viking', 'haining', 'matthew', 'halpenny', 'patrick', 'peter', 'e', 'cumming', 'hoard', 'stephens', 'arkady', 'books', 'polonica', 'press', 'harcourt'], ['brookes', 'parker', '2007', 'volume', 'russia', 'hayward', 'hooton', 'publishing', 'ciglic', 'jackson', 'james', '1940', 'malizia', 'press', 'e', 'luftwaffe', 'robert', 'muller', 'sebastian', 'weis', 'bungay', 'cull', 'c', "luftwaffe's", 'savic', 'britain', 'cox', '1974', 'armour', 'lander'], ['halley', 'pp', '53', '2013', '1993', '2006', 'jones', '1973', '38', 'james', 'hubbard', 'gilchrist', '2001', '2008', '1985', 'publishing', 'ltd', '–', '1980', 'barry', 'tim', 'limited', '2003', 'robert', 'press', '1990', 'om', 'osprey', 'sword', 'bill', 'force', '1997', '2007', '2', 'bombers', 'wz999'], ['47', 'murphy', 'waller', 'constantine', 'barbarossa', 'hardcover', 'mineau', 'pp', 'taylor', 'efield', 'rees', 'andre', 'press', 'donald', 'l', 'paperback', 'schuster', 'review', 'mifflin', 'front', 'e', 'december', '1293', 'new', 'eds', 'reich', 'rayfield', 'london', 'vol', 'stalin', 'rodopi', 'shirer'], ['john', 'tsr', 'segell', 'smith', 'gunston', 'paul', 'bill', 'lucas', '1984', '1998', '2002', 'tim', '1997', 'co', 'mclelland', 'taylor', 'james', 'bedford', 'logan', '2009', 'press', 'dan', 'sweetman', 'w', 'glen', 'garver', 'paterson', 'report', "jane's", '2006', 'publications', 'sharpe', '2', 'harver', 'group', 'kaldor', 'faber', 'history', 'hastings', 'e', 'r', '1980', '1978', 'world', 'routledge', 'pictorial', 'mary', "britain's", '2010', 'publishers', 'tornado'], ['farrell', 'murray', '920', 'glantz', 'krivosheev', 'hardcover', 'kershaw', 'london', 'books', 'koch', 'latimer', 'gorodetsky', 'rtd', 'press', 'j', 'tempus', 'pp', '–', 'war', 'p', 'f', '26', 'kansas', 'olzog', 'rodopi', 'allan', '42', 'paperback', 'russia', 'lawrence', '1941', 'littelefield', '599', 'battle'], ['vor', 'blood', 'antony', 'perry', 'nicholas', 'blandford', 'clay', 'beevor', 'bird', 'armin', '2002', 'books', 'viking', 'w', 'bottger', 'edmund', '1942', 'smith', 'bergstrom', 'day', 'bethell', 'blair', 'hunted', 'socialism', 'biddiscombe', 'house', 'ii', 'gerwarth', 'winston', 'bessel', '2015', 'werwolf', 'crewman', 'reich', '–', 'dulles', 'press', 'browning', '1945', '2006', 'christopher', 'inc', 'richard', 'library', 'gruener'], ['aka', 'p', '–', '2006', 'heroes', "vision's", "team's"], ['hugh', 'richard', 'volume', 'mathew', 'quinlan', 'moyes', 'taylor', 'luftwaffe', 'john', 'roper', 'parker', 'chris', '45', 'britain', 'r', 'press', 'war', 'phillip', 'uwe', 'richards', 'andy', 'ltd', 'london', 'michael', 'b000qiv8am', '2004', '1939', 'sword', 'feist', 'defeat', '2000', '1', '1945', 'publishing', 'korda', 'goss', 'hooton', 'focus', '1983', 'saunders', 'pacific', 'murray', 'francis', 'james', 'sebastian', 'cox', 'washington', 'terraine', 'allan', 'books', '–', '1993', '109']]
TOP TOKENS [['functor', 'category', 'homomorphisms', 'categories'], ['functor', 'functors', 'category', 'morphisms', 'categories', 'homomorphisms'], ['functor', 'functors', 'category', 'categories', 'homomorphism', 'morphism'], ['functors', 'homomorphisms', 'categories', 'functor', 'category'], ['functor', 'functors', 'category', 'morphisms', 'categories'], ['functors', 'category', 'functor', 'homomorphisms', 'morphism'], ['functors', 'functor', 'morphism', 'categories', 'category', 'morphisms'], ['functor', 'functors', 'morphism', 'morphisms', 'category'], ['functor', 'functors', 'morphisms', 'category', 'morphism', 'categories'], ['2-functor', 'functors', 'functor', '2-functors', '1-morphisms', '2-morphism', 'hom-category'], ['functors', 'functor', 'categories', 'category'], ['functor', 'functors'], ['functor', 'functors', 'category', 'morphism', 'adjoints', 'characterizes'], ['functors', 'functor', 'categories', 'morphisms', 'morphism', 'functoriality'], ['functors', 'functor', 'categories', 'category', 'morphisms'], ['functor', 'functors', 'morphism', 'category'], ['functors', 'functor', 'category', 'induces', 'funct', 'categories'], ['functor', 'functors', 'categories', 'category', 'morphism', 'morphisms'], ['2-functor', 'functor', 'functors', 'cat-functor'], ['functor', 'functors', 'category', 'categories']]
TOP TOKENS [['nominative', 'accusative', 'persons', 'example', 'grammars', 'plural', 'dative'], ['vocative', 'nominative', 'dative', 'accusative', 'genitive', 'possessor', 'pronouns', 'hand'], ['n', 'whereas', 'voice', 'aspect', 'nevertheless', 'perfective', 'accordingly', 'verbs', '”', 'usually'], ['nominative', 'accusative', 'another', 'however', 'schmitt', 'ed'], ['nominative', 'genitive', 'dative', 'forms', 'accusative', 'vocative', 'verbs', 'stems', 'addition', 'verbal', 'adverbial', 'though', 'pronominal', 'locative'], ['genitive', 'nominative', 'pronoun', 'order', 'one', 'shifted', 'noun', 'adnominal', 'many', 'typically', 'pronouns', 'adverbal'], ['suffixes', 'adjectives', 'relative', 'g', 'demonstrative', 'also', 'beings', 'case', 'determiner'], ['adjectives', 'possessors', 'perfective', 'juxtaposition', 'conjunctions', 'mainly', 'quantifiers', 'may', 'optative', 'indicative', 'iterative', 'three', 'affixes', 'habitual', 'conjunctive', 'conditional', 'features', 'present', 'however', 'progressive'], ['cemen', 'men', 'adem', '3', '5', 'person', 'intransitive', 'pronominal', 'west', 'dative', '26', '4', 'transitive', 'pp', '2'], ['nominative', 'genitive', 'dative', 'allative', 'adessive', 'accusative', 'objects', '“', 'kurdish', 'transitive', 'semnani', 'dimili', 'postpositions'], ['demonstrative', 'postpositions', 'characteristics', 'nominative', 'emphasis', 'description', 'tenses', 'present', 'past', 'prepositions', 'transitivity', 'indicative', 'sorani', 'consist', 'possession', 'following', 'conditional', 'general'], ['pronoun', 'verbs', 'suffix', 'may', 'accusative', 'phrases', "busud,'other", 'instead', 'decimals', 'almost'], ['accusative', 'suffixing', 'nominative', 'process', 'postpositions', 'voice', 'plurality', 'characteristic', 'morphology', 'demonstratives', 'suffixes', 'several', 'final', 'tenses', 'fact', 'pronouns', 'include', 'indirect', 'plural', 'also', 'imperfect', 'past'], ['aspect', 'intransitive', 'also', 'lative', 'singular', 'take', 'person', 'particles', 'root', 'suffixes', 'nonetheless', 'feature', 'genitive', 'inflected', 'volitional', 'forms', 'morphologically', 'subcategories'], ['nominatives', 'active', 'usually', 'gender', 'past', 'indicative', 'person', 'present', 'imperative', 'infinitive', 'causative', 'verbs', 'conditional', 'pronouns', 'pluperfect', 'given', 'predicate', 'used', 'number', 'nominative', 'unmarked', 'noun'], ['imperative', 'suffix', 'markers', 'general', 'also', 'pronouns', "seated,'hɨp'refers", 'inferring', "and'hoːɾi'refers", 'inflection', 'prefixes', 'interrogative', "and'tɨpoŋ'is", 'demonstrative', 'pronominal', 'intransitive', "distal,'ɲa'refers"], ["hualapai's", 'nominative', 'allative', 'articles', 'hualapai', 'accusative', 'belonging', 'demonstratives', 'adessive', 'also', 'system', 'verb', 'possessive', 'appellative'], ['nominative', 'dative', 'intransitive', 'constituent', 'accusative', 'type', 'subject', 'inflection', '1997', 'though', 'kurdish'], ['nominative', 'accusative', '–', '‘', '2', 'stative', 'another'], ['nominative', 'show', 'kurmanji', 'nouns', 'endings', 'tense', 'vocative', 'cls', 'accusative']]

Processing features:  22%|██▏       | 22/98 [10:19<35:47, 28.26s/it]

getting sample prompt forgetting sample prompt for 23665
 23664
getting sample prompt for 23666
getting sample prompt for 23667
getting sample prompt for 23668
getting sample prompt for 23669
getting sample prompt for 23670
getting sample prompt for 23671
getting sample prompt for 23672
getting sample prompt for 23673
getting sample prompt for 23674
getting sample prompt for 23675
TOP TOKENS [['“leapers”', 'leap', '“a', '“leaplings.”', 'year?”', 'year'], ['leap', 'donkey', 'leaper', 'strip', 'year', 'leapling', 'years', 'day', 'days', '4', 'ribbit', 'cls'], ['leap', '“leapers”', '“leaplings”', 'non-leap', 'year', 'day'], ['leap', 'non-leap', 'year', 'even'], ['leap', 'leapers', 'year', 'day', 'years', 'sun', '24', 'quite', 'introduced'], ['leap', 'leaplings', 'leapling', 'ago', 'year', 'day', 'identify', 'years', 'days', '2', 'babies', 'rosebank'], ['leap', 'leapers', '‘leapers’', 'years', '4', 'year', 'first', 'day', 'reading', 'well-known', 'days'], ['leap', 'day', 'year', 'man-made', 'familiar', 'created', 'welcomed', 'cake', '3,000'], ['leap', 'leap-lips', 'leaplings', 'leapfrogs', 'non-leap', 'day', 'year'], ['student', 'leap', 'skills', 'uses'], ['leapp'], ['29', 'leap'], ['years', 'leap'], ['divine', 'leap'], ['game', 'leap', 'leapfrog', 'leap-frog', '1914–1980', 'infantry'], ['leaper(s', 'leaper', 'little', 'leapers'], ['leap', 'english-language', 'television', 'beth', 'flashforwards', 'series'], ['others', 'leapman', '1995', 'born', 'david', 'following', 'biography', 'moved', 'jerwood'], ['leap', 'advantage', 'agency', 'website', 'workforce', 'project'], ['leap', 'serviced', 'inland', "o'donovan's", 'seacoast', '1684']]
TOP TOKENS [['tagetes', 'ft', 'tages', 'religion', 'founding', 'passion', 'lemmonii', 'aztecs', 'fidelity', 'america'], ['taguchi', 'article', 'design', "taguchi's", 'stick', 'using', 'inefficiencies', 'highly', 'approach'], ['tagamet', 'acid', 'use', 'measure'], ['tagus', 'tagusˈteɪ', 'albarracín', 'random', '47', 'ibérico', 'iberian', 'salvaterra', 'word', '80,100', 'mouth', 'tejo', 'km', 'along', 'area'], ['tagetes', 'properties', 'practices'], ['tagore', "tagore's", 'conduct', 'mansion', 'birth', 'common', 'heralded', 'poetry', 'man'], ['tagetes', 'man', '4', 'sprigs', 'properties', 'uses', 'red', 'world', 'stunning'], ['taguchi', 'occur', 'proposals', 'however', '’', 'cls', 'significant'], ['tagore', "tagore's", 'pupils', 'monies', 'kawabata', 'bengalis', 'tag', 'implemented', 'evenings', 'individualised', 'worked', 'states', 'afternoons', 'calcutta', '’', 'festival', 'annual', 'provide'], ['tagore', '”', 'tolstoy', 'translated', 'damn', 'involving', 'reputation', 'twenty', '“', '’', 'possibly', 'translations', 'deeper'], ['tagg', 'taggart', '1983', 'small', 'beverly', 'john', 'american', 'prototype', 'r'], ['19262016', 'tago', 'born'], ['tagg', '1979', 'born', "tagg's"], ['taga', 'may', 'refer', 'north-eastern', 'archeological'], ['tague'], ['tagami', 'may', 'refer', 'similar-sounding'], ['tajine'], ['universe#tagora', 'tagora'], ['tagi', 'refer', 'unicolor'], ['tages', 'tage']]
TOP TOKENS [['agenda', 'team', 'seminar', 'inform', 'facilitation', 'items', 'track', 'minutes', 'order', 'cloud', 'free', 'voting'], ['meeting', 'informative', 'everything', 'agenda', 'topic', 'cover', 'meetings', 'agendas', 'good'], ['separate', 'agenda', 'discussed', 'votes', 'essence', 'important', 'previous'], ['separate', 'agenda', 'discussed', 'votes', 'essence', 'important', 'previous'], ['agenda', 'you’ll', 'done.”', 'along'], ['reference', 'agenda', 'agendas', 'discussion', 'covered', 'entire', 'made', 'cohesive', 'cls', 'included', 'flow'], ['reference', 'agenda', 'agendas', 'discussion', 'covered', 'entire', 'made', 'cohesive', 'cls', 'included', 'flow'], ['describe', 'agenda', 'fancy', 'group', 'allocates', 'complete', 'adjournment', 'agendas', 'meeting', 'choose', 'clear', 'timed', 'prioritized'], ['altogether', 'agenda', '“', 'agendas', 'underlying', '”', 'done', 'meeting', 'list', 'eliminating', 'longer'], ['agenda', '’', 'serve', 'order', 'hidden', '3', 'anoint'], ['links', 'addition', 'external', 'agenda', 'year', '1991', 'routledge'], ['1983', 'evening', "agenda's", 'agenda', 'sundays', 'may', 'right'], ['2001', 'african', 'uk-based', 'dos-based', 'agenda', 'programme', 'tank', 'pet', 'current', 'british'], ['tax', 'enterprise', 'lippestad', 'center-left', 'agenda', 'establish', 'non-partisan', 'august', 'norway', "agenda's", 'argued', 'jointly', 'policy'], ['agenda', 'activities', 'agendas', 'follow', 'adjournment', 'meeting', 'gerundive', 'upon', 'cattle', 'usually', 'plural', 'session'], ['week', 'agenda', 'canberra', '2001', '4', 'park', 'usually', 'keneally', 'sunday'], ['americans', 'care', 'key', 'based', 'focused', 'served', 'activists', 'well', 'issues'], ['2016', 'began', '27', 'agenda', '60', 'november', 'ahead', 'discuss', 'presented', 'broadcast', '10.45pm'], ['house', 'game', 'film', 'supermassive', 'agenda', 'hidden'], ['week', 'agenda', 'returned']]
TOP TOKENS [['oboe', 'tone-colour', 'century'], ['oboe', 'tone-colour', 'century'], ['oboe'], ['oboe', 'oboes', "oboe's"], ['oboe', "oboe's"], ['oboe', 'oboes', 'tone'], ['oboe', 'oboes'], ['oboes', 'oboe', "oboe's", 'result'], ['oboe', 'oboes', 'violin', 'role', 'parts'], ['oboe’s', 'oboe', 'oboes'], ['oboe'], ['oboe'], ['oboe', 'oboes', 'oboeschule', 'instruments'], ['oboe', 'oboes'], ['oboe', 'harp'], ['oboe', 'oboe-type', 'oboes'], ['oboes', 'oboe', 'increased', 'instruments', 'sound', 'instrument', 'dresden'], ['oboe', 'aircraft', 'h2s', 'cls', 'allowed'], ['oboe', 'violoncellos', 'oboist', 'carewe', 'collegium'], ['oboe']]
TOP TOKENS [['coordinators', 'coordinator', 'scores', 'educator', 'activities'], ['coordinator', 'oversees', 'manner', 'coordination', 'etc', 'cls', 'aegis', 'amount'], ['coordinators', 'coordinator', 'performs', 'able', 'coordinate'], ['coordinator', 'coordinators', 'works'], ['coordinators', 'coordinator'], ['coordinators', 'coordinator', 'care'], ['coordinator', 'knowledge', 'ways', 'organisation'], ['coordinators', 'coordinator', 'process', 'development', 'must'], ['coordinator', 'coordinators', 'driven', '‘', 'markets', 'skills'], ['coordinator', 'coordinators', 'coordination', 'coordinating'], ['coordinators', 'coordinator', 'parenting', 'joe'], ['coordinator', 'oversees', 'report', 'also'], ['coordinator', 'coordinators'], ['coordinator'], ['coordinator', 'coordinators', 'departments', 'script'], ['coordinators', 'coordinator', 'coordination', 'review', 'transplant'], ['coordinator', 'coordinators', 'single', 'throughout'], ["coordinator's", 'coordinator', 'stunt', 'director', 'coordination'], ['coordinator', 'finance', 'scholarship'], ['coordinator', 'officially', 'serves', 'production', 'usually', 'responsible', 'often', 'office', 'varied', 'manager', 'personnel', 'usa)industry’s', 'movie']]
TOP TOKENS [['welfare', 'animal', 'managing'], ['welfare', 'animal'], ['welfare', 'animal'], ['welfare'], ['welfare', 'animal', 'environment', 'upon'], ['welfare', 'animal', 'define', 'relates'], ['welfare', 'animal'], ['welfare', 'animal', 'regarding', 'standards', 'upraising'], ['welfare', 'animal'], ['welfare', 'animal', 'management'], ['welfare', 'animal', 'poor', 'defined', 'farmed', 'dictionary', 'assessment', 'ascertaining', 'animals'], ['welfare', 'animal'], ['welfare', 'animal', 'act'], ['welfare', 'animal'], ['welfare'], ['welfare', 'animal', 'standards', 'animals', 'injury', 'treat'], ['welfare', 'animal', 'laws', 'cls'], ['welfare', 'animal', 'science', 'quality', 'society', 'behavioural'], ['welfare', 'animal', 'farmed', 'conditions', 'standards', 'rearing', 'hens', 'welfare-conscious'], ['welfare', 'animal', 'cls', 'suffering', 'done', 'act', "protection's"]]
TOP TOKENS [['leed', '60-79', 'gold'], ['leed', 'project', 'achieve'], ['leed', 'builders'], ['leed', 'leed-certified', 'involved', '1998', 'cost-saving'], ['leed-eb', 'leed', 'leed-cs', 'leed-ci', 'leed-nc', 'silver', '240,000', 'high-performance', '16,373', '83,713', '2012'], ['leed', 'former', 'energy', 'u.s', 'council’s'], ['leed', 'estimating'], ['update', 'leed', 'developed', 'standard', 'context', 'cannot', 'leedership'], ['“leed', 'leed', '1994'], ['leed-certified', 'leed', '“leed”'], ['leed', 'buildings', 'developed', 'qualifying', 'latter', '0'], ['leed'], ['leed', 'u'], ['leed', '2000', 'inception', 'museum', '’', 'date'], ['leed', 'rates', 'concerns', '205', 'economy', 'despite', 'offices', 'u', 'allowances', 'capita'], ['leed', 'risk', 'certified'], ['leed'], ['leed', 'leed™', 'homes', '2024'], ['design', '1955–2017'], ['leed', 'terms', 'cls', 'depending', 'new']]
TOP TOKENS [['stairway', 'floors', 'building', 'stairs', 'stair', 'landing', 'staircase', '2'], ['stairways', 'stairs', 'staircases', 'stairway', 'finished', 'buildings', 'stair', 'floor'], ['stairs', 'cls', 'stair', 'staircase', 'staircases', 'codes', 'stairway', 'using', '“', 'stairwell', 'steps'], ['stairway', 'staircase', 'stairs', 'stair', "stair's"], ['stairs', 'staircase', 'stair', 'staircases', 'stairway', 'steps', 'sep', 'mean', 'called'], ['stairs', 'value', 'stair', 'buildings', 'staircase', 'made', 'floors', 'used'], ['stair', 'stairs', 'staircase', 'steps'], ['stairs', 'stairways', 'staircase', 'stair', 'building', 'enough', 'intended', 'good', 'cls'], ['stairs', 'stairways', 'stairwaythe', 'stair', 'stairway', 'build', 'words', "there's"], ['stairs', '”', 'stair', 'staircases', 'staircase', 'cls', 'elements', 'often', 'thought', 'way'], ['steps', 'song', 'film', 'game'], ['disambiguation', 'staircase', 'stairway', 'play'], ['steps', 'disambiguation', 'stairway', '1992–2017'], ['stairway', 'stairs', 'means', 'staircase', 'cls', 'stairwell', 'buildings', 'ramps', 'distances', 'ladders'], ['1848–1904', 'stairs', 'edison', '1863–1892'], ['stairway', 'stairs'], ['staircase', 'dumps', 'among', 'dedication', 'loft', 'carpenter', 'building', 'furious'], ['stairs', 'years', 'win', 'clients'], [], ['stairs', 'stair', 'steps', 'next', 'tread']]
TOP TOKENS [['fasteners', 'fastener', 'fasten', '—'], ['fasteners', 'products', 'fastener', 'advance', 'manufacturing', 'process'], ['fasteners', 'fastener', 'minor', 'manufacturing', 'may', 'inconspicuous', 'adaptability', 'moreover', 'satisfaction', 'industry', 'paramount', 'seem'], ['fasteners', 'fastener', '‘', 'parts', 'without', 'correct', 'certainly', 'one', 'yes', 'former', '30'], ['fastener', 'fasteners', 'importance', 'coatings', 'place', 'cls', '’', 'come', 'buildings'], ['fasteners', 'fastener', 'cls', 'equally', 'come'], ['fasteners', 'fastening', 'fastener', 'one', 'range', 'wide', 'presently', 'cls', 'objects'], ['fasteners', 'fastener', 'north', 'time', 'uses', 'value', 'various', 'cls', 'clips'], ['fasteners', 'fastener', 'common', 'types'], ['fasteners', 'fastener', 'used'], ['fastener'], ['fasteners', 'fastening', 'fastener', 'methods'], ['fasteners', 'fastener', 'models'], ['fasteners', 'fastener', 'melded'], ["fastener's", 'fastener', 'slots', '16', '12', 'position', 'relaxed', 'placing', '11', '22', '10', 'head', "slot's", 'fuselage', '17', 'screwdriver', 'noise'], ['fasteners', 'fastener', 'also', 'etc', 'securing', 'altogether', 'multiple', 'secured', 'publication', 'anyone', 'sep', 'cut', 'retention', 'another', 'millimeters', 'metal'], ['fasteners', 'fastener'], ['fastener', 'stuttgart', 'also', '1950s', '44', 'years', 'accounts', 'supply'], ['fasteners'], ['fastener', 'glove', 'rigueur', 'crochet', 'coolus', 'whites', 'asian', 'cycling', 'czapka', 'compression', 'duck', 'cowhide', 'stays', 'dep', 'stockings', 'fastness', 'collection', 'coat', 'concert', 'damask', 'cuban', 'cricket', 'colour', 'cornrows', 'coloured', 'hat', 'conical', 'couturier', 'thread', 'cap', 'vest', 'shirt']]
TOP TOKENS [['variational', 'variations', '“', 'ashənəl'], ['variational', 'variations', '42', '505', '”'], ['variational', '2009', 'method', 'image002'], ['variation', 'problems'], ['variation', 'used', 'essential', 'theory', 'make', 'arises'], ['variation', 'handel’s', 'music', 'variations'], ['variation', 'commutes', 'variational', 'computes', 'thus', 'η', 'δηf', '32', 'equations', 'using'], ['variational', 'used', 'principle', 'optics', 'explains', 'methods', 'famous'], ['variational', 'cases', 'special', 'methods', 'formulation', 'apparatus'], ['variational', 'variations', 'differential', 'according', 'principles', 'principle'], ['variational', 'variation', 'variations', 'using', "maupertuis'principle", 'method'], ['variation', 'eigenstate', 'variational', 'variations', 'minimizing'], ['variational', 'method', 'mechanics', 'state', 'complications', 'apply', 'eigenstate'], ['variation', 'variations', 'chess', 'analysis'], ['variational', 'variations', "fermat's", "luke's", 'cycloid', "noether's"], ['north', 'eddie', 'astronomy', 'last', 'pas', 'avant-garde', 'journal', 'variations', "stravinsky's", '1982', 'true', 'seul', 'minima', 'george', 'peter', '1966'], ['variations', 'variational', 'w', 'variation', '3rd', 'methods', "ekeland's", 'elsgolc', 'publ', 'dacorogna'], ['variational', 'variation', 'use'], ['variationum', 'variations', 'variational', 'many', 'uses', 'may', 'involving', 'given'], ['variations', 'variation', 'number', 'elaborate', 'common', 'music', 'one', 'end', 'depends', 'upon']]
TOP TOKENS [['upskilling', 'competitive', 'upskill', 'achievable'], ['conclusion', 'upskilling'], ['upskilling', 'reskilling', 'training'], ['upskilling', 'upskilled', 'receive', 'reskilled', 'reskilling', 'drive', 'also', 'reskill', 'get'], ['upskilling', 'reskilling', 'cls', 'individuals', 'role'], ['upskilling', 'reskilling'], ['upskilling', 'upskill', 'furthermore', 'employees'], ['upskilling', 'reskilling', '“', 'make'], ['upskilling', 'reskilling', 'case', 'comes', 'one'], ['upskilling', 'reskilling', 'airdrop', 'currently', 'years', 'end', 'upskill', 'twenty', 'assistance', '“', 'allow', 'full'], ['roadkill', 'states', 'regularly', 'often', "roadkill's", "steve's", 'well', 'taking', 'cls', '2015', "dulcich's", 'views', 'since', 'mechanic'], ['2018', 'roadkill', '2000', 'british', '2005', 'wrestler', 'kill', 'film', 'series', '2006', 'american', '2020', 'professional', 'engerica', 'television'], ['giannattasio'], [], ['1', 'many', 'modes', 'animosity', 'rather', 'whose'], ['overkill', 'transformers', 'american', 'book', 'horrid'], ['tim'], ['took', 'joining', 'replaced', 'history', 'since', 'alongside', "band's", "di'anno's", '1981', 'guitarist', 'lead', 'features', 'cls', 'ammendola', 'f', 'falck'], ['able', 'form', 'unlocks', 'roadkill', 'given', 'obtains', 'storyline', 'launchers', 'improved', 'cls', 'upgrades', 'explosives', 'performs', 'cars', 'jobs', 'garages', 'missiles'], ['roadkill', 'cookbook', 'united', 'canada', 'areas', 'countries', 'apart', 'almost', 'diet', 'kill', 'well', 'also', 'cls', 'including']]
TOP TOKENS [['bit', 'aes', 'ciphers'], ['aes', 'cipher', 'ciphers', 'bit', 'des', 'use', 'version'], ['aes', 'used', 'individually', 'key', 'bit', 'bits'], ['bits', 'ciphers', 'cipher', 'block'], ['aes', 'bit', 'twofish', 'cipher', 'ciphers'], ['cipher', 'aes'], ['cipher', 'aes'], ['bit', 'rounds', 'key', '–'], ['aes', '128', 'size', 'bit', 'bits', '256', 'rounds', 'ciphers', '–'], ['aes', 'ciphers', 'standard'], ['aes', 'bits', 'cipher', '256', 'bit', '128', 'key', 'block'], ['bit', '256', 'aes', 'rounds', 'bits', '128'], ['aes', 'bit', 'uses', 'standard', '256', 'cipher', 'bits', 'represents', '128'], ['ciphers', 'tweakable', 'called', 'example'], ['aes', 'cipher', 'key', 'sizes', 'des', 'ciphers', 'size', '128', '256'], ['192', 'ciphers', 'aes', '128', '256', 'relatively', 'unsuitable', 'des', 'bits', 'known'], ['ciphers', 'cipher', 'block'], ['cipher', 'size', '128', 'bit', 'uses'], ['aes', 'uses', 'bit', 'terabytes', "openssl's", '128', '9007'], ['aes', 'ciphers', 'bits', '256', 'cipher', 'encryption', '×', "nist's", 'consequently']]

Processing features:  23%|██▎       | 23/98 [10:48<35:26, 28.35s/it]

getting sample prompt forgetting sample prompt for 23677
 23676
getting sample prompt for 23678
getting sample prompt for 23679
getting sample prompt for 23680
getting sample prompt for 23681
getting sample prompt for 23682
getting sample prompt for 23683
getting sample prompt for 23684
getting sample prompt for 23685
getting sample prompt for 23686
getting sample prompt for 23687
TOP TOKENS [['rstudio', 'r', 'rmd', 'rmarkdown'], ['r', 'rinruby', "require'rubygems'require'rinruby'there", 'using', 'integrating'], ['r', 'rstudio', 'installed', 'install'], ['rstudio', 'r', 'rmd', 'preferably'], ['r', 'rscf', 'name||rez', 'file'], ['r', 'rnotebooks', 'rstudio', 'rmarkdown'], ['r', 'rstudio', 'https://www.rstudio.com/products/rstudio/download', 'http://cran.us.r-project.org', 'install'], ['r', 'rprogramming', 'official'], ['r-studio', 'r', 'rstudio', 'language'], ['rrc', 'rab', 'rb', 'terms', 'rnc', 'srb', 'trb', "term'trb'used", 'cls'], ['r'], ['r'], ['rrac', 'r.r.a.c', 'racq', 'raozan', 'racc', 'rac', 'ramgati-ramdhan-abdul', 'raac', 'disambiguation'], ['r-ras', 'rras', 'ralgds'], [], [], [], ['r'], [], []]
TOP TOKENS [[], ['strain', 'electron-doped', 'camno3', 'thus'], ['machined', "really'modern'stuff", 'like', 'rifling', 'cases', 'refinement'], ['great', 'due', 'much', 'however', 'possible'], ['certain', 'base', 'duration'], ['–', 'obtained', 'respectively'], ['bytes'], ['amps', 'graph'], ['atomically', 'based'], ['2'], ['1990s'], ["ma's"], ['limited', 'still', 'animated', 'canadian', 'television', 'series', 'local', 'originally', 'richthofen', '2000-year-old', 'references', 'comically', 'set', 'kitzel', 'links', 'and/or', 'cast', 'max', 'person(s', 'boone', 'others', "ebert's", 'essentially', 'whose', 'typically', 'total'], ['black-and-white', "gtv's", 'english-language', 'original', 'see', 'references', 'well-known', 'series', 'television', 'aired', 'cup'], ['english-language', 'bbc', 'television'], [], [], ['television'], ['programming'], []]
TOP TOKENS [['glossary', 'mean', 'explains'], ['glossary', 'maximum', '’', 'absolutely', 'example', 'languages', 'given'], ['existing', 'glossary', 'click', 'right', 'use'], ['glossary', 'accepted', 'appears', 'built-in', 'activity', 'traditionally'], ['glossary', '“', 'every', 'terms', 'use', 'glossaries', 'specifically', 'means'], ['glossary', 'rather', 'etc'], ['glossary'], ['glossary', 'applications', 'contains', 'ontology<ref>r', 'within', 'certain', 'introduced', 'least', 'appears', 'includes'], ['glossary', 'contains', 'near-synonyms', 'within'], ['glossary'], ['provided', 'glossary', 'enables', 'useful', 'recent', 'sense', 'also', 'near-synonyms', 'glossarist.com', 'traditionally', 'appears'], ['glossary', 'wikipedia', 'glossaries', 'r'], ['glossary', 'southampton', 'glossaries'], ['p.g', 'market', 'mick', 'christianne', 'riverland', 'wales', 'glossop'], ['glossary', 'glossaries', 'r'], ['glossary', 'inclusive', 'f', 'e', 'glossaries'], ['glossary', 'r', 'corresponding', 'glossaries', 'l'], ['glossary', 'page', 'glossaries', 'l'], ['glossary', 'glossaries'], ['glossocardia']]
TOP TOKENS [['west', 'nile', 'west-nile-related', 'people', 'virus', 'rarely'], ['west', 'nile', '515', 'virus', 'b', '2004', 'dis', 'kramer'], ['west', 'nile', 'infected', 'virus'], ['west', 'nile', 'ag', 'ni'], ['west', 'nile', 'viral', 'fall'], ['west', 'nile', 'virus', 'usgs'], ['nile', 'west', 'virus'], ['west', 'nile', 'e', 'manifestations', 'virus', 'jr', 'h', '537', 'immunity', 'human', 'nat'], ['west', 'nile', 'causes', 'virus', 'take'], ['nile', 'west', 'virus'], ['nile', 'west', 'virus', 'year', '494', 'disease', '80'], ['nile', 'west', 'virus', 'cls', 'fever', 'encephalitis', 'causes', 'studies', 'electron', 'microscope'], ['west', 'nile', 'virus', 'range', 'subtype', 'sylvanus', 'america', 'infected', 'salinarius', 'urophasianus'], ['west', 'nile', 'fever', 'also', 'virus'], ['west', 'nile', 'virus', 'often'], ['west', 'nile', 'infection', 'virus', 'neuroinvasive', 'effects', 'control', '–', 'october', 'seasons', 'geographic', 'mosquito', 'delivery', 'region', 'infected', 'transmission', 'people', 'transplantation'], ['west', 'nile'], ['nile', 'west'], ['nile', 'west', 'virus', 'infection', 'daniels', '4095', 'mar', 'yu', 'wilton', 'dorsey'], ['nile', 'west', 'virus']]
TOP TOKENS [['well'], [], [], [], [], [], [], ['part', 'solely', 'well', 'software', 'documents', 'reports', 'made', 'analyses'], ['part', 'solely', 'well', 'software', 'documents', 'reports', 'made', 'analyses'], ['part', 'solely', 'well', 'software', 'documents', 'reports', 'made', 'analyses'], ['given', 'lines', 'otherwise', 'name', 'states', 'low', 'gives', 'sep', 'feet', '378'], ['x11'], ['moist', 'already', 'changed', 'natural', 'tropical', 'forests', '1999', 'pitcairnia', 'loss', 'name', 'bromeliaceae', 'ecuador'], [], ['ecuador', 'pitcairnia'], [], [], ['ecuador', 'none', 'subpopulations', 'known', 'habitat', 'area', 'hooveri', 'bromeliaceae'], [], ['almost', 'contains', 'apart', 'designated', 'ii', 'england', 'completely', 'grades', 'settlements', 'significant', 'interest', 'derbyshire']]
TOP TOKENS [['shale', 'among', 'thanks', 'suggest', '2020', 'aspect', 'development'], ['shale', 'cls'], ['shale', 'shales'], ['shale', 'gov', 'oil'], ['shale', 'shales', 'shale[change', 'vine', 'variable', '352', 'zangerl', '65'], ['shale', 'shales', 'gas', 'much', 'cls'], ['shales', 'shale', 'gas', 'coal', 'cls', 'formations'], ['shale'], ['shale', 'shales', "shales'are", 'vine', 'tourtelot', 'cls', 'variable'], ['shale', "shale's", 'place'], ['shale', 'shalë', 'shalës', 'shales'], ['shales', 'shale'], ['shale'], ['shale', 'shales'], ['shale', 'shalë', 'nicaj-shalë', 'municipality'], ['shale', '2000'], ['shale', 'shales', 'cls', 'gas'], ['shalë'], ['shale', 'oil', 'chemicals', "oil's"], ['shale', 'oil']]
TOP TOKENS [['yang', 'fief'], ['yangist', 'yangists', 'yangzhuxuepai', 'yangism', 'yang', 'individual', '楊', 'confucianism', 'egoism', 'obscurity', 'cls', 'chunqiu', 'zhuangzi'], ['yang', 'yangson', 'type', 'tree', 'name', 'also', 'model', 'purposes', 'submodules', 'example'], ['yang', 'wikimedia', 'index'], ['yang', 'emperor', '607', "yong's", 'luoyang', '楊'], ['yang', 'peppers', 'headache'], ['yang', 'yangzi', 'yangism', '楊', 'particular'], ['yang', 'yangson', 'type', 'interfaces', 'substatements', 'tries', 'model', 'python'], ['yang', 'zongdai', '’', 'destinies', '“', 'workers'], ['yang', 'zongdai', '’', 'destinies', '“', 'workers'], ['yang', 'yangyang', 'conductor'], ['yang', 'field', 'medalists', 'nanjing'], ['yang', '1st/2nd', 'players', 'olympics', '2006/2007'], ['yang', '小杨阳', 'medalists'], ['yang', "yang's", 'council'], ['yang', '2015', '2014', 'injury', '0', 'c', 'links', 'births', 'f', 'players', 'sohu'], ['yang', '2015', '2014', 'season', "men's", '19', 'chinese', 'zhenyu', 'plans', 'two', 'side', 'references', 'players', '28'], ['yang-style', 'yang', 'yangzhou', 'yo', 'wen-li'], ['yang', 'born', 'living'], ['yang', 'ming-yang', 'people', '2021', 'sportspeople', '2017']]
TOP TOKENS [['oakley', '1922', 'annie'], ['oakley', "oakley's", 'oakleys', 'annie', 'taker', 'image'], ['oakley', 'career', 'annie', '“', 'years'], ['oakley', "oakley's", '1910'], ['oakley', 'darke', 'annie', 'edge', '1901'], ['oakley', "oakley's", 'portrayed', 'america'], ['oakley', 'annie', 'darke', 'darning', 'put'], ['oakley', 'darke', 'annie'], ['oakley', '“', 'annie', 'darke'], ['oakley', 'annie'], ['oakley', 'william', 'born', 'internet', '1975'], ['oakley', "oakley's"], ['oakley', "oakley's", 'also', '2018', 'celebrities'], ['oakley'], ['oakley', 'guru-murthy', "pernice's", 'pernice', 'people'], ['oakley'], ['oakley', '2013', 'los'], ['oakley', 'november', '2019', '2020', 'released'], ['oakley', 'butetown', 'career', 'boys'], ['oakley', "oakley's", 'portrayed', 'president', 'annie']]
TOP TOKENS [['celesteela', 'literal', 'xurkitree', 'steel', 'pokemon', 'user', 'artificial', 'faceless', 'drain', 'seed', 'power', 'stylised', 'moveslot', 'something', 'ness', 'warhead', 'although', 'pretty', 'slam', 'roost', 'finally'], ['c12', 'd8', 'q1a', 'fdp2532', 'agnd', 'd44', '68uf', 'r36', 'sense', 'gnd', '0805', '1k', 'lowesr', 'd4', '25v', 'c49', 'c14', 'bzx85c16', 'c64'], ['columbia', 'corinne', 'nyc', 'girls', 'personal', 'details', 'small', 'memphis', '”', 'kaleidoscope', 'share', 'bacterial', 'evocative', 'thinking', 'also', 'specific', 'developing', 'example', 'collaborate', 'slowly', 'others', 'back', 'iteratively', 'fingernails', 'one', '“', 'everywhere', 'legos'], ['christensen', 'blockcities', 'agriculture', '’', 'built', 'forms', '2021', 'work', '”', 'metaverses', '—', 'still', 'soon', 'mind', 'something', 'solutions', 'assets', '“', 'earth', 'though'], ['celesteela', 'wicke', 'hiroshima', '“', '’', 'call', 'homeworld', 'hime', 'craters', 'traversing', 'rooted', 'arrive'], ['lowe', 'never', 'eke', 'used', 'little', 'already', 'well', 'together', 'barely', '’', 'every', 'know', 'abiding', 'existing', 'manage', 'dark', 'effect', 'high', 'yep', 'however', 'get'], ['concept', 'ecosystem', 'melissa', 'earthlike', 'core', 'knew', 'aquatic', "can't", 'currently', 'ghent', 'update', 'bacteria', 'benedikt', 'earth', 'based', 'photohererotrophic', 'like', 'food', 'ecosystems', 'put', 'though', 'well', "one's", 'one'], ['cuore-0', 'cuore', '2.57', '2014-08-01', 'obtained', '0.019', 'background-dominated'], ['awareness', 'moblie', 'geckoorient', 'sensor-fused', 'effective', 'filters', 'truly', 'enables', 'location', 'determining', 'identified', 'first', 'autonomous', 'physical', "robot's", 'creates', 'governed', 'created', 'presently', 'geckospio'], ['proximityone', 'acp', 'pages', 'publication', '364', 'methodologies', '7656', 'without', 'documents', '888', 'resources', 'solely', 'organizations', 'software', 'projections', 'well'], ['silva', 'robson', 'diego', 'antônio', 'moura', 'melissa', 'no-gi', 'leonardo', 'pelotas', 'kapincho', 'championship', 'world', 'jiu-jitsu', 'brazilian', 'association', 'career'], ['blue', 'overall', 'cleveland', '246th', 'backs', 'terrence', 'texas', 'players'], ['bills', 'columbus', 'hokies', 'ohio', 'colts', 'tenuta', 'indianapolis', 'tech', 'nicholas', 'round', '209th', 'overall', 'players', '25', 'football', 'bio', '2022', 'waived', 'nfl'], ['abilene', 'culbert', 'cornhuskers', 'backs', 'nebraska', 'narbonne', 'argonauts', 'realmajorculbert.com', 'gauchos', 'back', 'nebraska–lincoln', 'football'], ['aviators', 'rome', 'stripers', 'texas', 'pache', '258', 'minor', 'peoria', '255', 'league', 'chatham', 'pitch', 'langeliers', '498', 'professional', 'united', 'slashing', 'mlb', 'pandemic', '338', 'august', '343', 'braves', 'baylor', 'major', 'covid', '310', 'first', 'baseball', 'portland', 'player', '52', 'roster', 'season', 'game', 'two'], ['flyweight', 'external', '19', 'links', 'women', 'female', 'june', 'american', 'born', 'sportspeople', 'held', '1981'], ['cortlandt', 'january', 'female', 'american', '24', 'defensive', 'johannesburg', '1989', 'field', 'county', 'born'], ['field', 'gqeberha', 'pretoria', 'molikoe', 'state', 'never', 'squad', 'despite', 'family', 'matches', '21st-century'], ['nyone', 'traoré', 'operations', '64th', '2022', 'demobilization', 'doctrine', 'army', 'observer'], ["women's", 'academy', 'overall', 'three', 'joe', 'female', 'games', '268th', 'whl', 'columbia', 'pei', 'barclay', 'round', 'led', 'chloe', '2022–23', 'u15', 'program', '2021–22', '2023–24', '2022']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['accessions', 'cultivars', 'qtl', 'snp', 'accession', 'marker', 'per', 'snps', 'collection', 'landraces', 'markers', 'breeding'], ['agronomic', 'qtl', 'traits', '436', 'loci', 'genotypic'], ['cultivar', 'agronomic', 'genotypes', 'genotypic', 'traits', 'germplasm'], ['accessions', 'genotypic', 'homozygous', 'heterozygous', 'genotypes', 'loci', 'allelic', 'marker'], ['accessions', 'agronomically', 'germplasm', 'traits', 'genotypes', 'markers', 'cereals', 'snp', 'breeder', 'varietal', 'linked'], ['breeders', 'agronomically', 'qtl', 'traits', 'marker', '×', 'opportunity', 'grain', 'introgress', '1460'], ['accessions', 'rowed', 'trait', 'cereals', 'qtl', 'collection', 'marker'], ['germplasm', 'g', 'qtl', 'et', 'putatively', 'marker', 'loci', 'traits'], ['accessions', 'group', 'plant', 'markers', 'snp', 'barleys', 'qtl'], ['markers', 'inbred', 'traits', 'identify', 'qtl', '5', 'sunflower', '7', '4'], ['cultivar', 'breeders', 'legumes', 'trait', 'cycles', 'genotypes', 'qtl', 'breeding', 'crop', 'heterozygo', 'favorable', 'markers', 'estimated', 'created', '3130', 'crops', 'genotype'], ['inbred', 'crop', 'various', 'producing', 'reconstitution', 'breeding', 'introgressed', 'traits', 'yield', 'polygenically', 'heritability', 'plant', 'involving'], ['qtls', 'traits', 'qtl', 'shilin', 'plantarum', 'trait', 'genotyping', 'r', 'chen'], ['qtl', 'traits', 'genotypes', 'studies', 'inbred', 'population', 'selected', 'markers', 'interest', 'usda', 'range', 'study', 'genotyped'], ['cultivar', 'heterozygous'], ['cultivars', 'traits', 'introgression', 'trait', 'cultivated', 'desired', 'landrace', 'sp', 'major', 'chromosome', 'hence', 'addition', 'intergeneric', 'breeding', 'introgressed', 'segments', 'varieties', 'novel', 'haploid', 'incompatibilities', 'wheat', 'groupings', 'millet', 'f', 'many', 'retain', 'hybridize'], ['qtls', 'system', 'plant', 'line', 'g', 'mendelian', 'markers', 'breeding', 'ests', '879', 'booth', 'genomics', 'c', 'chromosomal', 'taylor', '874', 'newton', 'h', 'gene', 'p', '2000', 'fried'], ['cultivar', 'cultivated', 'cultivating', 'cultivation', 'create', 'produced', 'monophyletic', 'loci', 'domesticated', 'domestication', 'study', 'species', 'studied', 'developing'], ['inbred', 'cultivars', 'traits', 'produce', 'yield', 'making', 'production', 'yielding', 'realised', 'grain', 'heritability', 'trait', 'al', 'produced', 'heterosis', 'released'], ['qtls', 'traits', 'loci', 'trait', '2013', 'genetic', 'identification', 'associated', 'domestication', 'mm', 'quality', '2014', 'ss', 'yf', 'tuberosum', 'fan', '32', 'c', 'mendiburu', '2017']]
TOP TOKENS [['air', 'airwaves', 'noun', 'word'], ['air', 'importance'], ['air', 'right', 'altered', 'water', 'must', 'percentage', 'cls'], ['air', 'airplants', 'airvplant', 'several', 'scissors'], ['air', 'air-entraining', 'entrained'], ['air'], ['air', 'poor'], ['air-mazing', 'air'], ['air', 'aire'], ['air', 'airwaves', 'definition', 'midnight'], ['air', '1985', 'kym'], ['air', 'artnet.com', 'tuileries', 'jardin', 'women'], ['air', 'rivet'], ['air', 'airflow', 'pressurized', 'atmospheric'], ['aire', "l'aire", 'air', "aire-sur-l'adour", 'aïre', 'aire-la-ville', 'aire-sur-la-lys'], ['air'], ['air'], ['air'], ['air', 'appeared', '2017', 'people', '2013', '2018', 'sport', 'however', 'january', 'demand', 'later', 'november'], ['air', 'aircard', 'airh”card']]

Processing features:  24%|██▍       | 24/98 [11:16<34:50, 28.26s/it]

getting sample prompt forgetting sample prompt for 23689
 23688
getting sample prompt for 23690
getting sample prompt for 23691
getting sample prompt for 23692
getting sample prompt for 23693
getting sample prompt for 23694
getting sample prompt for 23695
getting sample prompt for 23696
getting sample prompt for 23697
getting sample prompt for 23698
getting sample prompt for 23699
TOP TOKENS [['manet', 'manet’s', 'forms', 'art', '1832', 'artist', 'way', '1865', 'expressively', 'times'], ['manet', "manet's", 'educated', 'marines', 'rather', 'although', 'well', 'louvre', 'realism'], ['manet', "manet's", 'paris', 'means', '23', 'redirected', 'nude', 'rather'], ['scenes', 'manet', 'studio', 'matter', 'lessons', 'men', '’', 'subject', 'october', 'brother'], ['manet', 'édouard', 'january', 'mb'], ['manet', 'friends', 'year', 'however', 'hand', 'honor', 'one', 'painted', 'past', 'years', 'cls', 'seems', '’'], ['manet', 'words', '’', 'reveal', 'took', 'hard'], ["manet's", 'manet', 'paris', 'picture', 'commune', 'among', 'shows', 'domestic', 'may', 'painted', 'dog', 'january', 'depicted'], ["manet's", 'manet', 'paris', 'picture', 'commune', 'among', 'shows', 'domestic', 'may', 'painted', 'dog', 'january', 'depicted'], ['manet', "manet's", '3', 'hail', 'context', 'veldzquez', 'later', 'wrote', 'offered', 'edouard', 'salon', 'wall'], ['painter'], [], [], ['mythology', 'manes', 'disambiguation'], ['manetas'], ['manesh'], ['1986', 'manek', 'surname'], ['mánes', 'manes', '1893–1989', '1934–1986', 'union', 'mane', 'borough'], ['england', 'maney'], []]
TOP TOKENS [['spectrum', 'spectral', 'spectra', 'latin', 'prism', 'spectrums', 'quantifiable'], ['spectrum', 'time', 'use', 'purposes', 'times', 'word'], ['spectrum', 'ideas', 'products', 'etc', 'definition'], ['spectrum', 'systems', 'spot', 'lives', 'study'], ['spectrum', 'communication', 'use', 'data', 'purposes', 'ground', "that's", 'nation', 'auctioned', 'whole', 'manage'], ['spectrum', 'gaming', 'release'], ['spectrum', 'page', 'program'], ['spectrum', 'said', 'students', 'keys', 'math', 'skills'], ['spectrum', 'worldwide', 'teachers', 'tests'], ['spectra', 'spectrum', 'mathematics', 'degree', 'n', 'categories', 'gives', 'general', 'category'], ['continuum', 'spectrum', "asperger's", 'topology', 'eigenvalues', 'pseudospectrum', 'sentence'], ['spectrum', 'spectrums', 'spectral', 'sinclair', 'us'], ['spectrum'], ['spectrum', '1991', 'computers'], ['spectrum', 'stick-insects', 'association', '1802', 'mcn', 'topology', 'journal', 'computer', 'spectra', 'rca', 'helmet', 'polyethylene'], ['spectrum'], ['spectrum', 'styler'], ['spectrum', 'links', 'external'], ['spectrum', 'software', 'texas'], ['spectrum', '1994', 'collegian', 'history', 'community', 'paper', 'newspaper']]
TOP TOKENS [['transgenic'], ['transgenic', 'make', 'introduced', 'plant', 'develop', 'crops', 'transgenes', 'plants', 'new'], ['transgenic', 'plants', 'developed', 'engineered'], ['transgenic', 'becomes'], ['transgenic', '‘transgenic’', 'plant', 'introduced'], ['transgenic', 'plants', 'grown', 'however', 'modified'], ['transgenic', 'technologies'], ['transgenic', 'plant', 'tr8nsgenic', 'plants', 'transform', 'developed'], ['transgenic', 'incorporating', 'plants', '2009', 'technology', 'new'], ['transgenic', 'many', 'recombinant', 'use', 'expressed', 'animals'], ['transgenic', 'transgenics', 'cisgenic', 'plants', 'subgenic', 'laboratory', 'made', 'exhibit'], ['transgenic', 'generation', 'produce', 'shoot', 'transferred', 'plants'], ['transgenics', 'transgenic', 'developed', 'transpose', 'cells', 'progeny', 'develop', 'stress', 'bodies', 'extent'], ['transgenic', 'transgenes', 'transgene', 'markedly', 'using', 'created', 'resembles', 'transplanted', 'fertility', 'better', 'recently', 'rats', 'conducted'], ['transgenic', 'transgenesis', 'introduced', 'produced', 'invasiveness', 'plants', 'incorporated', 'introduce', 'ability'], ['transgene', 'engineered', 'transformation', 'generated', 'produce', 'modified', 'yields', 'plant', 'plants', 'lines', 'bred', 'grow'], ['transgenic', 'transgenes', 'using', 'transgene', 'fish', 'increases', 'expressing', 'expressed', 'times', '100'], ['transgenic', 'specifically', 'exhibited', 'plants'], ['transgenic', 'plant', 'expressed', 'commercialized', 'transfer', 'inserted', 'created', 'resulting', 'inserting'], ['transgenic', 'expression', 'expansion', 'crops', 'introduction', 'surrounding', 'material', 'plant', 'mutagenesis', 'rewritten', 'transfer', 'endogenous', 'insertional', 'newly', 'high', 'reach', 'increase', '2']]
TOP TOKENS [['rss', 'feeds', 'many'], ['rss', 'http://www.ca7.uscourts.gov/fdocs/docs.fwx?submit=rss_ops', 'http://www.ca7.uscourts.gov/fdocs/docs.fwx?submit=rss_args', 'feeds'], ['rss', 'feeds'], ['rss', 'feeds'], ['rss'], ['rss'], ['rss'], ['rss', 'feeds'], ['rss', 'feeds'], ['rss', 'feed'], ['rss', 'eastern', 'formats', 'taoist', 'ibm', 't-cell'], ['rss', 'feeds', 'feed'], ['rss', 'feeds', 'feed', 'cls', 'march', "feed's"], ['rss'], ['rss', 'feed', 'feeds'], ['rss', 'use'], ['rss', 'feeds', 'feed'], ['rss', 'rss-dev', 'rss-0.90', 'rss-1.0', 'rss-reader', 'rss-0.91'], ['rss', "userland's", 'feeds'], ['rss', 'feed', 'feeds', 'aggregators']]
TOP TOKENS [['italians', 'italy', 'italian'], ['italy', 'italian', 'italia'], ['italians', 'italy', "chapels.'italians", "word'italy'what's", 'italian', "italy's", "italian'harlequin'by"], ['italy', 'italian', 'agriculture'], ['italy', 'italian', 'italians', 'french'], ['italy', 'italians', 'italian', 'sunday', 'time'], ['italy', 'italian'], ['italians', 'italy', 'italian', "italy's", 'italia', 'tours'], ['italy', 'italians', "italy's", 'italian'], ['italy', 'italian', 'italians'], ['italy', 'italian'], ['italian'], ['italy', 'external', 'country'], ['italy', 'italian'], ['italy'], ['italy', 'international'], ['italy', 'italians', 'italian', 'italia'], ['italians', 'italy', 'italian', 'italia', 'restaurants', 'sports', 'business'], ['italy', 'italian'], ["italy's", 'italy', 'italian']]
TOP TOKENS [['letter', 'recipient', '“', 'information', 'contact'], ['letter', 'cover', 'written'], ['letter', 'addressed', 'e'], ['letter', 'letters', "letter's", 'cover', 'writing', 'write'], ['letter', 'recipient', 'written', 'paragraphs', 'behalf'], ['letter', 'details', 'contact', 'writing', 'information', 'especially'], ['letters', 'letter', 'cover', 'paragraphs', 'covering'], ['letter', 'cover', 'letters', 'paragraphs', 'aligning'], ['letter', 'cover', 'letters'], ['recipient', 'letter', 'contacting'], ['letter', 'recipient', 'letters', "recipient's", "letter's", "sender's", 'subject', 'line', 'request', 'valediction', 'address', 'dear'], ['letter', 'written', 'letters', 'recipient', 'cover', 'covering', 'sender'], ['recipient', 'recipients', 'written', 'letter', 'letters', 'message'], ['letter', 'resignation', 'written', 'simply', 'then-president', 'receipt', 'response'], ['letter', 'letters', 'email', 'testimonials', 'headline', 'emails', 'page', 'unsolicited', 'customer', 'text', 'mail', 'customers', 'information', 'webpages', 'designed', 'cls', 'sends'], ['letter', 'letters', 'cosponsors', 'action', 'sent', 'members', 'matters', 'short', 'dear', 'including', 'transportation', 'disseminated'], ['letter', 'letters', 'written', 'response'], ['recipient', 'letter', 'letters', 'sender', 'addressed', 'subject', 'servant', 'person', 'members'], ['letter', 'letters', 'sales', 'customers', 'reply', 'write', 'design', 'nature', 'response'], ['letters', 'letter', 'engagement', 'provided', 'addressed', 'describe', 'realizable', 'rendered', 'used', 'nature']]
TOP TOKENS [['larvae', 'larva', '1', '6'], ['larvae', 'larval', "larva's", 'larva'], ['larvae', 'larva', 'larvas', 'larval'], ['larvae', 'larval', 'instar', 'larvaspa', 'stages', 'pupariating', 'second'], ['larvae', 'larva', 'instar', 'pupation', 'pupate', 'head'], ['larvae', 'instar', 'larvaspa', 'pupariating', 'second', 'stages'], ['larvae', 'larval'], ['larvae', 'larva', 'larval', 'instar', 'experimental', 'pupal', 'reared'], ['larvae', 'larval', 'larva', 'juvenile', 'juveniles', 'within'], ['larvae', 'larva', '‘'], ['larvae', 'larva', 'juvenile', 'computer-animated'], ['larvae', 'larval', "larva's", 'larva'], ['larvae', 'larva', 'larval', 'adults', 'dispersing'], ['larval', 'larvae', "as'pluteus'larvae", 'larva', "an'echinopluteus'larva", "a'bipinnaria'larva", "armed'brachiolaria'larva", "an'ophiopluteus'larva", 'new', 'juvenile', "cucumber's"], ['larvae', 'larva', 'larval', 'pupa', 'adult'], ['larvae', 'develop', 'instars'], ['larvae', 'larval', 'larva', 'puparium', 'pupal', 'pupa', '–'], ['larvae', 'pupate', 'pupae', 'larva', 'instars', 'pupal', 'hatching', 'development', 'maturation', 'heads', 'mature'], ['larva', 'larvae', 'pupate', 'mature', 'head', 'pupa', 'pupae'], ['larvae', 'larval', 'pupal', 'pupa', 'instar', 'development', 'hatching']]
TOP TOKENS [['monsanto', 'www', '04'], ['monsanto', '1920s', 'chemical', 'relations', 'pressing', 'better', 'self', 'cls'], ['monsanto', "monsanto's", 'included', 'like', '’', 'allows', 'even', 'ends'], ['monsanto', 'environment', 'handles', 'became', 'louis', 'presents', 'lawns', '’'], ['monsanto', 'world', 'knew'], ['monsanto', 'compiled', 'products', '’'], ['monsanto', 'mistakes', 'doubled'], ['monsanto', "monsanto's", 'eating', 'mislead'], ['monsanto', "monsanto's", 'monsantoblog'], ['monsanto', 'inhabitants', 'century', 'farmers', 'cancers', 'represents', 'biofuels'], ['monsanto', 'company'], ['monsanto', 'lightseekers', 'eduardo'], ['monsanto'], ['monsanto', 'g.d.r', '1', 'fifth', 'also', 'competes', 'pião', '2', 'currently'], ['monsanto', '1946', 'states', 'clocks', '1949', 'open', 'developed', '1954', '1970s', 'became', '1977', 'partnered'], ['monsanto', "monsanto's", 'revenue', 'patents', 'biotechnology', 'missouri', 'company', 'nascent'], ["monsanto's", 'monsanto', 'open', '1985', 'production', 'five', 'renamed', 'citing', 'scientists'], ['monsanto', '2015'], ["monsanto's", 'monsanto', 'products', 'violations', 'co'], ['monsanto', 'covered', 'sponsored', 'concelho', 'gualdim', 'government', 'even', 'later', 'abruptly', 'would', 'repopulated', 'granted', 'conquered']]
TOP TOKENS [['warfare', 'secret'], ['warfare', 'information', 'laws', 'adversaries'], ['warfare'], ['warfare', 'iw', 'term', 'enemy', 'world'], ['warfare', 'etc', 'wars', 'enemy'], ['warfare', 'cls', '“', 'environment'], ['warfare'], ['warfare', 'form', 'defined', 'enemy', 'cls', 'meted', 'world'], ['warfare', 'farms', 'world', 'century', 'techniques', 'actors'], ['warfare', 'cls', 'iw', 'war', 'ops', 'operations', 'information', 'dimension'], ['warfare', 'cls', 'iw', 'demoralize'], ['warfare', 'control', 'combat', "enemy's", 'centric', 'military', 'capabilities', 'ew'], ['warfare', 'world', 'combat', 'methods', 'era', 'war', 'theory', 'proceedings'], ['warfare', 'attacks', 'information', 'swarming', 'opponent', 'operations'], ['warfare', 'upon', 'sentry', 'control', 'premises', 'people', 'centric'], ['warfare', 'iw', 'personnel', 'c', "one's", 'military', 'subject', 'type', 'enemy', 'information', "actions.'they"], ['warfare', 'analysts', 'wars'], ['warfare'], ['warfare', 'hence', 'enemy', 'theory', 'military'], ['warfare', 'centric', 'information', 'war', 'world', 'adversaries', 'affairs', 'territory', 'techniques', 'identity', 'c4isr', 'disrupting', 'enemy', 'battlefield', "party's", 'realm', 'ability', 'includes']]
TOP TOKENS [['juliet', 'romeo'], ['juliet', 'romeo'], ['juliet', 'romeo', 'prorogued'], ['romeo', "juliet's", 'juliet'], ['juliet', 'romeo', "juliet's"], ['juliet', 'romeo'], ['romeo', 'juliet'], ['juliet', 'romeo', "romeo's"], ['juliet', 'romeo', 'story'], ['romeo', 'juliet', 'romeos'], ['romeo'], ['romeo'], ['juliet'], ['juliet', 'romeo'], ['romeo', 'juliet', 'julieta'], ['romeo', 'juliet', "juliet's", 'grigio', 'et'], ['romeo', 'juliet'], ['romeo', 'juliet', '1978'], ['romeo', 'italian'], ['romeo', 'juliet', "romeo's"]]
TOP TOKENS [['langley', 'people', 'cls', '1910'], ['langley', 'people', 'cls', '1910'], ["langley's", 'langley', 'fort'], ['langley', 'uss', 'tender', 'cls', '165', '6'], ['langley', 'cls'], ['langley', '1905'], ['langley', 'ii', '1927', 'february', 'continued', 'january', 'problems', 'fleet'], ['langley', 'fort', 'today'], ['langley', 'instruments', 'u', 'aerodromes', 'allegheny', 'may', 'aeronautical', 'aircraft'], ['langley', "langley's", 'successful', 'aloft', '1886', 'telescope'], ['langley'], ['langley', 'p', '6–8'], ['langley', 'c', 'hawaiian', 'census'], ['langley', 'mclean'], ['langley'], ['langley'], ['langley', 'langley—abbotsford', 'cloverdale—langley', 'rock—langley', 'langley—aldergrove', 'by-election', '6', '2004', 'act', 'election', 'rights'], ['langley', 'external', 'bibliography'], ['langley', 'historic'], ['langley', 'american']]
TOP TOKENS [['passive', 'voice'], ['“', 'passive', 'voice', '—', 'concerning'], ['passive'], ['passive'], ['passive', 'voice'], ['passive'], ['reputation', 'passive', 'voice'], ['however', 'passive', 'passive-voice', 'voice'], ['passive', 'sentence', 'voice'], ['writing', 'passive', 'used', 'voice'], ['passive', 'nonetheless', 'voice'], ['passive', 'voice'], ['passive', 'voice'], ['passive', 'voice'], ['passive', 'voice', 'passives', 'sentences', 'one', 'due'], ['passive', 'passives', 'voice', 'periphrastic', 'verb', 'voices', 'doer', 'castles', 'feature'], ['passive', 'voice', 'passives', 'active', 'straight'], ['passive', 'voice', 'passives', 'regarded', 'verb', "verb's", 'e', 'cut'], ['therefore', 'passive', 'voice', 'investigated', 'using'], ['passive', 'voice', 'passives', 'verb', 'sentences', 'imperatives', 'present', '13', '“', 'unk', 'verbs', 'notional']]

Processing features:  26%|██▌       | 25/98 [11:55<38:28, 31.63s/it]

getting sample prompt forgetting sample prompt for 23701
 23700
getting sample prompt for 23702
getting sample prompt for 23703
getting sample prompt for 23704
getting sample prompt for 23705
getting sample prompt for 23706
getting sample prompt for 23707
getting sample prompt for 23708
getting sample prompt for 23709
getting sample prompt for 23710
getting sample prompt for 23711
TOP TOKENS [['scaling', 'scale', 'understand', 'put', 'go'], ['scaling', 'procedure', 'need', 'comes'], ['scaling', 'done', 'scaler', 'procedure', 'one', 'regular', 'get', 'however', 'really'], ['scaling', 'scaling/cleaning'], ['scaling', 'performed', 'part', 'recommend'], ['scaling', 'typically', 'procedure', 'helps', 'tooth'], ['scaling'], ['scaling', 'goes'], ['scaling', 'successful'], ['scaling', 'scale', 'scalable', 'future', 'significantly', 'scalability', 'reduce', '“'], ['scaling', 'along', 'widom', 'scalability', 'e.g', 'extensive', 'ability'], ['scaling'], ['scaling', 'scaled', 'expanded', 'mainstreaming', 'development', 'scalability', 'reach'], ['scaling', 'scaled', 'built', 'scale', 'values', 'common', 'representation', 'extra', 'operations', 'multiplication'], ['scaled', 'high', 'methods', 'statistics', 'correlation', '25', 'alpha', 'higher', 'range', 'coefficient'], ['scaling', 'limit', 'ordinary'], ['scaling', 'rescaling', 'dimension', 'dimensions', 'scale', 'physics', 'expansion', 'including', 'lagrangian'], ['scaling', 'algorithms'], ['scaling', 'scale', 'feature', 'particular', 'max', 'another', 'processing', 'rescaling', 'rescale', 'nature', '200', 'cls', 'converges', 'pounds', 'apply', 'applied', 'one', 'much', 'normalization'], ['scaling', 'although']]
TOP TOKENS [[], ['đoc', 'đuoc', 'prussian', 'gia', 'khac', 'đanh', 'moltke', 'thi', 'one', 'comprises'], ['đoc', 'đanh', 'khac', 'moltke', 'prussian', 'đuoc', 'one', 'khong', 'comprises', 'thi'], [], ['ascendants', 'one', 'especially', 'many', '1889', 'particularly', 'carrying', 'also', 'tomatoes', 'toppings', 'pizza', 'reaction', 'people', 'naples', 'place'], ['đoc', 'prussian', 'gia', 'đuoc', 'đanh', 'one', 'moltke', 'khac', 'comprises', 'many'], ['pure', 'see', 'εὔτηκτος', 'eu', 'classical', 'unverified', 'pressure'], ['pizzas', 'dominos', 'pizza', 'one', 'toppings', 'defrosting'], ['spring', '3', 'esposito', 'however', 'europeans', 'century', 'little', 'naples', 'pizza', 'long', 'us', 'called', 'fish', '1889', 'centuries', 'flag'], ['spring', '3', 'esposito', 'however', 'europeans', 'century', 'little', 'naples', 'pizza', 'long', 'us', 'called', 'fish', '1889', 'centuries', 'flag'], ['last', 'pizzeria', 'ingredients', "that's", 'pizza', 'toppings', '1889', "pietro's", 'although', "esposito's", 'yet'], ['neapolitan', 'pizza', 'grandma', 'traced', 'rather', 'left', 'mainly', 'roots', 'generations', "pie's", 'despite'], ['pointing', 'undermining', "esposito's", 'later', '2', 'cast', 'pizza'], ['origus', 'panago', 'pizza', 'rossopomodoro'], ["other's", 'one', 'tangibly', 'different', 'see', '–', '1886', 'since', 'also', 'example', 'diagram'], ['pizza', 'zizzi', 'also', 'pizzaexpress', 'restaurants', "carluccio's"], ['max', 'called', 'philippe', 'kotipizza', 'dough', '107', 'factory', 'individual', 'pizza', 'three', 'pizzas', '4', 'franchisees', 'spui', '2000', 'also', 'result', 'years'], ['varieties', 'march', 'pizzerias', 'history', 'july', 'one', 'carolina'], ['1020354', '124', '1', '00377996'], ['sorbillo', "that's", 'pietro', "seaman's", 'although', 'casts', 'though']]
TOP TOKENS [['game', 'tackle', 'second', 'date', 'schedule', 'expect'], ['games', 'unexplainable', 'point', 'extra', 'exactly', 'win', 'points', 'seasons', 'end', 'high', 'uprights', 'touchdown'], ['games', 'pts', 'game', 'defense', 'season'], [], [], ['nearby', 'games', 'neville', 'touchdown'], ['region', 'state', 'secure', 'pervaded'], ['moved', 'within', 'place', 'search', 'find', 'nearly', 'much', 'region', 'could', '3', '’', '84', 'members', 'either', 'alaska'], ['game', '26', 'remainder', '1931', '1932', '1935', 'however', 'season', '1937', 'tie', '1939'], [], ['parts', 'stronghold', 'received', 'era', 'last', 'vote', 'surrounding', 'voted', '’', 'tisbury'], ['supported', 'margin', 'narrowly', 'broke', 'vote', "humphrey's", 'percent', 'hillsborough', 'strongest'], ['part', 'enclaves', 'region', 'neighboring', 'vote', 'thin', 'razor', 'northwestern', 'last', 'streak', 'voted', '2', 'home', '8', 'otherwise', 'voting', 'able', 'hampshire'], ['areas', 'last', 'suburbs', 'supported', '43', 'westernmost', 'vote', 'occasion', 'following', 'region', 'carry', 'scurry', 'support', '18'], ['areas', 'regions', 'area', 'majority', 'heavily', 'recent', 'carried', 'voted', 'relatively', 'last', 'remainder', 'borough', 'support', 'outer', '42', 'southern', 'census', 'ketchikan', 'anchorage', 'plurality', '0', 'incumbent', 'state', 'defections', 'percent', 'permitted', 'vote', '86', 'well', 'usual', 'little', 'remains', 'within'], ['forlorn', 'support', 'carrying', 'held', 'given', 'amongst'], ['needed', 'brandstater', 'sluggish', '172', 'yards', '284', '115', 'two', '1989', '1', '175', 'season', 'lonyae', 'passes', '143', '313', '–', 'game', 'moore', 'state', '91', 'bulldogs', 'touchdowns', '201', '29'], ['areas', 'heavily', 'relatively', 'base', 'support', 'badly'], ['buildings'], ['area', 'points', 'remain', 'garnett', 'strongly', '49', 'plurality', 'side', 'adjacent', 'time', 'portion', 'run', 'contains', 'however', 'significant']]
TOP TOKENS [['hall', 'fame', 'goals.the'], ['fame', 'hall'], ['fame', 'hall'], ['hall', 'fame', 'inducted', 'inductees', 'induction'], ['hall', 'fame', 'fields.the', 'inducted', 'world.the'], ['fame', 'hall', 'inductees', 'inducted', 'inductee', 'notable', 'inducting'], ['fame', 'hall'], ['fame', 'hall'], ['hall', 'fame', 'inductees'], ['hall', 'fame', 'halls'], ['hall', 'fame'], ['hall', 'fame', 'halls', 'inductees', 'inducted'], ['hall', 'fame'], ['hall', 'fame'], ['fame', 'hall', 'inducted', 'inductees', 'halls'], ["fame's", 'hall', 'fame', 'halls', 'inductees'], ['hall', 'fame', 'inducted', 'inductee'], ['hall', 'fame', 'inductees', 'inducted', 'halls'], ['fame', 'hall'], ['hall', 'fame', 'fames', 'inductees']]
TOP TOKENS [['vostok', 'lake', '“surface”'], ['vostok', "vostok's", "russia's", 'scientists', 'lake', 'quite', 'revealed', 'chance'], ['vostok', 'miles', 'lake', '400', '300', 'indicated'], ['vostok', 'lake', '3', 'want', 'withdraw', 'winter', 'fluid', 'antarctic'], ["vostok's", 'vostok', 'scientists', 'near', 'place', 'lake', 'across', 'icescape', 'estrange', 'drive', 'soften'], ['vostok', "vostok's", "russia's", 'fathom', 'icescape', 'quite', 'scientists', 'lake', 'chance', 'revealed', 'open'], ['vostok', 'nevertheless', 'lake'], ['vostok', 'around'], ['vostok', 'lake', 'around', '1988'], ['vostok', 'saturn', 'lake', '1996', 'mi', '50'], ['vostok', 'primorsky'], ['vostok', "district's"], ['vostok', 'primorsky', 'subglacial', 'opportunity', 'rover', 'motorcycles', 'uschod'], ['vostok', 'kirov', 'sharkansky', 'vostochinsky', 'yenotayevsky', 'khutor', 'krasnoyarsk', 'bigildinsky'], ['vostok', '623', '3', '770', 'lake', 'metres', 'although', 'page'], ['vostok', 'however', 'roughly', 'final', 'confirmation', 'lake', 'lakes', 'approximately', 'continuous', 'made', 'named'], ['vostok', 'searle', 'gottlieb', 'fabian', 'place-names'], ['vostok'], ['vostok', '1975', 'magnetometry', 'sheet', '1962', 'reliably', 'south', 'pole', 'mirny'], ['vostok', 'khabarovsk', 'history', 'mi-8t', '30', 'trading']]
TOP TOKENS [['cigars', 'cigar', 'e'], ['cigars', 'cigar'], ['cigars', 'cigar', 'tobacco', 'cls', 'way', 'filter', '5', 'marijuana'], ['cigar', 'cigars', 'cigarettes', 'smokers', 'tobacco', 'decrease', 'mucosa'], ['cigars', 'cigar', 'u', '–', '5'], ['cigar', 'cigars', 'tobacco', 'sense', 'market'], ['cigars', 'cigar', 'discoloured'], ['cigars', 'cigar', 'older', 'tobacco', 'u'], ['cigars', 'cigar', 'cigarettes', '1993', 'use', 'smokers', 'nonsmokers'], ['cigars', 'cigar', 'report'], ['cigar', '1928–2017', 'aviation', 'tobacco', 'run-up', '1990–2014', '1925–2013', 'horse'], ['cigars', 'cigar', 'cigarmaker', 'completed', 'hand', 'manufacturers', 'system', 'bunching'], ['cigars', 'cigar', 'cigarillo', 'cigarillos', 'tobacco'], ['cigar', 'cigars'], ['cigar', '2014', "cigar's", 'century', 'ranking', 'pregnant', 'horse'], ['cigars', 'cigar', 'tobacco', 'smoked', 'shape', 'smoke'], ['cigar', 'cigars', 'tobacco', 'aging', "was'the", 'production'], ['cigars', 'cigar', 'lit', 'nevertheless', 'claimed', 'smoker', 'sale'], ['cigar', 'cigars', 'run-up'], ['cigars', 'cigar']]
TOP TOKENS [['avatar', 'avatars', 'techopedia', 'two-dimensional', 'user', 'intelligence', 'worlds'], ['avatar', 'muds', '7', 'term', 'story', 'user', 'felt'], ['avatar', 'avatars', 'word', 'information', "that's"], ['avatar-the', 'avatar', 'avatars', '“avatar”', 'term', 'freeways'], ['avatar', 'avatars', '“', 'word', 'dealing', 'anything', 'friends'], ['avatar', 'technology', 'medium', 'descent', 'room', 'deity'], ['avatar', 'avatars', 'page', 'name', 'application', 'paint', '1993', 'reality', 'nearly', 'chatrooms'], ['avatar', 'avatars', 'ease'], ['avatar', 'avatars'], ['avatar', 'avatars', 'new', 'free'], ['avatar', '1979', 'history', 'groups', 'navigating', 'oubliette', 'illinois', 'player', 'develops', 'sides'], ['avatar', 'film', "cameron's", 'weapons', 'offering', 'enemies', 'cls', '2'], ['avatar', '7', 'robin', 'title', 'production', 'atkin', 'films', 'working', 'ui-hoon'], ['avatar', 'built', 'rlv-td', 'atmosphere', 'phase', "india's", 'launch', '98', 'bangalore'], ['avatars', 'avatar', 'inflation', "jake's", 'states', 'operator', "rda's"], ['avatar', 'avātar', 'romanized', 'also'], ['avatar', 'natives', '2010', 'cls', 'installment', 'attractions', "film's", '15', '2009', 'water'], ['avatar', '—', 'american', 'a.k.a', 'history', '18–23', 'cult', '26'], ['avatar', 'market', 'territories', 'weekends', 'dollars', 'billion', 'time', 'except', 'globe', 'set', 'kingdom', 'also', 'unadjusted', 'million', 'fastest-grossing'], ["avatar's", 'avatar', 'murder', 'person', 'vii', 'mondain', 'leaving', 'vague', 'set', 'survive', 'darkness']]
TOP TOKENS [['globe', '’', 'legislation', 'country'], ['legislation', 'regulation', 'legislations', 'place', '’', 'routines', 'nation', 'speaking', 'lawful'], ['nations', 'jurisdiction', 'legislation', 'regulation', 'countries'], ['legislation', 'britain', 'nations', 'nation', 'well'], ['lawful', 'realms', 'regulation', 'legislation', 'nation', 'nations', 'actions', 'britain'], ['legislations', 'legislation', 'politically', 'feeling', 'lawful', 'subconscious', 'place', 'male', 'globe'], ['legislation', 'directive', 'another', 'country', 'legislations', 'pass', 'shrewdness', 'one', 'expediency', 'followed', 'enacted', 'society', 'etc', 'activities'], ['legislation', 'cls', 'people', 'work', 'others', 'constitutional', 'well', 'lawful', 'jurisdiction'], ['pretrial', 'regulation', 'legislation', 'example', 'curriculum', 'subject', 'well', 'lawful', 'nations'], ['legislation', 'webster', '‘', 'enacted', 'law', 'word', 'merriam'], ['legislation', 'regulate', 'authorize', 'grant', 'sanction', 'member', 'small'], ['legislation', 'association', 'provincial', 'regulations', 'issues', 'prescribing', 'proclamations', 'furnishing', 'authorise', 'amend'], ['edict', 'west', 'auc', 'law', 'realm', 'edicts', 'coinage', 'rights', 'imperial', 'bridgeheads', "praetor's", 'restrictions', 'carta', 'julian', 'decree', 'neustria', 'c', 'cls', 'january', 'periodic', 'edictum', 'calendar', 'frankish', 'standardising', '709', 'document', 'bc', '313', 'charles', 'sanctioned', '129', '614', 'across', 'toleration', 'republic'], ['férussac', '1821', 'plegma', 'morelet'], ['legislation', 'control', '2', 'staff-written', 'states', '1', 'government', 'u.s', 'public', 'n.d'], ['lothringen', 'oil', 'cdz-gebiet', 'administrative', 'german', 'sms'], ['legislation', 'ubersicht', 'wirklicher', 'hypothekenverfassung', 'kriminalsachen', '12'], ['enacted', 'legislation', 'texts', 'authorization', '§', 'act', 'legal', 'decree', 'ordinances', 'commission', 'directives', 'ordonnances'], ['pagnona', 'municipality', 'delebio', 'casargo'], ['protection', 'rooted', 'legislation', 'standards', 'enacted', "pentagon's", 'example', 'regulation', 'permit', 'refused', 'provisions', 'brought', 'undid', 'day', 'activism', 'bodies', 'rather', 'adopt', 'litigation', 'force', 'cls', 'haley', 'allowing', 'circumvent', 'rights', 'global', 'civil']]
TOP TOKENS [['suicide', 'uncontroversial', 'suicidal', 'history', 'characterize', 'behavior', 'surrounding', 'raises', 'philosophers'], ['suicide', 'uncontroversial', 'suicidal', "suicide's", 'history', 'characterize', 'behavior', "person's", 'surrounding', 'raises', 'philosophers'], ['suicide', 'suicidal', 'suicides', 'research', 'present', 'behavior'], ['suicide', 'suicidal', 'accounts', 'commit', "one's"], ['suicide', 'suicides', 'suicidal', 'cls', 'approximately', 'america', '2002', 'behavior'], ['suicide', 'suicides', 'suicidal', 'among', 'cls', 'states', 'overall'], ['suicide', 'word', '“', 'describes', 'constitutes', 'say'], ['suicide', 'commit', 'addition'], ['suicide', 'abuse', 'may', 'suicidal', 'commit', 'behavior', 'committing', 'turn', 'people'], ['suicide', 'commit', 'suicidal', 'populations', 'higher'], ['suicide', 'album', 'book', 'wall', 'forest'], ['suicide'], ['suicide', 'suicidal', 'also', 'kill'], ['suicide', 'suicides', 'world', 'consider', 'cls', 'factors', 'times', 'firearms'], ['suicide', 'suicides', 'among', 'considered', '–', 'number', 'professionals', 'rate', 'suicidal', 'states', 'rates', 'yearly'], ['suicide', 'suicides', 'among', 'within', 'higher', 'states'], ['suicide', 'risk', 'predictor', 'suicidal', 'j', 'attempts', 'cognitions', 'ideation', 'treatment'], ['suicides', 'suicide', 'suicidal', 'similarly', '1994', 'considering', 'predicts'], ['suicidal', 'suicide', "person's", 'given', 'suicidology', 'crises'], ['suicide', 'suicides', 'suicidality', 'older', 'china', 'suicidal', 'attempt', 'attempted', 'harm']]
TOP TOKENS [['mortality', 'understanding', 'impact', 'improvements', 'relative', '2001'], ['mortality', 'gross', 'nonetheless', 'deaths'], ['mortality', 'higher', 'reduction', 'analyse', 'versa', 'individuals'], ['mortality', 'infant', 'factors', 'rate', 'three', 'expenditure', '2008', 'public', "2008'has"], ['mortality', 'provisional', 'gross'], ['mortality', 'influencing', 'causes', 'variation', 'area'], ['mortality', 'improvement', 'under-5', 'rate'], ['mortality', 'cause-specific', 'standardised', 'decreases', 'inequalities', 'rates', 'public'], ['mortality', 'determining', 'explaining', 'importance', 'differences', 'period', 'age-specific'], ['mortality', 'infant', 'additionally', 'death', 'current'], ['immortality', 'disambiguation', 'mortality', 'mortality/differential', 'book'], ['mortality', 'child', 'deaths', '1', 'followed', 'advances'], ['mortality', 'infant', 'child', 'reduction', 'births', 'rate'], ['mortality', 'single', 'even', 'nature', 'child', 'countries'], ['mortality', 'disability'], ['mortality', 'under-five', 'infant'], ['mortality', 'infant', 'under-five', '1,000', 'deaths'], ['mortality', 'deaths', 'overall', 'term'], ['mortality', 'child', '5', 'deaths', 'newborn', 'reduce'], ['mortality', 'group', 'under-five', '2018', 'bahamas']]
TOP TOKENS [['franchisee', 'franchisees', 'franchise', 'franchises', 'franchising', 'franchisor'], ['franchisee', 'franchise', 'franchisees', 'become', 'franchising', 'business'], ['franchise', 'franchisee'], ['franchisee', 'franchises', 'franchiser', 'franchise', 'franchisor'], ['franchisees', 'franchisee', 'franchise', 'franchiser', 'franchises', 'typical', 'franchisor', 'franchisors'], ['franchise', "franchisee's", 'franchisee', 'franchises', 'franchisees', 'franchisor', 'business'], ['franchisee', 'franchise', 'franchisees', 'franchisor', 'cls'], ['franchisee', 'franchise', 'franchisees', 'franchisor', 'cls'], ['franchisee', 'franchisees', 'franchise', 'incompetent', 'franchising'], ['franchisee', 'franchisees', 'franchise', "franchisee's", 'business'], ["franchisee's", 'franchisee', 'franchise', 'franchised', 'franchisor', 'franchising'], ['franchisees', 'franchisee', 'franchise', 'franchises', 'franchisor', 'costs'], ['franchise', 'franchisee', 'franchisees', 'franchisor', 'franchisors', 'franchising'], ['franchisees', 'franchises', 'franchisee', 'franchise', 'franchisor', 'franchisors', 'licensee'], ['franchisee', 'franchisees', 'franchises', 'franchise', 'franchisors', 'franchising'], ['franchisees', 'franchisee', 'franchises', 'franchise', 'franchisor', "franchise's"], ['franchise', 'franchisees', 'franchisee', 'franchises', 'franchising', 'franchisor', 'franchisors'], ['franchisee', 'franchises', 'franchise', 'franchisees', 'franchisor'], ['franchisees', 'franchise', 'franchisee', 'franchises', 'franchisor', 'franchisors', "cls]'franchise", 'franchising'], ['franchisee', 'franchisees', 'franchise', 'franchises', 'franchisors', 'franchising']]
TOP TOKENS [['luxury', '“', '”', 'second'], ['luxury', 'luxurious', 'luxuries', 'particularly'], ['luxury', 'luxurious', 'power', 'result', 'cls', 'expensive', 'luxurie', 'excess', 'example', 'exotic', '’', 'something'], ['luxury', 'conventional', 'talk'], ['luxury'], ['luxury', 'item'], ['luxury', 'luxuriousness', 'hand', 'extravagant', 'word', 'opulence'], ['luxury', '“', 'first', 'made', '”'], ['luxury', 'luxurious', 'item'], ['luxury', '‘', 'word', '’', 'onwards', 'excess', 'opulence', 'squandering'], ['luxury', 'pt', 'links', 'albums', 'external', 'journalist'], ['luxury', 'ball'], ['luxury'], ['luxury', 'luxurious', 'affluent', 'cities', 'unfavorable', 'true'], ['luxury', 'wealthy'], ['luxury', 'upscale'], ['luxury', 'expensive', 'absolute', 'good'], ['luxury'], ['luxury', "luxury's", 'called', 'work', 'album', '2008', 'cls'], ['luxury']]

Processing features:  27%|██▋       | 26/98 [12:25<37:15, 31.05s/it]

getting sample prompt forgetting sample prompt for 23713
 23712
getting sample prompt for 23714
getting sample prompt for 23715
getting sample prompt for 23716
getting sample prompt for 23717
getting sample prompt for 23718
getting sample prompt for 23719
getting sample prompt for 23720
getting sample prompt for 23721
getting sample prompt for 23722
getting sample prompt for 23723
TOP TOKENS [['strip', 'strips', 'stripping', 'place', 'strip-searched', 'median', 'two', 'marsals', 'discussions', 'thus', 'together'], ['strips', 'prairie', 'weekend', 'specialists', 'stands', 'spreading'], ['strip', 'flat', 'airfield', 'strips', 'draw', 'without', 'bare', 'relatively', 'stripped', 'right', "someone's", 'search', 'lay'], ['strips', 'strip', 'led', 'illumination'], ['strips', 'strip'], ['strip', 'groupwise', 'half-inch', 'edge', 'width', 'leather', 'new', 'hansing', '1'], ['strips', 'use', 'using'], ['strip', 'strips', 'outlet', 'needed', 'power'], ['http://www.opengroup.org/onlinepubs/007908799/xcu/strip.html', 'strip', 'systems'], ['strips', 'strip', 'need', 'stainless', 'provides', 'based', 'steel', 'length', 'purchasing', 'thinner', 'thicker', 'intended'], ['strip', 'limits', 'central'], ['strip', 'band/piece/strip', 'strips'], ['strip'], ['strips', 'strip', 'planning', 'term'], ['strip'], ['strip', 'striplights', 'overhead', 'striplight', 'board', 'spaced', 'evenly', 'general', 'schools', 'internal', 'separate', 'different'], ['strip', 'stripsearch', 'arcade', 'removal'], ['strip'], ['strip', '22'], ['strip']]
TOP TOKENS [[], [], [], [], ['77'], [], [], [], [], [], ['previously', 'currently', '8', 'viewed', 'present', 'billion', 'october', '23', 'cumulative', 'five', '2021', '7', '14', '20', 'two', '29', 'original', '13', '317', 'become', 'approximate', 'video', 'posted', '9', 'exceeded', 'july', 'november', 'views', 'list'], ['2012', '1973', 'notable', 'lakeland', 'florida', '–'], ['three', '1988', 'since', 'shannock', '8', '2016', '2020', '2001', '2009', 'exception', '1859', 'chief', 'notable', '1826', '1940', 'often', 'nominees'], [], ['2000–2001', '1997–1999', '1999', 'denver', '2000', 'st', 'alma', 'mater', 'draft'], ['company'], ['2010', 'april', 'eventual', '18', "viewed's", 'links', 'external', 'see', 'partial', 'australia', 'references', 'also'], ['november', 'week', 'successful', '26', 'number-one', 'billboard', 'hit', 'spent'], ['2017', '2021', 'e', 'u', 'perpetrator', 'notable', 'berry', 'people', 'recipient', 'access', 'official', 'webb', 'programs', 'war', 'well'], ['308', 'appointed']]
TOP TOKENS [['hayworth', 'heyworth', 'haworth', 'william', "physic'living"], ['walworth', 'atworth', 'thaworth', 'elsworth', 'bosworth', 'ainsworth', 'winworth', 'answorth'], ['elworth', 'ellsworth', 'ellsworths', 'ellisworth', 'ellesworth', 'elsworth', 'eleswurth', 'elisworth', 'caxton', 'rather'], ['halworth', 'haldeworth', 'holdworth', 'holdsworth', 'houldsworth', 'haldewrth', 'settlement'], ['cudworth', 'dworth', 'concept'], ['haworth'], ['haworth', 'hayworth', 'mahlon', 'ray', 'brothers', 'ron'], ['houseworth', "houseworth's", 'optometrist', 'plummeted'], ['edgeworth', "edgeworth's", 'edgeworthstown', 'read', 'later', 'oxfordshire', 'although'], ['edgeworth', "edgeworth's", 'warning', 'mr', 'would', 'activities', 'mathematics', 'keynes'], ['dilworth', "dilworth's"], ['aldworth', 'allworth', 'alworth'], ['edgworth', 'edgeworth', 'pennsylvania'], ['ashworth', 'african', 'lancashire'], ['haworth', "haworth's", 'hayworth'], ['allworth'], ['wedgeworth', '1934–2017'], ['longworth', 'england'], ['killingworth', 'killingsworth', 'england', '1699–1778'], ['killingworth', 'killingsworth']]
TOP TOKENS [['english', 'marching', 'pace', 'urdu', 'translations', 'example', 'literary', 'time', 'quotations', 'translation'], ['english', 'quotations', '1830s', 'translations', 'urdu', 'translation', 'decade', 'related', '1830', 'translate'], ['english', 'translations', 'decade', '1930s', 'quotations', 'example', 'urdu', 'help', 'it’s', 'would', 'take', 'possible', 'taken'], ['imposing', 'procession', 'verbal', 'advanced'], ['english', 'roman', 'urdu', "saint's"], ['kenyan'], ['english', 'translations', 'urdu', 'quotations', 'it’s', 'sentences', 'also', 'would', 'help'], ['working', 'work'], ['english', 'translations', 'urdu', 'quotations', 'improve', 'help', 'arousing', 'related', 'take', 'use', 'even', 'would'], [], ['moldovan'], ['uprising', 'occurred'], ['soviet', 'weightlifters', 'olympic', 'sportspeople'], [], [], [], ['olympic'], [], [], []]
TOP TOKENS [['oslo', 'world'], ["oslo's", 'oslo', 'oslofjord', 'areas', 'end', 'yard', 'eyesores', 'groruddalen', 'skiing', 'instead', 'sights'], ['oslo', "oslo's", 'oslofjord', 'world', "oslofjord's", 'winter', 'shape', 'ticket'], ['oslo', 'queue', 'sep', 'weapons'], ["oslo's", "later'oslo", 'oslo', 'oslofjord', 'osloregionen', 'integrated', 'region'], ['oslo', "oslo's"], ['oslo', 'sea', 'visit', 'playground', 'days', 'system', 'winter'], ['oslo', '“', '”', 'fact', 'accords'], ['oslo'], ['oslo', 'history', 'scandinavia', 'nightlife', 'population', 'beauty', 'ground', 'norway', 'iv', '1,000-year'], ['oslo', 'play', 'film', '2013', 'album', 'band', 'hackney', 'oslofjord'], ['oslo', '1902'], ['oslo'], ['oslo', 'oslo.skrika', 'oslos', '2013', 'karen.j.robins', 'u.s', 'appears', '2003', 'used', 'scream'], ['oslo', 'youngstorget', '2011'], ['oslo', 'oslofjord', 'fergene'], ['oslo'], ['oslo', 'references', 'shepstone', 'beach', 'present', 'facilities', 'including', 'however', 'mi'], ['oslo'], ['oslo']]
TOP TOKENS [['fawn', 'term', 'boxers'], ['fawns', 'fawn', 'euthanized', 'stays'], ['fawn', 'https://fawn.ifas.ufl.edu'], ['fawn', 'fawns'], ['fawn', "fawn's", 'fawns', 'wildlife'], ['fawn', 'fawns', 'little', 'bawling'], ['fawn', 'fawns', 'age', 'week', 'begins'], ['fawns', 'fawn', 'death'], ['fawns', 'fawn', '’', 'living'], ['fawn', 'fawns'], ['fawn'], ['fawn'], ['fawn', 'material'], ['fawn'], ['fawn', 'term'], ['brawn'], ['ewnetwork', 'ewn'], ["fawn's", 'fawn', 'work', '1976', "woman's", 'paperback'], ['fawn', '1865', 'uss', 'also'], ['fawn', 'find', 'turns', '5:02', 'well']]
TOP TOKENS [['web'], ['web', 'darknet', '’', 'dives'], ['web', 'short', 'web’s', 'news', 'ultimately'], ['web'], ['web'], ['web', 'dark'], ['web', "web's", 'darknet', 'darkweb'], ['web', 'someone'], ['web', 'dark', 'darknet'], ['web', 'vs', '’'], ['web', 'freenet'], ['web', 'darknet', 'dark', 'tor', 'deep', 'additionally'], ['web', 'darknet', 'dark', 'engine', "web'synonymously"], ['web', 'darknet'], ['web', "web'to", 'dark', 'darknet'], ['web'], ['web', 'dark', 'darknet', 'darknets', 'individuals', 'markets', 'ebay', 'became', 'widely', 'cannabis', 'anonymized', 'via'], ['web', "web'to", 'dark', 'darknet', "surfing'dark"], ['web', 'dark'], ['darknet', 'net', "darknet's", 'dark', 'bypassing', 'equated', 'darknets', 'cryptoanarchists', 'circumventing', 'described']]
TOP TOKENS [['virgil', "virgil's", '”', 'studious'], ['virgil', '”', '’'], ['virgil', "virgil's", 'b', "poems'and'selections"], ['virgil', "virgil's", 'b', "poems'and'selections"], ['virgil’s', 'virgil', 'society'], ['virgil', "virgil's", 'virgilianae', 'virgilio', 'ages', 'containing', 'ii', "octavian's", 'romanus'], ['virgil', 'cls', 'gaul', 'peace', 'also'], ['virgil', 'borneo', 'nonsense', 'others', 'administration'], ['virgil', 'virgile', 'virgilian', 'home', '’'], ['virgil', 'cls', 'rome', 'particular', 'aeneid', '’', 'underworld', 'author'], ['virgil', 'virgilius', 'american'], ['virgil', "virgil's'i", 'behind', 'sure'], ['virgil', "virgil's", 'cls', 'walkers'], ['virgil'], ["virgil's", 'virgil', 'paintings'], ['virgil', 'career', 'ended', 'phoenix', 'san', 'people'], ['virgil'], ['virgil', "virgil's", 'trustworthy', 'virgilius', 'fragments'], ['virgil', 'states'], ['virgil', "virgil's", 'virgilian']]
TOP TOKENS [['deep', 'cassia', 'brown', 'seed'], ['cassus', 'cassis', 'cassius', 'cassia', 'warriors', 'gaius', '‘', 'hollow'], ['cassava', 'marketplaces', 'influence', 'reside', 'black'], ['color', 'cassia', 'leaves', 'white', 'verum', 'c', 'infusion', 'brown', 'areas', 'grown', 'growing', 'however'], ['cassius', 'cassianus', 'cassian', 'calendar', 'revenge', 'turned', 'inflicted', 'death', 'saint', 'martyrdom'], ['cassava', 'communities'], ['cassava', '5.3', 'utilissima', '5.6', 'cent', '13.86', 'extract', 'per', 'large', 'particularly', 'processed', 'yields', '65.7', '1.6'], ['cassava', 'dried', 'potatoes', 'goods', 'world', 'level'], ['plant', 'cassia', 'belongs', 'druggists', 'known'], ['cassava', 'dried', 'flour'], ['surname', 'casso', 'cássio', 'cashio'], ['cassius', 'bc', '1998'], ['loureiroi', 'cassia', 'carao', 'cassiane', 'sicklepod', 'trees', 'disambiguation', 'cinnamon'], ['1924–2014', '1932-1979', '1959', 'cassian', '350'], ['cassis', 'davis', 'cassi'], ['1588–1657', 'disambiguation', 'cassiano', 'apulia', 'producer', '1971'], ['1962–2001'], ['casserly', 'family', 'politician', 'school'], ['cassio', 'disambiguation'], ['disambiguation', 'cassia']]
TOP TOKENS [['ice', 'sheet', 'antarctic', 'crevasses'], ['sheet', 'ice', 'eais', 'antarctic', 'wais', 'much', 'west', 'level', 'glaciological', 'substantial'], ['ice', 'sheet', 'antarctic', 'parts', 'meets', 'isostatic', '36', '1958', '24'], ['sheet', 'ice', 'antarctic', 'unclear', '1958', 'bed'], ['sheet', 'ice', 'antarctic', 'map'], ['sheet', 'ice', 'antarctic', 'crevasses', 'lies'], ['ice', 'sheet', 'antarctic', 'al', 'glaciological', 'contribution', 'shelf', 'west', 'elucidated', 'et', 'margin', '2017', 'thinning', 'work'], ['sheet', 'ice', 'sheets', 'antarctic', 'beneath', 'assess', 'significant', 'along', 'oscillations'], ['sheet', 'ice', 'wais', 'reconstruct'], ['ice', 'sheet', 'wais', 'antarctic', 'perturbations', 'around', 'woodward', 'manifested', 'divide', 'm.j', 'smith'], ['sheet', 'sheets', 'ice', "greenland's", 'bed', 'work', 'estimated'], ['sheet', 'ice', 'reaches', 'antarctic', 'reanalyzed', 'outward', 'flow'], ['sheet', 'ice', '166°e', '65°w', 'amundsen', '136°w', '75°w', '155°w', '15', 'antarctic', 'troughs', "103°24'–", '103°w'], ['ice', 'sheet', 'analysis', 'antarctic', 'meets', 'isostatic', '1958'], ['sheets', 'sheet', 'ice', 'glaciology', 'protrude', 'conduits', 'limited', 'scope', 'overlying'], ['sheets', 'sheet', 'ice', 'antarctic', 'also', 'edge', 'programs', 'lubrication', 'west', 'entire', 'clips', 'list', 'multidisciplinary', '–'], ['sheet', 'ice', 'antarctica', 'antarctic', 'rise', 'peninsula', 'flow', 'recorded', 'displace', 'atop', 'west', 'embayment', 'longer'], ['sheets', 'ice', 'sheet', 'laurentide', 'geology', 'survey', 'glaciology'], ['sheet', 'ice', 'glaciology', 'sheets', 'channels', 'rapidly', 'cap', 'antarctic', 'glaciation', 'patagonian', 'periphery', 'flowing'], ['ice', 'sheet', 'antarctic', 'glaciologist', 'west', 'glaciological']]
TOP TOKENS [['metamaterials', 'metamaterial'], ['metamaterials', 'metamaterial'], ['metamaterials', 'metamaterial-based'], ['metamaterials', 'metamaterial', 'nanomaterials'], ['metamaterials', 'metamaterial', 'similarly'], ['metamaterial', 'metamaterials'], ['metamaterial', 'metamaterials', '’', 'light', 'materials'], ['metamaterials', 'metamaterial'], ['metamaterials', 'metamaterial', 'radiation'], ['metamaterials', 'metamaterial-based', 'metamaterial'], ['metamaterials', 'metamaterial'], ['metamaterials', 'metamaterial'], ['metamaterials'], ['metamaterials', 'metamaterial'], ['metamaterial', 'metamaterials'], ['metamaterials', 'metamaterial'], ['immaterial', 'immaterialism'], ['metamaterials', 'metamaterial'], ['metamaterials', 'metamaterial'], ['metamaterial', 'metamaterials', "metamaterials'negative"]]
TOP TOKENS [['pronouns', 'pronoun', 'cls'], ['pronouns', 'pronoun', "pronoun's"], ['pronouns', 'pronoun', 'cls'], ['pronouns', 'pronoun?define', 'pronoun', 'use'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun', 'pronounstypes'], ['pronouns', 'cls', 'pronoun', 'pronominal'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun', 'cls'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun'], ['pronouns', 'pronoun', 'english'], ['pronouns', 'pronoun', 'sentences', 'g', 'person'], ['pronouns', 'pronoun', 'person', 'pronominal', 'personal'], ['pronouns', 'pronoun', 'ought', 'personal', 'english', 'person', "l'aime'he"], ['pronouns', 'pronoun', 'person', 'subject'], ['pronouns', 'pronoun', 'person', 'several', 'cls'], ['pronouns', "pronoun'replaces'it", 'pronoun', 'sentence', 'sentences']]

Processing features:  28%|██▊       | 27/98 [12:52<35:21, 29.89s/it]

getting sample prompt forgetting sample prompt for 23725
 23724
getting sample prompt for 23726
getting sample prompt for 23727
getting sample prompt for 23728
getting sample prompt for 23729
getting sample prompt for 23730
getting sample prompt for 23731
getting sample prompt for 23732
getting sample prompt for 23733
getting sample prompt for 23734
getting sample prompt for 23735
TOP TOKENS [['tuck', 'tuckle', 'tuckling', 'tuckled', 'tuckles'], ['tuck', 'tuckle', 'tuckling', 'tuckled', 'tuckles'], ['tuckpointing', 'condition', 'new', 'orginal', 'hundreds'], ["tuck's", 'tuck', 'look', 'pakistan', 'shop', 'term', 'tucker', 'famous', 'food', 'british'], ['tuckpointing', 'tuckpointer', '“', 'means', 'tuck', 'term', 'uniform', 'real', 'one', 'whatever', 'bricks'], ['tuckpointing', 'tuckpointed', 'tuck', 'joints', 'brickwork', "faq's", 'term', 'cls', 'facts'], ['tuckpointing', 'tuckpointed', 'tuck', 'joints', 'brickwork', "faq's", 'term', 'cls', 'facts'], ['tuckpointing', 'tuck', 'tuckpoint', 'obtained', 'putty', 'home', 'called', 'unfilled', 'unrubbed', 'superimposed', 'colour'], ['tuckpointing', 'tuck', 'joints', 'damage', 'proper', 'cls', '“', 'walls', 'term', 'also', 'poor', 'called', 'integrity'], ['tuckpointing', 'bricks', 'colour', 'cls', 'historically', 'requires', 'succeed', 'skill'], ['tuck', 'tucking', "hood's", 'tucks', 'place'], ['tuck'], ['tuck', 'arizona', 'life', 'w'], ['tuck'], ['tuck', 'pinkney'], ['tučkovo', 'people'], ['tuck'], ['tuck'], [], ['tuck', 'photographs', 'hung', '1900–1999', 'life', 'died']]
TOP TOKENS [['usenet', "spaf's", 'spafford', 'mostly', 'mind', 'https', 'somewhat', 'redirect', 'administration', 'excrement', 'paradoxically', 'beginnings'], ['wordnet', "wordnet's", 'wordnets', 'eurowordnet', 'called', 'online', 'gpl', 'accessing', 'upon'], ['behaviournet', 'communication', 'agency', 'agencies', 'deliverables', 'valuable', 'thoughts', 'roll', 'involved', 'support', 'interest', 'project', 'world', 'phase', 'challenging', 'collect', '1', '’', 'complements', 'turn', 'concept'], ['wordnet', "wordnet's", 'wordnet®', 'browser', 'langone', 'available', 'download'], ['imagenets'], ['wordnet(r', 'http://wordnet.rkbexplorer.com', 'wordnet', 'gmail.com'], ['wordnet(r', 'http://wordnet.rkbexplorer.com', 'wordnet', 'gmail.com'], ['mainnet', 'testnet', '4', 'market', '5'], ['wordnet', 'wordnet®', 'copyrights', 'software', 'language', 'implied'], ['usenet', 'priviliges'], ['monnet', 'teaching', 'ecsc', 'mont-sur-monnet', 'c.s.sp', 'impresario', 'lorbeau', 'hockey', 'theatre', '1766–1819'], ['disambiguation', 'kennet', 'american'], ['geonet'], ['fournet', '1913–2008', '1752–1834', 'fournet-fayard', 'honor', 'department', 'officer', 'fournets-luisans', 'bourgogne-franche-comté'], ['scinet'], ['sportsnet', 'snet', 'america'], [], ['disambiguation', 'ticket', 'terrain', 'carnet', 'ifmga', 'services'], ['u.s', 'bennet', 'band'], ['sportnet.hr', 'sportnet', 'sportsnet', 'comcast']]
TOP TOKENS [['physicalism', 'materialism', 'reduced'], ['“racialism”', 'racialism', 'activity', 'criminal', 'inherently', 'worse', 'many', 'races', 'mean', 'different'], ['regionalism(redirected', 'regionalism', 'and/or'], ['meaning', 'humanism', 'point', 'article', 'republicanism', 'wikipedia', 'rituals'], ['materialism', 'potency', 'mind', '01', 'values', 'materialists', 'sensations', 'materia', 'democritis', 'upon', '08'], ['spirit', 'capabilities', '“humanism', 'lives', 'humanism'], ['materialism', 'physicalism', 'c', 'references[change', 'substance', 'materialists', 'spirit', '1995', 'materialist', 'friedrich'], ['materialism', 'physicalism', 'seems', '”', 'materialist', 'manifestation', 'therefore', 'used', 'postulates', 'order', 'substances', 'english'], ['materialism', 'materialists', 'existence', 'things'], ['materialism', 'physicalism', 'extend', 'important', 'entirely', 'materialists', 'substance', '1995', 'materialist', 'prometheus', 'c', 'york', 'new'], ['value', 'introduced', 'energy', 'history', 'materialism', 'theory', 'trungpa', 'combination', 'dialectical'], ['song'], ['urbanism'], ['internationalism', 'morality', 'cosmopolitanism', 'linguistics', 'relations', 'style', 'translingually'], ['exists', 'truly'], ['mxpx', 'americanism', 'pro-americanism'], ['pragmatism', 'education', 'beliefs', 'sarkar', 'humanism'], ['2019'], ['france', 'inclination', 'nations', 'states', 'century', 'espiritismo', 'forms'], ['end', 'disambiguation', 'thought', 'term', 'position', 'supremacy', 'libertinism']]
TOP TOKENS [['sugar', 'syrup', 'profile', 'various', 'use', 'resulting', "syrup's", 'weight', 'need', 'ways', 'types', 'syrups', 'approx', 'materials', 'derived'], ['alternative', 'syrup', 'beverages', 'drinks', 'products', 'marinades', 'moreover', 'recipes', 'sources', 'varioa', 'tapioca', 'maple', 'corn', 'vitamins'], ['traditional', '1850s', 'sugar', 'syrup', 'cool', 'demulcents', "children's", 'u.s', 'together', 'byproduct'], ['syrup', 'corn', 'increases', 'fudge', 'well'], ['syrup', 'freshness', 'sweetness', 'corn', 'sweeteners'], ['syrup', 'freshness', 'sweetness', 'corn', 'sweeteners'], ['syrup', 'freshness', 'sweetness', 'corn', 'sweeteners'], ['syrup', 'taste', 'easy', 'syrups', 'sugars', 'cls', '1', 'achieved', 'perpetuated', 'months'], ['syrups', 'syrup', 'peculiarities', 'sucrose', 'thickeners', 'ingredients', 'pharmacy', 'sep', 'one'], ['bacteria', 'syrup', 'confectioners', 'oligosaccharides', 'compound', 'grade', 'sugar', 'german', 'flavor', 'corn', 'due', 'depending', 'pressure', '1812', 'food', 'general', 'currently'], ['film', 'crystals', '1881–1945', '3-6', 'sugars', 'cough'], ['molasses', 'phosphate', 'water', 'crystals', 'syrups', 'syrup', 'notable', 'fruit', 'groups', 'sugars', 'cough', 'sweetened', 'sugar', 'unrefined', 'barley', 'eastern', 'savory', 'middle', 'carbonated'], ['drizzled', 'syrup', 'use', 'milkshake', 'item', 'cakes', 'chocolate', 'drizzling', 'nesquik', '60', '1890s', 'syrups', 'clothing', 'artistic', 'toppings', 'xanthan', 'cream', 'needs', 'colic'], ['syrup', 'type', 'groups', 'syrups', 'flavored', 'molasses', 'water', 'instance', 'superior', "syrups'aromatics", 'range', 'following', 'containing', 'corn', 'crystals'], ['bacteria', 'syrup', '1811', 'grade', 'flavor', 'gottlieb', 'oligosaccharides', 'corn', 'tapioca', 'dilute', 'kirchhoff', 'food'], ['syrup', 'syrups', 'simple', 'flavored', 'maple', 'chocolate', 'heated', 'bludwine', 'flavors'], ['preservatives', 'table', 'syrups', 'capitalize', 'syrup', 'maple', 'flavoring', 'pure', 'areas', 'sorghum'], ['syrup', 'instance', 'life', "syrups'aromatics", 'syrups', 'consists', 'beet', 'fermentation', 'type', 'list', 'example', 'oxygen', 'sugar', 'gum', 'japan', 'sap', 'maple'], ['sep', 'syrup', 'maple', 'cuisine', 'flavors', 'table', 'price', 'american'], ['sep', 'syrup', "butterworth's", 'chocolate', 'inc', "steen's", 'cane', 'packaged']]
TOP TOKENS [[], [], ['changed', 'exhausted', 'resembling', 'football', 'swear', 'us', 'shouted', '”', 'hissed', 'swelled', '–', 'celsius', 'without', 'also', 'kind', 'though', 'seemed', 'head', 'something', 'turning', 'moving', 'yet', 'rounds', 'anxiety', 'became', 'halo', 'emerge', 'general', 'directions', 'got', 'vehicle', 'location', 'hot', 'going'], [], ['horizon', 'reversing', 'point', 'normal'], [], [], ['marcha', 'come'], ['france', 'jacinto', 'england'], [], ['andrews', 'slipknot', 'american', 'including', 'singles', 'u.s'], ['broadway', "band's", 'guns', 'lynch', 'osbourne', 'celebrity', 'took'], [], ['written', 'tv', 'relief', "cleopatra's", 'well', 'cook', 'together'], ['aftermath', 'reynolds', 'immediately', 'well', 'vettese', 'honesty', 'wells', "alex's", 'introduction', 'written', 'europe', 'hewerdine', 'musicians', 'music', 'also', 'since', 'artists', 'songs', 'career', "christie's", 'went'], [], [], ['composed', 'arnelas', 'wrote', 'co', 'contest', 'tangen', 'angels', 'songs', 'thus', "georgia's", 'germany'], ['co', 'music', 'series', 'wrote', 'songwriter', 'writing', 'rockers', 'wildside', 'fellatio', 'known', 'performer', 'whitlams', 'better', 'made', 'word', 'well', 'cls', 'independent', 'also', 'album', 'ford', '2005', 'went', 'include'], []]
TOP TOKENS [['janmashtami', 'krishna', 'thus', 'elderly', 'texts', 'name', 'janma', 'playfulness', 'birth', 'devaki', '’', 'gitagovinda', 'zeal', 'ashtami', 'people'], ['janmashtami', 'significancejanmashtami', 'cls', 'krishna', 'however', 'e', 'anniversary'], ['janmashtami', 'krishna', 'cls', 'family', 'form', 'milk', 'midnight', 'many', 'aatham', 'also', 'rohini', 'year'], ['janmashtami', 'janmashtmi', 'handis', 'cls', 'known', 'krishna', 'one', 'rocked', 'milk', 'celebrations', 'sometimes', 'boys', 'gopis', 'part', 'temple', 'perfomed', 'fasting', 'day', "hindusim's", 'butter'], ['janmashtami', 'cls', 'year', "mathura's", 'vishnu', 'evil', 'pradesh', 'order', 'take', 'overlaps', 'vasudeva'], ['janmashtami', 'cls', 'year', "mathura's", 'vishnu', 'evil', 'pradesh', 'order', 'take', 'overlaps', 'vasudeva'], ['janmashtami', 'celebrated', 'krishna’s', 'borned', 'celebrate', 'incarnations', '3', 'events', 'arti', 'onwards', 'songs', '4:30pm', 'vasudev', '2', 'pujas', 'cradles'], ['janmashtami', 'cls', "krishna's", 'bhagavad', 'yet', 'krishna', "sister's", "devaki's", 'vasudeva', 'month', "kansa's"], ['janmashtami', 'place', 'cls', 'krishna', '’', 'celebration', 'mother', 'dark', 'fast', 'lord', 'simply', 'krishnashtami', '‘', 'sometimes', 'vasudeva', 'following', 'aatham', 'rohini', 'also', 'universe', 'one'], ['janmashtami', '“janmashtami”', 'yuga', 'ghee', 'fruits', 'krishna', 'krishna’s', 'leela”', 'https://creativecommons.org/licenses/by-sa/3.0', 'along', 'midnight', 'sugar'], [], ['janmashtami', 'region', 'feats', 'tradition', 'retreating', 'states', 'e', 'recalled', 'pradesh'], [], [], [], ['many', 'births', 'also'], [], ['janmashtami', 'krishnashtami', "krishna's", 'cls', 'thus', 'avatars', 'certain', 'festival', 'krishna'], [], []]
TOP TOKENS [['pemphigus', 'pemphigoid'], ['pemphigus', 'pemphigus(redirected'], ['pemphigus'], ['pemphigus'], ['pemphigus', 'past'], ['pemphigus', 'pemphigoid', 'one'], ['pemphigus', 'pemphigusˈpɛm'], ['pemphigus'], ['pemphigus', 'effects', 'lesions'], ['pemphigus', 'effects', 'lesions'], ['pemphigus', 'pemphix', 'cls'], ['pemphigoid', 'pemphigus'], ['pemphigus', 'pemphix', 'cls', '1998', 'pathophysiology', 'corticosteroids'], ['pemphigus'], ['pemphigoid', 'bullous', 'bulbous'], ['pemphigus', 'affected', 'immunosuppressant'], ['pemphigus'], ['pemphigus', 'formicetorum', 'monophagus'], ['pemphigus', 'treat', 'treated', 'intraepidermal'], ['pemphigus', '14', '000', 'disease', 'simllarly', 'mofetil', 'p', 'prevalent', '1', 'vulgaris']]
TOP TOKENS [['dormant', 'dormants', 'go', 'becoming', 'might', 'dormancy', 'state', 'usually', 'mean', 'obvious', 'occur', 'plants', 'plant'], ['dormant', 'dormant/delayed', 'delayed-dormant', 'stage'], ['dormantcategorized'], ['dormant', 'pruning', 'pruned', 'trees', 'diseases', 'reasons', 'plenty'], ['dormant'], ['dormant', 'largely', 'essentially', 'often', 'become', 'go', 'lay', 'becomes'], ['dormant', 'cause', 'dormancy', 'also', 'bud', 'mean', 'buds', 'state'], ['dormant', 'local', 'aphids', 'sprays', 'needed', 'spray'], ['dormant', 'different', 'nearly', 'seeds', 'dormancy', 'seed', '2000', 'less', 'cls', 'suffering', 'germinate'], ['dormant', 'use', 'seeding', 'dormancy', 'inactivity', 'survive', 'overseeding'], ['dormant', 'company'], ['dormant', 'state', 'reasons', 'remain', 'cancer', 'dormancy', 'behind', 'cells'], ['dormant', 'still', 'deemed', 'considered', 'company', 'change', 'dormancy'], ['dormant', '2020', '1903', '–', '1882', 'xi', 'epsilon'], ['dormant', '“dormant', 'therapy”', 'therapy'], ['dormant', 'gave', "governor's", 'commission', 'held', 'convention', 'may'], ['dormant', 'different', 'seeds', 'survival', 'seed', 'appears', 'dormancy', 'inherent', 'another'], ['dormant', 'period', 'enter', 'plants', 'dormancy', 'treatment'], ['dormant', 'state', 'due', 'goes', "m'goes", 'j', 'time', '∈', 'otherwise', 'depending'], ['dormant', 'broadcast', 'dental', 'midshipmen', '–']]
TOP TOKENS [["wittgenstein's", 'wittgenstein', 'wittgensteinian'], ['wittgenstein', "wittgenstein's", 'wittgensteinian'], ['wittgenstein', "wittgenstein's", 'wittgensteinian'], ['wittgenstein'], ['wittgenstein', 'metaphors', 'limits'], ["wittgenstein's", 'wittgenstein', 'wittgentein', 'example', "book's"], ['wittgenstein', '’', '4'], ['wittgenstein', 'experiences', 'sensation', 'since', 'idea', 'discourse', 'example', 'exasperating', 'also'], ["wittgenstein's", 'wittgenstein'], ["wittgenstein's", 'wittgenstein', 'resemblances', 'explains'], ['wittgenstein', 'wittgensteins', "wittgenstein's"], ['wittgenstein', "wittgenstein's"], ['wittgenstein', "wittgenstein's", 'pencil', 'moreover', '5', 'n'], ["wittgenstein's", 'wittgenstein'], ['wittgenstein', "wittgenstein's", 'notable', 'attempts'], ['wittgenstein', 'wittgensteinians', 'schonbaumsfeld'], ["wittgenstein's", 'wittgenstein', 'entailed'], ['wittgenstein', "wittgenstein's", 'wittgensteinian'], ['wittgenstein', 'present', 'tgenstein'], ['wittgenstein', 'society', 'puts', 'things', 'way', 'boundaries', 'another', 'sharp', 'instance']]
TOP TOKENS [['synopsis', '120', 'attacks', 'long', 'members', 'u.s', 'taylor', '11', 'ft', 'numbers', 'pounds', 'army', '4th'], ['summary', '1970s', 'early', 'moon', 'mission', 'already', 'spacex', 'first'], ['ibarruri', 'pasionaria', 'party', 'birthplace', 'synopsis', 'first', 'since', '38', 'la', 'general', 'years', 'last', 'time', 'sunday'], ['adults', 'behavior', 'correlates', 'gender', 'never-married', 'gay', 'noncohabiting', 'same-sex', 'experience'], ['egypt', 'synopsis', 'passover', 'ago', 'year', 'last', 'introduction', 'two', 'first', 'coincided'], ['context', '1509–2009', 'calvin”', 'activities', 'virtual', 'friends', 'calvin’s', 'familiar', 'woke', 'reformation', 'expertise', 'era'], ['excerpt', 'despite', '2015', 'great', 'known'], ['context', 'disquiet', 'yearly', 'emulate', 'medical', 'yet', 'far', 'junctions', 'inventors', 'person', '’', 'across', 'diagnostics', 'hundred', 'humans', 'misidentification', 'misguided', '70', 'every', 'prominent'], ['description', 'charles', 'june', '1943', 'crews', 'later', 'diminished', 'despite', '18'], ['summary', 'duration', 'protocol', 'minutes', 'exists', 'user’s', 'request', 'user'], ['daniel', 'recently', 'synopsis', 'tutor', 'family', 'instead', 'jail', 'obliged', 'causing', 'sleep', 'skal'], ['skin', 'nessarose', 'morrible', 'day', 'back', 'west', "nessarose's", 'earlier', 'following', 'nerdy', 'one', 'childhood', 'years', 'mother', 'father', 'munchkinland'], ['lapalme', 'thirds', 'le', '1940', '1939', 'party', 'even', '1947', 'abilities', 'full', 'two', 'polling', 'additional', '1950s', 'finetuned', 'time', 'favour', 'areas', 'radio', 'large', 'focus'], ['events', 'prologue', 'resident', 'de', 'giudicelli', 'plot', 'populaire', 'france', 'life', '1881', 'explained', 'grand', 'giry', 'dazzled', 'richard', 'situation', 'mammoth', 'box', 'successors', 'meg', 'christine', 'noting', 'raoul', 'first', 'vicomte', 'opera', 'bid', "populaire's", 'place', 'paris', 'owner'], ['общая', 'minor', 'девушек', 'тобою', '4', 'дикая', 'introduction', '8', 'мальчиков', 'привольно', 'пляска', 'b', 'воздух', 'andantino', 'тебя', 'major', 'дремлют', '2nd', 'reprise', 'улетаи', 'говор', 'мужчин', '6', 'presto', 'плавная', '2', 'allegro', 'f'], ['sounded', 'field', 'summary', 'decided', 'able', 'stop', 'attempt', 'later', 'effort', 'p', '100', 'humid', 'leases', 'incident', 'speed', 'putting', 'opened', 'bubble', 'lap', 'solidly', 'afternoon', '30', 'time'], ['time', 'particularly', 'great', 'century', 'arts', 'synopsis', 'poetry', 'minnesingers', 'year', 'wartburg', 'love', 'landgraves', 'nymphs', 'ofterdingen', 'would', 'ago', 'interior', 'home', 'around', 'minnesinger', 'venusberg', 'venus', 'captivate', 'germany', 'ruled'], ['purpose', 'years', 'women', '15', 'existence', '30', '40', 'los', 'per', "association's", '00', 'artists', 'field', 'day', 'attended', 'cost', 'technicians', 'stage', 'four', 'million', 'hospitals', 'revenue', 'people', 'paying', 'wrote', 'nearly', 'reemployment', 'primary', 'programs', 'new', '65', 'project', 'south', 'factories', 'hours', 'receipt', '—'], ['opening', 'august', 'two', 'liss', 'bold', 'tv', 'title', 'first', 'asto', 'nov', 'made', 'july', 'fellow', 'publishers', 'series', 'war', 'nut', 'jan', 'succeeded', '–', 'debut', 'instead', 'historians', "boltinoff's", 'respectively', 'smattering', '79', 'period', 'stories', 'soon', 'schwartz', 'drake'], ['army', 'reputation', 'synopsis', 'food', '’', 'hope', 'eustachio', 'except', 'edmondo', 'defenders', 'eleonora', "aurelio's", 'god', 'son', 'oggetti', 'calais', 'unhappy', 'edoardo', "dell'orrenda", "m'investe", 'follows', 'gelo', 'le', 'inside', 'motion', 'assails', 'city', 'orrida', 'oh']]

Processing features:  29%|██▊       | 28/98 [13:20<34:06, 29.24s/it]

getting sample prompt forgetting sample prompt for 23737
 23736
getting sample prompt for 23738
getting sample prompt for 23739
getting sample prompt for 23740
getting sample prompt for 23741
getting sample prompt for 23742
getting sample prompt for 23743
getting sample prompt for 23744
getting sample prompt for 23745
getting sample prompt for 23746
getting sample prompt for 23747
TOP TOKENS [['transmitted', 'transmission', 'transmitting', 'line', '«', 'constant', 'propagation', 'sample', 'communications'], ['transmission', 'adequate', 'expert', 'customers', 'costs', 'oncor', 'capability'], ['transmitted', 'transmission', 'transmit'], ['transmission', 'method', 'ratio', 'way', 'transmissions', 'types', 'cls', 'structure', 'intersecting', 'reliable', 'large'], ['transmission', 'transmit.]transmissive', 'transmitted', 'transmit', 'transmitting', 'word'], ['transmission', 'transmits', 'propagative', 'legal', 'converter', 'transmissions', 'cls'], ['transmission', 'transmitted', 'term', 'transmissions', 'ratio', 'refers', 'another', 'power', 'device', 'whole', 'cls', 'process'], ['transmission', 'electric-power', 'power'], ['transmission', 'efficacy'], ['transmission', 'term', 'transmissions', '“', 'transmitted', 'electromechanical', 'hydromechanical', 'diffuse', 'mechanical'], ['transmission', 'transmit', 'transmittance', 'generation', 'device', 'pathogen', 'transmissions', 'another', 'electric', 'cicierega', '1993', 'sending', 'actual', 'experimental/post-rock'], ['transmission'], ['transmission', 'system'], ['transmission', 'also', 'reasons', 'sponsored', 'links'], ['transmission'], ['transmission', 'known', 'neustadt-glewe', '2014', 'also', 'slovakia'], ['transmission', 'transmissions', 'hydrokinetic', 'hydrostatic'], ['transmission', 'data', 'fiber-optic'], ['transmission', '2014', 'films', '2009', 'called', 'mackie', 'number'], ['transmission']]
TOP TOKENS [['hermetic', 'hermeticism', 'hermetism', 'hermeticum', 'hermetismus'], ['hermeticism', 'hermetic', 'hermetism', 'hermetica'], ['kemetic', "the'kemetic", 'methodical'], ['kemetic', "the'kemetic", 'methodical'], ['kemetic', 'kemeticism', 'kemetism', 'kemet'], ['kemetic', 'kemeticism', 'kemetism', 'kemet'], ['kemetic', 'kemet', 'kemetism', 'kemetists', 'kemetics', 'k'], ['kemetic', 'kemet', 'kemetist', 'kemetics', 'kemetism'], ['mimetic', 'mimetics'], ['hermeticism', 'hermetic'], ['kemetic', 'kemetism', 'kemet'], ['kumeta'], ['eumeta'], ['emmet', 'densmore', 'byrne'], ['šemeta', 'šėmeta', 'shemetov', 'szemet', 'shemet'], ['zamęt'], ["kumeta's", 'kumeta', "websunday.net's", 'bulk', 'kōji', 'kodansha', 'manga'], ['mimetidae', 'ermetus'], ['cimet'], ['zamęty', 'korzeniew', 'south-east']]
TOP TOKENS [['tipton', 'states', 'among', '’', 'stood', 'firmly', 'experience', 'unflagging', 'vindication'], ['tipton', '1789', 'episcopalian', 'convention', 'hillsborough', 'vol', '1', 'america', 'family', '006165369', 'moore'], ['tipton', 'herald', 'morris', 'watched', '’', 'exactly', 'surprised', 'stated', 'change', 'acting', 'recently', 'perfect', 'tell', 'like', 'always', '—', 'letter', 'aw', 'phase', '3', 'remain'], ['tipton', '0.67', '70,84', '29,16', 'county'], ['tipi', 'tipis', 'different'], ["tipu's", 'tipu', 'rao', 'says', 'kodavas', 'khan', 'know', 'writes', 'say', 'wrote'], ["tipton's", 'tipton', 'sides', '1788', '1785', 'sons', 'hillsborough', '77', 'forty', 'followed', 'politics'], ['around', 'tipis', 'tipi', 'given', 'would', 'front', 'along'], ['madrigals', 'tippett', 'tippett’s', 'student', 'would', 'idealised', 'worlds', 'mid-1950s'], ['madrigals', 'tippett', 'tippett’s', 'student', 'would', 'idealised', 'worlds', 'mid-1950s'], ['tipton', 'states'], ['tipton', 'selected', 'wallace', 'portrait', 'finding', 'aid', 'collection', 'month'], ['tipton', 'u.s', 'west', 'history', 'east', '2,490', 'southeast'], ['carolina', 'tipton', 'years', 'program', 'related'], ['tipton', 'senators', 'team', 'began', 'war', 'athletics', 'finding', 'hit', 'season', 'emerged', 'played', 'end', 'two'], ['tipton', "men's", '1898'], ['tipton', 'became', 'england'], ['tipton'], ['tipton', 'cerbat', 'wilderness'], ['tippecanoe', 'tipton', "tipton's", 'describes', 'links', 'road', 'years', '1786']]
TOP TOKENS [['try'], ['rag', 'head'], ['rogue', 'books'], [], ['alleluia', '”', '“', 'indeed', '–'], ['alleluia', '–', '—', '”', '1', '8', 'publishers', 'result', 'alms'], [], ['qua', '”', 'luster', 'brilliance', '“', 'rhetoric'], [], ['alleluia', '—', '“'], ['alleluia', 'unaccompanied', 'g', 'fanfare', 'sopranos', 'july', 'koussevitzky', 'woodworth', '1940', 'instead', '8', 'center', 'amen', 'end', 'france', 'thompson'], [], ['rock', 'power', 'television', 'metal', 'band', 'series', 'stand-up', 'opera', 'tv'], [], [], ['freddy', 'must', 'moreover', 'narrative', 'endearing', 'considerable'], [], ['adoratio', 'latin', 'ye'], ['grīsniņš', 'song'], []]
TOP TOKENS [['seti', 'project', 'crossed', 'must', 'race', 'one', 'traveling', 'concerning', 'clearly'], ['seti', 'setˈe', 'one', 'giuseppi', 'cls', 'institute', 'sun', 'group', 'initiated', 'everywhere', 'civilizations', 'epsilon', 'modern'], ['seti', 'setˈe', 'one', 'giuseppi', 'cls', 'institute', 'sun', 'group', 'initiated', 'everywhere', 'civilizations', 'epsilon', 'modern'], ['seti@home', 'seti'], ['seti'], ['seti', "seti,'of", 'one', "alongside'traditional"], ['seti', 'setiquest', 'using', 'years', 'institute', 'signals', 'enthusiasts'], ['seti@home', 'seti', '2'], ['seti', 'institute', '’', '—'], ['seti', 'setiquest', 'longevity', 'use', 'cls', 'public', '”', '“'], ['seti', '1197', 'active', 'sete', 'amun-her-khepeshef'], ['seti', '8885th', 'sette', 'sett', 'magazine', 'setté', '1900–1972', 'hill'], ['seti', 'disambiguation', 'sete'], ["seti's", 'music', 'seti', 'recesses', 'one-time', 'expansive'], ['setario', 'died'], ['seto', 'setomono', 'early', '1810', 'around', '27', 'mm', 'period', 'geography', 'along'], ['2013', 'seto', '2015', 'chronicle'], ['sętki', 'radzyń'], ['levi-setti', 'setti'], ['setsch', 'setchell', 'setchey', 'setch']]
TOP TOKENS [['gentile', 'gentiles”', '“gentile”', 'gentiles', '“the'], ['gentiles', 'gentile', 'word'], ['gentiles', 'gentile', 'word', 'period'], ['gentiles', 'gentile', 'use', 'gentilis', 'meaning', 'gentes'], ['gentile', 'term'], ['gentiles', 'gentile', '“', '”', 'word', 'english'], ['gentiles', 'gentile', 'christ', 'jew', 'jesus'], ['gentiles'], ['gentiles', 'gentile', 'one'], ['gentiles', 'gentile'], ['jew', 'gentile', '1171'], ['gentile', 'mean', 'term', 'word', 'gentilis', 'group', 'cls', 'along'], ['gentile', 'works', 'world'], [], ['gentile', "gentile's", 'years', 'external', 'links', 'giovanni', 'remains', 'interest', "dell'accademia", 'assigned', 'especially'], ['gentile', 'gentiles', 'word', 'version', 'include', 'thy', 'israelite'], ["gentile's", 'gentile', 'nonetheless', 'montescaglioso', 'cls', '1168', 'nevertheless', 'foreigner'], ['gentile', 'ordained', 'panciatici'], ['gentile', '1555–1616', 'salvatore', '1934', '1875–1944', 'catholic', 'skeeter', 'melissa', '1921–', '1835–1893', 'american', 'doris'], ["gentile's", 'gentile', "gentile'wrote", '1960s', 'days', 'story', 'said']]
TOP TOKENS [['video', 'videos', 'watching', 'made'], ['video', 'videos'], ['video', 'videos', 'animations', 'life', 'say'], ['videos', 'video', 'film', 'watch', 'segment', 'script||creative', 'filming'], ['videos', 'video', 'class', 'thing', 'record'], ['video', 'videos', 'visuals', 'audio', 'provide'], ['video', 'videos', 'recording', 'decades', 'clips', 'leverage'], ['video', 'videos', 'film', 'alouds', 'cls'], ['videos', 'video', 'record', 'series', 'speak'], ['videos', 'video', 'cls', 'class', 'clips', 'media', 'clip'], ['videos', 'video', 'videotape', "emes'video", 'film', 'developed', 'cameras', 'worked', "mallet's", 'produced', 'music', 'use'], ['s-video', 'video', 'albums', 'song', 'vista'], ['video', 'videos', 'engage', 'result', 'media', 'sequences'], ['video', 'videos', 'dvds', 'documentary', 'film', "film's", 'filmmakers', 'clips', 'genre', 'filmmaking', 'show', 'lenses', 'released'], ['videos', 'video', 'engage', 'footage', 'film', 'practice', 'ethnographic', 'filmed', 'practitioners', 'recording'], ['videosingles', 'videos', 'video'], ['video', 'videopoetry', 'videosyntheatronica', 'videopoemetti', 'videopoemopera', 'dvds', 'recorded', 'fictions', 'recording', 'visual', 'work', 'works', 'cinema'], ['video', 'videos', 'videography', 'film', 'films', 'fincher', 'music', 'song', 'dancers', 'recorded'], ["video's", 'video', 'series', 'utilizes', 'filmmakers', 'films', 'entertainment', 'way', 'academia', 'filmmaker', 'film', 'essay', 'author', 'media', 'vengeance'], ['video']]
TOP TOKENS [['kangaroo', 'overall'], ['kangaroo'], ['kangaroo', 'kangaroos', 'www', 'htm', 'grown', '1997'], ['kangarooing', 'kangaroo', "kangaroo's", 'skin', 'care', 'lines', 'states', 'percent', 'simulating', '2', 'well', 'thriving'], ['kangaroo', 'kangaroos', 'bam', 'wordreference', 'access'], ['kangaroo', 'kangaroos', "kangaroo's", 'cattle', 'day'], ['kangaroo', "kangaroo's", 'kangaroos'], ['kangaroo', "kangaroo's", 'kangaroos', 'cattle', 'meats', 'currency', 'head', 'plentiful', 'hides'], ["that'kangaroo'was", 'kangaroos', 'kangaroo', "kangaroo's", 'plentiful', 'cattle', 'meat'], ["that'kangaroo'was", 'kangaroos', 'kangaroo', "kangaroo's", 'plentiful', 'cattle', 'meat'], ['kangaroo'], ['kangaroo', 'kangaroos', 'express', 'sep', 'order', 'word'], ['kangaroo'], ['kangaroo', 'external', 'albums', '1995', 'references'], ['kangaroo', 'kangaroos', 'kangaroolike'], ['kangaroo', 'anti-kangaroo', 'kangaroos'], ['kangaroo', 'kangaroos', 'disambiguation'], ['kangaroo', 'october', 'september', '1798'], ['kangaroo', 'kangaroos', "kangaroos'pouches", 'characters'], ['kangaroo', 'belongings', 'wallets', 'people']]
TOP TOKENS [['debenture', 'debentures'], ['debenture', 'debentures'], ['debenture', 'debentures', "define'debenture"], ['debentures', 'debenture'], ['debenture', 'debentures'], ['debenture', 'debentures'], ['debentures', 'debenture', 'debenture-holder', 'debenture”'], ['debenture', 'debentures'], ['debenture', 'debentures', 'debentures&v=4v0lcokt-rq', 'debentures&v=imny8enoyco'], ['debenture', 'debentures'], ['debentures', 'debenture', "of'debenture'is"], ['debenture', 'debentures', 'wimbledondebentureholders'], ['debenture', 'debentures'], [], ['debenture'], ['debenture', '“debentures”', 'debentures'], ['debentures', 'debenture'], ['witnesham', 'deben', 'bealings', 'otley', 'alderton'], ['debenhams', 'debenham', 'f.c'], []]
TOP TOKENS [['conceptual', 'conceptional', 'people', 'respresentation', 'practical', 'idea'], ['conceptual', 'conceptional', 'people', 'respresentation', 'practical', 'idea'], ['conceptual', 'conceptually............in', 'movement', 'mid'], ['conceptual', 'putting', 'interested', 'known'], ['conceptual', 'aspect', 'aspects', 'important', 'another', 'well', 'one'], ['conceptual', 'conceptualism', 'conceptualists'], ['conceptual', 'theme', 'inquire', 'hypotheses', '’'], ['conceptual', 'conceptualism', 'uk', 'however', 'epithet', 'term', 'previously'], ['art?.conceptual', 'conceptual', 'video', 'so-called', 'follows', 'hence'], ['conceptual', 'based', 'place', 'physicists', 'much', 'make', 'objects', 'consider', 'attempt', 'ideas', 'every', 'made', 'include', 'extra', 'represent', 'science', 'physics'], ['conceptual', 'external', 'excellent', 'regular', '37'], ['conceptual'], ['conceptual', 'conceptualism', 'utilizes', 'third', 'hudson', 'heading', 'see'], ['conceptual', "term'conceptual", 'described', 'term', 'illustration'], ['conceptual', 'described'], ['conceptual', 'conceptualists', 'conceptualism', 'kingdom', 'term', 'prototypically', 'however', 'art'], ['conceptualism', "conceptualism's", 'conceptuality', 'conceptual'], ['conceptual', 'entry'], ['conceptual', 'conceptests', 'engage', 'previously', 'example'], ['conceptual', 'change', 'single', 'must', 'external', "person's", 'users', 'one']]
TOP TOKENS [['contaminants', 'electronics', 'electronic', 'microwaves'], ['electronics', 'electronic', 'away', 'unwanted', 'throwing', 'cls', 'waste'], ['electronics', 'recycle', 'electronic', 'harvesting'], ['world', 'electronics', 'semiconductors', '7', 'various'], ['items', 'products', '800,000', 'electronics', 'makes', 'one'], ['electronics', 'materials', 'tvs', 'major', 'electronic', 'waste', 'comes', 'discarded', 'countries'], ['place', 'electronic', 'electronics”'], ['electronic', 'electronics', 'waste', 'device', 'computer', 'computers', 'metals', 'retardants'], ['electronics', 'retardants', 'wisely'], ['items', 'electronics', 'contain', 'million', 'life', 'televisions', 'objects'], ['pcs', 'electronics'], ['electronics', 'cls', 'usables', 'waste'], ['electronics', 'consider', 'cls', 'electronic', 'level', 'metals'], ['electronic', 'waste', 'states', 'electronics', 'thus', 'tantalum'], ['manufacturers', 'unscreened', 'electronics', 'person', 'computers', '–', 'waste', 'donating', 'wastes', 'items', 'takes'], ['electronic', 'computer', 'products', 'waste', 'computers', 'also'], ['electronics', 'waste', 'tvs', 'set', 'electronic', 'also', 'definitions', 'speculatively', 'hazardous', 'order', 'microwaves'], ['improperly', 'crts', 'disposed', 'computers', 'waste', 'phones', 'enough', 'ferrous', 'fractions', 'complicated', 'manufacturers', 'still', 'e', 'rather', 'metals', 'one', 'product', 'toxic', 'pieces', 'screens', 'companies', "user's"], ['2005', 'electronics', 'electronic', '13', 'manufacturers', 'however', 'regulations', 'years', 'devices'], ['waste', 'electronic', 'products', 'electronics', 'devices', 'computers', 'ending', 'wastes', 'manufacturers', '10', 'reusable', 'cls', '27']]
TOP TOKENS [['cowbirds', 'bluebird', 'blackbirds', 'cowbird', 'ac', 'molothrus', 'bird', 'birds', 'cow', 'wheye', 'parasitic', '08', "birds'nests"], ['cowbird', 'blackbirds', 'blackbird', 'cowbirds', 'molothrus', 'grackles', 'songbird', 'livestock', 'songbirds', 'birds', 'headed', 'incubate', 'kernels', 'grackle', 'redwings'], ['bluebirds', 'blackbirds', 'cowbird', 'cowbirds', "bird's", 'cows', 'also', 'molothrus', 'sparrows', 'headed', 'egg'], ['blackbirds', 'cowbird', "cowbirds'toll", 'buntings', 'catbirds', 'jays', 'gnatcatchers', 'yellowthroats', 'harasses', 'kingbirds', 'meadowlarks', 'thrashers', 'warblers', 'winged', 'sparrows'], ['bluebirds', 'bluebird', 'cowbird', 'birds', 'catbirds', 'woodpeckers', 'nest', 'headed', 'e'], ['grackles', 'blackbirds', 'cowbirds', 'cowbird', 'blackbird', 'songbirds', 'bird', 'headed', 'city'], ['cowbird', 'cowbirds', 'birds', 'parasitism', 'ravenous', 'parasitized'], ['bluebirds', 'cowbirds', 'bluebird', 'cowbird', 'chickadees', 'birds', 'woodpeckers', 'parasitized', 'headed'], ['blackbirds', 'cowbirds', 'cowbird', 'cowbird“', 'full', 'catbirds', 'brown-headed', 'birds', 'bird'], ['cowbirds', 'cowbird', 'jays', 'headed', 'buntings', 'parasitism', 'meadowlarks', '1972', 'catbirds', 'kingbirds', 'thrashers', 'waxwings', 'past'], ['cowbirds', "cowbirds'brood", 'cowbird'], ['cowbirds', 'cowbird', 'blackbirds', 'greater', 'bird'], ['cowbirds', 'cowbird', 'headed', 'catbirds', 'birds', 'conceivably', 'gnatcatcher'], ['blackbirds', 'blackbird', 'hayfields', "bird's", 'ostrinia', 'flocks', 'winged', 'birds', 'devastate', 'late'], ['cowbirds', 'cowbird', 'blackbirds', 'grackles', 'parasitized', 'birds', 'upon', 'headed', 'rearing', 'fledge', 'part', 'partly'], ['grackle', 'cowbird', 'headed', 'songbird', 'birds', 'mexicanus', 'vol', 'bird', 'bioscience', 'cody', 'l', 'avian', 'sparrows', 'university', 'species', "america's", 'invaded', 'bonney', 'r'], ['blackbirds', 'molothrus', 'cowbird', 'cowbirds', 'parasitism', 'auk', 'animal', 'behaviour', 'p', 'parasitizing', '1', '103'], ['blackbird', 'molothrus', 'cowbirds', 'cowbird', 'although', 'bird', 'parasitized', 'parasitize', 'one', 'parasitism', 'baywing'], ['cowbirds', 'cowbird', 'obligate', 'finches', 'wagler', 'bird', 'white-naped', 'birds', 'ground-sparrows', 'parkes', 'molothrus', '1829'], ['blackbirds', 'cowbird', 'molothrus', 'cowbirds', 'guayaquil', 'chapman', 'stolzmann', 'venezuelensis', 'parasitised', 'eastern', 'berlepsch', 'bolivia', 'cassin', 'occidentalis', 'aequatorialis', 'bonariensis', "cowbird's", 'bird', 'uruguay']]

Processing features:  30%|██▉       | 29/98 [13:52<34:30, 30.00s/it]

getting sample prompt forgetting sample prompt for 23749
 23748
getting sample prompt for 23750
getting sample prompt for 23751
getting sample prompt for 23752
getting sample prompt for 23753
getting sample prompt for 23754
getting sample prompt for 23755
getting sample prompt for 23756
getting sample prompt for 23757
getting sample prompt for 23758
getting sample prompt for 23759
TOP TOKENS [['headgear', 'hat', 'hair', 'brim', 'circumference', 'payjama', 'forward', 'zip', 'front', 'head', 'hand'], ['hat', 'hats', 'women’s', 'wearing', 'sculptures', 'england', 'straw', 'https://en.wikipedia.org/wiki/hat', '“hats', 'cloche', 'displays', 'cap', 'woven', 'beanie', 'paleolithic', 'hatter'], ['long', 'hats', 'warm', 'hat', 'cap'], ['hat', 'classic', 'wear', 'hats', 'psyche', 'types', 'inclusive', 'r', 'caps', 'around', 'haven’t', 'invented'], ['wear', 'hats', 'hat', 'unwieldy', 'powerful', 'release', 'news'], ['hat', 'network', 'networks', 'permission', 'seo', 'black'], ['hat', 'hats', 'expressed', 'wear', 'civilization', 'brims', 'look', 'different', 'style'], ['milliners', 'world', 'hats', 'hat', 'significance', 'head', 'beret', 'people', 'numerous'], ['hat', 'hats', 'cloche', 'pillboxes', 'chef’s', 'caps', 'deerstalkers', 'wear', '1797', 'day', 'berets'], ['hat', 'sep', 'lot', 'washington'], ['hats', 'hat', 'entertainment'], ['head', 'hat', 'group', 'mahrah', 'cls', 'thailand', 'american', 'mathematical', 'jack', 'trypanosomiasis', 'worn', 'gorgoroth'], ['hat', 'hats', 'series'], ['party', 'instrument', 'disambiguation', 'hats', '18th-century', 'edward'], ['hat', 'united', 'cap', 'security', 'blackhats', 'black', 'nefarious', 'hats', 'black-hat'], ['hat', 'nepal'], ['hat'], [], ['hať', 'republic', 'formerly', 'region'], ['hat', 'holmskioldia']]
TOP TOKENS [['cream', 'creaminess', 'thickened', 'diet', 'pure', 'make', 'cls', 'homogenization', 'rises'], ['cream', 'note', 'include'], ['cream', 'creams', 'whipped', 'purposes', 'types', 'kinds'], ['cream', "cream's", 'buttermilk', "manufacturer's", 'similar', 'content', 'half-and-half', 'elsewhere', 'us'], ['cream', "cream's", 'buttermilk', "manufacturer's", 'similar', 'content', 'half-and-half', 'elsewhere', 'us'], ['cream', "cream's", 'buttermilk', "manufacturer's", 'similar', 'content', 'half-and-half', 'elsewhere', 'us'], ['cream', 'qualities', 'creams', '”', '“', 'collected', 'needed', 'type', 'aerosol', '0', 'etc', 'rises', 'stabilizers', 'g', 'creameries', 'separation', 'cls'], ['creams', 'cream', "cream's", 'qualities', 'harold', 'dishes', 'fruitiness', 'type', 'desserts'], ['cream', 'creaming', 'softened', 'butter', 'get'], ['cream', 'states', 'cls', 'color', 'countries', 'white', 'content', 'coffee'], ['album', 'cream', 'c.r.e.a.m', 'magazine', 'creamed', 'whipped', 'bizarre', 'chiboust', 'custard', 'film', 'creaming', 'nightclub', 'product', 'bavarian', 'rapper', 'rabbit'], ['wisconsin'], ['cream', 'cream-coloured', 'butter', 'anime', 'featured', 'south'], [], ['cream', 'also'], ['cream', 'consultant', 'disambiguation', 'dead', 'also', '1986', 'creamer', 'matthew', 'born', '1916–1942', 'see', '1916–2020', 'vessel'], ['cream'], ['cream', 'dub', 'derangement', 'mix', "noble's", 'amnesia'], ["cream's", 'cream', 'functions', 'experienced', "vim's", 'operability', 'menus'], ['cream', "cream's", 'm.i.b', 'february', '14', '2011', 'young', 'started', 'january', 'daejeon']]
TOP TOKENS [['perches', 'waxwings', 'waxwing', 'feathers'], ['birds', 'waxwings', 'waxwing', 'irruptions', 'entice', 'several', 'incubates', 'approximately', 'crests', 'approachable'], ['waxwings', 'raised', 'content', 'waxwing', 'pencils', 'typically', 'feeders', 'turn', 'cedar', 'sometimes', 'bring', 'diets', 'small', 'may'], ['threatened', 'america', 'waxwings', 'waxwing', 'also', 'sources', 'plucking', 'bohemian'], ['waxwings', 'way', 'waxy', 'summer', 'waxwing', 'pigment', 'please', 'landmass', 'primarily', 'ever', 'robertson', 'northern', 'cedar', 'though', 'species', 'eluded', 'plumage', 'sized', 'tip', 'frugivorous'], ['waxwing', 'waxwings', 'typically', 'really', 'winter', 'ever', 'regardless'], ['waxwings'], ['waxwing', 'waxwings', 'one', 'submitted', '2012', 'lets', 'cedar', 'overripe', '95', 'regurgitate', 'vireos'], ['waxwing', 'waxwings', 'one', 'submitted', '2012', 'lets', 'cedar', 'overripe', '95', 'regurgitate', 'vireos'], ['waxwings', 'waxwing', 'winter'], ['waxman', 'long', 'also', 'affiliations', 'washington', 'setting', 'standing', 'furthermore', 'american'], ['bombycilla'], ['along', 'neurologist', 'waxman', '2020', 'dr', 'g', 'great', 'nation'], ['waxman', '2011', 'sally', '1994', '1993', 'made', '2006', 'became', 'television'], ['rosedale', 'plantation', 'people', 'states'], ['1912', 'waxhaw', '1900', '1', 'a.w', 'r.j', 'company'], ['cap', 'flexibility', 'stoner', 'horse', '2015'], [], ['collection', 'october', 'waxman', 'also', '23', '1980', '1938'], ["men's", 'waxman', '1948–49', 'served', 'may', '22', 'players', '2013', '20']]
TOP TOKENS [['monsoon', '“'], ['monsoon', 'monsoons', 'cls', 'weak', 'myanmar'], ['monsoon', 'monsoons', 'విశేషము'], ['monsoon', 'monsoonal', 'zhang', 'webster', 'malabar'], ['monsoon', '“', 'areas', '”', 'high'], ['monsoon', 'monsoons'], ['monsoon', 'monsoons'], ['monsoon', 'monsoons'], ['monsoon', 'monsoons'], ['monsoon', 'monsoons', "a'normal'monsoon"], ['monsoon', 'wilbur', 'monsun', 'english-language'], ['monsoon', 'sons'], ['monsoon', 'monsoons', 'monsoonal', 'asian', '–'], ['monsoon', 'bach', 'escalation', 'dan', '9', 'glenn'], ['monsoon'], ['monsoon', 'boat', 'cutter'], ['monsoon', 'leicestershire'], ["monsoon's", 'monsoon', 'following', 'films', 'india'], ['monsoon'], ['monsoon', 'fiancé', 'india', 'pohlmann', "julia's", 'films', 'references']]
TOP TOKENS [['buren', 'banks', '’', 'van', 'worse'], ['buren’s', 'buren', "buren's", 'van', '1837–41', '1833–37', 'u.s', 'society', 'executive'], ['buren', 'groups', 'hamilton', 'van', 'law', 'r', '1800', 'clinton', '5th', 'one', 'jefferson', 'held'], ['buren', '1840', 'van', 'would', 'martin'], ['buren', 'van', 'win', 'years', 'ness'], ['buren', "buren's", 'van', 'divisive', 'company', 'territories', 'martin', 'grandchildren'], ['buren', "buren's", 'van', 'jackson.van', 'president', 'opponents', 'language', 'december', '1829–1831', 'democracy', 'party', 'particularly', 'irish', 'presidency', 'martin'], ['buren', 'van', 'canvass', 'situation', 'government', 'length', 'insensible', 'envenomed', 'taking', 'without', 'unvarying', '000', 'led', 'also'], ['buren', 'worse', 'van', 'states', '1836', '’', 'cabinet', '1827', 'became', 'prospering', '1821', 'soon'], ['buren', 'party', 'van', 'regency', 'latter'], ['buren', 'game', 'township', 'michigan', 'u.s', 'büren'], ['buren', 'june'], ['buren', 'major', 'philadelphia', '1847', 'service', 'states', 'authorities', 'van', '1859', 'served', 'military', 'churubusco'], ['buren'], ['buren'], ['buren', "buren's"], ['buren'], ['buren', "area's", 'races', 'households', '1835', '1837', 'van'], ['buren'], ["buren's", 'buren', 'van', 'martin']]
TOP TOKENS [['jaguar', 'jaguars', 'fear', 'hearts', 'blow”', 'form'], ['jaguar', 'jaguars', 'forest', 'deserts'], ['jaguars', 'jaguar', "jaguar's", 'rarissimes', 'unknown', 'passage', '7', 'onca', 'underworld', 'ground', 'earth', '6'], ['jaguar', 'jaguars', 'cubs', 'year'], ['jaguar', 'jaguars', 'free', 'quickly'], ['jaguar', 'jaguars', 'myth', 'etc'], ['jaguars', 'jaguar', 'jaguar’s', 'tail', 'pounds'], ['jaguars', 'jaguar', 'problem', 'animals'], ['jaguar', 'jaguars', 'sep'], ['jaguar', 'jaguars', 'caves', 'areas'], ['jaguar', 'nl:jaguar'], ['jaguar'], ['jaguar', 'mononymously', '1'], ['jaguar', "jaguar's", 'night'], ['jaguar', '2011', 'projects'], ['jaguar', 'palace', 'daylight', 'underworld', 'body'], ['jaguar', 'feature', 'uses', 'featured', 'lmp2', 'cis', 'dispersion-corrected', 'distinctive', '2020'], ['jaguar', 'jaguars', 'american', 'south'], ['jaguar', 'jaguars', 'realm', 'daytime', 'threatening', 'communities'], ['jaguars', 'jaguar', 'fire', 'also', 'p', 'eds']]
TOP TOKENS [['jackie', 'robinson', '1947', 'apparently'], ['jackie', 'jacqueline', 'despite', 'grace', 'kennedy', 'yet'], ['jackie', 'time', 'robinson', 'ucla'], ['jackie', 'worth', 'robinson', 'segregated', '“', 'time'], ['jackie', 'jackierobinson', 'robinson', 'cls', 'inand'], ['jackie', 'kennedy', '’', 'almost'], ['jackie', 'young', 'downs', 'america', 'could', 'something', '’', 'karl'], ['jackie', 'way', 'world', 'violence', '’', 'hate', 'used', 'tactic'], ["jackie's", 'jackie', 'dodgers', 'robinson', '“', '1962', 'movement', 'today', 'baseball'], ['jackie', "jackie's", 'focus', 'difficulties', 'anyone'], ['jackie', 'jacqueline'], ['jackie', 'jacqueline'], ['jackie', 'official', 'numerous', 'external', 'american', 'university', 'academic', 'links', 'smith'], ['jackie', '“jackie”', 'magazine'], ['jackie'], ['jackie', 'jacqueline', 'debut'], ['jackie', '2021', 'starred', 'life'], ['jackie'], ['jackie', 'september', 'traditional', 'living', 'also', 'male', 'american', 'james', '21st-century', 'singer-songwriters', 'people', 'others', 'kenny'], ['jackie']]
TOP TOKENS [['hull', 'year', 'culture', '1929', 'britain', '1930s', '1'], ['hull', '1907', '1916', '19', 'b', '1897', 'served', 'family', 'became'], ['hull'], ["hull's", 'hull', 'children', 'efforts'], ['hull', '87'], ['hull', "hull's", 'features', 'hullonian', 'lavin', 'coast', 'james', 'boston', 'landscapes', 'street'], ['hull', 'west', 'cesspool', 'ago', 'share', 'year', 'estate', '23'], ['hull', 'west', 'cesspool', 'ago', 'share', 'year', 'estate', '23'], ['hull', 'friends', '’', 'general', 'war'], ['hull', 'hulls', '1773-1843', 'groundwork', '7', '4', '3', '2', '1871-1955', '5', 'word'], ['hulls', 'hull', "hull's", 'research', 'honours', 'physics', 'cambridge'], ['hull', 'carey', 'jones', 'scientist', 'christ'], ['hull', "hull's", '1988', 'house', '1925', 'lifetime'], ['hull', "hull's", 'congress', 'targeted'], ['hull', 'hull–white', 'ottawa'], ['hull', 'cambridge', 'war', 'deaths', 'amyatt'], ['hull', 'women'], ['hull'], ['hull', 'season', 'ultimately', '2018', 'loss', 'draft', '2015', 'later', 'commented', 'team'], ['hull', 'colony']]
TOP TOKENS [['flush'], ['fo.flush', 'flush', 'flushes', 'file', 'method'], ['flushes', 'flush', 'flushing', 'means', 'normal', 'terms', 'fluid'], ['flushing', 'flush', 'title', 'allocate-on'], ['flushes', 'flush', 'flushing', 'flushed', 'term'], ['flush', 'flushing', 'sex', 'skin', 'forehead', 'temperature'], ['flush', '18', '16', '17', '15', '14', 'great', '5', '13', 'flushed', '12', '6'], ['flushing', 'flush', 'occurs', 'headache', 'related', 'gustatory'], ['flush', 'low-flush', 'experienced', 'experiencing', 'dyslipidemia', 'al', 'fire', 'reducing'], ['flushing', 'flush', 'flushed', 'want', 'part', 'checkpoint', "pass'for", 'buffers'], ['flushing', 'flush', 'poker', '1997'], ['flush', 'annual', '2001', '1927'], ['flush', 'flushing'], ['flush', 'flushes', 'word'], ['flushing', 'flush', 'buildings'], ['flush', 'flushing', 'painful', 'vein', 'saline', 'cannula', 'line', 'patent', 'chemotherapy'], ['flush', '1977', 'end', 'jeannie'], ['flush'], ['flushing', 'three', 'practical'], ['flushing']]
TOP TOKENS [['►'], ['brazil', 'high', 'looking', 'headed', 'interview', 'u', 'lingering'], ['help', '2007', 'progetto', 'great', 'height', 'pp', '6', 'became', '144', '117', 'half', '155', '71', 'donald', 'n'], ['please', 'learn', 'forward', 'cls', 'visitors', 'approved', 'million', 'enthusiastically', 'recognizing', 'afresh', 'consequential', '1950s', 'capitol', 'historical', 'bound', 'national', 'j', 'back', 'u', 'users', '96', '3', 'undertaking'], ['identified', 'diagnosing', 'occur', 'enter', 'however'], ['error', '2016', '73', '421', '9796163', 'extremen', 'ekeroth', '13', '304', 'tol', "alcest's", 'march', '2015'], ['please', 'unique', 'forms', 'features', 'forward', 'several', 'stages', 'heart', 'using', 'covered'], ['approaching', 'many', '’', 'happened', 'close', 'severe', 'data02', 'error', 'cls', 'current', 'maximum', 'minimum', 'taking', 'place', 'half', 'established'], ['key', 'valuable', 'exactly', 'important', 'helped', 'features', 'seriously', 'family', 'progress', 'watched', 'bring', 'experienced', 'lot', 'affected', 'eligible', 'may', 'mwai', 'troubles'], ['help', '44', 's0021911808001782', '1931', 'jbs', 'ikeya', 'zuzanna', 'targosz', '684', '6716', '16', 'kyaw', '2008', '07', '46', '2012'], ['message', 'leading', 'error', 'cannot', 'changed', 'dependencies', 'looking', '404', 'ganga', 'make', 'eng/terranaturabenidorm/ficha3.aspx', 'review', 'url', 'unavailable', 'please', 'requested', 'correctly', 'description', 'one', 'found', 'following', 'aquarium', 'pacific', 'references', 'sure'], ['maharaj', '467', 'baiyun', 'heavy', 'error', 'shivaji', '110', 'ravensthorpe', '2193', '5735', 'passengers', '6237', 'november', 'near', 'australia', 'fuselage', 'whilst', '2023', 'kunming', '179', 'chhatrapati', '1344', 'guangzhou'], ['course', 'around', 'since', 'face', 'unleashing', 'concerning', 'past', 'error', 'nearest', 'clear', 'rampant', 'great', 'may', 'many', 'senseless', 'neighbors', 'followed', 'starting'], ['september', "shaffer's", 'error', 'premieres', 'behind', 'october', '14', '2007', 'official', 'show', 'december', 'retrieved', 'commentary', '2', 'et', 'p', 'discussion', 'march'], ['12', '4', 'immediately', 'gradually', 'bethsura', 'series', '13', 'altogether', '9', 'largely', 'dura', 'hasmonean', 'mostly', 'progenitor', 'hyrcanus', 'wars', 'latter'], ['duterbrand', 'squads', 'paparemborde', 'haget', 'error', 'c', 'peter', 'blake-knox', 'jean-pierre', 'roly', 'gravell', 'sandy', 'lavery', 'mckinney'], ['error', '20th', '–', 'shediac', "moncton's", 'main', 'g', 'national', 'salter', 'resurgo', 'century', '1959', 'moncton', '1918', '1926', '1875', 'status', 'bridge', 'john', '1860s', 'cnr', 'merge', 'extensive', 'collapses', '1940', 'air', '1906', '1868', 'reincorporate', 'shops', '1871', 'including', '1912', '1913', 'founded', 'canada', 'bankruptcy'], ['watching', 'focused', '15', 'spectators', 'police', 'direct', 'staff', 'center', 'thousands', 'error', 'many', 'september', 'july', 'several', 'film', 'widows', 'new', 'noon', 'local', 'practice'], ['afterwards', 'corrected', 'june', 'error', 'semiquincentennial', 'ascended', 'internal', 'accused', '2022', 'run', 'opinions', 'discrimination', 'far', 'thinking', 'layer', 'swanson', 'however', 'important', 'foundation', 'amount', 'filled', 'variety', 'denies', 'leadership', 'report', 'oriented', 'immediate', 'commission', 'appropriations'], ['error', 'references', '2012', 'notes', 'links', 'external', 'games']]
TOP TOKENS [['27', "robespierre's", 'e'], ['king', 'louis', 'xvi'], ['louis', 'xvi', 'king', 'maximilien', 'robespierre', 'guillotined', 'terror', '‘'], ['terror’s', 'guillotine'], ['guillotine', 'terror', 'robespierre'], ['guillotine', 'terror', 'revolutionary', 'revolution'], ['1789', 'august', '1791'], ['terror', 'monarchy'], ['guillotine', 'france', 'terror', 'tribunals', 'french', 'enemies'], ['robespierre'], ['terror', 'robespierre'], ['terror', '1792', 'louis', 'national'], ['king', '1789', "revolution's", 'ancien'], ['guillotine', 'louis', "d'angremont", 'revolutionary', 'government', 'xvi', 'legislative', 'revolution', 'political', 'monarchy', 'august'], ["terror's", '1794', 'robespierre', 'maximilien', 'upheaval', 'many', 'guillotined', 'however'], ['terror:the', 'robespierre', 'revolutionary', 'french'], ['robespierre', 'insurrectionist', 'others', 'terror', 'herbois', 'back', 'imprisonments', 'moderates'], ['1789', 'july', 'national', 'steeped', 'also', 'revolutionary', '1793', 'several', 'across', 'robespierre', 'seven'], ['april', 'xvi', 'louis', '1792', 'robespierre', 'king', 'legislative'], ['national', '1791', '1789', 'french']]
TOP TOKENS [['microservices', 'microservice'], ['microservices', 'microservice'], ['microservices', 'microservice'], ['microservices'], ['microservices', 'microservice', 'microservices.«'], ['microservice', 'microservices'], ['microservice', 'microservices'], ['microservices', 'microservice'], ['microservic', 'microservices', 'microservice', 'possibility'], ['microservices', 'microservice'], ['microservice', 'microservices'], ['microservices', 'microservice', 'e'], ['microservices', 'difference', 'system', 'embraces'], ['microservices', 'microservice', 'since', 'software'], ['microservices', 'microservice', 'developing', 'way'], ['microservices', 'microservice', 'term', 'designed', 'even'], ['microservices', 'difference', 'vs', 'concepts', 'side', 'micro', 'services', 'two'], ['microservices', 'also'], ['geoservices'], ['microserver', 'microservers', 'e', 'eliminates', 'due', 'cores']]

Processing features:  31%|███       | 30/98 [14:21<33:34, 29.63s/it]

getting sample prompt forgetting sample prompt for 23761
getting sample prompt for 23762
getting sample prompt for 23763
getting sample prompt for 23764
 23760
getting sample prompt for 23765
getting sample prompt for 23766
getting sample prompt for 23767
getting sample prompt for 23768
getting sample prompt for 23769
getting sample prompt for 23770
getting sample prompt for 23771
TOP TOKENS [['alaric', "alaric's", '2012', '370–410', 'use', '2000', '4', 'commanders'], ['alabaster', '0', '8', '32', '2', '1', 'married', '73', '69', '02', '11', '64', '81'], ['alaric', "alaric's", 'alaricus', 'april', 'army', 'alareiks', 'half', 'roads', 'rothestes', 'italy', 'empire', '6', '395', 'eastern'], ['alabaster', 'writings', 'elegies', 'much', 'cambridgeshire', 'roman', 'wavering', '1609', 'mystically'], ['alaric', "alaric's"], ['alabaster”', 'alabastermiddle', 'alabaster', 'alabastre', 'alabasters', 'uncountable', 'thin', 'alabastos', 'fine-grained', 'enough', 'alabastros', 'ἀλάβαστος'], ['alaric', 'alaric(370?–410', 'short', 'empire', 'withdraw', '402', 'italy'], ['alaria', '1950', 'single', 'circulation', '5', 'first', '15', 'warm', 'less', 'since', 'two', 'adapted', 'onagawa', '19'], ['alaric', "alaric's", 'treason', 'ălˈərĭk', 'indecisive'], ['alaric', "alaric's", 'alaricus', 'army', 'italy', 'alareiks', 'half', 'april', 'eastern', 'rothestes', 'appointed', 'first'], ['alar', 'regulator', 'toomre', 'alaer', 'weightlifter'], ['alair'], ['alabaster', 'hydrous', 'rend', 'worship', 'r'], ['alaria'], ['alaca'], ['alahis', 'alagis', '689', '688', 'p'], ['alabaster', 'chaloner'], ['alak', 'locality'], ['alaric', 'alareiks', 'alarich', 'alarichus', 'alarik', 'alrekr', 'alaricus', 'ἀλάριχος', '1940–1960', 'alarico', 'june', 'union', '395–410', 'tokpa', 'ii'], ['ālā’ī', 'alai', 'romanized', 'also']]
TOP TOKENS [['westminster'], ['westminster'], ['westminster', "westminster's", 'kingdom', 'confessor', 'civil'], ['westminster', 'variety'], ['westminster'], ['westminster', 'loans'], ['westminster', 'www', "president's"], ['westminster', "westminster's", 'context', 'churches'], ['westminster', 'city', 'creation'], ['westminster', 'arts', 'wrong'], ['westminster'], ['westminster'], ['westminster', 'focus'], ['westminster'], ['westminster', 'originally', 'except', 'history', 'city'], ['westminster', 'city', 'links', 'sep'], ['westminster'], ['westminster'], ['westminster', 'jenna', 'city', 'official', 'links'], ['westminster', "westminster's", 'abandoned', '17', '1990']]
TOP TOKENS [['likert', 'product', 'scale', 'rensis', 'options', 'question'], ['sqrt', 'bit', 'numberstart', 'o=72+0', 'o=10+0', 'continue'], ['winrt', 'apis', 'support', 'let', 'specific', 'device'], ['usart', 'usart3', 'uart', 'bit', 'supplied', 'peripheral'], ["likert's", 'likert', 'dr', 'thomson', 'r', '↑', 'scallik', 'babbie', 'stathelp', '174', 'scales'], ["likert's", 'likert', 'dr', 'thomson', 'r', '↑', 'scallik', 'babbie', 'stathelp', '174', 'scales'], ['uart', 'vcsharp_uart_demo.exe', 'vcsharp_uart_demo', 'pc', 'rs232', 'vcsharp', 'rs-485', 'use', 'part', 'rs-232', 'v1.1a', 'universal', 'application'], ['likert', "word'likert", "and'likert", 'e', "urt'and", "scale'to", 'available', 'statement', 'item'], ['likert', "word'likert", "and'likert", 'e', "urt'and", "scale'to", 'available', 'statement', 'item'], ['winrt', "winrt's", 'accordingly', 'library', 'api', 'sandboxes', 'features'], ['birt', 'scophthalmidae'], ['cort', '1742-1810', '1913–2006', '1989', 'korea'], ['gart', 'formyltransferase', 'graphics', 'phosphoribosylglycinamide'], ['wirt', 'wirt-dt', '1784-1857'], ['birt', 'frequently'], ['kort', 'korts', 'cort', 'american', 'holmis', 'komi'], ['bort', 'french'], ['hort', '1674–1751'], ['dort'], ['wert']]
TOP TOKENS [['emperor', 'penguins', 'let'], ['emperor', 'emperors', 'penguins'], ['emperor'], ['emperor', 'habitat', 'penguins', 'size', 'half', 'offspring', 'others', 'begins'], ['emperor', 'emperor’s', 'penguins'], ['emperor', "emperor's", 'penguin', 'penguins', "penguin's"], ['emperor', 'penguin'], ['emperor', 'penguins', 'winter', 'top'], ['emperor', 'penguins', 'species', '1,500', 'cheeks'], ['emperor', 'except', 'penguins', 'warm', 'penguin', 'group', 'cls', '49', 'adult', 'almost'], ['emperor', 'penguins', 'antarctic', 'coinciding'], ['emperor'], ['emperor'], ['emperor', 'classification', 'south-southwest', 'u.s'], ['emperor', 'classification', 'east', 'archduke-emperor'], ['emperor', 'eastern', 'penguin', 'nearer', 'penguins', 'first', 'entirely', 'flows', 'train'], ['emperor', 'penguin', 'penguins', 'greater', 'quasi'], ['emperor', "jojo's", 'piano', 'film', 'chitoria', 'documentary', 'f', 'entertainment', 'iron', 'palpatine', '76', 'short', 'dune'], ['emperor', 'penguin', 'links', "label's"], ['emperor', 'penguin', 'exerts', 'swimmer', "penguin's", 'penguins', 'attack', 'giganteus', 'repeatedly', 'mainly']]
TOP TOKENS [['hemangioma', 'hemangiomas', 'telangiectasias'], ['hemangiomas', 'hemangioma', 'http://www.accessmedicine.com/resourcetoc.aspx?resourceid=678', 'http://www.accessmedicine.com/resourcetoc.aspx?resourceid=14'], ['hemangiomas', 'hemangioma', 'telangiectasias'], ['hemangiomas', 'hemangioma', 'defects'], ['hemangiomas', 'hemangioma'], ['hemangioma'], ['hemangioma'], ['hemangioma', 'hemangiomas'], ['hemangioma', 'hemangiomas', '9', 'genitalia', 'treating'], ['hemangiomas', 'hemangioma', 'telangiectatic', 'life', 'cutaneous'], ['guang'], ['guang', 'selangor', 'kuang'], ['hemangiomas', 'hemangioma', 'haemangioma'], ['hemangiomas', 'hemangioma'], ['siang-khoe', 'shuang', '郑双)(born', 'hongwu', 'xiong'], ['mauzac-et-grand-castang', 'castang'], ['tsang'], ['hemangiomas', 'intracranial', 'illness', 'treatment'], ['zhuang'], ['luang', 'wetang', 'maluku']]
TOP TOKENS [['use', 'great', 'check'], ['href="https://www.teacherspayteachers.com/product/valentines-day-multiplication-and-division-task-cards-ccss-4th-5th-grades-4329360">here', 'gems!</a'], ['building', 'problems', 'put', 'throughout', 'anywhere', 'go'], ['building', 'problems', 'put', 'throughout', 'anywhere', 'go', 'problem'], ['designated', 'use', 'problems', 'solve', 'provided', 'answer', 'place', 'around', 'way', 'instead'], ['crazy', 'problems', 'count', '10s', 'especially'], ['used', 'answer', '•'], ['•write', '5’s'], ['outcomes', 'solve', 'answer', 'sheets', 'multiplying', 'problems', 'fractions', 'perfect', 'problem', 'correct', 'recording', 'solving', 'corresponding', '●3', 'use', 'thus', 'answers', '●1', 'eliminates'], ['problem', 'use', 'needed', 'spend', 'problems', 'used', 'tasks', 'cards', 'also', 'sounds', 'could', 'specific', 'time', 'people', 'check', 'work', 'would', 'love', 'hear', 'inch', 'still', 'one', 'well', 'day', 'even', 'like', 'take'], ['example', 'ok'], [], [], ['use', 'case', 'may', '9', '8', "player's", 'remaining', 'long', '3', 'table', 'run', 'come', '7', 'group', '6'], [], ['room', 'based'], ['rescue', 'sheerluck', 'edition'], [], [], ['july', '27']]
TOP TOKENS [['incorporado', 'things', '—', 'espectaculo'], ["company's", 'things', 'many', "there's", 'sorts', 'witnessed'], ['detailing', 'mostly', 'went', 'bills', 'things', 'wallet'], ["warrior's"], ['things', 'keep', 'given'], ["what's", 'whenever', 'things', 'spend', 'wondered'], ['things', 'guarda', 'gets'], ['liquid', 'surfacemotor', 'things', 'surgirpublic'], ['things', 'wondered', 'many', 'english', 'preguntas', 'powers', 'militarism', 'harness', 'form'], ['varied', 'things', '1970s', 'many', 'minted', 'much'], [], ['label', 'tribute', 'libyan', 'm-flo', 'magazine', 'mimics', 'specific', 'targeting', 'de', 'fm', 'american', 'album', 'ale', 'arrow', 'collection', 'ticket', "artist's", 'ticketing', 'english-language', 'paul'], ['2022'], ['2017'], ['dispersion', 'pledges', 'norwegian', '1995', 'fair', 'disambiguation', "player's", 'uniform', 'name', 'provider', 'given', 'list', "lloyd's"], ['featured', 'compiled', 'comments', 'based'], ['1968', 'set', 'album', 'smetana', '2011', 'korean'], ['fandom'], [], ['well']]
TOP TOKENS [['hazmats', 'hazmat', 'material', 'classifies'], ['hazmat'], ['hazmat', 'least', 'participants’', 'self-paced', 'pre-test', 'medically', 'post-test', 'healthcare', 'also'], ['hazmat', 'u', '’', '8', 'training', 'damage', '49', 'manage', 'biohazardous'], ['hazmat', 'differing', 'packagingfor', 'well'], ['hazmats', 'hazmat'], ['hazmat'], ['hazmat', 'incidents', 'initial', 'ocean', 'right'], ['hazmat', 'materialshazardshazmatincident', 'operator', 'specific'], ['hazmat'], ['hazmat'], ['hazmat', 'storyline', 'strange', 'mutant', 'avengers', 'jan', "marvel's", 'feb', '96', 'american', 'oct', '–', 'hazzard', '2001', "griffin's", 'surprise'], ['hazmat', 'chemicals', 'uncontaminated', 'respirators', 'versions', 'air', 'malayan'], ['hazmat', 'vehicle', 'non-miscible', 'typical'], ['hazmat', 'haz', 'alternatively', 'units', 'single', 'mat'], ['hazmat', 'cls'], ['hazmat', 'incomplete', 'cls', 'full', 'due', 'knowing', 'next', 'way', 'axe', 'forces', 'another', 'adam', 'office', 'butt', 'move'], ['hazmat', 'haz', 'every', 'one'], ['hazmat', 'least', '5107'], ['hazmat', 'groups', 'route', 'placard', '13', 'chemical', 'layer', 'greatest']]
TOP TOKENS [["goguryeo's", 'goguryeo', 'baekje', 'silla', 'century'], ['silla', 'baekje', 'also'], ['goguryeo', "goguryeo's", 'process', 'baekje'], ['goguryeo', "goguryeo's", 'baekje', 'silla', 'ally', 'east'], ['koguryeo', 'goguryeo', 'forces', 'claim'], ['goguryeo', "goguryeo's", "silla's"], ['goguryeo', 'koguryeo', 'baekje', '660', '667', 'centuries'], ['century', 'goguryeo', 'well', 'militarily', 'states', 'although', 'government', 'buyeo'], ['baekje', 'goguryeo', '433', "baekje's"], ['baekje', 'goguryeo', '433', "baekje's"], ['goguryeo', "goguryeo's", 'baekje', 'political', '655', '642'], ['goguryeo', 'kingdoms', 'beginning', '구리', '–'], ['koguryo', 'goguryeo', "goguryeo's", 'baekje', "sosurim's", 'korea', 'also'], ["baekje's", 'goguryeo', 'baekje', 'korean'], ['goguryeo', 'kingdoms', "china's", 'buyeo', 'baekje', 'enhances', 'including'], ['goguryeo', 'baekje', "means'seven'and", 'part', '635', 'sagi', 'buyeo', 'history', 'according'], ['koguryo', 'goguryeo', "goguryeo's", 'ancient', 'baekje', 'fortress', 'yamato', 'known'], ['goguryeo', "goguryeo's", 'kingdoms', 'buyeo', 'like', 'unk', 'silla', 'endonym'], ['goguryeo', 'baekje'], ['goguryeo', 'century', "goguryeo's", '7th', 'around', 'earlier', 'wei', 'kingdoms']]
TOP TOKENS [['patients', 'acids', 'nucleic', 'cd32a', 'sle', 'human', 'pdc', 'pathogenesis', 'ics', 'ifna', 'ic', 'leukocyte', 'fcgriia', 'cytokines'], ['patients', 'relapses', 'cells', 'autoantibody', 'antiperinuclear', 'autoantibodies', 'creatinine', 'sle', 'disease', 'antigenicity', 'dna', 'immune', 'condition', 'pdcs', 'infections'], ['patients', 'cases', '5p', '99a', 'macrophages', 'molecular', 'disease', 'oa', 'pbmcs', 'sle', 'diseases'], ['patients', 'mononucleosis', 'nucleosomes', 'erythematosus', 'scleroderma', 'cases', 'cell', 'sle', 'body', 'nucleus', 'forms', 'diseases', 'dsdnk'], ['patients', 'persons', 'nucleolar', 'sclerosis', 'drug', 'diseases', 'pattern', 'antibodies', 'sle', 'elisa', 'nephritis', 'lupus', 'syndrome', 'disease', 'centromere', 'idiopathic'], ['patients', 'antinuclear', 'antigen', 'ssa', 'sle', 'rnp', 'clinical', 'syndrome', 'disease', '●antiribosomal', 'antibodies', 'antiribosomal', 'dna', 'stranded', "on'clinical"], ['polymerase', 'ribonucleoproteins', 'patient', 'cytoplasmic', 'material', 'sle', 'polymorphonuclear', 'nuclear', 'dna', 'drug', 'autoantibodies', 'autoantibody', 'nuclei', 'clinically', 'pol', 'autoimmune', 'leukocyte', 'centromere', 'ena', 'pm1', 'phagocytosed', 'leukocytes'], ['patients', 'human', 'subjects', 'antinuclear', 'immune', 'autoantibodies', 'sle', 'monocytes', 'immunoinflammatory', 'pathogenic', 'vasculitis', 'pathogenesis', 'κb', 'cell'], ['patient', 'human', 'macromolecular', 'acid', 'chromosome', 'nucleic', 'polymerization', 'supranuclear', 'purifying', 'electrophoretic', 'microtubule', 'region', 'prepared', 'neurodegeneration', 'purified', 'concentrations', 'microtubules', 'cpt', 'psk41', 'encoding', 'pathogenic', 'gene', 'obtaining', 'orit', 'footprinting'], ['patients', 'cytoplasmic', 'antineutrophil', 'plasminogen', 'antinuclear', 'pathogenesis', 'antimitochondrial', 'ena', 'citrullinated', 'protein', 'autoantibodies', 'diseases', 'dsdna', 'peptide', 'trypsin', 'ccp', 'pancreatitis', 'bogdanos', 'kriese', 'k', 'ana', 'secretory', 'rheumatic', 'burroughs', 'antibodies', 'autoimmune', 'koutsoumpas'], ['molecules', 'nucleosomal', 'nucleosomes', 'patients', 'c1q', 'autoantibodies', 'cellular', 'cells', 'individuals', 'nucleus', 'proteins', 'rheumatoid', 'antigens', 'people', 'laminin', 'glomerular', 'within'], ['leukocyte', 'cytoplasmic', 'individuals', 'cases', 'aminoacyl', 'human', 'molecular', 'nuclear', 'polypeptides', 'trna', 'cell', 'synthetase', 'epstein', 'rheumatic', 'scleroderma', 'diseases', 'components', 'nephritis', 'histidyl', 'dermatomyositis', 'hla', 'activity'], ['nuclear', 'phosphorylation', 'diseases', 'disease', 'molecule', 'autoimmune', 'ifn', 'cns', 'phosphorylated', 'pathogenesis', 'usp18', 'erythematosus'], ['molecule', 'human', 'chains', '2xrc', 'asn', 'c3', 'omim', 'diseases', 'clinical', 'peptidases', 'complement', 'glycosylation', 'cases', 'pathway', 'uremic', 'unregulated', 'overactivation', 'rearrangement', 'factor', 'activity', 'incubated'], ['people', 'human', 'ribonucleoprotein', 'molecular', 'individuals', 'ribonucleoproteins', 'u6', 'sle', 'proteins', 'snrnps', 'nuclear', 'polymerase', 'cells', 'clinical', "b'and", 'epstein', 'pericarditis', 'immune', 'disease'], ['nucleosome', 'people', 'scleroderma', 'cases', 'nuclear', 'cells', 'glycoprotein', 'nephritis', 'cell', 'membrane', 'fibronectin', 'nucleoporin', 'disease', 'within', 'glomerular', 'drug', 'sle', 'heparan', 'lupus', 'laminin', 'idiopathic', 'proteins', 'h2a'], ['nucleotide', 'pathogenic', 'complement', 'cells', 'microbial', 'autoimmune', 'diseases', 'residue', 'host', 'infections', 'activity', 'clinical', 'protein', 'amd', 'susceptibility', 'factor', 'healthy', 'macular', 'tryptophan', 'atomic', 'aberrant', 'virulence', 'ccps', '13', 'p', 'underactive', 'present', 'groups', '12', 'may'], ['patients', 'syndrome', 'clinical', 'p21', 'proteasomes', 'disease', 'human', 'autoimmune', 'rheumatoid', 'sle', 'applied', 'stability', 'biomarkers'], ['macroglobulinemia', 'molecules', 'kinase', 'cells', 'autoimmune', 'catenin', 'mapk', 'protein', 'carbohydrate', 'erk', 'cryoglobulinemia', 'cd40', 'pathways'], ['people', 'molecular', 'process', 'relapses', 'macrophages', 'cd166', 'leukocyte', 'metalloproteinases', 'biochemical', 'monocyte', 'peroxynitrite', 'molecules', 'case', 'cxcl13', 'physiological', 'spms', 'ppms', 'cxcl12', 'nanoparticles', 'cells', 'lps', 'protein', 'therapeutic', 'causative', 'cell', 'molecule', 'mmp', 'inactivation']]
TOP TOKENS [['historically', "the'nineties", 'meanwhile', 'eschatological', 'subsequently', 'solution', 'historical', 'supernatural', 'contemporary'], ["not'broken'at", 'women', 'mythical', 'therefore', 'allegorically', 'historical', 'christians', 'biblical', 'man'], ['historical', 'mythological', 'corinthians', 'historicity', 'alive', 'history', 'eve', 'real', 'human'], ['earthly', 'world', 'bible', 'difficulty', '6', 'rev', 'unambiguously', 'either', 'says', 'prophetically', 'earth'], ['justinian', 'logically', 'rightly', 'theoria', 'natures', 'divine', 'tritheists', 'thus', 'theandric', 'even', 'fact'], ['simply', 'thus', 'immature', 'divinity', 'mature', 'god', 'irenaeus', 'since', 'therefore', 'life', 'sent', 'spread', 'time'], ['causally', 'divine', 'incidental', 'biblical', 'ancient', 'historical', 'world', 'transgression', 'cosmic', 'natural', 'history', 'quite'], ['worlds', 'celestial', 'cosmogonic', 'matter', 'hypostatically', 'enigmatic', 'yet', 'humanity', 'element', 'corporeality', 'unknowable', 'thus', 'aeon', 'existent', 'abortive', 'clearly', 'distinct', 'aeons', 'anthropos'], ['eschatological', 'one', "adam'itself", 'gichtelian', 'testament', 'irremediably', 'ontological', 'eckhartian', 'androgyne', 'anthropomorphic', 'since', 'later', "can't", 'destinies', "thought'and", 'human', 'divine', 'therefore'], ['cosmic', 'past', 'one'], ['things', 'temporal', 'eternal', 'devil', 'would', 'traditional', 'something', 'euphemism', 'interpretive', '47', 'holy', 'history', 'woman', "history's", '22'], ["to'historical", 'divine', 'metaphysical', 'historical', "an'absolute'time", 'heaven', '‘', '“', 'original', 'present', 'result', 'rather'], ['celestial', 'worlds', 'cosmogonic', 'world', 'matter', 'valentinian', 'enigmatic', 'hypostatically', 'yet', 'corporeality', 'aeon', 'thus', 'humanity', 'element', 'aeons', 'anthropos', 'forth'], ['bible', 'ecclesiasticus', "god's", 'biblical', "paul's", 'logically', '12', 'joyfully', 'world', 'genesis'], ['eschatological', 'divine', "paul's", 'incarnate', 'johannine', 'irenaeus', 'cosmic', 'christology', 'patristic', 'also', 'adam', 'human', 'nativity', 'following', 'birth', 'person', 'man', 'age'], ['fathers', 'effected', 'juridical', 'supernatural'], ['history', 'terrestrial', 'dualistic', 'world', "god's", 'matter', 'yet', 'divine', 'inevitability', 'within', 'good', 'precipitated', 'whenever', 'contingently', 'happen'], ['testamental', 'like', 'irenaeus', 'earth', 'valentinianism', 'valentinian', 'humans', 'deity', 'god', 'evil', 'scholars', 'ignorant'], ['heavenly', 'patristic', 'creaturely', 'historical', "adam's", 'atemporal', 'christian', 'divine', 'temporal', 'possible', 'differentiations'], ['historical', 'dostoyevskian', 'theistic', '3', 'history', 'biblical', 'b', 'humans', 'universe', 'several', 'atemporal', 'early', 'creatio', 'fathers', 'actually', 'wm']]
TOP TOKENS [['abundance', 'diversity', 'species', 'distribution', 'relative', '86'], ['diversity', 'richness', 'abundance', 'species', 'higher', 'abundances', 'biodiversity'], ['richness', 'composition', 'diversity', 'determine', 'compositional', 'species', 'scale', 'compositions', 'greater', 'median', '450', 'identified'], ['richness', 'diversity', 'species'], ['species', 'richness', 'abundance', 'composition', 'diversity', 'increased', 'analysis', 'expected', 'estimation', 'total', 'patterns', 'community', 'investigate'], ['richness', 'species', 'taxonomic', 'diversity', 'beta-diversity', 'measure', 'biodiversity', 'assess', 'alpha-diverse', 'over-represented'], ['composition', 'diversity', 'richness', 'explained', 'values', 'species', 'heterogeneity', 'increase', 'significantly'], ['diversity', 'species', 'taxonomic', 'predicting'], ['abundance', 'richness', 'diversity', 'species'], ['richness', 'species', 'increases', 'total', 'assemblage'], ['richness', 'species', 'diversity', 'abundances', 'abundance', 'distributions'], ['richness', 'species', 'endemic', 'rare', 'common', 'area', 'widespread'], ['richness', 'abundance', 'species', 'diversity', 'abundant', 'quantifies', 'indices', 'quantify', 'areas', 'least'], ['composition', 'diversity', 'species', 'patterns', 'biodiversity', 'higher', 'relative', 'diversification', 'studies', 'predicted', 'events'], ['richness', 'higher', 'diversity', 'species', 'peaks', 'patterns', 'lists', 'suggest', 'rich', 'ultimately'], ['abundance', 'diversity', 'abundant', 'abundances', 'richness', 'species', 'least', 'smaller', 'taxonomic'], ['abundances', 'composition', 'diversity', 'α-diversity', 'β-diversity', 'taxonomic', 'ζ-diversity', 'overlap', 'biodiversity', 'describing', 'held', 'common', 'measures'], ['abundance', 'diversity', 'richness', 'species', 'rarity', 'biodiversity', 'determine', 'estimating', 'commonness'], ['richness', 'species', 'abundances', 'diversity', 'abundant', 'abundance', 'list', 'exceed', 'indices', 'rare', 'popular', 'contains', 'equally'], ['richness', 'abundance', 'abundant', 'abundances', 'composition', 'species', 'percent', 'rare', 'rank', 'common', 'patterns', 'compete']]

Processing features:  32%|███▏      | 31/98 [14:52<33:42, 30.19s/it]

getting sample prompt for 23772
getting sample prompt for 23773
getting sample prompt for 23774
getting sample prompt for 23775
getting sample prompt for 23776
getting sample prompt for 23777
getting sample prompt for 23778
getting sample prompt for 23779
getting sample prompt for 23780
getting sample prompt for 23781
getting sample prompt for 23782
getting sample prompt for 23783
TOP TOKENS [['hope', 'since', 'contribute', 'saw', 'work'], ['lane', "a'a", 'example', 'hihohiho', 'thoughts', 'look', 'really', 'meet', 'sep', 'demanding'], ['anti', 'joint', 'executive', 'extradition', 'countries', '2014', 'one', 'late', 'representative', 'except'], ['center', 'advocate', 'chicago', 'children'], ['may', 'become', 'place', 'space', 'could', 'good', 'l', 'create', 'practice', 'opportunities', 'learning', 'build', 'one', 'helps'], ['1838', '1918'], ['person', 'intimate', 'like', 'get', 'one', 'experience', 'hopefulness'], ['could', 'block', 'oral', 'finally', 'city', 'projected', 'audience', 'sep'], ['republic', 'hope'], ['initiative', 'else', 'people', 'particularly', 'someone', 'details', 'think', 'get', 'really', 'haiti', 'specific', 'helpful', 'definitely', '’', 'helping', 'despite', 'possible', 'idea', 'help', 'thinks', 'hours', 'many', 'year', 'affected', 'awesome', 'one'], ['2', '27', 'record', 'rout', '5', 'notched', 'starts', '28', 'struck', 'batted', '3', '–', 'focus', '11', '78', 'managed', 'earning', 'made', '4', 'april', 'eight', '8', 'took', '65', 'posting', 'september', 'pitched', '2016', '82', 'july'], ['collaboration', 'organization', 'ballade', 'learning'], ['2022', '15', '4', '314', 'pandemic', 'games', 'achieve', 'country', '392', 'hitting', '11', 'reaching', '10', 'july', '2017', 'season'], ['anti', '1982', 'civil', 'administrative', 'klaverns', 'prominent', 'sphere', 'actively', 'group', 'beyond', 'government', 'klan', 'well', '1971', "black's", 'confining', 'views', 'nearly'], ['act', 'acts', 'employee', 'comedie', 'bossu', 'anicet', "l'ambigu", 'jouslin', 'auberge', 'partie', 'cornu', 'lurieu', 'l', 'worked', 'gymnase', 'ambigu', 'comique', 'acteurs', 'nationale', 'actes', 'action', 'entered', 'de', 'la', 'achille', 'vaudeville', 'royal', '1830', 'parts', '1794', 'met', 'scribe', 'vaudevilles', 'bourgeois', 'lithographies', 'varietes', "l'enfant", 'etc', 'consolations'], ['2022', 'http://www.jibujacob.com', '2014', '2013', 'k', 'long', '2002', 'highest-grossing', 'vellimoonga', 'time', 'made', 'cinematographer', 'success', 'later', 'industry', 'people'], ['2', 'record', '7', '52', '22', '27', '24', 'bones', 'appearances', 'games', 'pitched'], ['2', 'seibu', '12', '2017', '9', 'toronto', '22', '11', 'contract', 'expansion', 'part', '1', 'league'], ['intellectuals', 'part', '1982', 'parliament', 'kamal', 'jumblatt', 'took', 'towards', '17', 'october', 'led', 'activities', 'attitude', 'national', 'maronites', 'elected', 'positive', 'became', 'left-wing', "party's", 'policies', 'people', 'lebanese', '1971', 'april'], ['2', '19', '10', "cardinals'walk", 'struck', '–', 'four', 'august', 'despite', 'official', '62', '12', 'month', 'appearances', 'made']]
TOP TOKENS [['comedians', 'comedian', 'standup', 'comedy'], ['comedians', 'standup', 'show', 'stand', 'comedy', 'performing', 'fortunately'], ['stand', 'comedian', 'comic', 'comedy', 'performed', 'show'], ['standup', 'comedians', 'comedy', 'comedian', 'shows', 'act', 'performing', 'routine', 'supported', 'period', 'toured', 'members'], ['stand-up', 'comedians', 'routines', 'comedy', 'jokes', 'routine', 'joke', 'seinfeld', 'you’ve'], ['stand', 'comedians', 'comedian', 'comedy', 'perform', 'performances', 'clubs'], ['stand', 'comedian', 'comedians', 'letterman', 'comedy', 'show'], ['stand', 'comedians', 'many', 'comedy', 'american', 'actors', 'shows', 'seinfeld'], ['comedians', 'stand', 'comedy', 'perform', 'performing', 'theater', 'colbert', 'improv', '1983', 'one', 'comedysportz', "johnstone's", 'performed', 'sedaris', 'stars'], ['stand', 'comedian', 'comedians', 'comedy'], ['stand', 'comedians', "comedian's", 'cls', 'comedian', 'vaudeville', 'ups', 'comedy', 'humorists', 'performers', 'clubs', "performers'most"], ['stand-up'], ['comedian', 'stand', 'comedy', 'vaudeville', 'performer', 'club'], [], ['comedian', 'stand-up', 'comedians', 'stand'], ['comedians', 'stand', 'comedy', 'vaudeville', 'show', 'acts', 'performances', 'shows', 'performers', 'act', 'touring'], ['comedians', 'stand', 'performers', 'comedy', 'vaudeville', 'comic', 'performed', 'show', 'live'], ['stand-up'], ['comedian', 'stand', 'comedians', 'ups', "comedian's", 'comedy', 'spagnolli', 'show', 'conventions', 'joke'], ['stand', 'comedian', 'comedians', 'comedy', "comic's", 'show', 'performance', 'act']]
TOP TOKENS [['mumps', 'vaccine'], ['mumps', 'inflammation'], ['mumps', 'myocarditis'], ['mumps'], ['mumps', 'spaces', 'campuses', 'serious', 'sneeze', 'close-quarters'], ['mumps', 'cheeks’'], ['mumps'], ['mumps'], ['mumps', 'study', 'person', 'following'], ['mumps', 'mump', 'mumpa', 'ears', 'areas', 'rarely'], ['mumps', 'disease', 'closer'], ['mumps', 'mumpsvax'], ['mumps', 'individuals', 'person', 'body', 'virus'], ['mumps', 'mump', 'vaccines', 'certain', 'causes', 'republic'], ['mumps', 'get', 'infection', 'person', 'one', 'oophoritis', '2', 'people'], ['mumps', 'membranes', 'symptoms', 'affected', 'contract'], ['mumps', 'critics', 'reviews', 'brandon', 'mcdiarmid', '–', 'mike', 'brent', 'quartet', 'place'], ['mumper'], ['mumps', 'develop', 'intramuscular', 'patients', 'inflammatory', 'vaccines', 'light'], ['mumps', 'status', 'populations', 'vaccination']]
TOP TOKENS [['regiment', 'word'], ['regiment', 'word', 'regiments'], ['regiment', 'regimentum', 'regiments2', 'controlregimentaladj.regimentallyadv.regimentationn', 'rej′ə'], ['regiments', 'regiment'], ['regiment', 'regiments'], ['regiment', 'siege'], ['regiment', 'siege'], ['regiment', 'history', '1758', 'war', 'germany'], ['regiment', 'regimental'], ['regiment', 'regiments', 'word', 'regimental', 'lived', 'term', 'immemorial', 'spain', 'however'], ['regiment'], ['regiment', 'regiments', 'term', 'e', 'word'], ['regiment'], ['regiment'], ['regiment', 'regiments', 'régiment'], ['regiment', 'regiments', "regiments'field", 'regimental', 'cls'], ['regiment'], ['regiment'], ['regiment', 'sometimes', 'development'], ['regiment', "regiment's", 'caractacus']]
TOP TOKENS [['fulfilled', 'lawsuit', 'sue', 'suing', 'array', 'necessary', 'consider', 'files', 'file', 'sort'], ['lawsuit', 'party', 'resolve', 'litigation', 'files', 'parties', 'damage'], ['potential', 'sue', 'actually', 'lawsuits', 'lawsuit', 'sued', 'rule', 'far', 'vaccinate', 'became', 'authorizing', 'arduous'], ['potential', 'sue', 'actually', 'lawsuits', 'lawsuit', 'sued', 'rule', 'far', 'vaccinate', 'became', 'authorizing', 'arduous'], ['lawsuits'], ['lawsuit', 'liability', 'number', 'presented', 'also', 'file', 'judgment', 'suing', 'suits', 'product', 'usually', 'case'], ['sue', 'suing', 'lawsuit', 'litigation', 'argument', 'party'], ['sue', 'lawsuit', 'issues', 'lawsuits', 'unlikely', 'worried', 'possible', 'suing', 'concern', 'begin', 'could', 'uphold', 'individuals', 'though', 'might', 'communities', 'problem'], ['sue', 'lawsuit', 'issues', 'lawsuits', 'unlikely', 'worried', 'possible', 'suing', 'concern', 'begin', 'could', 'uphold', 'individuals', 'though', 'might', 'communities', 'problem'], ['sue', 'suing', 'lawsuit', 'argument'], ['lawsuit', 'claims', 'organizations', 'act', 'litigation', 'disputes', 'one', 'actions', "plaintiff's", 'law', 'sue', 'still', 'favor', 'suit'], ['several', 'suits', 'lawsuits', 'lawsuit', 'newer', 'suit', 'community', 'two', 'ventura', 'filed', 'handful', 'fourth', 'sixth', 'behalf', 'also', 'first', 'one', 'states', 'fifth'], ['similar', "orthodontist's", 'lawsuit', 'sue', 'brought', 'suit', 'authorize', 'ridiculed', 'action', 'bring', 'filed', 'lawsuits', 'merits', 'filing', 'designed'], ['litigation', 'lawsuits', 'list', 'security'], ['lawsuit', 'action', 'lawsuits', 'current', 'litigation', "workers'lawsuit", 'suits', 'class', 'suit', 'fuqi', 'everbank'], ['lawsuit', 'sue', 'file', 'individuals'], ['lawsuit', 'filed', 'filing', 'suit', '2015', 'litigation', 'moot', 'file', 'brought', "plaintiff's", 'january', 'november', '18'], ['grove', 'lawsuit', 'entities', 'lawsuits', 'armley', 'environmental', 'distinction', 'entity', 'south', 'action', 'class', 'west', 'manufacturers', '§'], ['lawsuit', 'suit'], ['lawsuit', 'another', 'judge', 'filed', '25', 'plaintiff', '2022', 'tarts', '2021', 'june', 'would', 'butter', 'purchased', 'impact', 'dismissed', 'claiming', 'cereals', 'began', "methylnaphthalene's"]]
TOP TOKENS [['different', 'radically', 'life', 'first', 'another', 'planet', 'works'], ['lenient', 'rearranged', 'times', 'recluse', 'hero', 'story'], [], ['orphan', 'hands', 'misdirected', 'xxi', 'falls', 'denouement', 'might', 'less'], ['orphan', 'hands', 'misdirected', 'xxi', 'falls', 'denouement', 'might', 'less'], ['version', 'weir', 'two'], ['fate', 'shipwrecked', 'life', 'wady', 'quite', 'local', 'isis', 'nebhat', 'comes'], ['‘incorrect’', 'usages', 'actually', 'two', 'original', 'changed', '302', 'succeeded', 'like', 'permanently', 'use', 'ways', 'implicitly'], ['8pm'], ['one', 'thought', 'even', 'real', 'got', 'people'], ['john', 'english', '1616–1681', 'george', '1619–1682', '1896–1924'], ['signed', 'january', 'club', '13', 'october', 'superdraft', 'danville', 'born', 'links', 'deal', '19', 'year', 'professional', 'u', '2010', 'soon', 'plays', 'eventual', '18', 'season', '2009', 'due', 'first', '5', 'cls', '2011', 'bingham'], ['2021', 'signed', 'ortiz', 'states', 'births', 'january', '2016', 'february', '2020', "men's", 'born', 'people', '9', 'players', 'football', 'links', 'american', '28', 'end', 'season', 'association', 'academy', 'bio', 'club', 'august', 'college', '4'], ['league', 'august', 'mexicali', 'players', 'deadline', '17', '22', 'sox', 'run'], ['contract', 'end', 'f.c', 'danny', 'links', 'one', 'career', 'professional', 'born', 'semi-final', 'rangers'], ['2020', '8', '2021', 'signed', 'players', 'american', 'people', '1', 'baseball'], ['8', 'august', '2010', 'signed', '2013', 'january', '2011', '2014', '9', '2016', '1', '10', 'blazers', '2012'], ['happened', 'later', 'cf', 'city'], ['contract', 'signed', 'tribeathletics', 'day', 'miami', '2', '8', 'played', 'october', 'player', '20100804094259', 'born', '2021', 'archive', 'school', 'web', 'com', 'goal', 'https', 'also', 'http', '10', '2010'], ['born', 'career', "men's", "newell's"]]
TOP TOKENS [['intensive', 'critical', 'icu', 'care', 'critically'], ['intensive', 'icu', 'critically', 'critical', 'icus', 'ill', 'care', 'severely'], ['intensive', 'critical', 'icu', 'ct-icu', 'care'], ['intensive', 'icu', 'critical', 'care'], ['icu', 'intensive', 'critically', 'intensivecarehotline', 'ill', 'care'], ['icu', 'critically', 'intensive', 'critical', 'ill', 'icus', 'care'], ['intensive', 'icu', 'critical', 'care', 'ventilators'], ['icu', 'intensive', 'icus', 'critical', 'care'], ['icu', 'intensive', 'critically', 'critical', 'ill', 'care'], ['intensive', 'critical', 'critically', 'care', 'ill', 'icu', 'cls', 'mechanical', 'wean'], ['intensive', 'icu', 'icus', 'critical', 'critically', 'care', 'seriously'], ['intensive', 'intensive-care', 'critical', 'critically', 'ill'], ['icu', 'intensive', 'care', 'severely', 'medical'], ['intensive', 'care', 'icu', 'hospital'], ['critical', 'intensive'], ['icu', 'intensive', 'icus', 'critically', 'critical', 'care', 'within'], ['intensive', 'intensive-care', 'critical', 'care', 'human'], ['intensive', 'icu', "icu's", 'critical', 'care'], ['critical', 'icu', 'illness', 'following'], ['intensive', 'critical', 'care']]
TOP TOKENS [['quarantine', 'quarantined'], ['quarantine', '“quarantine”', 'etc'], ['quarantine', 'quarantined', 'putting'], ['quarantine', 'etc'], ['quarantine', 'quarantined', 'see', 'disambiguation', 'natural'], ['quarantined', 'quarantine', 'clothing', 'feeling'], ['quarantining', 'quarantine', 'pathogens'], ['quarantine', 'quarantines', 'accompany'], ['quarantine', 'quarantined', 'quarantines', 'quaranta'], ['quarantine', 'quarantining', 'quarantined'], ['quarantine', 'quarantined', 'infection', 'quarantines', '1983'], ['quarantine', 'quarantines'], ['quarantine'], ['quarantine'], ['quarantine', 'enjoy', 'media', 'uses', 'conceit'], ['quarantined', 'mott', 'wilbur', 'dr', 'group'], ['quarantine', 'result', 'material', 'sequel', 'cls', 'features', 'leave', 'immigrant', "building's", 'angela'], ['quarantine', 'resolve', 'world', 'unfolds', 'human'], ['quarantine', 'advance', 'would', 'required', 'subtitled', 'consists', 'replenishes', "player's"], ['quarantine']]
TOP TOKENS [['adirondacks', 'adirondack'], ['adirondacks', 'adironda', 'adirondack'], ['adirondack'], ['adirondacks', 'adirondack', 'adirondack.net'], ['adirondacks', 'adirondack'], ['adirondack', 'adirondacks'], ['adirondack'], ['adirondacks', 'adirondack', "adirondack'originated"], ['adirondacks', 'adirondack', 'h'], ['adirondacks', 'adirondack', 'shoes'], ['adirondack'], ['adirondack'], ['adirondack', 'adirondacks', 'wolpin'], ['adirondack', 'adirondacks'], ['adirondack', 'country', 'hoss', 'wild', "kelly's", 'sargent'], ['adirondack', 'adirondacks', 'bark', "eastlake's"], ['adirondacks', 'adirondack', 'adirondakx', 'den', 'word', 'south', 'algonquians'], ['adirondacks', 'adirondack'], ['adirondack', 'adirondacks'], ['adirondack', 'adirondacks', 'schibli', 'four']]
TOP TOKENS [['passengers', 'passenger', 'attendant', 'surly', 'unruly', 'attendants', 'flight', 'cabin'], ['passengers', 'luggage', 'attendant', 'passenger', 'attendants', 'seats', 'cabin'], ['passengers', 'passenger', 'luggage', 'attendants', 'travelers', 'apprehensive', 'crew', 'attendant', 'board', 'cabin'], ['passengers', 'passenger', 'attendants', 'luggage', 'cabin', 'seats', 'board'], ['passengers', 'attendants', 'attendant', 'luggage', 'cabin', 'flight', 'assist'], ['passengers', 'luggage', 'seats', 'attendant', 'let', 'kind'], ['passengers', 'attendant'], ['passenger', 'travelers', 'airlines', 'passports', 'carriers', 'data', 'travel', 'security'], ['passengers', "attendant's", 'luggage', 'fellow', 'attendant', 'enter', 'flight'], ['passengers', 'passenger', 'aboard', 'attendants', "passengers'comfort", 'luggage', 'seats', 'board', 'personnel', 'attendant', "attendant's"], ['passengers', 'passenger', 'eric', 'film'], ['passenger', 'passengers', 'luggage', 'boarding', 'onto', 'bags', 'seats', 'load', 'security', 'contact', 'terminal', 'flight', 'ride'], ['passengers', 'passenger', 'non-passenger'], ['attendant', 'passengers', 'flight', 'employees', "passenger's", 'passenger', 'crew', 'flying', 'airline', 'members', 'steward', 'board', 'traffic', 'airliners', 'driver'], ['passengers', 'passenger', 'cabin', 'anxiety', 'attendant', 'attendants', 'flight', 'board', 'stricken', 'seat', 'disembark', 'cockpit'], ['passengers', 'passenger', 'attendant', 'cabin', 'crew', 'attendants', 'stewards', 'flight', 'transportation', 'board', 'cockpit', 'male', 'steward', "ships'personnel", 'personnel'], ['passengers', 'passenger', 'baggage', 'seats', 'attendants', 'cabin', 'attendant', 'vips', 'disembark', 'board', 'armrests', 'stowed', 'boarding'], ['passengers', 'passenger', 'cabin', 'attendants', 'attendant', 'crew', 'flight', "attendants'in", 'lives', 'pakistani', 'members', 'stewardess', 'airlines', 'transportation', 'protect', 'staff'], ['passengers', 'passenger', 'luggage', "passengers'address", 'baggage', 'checked', 'security', 'cabin', 'boarding', 'seat'], ['passenger', 'passengers', 'board', 'baggage', "passengers'address", 'luggage', 'boarding', 'carry', 'cargo', 'cabin', 'approves']]
TOP TOKENS [['injuries', 'sports', 'basketball', 'common', 'range'], ['injuries', 'basketball', 'plays', 'play', 'common', 'facial', 'hamstring', 'athlete'], ['injuries', 'injury'], ['injuries', 'injury', 'common', 'basketball', 'play', 'playing', 'injured'], ['injuries', 'sports', 'injury', 'damage', 'common', 'damaged', 'get'], ['injuries', 'playing', 'sport', 'play', 'sports', 'injury', 'game', 'hockey', 'foot', 'aches', 'cls', 'tackling'], ['injury', 'sports', 'injuries', 'basketball', 'chronic', 'musculoskeletal', 'common'], ['injuries', 'common', 'sustained', 'gameplay', 'injury', 'play', 'game', 'playing'], ['sports', 'injured', 'athletic', 'injuries', 'cls', 'every', 'player', 'damage', 'injury', 'sport'], ['injuries', 'common', 'injury', 'basketball', 'playing', 'rice', 'foot'], ['sports', 'injuries', 'sport', 'injury', 'cls', 'athletic', 'injured'], ['sports', 'injuries', 'sport', 'injured', 'many', 'injury', "men's", 'competitive', 'gymnastics'], ['injuries', 'injury', 'sports', 'athletic', 'play', 'risk', 'sport', 'valgus', 'practices', 'games', 'tears', 'risks', 'overuse'], ['injuries', 'play', 'injured', 'games', 'tendinitis', 'sprained', 'barbosa', 'lampe', 'bruised', 'inflammation'], ['play', 'ligament', 'damage', 'injured', 'sprained', 'bruised', 'game', 'tendinitis', 'reserve', 'williams', 'foot', 'loren', 'finger', 'sam'], ['game', 'despite', 'injury', 'every', 'suffered', 'suspecting', 'damage', 'ankle', 'playing', 'waterskiing', 'nerve', 'drills', 'games', 'pain', 'played', 'noticed', 'season', '1959', 'one', 'short', 'athletic', 'loss', 'cut', 'pulled'], ['injury', 'games', 'ankle', 'miss', 'led', 'game', 'season', 'play', 'year', 'losses', '–', 'team', 'bears', "mirkovic's", 'colorado', 'beach', 'conference', 'schedule'], ['game', 'injuries', 'injury', 'common', 'commonly', 'injured', 'knee', 'playing'], ['injuries', 'playing', 'injured', 'game', "team's", 'games', 'season', 'snap', 'pregame', 'career', 'warmups', 'suffered', 'contract', "collier's", 'ended', 'lost', 'single', 'franchise', 'months', 'missed', 'recession', 'years', 'television'], ['injuries', 'play', 'games', 'tissue', 'injury', 'common', 'sports', 'including', 'suffer', 'career', 'sport', 'surgery', 'however', 'game', 'issues', 'problems']]

Processing features:  33%|███▎      | 32/98 [15:21<32:47, 29.81s/it]

getting sample prompt forgetting sample prompt for 23785
 23784
getting sample prompt for 23786
getting sample prompt for 23787
getting sample prompt for 23788
getting sample prompt for 23789
getting sample prompt for 23790
getting sample prompt for 23791
getting sample prompt for 23792
getting sample prompt for 23793
getting sample prompt for 23794
getting sample prompt for 23795
TOP TOKENS [['iep', 'programs'], ['iep', 'ieps', 'clicking', 'agencies', 'happening', 'clear', 'however', 'program', 'challenging', 'often'], ['iep', 'ieps', 'identifiable', 'w', 'basics'], ['ieps', 'iep', '’', 'tendency', 'also', 'faith', 'yes', '”'], ['iep', 'ieps'], ['iep', 'ieps', 'ever'], ['iep', 'ieps', 'ever'], ['iep', 'ieps', 'objectives', 'entirety', 'may', 'goals'], ['iep', 'nonacademic', 'think', 'needs', 'education'], ['iep', 'upon', 'needs', 'right', 'must'], ['1954', 'ien', '1931–1994', 'iens'], [], ['i.e.m', 'music', 'iem', 'incredible', 'international', 'explaining', 'expanding', 'mathematics'], ['institutes'], ['ier', 'hungary'], [], ['ieac'], [], [], ['car', 'iena', 'iéna']]
TOP TOKENS [['wonder', 'sep', 'line'], ['migrating', 'every', 'almost', 'disheartened', 'southward'], ['previous', 'shows'], [], ['row', 'followed', 'sep'], [], [], ['ever', 'optimizes', 'code', 'sep'], ['0rvorpbma', 'https'], ['cls', 'two'], ['heliozela', 'heliozelidae', 'markings', 'grey', 'family'], [], ['heliozela', 'j', '2015', 'found', 'heliozelidae', 'references', 'africa', 'family'], ['mixosemia', 'borneo', 'geometridae', 'described'], ['ara', 'episode', 'sep', 'youtube'], [], ['references', 'wiltshire', 'menetries', 'ronkay', '2003', 'staudinger', 'nilotica', 'heliothidia', 'panaceorum', 'maritima', 'fletcheri', 'armadini', 'armada', '1912', 'fibiger', 'philbyi'], [], [], ['family', '2015', 'boards']]
TOP TOKENS [['montesquieu', 'mores', 'various', 'enlightenment', 'c', 'england', 'revolutionaries', 'noblemen', 'cls', 'etc'], ['montesquieu', 'individual', 'de', 'significantly'], ['montesquieu', 'graduating', 'consider', 'upon', 'minded', 'cls'], ["montesquieu's", 'montesquieu', 'spirit', 'death', 'grandeur', 'feudalism', 'adopted', 'cls', 'reinterpreting', 'models', 'thus', 'described'], ['montesquieu', 'life', 'thought', 'laws', 'however', 'surrendering', 'responsible'], ['montesquieu', 'montesquieu-the'], ['montesquieu', 'montesquieu’s', 'book', 'however'], ['montesquieu', 'de', 'humaines', 'chez', '’', 'spector', 'lii', 'spip', 'pouvoirs'], ['montesquieu', 'tongues', 'status', 'cls', 'endeavors', 'following', 'however', 'celebrated', 'scientific', '”', 'would'], ["montesquieu's", 'montesquieu', 'hand'], ['montesquieu'], ['montesquieu', 'montesquiu'], ['montesquieu', "montesqui's", 'regarding', '“'], ['montesquieu', 'montesquiu', 'de'], ['montesquieu', "montesquieu's", 'caricatured', 'pangle', 'de', 'rubrique186', "l'esprit", 'encyclopedia', 'stanford', 'spip', 'catherine', 'laws', 'cambridge', 'mason', 'hulliung'], ['montesquieu', '“', 'ed', '’', 'eds', '693', 'hulliung'], ["montesquieu's", 'montesquieu', 'britain', 'pocock', 'powers', 'considered', 'views', 'history', 'many', 'lutz', 'minimized'], ['montesquieu', "montesquieu's", 'companion', 'work', 'impact', 'seignorial', 'reflected', 'impediments', 'outwardly', 'great'], ['montesquieu', "montesquieu's", 'years', 'impact', 'simply', 'de', 'constitution', 'brought', '1689', '–', '1716', 'biography'], ['montesquiou', 'montesquiu']]
TOP TOKENS [['phrygian', 'contains', '’', '‘'], [], ['phrygian', 'point', 'tonalities', 'aeolian', 'mixolydian', 'iii', 'sixth', 'seen', 'authors', 'answer', 'misleads', 'e'], ['10', '11', 'þu', '12', 'beo', 'aeolian', '9', 'name', 'century', 'hypoionian', 'dodecachordon', 'case', 'example', 'finalis', 'time', '8', 'back', 'reason', '–', 'show', 'putative'], ["margin'there", 'case', "balrogs'to'his", 'one', 'devised', 'least', 'etc'], ['also', 'may', '2', '3', 'known', 'mode', 'phrygian', 'p', 'presented', '5', 'pythagorean', 'found', 'considering', 'one', 'involving', '1989', 'therefore', 'primes', 'mcclain', 'see', '1976', 'godwin', 'lauer', 'etc', '7'], ['29', '4', 'aeolian', 'exist', 'variations', '5', 'phrygian', '2016', 'one'], ['cls', 'phrygian', 'flavours', 'us', 'commonly', 'many', 'although', 'thing', 'mainly', 'scales', '2nd', 'uses'], ['phrygian', 'lydian', 'dorian', 'mixolydian', 'aeolian', '’', 'ionian', 'given', '4', '—', 'much', '”', 'b2', 'formula', 'like', 'grand', 'leaves', 'applies', 'theory', 'b5', 'locrian', 'respectively'], ['tonoi', 'iii', 'jeffery', 'tyrrell', 'aristoxenian', 'theory', 'dictionaries', 'j', '2001', '56159', '2', '6', '§', 'york', '’', 'oktoechos', 'synthesis', 'music', 'musicians', 'london', 'powers', 'edition', 'edited', 'publishers', '1', 'mathiesen'], ['nephthys', 'sekhem', 'horus', '3', 'ankh', 'slightly', 'shu', '1:03', '2', 'epilogue', '1:11', '7:41', 'thoth', '10:43', "maat's", 'hapi', '5:11', '1:27', 'feather', '5:15', '1:31', '0:45', 'nut', '0:40', 'osiris', '1', 'anubis'], ['phrygian', 'scale', 'tetrachord', 'half', 'second', 'c', 'whole', 'therefore', 'could', 'fifth'], ['ginnungagap', 'gomorrah', '26', '–', 'greece', '52', 'seawinds', 'thessaloniki', '37', '53', 'lithuania'], ['parhypate', 'paranete', 'diezeugmenon', 'phrygian', 'paramese', '′', '″', 'nete', 'proslambanomenos', '–', 'trite', 'n'], ['parhypatai', 'four', 'harmonics', 'mathematic', '2048', 'may', 'although', 'noncomposite', 'type', 'later', '2', '4', 'uses', 'unequivocal', '31', 'correspondingly', '39', 'theorists', 'eratosthenes', 'archytas'], ['parypate', 'vi', 'φθογγοι', 'lycanos', 'παρυπατη', 'redigatur'], ['hemitona', 'βαρυ', 'τρια', 'δυο', 'αοριστως', 'οξυ', 'διαιρειται', 'διηρημενον', 'τονον', 'του', 'και', 'τριτημορια', 'διαστηματα', 'τον', 'οξεος', 'τριτημοριον', 'δεν', 'hence', 'το', 'τεσσαρα', 'οποια', 'ειναι', 'ημιτονον', 'εννοει', 'ακριβως'], ['edition', 'villes', 'dictionnaire', "weyer's", 'goetia', 'daemonum', 'rankine', 'thirty-eighth', 'demonology', 'malthas', "rankine's", 'malphas', "plancy's"], ['tetrachord', 'mediant', 'c–d–e–f', 'modulations', 'however', 'requiem', 'predominance', 'therefore', 'pentachord', 'lydian—was', 'tenor', 'one', 'mode—even', 'mode', 'tone—was', 'f–g–a–b–c', 'described', 'introit'], ['2001', 'tetrachord', '256', 'phrygian', 'isconsidered', 'equated', 'especially', 'since', 'iii', 'suite', 'accidentals', 'f', 'may', 'c', 'part', 'e', 'necessary', 'abstracted', "cogulu's", '32']]
TOP TOKENS [['oak', 'method', 'explant', '43.25', 'cm'], ['oaks', 'oak', '7', '5', '4'], ['oak', 'quercus'], ['oak', 'oaks', 'shoots', 'offspring', 'quercus', '700', 'unisexual'], ['oak', 'oaks', 'quercus'], ['oak', 'oaks', 'six', 'helper', 'july', 'world', 'tree', 'earth'], ['oak', 'burls', 'texture'], ['oaks', 'oak', 'quercus'], ['oak', 'wood', 'lenticularis', 'gall', 'quercus', 'insect', 'young'], ['oaks', 'oak', 'times', 'value', 'well', 'since'], ['1917–2007', 'schwarzenegger', 'band', 'oak', 'fagaceae', 'california', 'language', 'milk', 'manga', 'disambiguation', 'she-oak'], ['oak', "oak's", '2017', '2013', 'flavours', '2019', 'seasonally'], ['oak', 'september', 'eleven', 'april', "allen's", 'nestle'], ['oak', 'grafts', 'infected', 'healthy', 'taken', 'issue', 'quercus', 'sanitation', 'red'], ['oak', 'oaks', 'cultivation', 'centre', 'lam', 'wild', 'fissured'], ['oak', 'euronext', 'oil', 'references', 'links', 'external', 'b'], ['oak', 'group', 'california', 'florida', 'carolina', 'war', 'louisiana'], ['oak', 'oaks'], ['oak', 'quercus', 'brown', 'five', 'aspects', 'years', 'clumps', 'axils'], ['oak', 'chicago', 'time']]
TOP TOKENS [['particular'], [], [], [], [], [], [], ['time'], [], ['recognition'], ['chyabrung', 'known', 'kirat'], ['regions', 'one'], ['depth', 'dervishes', 'rebab', 'chuurqin', 'however'], [], [], [], ['modestly', 'artificially', 'time', 'make', 'water', 'able', 'sections', 'painstakingly'], [], [], []]
TOP TOKENS [['deception', 'falsehood', 'deceive', 'hoax', 'deceived', 'false', 'fabricated', 'deceptive', 'deliberately', 'mockery', 'trick', 'proven'], ['deception', 'false', 'information', 'misleading', 'fraud', 'fraudulent', 'misrepresentation', 'truthful', 'concealment', 'true', 'lies'], ['true', 'deception', 'deceive', 'deception—stating', 'lying'], ['deception', 'misleading', 'mislead', 'intentionally', 'deceives', 'lie', 'advantage'], ['misleading', 'falsehood', 'fabricated', 'deceptiondɪˈsɛp', 'deception', 'misrepresentation', 'deceiving', 'deceive', 'untruthful', 'truthful', 'truth', 'deceit', 'partners', 'mislead', 'fraud', 'beguilement'], ['deceive', 'lying', 'deception', 'lied'], ['deception', 'false', 'information', 'deceptionedit', 'misleading', 'truthful', 'fraud', 'fraudulent', 'true', 'misrepresentation', 'concealment', 'infer', 'untruthful'], ['deception', 'hoax', 'pretends', 'faker', 'fake', 'fraud', 'false', 'trickery', 'impostor', 'deceit', 'deliberately', 'deceive', 'fraus', 'imposter', 'contract', 'fraudulent', 'trick', 'truth'], ['true', 'deceive', 'false', 'deception', 'lying', 'fact', 'untrue', 'lies'], ['deception', 'falsehoods', 'fake', 'fabrication', 'lie', 'false', 'deceive', 'intentionally', 'cover', 'deceiving', 'claim', 'situations', 'deceiver', 'really'], ['deception', 'information', 'false', 'misleading', 'falsehood', 'fraudulent', 'fraud', 'misrepresentation', 'misleads', 'truthful', 'true', 'advantage', 'untruthful'], ['deception', 'truth', 'distorting', 'deceptions'], ['false', 'hoax', 'deliberate'], ['deception', 'duped', 'lying'], ['fake', 'pretending', 'faking', 'profession'], ['deception', 'fraud', 'mislead', 'deceptive', 'false', 'inaccurate', 'sep', 'misleading', 'hoaxes', 'fake', 'hoax'], ['fool', 'fake', 'false', 'deception', 'truth', 'fabricated', 'lies', 'fabrication', 'deceive', 'mistake', 'honest', 'untruths', 'misinterpreting', 'decoy', 'thinking', 'concealments', 'deceptive'], ['deception', 'false', 'true', 'deceiver', 'deceiving', 'dishonest', 'misleading', 'feigning', 'deceive', 'deceives', 'actually'], ['deception', 'deceived', 'deceit', 'misleading'], ['falsely', 'fraud', 'claimed', 'pretends', 'pretended', 'fraudulent', 'false', 'fact', 'disguise', 'impostors', 'supposedly', 'washington', 'released', 'claims', 'theft', 'impostor', 'means']]
TOP TOKENS [['levels', 'mg', 'compared', 'hypercholesterolemia', '0', 'ml', 'falciparum', 'hypertriglyceridemia', 'cholesterol', 'albumin', 'group', 'parameters', 'concentration', '–', 'showed', 'whereas', 'however'], ['levels', 'cholesterol', 'also', 'concentration', 'passers', 'significant', 'compared', 'content', 'alkaline', 'ldl', 'authors', 'intestine', 'patients', 'biliary'], ['including', 'indicated', 'experimental', '1', 'c', '6', 'intakes', 'calorie', 'phospholipids', 'minerals', 'e', 'understood', 'exacerbation', 'scd', 'carotenoids', 'micronutrients'], ['including', 'indicated', 'experimental', '1', 'c', '6', 'intakes', 'calorie', 'phospholipids', 'minerals', 'e', 'understood', 'exacerbation', 'scd', 'carotenoids', 'micronutrients'], ['117', '53', '0', '65', '18', '3', '4', '9', 'factors', '76', '2', 'microg', '72', '6', '71', 'dl', 'attributable', 'changes', '19'], ['concentrations', 'micromol', '0', '16', 'malnutrition', 'status', 'tocopherol', 'micronutrient', '727', 'anthropometry', 'occurred', 'carotenoids', 'antituberculosis', 'l', 'carotenoid', 'retinol', 'deficiencies', 'significantly', 'hypothesized'], ['g/kg/day', '×', '2.5', '5', 'macronutrients', '0.01', '0.059', '92'], ['status', 'biosciences', 'changes', 'copper', 'equivalents', 'micronutrient', 'antituberculosis', 'evaluate', 'levels', 'selenium', 'mo', 'measurements', 'mg', 'chemotherapy', 'patients', 'zinc'], ['calorie', 'b6', 'adolescents', 'e', 'intakes', 'indicated', 'including', 'status', 'c', 'compared', 'carotenoids', 'minerals', 'micronutrients', 'exacerbation', 'understood', 'drops', 'many', 'persons', 'crises', 'levels', '1'], ['physiologic', 'area', 'levels', 'addition', 'patients', 'disease', 'correlations', 'malnutrition', 'much', 'studies', 'involving', '10', 'identified'], ['hypomagnesemia', 'hypophosphatemia', 'deficiencies', 'hypocalcinemia', 'hypocalcemia', 'osteoporosis', 'well', 'deficiency', 'disease', '–'], ['cls', 'treatment', 'regarding', '–', 'aids', 'micronutrient', '2', 'malnourishment', 'adults', 'requirements', 'often', 'suggested', 'systems', 'levels'], ['levels', 'secretion', 'hypertrophy', 'patients', 'mammoplasia', 'leptin', 'tissue'], ['326', 'ng', 'specifically', 'levels', 'among', 'however', 'additionally', '0', 'found', '9', 'interestingly', 'pfs', 'vs', 'compared', 'al', 'median', '3', '0108', 'treatment'], ['clinicians', '5', '2', 'levels', 'mmhg', 'disease'], ['–', '0', 'malabsorption', 'requirements', 'malnutrition', 'intolerance', 'changes', "body's", 'imbalances', 'nutrients', 'acid', 'time', 'specifically', 'although'], ['levels', 'compared', 'membrane', 'individuals', 'production', 'treatment', 'patients', 't308', 'storm', 'κb'], ['concentrations', 'hyperglycemia', 'downregulation', 'blastocysts', 'timepoints', 'especially', 'implantation', 'previously', 'support', 'γ', 'instead', 'origins', 'trophectoderm'], ['concentration', 'electrolyte', 'hypophosphatemia', 'hypoglycemia', 'euglycemia', 'stores', 'depletion', 'hepatic', 'one', 'gluconeogenesis', 'skin'], ['levels', 'hypocalcaemia', 'people', 'atrophy']]
TOP TOKENS [['idle', 'word', 'use', 'idling'], ['idle', 'named', 'python', 'directly', 'interact', 'start', 'development'], ['idle'], ['idle', 'talk', 'work', 'life', 'machine'], ['idle', 'recall', 'interpreter', 'code', 'rossum', 'default', 'executes', 'restarting', 'find'], ['idle', 'use', 'money', 'also', 'cash', 'constitutes', 'inflation'], ['idle', 'idling', 'word', '”', 'synonym', 'verb'], ['idle', 'using', 'use', '“', 'word', 'meaning', 'start'], ['idle', 'necessary', 'use', 'upload', 'provides', 'published', 'features', 'well', 'groups', 'learning'], ['idle', 'cash', 'business'], ['idles', 'idle', 'idler', 'energy', 'mrs', 'epithelial', 'idleness'], ['idles', 'idle', 'band', 'idlès', 'idless'], ['idle', 'name', 'links', 'says', 'using', 'tcl/tk', 'external', 'home', 'page', 'stands', 'short', 'according'], ['idle', 'idler', 'idlers', 'idler-wheel', '1610–1669', 'see'], ['idle', 'another', 'station', 'myland', 'serving'], ['idle', 'called', "idle's", 'officially', 'jones', 'aforementioned', 'stands', '2019', 'greedy', 'eric', 'holds'], ['idle', 'idlecroft', '1875'], ['idle', 'idleness', 'idler', 'idling', 'person', 'busyness', 'idly'], ['idle', 'incorporating', 'feature', 'animations', 'links', '1983', "a'g", 'external', 'era'], ['idle', 'behind', 'i-65', 'conceived', 'community', '48,462', 'entrepreneur', '2013']]
TOP TOKENS [['gave', 'eating', 'enjoy', 'would', 'make', 'eventually', 'crunching', 'began', 'soaps', 'substance', 'thyer', '2008', 'taking', 'disease', 'really', 'pica', 'unless', 'amount', 'one', 'certain', 'powder', 'lot', 'rice', 'way'], ['encopresis', 'soiling', 'cases', 'physical', 'family', 'practice', 'preoccupation', 'occurs', 'divorce', 'defecation', 'cultures', 'experience', 'behaviours', 'constipation', 'times', 'often', 'fruitlessly', 'may', 'increasingly', 'areas', 'difficulties', 'become', 'occur'], ['soiling', 'encopresis', 'incontinence', 'defecated', 'girls', 'defecation', 'nonretentive', 'condition', 'cls', 'percent', 'aggravate', 'cases', 'constipation', 'defecate', '95', 'toileting', 'physical', 'habits', 'disorder'], ['cases', 'practitioners', 'majority', 'damage', 'procedure', 'proportion', 'people', 'unqualified', 'attempt', 'person', 'addiction', 'many', 'significant', 'often', 'addicts', 'simply'], ['encopresis', 'morbidities', 'painful', 'process', 'soiling', 'parents', 'used', 'bodily', 'condition', 'pediatrician', 'behavioural', 'common', 'patients', 'majority', 'chance', 'treating', 'enemas', 'laxatives', 'based', 'may'], ['act', 'pleasure', 'done', 'pain', 'way', 'desired', 'harm', 'disorders', 'ways', 'sort', 'disorder', 'involved', 'esteem'], ['gave', 'cases', 'eventually', 'substance', 'began', 'found', 'disorder', 'person', 'patient', 'maybe', 'misdiagnosed', 'substances', 'someone', 'v'], ['encopresis', 'soiling', 'cases', 'g', 'constipated', 'one', 'cls', 'either', 'condition', '5', 'accomplished', 'play', 'least', 'behavioural', 'deal', 'issues', 'often', 'croffle', 'context'], ['soiling', 'encopresis', 'substance', 'methods', 'frequency', 'used', 'level', 'assessment', 'filled', 'condition', 'constipation', 'involuntarily', 'g', 'one', 'defecating', 'including'], ['encopresis', 'pa', 'disease', 'bf', 'ed', 'philadelphia', 'urinary', 'eds', 'st', 'nf', 'time', 'funcational', 'evaluation', 'clinical', 'incontinence', 'infrequent', 'js', 'chronic', 'constipation', 'teach', 'stools', 'r', 'may', 'ogilvie', 'mha'], ['engaging', 'physical', 'cases', 'extremities', 'common', 'case', 'compulsive', 'patients', 'example', 'severity', 'due', 'picking', 'may', 'commonly', "one's", 'damage', 'neck', 'significant', 'often', 'abscesses', 'person'], ['scrumptious', 'father', 'afar', 'methods', 'rearing', 'enrage', 'later'], ['gynecomastia', 'look', 'preferred', 'trying', 'possible', 'type', 'tried', 'struggled', 'topically', 'liposuction'], ['diligent', 'choreography', 'tantrums', 'huge', 'bea', 'memorizing', 'good', 'gets', 'boast', 'enrolls', 'spending', 'much', 'regularly'], ['excessively', 'cultural', 'wax', 'analysis', 'protracted', 'repetitively', 'camouflaging', 'reassurances', 'compulsive', 'abuse', 'detailed', 'attempts', 'one', 'disorder', 'many', 'cases', 'patients', 'covertly', 'outfits', 'generally', 'leading', 'mirrors', "bdd's", 'neglect', 'sometimes', 'might', 'hand', 'trauma', 'often', 'yet', 'dysphoria', 'socializing'], ['occupational', 'use', 'status', 'patient', 'participants', 'identified', 'diagnosis', 'social', 'substance', 'marital', 'health', 'disorders', 'condition', 'volunteering', 'study', 'disorder', 'found', '45', 'ses', 'compulsive', 'describing', 'uncontrolled', 'ranged', 'often', 'individuals'], ['practice', 'diagnosed', 'procedure', 'relationships', 'performed', 'sexual', 'patients', 'outcome', 'results', 'comes', 'every', 'individuals', 'resulting', 'alarmingly', 'lot', 'individual', 'one', 'person', 'hundred', 'categorised'], ['engage', 'occupational', 'use', 'disorder', 'excoriation', 'also', 'compulsive', '16'], ['performed', 'fetishism', 'fetish', 'caressing', 'using', 'activities', 'experience', 'act', 'levels', 'fisting', 'intimacy', 'fingering', 'fetishes', 'action', 'physical', 'cheirophilia', 'inserting', 'sexual', 'involve', 'ways', 'masturbating', 'fantasy'], ['diagnoses', 'occupational', 'conform', 'pondering', 'actual', 'dysmorphia', 'insatiable', 'levels', 'use', 'nervosa', 'internalization', 'higher', 'disorder', 'generally', 'involves', 'overtraining', 'general', 'deficiencies', 'muscularity', 'half', 'may', 'roughly', 'well', 'weakness', 'yet', 'smallness']]

Processing features:  34%|███▎      | 33/98 [15:52<32:30, 30.01s/it]

getting sample prompt forgetting sample prompt for 23797
 23796
getting sample prompt for 23798
getting sample prompt for 23799
getting sample prompt for 23800
getting sample prompt for 23801
getting sample prompt for 23802
getting sample prompt for 23803
getting sample prompt for 23804
getting sample prompt for 23805
getting sample prompt for 23806
getting sample prompt for 23807
TOP TOKENS [['piñata', 'piñatas', 'turn'], ['pinata', 'pinatas', 'bowls', "let's", 'little', 'inside'], ['pinata', 'pinatas', 'balloon', '7', 'make'], ['pinata', 'piñata', 'side', 'make'], ['pinata', 'pinatas'], ['pinata', 'pinatas', 'stick'], ['pinata'], ['pinata', 'order'], ['pinata', 'pinatas', 'prepare', 'mexican'], ['pinata', 'nose'], ['piñata', 'island'], ['tomata'], ['armata', 'separatist'], ['takata', '1883–1972', 'rikuzen-takata'], ['agata', 'gamma-ray'], ['kanata', 'actress', 'voice', 'canada'], ['prata', 'municipality', 'di', 'cuisine', 'prato', 'province'], ['bonata'], ['salata', 'salad'], ['tabata']]
TOP TOKENS [["saio's", 'saio．', 'saiku．it', 'saio，selected', 'saiku．during', 'saio', 'saiku', 'saios', 'saio，who', 'holy', 'ise．', 'cabinet，male', 'name', '6', 'offices．', 'shingle，erected'], ['saim', 'joined'], ['saitapharnes', 'saita', 'saii', 'word', 'name', 'avestan', 'sudrußland'], ['saipan', 'people', 'guam', '120', "saɪ'pæn", "saɪ'pɑn", 'tribune', 'ipa', '15°10’51”n', '145°45’21”e'], ['saivism', 'exceptional', 'necessary', 'incarnate', 'prior', 'inviolable', 'anything', 'disinterested', 'souls', 'individual', 'human', 'unconditionally'], ['saigo', 'slightest', 'could', 'say', '’'], ['saivism', 'saivas', 'hence', 'hindu', 'beyond', 'argue', 'philology', 'hinduism', 'creates', 'philologist'], ['saigyō’s', 'saigyō', 'kokin-shū', 'ceremonies', 'periodic', 'punctuated', 'career', 'march', 'latter', 'oppressed', 'priest'], ['saiga', 'saigas', '860', 'tulgat'], ['śaivism', 'śaiva'], ['sai', 'sain', '1830–1910', 'saine', 'centuries', '1932–2003', '1869–1932', 'saïn', 'disambiguation'], ['saina', 'nehwal'], ['saira', '1964', 'singer', '1988', '1900–1960'], ['saia-levy', 'saia', 'roman', 'australian'], ['saikot', 'saiko', 'saikō', '1990', '1787–1861', 'band'], ['saito', 'saitō', 'itakura–saito', 'surname', 'saito-nishi', 'perceptual', 'miyazaki', 'ghost'], ['saiyed', 'burma'], ['saimaa', 'saima', '1844–1846'], ['saia', 'appearances', 'seasons', 'son', '–', 'cal'], ['saito', 'japanese', 'living', 'association', '1992–1998', 'montedio']]
TOP TOKENS [['havre', 'french'], ['havre', 'le', 'channel', '76600', 'hours', 'p', 'tourist'], ['havre', 'today'], ['havre', 'havre-de-grâce', 'le', 'lə', 'äˈvrə'], ['havre'], ['havre', "havre'can", 'city', 'production', 'also', 'le', 'history', 'destroyed', 'century'], ['havre'], ['havre'], ['havre', 'france', 'le', '2005', 'history', '8', 'latter', 'marshy'], ['havre', 'europe', 'le', 'cls'], ['havre'], ['havre', "l'havre"], ['havre', "montana's", 'areas', 'montana', 'soleil', 'du'], ['havré', 'd’havré', 'economy', 'saint-antoine-in-barbefosse', 'saint-martin'], ['havre', 'havre-1', 'havre-6', 'havre-3', 'havre-5', 'havre-4', 'havre-2'], ['havre'], ['havre', "havre's", 'august', 'cls'], ['havre', 'épretot', 'saint-gilles-de-la-neuville', 'trois-pierres'], ['havre', 'links', 'le', 'information', 'external', 'official', 'steiner'], ['havre', 'cls', 'gare', 'le', 'j', "l'estuaire", 'rail', 'montivlliers', 'dame']]
TOP TOKENS [['giving', 'means', 'experience', 'try', 'offer', 'goal', 'cultivate', '‘tong-len', 'well', 'deep', 'give', 'cultural', 'receiving', 'practice', 'focuses', 'also'], ['veneration', 'knowledge', 'means', 'proverb', 'expresses', 'highly', 'similar', 'return', 'helps', 'though', 'represents', 'midwife', 'gives', 'midwifery', 'great', 'regards', 'says', 'midwives', 'detail'], ['conception', 'helped', 'appears'], ['believe', 'midan', 'kk', 'midwife', 'tan', 'caring', 'activities', 'restore', 'strenuous', 'basis'], ['applications', 'received'], ['show', 'tipis', 'demonstrate', 'stands', 'implies', 'days', 'time', 'wards', 'ability', 'great', 'gives', 'please', 'things', 'lasts', 'knowledge', 'give', 'ready', 'unbraided', 'efforts', 'becomes', 'sets', 'several', 'goes', '’'], ['comfort', 'take', 'away', 'gives', 'helps', 'considered', 'altruism', 'send', 'really', '“whether', 'said', 'meditation', '“with', 'immense.”', 'thousand', 'known'], ['show', 'expected', 'employs', 'use', 'mean', 'showing', 'also', 'fact', 'must', 'conversation', 'closely', 'used', 'wants', 'ie', 'addition', 'speech'], [], ['convey', 'imagine', 'focuscaring', 'emphasize', 'helps', '“', 'express', 'best', 'scene', 'describe', 'expressed', 'meaning', 'tells', 'fact'], ['lift', 'help', 'reality', 'awareness', 'contain', 'moods', 'short', 'films', 'potent', 'directed', 'elements', '—', "zinnemann's", 'time', 'film', 'leading', 'whether'], ['treat', 'good', 'limited', 'references', 'applied', 'similar', 'belief', '“the', 'means', 'applies', 'comes', 'related', '“ny', 'concept', 'capture', 'full', 'loosely', 'reflected', '“relationship”', 'goodwill'], ['equaled', 'five', 'quite', "lloyd's", 'high', 'exciting', 'well', 'compare', 'counted', 'also'], ['television'], ['vacations', 'context', 'show', 'said', 'set', 'plays', 'television', 'reference', "indians'apparent", 'honored', 'depict'], ['sense', 'foresee', 'presumed', 'duty', 'owed', 'saying', 'apprehend', 'expresses', 'anticipated', 'involves', 'law', 'imagine', 'also', 'beset', 'idiosyncrasies', 'eliminates'], [], ['evident', 'made', 'quite'], ['vacation', 'reminds', 'hints', 'hear', 'wish', 'ned', 'trying', 'convince', 'explain', 'wants', 'pointing', 'attempts', 'astonished', 'states', 'know', 'canyon', 'trip', "zillionaires'camping", 'realizes', 'view', 'eats', 'place', 'shenanigans', 'took', 'volunteering', "homer's"], []]
TOP TOKENS [['alkaline', 'alkali', 'alkalis', "alkali's"], ['alkaline', 'alkali', 'alkalising'], ['alkalizing', 'alkaline', 'alkaline-forming', 'alkalize', 'primarily', 'smoking', 'hunter-gatherers', 'health'], ['alkaline', 'alkalize', 'alkalizing', 'also'], ['alkaline', 'oh', 'it’s', 'well', 'don’t'], ['alkaline', 'alkalinity', 'majorly', 'diet'], ['alkaline', 'alkalizing', 'highly', 'highest', 'spinach'], ['alkaline', 'alkali', 'electrolyzed', 'good', 'scholarly', '’', 'water'], ['alkaline', 'alkalinity', '8', 'going'], ['alkaline', 'alkalosis'], ['alkaline', 'alkali'], ['alkaline', 'alkali', '1950'], ['alkaline', 'alkali', 'alkalinity', 'secwepemc'], ['alkali', 'alkaline', 'spiny', 'arbor', 'stanleya', 'system', 'evening-primrose', 'also', 'family', 'phlox'], ['alkalibacter', 'saccharofermentans'], ['alkaline', 'alkali', 'alkalis', 'adjective', 'caustic', 'slaked', 'one'], ['alkalibacter', 'alkaliphilic', 'alkaliphiles'], ['alkaline', 'alkalinity', 'alkali'], ['alkalibacterium', 'alkaline', 'ishikawa', 'alkali', 'ntougias', 'indicireducens', 'olivoapovliticus', '2004', 'putrid', 'et', 'subtropicum'], ['alkali', 'u.s']]
TOP TOKENS [['awareness', 'aware', 'lines', 'goes', 'hand', 'spreading', 'understood', '“', 'side', 'experience', 'knowledge', 'open', 'sometimes', 'reason', 'condition'], ['awareness', 'aware', 'next', 'soul'], ['awareness', 'aware', 'creating', 'create', 'become', 'mass', 'promoting', 'different'], ['awareness', 'brand'], ['awareness', 'aware', 'reason', 'raising', 'best', 'issues', 'ways'], ['awareness', 'aware', 'recognition', 'reached', 'acknowledgement', 'community', 'condition', 'level', 'self', 'lines', 'goals', 'goes', 'means'], ['awareness', 'aware', 'situation', 'behind', 'self', 'plants'], ['awareness'], ['awareness', 'increasing', 'better'], ['awareness', 'aware', 'see', '“', 'codes', 'aisle'], ['awareness', 'brand', 'aware', 'resuscitation'], ['awareness', 'public', 'aware', 'behaviorally', 'list', 'situation'], ['awareness', 'result', 'naturalness', 'baños', 'title', 'tomatoes', 'two', 'roque', 'exposed', 'great'], ['awareness', 'aware', 'direction', 'synonymous', 'self', 'focused', 'popular', 'perceiving', 'often', 'represented'], ['awareness', 'increase', 'public', '1995', 'exhibitions'], ['awareness', 'brand', 'levels', 'conditions', 'category', 'recognition', 'creating'], ['awareness'], ['awareness,”', 'awareness', 'awareness”', 'aware', 'investor'], ['awareness', 'measuring', 'security', 'impose', 'directly', 'focus', 'enablers', 'means', 'understanding', 'specifically'], ['awareness', 'raise', 'around', 'host', 'mha', 'reduce', 'observances', '18.1', 'mental', 'nctsn']]
TOP TOKENS [['spectra', 'spectroscopy', 'spectrum', 'spectral', 'measured', 'spectroscopic', 'spectrography', 'spectrometers', 'spectrographs', 'cls', 'spectrophotometers', 'studies', 'historically'], ['spectra', 'spectroscopy', 'spectrum', 'needed', 'analyzed', 'specimen', 'emission', 'grating', 'absorption'], ['spectra', 'spectral', 'spectroscopy', 'containing', 'spectroscopic', 'classification', 'eg', 'contains'], ['spectrum', 'spectroscopy', 'spectrums', 'spectrometers', 'spectroscope', 'spectroscopes', 'spectrometry', 'spectral'], ['spectra', 'spectroscopy', 'spec', 'analyze', 'spectroscopic', 'spectroscopes', 'spectroscope', 'acceptable', 'data', 'stellar'], ['spectroscopy', 'spectrum', 'spectrometry', 'spectrophotometry', 'spectrums', 'cls', 'understand'], ['spectroscopy', 'spectra', 'spectrometer', 'spectrum', 'emission', 'spectral', 'spectrographs', 'spectrometry', 'absorption', 'identification', 'sensing'], ['spectral', 'spectroscopy', 'spectra', 'spectrometers', 'spectrometer', 'measurements', 'collecting', 'cls', 'new', 'samples'], ['spectra', 'spectral', 'spectrum', 'spectroscopy', 'spectrography', 'spectrometry'], ['spectral', 'spectroscopy', 'spectra', 'spectrum', 'features', 'cls', 'analyze', 'data', 'unique', 'study', 'techniques'], ['spectrum', 'spectral', 'operators'], ['spectroscopy', 'spectrum', 'spectrograph', 'francisco', 'spectral', 'spectrometry', 'imaging', 'features'], ['spectroscopy', 'spectroscopic', 'instrumentation', '1985'], ['spectra', 'spectrum', 'light', 'optare', 'spectre', 'dassault', 'two-way', '1802', 'continuum', 'ultra-high-molecular-weight', 'fighter', 'thales'], ['spectroscopy', 'spectrum', 'spectral', 'image', 'spectrograph', 'spectrographs'], ['spectroscopy', 'spectroscopic', 'spectrometry', 'spectrometer', 'spectral', 'scanners', 'imaging', 'spectrally', 'cls', 'combines', 'produces'], ['spectra', 'spectroscopy', 'spectrum', 'spectral', 'measuring', 'absorption', 'cls', 'quantify', 'sensing'], ['spectroscopy', 'spectra', 'spectrum', 'spectral', 'transition', 'band', 'bands', 'electromagnetic', 'studies'], ['spectroscopy', 'spectrum', 'instrument', 'spectral', 'eigenvalues'], ['spectroscopy', 'spectra', 'spectrum', 'spectral', 'emission', 'absorption']]
TOP TOKENS [['phobos'], ['phobos'], ['phobos'], ['phobos', 'marking', 'given', 'deimos', 'settle'], ['phobos'], ['phobos', '1977', 'synchronous'], ['phobos', 'point', 'using', 'well', 'pole'], ['phobos', "phobos'interior", 'al'], ["phobos'doomed", 'phobos', 'planet', 'impact'], ['phobos', 'fobos', '“'], ['phobos', 'phobus', 'either'], ['phobos', "phobos's", 'fobos', 'links'], ["phobos's", 'phobos', "moon's", 'quarter', 'consistent'], ["phobos's", 'phobos', 'fobos'], ['phobos'], ["phobos's", 'phobos', '7', 'since'], ['phobos', "phobos'surface"], ['phobos', 'onto', 'mars', 'around', 'would'], ['phobos', 'possible', 'mars', 'reaccreted', 'deimos', 'recent'], ['phobos', "phobos's", 'closely']]
TOP TOKENS [['ionic', 'liquids', 'liquids.”', 'book'], ['ionic', 'liquids', 'nonetheless', 'furthermore'], ['ionic', 'il', 'liquids', 'i.e', 'well', 'synthesis', 'catalysis', 'well-defined', 'information’s', 'lots', 'conductivity'], ['ionic', 'liquids', 'liquid', 'functionally'], ['ionic', 'liquids', 'compounds', 'cls', 'pressure', 'evaluate', 'change', 'reactions', 'much', 'provide'], ['ionic', 'liquids', 'ils', 'l−1', 'bmim][bf4'], ['ionic', 'ils', 'various', 'liquids', 'solvents', 'shows', 'many', 'main', 'volatilize', 'conditions', 'traditional', 'also'], ['ionic', 'liquids', 'liquid', 'many', 'undesirable', 'utilizing', 'make'], ['ionic', 'liquids', "liquid's", 'liquid', '°c', 'possesses'], ['ionic', 'liquids', 'liquid', 'k', 'robust', 'littau', 'based'], ['ionic', 'liquids', 'solvents'], ['ionic', 'liquids', 'contamination', "liquids'low", "liquids'aquatic", 'liquid', 'based'], ['ionic', 'atmosphere', 'specific', 'liquids', 'however', 'amines', 'could', 'high', 'selectivity'], ['ionic', 'however', 'liquids', 'atmosphere', 'additionally', 'sequestration', 'facilities'], ['ionic', 'therefore', 'liquids', 'makes', 'call', 'cycles', 'sep', 'offer', 'industry'], ['ionic', 'liquids', 'liquid', 'significantly', 'solution'], ['ionic', 'salts', 'liquids', 'furthermore', 'liquid'], ['ionic', 'properties', 'liquids', 'many', 'applications', 'methylimidazolium'], ['ionic', 'liquids', 'include', 'sulphate', 'base', 'tetrachloroferrate', 'trifluoromethanesulfonimide', 'steps', '6', 'ils'], ['ionic', 'liquids', 'optimistically', 'emerged', 'solvents', 'reversible', 'example', 'strength', 'polarity', 'hydrophilicity', 'volatility', 'imidazole', 'immiscible']]
TOP TOKENS [['assistance', 'income', 'eligible', 'benefits', 'people', 'person', 'temporary', 'programs', '’', 'month', 'program', 'potentially', 'needy'], ['assistance', 'welfare', 'income', 'payments', 'program', 'tanf', 'help', 'benefits', 'fund'], ['assistance', 'eligible', 'eligibility', 'income', 'payments', 'meals', 'individuals', 'programs', 'program', '“', 'benefit'], ['income', 'assistance', 'programs', 'eligible', 'aid', 'receiving', 'temporary', 'program', 'benefit', 'payments', 'helping', 'benefits'], ['assistance', 'income', 'supporting', 'eligible', 'programs', 'program', 'individuals', 'eligibility', 'aid'], ['income', 'assistance', 'eligible', 'help', 'program'], ['income', 'assistance', 'aid', 'benefits', 'individuals', 'programs', 'welfare', 'one'], ['low-income', 'assistance', 'payments'], ['income', 'assistance', 'individuals', 'programs', 'individual', 'temporary', 'poverty', 'cash'], ['assistance', 'income', 'temporary', 'benefits', 'needy', 'programs', 'welfare'], ['income', 'assistance', 'receiving', 'persons', 'programs', 'welfare', 'work', 'program', 'funds', 'waiver', 'policy', 'provide', 'public'], ['assistance', 'programs', 'administration', 'temporary', "reagan's", 'aid', 'indigent', 'benefits', 'welfare'], ['assistance', 'eligible', 'program', 'net', 'programs', 'poor', 'eligibility', 'benefit', 'benefits', 'government', 'work', 'providing', 'welfare', 'provide', 'public', 'needy'], ['assistance', 'aid', 'assist', 'reauthorization', 'funds', 'people', 'temporary', 'program', 'called', 'unemployment'], ['pay', 'income', 'support', 'program', 'wage', 'welfare', 'paid', 'poverty', 'benefits', 'disincentivized', 'programs', 'tanf', 'sufficient', 'allow', 'enrollees', 'child', 'states'], ['assistance', 'programs', 'income', 'eligible', 'government', 'program', 'services', 'united', 'support', 'supplemental', 'policy', 'medicaid', 'work', 'tanf', 'welfare', 'states'], ['assistance', 'assists', 'temporary', 'eligibility', 'program', 'eligible', 'individuals', 'meals', 'income', 'funds', 'aid', 'benefits', 'stamps', 'became', 'adjunctive', 'automatically', 'programs'], ['income', 'pay', 'apply', 'financially', 'payment', 'benefit', 'benefits', 'policy', 'time', 'loans', 'allowance', 'emergency', 'work', 'paid', 'rewarding', 'would', 'get', 'theory', 'make', 'monthly', 'incentives', 'support', 'claimants', 'employment', 'incentivise', 'system', 'simplify', "jobseeker's"], ['assistance', 'benefit', 'targeting', 'beneficiary', 'income', "families'incomes", 'financial', 'qualify', 'childcare', '000', 'poverty', '70', 'adults', 'thresholds', 'abatement', '285', 'recipients', 'impact', '00', 'types', 'child', 'families', 'would', 'work', 'money', 'benefits'], ['assistance', 'income', 'paid', 'receiving', 'qualify', 'payment', 'receive', 'get', 'week', 'budget', 'amount']]
TOP TOKENS [['sumerian', 'sumerians', 'sumer', 'sumers', 'womb', 'age'], ['sumerian', 'sumeria', 'noun', 'language'], ['sumerian', 'sumerians', 'genders', 'sumer', 'unfamiliar'], ['sumerians', 'sumerian', 'sumer', 'underworld', 'cls'], ['sumerians', 'sumerian', 'sumer', 'moreover', 'aspect'], ['sumerians', 'sumerian', 'sumer'], ['sumerian', 'sumer', 'sentence'], ['sumerian', 'sumer', 'sentence'], ['sumer', 'sumerian', 'sumerians'], ['sumerian', 'sumerians', 'word', 'goes'], ['sumerian'], ['sumerian', 'sumeria', 'sumer'], ['sumerian', 'sumerians', 'precludes'], ['sumerians', 'sumerian', 'sumer', 'exert', 'underworld'], ['sumerian', 'sumer', 'exact', 'ceremonial', 'religious', 'cls', 'content', 'written', 'nippur'], ['sumerian', 'nouns', 'data', 'transliterated', 'mood', 'verbs', 'albeit', 'well'], ['sumerians', 'sumerian', 'elsewhere', 'gods', 'dome'], ['sumerian', 'sumerians', 'sumer', "sumerians'black", 'rivers'], ['sumerian', 'sumeria', 'sumer'], ['sumerian', 'inauguration', '2022', 'cls']]
TOP TOKENS [['enron', 'skilling', 'people'], ['enron', 'made', 'defraud', 'mastermind'], ['dahl', 'enron'], ['cls', 'corporate', 'enron', 'executives'], ['enron', 'like', 'included'], ['enron', 'providing', 'practices', 'leadership', 'one'], ['insider', 'trading', 'corporation', "enron's", 'enron', 'commission', '25', 'exchange'], ['enron', "enron's", 'executives', 'scandal', 'involved', 'top'], ['executives', 'executive', 'enron', '2', 'corporation', "enron's", 'corporate'], ['insider', 'enron', 'corruption', 'rule', 'company', 'corporate', 'trading'], ['2000', "enron's", 'enron', 'intermediaries', 'would', 'often', '83', 'options', "company's", 'helped'], ["company's", "enron's", 'lay', 'enron', 'many', 'financial', 'one', '2001', "skilling's"], ["company's", 'equity', "enron's", 'later', 'said', '2001', 'enron'], ['enron', "enron's", 'inside', 'effectively', 'corporate', 'accounting', 'elsewhere', 'initiatives', 'defraud', 'cfo', 'done', 'time', 'millions'], ['executives', 'enron', "enron's", "company's", '2001', 'officer'], ['enron', "enron's", 'reviewing', 'one', 'demise'], ['insider', 'within', 'enron', "enron's", 'quitting', 'trading', 'scandal', 'fraud', 'ceo', 'legal', 'information'], ['executives', "enron's", 'recurrently', 'enron', "company's", '1997', 'son'], ['enron', 'corporation', "enron's", 'scandal', 'financial', 'executives', 'misled', 'higher', 'high', 'ceo'], ['enron', 'scandal', 'securities', 'sec', 'many', 'executives', 'commission', 'senior', 'big', 'maneuvers', 'accounting', 'thoman', 'company', 'million', 'among', 'fined', 'related', 'several']]

Processing features:  35%|███▍      | 34/98 [16:19<31:12, 29.26s/it]

getting sample prompt forgetting sample prompt for 23809
 23808
getting sample prompt for 23810
getting sample prompt for 23811
getting sample prompt for 23812
getting sample prompt for 23813
getting sample prompt for 23814
getting sample prompt for 23815
getting sample prompt for 23816
getting sample prompt for 23817
getting sample prompt for 23818
getting sample prompt for 23819
TOP TOKENS [['córdoba', 'english', 'order', 'one'], ['córdoba', 'de'], ['córdoba', 'de', 'onyx'], ['cordoba', 'around', 'year', '70', 'remis'], ['córdoba', 'cordoba', 'hazm', 'patios'], ['cordoba', '25', 'iberian', 'humanity', 'conquest'], ['cordoba', 'plays', 'argentina', 'also', 'located', 'schule', 'century', 'another'], ['cordoba', 'south', 'city', '3', 'organizations', 'argentine', '2001', 'around'], ['cordoba', 'córdoba', 'patios', 'much', 'wiki-based', 'general'], ['cordoba', 'squares', 'de', '1369', 'st'], ['cordoba', '1955', 'c', 'ss', 'team'], ['cordoba'], ['cordoba', '817', 'spanish', 'de', '67', 'penuela', 'heroica', 'tepixtepec'], ['cordoba', '2022', '2021', '2018', 'league'], ['córdoba'], ['córdoba', 'split', 'pijao'], ['córdoba'], ['spain'], ['cordoba', 'cordobapedia', 'cordobasket', 'links', 'seats', 'external', '2004', 'also', 'century', 'nuremberg', '19th'], ['córdoba']]
TOP TOKENS [['dreidel', 'dreidels', 'sleigh'], ['freire’s', 'perpetuate'], ['freire’s', 'result-oriented', 'master-slave', 'solely', 'co-creation', 'oppressor', 'today', 'consciousness-raising', 'rather', 'innovative'], ['breier', 'breuer', 'braeuers', 'early', 'general', 'braeuer', 'ever', 'extended'], ['speick', 'september'], ['freire', 'freirian', '’', 'p', 'originality', 'reliving', 'presentation'], ['freire', 'ˈfɾeiɾi', '1946', 'ˈpawlu', 'would', 'best', 'improved', '2', 'guararapes', 'became', 'dos'], ["freire's", 'freire', 'pedagogy', 'teachers', 'best', 'according'], ['freire', 'forward', 'significant', 'ideology', 'reflection', 'seen', 'dialectical'], ['freire', 'importance', 'behind', 'fall'], ['brei'], ['greig'], ['creighton'], ['greiff', 'greif'], ['freier'], ['drei'], ['creighton', 'creightons'], ['speicher', 'ausserrhoden'], ['creich'], ['creighton']]
TOP TOKENS [['rugosa', 'rugose'], ['rugeley', '329', '5s', 'fn', '1473', 'manor', '330'], ['rügen', 'rugia', 'lat', 'ft', 'mi', '31.9', 'mecklenburg-vorpommern', 'length||51.4', '528', 'width||42.8', 'germany'], ['rasengan', 'use', 'used'], ['salona', 'defences', '5th', 'fortifications'], ['salona', 'independence', 'century', 'ελλαδος', 'διαταξις', 'χερσου'], ['wellhausen', "wellhausen's", 'complete', 'dominant', 'upon', 'progressively', 'use', 'tradition', 'dissipate', 'special', 'alive', 'higher', 'devoid', 'totally', 'edifice', 'revolution', 'falsified', 'need', 'foundations', 'order', 'rather', 'passed'], ['rugen', 'rugieri', 'stone', '1168', '926', 'slavic', 'strips', 'rise', 'protected', 'displaced', 'joined', 'wends', 'ummanz', 'jasmund', '161', 'cliffs', '40', 'strait', 'originally', 'cls', 'geologically', 'general', 'well', 'several', '120', 'distinguished', 'various'], ['basilisk', "basilisk's", 'basilisks', 'petrification', 'one', 'hid', 'petrified', 'whose', 'crowing'], ['threedipolesunion', 'interdigitallines', 'threedipoles', 'untrimnurbs'], ['vorpommern-rügen', 'rügen', 'sea', 'towns', 'islands', '1810', 'first', 'disestablishments', 'pomerania', 'hiddensee', 'history', 'vilm'], ['salonen', '1934', '1933–2019', 'till', '1973', '1946', 'born'], ['rugal'], ['ruga', 'rugia', 'strelasund', 'rugen', 'english', 'rügen', 'crossing', 'district', 'disambiguation', 'island', 'see'], ['rügland', 'osman', '“turkish', 'ruhet', 'still', 'constantinople', '1655', 'born', 'five', 'mythological', 'decorated', '1688', 'receive', 'rest', 'geboren', 'houses', 'belgrad', 'crusade”', 'christened', 'er', '1735', 'one', 'jahr', 'silver', 'zu'], [], ['salonga', 'filipina', '1920–2016', 'mononymously', '2000', 'born', '1924–1951'], ['ruganda', "ruganda's", 'setzuan', 'kampala', 'regular', 'golden', 'shreds', 'november', 'may', 'part', 'uganda', 'playwright', '1972', '2007', '30', 'university', 'august', '1970', '1974', 'kenya', '1', 'half-yearly', '1985', 'nairobi', 'centre', '1978', 'players', '19-32', '6'], ['rugen', 'rugard', 'reached', 'maintaining', 'sep'], ['ruge', 'john', 'fannie', 'apalachicola', 'tallahassee', 'fitchner', 'g', 'added']]
TOP TOKENS [['yield', 'actual', 'called', 'learn', 'instantly', 'reaction', 'percent', 'theoretical', 'calculator'], ['yield', 'called', 'actual', 'theoretical', 'reaction', 'percent', 'learn'], ['yield', 'correctly', 'important'], ['driving', 'generating', 'yield', 'true', 'yields', '”', 'higher', 'factor', 'costs', '“', 'decreases', 'note', '–', 'guarantee'], ['wouldn’t', 'militants', 'farm', 'yield', 'quality', 'good', 'results'], ['provide', 'yields', 'obtaining', 'yield', 'earn', 'via', 'opportunity', 'percentage', 'receive', 'aggregators', 'express', 'highest', 'work', 'return', 'lowers', 'refers', '10'], ['yields', 'yield', 'bond-yields.com', 'version', 'total', 'post', 'par'], ['quality', 'yield', 'data', 'differing', 'affecting', 'field', 'require', 'identify', 'information'], ['one', 'see', 'generator.the', 'yield', 'statement', 'associated', 'least', 'items(“warsaw”', '0x00c7a5d0', 'it’s'], ['yield', 'yields', 'kind', 'current', 'sucker', '6'], ['ecological', 'multithreading', 'earnings', 'programming', 'specific', 'fission', 'enroll', 'yield'], ['equation', 'yields', 'yield', 'fair', 'percentage', 'process', 'manual', 'theoretical', 'factors'], ['c++11', 'yield', 'explicitly', 'std::this_thread::yield', 'pthread_yield', 'required'], ['yields', 'yield', 'yielding', 'crop'], ['affect', 'yield', 'dial-a-yield', 'yields', 'vary', 'enough', 'significantly', "weapon's", 'explosive', 'primary', 'variable', 'incorporate', 'reaction', 'b61'], ['case', 'footprint', 'yield', 'higher', 'yields', 'calculating', 'formation', 'improved', 'versus', 'also', 'cereal', 'ha', 'increased', 'increase'], ['see', 'higher', 'yield', 'also'], ['established', 'average'], ['value', 'higher', 'power', 'yields', 'driving', 'must', 'yield', 'day', 'ecological'], ['regions', 'yields', 'typical', 'yield', 'quality', 'low', 'types', 'lower', 'usa', 'vary', 'europe', 'allowed', 'world', 'surface', 'hectoliters', 'viticulture']]
TOP TOKENS [['mobilization', 'war', 'mobilizing', 'mobilisation', 'joint', 'environmental', 'land', 'movement', 'unbelievable', 'wikipedia'], ['mobilized', 'mobilization', 'word', 'community', 'social', 'vs'], ['mobilization', 'mobilizations', 'notes', 'effectiveness', 'patellar', 'anterior', 'ionid', 'h'], ['mobilization', 'mobilized', 'community', 'social'], ['mobilization', 'nowadays', 'resource', 'attributes', 'mobilize'], ['mobilization', 'mobilisation', 'whole', 'cycle', 'mobilizing', 'county'], ['mobilization', '’', 'knowledge', 'us'], ['mobilization', 'effective', 'creativity', 'social', 'strategies', 'initiate', 'disasters', 'related', 'understand', '”'], ['mobilization', 'calculating', 'arms', 'costs', 'understanding', 'securing', 'cost'], ['mobilizations', 'mobilization', '‘mobilized’', 'joint', 'use', 'mobilisation', 'whereas', 'word', 'words', 'means', 'ligaments', 'won’t'], ['mobilization', 'resource', 'war', 'joint', 'community', 'committee', 'mobilizing'], ['mobilization', 'effect', 'employ', 'joint'], ['mobilization', 'eleven', 'holger', 'eventually', 'succeeded', 'external', 'journal', 'two', 'references'], ['mobilization', 'institutionalized', 'army', 'mobilized', 'word', 'war', 'mobilizing', 'well', 'emergencies', 'revolution', 'demobilization', 'century', '–', 'mobilize'], ['mobilization', 'needs', 'effort', 'lives', 'requirements', 'recently', 'resource', 'sector', 'community', "community's", 'mobilizing', 'proved', 'respect'], ['mobilization', 'civil', 'emergency', '1964', 'teachers'], ['mobilization', 'resource', 'manner', 'advocates', 'sees', "movement's", 'skills', 'taking', 'using', 'use', 'irrational', 'money', 'group', 'goals', 'effective'], ['mobilization', 'mass', 'mobilized', 'politics', 'action', 'social', 'engages', 'reach', 'seeks', 'based', 'powerful', 'words', 'popular', 'change', 'specific', 'institutions', 'engaged', 'levels'], ['mobilization', 'mechanisms', 'joint', 'defines', 'low', 'osteokinematic', 'douglas', 'amplitudes', 'cls', 'applied', 'maitland', 'manipulation', 'amplitude'], ['mobilization', 'society', 'mobilisation', 'military']]
TOP TOKENS [['rhine', 'aachen', 'düsseldorf', 'bonn', 'rhineland—the', 'rhineland', 'mainz', 'cologne'], ['rhine', "rhine's", 'mainz', 'rhein', 'bonn', 'river'], ['rhine', 'rhein', 'cologne', 'bonn', 'dusseldorf', 'westphalia', 'german'], ['rhine', "rhine's", 'mainz', 'bonn', 'river', 'rhein', 'cologne'], ['rhine'], ['rhine', 'rhein', 'rheinkilometer', 'der', 'german', "germany's", '–', 'encyclopedias'], ['rhine', 'aachen', 'dusseldorf', 'bonn', 'cologne', 'westphalia', 'rotterdam'], ['rhine', 'research'], ['rhine', 'river', 'dusseldorf'], ['rhine'], ['rhine', "rhine's", 'dallas'], ['rhine', 'rheinreisefuhrer', 'bonn', 'rhineland', 'koln', 'dusseldorfer', 'rheinburgenweg', 'kolner', 'german', 'rheinsteig'], ['rhine', 'rhines', 'provinces'], ['wars#rhineland', 'rhine', 'wars#rhine'], ['rhine', 'rhine-westphalia', 'niederrheinische', 'niederrheinisches'], ['rhine', 'rhineland', 'rheinland'], ['rhine', 'riley', 'world', 'sister'], ['rhine', 'rhine-westphalia', 'rhineland', 'www.niederrhein-tourismus.de', 'düsseldorf', 'bergish', 'niederrhein', 'german', 'river', 'rhenish'], ['rhine'], ['rhine', 'rhineland', 'aachen', 'palatinate', 'bonn', 'rheinprovinz', 'dusseldorf', 'westphalia', 'munster']]
TOP TOKENS [["coke's", 'coke', 'elizabeth', 'july', 'yeomen', 'wilhelmina', '–', 'sons'], ['coke', 'cokearticle'], ['coke', 'iron', 'ovens', 'petroleum', 'ores', 'tar', 'press', 'refining', 'lead', 'buildings', 'production'], ['coke', 'cokes', 'coking'], ['coke', "coke's", 'skinner', 'nearby', 'theophile', 'family', 'knew'], ["coke's", 'coke', '”', '1916', 'drawing', 'dealt', 'institutes', 'invitation', 'laid'], ['coke', 'cokes', 'coker'], ["coke's", 'coke', 'cokes', 'thomas', 'illness', 'certain'], ['coke', 'refineries', 'coking', 'processes', 'concern'], ['coke', 'ton', 'together', 'rows'], ['coke', '1906', '2010', 'justice', 'constable', 'location'], ['coke', "coke's", 'talbot'], ['coke'], ['coke'], ['coke', "coke's", '1894', '1895', 'stevenson', 'death', '1879', 'along', '1897', 'cemetery', 'adventurers'], ['coke', "coke's", 'land', 'recorders'], ['coke', "coke's", '58', 'however', '1813', 'degrees', '29', 'volumes'], ['coke', "coke's", 'lost', 'nottinghamshire', 'derby', 'ceylon'], ['coke', 'jr', '1552–1634', '1921-2004', '1913–2008'], ['coke', 'king', '43', 'war', '1650']]
TOP TOKENS [['vietnam', 'cambodia'], ['vietnam', 'cambodia', 'indochina'], ['vietnam', 'vietnamis', 'cambodia', 'laos', 'chinese', 'country', 'china', 'vietnamese', 'nation', 'cls', 'thailand'], ['vietnam', 'cambodia', 'vietnamis', 'laos', 'country', 'chinese', 'china', 'countries', 'nation', 'thailand', 'vietnamese', 'cls'], ['vietnam', 'cambodia', 'country', 'countries'], ['vietnam', 'cls', 'country', 'communism', 'laos', 'vietnamese', 'cuba', 'communist', 'soviet', 'indochina', 'china'], ['vietnam', "vietnam's", 'cambodia', 'indochina', 'vietnamese'], ['vietnam', "vietnam's", 'viet', 'cambodia', 'cls', 'laos', 'country', 'nam', 'vietnamese', 'communist'], ['vietnam', "vietnam's", 'country', 'viet', 'countries', 'indochina'], ['vietnam', 'cambodia', 'vietnam’s', 'vietnamarticle', 'country', 'asia', 'hanoi'], ['vietnam'], ['vietnam', "vietnam's", 'cambodia', 'communist', 'country', 'viet', 'soviet', 'malaysia', 'indochina', 'cls', 'thailand'], ['vietnam'], ['vietnam', 'cambodia', 'viet', 'indochinese', 'cochinchina', 'indochina', 'france'], ['vietnam', 'iraq–vietnam', 'vietnamese', 'communist', 'iraq'], ['vietnam', 'vietnamese', 'cambodia', 'viet', 'indochinese', 'chinese', 'country', 'southeast', 'nation', 'china', 'laos', 'nam', 'countries', 'communist', 'socialist'], ['vietnam', 'viet', 'cochinchina', 'cambodia', 'vietnamese', 'communist', 'country', 'indochina'], ['vietnam', 'viet', 'communist', 'indochina', 'country', 'vietnamese', 'socialist', 'france', 'minh', 'communists', 'canada'], ['vietnam', 'vietnamese', 'hanoi', 'canada', 'gia', 'socialist', 'vinh'], ['vietnam', 'vietnamese', 'hanoi']]
TOP TOKENS [['trade', 'threading'], ['’', 'pitfall', 'rail', 'listing'], [], ['bryce', 'jr', 'katiemarie', 'gnu', 'iqbal', 'polyurethane'], ['threading', 'client'], [], ['–', 'titled', 'instance', '“', 'iteration'], [], ['young'], ['meetings', 'ks', 'work', 'sep', 'start'], ['prix', 'leung', 'mcleod', 'novice', 'together', 'vancouver'], ["that's", 'choice'], ['association', 'white', 'sep', 'judges', 'appeal', 'supreme', 'canadian', 'time', 'institute', 'defendants', 'law'], ['gymnastics'], ['listing', "listing's", 'law', 'sep'], ['mlas', 'bryce', 'general', 'political', 'legislature', 'early', 'canada', '2000', 'election'], [], ['ding', 'gymnastics'], ['membership'], ['event']]
TOP TOKENS [['nanoparticles', 'nanoparticle'], ['nanoparticles'], ['nanoparticles', 'nanoparticle', 'taheri', 'acad'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles'], ['nanoparticles', 'nanoparticle'], ['microparticle', 'microparticles'], ['nanoparticles'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticle', 'nanoparticles'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticles', 'nanoparticle'], ['nanoparticle', 'nanoparticles', "nanoparticles'dispersion"]]
TOP TOKENS [['chili', 'peppers'], ['chili', 'peppers', 'cls', 'bell', 'jalapeno', '6'], ['chili', 'peppers', 'jalapeno'], ['chili', 'chilis', 'peppers'], ['chili', 'chilies', 'peppers', 'hot', 'bell'], ['chili', 'chilies', 'peppers', 'hot', 'bell'], ['chili', 'peppers', 'chilies'], ['chili', 'peppers', 'bell', 'salsa'], ['chili', 'peppers', 'chilies'], ['chili', 'peppers', 'chilies'], ['chili', 'peppers', 'hot'], ['chilis', 'chili', 'peppers', 'jalapeno', 'jalapenos', 'pepper', 'light'], ['chili', 'hot', 'peppers'], ['chili', 'peppers', 'bell', 'jalapeno', 'cultivars'], ['chili', 'peppers', "women'soundtrack", 'hot', 'although', "girl'reaching", 'platinum', 'addiction', 'hit'], ['chili', 'peppers', 'bell', 'rice', 'hatch', 'potatoes', 'aubergines', 'used'], ['chili', 'peppers', 'hot', 'southwest', 'amount'], ['chili', 'peppers', 'hot', 'awards', 'way', "band's"], ['chili', 'peppers', 'chilies', 'cooking', 'leaves'], ['chili', 'peppers', 'hot']]

Processing features:  36%|███▌      | 35/98 [16:51<31:42, 30.19s/it]

getting sample prompt forgetting sample prompt for 23821
 23820
getting sample prompt for 23822
getting sample prompt for 23823
getting sample prompt for 23824
getting sample prompt for 23825
getting sample prompt for 23826
getting sample prompt for 23827
getting sample prompt for 23828
getting sample prompt for 23829
getting sample prompt for 23830
getting sample prompt for 23831
TOP TOKENS [['cost', 'costs', '4', 'range'], ['costs1', 'cost', 'costs', 'pricerlogonew', '•', 'prices', 'another', '200'], ['cost'], ['cost', 'costs', 'price', 'much', 'around'], ['costs', 'cost', 'expensive', 'around'], ['cost', 'anywhere'], ['cost', 'costs', 'price', 'many', '12', 'range'], ['cost', 'costs', 'expensive', 'include'], ['cost', 'charge', 'costs', 'anywhere', 'much', 'may', 'type'], ['cost'], ['cost', 'costs'], ['costs', 'cost', 'expenses', 'hill'], ['cost', 'costs', '2', 'though', 'incur', 'average', 'expensive', '000'], ['cost', 'costs', 'producing', 'produce'], ['costs', 'cost', 'price'], ['costs'], ['costs', 'cost', 'spend', 'per', 'expenses', 'amounted', 'respectively'], ['costs', 'cost', 'references'], ['cost', 'required'], ['costs', 'cost']]
TOP TOKENS [[], [], ['decapod', 'decapoda', 'malla', 'sergestidae', 'datos', 'el', 'porcellanidae', 'crustaceos', 'muestreo'], [], [], ['lutjanus', 'legat', 'kaplan', 'verley', 'remacle', 'caillaud'], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['anyone', 'also', 'many', 'anything', 'even', 'though', 'words', 'took', 'theories', 'refers'], ['anyone', 'also', 'many', 'anything', 'even', 'though', 'words', 'took', 'theories', 'refers'], ['schaefer'], ['let', 'given'], ['first', 'umpteenth'], ['ones', 'could', 'rhae', 'markets', 'therefore', 'brokers', 'one', 'however', 'else', 'anyone', 'market', '1902', 'prices', 'todays', 'psychology', 'institutions', 'book', 'fact', 'topic', 'days', 'years'], [], ['1902'], ['somewhat'], ['work'], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['dye', 'dyeing', 'dyes', 'cls', 'process'], ['dyeing', 'dyes', 'dye', 'dyestuff'], ['dye', 'dyeing', 'dyes', '1'], ['dye', 'dyes', 'dyeing', 'dye”', 'dyestuff', 'dyed', 'dyeme', 'dye·ing', 'dyemiddle', 'form'], ['dye', 'dyestuff(verb'], ['dyestuff', 'dyeing', 'dyes', 'dye'], ['dyeing', 'dye', 'dyes'], ['dyeing', 'dye', 'dyebaths', 'dyebath', 'dyes', 'dyed'], ['dyeing', 'dye', 'dyed', 'dye.continue'], ['dyeing', 'dyestuff', 'dye'], ['russo–dye', 'dye', 'dyes', 'applied'], ['dye', 'called'], ['de:dye', 'dye', 'r', 'suffragist', 'right'], ['dye', 'existence', 'geography', '2000'], ['dyé'], ['dyes-am', 'dyes', 'dyes-fm'], ['dyeing', 'dyes', 'dye', 'specific', 'commission'], ['dye', 'july', 'career', 'served', 'university'], ['dye', 'amalgamation', 'career'], ['dye', '1996', '2011', "men's", '56', 'sportspeople', 'season']]
TOP TOKENS [['walsh', 'http://en.wikipedia.org/wiki/walsh_(surname', 'http://www.pregnology.com/index.php?boys/walsh', 'waleis,wallace,wallis,walsh'], ['walsh', 'demo', '8', 'well', 'negative', 'first', 'note'], ['walsh', 'walshes', 'walshe'], ['walsh', 'inning', '1913', 'images5'], ['walsh', 'walshes', 'walshe', 'nantes', 'walsheman', 'james'], ['walsh', 'trust', 'deane', 'dawes', 'systems', '31'], ['walsh', 'walshes', 'walshe', 'edward', 'ireland', 'country', 'english', 'cls', 'e', "term'bretanach", "term'brethnaigh", 'england'], ['walsh', "walsh's", 'inning', 'major', 'sox', 'town', 'apocryphal', '1913', '1912', 'pennsylvania'], ['walsh', 'times', 'contacts', 'chifley', 'commentators', 'point', 'election', 'wales', 'team', 'catholic'], ['walsh', 'party', 'death', 'ed', 'bates'], ['walsh', 'washington', 'states', 'navy'], ['walsh'], ['walsh', '27', '14', '1', '16', 'september', 'october'], ['walsh', 'irish'], ['walsh', '2010', 'joneses', 'also', 'orloff', '2006', 'roberts'], ['walsh', "children's"], ['walsh', "o'reilly", 'publications', 'also'], ['walsh', 'walshe'], ['walsh'], ['walsh']]
TOP TOKENS [['environment', 'ladee', 'gallery', 'along', 'nasa’s'], ['environment', 'explorer', 'minotaur'], ['environment', 'http://www.nasa.gov/ladee', 'ladee', 'explorer', 'show', 'nasa’s', 'tenuous', 'sky', 'nearby', 'head', 'minotaur', 'atmosphere', 'play-by-play'], ['environment', 'ladee', 'explorer', '“the', 'atmosphere', 'u.s', 'shown', 'engineering', 'minotaur', 'systems', 'shows', 'you’ll', 'missions,”', 'along', 'order', 'nasa’s', 'horizon', 'p.m'], ['ladee–lunar', 'nasa’s', 'environment', 'available', 'explorer–will', 'isn’t', 'much', 'atmospheric', 'you’ll', 'probably', 'v', 'hint'], ['environment', 'ladee', 'minotaur', 'http://en.wikipedia.org/wiki/lunar_atmosphere_and_dust_environment_explorer', 'moffett', 'explorer', 'mission', 'developed', 'http://creativecommons.org/licenses/by-sa/3.0', 'surface', '2013', "nasa\\'s", '6', 'near', 'field', 'http://scitech.quickfound.net'], ['ladee', 'environment', 'take', 'thrusters', 'virginia', 'moon', '11:31'], ['environment', 'ladee', '–', 'explorer', 'finish', 'states', '156', '74', 'way', '5', '23:27', 'gets', 'night', 'even', '62', 'sept'], ['environment', 'explorer', 'ladee’s', 'ladee', 'surface', 'introduces', 'influences', 'environmental', 'dust', 'atmosphere', 'near', 'nasa’s', 'u.s', 'firsts', '2013'], ['environment', 'explorer', 'ladee’s', 'ladee', 'surface', 'introduces', 'influences', 'environmental', 'dust', 'atmosphere', 'near', 'nasa’s', 'u.s', 'firsts', '2013'], ['environment', 'underwent', 'ladee', 'mission', '2013', 'near', 'preparations', 'orbited', 'included', 'later', 'well', 'rise', 'ready', '31', "nasa's", 'prior', 'giving', 'side', 'scale', '7', 'detector', 'operations'], ['leeuwenhoek', 'molijn', 'well', 'toward', 'republic', 'bacteria', 'delft', 'lensmaking', 'came', 'mother', 'many', 'became', 'relatively', 'best', '1670s'], ['africa', 'khomas', 'including', "leeuwen's", 'gouda', 'studied', 'oemcke', 'sediments', 'washington'], ['would', 'announced', '2000', 'resulted', '2009', '2013', "rmc's", 'addition', '2', 'done', 'along'], ['leeuwenhoek', "leeuwenhoek's", 'opinion', 'rainwater', 'hartsoeker'], [], ['leeuwenhoek', 'press'], ['atmospheres', 'clouds'], [], ['ladee', 'environment', 'spacecraft', 'base']]
TOP TOKENS [['protein', 'proteins', 'n', 'amino', 'number', 'category', 'however', 'one', 'acid', 'nh', 'zn', 'e', 'present'], ['weight', 'tasks', 'bonds', 'proteins', 'anyway', 'protein', 'also', 'predominantly', 'quality', 'beginning', 'life', 'ions', 'diseases', 'contains', 'substances', 'functions', 'mucosa', 'every'], ['etc', 'protein', 'stronger', 'type', 'perfect', 'different', 'healthy', '–', 'proteins', 'popular', 'silk', 'shine', 'form'], ['protein', 'proteins', 'hydrolytic', 'group', 'taste', 'feather', 'obtained', 'solution'], ['proteins', 'function', 'many', 'recognized'], ['acids', 'protein', 'phosphorus', 'sulphur', 'fibrous', 'specified', 'prōtos'], ['id||/biology/protein/mmdb_id||/type/enumeration', 'acids', 'organisms', 'proteins', 'protein', 'consist', 'id||/biology/protein/entrez_gene_id||/type/int'], ['proteins', 'protein', 'etc', 'e'], ['high-quality', 'proteins', 'protein', 'known', 'plant-based', 'variety', 'based', 'wildlife', 'limitations', 'enzymes', 'grains', 'suitable', 'excess', 'hormones', 'come'], ['gram', 'organisms', 'body', 'protein', 'composed', 'consist', 'forms', 'skin', 'proteins', 'teeth', 'arterial', 'utilize', 'disease', 'mostly', 'walls', 'alkaline', 'water', 'balance', 'tissues', 'constituting'], ['acids', 'company', 'desambiguación'], ['protein', 'design', 'associated', 'isolates', 'sep', 'one', 'fibrous', 'proteins'], ['ordered', 'amino', 'protein', 'appropriate', 'ligands', 'electrophoresis', 'plants', 'proteins', 'attached', 'antibodies', 'cls', 'binds', 'glycoprotein'], ['protein', 'proteins', 'total', 'contributor', 'plasma', 'steroid', 'proteomics', 'progress', '55', 'identify', 'lipids'], ['antibodies', 'protein', 'proteins', 'g', 'yielding', 'igd', 'allows', 'interference', 'without'], ['proteins', 'protein'], ['addition', 'reviews', 'sons', 'journal', 'proteins', 'proposals', 'includes'], ['pathogenesis-related', 'proteins', 'originate', 'fungi', 'thaumatin-like', 'common', 'wine', 'industry', 'role'], ['proteins', 'uptake', '1'], ['protein', 'proteins', 'function', 'carcinogenesis', 'restricted', 'studying', 'sought', 'modifications', 'distinct', 'one', 'rough', 'cycle', 'translation', 'proteome', 'conditions', 'analysis', 'many', 'mentioned', 'different']]
TOP TOKENS [['dexter', 'dexterous'], ['dexter', "dexter's", 'dex'], ['dexter', 'dexterous', 'borrowed'], ['dexter', "dexter's", 'dexterous'], ['dexter', 'dex'], ['dexter', 'sep', 'bolt', 'schwarzkopf'], ['dexter', 'dexters'], ['dexter', 'outdone', 'profit', 'play', 'unbeknown'], ['dexter', 'friendly', 'ideals'], ['dexter', 'dexters'], ['dexter', 'blood', 'jr'], ['dexter', "dexter's", 'century', 'living', 'american', 'pianists', 'events', 'aligning', 'also', 'people'], ['dexter', 'site'], ['dexter', '0', '25', 'latino'], ['dexter'], ['dexter', 'early', 'celebrities'], ['dexter', 'known', '2', 't.a.c.g.r'], ["dexter's", 'dexter', 'sound', 'years', 'sep', 'screenwriters', 'powells', 'american', '–'], ['dexter', 'external', 'living'], ['dexter', 'songwriter']]
TOP TOKENS [['enzymes', 'enzyme', 'take', 'taking', 'doubt', 'given'], ['enzymes', 'enzyme-rich', 'enzyme', '“enzyme'], ['enzymes', 'bring', 'enzyme', 'ends', 'work', 'necessary', 'normal', 'take', 'taking', 'exercise'], ['enzymes', 'enzyme', 'get', 'enough'], ['enzymes', 'enzyme', 'blood', 'working', 'day', '150', 'use', 'exactly', 'oxygen'], ['enzymes', 'enzyme', 'synergistically'], ['enzyme', 'enzymes', 'raw'], ['enzyme', 'enzymes', 'efforts', 'basis', 'workhorses', 'use'], ['enzymes', 'enzyme', 'life'], ['enzymes', 'enzyme-rich', 'enzyme-depleted', 'enzyme', 'enzyme-making', 'regimen', 'system', 'diet', 'food'], ['enzyme', 'enzyme-linked'], ['enzyme'], ['enzyme', 'enzymes'], ['enzyme', 'enzymes', "enzyme's", 'example', 'thus', 'products', 'activity'], ['enzymes', 'enzyme', 'immobilized'], ['enzymes', 'enzyme', 'benefit', 'well', 'immobilized', 'autolysis', 'minimizing', 'kg'], ['enzymes', 'enzyme', 'application', 'immobilized', 'chemicals'], ['enzyme', 'enzymes', 'patients', 'use', 'containing', 'pompe', 'deaminase', '1991', 'therapeutic'], ['enzymes', 'enzyme', 'cells', 'due', 'greatly', 'immobilization', 'catalytic'], ['enzymes', 'enzyme']]
TOP TOKENS [['cleaning', 'uses', 'live', 'high', 'trimming', 'palms', 'extra', 'expense', 'electricity', 'property', 'exactly', 'use', 'efficient', 'life', 'unplug', 'energy', 'power', 'actually', 'thus', 'months', 'wintertime', 'costs', 'bill', 'carries', 'pricey', 'downpours', 'illuminations', 'residence', 'season', 'condo', 'elevate', 'house', 'lighting', 'lightings', 'therefore', 'leaky'], ['cleaning', 'extra', 'live', 'combing', 'wise', 'create', 'use', 'manage', 'spare', 'season', 'trimming', 'therefore', 'house', 'condo', 'actually', 'funds', 'elevate', 'daily', 'considerable', 'energy', 'palms', 'power', 'exactly', 'higher', 'costs', 'lightings', 'pearly', 'wintertime', 'winter', 'life', 'electricity', 'expensive', 'utilize', 'bill', 'result', 'faucet', 'lighting', 'expense', 'light'], ['cleaning', 'washing', 'extra', 'high', 'ideal', 'traits', 'palms', 'trimming', 'utilize', 'exactly', 'costs', 'every', 'repair', 'therefore', 'home', 'condo', 'lightings', 'create', 'expense', 'elevate', 'power', 'keep', 'higher', 'leaky', 'actually', 'time', 'tap', 'life', 'house', 'conserve', 'months', 'efficient', 'electricity', 'summer', 'make', 'energy', 'fixtures', 'winter', 'expensive'], ['version', 'make', 'either', 'usage', 'diabet'], ['manage', 'staying', 'higher', 'popsugar', 'set', 'uses', 'create', 'elevate', 'cause', 'absolute', 'lights', 'keep', 'means', 'use', 'condo', 'house', 'considerable', 'expense', 'exactly', 'summer', 'home', 'utilize', 'power', 'pricey', 'unplugging', 'natural', 'funds', 'winter', 'unneeded', 'actually', 'make'], ['manage', 'use', 'extra', 'residing', 'exactly', 'keep', 'specify', 'costs', 'makes', 'wise', 'items', 'season', 'therefore', 'power', 'life', 'whole', 'make', 'cash', 'house', 'naturalillumination', 'higher', 'electricity', 'energy', 'residence', 'lights', 'expensive', 'expense'], ['manage', 'utilize', 'factors', 'high', 'specify', 'makes', 'winter', 'costs', 'use', 'exactly', 'means', 'home', 'therefore', 'loan', 'house', 'life', 'things', 'summertime', 'pricey', 'create', 'lightlighting', 'actually', 'expense', 'energy', 'daily', 'residence', 'lights', 'elevate'], ['manage', 'high', 'wise', 'lightings', 'power', 'utilize', 'makes', 'specify', 'life', 'ordinary', 'season', 'actually', 'products', 'means', 'create', 'expense', 'energy', 'lightillumination', 'house', 'bill', 'therefore', 'day', 'costs', 'live', 'exactly', 'home', 'thus', 'electricity', 'elevate', 'money', 'summer', 'use', 'efficient', 'flat'], ['characteristics', 'used', 'outside', 'benefited', 'drawstring', 'ball', 'better', 'every', 'sphericity', 'history', 'argentina', 'offered'], ['combing', 'trimming', 'costs', 'washing', 'teeth', 'house', 'care', 'energy', 'costly', 'therefore', 'exactly', 'elevate', 'daily', 'property', 'higher', 'utilize', 'months', 'illuminations', 'bill', 'maintain', 'great', 'power', 'thus', 'hands', 'live', 'actually', 'expense', 'effective'], ['certain', 'shape', 'specific', 'else', 'made'], ['enchanted', 'prettiest', 'played'], ['effect', 'experiences', 'providing', 'another', 'also', 'huddling'], ['accessories', 'collectors', 'manufacturer', 'distinct', 'uses', 'many', 'addition', 'certain', 'amount'], ['roams', "herdsman's", 'alternatively', 'normally', 'placed', 'daughters', 'said', 'buschmutter', 'forest', 'gives', 'regionally', 'occasionally', 'times'], ['deaths', 'births', '–', 'references'], ['adds', 'add', 'manually', 'per', 'balance', 'extra', 'remove', 'mixture', 'around', 'achieve', 'extrudes', 'mix', 'rubber', 'pieces', 'methods', 'ensure', 'allows', 'approximately', 'applies', 'glass', 'better', 'still'], ['specific', 'distributing', 'spots', 'handled', 'finally', 'part', 'making', 'fang'], ['worn', 'influenced', 'supply', 'ordered', 'see', 'design', 'assist', 'given', 'near', 'figured', 'heaven', 'incorporated', 'also', 'members', 'amulets', 'honour', 'depict', 'sometimes', 'city', 'often', 'elaborately', 'alimenta', 'one', 'bearing', 'omnipresent', 'several', "faustina's"], ['care', 'links']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['60', 'factor'], []]
TOP TOKENS [['marginal', 'greater', '‘', 'com', '’'], ['marginal', 'certain', 'find', '10,000', 'lower', '30,000', 'others'], ['marginal', 'certain', 'find', '10,000', 'lower', '30,000', 'others'], ['marginal', 'say', '’', 'london'], ['marginal', 'another', 'particular'], ['marginal', 'employees', 'part-time', 'supports', 'failing', 'inhibit', 'employment'], ['marginal'], ['marginal', '“', 'thus', 'based', 'benefited', 'post', '‘'], ['marginal', 'combination', 'calculate', 'times', 'cost'], ['“marginal”', 'marginal', '“marginal', 'marginality', 'one'], ['marginal', 'marginalization'], ['marginal'], ['marginal', 'marginalism', 'marginalists', 'marginality', 'descriptive', 'greater', 'decrease'], ['“marginal”', 'marginal', '“marginal', 'marginalism', 'quantified', 'term', 'sorts'], ['marginal', 'marginality'], ['marginal', '“marginal”', 'considered', 'formerly', 'constitutes', 'conventional', 'term', 'less-than-ideal'], ['marginalize', 'marginalized', 'marginal', '1-26', 'thus'], ['marginal', 'contexts'], ['marginal', 'marginalizing', 'marginalized', 'marginalization', 'variables', 'also', 'various'], ['marginal', 'marginalism']]

Processing features:  37%|███▋      | 36/98 [17:19<30:26, 29.46s/it]

getting sample prompt forgetting sample prompt for 23833
 23832
getting sample prompt for 23834
getting sample prompt for 23835
getting sample prompt for 23836
getting sample prompt for 23837
getting sample prompt for 23838
getting sample prompt for 23839
getting sample prompt for 23840
getting sample prompt for 23841
getting sample prompt for 23842
getting sample prompt for 23843
TOP TOKENS [['woo?”', 'woofy', '“woofy', 'woo', 'woo”', 'woos”', 'call', 'woo!”', 'phrase'], ['woozle', '10', '1½', '6½', 'stand-up', '7¾'], ['farm/settlement’', 'two', 'wootton', 'following', 'one', 'farmstead', 'wood–timber’'], ['wooster', 'anecdotal', 'provides', '384', 'intricacies', 'points', '9', 'sound', 'time', 'deserves'], ['wootton', 'wooten', 'bassett'], ['wooster', 'wars', 'ineptitude', 'montgomery', 'wŏsˈtər', 'resigned'], ['‘woof’', 'woof', 'woo'], ['community', 'world', 'woogi', 'woogiworld', 'helping', 'addicts', 'wookie', 'materialism', 'develop', 'children', 'better', 'implementing', 'line', 'virtual', 'around', 'solution'], ['woozled', 'woozling', 'woozle', 'backing', 'disproportionate', 'one', 'bigger', 'saying', 'time', 'effort', 'case', '2010', 'true', 'problem', 'evidence', 'every', 'uncover', '“', 'starting', 'regrettably', 'central', 'strong', 'amount', 'people', 'nature', 'become'], ['wootz', 'wook', 'languages', 'items', 'precipitating', 'buttons', 'word', 'surface'], [], ['1780-1848', 'york-based', 'wooster', 'commander-in-chief', 'danbury', 'brigadier-general', 'square', 'u.s', 'ohio'], ['wooton'], [], ['retailer', 'chattanooga', 'wooton', 'w-zero-zero-t'], ['wootten', 'wooten', 'physician', '1957', 'american'], ['wootton', 'woottens', 'wootten'], [], ['wooster', '1903', 'remained'], ['new', 'wooster']]
TOP TOKENS [['coffin001', 'coffin003', 'coffin002', 'coffin', 'coffin005', 'coffin004', 'coffin006', 'lid', '001'], ['coffin', 'europe', 'war', 'enough', '1824', 'served', 'merchant', 'good'], ['coffin', 'coffins', 'rule', 'given', 'cls', 'world', 'demands', 'corpse', 'samuel', 'dawn', 'nigeria'], ['coffin', 'newport', '1847', 'slaves', 'merchant', 'funded', 'prospered', 'amendment', 'book', 'unmarked'], ['coffin', 'coffins', 'rebekah', 'zebdial', 'eliakim', 'bartlett', '2011'], ['coffin', 'coffins', 'captain', 'vessel', 'cls', 'tristram'], ['coffin', '1865', '”', 'right', '’', 'fisheries', 'adeline', 'cls', 'market', 'mass'], ['coffin', 'lieut', '1642', 'hon', 'elizabeth', 'adulthood', 'marriage', 'tombstone', 'old'], ['coffin', "coffin's", 'merchant', 'emeline', 'right'], ['coffins', 'coffin', 'caskets', 'cls'], ['coffin', 'coffins', 'centuries', '1642', "coffin's", 'boston', 'devonshire', 'royalist', 'antislavery', 'tristram', '1937', 'many', 'sloane'], ['coffin', 'corpse'], ['coffin'], ['coffin'], [], ['pine-coffin'], ['coffin'], ['coffin'], ['coffin'], ['coffin']]
TOP TOKENS [['lamina', 'basal', 'laminin', 'cc.edu', 'proteins', 'better', 'coincidence', 'survive', 'b'], ['lamins', 'lamina', 'lamin-binding', 'nucleus', 'plethora', 'certain', 'b-type', 'lamin'], ['lamin', 'domain', 'lamina', 'lamins', '572', 'mw', '139', '1', 'da', '566', '1a'], ['lamina', 'international', 'heaven', 'ˈlamənən', 'laminin'], ['three', 'save', 'entirely', 'laminate’s', 'laminate', 'also', 'much', 'directly', '–', 'resin-impregnated', 'lines', 'structure', 'nowadays', 'logoclic®'], ['lamina', 'laminae', 'lammergeier', 'lamnunguia', 'lammergeir', 'laminitis', 'laminiferous', 'southern', 'pl', 'northern', 'laminated', 'africa', 'lamish', 'n', 'lamm', 'europe', 'lammas'], ['lamins', 'lamin', 'designated', 'protein', 'laminadel10', 'later', 'asynchronously', 'rober'], ['lamina—a', 'lamins', 'lamina', 'lamin', 'proteinaceous', 'carboxy-terminal', 'c-terminal', 'box', 'laminins', 'carboxymethylated', 'inner', 'a-type', '5q23', 'gastrulation', 'veil'], ['laminate', 'laminations', 'laminators', 'lamination', 'well', 'home', 'laminator', 'heavy-duty', 'pre-cut', 'common'], ['lamination', 'laminations', 'better', 'may', 'beam', 'usually'], ['nucleus', 'house', 'surname'], ['veneto', 'crete', 'belluno'], ['density', 'family', 'flowerhead', 'layering', 'layers', 'horse', 'mass', 'laminar', 'peripheral', 'lamina'], ['described'], ['lami'], ['lamina', 'lamination', 'process', 'laminae'], ['1929', 'part', 'members', '118th', '156f', '48', '7', 'new', 'june'], ['northeast', '4', 'area', 'council'], ['northwest', '789', 'basin'], ['1901', 'porte', "bataille's", "brieux'la", 'saint', 'seule']]
TOP TOKENS [['botanical', 'botanicalbrahmanical', 'botanically', 'botanicals', 'japan', 'university', 'plants'], ['botanic', 'botanical', 'botanist'], ['botanical', 'botany', 'botanist', 'botanists', 'people'], ['botanical', 'botanist', 'botany', 'botanists', 'greenhouses', "bachelor's", 'companies'], ['botany', 'botanists', "botanist's", 'botanist', 'sc', 'bsc'], ['botany', 'botanicals', 'botanists', 'botanist'], ['botany', 'botanical', 'botanic'], ['botany', 'botanist', 'botanists'], ['botanists', 'botanist', 'botany'], ['botanical', 'botany'], ['botanical', 'botanic'], ['botanical', 'botanic', 'disambiguation'], ['botanic', 'botanica', 'botanical', 'botany', 'botanist'], ['botánica', 'botanica'], ['botany', '19th', 'around', 'latter', 'library'], ['botanical', 'botanic', 'jallo', 'zamindar', 'faisalabad', 'park', 'rani', 'mardan', 'education'], ['botany', 'botanist', 'opened'], [], ['botanical', 'botanic', 'education'], ['botany']]
TOP TOKENS [['humbert', 'halbert', 'dilbert', 'hurlbert', 'calbert', 'aubert', 'dalbert', 'edbert', 'ecbert', 'umberto', 'humberto', 'hammet', 'egbert', 'humphry', 'humphery'], ['elbert', 'ethelbert', 'elberta.kreatif', 'aubert', 'elbertei', 'dalbert', 'delbert', 'eielbert', 'eilwbert', 'adelbert', 'u.s'], ['norbert’s', 'norbert', 'norbertine', 'saint', 'noble'], ['norbert', "norbert's", "title'norbert", 'st', 'goal', 'heriberts', 'worldly', 'according', 'active', 'gennep'], ['norbert', 'st', '–st', 'life', 'place', 'priest', 'www.newadvent.org/cathen/11100b.htm', 'saint', 'heat'], ['norbert', 'norbertine', '1126', 'premontre'], ['norbert', 'life', 'priest', 'place', 'saint', 'like'], ['norbert', 'norbertine', 'st', 'monstrance'], ['norbert', 'norberts', 'norbertines', 'nickname', 'reluctantly', 'enemies'], ['norbert', 'life', 'priest', 'saint', 'place', 'like'], ['wilbert'], ['halbert'], ['imbert', 'imbert-terry', 'imbert–fedorov', 'chantenay-saint-imbert'], ['hebert', 'heberti', 'hebertville', 'thuit', 'foulbec', 'beati', 'manche'], ['shubert', 'disambiguation'], ['milbert'], ['kubert'], ['hobert'], ['elbert', 'elbertus', 'alibert', 'american'], ['dilbert']]
TOP TOKENS [['bedwetting', 'bed-wetting', 'bedwetters', 'wetting'], ['bedwetting', 'wetting', 'wet'], ['bedwetting', 'wetting', 'wet'], ['bedwetting', 'wetting', 'bed-wetting', 'wet'], ['wetting', 'bedwetting', 'wet'], ['bedwetting', 'wets', 'wet'], ['bedwetting', 'wets', 'wet'], ['bedwetting', 'wets', 'wet'], ['wetting', 'bedwetting', 'bed', 'wet'], ['bedwetting', 'wetting', 'bedwettingbehavioral', 'bedwettingchildren', 'wet', 'enuresis', 'bed'], ['bedwetting', 'bedwetters', 'wetting'], ['wetting', 'bedwetting', 'bed'], ['bedwetting', 'wetting', 'reoccurrence', 'causes', 'enuresis'], ['wetting', 'bedwetters', 'bedwetting', 'bed', 'wet', 'enuresis'], ['wetting', 'bedwetting', 'bedwetters', 'wet', 'wets', "child's", 'bed'], ['bedwetter', 'enuresis', 'nocturnal'], ['wets', 'wetting', 'bed', 'daytime', 'enuresis', 'clinically'], ['wetting', 'bedwetting', 'bed', 'mowrer', 'enuresis', 'nocturnal', 'wet', 'orval', 'pediatrician', 'significant'], ['wetting', 'bedwetting', 'bed', 'persistent', 'frustration'], ['wetting', 'one']]
TOP TOKENS [['mcnamara', 'goal', 'hierarchy', '—', 'robert', 'company', '1995'], ['mcnamara', "mcnamara's", 'poorest', 'time', 'robert', 'failure', 'war', 'vietnam'], ['mcnamara', "mcnamara's", 'cls', 'kennedy', 'lobbies'], ['mcnamara', '1981', 'however', 'administration', 'james'], ['mcnamara', '1981', 'leading'], ['mcnamara', '1981', 'apartheid'], ['mcnamara', 'berlin', 'war', 'communism', 'withdrawal', 'robert', 'cls'], ["mcnamara's", 'mcnamara’s', 'policies.”', '“his'], ['mcnamara', '”', 'lives', 'soared', 'robert', '’'], ['mcnamara', 'room', 'ceremony', 'children', '”', 'ii'], ['mcnamara'], ["mcnamara's", 'mcnamara'], ['mcnamara', 'scandal', 'edmonton', 'biography'], ["mcnamara's", 'mcnamara'], ['mcnamara'], ['mcnamara'], ['mcnamara', 'brigade', '99th', '1929', '1899–1902', 'military'], ['mcnamara', 'soccer', 'season', '2019–20', 'brazilian', 'devolli'], ['mcnamara', 'gymnastics', 'us'], ['mcnamara', "mcnamara's", 'griffins', 'seasons', 'born']]
TOP TOKENS [['ska', "ska's", 'world'], ['ska', "ska's", 'world'], ['ska', 'ska1', 'ska2', 'facility'], ['ska', 'major', 'cls'], ['ska', 'aims'], ['ska', 'aims'], ['ska', 'ska1', 'observations', 'sites'], ['ska', 'ska1', 'observations', 'sites'], ['ska'], ['ska'], ['ska', 'ska-energiya', 'khabarovsk', 'petersburg', 'ska-sverdlovsk', 'rostov-on-don', 'shoro-ska', 'ska-p', 'germany', 'society', 'ska-hatlon', 'army', 'leafhopper', 'ska-neftyanik', '1981'], ['ska', 'james', '2004', 'justin', 'trevor', 'charlotte', 'machine'], ['ska', 'support', 'studios', 'net/xna', 'video', 'controls', 'gory'], ['ska', 'ska-jazz', 'skatalites', '1950s', 'late', 'percussion'], ['ska', 'skatune', 'skatsune', 'interest', 'punk', 'also', 'interrupters'], ['ska', 'audiences', 'charts', 'though'], ['ska', 'pacific', 'ca', 'aquabats'], ['ska2', 'ska1', 'ska', 'ska3'], ['ska', 'san', 'man', 'frankenstein', 'city', 'kenji', 'wars'], ['ska', 'skatroits', 'sk', 'skall', 'electronica', 'ppisch', 'skapontas', 'bands']]
TOP TOKENS [['lung', 'cancer', 'nsclc', '2002'], ['lung', 'cancer', 'cancers'], ['lung', 'cancer', 'cell'], ['lung', 'nsclc', 'cell', 'chest', 'cancer', 'options', 'cases'], ['lung'], ['lung'], ['lung', 'lungnodule', 'saving', 'cancer'], ['lung', 'cancer', 'one'], ['lung', 'cancer'], ['lung', 'nsclc', 'cancer'], ['lung', 'nsclc', 'cell', 'cancer', 'sclc'], ['lung', 'medicaid', 'cancer'], ['lung', 'nsclc', 'cancer', 'cell'], ['lung', 'cancer'], ['lung', 'cancer', 'cell', 'disease', "patient's", 'scans', 'located'], ['lung', 'however', 'cancer'], ['lung', 'reports', 'scisearch'], ['lung', 'cell', 'cancer', 'patients', 'disease', '60', '4'], ['lung', 'cell', 'cancer', 'conference', 'carcinoma', '3', '17', 'disease'], ['lung', 'cell', 'cancer', 'tumour', '1', 'patients', 'radiochemotherapy', 'thoracic', 'hematologic', 'reduce']]
TOP TOKENS [['fed', "fed's", 'thus', 'restraint'], ['fed', "fed's", 'thus', 'restraint'], ['fed', 'years', '’'], ['fed'], ['fed', 'they’re'], ['fed'], ['fed', "fed's", 'prompt'], ['fed', 'least', '2013', 'oct'], ['fed'], ['fed', 'many', '“', 'several'], ['fed'], ['fed'], ['fed', 'links', 'external'], ['fed', "fed's", '2020'], ['fed', "fed's"], ['fed', 'put', 'also'], ['fed', '1', 'shutter', 'unit', 'hand', 'used'], ["fed's", 'fed', '2021'], ['fed', "reserve's", '2008', 'moreover', 'make'], ['fed', "fed's", 'lation', 'reserve', 'funds']]
TOP TOKENS [['household'], ['household'], ['exchequer', 'consisting', 'year'], [], ['exchequer', "heads'exchequer", 'consisting', 'year'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['make', 'use'], ['can’t', 'counterpart', '“because', 'latino', 'money?”', 'front', 'well.”', 'indicates', 'it’s', 'says', 'don’t', 'often', '1.how', 'despite', 'voice', 'i’m', '“please', 'saying', 'leader.”', 'item'], ['think', 'eye', 'can’t', 'mean', 'move', 'tells', 'help', 'see', 'hand', 'discovered', 'needs', 'need', 'people’s', 'really', 'feet', 'together'], ['always', 'helped', 'another', 'sometimes', 'since', 'course'], ['impact', 'something', 'significant', 'solve', 'note', 'see', 'bit', '“', 'way', 'much', 'ding', '”', 'budget', 'side', 'sure', 'going', '—', 'like', 'another', '’', 'needing', 'know', 'woes', 'user', 'taking', 'midst'], ['tells', 'supposed', 'found', 'brought', 'neglecting', 'might', 'see', 'usually', 'indicate', 'one', 'leads', 'often', 'second', 'since', 'spends', 'sigh', 'sometimes', 'highlights', 'easily', 'alike'], ['got', 'mean', 'provide', 'activities', 'things', 'various'], [], ['help'], ['helping', 'find', 'eye', 'even', 'whether', 'also', 'though', '’', 'favorite', 'told', 'periodically', 'quite', 'help', 'level', 'spoken', 'got', 'example', 'recall', 'needs'], ['point', 'affect', 'treating', 'momentarily', 'piggybacked', "seniors'joint", 'prove'], ['hear', 'presence', 'problem', 'evidence', 'idea', 'identify', 'syndrome', 'focus', 'reflected', '2008', 'squeaks', 'something', 'gets', 'assure', 'also', 'however'], ['improving', 'ordinated', 'issue', '850', 'concentrates', 'rotary', 'rise'], ['generously', 'always', 'explains', 'given', 'begrudgingly', 'admonishes', 'even', 'comments', 'apprehensive', 'around', 'break', 'hefty', 'better', 'pud', 'coming', 'also', 'alumni', 'different', 'trying'], ['inability', 'channel', 'something', "spongebob's"], ['lot', 'matter'], ['matter', 'much', 'matters', 'tries', 'many', 'one', 'hand', 'take', 'believes', 'says', 'moms', 'stays', 'ongoing', 'validate', 'say', 'sometimes', 'makes', 'may'], ['slip', 'often', '25', 'issues', 'subject', 'encouragement', 'fine', 'starbucks', 'discuss', 'withering'], ['informs', 'mistletoe', "sandy's", 'presented', 'compensate', 'much', 'show', 'sign', 'explains', 'hurting', 'graciously', 'overhead', 'follows', 'asking', 'winds', 'sees', 'rudeness', 'receives', 'perceiving'], ['one', 'airtight', 'another', 'often', 'small']]

Processing features:  38%|███▊      | 37/98 [17:46<29:11, 28.72s/it]

getting sample prompt forgetting sample prompt for 23845
getting sample prompt for 23846
getting sample prompt for 23847
 23844
getting sample prompt for 23848
getting sample prompt for 23849
getting sample prompt for 23850
getting sample prompt for 23851
getting sample prompt for 23852
getting sample prompt for 23853
getting sample prompt for 23854
getting sample prompt for 23855
TOP TOKENS [['tibia', 'tibial', 'femoral', 'femur', 'leg', 'broken', 'trauma'], ['tibia', 'tibial', 'fibula', 'leg'], ['femur', 'tibia', 'tibial', 'cls', 'fibula', 'minimally'], ['femur', 'tibia', 'tibial', 'cls', 'fibula', 'minimally'], ['tibia', 'femur'], ['tibia', 'tibial', 'femoral', 'tibiofibular', 'fibula'], ['tibia', 'tibial', 'anterior', '1-cm', 'subcutaneous', 'surface', 'artery', 'cadaveric'], ['tibia', 'femur', 'femora', 'coll', 'abbreviations'], ['tibia', 'tibiae', '0', '–', '39', 'posteriorly', '1', 'numerous'], ['tibia', 'femur', 'tibial', 'medial', 'cls'], [], ['tibialis', 'tibia', 'tibial', 'bifurcates', 'popliteus', 'ends', 'medial', 'fibia'], ['femoral-tibial', 'tibiae', 'tibia', 'femur'], ['tibia', 'tibial', 'tibialis', 'popliteal'], ['tibia', 'tibialis'], ['tibia'], ['tibia'], ['tibial'], ['tibial'], ['tibia', 'tibialis', 'fibula', 'together']]
TOP TOKENS [['garland'], ['garland'], ['garland', 'summers', 'also', 'rob'], ['garland', '2008', '1874', 'name', 'cls'], ['garland', 'h', 'today', 'company', 'city'], ['garland', 'largely', 'however'], ['garland', 'war', 'union', 'parte', 'adulthood', 'states'], ['garland', 'according', '’', 'processors', 'includes', 'downtown', 'city'], ['garland', "garland's", 'parte', 'law', 'cls'], ['garland', 'garlands', 'garlande'], ['garland', 'judy', 'album', '1952', '1923-1984', 'types', '1960', 'garlands'], ['garland', 'youngsville'], ['garland'], ['garland', 'defined', '1880s'], ['garland', '2017', '2020', 'guard', 'played', '2019', 'christian'], ['garland'], ['garland', 'p'], ['garland', "garland's", 'others', '2014', 'network', 'conference', 'international', 'received'], ['garland', 'links'], ['garland']]
TOP TOKENS [['continue', 'student', 'ages'], ['smelted', 'whims', 'owner', 'one', 'food', 'iron', 'finally', 'day', 'needs', 'even'], ['sec', 'came', 'ah', 'ahem', 'school', 'rant', 'promptly', 'virus'], ['little', 'owner', 'since', 'level', 'entrance'], ['”', 'later'], ['anything', 'minor', 'else'], ['breeze', 'sail', 'authors', 'guess'], ['says', 'later', 'talks', 'well', '’', 'tent', '”'], ['r', 'ry', '761', 'n', 'e', 'black', 'thinned', 'passengers'], ["there's", 'end', 'breaks', 'something', "luce's", 'tough', 'titanic', "that's"], ['control', 'boats', 'anyone', 'finder', 'like', 'likewise', 'even', 'existed', 'airplanes', 'meantime'], ['luton', 'philippines', 'devon', 'kent', 'cebu', 'teignbridge'], ['see', 'also'], ['technicality', 'past', 'assistance', 'rhythms', 'geography'], ['1847–1934', 'c', '1903–1971', '1838–1894', '1959', '1916–1982'], ['hockey', 'ice', 'sports', 'disambiguation', 'judoka', '1941–2022', '1919–1998'], ['e-book', 'naturalist', 'publisher', 'canadian', 'caius', 'journalist', '1792–1856', 'biolinguist', 'college', 'senator', '1943–2006', 'professor', 'psycholinguist', '1849–1921', 'poet', '1923–1998', 'representatives', 'u.s', '1805–1880', '1867–1873', 'phonologist', 'born', '1962', '1764–1855', 'l', '1825–1873', 'southwark', '1847–1889', 'bursar', 'locke'], ['hendrik', 'hendrik-ido-ambacht', 'producer', 'greenlandic', 'hans', '1832–1889', 'disambiguation', 'island', 'born', '1945'], ['municipality', 'aldehuela', 'jerte', 'de', '1729–1802', 'zaragoza', 'salamanca'], ['hockey', 'irish', '1901–1973', 'mid-1980s', 'motorcyclist', '1927', 'born']]
TOP TOKENS [['gloria'], ['gloria'], ['gloria', 'loved', 'sunflowers', 'death', 'earth’s'], ['gloria', 'cls', '14', 'explains', 'name', 'george', 'toward', 'naylor'], ['gloria', 'memory', 'heart'], ['gloria', 'gloriana', 'glōria', 'tell', 'glory'], ['gloria', 'far', 'children'], ['gloria', 'march', '11', 'steinem', 'magazines', 'chisholm', "women's", 'first', 'bella', '25', '1960s', 'wikipedia', 'came'], ['gloria', 'way', 'however', 'e', 'naylor', 'emphasizes'], ['gloria', '”', 'meyer', 'criminologist', '8103'], ['glória'], ['gloria'], ['glória', 'near', 'brazil'], ['gloria'], ['gloria', "gloria's", 'one'], ['gloria', "gloria'''s", 'magazines', '2007', 'croatia'], ['glória', '2006'], ['glória', 'gloria'], ['gloria'], ['glória', 'meaning', 'maria']]
TOP TOKENS [['instalacja', 'powstał', 'historycznej', 'została', 'czesci'], ['południe', 'zaleta', 'bedziemy', 'jej', 'stronie', 'tylko'], ['około', 'iazki', 'uzupełnie', 'przedswiateczny', 'przygotowuje', 'bedzie', 'południa', 'swiatowy'], ['artykuł', 'sekcja', 'mozesz', 'rozdział', 'nieprzetłumaczony', 'przetłumaczyc', 'błedny', 'pomoc', 'nawałnica'], ['wszech', 'jednego', 'powszechnego', 'uznawany', 'najwazniejszych', 'krywca'], ['wciskac', 'dopiszcie', 'sobie', 'cokolwiek', 'dobrze', 'własnie', 'zarzucac', 'wizytowki', 'ludziom'], ['dlaczego', 'powoduje', 'odpowiedzi', 'zaopatrzy', 'tym', 'rozdziale', 'stanowi', 'zmiana', 'piej', 'indywidualnych', 'pomoe', 'kosztowo', 'przerzucanie', 'korzystajcy', 'uytkownika', 'firmowej', 'wszyscy', 'powinni', 'czas'], ['wiecej', 'szczegołow', 'prywatnosci', 'takze', 'ustawien', 'zapisanych', 'korzystanie', 'urzadzenia', 'naszej', 'uzyskujemy', 'plikach', 'prawidłowego'], ['przeczytasz', 'idzie', 'wydarzeniem', 'dowolnej', 'gwarancje', 'obsługujacej', 'całosc', 'tysiace'], ['podpisało', 'wpisuje', 'słowami', 'wspołczesna', 'drogowskazy', 'działania', 'stanowia'], ['został', 'zostały', 'zołnierze', 'miała', 'tytuł', 'poczatkowo', 'przerwane', 'wydanie', 'grobu', 'powiesc', 'cesarzowej', 'powiescia', 'czarownice', 'grzechu', 'opublikowany', 'ostatecznej', 'jesli', 'planowane', 'twarze', 'nad', 'zapowiedziana', 'progiem', 'nosic', 'wojownik', 'lokalny', 'jestem', 'prace', 'przygotowaniu', 'antologii', 'wydawnictwo', 'mroku', 'słow', 'wyrocznia', 'czyli'], ['planowane', 'ostatecznej', 'wydanie', 'połowa', 'tytuł', 'reguły', 'opowiadania', 'czekajac', 'lokalny', 'poziom', 'spotkanie', 'zagłady', 'zbior', 'andrzejem', 'przygotowaniu', 'barbarzyncow', 'wypasacz', 'twarze', 'przestworzach', 'jesli', 'jestem', 'drzewinskim', 'młody', 'wspolnie', 'granicy', 'zamkniety', 'blisko', 'piekła', 'zakład', 'gorzowski', 'pułapka', 'naukowej', 'precedens', 'polski'], ['pieniadze', 'operacja', 'wszystko', 'prawo', 'pokoj', 'ekstradycja', 'nie', 'słodko', 'kochanka', 'lepiej', 'najwazniejsze', 'upadku', 'paweł', 'słaba', 'pułapka', 'zawrocony', 'tadeusz', 'obywatel', 'siedlisko', 'michał', 'kapelusza', 'weryfikacja', 'gorzki', 'mnie', 'straszny', 'spokojnego', 'pogrzebie', 'własnym', 'czy', 'dezerterow', 'wariatow', 'głowa', 'szczur', 'człowiek', 'ojca', 'miauczynski', 'mrzonka', 'dzidziusia', 'jako'], ['pozniej', 'samotnosc', 'noszy', 'perypetiach', 'dziestolatek', 'poziomo', 'czterdziestolatek', 'pojedynek', 'czyli', 'opałach', 'zgłos', 'sie', 'wiedzmy', 'zagoi', 'kanał', 'powiedział', 'wojna', 'klare', 'małgosia', 'licencja', 'społa', 'czarno', 'domu', 'synowie', 'ranczo', 'niezły', 'sublokatorzy', 'faceci', 'według', 'zastepcza', 'wziecia', 'kiepskich', 'lat', 'rodzicow'], ['fundacyjne', 'salezjanie', 'opactwo', 'nieznany', 'łukomskiego', 'sztuki', 'andrzej', 'relikwiarz', 'pocysterskim', 'nowsze', 'kosciele', 'malowidła', 'zeliwne', 'dawne', 'rocznice', 'mecenasa', 'zbigniewowi', 'ołtarz', 'łukasza', 'zaleskiego', 'widok', 'dedykowany', 'urodzin', 'wiel', 'historii', 'relikwie', 'procesy', 'seminare', 'janusz', 'opactwie', 'poł', 'mikołaja', 'zabytki', 'spustoszenia', 'odlewnictwo', 'latach', 'polsce', 'wyroby'], ['najwazniejszy', 'wspolnej', 'przedwiosnie', 'popielec', 'złotopolscy', 'biegiem', 'sprawa', 'siedlisko', 'gasienicow', 'połanieckich', 'zespoł', 'szpilki', 'miłosc', 'prosto', 'ojciec', 'rajskie', 'zostac', 'deszczu', 'szczegolne', 'psie', 'przeprowadzki', 'społka', 'pogoda', 'tredowata', 'dnie', 'wdowy', 'mateusz', 'polskie', 'pierwsza', 'wojna', 'przepis', 'rzeka', 'pensjonat', 'tancerze', 'twarze', 'drogi'], ['czyli', 'zespoł', 'sztuki', 'łukomskiego', 'nieznane', 'pocycterskim', 'koscioł', 'mistrza', 'rzym', 'opactwo', 'pocysterskiego', 'kosciele', 'zabytkowy', 'ołtarze', 'dwie', 'bozej', 'patriotyczne', 'zaleskiego', 'panstwowe', 'powstancza', 'historii', 'klasztorny', 'naukowe', 'seminare', 'czestochowskiej', 'janusz', 'widok', 'nagrobek', 'mogiła', 'wydawnictwo', 'cysterskiego', 'wielkopolski', 'pocysterski'], ['straganie', 'trzech', 'zespoł', 'skakanka', 'chodzenie', 'swiatła', 'wlazł', 'stokrotka', 'osenka', 'czasie', 'swiecie', 'lekcja', 'pawłowska', 'wesołe', 'domowa', 'dzieciecy', 'graniaste', 'zabawe', 'przedszkola', 'sie', 'czary', 'ługi', 'chciałbym', 'swoje', 'łazienkowe', 'murawska', 'goralski', 'imie', 'krasnoludki', 'teatru', 'najłatwiejsze', 'nazywam', 'misie', 'michał', 'szczesna', 'papugi', 'dominik', 'kazdy', 'kołko', 'łapci', 'dla'], ['zapiski', 'wiersze', 'trzech', 'urzad', 'slaskie', 'wydawanym', 'krzywej', 'pieszyc', 'sudecka', 'pieszyce', 'dzierzoniow', 'rozdział', 'stowarzyszenie', 'bogaty', 'dziki', 'naczelny', 'zdobyto', 'angielskie', 'zachod', 'poetyckich', 'pieszycki', 'wydanie', 'zabkowice', 'dziennik', 'poezja', 'poznaniu', 'złote', 'emigracja', 'poematy', 'zatoki', 'otwarty', 'polsko', 'publiczna', 'loteryjna', 'wiezy', 'odcinkach', 'czyli', 'biblioteka', 'artystyczne', 'latach', 'tygodniku', 'randka', 'miasta'], ['rakcyjne', 'turystyczne', 'szlaki', 'krajoznawczy', 'mały', 'dawnego', 'szczecina', 'kawiarenki', 'zielen', 'rusalka', 'dendrologiczny', 'przewodnik', 'tadeusz']]
TOP TOKENS [['opacity', '“', 'see', '’'], ['continues', 'time', 'character', '9', 'string', '4', 'next', 'n', '8', 'match', 'attempt', 'previously'], ['continues', 'time', 'character', '9', 'string', '4', 'next', 'n', '8', 'match', 'attempt', 'previously'], ['hitchhiker', 'everyone', 'driver', 'something', 'soon'], ['screen', 'one', 'earth', 'l', 'instead', 'sphere', 'way', 'example', 'fast', 'found'], ['exhibitions', '4', '2', 'screen', 'surfer', 'public', '1', 'cls', 'displayed', 'one', 'algebraic', 'minutes', 'time', 'interactive', 'visitors', 'surrounded', 'two', 'optionally', 'features', '0', 'tutorial', 'another', 'often'], [], ['car', 'reflections', 'city', 'several', 'cityscape', 'reflective', '10', 'map', 'visual', 'cls', 'temporarily', '1', 'see'], [], ['teleporno', 'one', 'taina', 'always', 'j', 'father', 'cj1e7t', 'right', 'ce', 'namarie', 'elendil', '5', 'vj', 'v5', 'utulien'], ['nowhere', 'overstays', 'describing', "game's", 'comes'], [], ['continental', 'strait', 'white', 'suburban', 'blue', 'purple', 'care', 'ray', 'c5', '10', 'however', 'seems'], ['electronic', 'ethereal', 'pop', '1', 'song', 'wildly', 'number', 'gloopy', 'chart', 'kilter', 'following', 'rainbows', 'psychedelic', '13', 'rainbow', 'warped', 'wobbling', '000', 'aural', 'music', 'careening', 'sales', "band's", 'zooming', "core's", "album's", 'blatantly', '200', 'elite'], ['australian', 'echoes', 'runaway', "aurora's", 'aurora', 'times', 'sky', 'repeatedly', 'norway', 'towards', 'song', 'release', 'chart', 'eeriness', 'became', 'billboard', 'background', 'standout', 'feneberger'], [], ['consistently', '–', 'retro-psychedelic', '10', 'weird', 'additional', 'highly', 'multi-tracked', 'nobody', 'dave', 'notes', 'maximum', 'trio', 'art', '11', 'separate', 'vague', 'samples', 'self-titled', '1', 'mixing', '2', 'affair'], ['descendant', 'descendants', 'j', 'numbers', 'n', 'type', 'ranks', 'unknown', 'resp', 'group', 'furthermore', 'let', 'next', 'h', 'contrast'], ['sonic', 'dynamic', 'australia', 'eternally', 'aria', 'acrobatic', 'overkill', 'song', 'number', "song's"], ['pollution', 'long', 'society', 'technological', 'much', 'woman', 'tree']]
TOP TOKENS [['scout', 'scouting', 'scouts'], ['scout', 'scouts', 'scouter'], ['scout', 'scouts'], ['scout', "scout's", 'scouts', 'scouters', "say'scout", "why'scout"], ['scout'], ['scout', 'scouting', 'scouts', 'www'], ['scout', "scout's", 'scouts', 'scouting', 'wildlife', 'comes', 'unselfish', 'clean'], ['scout', 'scouting', 'scouts', 'century'], ['scouts', 'scout', 'scouting'], ['scout', 'scouts', 'scouter', 'scouting', 'heard', 'deed', 'polite'], ['scouts', 'scout', "grey's", 'scouting', 'organisations'], ['scout', 'scouts'], ['scout'], ['scout', 'scouting', 'scouts'], ['scouts', 'scout', 'scouting', 'trapezoid-shaped'], ['scout', 'scouts', "scout's", 'scoutmaster'], ['scout', 'scouts', 'scoutmaster', 'others'], ['scout', 'scouts', 'scouting'], ['scouts', "scout's", 'scout', 'girl', 'scouters', 'scouting'], ['scout', "scout's", 'scouts', "scouts'duty", "scouts'association", "scouts'honour", 'scouters']]
TOP TOKENS [['continuous', 'take', 'using', 'non', 'used', 'present', 'generally', 'perfect'], ['continuous', '‘', 'like', 'versus', '“', 'think', 'ongoing', 'one', 'even'], ["a'continuous'process", 'continuous', 'without', 'number', 'gateway', 'x', 'speech', '1985', 'define', 'definition', 'hill'], ['continuous', 'place'], ['continuous', 'essence', '“', 'process', 'significance', 'implementing', 'exist', 'essential', 'every'], ['continuous'], ['continuous', 'continuously', 'continuousness', 'perforated'], ['continuous', 'continual'], ['continuous', 'continuously', 'different', '–'], ['continuous', 'continuously', 'different', '–'], ['continuous', 'attributes', 'practice'], ['continuous', 'continuous-time', 'continuous-space-time', 'uses'], ['continuous', 'continuously', 'search', 'specifically', 'one-parameter', 'achieved', 'higher-dimensional'], ['continuous', 'continuously', 'incremental', 'time', 'however', 'real', 'distinction', '1946'], ['continuous', 'assumption'], ['continuous', 'called', 'axioms', 'von'], ['continuous', 'non', 'strategies', 'however', 'generalization', 'uncountably', 'may', 'required'], ['continuous', 'high-intensity', 'forms', 'low-intensity', 'suitable', 'minutes', '100', '30', '60-65', 'intensity'], ['continuous', 'ongoing', 'constant', 'hours', 'system', 'assessment', 'formative', 'towards', 'feedback', 'proponents', 'despite'], ['continuous']]
TOP TOKENS [['modals', 'modal'], ['modal', 'modals'], ['modal', 'modals'], ['modal', 'modals', 'call'], ['modal', 'modals—words', 'modality', 'permission', 'modalities—qualify', 'modalities'], ['modal', 'modals'], ['modal'], ['modal', 'modals', '“modal', 'verbs'], ['modal', 'modals', 'suggestion', 'correct'], ['modal', 'modals', 'modality'], ['modality', 'modal'], ['modal', 'modality'], ['modal', 'modals', 'modality', 'advice'], ['modal'], ['modal', 'necessary', 'modality', 'modalities', 'taste', 'truths', 'construes', 'therapeutic'], ['modal', 'modality', 'following'], ['modal', 'modality', 'ineluctably', 'unarguably', 'indubitably', 'unquestionably'], ['modal', 'cls', 'obligation'], ['modal', 'modality', 'plato', 'stanford'], ['modality']]
TOP TOKENS [['plant', 'planting', 'want', 'ts', 'planted', '’', 'one', 'time', 'especially', 'cls'], ['planting', 'plant', 'conductive', 'want', 'may', 'planted', 'occur', 'time', 'unavoidable', 'method', 'best', 'future', 'putting'], ['planting', 'yield', 'plant', 'planted', 'statewide', 'starting', 'mean', 'idea', 'reasons', 'fall', 'average', 'one', 'may', 'establish', 'getting', 'late', '2012'], ['planting', 'selected', 'plant', 'plantings', 'late', 'within', 'recommend', 'university', 'embedded', 'respective', '10', 'planted', 'early'], ['plant', 'small', 'planting', 'planted', 'frozen', 'cls', 'likewise', 'time', 'avoid'], ['planting', 'plant', 'region', 'never', 'planted', 'properly', 'time', 'improperly', 'us', 'challenge', 'number'], ['planting', 'species', 'plant', '–', '’', 'around', 'tree', 'creates', 'whatever', 'individuals', 'heart', 'talk', 'trees'], ['planting', 'species', 'plant', '–', '’', 'around', 'tree', 'creates', 'whatever', 'individuals', 'heart', 'talk', 'trees'], ['plant', 'ordinary', 'planting', 'proper', 'time', 'planted', 'successful', 'make', 'hand', 'jab', '1', 'used'], ['plant', 'planting', 'grow', 'avoid', 'proper'], ['plant', 'planting', 'tree', 'companies', 'depending', 'activity', 'grow', 'planted', 'public', 'cls', 'parts', 'different', 'major', 'breathe', 'fire', 'amelioration', 'quality', 'involves', 'grounded'], ['roads', 'landscaping-gardening', 'planting', 'donation'], ['planting', 'mainly', 'encouraging', 'tree', 'plant', 'planted', 'conservancy', 'planter', '1', 'since', 'however', '1989', 'communities', 'period'], ['much', 'planting', 'britain', 'plant', 'thus', 'tree', 'plants', 'columbian', 'planters', 'great', 'work', 'factored', 'planter', 'average', 'often', 'experienced', 'upwards', 'germany', 'crews', 'harsh', 'slightly', 'per', '7', 'wanting'], ['planting', 'plant', 'common', 'tree', 'planter', 'restoration', 'style', 'practiced', '1990s', 'organizations', 'desired', 'trees', 'bag', 'machine', 'hand', 'taylor'], ['planting', 'succession', 'apply', 'crop'], ['planting', 'plantings', 'evaluating', 'elevation', 'management', 'quality', 'concluded', 'outplanted', 'definition', 'determination', 'use', 'foresters'], ['planting', 'planted', 'tree', 'volunteers', '2017', 'approximately', '’'], ['planting', 'gliricidia', '–', 'kanuga', 'plant', 'plants', 'peltophorum', 'arjuna', 'departments', 'mandal', 'crs', 'proposed'], ['planting', 'companion', 'mechanisms', 'rice', 'mesoamerica', 'herbs', 'large', 'assist', 'maximizing', 'operate', 'use', 'polyculture', 'many', 'least', 'reasons', 'productivity']]

Processing features:  39%|███▉      | 38/98 [18:13<28:06, 28.10s/it]

getting sample prompt forgetting sample prompt for 23857
 23856
getting sample prompt for 23858
getting sample prompt for 23859
getting sample prompt for 23860
getting sample prompt for 23861
getting sample prompt for 23862
getting sample prompt for 23863
getting sample prompt for 23864
getting sample prompt for 23865
getting sample prompt for 23866
getting sample prompt for 23867
TOP TOKENS [['peel', 'complexion', 'peeler', 'peeling', 'store', 'noun', 'tania', 'peeled', 'potatoes', 'shows', 'cls'], ['peel', 'either', 'antics', '1', 'cat', '3', 'across', 'difference', 'apple', 'lawrence', 'noun', 'peels'], ['peel'], ['peel'], ['peels', 'nurse', 'peel', 'peeling'], ['peels', 'peel', 'peeling', 'solution'], ['peels', 'peel'], ['peel(n', 'peel(v', 'peel', 'orange', 'skin', 'readily', 'oar', 'peels'], ['peels', 'peel', 'chemical', 'uses', 'tca'], ['peels', 'peel', 'peeling', 'several', 'problems', 'stronger', 'depth', 'proprietary', 'skin', 'agent', 'agents'], ['peel', '–', 'dwayne', "charlotte's", 'peeling', 'fisherman'], ['arkansas', 'w', 'peel', '1915'], ['peel', 'orange-peel', 'effect', 'zest', 'projection'], ['states', 'hill', 'peel'], ['links', 'external', 'significance', '–', 'peel'], ['part', 'brunswick', 'families', 'peel'], ['peel', 'surface', 'character', "peel's", 'long-lost', 'sam', 'roy', 'ja', 'munter', 'good-hearted'], ['links', 'site', 'external', 'peel', 'official', 'bandcamp'], ['peel'], ['peel', '1982', '1954', 'children', 'madoff', 'life', 'two', '2005', '2021', '2004', 'outstanding']]
TOP TOKENS [['tell', 'see', 'likes', 'decides', 'notices', 'illustrated', 'dislikes', 'yummies', 'reorganizing', 'head', 'bringing', 'get', 'newspaper'], ['old', 'one', 'see', 'cherished', 'antecedent', 'cricket'], ['sensed', 'allow', 'consists'], ['showing', 'leadership', 'jr', 'family', 'gives'], ['board—reasonable', 'represented', 'winter’s'], ['earth', 'due', 'frame'], ['accompanied'], ['squaring', 'see'], ['adapt', 'enrich', 'part', 'receive', 'solution', 'group', 'assessment', 'however', 'scheme', 'example', 'service', 'referral', 'advice'], ['find', 'provided', 'also', 'see', 'mentioned', 'suffices', 'appraisal', '‘', 'reflected'], ['member', 'belgium', 'one', 'netherlands', 'unbuilt', 'part'], ['specialize'], ['eu4', 'adapted', "thatcham's", '2', 'listed', 'activates'], ['adapter'], ['creator', '1914–1972', '1926–2009', 'sidekick', 'comical'], ['city'], ['compared'], ['pilot', 'early', 'adopter', 'part', 'pioneering', 'p', 'indicated', 'based', 'also'], ['disambiguation', 'album', 'see', 'play', 'film', 'come'], ['15', 'one', 'agricultural', 'per', 'public', 'uses', 'shown', '8', 'dozen']]
TOP TOKENS [['scottsdale', 'north', 'close'], ['scottsdale', 'north', 'close'], ['scottsdale', '’', '101', 'clinical', '“', '–'], ['scottsdale', 'valley', 'many'], ['scottsdale', '’', 'basis', '52', 'borders'], ['scottsdale', '’', 'basis', '52', 'borders'], ['scottsdale', "scottsdale's", '14', 'south', '21', '839', 'boundary'], ['scottsdale', 'near', 'center', 'others', 'swilling', 'ones', 'distance', 'much', 'day', 'year', "today's"], ['scottsdale', "scottsdale's", 'stores', 'mortuary', 'sweeney'], ['scottsdale', 'new', 'scottdale’s', 'aligns', 'said', 'led', '2010-2040', 'helps', 'high', 'provisions', '–', 'solar-ready', 'estimated', 'mitigate'], ['trim'], ['scottsdale', 'runs'], ['scottsdale', 'today', 'states', 'vasoni', 'utley', 'u', '3', '5', 'southern'], ['scottsdale', 'west', 'scott', 'boundary', 'system', '7400', 'surrey–delta', 'shuttles', 'on-site', 'serve', 'also', 'outside'], ['scottsdale', '668', 'ortega', 'flights', 'including'], ['scottsdale', 'south-east', 'road', 'runs'], ['scottsdale'], ["scottsdale's", 'scottsdale', 'evening', 'events', 'plethora', '100', 'galleries', 'segmented', 'district'], ['scottsdale', '2009', 'links', 'since'], ['scottsdale', 'company', 'scottdale', '1880', 'c']]
TOP TOKENS [['naming', 'convention', 'languages', 'names', 'conventions'], ['naming', 'nomenclature', 'name', 'word'], ['naming', 'name', 'names', 'conventions'], ['naming', 'convention', 'conventions', 'names', 'languages'], ['naming', 'syntax', 'convention', 'conventions'], ['naming', 'convention', 'named', 'please', 'call'], ['nomenclature', 'name', 'naming', 'write', 'writing'], ['name', 'naming', 'names', 'conventions', 'convention', 'style'], ['named', 'name', 'naming', 'names', 'syntactic', 'cls', 'conventions'], ['naming', 'name', 'something', 'names', 'things'], [], ['named', 'nomenclature', 'using', 'naming', 'uses', 'names', 'name'], ['nomenclature', 'cytogenomic'], ['naming', 'nomenclature', 'name', 'classify', 'language', 'languages', 'names', 'word', 'disciplines'], ['nomenclature', 'name', 'names', 'naming', 'referring', 'molecular', 'code', 'systematic'], ['naming', 'nomenclature', 'programming', 'identifier', 'terminology', 'convention', 'name', 'conventions', 'computer', 'program', 'product', 'grandfather', 'offspring', 'called', 'things'], ['nomenclature', 'naming', 'numbering', 'name', 'indicate', 'iubmb', 'names', 'identifier', 'written', 'identify', 'symbols', 'numbers', "iupac's", 'nomenclatures'], ['named', 'nomenclature', 'name', 'using', 'naming', 'conventions', 'names', 'terminology', 'based', 'recommendations', 'prefix'], ['naming', 'name', 'conventions', 'named', 'refer', 'convention', '1.0'], ['nomenclature', 'naming', 'name', 'gene', 'names']]
TOP TOKENS [['спасибо', 'огромное', 'доступно'], ['днеи', 'саите', 'что', 'согласны', 'не', 'напишите'], ['фантастическую', 'образом', 'уважаемым', 'световых', 'удалившись'], ['почитаю', 'что', 'более', 'толкина'], ['что', 'саите', 'не', 'согласны', 'если', 'днеи'], ['такои', 'укажите'], ['согласны', 'что', 'саите', 'не', 'его', 'надлежат'], ['лингвистике', 'задать', 'индиискои', 'для', 'санскрите', 'электронная', 'напишите', 'дополнительнои', 'получения'], ['вдалеке', 'прямо', 'метрах', 'фоне'], ['возвращаются', 'уникальности', 'даннои'], ['сделать', 'того', 'чтобы', 'пришлось', 'мне', 'работа', 'требовалось', 'переоркестровать', 'более', 'фильма', 'для', 'затем', 'эизенштеина', 'построить', 'первоначальном', 'симфонически', 'развить', 'идущии', 'прежде'], ['королеве', 'хосе', 'книга', 'малые', 'перевод', 'парламент', 'птичии', 'джон', 'касаль', 'избранные', 'дель', 'поэмы', 'средь', 'сонеты', 'триумфы', 'звезды', 'англииского', 'вишня', 'витковскии', 'водолеи', 'стихотворения', 'джеффри'], ['идеальнои', 'которои', 'стороны', 'запасом', 'впоследствии', 'которую', 'взяты', 'фразы', 'тои', 'пользовался', 'думе', 'например', 'недоставало', 'сером', 'контрапункта', 'идеальному', 'идеального', 'таланта', 'часть', 'заготовлен', 'гармонии', 'евреиских', 'смерть'], ['трополе', 'любовное', 'настро', 'гусарская', 'канада', 'карусель', 'настроение', 'никитин', 'карета', 'диска', 'номера', 'пропадаю', 'лучшие', 'года', 'девочка', 'лети', 'кабриолет', 'коллекция', 'любимыи'], ['достались', 'полет', 'тенеи', 'бытовые', 'мысль', 'мусоргскии', 'предоставлена', 'была', 'что', 'первая', 'явление', 'вновь', 'взял', 'довольно', 'некоторое', 'некоторые', 'чернобога', 'половина', 'деиствия', 'написал', 'мне', 'которую'], ['кровь', 'тюристы', 'роза', 'дуэлянты', 'ямато', 'небесныи', 'счастливыи', 'изумрудное', 'капитан', 'демон', 'страны', 'афродиты', 'фамильныи', 'дары', 'дракулы', 'лето', 'король', 'версаля', 'судьбы', 'монсегюра', 'сион', 'доспехи', 'могущества', 'капитана', 'ковчег', 'австразии', 'нибелунги', 'мародеров'], ['платоновои', 'музыке', 'текста', 'входить', 'сюжет', 'близок', 'знаменитому', 'этого', 'театральнои', 'последние', 'воспроизведения', 'гедеонове', 'сверх', 'бытовыми', 'пользовались', 'благодарным', 'композитор', 'фантастическими', 'являлся', 'этои', 'танцы', 'не', 'его', 'императорских', 'чисто', 'того', 'симпатиеи'], ['риала', 'вскоре', 'некоторое', 'вновь', 'мусоргскии', 'программои', 'было', 'затее', 'написал', 'что', 'почти', 'трио', 'суждено', 'же', 'покинул', 'еще', 'переделал', 'сочинив', 'впоследствии', 'изданныи', 'самои', 'отдельно', 'он'], ['необходимые', 'пермь', 'сведения', 'дударь', 'среды', 'электронике', 'механику', 'тензорного', 'учебное', 'иную', 'соотношении', 'методическим', 'исчисления', 'кинематика', 'учебно', 'студентов', 'прикладная', 'сплошнои', 'рекомендованное', 'отделом', 'гос'], ['совершенству', 'пираньи', 'фантазмы', 'кто', 'ние', 'вторжение', 'зачем', 'древо', 'правила', 'черныи', 'черное', 'света', 'сторону', 'сердце', 'черная', 'человек', 'реальность', 'сила', 'мы', 'дьявола', 'чудес', 'бои', 'правил', 'приговоренные', 'реальностеи', 'вселеннои', 'опыт', 'трансперсонального', 'контакты', 'земля']]
TOP TOKENS [['ent', 'ents', 'music', 'jeopardized', 'life', 'lives', 'almost', 'throat', 'snore', '”', 'conditions', 'treat', 'everyone'], ['ent', 'visit'], ['ent', 'otolaryngology', 'doctor'], ['ent', 'ents', 'head', 'cls', 'one', 'breathing'], ['ent', 'otolaryngology', 'surgery'], ['ent', 'sep', 'area', 'attitudes'], ['ent', 'degree', 'study', 'certified', 'advance', 'school', 'medical', 'objective', 'suitable', 'get', 'oral'], ['ent', 'ents', 'degree', 'otolaryngologist', 'otolaryngologists', 'tumors', 'specialist'], ['ents', 'ent', 'surgeries', 'annually', 'university', 'hospital', 'otolaryngologists'], ['ent', 'ents', 'treat', 'degree', 'otolaryngology'], ['ent', 'currently'], ['novels', 'ent', 'ents', 'marshall', 'also', 'refer', 'science'], ['ent', 'ent•uk', 'ent-uk', '2008', 'otorhinolaryngology', 'boars'], ['ent', "ent's", 'known', 'members', 'membership'], ['ent', 'prior', 'dieter', 'browser', 'history', 'phalese', 'edge', 'automatically', 'features', '1650', 'five', 'theuns'], ['ent', 'november', 'fleet', 'hughes', "harry's", "brook's", 'fiction', 'october', 'similar', 'early', 'ahead', 'launches', "children's", 'money', 'itv', '1963', 'star', 'shop', '17', '1987', '–', 'evening', "bleasdale's", '1982', 'blockbuster', 'written'], ['ent', 'r'], ['ent', 'republic', '2007', 'leaving', 'track', 'saw', 'vocalist', 'releases', 'time', '1999', 'getting', 'osmose', 'catchpole', 'richardson', 'candlelight'], ['ent'], ['ent', "ent's", 'ii', '1944', 'lightning', 'biography', 'fire', '1942']]
TOP TOKENS [['biosensor', 'biosensors'], ['biosensors', 'biosensor', 'ultrasensitive'], ['biosensors', 'biosensor'], ['biosensor', 'biosensors', 'sensor'], ['biosensors', 'biosensor'], ['biosensor', 'biosensors', 'sensor', 'sensing'], ['biosensors', 'biosensor'], ['biosensor'], ['biosensor', 'biosensors', 'nano-biosensors'], ['biosensor', 'microsensors', 'biosensors', 'sensing', 'sensors'], ['biosensor', 'biosensors', 'piezoelectric', 'cls'], ['biosensors', 'biosensor', 'sensors'], ['biosensors', 'biosensor', 'ultrasensitivity'], ['biosensors', 'biosensor'], ['biosensors', 'biosensor', 'detection', 'monitoring'], ['biosensors', 'biosensing', 'ultrasensitivity', 'biosensor', 'sensing', 'based'], ['biosensor', 'biosensors', 'nanobiosensors', 'sensors', 'detect', 'sensitive'], ['biosensors', 'requirements', 'cls'], ['biosensors', 'biosensor', 'sensor', 'sensitivity', 'sensitive'], ['biosensors', 'sensors']]
TOP TOKENS [['copyleft'], ['copyleft', 'license'], ['copyleft', 'license'], ['copyleft', 'restrictive', 'copylefted', 'redistribute', 'license', 'proprietary'], ['copyleft', 'license'], ['copyleft', 'licenses', 'license'], ['copyleft', 'licences', 'license', 'also', 'words'], ['copyleft', 'licences', 'license', 'also', 'words'], ['licenses', 'copyleft', 'proprietary'], ['copyleft', 'licenses', 'license', 'redistributor'], ['copyleft', 'licenses'], ['copyleft', 'licenses', 'freedoms'], ['copyleft', 'case', 'license'], ['copyleft', 'licenses'], ['copyleft', 'license', 'licenses', 'copylefted', 'copylefting', 'free', 'redistribute', 'proprietary'], ['copyleft', 'licenses', 'see', 'proprietary', 'released', 'redistributed'], ['copyleft', 'licenses', 'copylefted', 'license', 'licensed', 'cover'], ['copyleft', 'licenses', 'redistribute'], ['copyleft', 'licenses', 'license', 'software', 'licensing'], ['copyleft', 'license', 'licenses', "copyleft'd"]]
TOP TOKENS [['subjunctive(redirected', 'subjunctives', 'subjunctive'], ['subjunctives', 'subjunctive', 'treowwyrhta'], ['subjunctive', 'disjunctive', 'disjunction'], ['subjunctive'], ['subjunctive', 'tenses'], ['subjunctive'], ['subjunctive', 'subjuntivo', '“', '–'], ['subjunctive'], ['subjunctive'], ['subjunctive'], ['disjunctive', 'disjunct', 'disjunction'], ['subjunctive', 'subjunctives', 'conjunctive', 'indicative'], ['subjunctive', 'english'], ['subjunctive', 'subjunctivus', 'hypotaktike', 'word'], ['subjunctive'], ['injunctive'], ['subjunctive', 'subjunctives', 'virginia'], ['subjunctive', 'latin'], ['subjunctive'], ['subjunctive']]
TOP TOKENS [['dungeons', 'playing', 'dragons', 'dungeon', 'edition', 'roleplaying', 'game'], ['dungeon', 'dungeons', 'd&d', "d&d's", 'dragons', 'role-playing'], ['dm', 'dungeon', 'dungeons', 'dragons', 'rpg', 'd20', '5e'], ['dungeons', 'dungeon', 'dm', 'dragons', 'playing', 'role', 'dragonsyour'], ['dungeons', 'dungeon', "dm's", 'dm', 'dragons', 'rpg', 'playing'], ['dungeons', 'dungeon', "dm's", 'dm', 'dragons', 'rpg', 'playing'], ['dm', 'dungeons', 'dm-controlled', 'dragons', 'd&d', 'rpg', 'role-playing'], ['dm', 'dungeons', 'dm-controlled', 'dragons', 'd&d', 'rpg', 'role-playing'], ['dungeons', 'dungeon', 'playing', 'dragons', 'role'], ['dungeon', 'dm', 'dungeons', 'dragons', 'dnd', 'rpg', 'roleplaying'], ['dungeons', 'role-playing'], ['dungeons', 'role-playing', 'dragons'], ['dungeons', 'dungeon', 'dm', 'dragons', 'rpg', 'playing', 'role'], ['dungeons', 'dragons', 'playing', 'role'], ['dungeons', 'dragons', 'dm', 'dungeon', 'playing', 'rpg', 'game'], ['dungeons', 'role-playing', 'dragons'], ['dungeon', 'dungeons', 'dragons'], ['dungeons', 'dm', 'dragons', 'dungeon', 'dms', 'roleplaying', "dungeon's", 'dungeoncraft', 'players'], ['dungeons', 'dungeon', 'dragons', 'd20', 'roleplaying', 'rpg', 'gm', 'crusades', 'pathfinder'], ['dungeons', 'dungeon', 'dragons', 'playing', 'd20', 'role', 'opportunity', 'tabletop', 'games']]
TOP TOKENS [['get', 'age', 'older', 'years', '40s', 'ages', 'aging', 'gradually', 'slows', 'later', 'regular'], ['get', 'ages', 'age', 'years', 'older', 'aging', 'later', '40s', 'become', 'less', 'becomes'], ['decade', 'age', '70s', 'every', '60s', 'aging'], ['age', 'get', 'older', 'grow', 'slows', 'weaker'], ['age', 'get', 'years', 'become', 'older', 'aging', 'piling', 'start'], ['get', 'age', 'older', 'years', 'ages', '40s', 'aging', 'regular', 'later', 'gradually', 'slows', 'becomes'], ['become', 'age', 'aging', 'getting', '40s', '30s', 'older', 'less', '40', 'thins', 'decade'], ['thirties', 'age', 'fifties', 'successive', 'twenties', 'forties', 'declines', 'eighties'], ['age', '50s', 'becomes', 'thins', 'aging', 'slows', 'every', 'declines'], ['get', 'age', 'getting', 'older', 'begins', 'begin', 'years', 'old', 'aging', 'go', 'continue', 'lose'], ['age', 'geriatric', 'related', 'older', 'decline', '65', 'unintentional', 'increased', 'stressors', 'malnutrition', 'ambulating', 'loss', 'patients', 'toileting', 'fatigue', "person's", 'hygiene', 'may'], ['aging', 'yet', 'results', 'decreases', 'longer', 'shorter', 'response', 'old', 'greater', 'fibers', 'responses', 'demyelination', 'walking', 'adults', 'hand', 'perturbation'], ['age', 'become', 'years', 'lessening', 'old', '50', 'expand', '74', 'constrict', 'turns', 'lighting', 'time', 'may', 'older', 'less', 'efficiently', 'providing'], ['age', 'years', 'aging', 'life', 'year', 'late', 'lifespan', 'decline', '25', 'tremendously', 'decreases', 'throughout', 'impairments', 'develop', 'decrease', '43', 'proceeds', 'developing', 'older'], ['grow', 'age', "individuals'age", 'older', 'growing', 'time', 'increase', 'decline', 'life', "one's", 'losses', 'lifespan', 'gains', 'tend', 'cognitive'], ['age', 'ageing', 'years', 'lifespan', 'remodeling', 'many', 'old', 'adulthood', 'furthermore', 'older', 'loss', 'example', 'stiffness', '1997', 'definitions', '25', '80'], ['ageing', 'declining', 'capacities', 'functions', 'diminished', 'internal', 'degenerative', 'physiologic', 'alone'], ['gradually', 'age', 'aging', 'declines', 'early', 'years', '40', 'become', 'old', 'pathophysiology', 'decrease', 'include', 'way', 'decreased', 'decline', 'older', 'changes', 'thereafter', 'disorder', 'also', 'starts', 'atrophy'], ['get', "age's", 'age', 'older', 'aging', 'aged', 'problems', 'less', 'become', 'fret', 'old', 'takes', 'wandering', 'slowly', "alzheimer's", 'include'], ['ages', 'aging', 'age', 'decline', 'harder', 'older', 'waning', 'problems', 'loss', 'thickening', 'whitening', 'trimming', 'tend', 'mammary', 'incontinence', 'urinary', 'certain', 'change', 'changes', 'activity', 'reduced', 'elasticity', 'gastrointestinal', 'lining', 'pancreas']]
TOP TOKENS [['start', 'push', 'propellers', '1908', 'bags', 'statue', 'street'], ['out.println("日本', '8c', 'ef', 'e8', 'fileoutputstream(file', 'utf-8', 'こんにち', 'utf8', 'properly'], ['leaf', 'vellum', 'figures', 'collection', 'leaves', 'ink', 'ruskin', 'heaven', '1819–1900', 'object', 'tradition', 'firstname.lastname@example.org', 'email@example.com'], ['c', 'ive', '360/4'], ['civilizations', 'countries', 'president', 'wars', 'country', 'citizens', 'war', 'minister', 'india', 'neighbors', 'world', 'push', 'prime', 'clash', 'egyptian', 'nationalist', 'people', 'genocide', 'teachers', 'enemies', 'time'], ['g', 'e', 'dollar'], ['streets', 'cities', 'papers', 'someone', 'countries', 'wagon', 'planes', 'hands', 'fly', 'window', 'france', 'scatter', 'fire', 'people', 'fear', 'flag', 'shown'], ['c', 'limbs', 'conquering', 'astride', 'alters', 'glows', "love's"], ['chronique', 'historical', 'chronography', 'chronographies', 'materials', 'manuscript', 'chronik', 'latin', 'helm', 'canones', 'chroniques', 'lancon', 'stuttgart', 'band', 'milford', 'chronicon', 'photocopy', 'photocopied', 'roman', 'werke', 'chronici', 'press', 'text', "the'lemmas'of", 'octobre', 'ubersetzt', 'numbers', 'whatever', 'annees'], ['chronique', 'historical', 'chronography', 'chronographies', 'materials', 'manuscript', 'chronik', 'latin', 'helm', 'canones', 'chroniques', 'lancon', 'stuttgart', 'band', 'milford', 'chronicon', 'photocopy', 'photocopied', 'roman', 'werke', 'chronici', 'press', 'text', "the'lemmas'of", 'octobre', 'ubersetzt', 'numbers', 'whatever', 'annees'], ['chronologies'], ['albums', 'records'], ['editing', 'engineer', 'live', '–'], ['hunan', 'television', 'production', 'series'], ['auguste', "lagrone's", 'close', 'efforts', "video's", 'campus', 'sculpt'], ['births', 'april', 'deaths', 'musicians', 'philip', 'references', 'airplane', 'rivieras', '9', 'love', '1916', '–', 'one', 'benefit', '20th-century', '1997', 'co-wrote', 'co-writer', 'chart', 'kingsmen'], ['people', 'births', 'discographies', 'albums', 'medley', 'pop', 'living', 'singers', 'baritones', 'bio'], ['kingdoms', 'plays', 'papers', 'deaths'], ['albums', 'vinyl', 'produced', 'records', 'studio', 'record', 'charts', 'drums'], ['drama', 'serial', 'triller', 'television', 'series']]

Processing features:  40%|███▉      | 39/98 [18:42<27:58, 28.44s/it]

getting sample prompt forgetting sample prompt for 23869
 23868
getting sample prompt for 23870
getting sample prompt for 23871
getting sample prompt for 23872
getting sample prompt for 23873
getting sample prompt for 23874
getting sample prompt for 23875
getting sample prompt for 23876
getting sample prompt for 23877
getting sample prompt for 23878
getting sample prompt for 23879
TOP TOKENS [['underdog', 'undershirt', 'live', 'making', 'protected', 'word'], ['underpaid', 'position', 'beneath', 'word'], ['“under”', 'use', 'word'], ['illustrations', 'word'], ['underline', 'underlining', 'underlined', 'underlines', 'apply', 'text', 'give', 'encounter', 'common', 'effectively', 'enhance', 'make', 'visually', 'may'], ['particular', 'undername', 'applied', 'bringing', 'thing', 'oneself', 'business', 'property', 'descriptively'], ['undervolting', 'undervolt', 'undervolted', 'put', 'talking', 'process', 'overboard', 'little', 'hinder'], ['underscores', 'underscore', 'underneath', 'underlined', 'underline', 'beneath', 'use', 'line', 'underscoreˈʌn'], ['underun', 'beneath', 'go', 'going', 'watched', 'rule', 'warranted', 'went', 'indicated', 'wraps'], ['underun', 'beneath', 'go', 'going', 'watched', 'rule', 'warranted', 'went', 'indicated', 'wraps'], ['undercut', 'indivisible', 'work'], ['underberg'], ['underdog', 'underdogs', 'exilia', 'reality', 'underdogz', 'south', 'wee'], ['underlay', 'underlayment', 'beneath'], ['underprinting', 'underprinted', 'underneath', 'underprint'], ['undercuts', 'undercut', 'may', 'generally', 'molding', 'using', 'diameter', 'spindle'], ['underlining', 'underscored', 'underscores', 'underline', 'forms', 'underscore', 'underscoring', 'unbroken', 'back', 'typewriter', 'moved'], ['underhill', 'estate', 'vinge', 'u.s', 'j.r.r', 'dorset', 'named'], ['underbody', 'underseal', 'underfur', 'undercoat'], ['gun', '2007', '1984', 'perfect', 'animalize', 'nova']]
TOP TOKENS [['kotlin', 'currently'], ['kotlin', 'day', 'announced', 'concise', 'first'], ['kotlin', '1.7'], ['kotlin', '1.7'], ['kotlin'], ['kotlin', 'unk', 'java'], ['kotlin', '‘kotlin’', 'slate', 'google'], ['kotlin'], ['kotlin'], ['kotlin', 'go', 'pinterest'], ['kotlin', 'kotlin-class'], ['gatlin', '1809–1896'], ['kotlas', 'kotla', 'kotlassky'], ['kotlin', 'used', 'using', '2018', 'added'], ['kotlin', "kotlin's", '1', 'jemerov', 'e', '5'], ['gitlin'], ['kotli'], ['kotlin'], ['kotlin', 'programming', 'deduce', 'interoperable', 'pascal', 'ended', 'said', 'one'], ['kotlin', 'c', 'hello', 'java', 'p1', 'since', '1', 'mystringextensions']]
TOP TOKENS [['location', 'choose'], ['location', 'country', 'based', 'visits'], ['location', 'country', 'office'], ['country', 'location'], ['location', 'country', 'sites', 'note', 'visits', 'english', 'based', 'site'], ['location', 'country', 'select', 'based', 'visits', 'english', 'chinese', 'delimiters', 'different', 'site', 'list', 'optimized', 'sites'], ['location', 'country'], ['location', 'country', 'office'], ['location', 'country', 'select'], ['location', 'country'], ['constituencies', 'member', 'constituency', 'order', 'least'], ['diacritics', 'g'], ['depends'], ['syntax', 'singular', 'alphabetical'], ['5digit', '1'], [], [], ['venezuela'], ['blurry', 'however', 'abound', 'unk', 'would', 'often', 'example', 'still', 'also', 'used', 'etc'], []]
TOP TOKENS [['cat', 'consistency'], ['cat', 'cat-ing', 'contents', 'file', 'default', 'choice', 'home/john/myfile.txt'], ['cat', 'cats', 'translated', 'texts', 'working', 'memory', 'simplifying'], ['cat', 'early', 'catking', "let's"], ['cat', 'translations', 'variations'], ['cat', 'academic', 'b', 'paves', 'indian', 'business'], ['cat', 'etc', 'adobe', 'case', 'computer', 'able', 'indeed', 'grammar'], ['cat', 'causes', 'bottle', 'younger', 'back', '’'], ['cat', 'india', "the'alien'factor", 'sources'], ['cat', '8', '1/2'], ['cat', 'catenate', 'cls', 'history', 'time', 'bat', 'screen', 'systems', 'teletype', 'byte', 'features', 'ritchie'], ['cat', 'tribunal', 'species', 'telecom'], ['cat', "cat's", 'british', 'technician'], ['cat', '2020', '13'], ['çat', '2022', 'turkey'], ['cat', 'two', 'links'], ['çat', '2,031', 'turkey', 'belde', '2022', 'places'], ['cat'], ['cat', 'specified', 'byte', 'cases', 'stream', 'tabs', 'ascii'], ['cat', 'zcat', 'instead', 'one', 'case']]
TOP TOKENS [['celsius', 'fahrenheit'], ['celsius', 'fahrenheit'], ['celsius', 'fahrenheit'], ['celsius', 'celcius', 'fahrenheit'], ['celsius', 'fahrenheit'], ['celsius', '4°c', '9⁄5°c'], ['celsius', '4°c', '9⁄5°c'], ['celsius', 'fahrenheit', '20°c', '38°c'], ['celsius', 'fahrenheit'], ['celsius', 'fahrenheit', '32°f', '20°c', 'fahrenheits', '0°c'], ['celsius', 'temperature', 'celcius'], ['celsius', 'fahrenheit', 'temperature'], ['celsius'], ['celsius', 'fahrenheit', 'degrees', '°f', '°c', 'f', 'e'], ['fahrenheit', 'celsius', '°c', 'degrees', 'temperature', '−273'], ['celsius', "celsius'°c'with", '°c', 'e', 'degrees'], ['celsius', 'temperature', 'centigrade', 'auroral', '1732'], ['fahrenheit', 'celsius', "celsius's", 'temperature', 'thermometer', 'calibrated', 'generating', 'cels'], ['celsius', 'temperature', "celsius's"], ['celsius', '°c', 'degrees']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['definitive'], [], [], []]
TOP TOKENS [['clean', 'energy', 'plants', 'fuels', 'annually'], ['clean', 'energy', 'plants', 'fuels', 'annually'], ['cleantech', 'clean', 'little', 'started', '40', 'hamilton'], ['clean', 'key', 'energy', 'electricity'], ['clean', 'key', 'energy', 'electricity'], ['clean', 'install', 'installs', 'practice'], ['clean', "is'clean'is", 'efficiently', 'foods', 'mean', 'eating', 'diet', 'pizza', 'thrown', 'tend'], ['clean', 'energy', 'efficiency'], ['clean', 'cleantech', '“cleantech”', 'evaluated'], ['clean', 'cleanest', 'eating', 'part', 'though', '…', 'dirty', 'term', 'couple'], ['clean', 'vocals', 'deitiphobia'], ['cleantech', 'clean', 'cleantechlaw.org', 'tech', 'materials', 'field', 'technology'], ['cleanfilm', 'clean', 'links', 'external', 'dj', '2017', 'producer', 'bandit', 'june', 'references', 'co', 'plan', '–', 'braimah', "corbyn's", '2022', 'hizon', 'released', 'figures', 'endorsed', 'percussion', 'duhe', 'private'], ['clean', 'ncic', 'algorithm'], ['cleanhead'], ['clean', 'cleanfeed'], ['cleantechnica', 'clean', 'quarterly', 'tesla'], ['cleanfilms', 'cleanflicks', 'clean', 'cleanfilms.com', 'along', 'controversial', 'films', 'two'], ['clean', 'others', '2020', 'clean-energy', 'currently', 'oregon', 'engaged', 'custom', 'edge', 'nasdaq', 'also', 'clean-tech', 'cels', "edge's", 'launched', 'nation'], ['clean', "cleantech's", 'cleantech', 'project', 'edge', 'using', 'technology', 'flop', 'forecasted', 'activities', 'cited', '2009']]
TOP TOKENS [['relaxing', 'beautiful', 'favourite', 'calming', 'enjoyed', 'stroll', 'around', 'middle', '9', 'spend', '’', 'vibes', 'background', 'stone', 'one', 'rocks', 'really', 'two', 'good'], ['relaxing', 'beautiful', 'favourite', 'calming', 'enjoyed', 'stroll', 'around', 'middle', '9', 'spend', '’', 'vibes', 'background', 'stone', 'one', 'rocks', 'really', 'two', 'good'], ['user', 'single', 'satisfaction', 'make', 'cover', 'disturbed', 'long', 'get', 'regularly', '’', 'interface', 'done'], ['groceries', 'nearest', 'sundry', 'imported', 'dotting', 'sacred', 'entertainment', '”', '—', 'ecological', 'holy', "that's", 'get', 'secular', 'says', 'coastline'], ['one', 'treat', 'milkshake', 'special', 'ingredients', 'following'], ['edululu.org', 'featuring', 'mammoth', 'main', 'new', 'rating', 'common', 'édululu', 'character', 'appealing'], ['one', 'delight'], ['chilblains', 'chilblain', 'uncomfortable', 'creams', 'scarf', 'problem', 'prevent', 'using', 'cause'], ['boxed', 'equal', 'traditional', 'desktop', 'innovate', 'business', 'time', "suse's", 'inc', 'first', 'license'], ['experiences', 'one', 'enjoyable', 'children', 'use', 'offers', 'colors', 'provide', 'appropriate'], ['developer', 'developed', '3', 'different', 'mystery', '2008', '’', 'review', 'games', 'stars', 'gamers', '5', 'a−'], ['players', 'developer', "player's", 'player', 'permanently', "let's", 'ability', 'plays', 'well', 'time', 'period', 'long', 'game', "character's", 'thicker', 'extended', 'simple', 'impairs', 'throughout'], ['confection', 'playing', 'charming', 'game', 'like', 'play', 'gameplay', 'undulating', 'time', 'addictive', "that's", 'games'], [], ['addictiveness', 'viewpoint', 'limitation', 'introducing'], ['change', 'containing', 'playing', 'game', 'players'], ['new', 'fleecy', 'blocky', 'daffy', "award's", 'nightcap', 'matchstick'], ['played', 'features', 'items', '5'], ['game', 'lit', 'natural'], ['kyffhauser', 'visiting', 'primary', "shade's"]]
TOP TOKENS [['collagen‼️i', 'collagen', 'collagen-rich', 'unhealthy', 'piece'], ['collagen', 'role'], ['collagen', 'body', 'bonds'], ['collagen'], ['collagen', 'put', '“'], ['collagen', 'period', 'aging', 'signs'], ['collagen'], ['collagen', 'naturally'], ['collagen', 'injections', 'injecting'], ['collagen'], ['collagens', 'collagen', 'oxidative', 'subjected'], ['collagen', 'collagenases', 'collagens'], ['collagens', 'collagen', 'pro-collagen', 'links'], ['collagen', 'collagens', 'also', 'links', 'external', 'see', 'molecules', 'procollagen', 'genotypically'], ['collagen', 'collagens', 'links'], ['collagen', 'collagens', 'cells', '3', 'fibrils'], ['collagen', 'span', 'chains'], ['collagens', 'collagen', 'reading'], ['collagen', 'collagens', 'links'], ['collagen', 'ropelike', 'procollagen', 'fibrils', 'cls']]
TOP TOKENS [['comintern', 'party'], ['secretary', 'politburo', 'cpsu', 'committee', 'party'], ['committee', 'party', 'politburo', 'orgburo', 'congress', "orgburo's", 'committees', "party's"], ['cpc', 'party'], ['cpc', "cpc's", 'organizations', 'secretary', 'party', 'committee', 'office', 'central'], ['committee', 'party', "party's", 'congress', 'politburo', 'orgburo', 'central', 'secretary', 'communist'], ['committee', 'party', "party's", 'congress', 'politburo', 'orgburo', 'central', 'secretary', 'communist'], ['cpc', 'secretary', 'party', "cpc's", 'organizations'], ['committee', 'cpc', 'committees', 'central', 'within', 'organizations'], ['comintern', 'party', 'committee', 'held', 'communist', 'concerning', 'committees', 'c', 'international'], ['committee', 'congress', 'party', 'comintern', "party's", 'committees', 'central'], ['party', 'conference', 'secretary', 'committee', 'congress', 'within', 'orgburo', 'politburo', 'congresses'], ['party', 'committee', 'secretary'], ['comintern'], ['comintern', 'parties', 'events', 'international', 'стенографическии', 'politburo', 'party'], ['party'], ['secretary', 'committee'], ['party'], ['secretary', 'party', 'secretaries', 'politburo', 'committee'], ['party', 'politburo', 'secretary', 'committee', 'congress', 'officials', 'central']]
TOP TOKENS [[], ['possible', "crossfit's", 'crossfit', 'intensity', '24/20', 'fitness', '6-5-4-3-2', 'health', 'physical', '20/14'], ['crossfit', 'trainer', 'therefore', 'addition', 'dumbbells', 'general', 'physical'], ['crossfit', 'workout'], ['crossfit', '“crossfit', 'course', 'unit', 'movements', 'donʼt', 'may'], ['crossfit', 'camaraderie', 'life', 'workouts', 'stimulus', 'next', 'gets', 'workout', 'going'], ['crossfit', 'crossfit?”', 'possible'], ['crossfit', 'fitter', 'line', 'cute', 'visit', 'member', 'training', 'might', 'morning', 'surely'], ['crossfit', 'crossfitting', 'rowing', 'exercise', 'easy', 'power', 'among', '346', 'wanted'], ['crossfit', 'something', 'learn', 'workouts', 'treating'], ['crossfit', 'games', 'nine', 'vigneault', 'growth', 'two', '415', 'eight', '2018', '2a', 'completed', "open's", "women's", 'divisions'], ['crossfit', 'participants', 'located', 'states', 'unknowable', 'although', 'forms', 'may', '2000', 'training', 'body', 'exercises', 'trademark'], ['views', 'help', 'may', '“legends”', '2018', 'times', 'uk', 'appearing', '2008', 'nhs', 'six', 'channel', 'regarded', 'appeared', 'special', 'reality', 'mixed', 'released', 'final', 'pledged', 'often', 'works', 'persona'], ['crossfit', 'hold', 'regions', 'parts', 'affiliates', 'gender', 'accordingly', 'perform', 'open', 'winning', 'games'], ['crossfit', 'gym', 'online', 'compeitin', 'games', 'also', 'sport', 'affiliation', 'win', '2008', 'many', 'sanctionals'], ['crossfit', "year's", '216', 'open', 'games', 'live', 'hour', 'first', 'closest', '310', 'show', 'convincingly', 'saturday', 'respective', 'week', 'four', 'workouts'], ['crossfit', "crossfit's", '2021', 'next', 'system', 'immediately', "people's", '2019', '2018', 'many', 'espn2'], ['crossfit', "crossfit's", 'rapidly', 'wins', 'llc', 'games', 'normally', 'six', 'using', 'five'], ['crossfit', "crossfit's", 'mats', 'swimming', 'wod', 'female', 'weightlifting', 'domains', 'physical', 'executed', 'strength', 'individual', 'usually', 'llc', 'sports'], ['qualified', 'f', 'c', 'played']]
TOP TOKENS [["kierkegaard's", 'kierkegaard'], ['kierkegaard', "kierkegaard's", 'walker', 'church', 'subjectivity', 'thinker'], ['kierkegaard', 'engagement', 'best', "kierkegaard's", 'christ', 'prefaces'], ['kierkegaard', "kierkegaard's", 'necessitating', 'schlegel', 'generally', "god's"], ['kierkegaard', 'freud', 'friend', 'persecution', 'result', '”'], ["kierkegaard's", 'kierkegaard', 'recognized', 'kierkegaardian', 'long', 'although', 'politics'], ['kierkegaard', 'cls'], ['kierkegaard', "kierkegaard's", 'introduction', 'played'], ['kierkegaard', 'anniversary', "kierkegaard's", '2008'], ['kierkegaard', 'kierkegaardian', "kierkegaard's", 'expression', 'never', 'called', 'perhaps', 'pseudonyms', 'see'], ['kierkegaard', 'christer', 'sylvia'], ["kierkegaard's", 'kierkegaard', 'kierkegaardian', 'regard', 'future'], ['kierkegaard', 'thing', 'preface', 'p', 'decision'], ["kierkegaard's", 'kierkegaard', 'malden', 'university', '–', 'princeton', '1957'], ['kierkegaard', "kierkegaard's", 'kierkegaardian', 'authority', 'søren', 'system'], ['kierkegaard', "kierkegaard's", 'whether', '’', 'part'], ['kierkegaard', "kierkegaard's"], ['kierkegaard', "kierkegaard's", 'skepticism', 'et', 'near', 'recently', 'english'], ["kierkegaard's", 'kierkegaard', 'person'], ['kierkegaard', 'church', 'spirit', 'every']]

Processing features:  41%|████      | 40/98 [19:11<27:36, 28.56s/it]

getting sample prompt forgetting sample prompt for 23881
 23880
getting sample prompt for 23882
getting sample prompt for 23883
getting sample prompt for 23884
getting sample prompt for 23885
getting sample prompt for 23886
getting sample prompt for 23887
getting sample prompt for 23888
getting sample prompt for 23889
getting sample prompt for 23890
getting sample prompt for 23891
TOP TOKENS [[], [], ['play'], ['makes'], [], [], [], [], [], [], ['breakups'], [], [], [], []]
TOP TOKENS [['monad', 'monads', 'outsiders', 'scary', 'would', 'fashion', 'certain', 'found', 'wait', 'need', 'snippet', 'modules'], ['monad', '13', 'object', 'straight'], ['monads', 'monad!”', 'understanding', 'monad'], ['monads', 'monad!”', 'understanding', 'monad'], ['monads', 'monad', 'monadic', 'hark', 'back', 'use', 'let'], ['monads', 'monad', 'monadic', '’', 'nothing', 'possibly', 'however', 'values'], ['monads', 'monad', 'uses', 'monadio', 'b', 'monadmaybe'], ['monads', 'monad', 'invented', 'perhaps', 'term'], ['monads', 'monad', 'invented', 'perhaps', 'term'], ['monad', 'monadic', '10', '8', 'monads', 'opaque', "there's", 'without', '20', '14'], ['陌南镇', 'monan'], ['monak'], ['monan'], ['mona', 'prior', 'monaville', 'seat', '1.61', 'central', 'region', '1918', 'formerly'], ['monad', '1971', 'hapur', 'monads', 'monad/monado', 'monadology', 'monas', 'historical', 'monadic', 'proxy', '1564', 'algebra'], ['monads', 'modules', 'monadically', 'monad', 'monadic', 'even', 'though', 'appropriate', 'still'], [], ['southern', '18a'], ['texas'], ['monakovo', 'streets', '1,098']]
TOP TOKENS [['dominion', 'dominions', 'dominionists', '“', 'dominionism', 'word', 'cls'], ['dominion', 'human', 'education', 'makes'], ['dominion', '3', 'meaning'], ['dominion', 'dominionese', "dominion's", 'cls', 'universe', 'quadrant', 'respectively'], ['dominion', '“', 'means', 'regain', 'earth', 'every'], ['dominion', 'ideas', 'control', 'god'], ['dominion', 'dominions', 'word', 'savages'], ['dominion', 'enriching', 'name'], ['dominion', 'dominionism', 'dominionists', 'dominionist', 'diminished', 'dying'], ['dominion', 'megawatts', 'production'], ['dominion'], ['dominion', 'dominions', 'dominionism'], ['dominion', 'dominiondms', '2021'], ['dominion', 'dominions', 'years', 'world'], ['dominion', "dominion's", '2017', 'cls'], ['dominion', 'links', 'external', 'references', '–'], ['dominion'], ['dominion', 'references'], ['dominion', 'albums', 'elisha', 'references', 'ages', 'armageddon', 'release'], ['dominion', 'references', 'external', 'links']]
TOP TOKENS [['garfield', "garfield's", 'insane', 'eighteen', 'cleveland', '1854', 'simultaneously', 'abram'], ['garfield', "garfield's", '1999', 'intact', 'encyclopedia'], ['garfield', "garfield's", 'garfields', 'james', 'hancock'], ['garfield', "garfield's", 'cls', 'rudolph', 'war'], ['garfield', "garfield's", 'cls', 'rudolph', 'war', 'hard'], ['garfield', 'children', '’', 'later'], ['garfield'], ["garfield's", 'garfield', 'south', 'james', 'g'], ['garfield', "garfield's", 'arthur', 'www', 'congress', 'james'], ['garfield', 'garfield||winfield', 'a.garfield'], ['garfield'], ['garfield'], ['garfield', 'links', 'area', 'external'], ['garfield', '2', 'people', '07', 'households', '51', 'alone', '9', 'james', 'present', '111'], ['garfield'], ['garfield'], ['garfield', 'newell'], ['garfield', 'hispanic', '2', '953', 'cls'], ['garfield'], ['garfield', 'brighton', '3–2']]
TOP TOKENS [['rad', '1.27||octants', 'converter', 'radians', 'radian', 'direction', 'page', 'html', 'result||to', 'value', '1', 'tool'], ['us', 'gives'], ['0028', "7fe0'x,'0010'x", 'values', '524288', '992', 'image', '1', '4080', 'getvalue', '1052', 'imageptr', '524296', '0010', 'idl', '3056'], ['result', '5.0', 'expected', 'way', '9.fdiv(5', '9.0', '0.479425538604203', 'values', 'non-integer', '9.to_f', '1.8', '10/1', '25.0', 'mode', '5.to_f', '1/3*3', '1/8', 'value', 'it’s', '1', 'method'], ['used', 'working', 'solved', 'results', 'result', 'thanks', '0.9880316240928618', 'wrong', 'however', 'apparently', 'change'], ['6', 'calculator', '98', 'radians', '0', 'logarithms', 'get', 'basic82', 'calculat', 'using', '16299', '30298', 'answer', '8', 'used', 'orst', 'logarithm', 'trying', 'edu'], ['1', '0', '2', '5d', '1001', '101b'], ['0.52', 'cot', 'result', 'radians', 'value'], ['difference'], ['calculator', 'instead', 'get', '36.00', '36', 'decpercent', 'decimal', 'struggling', 'lblpercent.text', 'help', 'deccalories', 'code', 'button1.click'], ['1', 'value'], ['diff', 'interpolatedvalue', 'derivativevalue'], ['0', 'return', '0917202', '825482', '366881'], ['0', 'bondlength'], ['0'], ['0f', '1', '0'], ['data', 'expectancy'], ['00000040', '00000070', '00000010', '2a'], [], ['different', '0', '2']]
TOP TOKENS [['garibaldi', "garibaldi's", 'july', 'mankind'], ['garibaldi', 'redshirts', '1848-49'], ['garibaldi', '1860â€™s', 'garibaldiâ€™s'], ['garibaldi', "garibaldi's", 'america', 'july', 'gees'], ['garibaldi', '1848', 'giuseppe', 'pious'], ["garibaldi's", 'garibaldi', 'garibaldini', 'giuseppe', 'mazzini'], ["garibaldi's", 'garibaldi', 'garibaldini', 'giuseppe', 'mazzini'], ['garibaldi', 'giuseppe'], ['garibaldi', "garibaldi's", 'dress', 'riall'], ['garibaldi', '1860', 'point', 'outnumbered', 'battle'], ['garibaldi', 'metro', 'gariboldi'], ['garibaldi', 'joseph'], ['garibaldi'], ['garibaldi'], ["garibaldi's", 'garibaldi', '1819', 'cipressa', '1862–1938'], ['garibaldi', 'giuseppe', 'redshirts'], ['garibaldi'], ['garibaldi'], ['garibaldi', "garibaldi's", 'hero', '2012', 'unification', 'sicilies'], ['garibaldi', 'overall', '1970', 'strikeouts']]
TOP TOKENS [['pulmonary', 'diagnoses', 'hypertension', 'syncope', 'diagnosis', 'challenging', 'defect', 'weakness'], ['pulmonary', 'end', 'surgery', 'patients', 'wanting', 'groups', 'life'], ['pulmonary', 'exercise', 'branches', 'pressure', 'clinical'], ['pulmonary', 'page', 'classification', 'arteries', 'failure', '1', 'schistosomiasis', '4', 'needs'], ['pulmonary', '“', 'page', 'guidelines'], ['pulmonary', 'sep', 'progression', 'hypertension', 'inhaled', 'threatening'], ['pulmonary', 'exercise', 'hypertension', 'cls', 'output', 'hg', 'categories', 'units'], ['pulmonary', 'pressure', 'hypertension', 'circulation', 'hg', 'porto', 'dysfunction', 'treatment'], ['pulmonary', 'surgery', 'cls', 'anticoagulation', 'patients', 'although', 'conditions', 'hypertension'], ['pulmonary', 'cls', 'years', 'hypertension', 'worse', 'damaged', 'heart', 'pressure', 'blood', 'cases'], ['pulmonary', 'links', 'scan', 'artery'], ['pulmonary'], ['pulmonary', 'lungs', 'cls', 'alveoli', 'heart', 'fibrous'], ['pulmonary', 'thrombus', 'links', 'outcomes', 'thrombectomy', 'arteries', 'external'], ['pulmonary', 'people', 'rate'], ['pulmonary', 'hypertension', 'echocardiography', 'artery', 'elevated', 'indeed', 'may'], ['pulmonary', 'describe', 'sources', 'recency', 'scan', 'hypertension', 'literature', 'thrombosis', 'several', 'model', 'luqa'], ['pulmonary', 'diaphragm', 'heart', 'hilum', 'separate', 'tree'], ['pulmonary-to-systemic', 'pulmonary', 'opening'], ['pulmonary', 'problems', 'factors', 'symptoms', 'artery', 'harder', 'lungs']]
TOP TOKENS [['changing', 'change', 'within', 'changed', 'changes', 'changeprecontemplation', 'modification'], ['change', 'depends', 'go', 'changes', 'us'], ['change', 're-engineering', 'performance'], ['change', 'changed', 'changein', 'changefrom', 'changing', 'merely', 'something', 'changes', 'woman', 'also'], ['change', 'form', 'changes', 'becomes', 'ages'], ['change', 'changing', 'reversed', 'changed', 'different'], ['change', '’', '‘', 'another', 'changes', 'years', 'completely'], ['changed', 'changes', 'change', 'significantly', '“', 'changelessness', 'compounding', 'changeup', 'word'], ['change'], ['changes', 'changing', 'change', "also,'change", 'changed'], ['change', 'different', 'netherlands', 'applegate', 'changes'], ['changing', 'change', 'changed', 'changes'], ['changes', '1983', 'nakai', 'change', 'american', '2011', 'kiley', 'cls'], ['change', 'changes', 'also'], ['change', 'changes'], ['change', 'changed'], ['change'], ['change'], ['change', 'changed'], ['change', 'perro', 'behind', 'girl', 'song']]
TOP TOKENS [['architecture', 'data', 'knowledge', '“data', 'enterprise’s', 'forth', 'nicoelnino/shutterstock.com', 'activities'], ['architecture', 'security', 'depend'], ['architecture', 'data', 'information'], ['architecture', 'data', 'interconnecting', 'information'], ['architecture', 'systems', 'system'], ['architecture', 'software', 'architectural', 'manageability'], ['architecture'], ['architecture'], ['architecture', 'process', 'execution', 'business', 'technical', 'architectures', 'result', '’'], ['architecture', 'architectural', 'manageability'], ['architecture', 'technology', 'infrastructure'], ['architecture', 'architectures', 'catalog', 'permit', 'software'], ['architecture', 'network', 'structures', 'architects', 'use', 'systems', 'detailed'], ['architecture', 'architectures'], ['architectures', 'architecture', 'data', 'technology', 'enterprise', "agency's", 'methodologies', 'complete', 'combining', 'called', 'developing'], ['architecture', 'architectures', 'data', 'types', 'state', 'architect', 'software', 'system', 'systems', 'architectural', 'cls'], ['architecture', 'architectures', 'technology', 'data', 'systems', 'enterprise'], ['architecture', 'system', 'architectures', 'systems', 'pervasive', 'baseline', 'software', 'environment'], ['architecture', 'links', 'also', 'systems'], ['architecture', 'security', '1900–1936', 'information', 'product', 'shelter', 'systems', 'enterprise', 'processes', 'process', 'hardware']]
TOP TOKENS [['war', 'vietnam', 'anti-war'], ['war', 'vietnam', 'u', 'aa'], ['war', 'vietnam', 'war—the', 'post-tet', 'american'], ['war', 'vietnam'], ['war', 'vietnam'], ['war', 'vietnam', 'us'], ['war', 'vietnam', "america's", 'vietcong', 'americans'], ['war', 'vietnam', 'us', 'u', 'united', 'states', 'american', 'military', 'veterans', 'america'], ['war', 'vietnam', 'vietcong', 'americans', 'vets', '000', 'world', 'veterans', 'us', 'american'], ['war', 'vietnam'], ['vietnam', 'war'], ['war', 'vietnam', 'united', 'states'], ['war', 'pavn', 'vietnam', 'military', 'u', 'us', 'tet', 'troops', 'country', 'soldiers', 'fighting', 'vietnamese', 'states'], ['war', 'vietnam', 'americans', 'u', 'states', 'united'], ['war', 'vietnam', 'american', 'united', 'states', "states'involvement"], ['vietnam', 'war', 'states', 'people', 'united', 'victors', 'us', 'americans', 'tet'], ['vietnam', 'washington', 'war', 'u', 'american', 'doves', 'reservists'], ['war', 'vietnam', 'u', 'veterans', 'veteran', "veterans'movement", 'soldier', 'antiwar'], ['us', 'war', 'pavn', 'states', 'vietnam', 'united', 'vietnamization', 'military', 'america', 'soldiers', 'american', 'vc', 'tet', 'americans', 'militarily'], ['vietnam', 'war']]
TOP TOKENS [['11'], [], [], ['various', 'experiencing', 'could', 'ended', 'pushed', 'banked', 'knew'], [], [], [], [], ['imagico'], ['gave', 'us'], [], [], ['–', 'serves'], ['make', 'instruments', 'empire'], [], [], [], ['also'], [], []]
TOP TOKENS [['charities', 'charitable', 'charity', 'giving', 'money', 'donations', 'give', 'costs', 'people', 'important', 'raising', 'donation', 'gives'], ['charitable', 'gifts', 'contributions', 'charities', 'making', 'care', 'dues', 'industries', 'perspective', 'clubs', 'lodges', 'money'], ['charities', 'charitable', 'giving', 'people', '1', 'give', 'contributions', '000', 'much'], ['charitable', 'gifts', 'contributions', 'pay'], ['charitable', 'charities', 'gifts', 'charity', 'money', 'contributions', 'solicit', 'people', 'pay', 'budgets', 'hand'], ['charitable', 'beneficiaries', 'donations', 'people', 'trust', 'promotion', 'rights'], ['charitable', 'charities', 'amounts', 'giving', 'charity', 'poor', 'give', 'financial', 'funds', 'inputs'], ['charities', 'charity', 'gifts', 'donations', 'contributions', 'raise', 'donors', 'money', 'budget', 'auctioned', 'recipients', 'instances', 'contributors', 'financial', 'auctions', 'instance', 'attendees'], ['charitable', 'donations', 'contributing', 'less', 'giving'], ['charitable', 'contributions', '86', '281', 'charities', 'status', 'donations', "organization's", 'assets', 'fundraisers', 'deductible', 'grants', 'solicit', 'well', '2017', 'organizations'], ['charities', 'charitable', 'charity', 'gift', 'money', 'expire', 'vary', '“', 'issuer'], ['charity', 'charities', 'giving', 'charitable', 'e'], ['£100', 'charity', 'donates', '£125', '£25', 'gift', 'money', 'donated', 'donations', 'someone', 'donor', 'e', 'taxpayers', "people's", 'payment', 'buying', 'person', 'people'], ['charitable', 'contributions', 'charities', "organization's", '281', 'status', 'donations', '2017', '86', 'solicit', 'organizations', 'additionally', 'several'], ['charities', 'charity', 'beneficiaries', 'giving', 'give', 'contribute', 'gifts', 'donor', 'receives', 'donating', 'fund', 'given', '13', 'make', 'one'], ['charitable', 'charities', '£1', 'giving', 'donations', 'gift', 'gifts', 'declarations', 'charity', '£600', 'individuals', 'shops', '32', 'donor', '22', 'amounted', 'given', 'donation'], ['charities', 'gift', '£1', '£30', '£2', 'donations', 'charity', '£25', 'giver'], ['charitable', 'donors', 'charity', 'contribute', 'audits', 'contributions', 'remain', 'ones', 'charities', 'foundation', 'nonprofits', 'grants', 'manner', 'including', 'organizations', 'foundations', 'range', 'expenses', 'programs', 'grant', 'receive'], ['charitable', 'charities', "donor's", 'contributions', 'donor', 'donations', 'gift', 'amount', 'amounts', 'also', 'contribution', 'must', 'cls', 'organizations', '75', 'uses', 'exhaustive', 'synagogues'], ['charity', "giver's", 'giver', '£25', 'making', 'donation', 'donated', '£75', 'gift', '£125', '£68', '£31', 'paid']]

Processing features:  42%|████▏     | 41/98 [19:39<27:02, 28.46s/it]

getting sample prompt forgetting sample prompt for 23893
 23892
getting sample prompt for 23894
getting sample prompt for 23895
getting sample prompt for 23896
getting sample prompt for 23897
getting sample prompt for 23898
getting sample prompt for 23899
getting sample prompt for 23900
getting sample prompt for 23901
getting sample prompt for 23902
getting sample prompt for 23903
TOP TOKENS [['sawfish', 'saw', 'sawfish’s', 'haihanxeng', 'coммonly', 'froм'], ['sawfish', 'eat', 'saw', 'lose'], ['sawfish', "sawfish's", 'sawfish—historically', 'earned', 'appearance', 'sharks', 'teeth', 'decline', 'smaller', 'one'], ['sawfish', 'n', 'definition', 'saw', 'sawlike', 'wha', 'ass', 'ash', 'saws'], ['sawfish', 'cls', 'ufl', 'natural', 'museum', 'smalltooth', 'two', '■a', 'www', 'saw'], ['sawfish', 'cls', 'forth', 'smalltooth', 'swiping', 'cartilaginous', 'u', 'saw', 'alike', '6', 'japan', 'saws', 'part', 'sharks', 'along'], ['sawfish', 'sawfishes', 'time', 'newborn', 'saw'], ['sawfish', 'sawfishes', 'time', 'newborn', 'saw'], ['sawfly', 'adult', 'running', 'village', 'fairly'], ['sawfish', 'sawsharks', 'sawshark', '6', 'eww', 'saw', 'make', 'cartilaginous', '950', 'nevertheless'], ['sawa', 'references'], ['sawdust', 'wood'], ['sawa', 'sāwa', 'hrycuniak', 'ibaraki', 'may', 'refer'], ['saw', 'census-designated', 'moderate', 'small'], ['sawt'], ['sawki', 'międzyrzec', 'north'], ['sawi', 'refer', 'chumphon', 'may'], ['sawa', '1,315', 'local', '1,095'], ['sawer', "72°38'21e"], ['sawtelle', 'sawtell']]
TOP TOKENS [['ciao', 'ciaoallow', 'frau', 'kowtow', 'italian', 'capital'], ['ciam', 'market', 'one', 'full', 'vericlouds', 'dynamic', 'katryna', 'pii', 'feature', 'government´s', 'lam', 'vendors', 'dates', 'pki'], ['ciara', 'logy'], ['ciardi', '’', 'pervasive', 'nevertheless', 'often', 'true', 'observed', 'diction', 'father', 'world', 'belaboring', 'two', 'protean', '”', 'overstatement', 'poem', 'tenets', 'beginning', 'colloquialisms', 'something', 'beyond'], ['ciap', "ciap's", 'clearly', 'language', 'structure', 'profession', 'area', 'workplace', 'main', 'infrastructure', 'electronic', 'existing', 'different', 'power', 'search', 'behind'], ['cialis', 'ciais', 'felt', 'performed', 'effectiveness', 'weekend', 'use'], ['cialis', 'www', 'without'], ['ciara', 'chiara', 'ears', 'blissfully', 'depressed', '”', '180', '’', 'others', 'teach', 'triumphantly', 'eriu', 'seclusion', 'druid', 'derdriu', 'man'], ['cialis', 'cialisforsaleonlinecheapp', 'ultra', 'ive', 'viagra', '–', 'mind', 'viagraonlinegenericcheapnorx', 'youthful'], ['ciancio', 'cianciare', 'cianci(a', 'ciaccio', 'oxford'], ['ciao', 'greeting', 'disambiguation', 'film'], ['ciaz'], ['ciano'], ['galicia', 'ciar'], ['ciara', 'singer-songwriter', 'sierra', 'p42'], ['aeromodelling', 'cjdv-fm', 'ciam', 'ciam-fm', 'fort'], ['ciat'], ['ciara', 'ciarán', '2006', 'teachta', 'dark-haired', '1992', 'lucey', 'dála', 'original', 'janson', 'gaynor', 'mccormack'], ['ciaran', 'ciar', 'ciara', 'ciarraige', 'bourke', '1965', '1969', 'bairead', "o'keiran", 'hinds'], ['ciaf', "d'armistizio", 'ferroviarios']]
TOP TOKENS [['license', 'term', 'licensee', 'means', 'also', 'generally', 'money'], ['license', 'definition', 'ordinarily', 'possessing', 'therein', 'enumerated'], ['license', 'licensing', 'licenses', 'definition', 'licensees', 'licensee', 'general', 'licensor'], ['license', 'licensing', 'licensed', 'licenses', 'needed', 'whitening'], ['license', 'licence', 'licenses', 'give', 'licensee'], ['licence', 'license', 'grant', 'holds', 'licenses', 'noun', 'verb', 'licensee'], ['license', 'licensing', 'licence', 'licenses', 'grant', 'cls', 'activity'], ['licensing', 'license'], ['license', 'licence', 'licensing', 'licenses', 'use', 'using', 'however', 'fishing', 'broadcast', 'pay', 'vs'], ['licences', 'license', 'licenses', 'license”', 'business'], ['licensing', 'license', 'licenses'], ['license', 'licenses', 'licensed', 'licensing', 'require'], ['licensing', 'licenses', 'license', 'license4j', 'licensed', 'manager'], ['license'], ['licenses', 'license', 'licensing', 'metering'], ['license', 'licence', 'licensed', 'kill'], ['licenses', 'license'], ['licenses', 'license', 'licensed', 'licensing', 'enable'], ['license', 'performance', 'background', 'makoto', 'peaked', 'released'], ['license', 'licensing', 'licenses', 'site', 'fees', 'paid']]
TOP TOKENS [['richter', 'regarding', '’'], ['richter', "richter's", '2006', 'dedicated', 'gerhard', 'exhibition', 'dusseldorf', '2009', 'course'], ['richter', 'days', 'canvases', '2003', '’', 'later', 'world', 'works', 'good', 'year', 'sculptural', 'stage', 'reputation'], ['richter', "richter's", 'much', 'generation', 'years', 'berlin', 'art', 'litigation', 'accident'], ['richter', "richter's", 'see', 'says', 'today', 'sometimes', '1992'], ["richter's", 'richter', 'raisonne', 'date', 'gerhard', 'painting', 'biennale', 'dusseldorf', 'scale', '1'], ['richter', 'wrote', 'gegenstand', 'thought'], ["richter's", 'richter', '1950s', 'essays', 'fact', 'israel', 'cinema', 'film', 'dada', 'movies'], ['richter'], ['richter', "richter's", 'war', 'training', '1913', 'seeber', 'deutsches', 'artistic', 'aktion', 'kandinsky'], ['richter', '2012', '2022', 'season', '2016', 'end', "men's", 'fc'], ['richter', '1'], ['richter', 'carolina', 'death', 'north', 'war', 'american', '2009'], ['richter', '1985', 'chl', 'people', 'hospodar'], ['richters', '1955', 'ferdinand'], ['richter', 'hc', 'liga', 'czech', 'ice', 'people', 'hockey'], ["richter's", 'richter', 'game', 'played', 'australian', "men's"], ['richter'], ['richter', 'pfähler'], ['richter', 'schachzeitung', 'nf6']]
TOP TOKENS [["michigan's", 'michigan', "gov't"], ['michigan', "michigan's", 'difficult', 'around'], ['michigan', "flag-michigan's", "michigan's", 'state', 'see'], ['michigan', 'although', 'mich', 'cls', '’', 'however'], ['michigan', "michigan's", '“', '1980s', '’', 'educated', 'deaths', 'year'], ['michigan', 'often'], ['michigan', "michigan's"], ['michigan', "michigan's"], ['michigan', 'michigan’s', 'says'], ['michigan', 'cls', 'state', '000', 'billion', '10', '’', 'detroit', '3'], ['michigan'], ['michigan', '27'], ["michigan's", 'michigan', 'state', 'pg', '28'], ['michigan', 'u.s', '2', 'time', 'approximately', 'study', 'election'], ['michigan', 'onlyinclude'], ['michigan', 'land'], ['michigan', 'wolverine', '–'], ['rowspan', "michigan's", '26', '22', '4', 'mar', '–', 'michigan'], ['michigan', 'u.s', 'state'], ['michigan']]
TOP TOKENS [['cls'], [], ['adrift'], [], [], ["barnardo's", 'indentured'], [], [], [], [], [], [], [], ['centenarian', 'berthier', 'milliner', 'service', 'mccall', '1886–1962', '1759–1826', 'brownlow'], [], ['records', 'shops'], ['center', '1927', '1917', 'american', '1936', 'born', 'footballer', '–'], [], [], []]
TOP TOKENS [['enlarge', 'national', 'mn', 'click', 'map', 'facu', 'thickets', 'wetland', 'status:||gp', 'plant', 'distribution', 'ncne', 'stem', 'pick', 'glossary', 'please', 'point', 'visit', 'seen', 'easily', 'bloom', 'mw', 'near', 'habitat:||part', '1/3', 'usually', 'inches', 'also', 'park', 'often', 'season:||april', 'height:||4', 'woods'], ['mw', 'sepals', 'sepal', 'click', 'national', 'distribution', 'enlarge', 'narrowly', 'single', 'ncne', 'see', 'often', 'county', 'slight', 'sheathing', 'pronounced', 'map', 'behind', 'pick', 'recently', 'whose', 'wide', 'well'], ['mn', 'click', 'map', 'status:||none', 'national', 'enlarge', 'distribution', 'sponsors', 'feet', 'wetland', 'plant', 'buy', 'woods', 'glossary', 'parallel', 'height:||1', 'chayka', 'county', 'pick', 'see', 'running', 'please', 'habitat:||part', 'bloom', 'green', 'base', 'stems', 'courtesy'], ['distribution', 'click', 'map', 'status:||none', 'mn', 'national', 'please', 'wetland', 'sepals', 'enlarge', 'plant', 'indicator', 'season:||june', 'fully', 'habitat:||sun', 'cycle:||perennial', 'forest', 'county', 'evergreen', 'especially', 'glossary', 'inches', 'green', 'well', 'see', 'alternate', 'carpels', 'sheaths', 'height:||4', '½', 'palmately', 'woody'], ['near', 'click', 'national', 'branching', 'leaflets', 'edges', 'pick', '3¼', 'creamy', 'sharply', 'park', 'map', 'point', 'veins', 'enlarge', 'none', 'glossary', 'oddly', 'extended', 'also', 'separate', '1', 'quickly', 'please', 'technically', '30'], ['s.c', 'although', 'conservatism', 'conn', 'traits', 'dentate', 'state', 'ga', 'throughout', 'pp', 'glabrous', 'beneath', 'leaflets', 'seldom', 'adjacent', 'kans', 'sepals', 'lxxv', 'less', '3-9', 'hairs', 'generally', 'la', 'rarely', 'long'], ['national', 'closely', 'sepals', 'aligned', 'distribution', 'encloses', 'mw', 'except', 'occasionally', 'enlarge', 'broadly', 'along', 'less', 'frilly', 'though', 'click', 'side', 'glossary', "flower's", 'see', 'parted', 'relatively', 'erect'], ['distributionusa', 'yes', '6', 'provided', 'directoryaccording', 'avail', '2002', 'ms', 'national', '841', 'region', 'believed', 'picayune', 'burrell', 'sources', 'following', 'bibliographybibref', 'e', 'others', 'affiliate', '8', 'status', 'benefituse', 'de', 'johnstown', 'c', 'commercially', 'spring', 'associate', 'damude', 'nj', 'insects', '7', 'nc', 'dc', 'fl', 'circumneutral', 'tx', 'propagationdescription', 'necessary', 'ny', 'md'], ['national', 'click', 'distribution', 'nub', 'county', 'mw', 'primary', 'map', 'palmately', 'well', 'sepals', 'obl', 'typically', 'broadly', 'lip', 'pick', 'near', 'generally'], ['provided', 'avail', 'directoryaccording', 'following', 'yes', 'circumneutral', '8', 'picayune', '6', 'bibliographybibref', 'tx', 'bibref', 'region', 'hockessin', 'conspicuous', 'commercially', 'moist', '7', 'la', 'c', 'nc', 'benefituse', 'sandy', 'area', 'atlanta', 'loam', 'sc', 'wasowski', 'organizations', 'based', 'ms', '318', 'sown', '291'], ['appears', 'ideal', 'separate', 'range'], ['southeastern', 'mississippi', 'distribution', 'absent', 'carolina', 'outside', 'sepals', 'found'], ['likely', 'estimated', 'wv', 'natural', '67', 'given', '1', 'area', '—', 'occasionally', 'sk', '34', 'essentially', 'usually', 'provide', 'ri', 'qc'], ['basal', 'southeastern', 'distribution', 'assumed', 'around', 'mississippi', 'usually', 'present', 'extirpated', 'stem', 'records', 'april', 'alabama'], ['range', 'map', 'database', 'disjunct', 'north', 'southeastern', 'exists', 'along', 'ditches', 'another', 'plants', 'bogs', 'mississippi'], ['sheraton', 'woods', '–', 'foundation', 'jackson', 'carolina', 'organizational', 'official', 'national', 'florida', 'profile', 'tennessee', 'many', 'georgia', 'sep', 'dilorenzo'], ['southeastern'], ['region', 'range', 'addition'], ['leaflets', 'expected', 'database', 'sepals', 'inflorescence', 'north-central', 'without', 'tjm2', 'bractlets', 'central', 'flora', 'three', 'much', 'sometimes'], ['sepals', 'southeastern', 'national', 'moss', 'often', 'north-central', 'near', 'nearctic', 'south-central', 'vermont', 'eastern', 'united', 'n', 'america', 'states', 'hampshire', 'stem']]
TOP TOKENS [['leukoplak', 'leukoplakia', 'cls'], ['leukoplakia', 'well', 'even'], ['leukoplakia', 'cls'], ['leukoplakia', 'us', 'state||published', 'oral', 'follow-up'], ['leukoplakia'], ['leukoplakia', 'cls'], ['leukoplakia', 'cls'], ['leukoplakia', 'cls'], ['leukoplakia', 'cls', 'teeth'], ['leukoplakias', 'leukoplakia', '2-3', 'i.e'], ['leukodystrophies', 'leukodystrophy', 'leuko', 'cls', 'years', 'word'], ['leukorrh', 'leukorrhea', 'delivery', 'leukos', 'cls', 'leucorrhoea', 'flow', 'usually', 'word', 'finding'], ['leukodystrophies', 'leukoencephalopathies', 'leukoencephalopathy', 'leukodystrophy-like'], ['leukoplakia', 'leucoplasie', 'erythroplakia', 'english', 'area'], ['leukoplakia', 'leukos', 'leukoedema', 'cls', 'although', 'oidema', 'bilaterally', 'fact', 'οιδημα', 'disease', 'users'], ['leukomalacia', 'leukoencephalopathy', 'periventricular', 'less', 'around', 'vlasyuk', 'commonly', 'delays', 'starts', 'often', 'pvl'], ['leukoplakia', 'keratin', 'immunocompromised', 'especially', 'may', 'definition', 'upon'], ['leukoaraiosis', 'cls', 'associated', 'factors', 'individuals', 'ischemia', 'mri'], ['leukoplakia', 'term', 'erythroplakia'], ['leukoplakia', 'leukoedema', 'prognosis', 'epidemiology', 'depending', 'varying', 'history', 'lesion', 'presentation']]
TOP TOKENS [['durch', 'du', 'gesundheitsgefahrdung', 'upon', 'li', '1', 'p', 'health', 'gerstmann', 'fur', 'radium', 'h', 'b', 'w', 'mit', 'g', 'gesundheit', 'ingestion', 'u', 'v', 'schimmack', '05', 'roth', 'neuherberg', '23'], ['1', 'nevertheless', 'present', 'reproductive', '2', 'even', 'excess', 'forces', 'total', 'contrast', 'u', 'du', 'applications'], ['upon', 'amounts', 'shrapnel', 'inhaled', 'aerosolized', 'penetrators', 'du', 'used', 'two'], ['upon', 'amounts', 'shrapnel', 'inhaled', 'aerosolized', 'penetrators', 'du', 'used', 'two'], ['dry', 'du', 'windy', 'iraq', 'vaporized'], ['burning', 'inhaled', 'contact', 'however', '9', 'friction', 'du', 'u', 'wind', 'iraq', 'bosnia', 'huge', 'removed', 'single'], ['du', "du's", 'use', 'recent', 'ammunition', 'settings', 'however', 'data', 'even', 'civilians'], ['du', 'seven', 'tanks', "m1a1's", 'five', 'ingested', 'days', 'annual', "round's", 'impact', 'continually', 'amount', "iraqi's"], ['du', 'much', 'shrapnel', 'used', 'exposures', 'war', 'available', 'unnecessarily'], ['shrapnel', 'fire', 'du', 'poisoning', 'syndrome', 'vehicles', 'exams', 'also'], ['2005', 'du', '75', 'english', '2000', 'textbooks', 'books', 'china', 'papers', '1980s', 'australia–china', 'education', 'society', 'states', 'australian', 'april', 'many', '1992', 'literature', 'authored'], ['du', 'new', 'weight', '2018', 'life', 'khoo', 'personal', 'interviews', '2012', 'album', 'holdings', 'career', '2016', 'also'], ["russia's", "redkollegia's", 'dud', 'russian', '–', 'april'], ['dcfldd', 'updated', 'disk', 'one', 'utilities', '7', 'potentially', '3', 'whenever', 'file', 'harbour', 'calculations', '2021', '2023', 'another', 'updating', 'operation', 'filter', 'page', 'option'], ['du', '2009', 'living', 'asian', 'august', '21st-century', 'olympics', '29', 'new', 'sportspeople', "women's", 'summer', 'november', 'olympic', 'medalists', 'twice', '2003', 'fellow', 'however', 'sport', 'female', 'chinese', 'references', 'hebei', 'competition', 'later', '2006'], ['every', 'c', 'day', 'starts', 'scary', 'exclusive', 'single', '2011', 'rigorous', 'war', '18', 'cinematic', 'freedom', 'step', 'said', "game's", 'state', 'well', 'game', 'reality', '2', 'true', 'interdependence', 'delise', 'plausible', 'brands', 'include', 'everything', 'fictional', 'chinese'], ['application', 'operations', 'detectable', 'baiting', 'samples', '0', 'hours', '1080', '2442', '1', 'supplies', 'water', '2010', 'also'], ['du', 'sportspeople', 'chinese', "men's", 'living', 'references', 'people', 'career', 'yatai', '1–0', '2014', 'changjie', 'minute', 'external'], ['du', 'one', '2012', 'used', 'january', 'also', '2004', 'enrichment', 'u', '4', 'et', 'clear', 'fallujah', 'existing', 'hadithi', 'died', 'dead', 'including', 'manning', '6', 'al'], ['girl', 'also', 'voice', "na'el", 'crowe', 'appearance', '2011', 'grace', 'beanstalk', '2005', 'ny', 'numb3rs', '2010', 'voiced', 'role', '2008', 'megan', 'shooting', 'fiona', 'graber']]
TOP TOKENS [['abstracts', 'abstract', 'summary', 'less'], ['abstracts', 'abstract', 'words', 'writing', 'contents', 'work', 'good'], ['abstracts', 'abstract', 'cls', 'compelling', 'manuscripts', 'got'], ['abstracts', 'abstracted', 'abstract', 'findings', 'submission'], ['abstracts', 'how_to_write_extended_abstracts', 'abstract', 'writing'], ['abstracts', 'abstract', 'findings', 'content', 'words', 'results'], ['abstracts', 'abstract', 'carefully', 'work', 'short', 'findings'], ['abstracts', 'abstract', 'effective', 'publication', 'degrees', 'presentation', 'long', 'writing', 'article'], ['abstracts', 'abstract', 'deliver', 'brief', 'less', 'writing', '2', 'compared', 'rightfully'], ['abstracts', 'reports', 'abstract', 'containing', 'effective', '•', 'work'], ['abstract', 'abstracts', 'conclusions', 'reports', 'cls', 'synopsis'], ['abstracts', 'sometimes', "as'abstracts", 'abstract', 'content', 'society', 'words', 'logically', 'minutes', 'published'], ['abstracts', 'reports', 'abstract', 'pages', 'community', 'appendices', 'also', 'reporting'], ['abstracts', 'analytical', 'via', 'chemistry', 'journals', 'one', 'kingdom', 'abstracting'], ['abstracts', 'abstract', 'summary', 'event', 'preparing', 'work', 'investigation', 'full', 'data'], ['abstracts', 'abstract', 'results', 'findings', 'review'], ['abstracts', 'abstract', 'review', 'minutes', 'potential', 'written', 'implications', 'limitations', 'get', 'great', 'results'], ['abstracts', 'includes', 'published'], ['abstracts', 'abstract', 'abstract-related'], ['abstracts', '—', 'abstract', 'documentation', 'summary']]
TOP TOKENS [['peduncle', 'lowly', 'underutilized', 'make', '“', 'research', 'elasticity', 'fida', 'development', 'products', 'industry', 'authority', 'innovation', 'rationale', 'dietary', 'developed', 'left', 'titled', 'utilized', 'considered', 'material'], ['one', '“'], ['1d2', 'point', 'regards'], ['masticating', 'separated', 'one'], [], ['unsubstantial', 'regarding'], ['gandring', 'wad', 'based', 'unlucky', 'considered', 'months', 'cases', 'ways'], ['wither', 'prosper'], ['reproduction', 'something'], ['much', '“', 'far', 'concerned', 'nigh'], ['sessile', 'inferior', 'pedunculated', 'mass', 'said', 'peduncle', 'medicine', 'known'], [], ['divisions', 'external', 'body', 'part', 'connects', 'bodies', 'connect', 'caudal', 'used', 'lobes', 'attaches', 'arthropods'], ['manteri'], ['minoccurs'], ['stories', 'armageddon'], ['filamentous', 'granitic', 'fruticose', 'species', 'substrate', 'distribution'], ['pieces', 'leaving', 'without', 'stubby', 'traditions', 'two', 'invoke'], [], []]
TOP TOKENS [['marley', 'marley(redirected', 'reggae', 'bob', '2017'], ['marley', 'reggae', 'bob', 'century', 'комментарии'], ['marley', "marley's", 'reggae', 'bob', 'name', '60s', 'years'], ['marley', 'reggae', 'bob', 'cls', '’'], ['marley', 'reggae', 'bob', '”', 'everyone'], ['marley', 'marley’s', 'bob', 'love.”', 'life', 'white', 'thereafter', 'success'], ['marley', 'reggae', 'bob'], ['marley', 'reggae', 'bob', 'rock'], ['marley', 'marley’s', 'reggae', 'bob', 'youth', '1962', 'group'], ['marley', "marley's", 'reggae', 'bob', 'hyperbole', 'wisdom', 'universal', 'time'], ['marley', 'soundtrack', 'film', 'vinyl'], ['marley'], ['marley', 'bob'], ["marley's", 'marley', 'one', 'stage', 'prison', '1984'], ['marley', "marley's", 'bob', 'reggae', 'marleye', 'jamaican', 'damian'], ['marley', 'bob'], ['marley'], ["marley's", 'marley', '2007', '2019', 'reggae', 'life', 'xxxtentacion', 'jamaican', 'personal', 'tour'], ['marley', "marley's", 'reggae', 'career', 'jamaica', 'nesta'], ['marley', 'marleywould', "marley's", 'bob', 'music', 'drums']]

Processing features:  43%|████▎     | 42/98 [20:07<26:22, 28.26s/it]

getting sample prompt forgetting sample prompt for 23905
 23904
getting sample prompt for 23906
getting sample prompt for 23907
getting sample prompt for 23908
getting sample prompt for 23909
getting sample prompt for 23910
getting sample prompt for 23911
getting sample prompt for 23912
getting sample prompt for 23913
getting sample prompt for 23914
getting sample prompt for 23915
TOP TOKENS [['kroner', 'kr', '818'], ['1973', 'kroner'], ['8048', 'would'], ['kronor'], ['kroner'], ['kronor', 'kr648', '000'], ['kronor', '1973', '1980', 'kr187', 'kr50', '000'], [], ['kroner', 'kr'], ['kronor'], [], ['external', '1988', 'references', 'links', 'general', 'seasons', 'character', 'ewing', 'van', 'audrey', 'television', 'american', 'hunnicutt', "show's", 'series', 'dallas', 'r'], ['external', 'links', 'references', 'seasons', 'general', 'audrey', 'ewing', 'played', '20', '26', 'episodes', 'j.r', 'season', '2', 'vanessa'], ['bellamy', 'show'], [], ['1933', 'external', 'deaths', 'links', 'references', 'actors', 'also', '1991', 'throughout'], [], [], [], []]
TOP TOKENS [['1830', 'greater', 'hither', 'merrick', 'emerald', 'feet', '2,500', 'probably', 'wide', 'mericoke'], ['merkle', '’', 'first', 'change', 'impossible', 'tends', 'represented', 'real', 'actual', 'ever', 'useful', 'without', 'might', 'tree', 'uses', 'back'], ['merroth', 'mathias', 'click', 'merrothmerroto', 'merroy', '1949', 'merroths', 'merrrill'], ['merriner', '2000', 'james', 'merrio', '1991', 'merrington', 'merriners', 'h', 'merrink', 'merrinon', 'uncommon', 'merrini', 'merrinermerrinette', 'merringe'], ['merkel', 'came', 'unavoidable', 'scientist', 'spring', 'less', 'supported', 'times', 'phased', 'allowed', 'membership', 'advocated', "government's", 'favoured', 'opposition', 'may', '2003', 'law', 'overwhelming', 'large', 'u', 'defying', 'existing', 'see', 'planned', 'precise', 'number'], ['permission', 'jan', 'recognized', 'merle', '©', 'may', 'marking', 'marien-de', 'appears', 'sheepdog', 'hence', 'usually'], ['merle', 'merled', 'prominant', 'acts', 'acting', 'genetics', 'primarily', 'less', 'around', 'stick', 'stays', 'may', 'coat', 'undiluted', 'gene', 'often'], ['sep', 'merb', 'merback', '1912', 'merbmerbach'], ['merlion', 'last', '8546889°e', 'merly', "merlion's", '2870222°n', '88', 'part', '″', '1°17', 'park'], ['merle', 'may', 'comes', '1/2', 'incomplete', 'pattern'], ['england'], ['manhattan', '1919–2006', 'wig', 'philanthropist', 'new', 'merkin'], ['italian', '1248', 'merano', 'italy'], ['eastern', 'merkland', '1795–1852', 'new'], ['borders', 'alessandria'], ['1929', 'july', 'show', '10', '1931', 'merriam', 'actress', '1928'], ['1723–1807', 'charles', '1593–1650', '1647–1717', '1923-2007', '1800–1858'], ['surname'], ['1840s'], ['west', '1992', 'male', 'lead', 'merrick', 'springfield', '65672', 'minor']]
TOP TOKENS [['cress', 'property', 'eat'], ['cress', 'observations'], ['loess', '30'], ['cress', 'cress’', 'seeds', 'grow', 'garden', 'http://www.hindawi.com/journals/ecam/2012/596524', '‘garden'], ['cress', 'grow'], ['cress', 'cresson'], ['cress', 'cresses', 'garden', 'arvense', 'coarse', 'species', 'upland'], ['cress', 'days', 'garden', 'peppery', 'seed-starter'], ['cress', 'lips', 'eat', 'seeds', 'aromatic'], ['cress', 'garden', 'menswelfare', 'material'], ['gress'], ['bress'], ['cress', 'welsing', 'barbarea', 'william'], ['bress', 'syracuse', 'screenwriter', 'received', 'people'], ['cress', 'california', 'b', 'war', 'november', 'ness'], ['cress', '1944', '1947', 'retirement', '1950', '1945'], ['riess', 'riess-passer', 'erwin', 'adam', '1861–1928', 'german-american'], ['pless', 'course', 'virginians', 'double-a', 'vicksburg', '364', 'rance', 'tars', 'league', 'hill', 'millers', 'seasons'], ['cress', 'born', 'states'], ['gress']]
TOP TOKENS [['legal', 'law', "giuliani's", 'podair', 'hoerr', 'gadsden', 'c', 'michel', 'inglis', '‘', 'women', 'quinn', 'jordan'], ['legal', 'law', "giuliani's", 'podair', 'hoerr', 'gadsden', 'c', 'michel', 'inglis', '‘', 'women', 'quinn', 'jordan'], [], [], ['improvements'], ['settlement', 'technical'], ['letter', '15', '16', 'members', 'e'], ['technology', 'shining', 'get'], [], ['smiles', 'receive', 'bloom', 'chopin', 'new', 'elliott', 'inger'], ["fuse's", 'well', 'legislation', 'person', 'representative', 'awards', 'constituents', 'kilmer', 'finally'], ['a-lex', 'treatment'], ['mihai', 'ion', 'dumitru', 'alexandru', 'ovid', 'gheorghe', 'bogdan', 'nina', 'doru', 'ovidiu', 'list', 'p'], ['–', "blush's", 'milestones', 'stevenblush', 'march', '8', "city's", '28'], [], [], [], ['boom'], ['music', 'surfacing', 'band'], []]
TOP TOKENS [['prop', 'props', '“', 'cls', 'dictionary'], ['prop', 'props', "prop's", 'cls', '1', 'unless', 'storybuilding', 'special'], ['props', 'prop', 'word'], ['prop', 'props', 'cls', 'movement', 'pretty', 'yup', 'come'], ['props', 'prop', '1', '2', 'use', 'cls', 'foreign', 'conventional', 'using'], ['prop', 'props', 'eye', 'cars', 'function'], ['props', 'prop'], ['props', 'prop', '‘prop’', 'inputs', 'think'], ['prop', 'props', 'present'], ['props', 'using', '4', '3', 'use', '2', 'give'], ['props', 'set', 'prop-word', 'prop', 'glee', 'transporter'], ['prop'], ['props', 'inc', 'propellers', 'held'], ['props', 'prop', 'called', 'term'], ['props', 'prop', 'j', 'mathematics', 'kind', 'name'], ['props', 'science'], ['prop', 'props', 'cls', 'due', 'typically'], ['props', 'propping', 'prop', 'cls', 'many', 'schools'], ['prop', 'lack', 'cls', 'place'], ['prop']]
TOP TOKENS [['salvation', 'redemption', 'savior', 'help', 'translated', 'lytroo', "german'loskauf", "german'christ", 'redeem', 'election', 'religions', 'save'], ['salvation', 'redemption', 'obtain', 'saves', 'saved', 'achieve', 'save', 'word', 'following', 'saving', 'way'], ['salvation', 'thus', '“', 'saved', 'got', '”', 'really', 'gospel'], ['salvation', '“', 'based', '”', 'saved', 'unsaved'], ['salvation', 'heart', 'redemption', 'saves', 'burning', 'baulks', 'doubt', 'depth', 'hell'], ['salvation', 'redemption', 'sin', 'word', 'saved', 'god', 'cls', '…', 'truth', 'saving', '”'], ['salvation', 'redemption', 'obtained', 'translated', 'saved', 'eternal', 'said', 'save', 'extend'], ['salvation', 'redemption', 'redeem', 'judaism', 'precepts', 'cannot', 'cls', 'idea', 'saved', 'need', 'saving'], ['salvation', 'held', 'redemption', 'redeemer', 'amazement', 'redeeming', 'saving', 'devil', 'rescues', 'saves', 'saved'], ['salvation', '“', '3', '”', 'mine', 'saved', 'save', 'romans', 'christ', 'great', 'god', 'see', 'term', '6'], ['salvation', 'series', 'album', 'gugabriel', 'cranberries', 'situation', 'alias', 'manuella'], ['salvation'], ['salvation', 'redemption', 'redeemers', 'element', 'foreclosed', 'zorzi', 'suffering', 'born', 'theology'], ['salvation', 'behind', 'perspective', 'website', 'morphed', 'dark', 'lucafix', 'taking', 'avoiding', 'windows'], ['salvation'], ['salvation', 'albrecht', 'bengel'], ['redemption'], ['salvation'], ['salvation'], ['salvation', 'links', 'external']]
TOP TOKENS [['bougainvillea', 'bougainvilleas'], ['bougainvillea'], ['bougainvilleas', 'bougainvillea', 'bougain'], ['bougainvillea', 'bougainville', 'bougainvilleas'], ['bougainvillea', 'sunlight', 'season'], ['bougainvillea', "bougainvillea's", 'bougainville'], ['bougainvilleas', 'bougainvillea', '’'], ['bougainvilleas', 'bougainvillea', '’'], ['bougainvilleas', 'bougainvillea', 'bouga'], ['bougainvillea', 'bougainvilleas', 'm).bougainvillea', 'bougainville'], ['bougainville', 'bougainvillea', 'bougainvilliidae', 'bougainvillia', 'antoine', 'cgm'], ['bougainville'], ['bougainvillea'], ['bougainville', 'bougainvillia', 'bougainvilliidae'], ['bougainville'], ['bougainville'], ['bougainville', 'bougainvillean'], ['bougainville'], ['bougainville-class', 'bougainville'], ['bougainville', 'bougainvillea', 'infiniment']]
TOP TOKENS [['seiners', 'seine', 'seiner', 'purse', 'outfitted', 'seine/drum'], ['hayworth', 'rooney', 'canteen', 'doughnut', 'entire', 'dietrich', 'rogers', 'faithful', 'mickey', 'plays', 'gingham', 'rita', 'hollywood', 'performing', 'mouth', 'floor', 'putting', 'szigeti', 'old', 'around', 'staff', 'delightful'], ['pollarding', 'pollards', 'pollarded', 'broadleaved', '19th', 'majority', 'regrowing', 'pseudoacacia', 'shoots', 'malus', 'late', 'many', 'nobilis', 'trees', 'uk', 'hornbeams', 'century', 'metre', 'include', 'however'], ['seiners', 'purse', 'seines', 'pens', 'purses', 'tuna', 'ranching', 'also', '‘purse’', 'use', 'together', 'made', 'called'], ['purse', 'seine', 'seiners', 'equipped', 'seines', 'sayn', 'spruce', 'root', 'tuna', 'wove', 'cls', 'fishing', 'cork'], ['purse', 'seiners', 'seine', 'fad', 'method', 'yellowfin', 'flagged', 'free', 'france', 'caught', 'indian', 'ocean', 'sea', 'sets', '200kg', 'overfishing', 'overfished', 'albeit', 'length', "world's", 'handline'], ['seine', 'purse', 'seines', 'seiners', 'fleets'], ['sunset', 'mara', 'serena', 'safari', 'expedition', 'chui', '’', 'andbeyond'], ['seiners', 'seine', 'purse', 'seines', 'operations', 'engage', 'mostly', '61', 'outriggers'], ['run', 'around', 'gschriebn', 'wos', 'ummadumgrennt', 'viennese', 'washbowl', 'lavoir', 'kaffeetscherl', 'mir', 'flaaasch', 'times', 'kriegt', 'fir', 'n', 'hundert', 'widerliches', 'sidewalk', 'remains'], ['mundur', 'kandow', 'dana', 'dewi', 'siahaan', 'monos', 'cinta', 'yessy', 'prima', 'starring', 'yenny', 'gita', 'musim', 'mujur', 'sugara', 'ciptadi', 'robby', 'mariam', 'kena', 'cyntia', 'membakar', 'joice', '1981', 'arnaz', 'melodi', 'hati', 'otong', 'mangara', 'dari', 'zulkarnaen', 'guzman'], [], ['frank', '2009', 'sons'], ['smiley', "autry's", 'stuntwork', 'filming', 'whiskey', "rootin'tootin'rhythm", 'autry', 'canutt', 'natteford', 'burnette', 'aw', "burnette's", 'hills', 'taliaferro', "armida's", 'tex', 'kidding', 'augie', 'songs', 'clauser'], ['cabaret', 'u.s', 'english-language', 'panthera', '1929-1940'], ['seiners', 'seiner', 'purse', 'seine', 'pursed', 'nets', 'manoeuvrability', 'amidships', 'tuna', 'use', 'species'], ['sons', 'daughters', "ctv's", 'groups', '2013', 'musical'], ['sondaw', 'external'], ['range', 'prowlers', 'powder', 'roaring', 'humes', 'sunset', 'mounted', 'buck', 'films', 'western', 'work', 'em', 'west', 'hawk', 'back'], ['woof', 'thames']]
TOP TOKENS [['chives', 'sow', 'chive', 'plant', 'scallion', 'cls', '0'], ['chives', 'sow', 'chive', 'plant', 'scallion', 'cls', '0'], ['chives', 'sow', 'chive', 'plant', 'scallion', 'cls', '0'], ['chives', 'chive', 'scallions', 'plants', 'garden', 'cinch', 'cls', 'grass', 'onions', 'plant'], ['nasturtiums', 'nasturtium', 'bloomers', 'garden'], ['chives', 'chive', 'plant', 'allium', 'garden', 'schoenoprasum', 'potato', 'inches', 'flavor'], ['chives', 'garnish', 'theherbprof', 'subtlety'], ['nasturtium', 'linguine', 'routt', 'scallops', 'washed', 'scallions', 'petals', 'oeuvre', '1', 'diagonally', 'years'], ['chives', 'fiber', 'milder', 'onion'], ['chives', 'chive', 'lettuce', 'dishes', 'garden', 'crop', 'perennials', 'yard', 'pests'], ['hipparchia', 'tarpeia', 'grayling', 'amymone', 'norique', 'alpin', 'rockbrown', 'herrich', 'hierro', 'circe', "brown's", 'european', '1792', "graeser's", 'hubner', 'cingovskii', 'gomera', 'schneider'], ['elvenfolk', 'humanfolk', 'yuuki', 'beastfolk', 'girl', 'voice', 'normally', 'easily', 'immediately', 'life', 'woman', 'people', 'though', 'also', 'rei', 'accessories', 'clothes', 'sings', 'one'], ['rhellicani', 'pyreneesgymnadenia', 'gymnadenia', 'g', 'graebn', 'fohringeri', 'shawgymnadenia', '×', 'koreagymnadenia', 'j', 'schltr', 'e', 'asch', 'stoj', 'h', 'heufleri', 'var', 'w', 'b'], [], ['woollypod', 'milkvetch', "lackschewitz'milkvetch", "robbins'milkvetch"], ['ragwort', 'goldenrod', 'groundsel', 'butterweed', 'senecio', 'lambstongue'], ['chiton', 'girdle', 'undocaerulea', 'mottling', 'hues', 'pink', 'superficially', 'often'], ['hipparchia', 'grayling', 'neohipparchia', 'melanargia', 'circe', 'neapolitana'], ['heartwort', 'ricciaceae', 'liverworts', 'riccia', 'plants', 'ricciocarpos', 'ricciocarpus', 'plant', 'broader', 'waters', 'forms', 'water', 'aquatic'], ['astragalus', 'milkvetch', 'herb', 'legume', 'shevockii', 'granite-based', 'centimeter', 'centimeters', '1', 'flora', 'oval-shaped', '35', 'thin', 'profile']]
TOP TOKENS [['docker'], ['docker', 'dockerfile', 'let'], ['docker', 'running', 'dockerfile', 'direct', 'ubuntu', 'much'], ['docker', 'docker.io', 'usr/local/bin/docker', 'usr/bin/docker.io', 'https://docs.docker.com/userguide', 'https://hub.docker.com'], ['docker', 'dockerfile'], ['docker', 'https://hub.docker.com/r/_/nginx', 'also', 'maintainability', 'dockerfile', 'dependencies'], ['docker'], ['docker', 'dockerfile', 'image', 'container'], ['docker', 'dockerfile', 'cls'], ['docker'], ['docker', 'dockers', 'docker(s', 'dock'], ['docker', 'dockerfile', 'images', 'dockerd', 'nspawn'], ['döcker', 'docker', '1906–1983', '1842–1923'], ['docker', 'dockerfile', 'company', 'command', 'update'], ['dockerfile', 'docker', "docker's", 'september', 'specification', 'cls', '2014', 'hykes'], ['docker', 'called', '9', 'inc', 'cls', 'machines'], ['docker', '2015', '2011', '2021', 'restructuring', 'september'], ['docker', 'minute', 'last', 'november', "king's", '1914'], ['docker', 'arkholme'], ['dockery', '1933–2022', '1981', '1984']]
TOP TOKENS [['rainbow', 'pale', 'rainbows', 'usually', 'reflections'], ['rainbows', 'rainbow', '’', 'example', 'way', 'unless', 'exposures', 'normally', 'along', 'sun', 'light', 'nothing'], ['rainbows', 'rainbow', 'raindrop', 'bright', 'me,”', 'length'], ['rainbows', 'rainbow', 'sun', 'fact', 'overpowers', 'observed', 'quadruple', 'color', '6°', '42°'], ['rainbows', 'raindrops', 'rainbow', 'sun', 'important', 'roygbiv', 'fog', 'others', 'moon', '—', 'sky', 'light', 'around', 'banding'], ['another', 'rainbow', 'sun', 'refracts'], ['one', 'rainbow', 'first', 'raindrops', 'even', 'though'], ['arc', 'rainbows', 'wavelength', 'rainbow', 'due', 'classes', 'light', '1', '’', 'refracted', 'circumstances', 'reversed', 'well', 'sun'], ['rainbows', 'rainbow', 'raindrops', 'sun', 'click'], ['multiple', 'rainbows', 'rainbow', 'arc', 'sun', 'correspondingly', 'bow', 'seen'], ['rainbows', 'rainbow', 'one', '750nm', 'sun', 'practice', 'primary', 'theory'], ['artificially', 'sun', 'rainbow', 'arc', 'rainbows', 'ground', "observer's", 'conditions', 'reversed', 'water', 'rain', 'refracted'], ['rainbow', 'raindrops', 'shape', 'rainbows', 'ground', 'circle', 'well', 'since', 'diametrically', 'sky'], ['rainbow', 'rainbows', '—', 'sunset', 'however'], ['rainbow', 'rainbows', 'sun', "observer's", 'however', 'raindrops'], ['rainbow', 'maxima', 'rainbows', 'however', 'reflection'], ['rainbow'], ['rainbow', 'rainbows', 'droplets', 'degrees', 'e', 'course'], [], ['rainbow', 'rainbows', 'raindrops']]
TOP TOKENS [['music', 'musical', 'song', 'musicians', 'instrument', 'band', 'singer'], ['musical', 'music', 'instrument', 'musician', 'orchestra', 'musicians', 'songs', 'singers'], ['music', 'musician', 'musicians', 'songs', 'musical', 'songwriters', 'band', 'artists', 'singers', 'singer', 'singing'], ['music', 'band'], ['music', 'musicians', 'musical', 'band', 'bands', 'guitar', 'players', 'piano', 'singer'], ['music', 'songs', 'musical', 'instrument', 'virtuoso', 'melody', "composers'techniques", 'instrumental', 'lyrics', 'chords', 'orchestras', 'composers'], ['music', 'especially', 'trend'], ['music', 'musicians', 'musical', 'musician'], ['songs', 'music', 'song', 'musicians', 'musician', 'melody'], ['musicians', 'music', 'melodies', 'cls', 'backgrounds', 'musical'], ['musical', 'music', 'band', 'jazz'], ['music', 'musical', 'musician', 'musicology', 'composer', "musicians'union", 'instruments', 'biomusicology'], ['musicians', 'bands', 'music', 'songs', 'rock', 'song', 'pop', 'musical'], ['music', 'musicians', 'musical', 'piano', 'songs', 'song', 'composers', 'instrument', 'instruments', 'guitarists', 'playing', 'songsters', 'players'], ['music', 'musical', 'musician', 'band', 'musicians', 'instruments', 'guitar'], ['music', 'bands', 'musics', 'musical', 'singers', 'musicians', 'musicology', 'musicological', 'song', 'musicologist', 'concert'], ['music', 'musicians', 'instrument', 'bands', "bands'rehearsals", 'instruments', 'band', 'player', 'playing', 'styles', 'pop', 'play', 'rock', 'guitar', 'singers'], ['guitar', 'piano', 'guitars', 'percussion', 'drums'], ['music', 'musicians', 'musician', 'instruments', 'musical', 'songs', 'singer', 'song', 'melody', 'orchestra', 'band'], ['musician', 'bandleader', 'music', 'rock', 'guitar', 'songwriter', 'singer', 'player', 'guitarist', 'instrumentalist']]

Processing features:  44%|████▍     | 43/98 [20:35<25:52, 28.22s/it]

getting sample prompt for 23916
getting sample prompt for 23917
getting sample prompt for 23918
getting sample prompt for 23919
getting sample prompt for 23920
getting sample prompt for 23921
getting sample prompt for 23922
getting sample prompt for 23923
getting sample prompt for 23924
getting sample prompt for 23925
getting sample prompt for 23926
getting sample prompt for 23927
TOP TOKENS [['24', 'untreated', '6', 'quite', 'problematic', '5', 'actually', 'early', 'watery', '3'], ['24', 'christ', 'jesus'], ['24v', '24', '48v'], ['24v', 'finally', 'addition', '48v', '48', 'temperatures', 'expensive', 'advantage', 'another'], ['24', 'common', 'quite', 'greater', '675'], ['24v', '24', 'use'], ['24', '24×7', 'essentially', 'next', 'states'], ['24', '12', 'examples', 'p', '23', 'along', 'find', 'mm', 'cls', 'form', '07'], ['24', '23', 'midnight', 'avoid', '00', 'p', 'uses'], ['24-hour', '24', '23'], ['24a', 'm-24a'], ['24', 'simpsons', 'depraved', 'review', 'australia', 'series', '2', 'marketplace', '–', 'outstanding', 'television', 'rights'], ['24', '24/7', 'related'], ['24c', '24w', '24', '24b', '24d', 'n24'], ['24a', 'm-24a'], ['24-hour', '24'], ['24', 'campierganj', 'mardah'], ['24a', '24', '1923'], ['24', 'approximately'], ['24', '71', '67', 'external', 'links', 'small', '285', 'antero', 'i-25', 'concurrent']]
TOP TOKENS [['something', 'beholds', 'possible', 'behold', 'behealdan', 'etymology', 'please', 'keep', 'including'], ['areas', 'state', 'freight', 'goods', 'electronics', 'service', 'obtained', 'equipment', 'knowledge', 'chemistry', 'lodging', 'education', 'passengers', 'technical', 'biology', 'tickets', 'required'], ['areas', 'state', 'freight', 'goods', 'electronics', 'service', 'obtained', 'equipment', 'knowledge', 'chemistry', 'lodging', 'education', 'passengers', 'technical', 'biology', 'tickets', 'required'], ['arrant', 'possible', 'heterodoxy', 'het·ero·doxy', 'ˌdäk-sē'], [], ['original', 'create', 'aestheticize', 'commodify', 'commodifymodify', 'commodifying', 'playful', 'verb'], [], ['longer', 'hidden', 'sourced', 'business', 'future'], ['adulterated', 'adulteration', 'adulterant', 'adulterants'], ['something', 'existence', 'invention', 'originate', 'esp', 'numbers', 'etc'], ['consumed', 'operations', 'sep'], ['live', 'azadogly', '2010', 'localities', 'centre', 'russia'], [], [], ['folly', 'ate'], ['behold', 'surprise', 'world', 'sitcom', 'beholden', 'ho', 'gung'], ['outside', 'apprenticing'], [], [], ['product', 'optimization', 'search', 'service', 'discoverable', 'make']]
TOP TOKENS [['interpret', 'take', 'unless', 'really', 'think', 'look', 'goes', 'going', 'run', 'likely', 'forbes', 'quickly', 'data', 'long', 'seems', '–', 'thinks', 'know', 'shown'], ['interpret', 'lots', 'probably', 'see', 'links', 'disease', 'knowing', 'expect', 'predicting', 'limitations', 'still', 'odds', 'results', 'however', 'linked', 'scientists', 'tell', 'sense', 'predictor', 'could', 'tells', 'makes', 'consider', 'shows', 'us', 'plenty', 'one', 'many', 'lot'], [], ['interpret', 'number', 'uncertain', 'many', 'fast', 'believe', 'may', 'lots', 'headlines', 'observers', 'cells', 'know', 'yet', 'things', 'significance', 'careful', 'plenty', 'expensive', 'least', 'beware'], ['interpret', 'number', 'uncertain', 'many', 'fast', 'believe', 'may', 'lots', 'headlines', 'observers', 'cells', 'know', 'yet', 'things', 'significance', 'careful', 'plenty', 'expensive', 'least', 'beware'], ['direction', 'right', 'quickly', 'probably', 'pointing', 'though', 'start'], ['need', 'necessary', 'finally'], ['sars', 'need', 'take', 'long', '–'], ['connection', 'unknown', 'interpreting', 'linked', 'one', 'many', 'really', 'determine', 'snps', 'understanding', 'may', 'lot', 'things', 'might', 'trick', 'seems', 'read', 'matters', 'contrast', 'way', 'also', 'people', 'tells'], ['interpret', 'wait', 'get', 'different', 'sky', 'confirmation', 'easier', 'rolling', 'headlines', 'much', 'ball', 'surely', 'long', 'pretend', 'need', 'lets', 'seems', 'hope', 'like', 'factors', 'considering', '’'], ['simple', 'scientific', 'lot', 'opensnp', 'expensive', 'results', 'hopes', 'information', 'often', 'though'], [], ["fallin'on", 'surprise', 'three', 'entries', 'debuts', 'came', 'latter', 'christmas', 'individual', 'notes', 'debuted', 'went', 'becoming', 'given'], ['would', 'however', 'emerged'], ['external', 'alternate', 'suspect', 'database', 'links', 'references', 'paranoia', '–', 'movie', 'falls', 'slips'], ['need', 'correlation', 'secure', 'opensnp', 'decide', 'still', 'whether', 'predispositions', 'readily', 'strengthened', 'though'], [], [], ['start', 'victory', 'fashions'], ['constants', 'accordance', 'altogether', 'calculations', 'thereupon']]
TOP TOKENS [['dialogue', 'written', 'characters', 'create', 'marks', 'term', 'second', 'yet', 'examples', 'longer'], ['dialogue', 'identify', 'punchy', 'technique', 'directed', 'start', '2a', 'dialogues', 'types', 'lines', '19'], ['dialogue', 'identify', 'punchy', 'technique', 'directed', 'start', '2a', 'dialogues', 'types', 'lines', '19'], ['dialogue', 'yet', 'forward', 'identify', 'interfaith', '“', 'lines'], ['dialogue', 'yet', 'forward', 'identify', 'interfaith', '“', 'lines'], ['dialogue', 'love', 'story', 'using', 'writing', 'format'], ['dialogue', 'together', '2010', 'source'], ['dialogue', 'arguing', 'called', 'gang', 'opinions', 'person', 'for…'], ['dialogue', '2.dialogue', 'characters', 'point', 'write', 'called', 'ex', 'read', 'paragraph', 'friend!”', 'enclose', 'placed'], ['dialogue', 'intent', 'particular', 'today', 'word', 'point', 'prevail', 'learning', 'order', '“', 'rather', 'judgment', 'perhaps', 'coherently', 'community'], ['dialogue', 'writing', 'systems', 'exchange', 'chief', 'world', 'dialogues', 'socratic', 'federico', 'lem', 'bakhtin', 'galileo', '25', 'restaurants', 'length'], ['dialogue', 'dialogue+2', 'dialogue+1', 'higehiro', 'began', 'history', '23', 'stylized', 'october', 'ogata', '8', 'single', 'singles', 'two', 'ayaka'], ['dialogue', 'non-fiction'], ['dialogue', '2020'], ['dialogue', 'founded'], ['dialogue', 'external', 'links', 'established'], ['dialogue', 'dialogues', 'foundations', 'use', 'term', 'admired', 'socratic', 'whose', 'became', 'developed', 'cls', 'conversation', 'traditions', 'bc', 'literature', 'written', 'dialogos'], ['dialogue', 'h', 'died', 'also', 'mrs', 'city', 'see', 'century', 'younger', 'terminal', 'became'], ['scanned', 'dialogue', 'effect', 'weeks', '6:21', 'cd', '–', '1:55', 'fume', 'liquefaction', 'misnomer'], ['dialogue', 'emerges', 'boasts', 'course', 'partners', 'time', 'batting', '22', 'whole', 'affixed', '81']]
TOP TOKENS [[], ['jest', 'drayton', 'friend', 'p'], ['drayton', 'say', 'middleton', 'heart', 'world', 'cause', 'shot', 'let', 'well'], ['chascsa', 'chascs', 'chasco', 'edit', 'chasdub', 'click'], ['drayton', '”', '—', 'added', '’', 'alexandrines', '1', 'counties', 'pretense', 'entailed', 'especially', '2'], ['rather'], ['travis'], ['tavistock'], [], [], ['short', '2018', '28', '2017', 'travis', '2016', 'eventual', 'sig', 'limoges', 'however', '20', 'american', 'order', 'people', 'mans', '18', '7', 'expatriate', '2020', '6', 'points', 'october'], ['carlisle', 'drayton', 'mr', '1902', "drayton's", 'past', 'reportedly', '250', 'reports', 'caught', 'describe', 'enquirer', 'impersonating', 'however', 'divorced', 'sensationalized', 'claiming'], ['states', 'links', 'united', 'california', 'busch', 'event', 'references', 'mexican', 'nascar', 'events', 'led', 'winston', 'standings', 'lap', 'followed', 'also', 'time', 'eighteenth', 'series', 'qualify', 'sep'], ['drayton', 'papers', 'website', 'career', 'u', 'including', 'vindicated', '–', 'unsuccessfully', 'largely', 'links', 'unionist', 'level', 'moribund', 'united', 'shown', '1835', 'states', 'served', '12', '1896', 'forts', 'party', '1846', 'controversy'], ['external', 'links', 'reading', 'drayton', 'town', 'congress', 'hall', 'london', 'sent', 'people', 'home', 'deaths', 'lands', 'american'], ['reyes', 'biography', 'rosa', '2008', 'title', 'career', 'life', 'española'], ['reyes', 'rinauro', 'maff', 'world', 'name', 'romero', 'colt', 'got', '2006', '2005', 'ring', 'would', 'known', 'council', 'along', 'eventually', 'later', 'things', 'late', 'wrestled', '9', 'better', 'title', 'came', 'also', 'rest'], ['9', 'covina', 'reyes', 'born', 'june', '2008', 'california', 'people', 'sister', 'life', 'time', 'sportspeople', '2006', '2005', 'living'], ['mexican', 'reyes', 'song', 'ensemble', 'featuring', 'discography', 'latina', 'singer', 'links', 'singers', 'canada', 'music', 'artists', 'tous', 'monterrey', 'mexico', 'tempah', 'singing'], ['players', 'crayton', 'profile', 'external', 'births', 'weltfussball', 'references', 'homepage', 'publisher', 'footballdatabase', 'sources', 'goalkeepers', "men's", 'people', '08', 'links', '2008', 'im', 'personal', 'living', 'footballers', 'expatriate', 'jahre', 'life']]
TOP TOKENS [['tunisia', 'tunisians', 'century', '42', '348'], ['tunisia', 'tunisian'], ['tunis', 'tunisian', 'tunisia', 'tunisians', 'significant', 'minister', 'also'], ['tunisia’s', 'tunisia', 'tunis', 'tunisians', 'tunisian', 'people', 'another', 'however', 'tourists'], ['tunisia', 'tunisians', 'tunis', "tunisia's", 'symbolism', 'though', 'perhaps'], ['tunisia', 'tunis', 'tunisians', 'tunisian', 'art', 'right'], ['tunisia', 'tunisians', 'however', '2020'], ['tunisia', 'tunisians', 'tunisian', 'churned', 'therefore'], ['tunisia', 'tunisian', 'tunis', 'work', 'also', 'billion', 'r', 'carthage', 'artisans'], ['tunis', 'tunisia', 'rains'], ['tunisia', "tunisia's", '9795'], ['tunisia', 'tunis', 'tunisian', 'carthage'], ['tunisia', 'tunisian', 'msaddek', 'bousarsar'], ['tunisia', '965', '459', 'sea', 'tunisian', 'tunis'], ['tunis', 'tunisia', "tunisia's", 'tunisian', 'protection', '1992', 'years', 'de', 'due', '2014'], ['tunisia', "tunisia's", 'tunisian', '1995', 'modernization', 'assembly', 'president'], ['tunisia'], ['tunisia', 'tunisians', 'tunisian'], ['tunis', 'tunisians', 'tunisia', 'tunisian', 'although'], ['tunisia']]
TOP TOKENS [['windsor', 'berkshire', '‘bank’', 'saxe-coburg-gotha', 'event'], ['windsor', "windsor's", 'coaches', 'berkshire', 'park', "and'refurbishment'of", 'castle', 'came', 'comparison'], ['windsor', 'riverside', 'england'], ['windsor', 'berkshire'], ['windsor', '“', 'berkshire'], ['windsor', 'people', 'locals', 'years', 'culture'], ['windsor', "windsor's", 'old', 'clubs', 'centre', '10', '–', 'match', '1911'], ['windsorites', 'windsor', '“', 'simply', 'quite'], ['windsor', "windsor'a", 'berkshire', 'name', 'st', 'windleshora', 'gotha', 'events', "name'of", '1564', 'monasteries', 'u', '1734', '19th', 'status'], ['windsor', 'years', 'head-of-household', 'same-sex', 'races', '10.1', 'age', '15.1'], ['windsor', "windsor's", '2019', '2018', '12', 'italy', '2021'], ['windsor', 'windsor-fry', '1929–2017', 'amelia', '2003'], ['windsor', "men's"], ['windsor', 'v', 'windsors'], ['windsor', 'berkshire'], ['windsor', "windsor's", 'berkshire', 'allen'], ['windsor'], ['windsor', 'appearances', 'thereafter', '2009', '3', 'season', '17'], ['windsor'], ['windsor', 'invention,"american', '1922', 'club', 'chicago', 'white', 'yacht']]
TOP TOKENS [['sewagemeaning', 'sewage'], ['sewage', 'i.e', 'nose', 'vomiting', 'etc', 'micro-organisms'], ['sewage'], ['sewage', 'word'], ['sewage', 'pump'], ['sewage', 'sewage-saturated', 'b', 'one'], ['sewage', 'cls', 'treating', 'treat', 'nutrients'], ['sewage', 'overflow', 'typically', 'risks', 'what’s', 'waste'], ['sewage', 'disaster', 'focus', 'comes', 'encounter', 'problems'], ['sewage', 'solids', 'discharge', 'thoroughly'], ['sewage', 'farms', 'cls', 'capacity', 'use', 'drains', 'contact'], ['sewage', 'treatment'], ['sewage', 'matter', 'feces', 'nutrients', 'enteroviruses', 'pathogens', 'found'], ['sewage', 'treatment', 'reactor', 'ali'], ['sewage', 'treatment', 'discharges', 'waters', 'certified'], ['sewage', 'cls', 'sanitary'], ['sewage', 'treatment', 'selecting', 'numerous', 'availability', 'studies', 'sanitary', 'septic', 'compatibility', 'surface', 'condition'], ['sewage', 'products', 'matter', 'domestic', 'organic', 'solids'], ['sewage', 'pumping', 'pumps', 'solids', 'small-scale', 'advantages'], ['sewage', 'cls', 'treatment', 'plant']]
TOP TOKENS [['vulture', 'vultures'], ['vultures', 'world'], ['vulture', 'vultures', 'cls'], ['vulture', "vulture's", 'vultures', 'wind', 'male', 'nature', 'done', 'everything'], ['vulture', 'vultures', 'vulturesedit'], ['vultures', 'vulture'], ['vulture', 'vultures', 'circling'], ['vultures', 'vulture’s', 'vulture', 'ruppell’s', 'world'], ['vulture', 'vultures'], ['vulture', 'vultures', "vulture's"], ['vultures', 'vulture', 'prey'], ['vulture', 'vulture-alto', 'vulture-melfese'], ['vultures', 'vulture', 'indian'], ['vulture', 'vultures', 'indian'], ['vulture', 'slowly', 'finally', 'cls'], ['vultures', 'vulture'], ['vulture'], ['vultures', 'vulture', 'whalers'], ['vulture', 'vultures', 'billed', 'world'], ['vulture', 'vultures', 'indian', 'world', 'billed']]
TOP TOKENS [['cretaceous', 'gas'], ['cretaceous', 'marine', 'derived', 'late', 'paleooceanography'], ['cretaceous', 'northern'], ['cretaceous', 'india', 'early', 'lush'], ['cretaceous', 'microscope', 'cenomanian'], ['cretaceous', 'microscope', 'cenomanian'], ['cretaceous', 'cretaceous/paleogene', '145'], ['cretaceous', '145', 'late', 'paleogene', 'unk'], ['cretaceous', 'late', 'maniraptora'], ['cretaceous', 'system', 'late', 'warm', 'important', 'gallic'], ['cretaceous', 'middle', 'northern', 'system', 'stagnation'], ['cretaceous', 'late'], ['cretaceous', 'marine', 'late', 'shelled'], ['cretaceous'], ['cretaceous', 'late', 'mosasaurs', '66', 'molluscs', 'cenozoic'], ['cretaceous', '145', 'aptian'], ['cretaceous', 'cenozoic', 'late'], ['cretaceous', 'sites', 'cenomanian', 'corda'], ['cretaceous', '2014', 'aptian', 'mongolia', 'late'], ['cretaceous', 'late', 'upper', 'enigmatic', 'research', 'fossiliferous']]
TOP TOKENS [['prostate', 'prostatitis', 'anticancer'], ['prostate', 'prostatic', 'one'], ['prostate', 'prostatic', 'health'], ['prostate', 'prostatic'], ['prostate'], ['prostate', 'prostatitis', 'anticancer'], ['prostate', 'prostatic'], ['prostate', 'prostatic'], ['prostate', 'prostatic'], ['prostate'], ['prostate'], ['prostate', 'prostatectomy', 'two', 'urinary', "young's"], ['prostate', 'prostates', 'prostatic'], ['prostatectomy', 'prostate', 'intraprostatic', 'organ', 'perineal', 'penile', 'metastatic'], ['prostate', 'prostates', 'prostatic', 'prolonging'], ['prostate', 'prostatic', 'urological', 'urology', 'prostatitis', 'proscribed'], ['prostate', 'prostatectomy', 'prostatectomies', 'proximally', 'urinary', 'pelvic'], ['prostate', 'prostatectomy'], ['prostate', 'prostatic', 'prostatectomy', 'extraprostatic', 'collagenous'], ['prostate', 'prostatic', 'prostatitis', 'trial']]
TOP TOKENS [['foreskin'], ['foreskins', 'foreskin', 'circumcision', 'circumcised'], ['foreskin'], ['foreskin', 'circumcised'], ['foreskin', 'circumcised', 'circumcision', 'antifungal'], ['foreskins', 'foreskin', 'circumcision', 'may', 'uncircumcised'], ['foreskin', 'circumcision'], ['foreskin', 'retractile', "son's", 'circumcision', 'circumcised', 'tightforeskin'], ['foreskin', 'circumcision'], ['foreskin', 'circumcision', 'circumcised', 'uncircumcised'], ['foreskin', 'circumcision', 'urinary', "pediatricians'now"], ['foreskin', 'circumcision', 'relieve', 'uncircumcised', 'circumcised'], ['foreskin', 'foreskins', 'circumcision'], ['foreskin', 'retractile', 'first'], ['foreskins', 'foreskin', "or'redundant'foreskin", 'retractable', 'retract', 'whose', 'retraction'], ['foreskin', 'circumcision'], ['foreskin', 'circumcised', 'circumcision', 'retraction', 'circumcisions', 'uncircumcised'], ['foreskin', 'retract', 'anatomy'], ['foreskin', 'first', 'circumcision', 'retract', 'retraction'], ['foreskin', 'general', 'common', 'removes', 'take', 'urinary', "circumcision's", 'little', 'poor']]

Processing features:  45%|████▍     | 44/98 [21:04<25:31, 28.37s/it]

getting sample prompt forgetting sample prompt for 23929
 23928
getting sample prompt for 23930
getting sample prompt for 23931
getting sample prompt for 23932
getting sample prompt for 23933
getting sample prompt for 23934
getting sample prompt for 23935
getting sample prompt for 23936
getting sample prompt for 23937
getting sample prompt for 23938
getting sample prompt for 23939
TOP TOKENS [['pope', 'popes', 'papacy'], ['popes', 'pope', 'papacy'], ['pope', 'popes', 'papacy'], ['popes', 'pope', 'papacy'], ['popes', 'papacy', 'pope', 'whose', 'papal', 'benedict', 'xvi'], ['popes', 'pope'], ['pope’s', 'pope', 'popes', 'papacy'], ["pope's", 'pope', 'origins', 'christ', "church's", 'church', 'bishops'], ['pope', 'index'], ['popes', 'pope', 'papacy'], ['pope', 'popes', 'county', 'name'], ['pope'], ['pope', "pope's", 'links', '0', 'external', 'people', 'references', 'f', 'international', 'notes', 'profile'], ['pope'], ['pope', 'popes', 'word', 'term', 'marcellinus'], ['pope'], ['popes', 'pope'], ['pope', '2023', '2019', '24', '2022', 'people', '2021', "men's", 'births'], ['pope', 'military', 'officer'], ['pope', 'biography']]
TOP TOKENS [['plows', 'plow', 'plough', 'plowing', 'furrow', 'word', 'plowed', 'engines', 'crops', 'exploration', 'decades', 'also', 'later'], ['plow', 'plows', 'furrow', 'furrows', 'plough', 'ploughed', 'plowing', 'ploughs', 'also'], ['plow', 'plows', 'furrow', 'furrows', 'plough', 'ploughed', 'plowing', 'ploughs', 'also'], ['plow', 'plough', 'plows', 'ploughs', 'plowed', 'furrow', 'furrows', 'plowing', 'ploughed', 'cls'], ['plow', 'plows', 'plowing', 'furrow', 'furrows'], ['plow', 'plows', 'plough', 'plowshare', 'furrow', 'spelled', 'cls'], ['plow', 'plows', 'plowing', 'furrow', 'furrows'], ['plow', 'plough(redirected', 'plough(us', 'plough', 'plough(esp', 'furrows'], ['plow', 'plows', 'furrow', 'plowing', 'furrows'], ['plow', 'plows', 'furrow', 'plowing', 'furrows'], ['plow', 'plough'], ['bellows', 'bellow', "bellow's"], ['stow', 'stowe', 'stowmarket', 'stow-on-the-wold'], ['bellow', 'bellows'], ['fallow', 'fallows'], ['tallow'], ['trow', 'britain'], ['derow'], ['clow'], ['scow', 'kate', 'c-scow', 'e-scow', 'a-scow']]
TOP TOKENS [['essex', "essex's", 'year', 'colchester'], ['essex', 'statistics', 'roding', 'c', 'south-eastern', 'liberty', 'pars', 'fertile', '1', 'mersea'], ['essex', '”'], ['essex', '1016', 'southend', 'anything', 'learn', 'harlow', 'web', 'england'], ['essex', 'southend', 'chelmsford', 'along', '300', 'sea'], ['essex', 'thereafter', '1620', '1937', 'press', 'could', 'earl'], ['essex', "essex's", 'anglian', 'belief', 'stereotypes', 'southend', 'however'], ['essex'], ['essex', '1814', 'aboard', '”', '1813'], ['essex', 'http://www.essexhistory.org/research-at-essex-historical-society.htm', 'http://www.essexct.gov/history/briefhistory.html', 'history', 'http://www.ctrivermuseum.org/content/visitinfo.aspx?sid=0'], ['essex'], ['essex', '1779', '1947'], ['essex', '2015', '2014', 'maintenance', 'deck', 'october', 'may', 'side', 'links', 'also', 'uss', 'executed', 'california'], ['essex', 'essex-class', 'six'], ['essex', "essex's", 'hms', 'battle'], ['essex', '60-gun', '70-gun'], ['essex', 'b', 'isaac', 'units', 'settler'], ['essex', 'neighbor', 'operational', 'three', 'aircraft', 'town', '40', 'abandonment', "community's"], ['essex'], ['essex', '1929']]
TOP TOKENS [['saucers', 'saucer', 'l'], ['saucer', '2011', 'saucerful', 'saucerfull', 'pdt', 'med'], ['saucers', 'saucer', 'flying', 'fields'], ['saucer'], ['saucer', 'put'], ['saucers', 'saucer”', 'saucer.”', '“flying'], ['saucer', 'saucers', 'flying', 'hoaxes', 'c', 'one'], ['saucer', 'saucers', 'flying', 'proposed'], ['saucer', 'saucers', 'choosing', 'quickly', 'healthy', 'plant'], ['saucer'], ['saucer', "saucer'64", "flyin'saucers", 'saucers', "joker's", 'ufo', 'flying'], ['saucers', 'saucer', 'flying'], ['saucer', 'saucers', 'cup-and-saucer', 'cobaea', 'sanguinea'], ['saucers', 'saucer', 'flying', 'spaceship'], ['saucer'], ['saucer', 'saucers', 'flying'], ['saucers', 'flying', 'product', 'kingdom'], ['saucer', 'cordilleran'], ['saucers', 'saucer', 'flying'], ['saucer', 'flying', 'footers', 'history', 'also']]
TOP TOKENS [['matrices', 'matrix', 'officially', 'ways', 'thing'], ['matrix'], ['matrix', 'matrices'], ['matrices', 'matrix'], ['matrix', 'matrices?thanks', 'matrices', 'matrix?”a', 'around', 'theory', 'column'], ['matrix', '3', '2'], ['matrices', 'matrix'], ['matrix', 'matrices'], ['matrix', 'matrices', 'change', 'eg', '2d'], ['matrix', 'using', 'a[j', 'array', 'however', 'program', 'right', 'math.h', 'stdio.h', '5'], ['matrix'], ['matrices', 'matrix'], ['matrix', 'dot-matrix', 'code', 'printers'], ['matrices', 'matrix', 'mathematics'], ['matrices', 'matrix', 'purposes'], ['matrix'], ['matrix', 'matrices', 'graph'], ['matrix', 'pitched', 'originally', 'first', 'adventure', 'unworkable', 'face-to-face', 'era', 'ace'], ['matrix', 'matrices', 'a−1', 'column'], ['matrix', 'matrices', 'word']]
TOP TOKENS [['cloffa', 'beneath', 'ref', '1', 'gen', '1441', 'classification', 'elongated', '13371'], ['cloffa', 'lm', 'namessynonymsmetabolismpredatorsecotoxicologyreproductionmaturityspawningspawning', 'worms', 'surkhan', '45335', 'ref', '82804'], ['southward', 'cloffa', 'ref', 'aral', 'south', '2059', 'gen', '39', '65°', 'baltic', 'worms', '0', 'classification', 'except', 'white', 'sp', 'france'], ['cloffa', 'worms', 'ref', 'lm', '45335', '53530', '4', 'col', 'killifishes', 'genus', '3'], ['cloffa', '79012', 'worms', 'range', 'gen', '8', '12468', '86798', 'namessynonymsmetabolismpredatorsecotoxicologyreproductionmaturityspawningspawning', 'ref'], ['cloffa', '3', 'lm', 'gen', 'worms', '4', 'greek', '39226', 'ref', '6', '1'], ['cloffa', 'gen', 'worms', '9', '75799', 'except', 'lm', 'classification', 'sp', 'vs', 'itis', '45335'], ['cloffa', '45335', 'worms', 'gen', 'ref', 'benthopelagic', '72462', '22', 'classification', '16', '6', 'sp', '39°n', '17', 'temperate'], ['cloffa', 'ref', 'gen', '2', '59043', '62', '2059', 'classification', 'worms', 'lm', 'sp', 'synonyms'], ['cloffa', '12193', 'gen', 'worms', '61', 'greek', 'ref', '25', '45335', '1', 'range', 'classification', 'sp'], ['references'], ['cls', 'airbreathing', 'squatinidae', 'notothenioidei', 'species', 'pomfret', 'suborder', 'perciformes', 'others', 'pomacentridae', 'refer', 'heteropneustes', 'still', 'may', 'brevirostre', 'bathybius', 'subfamily', 'family', 'pomacanthidae', 'lophiiformes', 'piscatorius', 'anguillare', 'toxotes', 'including', 'peristediidae'], ['worm', 'lumbrineridae', 'renier', 'earthworm', 'karageorgopoulos', 'bosc', 'family', 'syn', 'euphrosinidae', 'montagu', '1954', 'bristleworms', 'quatrefages', 'chiaje', 'kinberg', 'stephen', 'aphroditois'], ['see', 'also', 'ed', 'worms', 'original', 'vols', 'literature', 'publication', 'w.n', 'monthly', 'francisco', 'names', '3', '2905', '697', 'eschmeyer', 'contains', 'instance', '1998', '10,600'], [], ['sabanejewia', "choi's", 'species', 'rossomeridionalis', 'parabotia', 'spined', "luther's", 'leiocassis', 'cobitis', "krynicki's", 'ciscaucasian', 'glanis', 'weatherfishes', 'oxynoemacheilus', 'lutheri', 'loaches', '—', 'spiny', 'catostomus', "soldatov's", 'choii', 'tachysurus', 'lefua', 'caucasica', 'barbatula', 'siluridae', 'fossilis', 'catfishes', 'siluriformes'], [], ['schistosomiasis', 'gastrodiscoidisis', 'diseases'], [], ['†', '–']]
TOP TOKENS [['doughnuts', 'dressings', 'sugar', 'eat', 'consume', 'eats', 'salad', 'eating'], ['sugar', 'eat', 'consumes', 'vitamins'], ['dressings', 'sugars', 'sugar'], ['sugar', 'intakes', 'diabetic'], ['sugars', 'sugar', 'it’s', 'daily', 'eat'], ['eat', 'sugar', 'consumption'], ['sugar', 'sugars', 'ate'], ['sugars', 'applesauce', 'eat', 'condiments', 'sugar', 'much', 'pastries', 'eating'], ['sugar', 'dressings', 'teaspoons', 'substitutions', 'things'], ['much', 'intake', 'candies', 'sugar', 'that’s'], ['sugar', 'intake', 'sugars', 'juices', 'sweeteners', 'desserts', 'calorie', 'products', 'consumption', 'health', 'carbohydrate', 'food', 'carbohydrates', 'disaccharide'], ['sugar', 'sugars', 'intake', 'juices', 'nectars', 'consumption', 'beverages', 'per'], ['sugar', 'cereals', 'foods', 'yogurts', 'drinks', 'chocolate', 'consumption', 'cookies', 'cream', 'healthier', 'sugary', 'diet', 'etc', 'health', 'year', 'many', 'common', 'diets'], ['sugar', 'whiting', '1971', 'james', 'glee', 'cls', '–', 'female', 'actress', 'substances', 'motta', 'marimon', 'beard', 'singer'], ['sterling', 'sugar', 'utensils'], ['sugars', 'sugar', 'intake', 'amount', 'juices', 'consumption', 'calories', 'sugary', 'eating', 'syrups', 'diets', 'item', 'disaccharides', 'foods', 'food', 'obesity', 'concentrates'], ['sugar', 'sugars', 'syrups', 'per', 'concentrates', 'juices', 'consumption', 'intake', 'disaccharides', 'foods', 'consume', 'experts', 'juice', 'around', 'e', 'belgium'], ['sugar', 'creams', 'candies', 'sri', 'either', 'placed', 'added', 'also', 'many', 'soups', 'cuisine'], ['sportspeople', "men's", 'expatriate', 'vojvodina', 'association', 'footballers'], ['olympic', 'volleyball', 'references', 'south']]
TOP TOKENS [['cirrhosis', 'certain', 'direct'], ['cirrhosis'], ['cirrhosis'], ['cirrhosis'], ['cirrhosis'], ['cirrhosis'], ['cirrhosis', 'cirrhotic'], ['cirrhosis', 'people', 'nonspecific'], ['cirrhosis', 'people'], ['cirrhosis', 'cls'], ['cirrhosis', 'cirrhotic', 'people', 'occurs', 'illness'], ['cirrhosis', 'hepatic', 'cancer', 'cls', 'cholesterol', 'sclerosing'], ['cirrhosis', 'cirrhotic', 'igg', '–', 'ana', 'diagnosed', 'igm', "wilson's", 'ceruloplasmin'], ['cirrhosis', 'word', '100'], ['cirrhosis', 'familial'], ['cirrus', 'germany'], ['cirrhia'], ['cirrhosis', 'cirrhotic', 'people', '0', 'might', '1', '–', 'esophageal', 'evidence', 'another'], ['cirrhosis', 'cirrhotic', 'flavus', 'cause', 'related', 'described'], ['cirrhosis', 'people', 'exist', 'cavity', 'tendinous', 'thinning', 'discontinuities', 'like']]
TOP TOKENS [['wreaths', 'wreath', 'cls', 'garlands', 'aphrodite', 'mortal', 'construction', 'corona'], ['wreath', 'wreaths'], ['wreaths', 'wreath', 'nowadays'], ['wreath', 'wreaths', 'simple', 'word', 'cls'], ['wreath', 'wreaths', 'today', 'b.c', 'garlands'], ['wreaths', 'world', 'wreath'], ['wreaths', 'wreath', 'cls', 'life', 'events', 'faith'], ['wreaths', 'wreath', 'status', 'door'], ['wreath', 'wreaths', 'evergreen', '4740', 'festive'], ['wreath', 'wreathes', 'beautiful'], ['wreaths', 'wreath', 'word', 'cls', 'wrethe', 'laurel', 'corona'], ['wreath', 'wreaths', 'cls', 'crown'], ['wreaths', 'wreathed', 'wreath', 'wine', 'sacrilege'], ['wreath', 'links', 'garden', 'metaphor'], ['wreaths', 'wreath', 'bouquets', 'decorative', 'years'], ['wreaths', 'wreath', 'bouquets', 'flowers'], ['wreaths', 'wreath', 'wreathed', 'onwards', 'theocritus', 'laurel', 'wearing', 'wine', 'battle'], ['wreaths', 'wreath', 'kingdom', 'memorial', 'lay', 'lays'], ['wreath'], ['wreaths', 'wreath', 'modern', 'make', 'christmas', 'games']]
TOP TOKENS [['discrepancies', 'together', 'organisations', 'arification', 'subdivided', 'one', 'either', 'ones', 'also'], ['one', 'could'], ['proper', 'person', 'others', 'often', 'another', 'example', 'easy', 'hours', 'nevertheless', 'world'], ['8f'], ['cls', 'well'], ['aaa', 'basis', 'aa', 'national', 'published', 'bb', 'e', 'may', '–', 'divisions', 'one', 'considered', 'intervals', 'years', 'well', 'usually', 'standards', 'serve', 'conditions', 'also'], ['used', 'terms', 'aggregated', 'areas', 'rankings', 'factors', "magazine's", 'example', 'one', 'least'], ['committee', 'authority', '1ł', 'pledges'], ["today's", 'behalf'], ['persons', 'order'], ['authorize', 'countries', 'nontransparent', 'frameworks', 'authorities', 'question', 'often', 'commission', '2010s', 'corresponds', 'odds', 'bet', 'proposition', 'occurred', 'expressed', 'hand', 'betting', 'according', 'also', '—', 'example', 'sort', 'specific'], ['desirable', 'use', 'instance', 'available', 'g'], ['way', "interviewee's", 'permits', 'one', "person's", 'teachers', 'example', '—'], [], ['respectively', 'would', 'whether', 'someone', 'country', 'could', 'ambiguous', 'tactically', 'able', 'creators', "government's", 'leaves', 'describes', 'degree'], [], ['genders'], [], ['community', 'parts', 'two', 'used', 'contests', 'together', 'cater', 'legs', 'hardbodied'], ['together', 'acted', "men's", 'event', 'also', 'one', 'compared']]
TOP TOKENS [['used'], ['like', '–', 'wind', 'alliteration', 'use', 'sound', 'common', 'splash', 'water', 'refrains', 'onomatopoeic', 'elements', 'shush', 'great', 'assonance', 'especially', 'swish', 'write'], ['hera', 'ganymed', 'juno', 'eros', '’', '50s', 'course'], ['hera', 'ganymed', 'juno', 'eros', '’', '50s', 'course'], [], [], [], ['solomon', 'provides'], ['59', 'suppose', 'hh:mm', 'say', 'also', 'moments', "let's", 'clarity', 'ab:ab', '23', 'occurrences', 'represents', 'well', 'written'], [], ['similarly', 'directed', 'writing', 'equating', 'rating', 'storyline'], [], ['singling', 'compared', 'easily', 'indistinguishable', 'displays'], ['many', 'examples', 'yet', 'borrowed', 'also', 'noted', 'offering', 'called', 'referred', 'two', 'unique'], ['guild', 'award'], ['–', 'overhead'], [], [], [], []]
TOP TOKENS [['watarru', 'tuchitua', 'yapeen', 'x1a', 'yt', 'tas', '5s8', 'muston', 'ab', 'nb', 'v8w', 'wendouree', 'pohenegamook', 'canada', 'slocan', 'sa', 'qld', 'bc', 'vic'], ['burramine', 'jonction', 'yt', '9w3', 'tas', 'v8w', 'nb', '6073', 's4p', '1n3', 'e3b', 'x1a', 'mb', 'nl', 'canada', 'sk', '5c1', 'vic', 'nt', 'south', 'coulee', '1s2', '4l7', 'nicolet', '5j2', 'r3b', 'coquitlam', 'qc', 'ns'], ['tas', 'yt', 'mundare', 'nb', 'v8w', '6093', 'sk', 'glenavon', '8s2', 'malbaie', 'ab', 'hartney', 'percee', 'r3b', 'wa', 'e3b', 'nt', 'bawlf', 'richelieu', 'glenaire', 'mb', 's4p', 'pe', 'wekweeti', 'qc', 'canada', 'x1a', 'bc', 'powassan'], ['yt', 'nt', 'macnutt', 'x1a', 'tuchitua', 'ab', 'sk', 'tas', 'sa', 'y1a', 's4p', 'wa', 'nb', 'canada', '7072', '5052', 'qc', 'vic', 'qld', 'bc', '9l3', '4s4', 'v8w', '5n1', 'ns', 'pe', '4069', 'e3b'], ['e3b', 's4p', 'yt', 'v8w', 'nb', 'ns', 'beloeil', '5s6', 'ab', 'beaverlodge', 'terrebonne', 'minto', 'resolution', 'camooweal', 'qc', 'kinkora', 'pe', 'x1a', 'mundallio'], ['yt', 'curlewis', 'v8w', 'qc', 'y1a', '3w6', 'x1a', '7l8', 'mb', 'sk', 'vic', 'wekweeti', 'bc', 'tas', 'senlac', 'canada', 'ab', '4n2', 'nt', 'nb', '8s8', '3009', 'whitwarta', 'sa', 'qld', 'ns', '6062', '1j4', 'wa', 's4p', '5054'], ['yt', 'x1a', 'wette', 'tas', 'tsiigehtchic', 'v8w', 'nt', 'sk', 'canada', 'sa', 'vic', 'nb', 'pe', 'qld', 'carstairs', 'lebret', '6073', 'wa', 'y1a', 'molyullah', 'trinite', 'creston', 'bc', 'mb', '8p8', 'ab', '6n6', 'granya', 'dunnottar', 'maggea', '1c9', 'birkenhead'], ['yt', 'nt', 'sadadeen', 'v8w', 'y1a', 'x1a', 'ab', 'calen', 'qld', 'sk', 'nb', 'canada', 'bc', 'vic', 'eungella', 'tas', 'e3b', '5092', 'semaphore', 'sa', '7014', 'masset', '8s7', 'qc', 'r3b', 'manning', 'smythes', '4039'], ['yt', 'nb', 'tas', 'qc', 'r3b', 'nt', '9w9', 'goranba', 'ab', 'lansdowne', 'v8w', 'sk', 'senneterre', 'x1a', 'mb', 'groote', 'mannus', 'bc', 'sa', 'vic', 'wekweeti', '6026', 'qld', 'y1a', 'neds', '3l8', 'canada', '5c8', 'horfield', 'jansen', 'sorell', '5064'], ['mistassini', 'a1b', 'r3b', 'x0a', 'qc', 'nb', 'mb', 'yt', 'beaubassin', 'wabush', 's4p', 'e3b', '1s7', 'nl', 'luseland', 'x1a', 'qikiqtarjuaq', '4p5', 'ns', 'nt', 'aylen', 'senneterre', 'c1a', 'beausejour'], ['mke1', 'yyz4', 'yyz7', 'yyz3', 'yyz9', 'yyc6', 'yyc1', 'yyc4', 'yyz1', 'yow1', 'mex1'], ['oromocto'], [], [], ['quispamsis'], ['templestowe', 'woodside', 'tunbridge', 'bathurst', 'circuit'], ['okayama', 'kix4', 'sjab', 'takatsuki', 'nct'], ['shelburne'], [], []]

Processing features:  46%|████▌     | 45/98 [21:33<25:12, 28.55s/it]

getting sample prompt forgetting sample prompt for 23941
getting sample prompt for 23942
 23940
getting sample prompt for 23943
getting sample prompt for 23944
getting sample prompt for 23945
getting sample prompt for 23946
getting sample prompt for 23947
getting sample prompt for 23948
getting sample prompt for 23949
getting sample prompt for 23950
getting sample prompt for 23951
TOP TOKENS [['petrus', '1988', 'made', 'slavs', 'delta', 'danube', 'peter', '601', 'petros', 'later', 'brother', 'witness', 'carry', 'attempted', 'cappadocia', 'chalcedon', 'calm', 'arabissus', 'πέτρος', 'defeated'], ['1853', 'whilst', 'petrie', 'fayoum', 'later', 'developed', 'one', 'nurture'], ['home/ben/petard-foo', 'petard-foo', 'petard', 'petardfs', 'specify', 'without', 'file', 'example'], ['breakdown', 'petrov', 'quintessential', 'first', 'world', 'different', '–', 'orders', 'hand', '”', 'made', '’', 'disorganized', 'unfocused'], ['petasites', 'websites[change', 'multimedia'], ['petrie', 'charles', "petrie's", 'zion', 'substantiated', 'friend', 'also', 'society', 'number', 'new', 'head', 'periods', 'lost', 'painstaking', '’', 'century', 'often', 'standing', 'london'], ['petaras', 'society', 'phear', 'many', 'petards', 'surely', 'jacques', 'oriental', 'petara', 'samuel', 'straits'], ['petri', 'word', 'colleague', 'dish', 'dishes', 'm”', 'dates'], ['petasites', 'oral', 'days', 'influence', '2', 'three', 'mg'], ['petry', 'top', 'community', 'acquiesce', 'compassion', '’', 'insistent', 'delineates', 'includes', 'adept', 'produces', 'cruelly', 'exposes', 'biting', 'necessitates', 'play', 'willingness', 'single', 'also', 'affirming', 'lampoons', 'propel', 'certain'], ['1585', 'petrov', 'first'], ['1569', 'alkali-sulphurous', 'kyjovka', 'inhabitants', 'left', '1391', 'reservation', 'today', 'local', 'west', 'petrov', 'petr', '1987', 'above-ground', 'stream'], ['administrative', '30', 'mountains', 'petříkov', 'also'], ['cryptocurrency', 'disambiguation', 'vodou', 'surname', 'petr', 'petri'], ['relegation', 'avoid', 'began', 'two', 'manastirishte', 'start', 'petrov', 'game', 'finishing', 'conceding', 'senior', '2:1', 'switzerland', 'matches', '2', 'first', 'honours'], ['first', 'december', 'away', '20', 'season', 'allsvenskan', 'march', 'petrović', 'duration', 'expatriate', 'radnički', 'locomotive', 'lunar', 'östers', 'ff', 'time', 'swedish'], ['petri', 'businesswoman', 'ice', 'petrie', 'valentin', '1966', 'petry', 'writer', 'irène'], ['inhabitants', 'approximately'], ['geopedia'], ['2004', 'sospetto', 'zibetti', '1962', 'editore', 'petri', '1978', 'new', 'references', "miller's", 'directed', "d'argento", 'role', 'tindalo', 'due', '1981', 'milan', '1970', 'al', "d'or"]]
TOP TOKENS [['benin’s', 'benin'], ['benin'], ['benin', 'benin’s', 'evaluated'], ['benin', 'benin’s', 'evaluated'], ['benin', 'sep'], ['benin', 'south', 'weatherinbenin'], ['benin', "benin's", 'still', 'limestone'], ['benin', 'country', 'disengage', 'countries', 'results', 'improved', 'accompanying', '’', 'population'], ['benin', 'protestantism', 'million'], ['benin', "benin's"], ['benin'], ['benin', 'bénin'], ['benin', 'beninese', 'references'], ['benin', 'beninese', '9', '1'], ['benin', 'benin-burkina', 'benin-niger', 'institutions', "people's", 'recent'], ['benin'], ['benin', "benin's"], ['benin', 'combined'], ['benin'], ['benin', 'beninese']]
TOP TOKENS [['metrics', 'metric(s', 'metric'], ['metric(noun', 'metric'], ['metric', 'metrics', 'imagine', 'questions', 'deal', 'normally', 'resistance'], ['metrics', 'metric'], ['metrics', 'metric', 'question'], ['metrics', 'metric', 'behind', 'foundation'], ['metric', 'calculated'], ['metrics', 'metric', 'types'], ['metrics', 'metric', 'route', 'using'], ['metric', 'metricˈmɛ', 'quantification', 'metrical', 'name', 'real', 'rhythm', 'metricus', 'gr'], ['metric', 'metrics', 'string'], ['metric', 'metrics', 'selected'], ['metric', 'object', 'distance', 'learning', 'scalability', 'software'], ['metric', 'metrics'], ['metric', 'metrics'], ['metric', 'measure'], ['metric', 'quantifying', 'risk', 'something'], ['metric', 'spaces'], ['metrics', 'metric'], ['metric', 'non-metric']]
TOP TOKENS [['tryptophan', 'occur', 'acetaminophen', 'supplements', 'improve'], ['tryptophan', 'signals', 'quality', 'generally'], ['tryptophan', 'second', 'levels', 'small'], ['tryptophan-rich', 'tryptophan', 'ways', 'acid'], ['tryptophan'], ['tryptophan', 'aforementioned', 'sleep', 'addition', 'nutrient', 'triglycerides'], ['tryptophan', 'effects', 'acids', 'niacin', 'besides'], ['tryptophan', 'body', 'melatonin', 'additives'], ['tryptophan', 'doctor', 'liver'], ['tryptophan', 'rhythms', 'essence', 'turns', 'satiation', '—', 'trypo', 'weapon'], ['s.v', 'γραμματική', 'line', 'τρύφωνος'], ['tryphena', 'tryphaena', 'tryphosa'], ['wasp', 'play', 'tryphon', 'trypho', '1861–1934', 'turkestanov'], ['tryptophan', 'membrane', 'substituent', 'life', 'including', 'proteins', 'synthesize', 'brain'], ['trysa'], ['present', 'trypticase', 'trypsin', 'bacteria', 'chains', 'tryptone'], ['tryphonis', 'trypho'], ['aph-1', 'tryon', 'surname', 'creek'], ['tryphaena', 'turkey', 'died', 'τρύφαινα', 'apart', 'cyzicus'], ['tryptophan', 'trypt', 'tryptamine', 'acid', 'others', 'vivo', 'tryptamines', 'plants']]
TOP TOKENS [['spyware', 'webopedia.com', 'else'], ['spyware', 'http://www.microsoft.com/spyware', 'anti-spyware', 'download'], ['spyware', 'http://www.microsoft.com/spyware', 'anti-spyware', 'download'], ['spyware', '“spyware”', 'anti-spyware', '“anti-spyware”', 'performance'], ['spyware', 'spybot', 'find', 'installation', 'spy', 'finish', 'whether', 'vs', 'detected', 'running', 'helpful'], ['spyware', 'spybot', 'find', 'installation', 'spy', 'finish', 'whether', 'vs', 'detected', 'running', 'helpful'], ['spyware', 'mean', 'anti-spyware'], ['spyware', 'spyware-are', 'files', 'since', 'spy'], ['spyware'], ['spyware', 'spyware……', 'oversee', 'many', 'used'], ['spyker'], ['spyrock', 'spy', 'formerly', '5,832', 'east'], ['spyglass', 'spy', 'formerly'], ['spyfu', "spyfu's", 'question', 'markets', 'somewhat', '4-hour', '2005', 'dependent', 'based'], ['spyce'], ['spyeye', 'use', 'initiate', 'time', 'next', 'auto-fill', 'allows', 'compromised', 'transactions', "user's", 'emanated', 'config'], ['spycker', 'france', 'see'], ['spy', 'it:spy', 'following', 'hunter'], ['spymac', 'aforementioned', '2004', '2.0', "site's", 'outcry', 'transition', 'even', 'known', 'led', 'service'], ['spyhunter', 'spyware', 'also', 'custom', 'computer', 'usability', 'targeting', 'good', 'startup', 'release', "malwarebytes'software", 'stars', 'gave', 'fix']]
TOP TOKENS [['users', 'small', 'user', 'standard', 'models', 'metastatic', 'fixed', 'low', 'applications', 'semiautomated', 'platform', 'vivo', 'clinical', 'center', 'preclinical', 'interested', 'model', 'utilized', 'system', 'throughput', 'protocol', 'breast', 'institute', 'cells'], ['keeping', 'eye', 'informal', 'funky', 'types', 'specific', 'angle', 'people', 'audiences', 'traditional', 'environment'], ['born', 'designer', 'suit', 'babies', 'popular', 'match', 'perfect', 'baby', 'charlie', 'five', 'create', 'types', 'high', 'labelled', 'characteristics', 'term', 'choosing', 'whose', 'right', '–', '’', 'used', 'chance', 'disorder', 'possess', 'boy', 'jamie'], ['appearance', 'required', 'needing', 'used', 'brand', 'uses', 'made', 'however', 'use', 'logo'], ['profile', 'visitors', 'attractive', 'mole', '–', 'million', 'kept', "nature's", 'good-looking', 'received', 'species', 'cats', 'weird', 'cent', 'ugly', 'using', 'cuddly', 'giraffes', 'focus', 'unattractive', '5,334', 'found', 'panda', 'things', 'zoos'], ['version', 'profile', 'looks', "version's", 'esque', 'versions', 'redesigned', 'introduced', '1985', 'actually', "m150's", 'designed', 'fixture', 'identical', 'similar', 'shaped', 'taking', '1986', 'boxy', 'distinguish'], ['needed', 'cycle', 'required', 'doppelganger', 'something', 'conceive', 'doppelgangers', 'world', 'end', 'specific', 'service', 'going', 'falls', 'range', '–', 'cryogenics', 'job', 'used', 'community', 'digital'], ['revised', 'b', 'style', 'faces', 'life', 'extroverted', 'edition', 'trackers', 'dogs'], ['become'], ['commonly', 'popular', 'include', 'kept', 'primarily', 'animals', 'rabbits', 'two', 'appearances', 'crocodiles'], ['cycle', 'novel', 'designs', 'release', '0', 'study', "uberstudent's", 'specification', 'specific', 'reading', 'templates', 'continually', 'editions', 'application', 'uberstudent', 'lightweight', 'stability', 'intent', 'fits', 'format', '3', 'announced', '2', 'utilities', 'developers', 'behind', 'new', 'releases', 'designed', 'edition', 'invigorate', 'friendliness', 'traditional', 'intended', 'management'], ['styled', 'cover', 'aesthetics', 'formula', 'nature', 'type', 'glance', 'design', 'story', 'built', 'class', 'drivers', 'version', 'compact', 'sheet', 'rims', 'cyclekart', 'scale', 'simplified', 'resemble', 'driver', 'specification', 'purely', 'cylinder'], ['booklist', 'readers', 'college', 'novel', 'selection', 'published', 'dreams', 'guide', 'books', 'year', 'selected', 'review', 'young', 'novels', 'book', 'g.p', '2017', 'tells'], ['style', 'students', 'intended', 'use'], ['developmental', 'profile', 'unaltered', 'individuals', 'faces', 'used', 'class', 'changing', 'prototypical', 'individual', 'face', 'instance', 'consisting'], ['goes'], ['cohort', 'institutions', 'born', 'choosing', 'dates', 'groups', 'people', 'marketing', 'person', '1980', 'birth', 'generation', 'marketers', 'used', '1996', 'particular', 'u'], ['originally', 'intended', 'middle', 'season', 'premiere', 'appearance', 'pick', 'interns', 'introduced', 'million', 'decided'], ['1986', 'species', 'perennial'], ['season', 'qualifying', 'practice', 'qualify', 'reduced', 'beforehand', 'race', 'drove', 'drive']]
TOP TOKENS [['vijaya', 'numerous', 'deploy', 'pain'], ['vijayadasami', 'vijaya', 'vijay', 'mahisasura', 'means', 'injustice', 'thoughts', 'pride'], ['vijayanagar', 'vijaya', 'vijayawada', '‘', 'pradesh', 'kondapalli', 'cls'], ['vijayanagar', 'vijayanagara', 'also', 'kingdom', 'abounds', 'gardens', 'bazaars'], ['vijaya', 'vijayawada', 'cite_note-vijayawada.e2.80.99s_inclusive_expansion-1', 'india'], ['vijaya', 'effects', 'cramps', 'brain', 'says'], ['vijaya', 'srivijaya', 'jayavarman', 'bai', 'sema', 'likely', 'singhasari', 'ruled', 'majapahit', 'years', 'enshrined', 'spent', 'javanese', 'sanjaya', 'existence', 'first'], ['vijaya', 'vijayadasami', 'vijayadashami', '”', 'houses'], ['vijayadasami', 'vijayadashami', 'around', '“', 'mahisasura'], ['vijaya', 'vijayawada', 'pradesh', '1', 'road', 'vurimi', 'ad', 'late', 'also', 'hub', 'krishna'], ['vijaya', 'vijaya-bhattarika', 'vijayawada', 'vijaynagar', 'jaya-vijaya', 'vijay', 'vijayalakshmi'], ['vijaya', 'vijay', 'vijayan', 'disambiguation', 'salgaonkar'], ['vijaynagar', 'vijayanagara', 'vijayanagar', 'vijayanagaram', 'vijay', 'vijayapura', 'indore', 'aland'], ['vijaypal', 'vijay', '2004', '–', 'indian'], ['vijayapura', 'vijaypur', 'vijayapur', 'vijayapuram', 'vijay', 'vijayapuri', 'raghogarh-vijaypur'], ['vijayakumar', 'vijay'], ['vijaya', 'vijayanagar', 'serving', 'c', 'see', 'india'], ['vijaya', "vijaya's", 'vijayapura', 'champa', 'export'], ['vijayakumar', 'vijay'], ['vijaypur']]
TOP TOKENS [['parade', 'schutzenfest', 'parades', 'marching', 'bastille', 'illinois'], ['parade', 'parades', 'day', 'parades[change'], ['parade', 'schutzenfest', 'parades', 'balloons', 'floats', 'usual', 'kind', 'procession', 'shore', 'instead'], ['‘parade’', 'parade', 'parades', 'someone’s', 'procession', 'professionalism', 'another', 'fiesta'], ['parade', 'schutzenfest', 'parades', 'balloons', 'procession', 'kind', 'connotations', 'pride', 'cls', 'periodic', 'march', 'costume', 'marching'], ['parade', 'parades', 'balloons', 'procession', 'schutzenfest', 'paradesedit', 'marchers', 'kind', 'usual', 'connotations', 'floats', 'cls', 'within', "washington's", 'costume'], ['parade', 'day', 'victory', 'annual', 'paradesedit', 'stampede', 'roses', 'birthday'], ['parade', 'schutzenfest', 'parades', 'ii', 'annual'], ['parade', 'parades', 'every', 'procession', 'marching', 'float', '1868', 'cls'], ['parade', 'parades', 'procession', 'day'], ['parade', 'people', 'la', 'parades'], ['parade', 'called'], ['parade'], ['parade'], ['parade', "parade's", '1962', '1964', 'sedawie', 'early', 'performer', 'premise', 'performances', 'entertainers'], ['parade', 'north', 'inhabitants', '1808', "town's", 'name', 'came', 'union', 'direction'], ['koi-youbi', 'parade', 'film', 'song', 'parade"—"color', 'germany', 'ibifornia'], ['parade', 'style', 'version', 'album', '1995', "anniversary's", 'released', 'night', '2013', 'tracks'], ['parade', 'residence', 'costs', 'capital', 'tati', 'festivities', 'circus'], ['parade', 'song']]
TOP TOKENS [['light', '“', 'brought', 'shining', 'us', 'gives', 'world'], ["christ's", "world's", 'light', 'shining'], ['jesus--the', 'light', 'light--jesus--so', 'brings', 'lives--the', 'brought'], ['light', 'masquerading', 'god'], ['light', 'lights'], ['light', 'let', '”', 'hath'], ['light', 'let', '”', 'hath'], ['light', 'lights', 'let', 'lamp', '‘', 'spiritually'], ['light', '“', 'shines'], ['light', "allah's"], ['light', 'la'], ['light', 'rattner', 'episode', 'film', '1998', '2017', 'story', '2019', '1:3', 'huston', '2007', 'let'], ['light', 'divine', 'illuminatio'], ['light', 'lighteth', 'century', 'christ', 'world'], ['light', 'lux', 'means', 'biblical', '’ôr', 'let', 'latina', 'also', 'γίγνομαι', '–', 'γενηθήτω'], ['light', 'verse:he', 'people', 'lamp', "god's", 'allah', 'lights', 'quran', 'religion', 'mulla', 'god', "qur'an"], ['light', 'proclaims', 'god', 'buddhas', 'judaism', 'shines', 'truth', 'term'], ['light', 'patristics', 'ray', 'scriptures', 'identify', 'luminous', 'christianity', 'lighting'], ['light', 'lights', 'view', 'god', 'denote'], ['light', 'also', 'interpretations', 'sun']]
TOP TOKENS [['every', 'get', 'second', 'next', 'simply', 'go', 'number', 'full'], ['accumulator', 'values', 'say', 'expect', 'accumulators'], ['phi(m,n', 'a*2', '16#16', 'a+a', 'values', '1', 'm==n', 'm+n', 'four', 'i.e', 'either', 'different'], ['one', "there's", 'value', 'results', 'accumulator', 'acc', 'sum', 'left', 'needed'], ['element', '“', 'function', 'horse', 'b', 'fine', 'e', '’'], ['1', 'instance', 'one', 'tangle', '’', 'rest', 'go', 'multiplications', 'let', 'particular', 'matter', 'rhs', 'right', '–', 'b', 'points', 'know'], ['1', 'instance', 'one', 'tangle', '’', 'rest', 'go', 'multiplications', 'let', 'particular', 'matter', 'rhs', 'right', '–', 'b', 'points', 'know'], ['foldr1'], ['001001001', 'two', 'follows', '110', '011011011', 'turn', '611260467', '010010010', '110110110', 'example', '001', 'corresponding', '188255099'], ['reevaluated', 'specified', 'entries', 'looping', 'reevaluates', 'except'], ['binomial', 'n', '–', 'links', 'vol', 'reading', 'factorial', '3', 'guy', 'transform'], ['128', '1', '0', 'sign', '324', '10', '400', '692', 'inverse', '63', '8', 'noninvolutive', '528', 'binomial', '1n2', '1485', 'applying', '900', 'involution'], ['finds', 'permutation', '–', 'efficient', 'permutations'], ['follows', 'said', 'makes', 'calculating', 'mathematically', 'according', 'respect', 'namely', 'since', 'respective', 'onto', 'interval'], ['product', 'codomain', 'universal', 'set', 'cardinal', 'indexing', 'result', 'operation', 'e'], ['transform', 'values', '—'], ['values'], ['equivalently', '–', 'specialize', 'also', 'according', 'concretely', 'formula', 'values', '2', 'see'], ['rungekstep', 'references', 'also', '–', 'rungeknystroemsstep', 'mcs033', '17', 'maths', 'external', 'kutta', '6', 'list', 'runge', '（', 'notes'], ['gives', 'fixes', 'points', 'equivalently', 'values', 'since']]
TOP TOKENS [['foia', 'requests', 'request', 'c'], ['foia', 'request'], ['foia', 'request', "nro's"], ['foia', 'requests', 'request', 'time'], ['foia', 'requests', 'requester', 'request'], ['foia', 'request', 'u'], ['foia'], ['foia', '“', 'public', 'requests', '”', 'submitting', '’', 'us'], ['foia', 'requester', 'request', 'requesters'], ['foia', 'www'], ['foia', 'fóia'], ['foia', 'requests', 'request', '1997', 'found', 'requester', 'respond'], ['foia', 'request', 'found', 'government', "public's"], ['foia', 'request', 'requests', 'considered', 'effective', 'act', '1129', 'profit', 'december'], ['foia', 'u', 'recent', 'responses', 'cls', 'additionally', 'specifically', 'statute'], ['foia', 'capricious', 'request', 'requests', 'legislative', 'u', 'expressly', 'individuals', 'act'], ['foia', 'requests', 'request', 'deadlines', 'comply'], ['foia', 'request', 'requests'], ['foia', 'requests', 'law', 'requesters', 'implemented', 'amend', 'ignoring', 'starting'], ['foia', 'requests', '5', 'request', 'act', 'companies', 'one', 'would']]
TOP TOKENS [['pooh', "pooh's", "milne's", 'winnie', 'milne'], ['pooh', 'pooh’s', 'milne', 'winnie-the-pooh', 'winnie', 'milne’s', 'a.a', 'winniethepoohday'], ['pooh', 'milne', 'winnie'], ['pooh', 'winnie', 'poohsticks', 'milne'], ['pooh', 'winnie', 'milne', "milne's"], ['pooh', 'winnie', 'milne', "milne's"], ['pooh', 'winnie', 'milne'], ['pooh', 'winnie-the-pooh', "pooh's", "winnie-the-pooh's", "milne's", 'milne'], ['“pooh”', 'pooh', 'pooh’s', 'winnie-the-pooh', 'winnie', 'milne', 'milne’s', 'milnes', 'a.a', 'he’d'], ['pooh', 'winnie', 'milnes', 'milne', 'plush'], ['pooh', 'milne', 'winnie', "pooh's", "milne's", 'poohsticks'], ['pooh', 'milne', "milne's", 'winnie', 'e', 'world'], ['pooh', 'winnie', "milne's", 'milne'], ["milne's", 'pooh', 'milne', 'winnie-the-pooh', 'winnie', 'poohsticks'], ['pooh', 'milne', "milne's", 'winnie', 'adaptations'], ['pooh', 'winnie', 'milne'], ['pooh', 'winnie', "milne's", 'milne', '1931'], ['pooh', "pooh's", "milne's", 'milne', 'winnie', 'fact', 'panel', 'kanga'], ['pooh', 'winnie', 'milne', "milnes'invention", "milne's"], ['winnie', 'winnie-the-pooh', 'milne', 'a.a', 'pooh', 'japanese', 'pooh-man', 'world']]

Processing features:  47%|████▋     | 46/98 [22:00<24:18, 28.06s/it]

getting sample prompt forgetting sample prompt for 23953
 23952
getting sample prompt for 23954
getting sample prompt for 23955
getting sample prompt for 23956
getting sample prompt for 23957
getting sample prompt for 23958
getting sample prompt for 23959
getting sample prompt for 23960
getting sample prompt for 23961
getting sample prompt for 23962
getting sample prompt for 23963
TOP TOKENS [['midway', 'prominent', "john's", 'interrelated', 'much', 'st', 'gallery'], ['midway', 'prominent', "john's", 'interrelated', 'much', 'st', 'gallery'], ['midway', 'uss', '1955'], ['midway', 'ocean', 'looms', '1988'], ['midway', '“midway', 'midway’s', 'midwaytoday'], ['midway', 'uss', 'country', 'battle', '238', '34'], ['midway', 'land', 'visiting', 'piece', 'trip'], ['midway(adj', 'midway', 'midway(adverb', 'word', 'middle'], ['midway'], ['midway', 'island', 'imported', 'also', 'known', '00:17:17', 'however'], ['midway', 'disambiguation', 'el'], ['midway'], ['midway'], ['midway', 'milton', 'navarre', 'u.s', 'intracoastal', 'often', 'category', 'populated'], ['midway'], ['midway'], ['midway'], ['109', 'midway'], ['states', 'united', 'midway'], []]
TOP TOKENS [['canola', 'applied', '522', '10', 'drier', 'per', '1', 'also', 'growers', 'adequate'], ['canola-specific', 'canola', '2012', 'high'], ['canola'], ['canola', 'problems', '6', 'change', 'per', 'along'], ['canola', "canola's", 'less', 'round'], ['canola', '5'], ['canola', 'quality', 'producing', 'food'], ['canola', 'clear'], ['canola', 'late', '90', 'mm', 'two'], ['canola', '0', 'one', '7', '05'], ['canola'], ['dongola', 'sudan'], ['zola', 'zolas', 'film', 'zolaism', 'planner', 'greek', 'major', 'jesus', 'moth', 'writer'], ['parola-class', 'parola', 'cay'], ['casola', 'cassola'], ['genola'], ['piola', '1666–1724', 'milan', 'italy'], ['meola', '1969'], ['cassola', 'casola', 'italian', 'arnold'], ['payola', 'disambiguation', 'paola']]
TOP TOKENS [['chance', 'things', 'ground', 'alive', 'marker', 'what’s', 'makers', 'cent', 'staking', 'pole', 'well', 'support', 'stake', 'plants', 'boundaries', '1,600'], ['stake', 'stakes', 'staked', 'staking', 'protocol', 'tokens', 'mining'], ['stake', 'staking', 'stakes', 'form', 'sturdy', 'proper', 'drive', 'straight'], ['stake', 'staking', 'encyc', 'driving', 'stakes', 'staked', 'stakehead'], ['stake', 'stakes', 'staking', 'deep', 'staked', 'pound', 'putting', 'push'], ['stake', 'staking', 'use'], ['stake', 'around', 'stakes', 'staked', 'staking', 'conspicuous', 'placing', 'guidelines'], ['stake', 'staked', 'staking'], ['staked', 'stake', 'stakes'], ['ceilings', 'overcome', 'places', 'game', 'health', 'stake', 'instantly'], ['torture', '1951', "archer's", 'stake', 'manufacturing', 'staking', 'saints', 'crucifixion', '1977', 'disambiguation', 'steel', 'miniseries'], ['stake'], ['stakes', 'metal'], ['rights', '2019', 'alabama'], ['1838', '3', 'stake', 'thy', 'president', 'stakes', 'lengthen', 'cords', 'july', 'additional', 'thine', 'later', '1836', 'new', 'wards', 'cls'], ['stake', 'distinction', 'years'], ['stake', 'overwhelmingly', 'received', 'sunn', 'name'], ["archer's", 'foot', 'stakes', 'stake', 'j', 'archers', '1415', 'campaign', 'used', 'war', '1976'], ['anggraini', 'even', 'bank', 'stake', 'though', 'parengkuan', 'cls', 'giulio', 'could', 'lost', 'day', 'simply', '18', 'ical', '2017', 'occurred', "father's"], ['boys', 'film', 'stakes', 'series']]
TOP TOKENS [['movement', 'moving', 'moves', 'motion'], ['motion', 'movement', 'defines', 'describing', 'clearly', 'term'], ['motion', 'moves', "motion'has", "term'absolute", 'movement', 'displacement', 'trajectory', 'motions', 'laws', 'rectilinear', 'types', 'description'], ['motion', 'move', 'moves', 'types', 'moving', 'line'], ['movement', 'motion', 'motions', 'move', 'thing', 'fact', 'moving', 'concept'], ['motion', 'motions', 'term', 'immobile', 'speed', 'point', 'velocity', 'position'], ['motion', 'movement', 'movementˈmuv', 'move', 'word', 'reflex', 'drift', 'apparent', 'trend', 'moving', 'motility', 'drive', 'self'], ['motion', 'movement', 'reflex', 'move', 'moving', '11', 'motility', 'apparent', '2', '7', 'object'], ['movement', 'move', 'motion', 'moving', 'motions'], ['motion', 'move—like', 'art', 'pitch', 'move', 'appearing'], ['movement', 'move', 'self-motion', 'motion', 'motions', 'locomotion', 'live', 'government', 'calvin', 'perpetual', 'type'], ['movement', 'motion', 'move'], ['motion', 'move', 'movement', 'system', 'motor', 'also', 'fulda', 'syntactic', '9mm'], ['motion', 'self-motion'], ['movement', 'motion', 'moving'], ['motion', 'movement', 'motions', 'moving', 'consider', 'bodily', 'cause'], ['movement'], ['movement'], ['motions', 'motion', 'term', 'role', 'called'], ['movement', 'movements', 'motion', "body's", 'moving']]
TOP TOKENS [['pass', "mother's", 'body'], ['aβ', 'deviation', 'eds', '1', '005', 'brain', 'later', '091', '033', '±standard', '2', '95', '73', 'e', '0', '7', 'napped'], ['viviparous', 'fetuses', 'viviparity', 'species', 'kingdom', 'young', 'instances'], ['viviparity', "mother's", 'ovoviviparous', 'oviparous'], ['oviparous', 'paws', 'ovoviviparous', 'bipedal', 'tiny', 'cnidarians', 'immature', 'move', 'young', 'maturity', 'may', 'led', 'snake', 'invertebrate', 'female', 'shrub', '…', 'sponges', '15', 'march', 'flatworms', 'case', 'almost', 'placozoa'], ['triumph', 'proponents', 'reforms', 'vivir', 'nature', 'turned', 'led', 'bien', 'visions', 'development', 'controversies', 'attention', 'jurisprudence', 'generating', 'stage', 'came', 'however', 'vision', 'hopes', 'like', 'another', 'pass', 'still', 'one', 'disputes', 'internationally', 'actuality', 'sharper', 'countries'], ['viviparous', 'ovoviviparous', 'oviparous', 'one', 'young', 'body', 'eggs', 'less', 'parent', 'sep'], ['body', 'ovoviviparous', 'young', 'internally', 'oviparous', 'bodies', 'viviparous', 'externally', 'becomes', 'eggs', 'become', 'snakes', 'amphibians', 'animals', 'sharks'], ['oviparous', 'viviparity', 'hemotrophic', 'marsupium', 'amphibians', 'ovoviviparous', 'oviparity', 'ventral', 'insects', 'pagenstecheri', 'sac', 'mother', 'fertilization', 'parents', 'body', 'monotremes', 'molluscs'], ['ovoviviparos', 'mouse', 'viviparous', 'womb', 'reproduces', 'oviparous', 'egg', 'sexually', 'turn', 'body', 'develop', 'developed', 'reproduce', 'things', 'pregnant', 'viper', 'differ', 'environment', 'pigeons', 'cases', 'organs', 'example', 'whose', 'becomes', 'baby', 'depends', 'humans', 'latter'], ['”seasons', '1997'], ['dance', 'pop', 'months', 'music', 'decks', 'artists', '1987', 'songwriter'], [], ['folk-singer-songwriter', 'singer-songwriter', 'write', 'stories', 'indie-pop', 'reverb', 'sings', 'year', 'tour', 'young', 'chart', 'musically', 'magazine', '4.5', 'person', 'beware', 'sweeps', 'work', 'make', 'overall', 'debut', 'adding', 'life', 'people', 'ep', '2014', 'comparison', 'australia', '5', 'rather', 'perfection', 'attention'], ['newspaper', 'vice', 'president'], ['coelom', 'anterior', 'posterior', 'organs', 'duplication', 'california', 'reported', 'segmentation', 'consist', 'bay', 'america', 'worm', 'midwater'], ['adolescents', 'music', 'management', 'rich', 'song', 'plural', 'amoeba', 'defense', 'album', 'buggin', 'band', 'single-celled', 'genus'], ['monica', 'breath', 'april', 'toby', 'west', 'booklet', 'dammit', 'demo', 'flown', 'recorder', 'version', 'annwyn', 'acoustic', 'cassandra', 'mercyground', 'proud', 'ginger', 'ave', 'angler', 'violin', 'jeremy', 'wisperthal', 'jim', 'ramon', 'percussion', 'angeles', 'traycard', 'ocean', 'gent', 'unquiet', 'original', 'kipnis', 'sea', "rhea's", 'demos', 'mastering', '—', 'cls', 'guitars', 'e'], [], ['transferred', 'evans', 'mabille', 'mielke', 'natural', '1955', '1898', '1900', '1980']]
TOP TOKENS [['prescribed', 'burning', 'burn'], ['prescribed'], ['prescribed'], ['prescribed', 'use', '‘controlled'], ['prescribed'], ['prescribed', 'cls', 'prescription', 'practitioners', 'burn', 'burner', 'trained', 'permit'], ['prescribed', 'controlled', 'approved', 'personnel', 'burn', 'cls', 'burning', 'planned'], ['prescribed', 'prescription', 'burn', 'appropriate'], ['prescribed', 'controlled', 'burning', 'burn', 'experts', 'fire'], ['prescribed', 'use', 'general', 'cls', 'regime'], ['prescribed', 'burning', 'practices', 'incorporated', 'controlled', 'pyriscent', 'permits', 'use', 'burn', 'burns', 'conducted', 'used', 'fires', 'natural', 'ignited', 'fire', 'set', 'regulations', 'flammable', 'intentional', 'slowly', 'enacted', 'foresters', 'control', 'hotter', 'authorities', 'abatement', 'catastrophic', 'management'], ['prescribed', 'burning', 'recommendation', 'burns', 'burn', 'blame', 'burnt', 'experts', 'unplanned', 'conducted', 'fires'], ['prescribed', 'application', 'administered', 'burns', 'controlled', 'burning', 'regimes', 'fire', 'regime', 'burn', 'use', 'treatments', 'management', 'even'], ['prescribed', 'controlled', 'burning', 'burns', 'fire', '10', '02'], ['prescribed', 'burning', 'controlled', 'burns', 'burn', 'controllable', 'fire'], ['prescribed', 'controlled', 'fire', 'burns', 'practice', 'administered', 'supported', 'burning', 'burn', 'procedure', 'fires', 'tend'], ['prescribed', 'practice', 'burning', 'burn', 'protocols', 'controlled', 'burns', 'perform', 'surrounding'], ['burn', 'burning', 'fires'], ['burn', 'practice', 'conduct', 'practitioners', 'scheduled', 'burns', 'burning', 'practices'], ['controlled', 'burns', 'burn', 'prescribed', 'fires', 'consumed', 'conditions', 'fire', 'directives', 'allow', 'allowed', 'unhindered']]
TOP TOKENS [['chavez', "chavez's", 'cso', 'efforts', 'fabela'], ['chávez’', 'chávez', 'chávez”', 'césar'], ['chavez', 'chávez', 'cesar'], ['chavez', "chavez's", 'cesar'], ['chavez', 'cesar'], ["chavez's", 'chavez', 'cesar', 'e', 'davis'], ['chavez', "chavez's", 'later', 'librado'], ['chavez', 'cesar', 'estrada', '31', '5', 'ufw', '4'], ['chavez', 'cesar'], ['chavez', 'cesar'], ['chávez', 'chavez', 'césar', 'cesar'], ['chavez', 'cesar', '2024', 'born', 'meza', 'senate'], ['chavez', 'chavez/67th', 'chávez', 'cesar'], ['chavez', 'cesar'], ['chavez', '23', 'tomateros', 'california'], ['chavez', 'references', 'cesar'], ['chavez', 'cesar', '1970s', 'cso', 'estrada', "cso's", 'cesario'], ['chavez', 'cesar'], ["chavez's"], ['chavez', 'cesar']]
TOP TOKENS [['coaxial'], ['coaxial'], ['coaxial', 'coaxially', 'coax', "80's", '“'], ['coaxial', 'tolerances'], ['coaxial'], ['coaxial', 'unfortunately'], ['coaxial', 'coax'], ['coaxial'], ['coaxial', 'cable', 'polyethylene', 'types', 'coax'], ['coaxial'], ['coaxial'], ['coaxial'], ['coaxial'], ['coaxial'], ['coaxial', 'coax', 'aerodynamics', 'kamov', 'manzolini', '1997', 'dorand'], ['coaxial', 'coax', 'since', 'connectors', 'cable'], ['coaxial', 'connectors', 'repeaters', '1880', 'axis', 'turn', 'radio', 'term', 'shield', 'specialized', 'cable', 'give', 'spacing', 'antennas'], ['coaxial', 'makes', 'signaling', 'magnetic', 'dielectric', 'radiate', 'quality', 'capability'], ['coaxial', 'rotation', 'rotors', 'arise', 'force', 'blades'], ['coaxial', 'coax', '−13', 'ω', 'may', 'via', 'radio', 'cables', 'connectors', 'cabling', 'chain']]
TOP TOKENS [['’', 'inequalities', 'disproportionately', 'hia', 'level', 'population', 'health', 'process', 'affected', 'unintended', 'degree', 'wellbeing', 'identified', 'equity', 'focused', 'implementation'], ['”', 'hia', 'people', 'matter', '“', 'planners', 'order', 'impacts', 'programme', 'time', 'paper', 'population', 'may', 'facilitate', 'according', 'immediately', 'words', 'else', 'policy', 'program', 'affected', 'takes'], ['1999', 'hia', 'europe'], ['inequalities', 'health', 'proposal', 'local', 'policies', 'regional', 'however', 'provide', 'least', 'hia', 'within', 'valuable', 'levels', 'provides', 'provided'], ['inequities', 'unnecessarily', 'g', '’', 'hiap', 'health', 'prioritized', 'hia', 'perpetuating', 'council', 'town', 'real', 'may', 'around', 'impact', 'derived', 'policies', 'equity', 'using', 'receive', 'disparities', 'example', 'well', 'advocates', 'disease'], ['interest', 'significantly', 'first', '5', 'hia', 'squarely', 'effects', "health'is", 'outcomes', 'within', 'third', '3', 'things', 'must', 'second', 'even', 'several', 'ascertain', 'becomes', 'course'], ['squarely', 'prospectively', 'goals', 'outcomes', 'either', '2', 'otherwise', 'preferable', 'giving', 'comprehensively', 'health', 'effects', 'framework', 'proposal', 'decisions', 'projects', 'evidence', 'groups', 'unknown', 'disparities', "health'is", 'unexpected', 'field', 'several', 'including'], ['people', 'health', 'hia', 'effects'], ['assuring', 'inequities', 'e', 'often', 'health', 'g', 'determine', 'policies', 'quality', 'several', 'matter', 'includes', 'exposure', 'policy', 'beyond', 'tools', 'services', 'resources', 'past', 'fluoridation', 'made'], ['inequitable', 'including', 'hiap', 'respective', '—', 'order', 'policymaking', 'role'], ['health', 'association', 'jan', 'hiap', 'policies', 'washington', 'partners', 'challenges', 'experiences', 'projects', 'made', 'web', 'life', 'equity', '1987', 'humanimpact', 'main', 'en', 'ec'], ['rationale', 'education', 'benefits', 'forward', 'routinely', 'made', 'carried', 'governments', 'health', 'consider', '1986', "health's", 'acknowledgment', 'including', 'articulated', 'embedded', 'broader'], ['especially', 'hias', 'many', 'health', 'however', 'making', "hia's", 'population', 'constraints', 'program', 'overview', 'magnitude', 'assessment', 'also', 'order', 'though', 'nature', 'listed', 'impacts', 'made', 'seeks', 'contexts', 'usually'], ['health', 'impacts', 'project', 'help', 'like', 'decisions', 'equity', 'finland', 'government', 'provides', 'making', 'synergies', 'promotion', '1972', 'involved', 'obligations'], ['underpins', 'focus', 'social'], ['hia', 'outcomes', "makers'attention", "policy's"], ['departments', 'report', 'framework'], ['impact', 'health', 'alliance', 'british', 'islands', 'hia', 'plans', 'associate', 'initiative', 'herzberg', "women's", 'magazine', 'northern', 'americas', 'association'], ['health'], []]
TOP TOKENS [['figs', 'al', '11a', 'recirculation', '0', 'regime', 'extent', 'velocities', 'g', 'sheltering', '13a', 'level', '12a', 'one'], ['discharges', 'voiding', 'without', 'chamber', 'empties', 'rises', 'usage'], ['pipelines', 'balances', 'discharges', 'either', 'nevertheless', 'analysed', 'view', 'may', 'placed', 'related'], ['increases', '0', 'widths', 'without', 'discharges', 'accumulates', 'non', 'percentages', '5', 'experiments', '3'], ['especially', 'area', '0', 'thus', 'curb', 'm2'], ['includes', 'arrangement', '4'], ['exist', 'g', 'attains', 'e', 'abstractions', 'storage', 'ponding', '4', 'well', '0', 'latter', 'may', 'close'], ['go', 'fig', '6', '9', 'instance', 'comes', 'ledges', '3'], ['sump', 'sumps', 'water', 'pipes', 'however', 'hydraulically', 'result'], ['inlets', "waste's", 'chamber', 'venting', 'pipe', 'velocity'], ['either', 'layer', 'soil'], ['hydrology', 'system', 'model', 'systems', 'water', 'service', 'links'], ['sewers', 'manhole', 'way', 'location', 'ways', 'laterally', 'laid', 'water'], ['sump', 'sumps', 'may', 'predictable', 'vehicle', 'one', 'filter', 'system'], ['figure', 'bins', "slug'of", '1', 'slugs', "this'falling", 'odes', 'employed', 'furthermore', 'following', 'necessitates', 'detaches', 'occurs', 'infiltrates', 'reference', 'essentials'], ['flow', 'h2', 'spillways', 'spillway', 'method', 'discharges', 'coefficients'], ['moghadam', 'h', 'nodoshan', 'barati', 'conditions', 'shahheydari', '11', 'however', 'flow', 'dissipation'], ['line'], ['go', 'pipe', "ground's", 'water', 'order', 'allowing', 'level', 'manholes', 'manhole'], ['input', 'abstraction', 'puddles', 'adjacent', 'equation', 'components', 'one', 'runoff', 'evapotranspiration', 'output', 'transpiration', "richards'equation", 'budget', 'expensive', 'computationally', 'infiltration', 'etc', 'method', 'well']]
TOP TOKENS [['actual', 'structures', '–', 'activities'], ['unk', '，', '、', '的'], ['03', 'empire', 'com', '30', '02', 'joystiq', 'report', 'gamesetwatch', 'wired', '09', '01', '18', 'gamasutra', '14', 'arstechnica', 'retrieved', '11', 'gamesarefun', 'nytimes', '12', '21'], ['congressmen', 'much', 'exaggerate', 'average'], ['muchos', 'interesante', 'el', '’', 'spotlightonchile', 'panhco', 'es', 'also', 'chicken', 'arm', 'well'], ['especially', 'good', 'shredded', 'heartedly', 'covers', 'tatewaki', 'though', 'gets', 'upon', 'landing', 'buffs', 'worsening', 'various', 'anime', 'help', 'ridiculous', 'around', 'filled'], ['cd'], ['”', 'opinion', 'however', 'socialistic'], ['jubilaumswochenende', 'zum', '20', 'german', 'im', 'vom', 'pp', 'eisenbahnen', '2008', 'lauter', '–', '21'], ['professional', 'services', 'church', 'care'], ['nxne', 'nxnw', 'mi', '2', '3', 'exse', '10', '8', 'nd', 'n', 'ne', '16', '4'], [], ['garland', 'american', 'austin', 'newport', 'people'], ['however', 'tochigi', 'cases'], ['official', 'along', 'foot-tapping', 'testament', 'anthems', 'talkshoplive', 'authentic', 'pumped', 'similar', 'put', 'time', 'gratification', 'release', 'cds', 'upper', 'list', '2012'], ['received', 'critical', '3', '2', '9', '1', 'e', 'direction', '–', 'dinosaur', '7', '—', 'gave', 'n', 'concluded', 'music', 'breaching', 'ultimately', 'would', 'also', 'johnny', 'stating'], ['surveillance', 'including', 'terrains', 'compass', 'missiles', 'aircraft'], ['153', 'marv', 'portland', 'disestablishments', 'musical', 'books', 'single'], ['addition', 'together', 'also', 'platforming', 'achieve', 'several', 'order', 'due', 'monotonous', 'thus', 'circumnavigates', "series'initial", "character's"], ['breasts', 'dallas', 'along', 'extraordinarily', "that's", "duo's", 'services', 'local', '100', 'texas', 'mustaches', 'talk', 'stations', 'percent', 'unique', 'year', 'show', 'mix', 'said']]
TOP TOKENS [['land', 'past', '…', 'within', 'poland', 'lifted', 'active', 'admonition', 'austria', 'weltsturm', 'year', 'nothing', 'make', 'vitality', 'office', 'little', 'poles', 'lorraine'], ['birth', "what's", 'really', 'filled', 'tasty', 'small', 'right', 'created', 'bit'], ['u', 'upon', 'us', 'let'], ['birth', "what's", '10', 'small', 'today', 'tasty', 'right', 'bit', 'created'], ['158', 'exaltation', 'exceedingly', 'great', 'servants', 'ardor', 'intolerable', 'old', '’', 'small', 'relations', 'also'], ['editing', 'ph', 'loop', 'obvious', 'things', 'a€syes', 'brings', 'sometimes', 'know', 'deadlines', 'well', 'doesna€™t', 'whenever', 'a€t', 'research', 'paper', 'available', 'onea€™s', 'specializes'], ['civilization', 'society', 'existed', 'else', 'produce', 'engineering', 'richer', 'mars', 'nasa', 'find', 'definitive'], ['twain', 'company', 'ride', 'foremost', 'knowledge', 'rich', 'steps', 'forward', 'change', 'reality', 'equipping', 'deliverables', 'insights', 'team', 'relationships', 'darwin', 'einstein', 'edison', 'outsider', 'ideas', 'repeatedly', 'outlining', 'empowering', 'visionaries', 'offer'], ['ring', 'power', 'commitment', 'com', 'sndgems', 'may', 'find', 'world'], ['ad', 'supra', 'arunhaba', 'essential', 'fund', 'nov'], ['way', 'ha', 'every', 'fashion', 'hours', 'appears', 'real', 'nice', 'one', 'well', 'quite'], [], ['suited', 'speak', 'well', 'got', 'getting', 'gradually', 'centred', 'undoubted', 'put', 'thing', 'hitherto', 'one'], ['makes', '2004', '293', 'brings', 'alone', 'others', 'occur', 'brothels'], [], [], [], ['idea', 'sleeve', 'requisite', 'turns', 'fitting', 'imperative', 'armature', "enormous'apart'—"], ['humanity', 'f', 'j', 'exultation', 'apt', 'per', 'se'], ['annotated', 'barnes', 'benjamin', 'b', 'albion', 'w', 'g', '1965', 'experience', 'pope', '1971', '1972', '1959', 'sea']]

Processing features:  48%|████▊     | 47/98 [22:30<24:19, 28.62s/it]

getting sample prompt forgetting sample prompt for 23965
 23964
getting sample prompt for 23966
getting sample prompt for 23967
getting sample prompt for 23968
getting sample prompt for 23969
getting sample prompt for 23970
getting sample prompt for 23971
getting sample prompt for 23972
getting sample prompt for 23973
getting sample prompt for 23974
getting sample prompt for 23975
TOP TOKENS [['aure', 'møre'], ['auden', 'spiritual', 'refused', 'auden’s', '1973', 'wide', 'ezra', 'socially', 'doc', 'pound', 'revival', 'poetry', 'apparent'], ['auden', 'actually', 'several', 'plays', '’', 'natural', 'pr', 'typical', 'mentality', 'already', 'verse', 'young', 'thorough', 'noted', 'strive', 'readership', 'harbinger', 'attempts', 'man'], ['auden', 'consciously', 'pr', 'actually', '’', 'person', 'away', 'far', 'typical', 'heartfelt', 'several', 'sexual', 'open', 'plays', 'natural', 'agree', 'freudianism', 'already', 'aware', 'diagnose', 'vindictive', 'injustice', 'verse', 'bound', 'response', 'noted', 'joseph'], ['aurutils', 'aur', 'using', 'use', 'auracle', 'may', 'install'], ['aurea', 'soon', 'decided', 'st', 'woman'], ['auden', 'poet', '’', 'new', 'even', 'yet', 'context', 'scholar', 'proclaim', 'prescient', 'suddenly', 'attacks'], ['aureoli', 'aureolus', '1345', 'aublic', '1319', '“repercussorium”', 'toulouse', '1314', 'paris', 'xxii', 'rome', 'd’auriol', 'points', '1596-1605', 'john', 'commentary', 'province', 'philosophy', '“sermons”'], ['aubrieta', 'aubriet', 'europe', 'wall', 'plant', 'footprint'], ['auris', 'c', 'infection', 'genome', 'whole', 'sequencing', 'southern'], ['audel', 'victor', 'expatriate', "men's", '2017', 'sportspeople', 'mnk', '1', 'town'], ['39'], ['auri'], ['fever', 'aurum'], ['1921–2013'], ['aulakh', 'jind'], ['aurelin', 'poland'], ['aulin'], ['auken', 'kirsten'], ['india']]
TOP TOKENS [['indicators', 'indicator', 'activity', 'outputs', 'intermediate', 'program', 'type', 'generated', 'provided'], ['indicator', 'indicators', 'directional', 'towards', 'specific', 'summarizing', 'flow', 'goals', 'defined', 'effect', 'etc'], ['indicators', 'number', 'values', 'initiatives', 'thus', 'long', 'proactive', 'results', 'methodologies', 'also', 'legitimise', 'overall', 'many', 'often'], ['indicators', 'indicator', 'type', 'useful', 'types', 'measure', 'caused', 'related', 'great', 'selecting', 'however', 'difference'], ['indicators', 'indicator', 'reliable', 'cooperation', 'education', 'realities', 'create', 'helps', 'words'], ['indicators', 'indicator'], ['indicators'], ['indicators', 'indicator', 'relates', 'include', 'reached'], ['indicator', 'indicators', 'trend', 'key', 'direction', 'measurement', 'context', 'occurs', 'benefits'], ['indicators', 'indicator', 'point', 'also', '6401c09', 'change', 'better', '2', 'see'], ['indicator', 'level', 'complexometric', 'cls', 'value', 'water', 'exceeded', 'conditions', 'old', 'macroeconomic', 'honeyguides', 'indicators', 'engine', 'species', 'honeyguide', 'known', 'estimate', 'samples', 'world'], ['indicators', 'indicator', 'available', 'environmental', "institute's", 'environment', '3', 'seen', 'like', 'prominent', 'phenomenon'], ['indicator', 'indicators', 'main', 'change', 'organizations', 'index'], ['indicator', 'indicators', 'bankruptcies', 'reports', 'statistics', 'rate', 'cycles', 'activity', 'leading', 'principal', 'performance', 'bureau', 'economic', 'conditions', 'cls', 'allow', 'gross'], ['indicator', 'term', 'student', 'use'], ['indicators', 'indicator', 'validity', 'population', 'feed', 'feasibly', 'typically', 'generalize', 'time', 'sustain', 'result', 'year', 'exclusive', 'number', 'make'], ['indicators', 'indicator', 'environment', 'biodiversity', 'systems', 'types', 'used', 'variety', 'terms', 'created', 'since', 'play'], ['indicators', 'embraced', 'three', 'history', 'declining', 'journal', 'forms', 'cls', 'first', 'typically', 'information', 'goals', 'essence', 'money', 'outcomes', 'predominantly', 'transactions'], ['indicators', 'indicator', 'time', 'issues', 'system', 'depletion', 'health', 'environmental', 'environment', 'good', 'respect', 'measurements', 'enable', 'quantitative', 'regional'], ['indicators', 'macroeconomic', 'category:macroeconomic']]
TOP TOKENS [['byod', 'cls', 'wherever', 'might', 'actually', 'education'], ['byod', 'recently', 'bandwagon', 'onto'], ['byod', 'gt', 'yr', 'etc', 'e.g', 'supply', 'also', 'id'], ['byod', 'wiped'], ['byod', "byod's", '3', 'implementing', 'students'], ['byod', "byod's", '3', 'implementing', 'students'], ['byod', 'use', 'key'], ['byod', 'fairly', 'office', 'cls', 'simple', 'well'], ['byod', 'cls', 'important', 'industry', 'suit'], ['byod', 'helpful', 'successful', 'time', 'everything', 'assembled'], ['jpod'], ['detail', 'clods', 'clod', 'disambiguation', 'cloud', 'beef', 'nella'], ['marco', 'disambiguation', 'crucifix', 'rood'], ['series', 'tripod', 'device', 'worlds', 'joint', 'band', 'island', 'triangle'], ["bigod's", '1507–1537', 'bigod', '1120'], ['eod', 'organ'], ['gmod', 'file', 'g-mod'], ['ood', 'object-oriented'], ['tvod'], ['amod', 'b']]
TOP TOKENS [['wilkins', '1966', 'day', 'naacp'], ['wilkins', '1987', 'dna', 'molecules', 'also', '1984', 'took', 'party', 'laureates', 'nuclear', 'tranquillity', '1969'], ['wilkins', 'wilkins(noun', 'wilkinsˈwɪl', 'word'], ['wilkins', 'years', '1984', 'activities', 'reactors', 'may', '1953', 'polynomials', 'spent'], ['wilkins', 'mr', '1992', '”', '1973', 'presidency', '1969', 'detected', 'along'], ['wilkins', 'mr', '1992', '”', '1973', 'presidency', '1969', 'detected', 'along'], ['wilkins', 'jr', 'stewart'], ['wilkins', 'banks', 'participated', '1967', 'carter', '76'], ['wilkins', 'banks', 'participated', '1967', 'nonviolence', '1968', '76', 'also', 'naacp', '1976', 'carter'], ['wilkins', 'news', 'rights'], ['wilkins'], ['wilkins'], ['wilkins', "wilkins'nhl", 'would', 'pittsburgh', 'penguins', '1979'], ['wilkins', '1762–1845', 'politician'], ['wilkins'], ['wilkins', '2010', 'runner-up', 'basketligaen', 'play-offs', '21.8', 'season', 'newell', 'team'], ['wilkins', 'patriotism', 'maryland', 'harris', 'time', 'mason', 'schuster', '2001', 'press'], ['wilkins'], ['wilkins', 'wilkin', '1990s–2010s'], ['wilkins', "men's", 'basketball', 'afrobasket.com']]
TOP TOKENS [['chiggers', 'chigger', 'jiggers'], ['chiggers', 'disease'], ['chigger', 'chiggers'], ['chiggers', 'chigger'], ['chigger', 'chiggers', 'belief'], ['chiggers', 'chigger'], ['chigger', 'chiggers', 'healthwise'], ['chiggers', 'chigger', 'hives'], ['chigger', 'chiggers'], ['chiggers', 'chigger'], ['jigger', 'chigger', 'chiggers'], ['jigger', 'jiggermast', 'jiggerpole', 'england', 'jig', 'midlands', 'inn', 'hand-operated', 'jigga', '919–967', 'transportation'], ['nigger', 'word', 'nigg', 'niggardly', '19th-early', 'people'], ['lugger'], ['jigger', 'jiggers'], ['hagger', 'haggar'], ['tigger', 'tiggers'], ['jigger', 'kilometers'], ['jigger', 'johnson', 'darach', 'albert'], ['chigger', 'history']]
TOP TOKENS [['madrid', 'barcelona'], ['madrid', 'europe', 'executions'], ['madrid', 'yet'], ['madrid', 'died', "correos'clock", '1563', 'monday', 'flemish', 'winters'], ['madrid'], ['madrid', 'died', 'alajode', 'monday', 'every'], ['madrid', 'de', 'rome', 'home', 'bailiff'], ['madrid', 'industry', 'politically', '4', 'republic'], ['madrid', 'development', 'cramped', 'dignitaries', 'mayor', 'convents', '”', '’', 'visitors', 'ones'], ['madrid', "madrid's", 'year', '’', 'however'], ['madrid'], ['madrid', 'new', 'c.f'], ['madrid'], ['madrid', 'us', 'sep', 'citations', 'bibliography', 'informational', 'references', 'notes', 'olympics', 'crisis', 'city'], ['madrid', 'team', 'l.d.u', 'http://www.mundodeportivo.com.ec/newsv2.php?id_noticia=22854', 's.c', 'c.d', 'footballers'], ['madrid', '–', 'eta', 'established', 'mayor'], ['madrid'], ['madrid', 'people'], ['madrid', "madrid's", '19', 'mining', '7', 'textiles', 'transport', 'time', 'chemical'], ['madrid', "madrid's", "villaverde's", 'region', 'km2', 'transport', '2006', 'industry', 'spain', 'prominent']]
TOP TOKENS [['reported', 'reports', 'reporting'], ['reporting', 'report', 'several', 'type', 'options', 'reports', 'cls', 'file', 'reportviewer'], ['report', 'reporting', 'reported', 'reports', 'also', 'many', 'spontaneous', 'parts', 'identify'], ['report', 'reports', 'reporting', 'well', '2010', 'parts', 'might', 'called', 'create'], ['report', 'reporting', 'reported', 'use', 'verb', '‘are', 'like'], ['report', 'reports', 'example', 'specific', 'exported', 'exporting'], ['report', 'reporting', 'reports', 'selecting', 'items', 'parts'], ['reporting', 'report', 'reports', 'format'], ['report', 'reports'], ['reporting', 'report', 'reports', 'one', 'formats', 'message'], ['reporting'], ['report', 'speech'], ['reporting', 'report', 'readership', 'export', 'relevant', 'generator', 'writer'], ['reporting', 'software', 'report', 'notable', 'generator', 'reports'], ['reporting', 'reports', 'report', 'operational', 'enterprise', 'process', 'public'], ['report', 'reports', "report's", 'business', 'cls', 'elements', 'written', 'often', 'play'], ['reported', 'reporting', 'underreporting', 'positives', 'data'], ['report', 'reporting', 'reports', 'party', 'links', 'services', 'defining', 'external'], ['report', 'reported', 'reporting', 'reports', 'development', 'also', 'methods', 'spontaneous', 'ae', 'oblige', 'patient'], ['report', 'reporting', 'reportviewer', 'reports', 'manager', 'settings', 'manage', 'services', 'typically']]
TOP TOKENS [['speleothems', 'speleothem', 'speleology', 'calcareous'], ['speleothem', 'speleothems'], ['speleothem', 'speleothemes', 'speleotheme', 'speleotemi'], ['speleothems', 'speleothem', 'c', 'e', 'p'], ['speleothems', 'speleothem'], ['speleothems', 'speleothem-based', 'speleothem'], ['speleothem', 'speleothems', 'spleotherm'], ['speleothems', 'speleothem', '1'], ['speleothems', 'speleothem', 'context'], ['speleothem', 'speleothems', 'speleology', 'speleological', 'speleogenesis', 'geoscience', 'site', "group's", 'country'], ['speleothems', 'speleothem', 'stalagmites', 'calcium'], [], ['speleothem', 'speleothems'], ['speleothems', 'speleothem', 'speleoseismites', 'speleoseismite'], ['speleothems', 'speleothem', 'stalagmites'], ['speleology', 'speleologia', 'speleologica', 'spéléologie', 'biospeleology', 'physical', 'j', 'environment', 'nazionale', 'geology-geomorphology', 'società', 'kramer', 'added'], ['speleotherapeutic', 'speleotherapy', "speleology's", '1985', 'hory', 'climatic', 'sanatorium'], ['speleotherapy', 'speleotherapeutic', 'cls', 'spelaion', 'residents', 'spannagel', 'ennepetal', 'hermann', 'clinic'], ['speleological', 'speleology', 'speleologists', 'speleogenesis', 'speleologie', 'speleomorphology', 'physical', 'cls'], ['speleogens', 'speleothems', 'speleogen', 'speleogenesis', 'ceilings', 'anastomoses', 'caves']]
TOP TOKENS [['rate', 'rates', 'heart', 'resting'], ['rates', 'rate', 'heart'], ['rate', 'heart'], ['rate', 'heart', 'rates'], ['rate', 'heart'], ['rate', 'rates', 'heart', 'beats'], ['rate', 'rates', 'heart'], ['rate', 'heart'], ['rate', 'heart'], ['rate', 'rates', 'heart', 'bpm', 'beats'], ['rate', 'rates', 'heart', 'resting', 'beats', 'bpm'], ['rate', 'heart', 'rates', 'increases', 'bpm', 'resting', 'cls', 'conditions'], ['rate', 'heart', 'measure', 'medical', 'display', 'measuring'], ['rate', 'heart', 'rates', 'resting', 'data', 'individuals', 'beats'], ['rate', 'rates', 'heart', 'vary', 'ranges', 'maximum', 'bpm'], ['heart', 'rate'], ['rate', 'heart', 'old', '–', 'bpm', 'years'], ['rate', 'heart', 'determining', 'measure', 'elbow', 'measuring', 'another', 'involves', 'beats', 'monitors', 'instantaneous'], ['rate', 'heart', 'beats'], ['rate', 'heart', 'maximum', 'declines']]
TOP TOKENS [['cliches', 'cliche'], ['cliche', 'cliches'], ['cliche', 'cliches', 'dictionary.com'], ['cliches', 'cliche'], ['cliches', 'cliché’', 'cliche', 'word', 'use'], ['cliches', 'cliche', 'precious'], ['cliche', "cls]'cliche", 'cliches', 'clicher', 'nowadays', 'boilerplate'], ['clichés', 'cliché', '“anti-cliché”', 'although'], ['cliches', 'cliche', 'pain'], ['cliche', 'cliches'], ['cliché', 'cliche', 'karen', 'mxmtoon', 'overuse', 'melotron'], ['cliche', 'cliches', 'cliched', "clicher,'to", 'bath', 'time', 'imbecile'], ['cliches', "that's", 'enamored', 'sports', 'shorthand'], ['pastiche'], ['cliche'], ['clichés', 'album', '2:49', 'participated', "let's", 'lost', 'later', 'lies', 'bergman', '–'], ["cliche's", 'cliche', 'links', 'site'], ['cliche', "cliche's", 'creative', '2012', 'cls', 'vegas'], ['cliché', 'éloizes', "radio's"], ['corniche']]
TOP TOKENS [['intelligences', 'person', '’', 'people', 'factor', 'someone', 'tests', 'intelligence', '‘'], ["sternberg's", 'people', 'general', 'intelligence', "can't", 'abilities', 'group', 'factor-->group'], ["sternberg's", 'people', 'general', 'intelligence', "can't", 'abilities', 'group', 'factor-->group'], ['factor', 'person', 'intelligence', 'psychometricians', 'intelligences', 'verbal'], ['verbal', 'people', 'factor', 'intelligence', 'intelligences', 'subjects'], ['psychometric', 'intelligence', 'tasks', 'summarizes', 'quotient', 'cognitive', 'abilities'], ['tests', 'subjects', 'intelligence', 'factor', 'abilities', "today's", 'results', 'visual', 'scores', 'ability', "spearman's", 'general', 'test', "test's"], ['general', 'pp', 'tests', 'verbal', 'components', 'psychometric', 'witten', '“', 'erlbaum', 'tasks', 'aptitude', 'r', 'people', '’', 'intelligence', 'mahwah', 'james', 'hastie', 'factor', '39', 'content'], ['tests', 'psychometric', 'white', 'general', 'intelligence', 'presents', 'g', 'individual', 'abilities', 'also', 'people', 'test', 'scores', 'factor', 'measure', 'heritability', 'concentrates', 'cognitive', 'curve', 'genetics', 'spearman', 'working'], ['takers', 'intelligence', 'aptitude', 'tests', 'people', 'standardized', 'testing', 'backgrounds', 'propagating', 'edd', 'field', 'ability', 'variety', 'example', 'test'], ['intelligences', 'individuals', "gardner's", 'tests', 'intelligence', 'researchers', 'scientific', 'psychometricians', 'skills', 'abilities', 'batteries', 'talents', 'contends', 'educationalists', 'model', 'one', 'psychometric', 'neglecting'], ['intelligence', "person's", 'tests', 'psychometrics', 'theories', "one's", 'factor', 'reason', "individual's", 'group', 'well', 'psychometric', 'individual', 'general', 'cognitive'], ['intelligence', 'writing', 'general', 'individual', '352', 'work', 'differential', '–', 'international', 'race', 'conceptualize', 'cognitive', '2006', 'science', 'wagenmakers', 'iq', 'vol', 'useful', 'westview'], ['factor', 'intelligence', 'researchers', 'publishers', 'j', 'g', 'ability', 'research', 'edition', "today's", "spearman's", 'general', 'theory', 'modules', 'psychology'], ['intelligence', 'tests', "children's", "person's", 'subjects', "individuals'standing", 'psychometric', 'general', 'task', 'cognitive', 'tasks', 'test'], ['subjects', 'groups', 'people', 'intelligence', 'individuals', 'general', 'intelligences', 'verbal', 'factor', 'area'], ['intelligences', 'measure', 'theory', 'intelligence', 'general', 'person', 'individuals', 'g', 'measures', 'term', 'psychology'], ['intelligence', 'human', 'personality', 'general', 'howard', 'cambridge', 'psychology', 'cognitive', 'theory', 'factor', 'psychometrics'], ['verbal', 'van', 'test', 'colleagues', 'cognitive', 'intelligence', 'tests', 'human', 'tasks', 'mechanisms', 'person', 'psychometrics', 'general', 'e', 'spatial'], ['general', 'tests', 'intelligence', 'abilities', 'researchers', 'factor', 'test', 'scientific', 'ability', 'individual', 'research', 'one']]
TOP TOKENS [['beetles', 'beetle', 'others', 'sunlight'], ['beetles', 'beetle', 'tortoise', 'flat', 'trunks'], ['beetle', 'beetles', 'cerambycidae', 'family', 'whirligig'], ['beetles', 'beetle', 'heads', 'every', 'worms'], ['beetle', 'beetles', "beetle's", 'stage', 'caps', 'smooth', 'predators', 'eggs', 'mandibles'], ['beetles', 'beetle', 'year', 'animals', 'frequently', '”'], ['beetles', 'beetle', 'error', 'often', 'humans', 'wetlands', 'continue', 'million', 'millennia'], ['beetles', 'beetle'], ['beetles', "beetle's", 'beetle', 'ones', 'classified', 'species', 'blind', 'water', 'peninsula'], ['beetles', 'cerambycidae', 'allow', 'look'], ['beetles', 'beetle', 'beatles', 'novel', '1895–1961', 'film', 'volkswagen', '1913–2003', 'asic', 'inc', 'comics', '1938–2003'], ['beetle', 'beetles', 'disambiguation', 'comics', 'orientalis', 'beatles'], ['beetle', 'links', 'external'], ['beetle', 'syren', 'djinn', 'pamela', 'milo', 'banda'], ['beetle'], ['beetle', 'beetles', 'coleoptera', 'cerambycidae', 'world'], ['beetle', 'spider', 'august'], ['beetle', 'universe', 'marvel'], ['beetles', 'beetle', 'intelligent', 'unusual', 'horn', 'children'], ["beetle's", 'beetles', 'beetle', "players'beetles", "player's", 'two', 'whose', 'controlled', 'representing', 'play', 'reader']]

Processing features:  49%|████▉     | 48/98 [23:01<24:35, 29.52s/it]

getting sample prompt forgetting sample prompt for 23977
 23976
getting sample prompt for 23978
getting sample prompt for 23979
getting sample prompt for 23980
getting sample prompt for 23981
getting sample prompt for 23982
getting sample prompt for 23983
getting sample prompt for 23984
getting sample prompt for 23985
getting sample prompt for 23986
getting sample prompt for 23987
TOP TOKENS [['trichome', 'trichōma', 'trichom', 'trichoun'], ['tricho', 'v.—trichosis.—morbid', 'trichosis', 'trichonosis', 'trichonosus'], ['sancho', 'sancho.see', 'pancho', 'sincho', 'emicho', 'foncho', 'anicho', 'sanche', 'san-cho', 'sandino', 'bartho', 'safcho', 'sandero'], ['ancho'], ['anchoa', 'anchovies', 'anchovy', 'anchoveta', 'encrasicholus'], ['anchovies', 'anchovy', 'anchoveta', 'anchovy(redirected', 'anchovy,small', 'chordatachordata', 'enso', 'e.g'], ['trichomes'], ['tricho', 'trichodesmium', '”', '“', '’', '3782'], ['sancho'], ['trichome', 'trichomes'], ['ticho'], ['nacho', 'nachos'], ['tachometer', 'tachograph', 'tacho'], ['sancho'], ['concho', 'conchos'], ['tycho', 'tycho-1', "tycho's", 'tycho-2', 'disambiguation'], ['pancho', "pancho's"], ['wancho', 'wanchojang'], ['ticho', 'cicho', 'links'], ['kachō', 'kachō-no-miya']]
TOP TOKENS [['lester', 'r'], ['lester', 'various', 'one', 'r', 'cls', 'mid', 'forests', 'manhandling'], ['lester', "lester's", 'minister', "1970's", '1960', 'manual', 'ed', 'department', 'later'], ['lester', 'building', 'lays', 'style', 'west'], ['lester', 'building', 'lays', 'style', 'west'], ['lesterol', 'thompson', 'mahan', 'ofapril', 'husney', '06', 'nhlbi', '5235', '742', 'levels', 'lung', 'healthwise', 'ed', 'martin', 'diets', 'cholesterol', 'pp'], ['lesterol', '88', 'public', 'tremendous', 'touch', 'across', 'ground', 'individuals', 'farmers', 'play', 'whole', 'part', 'residents', 'unique'], ['lesterol'], ['lesterol', 'many', 'depression', 'senior', 'estrogens', 'cholesterol', "today's", 'better', 'much', 'heart', 'today', 'body'], ['lesterol', 'bran', 'broccoli', 'big', 'blood', 'brussel', 'cholesterol', '5', 'red', 'sprouts', 'wheat', '…', '35', '20', 'germ', 'option', 'least', 'special'], ['lester', 'sits'], ['lester', "lester's"], ['lester', 'million', '2011', 'births', '2009', 'time', 'grew', 'american'], ['lester'], ['lester'], ['lester', 'biography', '1940', '1930s'], ['lester', 'julia', 'jim'], ['lester', 'california'], ["lester's", 'lester', 'comrades', 'position', 'unhesitatingly', 'others'], ['lester']]
TOP TOKENS [['mock', 'mocks', 'mockbox', 'test', 'dependencies', 'apis', 'mocking'], ['mock', 'environment', 'using', 'use', 'configuration', 'learn'], ['mock', "succeed.'mocks", 'tests', 'test', "test'is", 'utet'], ['mock', 'mockers', 'mocker', 'mockito', 'manages', 'object', 'testers'], ['mock', 'ways', 'imitate'], ['mock', 'correctly', 'cluster'], ['mock', 'wiki', 'use', 'rpms', 'default', 'using'], ['mock', "mockoon's", 'mockoon', 'first', 'experience', 'enough', 'needed', 'body', 'realistic'], ['mock', 'etc', 'interviews', 'interview'], ['mock(redirected', 'mock', 'mocks', 'mockery', 'mocking', 'new', 'mocked', 'looks'], ['mock', 'mocker', 'disambiguation', 'surname'], ['möck', 'mock', 'jerrie'], ['mocker', 'mockers'], ['mock', 'c', 'eight', 'home', 'railway', 'surrounding', 'gnis', 'beyond', 'miles'], ['mock', 'started', 'dixie', 'moonshot', 'anna', 'nicole', 'went', 'go', 'model', 'wb/cws', 'got', 'brought', 'would'], ['mock', 'short', 'enough', 'sputtered', 'career', '4th', 'went', 'played', "state's", 'well', 'left', 'however'], ['mocksville', "mocksville's", 'c'], ['mock', 'interview', 'self-presentation', 'purposes', 'process', 'interviews', 'schedule'], ['mock', '2003', 'never', 'recorded', 'lake'], ['möckern', 'saale-holzland-kreis']]
TOP TOKENS [['yin', 'inferior', 'receptive', 'yang'], ['yin'], ['yin', 'valley', 'yang', 'side', 'revealed', 'hua'], ['yin', "yin's", 'yang'], ['yin', 'yinyang'], ['yin', 'yang'], ['yin', 'yin-yang', 'ago', 'word', 'yang', 'black', 'like', 'traditionaly'], ['yin', 'yang', 'everything'], ['yin', 'yang', 'still'], ['yin', 'yin-yang', 'government', 'thought', 'yang'], ['yin', 'yining', 'yinxu', 'yǐn', 'lingyin', 'state'], ['yin', 'also', 'character', 'dynasty'], ['yin', 'yin-yang', 'yinyang', 'yang', 'album', 'ying'], ['yin', '2022', '2020', '2016', '2015', 'conduct'], ['yin', '印', 'poem', 'seal".<ref>the', '0.0091', '印子月', 'population'], ['yin', 'class', 'dynasty', 'asia', 'capital', 'cls', 'poem', 'country'], ['yin', 'year', 'heath', 'china'], ['yin', "yin's", 'myers', 'public', 'engineering', 'livelihood', 'market', 'taiwan', 'chunqiu', '1950s', 'countries'], ['yin', 'expatriate', 'links', '—'], ['yin', 'january', 'party', '2015', 'china', 'despatched', 'addition', '19', '2002', '2018', 'ccp']]
TOP TOKENS [['sponge', 'spongelike', 'sponges', 'spongemiddle', 'spongethe', 'milk'], ['sponge', 'sponges', 'sponge(say'], ['sponge', 'sponges', 'spongey', 'spongebob', 'involving', 'one'], ['sponges', 'sponge', "sponge's"], ['sponges', 'sponge', 'cls', 'organs'], ['sponge', 'sponges'], ["word'sponge'is", 'sponges', "called'sponge", 'sponge'], ['sponge', 'sponges', 'life'], ['sponge', 'sponges', "sponge.'porifera'means'pore"], ['sponge', 'sponges', 'named'], ['sponge', 'sponges', 'porifera', 'disambiguation'], ['sponge', 'sponges', 'competing', 'sea', 'synthetic', 'cls'], ['sponge', 'sponges', 'spongebob'], ['sponge', 'sponges', 'aegyptiaca'], ['sponges', 'sponge', 'cls', 'many', 'process', 'pores'], ['sponge', 'sponges', "sponges'spicules", "sponge's", 'freshwater'], ['sponges', 'sponge', 'poriferans'], ['sponge', "sponge's", 'pinata', '2021', 'also', 'partnered', 'drums', '2019'], ['sponge', 'united', 'torso'], ['sponges', 'sponge']]
TOP TOKENS [['ombudsman', '‘ombudsman’', 'ombudsperson'], ['ombudsman', "ombudsman's", 'ombuds'], ['ombudsman', 'ombudsmen'], ['ombudsman'], ['ombudsman’s', 'ombudsman', "ombudsman's", 'ombudsman-type'], ['ombudsmen', 'ombudsman', 'justitieombudsman'], ['ombudsmen', 'ombudsman', 'justitieombudsman'], ['ombudsmen', 'ombudsman'], ['ombudsman', 'ombudsmen'], ['ombudsman', '“'], ['ombudsman', 'ombudsmen', "ombudsman's", 'ombudswoman', 'ombudsperson'], ['ombudsmen', 'ombudsman'], ["ombudsman's", 'ombudsman', 'ombudsmen'], ['ombudsman'], ['ombudsman', 'ombudsmen', "ombudsmen's", "ombudsman's"], ['ombudsman', 'ombudsmen'], ['ombudsman', 'ombudsmen', 'ombuds', 'ombudspersons'], ['ombudsman', 'ombudsmen'], ['ombudsman', 'ombudspersons'], ['ombudsman']]
TOP TOKENSTOP TOKENS [['nathaniel', 'read', "hawthorne's", 'hawthorne', 'want', '1835', 'young', 'goodman', 'brown', 'story'], ['caesar', 'studycom', 'julius', 'brutus', 'hero', '4', 'marcus', 'journal', "shakespeare's"], ['journals', 'literature', 'studies', 'faulkner', "faulkner's", 'william', 'story', 'rose', 'emily', 'paper', 'analysis', 'faulkners', 'emilybr', 'librarian', 'pages', "emily,'everyone"], ['wind', 'henry', 'inherit', 'jerome', 'drummond'], ['understanding', 'edgar', 'study', "poe's", 'poe’s', 'critical', 'deeper', 'lee', 'annabel', 'analyzes', 'allan', 'poe', 'allen', 'essays'], ['grapes', 'wrath', 'winfield', 'analysis', 'paper', 'literature', 'papers', 'study'], ["shakespeare's", 'william', 'shakespeare', 'birthplace', 'sparknote', 'editor', 'escapes', 'revolutionary', 'trust', 'analysis', 'study', 'macbeth', 'composer', "england's", 'introduction', "in'macbeth", 'exciting', 'summary', 'cares'], ['nathaniel', 'goodman', "hawthorne's", 'hawthorne', 'hawthornes', "hawthorne's'young", 'analysis', 'young', 'literature', 'analyzing'], ['nathaniel', 'goodman', "hawthorne's", 'hawthorne', 'analysis', 'young', 'civil'], ['silas', '1819', 'george', 'book', 'developed', "eliot's", 'analysis', 'summary', 'novel', 'marner'], ['faulkner', 'pen/faulkner', "pirate's", 'william', 'prize'], ['lancaster', 'literarischen', 'control', "wallace's", 'critique', 'david', 'infinite', 'bernhard', 'ideology', 'wallace', 'societies', 'loop', 'arms', 'many', '218', 'kadmos', 'children', 'foster', 'literature', 'april', 'braving', 'book', "art's", 'studies', 'literatures', '4', 'theorising', "dostoevsky's"], ['iv', 'henry', 'kedros', 'ii', 'merry', 'william', 'eugene', 'shakespeare', 'midsummer', 'timon', 'bennett', 'pub', 'titus', 'romeo', 'athens', 'lear'], ['hannah', 'arendt', 'hannaharendt', 'arendtian', "arendt's", 'carl', 'humanities', 'study', 'articles'], ['dorian', 'gray', 'audrey', 'henry', 'howard', 'de', 'todd', 'vane', 'brett', 'harry', 'jacqueline', 'retrato', 'sibyl', 'il', 'entry', 'enrique', 'age', 'chaplin', 'lord', 'richard', 'old', 'jarrott', 'basil', 'charles', 'hallward', 'cedric', 'german', 'felix'], ['gray', 'dorian', 'grey', 'doronin', 'brett', 'de', 'bernd', 'felix', 'elet', 'enrique'], ["ogden's", "o'hara", 'cheever', 'boston', 'lynne', 'study', 'library'], ['literature', 'study', 'george', 'sandulescu', 'bucharest', 'finnegans', 'james', '104', 'scandinavian', 'c', 'pages', 'unenglish', 'contemporary', '003'], ['jane', 'j', 'scott', 'b', 'janeites', 'emma', 'todd', 'c', 'juliet', 'macmillan', 'austen', 'douglas', '227', 'walter', 'edward', 'grey', '232', '1812', 'cambridge', 'southam', 'heritage', 'quarterly', 'alfred', 'literature', 'copeland', 'david', 'london', '1940', 'routledge'], ['darling', 'pulitzer', 'widow', 'good', 'editorial', 'margaret', 'biography', 'prizes', 'convict', 'autobiography', 'florida', 'notes', 'prize', 'writing', 'distinction', 'grace']]
 [['language', 'skills', 'conditions'], ['climate'], [], ['toward', 'many'], ['expertise', '2', 'thirteen', 'pages'], ['lugduni', 'artifialium', 'fervantur', 'rariorum', 'earth', 'worm', 'elseviriorum', 'exoticarum', 'brayshaw', 'quae', 'doctor', 'seu', 'hafniae', 'authoris', 'naturalium'], ['lofty'], ['citizens', 'good', 'community', 'cultural', 'enough', 'sense', 'member', 'strive'], ['caroline', '3844513806', 'spoken', 'raab', '·', '520', 'wenzl', '89849', 'pool', '3844511192', '2002', 'rundfunk', 'hammelstein', 'luckenhaus', 'ptok', 'kremer', '2013', 'cds'], ['political', 'current', 'inclined', 'certitude', 'may'], ['mb', 'v2', 'g', 'id3v2', 'bears', 'id3v1', 'may', 'cover', 'analogues'], ['anguis', "order's"], ['sea', '2400', 'eveleth', 'however', 'able', 'side'], ['fearued', 'name', 'praper', 'vocals'], ['aarakocra', 'geography', 'psionics', 'imagination', 'regions', 'specific', 'various'], ['align'], [], ['sirenia', 'fantasy', 'eduction', 'science', '119', '125', '115'], ['npcs', '148-page', 'lejentia', 'would', 'describing', 'based'], []]
TOP TOKENS [['abel', 'abell', 'england'], ['abel', 'abelle', 'abeler', 'abell', 'abelson', 'abele', 'abeles', 'distinguished', 'aball', 'however', '1199', 'abill', 'english', 'john', 'ablson'], ['abel', '’', 'produce', '21', 'well', 'one', 'sorensen', 'objects'], ['abel', 'abelia', 'abelias', 'dr', 'fully', 'british', 'climbing'], ["abel's", 'however'], ['abel', 'abelina', 'abela', 'abele/abelino', 'ábel', 'eve', 'abelis', 'abels', 'ages', 'old'], ['abel', 'ábel', "abel's", 'abedah', '2019', 'sacrifice'], ['abel', "abel's", 'africanus', 'xxi', 'jesus', 'righteous', 'matt', '4'], ['abelia', 'abelias', 'snip', 'begins', '1', '9', 'spp', 'well-drained', 'entire', '5'], ['abel', '1199', 'william', 'germany', 'retake', '”', 'adam', '12th', 'swabia'], ["abel's", 'american', '1997', 'abel', 'inter', 'life', '870', 'personal', '78219', 'new', 'bantam', 'u', 'award', '0', 'mifflin', 'association', '1970', 'georgia'], ['abels', "abel's"], ['abel', '1920s', 'illness', 'charlottenburg', 'ariernachweis', '1924', 'began'], ['abel', 'london', 'overseas'], ['abelian', 'abelson', 'abel', 'abell', 'abels', 'lincoln', 'bahrelghazali', 'disambiguation', 'abil', 'annual', 'states', 'prize', 'season', '1986'], ['abel'], ['abel', 'american'], ['abels', "abels'death", 'years', '1989', 'unstated', 'deep', 'equinox', 'six', 'nyac'], ['abel', 'abelsøn', 'iii', '1', 'elder', 'schwerin', '1317', 'rudkøbing'], ['abel', '20th-century', 'colorado', 'ohio', 'hadley', 'arts']]
TOP TOKENS [['mead', 'herbert', 'read', 'world', 'george', '—', 'self', 'today', 'never', 'social'], ['mead', "mead's", 'herbert', 'read', 'world', 'never', 'george', 'self', 'today'], ['mead', 'watts', 'feminist', 'teenagers', 'pursuits', 'cengage', 'morrow', 'margaret', 'scholars'], ['mead', 'meads', 'nature', 'among', 'meadery', 'poland'], ['mead', 'family', 'cls', 'notes', '1888', 'articles'], ['mead', 'meads', 'tank', 'gravity', 'herbs', 'order'], ['mead', 'cls', 'ingredients'], ['mead', 'structures', 'focuses', 'roles', 'guillaume', 'wilder', 'one'], ['mead'], ['mead', '’', 'century'], ['mead', '2017', 'january', 'roosters', 'finals', '2020', 'stadium'], ['mead', 'columbia', 'district', 'life', 'personal'], ['mead', '1858–1925'], ['mead', 'jon', '–', 'elwood', 'college'], ['mead'], ['mead'], ['mead', 'son', 'career', 'also', 'babe', 'actors', 'well', 'viejo', 'links'], ['mead', '2003', 'august', 'iowa', 'baltimore', 'poetry', 'mexico', 'embrace', 'speculation', 'times'], ['mead', 'divinity', 'baldwin', 'hines', 'biography', 'michigan', 'parishfleld'], ['mead']]
TOP TOKENS [['carpet', 'carpets', 'rugs', 'separately', 'recyclable', 'recycle', 'options'], ['carpet', 'carpets', 'composition'], ['carpet', 'carpets', 'carpeting'], ['carpet'], ['carpet'], ['carpet', 'https://www.epa.gov/greenerproducts/identifying-greener-carpet', 'carpet’s'], ['carpet', 'carpets', 'separately', 'recyclable', 'asking', 'together', 'silk'], ['carpet'], ['carpet', 'carpets', 'rugs', 'rug', 'bisselling', 'term', 'unaware', '”', 'germs', 'unclean'], ['carpets', 'carpet', 'room', 'homes', 'surface'], ['carpets', 'carpet'], ['carpet', 'aladdin', 'game', 'lift', 'u.s', 'song', 'vehicle', 'disambiguation'], ['carpet', 'band', 'film', 'software', 'bc'], ['carpet', 'carpets', 'residences', 'embroidered', 'room', 'rug', 'structure', 'floor'], ['carpet', 'foundations', 'talon', 'i.e', 'dealt', 'cards'], ['carpet', 'carpeted', 'carpetbaggers', 'term'], ['carpet', 'carpets', 'fibers', 'leaving', 'methods', 'allergens', 'onto'], ['carpet', 'carpets'], ['carpet', 'carpets', 'onto', 'time', 'fibers', 'wool'], ['carpet', 'carpets', 'rug', 'rugs', 'agic', 'world', 'term', 'magic', '1816', 'commercial', 'contempt']]
TOP TOKENS [['manhood', 'time', 'posey', 'statesman', "alex's", "man's", 'well', 'man', 'happy', 'humorist', 'eagerness', 'poet', 'chance', 'first', 'enabled'], [], ['decline', 'first'], ['negotiator', 'enough', 'merchants', 'foreign', 'world', 'acting', 'translator', 'rebellion', 'later', 'u', 'period', 'constitution', 'time', 'one'], ['ultimately', '’', 'dancing'], ['ultimately', '’', 'dancing'], ['1', 'polyphonica', 'coaches', 'decide', "auditioner's", '4', '26', 'tuesday'], ['comically', "mother's", 'fruit', 'kovu', "kiara's", "rafiki's", 'yells', 'sky', 'ascends', 'away', 'cubhood'], ['hail', 'days', 'games'], ['u', 'ago', 'union', 'amendment', 'later', 'q'], ['first', 'historic', 'game', 'ever', 'thanks', 'earlier', '–', 'eventual', "league's", 'road', '39', 'appearance', 'also', 'history'], ['https://web.archive.org/web/20091021215854/http://geocities.com/cfl_historical/wilcox.g.htm', "cfl's", 'football', 'season', 'also', 'canadian', 'births'], ['tennessee', 'mars'], ['two', 'also', 'played', 'footage', 'career', 'music', 'major', '2013', 'first', 'completing', 'year', 'well', 'featured', 'childhood', 'awards', 'shortly'], ["sazh's", "alyssa's", 'along', 'better', "fang's", 'nagashima', 'went', 'several', 'name', 'much', 'since', 'included'], ['victory', 'louisville', 'miss', 'due', '2018', 'however', '18', '1', 'along', '9', '–', '23', 'yards', 'game'], ['saw', 'adaptation', 'templar', 'descendants', 'based', 'real', 'overruns', 'also', 'appeared', 'mistrust', 'must', 'appearing'], ['19', '15', 'iv', 'january', '2011', '2012', 'cincinnati', '22', 'following', 'marion', 'incidentally', 'playoffs', 'teams', 'tupelo', 'sesay', 'history', 'tracing', 'acquisition', 'friday', "monsters'elimination", 'markets', 'erie', 'time'], ["frogs'1999", 'future', 'victory', 'galleryfurniture', 'football', 'time', 'three', 'back', 'games', 'season', 'appearances', 'bowl', '4', 'jets', 'record', 'subsequently', 'also'], ['making', 'march', '1', 'season', 'panthers', 'february', 'stars', 'penguins', '–', "chicago's", 'game', '2005', '2009', 'series']]

Processing features:  50%|█████     | 49/98 [23:29<23:47, 29.12s/it]

getting sample prompt forgetting sample prompt for 23989
 23988
getting sample prompt for 23990
getting sample prompt for 23991
getting sample prompt for 23992
getting sample prompt for 23993
getting sample prompt for 23994
getting sample prompt for 23995
getting sample prompt for 23996
getting sample prompt for 23997
getting sample prompt for 23998
getting sample prompt for 23999
TOP TOKENS [['bathroom', 'bathrooms', 'restrooms', '“female”', '“non-binary”'], ['bathrooms', 'bathroomsforh', 'restroom', 'restrooms', 'odell', 'make'], ['bathrooms', 'restrooms', 'bathroom'], ['bathrooms', 'bathroom', "girls'bathrooms", 'whole', "women's", 'thing', 'restrict', 'urinals'], ['bathroom', 'bathrooms', 'restrooms', 'restroom', 'marked'], ['bathrooms', 'restrooms', 'bathroom', 'access', 'pee'], ['bathroom', 'bathrooms', 'fluids', 'public'], ['bathrooms', 'restrooms', 'restroom'], ['bathrooms', 'bathroom', 'although', 'spaces'], ['bathrooms'], ['bathroom', 'bathrooms', 'restrooms', "women's", 'bill', 'using', 'bills', 'stall', 'room'], ['bathrooms', 'bathroom', 'restroom', 'restrooms', 'public', 'bills', 'make'], ['bathrooms', 'bathroom', 'related', 'restroom', "women's", 'occupancy', 'law', 'degree', 'using', 'use', 'neutral', 'repealed'], ['bathroom', 'restroom'], ['bathroom', 'fellino', 'kohler', 'showrooms'], ['bathroom', 'break', 'urinate', 'nostalgia', 'employees', 'queue'], ['bathroom', 'bathrooms', 'reading', 'stalls', 'sex'], ['bathroom', 'bathrooms', 'restrooms', 'restroom', 'policed', 'public', 'using', '“'], ['restroom', 'bathroom', 'restrooms', 'every', 'limited', 'public', 'use', 'bill', 'user', 'access', 'hands', 'require', 'restricting', 'define', "driver's"], ['bathroom']]
TOP TOKENS [['spot-on', 'cv', 'tips'], ['cv'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'uneven'], ['spot-on', 'cv', 'tips'], ['spot-on', 'cv', 'tips', 'hook.’'], ['cv', 'cls', '2019', 'places', 'uk', '–', 'acute', 'arts', 'german', 'science', 'verde', 'england', 'designator', 'spanish', 'iata'], ['society', 'cv', 'kingdom', 'touch-a-billion', "cv's", 'impact-a-nation'], ['cv', 'shortened', 'applying', 'careers', 'achievements', 'countries', 'often', 'abbreviation', 'called', 'cvs', 'short', 'english'], ['careers', 'links', 'external', 'cv', 'shorter', 'industry', 'achievements', 'cvs', 'academia', 'generally', 'medical', 'usually'], ['cv', 'bulqize'], ['cvs', 'time', 'g', 'origins', '1', 'guarantee', 'however', 'history', 'due', 'since', 'including', '2003', 'functionally', "cvsnt'ls", 'e', 'cvsnt'], ['cv', 'people', 'english'], ['gov', 'cv', 'cls', 'iana', 'com', 'net', 'nome', 'october', 'publ', 'ciencias', 'transferred', 'ao', 'tome'], ['abbreviated', 'cv', 'commonly'], ['cv', 'amended', 'changed', 'issued', 'defended', 'varied', 'overruled', 'passed', 'described', 'period', 'stated', 'rubbish']]
TOP TOKENS [['reblogged', 'retrocausal', 'emberkeelty', 'tentacandy'], ['reblogged', 'gunslingerhorseygirl', 'raevyrn', 'apeurohist', 'sincerelettersfromaninsaneasylum'], ['victoriousvocabulary', 'reblogged'], ['reblogged', 'popsixsquishcicerolipschitz', 'hajandrade', 'figbuckindeal', 'babalou71', 'rezazabeti', 'ayuwringal', 'mitologiasvivas'], ['iamablasphemousgirl', 'cyanita', 'reblogged', 'msexplorer', 'rayneredwolf', 'northandinthemiddle', 'anywigwilldo', 'michedug1983'], ['reblogged'], ['reblogged', 'r', 'youlookcoolphotography', 'sebastionsebastionyes', 'snailly', 'l', 'midniteguerilla', 'gooseandjewels', 'thelastrecluse'], ['reblogged', 'kbroddd', 'moreanimalia', 'likes', 'ilovehimbuthewonteverknow', 'bonewhiteglory', 'biologynerdynerd', 'lifeisjustatheory', 'luna0abbi', 'thedirtyrussian'], ['reblogged', 'soycheely', 'curvydallas', 'hareehstyles', 'thepinkbubble', 'suzannedequaalude', 'handjob', 'bigknoze'], ['leadershape', 'reblogged', 'sological', 'yrruf', 'infukingbruges', 'justapalebluedot', 'rigoamavizca', 'likes', 'cyenn', 'brandonavance'], ['township', 'cheboygan', 'county', 'lackawanna', 'hodgeman', 'keokuk', 'knox', 'ringgold', 'taylor'], ['moanin', 'moaner', 'moan', 'moaning', 'magnus', 'fulfilled', 'raymond', 'keys', 'blakey', 'throat', 'henny', 'black', 'torgeir', '1999', 'clayton', '1936'], ['jingjiang', 'jiangyin', 'donggang', '孤山满族镇', 'haicheng', 'village', 'gushan', 'گوشان', '顾山镇', 'huancui'], [], ['ohio', 'paulding', 'township', 'hocking'], ['hodgeman', 'pages', 'disambiguation', 'township', 'refer', 'county'], ['gushchin', 'retired', 'ukrainian', 'b', 'oleksandr', 'footballer', 'may', 'refer', '1966'], ['ksln'], ['styria', 'lorenzen', 'sankt', 'scheifling'], ['independently', 'fixed', 'inconclusive', 'specific', 'performance', 'evidence', 'focused', 'revealed', 'interaction', 'study', 'research', 'attention', 'quickly', 'reinvestment', 'notes', 'brought', 'one', 'various', 'rather', 'e']]
TOP TOKENS [['glacial', 'glacially', 'blank', 'alga'], ['glacial', 'pleistocene', 'stagearticle', 'cls', 'stage', 'last', 'interglacials', 'glaciation', 'glaciations'], ['glacial', 'period', 'pleistocene', 'alternatively', 'last', 'age', 'glaciations', 'glaciation', '110'], ['glacial', 'pleistocene', 'history', 'glaciation', 'cls', '1111', 'glacigenic', 'last', 'glaciations'], ['glacial', 'period', 'pleistocene', 'post', 'glaciation', 'detritus', '1339', '1351', '1360'], ['glacial', 'glacials', 'pleistocene', 'period', 'quaternary', 'periods', 'cycles', 'ice'], ['glacials', 'glacial', 'pleistocene', 'glaciology', 'geology', 'interglacial', 'terms', 'interest', 'expand'], ['glacial', 'last', 'al', '06', 'boundaries', 'et', 'slowey', 'interglacial', '1038'], ['glacial', 'period'], ['glacial', 'till', 'underlying', 'extremely', 'soils', 'dense', 'white'], ['glacialis', 'reading'], ['glacial', 'pleistocene', 'glaciation', 'quaternary', 'stratigraphy', 'map', '2004', 'interglacials', '1980a', 'period', 'boreham'], ['glacial', 'pleistocene', 'period', 'glacials', 'alternatively', 'glaciations'], ['glacialis', 'references'], ['glacialis'], ['glacialis'], ['glaciale'], ['pleistocene', 'quaternary', 'glaciations'], ['glacial', 'pleistocene', 'terminal', 'glaciation', 'series', 'zungenbecken', 'cls', 'glaciers', 'meltwater', 'ground'], ['glacialis']]
TOP TOKENS [['discovery', 'using'], ['discovery', 'discoveryeducation', 'learning', 'www', 'education', 'world'], ['discovery', 'discoveryeducation', 'learning', 'www', 'education', 'world'], ['discovery', 'based', 'upon', 'learning', 'instruction'], ['discovery', 'used', 'thus'], ['discovery', 'limited', 'markets', '1992'], ['discovery', 'textbooks', 'relying', 'education', 'partnership', 'concepts'], ['discovery', 'limited', 'markets', '1992'], ["discovery's", 'discovery', 'learning'], ['discovery', 'space', 'voyage', 'please', '1984', 'one'], ['discovery', '2010', 'mr', 'records'], ['discovery', 'discovery-spring'], ['discovery', 'hong'], ["discovery's", 'discovery', 'complete'], ['discovery', 'discover'], ['discovery', 'newton-conover', 'county'], ['discovery', 'methodology'], ['discovery', 'location', 'season', 'april', '1'], ['discovery', "discovery's", 'bros', 'since', 'entertainment', 'week-long', 'asia-pacific', '5', 'annual'], ['discovery', 'platform']]
TOP TOKENS [['persimmon', 'persimmons', 'e', 'fruit'], ['persimmons', 'persimmon'], ['mammon', 'mammonismplay', 'mammona'], ['mammon', '’', 'η', 'ενα', 'δυσι', 'pavement', 'ου', 'τον', 'αγαπησει', 'cls', '9', 'κυριοις'], ['persimmon', 'hemorrhagic', 'also', 'inflammatory'], ['lemmon', 'plummer', 'mount', 'observatory', '795', 'explorations'], ['lemmon', 'lemmons', "lemmons'two", 'intrepid', 'mrs', 'convalesced', 'lemmoni', 'g', 'mount'], ['persimmons', 'persimmon', 'infective', 'related', 'selectively', 'lycopene'], ['persimmons', 'persimmon', 'leptin'], ['persimmons', 'persimmon'], ['gammon', 'american', 'gammons', '1915–1981', 'born', 'insult', '1940–2010'], ['mammon'], ['persimmon'], ['lemmon', '–', 'born', 'cls', 'english', '1908', '1925', 'g'], ['lemmon'], ['mammon', 'boss', 'envy', 'iidx', 'mamon', 'shana'], ['persimmon', 'communities'], ['gammon', 'also', 'deaths', 'mesa', 'century', 'portrayed', 'american'], ['lemmon', 'programs', '2013', 'honours', 'serves'], ['lemmon', 'tribune', '1999', 'angeles', 'confirmed', '1985', 'corporate', '1989', 'die']]
TOP TOKENS [['morphology', 'morphological', 'morphologicalgraph', 'structures'], ['morphological', 'use', 'morphology', 'morphologically', 'images', 'image', 'neighborhood'], ['morphology'], ['morphology', 'morphology”', 'something”', 'morphological', 'studying', 'term', 'syntax', '“what', 'thus'], ['morphology', 'morphological', 'term', '2', 'cls', 'linguistics'], ['morphology', 'n', 'word', 'promorphology'], ['morphology', 'morphological', 'addition', 'articulation', 'interaction', 'position', 'deals'], ['morphology', 'another', '1a', 'morphologicallyplay', '1828', 'look', 'evolution', 'biology', 'k(ə-)lē', 'particularly'], ['morphology', 'morphological'], ['morphological', 'using', 'cls', 'ahn', 'tasks', 'study', 'awareness', '2013'], ['morphological', 'morphology'], ['morphology'], ['morphological', 'morphologically', 'tongue', 'cls', 'approach', 'parsing'], ['morphology', 'morphological', 'closings'], ['morphology', 'morphological', '1991'], ['morphology', 'handling', 'morphological', 'dvn07', 'emerged', 'kinds'], ['morphological', 'morphology', 'gradients', 'processing', 'commonly', 'paris', 'foundation', 'applied', 'segmentation', 'mathematical', 'history', 'morphologie', 'erosion'], ['morphologically', 'morphology', 'word', 'function', 'comparative', 'differ', 'structure', 'cls', 'morphological', 'hilaire', 'richard', 'well'], ['morphology', 'morphological', '1992', 'introduction', 'mathematical', 'image', 'processing', 'using', 'erosion', 'operations'], ['morphology', 'morphological', 'strategy', 'understanding', 'system', 'years', 'cls', 'mind', 'claims', 'theories']]
TOP TOKENS [['rousseau', 'thirteen', 'therefore', 'america', 'jacques', 'woman', 'book'], ['rousseau', "rousseau's", 'theory'], ['rousseau', "rousseau's", '—', 'however', 'thought', '1728', 'catholicism', 'injustice'], ['rousseau', "rousseau's", 'murmurings', 'example', 'morals', 'government', '1755'], ['rousseau', 'savage', 'man'], ['rousseau', "rousseau's", 'rousseau(noun', 'http://www.definitions.net/definition/jean-jacques', 'jean-jacques', 'thought'], ["rousseau's", 'rousseau', 'rousseau´s', 'alienation', 'acceptable'], ['rousseau', 'jacques', 'way', 'humanity'], ['rousseau', 'jacques', 'way', 'humanity'], ['rousseau', 'rousseaujean', 'rousseaus', 'jacques'], ['rousseau', "rousseau's", 'representatives', 'hogan', 'enraging', 'e', 'gen', 'life', 'know', '1867', 'personal'], ['rousseau', '1782', '1780', 'basra'], ['rousseau', 'c', 'american', 'waldeck', 'rene', '2002'], ['rousseau'], ['rousseau'], ['rousseau', 'jean-jacques'], ['rousseau', 'style', 'jacques', 'de', 'much', 'holland', 'family'], ['rousseau', 'science', 'l', '1960s', 'ii', 'works', '1970s', 'comprendre', 'ciel', '48', 'pour', 'terre', '’', 'la', 'etoile'], ['rousseau', "rousseau's", '1893', 'school', 'subjects', '1891', 'quality'], ['rousseau', "rousseau's", 'fact', 'world', '—']]
TOP TOKENS [['clement'], ['clement', 'clementclem·ent·ly'], ['clement', 'saint'], ['clement', 'name'], ['clement', 'clementine', 'literature', 'sea', 'tradition'], ['clementia', 'clement', 'clementemerciful', 'clemente', 'clementine', 'century', 'swamp', 'clemence', 'tempered'], ['clement', 'st'], ['clement', '3', '—', '69', 'points', 'influence', 'polemic'], ['clement', 'clemente', 'clementine', "clement's", 'literature', 'sea'], ['clement', "clement's", 'clemente', 'punishment', 'clementedit', 'san', 'saint'], ['clemente', 'clément', 'clements', 'clement', 'clementine'], ['clement', 'clementine'], ['clement', "clement's", 'clements'], ['clement', 'champion', 'medalists', 'people', 'event', 'well', 'field'], ['clement', "clement's", 'war', 'withdraw', 'battalion', 'clements', 'deaths', 'references'], ['clément'], ['clement', '24'], ['clement', 'trade', '1918'], ['clement', 'called'], ['clement', 'newspapers', '1932', 'team', '1929', 'sprinting']]
TOP TOKENS [['barcelona', "barcelona's", 'catalan', 'catalonia', 'supermarkets', 'midnight', 'city', 'day', 'repressed', 'decades'], ['barcelona', 'catalans', 'catalan', 'catalonia'], ['barcelona', 'catalana', 'catalonia'], ['barcelona', 'catalana', '2005', 'cultures', 'vicens', 'musica', 'la', 'opinions'], ['barcelona’s', 'barcelona', 'base'], ['barcelona', 'barcelona’s', 'tourist', 'romans', 'name'], ['barcelonasociety', "barcelona's", 'barcelona', 'catalan', "catalonia's", "catalans'rights"], ['barcelonasociety', "barcelona's", 'barcelona', 'catalan', "catalonia's", "catalans'rights"], ['barcelona’s', 'catalans’', 'barcelona', 'catalan', 'catalonia’s', 'independence', 'metropolis'], ['barcelona', 'catalan', 'botifarra', 'escalivada', 'fish'], ['barcelona', 'catalonia', "d'antiguitats", '2009', '2013'], ['barcelona', 'song', '1704', 'catalonia', 'orchestra'], ['barcelona', 'lands', 'hundred', 'port', 'guatlla', 'practically'], ['barcelona', '1704', '1635–1659'], ['barcelona', "barcelona's", 'erected', '000', 'darder', '1826', 'churches', 'fountains', 'century', '1673', 'renaissance', 'raphael'], ['barcelona', 'catalana', 'lletres', 'quarter'], ['barcelona', "barcelona's", 'catalonia', 'inhabitant', 'channel'], ["barcelona's", 'barcelona', 'catalonia', 'catalan', 'spain', 'mayor', 'regulatory', 'government'], ['barcelona', 'catalonia', 'catalan', "catalonia's", "barcelona's"], ['barcelona', '1984', 'area', 'council']]
TOP TOKENS [['exclusive', 'area', 'unenlightened', 'came', 'side', 'quickly', 'precariously', 'diligently'], ['jungles', 'jungle', 'available', 'science', 'entire', 'prey', 'filled', 'traveled', 'w'], ['eminently', 'wherewithal', 'grid', 'wilds', 'jungles', 'ensconced', 'transformed', 'riches', 'merely', 'long', 'scientifically', 'fer', 'best', 'derring', 'incas', 'left', 'hinterlands', 'rife', '“', 'demarcated', 'forbidding', 'right', 'lurk', 'exceed', 'american', '—', 'delineates', 'various'], ['ever', 'reach', 'uncharted', 'sabre', 'almost', 'fold', 'reshape', 'every', 'regions', 'harness', 'roost', 'expanding', 'toothed', 'could', 'habitable', 'many', 'well'], ['recesses', 'things', 'forth', 'calls', 'found', 'pluck', 'get', "canyon's", 'enough', 'still', 'crawlers'], ['hubs', 'urbanizing', '’', 'primeval', 'newly', 'act', 'find', 'constrained', 'zwischenstadt', 'reconfiguring', 'new', 'longer', 'commoditized', 'range', 'hotspots', 'redirecting', 'across', 'dynamics', 'flexibly', 'instance', 'subcontracting'], ['edge', 'dense', 'tropics', 'five', 'six', 'raggedy', 'monstrous', '“', 'earthy', 'front', 'fifty', 'sawmills', 'feet', 'emergents', 'destined', 'three', 'like', 'stalks', 'barely', 'see', 'whose'], ['edge', 'dense', 'tropics', 'five', 'six', 'raggedy', 'monstrous', '“', 'earthy', 'front', 'fifty', 'sawmills', 'feet', 'emergents', 'destined', 'three', 'like', 'stalks', 'barely', 'see', 'whose'], ['edge', 'dense', 'tropics', 'five', 'six', 'raggedy', 'monstrous', '“', 'earthy', 'front', 'fifty', 'sawmills', 'feet', 'emergents', 'destined', 'three', 'like', 'stalks', 'barely', 'see', 'whose'], ['rich', 'come', 'forever', 'lonely', 'doubtless', 'stands'], ['globe-news', 'linn', 'links', 'edge'], ['hooks', 'nature', 'tethers', 'force', 'singalongs', 'dictate'], ['center', '5', 'industry', 'edge', 'reviews', 'dramatically', 'critics', 'rights', 'creative', 'release', '34', 'films', '100', '42', 'undoubtedly', "website's", '9'], ['capture', 'crimes', 'expect'], ['numerous', 'projectiles', "car's", 'earthly', 'environments', 'come', 'boundaries'], ['friedlander', 'games', 'yet', '6th', 'edge', 'game', 'place', 'leads', 'set'], ['schreck', 'edge', 'hauptmann', 'world', 'babelsberg', 'geselle', 'der', 'gmbh', 'troedler', 'johns', 'malten', 'magda', 'frau', 'stranger', 'films', 'imre', 'hollay', 'studios'], ['game', 'even', 'real'], ['vhs', 'thriller', 'forests', 'canadian', 'six', 'films', 'initial', 'set', 'drama'], ['feverish', 'time', 'quadruple', 'replete', 'every', "noir's", 'drawn', '—', 'nothing', 'pacing', 'camera', 'goes', 'story', 'exceptions']]
TOP TOKENS [['totmonslow', 'tewkesbury', 'leigh', 'ashchurch', 'gloucester', 'smith', 'somerset', 'parish', 'cannington', 'vicarage', 'hundred', 'whose', 'impropriators', 'pasture', 'tything', 'e', 'acres', 'rectory', 'varied', 'arable'], ['acres', 'chester', 'independents', 'rectory', 'congleton', 'northwich', 'found', 'simonward', 'n', 'pawton'], ['petham', 'n', 'kyloe', 'augustine', 'islandshire', 'acres', 'st', 'e', 'suffolk', 'carlford', 'woodbridge', 'lowlin', 'parish', 'tithes', 'bealings', 'kent'], ['stacey', 'wilton', 'n', 'barnstaple', 'wilts', 'southampton', 'freemington', 'impropriator', 'parish', 'andover', '3370a', 'malmesbury'], ['york', 'halifax', 'w', 'morley', 'chafford', 'romford', 'township', 'recreation', 'arable', 'mills', 'essex', 'acres', '2793a', '28p', 'warley', 'st'], ['claro', 'york', 'goldsborough', 'w', 'n', 'street', 'malton', 'salop', 'atcham', 'township', 'undulated', 'rectory', 'vicarage', 'condover', 'gravelly'], ['chester', 'runcorn', '22p', 'portbury', 'wateringplace', 'chancel', 'chapel', 'rectory', 'n', 'acres', 'arable', 'somerset', 'abundant', 'bedminster', 'e', 'hamond'], ['rosthern', 'derby', 'n', 'berks', 'faircross', 'chester', 'mansion', 'newbury', 'chieveley', 'macclesfield', 'appletree', 'land', 'radford', 'township'], ['n', 'thirsk', 'otterington', 'york', 'walshcroft', 'boston', 'allertonshire', 'birdforth', 'parish', 'lindsey', 'house', 'caistor', '£9', 'rectory'], ['n', 'thirsk', 'otterington', 'york', 'walshcroft', 'boston', 'allertonshire', 'birdforth', 'parish', 'lindsey', 'house', 'caistor', '£9', 'rectory'], ['fir', '6', 'per', 'barley', 'parish', 'barnhourie', 'loam', 'potatoes', 'granite', 'water', 'patrons', 'scale', 'fertile', '£6006', 'also', 'retires'], ['003', 'acres', 'ground', 'value', '£3', '10s', 'family', '£800', '£10', 'curacy', 'stoneley', 'estates', 'rateable', 'population', 'building', 'leighs', 'ease', 'whitworth', 'warwickshire', 'book', 'gave', 'survey', '1', 'benefactions', 'manor'], ['parish', 'arable', '1', 'st', '876', 'wheat', 'rectory', 'value', 'llawddog', 'schools', '£3', 'acres', '1851', "david's", 'way', 'cultivated', 'property', 'hilly', 'school', '285', 'carmarthen', 'trinity', 'r'], ['hamilton', '569', 'september', '–', 'winds', '9d', 'affording', '1763', 'geo', '1', 'rev', 'harbour', '11', 'within', 'proprietor', 'corn', '1811', "tons'burden", 'vessels'], ['caerphilly', 'tydfil', 'glamorgan', 'named', 'parish', 'picturesque', 'arable', 'gellygaer', 'pasture', 'craigyberthlwyd', 'common'], ['division', 'goscote', 'zouch', 'county', 'cooper', 'theol', 'vicarage', 'greaves', 'parish', 'sessional', 'repton', 'pinnacles', 'consisting', 'subsoil', 'order', 'ecclesiastical', 'diocese', 'f', 'evangelist', 'nave', 'residence'], ['£69', 'upwards', 'whilst', 'metal', '918', '22', 'acres', 'wood', 'exist', '792', '£7104', '£6560', '14', 'children', 'ayrshire', 'general', 'features', 'ord', '1880'], ['laysters', 'residence', '£2', 'houses', 'marl', 'occupiers', 'value', 'vicarage', 'landowners', 'open', 'division', 'eminence'], ['parish', 'clay', 'within', 'oak', 'ken', 'structure', 'kenmure', 'gordons', 'birch', 'mount', 'lochinvar', 'however', 'mary', 'castle', 'viscount', 'london', 'plantations'], ['parish', 'edward', 'gillespie', 'one', 'individuals', 'school', 'heron', 'refinement', 'lewis', 'lowe', 'kells', '98']]

Processing features:  51%|█████     | 50/98 [24:06<25:11, 31.50s/it]

getting sample prompt forgetting sample prompt for 24001
 24000
getting sample prompt for 24002
getting sample prompt for 24003
getting sample prompt for 24004
getting sample prompt for 24005
getting sample prompt for 24006
getting sample prompt for 24007
getting sample prompt for 24008
getting sample prompt for 24009
getting sample prompt for 24010
getting sample prompt for 24011
TOP TOKENS [['cropping', 'crop', 'cropped'], ['cropped', 'crop'], ['crop', 'cropping', "what's"], ['cropping', 'cropped', 'crop', 'aspect'], ['crop', 'cropping', 'needed', '10″x8″', '6″x4″'], ['cropped', 'crop', 'cropping'], ['cropping', 'crop', 'cropped', 'dreamweaver’s'], ['cropping', 'cropped', 'crop', 'finally', 'restrictions', 'frame', 'along', 'unnecessary', 'tools', 'aesthetics', 'rules', 'images'], ['crop', '“crop”', 'corners', 'settings'], ['crop', 'cropping', 'like', 'side', 'want', 'inside'], ['cropping', 'cropped', 'cls', 'industries', 'sharpening', 'crop', 'image', 'marks', 'businesses'], ['cropping', 'tail', 'outer', 'punishment'], ['crop', 'cropper', 'used'], ['cropped', 'cropping', 'following', 'used', 'image', 'crop'], ['cropping', 'cropp', 'pacific', 'crop', 'hairstyle'], ['cropping', 'croppings', 'arson', 'peters', 'see', 'hammurabi', 'also', 'seditious', '1839', 'samuel'], ['crop', 'cropp'], ['cropp', 'wolf-ulrich', 'linda'], ['cropley'], ['cropley']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], ['l', 'monopsis', 'wimm', 'c', 'e', 'dryand'], ['80th'], [], [], [], [], [], [], []]
TOP TOKENS [['poetry'], [], [], [], [], [], ['service', 'guys', 'unintentionally', 'dictionary', '1', 'per', '2011', '“'], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['second', 'world', '1940s', "1940's", 'war'], ['nazi', 'nation', 'ms', "hitler's", 'time', 'josef'], ['nazi', 'nation', 'ms', "hitler's", 'time', 'josef'], ['1940s', 'world', 'ii', 'war', 'depression', 'era', '1930s', '1933', 'great'], ['1940s', '1950s', '1945', '1937', '1930s', 'world', '1939', '1939publications1930', '1938', 'war', 'ii'], ['second', 'world', '1940', '1940s', 'war', '1930s', '1945', 'adolf', '1939', 'hitler', 'nazi', 'roosevelt', 'ww2', 'national', '2'], ['1940s', 'world', 'war', 'ii', '1940', '1945', 'nazi', 'wartime', '1947', '1941', '1949', '1942'], ['1940s', 'post-war', 'war', 'years'], ['world', 'second', '1930s', '1939'], ['1930s', '1940', '1940s', '1950', 'war', 'wwii', '–', 'early'], ['20th', 'century', '1930s', 'year', 'antónio', 'years'], ['20th', 'century', 'years', '1930s', 'year'], ['20th', '1940s', 'century', 'references', 'years'], ['year', 'july', 'albert', 'actress', '1930s', 'november', 'president'], ['1940s', '20th', 'century'], ['20th', 'world', 'century', 'war', 'ii', 'years'], ['20th', '1940s', 'century', 'years', 'references'], ['20th', '1940s', 'century'], ['20th', '1940s', 'century', 'years', 'references'], ['world', '1940s', 'year', 'ii', 'adolf', 'war', 'hitler', 'benito', 'july', '1940']]
TOP TOKENS [['intellectual', 'property', 'securing', 'dilution', 'safeguard', 'secure'], ['intellectual', 'property', 'undocumented'], ['intellectual', 'property', 'relations', 'cls', 'define'], ['intellectual', 'property'], ['property', 'intellectual', 'term'], ['intellectual', 'property'], ['intellectual', 'property', 'relations', 'labor'], ['property', 'intellectual'], ['intellectual', 'property', 'interest', 'inventions', 'person’s'], ['property', 'intellectual', 'effectively', 'rights', 'exploit'], ['intellectual'], ['intellectual', 'property', 'australian', 'festival', 'international'], ['intellectual', 'property', 'international'], ['intellectual', 'property', 'deter'], ['intellectual', 'property'], ['intellectual', 'property', 'rights', 'personality'], ['intellectual', 'property', 'secrets', 'derives', 'cls', 'ip', 'based'], ['intellectual', 'property', 'effective', 'summarizing', 'achieve'], ['intellectual', 'property', 'make', 'ip', 'respect', 'future', 'taking', 'relevance'], ['intellectual', 'property']]
TOP TOKENS [['rails', '6', '1,000'], ['rails'], ['rails', 'developers'], ['rail', 'rails', 'volt'], ['rails', 'cls'], ['rails'], ['rails', 'controller||bin/rails', 'bin/rails', 'since', 'convention', 'parts', 'rails_env=development', 'e.g', 'therefore', 'attributes', 'controllers/articles_controller.rb||views/articles/index.html.erb'], ['rails', 'rail', 'black', 'california'], ['rails', "require'rails", 'cls'], ['rails', 'know', 'many', '–', 'programming'], ['rails', 'magazine', 'rail', 'film', 'theater', 'railing', 'ruby', 'layout', 'firearms'], ['rails', 'rail', 'introduction', 'object', 'objects', 'justified'], ['rail', '1941–2019', 'joanes', '1958', '1985'], ['rails', 'rail', 'include', 'also'], ['rails', 'rail', 'style'], ['rails', 'rail', 'system', 'shapes', 'guiderail', 'tools'], ['rails', 'railgun', 'railguns', 'used', 'practice'], ['rail', "rail's", 'plumbeous', 'blackish', 'scraps'], ['rail', 'oregon', '1944', 'may', 'uss'], []]
TOP TOKENS [['nehemiah'], ['nehemiah', 'nehemya'], ['nehemiah'], ['nehemiah', "king's", 'man', 'dispersed'], ['nehemiah'], ['nehemiah'], ["nehemiah's", 'nehemiah', 'perhaps'], ['nehemiah', 'nehemiah’s'], ['nehemiah'], ['nehemiah'], ['nehemiah', 'nəhemya', "judah's"], ['nehemiah', 'nechemiah', 'r', 'honor', 'ca', 'berabi', 'rabbi'], ["nehemiah's", 'nehemiah', 'septuagint', 'cls'], ['nehemiah', 'cls', 'septuagint'], ['nehemiah', 'leader', 'though', 'bhk', 'book', 'time'], ['nehemiah', '1b', 'septuagint', 'text', 'cls'], ['nehemiah', 'cls', 'b', 'also', 'book', 'well'], ['nehemiah', 'section', 'b', 'cls', 'well', 'text'], ['nehemiah'], ['nehemiah', 'septuagint', 'modern', 'jerusalem', 'alexandrinus', 'cls']]
TOP TOKENS [[], ['passed'], ['000', '’', 'throughout'], [], [], [], [], [], ['dictate'], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['rdf', 'recognised', 'found', 'author', 'members', 'uk', 'means', 'increase', 'work', 'though', 'mind', 'memberships'], ['rdf', 'increase', 'give', 'work', 'essentially', 'connected', 'w3c', 'means', 'restricted', 'opportunity', 'available'], ['rdf', 'rdfa', 'short', 'overhead'], ['rdf', 'rdfa', 'using', 'use', 'docuemnts', 'note'], ['rdp', 'rdpbcgr', 'term', 'rdpeudp', '1', 'used', 'simpler', 'fails', 'use', 'successful'], ['rdf', 'rdql', "rdql's", 'becoming', 'model', 'either', 'frameworks', 'created'], ['rdma', 'require', 'tcp', 'offered', 'need', 'developed', 'offers', 'prior', 'recoding', 'take', 'library', 'cls', 'using', 'fails', 'like', 'option', 'physical', 'transferring', 'executing'], ['rda', 'rdas', 'rdi', "rdi's", 'different', 'major', 'cls', 'stronger', 'council', 'allowance'], ['rdf', 'lot', 'provides', '1997', 'develop', 'summary', 'certainly', 'accommodating'], ['rdf', 'rdfa', "to'marry'rdf", 'using', 'real', 'rdfxml', 'people', 'type', 'require', 'world', 'vs'], ['rda', 'within', 'démocratique', 'access', 'sequence', 'code', '1950', 'agent', 'cataloguing', 'rafael', 'africain', 'dietary', 'authority', '1971', 'cdna', 'may'], ['rdma'], ['rdf', 'erbtüchtigen', 'may', 'kingdom', 'charisma', 'w3c', 'kinderreichtum', 'reference', 'particle', 'rapid'], ['rdac'], [], ['01', 'remdesivir', 'rdv'], ['rdf', 'rdflib', 'order', 'python', 'rdfl', '1', 'xml', 'use', '20', 'release', 'object1'], ['rdbms'], ['rdn.pe', 'rdn', 'british'], ['rdf', 'rdfs', 'languages', 'notation', 'parse', 'format', 'graphs']]
TOP TOKENS [['borglum', 'rushmore', 'time', 'head', 'gutzon', 'expertise', '’', 'see'], ['borglum', 'rushmore', 'hand', 'guy', 'mount', 'bold'], ['borglum', 'rushmore', 'hand', 'guy', 'mount', 'bold'], ['borglum', "borglum's", 'rushmore', 'mount', 'including', "burkett's"], ['borglum', '’', 'depression', 'rushmore', 'klu', 'course', 'explosions', 'scene', 'game', 'could'], ['borglum', "borglum's", 'rushmore', 'association', 'mount', 'mountain'], ['borglum', "borglum's", 'rushmore', 'carolina', 'made', 'newark', 'mountain', 'john', 'reno', 'city', 'also', 'glendale', 'works', 'mount', 'gutzon'], ['borglum', 'rushmore', 'burkett', 'chamber', 'originally', 'embolism', '187677', 'mount', 'lincoln', 'rock', '8', 'u', '1934'], ['borglum', 'rushmore', 'hard', 'mount', 'dynamite', 'gutzon', 'end', 'case'], ['borglum', 'rushmore', 'descriptions', 'paris', 'gutzon', 'southeasterly', 'well', 'models', 'art', 'mountain', 'mount', 'chin', '1925', 'take'], ['gatling'], ["borglum's", 'rushmore'], ['borglum', "borglum's", 'rushmore', "sculpture's", "rushmore's", 'gutzon', "pickett's", 'unveiling', '15', 'mt', 'portland', 'memory', 'stamford', 'sculpted', 'depicts', 'magazine'], ["borglum's", 'borglum', 'rushmore', 'mount', 'gutzon', 'project'], ['borglum', 'rushmore', 'mount', 'gunderson', 'support', 'seeing', 'born', 'injustices', 'location', 'gutzon', 'ceremony'], ["borglum's", 'borglum', 'rushmore', "father's", 'alternated', 'york', 'chicago', 'mount', 'exhausting', 'project', 'absence', 'following', '1918', 'works', 'portland'], ['borglum', "borglum's", 'rushmore', 'however', '1923', 'carving', 'thereafter', 'mount', 'remains'], ['gatling', '1893', 'cranked', 'gun'], ['gatling', 'july', '1944', 'action', 'gun', 'tanahmerah', '58', 'francisco', 'occurred', '1943', 'thereafter', 'december', 'california', 'harbor', 'day', 'sea'], ['rushmore', 'borglum']]
TOP TOKENS [['muscles', 'muscle'], ['muscle', '8/28/2013'], ['muscles', 'muscular', 'muscle', 'specific'], ['muscle', 'muscular', 'muscles', 'myofibrils', 'seen', 'disuse', 'underexercised'], ['muscle', 'muscles', 'ask', 'myocardial', 'neuromuscular', 'myocarditis'], ['muscle', 'muscular', 'muscles', 'neuromuscular', 'myofibrils', 'myopathies'], ['muscles', 'muscle', 'muscular', 'biceps', 'source'], ['muscle', 'muscles', 'muscular'], ['muscle', 'muscles', 'muscular', 'away'], ['muscle', 'muscles', 'muscular', 'myofibrils', 'myoblast', 'myocytes', 'endomyscium'], ['muscle', 'muscles', 'cls', 'tropomyosin', 'myogenesis'], ['muscle', 'muscles', 'tissue', 'variation', 'cardiac', 'game', 'musician', 'vertebrates'], ['muscle', 'muscles', 'muscular', 'myoblasts', 'myofibrils', 'myogenesis', 'myofilaments'], ['muscle', 'muscles', 'myofibers', 'myofibrillar', 'extremity'], ['muscle', 'muscles', "muscle's", 'myogenesis', 'myofiber', 'myotendinous', 'myoblasts', 'biceps', 'endomysium', 'myonuclear'], ['muscles', 'muscle', 'muscular'], ['muscles', 'muscle', 'neuromuscular', 'motor', 'mass', 'fibers'], ['muscles', 'muscle', 'muscular', 'myofibers', 'myofiber', 'myogenic', 'myonuclei', 'skeletal'], ['muscle', 'myoblasts', 'myogenesis', 'myofibers', 'myogenic', 'myotubes', 'myoblast', 'dermomyotome', 'skeletal'], ['muscle', "muscle's", 'myogenic', 'myopathy']]
TOP TOKENS [['emmett', 'till', 'louis', 'bryant', 'roy'], ['emmett', 'till', 'chicago', 'states', 'facts', 'cls', 'louis', '28', 'black', 'actually', 'named'], ['emmett', 'tills', 'till', "emmett's", 'cousins', "till's", 'old', 'yet'], ['emmett', 'till', 'old', 'days', '“', 'files', 'louis'], ['emmett', 'till', 'till’s', 'day'], ['emmett', 'till', 'unrecognizable', '2005'], ['emmett', 'till', 'http://www.emmetttillstory.com', "till's", 'till-mobely', 'louis', 'however'], ['emmett', 'till', 'mose', 'forget', 'bryant', 'segregation'], ['emmett', 'till', '1955', '“', 'recalled', 'shoulders', '”'], ['emmett', 'till', 'files', 'days'], ['http://firelightmedia.tv/project/the-murder-of-emmett-till', 'emmett', 'till', "emmett's", 'http://www.pbs.org/wgbh/amex/till'], ['emmett', 'till', "emmett's", "till's", 'concerning'], ['emmett', 'till', 'including', "emmett's", "till's", '—', 'metress'], ['emmett', 'till', "till's", 'various', 'october'], ['emmett', "till's", 'till', 'links'], ['emmett', 'till', "till's", 'center', '2012'], ['emmett', "till's", 'till', 'louis', 'store', 'cls', "uncle's", 'jim', 'roy', 'bryant', 'u', 'son'], ['emmett', 'old', 'till', "till's", "emmett's", 'tills', 'lives', "bryant's"], ['emmett', 'till', 'states', 'also', 'see', 'united'], ['emmett', 'till', "emmett's", "till's", 'louis', 'american', 'mamie']]

Processing features:  52%|█████▏    | 51/98 [24:33<23:36, 30.13s/it]

getting sample prompt forgetting sample prompt for 24013
 24012
getting sample prompt for 24014
getting sample prompt for 24015
getting sample prompt for 24016
getting sample prompt for 24017
getting sample prompt for 24018
getting sample prompt for 24019
getting sample prompt for 24020
getting sample prompt for 24021
getting sample prompt for 24022
getting sample prompt for 24023
TOP TOKENS [[], ['avocado', 'dish', 'ripe', 'mix'], ['well', '2m', 'excellent', 'vigorous', 'upright'], [], ['siegerrebe', 'known', 'well'], [], [], ['bulletproof', 'bite'], [], [], ['ajc', 'champion', 'filly', 'fr', 'oaks', 'thoroughbred', 'nz', 'racehorse', 'including', '1,200m', 'ire', 'plate'], ['tame', 'short-faced', 'along', 'one'], ['one'], ['choreveco', 'mountain', 'possibly'], ['raise', 'domesticated', 'along', 'breeding', 'young', 'due', 'columba', 'feathered'], ['food'], ['footballers', 'expatriate', 'championship', 'players', "men's", 'cup', '1950–1957', 'f.c', 'state'], [], [], []]
TOP TOKENS [['lynn', 'employment', 'swampscott', '2.4-km', 'bay'], ['lynn', 'went', 'factories', 'galaxies', '000'], ['lynn', "word'lynn'is", "children'lynn'it", "to'lynn'to", "word'lynn'who", 'meaning', 'cls', 'line'], ['lynn', 'lynners', 'jobs'], ['lynn', 'today', 'lynnfield', 'cls', 'people', 'county', 'ireson'], ['lynn'], ["lynn's", 'lynn', 'schoolyard', 'rizzotto'], ['lynn', 'norfolk', 'hanseatic'], ['lynn', 'striking', 'lynnmere', 'especially', 'section', 'boston', 'persons', 'congregationalist', '1', 'lincoln', '—', 'african', 'general'], ['lynn', "lynn's", '1629', 'rtes', 'snowy', 'industry', 'south', 'rte', 'boston'], ['lynn', 'lynne', 'lynns', 'lynnville'], ['lynn'], ['lynn'], ['lynn'], ['lynn'], ['lynn', "lynn's", 'playwrights', '’', 'show', 'english', 'century'], ["year.'lynn", 'lynn', '2014', 'american', 'people', 'also'], ['lynn', "lynn's", 'round'], ['lynn', '34', 'i-25', 'geography', 'area'], ['lynn', 'states']]
TOP TOKENS [['oxalate', 'oxalic', 'oxalates', 'milligrams', 'interchangeably', 'acid'], ['oxalis', 'sanity', 'volatile', 'cls', 'inflexible', 'resolve', 'like', 'easy', 'system', 'upon', 'produces', 'viable', 'parts', 'managing'], ['oxalic', 'oxalate', 'oxalis', 'part', 'c', 'precipitates', 'derived'], ['h2c2o4-2h2o', 'oxalic', 'acid', 'oxalate', 'following', 'processes'], ['h2c2o4-2h2o', 'oxalic', 'acid', 'oxalate', 'following', 'processes'], ['oxalsäure', 'oxálico', 'oxalis', 'oxalique', 'oxalic', 'noun||1.||oxalic', 'ox•al′ic', '→', 'ic', 'acid(redirected', 'see', 'water-soluble', 'ac′id(ɒkˈsæl', 'acid'], ['oxalic', '6th', 'oxalate', 'calcium', 'removal', 'poisonous', 'key', 'sublimation'], ['oxalic', 'oxalate', '°f', 'water', 'ion', 'radiators', 'cations'], ['oxalic', 'oxalate', 'calcium', 'removal', 'poisonous', 'key', 'sublimation'], ['oxalic', 'oxalis', 'shape', 'contain', 'also', 'acid', '20-35', 'cluster', 'rosea', 'winter'], ['oxylaena', 'cape'], ['1908', 'developed', 'oxberry', '35', 'south-southeast'], ['oxneria', 'oxner', 'teloschistaceae'], ['oxalis', 'sep'], [], ['oxereae', 'oxera', 'rugosa', 'glandulosa', 'guillaumin', 'brevicalyx', 'gmelinoides'], [], ['nottinghamshire'], ['wangaratta', 'oxley', '1', 'january'], ['oxymitra', 'androgyna', 'oxymitraceae', 'missouri']]
TOP TOKENS [['harness', 'harnesses', 'wire', 'wiring', 'threads'], ['harness', 'test', 'expected'], ['harness', 'harnesses', 'wire'], ['harness', 'harnesses', 'test', 'scenarios', 'component', 'gives', 'cls', 'model'], ['harness', 'harnesses', 'committee', 'standards', 'century', 'manufacturers', 'standardization', 'tied'], ['harness', 'wiring', '10:36:00'], ['harness', 'wiring', 'harnesses', 'controlled', 'mix', '70s', 'since', 'complex', 'aftermarket', 'much', 'cls', 'wire'], ['harness||test', 'harness', 'harness”', '“test', 'test', 'use', 'drivers'], ['harnesses', 'harness', 'wiring', 'produced', 'end'], ['harness', 'harnesses', 'wiring', 'application', 'wire'], ['harness'], ['harness'], ['harness', 'called'], ['harness', 'harnesses', 'kinds', 'aforementioned', 'tightens', 'rely', 'archeological', 'sleds', 'walks', 'dog', 'cls'], ['harness', 'harnesses', 'use', 'around', 'arrest', 'safety', 'make'], ['harness', 'harnesses', '2009', 'test'], ['harness', 'harnesses', 'cable', 'wiring', 'flexing', 'wires', 'wire'], ['harness', "harness'gear", 'seat', 'harnesses', 'climbing', 'guidelines', 'associations', 'manufacturers', 'improvised', 'standardization'], ["harness'conspiracy", "harness's", 'harness', 'greenlit', '2009', 'brodie', '2018', '2011'], ['harness', '1986', 'joined', 'stayed', 'freda', 'life']]
TOP TOKENS [['reactive', 'time', 'question', 'programming', 'within', 'define', 'degree'], ['reactive', 'reactiveasco', 'reactiveml', 'programming', 'systems'], ['reactive', 'past', 'historically', 'us', 'properly', 'programming', 'continue', 'whatever', 'ever'], ['reactive', 'programming', 'behind'], ['reactive', 'programming', 'operation', 'volume', 'contrast', 'insists', 'techniques', 'older', 'focusing', 'generally', 'program'], ['reactive', 'fame', 'programming', 'functional', 'spotted', 'goes'], ['reactive', 'voltage', 'part', 'questions', 'across', 'power', 'current'], ['reactive', 'solutions', 'reactivex', 'programming', 'facilitates'], ['reactive', 'managing', 'need', 'ampere', 'require', 'power', 'enough'], ['reactive', 'understandability', 'code', 'programming', 'gatherings', "enter,'keypress", 'declarative', 'basic', 'devices'], ['reactive', 'interfaces', 'algebra', 'reactivex', 'upon', 'naturally', 'implementing', 'makes', 'imperative', 'based', 'oriented', 'programming'], ['reactive', 'circuits', 'programming', 'inferred', 'various', 'govern', 'later'], ['reactive', 'disambiguation'], ['reactive', 'programming', 'languages', 'used', 'available', 'operators', 'reactivex', 'extensions', 'may', 'item', 'functional'], ['reactive', 'reactivex', 'known', 'languages', 'implementation', 'asynchronous', 'programming', 'extensions', 'also', 'combines'], ['reactive', 'make', 'side', 'programming', 'differentiated', 'oriented', 'problem', '1', 'certain', 'programs', 'potentially', 'characters', 'classes', 'could'], ['reactive', 'different', 'constructed', 'programming', 'explicitness', 'expression', 'term', 'differentiated', 'dynamic', 'order', 'true', 'however', 'higher'], ['reactive', 'language', 'implementation', 'used', 'extensions', 'two', 'operator', 'vary', 'available', 'history', "project's", 'may', 'operators'], ['reactive', 'change', 'ethnicity', 'links'], ['reactive', 'telematics', 'state', 're-usable', 'description', 'full', 'step-by-step', 'according', 'generation', 'uses', 'blocks', 'extensive', 'abilities', 'code', 'ready-to-use']]
TOP TOKENS [['disk', 'disks', 'drive', 'diskspace', 'harddisk', 'hdd', 'harddisks'], ['drives', 'disk', 'drive', 'diskpart'], ['disk', 'disks', 'drives', 'drive', 'partition'], ['disks', 'diskpart', 'disk', 'drive'], ['disks', 'disk', 'drives', 'diskmgmt', 'partitions', 'drive', 'partition', 'raid'], ['disk', 'drive', 'partition'], ['drives', 'disk', 'bytes', 'hard'], ['disk', 'drive', 'drives', 'partition', '38gb', '188'], ['disk', 'disks', 'drive', 'partition'], ['disk', 'hdd', 'partition'], ['disk', 'drive', 'disks', 'drives', "drive's", 'hard', 'file'], ['disk', 'disks', 'drives', 'drive', 'partition', 'partitions', 'hard'], ['disk', 'disks', 'drive', 'drives', 'hard'], ['disk', 'drives', 'hard'], ['disk', "disk's", 'disks', 'write', 'file', 'raid'], ['disk', 'disk-based', 'raid', 'drive'], ['disk', 'drives', 'drive', 'disks', 'hdds', 'hard', 'time'], ['disks', 'disk'], ['disk', 'disks', 'drive', 'drives', 'hard', 'partition', 'storage', 'partitions', 'disc', 'device'], ['disk', 'drive', 'hdd', 'drives', 'hard', 'sata']]
TOP TOKENS [['23', '22', 'afterthought', '69', 'sacrosanct', '3', 'relatively', 'page', 'one', '26', 'experiences', 'evening', 'susceptibilities', '21', 'apart', 'e', 'may', '2'], ['23', '22', 'afterthought', '69', 'sacrosanct', '3', 'relatively', 'page', 'one', '26', 'experiences', 'evening', 'susceptibilities', '21', 'apart', 'e', 'may', '2'], ['field', 'three', 'mcconaughey', 'consecutive', 'cornfield', 'first', 'ultimate', 'earth', 'strange', 'part', 'leave', 'second', 'third', 'animals', 'hard', 'humiliations', 'middle', 'abandons', 'next', 'found', 'refer', 'tell', 'might', 'want'], ['never', 'ever', 'always', "can't", 'please', 'country', 'ooh', "there's", 'sure', 'tois', 'would', 'day', 'one', 'stand', 'greenest', 'given', 'like', "mother's", 'nobody', 'get', "on'cause", 'long', "england's", 'cause', "candle's"], ['pain', 'bulwark', 'kill', 'country', 'guerilla', 'salvadorean', 'comes', 'u.s', 'man’s', 'released', 'attempt', 'orange', 'stayed', 'directly', 'see', 'fighters'], ['air', 'seasons', 'feature', 'comic', 'based', 'park', 'like', 'proposal', 'still', 'last', 'may', 'certain', 'allows', 'issues', 'theme', 'become', 'condemnations', 'exactly', 'direct', 'adopting'], ['air', 'seasons', 'feature', 'comic', 'based', 'park', 'like', 'proposal', 'still', 'last', 'may', 'certain', 'allows', 'issues', 'theme', 'become', 'condemnations', 'exactly', 'direct', 'adopting'], ['page'], ['places', 'cockroaches', 'place', 'heartfelt', 'land', 'one', 'along', 'ever', 'said', 'mission', 'number', 'cut', 'hearts', 'tiny', 'cuddlewell', 'still', 'tend', 'animals', 'dead'], ['earth-orbit', 'released', 'earth’s', 'born', 'http://bit.ly/2rfo7h7', 'via', '“space', 'youtube'], ['horror', 'describe', 'felt', 'released', 'lyrics', 'name', 'titled', '1985', 'sweetest', 'sunrises', "album's"], ['satirical', 'american', 'struggling', 'films'], ['preceding', 'offers', 'middle', 'always', 'plea', "singer's", 'meant', 'sarcasm', 'gentle', 'titular', 'lyrically', 'blissful', "there's", 'eschews', 'whispered', 'later', 'struggles', 'continuously', 'final', 'describes', 'e5', 'one', 'die', 'ruminates', 'delivered', 'adversity', 'cascading', "song's"], ['released', 'finally', 'abridged', 'alternates', 'wish', 'cinematic', 'lack', 'fact', 'corbijn', 'sense', 'united', 'sleeve', 'release', 'political', 'lyrical', 'limited', 'ultimately', 'ideas', "band's", 'c', 'cliches', '–'], ['silhouetted', 'released', 'main', 'never', '22', 'online', 'several', 'remains', 'label', 'similar', '57', 'contain', 'included', 'listing', '28', 'announced', '43', 'maintains', 'proposed', "member's", 'since', 'remaining', '24', '34', 'difference', 'however', 'weeks', "album's", 'another', 'followed', 'january'], ['19', 'us', 'june', "album's", 'recent', 'hopefully', 'august', 'website', "there's", 'released', '9', 'mixed', 'united', 'fanzine'], ['lovely', 'trouser', 'gentle', 'ever', 'corrosive', "like'running", "junkie's", 'trancelike', 'like', '1991', 'ultimate', 'transom', 'except'], ['released', 'film', 'shown', 'release'], ['released', 'pack', 'august', '19', 'october', 'march', 'since', 'der', '28', '6', 'certain', 'end', 'standoff', 'new', 'map', 'releases', 'four', 'permanently', 'contains', 'revealed', 'april', 'may', 'maps', 'packs', 'july', 'purchasing', '11', 'june', 'february', 'xbox', 'third', '25', 'happened', 'would'], ['chillingly', 'mark', 'several', 'poignantly', 'post', 'subsequent', 'harrowing', "asimov's", 'washington', 'deals', '“', 'effect', 'wrote', 'apprehended', 'reception', 'appeared']]
TOP TOKENS [['relaxation', 'another', 'relax', 'relaxed', 'real', 'remain', 'longer', 'one', 'supportively', 'galvanic', 'emg', 'activities', 'may', 'human'], ['relaxation', 'relaxed', 'relax', 'specific', 'techniques', 'deep', 'state', 'relaxing'], ['relaxation', 'awareness', '“', 'practised', 'lopsided', 'people', 'time'], ['relaxation', 'ation'], ['relaxation', 'relax', 'insecurity', 'techniques', 'relaxed', 'remain', 'life', 'learning'], ['relaxation', 'relax', 'relaxed', 'relaxing', 'achieve', 'tense'], ['relaxation', 'practicing', 'life', 'works', 'regularly', 'using', 'wellness', 'enjoyable'], ['relaxation', 'time', 'stress', 'calculate', 'times'], ['relaxation', 'relax', 'practicing', 'true', 'total', 'meditation', 'term', 'practice', 'practitioners'], ['relaxation', 'techniques', 'better', 'practicing', 'relaxing', 'exercises', 'conditions'], ['relaxation', 'relax', 'relaxed', 'technique'], ['relaxation', 'relaxed', 'relaxations', 'solved', 'non-integer', 'over-relaxation', 'two', 'second', 'strategy', 'easier'], ['relaxation'], ['relaxation', 'relaxes', 'time', 'average', 'sciences', 'times'], ['relaxation', 'relaxed', 'remains', 'methods', 'interior', 'method', 'equations', 'generalization', 'study', 'systems', 'theory'], ['relaxation'], ['relax', 'relaxation', 'audio/visual', 'r-e-l-a-x-x-x', 'containing', 'continuous', 'system'], ['relaxation', 'relaxing', 'stress', 'increasing', 'calculations', 'time', 'subsequent', 'relieves', 'thus', 'amount'], ['relaxation', "relax...it's", 'relax', 'leisure'], ['relaxation', 'relax', 'progressive', 'techniques', 'multiple', 'training', 'promoting', 'technique', 'benefits', 'therapy']]
TOP TOKENS [['exosomes'], ['exosomes', 'exosomal', 'called'], ['exosomes', 'also'], ['exosomes', 'exosomal', 'agents', 'tlda', 'secrete'], ['exosomes', 'cell:exosomes', 'exosomal', 'exosome'], ['exosomes', 'exosomal', 'tlda'], ['exosomes', 'exosomal'], ['exosomes', 'exosomal'], ['exosomes', 'exosomal'], ['exosomes', 'exosomal'], ['exosomes', 'exosomal', 'increasingly', 'transducer'], ['exosomes', 'exosome', 'secreting'], ['exosomes'], ['exosomes', 'exosome-like'], ['exosomes', "termed'exosomes'by", 'cls', 'mvb', 'cells'], ['exosomes', 'exosome', 'exosomal', 'secreting', 'another', 'secrete', 'hypothetically', 'metastasis'], ['exosomes', 'exosome', 'exosomal', 'disorders', 'co'], ['exosome'], ['exosoma', 'laboissiere', 'quedenfeldt', 'jacoby'], ['ex']]
TOP TOKENS [['landmark', 'landmarks', 'environment', 'cls'], ['landmark', 'landmarks', 'originally'], ['landmark', 'landmarks', 'study', 'conifers', 'environment', 'natural'], ['landmark', 'landmarks', 'history', 'stunning', 'visit'], ['landmark', 'constitutes', 'definition'], ['landmark', 'also', 'place', 'places', 'highlighting'], ['landmarks'], ['landmarks', 'landmark', 'discoveries', 'thus', 'history', 'use', 'important', 'histories'], ['landmarks', 'landmark'], ['landmark', 'landmarks', 'significance', 'geography', 'environment', 'position', 'salient', 'considered'], ['landmark', 'landmarks', 'keangnam', 'building', 'hanoi'], ['landmark', 'landmarks', 'significance', 'conifers', 'environment', 'cls'], ['landmark', 'called'], ['landmarks', 'landmark', 'landmarkism', 'group'], ['landmark', 'produced'], ['landmark', 'landmarkonthenet.com', 'locations', 'known', 'business', 'limited'], ['landmark', 'pseudo-landmarks', 'landmarks', 'shortly'], ['landmark', 'landmarks'], ['landmark', 'places', 'faust'], ['landmarks', '5:13', 'music', '–', '3:05']]
TOP TOKENS [['regiment', 'unit', 'element', 'division', 'infantry', 'organized', 'form', 'companies', 'elements', '180th'], ['regiment', 'battalion', 'brigade', 'division', '153rd', '77th'], ['regiment', 'february', 'infantry', 'moved', '111th', 'separate', 'w', 'unit'], ['regiment', 'company', 'battalion', 'unit', 'infantry'], ['regiment', 'company', 'battalion', 'unit', 'infantry'], ['regiment', 'unit', 'battalion', 'infantry', 'division', 'units', 'organized'], ['regiment', 'battalion', 'companies', 'company', 'unit', 'organized', 'infantry', 'division'], ['regiment', 'companies', 'unit', 'enlisted', 'cls', 'g', 'company'], ['regiment', '74th', 'infantry', '174th', 'part', 'division', '1943'], ['regiment', 'battalion', 'infantry', 'unit', 'b'], ['regiment', 'fought', '118th', '”', 'units', 'casualties', 'infantry', '118thinfmain', 'brigade', 'private'], ['regiment', 'units'], ['regiment', 'battalion', 'battalions', 'infantry'], ['regiment', 'regiments'], ['regiment', 'infantry'], ['regiment', 'battalion', 'regiments', "regiment's", 'assigned'], ['regiment', 'battalions', 'battalion', '45th', 'division', 'infantry', '157th', 'entire', '177th', 'companies'], ["battalion's", 'battalions', 'battalion', '1944', 'members', 'units', 'formations'], ['regiment', 'battalions', 'unit', 'companies', 'units', 'battalion', 'redesignated', 'reorganized', 'organized'], ['regiment', 'regiments', '19']]
TOP TOKENS [['need', 'door', 'way', 'water', 'hard', 'news', 'something', 'key'], ['275', 'brazil', 'together', 'status', 'e', 'und', '28', '1c6', '202', 'montreal'], ["penis.'i", 'would', 'placed', 'taken', "say,'when", 'n', "say,'was", 'told', "indecency?'police", 'c', "that?'when", "him,'what", 'indecency'], ['telling'], ['seems', 'number', 'getting', 'e'], ['think', 'could', 'turns', 'wrong', 'policyalmanac', 'get', 'retrieved', 'would', 'www', 'provide'], ['might', 'chance', 'good', 'probably'], ['5'], ["jefferson's", 'seeing', 'goes', 'became', 'end', 'pick', 'one', 'means', 'like', 'however', 'represent', 'also'], ['saying'], ['102', '0', '1', '6', '3', '261', 'career', '4', '69', '9', '159', '21', '50', '12', '2', '7'], ['move'], ['0', '6', '850', '335', '2', '240', '12', '133', '3'], ['7', '14', '4', '6', 'www', '29', 'aspx', '9', '48', '3', '8', 'archive', 'default'], ['222', '21', '5', '2', '0', '7', 'style', '6'], ['award', 'earning', 'would', 'made', 'day', 'berkeley', 'later', "maradona's", 'led', 'equal', 'evidential', "italia's", '2'], ['–', 'align', 'bgcolor', '−1'], ['decided', 'said', 'named', 'instead', 'home', 'going', 'one', 'finishing'], ['instead', 'terminated', 'also', 'although', 'departure', 'award', 'wise', 'well'], ['keeping', 'take', 'giving', 'came', 'made', 'ended', 'appearance', 'making', 'matches', 'go', 'would', 'later', 'another', 'throughout', 'side', 'five', 'however', 'including']]

Processing features:  53%|█████▎    | 52/98 [25:01<22:35, 29.47s/it]

getting sample prompt forgetting sample prompt for 24025
 24024
getting sample prompt for 24026
getting sample prompt for 24027
getting sample prompt for 24028
getting sample prompt for 24029
getting sample prompt for 24030
getting sample prompt for 24031
getting sample prompt for 24032
getting sample prompt for 24033
getting sample prompt for 24034
getting sample prompt for 24035
TOP TOKENS [['benefits', 'benefit', '2'], ['benefits'], ['benefit', 'benefits', 'related', 'ineffective', 'management', 'assigning'], ['benefits'], ['benefits', 'enjoying', 'demand', 'demanding', 'result', 'sep', 'taste'], ['benefits', 'www', 'public'], ['benefits', 'benefit', 'estimate', 'minimum'], ['benefit', 'benefits', 'receive', 'existing', 'security', 'total', 'take'], ['benefits', 'benefit', 'qualify'], ['benefits', 'benefit', 'receiving', 'used', 'began', 'within', 'use', 'available', '000'], ['benefits', 'places', 'benefit', 'pre-retirement'], ['benefits.gov', 'benefit', 'https://web.archive.org/web/20070927104323/http://www.cwheroes.org/case_studies/usdepartmentoflabor.pdf', 'government', 'links', 'caregivers', 'apply'], ['benefit'], ['benefit', 'benefits', 'organisation', 'government', 'see', 'begins'], ['benefit'], ['benefit', 'durham', 'big', 'charity', 'risk', 'reliant', 'retirement', 'opt', 'excess', 'often'], ['benefits', 'benefit'], ['benefit', 'benefits', 'help', 'management', 'perceives', 'strategic', 'changes', 'created', 'process', 'consider'], ['benefits', 'benefit', '♥♥ith', 'rush', 'aaron', 'guy', 'march', 'mate', 'rich', 'friends', '2009'], ['benefit', 'benefits', 'public', 'true', 'become']]
TOP TOKENS [['obesity', 'words', 'extreme', 'company', 'year', '’'], ['obesity', 'percent', '5', 'cls', 'age'], ['obesity', 'answers', 'us'], ['obesity'], ['obesity', 'cls', 'cost', '70', 'percentages'], ['obesity'], ['national', 'obesity', 'obesity-related'], ['obesity', '70', 'cls', '50', '80', 'rates'], ['obesity', '2006', 'abstractadult', 'widespread'], ['obesity'], ['obesity', '2004', 'total', '2002', 'rate', 'countries', 'higher'], ['obesity', 'cls', 'year', 'according', 'although'], ['obesity', 'cls', 'education', 'american', 'certain'], ['obesity', 'cls', 'canadian', 'canada'], ['world', 'obesity', 'links'], ['obesity', '1975', 'countries', 'cls', 'century', 'world', 'worldwide'], ['obesity', 'taken', 'society', "king's", '2008', 'childhood'], ['obesity', 'countries', 'severe', 'scarcity', 'overall', 'rates', 'increase'], ['obesity'], ['obesity', 'cls', '85th', '2014', 'adults', 'severe']]
TOP TOKENS [['mediation'], ['mediation', 'mediations'], ['mediation', 'plan'], ['mediation', 'mediations'], ['mediation'], ['mediation', 'statutory'], ['mediation', 'example'], ['mediation'], ['mediation', 'structured'], ['mediation', 'mediations', '“', 'mediated'], ['mediation', 'telecommunications', 'mediation(s', 'billing'], ['mediations', 'special', '1990-1991'], ['mediation'], ['mediation', 'mediations', 'family-mediation', 'co-mediation'], ['mediation', 'outcome', 'mediated', 'process', 'framed', 'therefore'], ['mediation', 'mediate'], ['mediation', 'however', 'significant', 'empirically'], ['mediation', 'mediations', 'attending'], ['mediation', 'underpinnings', '393', 'transformative', 'program'], ['mediation', 'mediated', 'core', 'scenario', 'mediate', 'telecommunications', 'applications']]
TOP TOKENS [['extensively', 'plasterwork', 'sills', 'storey', 'regimented', 'including', 'ledge', 'situated', 'also', 'finishes'], ['made', '’', 'nailers', '”', 'plugs', 'disassembly', 'decomposed', 'disassembled', 'accreted', 'tacking', 'ones', 'replicated'], ['without', 'things', 'onto', 'ceremony', 'forth', 'proper', 'allowed', 'placed', 'chiseled', 'greywacke', 'occasion', 'go', '’', 'made', 'met', 'brought', 'food', 'ceremonial', 'bands', 'music', '“', 'never', 'cornerstone', 'one', 'several', 'often', 'accompanied', 'way', 'many', 'pomp', 'corn'], ['leaded', 'used', 'however', 'dome', '2', 'articulate', 'exchange', 'date', 'exclusively', 'along', 'belonging', 'one', 'provide', 'w'], ['flight', 'iron', 'detailed', 'red', 'arrangement'], ['’', 'like', 'fitted', 'apparently', 'catalogued'], ["governor's", 'ingenuity', 'one', 'detectors', 'keystone-cantilevered', 'dome', 'staircase', 'laying', 'cable', 'coffered', 'ornament', 'kind', 'ceremonies', 'balustrade'], ['needed', 'used', 'carefully', 'including', 'due', 'reframing', 'substantial', 'clips', 'well', 'multitude', 'copper', 'inadequate', 'additionally'], ['us', 'thanks', 'special', '’', 'common', 'sometimes', 'although', 'staircase', 'provided', 'architecture', 'buildings'], ['principal', 'inconel', '”', 'stored', 'corrosion', '–'], ['meetings', 'meeting', 'made', 'something'], ['procedure', 'plain', 'rikarður', 'used', 'wood'], [], ['feature', 'metal', '1931', 'washington', 'scrollwork', 'main', 'd.c', 'found', '15', 'structures'], ['generally', 'rattles'], ['balustrades', 'riveting', '1989remaining', 'unaltered'], ['carillon', 'carillons', 'mechanism', 'carillonist', 'structures', 'buildings', 'reads', 'waymarking.com', 'towerbells.org', 'hammers', '1974', 'equipped'], ['essential', 'made'], ['july', '19', '1884', 'enabled', 'gaol'], ['terracotta', 'cotta', 'aia', 'isabelle', 'stoddart', 'u.s', 'bears', 'corner']]
TOP TOKENS [['counselors', 'counselor', 'counseling', 'employment', 'setting'], ['counselor', 'counselors', 'mean'], ['counseling', 'counselor', 'counselors', 'yes', 'goals', 'conclusion', 'surrounding', '4'], ['counselor', 'counselors', "counselor's", 'counseling', 'assistance', 'cls', 'life'], ['counselors', 'counseling', 'school'], ['counselors', 'counselor', 'counseling', 'counselor’s', 'practicing', 'psychologists', 'groups', 'challenges'], ['counselors', 'counselor', 'counselors’', 'counseling', 'school'], ['counselors', 'counselor', 'counselors’', 'counseling', 'school'], ['counselors', 'counseling', 'counselor', 'guidance', 'situations', 'school'], ['counselor', 'counselor’s', 'counseling', 'school'], ['counselor', 'advertising', 'counseling', 'educational', 'counselor-in-training', 'counsel', 'others', 'credit', 'institute'], ['counselor', 'states'], ['counselor', 'counselors', 'counseling', 'school', 'expansive', 'selection', 'transitions'], ['counselor', 'counselors', 'counseling', 'cls', 'school', 'asca', 'education', 'students', 'framework', '2012', 'inappropriate', 'schmidt'], ['counselors', 'counseling', 'counselor', 'school', "counseling's"], ['counselor', 'counselors', 'counseling', 'school', 'programs', 'career', 'implemented'], ['counselors', 'counselor', 'counseling', 'certified'], ['counseling', 'counselor', 'outlines', 'co-counseling', 'disciplinary'], ['counselor', 'counseling', 'counselors', 'certified', "master's", 'dependence'], ['counseling', 'counselor', 'counselors', 'practice', 'certified', 'supervised', 'licensure', 'professional', 'licensed']]
TOP TOKENS [['drusen', 'druse', 'hard'], ['drusen', 'showing', 'md'], ['drusen'], ['drusen', 'drusenoid', 'drusen4', 'druse', 'pseudodrusen', 'choroid', 'choriocapillaris'], ['drusen', 'degeneration', 'waste', 'oxidized', 'degenerations', 'create'], ['drusen', 'older', 'apart', 'scattered'], ['drusen', 'within', 'pseudodrusen', 'disease', 'components', 'presence', '9', 'e', '10', '11', 'epithelial', 'secondary', "bruch's", 'reticular', 'histological', 'two'], ['“drusen”', 'drusen', 'coalescent', 'isolated', 'innocuous', 'photoreceptors', 'debris', 'choriocapillaris', 'overwhelm', 'known', 'underlying', 'epithelial', 'photoreceptor', 'overlying', 'atrophic'], ['“drusen”', 'drusen', 'coalescent', 'isolated', 'innocuous', 'photoreceptors', 'debris', 'choriocapillaris', 'overwhelm', 'known', 'underlying', 'epithelial', 'photoreceptor', 'overlying', 'atrophic'], ['drusen', 'large', 'impacted', 'also', 'composition', 'photoreceptor', 'photoreceptors', 'proteins', 'associated', 'decreased', 'amd', 'exhibit', 'marked', 'morphologic', 'figure', '22', '152', '145', 'implicated', 'epithelium'], ['drusen', 'deprive', 'disc', 'cases'], ['drusen', "drusen'may", "drusen'which", 'druse', 'amd', 'extracellular', 'related', 'pigment', 'ophthalmoscopy', 'cases', 'epithelium'], ['hausen', "hausen's", 'degrades', 'laevis', 'well-reviewed', 'peter', 'career', 'ph.d', 'rna/dna', 'focused', 'research', 'virology'], ['hausen', 'st', 'marne', 'von', 'einem', '1914', 'lion', 'zahringer', 'april', '1', 'deutschen', '20', 'der', 'cross', 'stellenbesetzung', 'firstworldwar', 'may', 'heere', 'osnabruck', 'wegner', 'years', 'verlag'], ['bekzod'], ['cousens', 'performing', 'major', 'talent', '2012–13', 'number', 'community', 'went', 'director', 'todd', 'career', 'productions', 'work', 'portrayed', 'love', 'misérables', 'spent', 'services', 'based', "london's", 'featured', 'worked', 'theatre', 'international', 'educated', 'year', 'appeared', 'also', 'include', 'nida', 'australia', 'studying', 'roles', 'company'], ['crusell', "crusell's", 'autobiographies', '1814', 'musikalische', 'c', 'musique'], ['scrutinized', 'cryptocurrency', 'professional', 'activities', 'embellishments'], ['ingevald', 'crusebjörn', 'fougt', '1878–1966', '1903', 'major', '23', 'frans', 'members', '1901'], ['damuseau', 'savoie', "d'ouverture", 'liège–bastogne–liège', 'race', 'du', 'sportspeople', 'paris–troyes', 'boucles']]
TOP TOKENS [['contained'], ['six', 'scene'], [], ['4', 'reason', 'ark', 'proposed', 'say', 'including', 'following', 'others', 'however'], ['—', 'shandumba'], ['asia', '50'], ['america', 'sustains'], ['hidden', 'existence', 'surviving', 'knauth', 'lest', 'according', 'said'], [], ['killing'], ['perez', 'america', 'latin', 'americas', 'mexico', '7', 'stasiak', '20', '13', '21', 'ranked', 'announced', '31', '16', 'ufc', '5', '15', '30'], ['brand', 'perez', 'season', "beermen's"], ['perez', '–', 'states', 'center', 'united', '17', '12', 'texas', 'however', 'due', '2023', '29', 'nevada', 'fight', '216'], ['america', 'perez', 'bantamweight', 'latin', 'cannetti', 'fredy', 'mexico', 'championship', 'ufc', 'show', '13', 'however', 'revealed', '17', '2017', '21', '3', '2014', '15', '10'], ['america', 'perez', '–'], [], ['pérez', '2018', 'patrick', 'players', '2021', 'american', 'links', '2020', 'people', 'season', "men's"], ['perez', 'championship', '126', 'american'], ['pérez', 'alejandro', 'c.d', '2018', 'perez', 'vázquez', 'mexico', "men's", 'mexicano', 'jalisco', 'players', 'cafetaleros', 'ascenso', 'guadalajara', 'clausura', 'mx', 'links', 'mexican', 'de', 'christian', 'births', 'querétaro', 'balompié', 'footballers'], ['american', 'mexicali', 'pérez', 'soles', 'mexico', 'team', 'career', 'players', 'olympics', 'professional', 'sportspeople', 'stats', 'latinbasket.com', 'state']]
TOP TOKENS [['“portable”', 'portable', 'portables', 'easily'], ['portable', 'portableapps.com', '2'], ['portable', 'portables', 'handheld', 'white', 'portability', 'computer'], ['portable', 'use', 'conventional', 'spectrum', '000', 'matter', 'compact'], ['portable', 'term', 'hear', 'seen'], ['portable', 'many', 'cls', 'usually', 'category', '488', 'personal'], ['portable', 'portable-programme', 'portable-soft', 'mean', 'computers', 'term'], ['portable', 'good', 'possible', 'single', 'use', 'cls'], ['portable', 'easy', 'handheld'], ['portable', 'makeshift', 'use', 'using', 'ladders', 'incorrect'], ['portable', 'portable.tv', 'brisebois'], ['portable', 'portables', "called'portable", 'compact', "workstations'or'portable", 'personal', 'wearable', 'major', 'together', 'cls', 'handheld', 'term', 'remain'], ['portable', 'portableapps', 'blenderportable', 'irfanview', 'single', 'launchy', 'list'], ['portable', 'another', 'portability', 'definition', 'installable', 'behavior'], ['portable', 'advantage', 'irrespective', 'detractors', 'mangling', 'cross-platform', 'nondeterminism', 'deprecated', 'systems', 'programming', 'computer'], ['portable', 'portableapps', 'however', 'firefox'], ['portable', 'manufacturer', 'floor', 'rather', 'impracticable', 'accordion-style', 'also'], ['portable', "portable's", 'appropriate', 'retains', 'firefox', 'known'], ['portable', 'encoding'], ["portable'stationary", 'portable', "first'semi", 'often', 'tractors', 'water', 'trucks', 'although', 'either']]
TOP TOKENS [['change', '—', 'used', 'plan', 'going', 'unlikely', '’', 'rely', 'since', 'fresh', 'still', 'cleaner'], ['tried', 'anyone', 'really', 'stop', 'madness', 'inheritance', 'dumbasses'], ['freaking', 'read', 'physical', 'brain-ish', 'garden', 'involved', 'everything', 'entire', 'orneriness', 'given', 'midget', 'i’d', 'cristata’s', 'pretty', '‘gibraltar’', 'topped', 'information', 'damage', 'generally', 'i’ve'], ['developed', 'switching', 'consider', 'recently', 'sorry', 'literally', 'havoc', 'interferes', 'got', '…', 'know', 'spray', 'kratom', 'said', 'difficult', 'wreaking', 'time', 'issue', 'effectively', 'ways', '”', 'hip', 'btw', 'every', 'probably', 'full', 'anything', 'selfdecode', 'kids', '“', 'mind', 'umm', 'strongly', 'crap', 'someone', 'also', 'even', 'ended'], ['heard', 'analyst', 'ingredient', 'entire', 'never', 'quarters', 'impacts', 'apart', 'cushy', 'essential', 'shutting', 'separated', 'colorless', 'probably', 'closed', 'transformed', 'crack', 'inside', 'u', 'parts', 'used', 'care', 'almost', 'foundation', 'much', 'percent', 'given', 'kothari', 'common', 'safely', 'detroit', 'polystyrene', '”', 'work', 'industry', 'synthetic', '’', 'ripens'], ['serious', 'practical', 'gone', 'topic', 'required', 'found', "let's", 'normally', 'oxidizing', '’', 'using', 'list', 'work', 'interested', 'apparently', 'igniting', 'amounts', 'consequence', 'hear', '“', 'looking', 'use', 'known', 'already', 'co', 'flamethrowers', 'go', 'plain', 'burnt', 'potentially', 'germans', 'sensible', 'one', 'fluorinating'], ['said', 'kill', 'pre', 'mixture', 'none', 'non', 'solution', 'almost', 'accept', 'ready', 'lot', 'time', 'ease', 'dabbing', 'regret', 'sacrifices', 'prevent', 'bad', 'details', 'four', '·', 'sure', 'recommend'], ['actually', 'owning', 'one', 'u', 'owner', '60', 'major', 'percent', 'limited', 'majority', '2010', '80', 'made', 'circumstances', 'standards', 'investment', '—', 'participation', 'reportedly', '’', 'johnson', '2002', 'retirements', 'nelly'], ['aware', 'willing', 'massive', 'near', 'require', 'understanding', 'companion', 'ensure', 'use', 'advance', 'considerations', 'need', 'scoping', 'solid', 'severely', 'groomer', 'set', 'etc', 'afford', 'heat', 'employing', 'plan', 'adopting', 'look', 'prepared', 'undergoes', 'specified', 'endured', 'stage', 'take', 'becoming', 'female', 'well', 'may'], ['thought', 'learned', 'finally', 'knowledge', 'bringing', 'months', 'take', 'unnecessary', 'newly', 'process', 'practice', 'overcome', '’', 'discussing', 'never', 'topics', 'would', 'paused', 'issue', 'bed', 'asking', 'work', 'talk', 'given', 'think', 'felt', 'ever', 'day', 'edges', 'found', 'openly', 'concerning', 'upon'], ['force', 'approved', 'cutthroat', 'limit', 'hands', 'choice', 'already', 'portion', 'extremely', 'significant', 'disney'], ['surgical', 'reduction', 'necessitating', 'cessation', 'suppress', 'reverts', 'negatively', 'partial', 'impact', 'severe', 'extremely', 'period', 'reportedly', "woman's", "adolescent's", 'rate', 'hypertrophy', 'onset', 'time', 'however', 'experienced', 'every', 'typically', 'within', 'years'], ['radically', 'used', 'shrunken', 'master', 'shrink', 'made', 'touches', 'use', 'also', 'grow', 'changing', 'altering', 'absorb', 'karate', 'permanence', 'based', 'order', 'effect', 'discharging', 'derive', 'born', "creation's", 'occasions', 'took', 'patterns', 'result', 'built', 'everything', 'contains', 'judo', 'properties', 'different'], ['anymore', 'someday', 'extensively', 'required', '2015', 'probably', 'know', 'soon', 'cure', '2017', 'filomensky', 'modified', 'g', 'interregional', '2007', 'need', 'quest', 'entirely', 'someone', 'commission', 'affliction', 'inquiring', 'garces', 'think', '25', 'institute', 'may', 'undoubtedly', 'practical', '35', 'official', 'would', "guitarist's", '2008', 'treatment', 'fellow', "overshopper's", 'rag', 'cool'], ['permanently', 'internalisation', 'deactivates'], ['permanently', 'detrimental', 'assimilated', 'adaptability', 'assimilates', 'effects', 'complete', 'prototype', 'damage', 'understood', 'utilize', 'matter', 'assimilation', 'causing', 'detonable', 'completely', 'inception', 'invasive', 'form', 'comprehend', 'copies', 'target', 'convert', 'nature', 'instabilities', 'condition', 'based', 'make', 'rapid', 'hold', 'due', 'particles', 'various', 'shape', 'strapped', 'initially', 'caused'], ['via', 'nigh', 'decimate', 'procedure', 'risk', 'uncontrollable', 'given', 'rupturing', 'means', 'extracting', 'rend', 'end', 'preventing', 'damage', 'incorporates', "frost's", 'zero', 'sufficiently', 'making', 'enough', 'rate', 'paramount', 'discomfort', 'perforate', 'invulnerable', 'sharp', 'enhancements', 'laser', 'things', 'knitting', 'cracking', 'one', 'based', 'form', "harden's", 'degree', 'etc', "ronnie's", 'little', 'dense', 'relative', 'easily', 'sustained', 'detonation', 'relatively', 'effected', 'emits'], ['end', 'becoming', 'brainstorming', 'think', 'assumed', 'shell'], ['end', '2020', '2021', 'combined', 'issues', '2017', 'osasuna', "supporters'group", 'limited', 'club', 'would', '5', '36', '2015', 'deportiva', '2011', 'made', 'due', 'roughly', 'june', '1', 'f', "supporters'society", 'anonima', 'ltd', 'owned', 'exchange', 'legally'], ['know-it-all']]
TOP TOKENS [['hungary', 'hungarian', 'monarchy'], ['hungary', 'hungarian'], ['hungarian', 'hungary', 'budapest'], ['hungarian', 'hungary', 'budapest'], ['hungarian', 'hungary', 'budapest'], ['hungary', 'budapest', 'hungarian'], ['hungary', 'varies', '15', 'budapest', 'hungarian', 'magyar'], ['budapest', 'hungary', 'cities', '10', '26', 'daily', 'szepasszony'], ['hungary', 'hungarian', '1989', 'year', "hungary's", 'bleak', 'budapest'], ['hungarian', 'hungary', '1000', '220', 'magyar'], ['hungary', 'hungarian', 'national'], ['hungary', 'hungarian', 'budapest', '5', 'relations'], ['hungarian', 'hungary', 'vitez', 'bolyai'], ['hungary', 'hungarian'], ['hungarian', 'hungary', "hungary's", 'budapest', 'corps'], ['hungary', 'hungarian', 'budapest', 'agglomerations', 'seventeen'], ['hungarian', 'hungary', 'atlatszo', 'budapester'], ['hungary', 'hungary’s'], ['hungary', 'hungarian', "hungary's", 'budapest', 'gosztonyi'], ['hungarian', 'hungary', "hungary's", 'age', 'assertions']]

Processing features:  54%|█████▍    | 53/98 [25:31<22:16, 29.69s/it]

getting sample prompt forgetting sample prompt for 24037
getting sample prompt for 24038
 24036
getting sample prompt for 24039
getting sample prompt for 24040
getting sample prompt for 24041
getting sample prompt for 24042
getting sample prompt for 24043
getting sample prompt for 24044
getting sample prompt for 24045
getting sample prompt for 24046
getting sample prompt for 24047
TOP TOKENS [[], ['teacher'], ['favourite'], ['friend,parents,or', 'teacher’'], ['“a', 'teacher', 'one'], ['teacher’s', 'teacher'], ['teacher', 'favourite', 'dear', 'best', 'teachings', 'teachers', 'great'], ['teacher', "teacher's", 'conducive', 'idolized', 'teachers', 'great', '’'], ['teacher’s', 'teachers', '“teachers'], ['teacher’s', 'teacher', 'serving', 'teachers'], ['ayache-vidal', 'player', 'hřebejk', 'cortázar', '2023', 'tennis', 'olivier', 'sorter', 'fidell', 'avedis'], ['teacher’s', 'teachers', 'teacher', 'sarvepalli', 'teachers/gurus', 'worship'], ['teacher', 'robert'], ['comedy-drama', 'teachers'], ['czech', 'drama', 'film'], ['teacher'], [], ['teacher', '1988', 'film', '2019', 'educator', 'belgian', 'disambiguation'], [], ['teacher', 'educator', 'e', 'g', 'may', 'specific', "teacher's", 'teaching', 'also', 'called', 'serve', 'cls', 'rather', 'anyone', 'perform', 'formally', 'schoolteacher']]
TOP TOKENS [['sgml', "sgml's", 'structure', 'problems', 'data', 'available', 'small', 'exists'], ['sgmlintro', 'sgml', 'sgmldecl', 'express', 'discussion', 'languages'], ['sgml'], ['sgml', 'web', 'equal', 'proper'], ['sgml', 'tag', 'regular', 'tags', 'element', "tag's", 'many'], ['sgml', 'sgmlshort', 'document', 'ways', '1986'], ['sgml', 'concrete', 'arbitrary', 'nodes', 'short', 'characterize', 'dynamically'], ['sgp', 'sgps', 'sgo'], ['sgml', 'parsing', 'since', 'plays', 'parsers', 'called', 'projects', 'valuable'], ['sgml', 'text', 'groups'], ['sg-1', 'sgr', 'sgr-a1', 'railway', 'constellation', 'substantia', 'standard', 'abbreviation', 'code', 'sécurité', 'risparmio', 'rolando', 'shaw', 'madaraka', 'stargate'], ['sgm', 'visual'], ['sg&a', 'sga', 'sg-1', 'samsung', 'startup', 'throughput', 'produced', 'synthetic', 'birth', 'aviation', 'effort', 'swanson', 'advance'], ['sgma'], ['sgm', 'sg-43', 'south', 'singa', '1-19', 'schweizer', 'series', 'stadsgewestelijk', 'sea', 'st', 'cornwall', 'geological', 'sleepytime', 's&p/asx', 'ministries'], ['sgp', '1-1', 'paraguay', 'processing', 'staatkundig', 'problem', 'model', 'general', 'sozialistische', 'simmering-graz-pauker'], ['sgro', 'sgouros'], ['sgo', 'st', 'station'], ['sgv', 'shikand-gumanig', 'schifffahrtsgesellschaft', 'gorres', 'sycip'], ['sgis']]
TOP TOKENS [['textual', 'provided', 'exist', 'reasons', 'benefit', 'include', 'prefixes', 'available', 'specifications', 'military', 'others', 'including'], ['whether', 'contain', 'short', 'consumables', 'items', 'include'], [], [], [], ['well', 'available', 'full', 'range', 'suit', 'multiple', 'come', 'including', 'see'], ['well', 'available', 'full', 'range', 'suit', 'multiple', 'come', 'including', 'see'], ['released', 'included'], ['well', 'suit', 'full', 'range', 'multiple', 'including', 'available', 'come'], [], ['dvd', 'log', 'features', 'dvds', 'plus', 'special'], ['version', 'made', 'accessories'], ['support', 'line', 'software', 'also', 'exist', 'besides', 'dos', 'requested', 'variables'], ['versions', 'released', 'contains', 'includes', 'tuxedo'], ['production', 'versions', 'version', 'continued', 'use', 'grille', 'trims', 'pickups', 'engines', 'wheels', 'black', 'could', 'given', 'ended', 'drive', 'received', 'except', 'successive', 'also', 'flares', 'year', 'following', 'generation', '1500s', '5', 'included'], ['versions', 'produced', 'options', '4wd', 'added', 'models', 'one', 'shows', 'ds0', 'mouldings', 'stabilizer', 'uses', 'sideskirts', 'version', 'ar1'], [], ['vehicle', 'combat', 'novels'], ["collector's", 'released', 'production', 'edition', 'vehicle', 'grille', 'camaros', 'units', 'come', 'available', 'steering', 'equipped', 'stripes', 'spoiler', 'output', 'paint', 'moldings', 'models', 'trims', 'car', 'badging', 'receiving', 'receive', 'features', 'matte', 'featuring', 'also', '1ls', 'lt', 'nuts'], ['released', 'version', 'mouldings', 'cars', 'sedans', 'featured', 'spoiler', 'trims', 'including', 'velour', 'rims', 'sedan', 'known', 'made', 'retrimmed', 'inserts', 'consisted']]
TOP TOKENS [['pinnacle', 'word', 'dictionary'], ['pinnacles', 'pinnacle', 'centuries', 'pinnaclearticle'], ['pinnacled', 'pinnacle', 'translation', 'word', 'many'], ['look', 'pinnacles', 'pinnacle', 'two', 'verticity'], ['pinnacles', 'prowess', 'souvenirs', 'go', 'resplendent', 'hike', 'construction', 'nature', 'national'], ['pinnacles', "pinnacles'climbing", "pinnacles'park", 'time', 'regulations', 'gear', 'curious', 'gulch', 'much', 'peaks', 'unknowingly', 'add', 'climbs'], ['pinnacles', 'back', 'volcano—its', 'denizens', 'chaparral-covered', 'today', 'years'], ['pinnacle', 'pinnacles', 'fissures', 'parallel', 'higher', 'volcanics', '1', 'cls', 'surface', 'buried', 'quartz', 'master'], ['pinnacles', 'consider', 'much', 'specifically', 'compant'], ['pinnacles', 'experience', 'site', 'however', '’'], [], ['pinnacle', '1901', 'sse', 'remains', '1894', 'stuccoed', 'one', 'two'], ['first', 'pinnacle', 'forest'], ['pinnacles', 'foods', 'pinnacle', 'ecuador'], ['pinnacle', 'pinnacles', 'queensland', 'townsville', 'rock'], ['pinnacle'], ['pinnacles', 'pinnacle', 'scottsdale', 'whatcom', 'disambiguation'], ['pinnacles', 'black-throated'], ['pinnacle', 'line', '2008', 'although', '013'], ['pinnacles', 'pinnacle', 'de']]
TOP TOKENS [['ruby', 'rubyist', 'works', 'sense', 'whatnot'], ['ruby'], ['ruby', 'rubyʼs', 'heritage', '1995', 'use', 'thinks'], ['ruby', 'mit'], ['ruby'], ['ruby', 'ones', 'style', 'amp'], ['ruby'], ['ruby'], ['ruby', 'rubyfan'], ['ruby'], ['https://github.com/ruby/spec', 'ruby', 'rubyspec'], ['ruby'], ['ruby', "11'ruby", 'basic', 'name', 'cool', 'u'], ["ruby's", 'ruby', 'property', '199', 'java', 'significant', 'used', 'etc', 'object', 'shell', 'literal'], ['ruby'], ['ruby', 'rubyforge'], ['ruby', "ruby's"], ['ruby', '1940', 'reuben'], ['ruby', 'notably', 'functions', 'stdlib', '2018', 'fixes', '2', '2016', 'gserver', 'operations', 'keys'], ['ruby', '“mod_ruby”', 'mod_ruby', 'ruby’s']]
TOP TOKENS [['pregnancy', 'pregnant', 'frequently'], ['pregnancy', 'pregnant', 'throughout'], ['pregnancy', 'pregnant', 'become', 'complicate'], ['pregnant', 'pregnancy', 'chronic', '’', 'cls'], ['pregnant', 'pregnancy', 'trimester', 'time', 'sometimes'], ['pregnant', 'pregnancy'], ['pregnancy', 'pregnant', 'trimester', 'away'], ['pregnant', 'pregnancy', 'whilst'], ['pregnancy', 'pregnancy-induced', 'pregnant'], ['pregnancy', 'pregnant'], ['pregnancy', 'pregnant', 'pregnancy-related'], ['pregnancy', 'pregnant', 'weeks', 'trimester', 'experienced', 'inside'], ['pregnant', 'pregnancy', 'trimester', 'deviations', 'unchanged', 'woman', 'occur', 'dispensed', 'women'], ['pregnancy', 'pregnant', 'non-pregnant', 'however', 'covid-19'], ['pregnancy', 'pregnant', "recognized'pregnancy", 'persons', 'furthermore', 'individuals', 'advances'], ['pregnancy', 'pregnant', 'trimesters', 'different', 'severe'], ['pregnancy', 'pregnant', 'trimester'], ['pregnancy', 'pregnant', 'trimester', 'healthy', 'woman'], ['pregnancy', 'pregnant', 'trimester', 'hypercoagulability', 'also', 'pregnancies'], ['pregnancy', 'pregnant', 'gestation', 'problems']]
TOP TOKENS [['eavesdrop', 'eavesdropping', 'abroad', 'eaves', 'eau', 'eavesdropper', 'boats', 'flow', 'listener', 'cf', 'cologne', 'eyelashes', 'v', 'private', 'brandy', 'vitae'], ['crossing', 'announcment', 'chic', 'even', "nintendo's", 'boards', 'towns', 'update', 'house', 'ww'], ['cls', 'actually', '”'], ['maxis', 'interview', '2', '2000', 'sims', '1997', 'later', 'ifying', 'said', '—', '2004'], ['sky', 'access', "hotel's", 'information', 'encrypted', 'altogether', 'solution', 'networks', 'ceos', 'along'], [], ['orian'], ['workshop', 'sims', 'writers', 'back', 'whole', '’', 'something', 'working', 'ever', 'basically', 'thing', '98', 'see', 'since'], ['tab'], [], ['2019', 'certifications', 'project', 'album', 'riaa', 'released', 'follow-up', '28', 'billboard'], ['personnel', 'albums', 'credits', "album's", "rupaul's", '11', '18', 'artist', 'take', 'american', 'released', 'vocals', '23', '16', '21', 'stewart', 'exes', 'composer', '–', 'release', 'clair', 'queen', 'murphy', 'also', 'reception', 'nicopop', 'references', 'producer'], ['albums', "clair's", "rupaul's", 'references', 'american', 'appearances', 'one', 'births', 'number', '21', '12', 'notes', 'discography', 'released', 'identity', 'living', 'singles', 'single', 'people'], ['capaldi', 'awards', 'best', '•', 'lewis', "spotify's", 'official', 'lyrically'], ['awards', 'also', '1', 'best', 'award', 'fromand', "hamilton's", '100', '5', 'singles', 'billboard', 'number', '4', 'hot'], ["rupaul's", 'american', 'one', '27', 'single', 'cls', 'released', 'well', 'school', 'track', '26', 'clair'], ['chic', 'downtown', 'school', 'romance', 'update'], ['list', 'mixing', 'production', '–', 'charts', 'engineering', 'ones', 'albums', 'ricci'], ['release', '–', 'production', "america's", 'references', 'singles', 'chris', 'written', 'songwriting', "ochoa's", 'personnel', 'vocals', 'programming', '2018', 'summits'], ['cls', 'x', 'versions', '15', "platform's", '3', '2', 'maxis', 'version']]
TOP TOKENS [['samuel', "samuel's"], ['samuel', "samuel's", 'tradition', 'cls', 'el', 'singing'], ['samuel', 'although', 'trans'], ['samuel', "samuel's", 'cls', 'tradition', 'el', 'singing', 'unifier'], ["samuel's", 'samuel', 'samuele', 'oratorio', 'sam'], ["samuel's", 'samuel', 'faults'], ['samuel', "samuel's", 'present', 'god'], ['samuel', 'samuel(noun', 'l'], ['samuel', 'ht', 'sources'], ['samuel', "samuel's", 'cls', 'name', 'sarah', 'eras', '7', 'bible', 'zuph'], ['samuel'], ['samuel'], ['samuel', 'links', '7', 'uk'], ['samuel'], ['samuel', 'samuela', 'samueli', 'samuelle', 'samuelu', 'l'], ['samuel', '1864–1947', '1896–1984'], ['samuel', "samuel's", '2010', 'featured', 'biography', 'jpatt', 'grammy-nominated'], ['samuel', 'sam'], ['samuel', '1868–1943'], ['samuel']]
TOP TOKENS [['bubbles', "bubble's", 'bubble', 'actually'], ['bubble'], ['bubbles', 'bubble'], ['bubbles', 'bubble', '“', 'asset'], ['bubbles', 'bubbleˈbʌb', 'bubble', 'air', 'market', 'sphere', 'produce', 'bubbling', 'material', 'word', 'guggle'], ['bubbles', 'bubble'], ['bubbles', 'bubble', 'fingers', 'fascinating', 'sooooooooo', 'they,though'], ['bubbles', 'bubble', 'hand', 'producing', 'science', 'cups', 'great'], ['bubbles', 'bubble', 'science', 'wondering'], ['bubbles', 'bubble'], ['bubble', 'miyako', 'bubbles', 'devere', 'yablonsky'], ['bubble', 'bubbles', 'soap', 'thus', 'cls', 'life', 'effect', 'substance', 'liquid', 'bubblegram', 'state', '1', 'reactions', 'nucleation', 'e'], ["bubbles'four", 'bubbles', '1925', 'years', 'abcs', 'monarchs', 'barons', 'foundation', 'stearnes', 'later'], ['bubbles', 'bubble', 'w', 'soap', 'author'], ['bubble', 'bubbles', 'justify', 'justified'], ['bubble', 'bubbles', 'page', 'causing', 'soap', 'education'], ['bubbles', 'bubble', '3898', 'links', '1944', 'external', 'make-believe', 'mack', 'old', 'acts', 'features', 'bros', 'apparatus'], ['bubble', "bubble's", '2019', 'purposes', 'tutorials', 'education', '2023', '2021', 'offers', 'size', 'cls', 'squarespace', 'straschnov', 'york', 'group', 'allows'], ['bubbles', 'bubble', 'dramatically', 'period', 'would', 'prices'], ['bubbles', 'simulation', "bubbles'full", 'cls', 'clattenburg', 'strength', 'julian', 'courts', 'usa']]
TOP TOKENS [['specific', '»', 'demonstrations', 'right', 'makes', 'download'], ['demonstrations', 'right', '»', 'wolfram', 'note', "web's", 'hand', 'knowledge', 'specific', 'makes'], ['right', 'demonstrations', 'specific', '»'], ['demonstrations', '»', 'right', 'specific', 'wolfram', 'makes', 'note', 'every', 'read', 'hand', 'download', 'demonstration', 'may'], ['demonstrations', 'right', 'wolfram', 'makes', 'read', 'download', 'hand', 'note', 'demonstration'], ['demonstrations', 'specific', 'hand', 'right', 'note', 'already', 'wolfram', 'makes', 'demonstration', 'download', "web's", '»'], ['demonstrations', 'right', 'specific', 'wolfram', 'makes', '»', 'hand'], ['demonstrations', 'right', 'specific', '»', 'makes', 'download'], ['demonstrations', 'right', 'specific', 'download', 'makes', "web's", 'wolfram', 'demonstration', 'note', 'already'], ['demonstrations', 'knowledge', 'wolfram', 'demonstration', 'right', 'specific', 'note', 'hand', 'download', '2017', '»', 'makes', 'creating'], ['demonstrations', 'interactively', 'wolfram', 'fields', 'population', 'response', "wolfram's", 'slider', 'demonstration', 'direct', '10,000', 'piece', 'run', 'snippet', 'recomputes', 'downloaded', 'includes', 'graphics'], [], ['tavakilian', 'paramelitta', 'pseudisthmiade', 'phygopoda'], [], [], [], [], [], [], []]
TOP TOKENS [['edmontonians', 'edmonton', 'still'], ['edmonton', '8', '17'], ['edmonton', "edmonton's", 'start', "sorrentino's", 'including', 'another', 'backgrounds', 'italy', 'chain', 'city'], ["edmonton's", 'edmonton', 'street', 'university', 'core', 'areas', 'ne', 'recommended', 'complete', '2016'], ['edmonton', 'context', 'beauty', 'overall', 'equality', 'immigrants'], ['edmonton', 'dressings', 'chapel', 'fn', 'pebbledash', 'belonging', 'sanctuary'], ['edmonton', '’', 'power', 'essential', 'plan'], ['edmonton', "edmonton's", 'range', "that's", 'hot', 'locales', 'widely', 'duration'], ['edmonton', 'edmontonians', '8', '270', '1970', 'types', '’', 'starts', '80', 'decade'], ['edmonton', 'edmontonians', "edmonton's", 'extensively', 'common', 'generations', 'arrived'], ['edmonton', 'reading', 'one', 'may', 'much', 'genuki', 'references', '1969'], ['edmonton', 'road', 'years'], ['edmonton', 'street', 'church', 'house'], ['edmonton', "edmonton's", 'scott', 'tun', 'mushroomed'], ['edmonton', "edmonton's", 'cargo', 'stores', 'centres', 'centre', 'river', 'retailers', 'mall', "city's"], ["edmonton's", 'edmonton', 'city', 'basswood', 'america', 'week', 'lakes'], ['edmonton', 'growth', 'around', 'census', 'cyclone', 'increased', 'grown'], ['edmonton', 'vessel', 'edmonton-castle', 'edmonton-whitemud', 'railway', 'north', 'canada', 'west', 'nll', 'anglican', 'middlesex', 'based'], ['edmonton', "edmonton's", 'river', 'america', '16'], ['edmonton', 'existence']]
TOP TOKENS [['chapter', 'next', 'unnecessarily', 'previous', 'cls', 'inconspicuously', 'least', 'knowing', 'groups', 'friends', 'workers', 'want', 'fellow', 'immorality', 'word'], ['chapter', 'predicament', 'indeed', 'known', 'unconcerned', 'jesus', 'blatant', 'claiming'], ['last', 'chapter', 'today', 'germany', 'satisfied', 'past', 'whole', 'price', 'real', '2', 'wars', 'though', 'still', 'truer', 'great', 'also', 'positive', 'undemocratic', 'strange', 'cls', 'meekly', 'probably'], ['chapter', 'much', 'present', 'scope', 'applies', 'world', 'infinite', 'spirituality', 'work'], ['chapter', 'outlet', '1', 'talks', 'taken', 'principals', 'mentioned', 'brought', 'positive', 'even', 'information', '3'], ['chapter', 'way', 'dispelled', 'die'], ['chapter', 'belief', 'stage', 'organized', 'peace', 'best', 'truths', 'mob', 'shorthand', 'bad', 'long', 'emanate', 'criminals', 'indeed', 'large', 'ask', 'cls', 'amounts', 'scale', 'particles', 'individuals', 'fix', 'rather', 'filtered', 'works', 'simpler'], ['chapter', 'building', 'iraq', 'wars', 'examines', 'mutual', 'fighters', 'world', 'respect', 'states', 'especially', 'east', 'countries', 'country'], ['chapter', 'ended', 'deals', 'world', 'etc', 'crime', 'spread', 'america', 'occurred', 'europeans', 'picked', 'lives', 'tussle'], ['chapter', '“very', 'taken', 'all.”', 'one', 'earlier', 'summary', 'eyes', 'catch', 'dinner...some', 'come', 'nervous', 'waiting', 'opportunity', 'tracks'], ['whole', 'chapter', 'would', 'group', 'anorexia', 'basis', 'cues', 'genders', 'justification', 'womanhood', 'separate', 'became', 'relationship', 'praised', 'also', 'created', "o'reilly", 'rather', 'abby'], ['chapter', 'class', 'focuses', 'better', 'actually', 'like', 'happening', 'chance', 'direct', 'impediments', 'smith', 'men', 'interests', "that's", 'references', 'mobility', 'concludes'], ['chapter', '“', 'presence', '6', 'nothing', 'chapters', 'final', "fretheim's", 'positively', 'actually', 'human', 'receptiveness', 'synthesize', 'text', 'god', 'controversial', 'several', 'appearances', 'form', 'calls', 'involve', '”', 'wrestling'], ['chapter', 'final', 'relationships', 'seventh', 'engage', 'become', "can't", 'including', 'enjoy', 'bdsm', 'biological', 'acceptance', 'charity', 'eighth', 'attraction', 'sex', 'agree', 'fact', 'valuable', 'good', 'cordelia', 'lifelong'], ['protests', 'asleep', 'chapter', 'hospital', 'ends', 'twan', 'money', 'craig', 'relaying', '20', '19', 'trying', 'seen', 'sylvester', 'shows', 'offending', 'remarks', 'decides', 'cop', 'hid', 'randolph', 'deeply', 'well'], ['movement', 'chapter', '15', 'descriptions', 'includes', 'france', '1975', 'rule', 'khmer'], ['chapter', 'retribution', '–', 'points', 'also', 'emphasises', 'encountered', 'full', 'worshipping', 'others', 'one', 'said', 'around', 'paramitas', 'gather', 'upon', 'declare', 'renders', 'beings', '7'], ['chapter', 'awake', 'used', 'town', 'bicycles', 'breaking', 'much', 'central', 'figure', 'morning', 'excitement', 'contortionist', 'mist', 'soon', 'air', 'man', 'way', 'strong'], ['chapter', 'religion', 'references', 'antisemitism'], ['chapter', 'labels', 'culture', 'etc', 'offset', 'opens', 'focuses', 'deals', 'within', 'identity', 'talks', 'back', 'people', 'step', 'stereotypes', 'focused', 'texts', 'date', 'help']]

Processing features:  55%|█████▌    | 54/98 [25:59<21:21, 29.13s/it]

getting sample prompt forgetting sample prompt for 24049
 24048
getting sample prompt for 24050
getting sample prompt for 24051
getting sample prompt for 24052
getting sample prompt for 24053
getting sample prompt for 24054
getting sample prompt for 24055
getting sample prompt for 24056
getting sample prompt for 24057
getting sample prompt for 24058
getting sample prompt for 24059
TOP TOKENS [['battle', 'battles', '34:1', '2'], ['battle'], ['battle', 'important'], ['battle', '8/13/1948'], ['battle', 'war'], ['famous', 'interesting', 'battle', 'ended'], ['battle', 'important', 'took', 'come', 'analysed', 'norway', 'fact', 'whilst'], ['battle', 'famous', 'actually'], ["dk's", 'explained', 'battle', 'draws', 'recorded', 'chronologically', 'covers', 'illustrated', 'together'], ['battle', 'important'], ['battle', 'caillat', 'parties', 'blur', 'battles', 'stanier', 'colbie', 'fairey', 'late', 'united'], ['battle'], ['battle', 'also', 'french'], ['battle', 'battler', 'east'], ['battle'], ['battles', 'battle', 'following'], ['battles'], ['battle'], ['battle(1802–1879', 'battle'], ['battle', '2005', 'guitars']]
TOP TOKENS [['monopod', 'monopods', 'attack', 'well'], ['http://nearpod.com', 'nearpod'], ['http://www.merriam-webster.com/dictionary/bipod', 'bipod-definition', 'bipods[change', 'bipod', 'bipods'], ['isopod', 'isopods', 'plants', 'gills', 'anyway', '1', 'terrestrial'], ['bipod', 'bipods', "bipods'length", 'west'], ['isopoda', 'isopod'], ['bipod', 'bipods', 'soldiers', 'degrees', 'way', 'along', 'arm', 'round', 'based', 'mulitple', 'diamter', "gunner's", 'attatched'], ['nearpod', 'rigor', '’', 'used', 'grades', 'using'], ['branchiopoda', 'branchiopod', 'phyllopodous'], ['branchiopoda', 'branchiopod', 'phyllopodous'], ['tetrapod', 'tetrapods', 'tripod', 'tetrapodomorpha'], ['tetrapod', 'hexapod', 'hexapoda', 'hexapod-telescope', 'platform'], ['airpod', 'range', 'starting', 'chassis', 'claimed', 'vehicle', 'posted', 'configurations', 'planned', 'mid-2019', 'prototypes', 'partially', 'number', 'international'], ['lifepod'], ['megapodiidae', 'macropodidae', 'macropod'], ['airpod'], ['kpod-fm', 'kpod'], ['cyllopoda', 'cyllopodini', 'walker'], ['heteropoda', 'wang'], ['heteropoda', 'torricelliana']]
TOP TOKENS [['ultra', 'makes', 'processed', 'changes'], ['ultra-careful', 'ultra', 'ultrafrom', 'ultramundane', 'ultrafrench', 'ultra-classical', 'ultranationalist', 'ultrā', 'ultra-latin', 'ultraconservative', 'ultraism', 'ultraromantic'], ['ultraproduct', 'ultraproducts', 'ultrafilter', 'ultrafilters', 'ultrapowers'], ['ultra', 'ultraprocessing', '66', 'processed', 'al', 'additives', '“', 'epidemic', 'physical'], ['ultra', 'cls', 'processed', 'health', 'consumption', 'thickeners'], ['ultra-processed', 'avoiding', 'meals', 'decades', 'says', 'calories'], ['ultrafilter', 'ultrafilters', 'every', 'mathematics', 'standard', 'immediate'], ['ultra', 'processed', 'recognize'], ['ultraism', '‘ultraism’', '‘ultraism', 'definition', 'manifestos'], ['ultra', 'packaged', 'tying', 'directly', 'processed', 'cls', 'unprocessed', 'clear', 'first'], ['ultra-man', 'ultraman', 'ultra', 'character', 'supervillainous'], ['ultra', 'ultras', 'fans', 'ultra-royalist', 'militantly', 'ultramarathon', 'ultra-tories', 'ultraverse', 'radical', 'ultra-leftists', '1960s'], ['ultra', 'ultrasport', 'super', 'extreme', 'megasport', 'sport'], ['ultra'], ['ultranet'], ['ultra', 'machine'], ['ultraproduct', 'ultrapower', 'ultrapowers', 'ultraproducts', 'ultrafilter', 'signature', 'theory', 'nonstandard'], ['ultrabeat', 'group'], ['ultra', 'ultracruiser', 'ultralight'], ['https://salsa.debian.org/debian/ultracopier.git', 'https://doc.ubuntu-fr.org/ultracopier', 'ultracopier', 'https://www.softpedia.com/reviews/windows/ultracopier-review-162037.shtml', 'https://mac.softpedia.com/get/utilities/ultracopier.shtml', 'https://alternativeto.net/software/ultracopier', 'http://www.ohloh.net/p/ultracopier', 'ultimate', 'basic', 'supercopier']]
TOP TOKENS [['francis', 'church', 'creatures', 'innocence'], ['francis', 'cls', 'assisi', 'strengths', 'thrifts', '“'], ['francis', 'father', 'job', 'assisi', 'fanatic'], ['francis', 'man', 'st'], ['francis', "francis's", 'actions', 'st', 'assisi', 'life'], ['francis', "francis'life", 'cls', 'cross', 'captivity', 'music', 'followed', 'patrimony', 'assisi', 'inside'], ['francis', 'sanctos', 'assisi', 'preparation'], ["francis'family", 'francis', "francis'work", 'purity', 'day', 'st', 'yet', 'worldly'], ['francis', 'st', 'cls', '—', 'franciscan', 'friars', 'images', 'christ', 'earth'], ['francis', "francis'meeting", "francis'birth", 'assisi', 'st', 'franciscan', 'life', 'youth', 'either'], ['disambiguation'], ['francis', 'francesco', 'film', 'disambiguation'], ['francis'], ['francis', 'links'], ['kay', 'nellie', 'francis', 'genie', 'league'], ['francis', 'zaragoza', 'cádiz', 'late', 'la', 'living', 'midfielders', "men's", 'liga', 'footballers', 'segunda', 'known', 'first-team', 'players', 'season'], ['francis', "men's", 'season', 'first-team', 'footballers', 'known', 'andalusia', 'references', 'one', 'players', 'betis', 'club'], ['francis', '2023', '9', 'season', 'wins', 'style', '2022', '1'], ['francis', '2014', 'career', '1', '2015', '2022', 'links', 'child', 'tournament', 'history', 'people'], ['francis', 'canada', 'see']]
TOP TOKENS [['stanford', 'fund', 'med'], ['stanford'], ['stanford', "stanford's", '1,600', 'business', '4.18', 'non-denomination', 'education'], ['stanford', "stanford's", 'undeveloped', 'well', 'real', 'despite', '1962', 'world'], ['stanford', 'stanfords', 'offered', 'systems', 'institution', 'sciences', 'programs', 'doctoral', 'humanities', 'campus', 'university', 'u', '’'], ['stanford', 'stanford—and', 'stanford’s', "stanford's", 'precarious', 'debt', 'research', 'significant'], ['stanford', "stanford's", 'programs', 'precarious', '1,000', 'percent'], ["stanford's", 'stanford', 'international', 'programme', 'guides', 'athletics', "quadrangle's"], ['stanfords', 'stanford', 'son', "stanford's", 'seal', 'leland', 'contemporaries', '1970'], ['stanford', 'medicine'], ['stanford'], ['stanford', "stanford's", '2008', 'e', 'also'], ['stanford', "stanford's", '2019', 'research', 'links', 'university', 'career'], ['stanford', "stanford's", 'disambiguation'], ['stanford'], ['stanford', "stanford's", 'games', '1940s'], ["stanford's", 'stanford', '1996', 'convention', 'education', 'opposition', 'however', 'proposals', 'sixty'], ['stanford', '1900', '20', 'america'], ['stanford', 'center', '7'], ['stanford', 'colspan']]
TOP TOKENS [['patrick'], ['curiousmarc', 'marc]’s', 'friend', 'meantime', 'observable', 'marc', 'stuff', 'click', 'required'], ['work', 'mind', 'little', 'there’s', 'won’t', 'job', 'doesn’t'], ['robson', 'runs', 'end-around', 'similar', 'puts', 'rafael'], ['work', 'mind', 'little', 'hacks', 'something', 'proper', '’', 'cracking', 'uses', 'trying', 'like', 'job', 'use', 'added', 'electronics', 'extreme'], ['messing', 'another', 'around', 'enough', 'ended', 'set', 'reason', 'making', 'using', 'make', 'neat', 'simply', '–', 'build', 'additions', 'took', 'create', '’', 'help', 'fairly', 'properly', 'pins', 'type'], ['really', 'hand', 'pretty', 'put', 'decided', 'something', '’', 'provide', 'set', 'awesome', 'go', 'together', 'else', 'well', 'closet', 'inventive', '–', 'wanted', 'like', 'simple', 'much', '315mhz', 'year', 'hacky', 'still', 'nice', 'able', 'charged', 'spent', 'ways', 'quite', 'doors'], ['allow', 'makes', 'completes', 'we’ve', 'used'], ['allow', 'makes', 'completes', 'we’ve', 'used'], ['robert]’s', 'uses', 'measure', 'it’ll', 'latest', 'anymore'], ['manages', "martin's", 'supplies'], ['old', 'one', 'get', "geoff's"], ['parts', 'preparing', 'unfortunately', 'one'], [], ['work', 'managed', 'making', 'knowledge', 'contained', 'worked', 'using', 'chip', 'showcasing', 'known', 'games', 'technically', 'access', 'february', 'may'], ['manages', 'taken'], ['modify', 'uses'], ['began'], [], ['involves']]
TOP TOKENS [['nobility', 'nobles', 'noblesse', 'noble', 'aristocracy', 'cls', 'hereditary'], ['nobility', 'nobleman', 'aristocracy', 'noble', 'gentry', 'aristocratic', 'noblesse', 'cls'], ['nobility', 'nobles', 'aristocracy', 'peerage', 'noble', 'cls', 'definitions'], ['nobility', 'word', 'noble'], ['nobility', 'nobles', 'aristocracy', 'noble', 'peerage', 'aristocratic', 'non-nobles'], ['nobility', 'nobles', 'gentry', 'noble', 'noblewoman', 'peerage', 'nobleman', 'commoner', 'concept'], ['nobility', 'noble', 'nobleman'], ['nobility', 'noble'], ['nobles', 'aristocracy'], ['nobility', 'noble', 'title', 'know'], ['nobles', 'nobility', 'members'], ['nobility', 'nobles', 'noble', 'aristocracy'], ['nobility', 'aristocratic', 'aristocracy', 'noble', 'gentry', 'term', 'cls', 'aristocrats'], ['nobility', 'gentry', 'aristocratic', 'nobleman', "nobleman'is", 'nobles', 'noble', 'titles', 'aristocrats', 'landed', 'patricians', 'usage'], ['aristocracy', 'nobility', 'peerage', 'lords', 'sit'], ['nobility', 'member', 'cls', 'savage', 'disambiguation', 'fi'], ['nobility', 'aristocracy', 'peerage', 'gentry', 'gentlemen', 'peers', 'british', 'aristocrats', 'gentleman'], ['nobleman', 'nobility', 'nobles', 'noble', 'noblemen', 'gentry', 'lords', 'members', 'squires', 'lord', 'magnates', 'title'], ['nobility', 'nobles', 'nobleman', 'aristocracy', 'gentry', 'noble', 'word', 'title', 'lords', 'aristocrat', 'landowners', 'duke', 'russian'], ['nobility', 'nobles', 'noble', 'aristocracy', 'gentry', 'noblesse', 'peers', 'list']]
TOP TOKENS [['accessibility', 'accessible', 'part', 'web', 'sep', 'others'], ['accessibility', 'accessible', 'spaces', 'pages', 'public', 'making', 'ontarians', 'guidelines', 'building', 'practices'], ['accessibility', 'accessible', 'time', 'many', 'taking', 'code', 'specific', 'major', 'pretty', 'classes', 'enabled', 'enablement', 'much', '’'], ['accessibility', 'accessible', 'accessibilitybroadly', 'available', 'effecting', 'define', 'way'], ['accessibility', 'accessible', 'entirely', 'engine', 'initiative', 'problems', 'website'], ['accessibility', 'accessible', 'features', 'implementing'], ['accessibility', 'accessible', 'inaccessible', 'finding', 'introduction', 'blatantly', 'broad'], ['accessibility', 'accessible', 'making', 'help', 'issues', 'overview', 'make'], ['accessibility', 'accessible', 'made', 'hands-on'], ['accessibility', 'choose', 'items', 'properties', 'allow', 'tester', 'onoverall', 'select'], ['accessibility', 'accessible', 'physical', 'standardize', 'use', 'requiring', 'usability', 'cls', 'contrast', 'disability', 'signatories'], ['accessibility', 'accessible', 'relating', 'side', 'guidelines', 'content', 'working', 'authoring', '1', '0', 'end'], ['accessibility', 'admissible', 'choosing', 'relates', 'available', 'conditions', 'fact'], ['accessibility', 'accessible', 'promote', 'aa', 'requirements', 'meet'], ['accessibility', 'transport', 'using', 'existence', 'potential', 'keeping', 'definition', 'number', 'development'], ['accessibility', 'general', 'accessible', 'e', 'country', 'direction', 'based', 'origin', 'work'], ['accessible', 'accessibility', 'designing', 'requirements', 'features', 'abilitynet', 'standards', 'options', 'guides'], ['accessibility', 'accessible', 'initiative', 'creating', 'centred', 'web', 'producing', 'create', 'need', 'authoring', 'process', 'guidelines', 'technology', 'access', 'design'], ['accessibility', 'methodology'], ['accessibility', 'years', 'game']]
TOP TOKENS [[], ['waxing', 'waning', 'new', 'illuminated', 'gibbous', 'moon'], ['waning', 'phases', 'gibbous', 'waxing', 'versus', 'getting', 'stages', 'various', 'around'], ['waning', 'waxing', '“', 'phases', 'two', 'resolution', 'hemisphere', 'part'], ['waning', 'waxing', 'crescents'], ['waning', 'waxing', 'phases', 'phase', 'gibbous', 'recognize', 'e.g'], ['waning', 'phases', 'waxing', 'called', 'part'], ['“', 'waning', 'waxing', '”', 'phase', 'gibbous', 'crescent', 'phases', 'third'], ['waxing', 'waning', 'phases', 'gibbous', 'http://www.primaryhomeworkhelp.co.uk/moon/phases.html'], ['phases', 'waning', 'waxing', 'phase', 'gibbous'], ['wanes', 'waxes', 'phase', 'looks', 'waxing', 'waning', 'like'], ['waxing', 'waning', 'waxes', 'looks', 'like'], ['gibbous', 'phases', 'phase', "moon's", 'new', 'around', '7', 'appearance'], ['phases', 'different', 'shows', 'part', 'circumference', 'represents'], ['lines', 'mooring', 'moorings'], ['phases', 'waning', 'also', 'see', 'phase', 'references', 'stated', 'earlier', 'babylonians', 'babylonian'], ['phase', 'waning'], ['phases', 'phase', 'goes'], ['waxing', 'waning', 'quarter', 'gibbous', 'moon', 'crescent', 'two'], ['phases', 'also', 'external', 'see', 'phase', 'links', 'moon', 'since', 'capricorn', 'astrology']]
TOP TOKENS [['thoughts'], ['thoughts', 'thought', 'intrusive', 'pass'], ['thoughts', 'thought', 'others', 'negative', 'reality', 'congruent', 'right', 'allow', 'whose', 'acceptance', 'achieve'], ['thoughts', 'reoccurs', 'person', 'case', 'us', 'negative', 'cls', 'image', 'positive'], ['thoughts', 'experience', 'thought', 'negative', 'unchecked'], ['thoughts', 'recurring', 'certain', 'life'], ['thoughts', 'time', 'experiences', 'unwanted', 'negative', 'could', 'activities', 'experience', 'additional', 'ways'], ['thoughts', 'low', 'believable', 'state'], ['thoughts', 'disturbing', 'intrusive', 'acknowledging'], ['thoughts', 'thought', 'life', 'bleak', 'perspective', 'negative', 'harmless', '”', 'pops', 'cls'], ['thoughts', 'voyager'], ['thoughts', 'disorder', 'experienced', 'ive', 'intrusive', 'bad', 'recognizing'], ['thoughts', 'whether', 'intrusive', 'persistent', 'eliminate', 'utterances', 'time', 'may'], ['night-thoughts', 'thoughts'], ['thoughts', 'ive', 'intrusive', 'amount', 'avoidant', 'reach', 'obsessional', 'suicidal', 'religious'], ['thoughts', 'thought', 'negative', 'thinking', 'ant', '1=low-high=5', 'worthless', 'experienced', 'course', 'automatic'], ['thoughts', 'experiencing', 'racing', 'thought', 'maintaining', 'associated', 'consciousness', 'sleep', 'might', 'random', 'apnea'], ['engineer/mixer', 'thoughts', 'management', '2017'], ['thoughts', 'still', 'unskillful', 'negative', 'distracting', 'thought', 'eliminate', 'continue', 'arise'], ['infidelity', 'thoughts', 'morning', 'evil', 'orazio', 'brambilla', 'venier', 'fog', 'next', 'lover', 'canceled', 'tognazzi', 'mazzarella', 'shotguns']]
TOP TOKENS [['graphic', 'design', 'designer'], ['graphic', 'design', 'designer', 'designers'], ['graphic', 'design', 'place', 'designer', 'illustrators', 'n'], ['graphic', 'design', 'designers', 'dominance', 'person', 'favour'], ['graphic', 'designer', 'design', '“', 'cls', 'designers', 'even'], ['graphic', 'design', 'designer', 'designers'], ['graphic', 'design', 'designers', 'designer', 'designs'], ['graphic', 'design', 'designer', 'designers', 'image', 'minded'], ['graphic', 'design', 'designers', 'designer', 'world', 'audience', 'cls', 'story'], ['graphic', 'design', 'designers'], ['graphic', 'designers', 'designer', 'channel', 'must', 'images', 'multimedia', 'computer', 'design', 'arts'], ['graphic', 'designer', 'designers', 'design', 'cls', 'art', 'experienced', 'artist', 'directors', "client's", 'models'], ['graphic', 'design'], ['graphic', 'designers', 'design', 'designer', 'registered', 'typographic'], ['graphic', 'design', 'designers'], ['graphic', 'design', 'designer', 'designers', 'designand', 'registered'], ['graphicly', "graphicly's", 'mentor', 'key', 'ludlow', '2010', 'adelson', 'graphic', 'cls', 'conversion', 'team', 'dave', 'part', 'magazines', 'additional', 'led', 'bolstered', 'directly', 'downloaded', 'book'], ['graphic', 'design', 'designers', 'designer', 'turning', 'teaching', 'style'], ['graphic', 'www.graphicexchange.com', 'design', 'graphics', 'broadening', 'exchange', '1995', 'included', 'agfa', 'arts', 'art', 'publication', '1998', 'creative'], ['graphicaudio', 'summer', 'serrano', 'cls', '2020', 'onsite', 'released', '2012', 'music', 'land']]
TOP TOKENS [['fasd', 'alcohol', 'fetal', '“fasd”', 'you’ve'], ['fasd', 'fas', 'alcohol', 'fetal'], ['fasd', 'fas', 'alcohol', 'fetal'], ['fasd'], ['fasd'], ['fasd'], ['fasd', 'known'], ['fasd', 'fas', 'fasds', 'alcohol', 'fetal', 'people', 'would', 'syndrome'], ['fasd', 'fetal', 'fas'], ['fasd', 'fas', 'fetal', 'distinctions', 'alcohol'], [], ['fasd', 'fas', 'drugs', 'fetal', 'alcohol', 'syndrome'], ['fasd', 'fasds', 'fetal', 'fas', 'drugs', 'fa', 'alcohol', 'disorders'], ['fasd', 'fas', 'fetal', 'alcohol', 'disorder', 'even'], ['fasd', 'fas', 'fasds', 'diagnoses', 'identifying'], ['fasd', 'fas', 'fetal', 'alcohol', 'syndrome', 'damage'], ['fasds', 'fetal', 'fas', 'alcohol', 'prenatal', '2', 'training', 'antidepressants', 'syndrome', 'especially'], ['fasd', 'fasds', 'fas', 'fetal', 'alcohol', 'disorders', 'syndrome', 'drinkers', 'problems', 'size', 'however', 'include', 'disease', 'peers', 'people'], ['fasd', 'alcohol', 'fetal', 'syndrome', 'disease', 'disorders', 'living'], ['fasd', 'fas', 'fetal', 'alcohol', 'spectrum', 'disorder', 'disorders', 'encompassing', 'dysmorphology', 'syndrome', 'society', 'international', 'diagnosis']]

Processing features:  56%|█████▌    | 55/98 [26:27<20:28, 28.56s/it]

getting sample prompt forgetting sample prompt for 24061
getting sample prompt for 24062
getting sample prompt for 24063
getting sample prompt for 24064
 24060
getting sample prompt for 24065
getting sample prompt for 24066
getting sample prompt for 24067
getting sample prompt for 24068
getting sample prompt for 24069
getting sample prompt for 24070
getting sample prompt for 24071
TOP TOKENS [['gui', 'hand', 'abbreviationfinder'], ['gui', 'hand', 'abbreviationfinder'], ['gui', 'communication', 'cls', 'example', 'guis', 'explain', 'today', 'based', 'system'], ['gui', 'guis', "gui's", 'programming'], ['gui', 'guis', 'ui'], ['gui'], ['gui'], ['gui', 'graphical'], ['gui'], ['gui', 'guis', 'interface'], ['gui', '1885–1975', '1953', '1964', '1934', 'vessel'], ['gui', '歸亞蕾'], ['gui'], ['gui', 'qi', 'shun', 'enfeoffed', '3159th-most'], ['gui'], [], ['gui', 'historical', 'entry', 'languedoc', 'notorious'], [], ['gui', 'dynamically', 'case', 'send', 'generating', 'get', 'domain'], ['gui', 'death', "gui's", 'adalgisa']]
TOP TOKENS [['paddy', 'paddy(noun'], ['paddy'], ['paddy', 'dried', 'individual', 'fields', 'unplanted', 'frost'], ['paddy'], ['paddy'], ['paddy'], ['paddy', 'cleaning', 'contaminants'], ['paddy', '0.08', 'wetland', 'missing'], ['paddy', 'years', 'report', 'rain', 'plant', 'period', 'methods', 'observed', 'way', 'thus', '30', 'drying', 'cultivation', 'issue'], ['paddy', '5', '60', '2', 'crop'], ['paddy', 'disambiguation'], ['paddy', "paddy's", 'later', 'college', 'died', 'faith', 'commons', 'successor', "wish'sic", 'oxford', 'library'], ['paddy'], ['paddy', 'word', 'cls', 'marshes', 'wetlands', 'iran', 'micronesia', 'times', 'large', 'rice'], ['paddy', 'maguire', 'clair', 'breeda'], ['paddy'], ['paddy', 'see', 'origin', 'derbyshire', 'specials', 'site', 'workings'], ['paddys', 'external', 'links'], ['paddy', 'bushels', 'million', 'decades'], ['paddy', 'problem', 'extent', '2', 'irrigation', 'however', 'gourd', 'year', '7', 'ha', 'bean']]
TOP TOKENS [['boban', 'naturally', 'goal', 'boots', 'feelings', 'era', 'reader', 'fiorentina', 'leanings'], ['longan', 'nhãn', 'longans', 'long-ngan', 'wikipedia', 'simplified', 'lóngyǎn'], ['cran', 'note'], ['monsan', 'hissan', 'koan', 'koans', 'oan', 'monto', 'one', 'field', 'sensory', 'known'], ['koan', 'koans', "gong'an", "kong'an", 'provoke', 'background', 'antoku', 'literally', 'term', '–', 'also', 'unk', '—', 'see', 'japanese', 'zen', 'according'], ['avidan.see', 'avidan', 'bradan', 'aitan', 'arman', 'elian', 'rian', 'aydan', 'alin', 'adrian▲'], ['lacan', "lacan's", 'emile', '1920s', 'rousselle', 'thin', 'gaetan', 'outcome', 'around', 'grounds', 'maurras', 'choisy', 'interest', 'emilie', 'completing', 'medicine', 'stanislas'], ['lippman', 'pman', 'states', 'llc', 'playground', 'cultivate', 'group', 'dr', 'io', 'books'], ['flans', 'flan', '“flan”', 'mixed', 'reason', 'latin', 'flavor', 'custard-like', 'years', 'dishes'], ['flans', 'flan', '“flan”', 'mixed', 'reason', 'latin', 'flavor', 'custard-like', 'years', 'dishes'], ['固安镇', 'kuan', "gu'an", 'guan', 'guān', 'central', '固安县', '灌县'], ['govan', '1971', '1942', '1794–1841', 'scotland', 'govans', 'sheena', 'shipbuilders', '1861–1927'], ['livan', 'livan-e', 'liván'], ['qian'], ['parkan'], ['1961', 'forman', '2005', '1797', '1894', '1922', 'player', 'ira'], ['cardan', 'rod', 'object', 'gimbal'], ['montan', 'disambiguation', 'sartre', 'montán', 'italy', 'sven'], ['xuan', 'duke', 'marquis'], ['kōan', 'agency', 'hackers', 'koan-lp', 'koan', 'river', '2009', 'hacker']]
TOP TOKENS [['remaining', 'slim', 'final', 'foresee', 'prospects', 'weak', 'efficiently', 'well', 'overlap', 'express', 'disounts', 'based', 'red', 'operated', 'complete', 'also', 'besides', 'survival', 'undoubtedly', 'many', 'appear', 'surprising', 'likely', 'next', 'sixty', 'consulting', 'heavily', 'year', 'wednesday', 'air', 'disappear', 'run', 'submerged', 'even', 'several', 'survive', 'half', 'said', 'airlines'], ['best', 'late', 'bracing', 'wind', 'rush', 'independance', 'still', 'predictions', 'view/post', 'falsely', 'prophets', 'never', 'waiting', 'throes', 'shuttling', 'megaflus', 'much', 'ahead', 'car', 'exhaust', 'precipitously', 'effort', 'verge', 'output', 'waited', 'perhaps', 'vain', 'possible', 'despite', 'popularized', 'doomsday', 'widely', 'espoused', 'claims', 'deal', 'dyson', 'frequent', 'often', 'hoist'], ['tug', 'hang', 'remaining', 'late', 'holding', 'close', 'coming'], ['likely', 'neither', 'end', 'even', 'easily', 'going', 'credible', 'might', 'fully', 'weak', 'could', 'side', 'able', 'knockout', 'term', 'stalemate', 'secure', 'blow', 'happen', 'waiver', 'analysts', 'eventually', 'short', 'go', 'prove', 'posting'], ['prevail'], ['whimper', 'end', 'meet', 'fizzle', 'rush', 'sum', 'bang', 'toward', 'beginning', 'tightly', 'whatever', 'fragments', "jupiter's", 'held', 'torn', 'explosions', 'outcome', 'primordial', '16', 'pile', 'meter', 'july', 'self', 'diameter', 'together', 'find', 'less', 'jupiter', 'clumping', 'stretching'], [], ['remaining', 'grabs', 'odds', 'exactly', 'still', 'tie', 'likelihood', 'going', 'one'], ['store'], ['ahead', 'overall', 'one', 'likely', 'last', 'enough', 'end', 'well', 'meanwhile', 'particularly', 'counted', 'languishing', 'conservative', 'nothing', 'find', 'respectively', 'candidate', 'less', 'still', 'fourth'], ['sole', 'enough', 'final', 'unanswered', 'close', 'left', 'possession', 'looked', 'remaining', 'yards', 'rattled', 'jeopardy', 'hopes', 'nearly', 'ahead', 'seconds', 'yard', 'loss', 'ball', 'scoreless', 'score', 'marvin', 'respond', 'threatened', 'serious', 'able', 'finally', 'drives', 'gave', 'managed', 'miscues', 'would', '1', 'times'], ['left', 'fizzled', 'scrimmage', 'short', 'final', 'minutes', 'late', 'ball', 'outcome', 'clinched', 'back', 'responded', 'eventually', 'answered', 'yard', 'first', 'yards', 'plays', 'remained', 'spark', 'slightly', 'hard', 'presentable', 'run', 'took', 'led', 'fought', 'halftime', 'later', 'finally', 'settled', 'right', 'respectively', 'passer'], [], ['left', 'remaining', 'kick', 'stalled', 'responded', 'yard', 'minutes', 'held', 'ball', 'false', 'yards', 'glanced', 'picked', 'stymied', 'fumbled', 'less', '06', 'first', 'times', 'good', 'flagged', '47', 'play', 'score', 'corral', 'able', 'went', "murray's"], ['ready'], [], ['doubt'], [], ['test', 'stands', 'pitchforks', 'growl', 'allmusic', 'hiphopdxs', 'lil', 'tape', 'concludes', 'mixtape', 'unlikely', 'weave', 'unmistakable', 'together', 'might', 'pitfalls', 'time', 'goes', 'playing', 'old', 'enough', 'forces', "dugg's", 'tinny'], []]
TOP TOKENS [['palace', 'palaces', 'paladin', 'palaceˈpæl', 'historic', 'word', 'dignitary', 'exhibitions'], ['palace', 'palaces', 'hill', 'word', 'minoan', 'known', 'aristocracy', 'century', 'senate', 'deacon', 'residence', 'exhibitions', 'usage', 'recognized', 'cls', 'palais', 'buildings'], ['palace', 'palaces', 'troops'], ['palace', 'aristocracy', 'rome', 'palaces', 'palais', 'word', 'power', 'though', 'original', 'buildings', 'long', 'palazzo', 'cls', 'france', 'pope', 'many', 'historic'], ['palace', 'portugal', 'palaces', 'cls', 'monarchs', 'architecture', 'country', '2', 'potala', 'many'], ['palace', 'palaces', 'cls', 'ii', 'rococo', 'emperors', 'royal', 'schonbrunn', 'summer', 'dignitary'], ['palace'], ['palace', '1478', 'palaces', 'word', 'royal', 'term', 'country', 'baroque', 'dalkeith'], ['palace', 'renowned', 'much', 'famous', 'lost', 'glorious'], ['palace', 'palaces', '1837', 'appearance', 'emperor', 'eunuchs', 'successfully', 'maids', 'took', 'buckingham', 'famous', 'nation'], ['palace', 'dignitaries', 'mysliwski', 'blackpool'], ['palace', 'miami', 'avenue', 'links', 'franyie'], ['palaces', 'palace', 'castle'], ['palace', 'succession', 'album', 'bratislava', 'palaces'], ['palace', 'called', 'old'], ['palace', 'date', '2022', 'hodges', '2016', '2015', 'history', 'released', '2019'], ["palace's", '1968', 'palace', 'thirty-five', 'standstill', 'june', 'palais', 'hour', '2007'], ['palace', 'weimar'], ['concrete', 'montana', 'hotel', 'register'], ['palace', 'marghazar']]
TOP TOKENS [["harm's", 'moment', 'well', "one's"], ['earth'], ['13825495', '40', '20462262'], ['com'], ['4.9(t-1.25)^2', 'afrer', 't>1.25'], ['instantly', 'much'], ['resounding', 'r'], ['inaccurate', 'commercial', 'verve', 'effervescence', 'dynamism', 'vigor', 'religious', 'political', 'prevail'], ['6562470756', '13825495', '327396192'], ["harm's"], ['tirado', 'mouth', 'autobiography', 'album', 'grotus'], ['radio', "women's"], ['narrowly', 'oblong', 'illawarra', 'less', 'spring'], ['website', '–', 'parents', 'directly'], ['interparliamentary', 'incorporated', 'technical', 'tetragrammaton', 'olfaction', 'association'], ['association', "people's"], [], [], ['tv', 'learning', 'disengaged'], ['air', 'brief', 'life', 'allergy', 'wondrous', 'organisation']]
TOP TOKENS [['maimonides', 'theologian', 'observation', 'ce', 'maimon'], ["maimonides's", 'maimonides', 'reflects', '1148', 'maimon', 'link', 'mishneh', 'also', 'mi', '2d', 'ben'], ['maimonides', "maimonides's", 'maimon', 'judaism', 'medicine', 'month', 'wandering', 'intolerant'], ['maimonideans', "maimonides'philosophical", 'maimonides', "maimonides'works", "maimonides'tomb", 'maimonidean', "maimonides'attacks", "maimonides'in", 'philosophy', "maimonides'patrons"], ['maimonides', 'intervene', 'god', 'scotus', 'well', 'philosopher', 'attribution', '0', 'unported', 'mishna', 'conditions'], ['maimon', 'atheism', 'resolved', 'disagreed', 'saw', 'ultimately', '’', 'recently', 'time', 'recognized', 'mid'], ['maimon', 'atheism', 'resolved', 'disagreed', 'saw', 'ultimately', '’', 'recently', 'time', 'recognized', 'mid'], ['maimonides', 'maimonists', 'maimon', 'christians', 'cls', 'already', 'mishnah'], ["maimonides's", 'maimonides', 'reflects', 'maimon', 'bible', 'topics', 'elucidated', 'god', 'mī´mən', 'mīmŏn´ĭdēz', 'ben'], ['maimonides', 'maimon', 'getting', '’', 'n'], ['maika', '1993', 'halfwolf', '1987', '尾崎妹加', '4'], ['maier', "maier's", 'documentary', 'classical', 'concerto', 'zaterdagmatinee', 'magnus', 'played', 'ylem', 'composer', 'speaking'], ['2015', '2002', '2007', '2014', 'august', 'released', '2021', 'mair', 'band', 'started', 'japan', 'ever', 'performed', 'remastered', '4'], ['maimonides', 'maïmonide', '1138–1204'], ['personality', 'maisy'], ['maimonides', '1867–1873'], ['berlin', 'maik', '1965', 'translator', 'szarszewski', 'außendorf', 'writer'], ['italian-french', 'maio', '1817-1884'], ['bihar', 'maibi'], ['end', 'maio', 'stabbed', "maio's", 'ajello', 'wrote']]
TOP TOKENS [['casters', 'caster'], ['casters', 'caster', 'equipped'], ['caster', 'need'], ['caster', 'caste'], ['caster'], ['caster', 'caster—the', 'leaving', 'cart'], ['caster', 'cornering', "tyre's", 'wheels', 'lean', 'negative'], ['caster', 'casters', '’', 'camber', 'visualize'], ['caster', 'casters', "casters'effects", 'whether', 'thicker', 'cls'], ['casters', 'caster'], ['caster', 'industry', 'suspension'], ['caster', 'aligned', 'motorcycles', 'improper'], ['casters', 'caster', 'castershox®', 'industrial', 'aerol'], ['caster', "caster's", '1946', 'credited', 'years', '39', 'blazes', 'san', 'later', 'sportspeople'], ['caster', 'casters', 'positive', 'kingpin', 'behind'], ['casters', 'caster', '‘caster', 'cast', 'casting', 'set', 'perforated', 'part'], ['caster', 'reduced', 'polyurethane', 'brands'], ['caster', '2003'], ['caster', "caster's", '1945', 'described', 'credited', 'series', 'knuckler', '150'], ['caster', "caster's", '2001']]
TOP TOKENS [['hearst', 'though'], ['hearst', 'william'], ['hearst', 'toward', 'william', 'business', 'randolph', 'mountains'], ['hearst', "hearst's", 'father', 'william', 'randolph', 'known'], ['hearst', "hearst's", 'reporting', 'randolph', 'william'], ['hearst', 'hearst’s', 'endeavors'], ['hearst', "hearst's", 'hearsts', 'spending', 'comedienne', '1904', "father's", 'nevertheless', 'character'], ['hearst', '2017', '23', '1943', '20', '2010', '1951', 'william', '2000'], ['hearst', '1898', 'randolph', 'william', 'debt', '2', 'sex'], ["hearst's", 'hearst', 'journal'], ['hearst', 'lydia', 'media', 'randolph', '1904–1972', 'phoebe', 'james'], ['hearst'], ["hearst's", 'hearst', 'california', 'simon', 'mrs', 'randolph'], ['hearst', 'u.s'], ['hearst', "hearst's", '39.49333'], ['hearst'], ['hearst', "hearst's", 'william', 'canada', 'swimming'], ['hearst', "hearst's", 'seven', 'years', 'later', '1873'], ['hearst', 'wilbur', 'born', 'california', 'corporation', 'jr', 'examiner', 'family', '1953–2004'], ['hearst', 'illinois', 'davenport']]
TOP TOKENS [['react', 'reactdom', 'cls'], ['react', 'overflow', 'learn'], ['react', 'cls'], ['react', 'one', 'learn'], ['react', 'reactjs', 'essentially', 'dom', '2012', 'else'], ['react', 'overflow', 'learn', 'using'], ['react’s', 'react', 'reactjs', 'complements', 'using'], ['react'], ['react'], ['react', 'developer', 'learn', 'using', 'popular', 'least', 'ecosystem'], ['cls', 'react', 'reactjs', 'reactdom', "from'react"], ['react', "react's", '2017', 'changed', '2013', '0', 'example', 'history', '2022'], ['react', "from'react"], ['react', 'integrating', '2014', 'user', '2022', '0', 'subsidiaries', 'october'], ['react', 'application', 'reusable', 'v16'], ['reactos', 'react', 'cls', 'joined', 'prosecution', 'name'], ['reactos', 'reactx', 'goto', 'chdir', 'august', '15', '7', 'popd', 'wordpad', 'june'], ['react', 'include', 'cls', 'known', 'term', 'almost', 'celebs', 'also'], ['react', 'particularly'], ['reactos', 'members', 'categorized', 'believed', '2015', '2009', 'distrowatch']]
TOP TOKENS [['lapse', 'stabilising', 'kind', 'stabilisation', 'stabilizer', 'time', 'lot', 'going', 'tweak', 'properly'], ['time-lapse', 'stabilizer', 'smoother', 'much', 'hyper-lapse', 'things', 'make', 'taken', 'hyper-lapses', 'get', 'several', 'isn’t'], ['time-lapse', 'say'], ['stabilization'], ['lapse', 'photography'], ['lapse', 'glory', 'period', 'cls', 'e', 'captured', '’', 'ceases', 'time', 'example', 'photography'], ['lapse', 'captured', 'cls', 'time', 'smooth', 'imperceptibly', 'creates', 'may', 'recorded', 'ensuring', 'e', 'similar', 'cavalry'], ['lapse', 'lapses', 'way', 'even', 'cls', 'meaning', 'essential'], ['lapse', 'include', 'cls', '1870s', 'allows', 'using', 'able', 'also', 'words', 'amount', 'us'], ['lapse', 'forwarding', 'nicer'], ['lapse', 'cls', 'captured', 'time', 'even', 'smooth', 'similarly'], ['lapse', 'time-lapse', 'ludovico', '2015', 'seventh', 'video', 'time', 'film', 'phonography', 'album', 'game'], ['lapse', 'stabilized', 'resulting', 'timelapse', 'example', 'relies', 'using', 'involves', 'appears', 'allows', 'exposures', 'achieve', 'achieved', 'also', 'minute', 'second', 'hyperlapses', 'form', 'back', 'include'], ['stabization', 'steadies', 'slowly', 'captured', 'stabilization', 'stabilized', 'course', 'party', 'one', 'due', 'drifts', 'based', 'either'], ['stabilisation', 'stabilization', 'stabilized', 'lies', 'stability', 'allow', 'especially', 'case', 'also', 'employing', 'viewfinders'], ['stabilized', 'stabilizes', 'stabilization', 'stabilizer', 'stabilize', 'compensates', 'fastening', 'camera', 'regardless', 'however', 'trails', 'lens', 'recording', 'conditions', 'since', 'magnifies', '7'], ['stabilizing', 'stabilization', 'stabilize', 'stabilized', 'consists', 'since', 'using'], ['stabilization', 'end', 'even', 'recorded', 'cls', 'photography', 'times', 'exposures', 'obtainable', 'cameras', '4', 'though', 'generally', '2', '5', 'also', 'astronomy'], ['stabilization', 'stabilisation', 'times', 'support', 'others'], ['lapse', 'exposure', 'example', 'heighten', 'achieved', 'thus', 'shot']]
TOP TOKENS [['graphing', 'autoshaping'], ['autoshaping', 'graphing'], ['graphing', 'acrylic', 'autoshaping', 'based'], ['graphing', 'autoshaping', 'x', 'based', 'acrylic'], ['graphing', 'autoshaping'], ['autoshaping', 'graphing', 'acrylic'], ['graphing', 'autoshaping'], ['graphing', 'autoshaping'], ['graphing', 'autoshaping'], ['graphing', 'autoshaping', 'based', 'x'], ['graphically'], ['translational', 'laboratory', 'online', 'genotype', 'provides', '10-40', 'public', 'hematology', 'single-nucleotide', 'characterizes', 'analysis', 'research', 'facilitate', 'levels', '2000', 'web-accessible'], ['memory', 'storage', 'behavior', 'computers'], ['automate'], ['disambiguation', 'american', 'fischer'], [], ['behavioral', 'behavioural', 'behaviours'], ['data'], ['8001000', 'onto'], []]

Processing features:  57%|█████▋    | 56/98 [26:54<19:49, 28.33s/it]

getting sample prompt forgetting sample prompt for 24073
 24072
getting sample prompt for 24074
getting sample prompt for 24075
getting sample prompt for 24076
getting sample prompt for 24077
getting sample prompt for 24078
getting sample prompt for 24079
getting sample prompt for 24080
getting sample prompt for 24081
getting sample prompt for 24082
getting sample prompt for 24083
TOP TOKENS [['trilled', 'trill', 'uvula'], ['trilled', 'trill', 'uvula'], ['rifles', 'tritium', 'makes', 'source', 'make', 'element', 'phosphor', 'tritium[change'], ['triton', 'tritons', 'among', 'another', 'tanagra', 'also', 'broader', 'would', 'appearance', 'supposed', 'come', '5'], ['triac', 'triacs', "here's", 'would', 'theory', 'works', 'poor', 'found', 'continue', 'trigger'], ['trireme', "father's"], ['vomiting', 'triazolam', 'prescribed', 'emphasized', '•', 'may'], ['tritone', 'apart', 'away', 'f', 'concerned', 'substitution', 'c', 'composition'], ['tritium'], ['triton', 'interesting', 'km', 'overlain...more', 'comparable...more', 'took', 'reveals', 'one'], ['judson'], [], ['wipers'], ['trivia', 'metal', 'rhetoric', 'trivium'], ['wins', 'guileless', 'socialism', 'philosophy', 'trine', '1893', 'emerson', 'bobbs-merrill', 'lived', '1891', '1920s', 'became', "trine's", '1906', "herron's", '9', 'biography', 'g', 'translated', 'described', 'writers'], ['states', 'sale'], ['piedmont', 'yelamos'], ['located', 'trilla', 'trilhanols', 'occitan'], ['trigonometry', 'company', 'trigo'], []]
TOP TOKENS [['geometry', 'cls', 'like', 'freeware', 'architecture'], ['geometry', 'word', "world's", 'blog'], ['geometry', 'form', 'space', 'study', "jē-om'i-trē"], ['geometry', 'form', 'space', 'study', "jē-om'i-trē"], ['geometry', 'geometrical', 'attention', 'representation', 'essential'], ['geometry', 'cls', 'use', 'geometrygroup', 'geometrical'], ['geometry', 'cls', 'world', 'cylinders'], ['geometry'], ['geometry', 'students', 'geometric', 'level'], ['geometry', 'geometrical', 'geometric', 'assignment'], ['geometry', 'relationships', 'geometric'], ['geometry', 'space', 'geometric', 'epipolar', 'links'], ['geometry', 'interactive'], ['geometry', 'links', 'references', 'external'], ['geometry', 'geometric'], ['geometry', 'geometric'], ['geometry', 'geometric'], ['geometry', 'cls', 'geometric', 'space', 'figures', 'world'], ['geometry', 'known'], ['geometry', 'geometricorum']]
TOP TOKENS [['poster', 'posters', 'e', 'sessions'], ['poster', 'posters', 'paper', 'material', 'session'], ['poster', 'panels', 'panel'], ['poster', 'posters', 'graphs', 'sentences', '5', 'histograms', 'normal'], ['poster', 'posters', 'graphic', 'session', 'printed'], ['poster', 'posters', 'software'], ['postering', 'poster'], ['poster', 'posters', 'powerpoint', 'images', 'fonts'], ['poster', 'posters', 'short', 'panels'], ['poster', 'posters'], ['poster'], ['posterholt'], ['poster'], ['poster', 'posters', 'powerpoint', 'lamination'], ['poster', 'pin-up'], ['poster', 'posters'], ['poster', 'documentary', 'conceived', 'short', 'film', 'english-language', 'post-traumatic', 'women', 'subject', 'photographed'], ['poster', 'posters', 'however', 'textual', 'times', 'gallo', 'placards', 'visually', 'advertisers'], ['posterized', 'poster', 'printed', 'high-flying', 'infrequently'], ["posterstein's", 'posterstein', 'postersteiner', 'altenburger', 'municipal', 'vollmershain', 'greiz', 'municipalities', 'rail', 'saxe-altenburg', 'thuringian', '1871–1918', 'bundesautobahn', 'burg']]
TOP TOKENS [['weiss', '’', 'pages', 'major', 'claire', 'st', 'establishment', 'weisman', 'choice'], ['weiss', '’', 'going'], ['weiss', 'group', 'r', 'bachner', '157235', 'couple', 'project', 'w', 'radiation'], ['weiss', 'citizenship'], ['weiss', 'suggests'], ['weiss', 'otherwise', 'sound', 'comparing', 'observatories', 'rainer', 'led', 'he’s', 'say'], ['weiss', 'world', 'time', '’', 'argued', 'although', 'pessimistic', 'coexistence', 'also', 'interests', 'well'], ['weiss', '’', 'society', '1922', 'citizenship', 'august'], ['weiss', '”', 'nouvelle', 'war', 'france', 'stamp', '–', 'defeat', 'sentiments'], ['weiss', 'trustees', 'views', 'one', 'traditions', 'scientific', '1843', 'twice', 'committee', 'loyalty', '1818'], ['weiss', 'projects', 'member', 'expected', 'servant', 'signatures', 'practice', 'donors'], ['weiss', 'derivatives', 'collection', 'also', 'report', 'deficit', 'publications'], ['weiss'], ["weiss'ordeal", 'weiss', "weiss's", '2022', 'like', '21', '10', '2008', 'teams', '2017', '2021', 'braves'], ['weiss', 'district', 'life'], ['weiss', 'excuses', 'participated', '28'], ['weiss', 'works', 'management', 'memberships', '2022', 'matters'], ['weiss'], ['weiss'], ['weiss', 'weisshorn', 'weissbier', 'weisse', 'disambiguation', 'north', 'military']]
TOP TOKENS [[], ['troops', 'incoming', 'fired', 'order', 'bombardment', 'place', 'forces', 'involving', 'time', 'fire', 'firing', 'soldiers', 'men', 'ships', 'message', 'smells', 'landing', 'acclimatize', 'general', 'followed', 'live', 'commander', 'felt', 'assault', 'incident', 'made'], ['troops', 'populations', 'wish', 'soldiers', 'time', 'war', 'observed', 'know', 'american', 'u', 'foes', 'world', 'times'], ['troops', 'soldiers', 'war', 'forces', "enemies'action", 'workers', 'land', 'bombs', 'landing', 'flight', 'paratroopers', 'ashore', 'come', 'soldier', 'bombardment', 'u', 'officers'], ['arrived', 'opened', 'approaching', 'firing', 'battery', 'fired', 'fire', 'approach', 'upon', 'garrison', 'fort', 'staff', 'start', 'cls', '1861', 'major', 'port', 'flying', 'war', 'time', '9', 'away', 'pilot', 'smoke', 'shots'], ['troops', 'war', 'soldiers', 'background', 'scene', 'troop', 'world', 'landing', 'discharging', 'beachhead', 'ii', '537', 'beach'], ['soldiers', 'troops', 'warplanes', 'flak', 'gunner', 'assault', 'world', 'aircraft', 'inoculated', 'cockpit', 'army', 'pilots', 'war', 'strafing', 'military', 'general', 'german', 'b', 'navy', 'bursting', 'occupied', 'british', 'conditions', '17s', 'landing', 'bursts', 'hitting', 'planning', 'crew', 'marshaling', 'bombs', 'command', 'lounge', 'spitfire', 'airdropped', 'flying', 'two', 'striking'], ['hast'], ['soldiers', 'troops', 'aiming', 'war', 'world', 'officers', 'smoke', 'shot', 'front', 'lines', 'berlin', 'german', 'rises', 'u.s', 'along', 'building'], ['troops', 'war', 'bound'], [], [], ['stationed', 'arriving', 'recruited', 'ordered', 'sent', '1863', 'mustered', '1864'], ['arrival', 'imminent', 'troops', 'arrived', 'sentries', 'sent', 'launched', 'received', 'brigadier', 'departure', 'commander', 'daybreak', 'battery', 'brig', 'battle', 'enemy', 'ordered', 'infantry', 'fire', 'men', 'afire', 'town', 'set', '4'], ['air', 'war', 'army', 'anita', 'fort', 'troops', 'pows'], ['staff', 'arthur', 'army', 'military', 'corporal', 'buffs', 'sergeant', 'stafford', 'infantry', 'henry', 'artillery', "wales's", 'guard', 'service', 'william', 'fitz', 'ryan', 'tierney', 'regiment'], ['coming', 'impending', 'approaching', 'flying', 'ordered', 'expected', 'order', '21s', 'pilots', 'air', 'take', 'alert', 'one', 'ready', 'phantoms', 'aircraft', 'airbase', 'leave', 'eaf', '00', 'number', 'kept'], ['air', 'station', 'naval'], [], ['grey']]
TOP TOKENS [['dulles', 'community', 'importantly', 'remarks', 'win', 'operations', 'reports'], ['dulles', 'brothers', 'foster', 'failed'], ['dulles', "dulles's", 'well', 'presented', 'italy', '’', 'policies', 'covert', 'state', 'highly'], ['dulles', 'yugoslavia', 'europe', '’'], ['dulles', 'dullith', 'agency', 'term', 'c', 'policy', '“', 'right', '”', 'drafted', '’', 'unexpired', 'much', 'negotiators'], ['dulles', 'europe', 'age', '1950s', 'ii', 'war'], ['dulles', 'dullith', 'lost', '”', 'personality', '“', 'exhausted', 'fullness', 'war', '’', 'campaign'], ['dulles', "dulles'younger", "dulles'life", "dulles'grandfather", "dulles'father", 'mr', 'dulleses', 'throughout', 'mrs', 'however', 'children', 'affairs'], ['dulles', 'outposts', 'ways', 'ended', 'another', 'said', 'played', 'grim', 'formosa', 'spent', 'ceaseless', 'stride', 'try'], ['dulles', '’', 'gottlieb', 'administration', 'kennedy', 'personally', 'foster', '”', 'discontinue', 'companies', 'series', 'became'], ['dulles'], ['dulles', '1952', 'f', 'w', '1959', "dulles's", 'recuperating', 'cofounder'], ['dulles', 'corporation', '22000'], ['dulles', "dulles's", 'foster', '457', 'john'], ['dulles', 'party', 'nations', 'member', 'ii', 'foster', 'tenure'], ['dulles', "dulles's", 'learn', 'post', 'monitor', 'pennsylvania'], ['dulles', "dulles's", 'america', 'government', 'welsh', 'john', 'tenure', 'harbor', 'w', 'cliosophic', 'examination'], ['dulles', "dulles's", 'beleaguered', '1950s', 'iowa', '1958', '1954', 'state', '1953', 'communists', 'time', 'phu'], ['dulles', 'wilson', 'forgery', 'cliosophic', 'fiasco', 'eleanor', '–', 'senior', 'presbyterian'], ['dulles', 'missiles', 'particular', 'europe', 'grimm', '1951', 'gestapo', '1947', 'six', 'making', 'recruited', 'firm', 'july', 'october', 'election']]
TOP TOKENS [['inadvertently', 'may', 'happen', 'destroy', 'get', 'would', 'trouble', 'experienced'], ['could', 'get', 'take', 'beware', 'spectacularly', 'via', 'never', 'lead', 'even', 'still', 'quite'], ['might', 'could', 'possibly', 'get', 'create', 'damage', 'car', 'however', 'likely', 'vehicle'], ['could', 'cause', 'bath', 'enough', 'electrocution'], ['may', 'warning', 'still', 'result', 'significant', 'care', 'enough', 'case', 'less', 'think', 'least', 'damage', 'unless'], ['may', 'warning', 'still', 'result', 'significant', 'care', 'enough', 'case', 'less', 'think', 'least', 'damage', 'unless'], ['potentially', 'may', 'cause', 'damage', 'could', 'happens', 'since', 'breaks', 'soap'], ['get', 'happens', 'cause', 'could', 'also', 'electrocuted', 'start', 'knock'], ['could', 'fatal', 'easily'], ['may', 'warning', 'still', 'enough', 'case', 'since', 'significant', 'least', 'also', 'think', 'result', 'less', 'even'], ['likely', 'manner', 'eventually', 'damage', 'harm'], ['accidentally', 'could', 'may', 'even', 'electrocution', 'touching', 'cause', 'beforehand', 'risk', 'avoid', 'pipes', 'immediately', 'prongs', 'plugging', 'easily', 'also'], ['potentially', 'cause', 'risk', 'damage', 'result', 'damaging', 'otherwise', 'could', 'avoided', 'lead', 'way', 'without', 'attempts', 'machines', 'care', 'devices'], ['resulting', 'event', 'resulted', 'chance', 'may', 'harms', 'serious', 'subjecting', 'launching', 'result', 'great', 'happened', 'abundance', 'occurred', 'exploding', '6', 'risks'], ['potentially', 'rupture', 'even', 'damage', 'cause', 'dangerous', 'arcing', 'may', 'considered', 'voltages', 'easily', 'catastrophically', 'instances', 'fatal', 'create', 'resulting', 'fail', 'vaporizes', 'failures'], ['may', 'incredibly', 'dangerous', 'danger', 'strength', '–', 'within', 'insulated', 'however', 'finally', 'time', 'dispersing', 'item'], ['could', 'even', 'pipes', 'risk', 'another', 'including', 'faucets', 'touching', 'also', 'water', 'flooring', 'pull'], ['may', 'enough', 'catch', 'eject', 'cause', 'result', 'create', 'results', 'explosively', 'long', 'point', 'takes', 'though', 'violent', 'severe', 'scalding', 'become', 'hazard', 'almost'], ['potentially', 'damaging', 'shorting', 'cause', 'may', 'mistakenly', 'potential', 'even', 'improperly', 'also', 'sparks', 'serious', 'grid', 'extremely', 'hazards', 'possible', 'pose', 'contact', 'hazard', 'although'], ['g', 'may', 'cause', 'damage', 'also', 'lead', 'beyond', 'unlikely', 'become', 'fatal', 'serious', 'dangerous', 'irreversible', 'explosion', 'lodged']]
TOP TOKENS [['universe'], ['universe', 'universes', 'cosmos'], ['universe', 'universes'], ['universe', '“'], ['universe'], ['universe'], ['universe', 'universes', 'within'], ['universe', 'cosmos', 'universes', 'reality'], ['universe', 'galaxies', 'stop', 'galaxy', '000'], ['universe', 'universes', 'cosmos', '“'], ['universe'], ['universe', 'cosmology'], ['universe', 'space'], ['universe'], ['universe', 'universes', 'mathematics', 'set'], ['universe'], ['universe', '1973'], ['universe'], ['universe', 'cosmos', 'galaxies', 'cosmology', 'cosmic'], ['universe', 'links', 'however', 'listed']]
TOP TOKENS [['morocco'], ['morocco', 'morocco’s', 'round.interior', 'south', 'italy'], ['morocco', 'moroccan', 'moroccans', 'kingdom'], ['morocco', 'ago', 'humid', 'temperatures', 'days'], ['morocco', 'expense', 'constitution', 'century'], ['morocco', '4'], ["morocco's", 'morocco', 'reach', 'moroccan', 'geography', 'degrees'], ['morocco', 'moroccans', 'although', 'religion', '26', 'today', 'sep'], ['morocco', 'moroccans', 'moroccan'], ['morocco', "morocco's", 'moroccan', 'casablanca', '1980s', '1999'], ['morocco'], ['morocco', "morocco's", 'ppp', 'government'], ['morocco', 'moroccan', 'south'], ['morocco', 'moroccan'], ['morocco', 'one', 'medal'], ['morocco'], ['morocco', 'casablanca', 'university'], ['morocco', 'moroccan', 'french'], ['morocco', 'moroccan'], []]
TOP TOKENS [['control', 'phonesats', "interplanetary's", 'include', 'trackers', 'spinning', 'shortcomings', 'attitude', 'saturation', '0', 'wheels', "wheel's", "nasa's", 'deployed', 'given', 'sensors', 'magnetorquers'], ['actuation', 'attitude', '1', '550nm', 'energy', 'support', 'station', 'trackers', 'one', 'uses'], ['modes', '7kg', '24', 'maneuver', 'valves', '28', 'torquers', 'upon', 'attitude', 'control', 'propellant', '0', '30kg', 'thrusters', 'altitude', 'specific', '2', '3', 'operational', '1', 'years', 'fuel', 'fulfilled', '23kg', 'weeks'], ['actuators', 'optic', 'reaction', 'control', 'illustration', 'aobc', 'uses', 'pointing', 'sensor', 'gyro', 'attitude', 'sensors', 'sensed', '8series', 'microsatellite', 'ground', 'comprised'], ['two', 'one', 'protocol', 'obc', 'axes', 'subsystem', 'thus', 'magnetometers', 'receiver'], ['accelerometers', 'heads'], ['accelerometers', 'heads'], ['reaction', 'control', '±0', 'wheels', '±1', 'orbit', 'addition'], ['trackers', 'control', 'attitude', '0', 'compared', 'dumps', 'unregulated'], ['one', 'measurement', 'attitude', 'wheels', 'gyroscopes', 'depending', 'axis', 'relevant', 'actuated', 'modes', 'maneuvers', 'two', "array's", 'used', 'steering', 'level', 'control', 'trackers', 'also', 'per', 'perturbations', 'thrusters', 'wrt'], ['rockets', 'control', 'attitude', 'spacecraft', 'pointed', 'applicators', 'axis', 'direction', "spacecraft's", 'instead', 'amount', 'thus', 'actuator', 'amounts', 'allowing', 'preferentially'], ['control', 'field', 'attitude', 'time', "spacecraft's", 'orbit', 'redundancy', 'mass', 'addition', 'controlled', 'low', 'since', 'therefore', 'axes'], ['second', 'left', 'westward', 'return', 'bgcolor', 'northward'], ['reaction', 'control', 'moreover', 'states', 'conversely'], ['attitude', 'reaction', 'control', 'direction', 'monopropellant', 'provide', 'hypergolic', 'rolling', 'directed', 'also', 'speeds'], [], ['two', 'control', 'prescribed', 'sensor', 'orientation', 'orbit'], ['s2', 'tested', 'satellite', 'container', 'analysed'], ['reaction', 'systems', "spacecraft's", 'wheels', 'desired', 'rate'], ['control', 'attitude', 'hand', "smm's", 'controllers', 'three', 'orbiting', "orbiter's", 'order']]
TOP TOKENS [['lifestyle', 'specify', 'actively', 'lives', 'life', 'live', 'living'], ['lifestyle', 'proactively', 'define', 'live', 'livings', 'life', 'lives'], ['lifestyle', 'live', 'behaviours', 'improvement', 'requires', 'make', 'life', 'living', 'day', 'decide'], ['lifestyle', 'habitually', 'definition', '“', 'actions', 'american', 'behaviors', 'performed', '”', 'given', 'widely'], ['lifestyles', 'lifestyle', '“lifestyle”', 'follow', 'term', 'person’s', 'lead', 'behaviors', 'behavior'], ['lifestyle', 'pursues'], ['lifestyle', 'pursues'], ['lifestyle', 'habit', 'specific', 'behaviors', 'habits', 'activity', 'diet'], ['lifestyle', 'lifestyles', 'living', 'live', 'decades', 'unhealthy', 'follow'], ['lifestyle', 'habits', 'life', 'living', 'healthy', 'implementing'], ['lifestyle', 'lifestyles', 'joe'], ['lifestyles', 'lifestyle', 'living', 'doings', 'life', 'choices', 'sense', "someone's", 'engaging'], ['lifestyle', 'life', 'everyday'], ['lifestyle', 'habits', 'behavior', 'avoidance', 'choices', 'preventable', 'personal', 'consumption', 'behaviors', 'reversed'], ['lifestyle', 'live', 'atlanta-based', 'song', 'records'], ['lifestyle', 'live', 'maintaining', 'life', 'radically', 'oftentimes', 'certain', 'living', 'healthy', 'person', 'owner'], ['lifestyle', '2016', 'interests', 'cls', 'contemporary', 'leisure'], ['lifestyle', '2016'], ['lifestyle'], ['lifestyle', "lifestyles'analysis", "lifestyles'components", 'lifestyles', 'habitus', 'actions', 'life', 'adopt', 'studies']]
TOP TOKENS [['rosencrantz', "guildenstern's", 'guildenstern'], ['rosencrantz', 'guildenstern', 'guildernstern', 'thats'], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern'], ['rosencrantz', "of'hamlet'and'rosencrantz", 'guildenstern'], ['rosencrantz', 'guildenstern', "guildenstern's"], ['rosencrantz', "guildenstern's", 'guildenstern', 'rosencrantz”', 'rosencrantz…i’m', 'guildenstern’s'], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern', 'rosenkrantz', "stoppard's"], ['rosencrantz', 'guildenstern'], ['rosencrantz', 'guildenstern', 'col', 'london', 'ryley', 'also'], ['rosencrantz', 'guildenstern'], ['guildenstern', 'rosencrantz', 'rosenkrantz-theil', 'tom', "shakespeare's", 'rosenkrantz'], ['rosencrantz', 'guildenstern', "stoppard's", 'playing', 'stoppard'], ["of'rosencrantz", 'rosencrantz', 'guildenstern', 'also', 'stoppard'], ['rosencrantz', 'guildenstern', 'play', 'julian'], ['rosencrantz', 'guildenstern']]

Processing features:  58%|█████▊    | 57/98 [27:27<20:08, 29.48s/it]

getting sample prompt forgetting sample prompt for 24085
 24084
getting sample prompt for 24086
getting sample prompt for 24087
getting sample prompt for 24088
getting sample prompt for 24089
getting sample prompt for 24090
getting sample prompt for 24091
getting sample prompt for 24092
getting sample prompt for 24093
getting sample prompt for 24094
getting sample prompt for 24095
TOP TOKENS [['something', 'sipaulovi', 'speakers'], ['hopis', 'hopi', 'never', 'deeply', '1050', '3rd', 'total', 'flat', '5', 'one', 'reverence', 'hopitu', 'considerably'], ['hopi', 'reflected', 'autochthonal', 'interconnectedness', 'called', 'forward', 'mustiness', 'care', 'demur', 'acquaint', 'structured', 'early'], ['hopi', 'coiled', 'days', 'underworld', 'email', 'first', 'clans', 'religious', 'indian', 'one', 'also', 'different', 'audio', 'rotate'], ['sometimes', 'hopi', 'dances', 'experiences', 'necessary', 'includes', 'famed', 'rather', 'individuals', 'spoken', 'often', 'village'], ['hopi', 'mild', 'two', 'relatively', 'name', 'new', 'everyday', 'matrilineal', 'carved', 'disturbances', 'learning', 'role', 'move', 'still', 'hopitu', 'also', 'life', 'according'], ['hopi', 'places', 'clans', 'polongahoya', 'much', 'sipapuni', 'larger', 'built', 'tribe'], ['hopi', 'silversmiths', 'significance', 'mesas', 'authorized', 'mesa', 'occupy', 'welcome', 'sipaulovi'], ['hopi', 'snares', 'paraphernalia', 'familiar', 'dramaturgic', 'earlier', 'neighboring', 'shows', 'language', 'uniform', 'times', 'dyeing', 'crude'], ['hopi', 'residents', 'spirits', 'call', 'etiquette', 'nobody', 'responsible', 'throughout', 'arts', 'explanations'], ['air-to-surface'], ['artvin', 'puzzle', 'see', 'hidden', 'joint'], ['non-alcoholic', 'squadron', 'hopi', 'hopalong', 'manchester', 'flying'], ['hopfields', 'hopfield', 'lyman–birge–hopfield', 'outside', '60', 'molecular'], ['soldiers', 'hoplitis'], [], ['hopwood'], ['published', 'hopi', 'fluent', '39', '60', 'american', 'project', 'nonprofit', 'arizona', 'program', 'recent', '75', 'shipaulovi'], ['cards', 'covid-19', 'streamyard', 'event', 'plans', 'etc', 'platform', 'hopin', '2021', 'address', '3.85', '7.8', 'express', 'agreed', 'get', 'deal', 'nato', '2023', 'pandemic', 'teams'], ['experimental', 'assif', 'mothfight', 'pythagorean', 'opera', 'tinashe', 'brian', 'garfield', 'hopscotch', 'tsahar', 'co-founded', 'solitaire']]
TOP TOKENS [['toolbar', 'toolbars'], ['toolbar', 'toolbars', 'tollbar'], ['toolbar', 'toolbars', 'tollbar'], ['toolbars', 'toolbar', 'toolbarexercise', 'toolbarenter', 'modifytoolbars'], ['toolbars', 'taskbar'], ['toolbars', 'toolbar', 'flow'], ['toolbar', 'toolbars'], ['toolbars', 'toolbar'], ['toolbars', 'toolbar', '6'], ['toolbars', 'toolbar'], ['toolbar', 'toolbars'], ['toolbar', 'archive', 'however', 'engine', 'part', 'starts', 'highlighting'], ['toolbar', 'toolbars', 'declined', 'particular', 'designed'], ['toolbar', 'toolbars', 'studio', 'development', 'customised'], ['drawbar'], ['drawbar'], ['tools', 'toolbox', 'jetbrains'], ['toolesboro', 'toole'], ['toolbars', 'toolbar', 'taskbar', 'utilities'], ['toolbar', 'also', 'bookmarklet', 'translation', 'june', 'google', "browser's"]]
TOP TOKENS [['bse', 'partly'], ['bse', 'spongiform', 'nine', 'encephalopathy', 'one'], ['bse', 'u.s'], ['bse', 'spongiform'], ['bse', 'spongiform'], ['‘spongy.’', 'bse', 'spongiform'], ['bse', 'scrapie'], ['bse', 'scrapie'], ['bse', 'scrapie'], ['bse'], ['bse', 'spongiform', 'scrapie'], ['spongiform', 'encephalopathy', 'bse'], ['bse', 'masking', 'spongiform', 'scrapie', 'kind', '–', 'following'], ['bse', 'spongy', 'spongiform', 'though', 'encephalopathies', 'case', "animal's", 'parts'], ['bse', 'cases', '1993', '013', '588', '1', 'two', '2004', 'disease', 'one'], ['bse', '1986', '2002', 'due', 'spongiform', 'globally', '2017', 'disease', '2018', 'encephalopathy', 'united', 'scrapie'], ['bse', 'scrapie', 'good', 'one', 'case'], ['bse', 'spongiform', '57', 'bovine', 'bseinqui', 'encephalopathies', 'shockbursts', 'encephalopathy', 'october', 'organophosphates', '–'], ['bse', 'scrapie', 'outbreaks', 'disease', 'confirmed', 'diseased', 'vertebral'], ['bse', 'spongiform', 'encephalopathy', 'notifiable', 'bovine', 'following', 'cadavers', 'onwards', 'british', '1989', '1990', 'brain']]
TOP TOKENS [['testing', 'antibody', 'allergy', 'test', 'tests', 'allergic', 'higher', 'food', 'skin', 'school', 'important', 'also', 'risk', 'assessment', 'means', 'cytotoxic', 'reproducible', 'children', 'child', 'called', 'whether', 'subjected'], ['test', 'allergy', 'prick', 'allergies', 'prior', 'allergic', 'testing', 'allergen', 'tests', 'pricking', 'allergens', 'preservatives', 'allergist', 'reaction', 'skin', 'tested', 'less', 'reactions', 'together'], ['allergic', 'test', 'tests', 'add', 'testing', 'allergy', 'level', 'report', 'next', 'tested', 'foods', 'close', 'instead', 'food', 'prick', 'reacts', 'allergist', 'consider', 'would', 'challenge', 'usually', 'positives', 'indicate', 'measures'], ['testing', 'test', 'antibody', 'tests', 'allergy', 'allergic', 'food', 'higher', 'reflexology', 'important', 'school', 'around', 'risk', 'also', 'children', 'assessment', 'reproducible', 'child', 'skin', 'subjected', 'whether', 'screening', 'cytotoxic', 'means', 'done'], ['allergy', 'test', 'testing', 'allergic', 'tests', 'antibodies', 'immunology', 'exclude', 'prick', 'allergen', 'reflexology', 'reactions', 'reaction', 'allergens', 'anaphylaxis', 'together', 'results', 'carefully', 'usually', 'considered', 'doctor', 'may', 'strategies', 'scientifically'], ['allergy', 'allergic', 'four', 'reevaluated', 'reaction', 'discontinue', 'injections', 'lengthened', 'also', 'remain', 'ready', 'indication', 'reactions', 'seasons', 'responded', 'may', 'worsening', 'necessary', 'symptoms', 'allergies', 'months', 'weeks'], ['reaction', 'allergic', 'relation', 'allergies', 'assessment', 'allergy', 'affiliations', 'information', 'undiagnosed', 'related'], ['allergic', 'allergy', 'good', 'tests', 'test', 'sample', 'antibodies', 'tested', 'allergies', 'reaction', 'reacting', 'allergens', 'sensitive', 'allergen', 'avoid', 'indication', 'blood', 'ige', 'still'], ['dr', 'serologic', 'allergy', 'important', 'testing', 'company', 'reinhardt', '1068', 'allergens', 'relative', 'et', 'allergic', 'even', 'determination', 'may', 'challenge'], ['dr', 'serologic', 'allergy', 'important', 'testing', 'company', 'reinhardt', '1068', 'allergens', 'relative', 'et', 'allergic', 'even', 'determination', 'may', 'challenge'], ['cw', 'season', 'mcu', 'arrowverse', 'avoid', 'would', 'particularly', 'weeklys', 'well', 'dc', 'earth', 'behind', 'episode', 'agents', 'felt', 'good', 'marvel', 'kind', 'comics', 'could', 'entertainment', "series'delayed", 'instead', 'l', 'space', 'inhumans', 'e', 'h', 'enough', 'series'], ['0', 'war', 'warps', 'great', 'infinity', '1', 'wars', '5', 'saying', '4', '3', '10', '2018', 'based'], ['already', 'promoting', 'feige', 'four', 'best', 'avengers', 'civil', 'away', "mcu's", 'mcu', 'well', 'film', 'done', 'widow', 'much', 'otherwise', 'longer', 'said', 'noted', 'making', 'previous', 'past', '2014', 'teasing', 'five', 'saying', 'however', 'later', 'potential', 'ultron', 'cautioned', 'could', "widow's", 'time', 'seeing', 'marvel', 'dedicate', 'prequel'], ["mysterio's", 'mysterio', 'match', 'second', 'feud', 'contrasting', 'guerrero', 'eliminated', 'opposing', 'fight', 'fighting', 'subsequently', 'flight', 'marked', 'rivalry', 'flying', 'challenged', 'versus', 'sides', 'began', 'similar', 'episode', 'wanting', 'well'], ['stark', 'harmon', "tony's", 'h', "industries'biochemical", 'sr', 'quinjets', 'iron', 'industries', 'marvel', 'e', 'helicarriers', 'avengers', 'war', 'advanced', 'tony', 'cls', 'company', 'works', 'comics', 'shafear', 'skunk'], ['state', 'closer', 'airport'], [], ['four', '4au', 'also', '4', 'good', 'two', 'best', 'contender', 'continuation', 'balanced', 'lima', 'stars', 'considered', 'gave', 'individually', 'independent', 'chock', 'unabashedly', 'interesting', 'better', 'continuing', 'add', 'value', 'like', 'everything', 'writing', 'full', 'nicely', 'showcases', 'enough', 'whilst'], ['betrays', 'cw', 'young', 'apprehension', 'younger', "komodo's", 'emiko', 'doctor', 'lovers', 'experienced', 'oliver', 'arrow', 'rejects', 'son', 'shado', 'side', 'together', "oliver's", "queen's", "arrow's", 'show', 'hawke', 'arrows', 'instead', 'alongside', 'instantly', 'chooses', 'recognizes', 'plans', 'reveals', 'thereon', 'skilled', "mother's"], ['cohesive', 'score', 'could', 'avengers', 'rather', '5', 'felt', 'stating', 'thought', 'even', 'calling', 'lack', 'though', 'offer', 'also', 'serving']]
TOP TOKENS [['dissolves', 'hydrochloric', 'phosphorus', 'either', 'e', 'gan', 'salts', 'depending'], ['oxidizing', 'disproportionation', 'character', 'b', 'si'], ['chemically', 'water', 'chloroform', 'acid'], ['ch3ch2', 'ch3co2ch2ch3', 'ch2ch2o', '0', '9', '1'], ['ch3ch2', 'ch3co2ch2ch3', 'ch2ch2o', '0', '9', '1'], [], ['take', 'addition', '11'], ['hydrochloric', 'long', 'much', 'immediately', '4', 'dissolves', '5', '400°f', 'silicon', 'time', 'passivation', 'superficially', 'bismuth', 'oxidised', 'selectively', 'bacause', '9037', 'uses', 'even', '100°', '2', 'freezes', 'process'], [], [], ['also', 'dissolves', 'ion', 'gallium', 'temperature'], ['glasses', 'reflectors'], ['dissolves', 'solute', 'comparison', 'regard', 'n', 'tetramethylethylenediamine', 'also'], ['aqueous', 'acids', 'aliphatic', 'gold(iii', 'iron(ii', 'tin(ii'], ['along', '3', 'adopts', 'aluminium', 'whereas', 'cl3'], ['try', 'knowing', "sunil's", 'roles', 'later'], ['dissolves', 'like', 'however', 'trihalides', 'example'], [], ['gacp3'], ['gives', 'end', 'hence']]
TOP TOKENS [['shrinkage', 'slab', 'total', 'shrinks', 'extent', 'masonry'], [], [], [], [], [], [], [], [], [], ["here's", 'garroway'], [], [], [], [], [], [], ['49', '1', "macdonald's", '0'], [], []]
TOP TOKENS [['combinators', 'combinator', 'bx)y)z=x(yz', '3'], ['produce', 'combinatorial', 'clever', '24', 'possible', 'ˌkäm-bə-nə-ˈtȯr-ē-ə-lē', 'combinatoriallyplay', 'feedback'], ['combinator', 'combinators', 'exactly', 'little'], ['combinatorist', 'n', 'combinatorics', 'later', 'combinatorialist', 'combinatorial', 'combinatorics/what', 'certain', 'accessible', 'one', 'powerful', 'twentieth', 'combinatoric', 'well', 'parts'], ['combinatorial', 'areas', 'historically', 'combinatorialist', 'combinatorics', '2', 'topology', 'theoretical', 'century', 'cls', 'later', 'geometry', 'many'], ['combinatorics', 'combinatorial', 'results', '“', 'though', 'combinatorialists'], ['opinion', 'combinatorics', 'centuries', 'largely', 'apparent', 'combinatorial', 'match', 'pejorative', 'independent', 'also'], ['combinatorial', 'underlying', 'required', 'introducing', 'example', 'key', 'important', 'applying', 'license', '20', 'series', 'cls'], ['combinatorial', 'polymers', 'combichem'], ['combinator', 'combinatorics', 'certain', 'rely', 'sciences', 'wide', 'situations', 'basic', 'learning', 'algebra', 'cls'], [], ['combinators', 'higher-level', 'kinds', 'expanding', 'combinator'], ['popular', 'built', 'combi', 'steamer', 'boiler'], ['combin'], ['combinatorial'], ['also', "comber's", 'popstrangers', 'punch', 'first', 'included', 'arcata', 'july', 'comber', 'supported', 'began', 'eureka', 'non', 'album', 'recording', 'verlaines'], ['combinatorial', 'instead', 'previously', 'problem', 'resorted', 'cases', 'consist', 'limited', 'ones', 'way', 'fields', 'cls', 'turn', 'solutions', 'closely', 'e'], ['combinatorial', 'combinatorics', 'algebra', 'novel', 'cls', 'results', 'area'], ['1835–1921'], ['ismael', 'south', 'situated', 'province', 'sub', 'confederation', 'hunza', 'east', 'ruler', '1586', 'conquistadores', 'poet', 'cómbita']]
TOP TOKENS [['data', 'lake', 'warehouse', 'required', 'pool'], ['data', 'irrespective', 'lake', 'might', 'warehouse'], ['data', 'decisions', 'lake', 'warehouse', 'vs', 'lakes', 'reports', 'warehouses'], [], ['data', 'lakes', 'marts', 'processing'], ['data', 'contrast', 'lake', 'summary', 'lakes', 'warehouse', 'warehouses', 'infrastructure'], ['vs', 'warehouse', 'data', 'lake', 'warehouses', 'lakes', 'interchangeable'], ['data', 'lake', 'warehouse', 'hub', 'costs'], ['data', 'lake', 'warehouse', 'lakes', 'hand', 'teams'], ['lake', 'data', 'lakes', 'warehouses', 'warehouse', 'sieve', 'hand', 'structure', 'well', 'though'], ['mart', 'data', 'marts', 'lake', 'lakes', 'tasks', 'based', 'cloud', 'could', 'interacting', 'repository', 'usually', 'etc'], ['data', 'warehouse', 'vs', 'mart', 'records', 'warehouses'], ['data', 'lake', 'warehouse', 'lakes'], ['using', 'links', 'also', 'data', 'store', 'lake', 'users', 'governs', 'external', 'analytics', 'sensors', 'resource', 'see', 'account', 'dynamically'], ['data', 'warehouse', 'mart', 'models', 'marts', 'snowflake', 'view'], ['data', 'mart', '–', 'warehouse', 'store', 'table', 'online'], ['lake', 'data', 'warehouse', 'tends', 'go-to', 'services', 'free-for-all', 'negotiate', 'store', 'hub'], ['data', 'warehouse', 'marts', 'also', 'view'], ['data', 'warehouse', 'marts', 'warehouses', 'define', 'sees', 'accurately', 'cannot', 'warehousing'], ['data', 'warehouse', 'warehousing', 'requiring', 'dataupia', 'theory', 'classic', 'appeal', '4.0', 'storage', 'auto-reporting', "dataupia's", 'custom-assembly', 'manage', 'united', 'network-attached', 'utopia', 'intelligence', 'analyze', 'built-in', 'appliance']]
TOP TOKENS [['apples', 'apple', 'world', 'data', 'riboflavin', 'hypertension'], ['apples', 'apple', 'mealy', 'fermentation', 'fruit', 'tissue', 'cls', 'activity', 'loss', 'potassium', 'juiced', 'cakes', 'silicon', '”', 'tonic'], ['apples', 'apple', 'mealy', 'fermentation', 'fruit', 'tissue', 'cls', 'activity', 'loss', 'potassium', 'juiced', 'cakes', 'silicon', '”', 'tonic'], ['apples', 'apple', 'raw', 'msg', 'activity', 'tract', 'intestines', 'anatolia', 'week', 'antitoxic', 'system', 'properties', 'fiber', 'inflammation', 'thirst', 'massachusetts'], ['apples', 'apple', 'today’s', 'history', 'b.c.e', '1600s', 'indiana', 'u.s', 'today'], ['apples', 'apple', 'nutritious', '2017', 'https://www.medicalnewstoday.com/articles/267290.php'], ['apples', 'apple', 'golden', 'applesauce', 'crisp'], ['apples', 'applesauce', 'apple', 'applesalexander'], ['apples', 'apple', 'applesauce', 'barely', 'cholesterol', 'bay', 'don’t', 'equivalence', '“an', 'untrue'], ['apples', 'apple', "apple's", 'attached', 'bottom', 'round', 'cls'], ['apples', 'apple', 'table'], ['apples', '1536', 'les', '1328', 'cls', 'aplis', 'hautemorges', 'amsl', 'century'], ['apples', 'apple', 'golden', 'war', 'καλλιστη', 'word'], ['apples', 'apple', 'golden', 'picked', 'eat', 'goddesses'], ['apples', 'fruit', 'apple'], ['apples', 'apple', 'mythological', 'cls', 'word', 'berries', 'fruit'], ['apples', 'apple', 'variations', 'cake', 'beuvron', 'nuts', 'nutmeg', 'century', 'throughout', 'europe', 'cakes'], ['apples', 'apple', 'sweet', 'peach', 'golden', 'tetofsky', 'astrachan', 'cooking', 'pomona', 'king', 'raisins', 'cinnamon'], ['apples', 'apple', 'cultivated', 'domesticated', 'wild', 'contributor', 'european', 'sites'], ['apples', 'apples-on-a-stick', 'apple', 'caramel', 'rolling']]
TOP TOKENS [['miðlaði', 'þær', 'eðli', 'við', 'siðr', 'að', 'væri', 'hugsuðu', 'fjaðrar', 'þriðja', 'jorðunni', 'grær', 'hlutum', 'þar', 'jorðinni', 'undruðust', 'spekðina', 'jarðarinnar', 'jorðin', 'þeir', 'onnur', 'hætti'], ['vistaðu', 'þu', 'með', 'profaðu', 'hlustaðu', 'og', 'avallt'], ['goðir', 'skipaði', 'landskostir', 'vellir', 'nu', 'með', 'staðinum', 'við', 'sviþjoðu', 'þar', 'haleygjatali', 'varu', 'hofðingjum', 'eftir', 'sæmingr', 'þær', 'borgstað', 'hafði', 'kallaðr', 'sinar', 'hofuðmenn', 'aðrir', 'þykkjast', 'ynglingar', 'rituð', 'hann'], ['þeir', 'væntu', 'talið', 'grunaði', 'siðan', 'gomul', 'truðu', 'þar', 'eignaðist', 'ræðr', 'spurðu', 'eðli', 'frændum', 'tolðu', 'gomlum', 'nokkurr', 'jarðarinnar', 'reði', 'fyrir', 'hundruð', 'fæddi', 'eða', 'veðranna', 'hlutum', 'oll', 'nafn', 'með', 'reð', 'þa'], ['þessi', 'eða', 'sviþjoð', 'þeir', 'staðaheiti', 'norðr'], ['eða', 'auðlindaraðuneytið', 'skoðað', 'getið', 'með', 'tilvitnun', 'samkvæmt', 'að', 'sloð', 'venjum', 'ofan', 'umhverfisraðuneytið', 'groðurhusalofttegunda', 'vitna'], ['cwæð', 'þæt', 'forði', 'wiðmeten', 'geseoð', 'hwæðer', 'forðan', 'scinað', 'oðer', 'ðisum', 'gewitað', 'bið', 'swiðe', 'geðread', 'ðe', 'seðe', 'þæs', 'rixað'], ['með', 'atrunaðr', 'væri', 'spekðin', 'smiðaðir', 'þeir', 'kallaðr', 'þjoðirnar', 'deilðar', 'skilðu', 'þa', 'pryði', 'stoðum', 'jorðin', 'syðri', 'nyrðri', 'hefir', 'þar', 'nær', 'suðri', 'oðrum', 'skilningu', 'eða', 'hlutir', 'avaxtar', 'jarðar', 'mið', 'eignir', 'nofn', 'tungurnar', 'jarðligri', 'sva', 'miðjarðarsjo', 'allir'], ['við', 'uarð', 'egiaði', 'miðian', 'varð', 'siðan', 'hafði', 'ein2byrðan', 'þeir', 'hann', 'iþan', 'raða', 'sigurðr', 'moðruvallabok', 'vlfheðni', 'iaði', 'vlfheþni', 'ihnaccann', 'rendan', 'kolskeggr', 'þat', 'hatt', 'gvnnarr', 'kom', 'fram', 'þa'], ['eða', 'sœmðar', 'aðrum', 'viðrsiannde', 'maðr', 'siðar', 'siðgoðr', 'vil', 'hværir', 'hirðar', 'auðit', 'heraðum', 'bæðe', 'mæðr', 'siðaðr', 'þu', 'værðr', 'vist', 'þeir', 'væl', 'hofðingium', 'mæð', 'væra', 'sva'], ['þekðusk', 'nær', 'framða', 'byggðir', 'biða', 'viðr', 'dauða', 'gerðu', 'floði', 'hvotuðr', 'aðr', 'friðskerðir', 'kyrrsetu', 'sverði', 'allnær', 'breiðri', 'norðimbra', 'þar', 'þer', 'bliðr', 'þengill', 'braðir', 'ættniðr', 'storu', 'illan', 'buendr', 'brauzt', 'norðan', 'herkall', 'brandfurðu', 'buðlungr', 'lætr'], ['þjóðfundur'], ['breiða', 'eiði', 'niðara', 'vatn', 'faroese', 'eiðisvatn', 'charr', 'slættaratindur', 'faroe', 'sea'], ['vatnið', 'eiði', 'norðbergseiði', 'myrarnar', 'hvalbiareiði', 'mjauvøtn', 'heiðavatn', 'suðuroy', 'vørðuvatn', 'vagseiði', 'heygsvatn', 'trælavatn', 'norðara', 'tindarliðarvatn', 'rættarvatn', 'hovsdalur', 'breiðavatn', 'alkuðarvatn', 'hvannhaga'], ['viðvikurhreppur', 'skefilsstaðahreppur', 'skarðshreppur', 'staðarhreppur', 'lytingsstaðahreppur', 'upstaður', 'skagafjorður', 'hornafjorður', 'dalabyggð', 'borgarbyggð', 'isafjarðarbær', 'isafjarðarkaupstaður', 'hornafjarðarbær', 'hliðarhreppur', 'þverarhliðarhreppur', 'herað', 'bæjarhreppur', 'suðavikurhreppur', 'suðureyrarhreppur', 'suðurdalahreppur', 'ripurhreppur', 'norður', 'hofshreppur', 'holahreppur', 'staðars', 'seyluhreppur'], ['afslætti', 'snæbjornsson', 'norðfjorð', 'viðar', 'með', 'auður', 'alþjoðlega', 'ljoðum', 'holaðu', 'þor', 'gissurarsonar', 'norrænar', 'ævisogu', 'ljoð', 'ljoðaha', 'loðmfjorð', 'norðdahl', 'orn', 'holmsteinn', 'jonsdottir', 'hannesar', 'sjalf', 'ljoða', 'bindi', 'breiðfjorð', 'dropi', 'eirikur', 'norðdal', 'steypu'], ['þórður', 'þórðarson'], ['stafræn', 'goð', 'friðbjornsson', 'þorpið', 'spaðadrottningarnar', 'þjoð', 'umboðsskrifstofa', 'fjarlægð', 'næstur', 'orðið', 'stræti', 'það', 'fjorir', 'tungumal', 'getur', 'jol', 'naglar', 'konur', 'utgafa', 'æsku', 'gomul', 'þig', 'og', 'landi', 'sjalfsmynd', 'trui', 'islenskir', 'regnbogans', 'reykjavikur', 'tjaningarfrelsi', 'eg', 'heim', 'aldrei', 'þu', 'nei', 'verk'], ['landafræði', 'farðu', 'við', 'heyrðu', 'að', 'fæddur', 'musikbuðin', 'hlið', 'siðasti', 'næturfuglinn', 'með', 'farmaður', 'mærin', 'og', 'vor', 'vertu', 'kokkur', 'vagninn', 'ingibjorg', 'er', 'komdu', 'jonsdottir', 'hvitir', 'rokkariagnar', 'svanir', 'sildarstulkurnar', 'horfa', 'fyrir', 'lagið', 'alltaf', 'augu', 'þorbergs', 'dimmbla', 'islenskir', 'flokku'], ['við', 'ferðin', 'sungið', 'þyðingar', 'brosið', 'lifið', 'sædyrasafnsins', 'ljoðum', 'ljoð', 'visur', 'gangstiginn', 'yfir', 'engið', 'nutið', 'hvilist', 'mannhafinu', 'tilgangur', 'og', 'hamrinum', 'lifsgrundvollur', 'æva', 'undir', 'aldrei']]

Processing features:  59%|█████▉    | 58/98 [27:57<19:51, 29.78s/it]

getting sample prompt forgetting sample prompt for 24097
 24096
getting sample prompt for 24098
getting sample prompt for 24099
getting sample prompt for 24100
getting sample prompt for 24101
getting sample prompt for 24102
getting sample prompt for 24103
getting sample prompt for 24104
getting sample prompt for 24105
getting sample prompt for 24106
getting sample prompt for 24107
TOP TOKENS [['toss', 'tosses', 'coin'], ['toss', 'tails', 'coin', "the'th", 'space', 'flip', 'flips', 'flipping', 'flipped'], ['toss', 'tosses', 'heads', 'coin', 'tails', 'tossed', 'tossing'], ['flip', 'coin'], ['tossing', 'flip', 'tossed', 'thh'], ['tosses', 'toss', 'coin', 'heads'], ['flips', 'flip', 'coin', 'lands', 'flipping', 'heads'], ['tosses', 'coin', 'flipping'], ['toss', 'tosses', 'tossing', 'coin', 'landing', 'tails'], ['flipping', 'flip', 'heads/tails', 'it’s', 'coin', 'flips'], ['toss', 'tosses', 'flipping', 'tails', 'flip', 'heads', 'coin', 'e', 'result'], ['tosses', 'flipping', 'coin', 'heads'], ['tosses', 'tossed', 'tossing', 'toss', 'tails', 'flip', 'flipping', "flip's", 'flips', 'coin', 'heads', 'e', '000', 'point', 'flipped'], ['toss', 'tosses', 'tossing', 'lands', 'flipping', 'flips', 'wins', 'coin'], ['tosses', 'flip', 'flips', 'tossed', 'coin', 'heads', 'flipping', 'lands', 'successive', 'two', 'observation'], ['tossing', 'tosses', 'toss', 'flips', 'tails', 'heads', 'coin', 'flipper', 'flipped'], ['flips', 'repetitions', 'flipped', 'tails', 'coin', 'heads'], ['tossed', 'tossing', 'tosses', 'toss', 'heads', 'coin', 'result', 'tails'], ['flips', 'coin', 'flipping', 'heads', 'n', 'many', 'successive'], ['flips', 'flip', 'coin', 'results', 'flipping', 'n', 'tails', 'heads', 'sequence', 'sequences', 'successive']]
TOP TOKENS [['jinnah', 'jinnah(noun'], ['jinnah', 'pakistan', 'bear'], ['jinnah', 'reluctantly', 'died', 'rule', 'pakistan', 'ali', 'came', 'made'], ['jinnah', 'pakistan', 'jinnahbhai', 'قايد', 'ali', 'karachi', 'rights', 'politics', 'however', 'political'], ['jinnah', "book'jinnah", 'ayesha', 'declared', '’'], ['jinnah', "jinnah's", 'ali', 'profile', 'truth', '1919', 'muhammad', 'people', '1906', 'quick', 'court', 'relentless'], ['jinnah', 'pakistan', 'ali', 'congress', 'mohammad', '14', '1948', '1916', 'plan'], ['jinnah', 'comparison', 'pakistan'], ['jinnah', "jinnah's", 'jannah', 'ali', '”', 'session'], ["jinnah's", 'jinnah', 'ali', 'round', 'mohammad', 'die-hard', 'grown', 'pakistani', 'nationalist'], ['bagh-e-jinnah', 'jinnah', 'pakistan', 'wolpert'], ['jinnah', 'career', 'ali', 'people'], ['jinnah', 'islam'], ['jinnah', 'jinnahbhai', 'india', 'pakistan', 'camps', 'ali', 'avoid', "lincoln's"], ['jinnah', 'ali', 'muhammad', '1997'], ['jinnah', "jinnah's", 'jinnahbhai', 'english', 'cases', 'camps', 'india', 'gondal', 'bear', 'bombay'], ['jinnah', 'ali', 'portrays', "lincoln's", 'wrote', 'muhammad', 'congress', 'pakistani', 'connon', 'court'], ['jinnah', 'subsequently', 'ali', 'honoring'], ['jinnah'], ['jinnah', "jinnah's", 'ali', 'pandit', 'cls', 'politics', 'links']]
TOP TOKENS [['doctors', 'doctor', 'doctor’s'], ['doctor', '“', 'physician'], ['doctor', 'doctors', 'doctorˈdɒk', "doctor's", 'dr', 'bushel', 'doc', 'der', 'physician', 'cls'], ['doctor', 'doctors', 'physician'], ['doctor'], ['doctors', 'doctor', "doctor's", 'physicians'], ['doctors', 'doctor', 'physicians', 'commemorating'], ['doctors', 'however', 'think', 'physicians', 'problems', 'us', 'among'], ['doctor', 'doctors', 'physicians', 'called'], ['doctors', 'doctor', 'need', 'lives', 'skills', 'solution'], ['doctor', 'dr', 'song'], ['doctor', 'doctors'], ['doctor', 'dr', 'cls', 'cyber'], ['doctor', '2003', '2002', 'draft'], ['doctor'], ['doctor'], ['doctor', 'doctorin'], ['doctors'], ['doctor', 'doctor”', 'doctors', 'protomen', 'film'], ['doctor']]
TOP TOKENS [['terraform', 'terraforming', 'project', 'resources', 'cls', 'address', 'snippet', 'common', 'automation'], ['terraform', "terraform's", 'costs', 'efficiently', 'high', 'cls', 'features', 'datacenter', 'really', 'surrounding'], ['terraform', 'space', 'wise', 'level'], ['terraform', 'terraforming', 'toolkit', 'interface', 'interact', 'despite', 'file'], ['terraform', 'costs', 'capabilities', 'provision', 'prone', 'providers'], ['terracotta', 'terracottas', 'made', '1000°'], ['terracotta', 'boiling', 'heat', 'straight', 'earth'], ['terraform', 'configuration'], ['terraform', 'v0', 's3', 'like', 'backward'], ['terraform', 'capabilities', 'using', 'installation', 'particular'], ['terranet', 'terralink'], ["terrafolk's", 'terrafolk', 'band', 'huge', 'external', 'links', 'also', 'pods'], ['terrani', 'terragni'], ['terra', 'canadian', 'continent', 'deva', 'musician', 'hazelton', 'alta', 'former', 'appearing', 'telomere', 'highland'], ['terrafire', 'far', 'level'], ['terraform', 'terraformer', 'terraforming', 'terra', 'terraformers'], ['terrani', 'terragni'], ['terracotta', 'terra-cotta', 'terra'], ['terra', 'later', 'elkhorn', 'links', 'wiki', 'external', 'storyline', 'hex', 'lassos', 'man'], ['terracotta', "terracotta's", '2.5', 'simplify', 'deployment', 'releases']]
TOP TOKENS [['translations', 'value', 'find', 'numerology', 'provides', 'translation', 'numerical', 'chaldean', 'languages'], ['translations', 'value', 'find', 'numerology', 'provides', 'translation', 'numerical', 'chaldean'], ['chaldean', 'translations', 'value', 'numerology', 'numerical', 'promise', 'pythagorean', 'web', 'away', 'provides', 'translation'], ['translation', 'value', 'numerical', 'translations', 'numerology', 'find', 'pythagorean', 'provides', 'possible', 'uniform', 'northern'], ['value', 'translations', 'numerical', 'numerology', 'translation', 'chaldean'], ['translations', 'numerology', 'chaldean', 'numerical', 'find', 'value'], ['translations', 'translation', 'value', 'numerical', 'chaldean'], ['translations', 'find', 'translation', 'numerology', 'value', 'meanings', 'numerical', 'chaldean'], ['translations', 'value', 'numerical', 'numerology', 'provides', 'translation', 'find', 'possible', 'chaldean', 'definitions', 'meanings'], ['translations', 'find', 'translation', 'value', 'numerology', 'numerical', 'daily', 'provides', 'meanings'], ['nationality', 'fortification', 'transport', 'london', 'roundel'], ['cup', 'cls', 'arts', 'entertainment', 'wayside', 'three', "women's", 'fylde', 'ball', 'structures', 'period', "ball'david", 'footballer', 'also', "d'or", 'club', 'see', 'fifa', 'people', 'annual', 'year', 'traditional', "paul's", 'golden', 'born', 'mindscape', 'award'], ['acronym', '10372', 'cls', 'characters', 'agencies', 'moran', 'company', 'land', 'station', 'medal', 'u', 'glacier', 'unisex', 'academy', 'river', 'title', 'radio', 'canyon', 'uses', 'murran', 'streetsboro', 'creek', 'character', 'language', 'science', 'bluff', 'morans', 'elsewhere', 'korea', 'years', 'kibbutz', 'letty', 'tibeto', 'syriac', 'municipality', 'town', 'name', 'richland'], ['mathematician', 'activists', 'mathematicians', 'canonization', 'southern', 'cls', 'coimbatore', 'palliser', 'activist', 'cause', 'united', 'navy', 'sullivan', 'missouri', 'ashburton', 'states', 'j', '–', 'sarum', 'island', '1982', 'counsellor', 'john', 'usually', 'born'], ['digraph', 'neuroethology', 'key', "jacobi's", 'curve', 'cyano', 'cyanogen', 'parameter', 'mathematics', 'computational', 'copernicium', 'acetophenone', 'cyanide', 'hydrology', 'companies', 'ratio', 'attribute', 'rainfall', 'formula', 'chemistry'], ['composer', 'american', 'arachnologist', 'schwendinger', '1962', 'also', 'born', '1998', 'people'], ['palomino', 'athlon', 'uses', 'puerto', 'town', 'processor'], ['numerary'], ['nusantara', 'binus'], ['cyclist', 'guatemalan', 'cereceda', 'landscape', 'altamirano', 'environmentalist', '1854–1931', 'orrego', 'luz', 'immigrant', 'diana', '1966', 'eduardo', 'orrego-salas', 'born', 'peruvian', 'chilean', 'eliana', 'antenor', 'ariana', 'juan', 'manuel', 'socialist', 'ecologist', '1964', '1998', '1981', 'rosario', 'navy', 'villacorta', 'writer', 'colombian', 'gymnast', '1850–1944', '1892–1960', 'rodrigo', '1982']]
TOP TOKENS [['grippers', 'grip', 'gripper', 'handled', 'great', 'better', 'misunderstood', 'use', 'gripz'], ['gripper', 'grip', 'grips', 'grippe', 'lose', 'used', 'exposure', 'dolly', 'chief'], ['grip', 'grips', 'ergonomic'], ['gripped', 'gripper', 'grippers', 'right', 'suitable', 'gripping', 'called', 'common', 'correct'], ['grip', 'gripping', 'situations', '“', 'athletes', 'rescued', 'strength'], ['grips', 'grip', 'type', 'life', '“', 'types', 'losing', 'declining', 'proper', 'gripping', 'gripped', 'good'], ['grips', 'grip', 'type', 'life', '“', 'types', 'losing', 'declining', 'proper', 'gripping', 'gripped', 'good'], ['grip', 'grasping', 'gripper', 'uses', 'grasp', 'arthritis', 'strong', 'require', 'speaking'], ['grip', 'ergonomic', 'grasping', 'gripped', 'hairgrip', 'grasp', 'seize'], ['grip', 'gripping', 'grippers', 'including', 'improve', 'make', 'dexterity', 'secure'], ['grip', '208', 'ltd', 'stranglers', 'berlin'], ['grip'], ['grip', 'unmechanical', 'known', 'mobile'], ['grip', 'grip1'], ['grip', 'compile', 'originally', 'uses', 'registered', '2', 'based', 'however', '17', 'available', 'march'], ['metacritic', 'grip', 'received', 'sep'], ['grip', 'others', '1894', 'grips', 'single', 'external', 'generally', 'racist', 'argues', 'suggests'], ['grip'], ['grip', 'grips'], ['grip', '2015', 'metacritic', 'shortened', 'received', 'line', 'gameplay', '2018', 'often', 'cls', 'planets', 'shotgun', 'littered', 'aggregator']]
TOP TOKENS [['—acts', 'acts', 'earth.”'], ['acts', 'modern', '17'], ['acts', "acts'historicity", 'press', 'theologically', 'ity', 'hypercriticism', 'harnack', 'britannica', 'encyclopædia'], ['acts', 'others.(acts', 'wisdom.(acts', 'faithful.(acts', 'others', '8:35', 'apollos'], ['acts', 'heard', 'christ', 'earth', '’', 'saved'], ['acts', 'gospel', 'world', 'speaking', 'authorities'], ['acts', 'wrote', 'physician', 'depict', 'stuck', 'luke', 'able', 'first-hand', 'day', 'thirty-year', '2'], ['acts', '17', 'chronicled', '27', "god's"], ['acts', 'appeal', 'jesus', 'awaiting'], ['acts', 'lines', 'lydia', 'reading', 'another', 'reason', 'authority', 'church', 'claim'], ['acts', "christ's"], ['apostles', 'scotland', 'genre', 'system', 'german', 'together', 'faith-based', 'satellite', 'acts'], ['acts'], ['acts', 'within', 'pagans', 'claudius', 'contains', 'festus', 'compared', 'parsons'], ['acts', 'either', 'much', 'al', 'etc', 'book', 'report', 'using', 'recommend', 'works'], ['acts', 'parsons', 'considered', 'ramsay', 'became', 'case', 'language', 'historicity', 'unreliable'], ['acts', '–', 'luke', 'epistles', 'lands', 'striking', 'resurrection'], ['acts', 'vaticanus', 'cls', 'antioch', '0', 'galatia', '43', 'timothy', 'corinth', "paul's", 'bezae', 'top', 'verses', 'anonymous', 'label', 'bible', 'cenchrea', 'well', 'size'], ['acts', 'cls', 'testament', 'references', 'witnesses', 'verses', 'century', '1', 'luke', 'gospel'], ['acts', 'cls', 'verses', 'wikitable', 'serves', 'verse', 'containing', 'references', 'sinaiticus']]
TOP TOKENS [['pork'], ['pork'], ['pork', 'idea', 'favorite'], ['pork'], ['pork'], ['pork'], ['pork'], ['pork'], ['pork', 'true', 'years', 'misleading', 'salt'], ['pork', 'true', 'years', 'misleading', 'salt'], ['pork'], ['pork'], ['pork', 'world'], ['1974'], ['pork', "pork's", '2008', 'cadillacs', 'august'], ['porker', 'porkers', 'lie'], ['pork'], ['pork'], ['pork'], ['pork']]
TOP TOKENS [['deciduous', 'plants', '“', 'trees', 'word', 'leaves', 'number', 'term', 'fall'], ['deciduous', '“'], ['deciduous', 'requested', 'highly', 'term'], ['deciduous', 'deciduous(redirected', 'falling'], ['deciduous', 'semi-deciduous', 'also', 'horticulture', 'converse', 'many', 'southeast', 'sense', 'herbaceous', 'metasequoia', 'leaves'], ['deciduous', 'need', 'maturity', 'uses', 'close'], ['deciduous', 'wholesale', 'course', 'certain', 'quantity', 'availability', 'helps', 'many', 'hardwood', 'home', 'flowers', 'board', 'minimum', 'functionally', 'commercially'], ['deciduous', '1900', 'medium', '‘', 'start', 'sized', '”', 'take', 'bare', 'choose', 'maintain', 'term', 'perfect', 'selecting', 'must'], ['deciduous', 'shoes', 'word', 'temperate', 'known', 'types', 'cls', '200', 'well', 'hardwood', 'flat', 'commonly'], ['deciduous'], ['deciduous'], ['deciduous', 'horticulture', 'many', 'converse', 'periods', 'term', 'natural', 'botany', 'processes', 'sheds', 'semi', 'leaves'], ['deciduous', 'botany', 'abscission', 'year', 'conserving', 'continuously', 'influenced'], [], ['come', 'ailments', 'mouth'], ['beah', 'clutter'], ['lovely'], [], ['0', 'kept'], []]
TOP TOKENS [['brisbane', '1859'], ['brisbane', '9', '6', '5', '”'], ['brisbane', "brisbane's", 'district'], ['brisbane', 'brisbanebrisbane', 'brisbane(redirected', 'brisbane(brĭz`bən', '2011'], ['brisbane'], ['brisbane', '647', '646', '728', '13'], ['brisbane', 'greater', '2001', 'recently'], ['brisbane', 'abs', 'gov'], ['brisbane', 'next', 'managers', '9', 'trades'], ['brisbane', '1908', '17', 'viejo', '44', 'daly', '1'], ['brisbane', 'hobart-class'], ['brisbane', 'city', '393'], ['brisbane', 'along', 'powerhouse', 'one', 'attendance'], ['brisbane', 'largely'], ['brisbane', 'brisbane’s', "brisbane's"], ["brisbane's", 'brisbane', 'west', 'construction', 'area', 'several'], ["brisbane's", 'brisbane', '5', '41', '2', '0'], ['brisbane', "brisbane's", 'kaohsiung', 'brighton', 'around', 'city', 'wynnum'], ['brisbane', "brisbane's", 'movement', "or'york's", 'ayrshire', 'however', 'cls'], ['brisbane', '1859', 'born', 'art', 'well', 'hub', 'cls']]
TOP TOKENS [['easing', 'quantitative', 'used'], ['easing', 'quantitative', 'employing', 'air'], ['easing', 'implement', 'quantitative', 'period'], ['easing', 'quantitative', 'cls', 'quantative', 'note', 'economy'], ['easing', 'easing,”', '“quantitative', 'quantitative', 'hey'], ['easing', 'quantitative', 'cls', 'since', 'towards'], ['easing', 'quantitative', 'topic', 'things'], ['easing', 'quantitative', 'enact', 'implements'], ['easing', 'quantitative', 'qualitative', 'would'], ['easing', 'quantitative'], ['easing', 'quantitative', 'inequality', 'cls', 'conventional', 'use', 'borrow'], ['easing', 'used', 'quantitative', 'eurozone', 'unk', '和', 'also', 'adopted', 'leaving'], ['easing', 'quantitative', 'discusses', 'bank', '–'], ['easing', 'quantitative', 'trilemma', 'implementing', 'practising', 'lower', 'round'], ['easing', 'quantitative', 'result', 'using', 'policies', 'economies', 'qe'], ['easing', 'quantitative', "people's", 'traditional', 'carry', 'pay', 'despite'], ['easing', 'quantitative', '0', 'amount', 'effects', 'may', 'required', 'found', 'inflating'], ['easing', 'quantitative', 'background', 'prolonged', 'uses', 'done', '2008', 'zero', 'qe', 'periods', 'monetary', 'ultra'], ['easing', 'credit', 'according', 'involves', 'called', '1', 'process', '200', 'money'], ['easing', 'quantitative', 'program', 'expand', 'round', '2', 'stability', 'qe', 'june']]
TOP TOKENS [['pyrolysis'], ['pyrolysis'], ['pyrolysis'], ['pyrolysis', 'industry', 'products'], ['pyrolysis', '10', 'around', 'cls'], ['pyrolysis', '10', 'around', 'cls'], ['pyrolysis', 'gas', '–', 'phase', 'favours', 'c'], ['pyrolysis', 'chemicals'], ['pyrolysis', 'thermolysis'], ['pyrolysis'], ['pyrolysis'], ['pyrolysis', 'pyro', 'combustion'], ['pyrolysis', 'fossils', 'chromatography', 'cls', '–'], ['pyrolysis', 'biofuel', '41'], ['pyrolysis', 'cooling', 'cls', 'subsequent'], ['pyrolysis', 'pyrolyses', 'coils', 'dating', 'use'], ['pyrolysis', 'turbine', 'molecules'], ['pyrolysis', 'century', 'proper'], ['pyrolysis'], ['pyrolysis', 'time', 'consequently', 'many', 'oxidative', 'amount']]

Processing features:  60%|██████    | 59/98 [28:26<19:08, 29.46s/it]

getting sample prompt forgetting sample prompt for 24109
 24108
getting sample prompt for 24110
getting sample prompt for 24111
getting sample prompt for 24112
getting sample prompt for 24113
getting sample prompt for 24114
getting sample prompt for 24115
getting sample prompt for 24116
getting sample prompt for 24117
getting sample prompt for 24118
getting sample prompt for 24119
TOP TOKENS [['wick', 'wicks', 'shot', 'john', 'hamlet', 'burned', 'penis', 'lighter', "veronica's"], ['brack', 'access'], ['huck', "huck's", 'actions', 'reasons', 'ck', 'exclaims'], ['huck', "huck's", 'point', 'companion', 'place', 'jim', 'due', 'stops', 'bat', 'better', 'respect'], ['dirck', 'dirck.see', 'wick', 'darck', '1980-1989', 'dircki', 'dack', '48', '384'], ['brack', 'bracks', '1', '1818', 'also', 'drove'], ['huck', 'world', 'moment', 'would', 'friend', 'however', 'addition', 'jim', 'duke'], ['huck', '810', '807'], ['openstack', 'abstracted', 'virtualized'], ["huck's", 'huck', 'ghost', 'morning', 'straighten', 'much', 'widow', 'woods'], ['bock', 'böck', 'germany'], ['böck', 'bock'], ['halleck'], ['monck', '1678–1751', 'nugent', 'writer'], ['köck', 'kock'], ['keck'], ['merck-saint-liévin', 'merck', 'johann-heinrich-merck-preis', 'finck', '1799', 'co', '1668'], ['kuck', 'kucks'], ['chock', 'chocks'], ['fick', '1852–1937', 'ludwig', "fick's", 'officer']]
TOP TOKENS [['supper', '“', "vinci's", "tintoretto's"], ['supper', 'supperthe', 'painting'], ['supper', '’', 'last', 'crucifixion'], ['supper', 'last'], ['supper', 'last', "vinci's"], ['supper', 'last'], ['supper', '’', 'lord', 'last', 'occurred', 'ceremony'], ['supper', 'crucifixion', 'last', 'thelast', 'sins', 'kingdom'], ['supper', 'last', 'domenico'], ['supper', 'lord’s', 'last', 'gospel', '14:12–25'], ['supper'], ['supper', 'cuadro.artehistoria.jcyl.es'], ['supper', 'last', 'pie', 'vigil', 'crucifixion', 'department', '–'], ['supper', 'chamber', 'music', 'director', 'aunt', 'house', 'ripening', 'opera', 'rhine-westphalia', 'roses', 'screenwriter', '1929', 'jolanthe', 'lotte', '1934'], ['supper', 'last'], ['supper', "lord's", 'climax'], ['supper', 'links', 'last', 'mustafa'], ['supper', 'last', 'christ'], ['supper', 'spanish', 'last', 'biblical', 're-enactment', 'arte'], ['supper', 'ryan', 'rian', 'albums', 'drums']]
TOP TOKENS [['lastname', 'appropriate', 'interested', 'firstname'], [], ['would', 'appropriate'], [], ['appropriate', 'would'], [], ['would'], ['would'], ['would'], ['would'], ["person's", 'sentimentalism', 'sentimental', 'possessed', 'shaftesbury', 'nature', 'one'], ['trite', 'sentimentalism', 'done', 'spurious', 'disproportionate', 'heightened', 'person', 'one', 'hand', 'uncomplicated', 'cls', 'incurring', 'level', 'shallow'], ['also'], ['sentimentality', 'iwasaki', 'sentimentalism', 'philosophy', 'tanita', 'hiromi', 'sentimental', 'voices', 'tikaram', 'kym'], [], [], [], [], [], []]
TOP TOKENS [['refactoring', 'refactored', 'refactor'], ['refactoring', 'refactored', 'refactor'], ['refactoring', 'refactor', 'mind', 'workflows'], ['refactoring', 'refactorings', 'refactor', 'term', 'word'], ['refactoring', 'refactor', 'refactorings'], ['refactoring', 'refact', 'refactored', '‘'], ['refactoring'], ['refactoring', 'refactorings', 'refactoring-capable'], ['refactoring', 'refactorin', 'refactorings', 'refactor', 'word', 'term'], ['refactoring', 'refactormercilessly'], ['refactoring', 'excessively', 'reason', 'simple', 'programmer', 'serve', 'often', 'important', 'needs', 'various', 'clearer'], ['refactoring', 'refactorings', 'refactored', 'sadalage', 'add', 'implement'], ['refactoring', 'http://www.refactoring.com/catalog/extractclass.html'], ['refactoring', 'refactorings'], ['refactoring', 'refactor', 'occupation', 'opportunity', 'code', 'performing', 'public', 'x'], ['refactoring', 'requirements'], ['redactor', 'redact', 'redaction'], ['refactoring', 'namesake'], ['refactoring', 'support', 'database', 'better', 'details', 'drawback', 'thoroughly', 'knowledge', 'verifying', 'major', 'functionality', 'referential', 'rules', 'development', 'techniques', 'performs'], ['refactorings', 'refactoring']]
TOP TOKENS [['https://clojure.org', 'clojure', 'example', '6'], ['clojure', 'structures', 'mean'], ['clojure'], ['clojure', 'clojure’s'], ['clojure', "clojure's"], ['clojure', 'since', 'cls'], ['clojure', 'works'], ['clojure', 'clojure—how', 'others', 'introduced', 'well', 'concurrency', 'possible', 'society'], ['clojure', 'using', 'line', 'introduces'], ['clojure', "clojure's", 'needed', 'cls', 'clean', 'system', 'var', 'correct'], ['clojure', "clojure's", 'explicitly', 'hickey'], ['clojure', "clojure's", 'clojurers', 'clojurescript', 'programming'], ['clojure', "clojure's", 'directly', 'lisps', 'cls'], ['clojure', 'clojurescript', 'explicitly', 'problem', 'extension', 'programming', 'structures'], ['štoj'], [], ['kl', '2020', '2014', '2008', 'people', '2023', '2018', 'mahaveeryar', '2011', '2015', '2022', 'references', 'tiyaan', 'living', 'manoj', '2010'], ['manoj', '1983', 'kannada', 'chennai', 'chakraborty', 'bollywood'], ['piojo', 'piojos', 'louse'], ['ploj', 'slovenian']]
TOP TOKENS [['tourism', 'travel'], ['tourism', 'country', 'tourist'], ['tourism', 'tourist', 'countries', 'economy', 'earnings'], ['tourism', 'travel'], ['tourism', 'country'], ['countries', 'country', 'tourism', 'tourist'], ['tourismconcerned', 'tourism', 'country', 'travel', 'place', '6', 'tourist'], ['tourism', 'countries', 'tourists', 'tourist'], ['tourism', 'country', 'countries', 'place', 'travel'], ['tourism', 'cls', 'tourist'], ['tourism', 'travel', 'world'], ["tourism's", 'tourism', 'economic', "nation's", 'international', 'economy', 'travel', 'policies'], ['tourism'], ['tourism', 'economy', 'culture'], ['tourism', 'tourist', 'destination', 'parts', 'tourists', 'destinations', 'capital', 'technology', 'components', 'government', 'technologies', 'cities'], ['tourism', 'tourist', 'sector', 'economy', 'technology', 'sectors', 'culture'], ['tourism', 'countries', 'tourist', 'ones', 'organization'], ['tourism', 'travel', 'tourists', "world's", 'countries', 'country', 'product', '2010', 'economy', 'worldwide'], ['tourism', 'travel', "master's", 'spencer', 'harris', 'j', 'thesis', 'cultural', 'rouba', 'international', 'john'], ['tourism', 'cultural', 'political', 'economic', 'country', 'asia', 'worldwide', 'world']]
TOP TOKENS [['phi', 'numbers', 'utilizing', 'express', 'nature', 'unconsciously', 'buildings', 'even', 'visible'], ['phi', 'considered', 'records', 'individual'], ['phi-scale', 'phi', 'phidias', 'honor', 'often', 'matte'], ['phi', 'embody', 'reason', 'clear', 'appearance', 'proportions', 'throughout', 'seems', 'see'], ['phi', 'regards', 'considered', 'care'], ['phi', '18', 'know'], ['phi', 'well', 'safeguards', 'protects', 'electronic', 'definition', 'office'], ['phi', 'hipaa', 'date'], ['phi', 'beneficiary', 'confidential', 'privacy', 'r.n', 'job-related', 'however', 'past', 'facilities’'], ['phi', '“', 'phimatrix', 'present'], ['phi', 'alphabet', 'size', 'single', 'dilemma', 'information'], ['phìn'], ['phinam'], ['phi', 'dango', 'solo', 'track', 'kersti'], ['phi'], ['phidian', 'phidias'], [], ['phi'], ['phi', 'stylized', 'official', 'links'], ['phi', 'iv']]
TOP TOKENS [['rand', 'ayn', 'herbert', '1945', 'devices', 'word'], ['rand', 'rand®', 'access', 'sep'], ['rand', 'universe', '’', 'ayn'], ['rand', 'coach'], ['rand', 'courage', 'ayn', 'rather', 'example'], ['rand', "rand's", '2017', 'mentioning', 'gaetano', 'ayn', 'world', 'without', "novel's"], ['rand', "rand's"], ['rand', 'career', 'success'], ['rand', 'follows'], ['rand', 'institute', 'ayn', 'said', 'whenever', 'people', 'society', 'novels', 'family'], ["rand's", 'rand', 'neil', 'said', 'ayn', 'sold', 'robbins', 'work', 'immortality', 'one'], ['rand', "rand's", '2017', 'ayn'], ['rand', 'randlord', 'graphic', 'ayn', 'randburg', 'sperry', 'randfontein', 'afrikaans', 'ingersoll-rand'], ['rand', '1883', 'geography'], ['rand'], ['rand', 'france', 'montagnards', 'career', 'thailand'], ['rand', "rand's", 'education', 'pardee', 'research', 'cls'], ['rand', 'ca', 'william', '1889', 'american'], ["rand's", 'rand', 'philosophy', 'influence', 'disputed', "nietzsche's", 'direct'], ['rand']]
TOP TOKENS [['honey', 'cavities', 'anti'], ['honey', 'rns', 'subcutaneous', 'honeys', 'ros', 'pathogens'], ['honey', 'elevates'], ['honey', 'honeys', 'antimetastatic', 'chemotherapeutic', 'antitumor', 'control', 'onkologii'], ['honey', 'periodontal', 'subcutaneous', 'adhesions'], ['therapeutic', 'ulcers', 'honey', 'clinical'], ['honey', 'cardioprotective', 'antimicrobial', 'ostomy', 'reduced', 'ulcers', 'clinical'], ['honey', 'urinary', 'body'], ['honey', 'clinical', 'incisional', 'wounds', 'antibiotic', 'ulcers', '4'], ['honey', 'clinically', 'medical', 'aetiologies'], ['honey', 'every', 'massaged', 'fokin', 'area', 'palms'], ['bodhon.honey', 'honey', 'ganguly.honey', 'acting', 'chakraborty', 'medical', 'non-acting', 'private', 'krishna', 'practising', 'first', 'industry'], ['honey', 'honeybees', 'honeybee', 'sac', 'currently', 'succumbing', 'bees', "host's", 'movement', 'destruction', 'result', 'appear', 'infection', '2', 'processing', 'bee', 'body', 'illness'], ["bees'susceptibility", 'opportunistic', 'pathogens', 'microorganisms', 'honey', "bees'immune", '15', 'infection', 'gut', 'bees', 'varroa', 'honeybee', 'strengthen', 'genomes', 'mites', 'infestation', 'even', 'infections', 'least', 'microbiota', 'well', 'bee', 'specific', 'mite', 'snodgrassella', 'however', 'genes'], ['honey', 'epithelial', 'humans', 'pathogens', 'nociceptor', 'synaptosomal', 'cells', 'cytokines', 'beehive', 'honeybee', 'pore', 'bees', 'various', 'infectious', 'cell', 'nav1', 'immune', 'bee', 'ii', 'resulting'], ['honey', 'p2o5', 'analysis', 'weighed'], ['medical', 'clinical', 'antihistamine', 'honey', 'people', 'creating', 'scientific', 'removed', 'anti', 'effective', 'exacerbate', 'anaphylaxis', 'anecdotal', 'even', 'either', 'sting', 'stings', 'whether', 'treatment', 'stung', '2'], ['honeybees', 'honeybee', 'infect', 'honey', 'pathogenicity', 'infects', 'virus', 'sbv', '832', 'lineages', "3'end", 'order', 'one'], ['phytopathologists', 'mycologists', 'honey', 'sciences', 'american', 'mycologist', 'life', 'b.s', 'shorewood', 'fields', 'ericaceae', 'pathologist', 'e', 'science', '1948', '1894–1941', 'pathology', 'σξ', 'state', '20th-century'], ['nutcracker', 'gastroesophageal', 'esophagus', 'esophageal', 'patients', 'pathophysiology', 'done', 'pathology', "auerbach's"]]
TOP TOKENS [['watt', 'world', '“', '’'], ['watt', '’', '“', 'world', 'never', 'exhibition'], ['watt', 'wattle', 'wattles', 'celebrate', 'else', 'anybody', 'happy'], ["watt's", 'watt', 'upon', 'birmingham', 'space'], ['watt', "the'watt", "watt's", 'gallery', 'power'], ['watt', 'embodied', 'interference', 'space', 'drilled', '’', 'devices'], ['wattle', 'watt', 'wattles', "wattle'leaves", 'phyllodes', 'parts', 'see'], ['watt', '‘'], ['wattle’s', 'wattle', 'day', 'it’s', 'australia'], ["watt's", 'watt', 'child', 'engine', 'training', 'canal', 'cls', 'e'], ['watt', 'key', 'disambiguation'], ['watt', 'broncos', 'season', 'offense', '2020'], ['watt', 'professional', 'hockeysfuture', 'contests', 'echl'], ['disambiguation', 'band', 'watter', 'twiste', 'watters'], ['watt', 'jedburgh'], ["watt's", 'watt', 'honors', '49ers', 'season', '5', 'boys', 'watson', 'knee', 'bengals', '2', 'window'], ['watt', "watt's", 'lines', 'wattii', 'work'], ['wattle-eye', 'wattle', 'wattles', 'steam', 'black', 'acacia'], ['watty', "watt's", 'watt', '2017', 'university', 'friends'], ['watt', 'worked', 'oxforddnb', '10']]
TOP TOKENS [['around', 'performed', 'centered', 'profiles', 'present', 'analysis', 'show', 'validating', 'revealing', 'analyze', 'comprising', 'results', 'sets', 'identified'], ['show', 'investigated', 'integrates', '“', 'analyzed', 'identify', 'studies', 'systematically', '9640', 'results', 'associations'], ['samples', 'identified', 'performed', 'study', 'identify', 'subtypes', 'wide', 'particular', 'genomic'], ['substudy', 'across', 'samples', 'genomic', 'type', 'identified', 'among', 'stratified', 'specificity'], ['14', 'containing', '129', 'contains', 'relevant', 'specific', 'regarding', 'analyses'], ['profiled', 'analyzed', 'profiles', 'seq', '67', 'identify', 'type', 'study', 'sequence', 'studies', 'find', 'become', 'experiments', 'results', 'suggests', '119', 'genomic', 'also', 'however', 'regions', 'sites', 'around', 'specific', 'human', 'performed', 'suggest', 'consistent', 'immunoprecipitation', 'moreover', '–', 'gene'], ['across', 'specificity', 'datasets', 'furthermore', 'results'], ['study', 'across', 'majority', 'identified', '14', 'using', 'specific', 'identify', 'enriched', 'known', 'find', 'analyzed', 'snps', 'genome', 'seq', 'long', 'vast', 'genomic', 'average', '–', 'terms', 'sequence'], ['identified', 'find', 'wide', 'finally', 'seq', 'sequence', 'used', 'identify', 'data', 'among', '19', 'scale', 'highlighting', 'importance', 'provided', 'order', 'bottleneck', 'us', 'known', 'functionally', 'particular', 'important', 'also', 'types', 'diverse', 'allowed', 'combinatorial'], ['cataloguing', 'showed', 'suggest', 'revealed', 'muscle', 'subset', 'indicated', 'furthermore', 'identify', 'fat', 'four', 'pancreas', 'exons', 'data', 'samples', 'tdmrs', 'analysis', 'liver', 'transcription', 'minority', 'encode', 'thus', 'factor', 'used', 'found', 'despite', 'annotate', 'number', 'predominance', 'genomic'], ['found', 'performed', 'study', 'suspects', 'many', 'provided', 'wide', 'genes', 'metastases', 'ranked', 'analyzed', 'evidence', 'find', 'signatures', 'showed', 'used', 'microarrays'], ['datasets', 'study', 'studies', 'information', 'methods', 'heterogeneity', 'found', '100', '2010', 'revealing', 'around', 'eight', 'however', '300', 'probing', 'indicating', 'studied', '–', 'types', '“', 'including', 'many', '000', 'efforts'], ['various', 'covering', 'type', 'contains', 'focuses', 'detailed', 'found', 'covers', 'classification', 'profiled', 'types', 'scrnaseq', 'different', 'associated', 'lists', 'together', 'available', 'comprises', 'g', 'analysis', '557', '31'], ['across', 'tumours', 'elucidated', 'example', 'studying', '000', 'provide', 'analyzed', 'genomes', 'show', 'studies', 'systematically', 'data', 'notably', 'clinical', 'analyzing', 'repetitively', 'types', 'found', '50', 'regions', 'accumulated', 'pathogenic', 'discovered', 'uncovered'], ['across', 'analysis', 'found', 'types', '000', 'expression', 'exomes', 'clinical', 'study', 'including', 'explored', 'studied', 'emergent', 'profiles', 'exome', 'commonalities', '38', 'develop', 'detect', 'among', 'used', '7', 'whole', 'genomic', 'analyzing', '2018', 'examine', 'diverse', '542', 'studies', 'genomes'], ['across', 'targeted', 'sample', 'addition', 'evidence', 'studies', 'needed', 'provides', 'genotyping', 'found', 'candidate', 'required', 'genes', 'sequenced', 'within', 'exomes', 'discovery', 'derive', 'studied', 'assays', 'number', 'gene', 'order', 'determine', 'identify', 'study'], ['studied', 'unravelling', 'heterogeneity', 'human', 'specific', 'particularly', 'analyses', 'disorders', 'interactome', 'disease', 'including', 'well', 'datasets', 'discovering', 'uncover', 'interactions', 'genomic', 'due', 'typically', 'biases', 'studying', 'found', 'notably', 'spectrometry', 'interactomes', 'characterized', 'amalgamate'], ['across', 'including', 'covers', 'analysis', 'study', '“', 'types', 'various', 'includes', '1132', 'presents', 'annotation', 'classification', 'specificity', 'provides', '1206', 'covering', 'classified', 'profiles', 'spatiotemporal', 'data', 'addition', 'studies', 'gene', 'based', 'contains', 'corresponding', 'lines', 'protein', 'also'], ['targeted', 'identify', 'test', 'clinical', 'locate', 'heterogeneity', 'many', 'tested', 'discover', 'analysis', 'disease', 'human', 'identified', 'complex', 'discovery', 'challenging', 'specificity', 'diagnose', 'causative', 'treatment', 'valuable', 'including', 'potential', "bilgular's", 'diagnostics', 'demonstrates'], ['revealed', 'concluded', 'many', 'genotyping', 'found', 'study', 'sequence', 'similarly', 'total', 'catalogued', '1', 'individuals', 'indicating', 'least', '6', '1111', 'carry', '041', 'genomes', 'outs', '2', 'estimated', '19', '472', '8', '584', '885', 'representative', 'diseases', 'orthologs', 'homozygous']]
TOP TOKENS [['“physical”', 'physical'], ['physical', 'physicalmiddle', 'physicalis', 'carnal', 'bodily', 'real', 'according', 'medical'], ['physical', 'real-world'], ['physical', 'something'], ['physical', 'physicals', 'primary'], ['physical'], ['physical', 'actual', 'current', 'biggest', 'early'], ['physical', 'actual', 'current', 'biggest', 'early'], ['physical', "category'physical", "category'physical'would", "of'physical", 'something', 'physicalists', 'process', 'non'], ['physical'], ['physical'], ['physical', 'release'], ['physical', 'practical'], ['physical', 'new', "juran's", 'personal', 'detailed', 'technical', 'd4169', 'materials', 'experiment', 'quantitative', 'measurable', 'scientific', 'assurance'], ['physical', '2020', '2022', '28', "john's", 'e', 'bit', 'frenetic', 'cosmopolitans', 'accolades', 'michael'], ['physical', 'less', 'hand', 'alternative', 'related'], ['physical', 'diego', 'scovel', 'goldman', 'dierdre', 'friel', 'cls', 'kilmartin', 'jose', 'geoffrey', 'season', 'paul', 'kazam', 'august', "tanya's", 'breem', 'comedy', 'rory', '1', 'liberal'], ['physical', 'roger', 'recording', 'clients', 'earlier', 'consecutive', 'reception', 'two', 'declined', "let's"], ['physical', 'object'], ['physical', 'many', 'directly', 'chemical', 'irreversible', 'general', 'every', 'repeatedly', 'composition']]

Processing features:  61%|██████    | 60/98 [28:57<18:58, 29.97s/it]

getting sample prompt forgetting sample prompt for 24121
 24120
getting sample prompt for 24122
getting sample prompt for 24123
getting sample prompt for 24124
getting sample prompt for 24125
getting sample prompt for 24126
getting sample prompt for 24127
getting sample prompt for 24128
getting sample prompt for 24129
getting sample prompt for 24130
getting sample prompt for 24131
TOP TOKENS [['things', 'vehemently', 'well', 'way'], ['vigilant', 'always', 'ever'], ['tending', 'expediency'], ['unk'], ['competent', 'authority', 'presbyterate', 'impediment', '1', '§', 'without', 'recourse', '2'], [], ['attempts', 'deliberate', 'spirit'], [], ['anything'], ['el', 'su', 'legal', 'la', 'las'], ['relations'], ['patriotes', 'trans'], ["panama's", 'even', 'coercion'], ['hooliganism'], [], ['1920', 'civil', 'rzeczypospolitej', 'na', 'disestablishments', 'władz'], ['century', 'law', 'could'], ['efforts', 'noted', 'singularly', 'effective', 'along'], [], []]
TOP TOKENS [['dysplasia', 'dysplastic'], ['dysplasia', 'dysplasiaanastasia'], ['dysplasia'], ['dysplasia'], ['dysplasia'], ['dysplasia'], ['dysplasia', 'neoplasia'], ['dysplasia'], ['dysplasia', 'hip', 'whose'], ['dysplasia', 'dysplasias'], ['dysplasia'], ['dysplasia', 'dysplasias', 'dysplastic'], ['dysplasia', 'hip'], ['dysplasia'], ['dysplasia', 'dysplastic'], ['dysplasia', 'hyperplasia'], ['dysplasia', 'dysplastic'], ['dysplasia', 'dysgenesis'], ['dysplasia', 'hip'], ['dysplastic', 'dysmorphism', 'dyskeratosis', 'rabah']]
TOP TOKENS [['galway'], ['galway', "galway's", '1652', 'however', 'length', 'seduced'], ['galway', "galway's", 'county', 'television', 'ireland', 'soft'], ['galway', 'surprise', 'fact'], ['galway', 'county', 'however', 'though', 'overall'], ['galway', 'galway….ireland'], ['connacht', 'galway', "galway's", 'rest', 'minutes', 'drunks', 'night', "if'colourful'place", 'rain'], ['galway', 'base', 'ireland', '1651', 'remarkable'], ["galway's", 'galway', 'unk', 'one', 'street', 'others', 'budget', 'including', 'spanish', 'bookshop'], ['galway', 'chonchuir', 'city', 'smaller', 'starkly'], ['galway', 'county', 'though', 'one', 'aughrusbeg', 'maumeen'], ['galway', 'ireland', 'republic', 'connacht'], ['galway', 'county'], ['galway', 'connacht', 'mayoralty', 'decline'], ['galway', 'connacht', 'irish'], ['galway', 'baronet', 'geoffrey', 'thomas', 'sir', 'disestablishments', '1661–1666'], ['galway', 'musician', 'irish', 'constituency', 'ireland', '1939', 'village'], ['galway', '45', 'households', '39', 'families', '9', 'males', '37', '750', '75', '11', '2'], ['galway', 'reliquary', '6d', 'nuns', '1696', 'mercy'], ['film', 'galway', 'people', 'canadian', 'development', 'including']]
TOP TOKENS [['rename', 'renamed', 'renaming', '‘', 'easily'], ['‘rename', 'rename', '‘rename’', 'renamed'], ['rename', 'renaming', '‘', 'renamed', 'line'], ['rename', 'renaming', '‘', 'renamed', 'line'], ['rename', "rename's", 'renamed', 'renames'], ['rename', 'rename-status', 'renames', 'renamed'], ['renamed', 'rename'], ['rename'], ['rename', 'renamed', 'want'], ['ws-rename', 'renaming', 'rename', 'renames', 'ws-d', 'ws-num'], ['renaming'], ['rename', 'renames', 'renaming', 'automate', 'process'], ['rename', 'renamer', 'renaming', 'renumber', 'options'], ['renamed', 'rename'], ['rename'], ['rename', 'renamed', 'renamer', 'renamers', 'renaming', "rename'en", 'authoring'], ['rename', 'provide', 'command', 'example', 'ren'], ['renames', 'rename', 'per', 'renamer', 'vista', 'features', 'systems', 'folder', 'xp', 'files', 'type', 'names', 'subdirectories'], ['rename', 'renamed', 'renaming', 'file03', 'batch', 'file02', 'notable', 'consideration', 'programs', 'fichiers'], ['rename', 'name']]
TOP TOKENS [['gibbs', 'though', 'salary', '’', 'doubted', 'minds', 'get', 'factories'], ['gibbs', "gibbs's", 'work', '1899', 'chemistry', 'found'], ['gibbs', "gibbs's", 'view', 'research', 'characteredit', 'time', 'except', 'life'], ['gibbs', "gibbs's", 'time', 'thermodynamics', '1889', 'heaviside', 'death', 'nature'], ['gibbs', "gibbs's", 'work', 'yale', 'gibbsian', 'notation'], ["gibbs's", 'gibbs', 'research', 'view', 'contributionsedit', 'years', '1884', 'genius', 'men'], ['gibbs', 'external', 'version', 'links', 'willard', 'algorithms', 'sampled', 'physics', 'however'], ['gibbs', "gibbs's", 'honour', 'person', 'willard'], ['gibbs', "gibbs'important", 'yale', 'died', 'cls', 'also', '1869', 'one'], ['gibbs', 'using', 'patients', "gibb's", 'situation'], ['gibbs'], ['gibbs', 'games', 'expatriate', '2009', 'game'], ['gibbs'], ['gibbs', 'seasons', 'wherein', 'injury'], ['gibbs', 'critic'], ['gibbs', "gibbs'contract", '2004', 'football', 'f', '2003', "men's", 'c'], ['gibbs', 'jeffers', 'cls', 'born'], ['gibbs', 'games', '2019', 'belgium', "men's"], ['gibbs', 'qualifiers', 'expatriate', 'f', 'berhalter', "men's", 'zealand'], ['gibbs']]
TOP TOKENS [['odi', 'plus', 'manufacturer', 'ports', 'therefore', 'https'], ["that's", 'transformers'], ['rovs', 'unworkable', 'functions', 'associated', 'system', 'rov', 'easily'], ['odissi', 'one', 'enrich', 'form', 'sculptures', 'citaristi', 'also'], ['odissi', 'beats', 'reknowned', "the'maharis", 'also', 'though', 'krishna', 'way', "of'gotipua'music", 'bhanja', 'alas', "of'mardal'players", "to'pakhawaj", "hindustani'dhrupad'style.'gamak'is"], ['mina', 'describing', 'rashi', 'shakti', 'e', '”', 'observables'], ['odissi', 'subsequently', 'odisha', 'moksha', 'completely', 'nacha', 'sep', 'elements', 'magadhi', 'forms', 'also', 'system', 'music'], ['odissi', 'form', 'jha', 'abroad', 'dancers', 'moksha', 'control'], ['keeping', 'exist'], ['odiya', 'literature', 'however', 'drama', 'management', 'vogue'], ['odissi', 'odia', 'jasobanta', 'jagamohana', "named'odia", 'ramayana', 'dasa', 'works', 'century', 'literature', 'bhagabata', 'including', 'banamali'], ['odissi', 'odisi', 'giving', 'status', 'odisha', '2007', 'patnaik'], [], ['odissi', 'odia', 'odisi', 'odisha', '2007', 'rethinking', 'sangeet', 'das', 'parasher', 'akademi', 'pad', 'pathy', 'panigrahi'], ['international', 'aeronautics', 'aerospace', 'possibilities', 'within', 'sep'], ['odissi', 'status', 'legends', 'items', 'goddesses', 'puri'], [], ['odissi', 'odias', 'odia', 'odisha', '2015', 'originality'], ['mechanics', 'therefore', 'e', 'also', 'equations'], ['telepathic']]
TOP TOKENS [['enhancers', 'enhancer', 'factors', 'thousands'], ['enhancement', 'enhance', 'enhancements', 'enhances', 'package', 'spots', 'points'], ['enhancer', 'enhanceradvancer', 'enhancers', 'enhances', 'one'], ['enhancements', 'enhancement', 'leveraging', 'effectively'], ['enhancer', 'enhancers', 'enhances', 'one'], ['enhancers', 'enhancer', 'factors', '000', 'eukaryotes', 'identified', 'specific'], ['enhancers', 'enhancer', 'factors', '000', 'eukaryotes', 'identified', 'specific'], ['enhancers', 'enhancer', "enhancer's", '1', 'factors', 'genes', 'may', 'site'], ['enhancers', 'enhancer', 'relient', 'within'], ['enhancements', 'enhancement', 'expectations', 'functionality', 'important', 'ensure', 'issues', 'performance', 'without'], ['enhancer'], ['enhance', 'disambiguation', 'additional', 'enhancement', 'blip', 'reverberant', 'self-enhancement', 'natural', 'via', 'quality', 'augmentation'], ['enhance', 'enhancer'], ['enhancer', 'enhanceosome', 'enhanceosomes', 'enhancers', 'towards', 'special', 'activator'], ['enhancer', 'enhancers', "enhancer's", 'genes', 'factors', 'bp', 'may', 'upstream', 'genetics'], ['enhancers', 'enhancer', 'identity', 'quantifiable'], ['enhancers', 'enhancer', 'typical', 'enriched', 'may'], ['enhancers', 'enhancer', 'applying', 'identified', 'factors', 'wide'], ['enhanced', 'enhancements', '3,000', 'many', 'united', '2004', 'used', 'water', 'states', 'flavors'], ['enhancers', 'enhancer', 'induced', 'putative', 'quantifying', 'cohort', 'enriched', 'strongest']]
TOP TOKENS [['prentice', 'alvin', 'man', 'children', 'lesson', 'godlike', 'young', 'apprentices', 'bear', 'fabled', 'teach'], ['pinto', 'amos', 'handcart', 'cattle', '1856', 'rufus', 'coleman', 'paiute', 'constable', 'grain', 'utah', 'h', 'thornton', 'hay', 'men', 'benjamin', 'widow', 'unmarried', 'spanish', 'old', 'allen', 'tullis', 'trail', 'area', 'indian'], ['id', 'transaction', 'serialized', 'segwit', 'non-segwit', 'structure', 'transactions', 'something', 'https://bitcoincore.org/en/2016/01/26/segwit-benefits'], ['benitoite', '′', 'eluvial', '“', 'unsuspected', '”', 'day', 'iron', 'deposits', 'crystals', 'forrest'], ['cattle', 'micronutrients', 'pigs', 'vitamins', 'tripe', 'lining', 'sheep', 'nutrients', 'intestines', 'bleached', 'minerals', 'nutrient', 'animals', '’', 'elements', 'health', 'phosphorous', 'healthy', 'essential', 'product', 'acidophilus', 'away', 'goats', 'lamb', 'world', 'stores', 'dogs'], ['strait', 'straits', 'extremity', 'use', '1888', '1892', 'fortune', 'see', 'word', 'driven', 'latin', '1500s', 'adjective', '1800s', '”', 'shakespeare', 'fact', 'figuratively', 'bible', '1900'], ['livestock', 'sheep', 'loco', 'cattle', 'swainsonine', 'leguminous', 'locoism', 'locoweed', 'syn', 'disease', '↑leguminous', '′', 'loh', 'several', 'various'], ['tripe', 'beef', 'vinegar', 'animals', 'clean', 'animal', 'cleaned', 'available', 'food', 'ingredient', 'usual', 'worry'], ['cattle', 'tripe', 'vitamins', 'pigs', 'intestines', 'animal', 'enzymes', 'bleached', 'nutritious', 'health', 'food', 'nutrients', 'nutritional', 'contents', '”', 'disgusting', 'kind', 'untreated', 'unbleached', '’'], ['cleaning', 'utility', 'experience', 'repair', 'supplies', 'equipment', 'worker'], ['smart', 'carrie', 'banjo', 'mr', 'lorraine', 'cast', 'stanley', "welles's", 'pace', "woollcott's", 'broadway', 'theatre', 'performances', '1972'], ['pinto', 'mexican', 'looey', 'genre', 'lousy', 'cullen', 'burton', 'guardian', 'nichols', 'pitts', 'scarecrow', 'elmer', 'ojeda', 'western', '1974', 'crittenden', 'english-language', 'andrew', 'press'], ['caine', 'jones', 'co', 'image', 'gulliver', "heart'n'soul", "band's", 'line', "there'than", 'vocals', 'guitar', 'chelsea', 'cls', 'ex', "somebody's", "more'out", 'turn', 'replaced', 'band', 'mcinerny', 'keyboards'], ['vincent', 'strait', 'head', 'marine', 'spencer', 'flinders', 'gulf', 'jervis', 'coast', 'kangaroo', 'passage', 'line', 'coasts', 'including', 'adjoining', '’', 'peninsula'], ['analgesic', 'magnificum', 'angola', 'klaineanum', 'gabonese', 'schumanniophyton', 'pflanzenfamilien', 'gelsemiaceae', 'taxonomist', 'naturlichen', 'chev', 'africa', 'native', 'good', 'forest', 'liberia', 'schum', 'tree', 'r', 'broad', 'n', 'ex', 'aubrev', 'hiern', '12', 'white', 'die'], ['caine', '11', 'flash', 'older', 'nt', '04', 'ubuntu', '5', 'operating', '18', 'version', 'linux', '9', 'one', 'memory', 'installed'], ['lee', 'sinoe', 'brambila', '2012', 'fitch', 'gelechiidae'], ['caine', "caine's", "caine'remained", 'titled', 'musical', 'boy', 'cane', 'talents', 'paternal', 'drug', 'smith'], ['captain', 'tarantula', 'blood', 'sheep', 'lady', 'comedian', 'manicurist', "jane's", '1922', '1919', 'teeth', 'myrtle', '1905', 'lights', 'actor', '1913', 'templar', 'girl', 'broadway', 'british', 'mouse', 'theatre', 'saxe', '1915', '1916', 'dancers', 'london', 'men', 'casino', 'tiger', 'finchurch', 'man', 'woman', 'starring', 'character', '1924', '1925', '1920', 'capel', 'lily', 'sidewalks', 'unadorned', '1921', 'wife', '1917', 'mary', 'beauty', 'edeveain', '1923'], ['blaise', 'feature', 'valerie', 'tante']]
TOP TOKENS [['add', 'freshly', 'half'], ['add', 'addition'], ['additions', 'added', 'addition', 'adding', 'experts', 'simply', 'part'], ['add', 'addition'], ['added', 'add', 'addition', 'adds', 'adding', 'one', 'shown', 'ways', 'front', 'various'], ['add', 'addition', 'adding', 'added', 'another'], ['added', 'add-ons', 'add–on'], ['add', 'adds', '’', 'command', 'options'], ['add', 'added', 'adds', 'adding', 'something'], ['add', '0', 'equivalent', 'invocation', 'f', 'using', 'false'], ['add', 'addition', '“add”', 'development', 'safety', 'mix', 'advanced', 'cave', 'viagra', 'model', 'loona', '2022', 'defense', 'match', '639-3'], ['added', 'addition', 'onto'], ['add', 'adds', 'addition', 'continues', 'one', 'subgroups', 'numbers', 'referring', 'concrete', 'performing', 'columns', 'number', 'terminology', 'two'], ['added', 'less', 'value', 'may', 'prior', 'therefore', 'analysis', 'integrated', 'distinguished'], ['addition', 'adduct', 'sequence', 'often', 'undergo', 'cycloadditions', 'bromine', "rr'cbr-brcr''r'''(typically", 'double-bond', 'alkynes', 'polar', 'reactions', 'proceeds', "rr'c=cr''r"], ['addition', 'f(y', 'particular', 'theorem', 'components', 'circle'], ['add', 'hardline', 'center', 'previously'], ['adds', 'features', 'added', 'value-added', 'value', 'reseller', 'much'], ['add', '3', '9', '2', '8', '1', '10', 'declared', 'vector', '6', '4', '5', 'true', 'higher', 'g', 'first', 'form'], ['added', 'adding', 'stalwarts', 'someone', 'environment', 'established', 'also', 'form', 'benote']]
TOP TOKENS [['scarlett'], ['scarlett', "scarlett's", 'gone', 'wind', "mitchell's", 'war', 'tara'], ["scarlett's", 'scarlett', 'gone', '1936'], ['scarlett', 'gone', "scarlett's", 'wind', '1936', "o'hara", 'scarlet'], ["scarlett's", 'scarlett', 'gone', "o'hara", "that's", 'wind'], ['scarlett', 'gone'], ['scarlett’s', 'scarlett', 'nonetheless', 'gone', 'sea.”'], ['scarlett', 'answer', 'attitude'], ['scarlett', 'scarletts', 'gone', "o'hara", 'wind'], ['scarlett', 'emotions', 'love', 'gone', 'people', 'well', 'south', 'minds', 'tragic', 'wind', '’', 'rhett'], ['scarlett', "scarlett's", 'rhett', "rhett's"], ['scarlett', "scarlett's", 'rhett', 'gone'], ['scarlett', 'gone', 'wind', "o'hara"], ['scarlett', 'contemporaneous'], ['scarlett', 'song'], ['scarlett', "scarlett's", 'dr', "o'hara", 'gone', 'tells'], ['scarlett', 'gone'], ['scarlett', 'gone', "o'hara"], ['scarlett', "scarlett's", 'gone', 'wind'], ['scarlett', 'gone', "o'hara"]]
TOP TOKENS [['meatballs', 'meatball'], ['meatballs', 'meatball', 'baking'], ['snowball', 'equal', '’', 'power', 'cause', 'unchecked', 'animals', 'society', '–'], ['meatball', 'meatballs', 'meatballstickball', 'spitball'], ['cheeseball', 'cheeseballs', 'cheeseballday', 'year', 'puffed', 'pineapple', 'ball'], ['snowball', 'enigmatic', 'confuse', 'ideals'], ['meatballs', 'meatball', 'org', 'meatloaves', 'flavor', 'dill', 'definition', 'give'], ['paintball', 'least', 'speedball'], ['fireball', 'roughly', 'area', 'equal', '33,000'], ['snowball', '’', 'progresses', '10'], ['hands', 'snowball', 'shaved', 'recruit', 'exotic', '1983', 'version', 'baltimore'], ['butterball', 'creek', 'herb', 'cenobite', 'township', 'butterballs', 'bassett', 'cream'], ['fireball', 'fireballs', 'punkabilly', '1988', 'purple'], ['powerball', 'speedball', 'powerballing'], ['reitman', 'meatball', 'metaballs', 'meatballs', 'aem-7', 'meatball(s', 'terms#meatball', 'carriers', 'campaign', 'wrestler', 'system', 'area', 'catobar-oriented', 'aircraft', 'preparation', 'surgery'], ['band', 'thunderball'], ['eyeball', 'eye'], ['paintball', 'drugs', 'drug', 'composition'], ['caenocara', 'puffball'], ['fireball', "fireball's", 'paperball', 'jahr', 'nurhan']]
TOP TOKENS [['infestations', 'cause', 'aesthetic', 'food', 'reside', 'create', 'problems', 'water', 'damage', 'inside', 'prefer', 'eat', 'meat'], ['droppings', 'enter', 'near', 'fallen', 'parasites', 'uncollected', 'diseases', 'faults', 'ground', 'around'], ['infestation', 'inhabit', 'living', 'contaminate', 'droppings', 'hazard', 'scurry', 'set', 'environments', 'along'], ['infestation', 'inhabit', 'living', 'contaminate', 'droppings', 'hazard', 'scurry', 'set', 'environments', 'along'], ['source', 'droppings', 'food', 'scurrying', 'making', 'environment', 'warmth', 'home'], ['droppings', 'enter', 'hazards', 'contaminate', 'surfaces', 'diseases', 'behind', 'white', 'occupied', 'residence', 'left', 'damage'], ['droppings', 'disease', '’', 'fires', 'excrete', 'nesting', 'diseases', 'day', 'leave', 'cause', 'making', 'jaundice', 'creatures'], ['infestations', 'infestation', 'deposited', 'accumulate', 'droppings', 'litters', 'environments', 'often', 'though', 'entry', 'nocturnal'], ['infestation', 'droppings', 'stained', 'ground', 'dark', 'nest', 'infestations', 'texture', 'get', 'small', 'cables', 'vegetation', 'putty', 'foundations', 'around'], ['water', 'leaves', 'infestation', 'inside', 'lines', 'firewood', 'environment', 'foundations', 'come', 'enter', 'access', 'place', 'dropped'], ['environment', 'unsightly', 'hazard', 'living', 'droppings', 'live', 'lived', 'pests', 'creatures', 'water', 'exist', 'organisms', 'roosts', 'stonework', 'systems', 'cause', 'nuisance', 'spouts', 'dumps', 'woodpeckers', 'conditions', 'gutters', 'rubbish', 'causing'], ['infest', 'disease', 'infesting', 'diseases', 'contaminate', 'infestations', 'contamination', 'pests', 'plague', 'pest', 'food', 'fleas', 'infection', 'ticks', 'damage', 'infections'], ['grows', 'species', 'found', 'grow', 'surface', 'aphids', 'moulds', 'discolour', 'however', 'peronosporaceae', 'aspergillus', 'mildews'], ['habitat', 'habitats', 'polluted', 'decaying', 'form', 'become', 'presence', 'home', 'found', 'puddles', 'water', 'organisms', 'around', 'surrounding', 'countries', 'rain', 'butterflies', 'disturbance', 'irresponsible', 'life', 'deliberately', 'insects'], ['contaminating', 'disease', 'parasitic', 'mites', 'nuisance', 'chyzeri', 'disliked', 'pathogenic', 'hyphae', 'woodwork', 'nematode', 'manure', 'hibernate', 'nonparasitic', 'crevices', 'place', 'mite', 'muscaedomesticae', 'phoretic', 'heaps', 'pupae', 'infected', 'reptiles', 'congregate', 'arouse'], ['p', 'outdoors', 'species', 'grow', 'environments', 'verrucosum', 'nalgiovensis', 'penicillium', 'prevalent', 'chrysogenum', 'texture', 'occur', 'steckii', 'aspergillus', '—', 'surface', 'growing', 'growth'], ['nesting', 'nest', 'quality', 'scavenge', 'living', 'sounded', 'faster', 'low', 'growing', 'scavengers', 'water', 'environments', 'birds', 'sizes', 'features', 'areas', 'waterfowl', 'frequency', 'geese', 'ducks', 'also', 'coots', 'food', 'year'], ['evil', 'craves', 'spawn', 'create', 'speak', 'predatory', 'hoard', 'health', 'vampire', 'creatures', 'opinions', 'along', 'physical', 'drawn', 'undead', 'mortis', "victim's", 'non', '–'], ['rot', 'tone', 'roam', 'raspy', 'theme', 'thrive', 'water', 'either', 'combat', 'infrastructure', 'sight', 'hair', 'necrosis', 'beings', 'empty', 'critics', 'damage', 'otherwise', 'smaller', 'many', 'afterwards', 'around', 'ruins', 'zombies'], ['residence', 'takes', 'manure', 'come', 'kobolds', 'servants', 'live', 'putting', 'creature', 'home', 'cold', 'enters', 'every', 'pests', 'kobold', "o'clock", 'homeowner', 'tale', 'stays', 'wood', 'someone', 'even', 'strewed', 'go', 'leaves', 'disappeared']]

Processing features:  62%|██████▏   | 61/98 [29:27<18:27, 29.93s/it]

getting sample prompt forgetting sample prompt for 24133
 24132
getting sample prompt for 24134
getting sample prompt for 24135
getting sample prompt for 24136
getting sample prompt for 24137
getting sample prompt for 24138
getting sample prompt for 24139
getting sample prompt for 24140
getting sample prompt for 24141
getting sample prompt for 24142
getting sample prompt for 24143
TOP TOKENS [['groups', 'live'], ['people', 'groups', 'ethnic', 'belong', 'group', 'etnologically'], ['another', 'groups', 'major', 'tribe'], ['group', 'people', 'live', 'tirurays', 'separate', 'peoples', 'ethnic', 'reside', 'bagobo', 'one'], ['peoples', 'telise', 'group'], ['peoples', 'people', 'tabasarans', 'inhabited', 'group', 'cls', 'called', 'dargin'], ['group', 'people', 'tribe', 'ethnic', 'groups'], ['group', 'living', 'people', 'known', 'cls', 'ethnic', 'belonged', 'one'], ['groups', 'live', 'ethnic'], ['lived', 'people', 'tribes', 'live', 'living', 'groups', 'group', 'called'], ['tribe'], ['tribes', 'sindhi', 'people'], ['people', 'groups'], [], ['groups', 'group', 'nomads', 'jamshidis', 'include'], ['groups', 'people', 'peoples'], [], ['peoples'], ['people', 'groups'], ['nyishi', 'group']]
TOP TOKENS [['acorns', 'acorn', 'effect'], ['acorns', 'acorn', 'eat'], ['acorns', 'acorn', 'minutes'], ['acorns', 'acorn', 'one'], ['acorns', 'acorn', 'species'], ['acorns', 'acorn'], ['acorns', 'acorn'], ['acorns', 'acorn', 'eat'], ['acorns', 'acorn'], ['acorns', 'acorn'], ['acorns', 'acorn'], ['acorn', 'grids', 'screenshots', 'features', 'runs', 'major', 'framework'], ['acorn'], ['zorn'], ['acorns', 'acorn'], ['acorn', 'filbert'], ['acorns'], ['acorn-bearing', 'acorn'], ['acorn', '432,192,100,000', 'women'], ['acorn', 'acornridge', 'remained']]
TOP TOKENS [['draco', 'draconian'], ['draco', "draco's", 'draconian', 'dracon', 'drakōn'], ['draco', 'dipper', 'polaris'], ["draco's", 'draco', 'draconis', 'abbreviation'], ['draco', 'repute', 'may'], ['draco', 'syracuse', '5', 'hill', '3400'], ['draco', 'draconids', 'constellation', 'camelopardalis', 'rastaban', 'cls', 'eltanin'], ['draco', 'draconian'], ['draconids', 'draco', 'draconis', 'although', 'constellations', 'cls', 'cometary'], ['draconids', 'draco', 'draconis', 'although', 'constellations', 'cls', 'cometary'], ['draco', "draco's", 'draconian', 'superdraco'], ['draco', 'draconian', 'drako'], ['draco', "draco's", '7.62×39mm'], ['“draco”', 'draco'], ['draco', 'draconian', 'draconic'], ['draco', 'dracon', 'hippocrates'], ['draconian', 'bosconian', 'enemy', 'links'], ['draco', 'draco-to-c'], ['draco'], ['draco', 'draconian', 'draconic', 'draconia', '1984', 'disambiguation']]
TOP TOKENS [['stirling', 'lindsey', 'archie'], ['stirling'], ['stirling'], ['stirling', '7.2', 'vcr', '4', 'warmer'], ['stirling'], ['stirling', 'robert', 'fundamental', 'routine', 'steam', 'one', 'engines'], ['stirling', 'cooler', 'ayrshire'], ['stirling', 'robert', 'rpm'], ['stirling', 'yachts'], ['stirling', 'mechanical'], ['stirling', 'australia', 'victoria', 'bighill', 'center', 'large'], ['stirling', "stirling's", 'work', 'external', 'moral', 'links', 'values'], ['stirling'], ['stirling', "stirling's", 'industry', 'closed', 'campground'], ['stirling', '1726−1783'], ['stirling', 'davis-stirling', 'adams-stirling', 'assembly', 'california', 'motive', 'higher', 'legislation'], ['stirling', '1953'], ['stirling', "stirling's", 'champions', '2008', 'row'], ['stirling', 'stirlings', 'automotive', 'systems'], ['stirling', "stirling's", 'ayrshire', 'efficiency']]
TOP TOKENS [['9', 'september', '11', '2001', '11th', '11attacks', 'sept'], ['9', '11', 'september', '11th', '2001', 'sept'], ['9', '11', 'september', '11th', '2001'], ['9/11', '9/11″', '11', 'september', '11th', '2001', 'trade', 'world'], ['9', 'september', '11', '11th', '2001', 'sept'], ['september', '9', '11', 'eleventh'], ['9', '11', 'prosperity', 'september', '“', 'reality', 'cls', '2001', 'post'], ['9', '11', 'september', '2001', 'happened', 'thing', 'act'], ['9', '11', 'september', 'day', 'recently'], ['9', '11', 'september', '11th', 'happened'], ['9', 'september', '11', 'trade', 'attacks', 'world'], ['9/11', '11', 'september', '2001', 'attacks'], ['9', 'september', '11', 'trade', 'attacks', 'news', '2001'], ['11', 'september', '911', '2001'], ['september', '11', '9-11'], ['11', '9', 'september'], ['9', 'september', '11', 'sept', 'trade', 'attacks'], ['9', 'september', '11', '2001', 'attacks'], ['9', 'september', '11', '2001'], ['9', 'september', '11', '11th', 'attacks', '2001']]
TOP TOKENS [['law', 'legal', 'lawyers', 'lawyer', 'laws'], ['law', 'law/interpretation', 'statutes', 'court'], ['laws', 'law', 'legal', 'lawyer', 'lawyers', 'case', 'practice', 'court', 'legislative'], ['law', 'laws', 'legal', 'judges', 'judge', 'legally', 'cases', 'legislation', 'case', 'court'], ['law', 'lawyers', 'legal', 'lawyer', 'juris', 'cases', 'court'], ['law', 'lawyers', 'legal', 'lawyer', 'cases', 'jurisprudence'], ['law', 'statutes', 'legal', 'judges', 'area', 'cases', 'case'], ['legal', 'law', 'judicial', 'courts', 'statutes', 'court', 'cases'], ['law', 'jurisprudence', 'lawyers', 'legal'], ['law', 'legal', 'lawyer', 'lawyers', 'justice'], ['law', 'laws', 'lawyers', 'legal', 'justice', 'juris'], ['law'], ['law', 'laws', 'legal', 'juris', 'attorneys', 'legally', 'court', 'courts', 'jurisdictions', 'doctor'], ['law', 'legal', 'judicial', 'case', 'cases', 'lawsuits', 'court', 'courts'], ['law', 'legal', 'jurisprudence', "law's", 'litigation', 'courts', 'cases', 'justice', 'attorneys'], ['law', 'legal', 'statutes', 'jurisprudence', 'case', 'rules', "court's", 'cases', 'courts', 'judges', 'court'], ['legal', 'law', 'laws', 'court', 'codes', 'decisions', 'jurisdictions'], ['law', 'cases', 'legal', 'judges', 'research', 'lawyering'], ['legal', 'law', 'laws', 'lawyers', 'judges', 'courts', 'lawsuit', 'juris', "barristers'chambers", 'attorney', "judge's"], ['law', 'jurisprudence', 'legal', 'courts', "court's", 'court', 'decision', 'v', 'judges', 'liability', 'areas']]
TOP TOKENS [['sources', 'aware'], ['looking', 'sources'], ['information', 'accuracy', 'evaluate', 'authority'], [], [], ['sources'], ['whether', 'information', 'like', 'sources', 'encountering', 'fact-checked', 'reliable', 'evaluate', 'look'], ['looking', 'source', 'sources', 'fact', 'checkers'], ['strict', 'research', 'sources.articles', 'scrutinize'], ['look', 'sources'], ['researching', 'whether', 'trust', 'unbiased', 'consideration', 'research', 'trustworthiness', 'sources', 'information', 'source', 'looking', 'certain', 'mind'], ['looking', 'sources', 'mind', 'source', 'whether', 'information', 'evaluating', 'trusted', 'using', 'media', 'reliability', 'unreliable', 'enough'], ['using', 'evaluating', 'sources', 'vol', 'edition', 'credibility', "wikipedia's", 'writing', 'cromwell', 'r', 'new', 'http', 'firstmonday', 'p', '1', '28', 'examination', 'source', '–', 'accuracy', 'york', 'encyclopedic', '2001', 'nature', 'w', 'research', 'davidson', '4', 'winter', '499', '483'], ['source', 'sources', 'information', 'research', 'check', 'verify', 'fact', 'read', 'reputable', 'reported', 'checking', 'checkers', 'journalistic', 'thorough', 'politifact'], ['fact', 'questionable', 'sources', 'checking', 'inconsistencies', 'misinformation', 'source', 'check', "check's", 'credibility', 'factualness', 'categorizes', '”', '‘', 'datasets', '’', '“', '81'], ['sources', 'credible', 'information', 'find', 'accurate', 'topic', 'give', 'source', 'actual', 'p', 'given', 'subject', 'words', 'according', 'purports'], ['sources', 'wrong', 'information', 'indicating', 'fact', 'checkers', 'read', 'used', 'critical', 'source', 'agence', 'identify', 'counter', 'research', 'checkable', 'agreed', 'evidence'], ['material', 'accurate', 'inaccuracies', 'factual', 'misinformation', 'reliable', 'accuracy', 'analyzed', 'whether', 'inaccurate', 'fact', 'false', 'verifying', 'corrected', 'misconceptions', 'content', 'checking', 'one', 'mixed', 'perhaps', 'statements', 'less'], ['accuracy', 'sources', 'inaccuracies', 'one', 'checking', 'trust', 'quality', 'fact', 'information', 'false', 'poor', 'party', 'verifiability', 'scope', 'susceptibility', 'confirm', 'omissions', 'including', 'reliability', 'reputable'], ['information', "source's", 'sources', 'facts', 'source', 'unbiased', 'something']]
TOP TOKENS [['pest', 'pests', 'conditions', 'contaminate', 'encephalitis', 'food', 'cls'], ['pests', 'pest'], ['pest', 'pests'], ['pests', 'pest', 'control', 'remove'], ['pest', 'pests', 'considered', 'eradicate', '”', 'control'], ['pests', 'pest', 'beings'], ['pests', "pests'causes", 'pest', 'controlling', 'cls', 'others'], ['pests', 'pest', 'conclusion', 'technology', 'behaviors'], ['http://www.stonybrook.edu/ehs/pest', 'pests', 'pest', 'http://www.stonybrook.edu/fixit/pestmanagement', 'control', 'environment', 'managing', 'help'], ['pests', 'pest', 'control'], ['american', 'pest', 'film', 'leguizamo', 'budapest'], ['pest', 'films', 'american'], ['pest', 'external', 'films', 'k', 'elmore', 'links', 'charles', 'james', 'references'], ['pest', 'a.k.a', 'short', 'hardy'], ['pest', 'archaic', 'name', 'connecting', 'independent', 'alternatively', 'local', 'separate', 'three', 'cls', 'history', 'ages', 'contra'], ['pests', 'pest', 'cls', 'conditions', 'crops', 'livestock', 'houseflies', 'homes', 'objectives', 'belong'], ['pests', 'pest', 'notable', 'incitation', 'best', 'well', 'creating', 'havoc', "nhl's"], ['pests', 'term', 'world', 'exhibitions'], ['pest', 'krisztián', 'born', 'neumarkt/pötting', 'baranya'], ['pests', 'pest', 'considered', 'regard', 'word', 'sense', 'also', 'plants']]
TOP TOKENS [['things'], ['opportunities'], ['ground', 'james', 'believes'], ['things'], ['places', 'example', 'unreliable'], ['fields', 'creating', 'making', 'well', 'way', 'find', 'improve', 'develop', 'tweaking', 'regarding'], ['unintentionally', 'work', 'degrees', "google's", 'attempts'], ['elsewhere'], [], [], ['season', 'duties', 'play', 'offseason', 'unsportsmanlike', 'bowl', 'yard', '–', '11', 'receptions', '3', 'seven', 'significant', 'game', 'gained', 'present', 'eventual', '025', "baldwin's", 'immediately'], ['mares', 'records', 'marroquin'], ['records', 'hollywood', 'gorres', 'american', 'new', 'city', 'hanes', 'singer', 'background', 'also', "song's", 'beach', 'chappell', 'gehringer', 'vocals', 'carpenter', 'bass', '1', 'guitars', 'music', "carpenter's", 'programming', 'served'], ['playoffs', 'season', 'equaling', 'passes', 'pass', '23', 'week', 'weeks', 'receptions', 'yards', 'later', 'threw', 'including', 'less', 'much', 'two', 'following', 'touchdowns'], ['around', 'pitchers', 'base', 'rbi', 'doubleheader', 'hitting', '4', 'hits', '’', 'runs', 'season', 'batted', '987', 'hops'], ['10s', 'indicate'], ['back', '11', '2012', 'midgets', 'years', 'season', 'place', 'year', '’', 'drove', 'prior', 'old'], ["year's", 'make', 'lets', 'completely', 'rosewood', "alison's", 'subject', 'jason', 'order', "toby's", 'something', 'flashback', 'says', 'mind', 'also', 'next', "aria's"], ['single', 'features', 'dates', 'harts', 'titled', '–', 'landed', 'included', 'weeknights', 'spot', 'throughout', 'well', "list'as", 'saying', 'earning', "hendrix's", "j'hit", 'released', 'independent', '24', '2014', 'quickly', 'shredding', 'gained', "who's", 'many', "harts'most", '2016'], ['actor']]
TOP TOKENS [["invader's", 'still', 'ere', 'walked', 'come', 'toiling', 'soil'], ['contestation', 'led', 'hegemony', 'freedom', 'possession', 'history', 'reading', 'still', 'reflected', 'read', 'enacts', 'reflects', 'within', 'representations', 'particularly', 'clearly', 'exists', 'though', '“', '—', 'supremacy', 'potently'], ['notre', 'confrontation', 'vol', 'forces', 'lamonde', 'filteau', "l'histoire", 'de', 'sa', 'members', 'des', 'politique', "l'exposera", 'la', 'que', 'durant', '…', 'ce', 'also', 'vie', 'studies', 'meilleure', 'conseil', 'patriotes', '“', 'ducharme', 'comme', 'according', 'humaines', 'leaders'], ['encountering', 'foot', 'rugged', 'marched', 'troops', 'aggressive', 'natives', 'met', '1839', 'delmar', 'arrived', 'familiar', 'road', 'unmistakably', 'picked', 'remained', 'drove', 'mckenzie’s', 'together', 'bend'], ['passed', 'turned', 'behind', 'walked', 'climbed', 'still', 'stood', '–', 'window', 'around', 'always', 'might', 'one', 'fife', 'mcclure', 'dismissed', '1910', 'county', 'term', 'children', 'time', 'harlan', 'closed', 'sure', 'well'], ['compare', 'heros', 'etc', 'read'], ['climbed', 'jimmied', 'using', 'botto', 'affront', 'authority', 'dadaistic', "boys'parents", 'upon', 'deemed', 'saying', 'sweeney', 'much', 'lightly', 'disciplined', 'student', 'desks', 'boys'], ['climbed', 'jimmied', 'using', 'botto', 'affront', 'authority', 'dadaistic', "boys'parents", 'upon', 'deemed', 'saying', 'sweeney', 'much', 'lightly', 'disciplined', 'student', 'desks', 'boys'], ['like', 'fend', 'assailed', 'use', 'harass', 'avenge', 'oppression', 'would', 'gervase', 'rebels', 'act', 'seaxburh', 'cruelty', 'special', 'another', 'along', 'afflicting'], ['defend', 'bravely', 'every', 'upon', 'others', 'sallied', 'building', 'ladders', 'forth'], [], ['violence', 'blockades', 'served', 'relinquish'], ['motorcyclist', 'took', 'actively', 'part', 'documents', 'near', 'july', 'led', 'arrival', 'uniform', 'besancon', 'seloncourt', 'meant'], ['brutal', 'among', 'remove', 'duffer', "loder's", 'caned', 'captain', "locke's"], ['took', 'prisoner', 'vandals', 'lieutenant', 'era', 'party', "granade's", 'e', 'arms', 'vicinity', '1', 'belonging', 'nearby', '1864', 'houses', 'indeterminate', 'h', 'sloped', 'based', 'side', 'guerrillas', 'clark', 'markers'], ['confrontational', 'action', "natal's", "riebeeck's", 'appearance', "champion's", 'separateness', 'succeeded', "luthuli's", 'bloemfontein', "league's", 'campaign', "anc's", 'league', 'active', 'leadership'], ['c', 'st', 'soccer', "pilsener's", 'competed', 'also', 'b', 'throughout', 'team', 'cup', 'played', '1929', 'league', '1955', 'vaughan'], ['antisemitism', 'chairman', 'proud', 'multiculturalism', 'among', 'supremacist'], ['c', 'reading', 'h', "today's", 'leading', "archie's", 'teams', 'original', 'stars', 'usl2', 'alive', 'soccer', 'league', 'brand', 'team', 'well', 'extraordinary', 'played', 'behind', "men's"], ["power's", 'keep', 'lieutenant', 'resistance', 'way', 'entered']]
TOP TOKENS [['zionists', 'zionist', 'zionism'], ['zionists', 'zionist', 'zionism', 'religious', 'jerusalem', 'jews', 'crusades'], ['zionists', 'zionist', 'everywhere', 'american'], ['zionists', 'zionist', 'zionism', 'critically', 'religious', 'rather', 'theory', 'jewish'], ['zionists', 'zionist', 'zionism', 'jewish', 'principle', 'precedes', 'redirected', 'jews', 'jerusalem'], ['zionist', 'zionism', 'political', 'ideological'], ['zionist', 'zionism'], ['zionist', 'zionism', 'political', "zion'had", "zion'and", "zion'disliked", 'zion', "zion'who", 'secretary'], ['zionists', 'zionist', 'zionism', 'political', 'jewish'], ['zionist', 'zionism', 'st', '20', 'persuing'], ['zionist'], ['zionist', 'proto-zionism', 'zionism', 'anti-zionism'], ['zionists', 'zionist', 'zionism', 'zion', 'external', 'references', 'links'], ['zionist', 'zionism'], ['zionist', 'zionists', 'zionism', 'zion', 'political', 'world'], ['zionist', 'zionists', 'zionism', 'zo'], ['zionist', 'zionists', 'zionism'], ['zionist', 'zionism'], ['zionist', 'jewish', 'yitzhak'], ['zionist', "b'nai", "b'rith", 'israelis', 'zo', 'world']]
TOP TOKENS [['mill', '’', 'enormous', 'reserve', 'commending', 'concluded', 'others', '”', 'sceptical', 'lastly', 'qualities'], ['mill', '’', 'enormous', 'reserve', 'commending', 'concluded', 'others', '”', 'sceptical', 'lastly', 'qualities'], ['mill', 'logic', 'life', 'falsehoods', 'corn', 'would', 'expression', 'majority', 'potatoes', 'today'], ['mill', "mill's", 'philosopher', 'liberty', 'life', 'inductive', 'society', 'deductive', 'period', 'methods', 'residues', 'advocated'], ['mill', '’', 'choice', 'differently', 'furthermore', 'life', 'claims', 'p'], ['mill', "mill's", 'mills', 'liberty', 'rights', 'also', 'taylor', 'life'], ['mill', "mill's", 'address', 'today', 'rightfully', 'offers', 'famous', 'even', 'sets', 'rulers'], ['mill', "mill's", '’', 'members', 'governed', '“'], ['mill', '’', 'links', 'element', 'romantics', 'speech', 'cornerstone', 'reason', 'therefore', 'one', 'offers', 'optimism', 'holds'], ["mill's", 'mill', 'click'], ['mill', "mill's", 'development', 'suggests', 'persistently', 'evidence', 'raised', 'reality', 'stuart', 'argued', 'arguments'], ['mill', 'pleasure', 'chapter', 'bentham', 'ethics', 'swine', 'believed', 'abandons', 'p', 'principle', 'tempts'], ['mill', "mill's", 'individuals', '1869', 'develop', 'greatest'], ['mill', "mill's", 'discussing', 'deserve', 'owing', 'considers', 'elements', 'conflicts', 'appreciates', 'offers', 'famous', 'influence', 'individuals'], ['mill', "mill's", 'development', 'women', 'try', 'felt', 'way', 'relations', 'interests', 'believed', 'population', 'suffrage', 'relationships', 'argued'], ['mill', "mill's", 'although', 'equality', 'consciences', 'also', 'foster', 'others', 'scotland', 'spectrum', 'hand', 'harder', '1869'], ['mill', "mill's", 'period', 'economy', 'association', 'others', 'also', 'income', 'therefore', 'however'], ['mills', '2023', 'appeared', 'better', 'praised', '2022', '1994', 'links', 'time', 'married', 'september', 'award', 'also', 'years', '1979', 'american'], ['mills', '2021', '2020', '2023', '26', '2022', 'century', 'released', '9', 'artists'], ['mill', 'furthermore', 'however', 'falsity', 'also', 'speech', 'affirmed', 'stated', 'held', 'dictators', "voltaire's", 'argued', 'chomsky', 'truth', 'noam']]

Processing features:  63%|██████▎   | 62/98 [29:55<17:40, 29.46s/it]

getting sample prompt forgetting sample prompt for 24145
getting sample prompt for 24146
 24144
getting sample prompt for 24147
getting sample prompt for 24148
getting sample prompt for 24149
getting sample prompt for 24150
getting sample prompt for 24151
getting sample prompt for 24152
getting sample prompt for 24153
getting sample prompt for 24154
getting sample prompt for 24155
TOP TOKENS [['hydrangea', 'hydrangeas', 'called'], ['hydrangea', 'hydrangeas', 'mites', 'times', 'wet', 'plant'], ['hydrangea', 'hydrangeas', 'mites', 'times', 'wet', 'plant'], ['hydrangea', 'hydrangeas', 'optional', 'planting'], ['hydrangea', 'hydrangeas'], ['hydrangea', 'hydrangeas'], ['hydrangeas', 'hydrangea', 'however'], ['hydrangea', 'hydrangeas'], ['hydrangeas', 'hydrangea', 'garden’'], ['hydrangeas', 'hydrangea', 'spot', '8a'], ['hydrangea', 'plants'], ['hydrangea', 'hydrangeaceae'], ['hydrangea'], ['hydrangea'], ['hydrangea', 'hydrangeas', 'hydrangeoides', 'properties', "concolor'moonlight's", "hydrangeoides'roseum's", 'glycosides', 'tea', 'whose'], ['hydrangea', 'also', '‘', '’'], ['hydrangea', 'hydrangeaceae', 'links'], ['hydrangea'], ['hydrangea', 'hydrangeaceae', 'cls', 'inconspicuous', '8', 'showy', 'one'], ['‘hydrangea’', 'hydrangea', 'climbing-hydrangea', 'hydrangeaceae', 'related', 'china', '5–15', "society's", 'closely', '2–3.5', '4–10', '3–5']]
TOP TOKENS [['ehr', 'ehrs'], ['ehr', 'system', '’', 'software', 'well', 'constraints', 'specialist', 'needs'], ['ehr', 'ehrs', '5', 'little', '4', 'ago'], ['ehr', 'ehrs', 'therefore', 'organization', 'record', 'health', '31', '“', 'reason'], ['ehr', 'ehrs'], ['ehr', 'patients', 'medical'], ['ehr'], ['ehr', 'many', 'board', 'contemporaneously', 'cautions', 'recommendations'], ['ehrs', 'ehr', 'settings', 'day'], ['ehr', 'ehrs'], ['ehr'], ['ehr', 'germany'], ['etc', 'ehs', 'school', 'may', 'wildomar', 'disambiguation', 'tucson', 'exchange', 'ellendale', 'eagan', 'high', 'refer', 'phone', 'services', 'esquimalt'], ['ehr', 'ehrs', 'certified', 'referrals', 'checks', 'health', 'drug'], ['disambiguation'], [], ['ehr', 'ehrs', 'ehealth', 'interoperability'], ['ehn'], ['ehr', 'measures', 'certified', 'also', '1', 'systems', '2'], ['ehr', 'ehrs', "ehr's", 'situations']]
TOP TOKENS [['measures', 'multiple'], ['measures', 'tighter', 'upkeep', 'avoided', 'safety', 'mean', 'irreversible', 'others'], ['un', 'measure', 'solution', 'measures', 'considered', '2', 'applied', '1', 'furthered', 'dropped', 'areas', 'operation', '3', 'away', 'issue'], ['measures', 'multiple', 'available'], ['state', '17.50', 'measure', 'quality'], ['important', 'measure', 'measures', "other'named'measures", 'e2', 'additive', 'zero', 'signed'], ['set', 'effective', 'suggested', 'prompt', 'appropriate', 'resources', 'adequate', 'considerable', 'measures', '出', 'took', 'give', 'summer', 'drastic', 'piece', 'measure', '…', 'full', 'achieved'], ['outcomes', 'accountability', 'improvement', 'measures', 'performing', 'individual', 'misuse', 'measure', 'common', '’', 'outcome', 'perceptions', 'policies', 'positive', 'identify', 'anyone', 'overuse', 'including'], ['measures', 'ive', 'corrective', 'also', 'success'], ['measures', 'group', 'infection', 'balancing', 'information'], ['abbington', 'sg-1'], ['measures'], ['measures', '1960', 'measure', 'always', 'inequivalent', 'variations', 'sets'], [], ['measures', '2', 'measure', 'fact', 'nontrivial', 'section', 'positive', 'unique'], ['measure', 'form', 'satisfying', 'fixed', 'processes', 'measures', 'element', 'equivalent', 'null', 'separable', 'mappings', 'induced'], ['st', 'may', '1939', '1964', 'measures', 'vikings', 'england', '84,488', 'james', 'merseyside', 'background'], ['0', 'measures', 'measure', 'references', 'positive', 'tight', 'λn', 'specifically'], ['measures', 'requiring', 'type', 'issues', 'communication', 'secondments', 'similar', 'include', 'information', 'structures', 'figures'], ['measures']]
TOP TOKENS [[], ['screen', 'lives', 'things', 'parthenon', 'writing', 'project', '’', 'picture', 'learning', 'pictures', 'work', 'relationship', 'well'], ['shine', 'earth', 'world', "can't", 'helping', 'planet', 'using', 'dark'], ['called', 'occasionally'], ['making', 'bibly', 'helpful', 'came', 'everything', 'instead', 'js', 'dialog', 'also'], ['also'], ['2013', '12', '6', 'arts', 'letters', '21', 'project', '•'], ['one', 'etc', 'also', 'version', 'happy'], [], ['one', 'ones', 'distinguishable', 'though', 'size', 'flags', 'nevertheless', 'therefore', 'andrew’s', 'even', 'yet', 'later', 'present', 'much', 'enough', 'george’s', 'wales', 'dragon', 'however', 'cross', 'especially'], ['holman', 'moulder', '3', 'david', '21', '15', '–', '24', '25'], ['notes', 'warner', 'british', 'vernon', 'people', 'artist', 'year', 'videos', 'covers'], ['nick'], ['cooper', 'released', 'guitar', 'vocals', 'jeremy', 'v', 'piano', 'producing', 'programming', '07', '3', 'credits'], ["men's", 'gutfleisch', 'place', 'summer', 'competed', 'paralympics', 'players', 'missing', 'people', 'birth', 'also', 'living'], ['vocals', 'jeremy', 'video', '–', 'production', 'programming', '20', 'listing', 'lee', 'also'], ['guitar', 'new', 'uk', 'city', 'production', 'australian', 'writing', 'vocals', '–', 'charts', 'sound', 'clearmountain', 'mixed', 'various', 'history', 'loops', 'palisades'], ['4', '5', '–', '22', '3', '24', '53', '01', '11', 'long', "night's", '49', '03'], ['new', 'people', 'american', 'male', 'century', 'website', "hell's", '2015', 'births', 'nominations'], ['nashville', 'harp', 'ballad', 'version', 'received', 'lee', "lee's", 'song', 'release', 'piano', 'playing', 'composition', 'background', 'also', 'critics', 'charts', 'makes', 'us', 'however', 'production', 'interview', 'musically']]
TOP TOKENS [['davenport'], ['davenport'], ['davenport', 'davenports', 'co', 'well'], ['davenport', 'richard', 'arden'], ['davenport'], ['davenport', 'native', '’', 'present', 'wrote', 'friend', 'said', 'review', 'could', 'carolina', 'genius', 'chapters', '”', 'gaventa'], ['davenport', "davenport's", 'association', 'thousands', 'administration', 'area', 'century', 'affected', 'demand', '62', '2', 'also', 'expansion', 'constructed', '13', 'another', '168', 'ii', "city's"], ['davenport', 'worked', 'church', 'area', 'orlando', 'coast', 'community', 'directly'], ['davenport', 'cleric', '1638'], ['davenport', 'laboratory', 'sciences', 'year', 'steggerda'], ['davenport', "davenport's", 'made', 'provides', 'engineering', 'management', 'according', 'indeed', 'included', 'review', 'rather'], ['davenport', 'series', 'runs'], ['davenport', 'season', '23', '2021', 'basketball', 'sportspeople'], ['davenport', 'harvard', 'day', 'war', 'airplanes', '1973', 'aircraft'], ['davenport', 'harry', 'film', 'gertrude', '–'], ['davenport', "davenport's", 'medalists', '2009', '2022', '1996'], ['davenport', 'links', 'external'], ['davenport'], ['davenport', '2014', 'june'], ['davenport', 'florida', 'davenports', 'manchester', 'peninsula', 'stream']]
TOP TOKENS [['heater', 'heaters'], ['heater', 'heaters', 'place', 'space'], ['heater', 'heaters', 'place', 'space'], ['heater', 'heaters', 'use', 'water'], ['heater', 'heaters', 'water'], ['heater', 'heaters', 'water', 'faucet'], ['heater', 'heaters', 'water'], ['heater', 'heaters', 'water', 'tankless', 'usage'], ['heater', 'heaters', 'water'], ['heater', 'water', 'heaters'], ['heaters', 'water', 'building', 'heater', 'band'], ['heater', '2020', '2011', 'addazio', 'adam', '2013', '2019', 'hired', 'life'], ['peak', 'heaters', 'gone', 'states'], ['heater', 'heaters', 'water', 'electric', 'heating'], ['heater'], ['heater', "heater's", 'heaters', 'water', 'faucet', 'hot', 'burner'], ['heater'], ['heaters', 'heater'], ['heaters', 'heater', 'wire', 'space'], ['heaters', 'heater', 'latter', 'references', 'space-heater', 'designed', '24-volt', 'versions', 'mainly', 'commercially', 'continued']]
TOP TOKENS [['shade', 'problem', 'shaded', '’', 'need'], ['shade', 'shaded', 'shading', 'cls', 'area', 'select'], ['shades', 'shade', 'shadeʃeɪd', 'word', 'n', 'go'], ['shader', 'shaders', 'shades'], ['shader', 'shaders', '“', 'vertex'], ['shaders', 'shade', 'shader', 'shading', 'graphics', 'edge', 'geometry', 'using'], ['shader', 'shaders', 'shaderlab', 'cls'], ['shaders', 'shader', 'explain', 'shading', 'right', 'shaded', 'realistic', 'feeding', 'rasterize'], ["shade's", 'shade', 'shades', 'hour', 'one'], ['shade', "of'shade'in", 'usage', "containing'shade'these", 'lost', "of'shade'example", "of'shade'video", 'rather', 'hue'], ['shades', 'shade', '1862', 'editor', 'mariah'], ['shade', 'w'], ['shade', 'residents', 'called', 'entity', '1880', 'set', 'old', 'village', 'branch'], ['shade', 'board', 'businessman', 'republican'], ['shade', 'lath', '1,000', 'shade-loving', '50'], ['shade', 'although', 'slattery', 'period', 'newspaper', 'march'], ['shaders', 'shader', 'shading', 'geometry'], ['shade', 'shades', 'shading', 'uses'], ['shader', 'shadeop', 'shadeops', 'shading', 'shaders', 'built-in', 'diffuse(nf', 'two', 'within', 'terms'], ['shade', 'shade3d', '14032x19842', 'applications', 'versions', 'current', 'exclusively', 'cls', 'marketed', 'ltd', 'geometry', 'history', '2013']]
TOP TOKENS [['meltdown', 'meltdowns', 'support', 'understanding'], ['meltdown', 'meltdowns', 'safety'], ['meltdowns', 'meltdown'], ['meltdown', 'meltdowns', 'awful'], ['meltdown', 'meltdowns', 'awful'], ['meltdown', 'meltdowns', 'experience'], ['meltdowns', 'meltdown', 'erupts', 'prevent', 'begins', 'cls', 'e', 'etc', 'activities', 'button'], ['meltdowns', 'meltdown', 'times'], ['meltdown', 'meltdowns', 'becoming', 'lesson', 'matter', 'enough'], ['meltdown', 'melting', 'eek', 'later', 'yeah', '’'], ['2000', 'meltdown', '2013', '2001', '1984'], ['meltdown', '128k', 'links', 'end-of-level', '64k', 'sub-games'], ['meltdown', 'links', 'tells'], ['meltdown', '25:23', 'scatter', '2001', '–', '5:14', "wyatt's", '10:25', 'festival'], ['meltdown', 'received', 'described', 'praised', 'something', 'today'], ['meltdown', 'reaction'], ['meinl-weston', 'cloth', 'suffolk', 'west'], ['melton'], ['meltdown', 'also', 'american', 'films', 'diablo', 'known', 'fiction', 'lyman', 'june', '6'], []]
TOP TOKENS [['signalman', '‘', 'signalling', 'signal', '’', 'like', 'spreadsheet', 'date', 'areas', 'relating', 'staff', 'think', 'straightforward', '–', 'wire'], ['signalling'], ['signalling', 'signal', 'type', '”', 'continued', 'relays', 'history', 'route'], ['signalman', 'signalling', 'signal', 'cls', 'british', 'signals', 'route'], ['signalmen', 'signal', 'signals', 'signalling', "a'clear'signal", 'names', 'cls', 'british', 'uk', 'found', 'policemen', 'roles', 'company', 'junction'], ['signal', 'signalling', 'signals', 'made', 'flag', 'corps', 'flags', 'making', 'kit', 'figures'], ['signalperson', 'signaling', 'manual'], ['signalling', 'signal', 'signals', 'system', 'systems', 'drivers', 'type', 'practice', 'obviously', 'railway', 'engineers', 'interlocking', 'driver', 'principle', 'control'], ['signalling', 'answer', 'telecommunication', 'part', 'e.g', '–', 'calling', 'call'], ['signalling', 'signal', 'signals', 'box', 'railway', 'contractors', 'boxes', 'operating'], ['signalman', 'signalmen', 'signaller', "signalman's", 'signalling', 'signal', 'cls'], ['signaller', 'signalman', 'signalmen'], ["signalman's", 'signalmen', 'signalman', 'signaling', 'signal', 'signalling', 'signals', 'system'], ["signaller's", 'signalman', 'signallers', 'signaller', 'signalling', 'signalmen', 'signal', 'including', 'africa', 'control', 'locations', 'states', 'workers', 'could'], ['signalmen', 'signal', 'signalman', 'signalling', 'secondly', 'system', 'relevant', 'box', 'man'], ['signalman', 'signalmen', 'signallers', 'signaller', 'signalling', 'signal', 'signaling', 'signals', 'flaghoist', 'rating', 'rank'], ['signallers', '1991', 'philippines', 'signal', 'signals', 'reservist', 'war', 'command', 'mindef'], ['signal', 'signalman', 'signalbox', 'signalling', 'boxes', 'signalboxes', 'signals'], ['signalman', 'signal-man', 'signal', 'light'], ['signalmen', 'signalling', 'signaling', 'signal', 'control', 'signals', 'wherever', 'locations', 'example', 'boxes', 'purposes', 'line']]
TOP TOKENS [['ivy', 'games', 'attachment', 'eight', 'brooches'], ['ivy', 'ivy’s', 'plant', 'england'], ['ivy', '“ivy', 'genus'], ['ivy', 'wall', 'skin', 'tea'], ['ivy', 'canariensis'], ['ivy', 'humans'], ['ivy', 'family', 'settles', 'topiaries'], ['ivy', 'ruins', 'evergreen'], ['ivy', 'ruins', 'evergreen'], ['ivy', '10-10-10', 'night'], ['araliaceae', 'ivy', 'tilsley', 'liana', 'valentine'], ['ivy', 'heyday', 'office'], ['ivy', '2020', 'wales'], ['ivy', '22', '2006', '2007', '2004', 'american'], ['ivy', 'bill'], ['ivy', 'shortened', '1851', '1750s', 'depot'], ['ivy', 'helix', 'usually'], ['ivy', 'newton', 'interests'], ['ivy', 'villanova', 'interception', 'university', '30', 'touchdown', 'recorded'], ['ivy']]
TOP TOKENS [['apoptosis', 'apoptotic'], ['apoptosis', 'apoptotic', 'phosphatidylserine'], ['apoptosis', 'apoptotic', 'mechanisms', 'key'], ['apoptosis', 'apoptotic', 'excessive'], ['apoptosis', 'apoptotic', 'excessive', 'certainly', 'around'], ['apoptosis', 'anti-apoptotic', 'involved'], ['apoptosis', 'ability'], ['apoptosis', 'e', 'amount'], ['apoptosis', 'apoptotic', 'thus'], ['apoptosis'], ['apoptosis', 'apoptotic', 'cls', 'fourteen', 'excessive', 'blebbing'], ['apoptosis', 'mechanisms'], ['apoptosis', 'apoptotic', 'mechanisms', 'spectacular', 'caspase'], ['apoptosis'], ['apoptosis', 'apoptotic', 'effective', 'defective', 'induce', 'plays', 'anti', '2'], ['apoptosis', 'induced', 'mediated', '221'], ['apoptosis', 'apoptotic', 'mediated', 'increases', 'modulated', 'death', 'sep', 'related'], ['apoptosis', 'apoptotic', 'cause', 'induce'], ['apoptosis', '”', 'induced'], ['apoptosis', 'anti-apoptotic']]
TOP TOKENS [['jepson', '1', 'cylindric', 'stamens', 'pubescens', 'eflora', 'pubescent', 'base', 'madrono', 'ovoid', 'stipules'], ['jepson', 'lobed', 'cauline', 'epipetalous', 'eflora', 'like', '1', 'generally', 'q'], ['jepson', 'salverform', 'epipetalous', 'cauline', 'eflora', 'generally', 'lobed', 'stamens', 'panicle'], ['jepson', '2', 'epipetalous', 'simple', '–', 'generally', 'eflora', 'q'], ['jepson', 'inferior', 'mostly', 'raceme', 'thomas', 'eflora', '3', 'q', 'mcneal', 'b', 'petals'], ['jepson', '–', '2', 'chamber', 'eflora', '0', 'deciduous', '5', 'q', 'base', 'inferior', 'generally'], ['jepson', '–', '2', 'chamber', 'eflora', '0', 'q', 'deciduous', '5', 'inferior', 'base'], ['jepson', 'j', 'eflora', 'shaped', '3', 'yellow', '1', 'q', 'johnson', 'involucres'], ['jepson', 'cauline', 'eflora', 'lancifolium', '5', 'ephemeral', 'q', 'generally', 'worldwide', 'stamens'], ['jepson', 'generally', 'raceme', '1', 'long', 'eflora', '2', '–', '4'], ['jepson', 'eflora'], ['eflora', 'jepson', "jepson's", 'tjm93', 'linn', '2012', 'tjm2', 'h'], ['jepsonii', "jepson's", 'calflora', 'jepson', 'calphotos', 'name', 'contra', 'bristly', 'oval'], ['jepson', 'eflora', "jepson's", 'tjm2', 'jepsonii'], ['jeppo', 'jepson', 'jepsonia', 'fresno', 'one', "jepson's"], ['jepson', 'links'], ['jepson', 'eflora'], ['jepson', 'links', 'malephora', 'treatment', 'cross-section', 'pienaarii', 'smooth'], ['links', 'jepson', 'external', 'jepsonia', 'pinkish', 'three'], ['jepson', "jepson's", 'department', 'county', 'life', 'fruition', 'akron', 'opera', 'personal', 'jersey', 'guild']]

Processing features:  64%|██████▍   | 63/98 [30:23<16:52, 28.94s/it]

getting sample prompt forgetting sample prompt for 24157
 24156
getting sample prompt for 24158
getting sample prompt for 24159
getting sample prompt for 24160
getting sample prompt for 24161
getting sample prompt for 24162
getting sample prompt for 24163
getting sample prompt for 24164
getting sample prompt for 24165
getting sample prompt for 24166
getting sample prompt for 24167
TOP TOKENS [[], [], ['activates', 'angiotensin', 'vasodilator', 'exert', 'ii'], ['activates', 'angiotensin', 'vasodilator', 'exert', 'ii'], ['process', 'neurotransmitters', 'within', 'example', 'act', 'similar'], ['also', 'increase'], [], ['make', 'makes'], ['induces'], ['made', 'stimulates', 'angiotensin'], [], ['angiotensin', 'synthesizes'], [], [], [], ['enzymatic', 'phosphatidylinositol'], [], ['transcripts'], [], []]
TOP TOKENS [[], [], ['united'], ['united'], ['united'], ['united'], ['united', 'america', 'states'], ['united'], ['united', 'states', 'america', 'year', 'hundred'], ['united', 'america', 'states', 'year'], ['united', 'states', '3', 'address', 'wednesday'], ['united', 'states', 'u', 'us', 'congress', 'h'], ['united', 'congress', '116th', 'states', 'enacted'], ['hereby', 'thousand', 'year', 'hundred', 'declare', 'one', 'merciful', 'god', 'proclaim', 'july', 'twenty', 'excellency', 'pertuan', 'majesty', 'whereas'], ['united', 'america', 'states', 'year', 'hereunto'], ['united', 'states', 'us', 'h'], ['united', 'states', 'hundred', 'hereby', 'u.s', 'year', 'america', 'proclamation', '20', 'citizenry', 'issued', 'whereof', 'congress', 'forty-first', 'order', 'therefore', 'country—and'], ['united', 'states', '113th', 'federal', 'congress'], ['united', 'states', '113th', 'references', 'us', 'also', 'see', '9', 'links'], ['united', 'states', 'hundred', 'america', 'thousand', 'year', 'whereof']]
TOP TOKENS [['invisible', 'pretty'], ['invisible', 'visible', '»', 'contain'], ['invisibles', 'invisibles”', 'showing', 'invisible', 'enable', '“show', 'like', 'show', 'displaying', 'changing', 'home/$user/.vimrc'], ['www.invisiblechildren.com', '“invisible,”', 'invisible', '“invisible', 'angles.invisible', 'bullet.invisible', '“invisible.”where', 'documentary', 'unseen', 'organization', '“invisibility'], ['invisible', 'invisibility', 'order', '–', 'ignored'], ['invisible', '“invisible', 'www.invisiblechildren.com', '“invisible,”', '“invisible.”', 'children', 'documentary', 'unseen', '“invisibility', 'organization', 'calcite', 'invisibility', 'seeing'], ['invisibleness', 'invisibility', 'invisible'], ['invisible'], ['invisible', 'visible', 'disability', 'umbrella', 'always', 'obvious', 'outwardly', 'make', 'types', 'however', 'without'], ['invisible', 'completely', 'turn', 'one', 'creating', 'create', 'multiple', '’', 'towards'], ['invisible'], ['invisible', 'invisibles'], ['invisible', 'hügel-marshall', 'emmy-winning'], ['invisible', 'ten'], ['invisible'], ['invisible', 'spectacular', 'le'], ['invisible', 'david', 'original', 'american', '1901'], ['invisible', 'reveal'], ['invisible', 'links', 'band', '3:26'], ['invisible', '–', 'd.f.w', '2:26', 'guitar']]
TOP TOKENS [['following', 'either', 'would'], ['would', 'note', 'return', '172', 'said', 'id', '177'], ['current', 'granted', 'asked'], ['infernal', 'may', 'limits', 'offend', 'could', 'people', 'columns', 'masters', 'power', 'havoc', 'unleash', 'transgenders', 'savvy', 'wreak', 'provincials', 'based', 'normalcy', 'simply', 'office', 'suburbs'], ['individual', 'fire', 'acting', 'try', 'remained', 'electrodes', 'managed', "that's", 'much', 'enable'], ['edge', 'slip', 'pepper', 'hints', 'along', 'vague', 'news', 'steadfast', 'use', 'furrows', 'play', 'reversals', 'pushes', 'return', 'reassignments', 'back', 'rear', 'lined', 'divining'], ['2000', 'works', 'unless', '01:44:59', 'work', 'sensitive', '28', 'dna'], ['used', 'example', 'experiment'], [], ['eliciting', 'included'], ['response', 'participants', 'one', 'opposed', 'reporting', 'findings', 'able', 'also'], ['pressed'], ['assembly'], ['party', 'political', "d'etat", 'politicians', 'belonging', 'time', 'yet'], ['return'], ['personal', 'yards', 'decision', 'hoped', 'ever', 'former', 'successes', 'fresh', 'none', 'win', 'accounted', 'snapping', 'however', 'day', 'disappoint', 'entire', '1', 'combined', 'except', 'time'], ['vary', 'used', 'primarily', 'within'], ['tested', 'works', 'configurable', 'confirmed'], [], ['expected', 'payload', 'effects', 'largefile', 'paragraph', 'section', '168', '80', '17', '2', 'look', 'also', '192', '1']]
TOP TOKENS [['entities', 'iii', 'us', 'iv', 'offers', 'actuality', '’', 'apple', 'possible'], [], [], [], [], ['strengthens'], [], ['dishonour', 'till', 'allurements'], ['dishonour', 'till', 'allurements'], ['stretching'], [], [], ['hitmen'], [], [], [], [], [], [], []]
TOP TOKENS [['burger', 'burgers', 'hamburger', 'americans', 'patties'], ['burgers', 'burger', 'hamburger', 'hamburgers', 'classic', 'sandwich'], ['burger', 'one', 'wash', 'medium', 'veggie', 'onion', 'putting', 'inside'], ['burger', 'burgers', 'diameter', 'bacon', 'mushrooms', 'soon', 'heat', 'inside', 'mayo', 'want', 'day', 'microscope', 'pounds'], ['burgers', 'burger', 'hamburgers', 'hamburger', 'etc', 'ons', 'cls', 'reason', 'foods', 'diet'], ['burger', 'burgers', 'hamburger'], ['burger', 'burgers', 'onions', 'cream', 'whole', 'source', 'limits', 'top', 'power', 'make', 'greens'], ['burger', 'burgers', 'hamburger', 'answer', 'patties', 'pepper', 'eaten', 'possible'], ['burger', 'burgers', 'hamburger', 'hamburgers', 'patties', 'patty', 'cook', '”', 'meals'], ['burgers', 'burger', 'dedicated', 'patty', 'day', 'hamburger', 'diet', 'bun', 'expend', 'quality', 'milligrams'], ['burger', 'album', 'burgers', 'meat', 'bürger', 'hamburger', 'cheese(s', '1973', 'station', 'roll', 'grape', 'vegetables', 'hamburgers', 'disambiguation'], ['burger', '2021', '17', 'madrigal', '2023', 'charlotte', 'notched', 'activated', 'hitter', 'moncada', 'injured', 'july', 'began'], ['burger', 'years', 'rugby', 'international', 'expatriate', 'births'], ['burger', 'j'], ['burger', 'cls', 'philosopher', 'rudolf'], ['burger', "burger's", 'circulation', 'wife', 'so-called', 'triangle', 'november'], ['burger', 'hamburger', 'hamburgers', 'simply', 'term'], ['burger', '1967', 'w', 'dutch'], ['burger', 'born'], ['burger', "burger's", 'burgers', 'hamburgers', 'melts', 'juicy', 'meat', 'core', 'added', 'quashed']]
TOP TOKENS [['augmented', 'reality', 'year'], ['augmented', 'reality', 'siemens', 'top'], ['augmented', 'reality', 'us', 'help'], ['augmented', 'reality', 'using'], ['augmented', 'reality'], ['augmented', 'reality', 'using'], ['augmented', 'reality.cause', 'reality', 'reality.below', 'using', 'reality.zynga'], ['augmented', 'reality'], ['augmented', 'reality', 'using', 'new', 'many'], ['augmented', 'reality.may', 'reality', 'concept', 'all.in'], ['augmented', 'reality', 'space', 'enhances', 'use'], ['augmented', 'reality', 'space', 'techniques', 'way', 'cls', 'immersive', 'actually'], ['augmented', 'reality', 'content', 'global', '2017'], ['augmented', 'reality', 'visualize', 'devices', 'learning', 'method', 'classroom', 'smart', 'takes'], ['augmented', 'reality', 'cls', 'upon', 'additional', 'learning', 'incorporate', 'personal', 'current', 'content', 'smartphones'], ['augmented', 'reality', 'reality-based', 'using', 'also', 'higher', 'previous', 'disassembling', 'combines', 'complex', 'see'], ['augmented', 'reality', 'advanced', 'technologies', 'ar', 'application', 'mizell', 'several'], ['augmented', 'reality', 'web', 'based', 'allows', 'special'], ['augmented', 'augmentedreality.org', 'reality', 'advancing'], ['augmented', 'reality', 'augmenting', 'january', 'experience', 'generated', "device's", 'atop', 'enable', 'per', 'feature']]
TOP TOKENS [['grammar', 'around', 'syntax', 'us'], ['grammar', 'school', 'english', 'grammatical'], ['grammar', 'grammarian', 'cls', 'daily', 'words', 'serves'], ['grammar', 'you’re', 'it’s', 'learning', 'practising'], ['grammar', 'hear', 'english', 'cls'], ['grammar', 'grammarman'], ['grammar', 'grammarman'], ['grammar'], ['grammar', 'teach', 'students', 'proper'], ['grammar', 'hear', 'cls'], ['grammar', 'language'], ['grammar', 'grammars', 'cls', 'english', 'enormously'], ['grammar', 'also', 'grammarians', 'grammarian'], ['grammar'], ['grammar', 'college', 'syntax', 'noordhoff', 'pt', 'hendrik', 'jespersen', 'p', 'vols', 'archives', 'english', '26766'], ['grammarians', 'grammar', 'grammars', 'grammarian', 'syntax'], ['grammar', 'grammars', 'grammatical', 'pedagogical', 'ed'], ['grammar', 'grammaticales', '627', '597', 'late', 'century', 'schools'], ['grammar', 'grammarians', 'grammarian', 'defined', 'biblical', 'success', 'noted'], ['grammars', 'grammar', 'grammatical', 'english', 'grammatices']]
TOP TOKENS [['lung', 'lungs', 'survive', 'transplant', 'condition', 'donor', 'life'], ['lung', 'lungs', 'person', 'later'], ['lung', 'disease', 'help', 'body', 'lungs', 'damaged'], ['lung', 'lungs', 'unsuccessful', 'disease'], ['lung', 'lungs', 'disease', 'failure'], ['lung', 'lungs', 'diseases', 'formed', 'rejected', '65', 'conditions'], ['lung', 'pathologist', 'deal'], ['lung', 'lungs', 'type', 'unsuccessful'], ['lung', 'lungs', 'transplant'], ['lung', 'lungs', 'unsuccessful', 'type', 'hours', 'dead', 'transplant'], ['1952', '1916–1975', 'lungs', 'surname', 'lung', '1974', 'play', '1934–2014', 'jr', 'medicine', 'ep', 'album', '1987', '1966', '龍'], ['lung', 'disease', 'lungs', 'improvement', 'lobe', 'necessary', '1963', 'sarcoidosis'], ['lung'], ['lung', 'transplants', 'developed', 'obsolete', 'drainage', '1909', 'tissue', 'hypertension', '1933', 'pulmonary', 'however'], ['lung', 'heart-lung', 'lungs', "patient's", 'developed'], ['lung', 'surgery'], ['lung', 'women', 'sep', 'references'], ['lung', 'lungs', 'pulmonary'], ["lung's", 'lung', 'fc', 'expatriate', 'years', 'people', 'players', 'sportspeople', "men's", 'footballers', 'silviu', 'politehnica', 'born'], ['lung', 'lungs', 'e', 'multiple', 'g', 'rheumatoid']]
TOP TOKENS [['andalusia', 'andalusian', 'seville'], ['andalusia', 'andalusian', 'cadiz', 'granada', 'sevilla'], ['andalusia', 'andalusian', 'andalucía', 'seville'], ['andalusia', 'granada', 'andalus', 'andalucia', 'castile'], ['andalusia', 'andalusian', 'seville', 'sevilla', 'granada', 'castile', 'malaga', 'castilian', 'around', 'cadiz'], ['seville', 'andalusian', "andalusian's"], ['andalusia', 'seville', 'almoravids', 'las', 'reconquered', 'almoravides', 'century'], ['andalusian', 'andalusia', "andalusia's", 'castilianization', 'seville', 'andalusiya', 'andalus', 'andalucia', 'entirely'], ['andalusia', 'seville', 'guadalquivir', 'e', 'abrabanel', 'c', 'cordoba'], ['andalusia', 'andalusian', 'sevilla', 'granada', 'cordoba', 'malaga'], ['andalusia', 'andalusian'], ['andalusia', 'andalusian', 'seville', 'granada', 'andalus'], ['andalusia', 'andalusian', 'seville', 'castilians', 'andalus', 'cadiz', 'la', 'granada', 'castilla', 'castile'], ['andalusia', 'andalucia', 'andalus', 'southern'], ['andalusia', 'andalusian', 'seville', 'andalusians', 'andalucia', 'la', 'de', 'granada'], ['andalusia', 'seville', 'granada', 'andalucía', 'castile'], ['andalusia', 'andalusian', 'seville', 'granada'], ['andalusia', "andalusia's", 'andalusian', 'cadiz', 'cordoba', 'granada', 'guadalquivir', 'b', 'huelva'], ['andalusia', 'andalusian', 'granada', 'seville', 'andalus', 'castile', 'especially'], ['andalusian', 'andalusia', 'seville', 'andalucia']]
TOP TOKENS [['helps', 'help', 'alleviate', 'promotes', 'helping', 'lower', 'helpful', 'beneficial', 'reduce', 'act', 'acts'], ['aiding', 'helps', 'improve'], ['help', 'reduces', 'helps', 'reduce', 'support', 'keep', 'reducing', 'give', 'promote', 'related', 'body', '10', 'provide', 'improving', 'supporting', '9', 'maintain', 'prevent'], ['helps', 'help', 'reduces', 'lower', 'lowers', 'body', 'makes', 'reduce', 'keep', 'lowering', 'skin', 'especially', 'support', 'get'], ['lowers', 'helps', 'helpful', 'role', 'beneficial', 'increases', 'promotes', 'body', 'plays', 'amount'], ['helps', 'helpful', 'supports', 'helping', 'various', 'improve', 'help', 'preventing', 'gives', 'system', 'minimizing', 'important', 'body', 'turn'], ['helps', 'helpful', 'supports', 'helping', 'various', 'improve', 'help', 'preventing', 'gives', 'system', 'minimizing', 'important', 'body', 'turn'], ['maintaining', 'prevents', 'role', 'makes', 'preventing', 'repairs', 'slows', 'keeps', 'help', 'get', 'provide', 'making', 'provides', 'furthermore', 'problems', 'health', 'helps', 'keeping', 'vital', 'keep', 'plays', 'good', 'pivotal', 'gives', 'body', 'firmer', '8', 'way', 'easy', 'gets', 'frequently', 'slowing'], ['helps', 'reduces', 'collagen', 'body', 'aid', 'help', 'aids', 'benefits', 'addition'], ['help', 'makes', 'improves', 'reduces', 'important', 'also', 'provide'], ['ameliorated', 'ameliorates', 'improved', 'decreased', 'attenuates', 'increased', 'oxidative', 'development', 'improves', 'non', 'enhances', 'acid', 'accumulated', 'skeletal', 'function', 'impairments', 'mediated', 'streptozotocin', 'disorders', 'reduced', 'pancreatic', 'well', 'involved', 'deficits'], ['total', '9', 'left'], ['help', 'improved', 'prevented', 'effects', 'impacts', 'used', 'increasing', 'oxidative', 'combating', 'increased', 'capabilities', 'amount', 'promising', 'impact', 'cells', 'inhibited', 'occurrence', 'increases'], ['contribute', 'neurodegenerative', 'role', 'myodegenerative', 'significant', 'forms', 'ventricular', 'dystrophies', 'maintains', 'involved', 'diseases', "alzheimer's", 'also', 'myc', 'plays'], ['help', 'aid', "body's", 'reduces', 'function', 'muscles', 'body', 'sugars', 'grains', 'act', 'growth'], ['α', 'contribute', 'role', 'rb', 'myodegenerative', 'neurodegenerative', 'significant', 'forms', 'creutzfeldt', 'ventricular', 'involved', 'dystrophies', 'also', 'myc', "alzheimer's", 'raf', 'diseases', 'plays', 'disease', 'amyotrophic', 'malignancies', 'additionally', 'myb', 'mos'], ['contribute', 'rb', 'role', 'α', 'forms', 'involved', 'myodegenerative', 'significant', 'neurodegenerative', 'also', 'ventricular', 'maintains', 'myc', 'moreover', 'plays', 'raf', 'associated', 'disorders', 'diseases', 'myb'], ['contribute', 'role', 'neurodegenerative', 'myodegenerative', 'significant', 'involved', 'forms', 'also', 'ventricular', 'maintains', 'diseases', "alzheimer's", 'disorders', 'myc', 'moreover', 'raf', 'plays', 'sclerosis', 'injury', 'well', 'dystrophies', 'associated'], ['applied', 'conditions', 'involved', 'role', 'also', 'additionally', 'moreover', 'plays', 'clinical', 'resulted', 'mainly', 'myb', 'subject', 'various', 'mechanistic', 'well', 'attributed', 'myc', 'β', 'src', 'raf'], ['role', 'total', 'important', 'promote', 'maintaining', 'roles', 'key', 'body', 'increases', 'purpose', 'plays', 'prevent', 'bodily', 'dealt', 'part', 'health', 'play', 'also', 'serves', 'via', 'major', 'well', 'like']]
TOP TOKENS [['deformation', 'elasticity', 'strain', 'stresses', 'distortional', '8', 'stress'], ['strain', 'stress', 'experimental', 'mechanical', 'constitutive'], ['deformation', 'mechanisms', 'fundamental', 'constitutive', 'test'], ['strain', 'actual', 'stress', 'stiffness', 'material', 'strains'], ['deformation', 'strain', 'stress', 'deformations', 'deforming', 'nature', 'stressed'], ['deformation', 'elastic', 'elasticity', 'levels', 'modulus', 'strains', 'strain', 'stresses', 'stress', 'σx'], ['deformation', 'strain', 'stress', 'vs', 'strained', 'shearing', 'firmness', 'elastic', 'failure'], ['elasticity', 'elastic', 'strain', 'constitutive', '7', 'strains', 'stress', '5', '3', '2', "airy's", 'behaviour', 'material', 'stresses'], ['deformation', 'hyperelastic', 'anelastic', 'behaviour', 'constitutive', 'stress', 'strain'], ['deformation', 'tensile', 'mechanical', 'elasticity', 'stress-strain'], ['plasticity', 'strain', 'stress', 'vs', 'toughness', 'hardening'], ['deformation', 'deforming', 'stress', 'strain'], ['elasticity', 'displacements', 'stiffness', 'strains', 'stresses', 'strain', 'subsequently', 'consistent', 'using'], ['deformation', 'deforming', 'stress', 'strain', 'elasticity', 'engineering', 'modulus'], ['strain', 'typical', 'stress', 'constitutive', 'deformed', 'corresponding', 'method'], ['deformation', 'deformations', 'deform', 'strains', 'kinds', 'stresses', 'stress', 'elasticity', 'strain'], ['deformation', 'plasticity', 'stress', 'hardening', 'extreme', 'strain', 'mechanics'], ['deformation', 'deforming', 'stress', 'strain', 'elasticity', 'engineering'], ['deformation'], ['deformation', 'elasticity', 'strain', 'theory', 'deforming']]

Processing features:  65%|██████▌   | 64/98 [30:50<16:02, 28.30s/it]

getting sample prompt forgetting sample prompt for 24169
 24168
getting sample prompt for 24170
getting sample prompt for 24171
getting sample prompt for 24172
getting sample prompt for 24173
getting sample prompt for 24174
getting sample prompt for 24175
getting sample prompt for 24176
getting sample prompt for 24177
getting sample prompt for 24178
getting sample prompt for 24179
TOP TOKENS [['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise'], ['healthwise', '2018', 'beginning', '154', 'additionally', 'handbook', 'replicated', 'history', 'became', 'self', 'parts', '23', 'fall'], ['homewise', '2012', 'founder', 'brokers', 'america', 'activities', 'offers', 'foundation', 'also', 'opened'], ['weatherwise'], ['rover', 'streetwise', 'nonprofit', 'group', 'opened', 'enterprises', 'institution', 'life', 'train', 'film', 'knowledge', 'possessing', 'transformers', 'kingdom', '1991', 'characters', 'series', 'name', 'brands', 'later', '1998', 'working', 'media', 'entertainment'], ['february', 'limited', 'went', '2001', 'former', 'company', '16', 'inc', 'march', 'spring', 'gutowitz', 'whatever', 'supported', 'noted', 'reason', 'history', 'september', 'including', 'november'], [], ['sugarwise', "sugarwise's", "officer's"], ['streetwise', 'streetwises', 'perimetric', 'alert'], ['chairman', 'hitwise', '2015', 'awards', "hitwise's", '2007', '1997', 'hitdynamics', 'director', '2002–2006', 'history', '2001', 'see', '2004', 'india', '19', 'states', 'similarweb', 'netcraft', 'alexa', 'share'], ['utilitywise', 'limited', 'division', "aim's", 'one', 'ball', 'thompson', 'later']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], [], ['kev'], [], [], []]
TOP TOKENS [['shinto', 'shindo', 'shin', 'shintoists', 'mythology', 'kanji', 'dao', 'shendao', 'past', '神', 'public', 'two', 'kami', 'essences'], ['shinto', 'shindo', 'shind', 'shin', 'mythology', 'past', 'kami'], ['shinto', 'shin—the', 'page[change'], ['shinto', 'shintoism', 'structure', 'universal'], ['shinto', 'deities', 'religion', 'https://www.ancient.eu/video/1198'], ['shinto', 'shintoism', '”', 'confucianism', 'ancient'], ['shinto', 'shintoism', 'college'], ['shinto', 'shintoism', 'word'], ['shinto', 'shinbutsu', 'shintoists', 'bathing', 'practitioners', '神', 'enshrined', 'adherents'], ['shintoists', 'shintō', 'shinto', 'shintoism', 'phrase', 'sins', 'kami'], ['shinto', 'shintō', 'religion'], ['shina', 'shin', 'disambiguation', 'language', 'nigerian'], ["shin'ai", 'shinai', 'anjar', 'sword'], ['shinkai'], ['shino', 'hack//roots', 'aburame'], [], ['shinka', 'shinca'], ['shinki'], ['shina', 'shing'], ['shinca', 'shinka-ron', 'shinka']]
TOP TOKENS [['electrical', 'electricity', 'electromotive'], ['electrical', '«', 'electric', 'conductors', 'electrode', 'electricity', 'conductor', 'electronics', 'electrodes'], ['electrical', 'electric'], ['electric', 'electrostatics', 'current', 'electrical', 'electricity', 'electromotive', 'term', 'electrolyte', 'currents', 'lectrical'], ['electrical', 'electrician', 'electric', 'electricity', 'current', 'ohms', 'conductors', 'wiring', 'conductor'], ['electrical', 'electric', 'voltage', 'electrostatic', 'current', 'voltages', 'circuit'], ['electrical', 'current/voltage', 'currents'], ['electrical', 'electric', '17electric', 'voltage', 'currentelectric', 'current'], ['electrical', 'electric', 'electricity', 'electrostatic', 'capacitance', 'dielectric', 'current', 'potentiometer', 'conductors', 'resistors'], ['electric', 'conductor', 'conducting', 'battery', 'electrons', 'voltages'], ['electrical', 'electric', 'voltage', 'electricity', 'current', 'electrometer'], ['electricity', 'electrical', 'electro', 'electrorh', 'electrochemical', 'impedance', 'electromechanical', 'conductance', 'electrocardiography', 'electromagnetism', 'electric', 'electrocaloric', 'electrogravitic', 'electrochromism', 'electrogravitics', 'electrodeionization', 'electroosmotic', 'electrodynamic', 'electrohydrodynamic'], ['electrical', 'electric', 'current', 'voltage', 'battery', 'conductors', 'transformer'], ['electrical', 'voltage', 'electro', 'electrohydrodynamics', 'conductor', 'electrification', 'electrostatic', 'dielectric', 'electric', 'electricity', 'current', 'phenomena', 'electrically'], ['electrical', 'electric', 'electricity', 'words', 'dielectrics', 'electrochemistry', 'electro', 'electrode', 'electronics', 'engineering', 'science', 'magnetism', 'voltaic', 'resistivity', 'bakewell', 'physics', '42', 'bioelectronics', 'physical'], ['electrical', 'amperes', 'volts'], ['electrical', 'electric', 'electricity'], ['electrical', 'electrochemical', 'electrolysis', 'electricity'], ['electrogenesis', 'electrography', 'electrophysiological', 'electrophysiology', 'electricity'], ['electrical', 'voltage', 'electrodes', 'current', 'electrode', 'seismo-electromagnetics', 'conductivity', 'telluric', 'also']]
TOP TOKENS [[], [], ['ineffective', 'thr1', '80', 'found', 'however', '10μm', '5μm', 'attributed', 'occurring', 'bortezomib', '44'], ['2', 'occur'], ['enough', 'large'], [], ['sentence', 'objects', 'well', 'generally', 'space', 'bit', 'side'], ['either', 'gene', 'zs97'], ['groups', 'decrease', '4', 'pdms', 'decreased', 'odors', 'levels', 'consequently'], [], ['possible', '2018', 'kelantanese'], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['develop', 'confident', 'personal', 'supports', 'build', 'achieve', 'qualities', 'promotes', 'excellence'], ['contribute', 'confident', 'success', 'confidence', 'respect', 'meaningfully', 'recognize', 'creativity', 'talents', 'development', 'ability', 'encourage', 'building', 'promote', 'approaches', 'inspirational', 'establishing', 'understand', 'growth', 'realizing', 'cultivate', 'fulfillment', 'involved', 'contributions', 'develop', 'approach', 'relevant', 'well'], ['contributing', 'developing', 'inspire', 'engage', 'respect', 'positively', 'connect', 'contribute', 'create', 'evolve', 'lives', 'progress', 'individuals', 'develop', 'empathy', 'excel', 'responsible'], ['contributing', 'developing', 'inspire', 'engage', 'respect', 'positively', 'connect', 'contribute', 'create', 'evolve', 'lives', 'progress', 'individuals', 'develop', 'empathy', 'excel', 'responsible'], ['successful', 'relevant', 'achieve', 'inspire', 'success', 'excellence', 'respect', 'strong', 'overcome', 'reach', 'promotes', 'ongoing', 'become', 'engage', 'fulfilling', 'support', 'helping', 'reflective', 'life-long', 'purpose', 'meaningful', 'respectful', 'promote', 'pride', 'goals', 'individuality', 'personal', 'conduct'], ['successful', 'relevant', 'achieve', 'inspire', 'success', 'excellence', 'respect', 'strong', 'overcome', 'reach', 'promotes', 'ongoing', 'become', 'engage', 'fulfilling', 'support', 'helping', 'reflective', 'life-long', 'purpose', 'meaningful', 'respectful', 'promote', 'pride', 'goals', 'individuality', 'personal', 'conduct'], ['successful', 'relevant', 'achieve', 'inspire', 'success', 'excellence', 'respect', 'strong', 'overcome', 'reach', 'promotes', 'ongoing', 'become', 'engage', 'fulfilling', 'support', 'helping', 'reflective', 'life-long', 'purpose', 'meaningful', 'respectful', 'promote', 'pride', 'goals', 'individuality', 'personal', 'conduct'], ['develop', 'creatively', 'effectively', 'appreciate', 'clarify', 'involvement', 'uphold', 'justify', 'ideas', 'stewardship', 'personal', 'relate', 'relevant', 'perspectives', 'sense', 'solve', 'processes', 'employ', 'situation', 'adopt', 'perspective', 'culture', 'keep', 'understand', 'effective', 'awareness', 'valid', 'accurately', 'support', 'present', 'value', 'practice', 'efficiently', 'convey', 'social'], ['succeed', 'classroom||meaningful', 'aptitudes', 'improve', 'skills||strong', 'clearly', 'productive', 'become', 'strengths', 'develop', 'solve', 'experiences||effective', 'confidence', 'responsible', 'social', 'cooperative', 'involvement', 'retention', 'helping', 'work', 'increasing', 'knowledge', 'life', 'quality', 'development', 'whole', 'connections', 'emotional', 'self', 'person', 'make'], ['improves', 'excellence', 'respect', 'teaching', 'responsiveness'], ['enhance', 'responsible', 'consistently', 'links', 'develop', 'supportive', 'building', 'positive', 'encourage', 'relationship', 'esteem', 'self', 'assert', 'abilities', 'build', 'promoting', 'achievement', 'promote', 'behaviour', 'developing', 'importance', 'offering', 'moral', 'recognise', 'fostering', 'reliance', 'interaction', 'respecting', 'feelings', 'motivate', 'awareness', 'actions', 'guidance', 'life', 'consequences', 'way', 'outlook'], ['develop', 'roles', 'development', 'skills', 'developing', 'competence', 'experience', 'receive', 'upskill', 'engages', 'delivering', 'engagement', 'active', 'actively', 'professionalise', 'become', 'purpose', 'primary', 'undertaking', 'order'], ['progress', 'encouragement', 'attitude', 'promotes', 'development', 'cultural', 'work', 'contribution', 'achieve', 'social', 'relationships', 'moral', 'develop', 'activities', 'feel', 'excellent', 'foster', 'lifelong', "pupils'achievements", 'achievement', 'successes', 'high', 'guardians', '2017', 'enables', 'supported', 'links', 'expectations', 'curricular', 'individual', 'spiritual', 'well', 'significant', 'support', 'experiences', 'operative', 'help', 'seen', 'offer', 'highest', '67'], ['develop', 'developing', 'better', 'together', 'respect', 'guide', 'self', 'others', 'work', 'guiding', 'concern', 'based', 'socially', 'abilities', 'use', 'values', 'areas', 'live', 'intellectually', 'staff', 'spiritually'], ['develop', 'well', 'progress', 'experiences', 'skills', 'understanding', 'knowledge', 'achieve', 'complete', 'experience', 'gain', 'work', 'encouraged'], ['linking', 'securing', 'virtuous', 'toward', 'connecting', 'contributes', 'great', 'enhance', 'figure', 'function', 'alongside', 'successfully', 'collective', 'fellow', 'engaging', 'beings', 'manner', 'views'], ['impact', 'well', "school's"], ['successful', 'realizing', "actions.'global", 'responsibly', 'act', 'identity', 'develop', 'acting', 'effectively', 'respectful', 'attitudes', 'necessary', 'qualities', 'conducting', 'solidarity', 'motivation', 'autonomously', 'respect', 'belonging', 'development', 'experience', 'sense', 'life', 'humanity', "one's", 'outcomes', 'take', 'facilitate', 'dispositional', 'understanding', 'defending', 'work', 'competencies', 'competence', 'asserting', "called'psychosocial", 'moral', 'empathy', 'approaches', 'attitudinal', 'interactions', 'values', "consciousness'and'global", 'peers', 'engaged'], ['relevance', 'excellence', 'advancement', 'action', 'encouragement', 'creation', 'success', 'contribute', 'strengthen', 'increase', 'positively', 'empower', 'personal', 'applied', 'rigorously', 'serve', 'values', 'sense', 'individuals', 'processes', 'wellbeing', 'sustain', 'create', 'ensure', 'efforts', 'understanding', 'good', 'central', 'endeavor', 'reach', 'learning', 'culture', 'build', 'raise', 'preparing', 'recognition', 'social', 'service', 'respond', 'manner', 'foster', 'mutual', 'application', 'partnerships', 'strive', 'responsibility', 'actively', 'isolation', 'teaching', 'timely'], ['relate', 'positive', 'well', 'represents', 'perseverance', 'leads', 'qualities', 'attitude', 'leadership', 'develop', 'integrity', 'interest', 'influence', 'extending', 'upholding', 'support', 'unity', 'honesty', 'organise', 'demonstrate', 'potential', 'high', 'community', 'able', 'important', 'strengthening', 'ways', 'bonding', 'integrated', 'bring', 'courtesy', 'character', 'demonstrating', 'gce', 'motto', 'entire', 'towards', 'conduct', 'end', 'exemplary', 'functions', 'looks', "one's", 'complete']]
TOP TOKENS [['sd', 'microsd', 'card', 'cards'], ['sd', 'card', 'sdcardrecovery', 'cards'], ['sd', 'card'], ['sd', 'card', 'microsd', 'sdfatlib', 'sdhc', 'cards'], ['sd', 'microsd', 'sdcard', 'minisd', 'card', 'cards', 'sdcards'], ['sd', 'microsd', 'card', 'cards'], ['sd', 'card'], ['sd', 'card', 'cards'], ['sd', 'card', 'cards'], ['sd', 'microsd', 'card', 'cards'], ['sd', 'card', 'cards', 'microsds', 'prerecorded', 'sandisk', 'sio2sd'], ['sd', 'card', 'cards', 'sdc', 'malfunctioning'], ['sd', 'microsd', 'card', "card's", 'sda', 'cards', 'sdhc', 'sdxc'], ['microsd', 'sd', 'card', 'sdsc', 'cards', 'sdr104', 'sdhc', 'sdxc'], ['sd', 'cards', 'microsd', 'card', 'minisd', 'smartsd', 'sdhc', 'memory', 'sdxc', 'v4', 'applications', 'sdio'], ['sd', 'card', 'cards', "card's"], ['sd', 'cards', 'minisd', 'card', 'sdio', 'sda', 'sandisk', 'memory', 'samsung'], ['sd', 'sd8', 'microsd', 'card', 'sdhc', 'cards', 'sdxc', 'sda', 'sduc'], ['sd', 'cards', 'minisd→sd→cf', 'minisd→cf'], ['sd', 'microsd', 'card']]
TOP TOKENS [['worsted', 'spun', 'spinning', 'yarns', 'would'], ['worsted', 'spinning', "yarn.'worsted'as", "knit.'worsted'as", "term'worsted'has", 'direction', 'smoothed', 'knitters', 'spinner', 'wheel', 'well'], ['worsted', '“', 'worstead', '”'], ['worsted', 'precisely', 'style', 'form', 'cls', 'spinning', 'drawn', 'preparation', 'combing', 'yarns', 'never'], ['“', 'worsted', 'worstead', '”', 'cls', 'variety', 'time'], ['worsted', 'dense', '“', 'fibers', 'yarn', 'term', 'know', 'wool', 'various'], ['worsted', 'fabric', 'insulation', 'brief', 'characterise', 'magnification', 'bits', 'thing', 'open', 'described'], ['worstead', 'norfolk', 'worsted', 'worsteds', 'rich', 'yarns', 'worstedˈwʊs', 'well-twisted', 'wool', 'worstede', 'fulled', 'carpets', 'suit'], ['worstead', 'norfolk', 'worsted', 'worsteds', 'rich', 'yarns', 'worstedˈwʊs', 'well-twisted', 'wool', 'worstede', 'fulled', 'carpets', 'suit'], ['worsted', 'worsted-spun', 'content', 'woolen', 'thoroughly', 'spun', 'neat', 'next', 'durability', 'several', 'disclaimer', 'welcome'], ['worsted', 'worsteds'], [], ['worsted', 'spin', 'spinning', 'create', 'slivers', 'yarns', 'yarn'], ['worstead', 'england', 'peak'], ['association', 'divorce', 'lone', 'worster', 'later', 'football', 'cats', "bachelor's", 'decided', 'life', 'also', 'austin', 'wife', 'died', 'rawlins', 'antonio', 'completed', 'spending', 'draft', 'one', 'year', 'three', 'could', 'ann'], ['worsted', 'woolen', 'term', 'yarns', 'categories', '5', '5mm', 'fibres', 'spinning', 'council'], ['described', 'rkd', 'worst', 'drawing', 'known', 'popular', 'today', 'good', 'ca.1635', 'time', 'spent', 'according', 'ca.1686'], ['worsted', 'worsteads', 'princess', 'along', 'worstead', 'served', 'edward', '1086', 'railway', 'north', 'within', "andrew's", 'station', 'derives', 'ground', 'wroxham', 'ordested', '91', 'bure', 'cloth', 'falls', "benet's", 'covered', 'broads', 'norfolk'], ['worst', '1958', 'worster-drought', 'worster'], ['worston', 'boundary', 'downham', 'told', 'said', 'coming', 'place', 'green', 'monday', 'met', 'bypassed', 'cls', "calf's", 'road', 'near']]
TOP TOKENS [['grace', 'group’s'], [], ['grace', 'career', 'lifetime', 'time', '1973', 'blame', 'admiral', '1969', 'without', 'doors', 'hopper', 'additionally', 'led'], ['•', 'grace', '1949'], ['grace', 'one', 'next', 'became', 'early', 'years', 'later', 'went', 'eventually', 'several'], ['grace', 'well'], ['m.a', 'corp', 'common-business-oriented'], ['grace', 'career', 'matic', 'murray'], ['grace', '–'], ['grace', 'career', "back'em", "hopper's", 'war', 'thing', 'although', 'hopper'], ['grace', 'even', 'hopper', 'part', 'bartik', 'coining', "hopper's", 'time', 'though', 'e', '1949'], ['grace', 'hand', 'hopper', '1949', 'one', 'also', 'desegregates', 'worsley', '–', 'u', 'becoming', 'weizac'], ['grace', 'hopper'], ['1958', "minsky's", 'mid', 'instead', 'long', 'work', 'university', 'proceedings', 'however', "lorenz's", 'include', 'one', 'time', 'pursue', '1961'], ['grace', 'forefront', 'carol', 'hopper', '1994', 'scientist', 'celebration', 'includes'], ['grace', 'digits', 'bloch', 'hopper', 'step', "raytheon's", 'tape', 'subroutines', 'toward', 'one', 'done', "bloch's"], ['code', 'including', 'became', 'people', 'hopper', 'one', 'israel', 'involved', 'several', 'college', 'cards', 'weizac', 'machines', 'programmer'], ['one', 'also', 'according', 'made', 'inventing', 'became', 'notable', 'contributions', 'later', 'several', 'included', 'gov', 'ivorydale', 'edu'], ['grace', 'scientist', 'hopper', 'computer', '23', 'including', 'later', 'permanent', '15', 'willoughby', 'science', 'mates', 'intelligence', 'october', 'large', 'corps', 'king', 'doris', 'devaney', 'stateside', '1942', '7', 'better', 'largely', 'november', "pharmacist's", 'july', 'demobilized', 'ellen', 'ready', 'rae', 'technology', 'mechanics'], ['grace', 'hopper', "hopper's", 'much', 'important', 'specifically', 'note', 'harper', 'ridgway', 'even', '1950s', 'november', 'worked', "harper's", 'primarily']]
TOP TOKENS [['cinematographer', 'cinematographers', 'cinematography', 'camera'], ['cinematographer', 'cinematographers', 'cinematography', 'photography', 'camera'], ['cinematographer', 'cinematographers', 'cinematography', 'cls', 'movies', 'shots', 'small', 'projects', 'photographers', 'sometimes', 'technology', 'according'], ['cinematographers', 'cinematographer', 'cinematography', 'films', 'cls', 'short', 'often', 'weather', 'opportunities', 'day', 'field'], ['cinematographers', 'cinematographer', 'cinematography', 'camera', 'networking', 'production', 'industry'], ['cinematographer', 'shot', 'cinematography'], ['cinematographers', 'cinematographer', 'cinematography', 'networking', "afi's", 'production', 'design', 'screenwriting', 'years', 'seminars', 'career', 'industry'], ['cinematographers', 'cinematographer', 'films', 'cinematography', 'field', 'qualification', 'eyesight', 'director', 'stock', 'film', 'education', 'filter'], ['cinematographers', 'cinematographer', 'cinematography', 'see', 'videos', 'film'], ['cinematographer', 'even', 'interchangeable', 'uniformly', 'complete', 'cinematography', 'insist', 'image'], ['cinematographers', 'cinematography', 'dick', 'dean', 'dante', 'seale', 'papamichael'], ['cinematographers', 'cinematographer', 'cinematography', 'see', '1932', 'filmmakers', 'please'], ['cinematographers', 'cinematographer', "cinematographer's", 'cinematography', 'cls', 'instances', 'piece'], ['cinematographers', 'cinematography', 'william', 'wages', '2020s', 'mankofsky', 'johnson'], ['cinematographer', 'cinematographers', 'saaraa', 'alagappan', 'v', 'krishna', 'k', 'arbhindu', 'nirav', 'c', 'indian', 'arvind', 'jayaraman', 'nihalani', 'rana', 'jaya', 'hari', 'p', 'govind', 'n', 'nair'], ['cinematographer', "cinematographer's", 'cinematographers', 'cinematography', 'result', 'knowledge'], ['cinematographer', 'cinematography', 'subramaniapuram', 'c', 'arivu', 'best', 'thaakka', 'thamizh', 'v', 'awards', 'paramahamsa', 'raavanan', 'deiva', 'angadi'], ['cinematographer', 'cinematography'], ['cinematographer', 'legend', '1992', '1977', '1979', '1974'], ['cinematographers', 'cinematography', 'leading']]

Processing features:  66%|██████▋   | 65/98 [31:18<15:32, 28.25s/it]

getting sample prompt for 24180
getting sample prompt for 24181
getting sample prompt for 24182
getting sample prompt for 24183
getting sample prompt for 24184
getting sample prompt for 24185
getting sample prompt for 24186
getting sample prompt for 24187
getting sample prompt for 24188
getting sample prompt for 24189
getting sample prompt for 24190
getting sample prompt for 24191
TOP TOKENS [['turn', 'years', 'anything', 'eventually', 'surely', 'hit'], ['turn', 'years', 'anything', 'eventually', 'surely', 'hit'], ['flew', 'thrown', 'around', 'stuck', 'moving'], ['floating', 'launching', 'spotted', 'showing'], ['traveling', 'actually', '“'], ['hit'], ['hit'], ['object'], ['send', 'heading', 'way', 'thing', 'something', 'making', 'earth', 'occasional'], ['fall', 'send', 'earth'], [], ['objects', 'neptunian', 'object', 'sized'], ['aimed', 'launched', 'antenna'], [], ['objects', 'launched', 'become'], ['trans-neptunian'], ['entered', 'falling', "earth's", 'launched', 'reentered'], ['objects', 'launched', 'list', 'earth', 'artificial', 'rockets', 'inert', 'tesla', 'micrometeoroid', '–', "lander's", 'eventually'], ['launched'], ['objects', 'durchmusterung']]
TOP TOKENS [['pecha', 'kuchas', 'kucha', 'cha'], ['pecha', 'narrative.pechakucha', 'kucha', 'pechakucha'], ['zechariah', 'ze-cha-ri-ah', 'less'], ["zechariah's", 'zechariah'], ['pecha', 'kucha', 'salespeople', 'loud', 'good', 'talkers'], ['panchakarma', 'pancha', 'panchamukha', 'tejas', 'vayu', 'aversion', 'vamana', 'elements/energies'], ['pecha', 'kucha', "can't"], ['zechariah', 'particular', 'jehoiada', 'name', '“', 'barachias', 'barachiah', '3', 'one'], ['zechariah', "zechariah's", 'jarchi', 'eschatological', 'ezr', '3', "writer's", 'haggai', 'began'], ['zechariah', 'others', 'mary', 'prophet', '1', '’', 'mostly', '‘', 'luke', 'yahya'], ['panchah', 'panchāh', "buq'eh", 'romanized', 'zaynolabideen', 'astaneh-ye', 'b'], ['concha', 'vicente', 'auricle', 'breathing', 'footballer'], ['kacha', 'kāchā', 'kácha', 'kacha-ye', 'sevastopol', 'naval'], ['tichá', 'ticha', 'penicheiro'], ['kuchar', 'kuchař'], ['kechakh', 'kachā', 'kacha', 'kāchā'], ['nacha', 'atlach-nacha'], ['kuchary'], ['india', 'pancha'], ['paschāt', 'paschat', 'romanized']]
TOP TOKENS [['pediatricians', 'pediatrician', 'pediatrics', 'pediatric', 'jobs', 'cls'], ['pediatricians', 'pediatrician', 'pediatrics', "pediatrician's", 'pediatric', 'one', 'diseases'], ['pediatricians', 'pediatrician', 'pediatrics', "pediatrician's", 'pediatric', 'one', 'diseases'], ['pediatrician', 'pediatricians', 'pediatrics'], ['pediatricians', 'pediatrician', 'diagnosis'], ['pediatricians', 'pediatrician'], ['pediatricians', 'pediatrician', 'pediatrics'], ['pediatricians', 'pediatric', 'pediatrics', 'cls', 'caregivers'], ['pediatrician', 'pediatricians', 'pediatrics', 'pediatric'], ['pediatrician', 'pediatricians', 'adults'], ['pediatric'], ['pediatrics'], ['pediatric', 'pediatrics'], ['pediatrics'], ['pediatric', 'pediatrics'], ['pediatricians', 'pediatrics', 'pediatric', 'qualified', 'patient'], ['pediatrics', 'pediatric', 'american'], ['pediatrics', 'pediatricians', 'pediatric'], ['pediatrics', 'scott'], ['pediatric', 'pediatricians', 'pediatrics']]
TOP TOKENS [['level', 'participation'], ['usa', 'strategic', 'looks', 'strategy', 'engage', 'democrats', 'said', 'way', 'organization', 'like', 'people', 'anymore', 'democratic'], ['takeatest', 'representatives'], ['mankind', 'world', '“', 'people', 'said', '30s'], ['things'], ['used'], ['world', 'todayâ€™s', 'yearâ€™s', 'proactive', 'country', 'people', 'states', 'communities'], [], ['devices', 'document', '3'], ['20mdia', 'participation', 'ac', 'global'], ['organization', 'citizenship', 'local', 'national', 'nations', 'well', 'members', 'reported', 'often'], ['website', 'american'], ['municipal', 'presbyterian', 'faith', 'members', 'christian', 'wholesale', 'catholic'], ['saying', 'text', 'people'], ['standards-http://www.dalynn.com/dyn/ck_assets/files/tech/tm53.pdf', 'particles', 'jama', '1.175', 'suspensions', 'barium', 'specified', 'joseph', 'standards:{2', '0.05', 'xlix(14):1176-1178', 'mcfarland', 'm.d', '1907', 'ml', 'falsely', 'bacl2•2h2o', 'made', 'forms', 'amounts', 'h2so4', '2014-12-10', 'together', 'susceptible', 'within', '0.5', 'occur', 'either', 'precipitate'], ['mcfarland', 'two', 'team', 'time', "mcfarland's", 'numerous', 'however'], ['county', 'interactive'], ['organisation', 'democracy', "party's", 'party', 'deputies', 'represent'], ['america'], ['pakistani', 'municipalities', 'presbyterian', 'judaism', 'represent', "city's"]]
TOP TOKENS [['stimulates'], ['act', 'works', 'allowing', 'system', 'better', 'increases', 'fiber', 'body', 'however'], ['lack', 'get', 'toxins', 'vitamins'], ['toxins', 'wastes', 'oxidative', 'metabolites', 'aid', 'antioxidants', 'body', 'boosts', 'result'], ['give', 'toxins', 'gets', 'found', 'cyanide', 'fuel', 'batteries', 'help', 'inhale', 'go', 'ridding', 'obesity', 'according'], ['gets', 'juices', 'toxins', 'beneficial', 'eliminates', 'wastes', 'help', 'brings', 'leafy', 'also', 'like', 'removal'], ['gets', 'juices', 'toxins', 'beneficial', 'eliminates', 'wastes', 'help', 'brings', 'leafy', 'also', 'like', 'removal'], ['toxins', 'body', '1', '4', 'due', '6', 'digestion', 'insufficiency', 'metabolism'], ['get', 'show', 'accumulates', 'sacs'], ['release', 'stimulating', 'lack', 'level', 'body', 'help', 'toxins'], ['reduced', 'glycaemic', 'noradrenergic', 'noradrenaline', 'results', 'order', 'slows', 'effect', 'dopaminergic', 'dopamine', 'associated'], ['body', 'utilise', 'sugars', "body's"], ['pheromone'], ['glycaemic'], [], [], [], ['hypopigmentation', 'deficiency'], ['instead', 'reversing'], ["the'single", 'excreted', 'usually', 'allows']]
TOP TOKENS [['spawn', 'spawning', 'types', 'benefit', 'methods', 'get'], ['spawns', 'spawning', 'spawn', 'others', 'particular', 'point', 'locations'], ['spawn', 'spawning', "spawn's", 'evil', 'spawnadorn', 'ever', "devil's", 'logging', 'away', 'blonde', 'spawned', 'right', 'effect', 'base', "nowlan's"], ['spawn-wind', 'spawn', 'spawner', 'using', 'variations', 'purposes', 'see', 'typical', 'full', 'allows'], ['spawn', 'spawning', 'actually', 'commences', 'place', 'season', 'route', 'intend', 'whose'], ['spawn', 're-spawns', 'spawn-point', 'term'], ['spawning', 'across', 'bed', 'spawn', 'atop', 'typical', 'ability', 'beds', 'example'], ['spawn', 'spawning', 'life'], ['spawn', 'used', 'inoculate', 'cultivation', 'spawning', 'mushroom', 'common', 'thrives', 'type', 'grain'], ['spawn_pty', 'spawn', 'proc::spawn', 'resources', 'spawned', 'returned', 'function'], ['spawning', 'spawn', 'organization', 'networks', 'reproduction', 'color', 'executes'], ['spawn', 'spawns', 'pads', 'spawning', 'spawned', 'create', 'created', 'unused', 'games', 'precise', 'typically', 'leave', 'area', 'camping'], ['spawn', 'feature', 'around', 'well'], ['spawn', 'spawnvpe', 'spawnle', 'spawnlpe', 'spawnv', 'spawnvp', 'spawnl', 'spawnlp', 'spawnve', 'family', 'function', 'followed', 'cls', 'execute'], ['spawn', 'spawning', 'vms', 'spawnp', "vms's", 'spawned', 'history', 'windows', 'mechanism', 'returns', 'posix', 'translation'], ['spawning', 'spawn', 'typical'], ['spawn', 'spawning', 'way', 'occurs', 'called', 'broadcast', 'consists', 'verb'], ['spawn', 'implementations', 'installation', 'discs', 'games', 'installations', 'contrast', 'additionally', 'value'], ['spawn', 'spawning', 'fungiculture', 'biology)#fungi', 'adding', 'inoculation'], ['spawning', 'implementation', 'responsible', 'titled', 'capable', 'networks', 'paper', 'chou', 'hamburg']]
TOP TOKENS [['permutation', 'permutational', 'commutation', 'commutare', 'permutations'], ['permutation', 'permutational'], ['permutations', 'permutation', '9'], ['permutations', 'permutation', 'npermutations'], ['permutations', 'permutationa', '“permutations”', '“permutation', 'permuted', '“permutations'], ['permutation', 'permutations'], ['permutation', 'permutations'], ['permutations', 'permutation', 'take', '“', 'fully'], ['permutation', 'permutations', 'time'], ['commutation', 'commutator', 'commutators'], ['permutation', 'order', 's-boxes'], ['commutation', 'commutator', 'noncommutativity', 'punishment', 'commutative', 'commuting'], ['permutation', 'links', 'helios', 'external'], ['permutation', 'links', 'may', 'external', '11'], ['permutation', 'permuting', 'permute', 'one'], ['permutation', 'permutations', 'theory', 'permuted'], ['permutation', 'line', 'permutations'], ['permutation', 'permutations', 'rules'], ['permutation', 'permutations', 'cls', 'exist'], ['permutation', 'corresponding', 'behind', 'test']]
TOP TOKENS [['drowning', 'aquamari', 'tiktok', 'sober', '2020', 'covid', 'handbooks', 'adore', 'today', 'sales', 'stock', 'list', '‑', 'moyer', 'tarkov', 'absolutely', 'ucinating', 'kali', 'english', 'ghetto', 'tamil', 'network', 'lyrics', 'imaz', 'breeds', 'quest', 'champagne'], ['real', 'pneumonoultramicroscopicsilicovolcanoconiosis', 'supercalifragilisticexpialidocious'], ['02', '23', '30', '18', '17'], [], ['1', 'organization', 'movie', '2', 'b', '3', 'intracellular', 'publications', '”', 'c', '“', 'plaques', 'e', '4'], ['1', '10', "malignant'disorder'and", '1961', '2', 'meter', 'far', 'cancer', 'sqm', 'tissue', 'course', 'elapse', 'nucleus'], ['normally', 'vactruth'], [], ['therefore', 'indeed'], ['erythromelalgia'], ['molar', 'u'], ['although'], ['us', 'november'], ['12', '9', '25', 'flicks', 'children'], ['vol'], ['experience', 'well'], ['however', 'may', 'therefore', 'soluble', 'gelatinous', 'starch'], ['7', 'covid', '31', '2020', 'government'], ['working', '2012', 'entertainment', 'october', 'mostly', 'officially', 'well', '2', 'heavily', 'public', 'franchising', 'may', "game's", 'remains', 'follows'], []]
TOP TOKENS [['getting', 'connections', 'internet', 'time', 'service'], ['getting', 'service', 'connections', 'strides', 'telephones', 'access', 'internet', 'phone', 'made', '18', 'lack', 'telecommunications', 'obtaining', "americans'lack"], ['making', 'connectivity', 'service', 'reach', '000'], ['services', 'connectivity', 'broadband', 'access', 'build', 'success', 'bandwidth', 'internet', '”', 'wireless', 'telecommunications', 'discounts', 'reliable', 'without', 'fiber', 'optic'], ['connections', 'speed', 'internet', 'without', 'connection', 'broadband'], ['declared', 'access', 'services', 'internet', 'connected', 'cls', 'connection', 'talk'], ['accessing', 'although', 'connectivity', 'access', 'unconnected', "world's", 'offline', 'million', 'remains'], ['makes', 'access', 'broadband', 'connections', 'service', 'carrier', 'mbit', 'million', 'connected', '4', 'make', 'services', 'speed'], ['including', 'internet', 'telecommunication', 'canada', 'phone', 'well'], ['connections', 'connectivity', 'broadband', 'connection', 'internet', '63', 'service'], ['public', 'access', 'connect', 'obtain', 'internet', 'expansion', 'connection', 'services', 'economic', 'networks', 'broadband'], ['million', '1', 'subscriptions', 'access', 'connectivity', 'services', 'colombians'], ['access', 'penetration', 'one', 'get', 'internet', 'broadband', 'amount', 'according'], ['access', 'service', 'connections', 'penetration', 'locales', '000', 'country', 'receive', 'internet', "ecuador's", 'via', 'schools', 'services', 'broadband', 'reach'], ['million', 'subscriptions', 'connections', '2009', 'access', 'reach', '1', "colombia's"], ['penetration', 'level', 'access', 'cls'], ['access', 'increase', 'listed', 'internet', 'services', 'scheme', 'sector', 'service', 'serve', 'mbit', 'expansion', 'broadband'], ['offering', 'offers', '534', 'access', 'online', 'moldovan', '298', 'subscribers', '100mbit', 'country'], ['000', 'access', 'internet', 'accessing', 'offering', '630', 'mobile', 'connections'], ['000', '867', '1', 'connections', 'mbit', '524', 'cls']]
TOP TOKENS [['keep', 'always', 'allowing', 'get', 'make', 'help', 'options', 'need'], ['using', 'plugging', 'ways', 'keep', 'use', 'sculpting', 'taxing'], ['get', 'keep', 'way', 'needs', 'make', 'help', 'include', 'inconvenient'], ['add', 'new', 'main', 'making', 'also', 'full', 'looking', 'goal', 'products', 'valuable', 'suggestions', 'balm'], ['keep', 'use', 'make', 'set', 'important', 'add', 'time', 'motivating', 'way', 'needs', 'kind'], ['get', 'needs', 'make', 'way', 'use', 'using', 'helps', 'let', 'replace', 'set', 'help'], ['keep', 'ways', 'track', 'allow', 'help', 'keeping', 'goal'], ['keep', 'stocking', 'track', 'use', 'allow', 'help'], ['using', 'receiving', 'accessories', 'help', 'add', 'saving', 'various'], ['keep', 'track', 'use', 'customize', 'using', 'needs', 'making'], ['stabilizer', 'stabilizers', 'additive', 'added', 'stabiliser', 'prevent', 'stabilisation', 'change', 'destabilisation', 'compensator', 'stability', 'provide', 'gyrostabilizer', 'support', 'adjusts', 'processing', 'food', 'stabilizes', 'distortion', 'unwanted'], ['used', 'role-playing', 'ember.js', 'paso', 'game', 'random', 'band', 'stoker', 'chip', 'el', 'lumen', 'company', 'intercity', 'lalaloopsy', 'non-profit', 'album', "children's"], [], ['trimmer', 'transfusion', 'embellishments', 'cutting', 'trimming', 'remove', 'package', 'trim', 'trimmings', 'adjustment', 'transpo', 'pruning', "vessel's", 'control'], ['sedentary', 'immobilization', 'inactive', 'provide'], ['way', 'options', 'needs', 'comfortable', 'alternative', 'wearing', 'needed', 'like', 'gives', 'put', 'attachment', 'ways', 'wear', 'bands', 'easier', 'take', 'clipped', 'helps', 'attaching', 'taking', 'expectations', 'keep', 'keeps', 'looser', 'including', 'belt', 'access', 'molds', "one's", 'fixation', 'enables', 'better'], ['swedish', 'fantasy', 'service', 'haiti', 'sistema', 'prilepin', 'sin', 'fullmetal', 'servicio', 'oleksandr', 'system', 'galway', 'inteligencia', 'national', 'kiske', 'nacional', 'peru', 'born', 'core', 'intelligence', 'moonspell', 'cars'], ['attachments', 'item', 'parcel', 'derived', 'accessory'], ['accessory', 'accessories', 'kit', 'bundles', 'bundled', 'startup', 'pack', 'funded', 'designed', 'party', 'transmitter', 'improve', 'attached', 'optimised', 'wirelessly', 'deluxe', 'padding', 'alternate', 'eyepieces', 'add', 'includes', 'wigig', 'launched', 'containing', 'comfort'], ['body', 'piece', 'allow', 'comfortable', 'prefer', 'want', 'supinate', 'create', 'lay', 'gain', 'keeping', 'pulleys', 'preference', 'maintain', 'full', 'barbells', 'wider', 'address', 'let', 'stand', 'grasp', 'barbell', 'starting', 'face']]
TOP TOKENS [['amenorrhea', 'e.g', 'cortisone'], ['amenorrhea'], ['amenorrhea'], ['amenorrhea'], ['amenorrhea', '’'], ['amenorrhea', 'amenorrheic', 'nervosa'], ['amenorrhea', 'menstrual', 'nervosa'], ['amenorrhea', 'amenorrhoea', 'amenorrheic', 'http://jap.physiology.org/cgi/content/full/84/1/37'], ['amenorrhea', 'menstrual', 'hormonal', 'cases'], ['amenorrhea'], ['amenorrhoea', 'amenorrhea', 'pathophysiology', '90'], ['amenorrhoea', 'amenorrhea', 'menstrual', 'although', 'age', 'cls'], ['amenorrhea', "amenorrhea's", 'hypothalamic', 'hysteroscopy'], ['amenorrhoea', 'amenorrhea', 'induce', 'experiences', 'cycles', 'primary'], ['amenorrhea', 'amenorrhoea', 'mechanism', 'females'], ['amenorrhea', 'hypogonadism', 'hypothalamic', 'detailed', 'perhaps', 'sexually', 'gonadotropin', 'axis', 'studies', 'reversible', 'disease'], ['amenorrhoea', 'induce', 'cause', 'year', 'progestogen', 'following'], ['amenorrhea', 'density', 'hypothalamic', "hypothalamus's", 'gonadotropic', 'menstruating', 'menstrual', 'primary'], ['amenorrhoea', 'amenorrhea', 'premenopausal', 'infrequently', 'menstrual', 'days', 'hypomenorrhea', 'reproductive', 'light', 'regularity', 'menstruation', 'broad', 'oligomenorrhea', 'physiologic', 'volume'], ['amenorrhea', 'primary', 'sometimes', 'ultrasound', 'hormonal', 'chronic', 'premenstrual', 'chlamydia', 'endometrial', 'include', "cushing's", 'bleeding', 'dysmenorrhea', 'laparoscopy', 'hysteroscopy', 'menstrual', 'magnetic', 'reasons', 'uncontrolled', 'ovary', 'tests']]
TOP TOKENS [['never', 'ever', 'must', 'type', 'g', 'e', 'long'], ['must', 'never', 'ever', 'part', 'neither', 'g', 'type', 'needs'], [], ['never', 'must', 'g', 'ought', 'long', 'flag', 'e', 'item'], ["flag's", 'either'], ["flag's", 'either'], ["flag's", 'either'], ['never', 'ought', 'ever', 'long', 'may', 'kind', 'proper', 'g', 'goes', 'throughout'], ['must', 'g', 'may', 'never', 'long', 'e', 'ever', 'proper'], ['ever', 'never', 'g', 'need', 'long', 'kind', 'occasions', 'part', 'neither'], ['must', 'times', 'displaying', 'done', 'may'], ['must', 'lowered', 'shall', 'cannot', 'flown', 'onlookers', 'slowly', 'state', 'displayed', 'occasions'], ['also', 'always', 'cars', 'may', 'platform', 'never', 'occasion', 'except', 'times'], ['vertical', 'must', 'generally', 'never', 'coincides', 'reserved', 'either'], ['never', 'even', 'displayed', 'placed'], ['never', 'governing', 'always', 'displaying', 'allowing', 'permitted', 'display', 'allowed', 'used', 'displayed'], ['lowering', 'lowered', 'flown', 'finally', 'allowed', 'position', 'presence', 'fit', 'always', 'displayed', 'mast'], ['must', 'displayed', 'periods', "host's", "guest's", 'vertically', 'placed', 'government', 'requires', 'someone', 'road', 'e'], ['displayed', 'also', 'mast', 'takes', 'traditionally'], ['times', 'flown', 'displayed']]

Processing features:  67%|██████▋   | 66/98 [31:45<14:58, 28.08s/it]

getting sample prompt forgetting sample prompt for 24193
 24192
getting sample prompt for 24194
getting sample prompt for 24195
getting sample prompt for 24196
getting sample prompt for 24197
getting sample prompt for 24198
getting sample prompt for 24199
getting sample prompt for 24200
getting sample prompt for 24201
getting sample prompt for 24202
getting sample prompt for 24203
TOP TOKENS [['azaleas', 'azalea'], ['azaleas', 'azalea'], ['azaleas', 'azalea', 'zonesazaleas'], ['azalea', 'azaleas'], ['azaleas', 'azalea'], ['azaleas', 'azalea', 'flowers'], ['azalea', 'azaleas', 'grimke'], ['azaleas', 'azalea', 'azaleas’', 'garden'], ['azaleas', 'azalea'], ['azaleas', 'they’re', 'white'], ['azaleas', 'azalea'], ['haale'], ['saale', 'rivers'], ['smale'], ['swale', 'swales'], ['azaleatin', 'azalein', 'rhododendron'], ['azalea', 'azalee', 'azaleos', 'azaleah', 'azaleia', 'azaleya', 'azalya', '1911-1988', 'azala', 'azalia'], ['azaleas', 'azalea', '6', 'family'], ['rodale', 'institute'], ['azalea', 'azaleastrum', 'azaleas']]
TOP TOKENS [['gleevec', 'work?gleevec', 'gleevec?gleevec®', 'medicines'], ['gleevec', 'growing', 'cls'], ['gleevec', 'growing', 'cls'], ['gleevec', 'dose', 'cells', 'states', 'receptor', 'cls', 'february', 'abl', '2008', 'kinases', 'several'], ['gleevec', 'since', 'however'], ['gleevec', 'gleevec®', 'click', 'called', 'grow', 'drug'], ['gleevec', 'receptor', 'kit', 'makes', '877'], ['gleevec', 'growth', 'cell', 'however', 'fingertips', 'parts', 'rapid'], ["gleevec's", 'gleevec', 'called', 'newsweek', 'glee', 'effects', 'claims'], ['gleevec', 'without', 'disease', 'like', 'says', 'drugs', 'alive', 'little'], ['surname', 'gleeson'], [], ['census-designated'], ['gleeson', 'tournament', '2011', 'country', 'yesterday', 'played', 'october', 'time', 'however', 'given'], [], ['2017', 'gleeson', '2008', '2019', 'july'], ['gleed', '1836–1916'], ['gleek', "gleek's", 'ringtone', 'cls', 'offs', 'appears', 'one', 'try', 'series', '1977'], ['later', 'gleeson', 'matches', 'offs', 'team', '23', 'marked', '–', 'age', '2017', 'received', 'slovakia', 'nine', 'despite'], ['gleed', 'military', '73', '60', 'law', 'contractors', 'worked']]
TOP TOKENS [['kazakhstan', "kazakhstan's", 'kazakh', 'kazakhstani', 'organisation', 'kazakhs', 'country', 'rule', 'nato'], ["kazakhstan's", 'kazakhstan', 'kazakhstani', 'kazakhs', 'powers', 'grain', 'kazakh', 'gas'], ['kazakhstan', 'independent', 'land'], ['kazakhstan', 'kazakh', 'kazakhs'], ['kazakhstan', "kazakhstan's", 'nato', 'kazakh', 'organisation', 'tip', 'kazakhs', 'ussr', 'century'], ['kazakhstan', 'etc', 'kazakhstani', 'kazakh', 'uzbekistan', '2016', 'republic', 'country'], ['kazakhstan', 'south', 'term', 'five'], ['kazakhstan', 'south', 'term', 'five'], ['kazakhstan’s', 'kazakhstan'], ['kazakhstan', "kazakhstan's", 'kazakhs', 'politics', 'kazakh', 'site', 'nevertheless', 'deltas', 'century'], ['kazakhstan', 'opposition', 'resources'], ['kazakhstan', 'medal'], ['kazakhstan'], ['kazakhstan', "kazakhstan's", 'kazakhs', 'kazakh', 'deserts', 'kazakhstani', 'mi', 'belarus'], ['kazakhstan', 'kazakh', 'kazakhstan-related', 'reading', 'links', 'kazakhs', '1957', 'external', '1934', 'soil'], ['kazakhstan', 'archery', 'muaythai'], ["kazakhstan's", 'kazakhstan', '53'], ['kazakhstan', 'july'], ['kazakhstan', 'kazakh', 'kazakhstani'], ['kazakhstan', 'country']]
TOP TOKENS [['di', 'sono', 'da', 'scipione', 'marcello', 'celebre', 'maturino', 'entrambi', 'p', 'teatini'], ['di', 'taddeo', 'da', 'della', 'buonarroti', 'benvenuto', 'agostino', 'benozzo', 'del', 'gian', 'raffaello', 'piero', 'fabriano', 'baccio', 'masolino', 'gentile', 'angelo', 'sansovino', 'gaddi'], ['bartolini', 'della', 'ricasoli', 'circonvallazione', 'di', 'piazza', 'salimbeni', 'viali', 'ponte', 'firenze', 'spini', "de'tornabuoni", 'del', 'reale', 'affari', 'palazzo', 'annunziata', 'nobili', 'innocenti'], ['di', 'sono', 'e', 'quello', 'sempre', 'che', 'nella', 'crociata', "dell'ultima"], ['di', 'san', 'del', 'beato', 'mannozzi', 'st', 'battista', 'da'], ["dell'ospizio", 'stesso', 'tutti', "que'fratelli", "quest'essempio", 'fervore', 'ricevevano', 'sempre', 'persone', 'di', 'nel', 'rendendosi', 'della', 'funzioni', 'poi', 'refettorio', 'continuandosi', 'sono', "dall'algardi", 'le', 'dando', 'intrapresero', 'sotto', 'lo', 'il', 'magnifico', 'facevano', 'e', 'presero', 'dipinto', 'che'], ['di', 'poggibonsi', 'giamberti', 'giuliano', 'maddalena', 'colle', 'palazzo', 'ludovico', 'delle', 'montepulciano', 'arezzo', 'de’', 'san', 'sansepolcro', 'sforza', 'biagio'], ['di', 'filippino', 'benedetto', 'della', 'memmi', 'baldassarre', 'gozzoli', 'costanza', 'benozzo', 'taddeo', 'fredi', 'filippuccio', 'duomo', 'bartolo', 'dei', 'lippi', 'jacopo', 'st'], ['di', 'distinzione', 'vendere', "de'sommi", 'questo', 'da', 'essendo', 'ammorbati', "sant'angelo", 'tutto', "l'interpetrazioni", 'ottavio', 'rinchiusi', 'fatto', 'costruito', 'stessero', 'questa', 'condiscendenza', 'prese', 'che', 'vecchie', 'la', 'lasciavansi'], ['borghese', 'corrottamente', 'di', 'doverebbe', 'palazzi', 'fonte', 'alessandrina', 'paluzzi', 'paolina', 'capizucchi', 'dei', 'palazzo', 'mezzo', 'stati', 'caetani', 'albertoni', "de'capizzucchi", 'che'], ['borghese', 'di', 'da', 'della', 'terme'], ['del', 'santi', 'di', 'apostoli', 'gentili', 'arcione', 'poli'], ['ottavio', 'dizionario-biografico', 'sepolcro', 'farnese', 'beato', 'degli', 'dizionario', 'italiani'], ['borgo', 'donnino', 'san', 'piacenza'], ['raguzzini', 'san', 'del', 'annunziata', 'porta', 'piazza'], ['visconti', 'della', 'bolognese', 'florentines', 'da', 'scala', 'ghibelline', 'bernabo', 'forli'], ['architetti', 'aldobrandini', 'girolamo', 'de', 'di', 'frascati', 'scultori', 'intagliatori', 'porta', "dell'acqua", 'le', 'ed', 'martino', 'pittori', "aldobrandini's"], ['rovere', 'di', '1725-1771', 'imperiale', 'scacciati', 'cosimo', 'della', 'foggini', 'battista', 'sculptor', 'lippi', '1684-1749', 'vittoria', 'younger', 'médicis', 'shading'], ['signorie', 'borgodelpozzo', 'dei'], ['di', "dell'immacolata", 'palazzo', 'san', 'bargellini']]
TOP TOKENS [['nutria', 'nutrias'], ['nutria', 'wildlife', 'early', 'water', '50'], ['nutria', 'yards', 'costly'], ['nutria', 'freshwater', 'early', 'vegetation', 'well', 'permit', 'tubers', '“', 'severe', 'parasites', 'released', 'also', 'subsequent'], ['nutria', "nutria's", 'moreover', 'overnight', 'loss', 'predominately'], ['nutria', "nutria's", 'moreover', 'overnight', 'loss', 'predominately'], ['nutria', 'u', '1', 'tracks', 'long'], ['nutria', 'c', 'states', 'banks', 'l', 'j', 'bilateria', 'ryan', 'university', '810', 'ed', 'merritt', 'drickamer', 'f', 'diversity', 'well', 'czaplewski', '389', 'k', 'jones', 'vaughan', 'wcb'], ['nutria'], ['nutria', 'pottery', 'neighborhood', 'literally', 'miles'], ['nutria', 'marshes', 'sugarcane', 'early', 'underground'], ['nutria', 'nutrias', 'enamel', 'days', 'reeds'], ['nutria', 'nutrias', 'fisheries', 'mothers', 'female', 'u', 'tails'], ['nutria', 'curraheen'], ['nutria', 'typically', 'larger'], ['nutria', 'notice', 'used', 'make', 'especially', 'though', 'expensive', 'phosphide'], [], ['state', 'bisiaco', 'piriá'], ['coria', 'corium', 'curia', 'inveresk'], ['janusia']]
TOP TOKENS [['kirchhoff', 'kirchoff', 'kirchoffs', 'series', 'second', '’', 'gustav', 'lost', 'continues'], ['kirchhoff', '’', 'known', 'respective', 'apply'], ['kirchhoff', '30', 'subtraction', '40', 'uses', 'r2', 'history', '148', 'v', 'gustav', 'simultaneous', 'r1', 'helpful', 'z', '936', '’', 'vb', '9'], ['kirchhoff', 'use', 'basic', 'using', 'revolve', 'values', 'many', 'complex'], ['kirchhoff', 'use', 'state', 'expressing', 'v1', 'plus', '’', 'another', 'total', 'law', 'note', '–', 'voltage', 'examples'], ['kirchhoff', 'use', 'circuit', 'vr3', '’', 'basic', 'gustav', '20', 'sufficient', 'volts', 'current'], ['kircher', 'considering', '1623', 'knowledge', 'monumentis', 'time', 'provide', 'fascinating', 'short', 'encounter', '—', 'grand', 'herwath', 'reveal', 'von', '1637', 'hieroglyphics'], ["kirchhoff's", 'kirchhoff', 'working', 'b', 'r', '22', 'explaining', 'apply', 'state', 'one', 'applying', 'loop', 'simple', 'often', 'use'], ['kirchhoff', '416', '2ω', '’', '0', 'r2', 'thing', '4i', '2i', 'series', '5', '12i'], ['kirchhoff', 'occur', 'robert', 'called', 'first', '0', '’', 'particular', '1'], ['kirchhoff', 'kirchhof', 'kirchhoffer', "kirchhoff's", 'kirchoff', '1890–1977', '1826–1908', 'adolf', 'gustav', 'american', 'institute', 'research'], ['kirchhoff', '3', 'players'], ['kirchberg', 'chirpăr', 'rhein-hunsrück', 'st', 'bensheim'], ['verchin', 'verchinois', 'flamboyant'], ["kirchhoff's", 'kirchhoff', 'fsv', "men's", 'haiger', '2', 'expatriate', 'germania', '1'], ["karcher's", 'karcher', 'although', '10', '6', '3', 'hired', 'record', '2011'], ['kirchbach', 'wolfgang', 'kirchbach-zerlach', 'first', '1850–1925', '1859-1912', 'world', 'styria'], ['durchov', 'pfc', 'first', "men's"], ['kircher', '3', "men's", '2019'], ['kirchdorf', 'diepholz']]
TOP TOKENS [['sparkling', 'water', 'fizzy', 'carbonated'], ['sparkling', 'carbonated', 'water', 'joesph', 'carbonation'], ['sparkling', 'carbonated', 'carbonation', 'refreshing', 'water'], ['sparkling', 'carbonated', 'carbonation', 'refreshing', 'water'], ['sparkling', 'water', 'including', 'seltzer', 'drinking', 'health'], ['sparkling', 'carbonated', 'water', 'carbonic'], ['sparkling', 'allfreightfree', 'made', 'water', 'carbonated', 'seltzer', 'impregnating'], ['sparkling', 'yes', 'water', 'carbonated', 'fizzy', 'carbonation', 'carbonic', 'seltzer'], ['sparkling', 'water', 'drinking', 'seltzer', 'carbonated', 'unhealthy', 'carbonation', 'like'], ['sparkling', 'water', 'infrared', 'carbonated', 'carbonation', 'fizzy'], ['sparkling'], ['sparkling', 'cls', 'fizzy'], ['sparkling', 'effervescent', 'carbonated', 'carbonation', 'seltzer', "priestley's", 'impregnating', 'waters', 'fizzy'], ['wisconsin.sparkling', 'sparkling'], ['sparkling', 'creative'], ['sparkling', 'unsweetened', 'carbonated', 'water', "of'fizz", 'seltzer', "city's", 'frying', 'make', 'plain', 'alcoholic'], ['sparkling', 'fizzy', 'effervescent', 'carbon', 'term', 'cls', 'pearl'], ['sparkling', 'water', 'carbonated', 'effervescent', 'daily', 'carbonic', 'teetha', 'mineral', 'gives'], ['sparkling', 'sparkle', 'making', 'champagne', 'wine', 'reds', 'red', 'fully'], ['carbonated', 'sassafras', 'sassafra', 'foamy', 'float', 'aromatic', 'cola', 'coca', 'confectionery', 'coal', 'root', 'teetotaler', 'consumed', 'u']]
TOP TOKENS [['scintillator', 'particle-beams', 'systems', 'device', 'volume', 'compatibility'], ['energy', 'tpc', 'cherenkov', 'technology', 'range', 'detector', 'kt', 'experiment', 'correlations', 'beam', 'protons', 'measurement', 'tool', 'lepton', 'experiments', 'high', 'kamioka', 'events', 'study', 'neutrino', 'science', 'gev', 'performed'], ['scintillator', 'muon-spallation'], ['scintillation', 'scintillator', 'scintillators', '0406035', 'liquid', 'detector', 'phys', 'c', 'experiment', 'nue', 'mckeown', '7be', 'ideal'], ['scintillation', 'scintillator', 'physics'], ['scintillator', 'scintillating', 'bits', 'given', 'uses', 'sandwiched', '2', 'high', 'thick', 'fibres'], ['scintillation', 'scintillator', 'detector', 'journal||journal', 'physics', 'york', 'trigger', 'us', 'lngs'], ['scintillation', 'detector', 'experiment', 'detectors', '7', 'kev', 'energy', 'recoils', '6', 'data', 'signal', 'target'], ['scintillator', 'scintillating', 'scintillators', 'scintillation', 'mev', 'experiment', 'protons', 'energies', 'high', 'angle', 'energy', 'luminosity', 'pellet', 'positrons', 'used', 'photons', 'target', 'higher', '96', '3', 'gev', 'plastic', 'projectiles', 'radiation', 'intensities'], ['scintillator', 'scintillators', 'respect'], ['scintillator', 'sciboone', 'target', 'peak', 'energy', 'experiment', 'mev', 'bunches', 'producing', 'cherenkov', 'protons', 'lappds', 'gev', 'detector', '4'], ['scintillator', 'scintillation', 'energy', 'energies', 'detector', 'cherenkov', 'mev', 'array', '30', '8', '17', 'antineutrinos', 'antineutrino', 'range', 'collecting', 'light', 'neutrinos', 'liquid', 'measured', 'proton'], ['experiment', 'particle', 'detector', 'physics', 'experiments', 'luminosity', '711fb−1', 'energy', 'target', 'taking', 'data', 'times'], ['scintillation', 'scintillator', 'scintillating', 'detector', '1325', 'energy', 'megaelectronvolts', 'antineutrinos', 'isotropically', 'cherenkov', 'light', "detector's", 'device', 'dimming', '20', 'mev', 'neutrinos'], ['scintillator', 'radiation', 'detector', 'highest', 'energies', 'cherenkov', 'events', '8mev', 'produced', 'event', 'emit', 'detectors', 'achieve', 'energy', 'neutrinos', 'physics', 'lappds', 'producing', 'scale', 'photons', 'order', 'interaction', 'around', 'higher', 'photodetectors'], ['lappds', 'event', 'energy', 'beam', 'physics', 'interactions', 'detector', 'neutrino', 'experiments', 'fall', 'data', 'done', 'tank', 'events', 'designed', 'used', 'pmts', 'phase'], ['experiment', 'detector', 'neutrinos', 'produced', 'energy', 'showers', 'instrumented', 'facility', 'data', 'lepton', 'interaction', 'appearance', '2010', 'cherenkov', 'taking', 'physics', 'located', '4', 'beam', 'ran', 'sent', 'produce', '99', 'towards', 'medium'], ['scintillators', 'experiment', 'detector', 'detectors', 'data', 'setup', 'trigger', 'experiments', 'antiproton', 'using', 'shower', 'calorimeters', 'cern', 'taking', 'emitted', 'collider', 'high'], ['scintillator', 'energies', 'experiments', 'experiment', 'particle', 'gev', 'lead', 'obtained', 't2', 'leptonic', 'expectations', '80', 'trigger', 'high', 'data', 'given', 'sep', 'production', 'time', 'bosons', 'boson', 'cern', 'mass'], ['detector', 'make', 'experiment', 'took', 'data', 'range', 'experiments', 'target', 'downrange', 'results', 'miniboone', 'neutrino', 'protons', 'decayed', 'hit', 'particles', 'event']]
TOP TOKENS [['kennedy', 'opportunity', 'befriend'], ['kennedy', 'kennedys', 'rose', 'come', 'dinners', 'kathleen', 'girls', 'parents', 'weeks', 'years'], ['kennedy', "their'way", 'nytimes', 'documents', '9', 'times', 'economy', 'vanquish', "house's", 'cfm', 'enemies', 'people', 'https', '120582', 'image'], ['kennedy', 'sen'], ['kennedy', 'election', 'times', 'congressional', 'jr', 'act'], ['kennedy', "kennedy's", 'j', 'f', "sr.'s", 'p'], ['kennedy', 'country', 'air'], ['kennedy', 'stake', 'proof', 'governments', 'federal', 'instead', '”', 'avers'], ['kennedy', '”', 'instance', 'presidency', 'race', 'way', 'says', 'cial', 'vote', '’', 'interracial', 'essays'], ['kennedy', 'leader', 'answered', 'maintained', 'leadership', 'president'], ['kennedy', 'american', 'football'], ['kennedy', "kennedy's", 'mr'], ['kennedy', 'also', 'pp', 'ashton', '2011', 'rev', 'l', 'susanna', 'sex', 'see', 'crime', 'scholarship', 'links', '2023', 'reading', 'history', "there's"], ['kennedy', 'kennedys'], ['kennedy', "kennedy's", 'plans', 'components'], ['kennedy', '2023', 'bureaucratic', 'daughters', 'diet', 'convention', 'stage'], ['kennedy', 'usl', 'soccer', "men's", 'deportes'], ["kennedy's", 'kennedy', 'interest', 'carolina', 'website', 'project'], ['kennedy', "kennedy's", '1935', '1941', 'north', 'numbers'], ['kennedy', 'apostolate', 'j', 'ed', 'investigations', 'loneliness', 'human', 'sexuality', 'life', 'counseling', 'ward', "d'arcy"]]
TOP TOKENS [['tefillin', 'traditionally', 'even'], ['tefillin', 'tefillen', 'cls', 'exist', 'תפילין'], ['tefillin', 'tefillin1', 'worn', '1', 'phylacteries1', '9:20'], ['tefillin'], ['tefillin'], ['tefillin', 'well', 'whether', 'century', 'laying', 'originally'], ['tefillin', 'process', 'online', 'hand', 'extending'], ['tefillin', 'cls'], ['tefillin', 'since', 'wearing', 'lay', "one's"], ['tefillin', 'wear'], ['tefillin', 'include', 'singular', 'torah', 'cls', 'tefillah'], ['tefillin', 'case', 'wear', 'peaks', 'whether'], ['tefillin', 'tefilin', 'wear', 'commandment'], ['tefillin', 'heb', 'bears', 'one'], ['tefillin', 'heb', 'tefilin', 'bears'], ['tefillin', 'hasoferet.com'], ['tefillin', 'scrolls', 'communities', 'per', 'head', '5', 'arm', 'tzitzit', 'ashkenazic'], ['tefillin', 'many', 'tzitzit'], ['tefillin', 'disqualify', 'maʻabarta', 'dough', 'lentil', 'e', 'barleycorn', 'thitura', 'would'], ['tefillin', 'whether', 'hamoed', 'wear', 'regarding', 'day', 'unless']]
TOP TOKENS [['klingons', 'klingon'], ['klingon', 'klingonisch'], ['klingons', 'klingon', "klingon's"], ['klingon', 'klingons'], ['klingons', "klingon's", 'klingon'], ['klingon', 'klingons', 'english/klingon', 'klingon/english', 'klingonese'], ['klingons', 'klingon'], ['klingon'], ['tlingit'], ['klingons', 'klingon', 'swarthy'], ['klingon', 'klingons'], ['klingon'], ['tlingit', 'stikine', '29'], ['tlingit', 'languages', 'american', 'syntactic'], ['klingon', 'klingonisch'], ['tlingit', 'events'], ['tlingit', "mother's", 'older', 'chilkoot', 'northwestern'], ['tlingit', 'tlingits', 'although'], ['klingon', 'duolingo'], ['klingon', 'klingons', "warrior's"]]
TOP TOKENS [['acne'], ['acne'], ['acne'], ['acne', 'vulgaris'], ['acne'], ['acne', 'vulgaris', 'pimples', 'teenagers'], ['acne'], ['acne'], ['acne', 'vulgaris', 'blemishes', 'known'], ['acne', 'even'], ['acne', 'vulgaris', 'disease', 'pimples', 'world', 'western', 'ones', 'available', 'worldwide', 'unclear'], ['vulgaris', 'acne', 'acneiform', 'pruritic', 'pimples', 'hair', 'conglobata', 'abscesses', 'comedones', 'infantile'], ['vulgaris', 'acne', 'adulthood', 'l', 'gr', 'appear', 'said', 'although', 'literature'], ['acne', 'infantile', 'acneiform', 'appear', 'play'], ['acne', 'vulgaris', 'adulthood', "acne's", 'old', '8', 'years', 'misperceptions', 'people'], ['acne', 'may', 'referral', 'gland', 'shampoos', 'pustulosis', 'acneiform', 'tends', 'maternal', 'ointments', 'neonatal', 'diseases', 'endocrinologist', 'creams', 'presents', 'present', 'occur', 'eruptions', 'warranted', 'sebaceous', 'glands', 'believed', 'mother', 'often', 'like', 'commonly'], ['acne', 'vulgare', 'vulgarism', 'vulgaris', 'diseases', 'disease'], ['acne', 'acneiform', 'eruptions', 'contraception', 'look', 'masculinizing', 'bumps', 'folliculitis', 'usually'], ['coarser', "adolescent's", 'hair', 'tends', 'cases', 'may', 'age'], ['acne', 'vulgaris', 'severe', 'tends', 'groups', 'may', 'appearance', 'descent', 'disease', 'physician', 'adolescence', 'amerindian', 'non', "skin's", 'diseases', 'small']]

Processing features:  68%|██████▊   | 67/98 [32:14<14:38, 28.33s/it]

getting sample prompt forgetting sample prompt for 24205
 24204
getting sample prompt for 24206
getting sample prompt for 24207
getting sample prompt for 24208
getting sample prompt for 24209
getting sample prompt for 24210
getting sample prompt for 24211
getting sample prompt for 24212
getting sample prompt for 24213
getting sample prompt for 24214
getting sample prompt for 24215
TOP TOKENS [['good', 'great', 'news', 'splendid', 'hear', 'bad', 'like', 'needed', 'sounds'], ['‘good', 'good', 'news’', 'news'], ['bad', 'news', 'transformation', 'hear', 'put', 'negative', 'receiving', 'deal', 'dealing', 'contextualization'], ['good', 'news', 'great', 'bad', 'want'], ['news', 'bad', 'good', 'receiving', 'surprising', 'cls', 'come', 'forms'], ['news', 'good', 'bad'], ['good', 'great', 'news', 'got', 'excited', 'splendid', 'bad', 'wow'], ['good', 'news', 'concerning', 'mixed', 'surprises'], ['news', 'made', 'good', 'much', 'coming', 'available', 'released', 'unknown'], ['recent', 'roundup', 'news', 'interesting', 'another', 'stories', 'catch', 'large'], ['news', 'musicals', 'good', 'musical', 'love', 'film'], ['events', 'news', 'film', 'carbon', 'extensible', 'musical', 'earring', 'gumball', 'theatre', 'worldshops', 'paramore', 'w', 'communique', 'n', 'arts', 'straits'], ['news', 'say', 'blink-182', 'heartbreak'], ['news', 'good', 'black-and-white', 'also', 'musical', 'musicals', 'shown', '1947', '1940s', 'based', 'production'], ['news', 'good'], ['news', 'good', 'albums'], ['news', 'good', 'abbey'], ['news', 'aggregation', 'network'], ['news', 'good', 'anything', 'albums', 'report'], ['news', 'deusm', 'serves', 'links', 'design', 'subscribers', 'tools']]
TOP TOKENS [['faucet', 'faucets', '29'], ['faucet', 'faucets'], ['faucet', 'faucetmiddle', 'kitchen'], ['faucet', 'faucets'], ['faucet', 'faucets', '14'], ['faucet', 'faucets', 'low-end'], ['faucets', 'faucet'], ['faucets', 'faucet'], ['faucet', 'faucets', 'leaking'], ['faucets', 'fauce', 'faucet'], ['faucet'], ['fauces'], ['faucets', 'faucet', 'flow', 'automatic'], ['faucette'], ['faucets', 'faucet', 'spigots', 'bolts'], ['fauces', 'b', '3.6.3'], ['faucets', 'faucet'], ['faucet', 'faucets', 'surface', 'sieve', 'non', 'flow'], ['faucette', 'engineered'], ['faucett', 'new', 'death', 'parliament', 'least', '8', 'april', "mary's"]]
TOP TOKENS [['quickly', 'immediately', 'quick', 'soon', 'urgency', 'sees', 'asap', 'next', 'instead', 'within'], ['quick', 'short-term', 'look', 'primary', '60,000'], ['immediately', 'immediate', 'instantly'], ['quickly', 'quick', 'rapid', 'instantaneous', 'fast', 'rapidity', 'quickkwɪk', 'leaking', 'swift', 'short'], ['quick', 'fast'], ['quick', 'rapid', 'quickly', 'fastest', 'quicker', 'moreover', 'furthermore'], ['rapid', 'fast', 'adj'], ['quickly', 'quick', 'hastily', 'immediately', 'promptly', 'brief', 'hurried', 'rapidly'], ['quick', 'quickly', 'short', 'already'], ['rapidly', 'quickly', 'speedily'], ['quick', 'quickly'], ['quick', 'band', '1932'], ['quickly', 'using'], ['kiss-me-quick', 'quick'], ['quick', '1945', 'historically'], ['quickly', 'external', '2008', '17'], ['rapid', 'rapid(s', 'brig'], ['quick', '1900'], ['quick', 'rapid'], ['quick', 'center', 'originally']]
TOP TOKENS [['plastic', 'plastics', 'computer'], ['plastic', 'steel', 'word', 'adhesives'], ['plastic', 'plasticity', 'plastics', 'word', 'many', 'people'], ['plastic'], ['plastic', 'plastics', 'use', 'simple', 'century', '’'], ['plastic', 'just…plastic', 'without'], ['plastic', 'plasticfree', 'unk', 'sense', 'personal', 'aisle'], ['plastic', 'plastics', '1960s'], ['plastic', 'plastically', 'plasticus', 'english', 'plasticity', 'plasticky', 'plasticize', 'оксфордский', 'n', 'shape'], ['plastic', 'plastics'], ['plastic', 'plastic.com', 'plastics', 'plasticity'], ['plastic'], ['plastic', 'external', 'links', 'town'], ['plastic', 'plastics', 'membranes', 'durable', 'etc', 'references', 'elasticity', 'polymers', 'moulding'], ['plastic', '1999'], ['plastic', 'plastics', 'pollutants'], ['plastic', 'herman'], ['plastic', 'free', 'range'], ['plastic', 'dichloromethane', 'tetrahydrofuran'], ['plastic', 'plastic-based', 'plastics', 'plasticized', 'items']]
TOP TOKENS [[], ['write'], ['write'], ['summarize'], ['critique'], ['critique', 'article'], ['rather', 'critical', 'critique'], ['critique'], ['critique', 'summarize'], ['critique', 'one', 'analysis'], ['critical', 'adelaide', 'critique', 'immanuel', 'consequences', 'critic'], ['review', 'analyses', 'summary', 'whereas', 'come', 'article', 'readers', 'papers', 'published', 'presents', 'made', 'authors', 'reading', 'writing', 'articles', 'presented', 'treated', 'author'], ['review', 'article', 'cls', 'biased', 'suggestions', 'summarizes', 'relevance', 'since', 'discuss'], ['solicited', 'usually', 'article', 'abbreviated', 'rests', 'written', 'columns', 'published', 'effect', 'editorials', 'opinionated', 'write'], ['review', 'evaluations', '1817', 'journal', 'brown'], [], ['code-named', 'un-sentimental', 'nonfictional', '1993', 'piece', 'document', 'clerkship', 'creeds', 'u.s', 'impeachment', 'publishing'], ['article', 'unsolicited'], ['francis', 'montaigne'], ['response', 'critica', 'criticism', 'written', 'writing', '“', 'critique', "kant's", 'range', 'presented', 'personalized', "between'critique'and'criticism", 'projectiles', 'detailed', 'practical', 'critiques', 'critical', 'influential', '”', 'theoretical', 'refers']]
TOP TOKENS [['large', 'year', 'although', 'panama'], ['rather', 'favours', 'slender', 'foothills', 'mostly', 'blotchy', 'woodland', 'cornered', 'abundant', 'commonly', 'obvious', 'apparently', 'thinly', 'head', 'small', 'robust', 'typical', 'areas', 'sounds', 'startling', 'spiny', 'lizards', 'pale', 'eyes', 'climbers', 'watercourses', 'although', 'well', 'include', 'usually'], [], ['barren', 'one', 'grasses', 'two', 'roots', 'addition', 'collected'], ['sinai', 'northeastern', 'egypt', 'peninsula'], ['espanola', 'barcelona', 'carranza', 'press', 'j', '2003', 'species', '2001', 'p', 'unpublished', 'europe', 'galan', 'brana'], ['rædwald'], ['dominican', 'species'], ['b', 'walker'], [], ['trachylepis', 'reptiles', 'zoologist', 'somalia', 'forest', 'somali', '2003', 'ferrarai', 'medium-sized', 'genus', 'lizard', 'zoologico', 'combination', '1', '271–280', '12', 'svl', 'skinks', '424', '407–465', '1990', 'description', '446'], ['lepidoblepharis', '197–201', 'milan', 'konrad', 'reptilia', 'abel', 'province', 'arcadio', '2015', 'snout-to-vent', 'sphaerodactylidae', 'gunther', 'andreas', '3-5', 'panama', 'species'], ['reptiles'], ['lepidoblepharis', 'reptiles', 'forest', 'cacao', 'gekkota', 'buchwaldi', 'buchwald', 'von', 'rezent', '1843–1934', 'ecuador', 'naturalist', '90', 'l', 'der', '2000', 'bekannten'], ['name', '28–153', 'kommentierte', 'reptiles', '2', 'thiere', 'zoologische', 'howell', 'wolterstorffi', 'edition', 'u', 'rezent', 'p', '1900', 'stephen', '1-70', 'harald', '465–475', 'bekannten', '10', 'systematik', 'tanzania', 'und', '1991', 'combination', '1', 'cladistic', 'kim', '124', 'der', 'spawls', 'für', 'subrezent', 'gekkonidae', 'gekkonomorpha', '13', 'urocotyledon', '2000', 'keys', '584–586', '119', 'species', 'geographie', 'lizards', 'jahrbücher', 'pp', 'bloomsbury', '1983', 'dg'], ['reptiles', 'cryptoblepharus'], ['reptiles'], ['cryptoblepharus', 'reptiles', '11–12'], ['deaf', "hanson's", 'born', 'c', 'grounds', 'program', 'f', 'also', 'archives'], ['army', 'world', 'links', 'war', 'external', 'ii', '1945', 'deaths', 'military', "darby's", 'darby', '1992', 'references', 'births', 'garda', 'states', 'col']]
TOP TOKENS [['products', 'product', 'cls', '4unsought', 'behavior', 'royce', 'new', 'speak', 'market'], ['product', 'products', 'classifying'], ['products', 'easier', 'product', 'another', 'first', 'recommend', 'sure', 'comes', 'side', 'reason'], ['product', 'customers', 'products', 'hygiene', 'nall', 'need', 'contract', 'categories', 'cls', 'business', 'new', 'made', 'intended'], ['product', 'products', 'effort', 'use', 'potential', 'expected', 'classification'], ['products', 'product', 'usage', 'products:customers'], ['products', 'include', 'grooming', 'care', 'needs', 'designed', 'masks', 'hygiene', 'haircare', 'skincare', 'promote', 'styling', 'routines', 'shampoos', 'cover', 'nourish'], ['product', 'purposes', 'things', 'consumption', 'products', '“', 'different', 'car', 'appeal', 'result', 'one', 'consume', 'cls'], ['effort', 'products', 'wanted', 'professional', 'product', 'less', 'one', 'wants'], ['products', 'accrued', 'stocked', 'product', 'compared', 'unhealthy', 'energy', 'one'], ['product', 'graph', 'music', 'simply', 'hairstyling'], ['product', '2011', 'michigan', "product's", 'tour', 'self', 'reilly', '2010', 'jerome', 'way', '1', 'played', 'number', 'released', 'e', 'several', 'better', 'used', 'voters', 'covered'], ['product', 'concern', 'products', 'extensions', 'fusion', 'chain', 'activation', 'fission', 'nndc.bnl.gov'], ['product', 'united', 'products', 'light-emitting', 'states—in', 'led', 'york'], [], ['product', 'different', 'products', 'unproven', 'graph', 'exception'], ['external', 'appearances', 'subscribers', 'links', 'products', 'rapid', 'offered', 'usa', 'merchandising', 'shop', 'history'], ['products', 'many', 'apheresis', 'immunoglobulins', 'product', 'suspensions', 'blood'], ['products', 'product', 'allow', 'power', 'identity', 'uninteresting', 'discussing', 'defining', 'convention', 'starting'], ['products', 'product', 'deliverables', 'liability', 'bystanders', 'touch', 'need', 'presents', 'manufacturing', 'project']]
TOP TOKENS [['actions', 'objects', 'action', '4', 'behave', '3', 'situation', 'performed', 'specified', 'first', '1', 'nested', 'certain', '2'], ['‘failed’', 'mark', 'chosen'], ['selected'], ['pointing', 'works', 'given', 'trouble', 'java', 'first'], ['text.mark_set(tkinter.insert', 'cursor', 'start', 'chars', 'method', '9', 'details', 'peter', 'see', 'icursor', 'information', '5.2', 'behind'], ["template's", 'action', 'actions', 'user', 'templates', 'printing', 'specified', "assistant's", 'one', 'assistant', 'also'], ['followed'], ['bananas'], ['button', 'objects', 'ball', 'actions', 'action', 'one'], ['select', 'items', 'user', 'button', 'cls', 'combo', 'combobox', 'item', 'either', 'box'], ['value', 'list', 'user', 'combo', 'single-line', 'either', 'drop-down', 'box', 'something'], ['items', 'element', 'item', 'elements', 'list', 'user', 'option>list', 'selected', '2</option', '5</option'], ['functors', 'adjunct', 'adjoint', 'adjunction', 'stand', 'see', 'may', 'one', 'quite', 'p', 'respective', 'two'], ['action', 'actions', 'tags', 'fires', 'iterselect', 'constructs', 'thing'], ['precedes', 'succeeds'], ['knockout', 'c', 'relation', 'therefore', 'b', 'antitransitive', 'vice', 'case'], ['indication'], ['argument', 'someone', 'work', "a'los", 'cunt', 'idiot', 'arsehole', 'whatchamacallit', 'twat', 'another', 'prat', '–', 'would'], ['opponent'], ['counts', 'occur', 'opponent']]
TOP TOKENS [['cactus', 'cacti', 'sunlight', 'backyard'], ['cactus', 'cacti', 'complicated'], ['cactus', 'cacti'], ['“cactus”', 'cactus', 'cacti', 'within'], ['cactus', 'cacti', 'thorny'], ['cactus', 'cacti', 'optional'], ['cactus', 'cacti', 'watering', 'yet'], ['cactus', "cactus's", 'cacti', 'watering', 'cactii'], ['cactus', 'cacti'], ['cactus'], ['cactus', 'mexico', 'ii', 'kaktus', 'usmc', 'cactaceae'], ['cactus', 'www.cactuscode.org', 'laptops', 'history', 'checkpointing', 'tools'], ['cactus'], ['cactus', 'pediocactus', 'ferocactus', 'opuntia', 'cylindropuntia', 'sclerocactus'], ['cactus', 'cacti', 'fence'], ['cactus', 'cacti'], ['cactus', 'bsk', 'city', 'older', 'individuals', 'population', 'present', '445'], ['cactus'], ['cactus', 'pediocactus', 'sclerocactus', 'may', 'white', 'long', 'gypsum', '1994', 'america', 'echinocactus', 'soil', 'porter', 'fibers'], ['cactus', '2014', 'portable', 'flashes', 'built-in']]
TOP TOKENS [['values'], ['conclusions'], ['conclusions'], ['9721', 'equals', 'concentrations', 'much', '45g', 'various', '9721l', '445g', '9g', 'add', 'result', 'get', 'know', 'several', '18', '1ml', 'exactly', '100g', 'adding', 'better', '5', '84', 'making', 'spend', 'ton', 'liters', '8', '0', 'would', 'said', 'similar'], ['system', 'nervous', 'appears', 'vision', 'member', 'represents', 'affects', 'cryptococcosis', 'confusion', 'cause', 'untreated', 'lead', 'genitals', 'candidiasis', 'eruption', 'primarily', 'often', 'exudate', 'skin'], ['syphilis', 'reclassified', 'chaffeensis', 'ewingii', 'nonparalytic', 'rickettsiosis'], ['ultimately'], [], ['cover', 'subcategories'], ['cover', 'subcategories'], ['seidman', 'michael', 'parkford', 'mixing', 'co-production', 'cian', 'normalized', 'gavin'], ['uncredited', 'herculoids'], ['–', '90', '02'], ['girls', 'einsteins', 'doremi', 'got', 'cockroaches', 'wow', 'pals', 'reborn'], ['2002', '2009', '2001', '2011', '2006'], ['voices', '2002', 'tv', '2001', '—'], ['family', 'american', 'series', 'television'], ['–', 'entertainment', 'created', 'present'], ['supervisor', 'effects', '2001', 'artist', 'thir13en', '–', 'special', 'inc'], ['imagesoft', 'artswwsegajp', 'workstns', 'entertainmentiguana', 'entertainment']]
TOP TOKENS [['rage', 'osteoarthritis', 'end-products', '2013', 'rolewska', 'al', 'products'], ['rage', 'word', 'raged', 'named'], ['rage', 'road', 'threats', 'verbal', 'abuses', 'shouting', 'yelling'], ['rage', 'road', 'characterized'], ['rage', 'esrage', 'face'], ['rage', 'word', 'raged', 'named'], ['rage', 'facilities', 'lab', 'node'], ['rage', 'rage?”', 'road', '“road', 'experienced', 'screaming', 'verbally', 'term'], ['rage', "rage's", 'called', 'molecule', 'produces'], ['rage', "rage's", 'called', 'molecule', 'produces'], ['rage', 'film'], ['rager', 'rage', 'cheek'], ['rage', 'endproducts'], ['rage'], ['rage', 'en-rage', 'keyboard', 'singles', 'subsequent', 'sadler', 'band'], ['rage', 'scourge', 'links', 'appearance', 'external', 'thrasher'], ['rage', 'wild', 'furious', 'cls', 'running', 'became'], ['rage', 'experiencing', 'cls', 'raige', 'frenzy', 'violence', 'madness', 'rave', 'state', 'fury'], ['rage', 'cls', 'motif', 'inflammatory'], ['rage', 'inflammation', 'amount', 'upregulated', 'e']]
TOP TOKENS [['zinc', 'nausea', 'day', 'effects', 'diseases', 'supplement', 'reactions'], ['zinc', 'wellbeing', 'digestion', 'much', 'properly', 'long'], ['zinc', 'cold', 'function', 'healing', 'deficiency'], ['zinc'], ['zinc', 'zn', 'industry', 'silver', 'change', 'dark', '1982', 'syntheses'], ['zinc', "in'zinc", '”', 'example', 'dna', 'respiration', 'system', 'ones'], ['zinc', 'fertility', 'know', 'flus', 'sweating', 'ginger'], ['zinc', 'function', 'another', 'absorption'], ['zinc', 'gland', 'bodies', '3g', 'density', 'healing', 'diet'], ['zinc', 'neurodermitis', 'used', 'intake', 'wounds', 'disorder', 'preference', 'sensors', 'intakes'], ['zinc', 'survival', 'levels', 'tone'], ['zinc', 'loss', 'skeletal', 'body', 'intake', 'men', 'mouth', 'use', 'however', 'range', 'systems'], ['zinc', "as'zinc", 'function', 'role'], ['zinc', 'element', 'band'], ['zinc', 'zn', "as'zinc", 'activations', 'geometry', 'health', 'compromised', 'symptoms', 'deficiency', 'cells', 'example', 'necessary'], ['zinc', 'zinc-containing', 'soil', 'supercontinents', 'significant', 'oceans', 'increase', 'wurtzite', 'organisms', 'lithosphere'], ['zinc', 'levels', 'g', 'grams', 'examined', 'described', 'oral'], ['zinc', 'also', 'micronutrients', 'forms', 'sulfate', 'states', 'teratogenesis', 'salts'], ['zinc', 'external', 'stops', 'infection', 'problems', 'recommended', 'immunity', 'risk', 'hepatic', 'disease', 'vapour', 'impregnated', 'airtight', 'treat', 'organization', 'vein'], ['zinc', 'radicals', 'crops', 'vines', 'seedlings']]

Processing features:  69%|██████▉   | 68/98 [32:43<14:11, 28.38s/it]

getting sample prompt forgetting sample prompt for 24217
 24216
getting sample prompt for 24218
getting sample prompt for 24219
getting sample prompt for 24220
getting sample prompt for 24221
getting sample prompt for 24222
getting sample prompt for 24223
getting sample prompt for 24224
getting sample prompt for 24225
getting sample prompt for 24226
getting sample prompt for 24227
TOP TOKENS [['bio', 'introduction', 'additionally', 'materials', 'ferrous', 'alloys'], ['e', 'h', '19', 'vol', 'view', '–', '132', 'vch', 'eds', 'germany'], ['kawagoe', 'sunday', 'additionally', 'saturday', 'castle', 'also', 'buddha', 'women', 'tokyo', 'unk'], ['hap', 'nanosize', 'phases', 'synthesized', 'homogenous', 'happens', 'figure', 'ellipse', 'shown', 'years', 'micrometer', 'better', 'al', 'vials', 'morphology'], ['chinese'], ['introduction', 'gui', 'http://trolltech.com', "trolltech's", 'using', 'dialogs'], [], [], ['include', 'evans'], ['smoother', 'clarity', 'first', 'gles20', 'resulting', 'value'], ['wellins', 'english', 'wells', 'british', 'male'], ['fortuna', 'ayotunde', 'ikuepamitan', "men's", 'profile', 'links', 'goalkeepers', 'expatriate', 'external', 'players', 'football', 'hnk', 'references', 'first'], ['english', 'players', 'c'], [], ['living', 'people', 'awolowo', 'birth', 'university'], ['american', 'century'], ['manuel', 'plays', '83rd-minute', "men's", 'people', 'uruguayan', 'academy', 'appearances', '1–0', 'footballers'], ['corrochano', 'region', 'sportspeople', 'offenbach', '2012', '2016', 'waldhof', '2', 'november', "men's", '3', 'born', 'kickers', 'due', 'players', '2017', 'sv', 'managers', 'eintracht', 'association', 'football', '4', 'footballers'], [], ['leslie']]
TOP TOKENS [['casares', 'casali', 'casale', 'casa', 'casal'], ['casa', 'casas', 'casa’s'], ['casas', 'casa'], ['casapy', 'http://casaguides.nrao.edu/index.php?title=calibrating_a_vla_5_ghz_continuum_survey', 'casa', 'using', 'inside', 'single', 'script', 'simple', 'whole'], ['casa', 'cases'], ['casals', "casals'impact", "casals'virtues", '1973', 'responsibility', 'unimpeachable', 'cursory', 'strove', 'far', 'addition', 'late', 'scornful', 'little', 'steadfast', 'overestimated'], ['casals', 'istomin', '’', 'died'], ['casals', "casals'impact", "casals'virtues", '1973', 'responsibility', 'unimpeachable', 'cursory', 'strove', 'far', 'addition', 'late', 'little', 'scornful', 'steadfast', 'overestimated'], ['casas', '“', 'dispossessed8', 'virulent', 'claim', 'made', 'detractors'], ['casac', 'email@example.com', '716', '664-3661', 'scientifically', 'drug'], ['casas', 'viejas', 'municipality', 'benalup-casas', 'ves', 'casas-ibáñez', 'de', 'guijarro'], ['casar', 'cäsar'], ['casau'], ['casas'], ['casasco', 'alessandria', 'momperone'], ['casas', "casas'brother", 'infection', 'later', 'may', '2021', 'soxprospects', 'broward', 'com', 'tournament', 'red', 'sportspeople', 'del'], ['casas', 'emilia', 'claudio', 'roberto'], ['casares', 'surname'], ['casatenovo', 'casati', '1620–1702', '1881–1957'], ['casali', '1374', '1320–after', '1715–1792']]
TOP TOKENS [['rush', 'rushes', 'rushlights'], ["rush's", 'rush', 'mint', 'independence', 'day', '1786', 'war', 'philadelphia'], ["rush's", 'rush', 'mint', 'independence', 'day', '1786', 'war', 'philadelphia'], ['rush', 'like', 'blowhards', 'would', 'world', 'one', 'someone', 'think', 'clearly', 'consider', 'stands', 'gleefully'], ['rush', 'including', 'sciences', 'university', 'colleges'], ['rush', 'discover', 'visit', '’'], ['rush', 'rush-bagot', 'ticket', 'spent', 'benjamin', '1942', '©'], ['rush', 'rushes', 'name', '1.5'], ['rush', 'rushes', "tib's", 'ague', 'junci', 'plentiful', 'unpeeled', 'soporiferous', 'alludes', 'acorus', 'rhizome'], ['rush', "rush's", 'beyond', 'officially', 'bondage', '23', 'dr', 'lawyer', 'benjamin', 'knowledge'], ['rush', 'rushes'], ['rush', 'geography', 'serves'], ['rush', 'rushes', 'toyota'], ['rush', 'fighters', 'release', 'population', 'hoarded', 'yor', 'rags'], ['rush', 'brandon', 'cls', 'darius', 'jockey', 'roberts', 'dj'], ['rush', 'rushes'], ['rush', 'school', '15–9', 'practice', 'speedy', '84'], ['rush'], ['rush'], ['rush', 'tv', 'addition', 'external', '21', 'march', 'audience', 'edge']]
TOP TOKENS [['minute', 'minutes', 'consider', 'joisey', 'species', 'would', 'edit', 'physicists', 'use', 'fashionable', 'content-free'], ['minutes', 'circulate', 'mr', '‘a’', '3', 'bil'], ['minute', 'minutes', 'min', 'writing', 'adjective', 'noun'], ['minutes', 'minute', 'every', 'styles'], ['noun||1.||minutes', 'minute', 'minutes', 'minute2', 'tr.v', '2(mī-no͞ot′', '3', 'middle', 'held', 'memorandum', 'meeting', '7', 'min·utes'], ['minute', 'word'], ['minute', 'contains'], ['minute', 'minutes', 'produce', 'quality', 'pretty', 'effective', 'elements', 'key'], ['minute', 'minuter', 'today', 'minutes', 'nba', 'make', 'every', 'enter'], ['minute'], ['minutes', 'minute', 'newspaper'], ['minute', 'known', 'per', 'increased', 'although', '12'], ['minutes', 'indicated', 'wanted', 'arrangements', 'background', 'etchells', 'withheld'], ['minute'], ['minutes'], ['minutes'], ['minutes', '1856', 'bonzo'], ['minute', 'minimum', 'mǐn', 'min', 'ancient', 'lee', 'guinea', 'minnesota', 'minuth', 'austronesian', '909–945', 'high-speed'], ['minute', '2013', 'described', 'representatives', 'june', 'war', 'daily', 'election', '2010', 'pen', 'cup', 'le'], ["minute'''s", 'minute', 'head', '1970s', 'years', 'cls', '1962', 'disaffected', 'politics', 'invited', 'hunted', "l'aurore", 'early', 'chief', 'heyday', 'charles']]
TOP TOKENS [['sandy', 'transcription', 'word'], ['sandy', 'hurricane', 'well'], ['sandy', 'superstorm'], ['sandy', "sandy's", 'whether', 'however', 'thing', 'coast', 'track', 'clear', 'says', 'margusity'], ['sandy', "sandy's", 'atlantic', 'coast', 'another', 'landfall', 'data', 'track', 'likely'], ['sandy', "sandy's", 'atlantic', 'coast', 'another', 'landfall', 'data', 'track', 'likely'], ['sandy', '’', 'superstorm'], ['sandy', 'tuesday', 'hurricane', 'miles', 'cls', 'feet', '’', 'coast', 'caribbean'], ["sandy's", 'sandy', 'worse', 'preventing', 'atlantic', 'hurricane', 'scale'], ['sandy', 'hurricane', 'combined', 'cls', 'possible', 'realized', '2012'], ['sandy'], ['sandy', "sandy's", 'sandy’s', 'official'], ['sandy'], ['sandy', 'sandys', '1977–2006'], ['sandy', '1900', 'history'], ['sandy', 'disambiguation'], ['sandy', 'born'], ['sandy'], ['sandy', 'disambiguation', '1922–2007', 'director'], ['sandy']]
TOP TOKENS [['give', 'giving', 'givers', 'constitute', 'providing'], ['give'], ['give', 'giving', 'would', 'away', 'gave', 'constitute'], ['giving', 'give', 'giving,â', 'giveâ', 'knowledge', 'given', 'much', 'love.â'], ['dance-giving', 'giving', 'mammas', 'one'], ['givers', 'giver', 'giving', 'give', 'view', 'spiritual', 'brings'], ['giveth', '129—giving’s', '131—giving', 'giver', '133—giving', 'giving', 'given', 'givest', 'give', 'gave', '“gave', 'beyond', 'gavest', 'giving—found', 'importance', 'tuesday', 'sacrificial'], ['give', '“givers', 'givers', 'work', 'giving', 'giver', 'get', 'others', 'employees', 'protect'], ['give', 'giving', 'ceremony', 'want', 'verb', 'away', 'burned', 'gave'], ['giving', 'given', 'give'], ['giving', 'giver', 'give', 'given'], ['givers', 'giver', 'give', 'giving', 'given'], ['give', 'giver', 'givers', 'programming'], ['give', 'external', 'links', 'gave', 'references'], ['giveon', "giveon's", 'contemporarily', 'give', 'explained', 'released', 'rev3', 'chahayed', 'rev3score'], ['giver', '50,000', 'non-fiction', 'three-time', 'outstanding', 'birthday', "children's", 'located', 'different', 'informational'], ['giver', 'giving', 'give', 'given'], ['give'], ['give', 'givenness', 'given', 'effect'], ['give', 'government', '1977']]
TOP TOKENS [['uyu', 'u', 'uranium', "u's", 'universal', 'union', 'word', 'metallic', 'definitions', 'thing', 'element'], ['uracil', 'u(noun', 'u'], ['ucl4', 'uranous', 'u•ra•nousˈyʊər', 'uranousˈyʊər', 'uranyl', 'uranium', 'uraninite', 'u4', 'uranic'], ['uuof4', 'uuo2', 'uuoh', 'ununoctium', 'uuof2', 'uuo', 'noble'], ['uuof4', 'uuo2', 'uuoh', 'ununoctium', 'uuof2', 'uuo', 'noble'], ['uranates', 'u2o7', 'u', 'uranate', 'uranium', 'uon', 'uranyl', 'uo4', 'uo3', 'uo2', 'oxyanion', 'oxide', 'bau2o7', 'cation', 'atoms', 'ox', 'used', 'oxygen'], ['uranylˈyʊər', 'uranyl', 'uranium', 'u-o', 'uo2', 'uo', 'definitions'], ['ugc-based', 'ugc', 'u', 'user-generated', 'url', 'soon'], ['uranyl', 'uranium', 'u', 'uo2', 'uf4', 'dioxide', 'uo3', 'industrial', 'oxide'], ['u', 'ugali', 'umngqusho', 'ugli', 'letter'], ['u', 'uline'], ['uox', 'urate'], ['ugb', 'united', '1980', 'gulf'], ['ufs', 'united', 'state', 'universal', 'system'], ['u', 'university', 'street', 'avenue', 'south'], ['uf', 'united', 'utrikespolitiska', 'capacitance', 'ultrafiltration', 'francophones', 'florida', '10−6', 'findlay', 'india', 'ultimate'], ['ub', 'united', 'u', 'universal', 'catalonia', 'ubiquitin', 'ubu', 'barcelona', 'bezpieczenstwa', 'ubo', 'ultimatebet', 'ubs', 'urantia', 'see', 'bohol', 'bator'], ['urophora', 'unica'], ['udea', 'uralica'], ['uracil', 'u', 'ularitide', 'ucephan', 'uni', 'umifenovir', 'urelumab', 'uredofos', 'ultraquin', 'urapidil', 'umirolimus', 'uremol', 'urefibrate', 'ultra', 'uramustine', 'ulimorelin', 'urabeth', 'ultravist', 'ufiprazole', 'ublituximab', 'utibapr', 'ufenamate', 'ultralente', 'umespirone', 'umeclidinium', 'ultragris', 'ultraseultratag', 'urtoxazumab', 'ultane', 'uldazepam', 'unisom', 'urex', 'urasal', 'ulo', 'urisec', 'ureaphil', 'ulobetasol', 'ubenimex', 'univasc', 'uloric', 'ulcerease', 'ulipristal', 'ursoursodeoxycholic', 'urecholine', 'ustekinumab', 'udenafil', 'ultravate', 'uredepa', 'ubidecarenone', 'usistapide', 'unguentine', 'urovist', 'uri', 'ubisindine', 'ultram', 'uniphyl', 'uridine', 'uroplus', 'uromitexan']]
TOP TOKENS [['wounded', 'knee', 'ghost', 'declared'], ['wounded', 'knee', 'go', 'site', 'protest', 'fought', 'announced'], ['wounded', 'knee', 'day', 'heard', 'lakota', 'fratricide', 'backed', 'bandwagon', 'december', '”', 'among', 'entire', 'peacefully', 'wipe', 'protection', '“', 'turned', 'history', '29', 'families'], ['wounded', 'knee', 'day', 'heard', 'lakota', 'fratricide', 'backed', 'bandwagon', 'december', '”', 'among', 'entire', 'peacefully', 'wipe', 'protection', '“', 'turned', 'history', '29', 'families'], ['wounded', 'knee', 'day', 'heard', 'lakota', 'fratricide', 'backed', 'bandwagon', 'december', '”', 'among', 'entire', 'peacefully', 'wipe', 'protection', '“', 'turned', 'history', '29', 'families'], ['wounded'], ['wounded', 'knee'], [], ['wounded', 'knee', 'spirit', 'site', 'historic', 'proclaimed', 'significant', 'outside', 'forces'], ['wounded'], ['wounded', "kershaw's", 'knee', 'places', 'landmark', '1997', 'national'], [], ["laffan's"], [], [], [], ['wounded', 'surrendered', 'knee', 'standoff', '20', 'geography', 'protest', 'near', 'bureau', '54', '1', 'december', '52', '0', '29', 'within', 'cls', 'members', 'history', '98', '51', 'americans', 'may', 'ensued', '22'], [], [], ['wounded', 'knee', 'voice', 'lakota', 'trials', 'massacre', '3', 'people']]
TOP TOKENS [['nefarious', 'want'], ['upheaval', 'hiding', 'uncover', 'hide', 'geopolitical', 'fugitive', 'shall', 'expected', 'let', 'political', 'though', 'course', 'ignoring', 'midday', 'better', 'would', 'say', 'even', 'nature', 'asia', 'incursion', 'simply', 'cast', 'delimiting', 'delimitation', 'fall', 'east'], [], ['fearing'], ['chosen', 'dysfunctional', 'scapegoat', 'scapegoating', 'someone', 'scapegoated', 'massage', 'picks', 'need', 'merely', 'probably', 'another', 'others', 'mainly', 'else', 'anyone', 'person'], ['entangled', 'adversary', 'influence', 'seduced', 'prominent', 'city', 'blinding', 'principal', 'serve', 'stupor', 'instead', 'drowsiness', 'midst', 'one', 'rested', "lord's", 'nation', 'used', 'hilarities', 'women', 'churchianity', 'world', 'might'], [], [], ['respite', 'divert', 'past', 'damnation', 'valuable', 'way', 'presumably', 'one', 'conscience', 'politicised', 'weeks', 'else', 'avert', 'era', 'nothing', 'gets', 'exactly', 'behind', 'replenish', 'people', 'kind', 'life', 'population', 'step', 'leaders', 'values', 'acting', 'politics', 'position', 'political'], ['hideaway', 'oppress', '–', 'people'], ['dichelopa', 'epiphyas', 'haematephora'], ["winchelsea's", "rajah's", '1', 'novel', 'wild', 'stolen', 'story', "brisher's", 'treasure', 'elopement'], ['saved', 'romance', 'feud', 'slave', 'bravest', 'love', 'lost', 'halfbreeds', 'perversity', 'wooing', "seminole's", 'mother'], [], ['drama', 'wait', 'song'], ['released', 'entitled', 'album', 'november', '2018'], ['colspan', 'align', 'bgcolor', 'right', 'votes'], ['scheme', 'seeks', 'orchestrated', 'lure', 'eliminate', 'plan', 'overthrowing', 'personally', 'ambitious', 'situation'], [], ['reception']]
TOP TOKENS [['starch', 'starches', 'cotton', 'cls', 'native'], ['starch'], ['starch', 'labeling', 'derivatives', '8'], ['starch', 'starches', 'starch-containing', 'plants'], ['starch', 'cls', 'co', '36', 'supplied'], ['starch', 'starches', 'board', 'labeling'], ['starch', 'detergents'], ['starch', 'cls', '’', 'starchy'], ['starch', 'cls', 'parts', 'firm'], ['starches', 'starch', 'applications'], ['starch', 'starches', 'applications', 'sodium', 'time'], ['starch', 'fired', 'worked', 'reception', 'specific', 'office', 'would', 'main', 'consisting'], ['starch', '76'], ['starch', 'clothes', 'kitchen', 'applying', "person's", 'either', 'would'], ['starch', 'starches', 'modified', 'soluble', 'containing'], ['starch', 'starches', 'generally', 'lead', 'efficiencies'], ['starch', 'starchy', 'starches', 'thus'], ['starch', 'wisconsin–madison', 'also'], ['starch', 'resistant', 'may'], ['starch']]
TOP TOKENS [['zucchini', 'plant', 'grilled', 'fiber'], ['zucchini', 'zucchinis'], ['zucchini', 'though', 'hypertrophy'], ['zucchini', 'though', 'hypertrophy'], ['zucchini', 'gourds', 'removed', 'plants', 'pollinate'], ['zucchini', 'zucchinis', 'soil'], ['zucchini', 'zucchinis', 'afflict', '’'], ['zucchini'], ['zucchini', 'zucchinis'], ['zucchini', 'zucchinis'], ['zucchi'], ['zucchini', 'zucchinis', '1915-1986'], ['zucchini', "treats'zucchini'as", 'zucchinis', 'cooking', 'flavor'], ['zucchini'], ['zucchini', 'zucchinis', "zucchini's", 'zucchina', 'word', 'nearly', 'italian', 'ordinary'], ['zucchini', 'bread', 'seasons', 'zucca', 'dish', 'empire', 'italy', 'rice'], ["treats'zucchini'as", 'zucchini', 'word', 'cooking', 'soups'], ['zucchini', 'similarly-named', 'cakes', 'sometimes', 'meals', 'perennially', 'east'], ['zucchinis', 'zucchini', 'grow', 'occur', 'round', 'one'], ['zucchi', 'rome', 'etchings', '1', 'life', '1770', 'carlo', 'kauffman']]
TOP TOKENS [['kit', 'slippery', "the'slippery'part", 'elm', 'nutritious', "a'demulcent'or", 'essential', "an'emollient'agent", 'convalescent', 'herb', 'hand', 'heals', 'reputation', 'refers', 'action', 'substance'], [], [], ['sodium'], ['elm', 'water', 'cupboard'], ['slippery', 'elm', 'cress', 'ulcer', 'clover', 'properties', 'boils'], ['slippery', 'elm', 'psoriosis', '–', '1'], ['slimey'], ['cls', 'one'], [], [], [], [], [], [], [], [], [], [], []]

Processing features:  70%|███████   | 69/98 [33:09<13:19, 27.57s/it]

getting sample prompt for 24228
getting sample prompt for 24229
getting sample prompt for 24230
getting sample prompt for 24231
getting sample prompt for 24232
getting sample prompt for 24233
getting sample prompt for 24234
getting sample prompt for 24235
getting sample prompt for 24236
getting sample prompt for 24237
getting sample prompt for 24238
getting sample prompt for 24239
TOP TOKENS [['stands', 'stand', 'stood', 'radio', 'please', 'speak', 'someone', 'act', '·', "sister's", 'arguments', 'numeral'], ['stand', 'standing', 'stood', 'actually', 'stands', 'say'], ['standing', 'stands', 'stood', 'position', 'stand', 'standstander', 'see', 'verb'], ['stand', 'position', 'stood', 'theater', 'standing', 'men', '…'], ['stand', 'standing', 'stands', 'stood', 'father', 'word'], ['stand', 'stand-in', 'usage', '2004)she'], ['stands', 'standingˈstæn', 'standing', 'thing', 'ovation', 'good', 'person', 'use', 'went', 'word'], ['standing', 'stand', 'stands', 'something', 'someone'], ['standing', 'stands', 'position', 'stand', 'stood', 'act', 'thing', 'someone', 'year'], ['stand', 'behaviour', 'stood', 'stands', 'back'], ['upright', 'standings', 'standing', 'good'], ['stand', 'standing', 'based', 'otherwise', 'position', 'lenny', 'novel', 'frame', 'england', 'album', 'could'], ['stand'], ['stand', 'stood'], ['standing', 'act'], ['standing', 'tall'], ['standring', 'standing'], ['stand', 'stand-in', 'seinfeld'], ['stand', '1969', '1985', '1986', '1987', 'wexler', 'label', '1979', 'rosenfeld', '1993'], ['stand']]
TOP TOKENS [['blue', 'vast', 'gmc', 'risque', 'adhering'], ['blue', 'vast', 'gmc', 'risque', 'adhering'], ['“blue', 'blue', 'blue!”', 'blues'], ['blue', 'western', 'masculine', 'indigo'], ['blue', 'belonging', 'unclouded'], ['“blue”', 'blue', '“blue,”', 'modern'], ['blue', 'infidelity', 'perseverance', 'colours', 'superstition'], ['blue', 'never', 'quite'], ['blue', 'blues', 'exude', 'uncaring', 'exhilaration', 'color'], ['blue', 'blues', 'aquamarine'], ['entertainment', 'blue', 'joseph', 'radio'], ['blue', 'skye', 'w', 'born', 'american'], ['blue', 'horacio', 'massimo', 'robert', 'franco', 'history', 'carlos', 'gipi', 'guido', 'loisel', 'riccardo', 'roberto', '20,000', 'comics', 'mattioli', 'eric'], ['blue'], ['blue'], ['blue', 'novembre'], ['blue'], ['blue'], ['blue'], ['blue', 'orchestra']]
TOP TOKENS [['clerk', 'tasks', 'clerical', 'job'], ['clerk', 'clerks', 'office', 'prospective', 'students', 'cls'], ['clerk', "clerk's"], ['clerk', 'clerks'], ['clerk', 'clerks', 'clerkwikipedia', 'word', 'cognate', 'office', 'term', 'read', 'apportionment', 'dutch', 'fairly', 'specific'], ['clerk', 'clerks', 'consider', 'many', 'g'], ['clerks', 'clerk', 'stamina', 'enjoyable', 'jobs'], ['clerks', 'clerk', 'stamina', 'enjoyable', 'jobs'], ['clerks', '57', 'function', 'accounting', 'hourly'], ['clerks', '57', 'function', 'accounting', 'hourly'], ["clerk's", 'clerk', 'clerks', 'patent'], ['clerks', 'clerk', 'also', 'cls', 'word', 'scholar', 'κληρικος'], ['clerk', 'dugald', 'historic', 'e', 'gabrielle', 'baronets'], ['clerk', 'clerks', "clerk's", 'court', 'practices', 'also', 'today'], ['clerk'], ['clerk', 'disambiguation', '1800–1889'], ['clerk', 'politician'], ['clerk', 'spelt'], ['clerk', 'jurist'], ['clerk']]
TOP TOKENS [['bulgaria', 'bulgarian', 'sofia'], ['bulgarians', 'bulgaria', 'bulgarian', 'religious', 'either'], ['bulgaria', 'bulgarian', 'sofia', '1951'], ['bulgaria', 'bulgarian', 'sofia', 'bulgarians', '–', 'times'], ['bulgaria', "bulgaria's", 'bulgarian', 'sofia', 'danube'], ['bulgaria', 'bulgaria’s', 'see', 'bulgarian', 'sofia', '1.8', '24.8', '45.2', 'ages', '113.4'], ['bulgaria', 'bulgarian', 'diplomacy', 'years', 'sofia', '4'], ['bulgaria', 'long', 'bulgarian', '17,600m', 'sofia', '148km'], ['bulgarian', 'bulgaria', 'bulgarians', 'others', 'present', 'delicious', 'centuries', 'tomb'], ['bulgaria', 'bulgarian', 'government', 'companies', 'side', 'century', 'country', 'today'], ['bulgaria', 'disambiguation', 'fungus', 'teams'], ['bulgaria', 'favour'], ['bulgaria', 'bulgarian', '2023', 'centralisation', 'may'], ['bulgaria'], ['bulgaria', "bulgaria's"], ['bulgaria', 'bulgarians', 'centralisation', 'bulgarian', 'ethnic', 'sofia', '7th', 'elections', 'resumed', 'administrative'], ['bulgaria', 'bulgarian', "bulgaria's", 'population', 'sofia', 'enemy', '1918'], ['bulgaria'], ['bulgaria'], ['bulgaria']]
TOP TOKENS [['pheasants', 'pheasant'], ['pheasants', 'pheasants.pheasants', 'pheasant'], ['pheasant', 'pheasants'], ['pheasants', 'pheasant'], ['pheasants', 'pheasant'], ['pheasant', 'pheasants'], ['pheasants', 'pheasant'], ['pheasants', 'pheasant', 'year', 'foods'], ['pheasants', 'pheasant', 'come'], ['pheasants', 'pheasant', 'necked'], ['pheasant'], ['pheasant', 'exploratory', 'states'], ['pheasant', 'manage', 'scotstoun', 'u-boats', 'expense', 'war'], ['pheasant', 'bowled'], ['pheasant', 'pheasants', "wales'pheasant", 'p', 'c'], ['pheasant', 'watershed'], ['pheasant', "pheasant's", 'pheasants', "reeves's", 'phasianinae'], ['pheasant'], ['pheasant'], ['pheasant']]
TOP TOKENS [['current', 'term', 'yes'], ['current', 'word'], ['«current»', 'current', 'word'], ['current'], ['current', 'currents'], ['current', 'currents', 'primary'], ['current', '10ua'], ['current'], ['current', 'currents', 'cls', 'supply', 'many'], ['current', 'abbreviate', 'abbreviations'], ['current', 'currents'], ['current', 'us'], ['current', 'currents'], ['current', '1981'], ['current', 'currents'], ['current', 'columbus', 'sculptures'], ['current'], ['current', 'links', 'external', 'references', 'keyboards', 'singles'], ['current', 'currents'], ['current', 'currents', 'conductor', 'dc', 'megahertz', 'engineering']]
TOP TOKENS [['kuiper'], ['kuiper'], ['kuiper', 'detail', 'known', 'present', 'apart'], ['kuiper'], ['kuiper', 'kupier', 'said', 'aforementioned', 'neptunian', 'fact', 'number'], ['kuiper', 'edgeworth-kuiper', 'known', 'within'], ['kuiper', 'neptunian'], ['kuiper'], ['kuiper', 'seer', 'belt', 'around', 'gerard'], ['kuiper', 'ifa', 'arnett', 'edu', 'html'], ['kuiper', 'kuipers'], ['kuiper', 'kuipers', 'mission', 'houten', '996', '2017', 'carried', 'classification'], ['kuiper', 'onant', '30', 'catalogues', 'known', 'like'], ['nl:kuiper', 'kuiper', 'de:kuiper', "kuiper's", 'it:kuiper', 'kuipers', 'eells–kuiper', 'kuyper', 'fr:kuiper', 'es:kuiper', 'p', 'kuijpers', 'kuijper', 'kuypers', 'rienk'], ['kuiper', 'kuiperian', 'overlies'], ['kuiper', 'number', 'objects', 'belt'], ['kuiper', '2010', 'jeff', 'jensen', 'sturtevant', '20', 'contra'], ['kuiper', '1947', 'belt'], ['kuipers', 'kuiper', 'kuipers-rietberg', 'kuijpers', '1973', 'kuypers'], ['kuiper', 'tuitjenhorn', 'naked', 'ejnar', 'hertzsprung', 'alsos', '1949', 'de']]
TOP TOKENS [['phytophthora'], ['phytophthora'], ['phytophthora', 'et', 'sci', 'wf', 'ja', 'phytopathology', 'henslee', 'vol'], ['phytophthora'], ['phytophthora', 'lineages', 'barriers', 'heterothallic', 'settings'], ['phytophthora', 'ytophthora', 'phytopthora', 'p', 'species', 'conclusively'], ['phytophthora', 'ytophthora', 'phytopthora', 'p', 'species', 'conclusively'], ['phytophthora', 'phyto'], ['phytophthora', 'phytophthoras'], ['phytophthora', 'phytophthora’s', 'nevertheless', 'similarities'], ['phytophthora'], ['phytophthora'], ['phytophthora'], ['phytophthora', 'ytophthora'], ['phytophthora'], ['phytophthora'], ['phytophthora', 'homothallic', 'groups', 'p', 'burgess'], ['phytophthora', 'phytophthoras'], ['phytophthora', 'infestans', 'cls'], ['pleurophora']]
TOP TOKENS [['encrypt', 'decrypt', 'encrypted', 'decrypted', 'select'], ['encrypt', 'encrypt(1)||general', 'manual||encrypt(1', 'encrypted', 'encrypting'], ['encrypt', 'encrypted', 'decrypt', 'decrypted'], ['encrypt', 'encrypted', 'decrypts', 'want'], ['encrypt', '–encrypt', 'encrypted', 'decrypting', 'decrypt', 'truecrypt', 'emailofrecipient@blah.com'], ['encrypted', 'encrypt', 'decrypted', 'truecrypt'], ['encrypted', 'decrypted', 'decrypting', 'decrypt'], ['encrypted', 'encrypt', 'decryptor', 'decrypting', 'decrypt', 'encryptor', "encryptor's"], ['encrypt', 'encrypted', 'decrypting', 'decrypted', 'decryption', 'e', 'check', 'jasyptpbestringencryptioncli', '1waezye7cph7zxvtipsqsdhtx7kv'], ['encrypt', 'encrypted', 'decrypted', 'encrypts', '“', 'truecrypt', 'virtually', 'reads'], ['encrypted', 'desperate', 'fatally', 'people', 'sohag', 'fantastic', 'hossain', 'tortured', 'indranil', 'investigating', 'narcotics', '1', 'captured', 'need', 'programme'], ['encrypted', 'truecrypt', 'veracrypt', 'opening', '200', '1', '500', 'user', '327', '16'], ['encrypted', 'encrypting', 'encrypts'], ['encrypted', 'decryption', 'scrypt', 'bcrypt', 'mcrypt', 'cryptographic', '256-bit'], ['encrypt', 'dedicated', 'transformed', "earth's", 'steve', 'art', 'sci-fi', 'lapierre', 'liberate', 'cannot', 'byproduct', 'protects', 'survival', 'agrees', 'anton', 'cataclysmic', 'reich', 'refuse', 'upheaval', 'help', 'surrounding', 'lead', 'show'], ['encrypted', 'encrypting', 'encrypts', 'ecryptfs', 'encfs', 'derived', 'encryption', 'deprecated', 'extended'], ['dnscrypt', 'anonymized', 'dnscurve', 'dns'], ['encrypt', 'encrypted', 'veracrypt', 'truecrypt', "veracrypt's", 'also'], ['encrypt', 'encrypted', "let's", 'take', 'systems', 'identrust', 'included', 'authority', 'tasks', 'set', 'acknowledged', 'unencrypted', 'melinda', 'accomplish'], ['encrypting', 'decrypt', 'must', '26', 'fairly', 'holds', 'picking', 'common', 'divisible', 'zero']]
TOP TOKENS [['voting', 'voter', 'registration', 'ballot', 'vote', 'rights', 'act', 'right'], ['voting', 'voter', 'registration', 'ballot', 'vote', 'rights', 'act', 'right'], ['voting', 'voter', 'vote', 'act', 'ballot'], ['voting', 'vote', 'rights', 'right'], ['voting', 'voter', 'rights', 'registration', 'right', 'laws', 'cls', "center's", 'vote'], ['voting', 'rights', 'law', 'vote', 'act', 'right', 'voter'], ['voting', 'voter', 'rights', 'registration', 'act', 'vote'], ['voting', 'laws', 'vote', 'voter', 'ballot', 'restrictions', 'rights'], ['voting', 'rights', 'voter', 'registration'], ['voting', 'rights', 'vote', 'laws', 'bills', 'right', 'voter'], ['voting', 'voter', 'laws', 'registration', 'vote', 'act', 'rights'], ['voting', 'rights', 'voter', 'restrictions', 'registration', 'voters', 'vote', 'allowed', 'restrict', 'residents'], ['laws', 'voting', 'voter', 'vote', 'ballot', 'enacted', 'registered', 'rolls', 'registration'], ['voting', 'rights', 'right', 'vote', 'voter', 'laws', 'act', 'law', 'federal', 'amendment', '1945', 'intentional'], ['voting', 'laws', 'act', 'rights', 'registration', 'vote', 'voter', 'right'], ['voting', 'rights', 'right', 'vote'], ['voting', 'right', 'laws', 'voter', 'vote', 'rights', 'act', 'registration', 'enact', 'rolls'], ['voting', 'voter', 'cls', 'vote', 'right', 'registration'], ['voting', 'laws', 'voter', 'registration', 'ballot', 'rights'], ['voting', 'rights', 'laws', 'voter', 'vote', 'act', 'ability', 'registering']]
TOP TOKENS [['formatting', 'uaclips', 'com', '14', 'epigrams', 'one', 'ds0otq2cuhe', 'epigraphs', '2013', '6', 'epigram', '1'], ['answer', 'epigraph', 'serves', "for'how", 'sort', 'often', 'epigraphs', 'get'], ['epigraph', 'dedications', 'epigraphs', 'poke', 'gently', 'instance', '’', '2', 'prefaces', 'attributed'], ['hangnail', '“#.”', 'burroway', 'header', 'docx', 'using', '10-12', 'might', '“***”', 'literature', 'grammarphobe’s', 'al', 'philosophy', 'roman', 'epigraph'], ["poem's", 'epigraph', 'epigraphs', 'beginning', 'pretty', 'lovera€'], ['epigraph', "can't", 'many', 'epigraphs', 'com', 'placed', 'exception', 'using', 'providing', '11', 'beneath', 'usage'], ['beginning', 'chest', 'instance', 'epigraphs', 'piece', 'submitting', 'epigraph', 'question'], ['beginning', 'jimenez', 'stein', 'gives', 'solicit', 'used'], ['epigraphs', 'epigraph', 'use', 'instance', 'serves', 'one', 'begins', 'befitting'], ['epigrams', 'epigram', 'writing', 'part', 'content', 'epitaphs', 'proclaim', 'standpoint', 'criticism'], ['programming', 'epigram', 'books'], ['epigraphs', 'including', 'joseph', 'throughout', "dostoyevsky's", "conrad's", 'j', "herzl's", 'epigraph', 'summary', 'beginning', 'except', 'used', 'part', 'line', "eliot's"], ['beginning', 'epigram', 'epigraphs', 'epigraph', 'quotation', 'album'], ['early', "rock's", 'giving', 'several', 'gesture', '000', 'adams', 'finger', "league's", 'centerpiece', 'esquire', 'part', 'rodriguez', 'national', 'awards', 'zvereva', 'speedy', 'towards', 'effenberg', 'smith', 'made', 'however', 'graves', 'mcdowell', '250', 'prison', 'montoya', 'grande', 'feature'], ['words', 'expletives', 'refer', 'taglines', 'runtime', 'intro', 'snippets', 'phrases', 'content', 'employ', 'verdicts', 'usually', "video's", 'case', '1', 'narrate', 'post', '18'], ['amount', 'run', 'use', 'adamiecki', "model's", 'show', 'human', 'thesis', 'using', 'completed', 'indicators', 'like', '1985', 'adopting', 'also', 'extent', 'asking', 'computing', 'involved', 'searches', 'expressed', 'however', 'described', '–', 'better'], ['slashes', 'use', 'due', 'part', 'also', 'trying', 'perhaps', '12', 'difficult', 'would'], ['serifs', 'minims', 'readers', 'parts', 'part', 'words', 'top', 'line', 'initial', 'various', 'essentially'], ['italics', 'martini', 'bmw', 'gt1', 'began', 'quizzed', 'hill', 'mercedes', 'also', '1998', 'fia', 'one', 'racing', 'indicate'], ['12', '28', 'first', 'harrowingly', 'title', 'troubles', 'around', 'end', '31', "spears's", 'times', 'candid', '—', 'includes', 'march', '16', "kingdom's", "director's", 'well', '7', "neville's", 'rigors']]
TOP TOKENS [['frostbite', 'frostbitten', 'frostnip'], ['frostbite', 'cls', 'develop'], ['frostbite', 'frostbitten'], ['frostbite'], ['frostbite', 'frostbitten'], ['frostbite', 'frostbitten'], ['frostbite', 'frostbitten', 'cls'], ['frostbite'], ['frostbite', '38.3°c', 'loss'], ['frostbite', 'frostbitten', 'possible', 'cls'], ['frostbite', "frostbite's", 'frostbites', 'wanted', 'specialty'], ['frostbite', 'frostibe', 'frostbiten'], ['frostbite'], ['frostbite', 'feature', 'date', 'player'], ['frostbite', 'frostnip', 'uncomplicated', 'prevent', 'treating', 'people', 'hemorrhagic'], ['frostbite', 'using'], ['frostbite', 'foes', 'avoiding', 'links', 'piece', 'adds', 'little', 'help', 'pieces', 'thwarting', 'represented', 'awarded'], ['frostbite', 'utilizing', 'using', 'consoles', 'two', 'utilizes'], ['frostbite', 'frostnip', 'old'], ['frostbite']]

Processing features:  71%|███████▏  | 70/98 [33:38<13:09, 28.19s/it]

getting sample prompt forgetting sample prompt for 24241
 24240
getting sample prompt for 24242
getting sample prompt for 24243
getting sample prompt for 24244
getting sample prompt for 24245
getting sample prompt for 24246
getting sample prompt for 24247
getting sample prompt for 24248
getting sample prompt for 24249
getting sample prompt for 24250
getting sample prompt for 24251
TOP TOKENS [['greenwood'], ['greenwood', 'greenwoods', '“', '”', 'anglican', 'st', 'family', 'hall', '1539', 'ffarmour', 'theory'], ['greenwood', 'arrangement', 'greenwoodarkansas', 'inc', 'today', '’', 'equipment', 'city', 'representatives', 'marriage', 'timbers', 'make', '1961', '1892', 'special'], ['greenwood', 'browse', 'burton'], ['greenwood', 'burton', 'browse'], ['greenwood', 'day', 'old'], ['greenwood', 'area'], ['greenwood', 'books', 'years', 'decency', '1921'], ['greenwood', 'minister'], ['greenwood', 'william'], ['greenwood', 'greenwoods'], ['greenwood'], ['greenwood', 'indiana'], ['greenwood', 'site'], ['greenwood', 'county', 'area'], ['greenwood', '230'], ['greenwood', 'links', 'external', 'county'], ['greenwood', 'panhandle'], ['greenwood', 'county'], ['greenwood', 'level', 'states']]
TOP TOKENS [['eaton', "eaton's", 'william', '1849'], ['eaton', 'eatons', 'pinketham'], ['eaton', 'eatons', "eaton's", 'century', 'family'], ['eaton', 'town'], ['eaton', 'eatons', 'stockport', 'derbyshire', 'cls', 'cheshire', 'generations'], ['eaton', 'mcpherson', '1955', 'franchises'], ['eaton', 'eatons', 'david'], ['eatongenealogy', 'eaton', 'like', 'name', 'surnames', 'surname', 'william'], ['eaton', "eaton's"], ['eaton', 'cls', 'vicinity', 'tinctured', '1', '2', 'lands'], ['eaton', "eaton's", 'eatonia'], ['eaton'], ['eaton', "eaton's", '2007', 'primary', 'j', '2016', 'gen'], ['eaton', "eaton's", 'morrisville-eaton', 'syms-eaton', 'maine'], ['eaton', '1970s', 'american', 'b'], ['eaton', 'tarr–eaton', 'p', 'e', 'mylius–eaton', 'abel'], ['eaton'], ['eaton', 'races', 'ethnicity', 'incendiaries', 'asian', '1849', 'william', 'various'], ['eaton'], ["eaton's", 'eaton', 'store', 'branding']]
TOP TOKENS [['environment', 'db', 'reverb', 'reverberation', 'environments', 'level', 'khz'], ['loudspeakers', 'db', 'reverberation', 'hundredth', 'loudspeaker', 'reverberant', '4', 'experienced'], ['db', 'reverberance', 'acoustics', 'reverberation', 'environments', 'acoustic', 'sound', 'e'], ['db', 'reverberance', 'reverberation', 'fig'], ['reverberation', 'reverberant', 'db', 'sound', 'msec'], ['db', 'conduits', 'get', 'heard', 'reverberation', 'case'], ['waves', 'sound', 'reflecting', 'reverberation'], ['db', 'reverberation', 'instead', 'room', 'even', 'example'], ['world', 'db', 'crossovers', 'tweeter', 'slope', 'line'], ['reverberation', 'reverberant', '10s'], ['db', 'reverberation', 'level', 'reflected', 'inaudibility', 'space', 'proportional', 'heard', 'terms', 'sound', 'sounds', 'impact'], ['db', 'waves', 'reverberation', 'dispersive', 'coefficient', 'different', 'case', 'inject', 'acoustical', 'many', 'notably', 'm3', 'sound', 'diminishes', 'room', 'rooms'], ['db', 'reverberation', 'reverb', 'reflected', 'reverberant', 'spaces', 'indoor', 'environments'], ['reverberation', 'standardized', 'db', 'sound', 'reflecting', 'dw', 'standard', 'acoustics', 'rw', 'spaces', 'compensating'], ['loudspeaker', 'loudspeakers', 'subwoofer', 'woofer', 'mountings', 'tweeter', 'crossover', 'crossovers', 'audio'], ['reverberation', 'electromagnetic', 'waves', 'audible', 'sound', 'compared', 'period', 'acoustic', 'coefficient', 'minimizes', 'reflected'], ['environments', 'reverberation', 'reverb', 'echo', 'chambers', 'acoustics', 'reflected', 'reflection', 'room'], ['reverb', 'reverberation', 'environments', 'traveling', 'spaces', 'sound', 'reflectivity', 'logarithmically', 'v'], ['reverberation', 'sound', 'label', 'floor', 'environmental', 'reverb', 'echo', 'bunnymen', 'isaac', 'airs', 'network', 'elevators', 'artificially', 'tv', 'engages'], ['world', 'loudspeakers', 'entire', '“', 'upon', 'remains', 'radiate', 'less', 'fact', 'acoustically', 'amount', 'behaves', 'one']]
TOP TOKENS [['discover', 'choosing', 'unhealthy'], ['harmful', 'consume', 'every', 'unhealthy', 'eat', 'product', 'food'], ['enjoy', 'find', 'enjoying', 'optimal', 'getting', 'avoided', 'instantly', 'like', 'health'], ['consume', 'rid', 'enjoy', 'healthy', 'foods', 'get'], ['intake', 'ingesting', 'consumption', 'nibbli8ng', 'enjoy', 'much', 'lifestyle', 'calcium', 'choices', 'food'], ['moderation', 'risk', 'likely', 'binge', 'eventually', 'eating', 'addictive', 'food'], ['unhealthy', 'sabotage', 'stuff', 'beginning', 'wisely', 'disease', 'cure', 'diet', 'improving', 'long', 'start'], ['unhealthy', 'bad', 'stuff', 'eating', 'lots'], ['trying', 'healthily', 'looking', 'benefits', 'diet', 'eating', 'possible', 'less', 'eat', 'include', 'like', 'try', 'go'], ['forego', 'opt', 'foods', 'choose', 'vegetables', 'going'], ['pure', 'clean', 'purity'], ['undesirable', 'seditious', 'contents', 'possession', 'objectionable', 'fulfil'], ['15', 'ingested', 'ingesting', 'ng', '10', 'concentration', 'metabolite', 'metabolites', 'blood', 'least', 'saliva'], ['selection', 'found', 'intake', 'consumed', 'dietary', 'consume', 'consumption', 'individuals', 'vitamins'], [], ['accumulated', 'highest', 'also', 'ingestion', 'concentration', 'excretion', 'allyl', 'observed', 'dosing', 'elimination', 'caused'], ['satisfied', 'true', 'products'], ['goods', 'initial', 'posited'], ['complete', 'whole', 'neither', 'expense', 'valuable', 'spared', '119', 'every', 'addition', 'endeavour', 'still', 'exertion'], ['wasted', 'worth', 'bought', 'estimated']]
TOP TOKENS [['bingo'], ['bingo', 'word', 'many'], ['bingo', 'use'], ['bingo'], ['bingo'], ['“bingo!”', 'bingo', 'bingos'], ['bingo', 'homework', 'print-and-go'], ['bingo', 'his/her'], ['bingo', 'one'], ['bingo', 'bingos'], ['bingo', 'film', '1974', 'p'], ['bingo'], ['bingo'], ['bingo', 'international'], ['bingo', 'bingobisraagaguillékaligrikoangakoulgorinsâsapelosilgotanghinvillazékemzougou'], ['bingo', 'cls', 'triumphal', 'relaxed'], ['bingo'], ['bingo', 'bingos', 'however', 'game'], ['bingo', 'cls', 'every'], ['bingo', 'musical', 'jeeves', 'though']]
TOP TOKENS [['inclusive'], ['inclusive', 'inclusive[in', 'inclusivelate', 'great', '10', 'superlative'], ['inclusive', 'incorporating', 'existing', 'create', 'planning', '”'], ['inclusive', 'education', 'incorporating', 'teaching'], ['inclusive', 'inclusiveness', 'elements', 'highly', 'inclusion', 'growth', '”', 'hindering', 'comprehensive', 'aspect', '“'], ['inclusive', 'getting', 'innovator', 'contextualize', 'specific', 'full', 'innovators'], ['inclusive', 'inclusion', 'implementing', 'method', 'unwelcome', 'excluded', 'toward', 'rather', 'face'], ['inclusive', 'considered', 'measure', 'growth', '“', 'meant'], ['inclusive', 'enable', 'leader', 'poweryourimpact.com/16'], ['inclusive', 'operationalizing', 'education', 'inclusion', 'define', 'pedagogy', "teachers'conceptualizations", 'classrooms', 'first', 'term'], ['inclusive', 'non-descendants'], ['inclusiveness—especially', 'inclusive', 'growth', 'direct'], ['inclusive'], ['inclusive', 'inclusion', 'interest', 'founded', 'structuring', 'way', 'management', 'building', 'cls', 'trade', 'public', 'encapsulated', 'one', 'process', 'related'], ['inclusive', 'several', 'inclusion', 'practices', 'identified', 'location', 'desired', 'public', 'however', 'including'], ['inclusive', 'inclusion', 'emergence', 'bringing', 'historically', 'disabilities'], ['all-inclusive', 'inclusive'], ['inclusive', 'certain', 'called', 'accepted', '2009', 'hegemonic'], ['inclusive', 'hand', 'case', 'also', 'might', 'use', 'would', 'ʔuush', 'simply', 'conversely', 'faces', 'exclusive', 'additional'], ['inclusive', 'regulation', 'incorporate', 'within', 'business', 'applying', 'overriding', 'types', 'framework', 'impact', 'wishing']]
TOP TOKENS [['peristaltic', 'primers', 'different', 'minute'], ['extensive', 'clang', 'weverything', 'also', 'sequential', 'o2', 'one', 'native', 'expressive', 'blas', "nsc's", 'gf', 'identical', 'module', 'ones', 'different', 'rudimentary', 'ofast', 'lmkl', 'exe', 'o1'], ['busy', 'message', 'send'], ['peristaltic', 'channels', 'duncan', 'acad', 'oscillatory', 'p', 'e', 'v', '187', 'diseased', '’', 'ahrar', 'u', 'oscillator', 'sci', 'proc', 'natl', '190', 'hwang', 'selected', 'n', '18109', 'part', 'logically'], ['busy', 'message', 'redial', 'button', 'send', 'intervals', 'different', 'repeatedly', 'another'], ['similarly', 'gazillion', 'large', 'software', 'clang', 'greatle', "clang's", 'us', 'vs', 'number', 'hardware', 'particular', 'tool', 'would', 'first'], ['similarly', 'gazillion', 'large', 'software', 'clang', 'greatle', "clang's", 'us', 'vs', 'number', 'hardware', 'particular', 'tool', 'would', 'first'], ['peristaltic', 'coordinated', 'peristalsis', 'rhythmic', 'ureters', 'rollers', 'tract', 'pumps', 'duct', 'finger', 'arterioles.flow'], ['interval', 'intervals', 'different', 'peristaltic', 'tract', 'peristalsis', 'cyclical', 'homogeneity', 'variable', 'diaphragm', 'one', 'metering', 'may', 'pulp', 'along', 'variation', 'rollers', 'gastrointestinal', 'similar', 'allows', 'tubing', 'another', 'vary'], ['clang', 'explicit', 'flag', 'per'], ['dynamic', 'optionally', 'consensus', 'number', 'evm', 'transaction', 'protocol', 'options', 'verifiable', 'one', 'decentralized', 'swapping', 'predefined', 'variety', 'ursa', 'known', 'interacts', 'time'], ['peristaltic', 'washing', 'dishwasher', 'nachos', 'ex', 'hydroponic', 'dosers', 'autoanalyzer', 'printing'], ["new'bridges'supercomputer", 'counterfactual', 'one', 'libratus', 'according', "special'heads", '3', "libratus'creators", 'million', "means'balanced", 'supercomputing', 'center', 'nominal', 'subteams', 'sequence', "nicknamed'the", "up'rules", 'strategy', '50', 'communications'], ['several', 'different', 'clang', 'standard', 'strong', 'siamese', 'symptoms', 'sometimes', 'stand', 'balls', "patient's", "word'clownfish", 'symptom', 'also', 'may', 'therefore', "clown'to'halloween", 'chaining', 'referred'], ['5', '891', 'e', 'g', 'eventually', 'decimal', '55', 'number', '89155020', '020', 'true', 'added', 'various', 'basis', 'consisted', 'threaded'], ['stream'], ['various'], ['metallic', 'robot', 'steampunk', 'knocking', 'deck-building', 'building', 'sound', 'webcomic', 'game', 'meaning', 'video', 'genius', 'clank', 'united', 'onomatopoeia'], ['peristalsis', 'peristaltic', '5222880', '249285', 'tract', 'united', 'states', 'gastrointestinal', 'j', 'u', 'cardiopulmonary', 'transfusions', 'may', 'additionally'], ['peristaltic', 'among', 'microfluidic', 'fluid', 'others', 'constant', 'due', 'lead', 'analytes', 'reason', 'amount', 'thickness', 'tubing']]
TOP TOKENS [['plaid', 'mid', 'countercultural', 'began', 'white', 'fashion', 'pop', 'late', 'women', 'flannel', 'gain', 'lumberjacks', 'may', 'wear'], ['plaid', 'huge', 'nancymangano', 'blankets', 'mangano', 'fashion', 'nancymmangano', 'today'], ['plaid', 'blankets', 'y4', 'wool', 'woven', 'ancient', 'today'], ['plaid', 'country', 'folk', 'punk', 'disco', 'sneak', 'dated', 'outdoorsmen', 'seemed', 'make', 'today'], ['ranchers', 'plaid', 'plaids', 'western', 'spanish', 'rebel', 'world', 'mexican', 'blanket', 'classic', 'kilt', 'became'], ['plaids', 'plaid', 'scotivum', 'still', 'cool', 'countryside', 'mccluskey', 'anglophiles', 'coigach', 'knickknacks', 'far', 'tartan', 'yellow', 'flannel', 'patterns', 'berkley', 'camouflage', 'classic', 'outdoor', 'clan', 'green', 'scotland', 'diagonal', '1854', 'woolrich', 'canadian'], ['country', 'english', '1962', 'many', 'owlpen', 'crohan', 'clive', 'limelight', "owlpen's", 'avray', 'another', 'members'], ['plaid', 'windowpane', 'plaids', 'mccluskey', 'gingham', 'highlander', 'kilt', 'india', 'indians', 'sioux', 'cheyenne', 'canada', 'countries', 'handwoven', 'scottish', 'woven', 'panes', 'chennai', 'wool'], ['web', 'spanish', 'time', 'went', 'involved', 'countries', '’', 'story', 'political', 'secrets', 'precede', 'book', 'even', 'note', 'less', 'communist', 'sometimes', 'war', 'another', 'tendency'], ['compact', 'historic', 'diversion', 'great', '7', 'water', "compact's", 'joyce', 'p', 'lakes', '6', 'chicago', 'griggs', 'massive', 'five', 'first', 'controversy', 'wars'], ['8th', 'hawkeyes', '4th', '4', '9', 'ppg', 'game', 'wisconsin', '105', '12', 'player', '8', 'kaufmann', '1', 'team', 'milwaukee', '3'], ['plaid', 'td', 'c', '6', 'consent', 'deferred', 'alfred', '7', '4', 'disclosing', '12', '3', 'party', '5', 'threat', 'united', 'sum', 'users'], ['plaid', 'reachy', 'jaroc', "plaid's", 'mvuki', 'goldfrapp', 'tekkonkinkreet', 'handley', 'uk', '2006', 'bfi', 'compilation', '26', 'first', 'ambient', 'elizabeth', 'june', 'date', 'waterloo', 'many', 'sometimes', '1', '2005', 'july', '2009', 'english'], ['player', 'conner', 'chicago', '22', 'league', 'wisconsin', 'badgers', 'team', 'signed', "house's", 'madison', 'goosens', 'college', 'fc', 'day', 'role', 'players', '4', 'fire', 'connor', 'championship', 'played', "men's", "chicago's", 'later', 'history', 'also', 'made', 'club', 'total', '18th', 'coming'], ['iowa', '7', 'kentucky', 'hawkeyes', '1', 'wildcats', 'left', '4', "men's", '5', 'colspan', '474', '8', 'style'], ['ncaa', 'shutout', '4', 'teams', 'team', 'lead', 'stymie', 'country', 'big', 'tournament', 'helped', '–', 'one', 'american', 'small', 'basis', 'malinski', "men's", 'overall', 'seed', 'points'], ['hedaya', 'threat', 'moss-bachrach', '8', 'dan', 'holmgren', 'digital', 'lada', 'mccaffrey', 'platforms', 'oksana', '10'], ['city', 'spill', 'punk', 'take', 'deja', '2006', 'purevolume.com', 'canvas', 'vroom', '2005', 'rory', 'dinner', 'oingo', 'kind', 'early', 'dcide', 'good', 'nationally', 'one', "could've", 'fame'], ['popular', 'meadowlark', "meadowlark's", 'nightstorm', 'eyes', 'wide', 'indie', 'pop', '3', 'glastonbury', '10', 'february', 'british', 'november', '2023', '26', 'may', 'postcards', 'june', '12', 'london', '2015', 'march', "band's", 'five', 'first', 'introducing', 'courtyard', 'came'], ['uefa', 'glentoran', 'c', '7', 'glens', '2007', '07', 'intertoto', 'premier', 'pre', 'k', 'brandywell', 'glenavon', 'velbazhd', 'august', 'fc', 'signed', '8', '19', 'pfc', 'july', 'top', "derry's", 'f', 'derry', '4', 'highest', "glentoran's", 'competitions', '3', 'gretna']]
TOP TOKENS [['vagabond', 'wasted', 'life', 'becoming', 'thrown', 'flits', 'away', 'horrid', 'flattering', 'bacchanalian', 'revelries', 'cast', 'delight', 'wreck', 'source', 'fate', 'misspent', 'ambition', 'admonished', 'visit', 'time', 'foundered', 'terrific', 'midnight', 'sought', 'days', 'indifferent', 'nest'], ['lifestyle', 'status', 'live', 'living', 'positioned', 'time', 'life', 'become', 'less', 'spending', 'away', 'way', 'wealth', 'one', 'ended', 'like', 'anything', 'else', 'successful', 'person', 'loss'], ['status', 'lifestyle', 'spent', 'life', 'provide', 'things', 'obtained', 'position', 'family', 'bought', 'stay', '’', 'examine', 'direction', 'lonely'], ['flattering', 'aspired', 'dignified', 'position', 'favorable', 'vagabond', 'occupied', 'pit', 'respectability', 'whose', 'endowed', 'aspect', 'prospects', 'countenance', 'manhood', 'age', 'risen', 'forlorn', 'opportunities', 'premature', 'wealth', 'positions', 'bright', 'earthly', 'one', 'honors', 'morning', 'spirited', 'old', 'persuasive'], ['lifestyles', 'gentlemen', 'gentry', 'wealthy', 'status', 'living', 'life', 'position', 'step', 'expecting', 'new', 'follow', 'away', 'men', 'successful', 'failed', 'provide', 'pleasant', 'social', 'post'], ['misspent', 'life', 'riches', 'sorts', 'story', 'period', 'world', 'vanity', 'behind', 'pursuing', 'traveling', 'tells', 'he’d', 'model', 'convalescence', 'youth', 'example'], ['gentlewomen', 'lifestyle', '‘', 'status', 'category', 'middling', 'modestly', 'officeholders', 'gentility', 'locations', 'sons', 'indicator', 'individuals', 'considered', 'lineage', 'title', 'end', 'wealthy', 'lives', 'estates'], ['gentlewomen', 'lifestyle', '‘', 'status', 'category', 'middling', 'modestly', 'officeholders', 'gentility', 'locations', 'sons', 'indicator', 'individuals', 'considered', 'lineage', 'title', 'end', 'wealthy', 'lives', 'estates'], ['well', 'joyless', 'powerful', 'thrown', 'whims', 'vanity', 'men', 'optimism', 'porcelain', '“', 'creature', 'life', 'avoiding', 'like', 'stupor', 'materialistic', 'aside', 'disheartened', 'pursuits', 'derided', 'evening', 'money', 'let', 'feat'], ['attention', 'entitlement', 'asinine', 'dwarfs', 'narcissistic', 'center', 'away', 'nearly', 'relishing', 'go', 'gives', 'responsible', 'life', 'spotlight', 'favor', 'full', 'walk', '‘', 'nothing', 'something', 'oh'], ['successful', 'insignificant', "women's", 'heeled', 'feel', 'menial', 'remarriage', 'men', 'mother', 'outlook', 'life', 'outcasts', 'sons', 'boast', 'losers', 'citizen', 'job', 'shown', 'chronically', 'unemployed', "normy's", 'mothers', 'thought', 'women'], [], ['altruistic', 'subservience', 'becomes', 'widower', "virginia's", 'empty', 'life', 'housework', 'vicarious', 'mother', 'women', 'absolutely', 'living', 'increasingly', 'live', 'fate', 'flown', 'widow', 'man', 'forties', 'leads', 'worthwhile', 'concession', 'newspaper', 'usefulness', 'neglecting', 'leaves', 'provide'], ['protagonist', 'mirthless', 'bereaved', 'margarita', 'career', "protagonist's", 'premise', 'film', 'moping', 'levieva', 'around', 'stand', 'dispiriting', 'unhappy', 'leonardo', 'budding', 'expanded', 'jennifer', 'absence', 'mc', 'passive', 'loved', 'juan', 'cls', 'standing', 'club', 'love', 'drama', 'justine', 'mudge', 'adam', 'moves', 'finding'], ['notability', 'achieved', 'list', 'prominent', 'figures'], ['sluttiest', 'castillo', 'cristobal', 'slut', 'film', 'ex-boyfriend', 'world', 'wanders', 'francisco', 'nicolás', 'independent', 'films', 'directorial', 'francisca', 'festival', 'bárbara', 'failure', "tania's", 'valentina', 'chilean', 'theaters', 'comedy', 'set', 'characters', 'international', 'sexual', 'synopsis'], ['observer', 'york', 'writers', 'biographies'], ['woman', 'ranking', 'equivalents', 'appeared', 'rankless', 'servant', 'funeral', 'life', "athena's", 'yuzuriha', 'soldiers', 'following', 'ivan', 'empty', 'relief', 'adaptation', 'weak', 'family', "hades'army", 'mephistopheles', 'characters', 'crane', "fyodor's", "pandora's", 'wear', 'featured'], ['aged', 'basis', 'decayed', 'impotent', 'vagabonds', 'act', 'provide', 'beggars', 'vagabonds.”', 'also', 'formed', 'rogues'], ['flattery', 'fame', 'worldly', 'flatterers', 'around', 'advisors', 'possessions', 'unremarked', 'life', 'flatterer', 'positions', "one's", 'story', 'men', 'people', 'hungary', 'considers', 'vincent', 'role', 'lukewarm', 'way', 'let', 'received']]

Processing features:  72%|███████▏  | 71/98 [34:08<12:50, 28.55s/it]

getting sample prompt forgetting sample prompt for 24253
 24252
getting sample prompt for 24254
getting sample prompt for 24255
getting sample prompt for 24256
getting sample prompt for 24257
getting sample prompt for 24258
getting sample prompt for 24259
getting sample prompt for 24260
getting sample prompt for 24261
getting sample prompt for 24262
getting sample prompt for 24263
TOP TOKENS [['mapito', 'beginning', 'ec', 'compared', 'unpacked', 'using', 'use', '3', '’'], ['mapp', 'helps', 'results', 'use', '’', 'model', 'process', 'brings', 'uses', 'based'], ['mapuche', 'mapu', 'anymore', 'strongly', 'chubut', 'live', 'defeated', 'arrived', 'mastered', 'long'], ['mapuche'], ['mapuche', 'mapu', '‘', '“', '’', '”', 'well'], ['mapudungun', 'mapuche', 'mapu', 'mapuche-written', 'mapuzugun', 'language', 'mapudungu', 'earth', 'regularly'], ['mapuche', 'mapudungun', 'communities', 'language', 'civilized', 'center', 'way'], ['mapuche', 'mapu', 'elements', 'encumbered', 'see', 'emptiness', 'fertilized', 'mixed', 'coexist', 'never', 'without', '”', 'next', 'china', 'abyss'], ['mapp', 'officials', '’', 'one', 'improving', 'use', 'process'], ['mapp', 'safety', 'parts', 'use', 'propane', 'mapd', 'propylene'], ['mapo', '马坡地区'], ['mapp'], ['maplins'], ['mapuana', 'mapu'], ['mapple'], ['mapo', 'mapo-gu'], ['mapa', 'mappa', 'may'], ['mappa', 'disambiguation', 'ha-mapah', 'mapa'], ['mapo', '2021'], ['mapp']]
TOP TOKENS [['brent', 'cargoes', 'events', 'oils', 'states', 'crude'], ['brent', 'sulfur', 'crude'], ['brent', 'company', 'crude', 'mean'], ['brent', 'crude', 'norway'], ['brentanian', 'brentano'], ['brent', 'brenta', 'nearby'], ['brentano', 'explicate', 'bettina'], ['brent', '“', 'crude', 'oilfield', 'b'], ['brentano', 'brentano’s', 'extraordinarily', 'ehrenbreitstein', 'bettina', 'braven', 'romanticism', 'prags', 'poets', 'schönen', 'later', 'six', 'knaben'], ['brentwood', 'lessons'], ['brent', "brent's", 'georgia'], ['brenta', 'gemonio'], ['brenta'], ['brenta', 'italy', 'two'], ['brenton', "brenton's", 'brent', "brent's", 'cls', '1671', 'jr'], ['brentz', 'red', 'major', 'living', 'boston'], ['brent', 'brentwood', 'brentwood-darlington', 'ongar', 'high'], ['brent'], ['brentidae', 'brentus'], ['brent']]
TOP TOKENS [['technology', 'investigation', 'counterproductive', 'tech', 'objectives', 'services', 'purpose', 'technological', '“', 'endeavors', 'society'], ['technology', '”', 'moving', 'friendly', 'level', 'etc', 'technologies', 'clothing', 'medical'], ['technology', '”', 'level', 'friendly', 'technologies', '1922', 'etc'], ['technology', 'advances', 'technical', 'art', 'age', 'machines', 'technologies', 'silex', 'cls', 'technological', 'nature', 'objects'], ['investigation', 'technology', 'factories', 'objectives', 'things', 'workings'], ['purposes', 'technology', 'animals', 'applications', 'instruments', 'used', 'mean', 'technologically', 'temperature'], ['problem', 'technology', 'craft', 'time', 'τεχνολογια', 'technique', 'hand', 'however', 'generally'], ['technology', 'technologies', 'techne', 'industries', 'another', 'ai'], ['“technology”', 'technology'], ['technology', 'give', 'positivity', 'technological', 'materials', 'like', 'clients', 'tasks'], ['humans'], ['technology', 'tech', 'technical'], ['technology'], ['technologies', 'technology', 'voice-disabled'], ['technology', 'arts'], ["technology's", 'technology', 'electronic', 'taken', 'credits', 'romesh', 'release', 'stay'], ['technology'], ['technology', 'technologies', 'forward', 'century', 'advances', 'elements', 'technical', 'progress', 'science', 'effective'], ['technology', 'impassive', 'kokhaev', 'roman', 'yudov'], ['technology', 'sci-tech', 'tech', 'science', 'scitech']]
TOP TOKENS [['atm'], ['atm', 'atms'], ['atm'], ['atm', '“', 'acronym', 'nothing', '”', 'cls'], ['atm', 'atms', 'cls', 'transactions'], ['“atm”', 'atm', 'mean'], ['atm', 'asynchronous'], ['atm', 'atms', 'cls'], ['atm', 'characteristics'], ['atm', 'cls', 'cable', 'one'], ['atm', 'cls', 'kod', 'fa', 'tasmania'], ['atman', 'atma', 'atme'], ['atmia', 'atm', 'atmoa', 'atms', 'conflict'], ['atmp', 'chelator'], ['atma'], ['atmos', 'fx-atmos', '6502-based', 'vitouš'], [], ['atma'], ['atmcs', 'atmc', 'atm', 'atms'], ['atm⁵', 'atm5', 'atm', 'atms', '2005']]
TOP TOKENS [['tired', 'tiredness', 'cls', 'feeling'], ['tired', '‘', 'cls', 'circumstances', 'felt', 'point', 'always'], ['tired', 'tired?”', 'tiredness', 'always', 'persistently', 'constantly'], ['tired', 'exhausted', 'exhaustion', 'word', 'weary', 'something'], ['tired', 'tiredness', 'feel', 'feeling', 'one', 'also', 'exhaustion'], ['tiredness', 'tired', 'feel', 'always', 'lives', 'though'], ['tired', 'tiredness', 'exhausted', 'feel', 'cls'], ['tired', 'exhausted', 'feeling', 'feel'], ['tiredness', 'tired', 'quite'], ['tired', 'exhausted', 'tiredness', 'feel', 'become', 'completely'], ['tired'], ['tired', 'album'], ['tired'], ['tired'], ['tired'], ['tired'], ['tired'], ['tired'], ['tired', 'song', 'levinson', 'songs', 'recordings'], ['tired', "gates's", 'song', '2014']]
TOP TOKENS [['swindon', 'hill', 'population', 'town', 'horses', '742', "said'the", 'fair', 'berkshire'], ['swindon', 'highest', 'hill', 'hub', 'old', 'text', 'prices', 'country', 'one'], ['prices', 'swindon', 'highest', 'sep'], ['swindon', 'continued', 'grow', 'century', 'also', 'built', 'road', '54', 'rapidly', '1899', 'years', '1888', 'became', 'borough'], ['town', 'luton', 'ages', 'population', 'wooden', "mary's", 'older', 'kingdom', 'church', 'world', 'railways', 'united', 'farmhouses'], ['luton', 'medieval', 'town', "luton's", 'ages', 'castle', 'london', 'skirmishes', 'population', 'people', "a'hospital'where", 'street', "loitone'probably", 'watermills'], ['swindon', 'london', 'early', 'areas', "to'overspill'towns", 'outpatients', "1950's"], ['stateless', '’', 'kenton', 'wallowed', 'gastronomic', '…', 'action', 'p', 'englishman', 'mother', 'happen', 'bodily', 'craved', 'undertakers', 'flecked', 'living', 'neither', 'dominate', 'alluded', 'things', 'go', 'inquisitive', 'eyes', 'many', '–', 'detective', 'came'], ['swindon', 'town', 'old', 'railway', 'hall'], ['wembley', 'stadium', 'raving', 'usa', 'played', 'station', 'show', 'todd', 'local', 'slash', 'every', 'trent', '2015'], ['swindon', 'parliament', 'united', 'uk', 'station', 'town', 'kingdom', 'team', 'f.c', 'gloucestershire', 'disambiguation'], ['leinster', 'hurlers', 'all-ireland', 'intermediate', 'level', 'irish', 'championship', 'c', 'walsh', '2019'], ['swindon', "swindon's", 'sports', 'francome', 'west', 'samuel', 'peter', 'european', '1974', 'time', 'john', 'welterweight', 'lewisham', 'melbourne', 'writer', 'actor'], ['swindon', '1987', 'irish', '159', 'town', 'swindonweb', "o'sullivan", 'bridgeman', 'tv', 'hardcover', 'host', 'radio', 'paperback', '96', 'atkinson', 'amberley', '2019', 'ltd'], ['irish', 'hurler', 'walsh', 'gaelic', 'galway', 'born', 'kilkenny'], ['kenton', 'st', 'sanders', 'bonin'], ['borough', 'swindon', 'lawns', 'elections', '1970s', 'town', 'walcot', 'politics', 'mp'], ['swindon', "swindon's", 'scandinavian', 'hill', 'old', 'lawn', "sweyn's", 'walcot', 'hastings', 'swain', 'sven', 'sweyn', 'man', 'part', 'manors', 'english', '14s', 'westlecot', 'town'], ['walsh', 'television', 'american', 'disambiguation', 'hurler', '1913–1975', 'videogame', '1911–2000', 'born', '1923–2014', 'welsh'], ['swindon', 'irish', 'west', 'william', 'steve', "o'sullivan", "swindon's", 'author', 'terry', 'scottish', 'midland', 'mayor', 'tv', 'member', 'television', "2's", 'street', '–', 'born', 'burnley', 'raised', '1914', 'wright', 'co', 'suffragette', 'london']]
TOP TOKENS [[], ['things', 'nil', 'containing', 'also', 'whole', 'entire', 'anything', 'multiple', 'two', 'contents', 'returns', 'php', 'include', 'via', 'geeksforgeeks', 'get', 'error', 'current', 'getwd()(dir', 'date', 'files', 'contribute.geeksforgeeks.org', 'one', 'directory/folder', 'timezones', 'firstname.lastname@example.org', 'various'], ['finitely', 'every', 'many', 'ever-expanding', 'left', '1/sin[z', 'let’s', 'z_0', 'analysis', 'first'], ['–', 'music', 'galleries', 'p', 'giveaways', 'pickaway', 'gmail', 'well', 'demos', 'potterylovers', '35', 'zanesvillejaycees', 'school', 'potteryloversinfo', 'jul', 'authentic', 'across', 'also', 'participating', '3636', 'sat', 'food', 'wildandwonderfulcrafts', 'sun', 'www', 'fri', 'many', 'artcoz', 'complimentary'], ['pretty', 'everything', 'little', '’', 'lot', '…', 'much', 'seriously', '”', 'problem', 'gothistory', 'magazines', 'midwestmaize', 'said', 'likes', 'source', 'cool', 'textbooks'], ['ways', '’', 'syria', 'september', 'going', 'silver', '“', 'well', 'change', '”'], ['lots', '29', 'like', '27', '28'], [], [], ['1', 'stuff', 'plus', 'used', 'got', 'questions', 'given', "the'songplayer'context", "subs'system", "code's", "song,'player", "perl's", 'code', 'songplayer'], ['due', 'rock', 'colombo-badulla', 'numerous', 'named', '2,000-year-old', "adam's", 'temple', 'covered', 'one', 'falls', 'pyramidal-shaped', 'bambaragala', 'peak', 'located', 'bridge', 'contains', 'ela', 'road', '1918', 'waterfall', 'beragala-hali', 'hill', 'station', 'town', 'fauna', 'line'], ['seven', 'bacon', 'entrees', 'wines', 'desserts', 'frites', 'six', 'related', 'include', 'bar', 'includes', 'main', 'puree', '2017', 'least', '8', 'cheese', 'garnished', 'mustard', 'beef', 'chicken', 'mussels', 'also', 'one'], ['may', 'disambiguation', 'one'], ['game', 'surname', 'given', 'card', 'known', 'name', 'including', 'versions', 'heinrich', 'crater', 'see', 'people', 'government'], ['crater', '1861', 'surname', 'given', 'virgin', 'king', 'ludwik', 'name', 'including', 'entertainment', "children's", 'arts', 'canal', 'ship', 'abandoned', 'cartoon', 'beyond'], ["america's", "mtv's", 'd’umo', '2', 'crew', 'ballot', 'singer-songwriters', 'american', 'chaz', 'robinson', '2012', '2014', 'plus', "broadway's", 'external', 'references', '21st-century', '2016', '2018', 'received', 'vol', 'december'], ['2', 'placeholder', '4', 'place', 'cars', 'things', 'twenty', '1', '18', 'hotels', 'eight', 'one', 'choices', 'included', 'number', '1k', '9k', 'mystery', "ea's", 'life', 'less', 'worlds', 'ea', 'see', 'ended', 'came', 'top', '2020', 'deemed', 'would', '2k'], ['spaces', 'colleges', 'various', 'korea', 'well', 'ufan', 'studios', 'cities', 'anniversary', '30th', 'galleries', '2004', 'yan', 'polignac', 'uprising', 'gallery', 'gwangju', 'biennale'], ['followed', 'two', 'following', "author's", 'mystery', "radio's", "fool's", "gullible's", 'due', 'also', 'style', 'along', 'way', '01', "apm's", 'every', 'peters', '1979', 'work', 'friends', 'places', 'forty', 'woes', 'life'], ['four', 'later', 'many', "village's", 'treed', 'much', 'doubling', 'elveley', 'associated', 'along', 'haltemprice', 'period', 'land', 'area', 'two', 'drive', 'due', 'periods']]
TOP TOKENS [['dementia'], ['dementia'], ['dementia', 'people'], ['dementia'], ['dementia'], ['dementia', 'people'], ['dementia', 'persons'], ['dementia'], ['dementia', "dementia's", 'one', 'patient'], ['dementia', "dementia's", 'one', 'patient'], ['dementia'], ['dementia', 'someone', 'barrier', 'people', 'individuals', 'live', 'since', 'clothing'], ['dementia', 'pamela'], ['dementia', '2012', "minister's", 'fund', 'people', 'national'], ['dementia', 'living', 'people', 'account'], ['dementia', 'work', 'experiences', 'uk', 'cls', 'living'], ['dementia', 'people', "patient's", 'saving', 'used', 'fed'], ['dementia', 'someone', 'live', 'engaging', 'person'], ['dementia', 'developed'], ['dementia', 'ballarat', 'regency', 'people', 'science', 'national', 'fore', "who's", 'tafe']]
TOP TOKENS [['lost', 'consider', 'contexts', 'kurson', 'colored', 'connote', 'language', 'abilities', 'concerning'], ['language', 'thought', 'sexist', 'way', 'famously', 'fascinatingly', 'granted', 'eliminated', 'four', 'closely', 'might', 'take'], ['falsely', 'common', 'authenticity', 'although', 'may', 'evolved', 'language', 'distancing', 'deep', 'deepest', 'grace', 'destined', 'sense', 'brutalization', 'r', 'time', 'obliterated'], ['shadows', 'e'], ['first', '”', 'reminded', 'experts', 'language', 'third', 'somehow'], ['“', 'language', 'stated', 'difficult', 'elucidate', 'exist'], ['–', 'see', 'sustain', 'moral', 'clear', 'language', '1985', 'got', 'opposites', '”', '61', '52', 'consider', '17'], ['truth', 'revealed', 'use', 'background', 'magnified', 'mystery', 'always', 'language', 'saying', 'singularity'], ['truth', 'revealed', 'use', 'background', 'magnified', 'mystery', 'always', 'language', 'saying', 'singularity'], ['descriptive', '–', 'true', 'judgements', 'use', 'describes', 'example', 'language', 'good'], ['bad', 'language', 'specific', 'avant', 'album', 'readings', 'communication', 'system', 'song', 'book', 'using'], ['love'], ['conversation', 'schegloff', '1925', 'b', 'many', 'century', 'external', 'twenty-fourth', 'review', 'language', "lees's", 'links', 'detail', 'positive', 'emanuel', 'continues', 'assessment', 'editorship', 'using', 'publication', '1.899', 'large', 'appear'], ['meaningless', 'included', 'imaginary', 'concision', 'often', 'generally', 'use', 'sometimes', 'precision', 'used', 'energy', 'example', 'one', 'know', 'different', 'completely', 'language', 'unambiguity', 'equivalence'], ['1914', 'also', 'references', 'links', 'new', 'see', 'henry', 'external'], ['love', '2014', 'vielle', 'swedish', 'kärlekens', 'welsman', 'språk', 'john', 'fordham', 'language', 'trobairitz', '32', 'no.13', 'sex-education'], ['unspoken', "bach's", 'may', 'reference', 'concepts', 'used', 'hidden'], ['2012', 'views', 'later', 'language', 'april', 'away', 'creature', 'bright', 'download', 'game', 'running', 'gammer', 'august', 'part', 'robinson'], ['ex-girlfriend'], ['emotivism', 'first', 'ayer', 'ethics']]
TOP TOKENS [['whiplash', 'go', 'every', 'see', 'reasons', 'history', 'range', "as'trigger", 'however', 'also', 'due', 'known', 'suffering'], ['whiplash', 'alleviate', 'injury', 'pain', 'suffer', 'leads', 'common', 'sufferers', 'less', 'doctor'], ['whiplash', 'detailed', 'many', 'history', 'tissues', 'medical'], ['whiplash', 'movement', 'worsening', 'assault', '20', 'disorders', 'weeks', 'syndrome'], ['whiplash', 'initiation', 'results', 'early'], ['whiplash', 'whiplash?june', 'get', 'treat', 'drivers', 'term', 'impractical', 'pain'], ['whiplash', 'injuries', 'treatment', 'common'], ['whiplash', 'complicated', '“', 'common'], ['whiplash', 'injury', 'range', '’', 'type'], ['whiplash', 'always', 'neck', 'accidents', 'aggravation', 'injuries', 'history', 'going', 'stick', 'symptom', 'sort'], ['whipple', '36p/whipple', "whipple's", 'mr', 'myer', 'abraham', 'type', 'united'], ['voorslag', 'whiplash', 'whips', 'band', 'album', '2006'], ['herculean', 'whippy', 'mr'], ['pl:whippet', 'whippet'], ['whipple-lacey', 'whipple', 'whipple-angell-bennett', 'whipple-cullen', 'whipple-jenckes'], ['1804-1876', 'load', 'puerto'], ['downstream', 'whipp', 'ill-fated', 'taught', 'marty', 'television', 'carlmont', 'male', '1970s', '1989–1990', 'many', 'july', 'drama'], ['whipple', "whipple's", 'educational', 'public', 'henry', 'american', 'inez', 'george'], [], ['whipple', 'since', '1871']]
TOP TOKENS [['ear', 'ears', 'eardrum', 'earal', 'eared', 'earable', 'earing', 'well', 'earring'], ['ear', 'cls'], ['ear', 'ears', 'structure', 'simple', '’'], ['ear', 'ears', 'structure', 'simple', '’', 'edge'], ['ear', 'ears', 'word', 'earache', 'arse'], ['ears', 'ear', 'head', 'whether'], ['ear', 'modeling', 'alone'], ['ear', 'ears'], ['ears', "dog's", 'ear', 'fights'], ['ears', 'ear', 'although'], ['ear', 'ears', 'auricula-judae'], ['ears', 'ear'], ['ears', 'ear', 'sound', 'also', 'disambiguation'], ['ears', 'ear', 'melodisc'], ['ears', 'name'], ['ear', 'ears', 'head', 'combination', 'describes'], ['ears', 'cited', 'accolades', '2016', 'featured', 'cls', 'also', 'sound', 'music'], ['ears', 'eared', 'ear', 'head', 'types', 'long'], ['ear', 'earring', 'ears', 'earrings', 'adulthood'], ['ear-picking', 'ear', 'earwax', '耳そうじ', '耳掃除', 'steadiness', 'tools']]
TOP TOKENS [['alligators', 'alligator', 'edge', 'prey', 'kayaking', 'action'], ['alligators', 'alligator'], ['alligator', 'alligators'], ['alligators', 'alligator'], ['alligators', 'alligator', 'stringer', 'edge'], ['alligators', 'alligator', 'pieces', 'drowns', 'land', 'noises', 'edge', 'bubbles', 'underwater', 'away'], ['alligators', 'alligator', 'movements', 'levels', 'clumsy', 'suffice', 'present', 'health', 'presence'], ['alligators', 'alligator', 'may'], ['alligators', "alligator's"], ['alligator', 'alligators', 'hand'], ['alligator', 'film', 'book', 'motorcycle'], ["alligator's", 'alligator', "alligators'main", 'alligators', 'transported', 'lunges', 'ground', 'lunge'], ['alligators', "alligator's", 'alligator', 'copulation', '4', 'chinese', 'minutes'], ["alligator's", 'alligators', 'alligator', 'females'], ['alligator', "alligator's", 'alligators', 'quarter'], ['alligator', "alligator's", 'alligators', 'alligatorinae', 'alligatoridae'], ['alligator', 'alligators', "alligator's", 'doubt', 'range', 'border', 'american'], ['alligator', 'ships', 'night', '1814', 'oars'], ['alligator'], ['alligator', 'alligators', 'target', 'years', 'chinese', 'american']]

Processing features:  73%|███████▎  | 72/98 [34:35<12:11, 28.13s/it]

getting sample prompt forgetting sample prompt for 24265
getting sample prompt for 24266
 24264
getting sample prompt for 24267
getting sample prompt for 24268
getting sample prompt for 24269
getting sample prompt for 24270
getting sample prompt for 24271
getting sample prompt for 24272
getting sample prompt for 24273
getting sample prompt for 24274
getting sample prompt for 24275
TOP TOKENS [['spear', 'users', 'called'], ['spear', 'spears', 'spearhead', 'edges', 'muses'], ['spear', 'times', 'phishing', 'structures', 'vishing', 'media'], ['spear', 'phishing', 'bob', 'information'], ['spear', 'spears', 'spearhead'], ['spear', 'anti-spear', '“spear', 'spear-phishing', 'reading', 'email', 'victim', '–', 'phishing', 'world', 'fig', 'computer'], ['spear', 'phishing', 'common'], ['spear', 'apt', 'www', 'phishing', 'itservices', 'consequences', 'attacks', 'strategy'], ['spear', 'crude', 'received', 'phishing', 'highlighted', 'security'], ['spear', 'narrative', 'information', 'create', 'attempt', 'messages', 'attackers', 'infect', 'phishing'], ['spear', 'spears', 'south'], ['spears', 'spear_system', 'spear', 'disambiguation', 'speare', 'spearing', 'response', "spear's", 's.p.e.a.r', '2005', 'liturgy', 'combat', 'ring'], ["spear's", 'lancets', '1957', 'points', 'edinburgh'], ['spear', 'spears', 'born', '1914–1974', 'lawrence', 'speir', 'rock'], ['spears', 'spear'], ['spear', 'system', 'programs'], ['spear', 'spearing', 'spearfishing'], ['spear', 'spears', 'arneill', 'nfl', 'britney', '1886–1974', 'disambiguation'], ['spear', '2014', 'guitar', 'performed', 'life', 'personal', 'activities', 'art'], ['spear', 'war', '1914', '1998', 'nevertheless']]
TOP TOKENS [['post', 'postal', 'service', 'mail', 'office', "america's"], ['post', 'postal', 'service', 'states', 'office', 'postmaster'], ['post', 'postal', '“post', 'offices', 'u.s', 'postmaster', 'service’s', 'office', 'destination', 'mails', 'service', 'addressee', 'usps'], ['postal', 'post', '1970', 'office', 'postmaster', 'usps', 'service', 'mail', 'states', 'providing'], ['postal', 'post', 'service', 'mail', 'cities', 'workers', 'employees', 'closing', 'u'], ['postal', 'post', 'service', 'usps', 'mail', 'historic', 'offices', 'states'], ['post', 'postal', 'u.s', 'states'], ['post', 'postal', 'postmaster', 'mail', 'system', 'office', 'cls', 'service', 'america', 'posthouses'], ['post', 'office', 'postal', 'postmaster', 'usps', 'service', 'states', 'mail', 'george’s'], ['postal', 'post', 'service', 'contrast', 'postmaster', '2', 'office'], ['post', 'office'], ['poste', 'national', 'post', 'central', 'old', 'network', 'postal'], ['post', 'postmasters', 'postal', 'offices', 'office', 'service', 'politician'], ['post', 'postal', 'office', 'postman', 'service', 'postage', 'mail', 'states', 'mails/pallets', 'character'], ['postal', 'postmasters', 'post', 'postmaster', 'providing', '1970', 'service', 'office', 'usps', 'mail'], ['post', 'postal', 'postmaster', 'service', 'mail', 'office', 'services'], ['postal', 'post', 'country'], ['post', 'postal', 'offices', 'states', 'mail', 'service', 'postmaster'], ['postal'], ['post', 'office', 'poste', 'postal']]
TOP TOKENS [['tension', 'anxiety', '8/28/2013', 'a-z', 'type'], ['tension', 'tension.”', 'need', '“tension', 'happen', 'word', 'nerves.”'], ['tension', 'surface', 'pictureofthephenomenonunder', 'liquid', 'different'], ['tension', 'combat', '2', 'psychologically', 'removing', 'cause', 'security'], ['tension', 'tensions', 'string'], ['tension', 'tensions', 'string'], ['tension', 'arises', 'life', 'resolve', '–', 'engage', 'faced', 'dynamic', 'like', 'unless', 'control', 'utilize', '”'], ['tension', 'alleviating', 'experiencing', 'alleviate', 'uncertainty', 'treating', 'tense', 'role', 'anxiety', 'unrelated', 'pressure'], ['tension', 'tensionconsider', 'tensionsurface', 'surface'], ['tension', 'following', 'bear', 'find', 'reindeer', 'm1', 'playground', 'passes', 'suppose'], ['tension', 'tenseness', 'physics', 'muscle', 'geology', 'known', 'electric'], ['tension', 'levels', 'pitch'], ['tension', "tension's", 'age', 'became', 'shows', 'people', 'formed', 'first', 'songs', 'left', 'cls', 'fell', 'together', 'strongarm', 'official', 'looked', 'completed', 'six'], ['tension', 'magnetic', 'permeability', 'gravity', 'mhd', 'right'], ['tension', 'swedish'], ['tension-controlled', 'tension', 'meters', 'measure', 'equation'], ['tension', '7:24', 'shake', '2:10', 'safe', 'october', 'dance', 'ghostly'], ['tension', 'breast'], ['tension', 'length', 'constant', 'called', 'system', 'elements', 'member', 'physics', "string's", 'object', 'also', 'due', 'pulleys', 'might'], ['tension', 'sexual', 'intensifies', 'sorrow', 'wish', 'situation—such', 'reasons', 'relationship', 'devoid', 'situations']]
TOP TOKENS [['headset'], ['hands', 'headset', 'new', 'unobstructed', 'eyes'], ['headset', 'use'], ['headset', 'headsets', 'hands-free', 'use', 'tasks', 'loudspeaker'], ['usersoperatorssupervisorssystem', 'functions', 'alerts', 'modules', 'offers', 'provides', 'features', "operator's", 'centers', '3', 'device', "operators'condition", 'provide', 'calleddata', 'connection', 'system', 'verificationsystem', 'operator'], ['headsets', 'headset', "headset,'he", 'muscles', 'eyestrain', 'minutes', 'headaches', 'used', 'people', "screen.'it's", '61'], ['headsets', 'switching', 'without', 'provide', 'software', 'perceived', 'get', 'focus', 'user'], ['headset', 'edition', 'using', 'real', "device's", 'able'], ['hands', 'free'], ['headset', 'headsets'], ['hands', 'headsets', 'cls', 'keeping', 'free', 'well', 'ear', 'allowing', 'offers', 'centers'], ['handset', 'headset'], ['handset', 'talkie', 'replicated'], ['headset', 'features', 'pack', '2005', 'technologically', '2003', 'retrofitted'], ['headset', 'hands', '3', '5', 'voice', 'experience', 'systems', 'include'], ['headset', 'handset', 'also', 'telephones', 'speak', 'tinsel'], ['headset', 'headsets'], ['hands', 'headsets', 'headset', 'wearable', 'free', 'carry', 'operated', 'feasible', 'common', '3', 'keeping', 'user'], ['movements', 'cultural', 'interaction', 'support', 'pedals', 'simulators', 'without', 'quick', 'limiting', 'tactical', 'skills'], ['headset', 'camera', 'japanese', 'attachments', 'later', 'contains', 'spanish', 'german']]
TOP TOKENS [['p', 'genera', 'families', 'materials', 'gray', '5', 'four', 'work', 'dated', 'early', 'three', 'kinds', 'ms'], ['volumes', 'fresh-water', 'volume', 'lamarck', 'morayshire', 'naturalists', 'tract', 'quadrupeds', "lyell's", '1797-1875', 'alluvium', 'molluscs', 'imbedded', 'stalagmite', 'testacea', 'tion', 'tribes', 'reefs', 'places', 'subaqueous', 'winds', 'calcareous', 'formation', 'variety', 'reptiles', 'races', 'racters', 'endlessly', 'zoophytes'], ['vol', 'soc', 'naturlichen', 'der', '510', 'geol', 'nachgewiesenen', 'v', '328', 'iii', 'ii', 'pp', '467', '205', 'iv'], ['volumes', 'volume', '8-1/2', 'pliocene', 'compiled', 'described'], ['ideology', '’', 'de', 'des', "lyell's", 'edition', 'stratigraphy', 'la'], ['volume', 'volumes', "lyell's", '1797-1875', 'endlessly', 'i—the', 'geology', 'freud', 'focuses', 'around'], ['vol', 'i.e', '3', 'encyclopedia', 'evidences', 'k', 'sister-in-law', '1830–33', '1863', 'epochs', 'addition', '2'], [], ['gradual', 'assemblages', "lyell's", 'uniformitarianism'], ['volume', 'h'], ['fields', 'meant', 'however', 'geologically'], ['volume', 'album', 'july'], ['stapf', 'references', 'nadu', 'panicoideae', 'poaceae', 'oceania', 'c.e.hubb', 'taxa', 'grasses', 'tanzania'], ['varieties', 'proofs', 'referring'], ['substacks', 'due'], ['volume', 'among', 'c'], ['k', '20', '79', '1', 'forces', '–', '24', '34', '285', '278', 'southern', 'planning', 'press'], ['volume', 'volumes', '–', '9', '“', 'f', '1', 'g', 'guide', '12', 'h', 'pp', 'ethnohistorical', '63', '165', '182', 'editor', 'cline', '”', 'indies', '17', 'relaciones', '452', '137', '11', '62', '2', '3', 'r', '369'], ['vol', 'volume', '–', '2', '1'], ['ptiliinae']]
TOP TOKENS [['globulars', 'globular'], ['globular'], ['globular'], ['globular', 'could', 'sun'], ['globular', 'globulars', 'clusters'], ['globular'], ['globular'], ['globular', 'several', 'typical'], ['globular', 'galaxy'], ['globular', 'addition', 'field'], ['globularia', 'globularias', 'globulariaceae'], ['globular'], ['globularia', '†globularia'], ['globular'], ['globulariopsis'], ['globular', 'thus'], ['globular', 'https://ncatlab.org/nlab/show/globular+set', 'algebra'], ['globularia', 'genus', 'north-central'], ['globularia'], ['globular', 'way', 'discovered', 'known', 'clusters']]
TOP TOKENS [['grief', 'cls', 'loss'], ['grief', 'cls', 'astray', 'lead', 'often', 'significant'], ['grief', 'life'], ['grief'], ['grief', 'learning', 'yet', 'cls'], ['grief', '“', 'cls', 'mourning', 'words', '—', 'feelings', 'word'], ['grief', 'experience', 'cls', 'divorced', 'complicated'], ['grief', 'cls', 'life', 'due'], ['grief', 'cls', 'experiencing', 'words', 'reality'], ['grief', 'fact', 'cls', 'lives', 'job', 'one'], ['grief', 'griefer'], ["grief's", 'grief', 'bands', 'see', 'york', 'cls', 'ohio', 'reuniting', '2005', 'may', '17'], ['grief', 'anticipatory', 'complicated', 'harm'], ['family', 'grief', 'charles'], ['griefing', 'griefers', 'grief', 'griefer', 'considered', 'objective', 'massively', 'ultima', 'giving'], ['griefing', 'griefer', 'considered', 'griefers', 'typically', 'combat', 'specifically', 'disguised', 'annul', 'oppose', 'report'], ['grief', 'griefing', 'griefer', 'griefers', 'players'], ['grief', "grief's", 'would', 'stadium'], ['grief', 'experience', 'anticipatory'], ['grief', 'cls', 'counseling', 'experiences', 'one', 'anticipatory', 'expresses', 'counselling']]
TOP TOKENS [['stunting', 'stunted', 'cls', '·', 'often', 'defines'], ['stunting', 'stunted', 'increased', 'severely'], ['stunting', 'solutions', 'height-for-age', 'stimulation', 'world', 'less'], ['stunting', 'kejadian', 'age'], ['stunting', 'especially', 'underlying', 'child'], ['stunting', 'stunted', 'higher', 'predictor', 'months', '24'], ['stunting', 'among', 'severe'], ['stunting', 'stunted', 'cls', 'age', 'become', 'words', 'poor'], ['stunted', 'stunting', 'one'], ['stunted', 'stunting', 'one'], ['growth', 'stunted', 'stunting', 'double', 'malnutrition', 'rademacher', 'stunters', 'plant'], ['stunting', 'stunted', 'stunt', 'agriculture', 'means', 'remedied'], ['stunting', 'stunted', 'poverty', 'society', 'uncontradicted', 'level', 'suggested'], ['stunted', 'stunting', 'poverty', 'cls', 'standards', 'permanent', "world's", 'according'], ['stunted', 'stunting', 'damage', 'undergone', '21'], ['stuntman', 'stunt', 'mad'], ['stunting', 'improve', 'reduce', 'lead', 'also', 'prevalence', 'child'], ['stunting', 'stunted', 'estimated', 'growth', 'reduce', 'childhood'], ['stunt', 'success', 'members', 'mid-1990s', 'pioneers', 'purpose', 'able', 'casting', 'according', 'a-list', "show's", 'commentary', 'appearance'], ['stunting', 'stunted']]
TOP TOKENS [['tm', 'superspies®', 'rifts®', 'writeup', 'trademarks', 'worlds', 'w'], ['twittertwittershare', 'linkedinlinkedinshare', 'messengermessengershare', 'yes', 'buttonsshare', 'us', 'whatsappwhatsappshare', 'addthis', 'gearing', 'desired', 'indeed'], ['hyp', '10', '1002', 'timing', 'doi', '–', 'p', '2782', 'support', 'sep'], ['—', '2010', 'may', 'world', '2001', "that's", 'funk', '76', 'news', '8', 'space', 'orbit', 'inspiration'], ['limited', '–', '1', 'actually', 'analyze', 'okay', 'mind', 'acceptance', 'order', 'ipad', 'distortions'], ['preliminary', 'shallow', 'seasonably', 'shanxi', 'low', 'normal', 'able', '526', 'melts', 'much', '316', 'hebei', 'however', 'guizhou', 'part', 'seriously', 'gansu'], ['sometimes', 'wherein'], ['far', 'unsung', '’', 'determined', 'innumerable', 'given'], ['green', '29', 'concept', 'ca', '–', 'signify', "reflects'that", '1', 'captitals'], ['small', 'attentively', 'moments', 'gabefernandez', 'fruitless', 'circumstances', '’', 'currently', 'intend', 'net', 'firstname', 'process', 'example', 'either', 'truth', 'ed'], ['–', '2000', "men's", 'sportspeople', '15', 'lower', 'links', 'along', 'october', '3', '26', '2004', 'vying', 'states', 'sports', "team's", "chris'mid", '97', 'united'], ['bgcolor', '1', '00', 'linyi'], ['05', 'style', '00', '01'], ['decision', 'drop', 'split', 'regarding', 'pan', 'colorado', 'contains', 'sometimes', 'guitar', 'tops', 'one', 'cadence', 'time', '2005', "daughtry's", 'made', 'disapproved', 'went', 'found'], ['01', '00', 'style', 'align'], ['believin', 'republic', 'anthems', 'recordings', 'orchestration', '–'], ['style', 'background', 'align'], ['imperfectly', 'symphony', '1994', 'rerecorded', 'original'], ['160', 'arena15', 'arena19', '7', '21', '14', '715'], ['ffbbbb', 'colspan', 'bgcolor', '–', 'paris']]
TOP TOKENS [['liquidity', 'liquid', 'sufficient'], ['liquidity', 'forth'], ['liquidated', 'liquidity', 'straightaway', 'others', 'transact', 'large'], ['liquidity', 'liabilities', '’', 'meet'], ['liquidity', "company's", 'due'], ['liquidate', 'liquidity', 'blown', '“', 'comes'], ['liquidity', 'liquid', 'term'], ['liquidity', '‘', '’', 'liquid'], ['liquidity', 'ample', "company's"], ['liquidity'], ['liquidity'], ['liquidity', 'liabilities', 'non-banking', 'readily', 'full', 'result'], ['liquidity', 'market'], ['liquidate', 'liquidity', 'sell'], ['liquidity', 'liquidated', "stock's", 'much', 'managing', 'cases', 'liquid', 'several'], ['liquidity', 'liquid'], ['liquidity', 'price', 'market', 'liquid', 'illiquid'], ['liquidity', 'liquid', 'higher', 'security'], ['liquidity'], ['liquidity', 'providing', 'liquid', 'ample']]
TOP TOKENS [['cytometry', 'cytometric', 'flow', 'cytofluorometry'], ['cytometry', 'cytometer', 'flow', 'function'], ['cytometry', 'cytometer', 'cytometers', 'flow'], ['cytometric', 'cytometry', 'cytometer', 'flow', 'cls'], ['cytometer', 'cytometry', 'flow', 'cls'], ['cytometry', 'cytometer', 'flow'], ['cytometric', 'cytometry', 'cytometer', 'flow', 'cls', 'basis', 'several'], ['cytometry', 'cytometers', 'flow', 'proliferation', 'cause'], ['cytometry', 'flow', 'cytometers', 'cls', 'flowrepository'], ['cytometry', 'flow', 'cls'], ['cytometry', 'flow', 'cytometers', 'cls', 'flowrepository'], ['cytometry', 'cytometer', 'flow', 'cytometers', 'cls', 'cytofluorograph', 'research'], ['cytometry', 'flow'], ['cytometry', 'flow', 'computational'], ['cytometers', 'flow', 'cytometry', 'cytometer', 'cytometric', 'systems'], ['cytometry', 'cytometers', 'cytometer', 'flow', 'computed', 'typical'], ['cytometry', 'flow', 'algorithms'], ['cytometry', 'flow', 'cytometer', 'pathology', 'traditional', 'inferred', 'computational'], ['cytometry', 'cytometric', 'flow', 'staining', 'microtome', 'perform', 'analysis', 'possible', 'immunohistochemistry'], ['cytometry', 'flow', 'use', 'limitation']]
TOP TOKENS [[], ['number', '20', '2', '33', '41', '15', '5', 'integers'], ['python', 'film', 'character', '’', 'also', 'psychologically'], [], ['create', 'improve', 'sometimes'], [], [], [], ['states'], [], ['fiance', 'indulgence', 'rituals', 'insecurity', 'ritz', 'hypocrisy'], [], ['human'], ['statement', 'plus', 'least', 'though'], ['british', 'bonita', '1990s', '1947–1958', '1948', '1990', '1947', 'later', '1986', 'film', 'show', 'lucky', 'known', '1986–1987'], ['karenina'], [], ['20th', 'births', 'businesspeople', 'links', 'living', 'american', 'century', 'references', 'schuster'], [], ['love']]

Processing features:  74%|███████▍  | 73/98 [35:02<11:38, 27.94s/it]

getting sample prompt forgetting sample prompt for 24277
 24276
getting sample prompt for 24278
getting sample prompt for 24279
getting sample prompt for 24280
getting sample prompt for 24281
getting sample prompt for 24282
getting sample prompt for 24283
getting sample prompt for 24284
getting sample prompt for 24285
getting sample prompt for 24286
getting sample prompt for 24287
TOP TOKENS [['encyclopedia', 'article', 'com'], ['encyclopedia', 'article', 'com'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia', 'com', 'article'], ['encyclopedia.com', 'also', 'encyclopedias', 'sources', 'allows'], [], ['com', 'dictionary', 'reference', 'encyclopedias', 'encyclopedia'], [], ['church'], [], ['book', 'centennial', '”', '12', 'july', '96'], ['otherwise', 'based', 'wikipedia', 'unfit', 'similarly', 'dates', 'name', 'birth', 'deletion'], [], []]
TOP TOKENS [['slots', 'slot', 'word', 'wings', 'creating', 'new'], ['slot', 'slots', 'word', 'suite', 'create', 'object'], ['slot', 'great', 'something', 'slots', 'successful'], ['slot', 'slots', 'page'], ['slots', 'slot', 'playing', 'word', 'types', 'space', 'installed', 'it’s'], ['slots', 'slot', 'markings', 'playing', 'custom', 'single', 'class', 'properties'], ['slot', 'window', '“', 'slots', 'symbols', 'word', 'person', 'gate', 'definition', 'century', 'however', 'breastbone'], ['slot', 'slot-based', 'cards', 'set', 'using', 'control', 'goals', 'completed', 'hockey', 'defensive'], ['slots', 'slot', 'wing', 'word', 'chance', 'use', 'syntactic', 'cls', 'confusing'], ['slots', 'slot', '“slot', 'plane', '“slot?”', 'two', 'so-called'], ['slot', 'slots', 'margareta', 'expansion', 'imaginary'], ["slot's", 'slot', '2023', 'month', 'coach', '2002', 'year', 'psv', 'arne'], ['slot', "slot's", 'slots', 'additional', 'adding', 'whose', 'one', 'include', 'changing', 'second', 'first', 'constant', 'runtime', 'name', 'objects'], ['slot', 'birth', 'players'], ['slot', 'slots', 'correspond', 'term', 'resources'], ['slot', 'f.c', 'expatriate'], ['slot', 'assemblies', 'microprocessor', "intel's", '7'], ["slots'axis", 'slot', 'slots', 'axis', 'antennas', 'multiple', 'parallel', 'slotted', 'pattern', 'antenna', 'current'], ['shae-lee', 'rodrigues', 'cagatay', 'slot', 'kinchela', 'xanthis', 'kington', 'original'], ['slot', 'high', 'low', 'hockey']]
TOP TOKENS [['intel', 'intel’s', 'corporation'], ['intel', '2013', 'corporation', '2012'], ['intel', 'time'], ['intel', 'technologies', 'cls', 'standards', '’', 'features', 'bodies'], ['intel'], ['intel', 'position', '2011', 'quarter'], ['intel', 'delaware,intel', 'corporation', 'commonly', 'known', '1981'], ['intel'], ['intel', 'intel’s', 'uses', 'areas', 'well', 'one', 'exactly'], ['intel'], ['intel', 'manufacturer'], ['intel', '2010s', 'corporation'], ['intel', 'x', 'windows', 'platform', '7.5'], ['intel', "intel's", 'cls', '2014', 'acquisitions', 'technologies', '57'], ['intel', "intel's", 'kmo', '1991-2001', 'las'], ['intel', 'http://www.intel.com/about/corporateresponsibility/education/programs/intelteach_ww/index.htm'], ['intel'], ['intel'], ['software.intel.com', 'intel', "intel's"], ['intel', 'intel®', 'webpage', 'devices', 'critical']]
TOP TOKENS [['wood', 'wooden', 'it’s', 'europe', 'steel', 'competitors', 'civilization'], ['wood', 'wooden', 'times'], ['wood', 'woodworking', 'woodcraftsmen', 'wooden', 'cls', 'time'], ['wood', 'professional', 'woode'], ['wood', 'lumber', 'wooden', 'products', 'timber'], ['wood', 'treated'], ['wood', 'wooden', 'log', 'sawing', 'hardness', 'properties'], ['wood', 'expensive', 'timber', 'materials'], ['wood', 'woodworker', 'woodworking', 'woodwork', 'woods', 'woodworkers'], ['wood', 'likes', 'future', 'better', '75', 'present', 'foundation'], ['wood', 'south', 'apa'], ['wood', '2018', '2017', '2015', '2013', '2014', 'signed', '25'], [], ['wood', 'september'], ['wood', '2023', '2021', '2022', '9'], ['wood'], ["wood's", 'wood', 'season', '2008', '2007', 'links', '2019', 'purchased', 'people'], ['wood', "wood's", 'nlds', '2018', '2017', 'hit', '17', 'season', 'july', '–'], ['wood', 'non', 'c', 'links', 'births', "men's", 'people', 'external', 'international', 'lanarkshire', 'references'], ['wood', '2019', '2020', 'international', 'del', 'signed']]
TOP TOKENS [['vantagescore', 'like', '990', 'experian', 'inc', "transunion's", 'karma', 'consumers'], [], ['app'], [], [], ['aws', 'certificate'], ['buried'], ['they’re', '—'], [], [], ['office', 'contingent', 'general'], ['synonym'], ['pnc', 'banks', 'america', 'history', 'bank', '2003', 'southeast'], ['vantagescore', 'systems', '850', 'unpaid', 'recently', 'calculated', 'situation', '0', '2017', 'time', 'cycle'], [], ['proshares'], [], [], [], ['vantagescore', "vantagescore's", 'three', 'bureaus', 'vantagescores', 'equifax', 'llc', 'risk', 'formula', 'experian', 'loan']]
TOP TOKENS [['contains', 'product', 'similar', 'ready-to-go', 'pack', 'easy-buy', 'ready', 'items'], ['like', 'also', 'pack', 'included', 'might', 'copies', 'look', 'classroom-ready', 'set', '●reading', 'product', '●guided', 'needs', '3rd-6th', 'different'], ['available', 'sold', 'seperately-unless', 'purchase', 'seperately'], ['products', 'printables', 'great', '6-pack', 'format', 'need'], ['packed', 'format', 'photocopiable', 'ready-to-go', 'product', 'printable/interactive', 'similar', 'see', 'photocopier', "teacher's", 'items', 'worth', 'ready-made', 'fully', 'cd-rom'], ['purchased', 'formats', 'available', 'previously', 'already', 'compatible', 'contains', 'printable'], ['available', 'purchased', 'product', 'booklet', 'included'], ['product', 'provides', 'cd-rom'], ['product', 'features', 'buy', 'versions', 'presented', 'purchased', 'included'], ['already', 'ready', 'another', 'booklets', '6', 'complete', '16', 'pages'], ['released', 'version', "read's", 'sold', "ti's", 'designed', 'features', 'set', 'earlier', 'successor', 'prior', 'functions', 'preprogrammed', 'library', 'series', 'contemporaneously', 'first', '–', 'lit', 'different'], ['brief', 'copy', 'informative', 'recommended', 'pad'], ['users', 'printed', 'pack', 'spent', 'available', 'released', 'user', 'files', 'device', 'feature', 'contains', 'transparencies', 'included', 'time', 'features', 'lets', 'affected', 'advantage'], ['use', 'format', 'x', 'includes', 'set', '11', 'materials', '1', 'made', 'vol', 'plan', 'cm', 'cd', 'rom', 'easy', '29'], ['wonderful', 'different', 'reading', 'licensed', 'item', 'introductory', 'official', 'counting', 'forty', 'commercial', 'cartridges', 'included', 'links', 'concentrate', '2002', 'stored'], ['edition', 'companion', 'available', 'users', 'release', 'released', 'replacement', 'feature', 'versions', 'trackage', 'run', 'consisting', 'original', 'features', 'custom', 'based', 'offer', 'allows', 'later', 'support', 'suite', 'references'], ['set', 'per', 'entertainment', 'pages', 'big', 'volume', 'recommended', 'retailed', 'version', 'containing', 'audio', 'edition', 'fun', 'guide', 'cd', 'material', 'unending', 'accompanied', 'media', 'reference', '45'], ['series', 'x', 'includes', 'player', 'available', 'justification', '5oz', '10mm', 'version', 'vga', 'formats', 'similar', 'installed', 'pt', 'built'], ['product', 'designed', 'released', 'personalized', 'edition', 'available', 'cartridge', 'release', 'form', 'teaches', 'memory', 'products', 'recorder', 'tag', 'like', 'patterned', 'camera', '–', 'built', 'content', 'gives', 'include', 'using', 'lasts'], ['interchangeable', 'discs', 'players', 'users', 'use', 'purchase', 'edition', 'companion', 'format', 'recommend', 'played', 'offered', 'reviews', 'editions', 'written', 'beveled', '3', 'cds', 'audio', 'user', 'studio', 'cd', 'installed', 'includes', 'comprising', '14']]
TOP TOKENS [['strongly', 'asterinoid', 'tissue', 'angustifolius', 'mutabilis', 'walled', 'fine', 'polyphyllus', 'outlines', 'majority', 'extended', 'rectilinear', 'zigzag', 'leaf', 'largely', 'made', 'also', 'parenchyma', 'various'], ['web', 'margin', 'leaf', 'extensions', 'edge', 'tissue', 'indentations', 'narrow', 'broadly', 'leaflets', 'veined', 'like', 'veins', 'longitudinally'], ['leaf', 'tissue', 'like', 'eudicot', 'net', 'venation', 'edge', 'vascular', 'reticulate', 'petiole', 'biloba', 'shows', 'leaves', 'part', 'also', 'midrib'], ['layer', 'interstitial', 'muscle'], ['myofilament', 'tranverse', 'hypodermis', 'filaments', 'cuticle', 'muscle', 'bands', 'small', 'cell', 'sheet', 'pers', 'comm', 'laterally', 'apposes'], ['sheath', 'serrulate', 'crenate', 'lobed', 'edge', 'dentate', 'midrib', 'margin', 'leaves', 'serrate', 'margins', 'typically', 'way', 'leaf', 'less', 'like', 'size', 'incisions', 'entire'], ['rotund', 'broad', 'cordate', 'interpetiolar', 'eg', 'part', 'paper', 'oval', 'orbicular', 'like', 'leaf', 'calendula', 'anthocephalus', 'sagittaria', 'zizyphus', 'dry', 'structure'], ['mesenchyme', 'grossa', 'membrane', 'nemerteans', 'ciliated', 'cuticle', 'nemertean', 'malacobdella', 'stretchy', 'connective', 'kind', 'outermost', 'microvilli', 'rhabdites', 'glandular', 'thickened', 'epithelium', 'gelatinous', 'muscles', 'layers'], ['margin', 'parts', 'edge', 'scalloped', 'leaf', 'toothed', 'palmately'], ['layer', 'nemerteans', 'layers', 'constrict', 'ganglia', 'sandwiching', 'cephalic', 'circular', 'nemertean', 'muscle', 'large', 'individual', 'species', 'ganglionated', 'general', 'muscles', 'nerve'], ['semiamplexicaul', 'unifoliata', 'marginal', 'fimbriate', 'tripinnata', 'trifoliolate', 'unifoliate', 'bristly', 'margins', 'acutifolius', 'tripinnate', 'trifoliata', 'acanceous', 'periderm', 'leathery', 'covering', 'completely', 'edge', 'acanthocladous', 'pinnately', 'waxy', 'end', '–', 'epidermis', 'fringe', 'texture', 'hirsute'], ['minusculus', 'mesenchyme', 'nemerteans', 'cuticle', 'grossa', 'annulonemertes', 'gelatinous', 'midline', 'dermis', 'cilia', 'little', 'layers', 'ciliated', 'rhabdites', 'connective', 'malacobdella', 'unsegmented', 'rhynchocoel', 'microvilli', 'include', 'stretchy', 'coelom', 'classes'], ['palmatus', 'cladodromous', 'craspedodromous', 'conglutinatus', 'veins', 'like', 'margin', 'secondaries', 'flabellatus', 'see', 'leaf', 'subclasses', 'midrib', 'flabellate', 'manner', 'upturned', 'vein', 'consisting', 'conglutinate', 'brochidodromous', 'radially'], ['media', 'flexible', 'portion', 'lines', 'axillary', 'alula', 'foldings', 'variable', 'nearly', 'flexion', 'thoracic', 'medially', 'often', 'radial', 'may'], ['leaf', 'multipinnate', 'imparipinnate', 'unipinnate', 'leaflet', 'leaves', 'tripinnate', 'muscles', 'leaflets', 'bipinnate', 'tetrapinnate', 'compound', 'also', 'pinnatus'], ['nemertea', 'multiciliated', 'nemerteans', 'part', 'connective', 'nemertean', 'spiralia', 'tissue', 'echiurans', "nemerteans'affinities", 'pattern', 'animals', 'among', 'echiura', 'sipunculans', 'acoel', 'widespread', 'small', 'lot', 'muscles', 'structure', 'endomesoderm', 'similar'], ['leaf'], ['musculi', 'crista', 'terminalis', 'smooth', 'part', 'parallel', 'muscular', 'muscles'], ['triplinerved', 'celtis', 'leaf', 'like', 'venation', 'acrodromous', 'subsequently', 'veins', 'suprabasal', 'similarly', 'conspicuous', 'leaves', 'especially', 'besides'], ['perfoliata', 'trifoliolate', 'paripinnate', 'trifoliata', 'spathulate', 'tripinnate', 'pinnata', 'subulata', 'reniform', 'pinnatifida', 'oval', 'elongated', 'ensiformis', 'oblong', 'linearis', 'oblanceolata', 'orbicularis', 'parallel', '–', 'middle']]
TOP TOKENS [['upon', 'seriously', 'also'], ['exactly', 'far', 'somewhere'], ['email', 'necessary', 'longer', 'loud', 'ok', 'though'], ['email', 'necessary', 'longer', 'loud', 'ok', 'though'], ['directly', 'cbslocal', 'first'], ['richmond', 'early', 'hard', 'inch', 'could', 'point', 'injured', 'past', 'stage'], ['time', 'important', 'taurusquest'], ['nuisance', 'conditionalthat'], ['nuisance', 'conditionalthat'], [], ['point-and-click', 'well', 'largely', 'less', '9,000', 'storyline', 'parents', 'game', 'well-balanced', 'jones', 'partners'], ['united', '23', 'states', 'blumhouse', 'january', 'october', 'march', 'later', 'stabbing', 'productions', "glasgowman's", '31', '14', '05', 'zombies', 'primarily', 'story'], ['next', 'clippings'], ['complete', 'woods', 'strongly', 'first', 'like', 'tapes', 'couple', 'also', 'bathtub', 'may', 'assures'], ['reality', 'prove', 'real', 'freedomtown', 'behind', 'otherwise', 'events', 'though', 'uncovers'], [], ['complete'], [], ['late', 'point', '£67', '2005'], ['wholly', 'september', 'substantially', 'announced', 'co', 'time', 'billion', 'march', 'written', '1995', 'insurance', 'inc', 'bermuda', 'canada']]
TOP TOKENS [['consideration', 'commonly', 'firm', 'others', 'important', 'lot', 'considerations', 'things', 'clear', 'frequently', 'fabian', 'within', 'general', '”', 'based', 'associated', 'hand', '“', 'speak', 'emphasized', 'several', 'followed', 'eternal', 'used', 'nothing', 'person', 'connotation', 'absorbed', 'also', 'sorry', 'unprecedented'], ['underwithhold', 'withholding', 'withheld', 'underwithholding', 'underwithheld', 'cover', 'jointly', 'file', 'withhold', 'use', 'amount', 'money', 'obligations', 'claimed', 'filing', 'owed', 'decide', 'status', 'number', 'made', 'separately', 'owe'], ['withholding', 'withhold', 'cover', 'holders', 'withheld', 'withholding(redirected', 'variety', 'amount', 'including', 'due', 'put', 'tax-free'], ['promised', 'promises', 'promise', 'abstain', 'already', 'consideration', 'promisor', 'pre', 'promisee', 'much', 'abstained', 'alone', 'parties', 'every', 'even'], ['withholding', 'withheld', 'withholdings', 'telling', 'amount', 'entering', 'remember', '1', '2019', 'provide'], ['promise', 'consideration', 'promisee', 'forbearance', "b's", 'anything', 'typically', 'per', 'enforceable', "a's", 'also', 'one', 'adopted', 'promised', 'something', 'b'], ['promise', 'consideration', 'promisee', 'promises', 'alone', 'promisor', 'something', 'one', 'party', 'forbearance', 'favor', 'gratuitous', 'subject', 'certain', 'refrained', 'specifically', 'detriment', 'exempted', 'free'], ['withhold', 'withholding', 'withholdmiddle', 'withholden', 'withheld', 'withholds', 'refrain', "someone's", 'etc', 'ž', 'with·holds', 'with·hold·ing', 'taxes', 'amp', 'tax'], ['encroachment', 'en*croach"ment', 'encroachments', 'another', 'silently', 'encroaching', 'establishment', 'tenant', 'lord', 'owes', 'upon'], ['promise', 'promisee', 'consideration', 'forbearance', "b's", 'misa', 'anything', 'one', "a's", 'b', 'enforceable', 'typically', 'act', 'per', 'adopted', 'something', 'also'], ['consideration', 'forbearance', 'promisee', 'promise', 'promisor', 'enforceable', 'detriment', 'undertaken', 'promised', 'lush', 'one', 'j'], ['promise', 'forbearance', 'consideration', 'one', 'stipulate', 'promisor', 'promises', 'enforce', 'detriment', 'undertaken', 'enforceable', 'thereof', 'consisting', 'party', 'accruing', 'promisee', 'promised', 'enforced', 'given', 'else', 'established'], ['benjamin', 'early', 'stephen', 'minnick', 'post-hardcore', 'rock', 'including', '2021', 'january', 'hardcore', 'later', 'self-released', 'metalcore', 'music', 'mine', '2006'], ['encroachment', 'quiet', 'intentionally', 'another', 'members', 'intentional', 'encroaches', 'prescription', 'title', 'late', 'action'], ['promise', "b's", 'forbearance', 'consideration', 'per', 'enforceable', 'promisee', 'something', 'adopted', 'one', 'promissor', "a's", 'anything', 'b'], ['institution', 'goddess', '2,340', 'education', '6', 'males', 'affiliated', 'sankari', 'also', 'years', '3,228', 'population', 'neighbouring', '75.49', '4,776', 'council', 'higher', 'beds', '2,436', 'village', 'females'], ['enforce', 'promise', 'provided', 'consideration', 'promisee'], ['loud', 'additional', 'vocals', 'male', 'singles', 'nashville', 'april', 'house', 'days', 'members', 'editing', 'vocal', 'elmwood', 'june', 'records', 'unilateral', 'vocalist', 'sterling', 'digital', 'mix', 'featuring', 'unauthorized', 'later', 'engineering', 'least', 'may', 'new', '2010', 'park', '750', 'made', 'two', 'sound'], ['consistency', 'group', 'already', 'underscore', 'necessary', 'depended', 'taking', 'inspiration', 'significant', 'customization', 'known', 'parallel', 'features', 'drastic', 'also', "resig's", 'extras', 'several', 'contributors', 'john', 'templating', 'lodash', 'making', 'prompted', 'started', "steele's", '2012', 'end', 'tux', 'changes'], ['objects', 'one', 'provide']]
TOP TOKENS [['tilapia', 'tilapias', 'spawns', 'diameter'], ['tilapias', 'tilapia', 'true'], ['tilapia'], ['tilapias', 'tilapia', 'mouth', 'true', '1992', 'consumption'], ['tilapia', 'tilap', 'cls', 'months', 'africa'], ['tilapia', 'list', 'considering', 'u', '’', '6', 'polyunsaturated'], ['tilapia', 'fresh', 'lipoproteins', 'fats'], ['tilapia', 'kg'], ['tilapias', 'tilapia', 'round', 'sea', 'even'], ['tilapia', 'service'], ['tilapia', 'tilapiine', 'namesake', 'bit', 'genus', 'localities', 'certain', 'however'], ['tilapia', 'tilapinevirus', 'cls', 'may', '641'], ['tilapia', 'tilapias', 'living', 'boneless', 'one'], ['tilapia', 'survive', 'spp', 'zones', 'modification', 'apparently'], ['tilapia', 'tilapiine', 'tilapiini', 'cls', 'either', 'art', 'aquaponics', 'oreochromini', 'egypt', 'due', 'taste', 'sun', 'temperate'], ['tilapias', 'tilapia', 'species', 'mozambique', 'mouthbrood', 'mouthbrooding', 'thus'], ['tilapia', 'tilapiini', 'even', 'poll', 'authorities', 'steatocranus'], ['tilapia', 'findings', 'weight', 'whole', 'prey', 'found', 'farmed', 'methylisoborneol', 'market', 'depending', 'freshness', 'others'], ['tilapia', 'tilapias', 'nile', 'along', 'base', '2004', 'effort', 'phenotype', 'commonly', 'done', 'name', '30', 'interest'], ['tilapia', 'tilapines', 'importer', 'live', 'preserved', 'disease']]
TOP TOKENS [['kneads', 'kneading', 'knead', 'kneaded', 'i’ll', 'cushy'], ['kneading', 'knead', 'kneads', 'cases', 'comfy', 'sure'], ['kneading', 'kneads', 'knead', 'nursing'], ['kneading', 'kneads', 'knead', 'nursing'], ['kneading', 'kneads', 'knead'], ['kneading', 'knead', 'kneaded'], ['kneads', 'kneading', 'knead', '“', 'good'], ['kneading', 'knead', 'strange'], ['kneading', 'knead', 'though'], ['kneading', 'knead', 'kneads', 'kneady', '“', 'go', 'seem', 'takes', 'place'], ['kneading', 'knead', 'two', 'secretion'], ['kneading', 'kneaded', 'no-knead', 'loaf', 'eventually', 'baking', 'creating'], ['kneaded', 'kneading', 'knead', 'stretching', "mother's", 'origin', 'object'], ['kneading', 'knead'], ['kneading', 'kneader', '000', '1', 'volume'], ['kneading', 'knead', 'adults', 'stretching', 'lactation', 'may'], ['kneading', 'kneaded', 'great', 'kneads', 'wear', 'mass', 'subtractive', 'one', 'rinsing', 'blue', 'plasticity'], ['kneading', 'origin', 'trying', 'corroborate', 'association', 'abnormal', 'evidence', 'completion', 'two', 'common', 'purr'], ['kneading', '1981', 'related', 'description'], ['kneading', 'kneader', 'requirement', '28', 'pages', 'november', 'continuous', 'performance', 'dr', 'times', '1']]

Processing features:  76%|███████▌  | 74/98 [35:30<11:10, 27.94s/it]

getting sample prompt forgetting sample prompt for 24289
 24288
getting sample prompt for 24290
getting sample prompt for 24291
getting sample prompt for 24292
getting sample prompt for 24293
getting sample prompt for 24294
getting sample prompt for 24295
getting sample prompt for 24296
getting sample prompt for 24297
getting sample prompt for 24298
getting sample prompt for 24299
TOP TOKENS [['malone'], ['malone', 'malones', 'malone’'], ['malones', 'malone', 'tecumseh'], ['malone', 'arkansas', 'clare', 'alton', 'lancashire', 'northumberland', '1530'], ['malone', 'malones', 'arms', 'including', 'irish', 'emancipation.the'], ['malone', 'r', 'nha', 'ireland'], ['malone', 'death', 'credit', 'result'], ['malone', 'jumper', 'kinder', "soon'cards", 'cls', 'g', 'taken', 'home', 'inventions', 'make', 'ventilation', 'spot', 'lies', 'wednesday', 'grateful', 'lessons'], ['malone', 'maloney', 'st', 'cls', 'bald', 'connaught', 'arkansas', 'john', 'corrupted', 'ohio', 'irish'], ['malone', 'intact', '1906', 'streets', '1902', '’', 'businesses', 'states', 'e', 'city'], ['surname', 'malone', '2000ad'], ['malone', 'healthcare', 'publications'], ['malone', "malone's"], ['malone', 'result', 'final'], ['malone', 'election', "brown's", 'massachusetts', 'venture', '2010', 'said', 'december', 'people', 'district', 'success', '1998'], ['malone', 'border'], ['malone', 'arnold', 'author', 'born'], ['malone', '2016', 'section', '2023', '2022', '2019', 'may'], ['malone', '2009', 'parents', 'nbc', '2011', 'december', 'views', 'awards', 'bostwick'], ['malone', '2019', '2021', '2020', 'delegates', 'shutdown', 'listed', 'life', 'caucus']]
TOP TOKENS [['ichthyofauna', 'palaeoclimatol', 'mus', 'province', 'deposits', '396', 'l', 'biostratigraphy', 'italiani', 'faune', 'verona'], ['water', 'palaeolithic', 'chondrichthyan', 'marivaux', 'elasmobranchs', 'waters', 'fauna', 'coastal', 'system', 'kluiving', 'carcharhiniformes', 'fining', 'faunas', 'one', 'assemblages', 'verpoorte', 'assemblage', 'correlates'], ['ichthyosaurs', 'however', 'agardhfjellet', 'time', 'ichthyosaur', 'svalbard', 'al', 'vertebrate', 'undorosaurus', 'tong', 'g', 'lethaia'], ['demography', 'sea', 'otter', 'otters', 'well', 'estimates'], ['paleoherpetology', 'neues', 'friedrich', 'pfeil', 'ichthyosaurs', 'holzmaden', 'palaontologie', 'sw', 'geologie', 'ichthyosaur', 'sep', 'abhandlungen', 'ichthyopterygia', 'fur', 'eurhinosaurus', 'pp', 'gj', '7'], ['salzgitter', 'ichthyosaur', 'ichthyosaurs', 'stratigraphie', 'palaozoologie', 'academique', 'abteilung', 'du', 'palaeontographica', 'paleontologica', 'saxony', 'la', 'boulonnais', 'bollettino', 'memoires', 'druckenmilleree'], ['waters', 'sea', 'dives', 'pelagic', 'al'], ['0', 'avian', 'otter', '748km', 'downstream', 'birds', 'area', 'predation', 'roche', 'thus', 'however', 'bones', 'otters', 'spawning', 'al', 'palearctic', 'sea', 'fish', 'rabbits', 'prey'], ['fauna', 'abyssopelagic', 'sea', 'teleosts', 'anguilliformes', 'fishes', 'r', 'zoologica', 'sequences', 'sci', 'syst', 'mar', '69', 'elopomorph', 'eel', 'order', 'scripta', '22662120', 'protoanguillidae', 'asahida', 'ichthyol'], ['remains', 'primates', 'dinosaurs'], ['swim', 'sea', 'however', 'washington', 'sharpe'], ['schweiz', 'schweizerische', 'grenzbitumenzone', 'mittlere', 'cephalopoden', 'fishes', 'deposits', 'schnyder', 'mte', 'tessin', '1939', 'paleontologie', 'alps', 'giorgio', 'geologie', 'neues', 'fur', 'switzerland', 'des', 'suisses', 'der', 'abhandlungen', 'palaeontologische', 'sp', 'palaontologische', 'palaontologie'], ['sosva', 'russia', 'langurs', 'langur-e', 'colobinae', 'disambiguation', 'langur'], ['vertebrate', '1982', 'fossil', 'mammals', 'paleontology', 'assemblages', 'cahiers', 'geologischen', 'bovidae', 'j', 'fichter', 'kiessling', 'vertebres', '1969', 'kana', 'g', '1976', 'paris', 'pandey', 'zum', 'les'], ['bodies', 'water', 'county', 'montana'], ['metatherians', 'bunodont', 'mammals', 'novitates', 'systematics', 'paleontologia', '1952', 'fossil', 'history', 'reassessment', 'museum', 'paleogene', 'paleocene', 'de', 'itaborai'], ['ichthyology', '1887', 'theropod', 'vertebrates', 'mammals', 'primates', '2003', 'dinosaurs', 'birds', 'balon', 'paleontology', 'barbour', 'maclaren', 'ambak', '–', '1979'], ['ichthyosaurs', 'ichthyosaur', 'svalbard', 'ichthyosauromorphs', 'vikinghøgda', 'økland', 'al', 'spitsbergen', 'embryos', 'fossils', 'large', 'animal', 'pliensbachian'], ['fauna', 'mammalian', 'quarry', 'mammals', 'biostratigraphy', 'ungulate', 'paleocene', 'mammalia', 'j', 'age', 'america', 'paleogene', 'e0200132', 'science', '80', 'e', '0200132', 'https', 'pone', 'upchurch', '141'], ['water', 'sea', 'fishermen', '2005', 'california', 'island', 'otters', 'otter', 'away', 'swimming', 'states', 'traversing', 'reported', 'shores', 'origins', 'individuals', 'however', 'stomachs', 'species', 'dives', 'fish', 'areas', 'peninsula', 'population']]
TOP TOKENS [['today', 'today’s', 'days/today', 'nowadays', 'use', 'formal', 'ago'], ["today's", 'today'], ['today', "today's", 'general'], ['today', 'convenient', 'function', 'insert', 'real', 'excel', 'value', 'use', 'thus', 'cases'], ['today', 'go'], ['today', 'even'], ['today', 'yesterday', 'want'], ['today'], ['today'], ['today', 'sure', '”', 'could', 'feeling'], ['today'], ['today'], ['today', 'reception', 'generally', 'described', 'kinsella', 'block'], ['today'], ['today', 'instruction', 'stated'], ['today', 'particular', 'publication', 'topics', 'green', 'phenomenology', 'work', 'published', 'current', 'contemporary', 'policy', 'reviews'], ['today'], ['today'], ['today', 'show', 'producer', 'radio', 'team', 'united', 'current', 'states', 'american', '1930', 'publisher'], ['today', '2020', 'external', 'release', 'links', 'titled', 'eder', 'album', 'production', 'exiting', 'original', 'may', '1961', '43000', 'single']]
TOP TOKENS [['fact', 'facts', 'interesting', 'learned', 'sharing', 'know', 'focusing', 'information', 'share', 'related'], ['fact', '1', 'wonder'], ['incomes.fact', 'there.fact', 'facts', 'romans.fact', 'culture.fact', 'attending.fact', 'more.fact', 'fun', 'fact', '1fact', '6'], ['fact', 'hinted', 'learn', 'know', 'favorite', '1'], ['fact', 'forget', 'fun'], ['fact', 'fun'], ['fact', '1', 'half', 'fully', '6962', 'named'], ['fact', 'despite', 'pepper'], ['facts', 'learn'], ['declaration.fact', 'freed.fact', 'kpelle.fact', 'monroe.fact', 'facts', 'man.fact', 'warbler.fact', '5', '1fact', '6', 'fact', '4', 'fun'], ['fact', 'newdow', 'facts', 'fight', 'g-apd', 'technique', 'biology', 'factnet', 'telescope', 'observatory', 'illinois', 'change', 'transcription', 'fair'], ['facts', 'friends', 'review', '3', 'official'], ['facts'], ['facts', 'song', 'post-hardcore', 'fact', 'album', 'japanese', 'band', 'real', 'h.e.r'], ['facts', '2005', 'established', 'competitor'], ['facts'], ['fact', 'set', 'facts', 'astronomical', 'english', 'circumstance', 'aspects', 'personal', 'point', 'repeatable', 'contains', 'obsolete', 'one', 'case', 'cls'], ['facts'], ['facts', 'work', '1946'], ['fact', 'full-time', '2007', 'inspiring', 'staff', 'new', 'overseas', 'london', 'group', 'york', 'uk', 'spain']]
TOP TOKENS [[], ['satoshis', 'satoshi', 'bitcoin'], ['cryptocurrency', 'satoshis', 'cryptocurrencies', 'bitcoin', 'us'], ['satoshi', 'satoshis', 'bitcoin'], ['sats', 'usd', '“sats”', 'satoshis', 'satoshi', 'bitcoin', 'bitcoin’s'], ['snickers', 'cracker'], ['sats', 'satoshis', 'satoshi', '000', 'usdsat'], ['satoshi', 'millisatoshiwhich'], ['101qs.com'], [], ['solvers'], ['十'], ['cougar'], [], [], [], ['san', 'yuen'], [], [], []]
TOP TOKENS [['community', 'many', 'due', 'topic', 'sometimes'], ['bar', 'singing', 'typesetting', 'directly', 'chorus', '2', 'sections', 'based', 'allowing', 'conveniently', '8', 'lyrics', 'etc', 'time'], ['mactech', 'realm', "other's", 'along', 'xplain', 'either', 'principle', 'e', 'yes', "what's", 'com'], ['ideas'], ['ideas'], [], ['community', 'along', 'sheet'], ["nature's", 'one', 'efforts', 'must', "experiment's", 'pantheon', 'meanwhile', 'also', 'tried', 'attempting', 'dr', 'another', 'chain', 'kind', 'concluded', 'next', 'time'], ['stellar', 'cryptocurrencies', 'moment', 'however', 'thus', 'also', 'due'], ['http', 'official', 'page', 'home', 'exist', 'firstname', 'gnu', 'com', 'licenses', 'example', 'precise', 'org', 'calendar', 'nongnu', 'world', 'zarathushtrian', 'year'], ['trackandfieldnews', "men's"], ['education', 'works', '14'], ['committee', 'engineering', 'chemists'], ['official'], ['systems', 'institute', 'synthetic', 'immune', 'new', 'fundamental', 'ph', 'complex', 'cell', 'signaling', 'pioneer', 'knowles', 'could', 'make', 'approaches', 'networks', "lim's", 'also', 'engineering', 'predictively', 'became', 'well', 'work', 'helped', 'general', 'information', '–', 'particularly'], ['xuhui', 'shanghai', '南', 'caoxi', "dong'an"], ['leavitt', "leavitt's", 'stellar', 'pyxidis', 'science', '1913', 'pyxis', 'developed', '—', 'occurred', 'one', 'also', 'sky', 'observatory', 'linearly', 'society', 'would'], ['xi', 'business', 'performance'], ['game', 'community'], ['official']]
TOP TOKENS [[], [], [], [], [], ['8'], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['feudalism', 'feudalisms', 'feudal'], ['feudalism', 'feudal', 'feudallsm', 'vassals'], ['feudal1', 'feudalism', 'feudal', 'feudalistic', 'feudalist', 'vassals'], ['feudal', 'feudalism', 'cls'], ['feudal', 'feudalism', 'feudalist', 'cls'], ['feudal', 'feudalism', 'feudalistic', 'cls'], ['feudalism', 'feudal', 'term'], ['feudalism', 'feudal', 'feudalistic'], ['feudalism', 'feudal', 'feudalistic'], ['feudalism', 'feudal', '“feudal”', 'word', 'know', 'term', 'society'], [], ['feudalism', 'feudal', 'society', 'fiefdom', "lords'rights"], ['feudalism', 'feudal', 'word', 'cls', 'society', "l'esprit", 'derives', 'mimicked'], ['feudalism', 'feudal'], ['feudal', '15'], ['feudalism', 'found', 'largely'], ['feudalism', 'feudal', 'prc', 'western', 'described', 'disfavor', 'conquered'], ['feudal', 'feudalism', 'feudalwesen', 'lord', 'vassal', 'cls', 'fiefs', 'benefizialwesen', 'vassals', 'one'], ['feudalism', 'feudal', 'form', 'societies'], ['feudal', 'included']]
TOP TOKENS [['johnson', 'reeder', 'bates', 'budson', 'killiany', 'anderson', 'decarli'], ['johnson', 'reeder', 'bates', 'budson', 'killiany', 'anderson', 'decarli'], [], ['order', 'character', 'rye'], ['example'], ['ahead'], [], ['characterizations', 'include', 'briefings', 'say', 'graham', 'president', 'recall'], ['information', 'viewpoint', "speaker's", 'student', 'actions', 'either', 'part'], ['key', 'functions'], ['early', 'casting', 'cast', 'announced', "kirkman's", 'q', 'later', 'ritter', 'joined', 'wife', 'hookstraten', 'shore', 'march', 'respectively', 'hannah', 'month', 'wright', 'characters', 'role', 'one', 'business', 'saying', 'also', 'explaining', 'november', 'well', 'staff'], ['woman', 'actually', '—', 'tells', 'says', 'blind', 'also'], ['room', 'told', 'supplies', 'informed', 'rapes', 'blank', 'efforts', 'keep', 'one', 'iv', 'apparent', 'casing', 'part', 'later', 'scene', 'instructions', 'along', 'becomes', 'rips'], ['picks'], [], ['scion', 'melissa', 'named', 'froelich', 'mentions', 'rumored', 'reveals', 'tells', 'character', 'back', 'understanding', 'revealed', 'vision', 'speculates', 'meanwhile', 'also', 'expected', 'offhandedly', 'later', 'thereafter', 'dying', 'fisherman', 'vacation', 'bludgeon', 'skull'], ['conspires', 'unfold', 'world', '—', 'betrayals', 'simplistic', 'ways', 'many', 'surprising', 'even', 'misunderstandings', 'enough', 'happens'], ['dr', 'unaware', 'reveals', "david's", 'also', 'benny', 'leaving', 'life', 'poole', 'turns', 'years', 'delve', 'phily', 'revealing', "syd's", 'lenny', 'however', 'monster', 'concludes', 'cube', 'may'], ['familiarize', 'embody', 'wiser', 'experience', 'older', 'enjoyable', 'projects', 'job', 'well', 'meant', 'including', 'boulton', 'circumstances'], ['webb', 'hacker', 'play', "kalloor's", 'cast', 'added', 'also', 'would', 'announced', '10', 'role', 'reprising', 'series', '15']]
TOP TOKENS [['cheerleaders', 'cheerleader', 'cheerleading', 'choice', 'typical', 'days'], ["cheerleader's", 'cheerleaders', 'cheerleader', 'cheerleading', 'cheer'], ['cheerleader-is', 'cheerleading', '“cheerleading', 'cheer'], ['cheerleaders', 'cheerleader', 'cheerleading', 'cls', 'skills', 'dancing'], ['cheerleader', 'cheerleading', 'cls', 'performances'], ['cheerleader', 'cheerleading', 'cheer', 'cls'], ['cheerleaders', 'cheerleading', 'cheerleader', 'cls', 'cheer', 'ironically'], ['cheerleaders', 'cheerleading', 'say', 'cls'], ['cheerleaders', 'cheerleading', 'say', 'cls'], ['cheerleaders', 'cheerleader', 'cheerleading', 'cheer', 'athletes'], ['cheerleader', 'cheerleader(s', 'cheerleading', 'cheerleaders'], ['cheerleading', 'cheer', 'disambiguation'], ['cheerleading', 'cheerleader', 'cheerleaders', 'cheer', "cheerleaders'athleticism", 'team', 'competitive'], ['cheerleading', 'cheerios', 'cheerio'], ['cheerleaders', 'cheerleader', 'cheerleading', 'cheer'], ['cheerleading', 'cheerleaders', 'cheerleader', 'cheer', 'competitive', 'hilarie', 'take', 'nature'], ['cheerleading', 'cheercon', 'cheerbrandz', 'cheer', 'competitive', '2000'], ['cheerleaders', 'cheerleading', 'cheer', 'star', 'upcoming'], ['cheerleader', 'cheerleading'], ['cheerleaders', 'cheerleader', 'cheerleading', 'cheers']]
TOP TOKENS [['scramjet', 'scramjets'], ['scramjet', 'scramjets', 'ramjet'], ['scramjet', 'turbojets', 'hence', 'able', 'ramjet', "a'standard'ramjet", 'rather', 'airflow', 'velocity', 'concomitant', 'combustor'], ['scramjet', 'scramjets'], ['scramjets', 'scramjet', 'ramjet', 'engine', 'spaceflight'], ['scramjet', 'scramjets', 'launches'], ['scramjet', 'scramjets', 'launches'], ['scramjet', 'scramjets', 'launches'], ['scramjet', 'scramjets', 'chamber', 'ramjets'], ['scramjet', 'ramjet'], ['scramjets', 'scramjet', 'milliseconds'], ['scramjet'], ['scramjets', 'scramjet', "scramjet's", 'scram'], ['scramjet', 'scramjets', 'scram', 'ramjet', 'ramjets', '5', 'supersonic', 'things'], ['scramjets', 'scramjet', 'ramjets', 'turbojet', 'ramjet', 'provides', 'since'], ['scramjets', 'scramjet', 'ramjet'], ['scramjet', 'scramjets', 'one', 'stringent', 'range', 'oxygen'], ['scramjets', 'scramjet', 'ramjet', 'engine', 'ramjets'], ['scramjet', 'scramspace', 'hypersonic', 'mach', 'turned', '8'], ['scramjet']]
TOP TOKENS [['ceramic', 'ceramics', 'components', 'porcelain', 'years'], ['ceramic', 'ceramics', 'difficult', 'adiabatic', 'material'], ['ceramic', 'ceramics', 'wear'], ['ceramic', 'ceramics'], ['ceramic', 'ceramics', 'porcelain'], ['ceramic', 'ceramics', 'easily', 'microelectromechanical'], ['ceramic', 'ceramics', 'conductivity', 'norm', 'etc', 'engineering'], ['ceramic', 'ceramics', 'nature'], ['ceramic', 'ceramics', 'corrosion', 'fact', 'toughness', 'accelerators', 'systems', 'nozzles'], ['ceramic', 'ceramics', 'developing', 'tech', 'environments', 'hydroxyapatite'], ['ceramics', 'ceramic', 'membrane', 'bonds', '1912–1913'], ['ceramic', 'ceramics', 'resonators'], ['ceramic', 'ceramics'], ['ceramic', 'ceramics', 'synthesis'], ['ceramic', 'ceramics'], ['ceramic', 'celsius', 'advantage', 'hot', 'hand', 'found'], ['ceramic', 'ceramics', 'use', 'industry', 'adiabatic', 'difficult', 'deform'], ['ceramics', 'ceramic', 'all-ceramic', 'engines', 'commercial'], ['ceramic', 'ceramics', 'typical', 'toys', 'resonator', 'receivers', 'piezoelectric', 'devices', 'connections', 'device', 'equipment', 'due'], ['ceramic', 'ceramics', 'control', 'rate']]

Processing features:  77%|███████▋  | 75/98 [36:07<11:46, 30.72s/it]

getting sample prompt for 24300
getting sample prompt for 24301
getting sample prompt for 24302
getting sample prompt for 24303
getting sample prompt for 24304
getting sample prompt for 24305
getting sample prompt for 24306
getting sample prompt for 24307
getting sample prompt for 24308
getting sample prompt for 24309
getting sample prompt for 24310
getting sample prompt for 24311
TOP TOKENS [[], ['reading', 'think'], [], [], ['access'], ['fun', 'take', 'certainly', '’', 'project', 'repetition'], [], ['something'], ['intuitively'], ['understanding', 'also', 'today', 'rise', 'ones', '’', 'yes', 'humanity'], [], [], [], ['ones', 'good'], ['therefore', 'found', 'designated', 'caves', 'believed', 'inkwells', 'come', 'essenes', 'used', 'well'], ['åre', 'are-taupota', 'm2', 'icao', 'activated'], ['rides', 'television', 'album', 'series', 'uk', 'disambiguation', 'u.s'], ['use', 'editors', 'opt', 'proceedings', '1995', 'gl', 'gustavii', 'jm', 'textrelease', '1', 'presentation', 'set', '2005', '14', 'j', 'version', 'bethesda', 'visited', 'publish', 'series', 'perspectives', '2003', 'preparation', '–', 'jr', 'preservation', 'z39', '2007', '6'], ["scribner's", 'works', 'destroyed', 'become', 'entitled', 'though', "twain's", 'period', 'controversy', 'version', 'made', 'disapprovingly', 'years', 'two', 'time', 'original', 'reconstruct', 'several'], ['postponed', 'elections', 'country', 'march', 'place', 'government', 'held', 'entire', 'would']]
TOP TOKENS [['organization', 'organizations', 'societies', 'fraternal', 'form', 'fraternity', 'cls', 'groups', 'fraternities', 'operates', 'together'], ['association', 'society'], ['organization', 'organization”', 'organizations', 'storied', 'ones', 'body', 'membership'], ['organization', 'organizations', 'societies', 'founded', 'society', 'rosicrucians', 'existed'], ['organization', 'organizations', 'fraternal', 'fraternities'], ['organizations', 'organization', 'new', 'association', 'fraternal', 'founded', 'interest', 'organized', 'similar', 'creating', 'growing'], ['organization', 'organizations', 'founded', 'originally', 'meetings', 'society'], ['organization', 'also', '‘', 'aim', 'associations', 'association', "teachers'voluntary", 'interests'], ['organization', 'organizations', 'arisen', 'interests', 'founded', '”'], ['organization', 'association'], ['organizations', 'established', 'professional', 'associations', 'association'], ['organizations', 'societies', 'association', 'associations', 'society', 'federation'], ['organization', 'organizations', 'define'], ['organizations', 'societies', 'american'], ['organizations', 'based', 'associations', 'established', 'society', 'endocrinology', 'medical', 'association'], ['organizations', 'organization', 'established'], ['organization', 'organizations', 'associations', 'based'], ['organizations', "veterans'organizations", 'association', 'established'], ['organizations', 'association', 'organisations'], ['organisations', 'organisation', 'organizations', 'association', 'founded', 'societies']]
TOP TOKENS [['given', 'gives', 'e.g', 'remember', 'sentences'], ['rope', 'lace', 'fasten', 'v', 'fix'], ['give'], ['say', 'oo', 'consonant.in', 'university', 'u', 'pronounced', 'since', 'hence', 'one'], [], ['let', 'succeed', 'much', 'time', 'first'], ['www', 'make', 'bbc', 'aljazeera'], ['quality', 'related', 'ha-swcnt', 'assess', 'optimized', 'qualitative', 'compared', 'gives', 'g/d', 'based', 'hand', 'developed', 'widely', 'sample', 'reliable.on', 'used', 'ha-swcnts', 'swnt', 'etc', 'd/g’', 'occurs', 'growth', 'certain', 'might', 'shows', 'shown'], ['necessary', 'chain', 'used', 'mean', 'example', 'anything', 'town', 'say', '’', 'put', 'words', 'openings', 'wants'], [], [], ['art', 'film', 'entertainment', 'ave', 'artists', 'vehicle', 'aviation', 'avé', 'alpha-3', 'choir', 'american', '639', 'california', 'engineers', 'vernacular', 'media', 'average', 'first', 'vocal', 'ne', 'dialect', 'powervm', 'francisco', 'technology', 'engine', 'togo', 'seattle', '1832–1901', 'iso', 'community', 'led', 'advanced'], ['albums', 'recorded', 'engineering', 'best', 'assistance', 'charts', 'number', 'list', '–', 'production'], ['band', 'novel'], ['produced', 'number', 'song'], ['disambiguation'], ['held', 'boys', 'soon', 'happening', 'jubilee'], [], ['nominees', 'sources', '1978–79', '1979–80', '1993–94', 'winners', '1994–95', '1989–90', '1982–83'], ['produced', 'albums', 'recording', '–', 'charts']]
TOP TOKENS [['sexism'], ['sexist', 'sexism', 'puts', 'therefore'], ['sexist', 'sexism', 'sexisms', 'course', 'key', 'experiences'], ['sexist', 'sexism', 'unmistakably', 'didactically', 'behind', 'lesson', 'critic', 'heiress', 'image'], ['sexism', 'treat', 'nation—even'], ['sexism', 'another', 'less', '17', 'women’s', 'china'], ['sextus', 'http://www.credoreference.com/entry/conscitech/sextant', 'sextant', 'longitude'], ['sextus', 'http://www.credoreference.com/entry/conscitech/sextant', 'sextant', 'longitude'], ['sexist', 'sexism', '’', 'sure', 'make', 'existence', 'certain', 'notice'], ['sexism', 'amid', 'well', 'first', 'pangs', 'cls', 'violence', 'frustrations', 'white'], ['sexton', 'presence', '2022'], ["sexton's", 'sexton', '1984', 'u21', 'first', 'management', 'led', 'f', '–', '1957', 'luton'], ['sexton', "sexton's", 'next', '9', 'expatriate'], ['sexton', "sexton's", 'remain', 'census-designated', 'history'], ['sextus'], [], ["sexson's", 'oregon', 'sexson', 'fine', '2023', '2014', 'lived'], ['sexton', '1907–1935'], [], ["sexton's", 'sexton', '54', 'league', '2007', 'natalie', '2009', 'decrette', 'july', 'charles', '1976', 'st', 'ellis']]
TOP TOKENS [['sheet', 'worksheets', 'data', 'workbook', 'cell', 'button', 'worksheet', 'cells', 'screen'], ['worksheets', 'box', 'worksheet', 'excel', 'cells', 'cell', 'columns', 'click', 'tab', 'data'], ['worksheet', 'cells', 'excel', 'worksheets', 'sheet', 'data', 'workbooks', 'cell', 'spreadsheet'], ['cell', 'workbook', 'sheet', 'worksheet', 'sheet1', 'excel', 'tab', 'sheets', 'tabs', 'worksheets', 'activeworksheet'], ['cell', 'worksheets', 'excel', 'column', 'cells', 'tab', 'shortcut', 'select', 'worksheet', 'command', 'contents', 'specific', 'sheets', 'columns', 'text', 'click', 'use', 'shortcuts', 'row'], ['worksheet', 'columns', 'cells', 'worksheets', 'rows', 'code', 'column', 'cell', 'data', 'excel', 'somebody', 'maybe', 'g8'], ['sheet', 'worksheets', 'tab', 'excel', 'tabs', 'workbook', "sheet's", 'mouse', 'box', 'sheets'], ['worksheets', 'worksheet', 'cell', 'excel', 'workbook', "excel's", 'paste', 'cells', 'zeroes'], ['worksheet', 'cell', 'worksheets', 'box', 'excel', 'worksheet”', 'sheet', 'data', 'workbooks'], ['worksheet', 'labels', 'worksheets', 'cells', 'cell', 'page', 'gridlines', 'box', 'formatting', 'sheet', 'rows', 'hide', 'use', 'select'], ['2023–24', 'results', 'also', 'basketball', 'see', 'style'], [], ['basketball', 'cowgirls', 'team', 'members', 'state', 'play', "women's", 'results', 'coach', 'season', 'division', '3–15', 'style', 'hoyt', 'colspan=9'], ['cells', 'cell', 'workbook', 'sheet', 'column', 'spreadsheets', 'spreadsheet', 'excel', 'data', 'tabs', 'sheets', 'desire', 'table', 'areas', 'putting', 'row', 'book', 'rows', 'blank', 'b2', 'tables', 'changing'], [], ['basketball', 'hornets', 'season'], ['série', 'brasileiro', '2023', 'b', '2024', 'round', 'matches', 'seasons', 'football', 'brazilian', 'postponed', 'teams', 'compete', 'played'], ['colorado', 'worlds', 'bellator', 'tko', 'align', 'derrick', 'center', '4', 'split', 'fight', 'denver', '2'], [], ['2023']]
TOP TOKENS [['paine', '1787', '”', 'read', 'tom', 'alongside', 'woefully', 'remained'], ["paine's", 'paine', '1783', 'government', '1776', 'thomas', 'revolution', 'six', 'wealthy', 'sensation', 'goes', 'like', '37', 'denouncing', 'british', 'wasted'], ["paine's", 'paine', '1797', 'men', 'france', '1809', 'although', 'king', 'states', 'critiqued'], ['paine', "paine's", 'thomas', '—thomas', 'profit', 'revolution', 'deism', 'england', '1737', 'church', 'said'], ['paine', 'phrase', 'thomas', 'knuckle', 'christians', 'lead', 'claim', 'question', '’', 'today'], ['paine', 'vain."paine', 'norfolk', '1792', 'thomas', 'despite', '1791', 'principal', 'franklin', 'start', 'great', 'american', 'rights', 'general', 'inclination".born', "america's", '1790s', 'french', 'critics'], ['paine', 'living', 'recommendation', 'hell', 'thomas', '”', 'ship', 'fever', 'upon', '1776', 'continued', 'need', 'county'], ['paine’s', 'paine', 'thomas', 'english', 'well'], ['paine', "paine's", 'thomas', 'bible', 'enemies', 'war', 'served', 'years', 'wealth'], ['paine', "paine's", 'london', '1791', 'movement', 'monarchy', 'although', 'independence', 'soon', 'thomas', 'emigrated', 'also'], ['1737-1809', 'paine', 'disambiguation', 'patagonia', 'river', 'historically'], ['paine', 'raf', '1919', 'military'], ["paine's", 'two', 'paine', 'months', 'inflated', '909', 'relief', 'players', 'posted', 'nishitetsu', 'hummelstown', 'family', 'chiefs', 'helping', 'life'], ['paine'], ['paine', '1999', '1989', 'roles', '1996', "paine's", '1993', '1991', 'theatresport', 'eight', '2017', 'mysteries', 'secured', 'began', 'commitments', 'work', 'show', 'appearing', 'found'], ['paine', 'paines', '442', '30', 'banker', 'scored', 'points', 'first', 'spanish–american', 'embarrass', 'war', 'sumner', 'olympics', 'withdrew'], ['paine', "paine's"], ['paine', "paine's", 'snowdrifts', 'first', 'headmaster', '12'], ['paine', "paine's", 'thomas', 'boston', 'war', 'venerated', 'reach', "washington's", 'aftermath', 'insurrections', 'opposition', 'considerable'], ['paine', 'new', '1935', 'state', 'fischer', '1961']]
TOP TOKENS [['tulsi'], ['tulsi', 'vaishnavas', 'word', 'herbs', 'urinary'], ['tulsi', 'mind'], ['tulsi', 'tulsi-matham', 'self-purifying'], ['tulsi', 'tulshi', 'plant', 'thulsi'], ['tulsi', 'infections', 'colds', 'ayurvedic', 'magnesium'], ['tulsi', 'tulasi', '“', 'ayurveda', 'purple'], ['tulsi:tulsi', 'tulsi', 'holy'], ['tulsi', 'holy', 'consume', 'however'], ['tulsi'], ['tulsi'], ['tulsi', 'tulsidas', 'greco-roman', 'indian', 'tulli', 'lahiri', 'avatar', 'minister', 'political', '1981'], ['tulsi', 'singh', 'pratima', '1984', 'narhar', 'sauda', 'karm', 'baraf', 'raaj', 'singhji', 'inderjeet'], ['tulsi', 'adult', 'madhesh', '2', 'politics', "jehovah's", 'expatriates', 'finally', '1926'], ['tulsi', 'household', 'tulasi', 'front'], ['tulsi', 'united'], ['tulasi', 'word'], ['tulsi', 'tulasi', 'veda', 'holy', "basil's", 'significance', 'hindu', 'often'], ['tulsi', 'tulsinol', 'tulasi', 'basil', 'called', 'common', 'simple', 'tea', '17', 'one', 'shyam', 'weed', 'commonly'], ['tulsi', '2014', 'chhattisgarh']]
TOP TOKENS [["handmaid's", 'handmaids', 'handmaid', 'jobs'], ["handmaid's", 'handmaid', 'handmaids'], ['handmaid’s', 'handmaid—a'], ['handmaid’s', 'handmaid', '“the', 'weren’t'], ['handmaid’s', "handmaid's", 'handmaid', 'handmaids'], ['handmaids', "handmaid's", 'handmaid', '’', "atwood's", 'papers'], ["handmaid's", 'handmaid', 'handmaids', '’'], ['handmaid’s', 'handmaid', 'tale', 'solely', 'hulu’s', 'gilead'], ['handmaid', 'handmaids', '’', 'tale', 'sense', 'would', 'read', '“', '”', 'anything', 'marthas', 'raving', 'foreign', 'think'], ['handmaid', 'handmaids', '“', '’'], ["handmaid's", 'handmaiden'], ["handmaid's", 'handmaids', 'gain', 'theonomic', 'individuality', 'overthrown', 'among', 'rights'], ["handmaid's", 'handmaids', 'actress', 'new', 'september', '14', 'tale', 'series', 'cls', 'called', '2021', 'wherein', 'season', "atwood's"], ["handmaid's", 'handmaid', 'handmaids', 'functions', 'regard', 'due', 'even', 'atwood', 'researcher', "gilead's"], ["handmaid's", 'handmaid', 'atwood'], ["handmaid's", 'handmaid', '2017', 'tale', 'especially', 'world', 'former', 'made'], ["handmaid's", 'handmaid', 'handmaiden', 'handmaids'], ["handmaid's", 'handmaid', 'first', 'atwood', 'tale'], ["handmaid's", 'instead', 'tale'], ["handmaid's", 'handmaids', 'handmaid', 'joy', 'name', 'husband', 'cls', 'tale', 'called', 'women', 'feigns', 'brewer', 'samira']]
TOP TOKENS [['trademark', '“trademark”', 'www.uspto.gov/trademarkbasics', 'trademark?what', 'trademarks'], ['trademarks', 'trademark', 'practice'], ['trademark', 'trademarks', 'entities'], ['trademark', 'trademarks', 'trademarked', 'lexus'], ['trademark', 'trademarks'], ['“trademark”', 'trademark'], ['trademark', 'competitor’s', 'company’s', 'remember', 'others', 'name'], ['trademark', 'trademarks', 'permission'], ['trademark', 'trademarks', 'inadvertently'], ['trademark', 'trademarks'], ['trademark', 'service', 'trial', 'security'], ['trademark', 'trademarks', 'registered', 'services'], ['trademarks', 'trademark', 'owner', 'using', 'owners', 'owns', 'deceive', 'infringement'], ['trademark', 'trademarks', 'owners', 'entity', 'concerning', 'advice', 'comprehensive', 'service'], ['trademark', 'registered', 'pursue', 'owner'], ['trademark', 'trademarks', 'rights'], ['trademarks', 'trademark', 'name', 'mark', 'specify', 'lowenbrau'], ['trademark', 'application', 'determining', 'registered'], ['trademarks', 'trademark', 'services', 'owners', 'requirements', 'sales', 'registered', 'misled', 'even', 'used', 'block'], ['trademark', 'trademarks', 'trademarked', 'sponsorship', 'law', 'create', 'new']]
TOP TOKENS [['submit', 'judgment', 'another'], ['submission', 'submission.the', '的翻译——'], ['submitted', 'submission', 'submit', 'submitbutton', 'submitting', 'submits', "submitbutton's", 'using', 'appropriate', 'multiple', 'done'], ['submission', 'submit', 'submitting', 'submitted', "word'submission'in", 'submissionsəbˈmɪʃ', 'etc', 'soumission', 'translations', 'word'], ['submit', 'submitting', 'window', 'main', 'form', 'want', 'files', 'let', 'whose', 'select'], ['submit', 'use', 'internet', 'book', 'cls', 'named', 'exactly'], ['submission', 'submitter', 'submits', 'alone', 'word', 'therefore', 'god', 'heard', 'state'], ['submission', 'submitter', 'submits', 'alone', 'word', 'therefore', 'god', 'heard', 'state'], ['submits', 'submitting', 'submission', 'submit', '“', 'submittere', 'notion', '”', 'verb', 'never', 'known', 'undecided'], ['submission', 'submitting', 'submit', 'submitted', 'submissions', 'time', 'make', 'submitassignment1', 'multiple', 'directory', 'run', 'unmodified'], ['submission', 'soumission', 'submitting', 'submits', 'submit', 'submission/submitter', 'superiors', 'artist', 'islamic', 'submitters', '2015', 'alton', 'combat'], ['submits', 'submissions', 'submission', 'submit'], ['submission', 'submissions', 'paper', 'application', 'management', 'submitters', 'electronically', 'submitter', 'processing', 'present', 'rate'], ['submit', 'submission', 'woman', 'full', 'ejaculations', 'bondage', 'sexual', 'prostitution', 'choose', 'include', 'type', 'may', 'women'], ['submit', 'submissions', 'submitting', 'submission', 'submitted', 'submitters', 'asked', 'entries', 'kind', 'managing', 'academic'], ['submission', 'management'], ['submission', 'submissions', 'submitted', 'submit', 'page', 'order', 'date', 'pertaining', 'regarding', 'online'], ['submit', 'e', 'toolin', 'pitchshifter', 'artwork', 'stuart'], ['submissions', 'submission', 'existing', 'etc', 'damage', 'defeat', 'anklelocks', 'rear'], ['submit', 'submitit/listbot', 'internet', 'created', 'easily', 'partners', 'started', 'inc', 'friends']]
TOP TOKENS [['quraysh', 'qurayza', 'ibn', 'disquieting', "defenders'strategy", 'representatives', 'according', 'besieging', 'meant'], ['quraysh', 'tribe', 'even', 'old', '”', 'swear'], ['quraysh', 'qurayshi', "quraysh's", 'umayyad', 'khuzayma', 'century', 'قريش', 'traditional', 'islam'], ['quraysh', 'qurayzah', 'found', 'unconditionally', 'message', 'henceforth', 'bani', 'increased', 'discomfiture'], ['quraysh', 'qurayzah'], ['quraysh', 'qurayza', 'besieging', 'overtly', 'serjeant', 'medina'], ['quraish', 'even', 'prophet', 'muhammad', 'hands', 'pbuh', 'umayyah', 'muslims', 'muslim', 'zahrah', 'tribe', 'disbelievers', 'allah'], ['quraish', 'elapsed', '1', 'qureshite', 'among', 'talhah', 'except', 'pp', 'days'], ['quraishi', 'quraish', 'point', "from'aqanqal", 'gain', 'muslim', 'present'], ['quraiza', 'qurayza', 'sow', 'approached', 'chief', 'bani', 'arrived', 'needed', 'infiltrator', 'go'], ['qureshi'], ['quraysh', 'qurayza', 'respectively', 'besieging', 'thus', 'muhammad', 'would', 'instigated', 'initially'], [], ['quraysh', 'qurayza', "qurayza's", 'either'], ['qurayza', 'qureshi', 'fighting', 'khaybar', 'quraytha', 'qurayzah', 'negotiations', 'however', "muhammad's"], ['qurayza', 'unconditionally', 'kohanim', 'khordadbeh'], ['quraysh', 'attacking', 'hotheadedness', 'unconcerned', 'reportedly', 'stopped', 'name', 'side', 'medina', 'caravans', 'time', 'merchants', 'approving'], ['quraysh', 'quraish', 'namely', 'employed', 'women', 'order', 'extending', 'contravention', 'however', 'offered', 'incite', 'one', 'gather', 'signatory'], ['qurayza', 'qurayzah', 'quraytha', 'quraiza', 'mubarakpuri', 'though', 'safiur', 'judgment', 'pubescent'], ['quraysh', "reputation.'if", 'received', 'neck', 'extent', 'polytheist', 'forsaken', 'khayyat', 'allah', 'walid', 'private', 'sumayyah', "beggary.'if", 'incited']]
TOP TOKENS [['ielts', 'train'], ['ielts', 'writing'], ['ielts', 'wishing'], ['ielts', 'essay', 'writing'], ['ielts', 'uk', 'skill', 'exam'], ['ielts', 'exam', 'uk', 'academic'], ['ielts', 'academic', 'course', 'courses'], ['ielts', 'ieltsgeneralnet'], ['ielts', 'test', 'training'], ['ielts'], ['ielts', 'test', 'academic', 'purposes', 'taker'], ['ielts', 'school', 'test', 'scores', 'academic', 'training', 'score'], ['ielts', 'zealand', 'test', 'academic', '2007', 'system', 'uk', 'band'], ['ielts', 'academic', '57', 'take', 'test', '6', 'tests', 'places', 'whether', 'training', 'however', '77'], ['shults'], ['ielts', 'selt', 'uk', 'test', 'reading'], ['ielts', 'argument', 'takers', 'academic', 'texts', 'places', '1', 'least'], ['shults', 'personnel', '7', 'aviators', '2020'], ['wlts'], ['fults']]

Processing features:  78%|███████▊  | 76/98 [36:36<11:04, 30.22s/it]

getting sample prompt forgetting sample prompt for 24313
getting sample prompt for 24314
 24312
getting sample prompt for 24315
getting sample prompt for 24316
getting sample prompt for 24317
getting sample prompt for 24318
getting sample prompt for 24319
getting sample prompt for 24320
getting sample prompt for 24321
getting sample prompt for 24322
getting sample prompt for 24323
TOP TOKENS [['digtcert', 'admgrp'], ['known'], ['optimizer'], [], ['complicate'], ['fuzes', 'fuze', 'vice'], ['tolerant', 'order'], ['speaks', 'one'], ['”', 'dilorenzo', 'link'], [], [], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['lowell', 'charm', 'r', '1885', 'james', 'co', 'nichols', 'brown'], ['lowell', 'lowellrate'], ['lowell', 'states', 'size', 'st'], ['lowell', 'russell', 'chilton', 'school'], ['lowell', "lowell's", '1977', '1953', '1964', 'massachusetts', '1959'], ['lowell', '10-hour'], ['lowell’s', 'lowell', "lowell's", '2002', 'forms'], ['lowell', 'lowell(noun', 'lowellˈloʊ'], ['lowell', "lowell's", 'works', 'carpet', 'day', 'joy', 'family'], ['lowell', 'charm', 'nichols', '1885', 'whittier', '1853'], ['lowell', 'francisco', 'indiana', 'california', 'massachusetts', 'uss'], ['lowell'], ['lowell', "lowell's", 'sawmills'], ['lowell', '1802', '1927'], ['lowell'], ['lowell', '1853'], ['lowell'], ['lowell', 'road', 'hot', 'system', 'clearwater', 'postmaster'], ['lowell'], ['lowell']]
TOP TOKENS [['anna', 'grace', 'put', 'also', '”', 'one', 'get', '18'], ['anna', 'saint', 'prophet', 'prophetess'], ['anna', 'cls'], ['anna', 'regarding', 'list', '28', 'jesus', 'cls', '“', 'zechariah'], ['anna', 'support', 'birth', 'one', 'marriage', 'little', 'nkjv'], ['anna', "gwalchmei's", 'battle', 'swan'], ['anna', 'tradition', 'st', 'thou'], ['anna', 'anna’s'], ['anna', "anna's", 'way', 'see'], ['anna', 'annagcockerille', 'college'], ['anna'], ['anna', 'links', 'external'], ["anna's", 'anna'], ['‘annā', 'anna'], ['anna', 'annavoronova', '2016', 'year'], ['anna'], ['anna', 'spain'], ['anna', '1879–1956'], ['anna'], ['anna', '‘annā']]
TOP TOKENS [['sri', 'sri’s', 'productive'], ['sri', 'making'], ['sri’s', 'sri', 'combined', 'white'], ["sri's", 'sri', 'members', 'established', 'january', 'devices', 'september', 'stanford', 'university'], ['sri', 'based', 'www', '1946'], ['sri', 'spacing', 'dealt'], ['sri', 'sriman', 'srimati', 'shri', 'shrimati', 'writing', 'grammar', 'शरीमान', 'cls', 'prosperity'], ['sri', 'guidelines', 'categories', 'investing'], ['sri'], ['sri', 'shri', 'languages', 'shrimati', 'cls', 'usage'], ['sri'], ['sris', 'sri', 'ssri', 'swiss', 'canada', 'independent', 'serviciul', 'toronto'], ['sri', 'total', '1968', 'also', 'e', 'leslie', 'inception', 'feinler', 'f', 'international', 'l', 'charles'], ['sri', "sri's", 'devices', 'cls'], ['sri', "sri's", 'james', 'cls', 'international'], ['private', 'naa', 'kurradu', '2004', 'chanti', 'indian', 'sri', 'aavida', 'chantigaadu', 'university', '2013', 'nidurinche', 'srinivasa', '2014', '1998', '1994', '2015', 'oka', '2003'], ['sri'], ['sri', 'r.m.t'], ['srim'], ['sri', 'total', '2011', '2014', 'addition', 'space', 'employees', 'international', 'february', '30']]
TOP TOKENS [['classroom', 'classroomthirdly', 'classroomclassroom', 'contexts', 'classroomfuture'], ['classroom', 'classroomthirdly', 'classroomclassroom', 'contexts', 'classroomfuture'], ['classroom', 'classrooms', 'experiences', 'organized', 'managed', 'students', 'organization', 'efficient'], ['classrooms', 'classroom', 'well-run', "room's", 'organized'], ['classroom', 'classrooms', 'language', 'syllables', 'class-room'], ['classroom', 'classrooms', 'creating', 'positive'], ['classrooms', 'classroom', 'constraints', 'overlook', 'offers', 'laptop', 'location'], ['communicator', 'classroom', 'space'], ['classroom', 'subjects', 'represents', 'resources'], ['classroom', 'classrooms', 'concerns'], ['classroom'], ['classroom', 'classrooms', 'types', 'distractions', 'organizations', 'cls', 'learn'], ['classroom', 'resources', 'tips', 'level'], ['classroom', "classroom,'content", 'classrooms', 'time', 'period', 'discussions', 'homework', 'laboratory', 'lessons', 'activities', 'class', 'tasks'], ['classroom', 'classrooms', 'similar', 'day', 'style', 'also'], ['arya', 'dasgupta', 'dutta'], ['classroom', 'also', 'see', 'teacher', 'relays'], ['classroom', 'classrooms', 'organized', 'organizes', 'environment'], ['classrooms', 'classroom', 'class', 'curriculum', 'social', 'run', 'teacher', 'perspective', 'action', '1988', 'lessons'], ['classrooms', 'classroom', 'relocatable', 'room', 'also', 'terminology', 'area', 'hallway', 'hutting', 'space', 'portable', 'home']]
TOP TOKENS [['find'], ["avoid'overthinking", 'sprinting', 'fundamentals', "possible'wrong'movement", 'skill', "for'closed", 'unfortunately', 'albeit', "cognitive'noise'that", 'whereby', 'finally'], ['whenever', 'defence', 'positions', 'complexity', 'bjj', 'part', 'since', '–', 'sophisticated', 'fact', 'rote'], ['however'], ['however'], ['point', 'improve', 'framework', 'becoming', 'however', 'system', 'course', 'see', 'even', 'features'], ['coordination', 'earlier', 'safety', 'one’s', 'basic', 'mediative', 'act', 'self-defense', 'also', 'abilities', 'krav', 'recalled', 'techniques', 'learn', 'maga'], ['white', '1900’s', '“control'], ['essence', 'beginning', 'ways'], ['better', 'skills', '“know', 'responded', 'maga’s', '“the', 'mettle', 'maga', 'krav', 'show-off', 'thing–to', 'you’re', 'him,’', 'you–', '–', 'courteously', 'possible', 'underscored', '“that', 'away', 'de-escalate', 'said', 'it’s', 'haphazardly'], ['best', "saying,'what's", "that's", "parkour?'and", 'confidence', "best?'is", 'head'], ['way', 'unaided', 'principles'], ['orienteering', 'world', 'since', '2013', 'championships', '2015', 'competitors', 'individual', '2010'], ['orienteering', 'confusion', 'use', 'point', 'today'], ['often', 'skilled', 'courses', 'orienteering', 'green', 'older', 'orienteers', 'sports'], ['grunpunkt', 'time', "trotter's", "climber's", '2010s', 'using', 'include', 'r', 'redpointing'], ['course', 'foxtrot'], ['pattern', 'correcting', 'gait', 'bucking', 'rearing'], ['krajicek', '10–7', 'partnered', '7–6(7–5', '0–6'], ['course', 'orienteering', 'e', 'sheet', 'may', 'however', 'example']]
TOP TOKENS [['harrows', 'harrow', 'harrowing', "harrowman's", 'roots'], ['harrow', 'harrows', 'harrowing', 'plowing', 'sowing'], ['harrow', 'harrowing', 'planting'], ['harrow', 'harrowingly', 'harrowed', 'har·rows'], ['harrow', 'harrowing', 'harrows', 'seedlings', 'cls', 'construction'], ['harrow', 'harrows', 'crop', 'ground'], ['harrowing', 'harrows', 'harrow'], ['harrowing', 'harrow', 'plowing'], ['harrow', 'n', 'm.a'], ['harrow', 'harrowed', 'harrows', 'harrowing'], ['harrow'], ['harrow'], ['harrow', '150', 'mayor'], ['harrow', "harrow's", 'cls', 'one', 'middlesex'], ['harrows', 'harrow', 'harrowing', 'agriculture', 'soil'], ['harrow', 'reception', 'group'], ['harrow', 'bloodstain', '2009'], ['harrow', "harrow's", 'campaign', 'office', 'nonetheless', 'greeley', 'measures', '1864', '2004'], ['harrow', 'councillors', "borough's", "university's"], ['harrow']]
TOP TOKENS [['hexateuchproblem', 'grundgesetz', 'deuteronomische', 'payne', '“', 'cf', 'pp', 'als', 'p', 'elohist', 'e', 'others', 'ilc', 'time'], ['acotyledones', 'hypogynous', 'co', 'perigynous', 'monocotyledons', 'ordinate', 'phanerogams', 'epigynous', 'necessary', 'exactly', 'give', 'reason', 'monocotyledones', 'dicotyledones', 'divisions'], ['bibliographica', 'thorntonl', 'ratione', 'studylight', 'biblical', 'pflicke', 'praecepta', 'brothers', 'theologische', 'viteb', 'tce', 'kritiken', 'www', 'cyclopoedia', 'decalogue', 'und', 'necessity', 'org', "for'decalogue", 'etc', 'expositions', '3', 'numerandi', 'lond', 'html'], ['st', "king's", 'vicarage', "souls'college", 'topographical', 'cls', 'e', 'rectory', 'whose', '7', 'extra', '13', 'tything', '£11', 'land', 'dorset', 'glebe', 'containing', 'structure', 'contains', 'inhabitants', 'parish'], ['pauline', 'communities', 'exegete', 'fully', 'exegetical', 'indispensable', 'necessary', 'studies', 'upon', 'culture', 'give', 'us', 'jesus', 'provide', 'home', 'moreover', 'accorded', 'though', 'easter', 'christianity', 'taking'], ['hierarchy', 'gentiles', 'reference', 'substance', 'enjoyed', "the'genuine'apostle", 'testament', 'years', 'e', 'century'], ['supporters', 'supputatio', 'exiguus', 'seine', 'lamb', 'particular', 'clearly', 'und', 'questions', 'certain', 'jahrige', 'morning', 'conclusive', 'cycle'], ['dianae', 'lateinischen', 'epigraphischen', 'gottheiten', 'attributive', 'und', 'deity', 'problematic', 'attributions', 'ambioreneses', 'der', 'account', 'nutrices'], ['burtonupon', 'given', 'many', 'topographical', 'cls', 'wilmot', 'newtons', 'sacheverel', 'esqrs', 'uttoxeter', 'chapelries', 'newton', 'litchurch', 'william', 'c', '2296a', 'sir', 'bart', 'withepol', 'parish', 'two', 'hall', 'w', 'radbourn', 'pole', 'strong', 'containing'], ['cobb', 'armen', 'loc', 'contrary', 'prostration', 'therefore', 'arab', 'cassian', 'joy', 'cit'], ['demoi', 'references'], ['bce'], ['oineïs', 'pergamon', 'references', 'demoi', 'attica', 'euandria', 'site', 'deme', 'places'], ['graeciae', "kiessling's", 'leipzig', 'cambridge', 'teubner', 'theio.com', 'university', 'perseus', '4', 'tzetzes', '1826', 'digital', 'edition', 'litt.d', 'original', 'w.h.s', 'descriptio'], ['references'], ['described'], ['grammarians', 'amphictyonic', 'panathenaea', 'atticans', 'platter', 'undisputed', 'pamboeotia', 'boeotians', 'even', 'trumpeting', 'spear-throwing', 'though', 'character', 'boeotia', 'offerings'], ['antiphons', 'psalms', 'ii', 'chapters', "saints'festivals", 'responsories', 'recital', 'sam', 'psalter', 'correspondingly', 'confessors', 'parts', 'day', 'canticles', 'matins', 'remaining', 'iii', 'elements', 'week', 'made'], ['references', 'trinity', 'corporis', 'sarum', 'alike', 'compounded', 'sanguinis', 'responsory', 'et', 'prayer', 'communionem', 'gall', 'liturgies', 'sept', 'agimus', 'rite', 'xxiv', 'satiasti', 'accedentes', 'iii', 'gelasian', 'scripsit', 'sort', 'later', 'words'], ['isaiah', 'psaltai', 'constantinopolitan', 'μνησθητι', 'apoc', 'μου', 'habakkuk', 'psalter', 'κυριε', 'long', 'given', '–', 'architecturally', 'however', 'even', 'important']]
TOP TOKENS [['basic', 'income'], ['basic', 'income', 'cls'], ['basic', 'income', 'ubi'], ['basic', 'income'], ['basic', 'income', 'lived', 'us', 'boom', 'ubi', 'ambitious'], ['basic', 'income'], ['basic', 'income', 'supporters', 'socialists', 'ubi', 'u', 'implementing', "india's"], ['basic', 'income'], ['basic', 'income', 'ubi', 'lives'], ['basic', 'basic-income', 'income', 'toward', 'ubi', 'many'], ['basic', 'income', 'yet'], ['basic'], ['basic', 'income', "citizen's", 'vanderborght', 'citizens', 'employment', 'universal', 'basica'], ['basic', 'income', 'favour', 'universal', 'ubi', 'propertylessness', 'citizens', 'monthly', 'introduce'], ['basic', 'income', 'though', 'include', 'universal'], ['basic', 'income', 'conducted'], ['basic', 'income', 'unconditional', 'something', 'universal', 'like', 'us', 'work', 'thinking', 'towards'], ['basic', 'level', 'income', 'furthermore', 'around', "sewa's", 'ubi'], ['basic', 'bureaucracy', 'income', "citizen's", 'ambitious', 'second'], ['basic', 'income', "citizen's", 'unconditional']]
TOP TOKENS [['center', "center's", 'trade', 'world'], ['center', 'trade', 'world', 'wtc'], ['center', 'trade', 'world', 'wtc', 'centers', 'wtcs', 'towers', '3'], ['center', 'trade', 'towers', 'wtc', 'world', 'centre', 'centers', 'twin', 'wtcs'], ['trade', 'center', 'world', 'wtc', "towers'replacement", 'tower'], ['center', 'world', 'trade', 'center’s'], ['trade', 'world', 'center', 'wtc'], ['center', 'trade', 'world', 'wtc', 'towers'], ['trade', 'center', 'world', 'wtc', 'tower'], ['world', 'trade', 'center', 'towers', 'wtc', 'twin'], ['center', 'trade', 'world', 'centre'], ['center', 'trade', 'world', 'tower'], ['center', 'wtc', 'trade', 'centers'], ['trade', 'center', 'world', 'wtc', 'tower'], ['center', 'world', 'trade', 'centers'], ['world', 'center', 'trade', "center's", 'wtc', 'towers'], ['center', 'trade', 'world', 'wtc', 'tower'], ['center', 'trade', 'world', 'wtc', 'towers', 'tower'], ['center', 'trade', 'wtc', 'world', "building's"], ['center', 'world', 'trade', 'wtc']]
TOP TOKENS [['5', 'gan', 'pu3', 'mu', '2', 'bi', '4', 'year', 'rev', 'ak', 'kam', 'ka', 'tablets', 'ka9', 'us2'], ['6', '5', '2', 'pow3', '3', 'exponent2', '10', 'look', 'pow', 'math', '25', 'function', 'pow2'], ['stewards', 'men', '−|the', 'shown', '05:44', '5', 'though', 'calendarsof', 'calendars', 'difference', 'sun', 'reckoning', 'days', 'year', 'middle-earth', 'long'], ['notation', 'generally', 'current', 'windings', 'notice', 'one', 'fig', '2', 'transformers'], ["or'b", 'g', "or'a", "in'f", 'ansi', "in'e", 'numeric', 'see', 'unit', 'written', 'precision', '–'], ["or'b", 'g', "or'a", "in'f", 'ansi', "in'e", 'numeric', 'see', 'unit', 'written', 'precision', '–'], ["天'heaven'like", "for'heaven", "八'eight'over", '11', 'script', 'khitan', "for'eight'and'great'not", "since'khitan'appears", '18', 'chinese', '22', 'scripts', 'texts', 'китаи', 'two', '104', "大'great'to", 'equivalents', 'e', 'hand'], ["there's", "thing's", 'guy', "who's", 'newspapers', 'underappreciated', 'get', 'got', 'course', 'famous', 'salinger', 'reading', 'usually', 'inward', 'positive', 'appears', 'therefore'], ['vərəθra', 'narəm', 'unk', 'spanəm', 'acc', 'gauuam', 'nərəs', 'starəm', 'zəma', 'plur', 'janəm', 'gavam', 'inst', 'dəng', 'sing', 'yav', 'masc', 'gen', '”', 'ghne', 'nom', 'oav', 'zəmat', 'earth', 'dat'], ['1', '2', 'mu', 'ak', 'natn', '3', 'us2', 'nig2', '27', 'ka', 'bi', '324', 'hul', '231', 'rev', '385', '293', '4'], ['external', 'papua', 'australia', 'new', 'guinean', 'links', 'stats', 'pastplayers', 'expatriate', 'wingers', 'references', 'profile', '→', 'player', 'rugby', 'sportspeople', 'baistand', 'archived', 'players', 'web', 'archive'], ['na', '–', '—'], ['features', 'alexander', 'plays', 'heading'], ['v', 'teacher', 'street', 'recipient'], ['external', 'links', 'club', 'football', 'association', 'profile', 'footballers', 'midfielders', 'references', "men's", 'rus', 'people', 'births', 'ukrainian', 'expatriate', 'fc', 'sportspeople', 'players', 'living', 'career'], ['acted', 'people', 'associated', '50', '000', "selvaraghavan's", '2013', '2012'], ['technicians', 'utsavam', 'star', 'mytamilmovie.com', 'state', 'raanjhanaa', 'awards', 'honours', 'award', 'writer', 'male', 'weeklies', 'vanitha', 'acting', 'leading', 'chennai', 'actor', 'times', 'vijay', '2011', 'behindwoods', '2014', 'national', 'honour', 'actors', 'academy', '2012', '2015', 'filmfare', 'special', 'vikatan', 'tamil', 'year', '2018', 'two', 'nadu', '–', '2017'], [], ['discourses', 'text', "bing's", 'veith', 'unschuld', 'see', '–'], ['мистецтвознав', 'мистецтво', 'забашта', 'мистецтва', 'нан', 'т', 'ред', 'фольклористики', 'м', 'століття', 'історія', 'степовик', 'р', 'ін', 'украінського']]
TOP TOKENS [['chiny', 'philocomasium', 'whomever', 'sure', 'assault', 'go', 'various', 'well'], ['shh', 'creak', 'us', 'rest', 'hah', 'step', 'come'], ['bringing', 'swiftly', 'coming', 'sudden', 'trifle', 'unraveled', 'feverish', 'clanged'], ["there's", 'dang', 'thing', 'exertion', 'gibbers', "will'appen", 'da'], ['whomps', 'several', "back's", 'times', 'quietly'], [], ['cavern', 'tramping', 'like', '”', 'intrude', 'cleverly'], ['began', 'every', 'alive', 'cacophony', 'best', 'point'], ['fellows', "that's", 'least', 'right', 'time'], [], ["group's"], ['ease', 'extremely'], ['voracious', 'incessantly', 'rest'], ['u', 'buttocks', '–'], ['chasm', 'carpathian', 'caves', '1992', 'perversion', 'lord', 'first', 'afterwards', "band's", 'however', 'late', 'winds', 'also'], [], ["sabretooth's", 'short', 'first'], ['metal', 'unimaginable'], ['juvenile', 'gratuitous', 'uses', 'soon'], ["euronymous's", 'euronymous', 'hellhammer', 'ecclesiastics', 'even', 'broad', 'prefix', "metal's", 'whose', 'inherent', 'contradictions', 'parts', 'time']]

Processing features:  79%|███████▊  | 77/98 [37:06<10:30, 30.01s/it]

getting sample prompt forgetting sample prompt for 24325
getting sample prompt for 24326
 24324
getting sample prompt for 24327
getting sample prompt for 24328
getting sample prompt for 24329
getting sample prompt for 24330
getting sample prompt for 24331
getting sample prompt for 24332
getting sample prompt for 24333
getting sample prompt for 24334
getting sample prompt for 24335
TOP TOKENS [['nsf', 'billion'], ['nsf', 'useful', 'www', 'http'], ['nsf', 'useful', 'www', 'http'], ['running', 'nstask', 'default', 'differs'], ['nsf', 'useful', 'http', 'www', 'billion'], ['nscope', 'nscope’s', 'range', 'breadboard', 'workbench'], ['nsdate', 'nslocale', 'knows', 'nstimeinterval', 'uses', 'nsdateformatter', 'particular', 'use', 'instance', 'one', 'want', 'nsdatecomponents', 'nscalendar', 'date', 'always', 'first'], ['nslookup', 'servers', 'press'], ['nscd(8', 'nscd', 'nscd.conf(5', 'nss', 'etc/nscd.conf', 'getpwnam(3', '2012-05-10', 'http://www.kernel.org/doc/man-pages', 'see', 'getgrgid(3', 'provides', 'give', 'nonstandard', 'etc/resolv.conf'], ['nsf', 'http', 'awards'], ['nsp1–nsp6', "intel's", 'nsp', "people's", 'programme', 'party', 'polysaccharide', 'franchisee', 'pokret', 'refer', 'singapore', 'may', 'nsp4', 'us', 'fiber'], ['1976-1985', 'code', 'shalev', 'nso', 'technicians', 'u.s.a', 'safe', 'several', '639-3'], ['nsl', '1974–1980s', 'group', 'ns1', 'disambiguation', 'government', 'refer', 'may'], [], ['nspf', 'refer'], [], ['nssf'], ['nsel'], ['sydney', 'nsl', 'northern', 'ns1', 'nsi', 'secondary', 'population', 'intelligence', 'neurological', 'india', 'nsí', 'outlying', 'economy', 'institute', 'various', 'security', 'former'], ['system', 'nsd', 'may']]
TOP TOKENS [['snp', 'snps', "that's"], ['snp', 'snps', 'including', 'mom'], ['snp', 'snps'], ['snp', 'snps', 'snpedia', 'fact', 'people', 'various'], ['snp', 'snps', 'snpedia', 'fact', 'people', 'various'], ['snps'], ['snps', 'snp', "person's"], ['snp', 'genesnp', 'nucleotide', 'also'], ['snp', 'snps', 'dbsnp'], ['snp', 'snps', 'dbsnp', 'u', 'cls'], ['snp', "sinopec's", 'shining', 'electrical', 'bystrica', 'research'], ['gnp', 'nottingham'], ['hnp', 'power', 'international', 'huaneng', 'railway'], ['pnp', 'upnp', 'planning', 'newport', 'organizations', 'requiring', 'pueblo', 'configuration', 'del', 'national', 'peruvian'], ['wnp'], ['nnp'], ['jnp', 'japanese'], ['vnp', 'railway'], ['snp', 'snps'], ['mt-snps', 'mt-snp', 'snp', 'y-snp', 'snps']]
TOP TOKENS [['erythritol', 'erythritol’s', 'almost', '70', 'table-top', 'supplements'], ['erythritol', 'cholesterol', 'tenths', 'people'], ['erythritol', '60–70', 'non-hygroscopic'], ['erythritol', 'calories', 'carbohydrates', 'fat||0', 'sugar'], ['erythritol', 'urine'], ['erythritol', 'erythrite'], ['erythritol', 'much', 'u.s', 'partially', '95', 'yeast'], ['erythritol', '13', 'glycemic', '2', 'sucrose'], ['erythritol', '”'], ['erythritol', 'people', 'hygroscopic'], ['erythrose', 'd-erythrose', 'erythritol', 'group', 'ἐρυθρός'], ['erythrobacteraceae', 'erythrobacter', 'et', 'dokdonensis', 'al'], ['erythrinus', 'erythrinidae'], ['erytholus', 'affinities', 'ediacaran'], ['erythritol', 'atp:erythritol', 'd-erythritol'], ['erythritol:nadp', 'erythritol', 'd-erythrulose', 'erythrulose'], ['erythraea', 'erythraean', 'erythrae', 'erythraian'], ['erythrinus', 'erythrinidae', 'gottlob', 'undescribed', 'major', 'paraná—paraguay', 'elieser'], ['erythrae', 'erythrai'], ['erythrae', 'erythraea', 'erythraean']]
TOP TOKENS [['suites', 'first', "bach's", 'clavichord'], ['mac', 'computer', 'pro', 'rstudio', 'appear'], ['smart', 'http', 'debianedu', 'debian', 'wiki'], ['francis', 'wide', 'first', 'impossible', 'turbine', 'cls', 'efficienlty', 'also', 'range', 'design', 'vanes', 'order'], ['kaplan', 'tight'], ['suites', 'first', 'clavichord', 'calls', '1', 'appellation', 'usually', 'however', 'cls', "bach's", 'nos', 'one', 'two', 'likewise', 'although'], ['e', 'climbers'], ['tutorials', '1', 'guide', 'digitranslator'], ['rstudio', 'lot', 'main', '3', 'beginner', 'first', 'simply'], ['rstudio', '1', 'main', 'lot', 'beginner', 'first', 'decision'], ['z1', 'x1', 'pro', 'kontrol', 'traktor', 'one', 'dj', 'deck', 'enthusiasts', 'touch', "traktor's", 'channel', 'controller', 'soundcard', 'software', 'variations', '3', 'display', 'mk2', 'sep'], ['knights', 'best', 'jaguar', '2farticles', 'web', 'ep', 'renegaderhythms', 'everything2', 'djs', 'archive', 'american', '2fur', 'aspx', 'http', 'sep'], ['suites', 'clavichord', 'first', 'calls', '1', 'appellation', 'however', 'cls', "bach's", 'usually', 'one', 'two'], ['time', 'wiiware', "iphone's", 'player', 'wii', 'video', 'players', 'controls', 'prolong', 'woof', 'touchscreen', "where's", 'kingdom', "remote's"], ['2zyconixzynapszyronzzzep', 'osx', 'warriorzoolzool', 'golfzarcanzardozzarathrustazaxxonzeewolfzeewolf', 'massacrezombizone', 'gravityziriaxzjyswav', 'iizeppelin', 'zork', 'iizork', 'revengezzak', 'outxp8xpilotx', "escapeyolandayuppi's", "yogi's", 'joe', 'racingxybotsyyo', 'mindbenderszany', '2zoom'], ['rockin', 'rockstar', '18'], ['conquering', 'circuit', 'hut', 'alps', 'glaciers', 'schartenspitze', 'blaueisspitze', 'hochkalter'], ['oscillation', 'external', 'counterexample', 'references', 'reading', 'sep'], ['japanese', 'caliente', 'rock', 'dubshakra', 'viva', 'sharp', 'mix', 'wintersun', 'bobby', 'del', '–', 'duel', 'atlanta', 'edit'], ['dj', '3', '–', 'jacqueline', 'mix', '52', '55', 'made', 'available']]
TOP TOKENS [['unpleasant', 'elude', 'escape'], ['escape', '6.96'], ['escape', 'escaping', '673', 'known', 'velocity'], ['escaper', 'escape', 'escape"?"escape', 'gripping'], ['escaper', 'escape', 'escape"?"escape', 'gripping'], ['escape'], ['escape', 'character', 'set', 'strings', 'characters', 'following', "a'single"], ['escape', 'insider>>http://www.techinsider.io/rocket-escape-velocity-earth-planets-2016-05fourther', 'greater'], ['escape', 'feature', 'deriving', 'formally', 'second', 'sources', '”', 'assumed', 'cases', 'misnomer', 'called', 'velocity', '“', 'independent'], ['escape', 'feature', 'deriving', 'formally', 'second', 'sources', '”', 'assumed', 'cases', 'misnomer', 'called', 'velocity', '“', 'independent'], ['spawning', 'resonant', 'escapement'], ['escape', 'film', "schitt's", '1980s'], ['wildfire', '1949', 'escape', 'fenimore'], ['escape', 'standardized'], ['wcbs-tv', 'links', 'fantasized', 'situation'], ['film', 'escape', "henderson's"], ['links', 'external', 'escape', 'long-running', 'sources', 'several', 'references'], ['escape', 'pacman', 'enable', 'allow', 'author', 'bandwagon'], ['series', 'escape'], ['escape', 'escaping', 'sequence', 'used', 'called', 'escaped', 'character', 'still', 'attached', 'source', 'sequences']]
TOP TOKENS [['teething', 'first', 'swollen'], ['teething'], ['teething'], ['teething', 'pace', 'parents', 'teeth'], ['teething'], ['teething', 'teething—but', 'they’re'], ['teething', 'old', 'set', 'one', 'come'], ['teething', 'cls', 'temperature'], ['teething', 'cls', 'babies', 'teethers', 'sensation', 'ease'], ['teething', 'parents'], ['teething', 'teether', 'teethers'], ['teething', 'experience', 'process'], ['mechanical', 'items', 'novelty', 'toy', 'chattering', 'manufacturer', 'toys', 'references', 'produces', 'teeth', 'u.s', 'models', "goldfarb's"], ['molar', 'incisor', 'mouth', 'fever', 'incisors', 'however', 'teeth', 'dentition', 'premolar', 'gums', 'lost', 'usually', 'life', 'eleven'], ['teethers', 'doubling', 'surfaces'], ['toothing', 'term', 'addition', 'slang', 'english', 'victor', 'dictionary', 'life', 'said', 'technology', 'miami', 'times'], ['dawning'], ['disambiguation', 'fingering', 'interface', 'mixing', 'colder'], ['teething', 'anxiety'], ['teeth']]
TOP TOKENS [['latitude', 'longitude', 'latitudes', 'longitudes'], ['latitude', 'longitude', 'latitudes'], ['latitude', 'longitude', 'latitudes'], ['latitude', 'longitude'], ['latitude', 'longitude', 'vs'], ['latitude', 'longitude', "word'longitude.'views", 'longitudes', 'degrees'], ['latitude', 'longitude'], ['latitude', 'longitude'], ['latitude', 'longitude', 'latitude/longitude'], ['latitude', 'longitude', 'latitudes', 'longitudes', 'cls'], ['latitude', 'latitudes'], ['longitude'], ['latitude', 'longitude', 'longitudes', 'however'], ['latitude', 'longitude', 'cls', 'determining', 'coordinates'], ['latitude'], ['latitude', 'latitude’s', '2023', '2021', 'history'], ['latitude', 'previously', 'crone', 'stands'], ['latitude'], ['latitude', 'longitude', "longitude's", 'determining', 'acts', 'act', "ship's"], ['longitude', 'act', 'fell', 'problem', 'prize', 'determine', 'could', 'determining']]
TOP TOKENS [['macroeconomics', 'microeconomics'], ['macroeconomics', 'microeconomics', 'study', 'example', 'macroeconomic'], ['macroeconomics', 'microeconomics'], ['macroeconomics', 'microeconomics', 'macroeconomic', 'microeconomic'], ['macroeconomics', 'microeconomics', 'l', "thinkwell's", 'stars'], ['macroeconomics', 'microeconomics'], ['macroeconomics', 'microeconomics'], ['macroeconomics'], ['macroeconomics', 'macroeconomicsmicroeconomicsmacroeconomicsmeaning', 'microeconomics', 'issues'], ['macroeconomics', 'microeconomics', 'macroeconomists', 'macroeconomic'], ['macroeconomic', 'category:macroeconomic'], ['macroeconomics', 'microeconomics', 'ap', 'https://www.edx.org/course/introductory-ap-microeconomics'], ['macroeconomics', 'macroeconomic'], ['macroeconomic', 'macroeconomics', 'microeconomics', 'gross', 'real', 'advantage', 'versus', 'domestic', 'sector', 'business', 'product', 'take'], ['microeconomics', 'http://publicationethics.org/members/studies-microeconomics'], ['2005', 'microeconomics', 'r'], ['macroeconomics', 'macroeconomic', 'microeconomics', 'microeconomic', 'micro', 'century', 'well', 'behind', 'however', 'assumption', 'led'], ['macroeconometric', 'macroeconomists', 'macroeconomics', 'macroeconomic', 'microeconomic', 'traditional', 'microeconomics', 'walrasian', 'understand', "the'permanent"], ['macroeconomics', 'macroeconomists', 'macroeconomic', 'microeconomic', 'microeconomics', 'cls', 'economics', 'keynesian', 'business', 'aggregates', 'cycle', 'goods', 'theory', 'rather'], ['macroeconomics', 'macroeconomic', 'covering', 'kansas', '4']]
TOP TOKENS [['assertion', 'assertions', 'assert', 'controlling', 'list.get(0', 'exception'], ['assertion', 'assert', 'range', 'assertions', 'specific', 'use'], ['assertion', 'http://download.oracle.com/javase/1.4.2/docs/guide/lang/assert.html', 'assert', 'assertions', 'works', 'executes'], ['http://www.roseindia.net/javatutorials/use-assertion-in-java.shtml', 'assertion', 'assert', 'implement', 'assertions', 'code'], ['http://www.roseindia.net/javatutorials/use-assertion-in-java.shtml', 'assertion', 'assert', 'implement', 'assertions', 'code'], ['assertion', 'assert', 'true'], ['assertion', 'assert', 'assertions', 'happened', 'time', 'practice', 'customer', 'abruptly'], ['assertions', 'assertion', 'assert', 'using', 'hr>assertion', 'assert_callback', 'assert_options', 'my_assert_handler($file', 'given', 'features', 'string', 'and/or'], ['assertion', 'assert', 'assertionerror', 'ability', 'use', 'benefit', 'using', 'code'], ['assertions', 'assert', 'control.exception.assert', 'assertion', 'using', 'following'], ['assertion', 'auditing', 'assertions', 'assert', 'specify'], ['assertion', 'assertions', 'assert', 'execution', 'run', '1', 'help', 'point', 'provide', 'including', 'r', 'use', 'two'], ['assertion', 'markup', 'test', 'assertions', 'specified', 'draft'], ['assert', "assertion'pointer'failed", 'assertion', 'c', 'language', 'add'], ['assertions', 'assertion', 'problem', 'assert', 'thus', 'defining', 'assertionerror', 'library', '1', 'provide', 'makes', 'debugging', 'code', 'timing'], ['assertion', 'assert', 'assertions', '1', 'using', 'assumption', 'eiffel', 'makes', 'use', 'result'], ['assert', 'assertions', 'assertion', 'practice', 'code', 'using', 'ndebug', 'longer', 'message'], ['assertion', 'assert', 'asserted', 'test'], ['assertion', 'assertions', 'intuitive', 'assert', 'asserts', 'based'], ['assertion', 'definition', 'designed']]
TOP TOKENS [['methane', 'storage'], ['methane', 'management’s', 'emitters”'], ['methane'], ['methane'], ['methane', 'amount', '2010', 'building', 'historically', 'compounds'], ['methane', 'way', '2013', 'past'], ['methane', 'methane’s', 'although', 'critically', 'around', 'image'], ['methane', 'examine', 'although'], ['methane', 'towards', 'ch4'], ['methane', 'towards', 'ch4'], ['methane', 'atmospheric'], ["methane's", 'methane'], ['methane', '1776', 'billion', 'world'], ['methane', 'measurements', 'containing', 'cls'], ['methane', "methane's"], ['methane', '2016', 'budget', 'ch4', 'atmospheric'], ['methane', 'ch4', 'day'], ['methane', 'tonnes'], ['methane', "earth's"], ['methane', 'methanesat']]
TOP TOKENS [['wars', 'star', 'jedi', 'yoda', '”', 'anakin', 'justice'], ['star', 'wars', 'vader', 'darth', 'sith', 'jedi', 'anakin'], ['skywalker', 'vader', 'darth', 'wars', 'star', 'yoda', 'jedi', 'sith', 'anakin', 'menace', 'leia'], ['star', 'wars', 'sith', 'darth', 'vader', 'starwars'], ['jedi', 'skywalker', 'yoda', 'leia', 'vader', 'darth', 'han', 'tatooine', 'wan'], ['wars', 'star', 'jedi', 'sith', 'bees', 'relevant', 'entirely'], ['wars', 'star', 'sith', 'jedi', 'skywalker', 'darth'], ['sith', 'skywalker', 'jedi', 'leia', 'darth', 'tatooine', 'wookiee', "leia's", 'galactic', 'vader'], ['jedi', 'yoda', 'skywalker', 'galactic', 'sith', 'leia', 'darth', 'vader', 'anakin'], ['wars', 'star', 'jedi', 'leia', 'sith'], ['jedi', 'yoda', "yoda's", 'darth', 'leia', "skywalker's", 'sith', 'vader', "vader's", "palpatine's", 'skywalker'], ['wars', 'darth', "skywalker's", 'star', 'vader', 'leia', 'han'], ['wars', 'skywalker', 'star', 'darth', 'tatooine', 'leia', 'jedi', 'sith'], ['yoda', 'leia', 'jedi', 'sith', 'vader', "vader's", 'wan'], ['wars', 'han', 'star', 'tatooine', "yoda's", 'vader', 'leia', 'skywalker', "kenobi's", 'darth', "wan's", 'menace'], ['wars', 'star', 'jedi', 'balance', 'sith', 'darth', 'menace', 'vader', 'individuals'], ['wars', 'star', 'yoda', 'darth', 'jedi', 'vader', 'han', 'leia', 'skywalker'], ['wars', 'star'], ['star', 'wars', 'jedi', 'yoda', 'skywalker', '2018', '2017', '3po', '2021', 'anakin', 'lucas', 'ewoks', 'cls', 'boba'], ['wars', 'star', 'films', 'jedi', "wars'franchise", 'installments', 'trilogy']]
TOP TOKENS [['import', 'default', "reactor.'reactor", 'reactor', 'found', 'callwhenrunning', 'twisted', 'rest', 'one', "print'hello", 'pollreactor', 'program', "rut.'from", 'traceback', "loop!'print'lately", "print'starting", 'use', 'lately', 'least', 'time', 'called', 'window'], ['similar', 'party', 'makes', 'centric', 'capable', 'server', 'information', 'code', 'collector', 'ability', 'acts', 'mode', 'dynamically', 'performs', 'items', 'modules', 'tables', 'line', 'based', 'comprehensive', 'procedures', 'statistics', 'oedipus', 'calls', 'loops', 'extensions', 'interface', 'standard', 'using', 'address'], ['import', 'num', 'factoryfrom', 'runner', 'web', '8007', 'reactorclass', 'protocol', 'addcallback', 'twisted', 'dns', 'loopreactor', 'return', 'serverfrom', 'modules', 'spreading', 'self', '4', 'gtk', 'examplefrom', 'telnet', 'sometimeout', 'reactor', 'example', 'internet', 'xmpp', 'deferred', 'deferreddeferred', 'mixing', 'predefined', 'arg1'], ['dependencies', 'absolutely', 'great', 'substitute', 'extension', 'used', 'already', 'standard', 'akin', 'similar', 'uses', 'tries', 'e', 'implementation', 'common', 'lets', 'well', "python's", 'g', 'excellent', 'therefore', 'functions', 'generic'], ['http://physics.nist.gov/cuu/units/binary.html', 'software', 'implementation', 'version', 'returns', 'email@example.com', 'compiles', 'pointless', 'equivalent', 'number::compare->new(">1m', 'accordance', 'simple', 'ki', 'may', 'standard', 'suffixed', 'longhanded', 'number::compare->new(">1ki")->test(1025', 'c->(1_200_000', 'and/or', 'subroutine'], ['version', 'could', 'asks', 'provide', 'may', 'many', 'perspective', 'minimal', '—', 'price', 'similar', 'currently', 'implemented', 'place', 'note', 'also', 'better', 'question', 'possible', 'another', 'leaving', 'uses', '“', 'based', 'uploads', 'would', 'synchronization'], ['similar', 'party', 'version', 'server', 'collector', 'named', 'based', 'centric', 'mode', 'distribute', 'web', 'items', 'acts', 'using', 'information', 'processor', 'kinds', 'dynamically', 'oedipus', 'wardriving', 'also', 'assembler', 'ministumbler', 'persistently', 'sends', 'performs', 'line', 'supplied', 'form', 'standard', 'modules', 'parsing', 'way', '’', '802'], ['produces', 'like', 'convert', '20', 'number', 'include', 'attempts', '5', 'one', 'code', 'specifications', 'plus', '10', 'tolerances'], ['periodical', 'issn', 'version', 'publications', 'print', 'available', 'line', 'contain', 'isbn', 'see', 'http', 'typically', 'number'], ['use', 'twisted', 'found', 'reactor', 'internet', 'pollreactor', 'program', 'default', 'explicitly', 'import', 'little', 'implementation', 'implement', 'module', 'code', 'one', 'around', 'example', 'implicitly', 'system', 'variety', 'would', 'scheme', 'includes'], ['permanently', 'incarnations', 'also', 'returns', 'venomized', 'bringing', 'different', 'appear', 'decide', 'native', 'multiverse', 'unrelated', 'mythos', 'gives', 'usually', 'turns', 'poisons', 'symbiotes', 'however', '23'], ['party', 'essentially', 'rely', 'directly', 'based', 'additions', 'access', 'described', 'offers', 'using', 'pubmed', 'instance', 'pmid2cite', 'include', 'versions', 'numbers', 'materials', 'taking', 'processed', 'cite', 'etc', 'augment', 'systematically', 'examples', 'methods', 'use', 'parameters', 'programming', 'unofficial', 'experience', 'wide', 'making', 'week', 'generators', 'one', 'effect', 'schroeder'], ['party', 'pubmed', 'additions', 'papers', 'commercial', 'issued', 'columns', 'due', 'also', 'wide', 'pmid', 'provides', 'value', 'fact', 'works', 'piece', 'free', 'text', 'effect', 'opinions', 'ovid', 'minimal', 'published', 'range', 'may', 'remained', 'suitable', 'initially', 'number'], ['analogous', 'salts', 'electrophiles', 'ortho', 'substituted', 'give', 'depending', 'phenolic', 'nucleophiles', 'invoked', 'iodonium', 'see', 'oxidations', 'counteranions', 'yield', 'however', 'related', 'undergo', 'may', 'example', 'inequivalent', 'react', 'provides', 'different', 'intramolecular', 'unsaturated'], ['counterpart', 'similar', 'durability', 'close', 'irresponsibly', 'humanly', 'consequences', 'faithful', 'familiar', 'invulnerability', 'mythos', 'counterparts', 'man', 'altruistic', 'uses', 'effects', 'fresh', 'likable', 'mainstream', 'marvel', 'based'], ['party', 'closures', 'system', 'lexical', 'extensions', 'include', 'eventually', 'shipped', "racket's", 'comes', 'like', 'machine', 'inspired', 'also', 'extensibility', 'modules', 'example', 'act', 'together', 'purpose', 'built', 'objects', 'functions', 'transparently'], ['append', 'arrives', "on'hostname'print", 'takes', "ready'predicate", "of'ls'that", 'returns', 'called', 'filename', 'sys', 'strings', 'another', 'wrapper', "result'property", 'since', 'modules', 'conn'], ['features', 'materials', 'including', '4', 'released', 'xulrunner', 'imagine', 'overhauled', '3', 'includes', '2011', 'connectors', 'allowing', 'abbreviations', 'plugin', '0', 'downloading', 'wish', 'introduced', 'interoperability', 'april', 'available', 'commons', 'use', 'made', '2010', '2', 'well', 'formats', 'october', 'standalone', 'included', '1', 'several', 'also', 'january', 'example'], ['parties', "google's", 'failure', '8', 'connects', 'code', 'may', 'versions', 'uses', 'natively', 'supported', 'ease', 'source', 'power', 'using', 'available', 'provided', 'officially', 'servers', 'node', 'simplified', 'supports', 'significant', 'modified', 'programming', 'similar', 'also', 'compile', 'others'], ['extended', 'languages', 'pipeline', 'based', 'oriented', 'python', 'imperative', 'extension', 'functional', 'concurrent', 'purely', 'dialected', 'metaprogramming', 'dataflow', 'interpreted', 'iterative', 'generic', 'declarative']]

Processing features:  80%|███████▉  | 78/98 [37:32<09:39, 28.96s/it]

getting sample prompt forgetting sample prompt for 24337
 24336
getting sample prompt for 24338
getting sample prompt for 24339
getting sample prompt for 24340
getting sample prompt for 24341
getting sample prompt for 24342
getting sample prompt for 24343
getting sample prompt for 24344
getting sample prompt for 24345
getting sample prompt for 24346
getting sample prompt for 24347
TOP TOKENS [['mtorc1', 'mtor', 'non', 'acid', 'body', 'top', 'biological'], ['mtbe', 'amendments', 'decade', 'sources', 'butyl', 'last', 'pollution', '40', 'contaminate'], ['mtp', '1', 'kbps', 'mtp2', 'mtp3', 'layer', '35', '1544', 'unit', '2048', '64', 'link'], ['mtbe', 'wells', 'methyl-t-butyl', 'content'], ['mtbe', 'mtbe(methyl', 'amendments', 'twenty-three', 'decade', 'sources'], ['mtle', 'http://www.mtleguide.com'], ['mtu', 'mss', '1460', 'option', 'gather', 'host', 'standardized', 'network', '1500', 'path', 'detection'], ['mtbe', 'mt', 'know', 'almost', 'recent', 'water'], ['mtss', 'full', 'potential', 'group'], ['mtss', 'pbis', 'data-based'], ['mto1'], ['mtu', 'financial', 'friedrichshafen', 'trace'], ['mtg1'], ['mtss', 'mts', 'also', 'mtss1', 'segurança'], ['mto', 'injection', 'medium-term', 'iso', 'orbiter', 'using', 'also'], ['mtrr'], ['mti', 'home', "master's", 'technical', 'singapore'], ['mts', 'srbija', 'system', 'entertainment', '2003', 'former', 'syndication', 'mattel', '–', 'turkmenistan', 'used', 'services', 'computing', 'provider', 'tracking'], ['mtel', 'montenegro'], ['mtac']]
TOP TOKENS [['rogue', "call'rogue", 'term'], ['rogue', 'rogues', 'considered', 'true', 'anecdotal', 'boat', 'greater'], ['rogue', 'feet'], ['rogue'], ['rogue', 'rogues', 'umpteenth'], ['rogue', 'rogues', '“', 'one'], ['rogue', 'regardless', 'aps'], ["rogue's", 'rogue', 'rogues', 'regiment'], ['rogue', 'rogues', 'software', 'major'], ['rogue', 'sites', 'security', 'cls', 'antispyware'], ['rogue', 'mountain'], ['“rogue', 'rogue', '”rogue'], ['rogue', 'internet', 'references', 'external', 'defunct', 'archive', 'united', 'links', 'via'], ['rogue'], ['rogues', 'wiktionary:rogues'], ['rogue'], ['hermosas-indie-film-company-rogue-arts-heads-for-higher-ground', 'rogue', 'thomsen', 'world', 'film', 'bessai', '2010', 'michael', 'toro'], ['rogue', 'year-round'], ['rogue', 'white', 'murray'], ['rogue', 'along', '2010', 'northeast', 'historic', 'northward']]
TOP TOKENS [['manning', 'prosecuted', 'people', '“', 'government', 'secrecy', 'seemingly', 'case', 'world', 'obama', 'alluding', 'almost', 'bradley', 'intention'], ['manning', 'month', 'international', '’', 'offense', 'admonishment', 'morrell', 'nations', 'instead', 'public', 'regardless', '9', 'counts', 'eight', '…', 'day'], ['manning', 'month', 'international', '’', 'offense', 'admonishment', 'morrell', 'nations', 'instead', 'public', 'regardless', '9', 'counts', 'eight', '…', 'day'], ['manning', '’', 'account', 'taking', 'wellbeing', 'unwarranted', 'u', 'obama', 'disclosures', 'empathy', 'ellsberg', 'perhaps', 'assertion', 'issues', 'exposed', 'exertion', 'us', 'de', 'corruption'], ['manning', 'acted'], ['manning', 'ewen', 'aren’t', 'nations', 'papers', 'us', 'whistleblowers', 'catch-all', 'person', 'provide', 'state', 'doesn’t', 'advocacy', 'ellsberg', 'government', 'act', 'wiretapped', 'journalism', '1971', 'rsf’s', 'sterling’s', 'gave', 'transparency,”', 'classified', 'defense', 'revealed.”', 'prosecutions'], ['manning', '’', 'paints', '”', 'time', 'drawing', 'industrial', 'picture', 'authorities', 'though', 'portray', 'epiphany', 'desensitized', 'affords', 'grasped', 'military', '…', 'difference', 'confided'], ['manning', 'pleaded', 'network', 'times', 'worldwide'], ['manning', 'punishment', 'strike', 'expiation', 'awaits'], ['manning', 'zones', 'nsa', 'ones', 'vehicles', 'america', 'senate', 'homeland', 'existing', 'even', 'began', 'hardware', 'cop', '”', 'inconceivable', 'disguised', 'states', 'typically', 'view', 'already', 'iraq', 'instance', 'meanwhile', 'wielded', 'towers'], ['manning'], ['2018', "men's", 'people', '2023', 'births', 'players', 'f', '2020', 'career', 'c', 'references'], [], ['real', 'living', 'espanyol', "men's", 'births', 'expatriate', 'la', 'players', 'sportspeople', '–', 'furniture', 'augsburg', 'fc', 'manninger'], ['manning', '2019', '2010', 'sa', 'offenses', 'txt', 'would', 'says', 'u', 'may', '—', 'vacuum'], ["manning's", 'manning', '2013', 'sentence', 'obama', 'disclosures', 'filed', 'states', 'doubt', 'may', '3'], ["manning's", 'january', 'death', 'bachmann', '30', 'manning', 'aviation', '1942', 'america', 'cressida', 'us', 'eisenhardt', 'florence', "captain's", 'remarked', 'partners', 'table'], ['manning', "manning's", '2011', 'federation', 'analysts', 'scientists', 'exchange'], ['manning', "manning's", 'pay', 'reported', 'lawhorne', 'said', 'defray', 'concluded', 'cited', 'help', '7', '256', 'baraitser', 'u', 'released', '12', 'march', 'since', 'material', 'ellsberg'], ['manning', '2019', 'also', '16', 'virginia', 'expired', '2013', '2020', 'objected', '8', 'march', '22', "women's"]]
TOP TOKENS [['strength', 'cls', '“', '’', 'strengths', '”', 'exactly'], ['strength', 'contradicted', 'benefits', 'definition', 'training', 'cls', 'words', 'weight'], ['strength', 'training', 'illnesses', 'nutshell', 'benefits', 'pace', 'lose', 'weight', 'safe', 'however'], ['strength', 'shown', 'stronger', 'pounds', 'training', 'weight', 'strengthening'], ['strength'], ['strength', 'losing', 'training'], ['strength', 'cls', 'training'], ['strength', 'training', 'cls', 'stronger', 'successful', 'muscles'], ['strength', 'mass', 'gaining', 'days', 'training', 'general', 'regular'], ['strength', 'balance', 'mechanics', 'plan', 'training', 'includes'], ['strength', 'may', 'cls', 'see', 'portland', 'strengths', 'music'], ['links', "strength's", 'external', 'strength', 'page'], ['east', '2000–2003', '1998', '1996–2000', '1996', 'strength', 'cd', 'ex', 'also', 'guitar', 'one', 'records', 'blood'], ['strength', 'activities', 'cls', 'equipment', 'training', 'exercise', 'stronger'], ['strength', 'although', 'album', 'recording', 'wrote', '1991', 'release', 'released', 'called', 'group', 'including', 'reworking', 'blue', 'glanville', 'thought'], ['strength', 'theory', 'stronger', 'significant', 'criticism'], ['strength', 'superhuman', 'religions', 'included', 'modification', 'cls', 'strengthen', 'greatly', 'history', 'range', 'gain', 'depicted', 'e'], [], ['strength'], ['strength']]
TOP TOKENS [['chips', 'heat', 'chip', 'potato', 'calorie', 'minerals', 'ounce', 'cooked'], ['chips', 'potato', 'favorite', 'ounces', 'oz'], ['chips', 'chip', 'potato', 'unsalted', 'turn', 'love', 'minutes', 'sep'], ['chips', 'chip', 'potato', 'unsalted', 'turn', 'love', 'minutes', 'sep'], ['chips', 'potato', 'bag', 'eats', 'quality', 'individuals', 'tortilla', 'make', 'caveat'], ['chips', 'market', 'overall', 'potato', 'salty', 'healthiest'], ['chips', 'potato', 'america', '“', 'properly'], ['chips', 'potato'], ['chips', 'potato', 'flavorless', 'select'], ['chips', 'potato', 'chip', 'heat'], ['chips', 'packaging', 'system', 'companies'], ['chips', 'potato'], ['chips', 'potato', 'cooked'], ['chips', 'variations', 'candies', 'states'], ['chips'], ['chips', 'architecture', 'architect'], ['chips', 'adaptations', 'disambiguation'], ['chips', 'chip', 'dried', 'fried', 'artichoke', 'dehydrated', 'veggie', 'glutamate', 'crisp', 'consistency', 'baked'], ['chips'], ['chips', 'potato', "lay's", 'indonesia', 'chip', 'prominent', 'common', 'flavors', 'takoyaki', 'yakitori', 'jill', 'yolk']]
TOP TOKENS [['clone', 'clones', 'cloning'], ['cloning', 'clone', 'cloned', 'pm', 'super.clone'], ['clone', 'cloning', 'cloned', 'want', 'clones'], ['clone', 'cloning', 'clones', 'lag', 'running'], ['cloned', 'clone', 'cloning', 'disk', 'hard'], ['cloned', 'cloning', 'genes', 'clones', 'clone', 'nature', 'plant', 'asexually', 'reproduce', 'techniques', 'considered'], ['cloned', 'clone', 'cloning'], ['cloned', 'cloning', 'clones', 'clone', 'cuttings'], ['clones', 'clone', 'cloned', 'cloning', 'labeled'], ['clone', 'clones', 'cloning', 'surrounding'], ['clone', 'clones', 'collects', 'ended', '16-20', 'book', 'him/herself', 'they’re', 'vs'], ['clone', 'cloneable', 'cloned', 'properly', 'clonenotsupportedexception', 'public', 'however', 'invoke'], ['clone', 'cloning', 'programming'], ['clone', 'cloned', 'cloning', 'links', 'external', 'claire'], ['cloners', 'cloner', 'cloned', 'clone', 'cloning', 'software', 'disk', 'based'], ['clones', 'clone', 'fact', 'new', 'cell'], ['clone', 'clones', 'steam', 'named', 'directly', 'carrying'], ['cloning', 'clone', 'clones', 'dozois'], ['clone', 'object', 'clonenotsupportedexception', 'often', 'cloneable', 'cls', 'overriding', "object's", 'myclass'], ['clone', 'cloned', 'clonezilla', 'laboratories', "computer's", 'effectiveness', 'alternatively', 'gzip']]
TOP TOKENS [['moldova', 'moldovan', 'university'], ['moldova', 'moldovan', 'country'], ['moldova', 'moldovans', 'bank', 'although'], ['moldova', 'moldovans', 'moldovan'], ['moldova', 'moldovan'], ['moldova', 'moldovan', '9'], ['moldova', 'moldova’s', '“moldova”', 'low', 'transnistria', 'milestii', '2007'], ['moldova', "moldova's", 'millimeters', 'world', 'eu'], ['moldova', 'moldovans', 'moldovan', 'minister', 'milk', 'hilly'], ['moldova', 'moldovan', '–'], ['moldova', "moldova's", 'moldovan', 'moldovans', 'transnistria'], ['moldova', 'moldovans', 'moldovan', '552', '1999', 'east', '5', '9', 'fact'], ["moldova's", 'moldova', 'moldovans', 'moldovan', 'europe', 'change', 'officially'], ['moldova', "moldova's", 'moldova–russia', 'moldova–nato', 'moldovans', 'moldovan-americans'], ['moldova'], ['moldova', 'international'], ['moldova', 'moldovan', "moldova's", 'therefore', 'cases', '100', 'including'], ['moldova', 'moldovan', '1994', 'moldavian'], ['moldova', 'moldovan', 'moldovans', '9', '5', '8', 'parliament', 'several'], ['moldova', 'moldovan']]
TOP TOKENS [['scratch', 'right', 'instead'], ['scratch', 'scratching', 'cls', 'inventors', 'license', 'shared', 'world'], ['scratch'], ['scratch'], ['scratch'], ['scratch’s', 'scratchers', 'scratch', 'scratch.mit.edu', 'see'], ['scratch', 'scratchjr', 'cls', 'scratching', 'note', '2', 'visits'], ['scratch', 'also', 'bit', 'programming'], ['scratch', 'scratchers', 'scratchjr', 'however', 'part', '2016'], ['scratch', 'scratchers', 'using', 'scratched'], ['scratch', 'develop', 'scratcher', 'uses'], ['scratch', 'scratchers', 'scratching', 'cls', 'world', 'size', 'tools', 'simulations', 'disk'], ['scratch', "called'scratchers", 'scratchers', 'scratcher', 'scratched', 'using', 'photography'], ['scratch', "scratch's", 'develop', 'explorer'], ['scratch', "scratch's", 'links', 'external', 'issue', 'profile', 'presents', 'references'], ['scratch', 'added'], ['scratch', 'scratchjr', 'interpretation', 'designed', 'eric', 'extension', 'programs', 'shaders', 'programming'], ['scratch', 'jacek', 'jerzy'], ['scratch', "scratch's", 'disowned', 'harkness', 'gorath', 'possesses', 'salem', 'discovered'], ['scratch', 'filesystems', 'ram']]
TOP TOKENS [['explore'], ['explore', 'present', 'offered'], ['attention', 'find', 'involved', 'share', 'look', 'attend', 'discuss', 'learn', 'work', 'greater', 'supplement', 'might', 'contacting', 'example', 'see'], ['discover', 'share', 'participate', 'read', 'contribute'], ['ask', 'sign', 'normally', 'via', 'link', 'go', 'necessary', 'encountered', '3', 'similar', 'show', 'make', '1', 'provide', 'inform', 'next', 'repeat'], ['inform', 'colleagues', 'ask', 'encourage', '1', 'see', '2', 'ways', 'share', 'connect', 'exhibits', 'members'], ['find', 'give', 'reach', 'members', 'like', 'u.s', 'talk', '0.5', 'share', 'called', 'continue'], ['find', 'check', 'share', 'ask', 'contact', '2', 'similar', 'read', 'attend', 'districts', 'identify', 'spreading'], ['ask', 'community', 'try', 'related', 'updates', 'go'], ['ask', 'visit', 'hiv', 'get', 'involved'], ['gain', 'weight', 'get', 'really', 'debasement', 'try', 'faster', 'criticizing', 'devaluing', 'deprive', 'disavowing', 'limit', 'things', 'degrading', 'presentation'], ['help', "o'reilly", 'returned', 'nxt', 'september', 'undisputed', 'collide', 'allies', 'day', 'series', 'bash', 'result', 'due', 'rest', 'though'], ['hand', 'convince', 'exert', 'recognize', 'possible', 'set', 'international', 'effect', 'turn', 'chosen', 'association', 'hear', 'associated', 'heighten', 'demoralize', 'asks', 'theatrically', 'continuing', 'neighborhoods', 'cause', 'show', 'called', 'dramatize', 'employer', '1'], [], ['nyada', 'impress', 'going', 'season', 'another', 'one', 'struggles', 'initially', 'graduation', 'later', 'year', "rachel's", 'two', 'gets', 'though', 'although'], ['order', 'alongside', 'itinerary', 'place', "annie's", 'tells', 'incriminates', 'offers'], ['contact', 'ask', 'members', 'send', 'club', 'simply', 'helpful', 'actually', 'would', 'quality', 'participate', 'could', 'maybe', 'particularly', 'tt5xyz', 'locations', 'promises', 'asks', 'noticeably', 'contests', 'station', 'occur', 'attempted', 'contest', 'example'], ['ideas'], ['way', 'attack', 'find', 'past', 'tossed', 'applauded', '17', 'november', 'response'], ['see', 'third', 'visit', "nanami's", 'meet', 'blend', 'regards', 'come', 'eventually', 'act', 'nanami', 'helping', 'treated', 'left', 'take', 'moved', 'confronted', 'back', 'allowing', 'human', 'becomes', 'society', 'ami', 'years', 'confesses', 'releasing', 'friend', 'minor', 'temporarily', 'still', 'towards', 'window', 'seems', 'times']]
TOP TOKENS [['tendencies', 'agreed', 'rights', '“', 'characteristic', 'forced', 'leaders', 'matter', 'heartily', 'obtaining', 'people', 'impoverish', 'impose', '20', 'waging', 'empower', 'proven', 'cls', 'whether', 'forebearers', 'otherwise', 'unless', 'including'], ['toward', 'tendencies', 'domination', 'someone', 'aggression', 'people', 'individuals', 'armed', 'peoples', 'power', 'desire', 'fear', 'emotions', 'shared'], ['subjection', 'sentiments', 'tendencies', 'political', 'incite', 'social', 'hunting'], ['like', 'warmongering', 'bloodlust', 'characteristic', 'justify', "one's", 'going', 'transgressions', 'means', 'warmongers', 'war', 'leader', 'affecting', 'solid', 'backstab'], ['ruling', 'involve', 'athleticism', 'class', 'people', 'idea', 'weapons', 'agreed', 'beings', 'however', 'leaders', 'can’t', 'agree', 'we’re', 'fights', 'killing', 'decide', 'want', 'choice'], ['race', 'ideologies', 'leaders', 'class', 'struggles', 'empathetic', 'unrest', 'armed', 'ii', 'bring', 'bloodshed', '“', 'cls', 'noun', 'settled', 'provoke', 'military', 'spiritually', 'unmitigated', 'thoughtful', 'actions', 'several', 'along', 'especially', 'century', 'war', 'coups', 'course', 'even'], ['militarism', 'people', '“', 'inevitable', 'anyone', 'years', 'find'], ['citizens'], ['equal', 'intimidation', 'others', 'people', 'every', 'verbally', 'use', 'popular', 'social', 'certain', 'leaders', 'aggression', 'inferior', 'inevitable', 'dominance', 'really', 'often', 'mockery', 'aggressive', '“', 'heart'], ['sedition', 'trouble', 'power', 'determinately', 'command', '“'], ['forced', 'moral', 'customary', 'word', 'commitment', 'conventional', 'one', 'object', 'referring', 'general', 'forces', 'meaning', 'defined', 'either', 'gladiators', 'generally', 'although', 'usually', 'usage', 'refer', 'infrequently'], ['majority–minority', 'agitator', 'people', 'political', 'action', 'criminal', 'achieve', 'anti-soviet', 'e.s.p', 'mixing', 'something'], ['behavior', 'ableism', 'majority', 'involving', 'action', 'acceptance', 'monarch', 'human', 'cls', 'political', 'syndicalism', 'equal', '–', 'agrarianism', 'amount', "man's", 'generally', 'governments', 'absolutism'], ['militaristic', 'political', 'conducive', 'militaries', 'involve', 'suzerainty', 'meant', 'exchange', 'control', 'latter', 'allowed', 'society', 'mention'], ['desire', 'motives', 'methods', 'power', 'wishing', 'policies', 'one', 'expressing', 'typically'], ['recruiting', 'called', '18', 'troops', 'always', 'part', 'major', 'game', 'well', 'control', 'army', 'overall', 'description', 'conclusion', 'warlords', 'gladly', 'action', 'complete', 'vie', 'conquering', 'various', 'november–december', 'either', 'forming', 'related'], ['beliefs', 'political', 'caste'], ['forces', 'militarily', 'e', 'warfare', 'renders', 'latter', 'battle', 'often', 'many', 'may'], ['oppress', 'rights', 'citizens', 'peoples', 'one', 'wars', 'people', 'right', 'period'], ['opinions', 'social', 'people', 'ideas']]
TOP TOKENS [['simulink', 'default', 'cases', 'e', 'g'], ['simulink', 'simulink®'], ['simulink', 'simulink®'], ['simulink', 'simulink®'], ['simulink', 'use'], ['simulink', 'simulink®', 'select'], ['simulink', 'choosing', 'groups'], ['simulink'], ['simulink', '1', 'configure', 'block', 'following', 'output'], ['simulink', 'simulink®', 'alternatively', 'spec1'], ['simulink'], ['simulink', 'specific', 'scalarvariable', 'comparison', 'dynamically'], ['simulink', 'engine'], ['simulink', 'example', 'overall', 'using', 'within'], ['inussulik', 'igdlulik', 'illulik', 'illulissuaq'], ['potulin', 'west-central', 'wągrowiec'], ['simulium', 'shiraki', 'amurense', 'vorobets', 'rubtsov', 'angulistylum'], ['simul8', 'graph', 'pipes', 'anything', 'automotives', 'desks', 'points'], ['simulium', 'dinulescu', 'g', 'c', 'chubareva', 'rubtsov', 'beringovi', 'fukuda'], ['simulink', 'coverage', 'models', 'test', 'cases', 'matlab', 'time', 'certain']]
TOP TOKENS [['emphysema', 'emphysema(redirected', 'emphysema(ĕmfĭsē`mə', 'emphysematous', 'emphersema'], ['emphysema', 'emphysema(redirected', 'emphysema(ĕmfĭsē`mə', 'emphysematous', 'emphersema'], ['emphysema', 'cls'], ['emphysema'], ['emphysema', 'walled'], ['emphysema'], ['emphysema', 'cls', '11', 'publication'], ['emphysema', 'cls'], ['emphysema'], ['emphysema', 'made', 'cases'], ['emphysema', 'cls', 'blood', 'alveolar'], ['emphysema'], ['emphysema', 'emphysematous'], ['emphysema', 'emphysematous', 'development'], ['emphysema', 'symptoms'], ['emphysema', 'care'], ['emphysema', 'subcutaneous', 'face', 'axillae'], ['emphysema', 'subcutaneous'], ['emphysema'], ['emphysema', 'emphy', 'subcutaneous', 'wall']]

Processing features:  81%|████████  | 79/98 [38:01<09:08, 28.85s/it]

getting sample prompt forgetting sample prompt for 24349
 24348
getting sample prompt for 24350
getting sample prompt for 24351
getting sample prompt for 24352
getting sample prompt for 24353
getting sample prompt for 24354
getting sample prompt for 24355
getting sample prompt for 24356
getting sample prompt for 24357
getting sample prompt for 24358
getting sample prompt for 24359
TOP TOKENS [['info', 'clip'], ['info', "clip's", 'clip', 'available', 'edit'], ["clip's", 'clip', 'available', 'info'], ["clip's", 'clip', 'available', 'info', 'edit'], ["clip's", 'clip', 'info', 'available', 'edit'], ['info', 'edit', "clip's"], ['clip', "clip's", 'info', 'edit'], ['info', 'available', 'clip'], ['available', 'info', 'edit', "clip's", 'clip'], ['available', 'info', 'edit', "clip's", 'clip'], ['saying', 'also', 'editing', 'well', 'heard', 'notes', 'links'], [], ['shows', 'well', 'zooms', 'pans', 'scene', 'empties'], ['approximately', 'white', 'scenes', 'also'], ['historical', 'clips', 'productions', 'production', 'footage', 'outtakes', 'shot', 'material', 'environments', 'various', 'may'], ['continent', 'film', 'one', 'held', 'black-and-white', 'briefly', 'links', 'shot', 'synopsis', 'also', 'part', 'among', 'parachutes', 'produced', 'external', 'way', 'see', 'prepare', 'defense', 'rationed', 'presumably', 'collection', 'shortly'], [], ['exerts', 'white', 'archive', 'org', 'links', 'american'], ['correct', 'confirmed', 'well', 'also', 'however', 'careful', 'carts', 'notes', 'buggies', 'defined', 'something', 'one', '1906', 'based', 'appear'], ['black-and-white', 'directed', 'film', 'cast']]
TOP TOKENS [['cape', 'capes'], ['cape', 'capes', 'exams', 'sea', 'verde'], ['cape', 'capes'], ['capes', 'cape', "cape's", 'fashion'], ['cape', 'investigations'], ['cape', 'capes', 'cod', 'ell', 'houses', 'proportioned', 'ridgeline', 'storms', 'house'], ['cape', 'capes', 'cod', 'ell', 'houses', 'proportioned', 'ridgeline', 'storms', 'house'], ['cape', 'capes', 'sea', 'coastline', 'ocean', 'cod'], ['cape', 'feature', 'possession', 'type'], ['capes', 'cape'], ['cape', 'plc', 'promontory', 'asian', 'hope'], ['capes', 'cape', '1962', 'certificat'], ['cape', 'north'], ['cape', 'capes'], ['2008', 'capeville'], ['cape', 'capes', 'capelet', 'word', 'fashion'], ['cape-1', 'cape-2', 'several', 'k5usl'], ['cape'], ['cape', 'special'], ['capepops', 'cape', 'cod']]
TOP TOKENS [['prefix', 'prefixes', 'practise', 'adding'], ['prefix', 'prefixes', 'using', 'nonsense', 'also', 'cls', 'classmates', 'different'], ['prefix', 'prefixes'], ['prefix', 'prefixes'], ['prefix', 'prefixes'], ['prefixes', 'prefix', 'see', 'prefixing', 'wrong', '“very”', 'use', 'using'], ['prefix', 'prefixes', 'prefixmeaningexamplesinter', 'use', 'learn'], ['prefix', 'prefixes', 'look', 'nouns', "вложение'investment'пре"], ['prefix', 'prefixes', 'prefixescardinalcardinal11undec', 'prefixesgreek', 'dodecadactylum13tredec'], ['prefixes', 'judgment', 'prefix', 'many', 'another', 'use', 'common', 'cls'], ['prefix', 'code', 'stations', 'notation'], [], ['prefix', 'merely', 'lack', 'codes', 'using'], ['prefixes', 'prefix', 'general', 'standardised', 'permitted'], ['prefix', 'prefixes'], ['prefixes', 'prefix', 'non-productive'], ['prefixes', 'prefix', 'different', 'english', 'cls'], ['prefixes', 'prefix', 'lawsuit', 'restrict', 'certain', 'prefixed', 'required', 'dedicated'], ['prefixes', 'prefix'], ['prefix', 'indicate', 'proper', 'empty', 'restrict', 'seen', 'denotes']]
TOP TOKENS [[], ['finche'], [], ['diverges', 'diverge', 'cross', 'away', 'move', '“'], ['marriage'], [], ['pitchers', 'baserunners', 'pitching', 'baseball', 'pitcher', 'pitch', 'whip', '1', 'pitched', 'well', 'whole', '2019'], [], [], ['echeveria', 'offshoots', 'sprouting'], [], [], ['hit', "dark's", 'would', '000', 'one', 'often', '1956', 'runs', 'probably', '1978', 'fielder', 'positions'], [], [], [], [], [], [], []]
TOP TOKENS [['plan', 'idea', 'need', 'might', 'reasons', 'create', 'could', 'possibly', 'include'], ['want', '「あなたがこれを読んでいるなら、私はもう死んでいるでしょう。」would', 'suggested', 'helping', 'turning', 'thinking'], ['1', 'might', '2'], ['idea', 'need', 'etc', 'ideas', 'want'], ['descriptionofthe', 'scenario', 'plausible', 'scenarios', 'analysing'], ['plan', 'help', 'prepare'], [], ['would', 'trying', 'going', 'using', 'future', 'plan'], ['introduce', 'idea', 'scenarios'], ['idea', 'ideas', 'something'], ['need'], ['limited'], ['planning', 'inspired', 'scenario'], ['containing', 'portraying', 'plans', 'plan', 'alert', 'emergency', 'information', 'history', 'profit', 'instructions', 'refer'], ['must', 'infomorph', 'memory', 'vaccine'], ['provide', 'background', 'abandoned', 'proposed', 'else', 'requirements', 'altogether'], ['referencing'], ['plan'], [], ['would', 'ostensibly', 'involves', 'could', 'potentially']]
TOP TOKENS [[], [], ['vs'], ['notation'], [], [], ['disciplines'], [], [], ['describe', 'used', 'studied', 'sort', 'notations'], [], [], [], [], [], [], ['expression', 'expressed'], ['say', 'definition', 'defined'], [], ['important', 'proved', 'least', 'applications', 'define', 'let', 'suppose', 'shown', 'says', 'say', 'context', 'e', 'g']]
TOP TOKENS [['process', 'greater', 'subsetting', 'simple', 'enough', 'subset', 'especially', 'order', 'becomes', 'particular', 'right', 'also', 'subsets', 'provide', 'different', 'broader', 'referentially', 'automating', 'need', 'relevant', 'want', 'deeper', 'departments', 'would', '’', 'three', 'certain'], ['like', 'arrange', "let's", 'plan', 'go', 'arranged', 'going', 'meeting', '。', 'expect', 'must', '…', '和', 'make', 'us', 'preparations'], ['http', 'en', 'generale', 'laetitia', '20150304', 'content', 'html', '20140928', '20150311', 'vatican'], ['exceptional', 'going', 'wide', 'g', 'e', 'serious', 'formalize', 'much', 'coming', 'likely', 'relevance', 'also', 'regularily', 'tried', 'hence', 'happen', 'way'], ['getting', 'piece', 'happy', 'idea'], ['subset', 'clear', 'immediately', 'easy', 'requires', 'make', 'technique', 'piece'], ['high', 'impressed', 'desirable', 'expedient', 'least', 'generally', 'agreements', 'exigencies', 'necessary', 'exporters', 'regard', 'thus', 'may'], [], ['impressed', 'quite', 'want', 'pleasantly', 'enough', 'whether', 'allowing', 'even', 'example', 'complies'], ['coherently', 'subset', 'except', 'decomposition', 'subsets', 'perform', 'chunk', 'processing', 'fact', 'involving', 'provides', 'may', 'also', 'generality', 'enumerated', 'represents', 'allocates'], ['county', 'ścinawa', 'scinawa', 'lubin', 'administrative'], ['born', "tapar's", 'attash'], ['parliament', 'greater', 'county', '1894-1904', 'peel', 'castle', 'railway', 'branch', 'town', 'metropolitan', 'local', 'current', 'united', 'r.u.f.c', '1889-1974', 'college'], ['raytracing', 'album', 'home', 'ep', 'tigers', 'directed', 'rendition', 'studio'], ['lechia', 'two', 'made', 'years', 'eventually', 'rising', 'born', 'grzegorz', 'chodzież', 'came', 'players'], ['tipperary', 'county', 'town', 'serving', 'new', '1923–2013', 'ireland', '1931–1987', 'radio'], ['belgium', 'well', 'service', '25', 'york', 'poznań', 'india', '2022', '21', 'nuncios', 'march', '2023', 'mexico', 'brazil', 'november', '1', 'representations', 'following', 'apostolic', 'new'], ['house', '1918-present', 'princess', 'lippe', 'schaumburg-lippe', 'countess'], ['estate', "wahtye's", 'bones', 'wahtye', 'second', 'old', 'two', 'meretmin', 'boat', 'king', 'one', 'probably', 'god', 'ptah'], ['album', 'webb']]
TOP TOKENS [['turtles', 'turtle', 'marine', 'al'], ['turtles', 'sea', 'turtle', 'marine', '42', 'ecol', 'j', '408', '–', '302'], ['turtles', 'turtle', "turtle's", 'turtle”', 'turtles.full'], ['turtle', 'turtles'], ['turtles', 'turtle', 'sea', '42', 'areas', '000', 'males', 'seaweed'], ['turtles', 'turtle', 'sscmarine', 'marine', 'fundamental', 'ecology', 'al'], ['turtle', 'turtles', 'toward', 'shell', 'fingers', 'many', 'eggs', 'good'], ['turtles', 'turtle'], ['turtles', 'turtle', 'turtley'], ['turtles', 'turtle'], ['turtle', 'turtles', 'band', 'shell', 'journey'], ['turtle', 'turtles', 'methods', 'river'], ['turtle', "turtle's", 'turtles', 'others', 'captured', 'trap', 'return', 'certain', 'reach', 'perspective', 'view', 'area'], ['turtles', 'turtle', 'sea', 'size', 'disturbances', '1992', 'output', 'available', 'predation', 'embryos'], ['turtles', "turtle's", 'turtle', 'sea', "turtles'skin", '000', 'encounter'], ['turtles', 'turtle', "turtle's", 'wood', 'species', 'accidents', 'traffic'], ['turtle', 'sea', 'species'], ['turtles', "turtle's", 'turtle', 'land', 'away', 'germination', 'capabilities', 'ability', 'die'], ['turtles', 'turtle', 'sea', 'amount', 'entangled', 'reptiles', 'day'], ['turtles', 'turtle', "blanding's", 'nine', 'rate', 'studied', 'wood', 'maze', 'instance']]
TOP TOKENS [['iterator', 'iterators', 'would', 'return'], ['iterator', 'next', 'iterable'], ['iterator', 'iterators', 'see'], ['iterator', 'iterable', 'iterables'], ['iterator', 'iterators'], ['iterator', 'iterators', 'iterating', 'abc', 'iter', '0x10a47f150', '“', 'b', 'happens', '0x10a47f190', 'implementing'], ['iterator', 'iterators', 'iterables', 'iterable', 'iterate', 'iter'], ['iterators', 'iterator', 'iterable', 'sight', 'required', 'returned', 'considered'], ['iterators', 'iterator'], ['iterator', 'iterable', 'iterators', 'data', 'iterate', 'repeat'], ['iterator', 'iterators', 'fixed', 'taken', 'programming', 'exhibit', 'iterating'], ['iterator', 'iterators', 'categories', 'using'], ['iterator', 'iterators', 'iterable', 'iterating', 'iterated', 'returns', 'implementing', 'however'], ['iterators', 'iterator', 'associated', 'using', 'instead', "java's", 'self', 'unbounded', 'iterable'], ['iterator', 'iterator1', 'iterators', 'implements', 'rather', 'sz', 'returns', 'implemented'], ['iterator', 'iterators', 'xl', '0', 'ienumerator', 'needs', 'ui', 'integeriterator', 'version', '2', 'counter', 'itertools'], ['iterators', 'iterator', "concept'randomaccessiterator", 'iter', 'randomaccessiterator', 'access', 'bidirectional'], ['iterator', 'iter', 'returns', 'numbers', 'multiplybytwo', 'calls', 'implements'], ['iterator', 'iterating', 'iterable', 'part', 'using', 'thought', 'itertools', 'bounded', 'let', "generator's"], ['iterator', 'iterators', 'using', 'iterate', 'use', 'iter', 'include']]
TOP TOKENS [['obsessive-compulsive', 'obsessions', 'obsessive'], ['obsessively', 'obsessive', 'compulsive', 'intrusive', 'obsessed', 'obsessions', 'word', 'compulsions'], ['obsessive', 'compulsive'], ['obsessive', 'compulsive', 'obsessions', 'obsession', 'intrusive', 'compulsion', 'urge'], ['obsessive', 'obsessions', 'intrusive', 'compulsive', 'obsession', 'compulsions'], ['obsessive-compulsive', 'obsessions'], ['obsessive', 'compulsive', 'obsessions', 'intrusive'], ['obsessive', 'compulsive', 'obsessions'], ['obsessive', 'compulsive', 'intrusive', 'obsessions', 'obsession', 'suppress', 'thoughts'], ['obsessive-compulsive', 'obsessive', 'compulsive', 'obsessions', 'compulsions'], ['obsessive', 'obsessive-compulsive'], ['obsess', 'obsessive', 'compulsive', 'obsessions', 'typical', 'ocd'], ['obsessive', 'compulsive', 'obsession', 'obsessions', 'compulsions', 'thoughts', 'harboring', 'ocd'], ['obsessive', 'obsessive–compulsive', 'obsessive-compulsive', 'compulsives'], ['obsessive', 'obsession', 'compulsive', 'obsessional', 'intrusive', 'obsessions', 'common', '–'], ['obsessive', 'compulsive', 'obsessional', 'intrusive', 'preoccupations', '–', 'ocd', 'pop', 'compulsions', 'e'], ['obsessive', 'compulsive', 'obsessed', 'obsession', 'obsessions', '–', 'symptoms', 'excessive'], ['obsessive', 'compulsive', 'obsessions', 'measures', 'compulsions'], ['obsessive', 'obsessions', 'compulsive', '–', 'make'], ['obsessive', 'compulsive', 'obsessions', '–', 'intrusive']]
TOP TOKENS [['tacrolimus', 'pimecrolimus', 'irritating', 'genes', 'corticosteroid'], ['tacrolimus', 'systemically', '8', '13', '03', '0'], ['tacrolimus', 'dogs', 'streptomyces', 'ointment', 'extent', 'uc'], ['tacrolimus', 'e', 'prematurely', 'take', 'ankles', 'sink', 'feet', 'needed'], ['tacrolimus', 'swelling', 'medications', 'cls', 'system'], ['pimecrolimus'], ['tacrolimus', 'country', 'cls', 'skin'], ['tacrolimus', 'id', 'lf', '816', 'rh', 'immunol'], ['tacrolimus', 'one', 'skin', 'doctor', "administration's"], ['tacrolimus', 'period', 'supratherapeutic'], ['tacrolimus', 'sirolimus', 'eyes', 'one', 'hyperglycemia', 'also', 'intravenous', 'nephrotoxicity', 'face', 'itching', 'various', 'occlusive'], ['tacrolimus', 'streptomyces', '30', 'cls', '46', 'ointment', "body's"], ['tacrolimus', 'sirolimus', '2017', 'streptomyces', 'atopic', 'memoir'], ['tacrolimus', 'pimecrolimus', 'topical', 'interactions', 'applications', 'patients'], ['tacrolimus', 'blood', 'one'], ['tacrolimus', 'sirolimus', 'mofetil', 'calcineurin'], ['sirolimus', 'everolimus', 'calcineurin', 'mtorc2', 'dependent', 'stomatitis', 'inhibitors', 'transplants', 'healing', 'acne'], ['tacrolimus', 'sirolimus', 'named', 'similarly'], ['sirolimus', 'coronary', 'vessels', 'factors', 'years'], ['sirolimus', 'hence', 'years', 'perioral', 'ranging', 'disease', '84']]
TOP TOKENS [['chromebooks', 'chrome', 'chromebook'], ['chrome', 'process'], ["chrome's", 'chrome', 'chromeos', 'ex', 'currently'], ['chromebooks', 'chromebook', 'chrome', 'show'], ['chrome', 'chromesetup', 'click', '“', 'page', 'browser', 'category', 'google'], ['chromebooks', 'chromebook', 'chrome', 'useless'], ['chrome', 'chromebook', 'chromestore', 'chromebooks', 'manufacturers', '6', 'acer'], ['chromebook', 'chromebooks', 'chrome', 'laptops', 'underlying', 'like', 'hard'], ['chrome', 'much', 'configuration'], ['chromebooks', 'chrome', 'chromebook'], ['chrome', "chrome's", 'survivor', 'switchboard', 'cleveland'], [], ['chrome', "chrome's", 'december', 'adaptation', 'fifth', 'games', 'year'], ['chromebooks', 'chromeos', 'chrome', "chromeos's", 'chromebook', 'chromeboxes', 'chromebase', 'totally', 'much'], ["chrome's", 'chrome', 'august', 'steel', '2010', '1995', 'hits', 'seatbelt', 'covid-19', 'seattle', 'several'], ['chromebook', 'chromebooks', 'chromeos', 'chromebase', 'chromeboxes', 'chromebit', 'chrome', 'chromebox', 'bluetooth'], ['chromebooks', 'chromeos', 'chromebook', "chromebook's", 'chromebit', 'chromebase', 'chromebox', 'chrome', 'lenovo', 'pogue', 'acer', 'unfavorably', 'new', 'december', 'fhd'], ['chromeos', 'chromebook', 'chrome', 'chromebooks', 'chromebox', 'chromebase', 'acer', 'lenovo'], ['chrome', 'test', '0', 'preinstalled', 'project'], ['chrome', 'chromebooks', 'chromeos', 'chromebook', 'chromebit', 'chromebase', 'chromebits', 'chromebox', 'stylus', 'acer']]

Processing features:  82%|████████▏ | 80/98 [38:30<08:38, 28.79s/it]

getting sample prompt forgetting sample prompt for 24361
 24360
getting sample prompt for 24362
getting sample prompt for 24363
getting sample prompt for 24364
getting sample prompt for 24365
getting sample prompt for 24366
getting sample prompt for 24367
getting sample prompt for 24368
getting sample prompt for 24369
getting sample prompt for 24370
getting sample prompt for 24371
TOP TOKENS [['honest', 'honested', 'honeste', 'test', 'honests', 'honestly', 'honestmiddle', 'honestus', 'honesting', 'genuine', 'salt', "day's", 'sincere'], ['honesty', 'honest', 'age', 'honesty[edit'], ['honest', 'honesty', '“', 'others', 'may'], ['honest', 'honesty', 'values', 'etc', 'week'], ['honesty', 'honest', 'community'], ['honest', 'honesty', 'say', 'principle', 'soon', 'dictionary', 'honestly'], ['honesty', 'honest', 'honesty….don’t', 'children', 'czafft2.wordpress.com', 'exactly', 'hearts'], ['honesty', 'honest', 'life', 'sharpens', '…', '1'], ['honest', 'honesty', 'things', 'behavior', 'wrong', 'fearless', 'happiness', 'person', 'life'], ['honest', 'honesty', 'sharpens', 'true', 'etc', 'honestythink', 'open', 'truthful', 'others'], ['honest', 'honesty', 'honestus', 'fairness', 'album', 'honestly', 'rodney', 'song', 'alex', 'lisa'], ['honest'], ['honest', 'coughlan'], ['honestbrew', 'named', 'startups', 'history', 'breweries', 'industry-wide', 'initial', 'also'], ['honest', 'honestech', 'https://www.honestech.com', 'mpeg', 'based', 'nscreen', '2.0'], ['honest', 'prison', 'second', '21:00', 'also', 'taking', 'week', '16', 'direct', 'school'], ['honest', 'july'], ['honestus', 'honesty', 'honestis'], ['honest'], ['honesty', 'staffed', 'guest', 'continuously', 'account', 'consumption']]
TOP TOKENS [['sociology', 'sociologists', 'sociologist'], ['sociology', 'sociological', 'sociologists'], ['sociologists', 'sociology', 'sociological', 'lives'], ['sociology', 'sociologists'], ['sociology', 'sociologists', 'sociological'], ['sociology', 'sociologists', 'sociological'], ['sociological', 'sociology'], ['sociology', 'sociologists', 'ethnicity'], ['sociologists', 'sociology', 'put', 'simply', 'choose', 'time'], ['sociology', 'sociologists', 'sociological'], ['sociology'], ['sociology', 'sociological'], ['sociology', 'sociological', 'sociomusicology'], ['sociologist', 'sociologists', 'sociology', 'sociological', 'eileen', 'american'], ['sociology', 'sociological'], ['sociologists', 'sociology', 'sociological', 'put', 'agency', 'cls', 'social', 'institutions'], ['sociologists', 'sociology', 'sociological', 'etc', 'cls', 'institutions', 'three'], ['sociology', 'sociological', 'david', 'view'], ['sociology'], ['sociological', 'sociology']]
TOP TOKENS [['mmr', 'mmrv'], ['mmr'], ['mmr'], ['mmr', 'current'], ['mmr', 'mmrv', 'get', 'called', 'vaccine', 'aids'], ['mmr', 'think'], ['mmr', 'mmrthequestions', 'mmrthefacts'], ['mmr', 'outbreak', 'shot', 'vaccine'], ['mmr', 'people', 'vaccination'], ['mmr', '77', 'vaccine', 'since', '303', '316'], ['methuselah', 'mmp', 'papyrus', 'germany', 'job', 'mixed-member', 'political', 'industry', 'party', 'per', 'miss', 'mm&p', 'county', 'labor', 'moldova', 'millington', 'milliliter'], ['mmr', '100,000', 'alpha-3', 'mesozoic', 'per', 'label', 'interconnectivity', 'ports'], ['mmb'], ['mms-class', 'under-construction', 'mms', 'subway', 'school', 'methanesulfonate', 'real', 'mérito'], ['mmy', 'v/line'], ['mmu', 'disambiguation', 'mmv'], ['1999', 'mm7'], ['mmi', 'former', 'rome', 'nyse', 'millersburg', 'marymount', 'see', 'freeland', 'unstructured', 'skills'], ['mmx', 'mm5'], ['transmission', 'transport', 'mmt']]
TOP TOKENS [['pearson', '7', '504', 'sep'], ['pearson', '—', 'sure', 'long', 'lined', 'year', 'charmed', 'specialist', 'preston'], ["pearson's", 'pearson', 'solutions'], ['pearson'], ['pearson', 'university'], ['pearson', 'university'], ['pearson', 'org', 'example'], ['pearson', "pearson's", '1892', 'lecture', 'e', 'society', 'questions', 'race', 'whole'], ['pearson', 'man', 'techniques', '447', 'analysis', 'also', '473'], ['pearson', 'man', 'techniques', '447', 'analysis', 'also', '473'], ['pearson', "pearson's", 'series', 'texas', 'airport'], ['pearson', 'medina', 'natalia'], ['pearson', 'e', 'eric', 'beatrice', 'lynn', 'ethel', 'denise', 'corey'], ['pearson', "pearson's", 'fleming', 'l', 'fire', 'men', 'opened', 'civil', 'military', 'history'], ['pearson', "pearson's"], ['pearson', '31', '9', '38', 'latino', 'individuals', 'hispanic', 'older', '45', '2'], ['pearson', 'bowfinger', 'lyle', 'rouse'], ['pearson', "pearson's", 'july', 'netherlands', '2021', 'international', 'links', '2019', '2023', 'redstat'], ['pearson', 'morris', 'k', 'sigma', 'international'], ['pearson', "pearson's", '1981', 'web', 'returns', 'site', 'teams', 'overall', 'corporations', 'league', 'official', 'also', 'franco', 'harris', 'links']]
TOP TOKENS [['excerpt', 'exclusively', 'true', 'http://www.westernforschungszentrum.de', 'especially', 'despite'], ['excerpt'], ['today', 'classroom', 'short', 'effective', '—'], ['excerpt', 'excerpts', 'publisher'], ['excerpts', 'excerpt', 'atlanta', 'reading', '2014', 'rocks', '1', 'pitcher', '2', 'two', 'already', '1914', 'readers'], ['city', 'drug', 'stds', 'pamphleteer', 'excerpt:â', 'bringing', 'revolution', 'laws'], ['excerpt', 'time', 'recorded', 'patients', 'one', 'nonhallucinating', 'heads”', 'activity'], ['victories', 'excerpt', 'progress', '1992', 'ups', '1995', 'incremental', '1980', 'retrospect', 'major', 'cls', 'changes', 'los', 'mid', 'promise', 'subsequent', 'leaders', 'unrequited'], ['anchor', 'openings', 'excerpt', 'right', 'became', 'plane', 'toward', 'cloud', 'pre', 'counted', 'across', 'seen', 'one', 'visible', '’', 'ocean', 'knew', 'small', '0749'], ['excerpt:â', 'skills'], ['excerpt', 'parker', 'j', 'matusow', "locke's", '1994', 'rossinow', 'liberalism', 'ed', 'debunks', 'mckee'], ['excerpt', 'wine', 'smokey', 'folklorists', "are'we", 'number', 'songs', 'catalog'], ['excerpt', 'sep'], ['excerpt', 'present', 'following', 'darts', 'writer', 'women', 'also', 'misogyny', 'nature', 'heterosexuality', 'possessor', '1556', 'one', 'decades', 'companions', 'various', 'stereotype', 'pairs', 'homosexual', 'sodomy', 'debated', 'rapturously'], ['time', 'dilated', 'excerpts', 'body', 'grasp', 'excerpt', 'center', 'pace', 'speaking', 'read', 'still', 'night', 'beyond', 'well', 'seen', 'times', "tomorrow's", 'modesty', 'thoughts', 'wrote', 'almost', 'book'], ['excerpt', "columbus's", '–', "honor'in", 'ii', '255', 'reinhard', '76', 'n', 'perlstein', 'unmaking', 'patterson', '2009', 'history', 'rick', 'bogus', 'p', 'b', 'crunden', 'since'], ['excerpt', 'wijeratne', 'monsters', 'could'], ['excerpt', 'soundtrack', 'husker', 'recorded', 'benefited', 'corpse'], ['excerpt', 'survey', 'scholars', 'relations', 'trefousse', 'trommler', '–', '”', 'frank', '1985', 'cooperation', 'meyer', 'gross', 'bonner', '1990', 'press', 'essays', 'american', 'herring', 'borrow', '2006', 'eds'], ['excerpt', 'following', 'hemispheres', 'would', 'represents', 'diverse', 'prevent', 'touching', 'also', 'value', 'book', 'g', 'know', 'ever', 'able', 'see', 'capable', 'tolstoy', 'building', 'things', 'though', 'economy']]
TOP TOKENS [['expectations', 'expected', 'expect', 'expecting', 'impacting', 'expectation', 'friend'], ['expect', 'expectations', 'manage', 'expected', 'frustrating', 'set', 'meet'], ['expectations', 'expecting', 'expect', 'expectation', 'probably', 'unexpressed', 'unwarranted', 'hoping', 'disappointed'], ['expectations', 'expect', 'cls', 'expectation', 'happen', 'manage', 'surprised', '“', 'fault', 'assumptions'], ['expectations', 'expect', 'expectation', 'nourish', 'etc', 'react', 'created', 'pass'], ['expectations', 'expected', 'expectation', 'surprising', 'desired', 'target', 'cls', 'schedules', 'occur', 'unexpected', '”', 'specific', 'changed'], ['expect', 'expected', 'unexpected', 'anticipated', 'turn', 'today', 'expects', 'coming', 'behaviors', 'look', 'mullins'], ['expectations', 'expect', 'manage', 'managing', 'expectation', 'management', 'effectively', 'expected'], ['expectations', 'expect', 'expectation', 'affect', 'clear', 'meet'], ['expectations', "expect('short').is_long", 'expected', "expect('loooooong').is_long", 'expect.raises(mycustomerror', 'raises(expected_cls=<type', 'expected_cls', 'expect', 'expectation', 'expect(4', 'expecter.expect(actual)¶', 'expecter', 'expect(5', 'add_expectation(is_long', 'e.g', 'using'], ['unexpected', 'expected'], ['expectations', 'great', 'expectation', 'kittler', 'album', 'expectations/overture', 'waltz', 'day'], ['expect', 'unexpected'], ['expectations', 'surprise', 'expectation', 'expect', 'expected', 'expectancies', 'unfavorable', 'happen', "one's"], ['expectations', 'luck', 'luck/sheehan', 'gent/jones/luck', 'hopes', 'exponents', 'chart', 'greater', 'singles', 'sunset', 'weeks'], ['expected', 'also', 'ignores', 'see', 'perfect', 'expectation'], ['expectations', 'value', 'chicago', 'trading', 'associates', 'newsletter'], ['expectations', 'cls', '2020', 'danton', 'scored', '—', 'depth', '100', 'exclaim', 'ballads', 'depression', '00'], ['continuation', 'unexpected', 'k.a', 'anticipation'], ['expectations']]
TOP TOKENS [['shepard', 'role', '1986', 'home', '2005', 'knocking', 'also', 'life', 'nominations', 'ago', 'one', 'web', 'years'], ['shepard', "shepard's", 'world', 'people', 'murder', 'matthew', 'later', '2008', 'also', 'movie'], ['shepard', 'b', 'cancelled', 'mission', '1971', 'mercury', 'annapolis', 'nausea', 'bartlett'], ['shepard', 'alan', '1995', 'also', 'usns', 'showing', 'honors', '1994', '1984', '1962', '1977', 'awards'], ['shepard', 'alan', 'b', 'usns', 'survey', '’', 'beach'], ['shepard', 'mission', '1971', '1974'], ["shepard's", 'shepard', 'matthew'], ['shepard', "shepard's", 'gaybashers', 'matthew', 'discredit', 'also'], ['shepard', 'allow', 'minutes', 'cross', '1961', '7', '’', 'pride'], ['shepard', 'shepard-byrd', 'matthew', 'unfortunately', '2009', 'week', 'found'], ['shepard', 'giants', 'pirates', 'mustangs', 'links'], ["shepard's", 'shepard', 'fiction', '2008', 'official', 'kelly', 'time', 'century', 'much', 'links', 'society', 'novelists'], ['shepard', '1946', 'deaths', 'alabama', 'african-american'], ['shepard', 'f', 'u.s', 'house'], ['shepard', "shepard's", 'placed', 'revisit', 'female', 'candidate', 'although', 'version', '2014'], ['shepard', "shepard's", 'series', '1', 'give', 'recorded', 'people', "men's", '000', 'percentage'], ['shepard', 'proposed', 'capital', 'party', 'april', '1953', '1955', 'deaths', 'change', 'sep', '67', 'committee', 'consolidation'], ["shepard's", 'shepard', 'recovered', 'honor', 'however'], ['shepard', '1901', 'college'], ['shepard', 'time', '2015', '2018', 'began', 'fantasy', '14', 'appearing', 'poehler', 'part', 'braverman', 'also']]
TOP TOKENS [['sassafras', 'sassafrax', 'gastrointestinal', 'molasses', 'safrole'], ['sassafras', 'sassafras-smoked'], ['sassafras'], ['sassafras', 'sassafra', 'surpass', 'leaves', 'one', 'safrole'], ['sassafras', 'brown'], ['sassafras', 'practice', 'red', 'scaly', 'first', 'three', 'soaps'], ['sassafras'], ['sassafras', 'tree'], ['sassafras'], ['sassafras'], ['sassafras', 'song'], ['sassafras'], ['sassafras'], ['sassafras', 'century'], ['sassafras'], ['sassafras', 'safrole'], ['sassafras'], ['sassafras', 'safrole'], ['sassafras', 'bobwhite', 'animals'], ['sassafras', "sassafras's", 'america', 'trees', 'glabratus', 'areas', 'flowers', 'north', 'carolinas', 'main']]
TOP TOKENS [['revolver', 'revolvers', "revolver's", 'certain'], ['revolvers', 'revolver', 'handgun'], ['revolver', 'revolvers', 'handgun'], ['revolvers', 'revolver', 'handgun'], ['revolver', 'revolvers', 'handgun', 'pistols', 'cls'], ['revolvers', 'revolver', 'longer', 'place', 'cylinder'], ['revolver', 'revolvers', 'advancements'], ['revolver', 'revolvers'], ['revolvers', 'revolver', 'drawn', 'cartridge'], ['revolvers', 'revolver', 'longer', 'release'], ['revolver', 'comics', 'album', 'rock'], ['revolver'], ['revolver', 'handgun', 'action', '6'], ['revolver', 'action'], ['revolver'], ['revolver', 'cylinder'], ['revolvers', 'revolver', 'firearms', 'chambered', 'double-action', 's&w', 'pistol', '357'], ['revolvers', 'revolver', 'snubnosed', 'cylinder', 'wesson', 'caliber'], ['revolver'], ['revolver', "revolver's", 'revolvers', 'cylinder', 'pistol']]
TOP TOKENS [['bodybuilders', 'bodybuilder', 'bodybuilding', '1970s', 'cls', 'make'], ['bodybuilders', 'bodybuilder', 'bodybuilding', 'visually'], ['bodybuilders', 'bodybuilder', 'bodybuilding', 'cls', 'conditioning', 'technique'], ['bodybuilders', 'bodybuilding', 'many'], ['bodybuilder', 'bodybuilders', 'bodybuilding', 'goal', 'cycle', 'carbohydrates'], ['bodybuilder', 'bodybuilders', 'bodybuilding', 'cls', 'definition', 'makes', 'injuries'], ['bodybuilders', 'bodybuilding', 'cls', '“', 'better'], ['bodybuilding', 'bodybuilder', 'bodybuilders', 'today', 'becomes'], ['bodybuilders', 'bodybuilder', 'bodybuilding', 'cls'], ['bodybuilding', 'bodybuilders', 'period', 'became'], ['bodybuilders', 'bodybuilder', 'bodybuilding', 'cls'], ['bodybuilders', 'bodybuilder', 'bodybuilding', 'drugs', 'grooming'], ['bodybuilders', 'bodybuilding'], ['bodybuilder', 'bodybuilders', 'bodybuilding', 'gyms'], ['bodybuilding', "women's", 'b', "macfadden's", 'outgrowth', "men's"], ['bodybuilders', 'bodybuilding', 'bodybuilder'], ['bodybuilders', 'bodybuilding', 'successful', 'day', 'events', 'steroids'], ['bodybuilders', 'bodybuilding', 'bodybuilder'], ['bodybuilder', 'bodybuilding', 'bodybuilders', 'become', 'field', 'competitive', 'career', 'taking', 'title', 'champion', 'finals'], ['bodybuilding']]
TOP TOKENS [['toward', 'hold', 'etc', 'get', 'receive'], ['etc', 'points'], ['etc', 'toward', 'give', 'establish', 'expressing'], ['undertake', 'join', 'making', 'go', 'combine'], ['etc', 'give', 'toward', 'establish'], ['v', 'bring', 'like'], ['thing', 'onto', 'toward'], ['toward', 'lower', 'reduce', 'adj'], ['found', 'moving'], ['thing', 'toward', 'involved', 'onto', 'etc', 'completion'], ['sound', 'therefore', 'servient', 'signifies', 'something', 'servitude', 'given', 'p', 'conveys', 'quality', 'action', 'property', 'negative', 'together', 'lat', 'either', 'proceeding', 'lands', 'conveyed', 'specific', 'wherefore', 'lease', 'act', 'joining'], ['merge', 'together', 'put', 'installation', 'influence', 'permanent', 'redress', 'things', 'reference', '–', 'english', 'remedy', 'compare', 'pressure', 'refer', 'used', 'equals', 'n', 'cantonment', 'someone'], ['something', 'like', 'lavatory', 'handcuffs', 'fellow', '1', 'enraged', '2', 'outstanding', 'policeman', 'get', 'dekho', 'force', "feel'or'cop", 'remove', 'excellent'], ['etc', 'put', 'ought', 'get', 'outbid', 'see', 'forgo', 'make', 'lean', 'lay', 'present', '–', 'leant', 'set', 'speak', 'might', 'interweave', 'let', 'leave', 'output', 'foresee', 'knelt', 'lent', 'forsake', 'got'], ['ko', 'kɪj', 'ka', '‘', 'skin', 'kok', '’', 'lay'], ['please', 'something', 'g', 'forward', 'e', 'bring', 'setting', 'journalist', 'messenger', 'redressal', "a'namaskar", 'due', 'reporter'], ['3', "off'school", "backronym'council", '2', 'woman', "to'do", 'blunder', "to'bunk", 'something', "in'it's", 'intercourse', 'someone', 'dick', '1', 'toast', 'clogs', 'nervousness', 'verb', 'spot', 'hook', 'conversation'], ['make'], ['mitigate', 'militate', 'something', 'game', 'exert', "have,'ve", 'happen', 'mitigated', 'increased', 'efficiency', 'make', 'novitiate', 'however'], ['fr', 'governasp', "rien'thing'fr", 'governasrd', 'choseocc', 'rengsc', "for'subject", 'pt', 'causacat', 'ofr', 'mesurarpt', 'ro', 'causait', 'sp', "rispettano'respect'fr", 'chossavgl', 'rienlim', 'nomgsc', "mensura'measure", 'governetfr', "res'nothing'sp", 'arrenopt', 'accofr', 'gouverneocc', "rese'head", 'governait', 'arresocc', 'mesurerocc', 'cosaopt', 'cosaosrd', "respectent'respect", 'mesurarcat', 'subiteocc', 'cosasp', 'medirsrd', 'governacat', 'envindrentosrd', 'reppererunt', 'mesuˈrare', 'mesurarrms', 'ressrd']]
TOP TOKENS [['eagles', 'bald', 'even'], ['eagles', 'bald', 'even'], ['eagles', 'bald'], ['eagles', 'bald'], ['eagles'], ['eagles', 'bald', 'wintering', 'summer'], ['eagles', 'bald', 'brooding', 'young'], ['eagles’', 'eagles', 'bald'], ['eagles', 'bald', 'beak', 'rivers'], ['eagles', 'amongst', 'bald'], ['eagles', 'film', 'team', 'c', 'sports'], ['eagles', 'eagle', 'golden', 'israeli'], ['eagles', 'bald', '100', 'beak', 'since', 'immature', '1970s', 'less'], ['eagles', 'bald', 'waters', 'wintering', 'even', 'sensitive'], ['eagles', 'bald', 'parents', 'attacked', 'eagle', 'habits', 'prey', "carcass's"], ['eagles', 'bald', 'wintering', 'eagle', 'average', 'averaging', 'scaled', 'long', 'raptors'], ['eagles', 'bald', 'golden', 'eagle', 'high', 'vultures', 'fall', 'talons'], ['eagles', 'adults', 'numbers', 'golden', 'range', 'migrant', 'whereas', 'male', 'scotland'], ['eagles', 'eagle', 'golden'], ['eagles', 'fledgling', '7', '0', 'wales', 'respectively', 'eggs', 'new', 'infrequently', 'around', 'south']]

Processing features:  83%|████████▎ | 81/98 [38:59<08:10, 28.83s/it]

getting sample prompt forgetting sample prompt for 24373
getting sample prompt for 24374
 24372
getting sample prompt for 24375
getting sample prompt for 24376
getting sample prompt for 24377
getting sample prompt for 24378
getting sample prompt for 24379
getting sample prompt for 24380
getting sample prompt for 24381
getting sample prompt for 24382
getting sample prompt for 24383
TOP TOKENS [['countries', 'country||capital', 'african', 'list', 'central', 'pretoria||5,495,724'], ['country', 'capita', 'countries', 'people', 'per'], ['groupings', 'countries'], ['countries', 'country', 'groupings'], ['countries', 'country'], ['community', 'organization', 'saarc', 'development'], ['countries'], ['countries', 'rank||country', 'list'], ['diplomatic', 'country', 'countries', 'it’s'], ['countries', 'country'], ['countries', 'country', 'list', 'lists'], ['capita', 'countries', 'country', 'per'], ['countries', 'list', 'guinea-bissau'], [], ['bosnia-herzegovina', 'tables', 'herzegovina'], ['sub-prefectures', 'administrative'], ['bouca', 'ouham-pendé', 'ouham-fafa', 'republic', 'african', 'prefecture', 'sub-prefectures'], ['bosnia-herzegovina', 'herzegovina', 'herzeg-bosnia', 'srpska', 'list', 'sportsport.ba', 'republika'], [], ['capita', "country's", 'groupings', 'countries', 'low-income', 'non-sovereign', 'per', 'entities']]
TOP TOKENS [['interactively', 'run', 'e', 'installation', 'g', 'delphi', 'specified', 'provided', 'required', 'facilitate', 'various', 'structure', 'may', '10', 'two', 'variety', 'output'], ['straightforward', 'online', 'maintain', 'better', 'delphi'], ['use', 'read', 'hand', 'next', 'colon', 'differentiate', 'daily', 'using', 'meet', 'hope', 'performance', 'offers', 'delphi', 'development', 'bit', 'programming'], ['unhappy', 'tightly', 'markets', 'little', 'judgments', 'interpret', 'areas', 'structured', 'rounds', 'connotation', 'several', 'delphi', 'pilot'], ['…', 'engage', 'marvellous', 'clarity', 'delphi', 'exist', 'knowledgeable', 'avow', 'ant', 'available', 'natured', '’', 'introduced', 'compendious'], ['delude', 'deluding', 'delusively', 'delusion', 'deluded', 'delusioun', 'deludere', 'delusio'], ['tells', 'instance', 'handling', 'cause', 'commands', 'flags', 'get', 'moment', 'inevitably', 'like', 'anticipate', 'delphi', 'note', 'uses', 'merely', 'comes', 'influence', 'course'], ['us', 'issues', 'kuusi', 'use', 'collecting', 'need', 'method', 'developed', 'additional', '6', 'meaningful', 'precise', 'transmitter', '4', 'delphi', 'would', 'dealing'], ['material', 'confusions', 'based', 'examined', 'delphian', 'still', 'act', 'program', 'amount', 'delphi', 'need', 'information'], ['america', 'milestone', 'latin', 'tricks', 'developers'], [], ['portal'], ['2008', 'deluge', 'genesis', 'saint-saëns', 'clézio', '1928', 'fowler', 'fireboat', 'historical', 'flood', 'myths', 'wright'], ['declared', 'established', 'community', 'near', 'lies', '1923', '1892'], ['spiders', '1935', 'delena'], ['suspense', '1955', 'misunderstanding', 'superior', '2005', 'israeli', 'fundamental', 'to-mera'], ['1842', 'journalist', 'personality', 'chairman', 'captain', 'banker', '1823', '1775', '1890', 'photographer', '1980', 'businessman', 'songwriter', 'american', 'family', '1941', 'county'], ['westmeath', 'ireland'], ['deleni', 'breznița-motru', 'dobrin', 'iași', 'village'], ['1951', '1920–1973']]
TOP TOKENS [['rock', 'wharves', 'rocky', 'whittled', 'boulders', 'bulkheads', 'however', 'represented', 'brewster', 'explanation', 'rap', 'wetlands', 'etc', 'habitat'], ['rock', 'wharves', 'rocky', 'whittled', 'boulders', 'bulkheads', 'however', 'represented', 'brewster', 'explanation', 'rap', 'wetlands', 'etc', 'habitat'], [], [], ['strollers', 'beachgoers', 'people'], ['train-mounted', 'people', 'quarter-mile', 'visitors', '—', 'it’s'], ['p'], ['walkers'], [], ['people', 'matches', 'surface'], [], ['mrs', 'del', 'mr', 'ms'], [], ['by-election', 'st', 'nursing', 'capital-value', "john's", 'rental-value', "city's", 'revelled', '1981'], ['anyone', 'peace'], ["o'brien-moore", 'mr', 'black-and-white', 'ruggles', 'kinescope', 'city', 'named', '1950–51', 'donald'], ['1930', 'ruggles', 'retirement', 'p', '–', 'c', 'baltimore', '1927', 'states', 'carolina', 'l', 'america', 'engineers', 'association', 'legion'], [], ['california', 'television'], ['park-and-ride']]
TOP TOKENS [['give', 'gave', 'see', 'something', 'gift'], ['giving', 'mammas', 'one', 'dance-giving'], ['given', 'give', 'giving', 'bestowed', 'receiving', 'receive', 'giver', 'thank', 'gift', 'thanking', 'gratitude'], ['give', 'receiving', 'given', 'receive', 'bestows', 'giving', 'gift', 'giver', 'gives', 'thank', 'gifts', 'thanks', 'gratitude', 'recipient'], ['give', 'bestowed', 'gave', 'receive', 'giving', 'something', 'showing', 'provided', 'gratitude', 'appreciate', 'recipients', 'taught', 'providing', 'givers', 'gift'], ['give', 'giver', 'manner', 'giving', 'receive', 'offering', 'gratitude', 'given', 'kindness', 'gift', 'receiving', 'received'], ['gives', 'give', 'given', 'recipients', 'gift', 'return', 'bestirs', 'something', 'promised'], ['give', 'given', 'giving', 'gifts', 'gift', 'giver', 'receiving', 'someone', 'sender'], ['give'], ['appreciate', 'give', 'gratitude', 'giving,â', 'receive', 'shown', 'giving', 'gifts', 'get', 'gift', 'given', 'ever'], ['receive', 'municipality', 'giving', 'give', 'ep'], ['give', 'gonna'], [], ['give', "recipient's", 'expectation', 'album'], ['give', 'something'], ['give', 'los'], ['give'], ['give'], ['give', 'gift', 'given', 'japanese'], ['givers', 'favor', 'give', 'give-n-take']]
TOP TOKENS [['trays', 'tray', 'design', 'stages', 'across', 'crossflow', 'towers', 'flow', 'columns', 'column', 'top'], ['tray', 'trays', 'tinker', 'inside', 'prefer', 'skills', 'projects'], ['tray', 'trays', 'tinker', 'inside', 'prefer', 'skills', 'projects'], ['trays', 'tray', 'stages', 'must-have', 'different', 'shape', 'adults', 'efficiently', 'experiences', 'numerical', 'play', 'child'], ['trays', 'tray', 'stages', 'must-have', 'different', 'shape', 'adults', 'efficiently', 'experiences', 'numerical', 'play', 'child'], ['trays', 'tray', 'make', 'time', 'made', 'run', 'motor', 'making', 'bolting', 'one'], ['trays', 'tray', 'make', 'time', 'made', 'run', 'motor', 'making', 'bolting', 'one'], ['trays', 'tray', 'low', 'purpose', 'procedure', 'monitor', 'etc'], ['tray', 'trays', 'using', 'fact', 'work', 'paper', 'stored', 'shelf', 'wooden'], ['trays', 'seedlings', 'herbs', 'size', 'set', 'treat', 'used', 'thus', 'great', 'grow', 'well', 'growth'], ['items', 'tray', '1860–1905'], ['trays', 'cuttings', 'pulp', 'tray', 'seed', 'cls', 'items', 'melamine', 'surface', 'sheet', 'theaters', "butler's", 'cafeterias', 'edges', 'hotels'], ['trays', 'tray', 'cuttings', 'seed', 'sized', 'impression', 'oven', 'photography', 'corrosion'], ['trays', 'tray', 'birthing', 'two', 'luciano', 'called'], ['trays', 'tray', 'material', 'disposable', 'customised', 'plastic', 'term', 'make', 'dentistry', 'special', 'stock', 'use'], ['trays', 'tray', 'spoons', 'spoon'], ['tray', 'hoosiers', '19th-century', '1905', 'james', 'minor', 'february'], ['trays', 'tray', 'cable', 'cables', 'types', 'laid'], ['tilt-tray'], ['tray', 'name', '1985', '1992–2016']]
TOP TOKENS [['napoleon', '“', 'campaigns'], ['napoleon', "napoleon's", '1808', 'code', 'today', 'union', 'nelson'], ['napoleon', 'bonaparte', '24', 'battle'], ['napoleon', 'napoleone', 'napoleonic', 'bonaparte'], ['napoleon', 'bonaparte', 'corruption', 'anymore', 'actuality', '’', 'foremost'], ['napoleon', "napoleon's", 'napoleonic', 'bonaparte', 'voluminous', 'one', 'knew'], ["napoleon's", 'napoleon', 'napoleonic', '1803'], ['napoleon', 'napoleonic', 'bonaparte', 'revolution', '“napoleonic'], ['napoleon', 'study－napoleon', "napoleon's", 'bonaparte', 'napoleonic', '1785,he'], ['napoleon', "napoleon's", 'napoleone', 'napoleonic', 'bonaparte', 'reform', 'territory'], ['napoleon', 'napoléon', '1807–1883'], ['napoleone', 'napoleon', 'bonaparte', '–'], ['napoleon'], ['napoleons', 'napoleon'], ['napoleon', 'napoléon', 'bonaparte'], ['napoleon', 'census'], ['napoleone', 'napoléon', 'bonaparte', 'colajanni', 'orsini'], ['napoleon', 'huxford'], ['napoleon', '46', 'bonaparte', 'households', '3', '8', '2', '1', 'emperor', '36', 'geography', 'cls'], ['napoleon', 'napoléon', "napoleon's", 'austerlitz', 'napoleonic', 'italian', 'french']]
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], ['–', '0', 'respectively', 'shoulders', 'case', 'body', 'makes', 'buttocks', 'females', 'results', 'proportionally', 'hip'], ['−6', 'magnitude', '2', 'similar', '1', 'show', 'possibly'], [], [], [], ['notably'], ['m199', 'l341', 'l883', 'l330', 'tree', 'l805', 'l570', 'l332', 'l889', 'pages126', 'l569', 'l890', 'l456', 'l884', 'l886', 'p106', 'l891', 'l329', 'l568', 'l571', 'l807', 'l400', 'l766', 'l804', 'l191', 'l334'], [], [], ['5']]
TOP TOKENS [['monaco', 'monte', 'cls'], ['monaco'], ['monaco', 'monaco.the'], ['monaco', "monaco's", '2001', 'genoa', '1993', 'finance'], ['monaco', "monaco's"], ['monaco', 'extinct', 'cls', 'regime'], ['monaco.the', 'monaco', 'however', 'principality'], ['monaco', 'monaco.the', 'climate', 'principality'], ["monaco's", 'monaco', '1993', 'french', 'principality', 'clarifies'], ['monaco'], ['monaco'], ['monaco', 'mónaco', '17th-century', 'band', 'album'], ['monaco', 'eu'], ['monaco', 'monte'], ['monaco'], ['monaco'], ["monaco's", 'monaco', '2005', 'monte', 'carlo'], ['monaco', 'exotique'], ['monaco'], ['monaco']]
TOP TOKENS [['connector', 'connectors', 'number', 'popular', 'type', 'different', 'defines'], ['connector', 'connectors'], ['connector', 'connectors', 'output'], ['connectors', 'connector', 'rise', 'overqualified', 'different', 'needs', 'various', 'customized'], ['connectors', 'connector', 'shelf', 'comes', 'power', 'demands', 'weaknesses'], ['connectors', 'connector', 'right', 'suggest'], ['connectors', 'connector', 'granted', 'equipment', 'increasing', 'device', 'taken', 'compact', 'placed', 'resulting', 'unnecessary'], ['connector', 'connectors', 'type', 'variety', '4mm', 'sturdy', 'cls', 'include'], ['connector', 'connectors', 'becomes', 'input', 'accordingly', 'type', 'portability', 'since', 'best', 'using', 'use', 'withstand', 'bigger'], ['connector', 'connectors', 'rated', 'systems', 'choose'], ['connector', 'software', 'science', 'plugs', 'ac', 'events', 'together', 'primary', 'freeway', 'database'], ['connector'], ['connector', 'connectors', 'berg'], ['connector', 'connectors', 'surface', 'change', 'braces', 'offers'], ['connector', 'connectors', 'efficient', 'also', 'din'], ['connector', 'connectors', '2', '1', '92', 'smaller', 'w', '35', 'rg405'], ['connectors', 'connector', 'many', 'reflection', 'kind', 'polished', 'require', 'g'], ['connectors', 'connector', "connector's", 'power'], ['formed', 'connector', 'connectors', 'bumps', 'onto', 'pin', 'center', 'insulation-piercing', 'contain', 'edge', 'notches', 'side(s'], ['connector', 'frame', 'release', 'fate', 'tightly']]
TOP TOKENS [['inbreeding', 'inbred', 'crossbreeding'], ['inbreeding'], ['inbreeding', 'inbred', 'crossbreeding'], ['inbreeding', 'inbred'], ['inbreeding', 'inbred', 'interbreeding', 'interbreed'], ['inbreeding', 'inbreed', 'interbreeding', 'inbred', 'interbreed', 'breed', 'breeding'], ['inbreeding', 'outbreeding'], ['inbreeding', 'terminology'], ['inbreeding', '’'], ['inbreeding', 'inbred', 'consanguinity'], ['inbreeding', 'crossbreeding', 'inbred'], ['inbreeding', 'inbred', 'outbreeding'], ['inbreeding'], ['inbreeding', 'inbred', 'minimizing'], ['inbreeding', 'outbreeding', 'breeding', 'outcrossing'], ['inbreeding', 'inbred', 'linebreeding'], ['inbreeding', 'inbred', 'intermarriage', 'consanguinity', 'progeny', 'consequences', 'among', 'minimizing', 'descent'], ['inbreeding', 'outbreeding', 'inbred', 'indeed', 'outbred'], ['inbreeding', 'inbred', 'industry'], ['inbreeding', 'inbred', "mother's"]]
TOP TOKENS [['whose', 'architecture', 'bastions', 'although', 'buildings', 'posts', 'thus', 'order', 'one', 'usually', 'seen', 'often', 'made', 'building', 'provide', 'compound', 'organization', 'show', 'veranda'], ['whose', 'architecture', 'bastions', 'although', 'buildings', 'posts', 'thus', 'order', 'one', 'usually', 'seen', 'often', 'made', 'building', 'provide', 'compound', 'organization', 'show', 'veranda'], ['also', 'omnipresent'], [], ['memorizing', 'true', 'one', 'music', 'stories', 'particularly'], ['voyageur', 'like', "josephine's", "charlot's", "anderson's", 'registres', '1833'], ['voyageur', 'like', "josephine's", "charlot's", "anderson's", 'registres', '1833'], ['cloaked', "travellers'tales", 'fabled', 'smelted', 'cities', "bergh's", 'sunk', '12', 'english', 'although', 'series'], ['directories', 'advertisers', 'well', 'boucaut', "directory'states", 'p', 'j', 'anyone', 'research', 'addition'], ['trapper', 'tail’s', 'agencies', 'particularly', 'several', 'www.mediasd.com', 'although'], ['whose', 'goods', 'voyageurs', 'river', 'include', "women's", 'hides', 'products', 'flints', 'clerks', 'storehouse', 'would', 'firearms', 'although', 'typically', 'also', 'clerk', 'dakota', 'years', 'company', 'furs', 'received', 'since', 'besides', 'historic'], ['business', 'commerce', 'trade', 'store', "ingomar's", "town's", 'prosperity'], ['season'], ['mooers', 'hazen', 'business', 'powder', "bailly's", "shakopee's", 'earn', 'brown', "traders,'not", 'traders', 'according', 'including', 'diligently', 'ever', 'meant', "get'nothing'from", 'ammunition', 'sibley', 'nevertheless', 'even', 'sisseton', 'warned', 'whereas'], ['buildings', 'government', 'homesteading', 'also', 'along', 'served', 'borough'], ['company'], ["lady's", 'also', 'regrouping', "margaret's", "earle's", "sheriff's", "cooper's", 'thereby'], ['trois-rivières', 'political', 'legislative', 'figure', 'canada', 'lawyer', 'canadian', 'saint-maurice', 'also', 'jean-antoine', 'city', 'assembly'], [], ['outposts', 'including', 'also', 'charax', 'like', 'one', 'areas', 'northern', 'inhabitants', 'ones', 'furs', 'territories', 'either', "dolin's", 'could', 'often', 'fueling', 'ocean', 'specifically', 'goods', 'clothing', 'examples']]
TOP TOKENS [['enzymatic', 'enzyme'], ['enzyme', 'enzymatic', "enzyme's", 'enzymes'], ['enzyme'], ['enzyme', 'enzymes'], ['enzyme', "enzyme's"], ['enzyme', 'catalytic'], ['enzyme', 'enzymatic', 'enzymes', 'catalyzes', 'one'], ['enzyme'], ['enzyme'], ['catalyse', 'enzyme', 'conformational'], ['enzymatic', 'enzyme'], ['enzyme', 'substrate', 'enzymes', 'kinetics', 'many'], ['enzyme', 'catalysis', "enzyme's", 'hampers', 'constants'], ['enzymatic', 'enzyme', 'activity', 'allosteric'], ['enzyme', 'enzymatic', 'substrate'], ['enzymatic', 'enzyme', "enzyme's", 'activity', 'substrate', 'inhibitors'], ['enzyme', 'enzymes'], ['enzyme', 'substrate', 'kinetics', 'obeying', 'reaction'], ['enzyme', 'catalyse', 'enzymatic', 'substrate', 'bimolecular', 'reaction', 'thus'], ['enzyme', 'enzymes', 'enzyme–substrate', "enzyme's", 'kinetics']]

Processing features:  84%|████████▎ | 82/98 [39:25<07:31, 28.24s/it]

getting sample prompt forgetting sample prompt for 24385
 24384
getting sample prompt for 24386
getting sample prompt for 24387
getting sample prompt for 24388
getting sample prompt for 24389
getting sample prompt for 24390
getting sample prompt for 24391
getting sample prompt for 24392
getting sample prompt for 24393
getting sample prompt for 24394
getting sample prompt for 24395
TOP TOKENS [['largely', 'empire'], ['embodiments', 'many', 'pedicles', 'illustrative', 'accompanying'], ['puffs', 'luminous', 'one', 'two', 'flashed', 'movements', 'motion', '“', 'another', 'octopus'], ['wondrous', 'enough', 'also', 'lakes', 'air', 'powerful', 'area', 'cover', 'understand', 'awe', 'alerts', 'behold', 'hailstorms'], ['embody', 'embodiment', 'embodies', 'embodying', 'woodrow', 'wilson'], ['pedicabs'], ['stretched', 'flexuous', 'excites', 'petiole', 'perpendicularly', 'twine', 'thinness', 'stick', 'form', 'excessively', 'bend', 'remarkable'], ['presents', 'belly', 'danced', 'references', 'throughout', 'extensions', 'performed', 'talking', 'dancing', 'orgiastic', 'context', 'dancers'], ['radiating', 'almost', 'looked', 'like', 'believe', 'multiplying'], ['onto', 'wafts', 'lakes', 'cyclonic', 'spirals', 'waterspouts', 'earlier', 'especially', 'pond', 'clouds'], ['analogies', 'wittgenstein'], ["gierach's", 'casting', 'championships', 'musings', 'fishes', 'sep'], ['embodiment', 'incarnation', 'knowledge', 'patent', 'embodyment', 'god', 'imagination', 'science', 'cognition', 'embodied', 'entity', 'person', 'design', 'play', 'ideas'], [], ['land', 'matter'], [], [], ['spanned', 'lengths', 'forming', 'times', 'play'], ['roman-era', '208th', 'sources', 'also'], ['brilliant']]
TOP TOKENS [['generator', 'generators', 'comes', 'use'], ['generator', 'generators', 'today’s', 'electricity', 'up’'], ['generator', 'generators', 'outage'], ['generator', 'generators'], ['generator', 'generators'], ['generator', 'generators', "generator's"], ['generator', 'generators', 'electric'], ['generator', 'generators', 'power', 'making', 'portable'], ['generators', 'generator'], ['generator', 'generators', 'help', 'sep', 'portable', 'house', 'last'], ['generators', 'generator', 'engine-generator', 'motor–generator', 'wearable', 'often', 'mathematics', "album's"], ['generator', 'cultoculus', 'god', 'evil', 'machine'], ['generators', 'generator', "generator's", 'design', 'steam', 'stream'], ['generators', "generators'first", '2013', 'videos', 'ep', 'berru', 'bass', 'cls', '1997', 'history', 'another'], ['engine-generator'], ['generator', 'year', 'tour', 'cls', 'scrapped', 'marked', "band's"], ['generators', 'generator', 'electrostatic', 'generation', 'electromagnetic', 'faraday', 'motor', 'even', 'powered', 'cls', 'electricity', 'synchronous'], ['generator', 'generators', 'standby', 'systems'], ['generator', 'generators', "generator's", 'science', 'however', 'iterators', 'iterator', 'continuations', 'ways', 'constructs', 'array', 'values'], ['generator', 'smoke']]
TOP TOKENS [['hack', 'hacked', 'food', '“', 'hacks', '‘', '«', 'someone', 'time', 'life', 'hackers'], ['hacker', 'hack', 'hacks', 'hacking', 'hacked', 'cls', '”', 'life', '“', '–', '’'], ['hack', 'hacking”', 'hack…', 'hacking', 'modding', 'hackthissite.org'], ['hackers', 'hacking', 'hacker', 'hacks', 'programmer'], ['hacking', 'hackers', 'hacker', 'hacks', 'programmer'], ['hackers', 'hacking', 'hacker', 'hacks', 'programmer'], ['hack', '‘', 'hacking', '’', 'system', '“', '”', 'witnessed', 'hackaday', 'enthusiasm', 'head'], ['hacksplaining', 'hack', 'th', '19', 'along', 'say', 'hackers', 'hacking'], ['hack', '“', 'hacks', 'hacker', 'hacking', 'hackers', '”', 'like', 'life', 'let', 'word', 'suggests'], ['hack', 'hackers', 'hacked', 'hacking', 'many'], ['hack', 'hacks', 'cbbc', 'electroclash', 'surname', 'hacker', 'expert', 'hacking', 'centurions', "hornet's", 'security', '1994', 'wasp', 'disambiguation'], ['hacking', 'disambiguation', 'hack', 'hacks', 'also'], ['hacker', 'civil', 'english', '1938–2012', 'leonard', 'dan', 'arthur', 'american', '1913–1990', 'australian', '1910–1994', 'katrina', '1935–2003', 'ice', 'indologist'], ['hack'], [], ["a'hack'was", 'hack', 'hacks', 'hacking', 'hacker', 'hackers', "word'hacker'referring", 'mathematics', 'considered', 'term'], ['häcker', 'birke', 'hacker'], ['hack', 'life', 'kitchen', 'hacker', 'hacking', 'life-hacks', 'hacks', 'term'], ['hack', 'eibel', 'weisel', '1932–2015', 'geomorphologist', 'german', 'southeast', 'born', 'sabine', '1805–1884', 'asia', 'hackworth', '1915–1997', 'karl', 'edward', 'josef', '1972', 'oregon', 'maria', 'counter-insurgency', 'alexander'], ['hacker', 'hacking', 'hack', 'hackish', 'hackers', 'programming', 'sense', 'considered', 'assumed']]
TOP TOKENS [['vegetarian', 'vegetarians', 'vegetarianism', 'cls', 'speaking', 'become'], ['vegetarian', 'vegetarians', 'sense', 'cls'], ['vegetarians', 'vegetarian', 'vegetarianism'], ['vegetarian', 'vegetarians', "what's", 'people', 'exactly'], ['vegetarian', 'vegetarians', "what's", 'people', 'exactly'], ['vegetarian', 'vegetarians', 'lacto-vegetarians', 'ovo-vegetarians'], ['vegetarian', 'vegetarians', 'vegetarianism'], ['vegetarians', 'vegetarian'], ["word'vegetarian'was", 'vegetarian', 'vegetarians', 'vegetarianism', '“'], ['vegetarians', 'vegetarian', 'vegetarianism', 'disease', 'cls'], ['vegetarian', 'vegetarianism'], ['vegetarian', 'vegetarians'], ['vegetarian', 'vegetarianism', '1'], ['vegetarian', 'vegetarianism', 'word', 'society'], ['vegetarianism', 'vegetarians', 'vegetarian'], ['vegetarians', 'vegetarian', 'vegetarianism', 'society', 'identify', 'place', 'mostly', 'diets', 'movement'], ['vegetarians', 'vegetarian', 'healthy', 'cls', 'damage', 'lactating'], ['vegetarian', 'vegetarianism', 'strict', 'society'], ['vegetarian', 'vegetarianism'], ['vegetarians', 'vegetarian', 'vegetarianism', "canada's"]]
TOP TOKENS [['judaism', 'judaism’s'], ['judaism'], ['judaism', 'judaism’s', 'history'], ['judaism', 'cashman'], ['judaism', 'rather', 'bible', 'christianity'], ['judaism', 'ages', 'ago'], ['judaism', 'faith', 'ages'], ['judaism', 'faith', 'ages'], ['judaism', 'family', 'address'], ['judaism', 'understood', 'judaisms', '12', 'fail', 'extents', '8', '10'], ['judaism'], ['judaism', 'links', "called'judaism'and'christianity", 'bibliography', 'external', 'rabbinical', 'rabbinic', 'sep'], ['judaism', 'within', 'christianity', 'rabbinic', 'criticized', 'justice'], ['judaism', 'christianity', 'conclusions', 'atlanta'], ['judaism', 'rabbinic', 'rabbanite', 'first', 'samaritanism', 'ce', 'bce'], ['judaism', 'history', '587', 'sumerian', 'bce', 'africa', 'mesopotamian', 'monarchic', 'grammatically', 'mythology', 'origins'], ['judaism', 'rabbinic', 'bce', 'cls', 'conflated', 'yahwism', 'century', 'religions', 'foreign', 'canaanite', 'traditions', 'origins', 'yahweh'], ['judaism'], ['judaism', 'studies'], ['judaism', 'rabbinic', 'modern', 'edition', 'ii', 'ancient', 'religions', 'leiden', 'iii', 'harrisburg']]
TOP TOKENS [['correlation', 'correlated'], ['correlation', 'correlated', 'vs', 'among', 'highly', 'within', 'covariance', 'relationship', 'two'], ['correlation', 'calculating', 'based', 'related', 'regarding', 'level'], ['correlation', 'correlated', 'two', 'apply', '0'], ['correlation', 'correlated', 'two', 'coefficient', 'using', 'calculate', 'scatterplot', 'variables', 'one'], ['correlation', 'using', '“correlation', 'relationship', 'coefficient”'], ['correlation', 'factors', 'coefficient', 'calculate', 'quantifies', 'calculator'], ['correlated', 'correlation', 'exists', 'therefore', 'two'], ['correlation', 'allows', 'org', '1', 'two', '2', 'relationship', 'line', 'association'], ['correlations', 'correlation', 'means', 'anywhere', 'measure', 'important', 'various', 'putting', 'two', 'cls', '00'], ['program', 'correlation', 'two', 'correlations', 'values', 'album', 'case', 'cross-correlation'], ['correlation', 'different', '−1', 'two', '±1', 'multivariate', 'several', 'kind'], ['two', 'correlation'], ['correlations', 'correlation', 'equal', 'calculating', 'values', 'sample', 'coefficient', 'x', 'canonical', 'coefficients'], ['correlation', 'correlations', 'curve', 'electricity', 'coefficient', 'produce', 'people', 'coefficients', 'several', 'refers'], ['correlation', 'two', 'econometrics', 'correlations', 'analysis', 'statistical', 'complicated', 'n×q'], ['correlation', 'correlations', 'function', 'spatial', 'uncorrelated', 'across', 'autocorrelation', 'mentioned', 'characterized', 'microscopic'], ['correlations', 'correlation', 'estimating', 'measures', 'measure', 'correlated', 'correlate', 'play', 'several'], ['correlation', 'system', 'full', 'correlated', 'coulomb', 'energy', 'word', 'related', '–', 'earlier'], ['correlation', 'following', '1', '7544', 'variables', 'coefficient', 'two', 'completely', '−1']]
TOP TOKENS [['leprechaun', 'leprechauns'], ['leprechaun'], ['leprechaun'], ['leprechaun', 'leprechauns'], ['leprechaun', 'leprechauns', 'countryside', 'leipreachan'], ['leprechaun', 'leprechauns'], ['leprechaun', 'leprechauns'], ['leprechaun', 'leprechauns'], ['leprechaun'], ['leprechauns', 'leprechaun'], ['leprechaun', 'leprecon', 'lil'], ['leprechaun', 'leprehaun', 'lepreehawn', 'luchrupan', 'luchorpan', "o'reilly's"], ['leprechaun', 'leprechauns', 'stereotypical'], ['leprechaun', 'leprachaun'], ["leprechaun's", 'leprechaun'], ['leprechaun'], ['leprechaun', "leprechaun's"], ['leprechauns', 'leprechaun', 'leprecha', 'america', 'features'], ['leprechaun', 'film', 'another'], ['leprechaun', "leprechaun's", 'films', 'million']]
TOP TOKENS [['mediterranean', 'preferences', 'markers'], ['mediterranean', 'well', 'carbohydrate', 'benefits'], ['mediterranean'], ['mediterranean', 'cholesterol', 'beans'], ['mediterranean', 'word'], ['mediterranean', 'word'], ['mediterranean'], ['mediterranean', 'foods'], ['mediterranean', 'lifestyle', 'foods'], ['mediterranean', 'diet'], ['mediterranean', 'recommendations'], ['mediterranean', '1990s', 'traditional'], ['euro-mediterranean', 'mediterranean'], ['mediterranean', 'diet', 'diseases'], ['mediterranean', 'euro-mediterranean', 'countries', 'pdf', '2008'], ['“mediterranean', 'mediterranean'], ['mediterranean', 'sep', 'additional', 'reading'], ['mediterranean'], ['mediterranean'], ['mediterranean', 'air', "operator's", 'africa', 'hub']]
TOP TOKENS [['c', 'turboc', 'well'], [], ['c'], ['c'], ['c'], ['c'], ['c', 'using'], ['c++?c', 'c'], ['c'], ['c'], ['c', 'throughout'], ['c', 'separate'], ['c'], ['c', 'interpreters', 'computer'], ['c'], ['c'], ['c'], ['c'], ['c', 'c++11', '1991'], ['c', 'built']]
TOP TOKENS [['lister'], ['lister', 'medicine."continue', 'joseph', 'england', 'surgeons'], ['lister', 'lister’s', 'joseph', 'effect', 'infections', 'work', 'germs'], ['lister', 'joseph', 'move', 'putrefaction'], ['lister', "lister's", 'life', 'joseph'], ["lister's", 'lister', 'importance', 'perfected', 'executed'], ['lister', 'scotland', '1877', 'work', 'antiseptic', 'methods', '1897'], ['lister', 'lister’s', 'joseph', 'removed'], ['lister', 'life', 'despite', 'london', 'called'], ['lister', 'sterile', 'infections', 'joseph', '1869', 'anne', 'germs', 'wounds', 'syme', 'acid'], ['lister', 'additionally', 'life', 'personal', 'blog', 'pp'], ['lister', '2014', 'career', '2012', 'life', 'personal', '2016', 'blackpool', '2001', 'also', '2021', 'sons', 'robsonwest'], ['lister', 'md', 'assurance', 'née', 'sanatorium', 'hospital', 'boys', 'mrcp'], ['lister', 'griselle', 'punishment', 'war', 'civil', '1647', '1616', 'life', 'early', 'also', 'née', '1597–1668', 'thomas', '1651', 'warrant', 'act', 'committee', '1653'], ['lister', 'extended', 'election', 'c', '1715', 'thomas', 'franklyn', 'contest', '1710', 'sacheverell', 'general'], ['lister', 'fortunes', 'thomas', 'stakes', 'may', 'time', 'london', 'anxiety', 'realm', 'riding', 'caldwell'], ['lister', "lister's", '1784', 'family', '1797', 'thomas', 'ribblesdale', 'life', 'early', '1723–61', '1794–5', '1780–1784', 'pimlico', 'raised'], ['lister', '2003', 'education', 'oxford'], ['lister', "lister's", 'years', 'treasurer', 'barrister', '2011', '8', 'party', 'anne', 'by-election'], ['lister', "lister's", '1997', 'service', 'seminar', 'women', 'others', 'personal', 'breach', 'ellis']]
TOP TOKENS [['bonsai'], ['bonsai'], ['bonsai'], ['bonsai'], ['bonsai'], ['bonsai'], ['bonsai'], ['bonsai', 'bonsai—caring'], ['bonsai'], ['bonsai', 'since', 'week'], ['bonsai', 'plants', 'film', 'bodies', 'trees'], ['bonsai', 'seeds'], ['bonsai'], ['bonsai', 'bonsais'], ['bonsai', 'tree'], ['bonsai'], ['bonsai', "bonsai's", 'appearance'], ['bonsai', "bonsai's", 'bark'], ['bonsai'], ['bonsai', "bonsai's", 'trees']]
TOP TOKENS [['shooting', 'shoot', 'shots', 'targets', 'shot', 'sighting'], ['aiming', 'shot', 'shooter', 'shots', 'target', 'fundamentals', 'sight', 'fire', 'yard', 'hitting', 'miss', 'firing', 'reticle', 'rifle'], ['shooting', 'aim', 'shoot', 'rifle', 'shot', 'shots', 'gun', 'sighting', 'fire'], ['shooting', 'hit', 'skill', 'shooter', 'shot', 'targeting'], ['shooting', 'shoot', "gun's", 'sighting', 'target'], ['shoot', 'shooting', 'shooters', 'targets', 'shooter', 'skills', 'scope'], ['aim', 'shoot', 'shooting', 'aiming', 'sight', 'aimed', 'target', 'rifle'], ['shooting', 'shooter', 'shoot', 'target', 'hit', 'sighting'], ['shooting', 'things', 'target', 'crosshairs', 'shooters', 'take', 'shot'], ['aiming', 'shooter', 'shot', 'shots', 'miss', 'fundamentals', 'hitting', 'rifle', 'target', 'fire', 'sight', 'firing'], ['aiming', 'shooting', 'sighting', 'rifle', 'shot', 'shooter', 'target', 'scope', 'crosshairs'], ['aim', 'aiming', 'shooting', 'shots', 'shot', 'shooter', 'shooters', 'rifle', 'sighting'], ['aim', 'shooting', 'shots', 'firing', 'targets'], ['shooting', 'hit', 'shot', 'sighting', 'target', 'shooters', 'shooter', 'rifle', 'scope', 'reticle', 'meter'], ['shot', 'target', 'sight', 'scope', 'adjust', 'shooter', 'reticle', 'meters', 'rifle', 'milliradians'], ['aiming', 'shooting', 'aimed', 'adjust', "shooters'skill", 'achieving', 'scopes', 'scope', 'skill', "shooter's", 'crosshairs', 'shooter', 'reticle', 'target', 'rifles', 'reticles', 'point'], ['shooting', 'target', 'shots', 'shot', 'miss', 'scopes', 'scope', 'competitive', "shooter's", "scope's", 'firearm', 'zeroing'], ['aiming', 'shoot', 'aim', 'shooter', 'shooting', 'sighting', 'sight', 'aligns'], ['aim', 'shooting', 'hit', 'shooter', 'misses', 'targets', 'mastering', 'score', 'aimed', 'crosshairs', 'rifle', 'scope', 'target', 'range'], ['aiming', 'shooting', 'shooter', 'sight', 'rifle', 'fire', 'target', 'adjusting', 'accurately', 'rangefinder', 'targets', 'accuracy', 'strike', 'bore']]

Processing features:  85%|████████▍ | 83/98 [39:54<07:04, 28.32s/it]

getting sample prompt forgetting sample prompt for 24397
 24396
getting sample prompt for 24398
getting sample prompt for 24399
getting sample prompt for 24400
getting sample prompt for 24401
getting sample prompt for 24402
getting sample prompt for 24403
getting sample prompt for 24404
getting sample prompt for 24405
getting sample prompt for 24406
getting sample prompt for 24407
TOP TOKENS [['utilizando', 'obtener', 'que', 'se', 'entendera', 'mediante', 'pero'], ['espero', 'seguira'], ['generalmente', 'utilizados', 'contactarme', 'aun', 'de', 'si', 'servirte'], ['ejercitar', 'en', 'publicar', 'caso', 'tienes'], ['completado', 'fotografiar', 'le', 'activamente'], ['por', 'consideren', 'hace', 'continuar', 'su', 'academiaes', 'porque', 'muy', 'nos', 'haciendolo', 'donativo'], ['por', 'consideren', 'hace', 'continuar', 'su', 'academiaes', 'porque', 'muy', 'nos', 'haciendolo', 'donativo'], ['esta', 'estrechamente', 'importante', 'aun', 'se', 'publicamente', 'explotan', 'quienes', 'cuando', 'ahora', 'vuelve', 'encuentran', 'comun', 'tratar', 'garantizar', 'dificil', 'pueden', 'nuestro', 'mas', 'han', 'primero', 'otro', 'forma', 'segundo', 'esto', 'situacion', 'detengan', 'evitar', 'apoyamos', 'permanezcan', 'llevar', 'tejida', 'reaccionar', 'generan', 'lugar', 'simpatizantes', 'vamos'], ['siquiera', 'hablan', 'seguir', 'obviamente', 'evidentemente', 'lo', 'actualizando', 'le', 'aportando', 'se', 'sinceramente', 'que', 'elementos', 'pero'], ['anteponen', 'garantizar', 'cuando', 'apoyamos', 'queremos', 'aquellos', 'permanezcan', 'canalizar', 'cualquiera', 'nosotros', 'ademas', 'exitosamente', 'entonces', 'aun', 'desviar', 'que', 'si', 'el', 'de', 'incluso', 'demuestran', 'encima', 'mejor', 'ausente', 'enfocadas', 'bloquear', 'disponemos', 'perdemos', 'abierto', 'individuos', 'demostrar', 'productivas', 'evitar', 'en', 'erroneamente', 'sentira', 'todas'], ['se', 'otro', 'desnudandose', 'escribiendo', 'crucificado', 'verlos', 'escapar', 'infierno', 'empezar', 'mas', 'de', 'dictadura', 'culpa', 'exprimiendo', 'sigue', 'en', 'con', 'por', 'supervivientes', 'comunistas', 'algunos', 'seria', 'nunca', 'placentera', 'algunas', 'siempre', 'esto', 'mientras', 'fuerte', 'laberintos', 'obligo', 'cortados', 'policial', 'vencer', 'sin', 'gusanos', 'politicos', 'tiempo', 'del', 'disparaba', 'al', 'canciones'], ['taxativamente', 'mediometraje', 'mas', 'relato', 'de', 'entrevista', 'ese', 'que', 'alla', 'lo', 'gratuita', 'es', 'acceso', 'vitales', 'colonizadas', 'decir', 'politica', 'legalmente', 'pueden', 'eltit', 'cuerpo', 'quien', 'en', 'la', 'dirigido', 'libreria', 'signos', 'puedo', 'fuerzas', 'editora', 'viene', 'regresiva', 'escritos', 'eterna', 'descargar', 'contagio'], ['mismo', 'esta', 'la', 'al', 'respuesta', 'opportuna', 'todo', 'nuestro', 'el', 'le', 'se', 'aire', 'quien', 'otro', 'frente', 'de', 'familias', 'noticias', 'compania'], ['fué', 'tener', 'tiene', 'empezo', 'en', 'mucho', 'rencarnado', 'nada', 'salio', 'esto', 'tuvo', 'pese'], ['del', 'blandos', 'las', 'titulo', 'en'], ['quererte', 'yo', 'atrevete', 'diga', 'diente', 'declaro', 'como', 'toda', 'gente', 'nadie', 'libres', 'calle', 'lagrimas', 'duelo', 'el', 'de', 'famosos', 'los', 'estudio', 'aplausos', 'en', 'lo', 'oir', 'sorpresas', 'sopotocientos', 'te', 'una', 'todo', 'alo', 'fama', 'humanos', 'fantastico', 'la', 'estrellas', 'dama', 'todos', 'tengo', 'valores'], ['encuentro', 'inutil', 'nunca', 'facil', 'pregunto', 'problema', 'quieren', 'sus', 'busca', 'volviera', 'pasiones', 'la', 'veleidades', 'entre', 'novio', 'apuros', 'fui', 'cunado', 'jugadas', 'marca', 'del', 'en', 'intimo', 'deseado', 'calamidades', 'si', 'inesperado', 'un', 'aquellos', 'nadie', 'senorita', 'justificado', 'matrimonios', 'incognita', 'argucias', 'semanas', 'engano', 'chica', 'hombres', 'lo', 'amigas', 'ella', 'las', 'de', 'tita'], ['de', 'aire', 'mejor', 'se', 'al', 'todo', 'limite', 'lo', 'totalvida', 'parodiando', 'frente', 'punto', 'la', 'traje', 'desnudo', 'con', 'mojoe', 'noticiero', 'esta', 'curiosidades', 'en', 'cierta', 'hasta', 'pequenos', 'apuesta', 'constraste', 'ahoraarchivos', 'mueve', 'familias', 'el', 'sin', 'cuentamelo', 'alla', 'del', 'despierta', 'allacronicas', 'noticias', 'hoy'], ['se', 'si', 'querida', 'semblanzas', 'busquemos', 'aquel', 'intimas', 'recuerdo', 'necesito', 'vaivenes', 'primer', 'al', 'experiencias', 'celosa', 'lo', 'intriga', 'raciales', 'ingrato', 'de', 'ayer', 'vacaciones', 'volvamos', 'con', 'momentos', 'verte', 'inquietud', 'razones', 'empleos', 'convenio', 'quiere', 'esta', 'acepto', 'como', 'puedo', 'prejuicios', 'las', 'asi', 'debilidad', 'vuelvas', 'la', 'humanos', 'playa', 'profesora', 'sin', 'testigos', 'situacion', 'aquella', 'en', 'desengano', 'amorosa', 'matrimonial'], ['atinale', 'gusto', 'criada', 'mucho', 'directo', 'primero', 'permiso', 'de', 'siempre', 'contraste', 'sin', 'respuesta', 'mismo', 'contacto', 'en', 'reencuentro', 'todo', 'hoy', 'minutos', 'al', 'mercado', 'se', 'fuera', 'con', 'el', 'noticias', 'adal', 'la', 'noticiero', 'nuevas', 'llevatelo', 'un', 'mananero', 'mueve', 'despertar', 'hora', 'fantastico', 'otro', 'aqui']]
TOP TOKENS [['orcid'], ['iaci'], ['orcid', 'information'], ['ascidiacea', 'ascidia', 'ascidiidae', 'ascidians', 'ascidium'], ['marici', 'angiras', 'atri', '”', 'pulastya', 'मरीचि'], ['ascidia', 'ascidians', 'ascidian', 'p', 'areolata', 'distaplia'], ['orcid'], ['asciidoc'], ['unciunco', 'unci', 'unciuncia', 'word', 'uncus'], ['orcid', 'orcids'], ['kaci-fm', 'kaci', 'kaçi', 'kaci-badon'], ['kuci', 'koći', 'kočí', 'koci'], ['naci', 'nací', 'orishas'], ['oci', 'institute', 'interface', 'occitan', 'company'], ['perci'], ['kočí'], ['raci', 'raći', 'negomir'], ['http://www.citybrazil.com.br/sp/jaci', 'jaci', '5,117'], ['koçi', 'kočí', 'koci'], ['ceci', 'cici', 'çiçi', 'ćići', 'cici-tv', "cici's"]]
TOP TOKENS [['layout', 'layoutmanager', 'default', 'layoutmanager.this', 'layouts', 'various', 'layoutmanager2', 'no.||layoutmanager', 'means', 'layout.it', 'use', 'functionalities', 'one', 'no.||interface', 'possible', 'properties', 'flexible'], ['layouts', 'layout', 'define', 'types', 'make', 'think', 'create', 'default'], ['layout', 'layouts', 'becomes', 'engagement', 'kinds', 'think', 'moves'], ['layout', 'layouting', 'comes', 'various', 'several', 'similarly', 'called', 'represent'], ['layouts', 'layout', 'user', 'construction', 'defining', 'obtain', 'specifies', 'specific', 'found', 'cls'], ['layout', 'great'], ['layouts', 'layout', 'specific', 'different', 'make'], ['layout', 'layouts', 'defines', 'added'], ['layouts', 'layout', 'one', 'different', 'example', 'cls', 'default', 'disable', 'called', 'set'], ['layout', 'layouts', 'using', 'different', 'first', 'auto', 'screen', 'know'], ['layout', 'include', 'dedicated', 'document', 'letters', 'analysis'], ['layout', 'eliminated', 'department', 'especially', 'product', 'according', 'multi-skilled'], ['de:layoutentwurf', 'layout', 'make'], ['layout', 'product', 'stations'], ['layout', 'author(s', 'consumption'], ['layout'], ['layout', 'layouts', 'catalog', 'page', 'later', 'artist', 'sentience', 'publishing', 'history', 'determine', 'involves'], ['layout', 'bring', 'clickers', 'helped', 'used', "90's", 'editor', 'others', 'bit', 'fully', 'unwanted', 'powered', 'area', 'effects'], ['layout', 'retooling', 'plant', 'heinemann', 'facility', 'able', 'reconfiguration', 'becoming', 'choice', 'quality', 'good', 'demand'], ['layout', 'artist', 'supercade', 'island']]
TOP TOKENS [['otitis', 'otolaryngology', 'sep', 'media', 'acute', 'team'], ['otitis', 'otolaryngology', 'media', '1429', 'acute', 'rovers'], ['otitis', 'media', 'acute', 'myringotomy', 'https://doi.org/10.1136/bmj.290.6474.1033', 'specialist', 'alone', 'days'], ['otitis', 'media', 'otitisuptp', 'otolaryngology', 'al', 'evidence', 'html', 'acute', 'overview'], ['otitis', 'media', 'acute', 'pediatrics', 'ogilvie', 'md', 'phd'], ['otitis', 'otorhinolaryngol', 'media', 'otolaryngol', 'acute', '2013'], ['otitis', 'media', 'acute', 'otorhinolaryngol2015792129', 'practitioner', 'otorhinolaryngol2015791429', 'alotitis', 'dis', 'mastoiditis'], ['otitis', 'media', 'otol', 'acute', '1970', 'pubmed', '1985', 'myringotomy', '474'], ['otitis', 'otolaryngology'], ['otitis', 'media', 'otolaryngology'], ['otolaryngology', 'otorhinolaryngology', 'otorhinolaryngological'], ['otitis', 'cls', 'media', 'smoke', 'present', 'symptoms', 'ear'], ['otolaryngology', 'otolaryngological', 'otorhinolaryngology', 'otological'], ['otolaryngology–head', 'otorhinolaryngology', 'otolaryngology'], ['otorhinolaryngology', 'otolaryngology—head', 'otolaryngology', 'otolaryngology–head', 'otorhinolaryngology—head'], ['otitis', 'ear', 'media', 'space', 'myringotomy', 'skull', 'tragus', 'people.otomycosis', 'effusion', 'externa', 'infection', 'bacterial', 'animals', 'canal'], ['otology', 'otorhinolaryngology'], ['otitis', 'media', 'acute', 'harms', 'treat', 'recommended', 'pain', 'oral', 'days', 'complications'], ['otitis', 'media', 'otitic', 'acute', 'ot', 'infants', 'e', 'health'], ['otitis', 'otitidis']]
TOP TOKENS [['wilmington', 'white'], ['wilmington', 'guard', 'well'], ['wilmington', 'guard', 'city', 'corporation', 'well', 'also', 'rebuilds'], ['wilmington', "wilmington's", '2008', 'cls', 'waterfront', 'within', 'spanish', 'schools'], ['wilmington', "wilmington's", 'places', 'city', 'delaware', 'circulation'], ['wilmington', 'www.town.wilmington.ma.us', 'town', 'schoolshawsheen'], ['wilmington', 'city', 'philadelphia'], ['wilmington', 'memorial', 'war', 'city', 'general', 'civil', '’', 'relics'], ['wilmington', 'coming', 'people', '”', 'way', '…', 'area', 'town', '1980', 'population'], ['wilmington', 'youth'], ['wilmington', 'serving', 'school', 'la'], ['wilmington', "wilmington's", '2008', 'pandemic', '1863', 'geography', 'war', '1', 'schools'], ['wilmington', 'census-designated'], ['wilmington'], ['wilmington', '15', 'race', 'geography', 'families', 'cls', 'america', 'individuals', 'houses', '2010', '5'], ['wilmington', 'bus', 'races', 'racial', 'west', 'water', '39', 'brook', 'cls', '41', '0', '102', 'transportation'], ['wilmington', '1907'], ['water', 'wilmington', 'external', '91.85', '2,811', 'units'], ['wilmington', 'community', 'become', 'would', 'centers'], ['wilmington', 'virginia']]
TOP TOKENS [['fiscal', 'fiscalfrench', 'fiscalis', 'fiscālis'], ['fiscal', 'economy', 'extent', 'term'], ['fiscal', 'years'], ['fiscal', 'j', 'pp', 'vol'], ['fiscal', 'policy'], ['fiscal', 'budget', 'well'], ['fiscal'], ['fiscal'], ['fiscal', 'definition', 'objective', 'contraction'], ['fiscal', 'several'], ['fiscal', 'colombo', 'magistrates’', 'shrike'], ['fiscal'], ['fiscal', 'institutions', 'ante', 'policy', 'government'], ['fiscal', 'additionally', 'activity', 'unworkable', 'science', 'general'], ['fiscal', 'fiscalism', 'fiscalists', "issuer's", 'meet', 'cls'], ['fiscal'], ['fiscal'], ['fiscal', 'san', 'borrastre', 'de'], ['fiscal', 'matthias', 'institute', 'dias'], ['fiscal', 'conservatives', 'words', 'conservatism', 'debt', 'call', 'onwards']]
TOP TOKENS [['pyrenees', 'great'], ['pyrenees', 'great', '’', 'toothed'], ['pyrenees', 'great'], ['pyrenees', 'great', 'meal'], ['pyrenees', 'great', "owner's", 'much', 'inquire', 'night', 'buyer'], ['pyrenees', 'great', "owner's", 'much', 'inquire', 'night', 'buyer'], ['pyrenees', 'pyreneese', 'great'], ['pyrenees', 'pyreneess', 'great'], ['pyrenees', 'pyreneess', 'great'], ['pyrenees', "pyrenees'size", "pyrenees'coat", 'great', 'tail', 'quite', 'space', 'however'], ['pyrenees', 'pyrénées', 'ship', 'disambiguation'], ['pyrenees', 'pyrénées'], ['pyrenees', "pyrenees's", 'catalonia', 'rubies', 'la'], ['pyrenees'], ['pyrenees'], ['pyrenees', 'sub-pyrenees', 'pre-pyrenees', 'catalan', 'solé'], ['pyrenees', '537', 'felix', 'europe', 'early', '1858', 'blue', 'wyeth', 'south', 'served', 'approximately', 'another', '980', 'wales', '1929'], ['pyrenees', '65', 'southwestern', 'side', 'bas', 'basque', 'ago', 'n', 'shearing', 'southern'], ['pyrenees', 'mid-course', 'natural', 'roll', 'right', 'corkscrew', 'immediately', 'andorra'], ['pyrenees', '1119', '2', '908']]
TOP TOKENS [['tyre', 'tyres', 'wheel'], ['tyre', 'peninsula', 'bc', 'century', 'erstwhile', 'cyprus', 'took'], ['tyre', 'tyres'], ['tyre', 'peninsula', 'c', 'destruction', 'executed', 'yahweh', '’'], ['tyre', "tyre's", 'tyre’s', 'years', 'caliphate', 'b.c', 'slavery', 'thirteen', 'ottomans'], ['tyre', 'tyre’s', 'made', 'mediterranean', 'today', 'period'], ['tyre', 'tyre’s', 'made', 'mediterranean', 'today', 'period'], ['tyre', 'tyres', 'maintenance'], ['tyre', 'tyres', 'maintenance'], ['tyre', 'peninsula', 'today', 'centuries', 'cls', 'period'], ['tyree', 'tyre', 'tyres', '1997'], ['tyre', 'dunbar', 'advocates', 'edinburgh', 'scottish'], ['tyre', 'macmillan', 'pierce', 'journal', 'georgia', 'atlanta'], ['tyre', 'tyree', 'tyreek'], ['tyree', "tyree's", 'season', '2022', 'draft', 'style'], ['tyre', 'included', 'games'], ['tyre', '996–998', 'baldwin', '1124'], ['tyre'], ['tyre', 'islamic', 'seven', 'months', 'king'], ['tyre', 'extent', 'city', 'long', 'conquest']]
TOP TOKENS [[], [], [], ['clare', 'kilkenny', 'winchester', 'breasail', '1109'], [], [], ['61'], [], [], [], ['various'], [], [], ['1911', 'june', 'january', '10'], ['june', '1912', 'may', '22', '9', 'goode', '1875', 'november', 'c', 'h'], ['eaeaea', '1', '0', '6', '3'], [], [], [], []]
TOP TOKENS [['must', 'considering'], ['performing', 'like', "austin's", 'uttering', 'beyond', 'performatives', 'one', 'evoke', 'reference', 'gets', "wittgenstein's"], ['performing', 'like', "austin's", 'uttering', 'beyond', 'performatives', 'one', 'evoke', 'reference', 'gets', "wittgenstein's"], ['pragmatics', "for'the", 'describing', 'communicative', "literary'and", 'rather', 'writing', 'understood', 'uses', 'constitutes', 'also', 'convey', "with'speech", 'recipient', "virgil's", 'meaning', 'pragmatic', 'via'], ['method', 'infer', 'want', 'i.e', 'however'], ['performing', "austin's", 'language', "language's", "wittgenstein's", 'makes', 'function', "word's", 'acknowledgement'], ['performing', "austin's", 'language', "language's", "wittgenstein's", 'makes', 'function', "word's", 'acknowledgement'], ['hermeneutical', 'hermeneutics', 'drawing', 'bringing', 'exegesis', 'book', 'meaning', 'revelation'], ['message', 'g', 'mean', 'contexts', '“', 'else', 'us', 'written', 'learn', 'give', 'possible', 'statement', 'include', 'things', 'make', '–'], ['application', '‘creating', '‘pronouncing', '‘writing’', 'writing', '‘reading’', '‘read’', 'involves', 'comes', 'words', 'reading', 'represents', '‘voicing', 'word', '‘voice’'], [], ['getting', 'bemeaning', 'fill', 'fille', 'work', 'ch', 'presents', 'spirit', 'sobirnes', 'wrought', 'worde', '—', 'getyng', 'beholding', 'god', 'contemplatyves', 'bemenyng', 'soule', 'thy', 'recks', 'good', 'thar', 'contemplatives', 'goodes', 'lokyng', 'thou', 'beholdyng', '40', 'vertewe'], ['analogous', 'pragmatics', 'morris', 'instance', 'terms', 'abstractions', 'related', 'writes', 'put', 'made', "carnap's", 'syntactical', 'language', 'finally', 'case', 'e'], ['performatives', 'performing', "austin's", 'offers', 'j', 'topic', 'performative', 'mentioned'], ['transmit', '—', 'able', 'within', 'working', 'whether', 'associated', 'although', 'characterizing', 'however'], ['pragmatics', 'philosophy', '2003', '2006'], [], ['works', 'pedagogical', 'books', 'submissive', 'creation', 'manuals', 'book', 'chaste', "women's", "wollstonecraft's", 'yet', 'compliant', 'thing', 'recently', 'graceful', 'modest', 'propagating', 'roles', 'pure'], ['pragmatics', "austin's", 'communicate', 'functionally', "saussure's", 'book', 'syntactics', 'draw', "bauer's", 'piotr', 'work', 'maxims', 'attempts', 'see', "leech's", "chomsky's", 'interacts', "habermas's", 'austin', 'conversational', 'grammar', 'www', 'l', "grice's", 'vonk', 'words', "simon's"], ['descriptions', 'description', 'understandings']]

Processing features:  86%|████████▌ | 84/98 [40:22<06:35, 28.25s/it]

getting sample prompt forgetting sample prompt for 24409
 24408
getting sample prompt for 24410
getting sample prompt for 24411
getting sample prompt for 24412
getting sample prompt for 24413
getting sample prompt for 24414
getting sample prompt for 24415
getting sample prompt for 24416
getting sample prompt for 24417
getting sample prompt for 24418
getting sample prompt for 24419
TOP TOKENS [['davis', 'greats', 'include', 'yossele', 'koussevitzky'], [], ['dr', 'famous', 'man', 'among', 'c', 'b'], ['anyone', 'else', 'edison', 'i’m', 'thomas'], ['people', 'innovators', 'individuals', 'two', 'fundamentally', 'names'], ['remembered'], ['stuart', 'sir', 'bradman', 'known'], ['individual', 'man', 'unfortunately'], ['birth', 'others', 'freud', 'aristotle', 'politician', 'propagated', 'figure', 'foundation', 'one', 'anyone', 'brought'], ['birth', 'others', 'freud', 'aristotle', 'politician', 'propagated', 'figure', 'foundation', 'one', 'anyone', 'brought'], ['notable'], ['al-qaeda'], ['b', 'prime', '1995–2002', '1796–1878'], ['following', 'people', 'notable'], ['born'], ['external', 'links', 'references', 'pioneer'], ['founder', 'notable', 'aho', 'important', 'people', 'marvin', 'inventor'], ['1884–1922', '1906–1982', 'h', 'j'], ['entrepreneur', 'born', 'american', '1843-1922', '1970'], ['striker', '1947', '1948']]
TOP TOKENS [['sept', 'buffon', 'volumes'], ['sept', 'buffon', 'volumes'], ['buffon', "buffon's", 'plantes', 'darwin', 'de', '1707-1788', 'choose'], ["buffon's", 'buffon', 'church', 'montbard', 'follow', 'marlin', 'française', 'darwin'], ['buffon', "buffon's", 'positions', 'posthumously', 'like', 'emulate', 'species'], ['buffon', 'factors', 'race', 'problems', 'propounded', 'point', 'work', 'ussher', 'forms', 'petit'], ['buffon', "buffon's", 'matters', '1780s', 'ago', 'represent', 'inscrutable', 'evidently', 'foremost', 'germane', 'regarded', 'one', 'individual', 'intricacies', 'probably'], ["buffon's", 'artists', 'buffon', 'work', 'paris', 'sorbonne', 'world', 'change', 'known', 'noted', 'considered', 'read', 'little'], ['buffon', 'minimizing'], ["buffon's", 'buffon'], ['buffon'], ['buffon', 'de'], ['buffington'], ['salem-buffington'], ['buffington', '6', 'two', 'hired', '10', 'first', '3', 'coaching', 'season', 'one', '–', '11'], [], ['buffington', 'congress', 'march', '1867–1869', 'buffinton', '1863', 'succeeding', '7'], ['buffington', 'bank'], ['buffum', 'edwin', 'b', 'former', '1901-1997', 'e', 'lillie', 'social'], ['buffington']]
TOP TOKENS [['borescopes', 'borescope', 'tiny', 'bore', 'image', 'day', 'fiberscopes', '2', 'modern'], ['bores', 'explosion', 'harmonizes', 'finally'], ['borea', 'ii', 'carried', '4.7', '533mm', '1939'], ['borescopes', 'borescope', 'magnified', 'device', 'eyepiece', 'occasionally'], ['britannica/boreas', "boreas's", 'boreas', 'boreasmos', 'tritons', 'vii', 'xii', 'festival', '189', 'ilissus', 'apollodorus', 'hist'], ['borel', 'supérieure', 'strategy', 'best', 'émile', 'pastor', 'avenue', 'next', 'set', 'first', 'exhibited', '30', 'february', 'normale'], ['boreas', 'boreads', 'βορεας', 'chione', 'aquilo', 'feet', 'took', 'erichthonius', 'apollo'], ['borescopes', 'nature', 'articulation', 'devices', 'make', 'play', 'minutest', 'least'], ['bore', 'cls', 'little', 'especially', 'delicious', 'gorgeous', 'put', "one's", 'support', 'hole'], ['borescopes', 'borescope', 'f', 'appropriate', 'size', 'distance', '’', '150'], ['boreal', 'borea'], ['borel'], ['boreas', 'boreal'], ['borens', 'boren'], ['borek'], ['borén', '14'], ['borek'], ['borek'], ['borei-class', 'borey'], ['borer', 'ash', 'sordidus', 'corn', 'mining']]
TOP TOKENS [['aurora', 'auroras', 'aurorah', 'emotions'], ['propagation||aurora', 'auroras', 'aurora'], ['aurora', 'auroras', "aurora's", 'infrequent', '1621', 'direction'], ["aurora's", 'aurora'], ['aurora', 'auroras', 'auroral', 'aurorasaurus', 'hello', 'enthusiasts', 'activity'], ['aurora', 'aged', 'killed'], ['auroras', 'aurora', 'aurorae', 'auroral', 'cls'], ['aurora', 'auroras', 'auroral', 'i.e'], ['aurora', 'auroras', 'auroral'], ['aurora', 'auroraans', 'period', 'cls', '0'], ['aurora', 'state', 'brazil'], ['aurora', 'gravesite', '1939', 'arthur', '2020', 'land', 'writers', '6–8', '–97.509615', 'cemetery'], ['aurora'], ['aurora', 'according', 'city-data.com', 'settlement', 'gnis'], ["aurora's", 'aurora', 'households', 'symphonic', '3', 'snowboarding', 'cities', '11', '777', 'concerts', '1903', '24', '43'], ['aurora'], ['aurora'], ['aurora', 'area'], ['aurora', '42', 'years', '9', 'census', 'people', '357', '31', '2'], ['aurora', 'beauty', 'colorist', 'mythology']]
TOP TOKENS [['demonstration', 'demonstrating', 'demonstrationalplay', 'showing', 'product', 'software', 'demonstrations'], ['demonstration', 'demonstration(redirected', '3', '30'], ['demonstration', 'demo', 'demonstrate', 'etc'], ['demonstration', 'demonstrations', 'performing', 'using'], ['demonstration', 'demonstrations'], ['demonstration', 'demo', 'demonstrations', 'demos', 'demonstrated', 'demonstrate', 'demonstrators', 'product', 'short'], ['demonstration', 'demonstrated', 'utilize', 'may'], ['demonstration'], ['demonstration', 'demonstrations', 'teaching', 'demonstrated', 'satisfy', 'demonstrates', 'learners', 'training', 'initiate'], ['demonstration', 'demonstrated', 'utilize', 'students', 'inspired', 'may'], ['demonstration', 'demonstrate', 'demo', 'demonstrations', 'teaching', 'jojo', 'proof', 'acting', 'technology'], ['demonstration', 'demonstrations', 'demonstrating', 'demonstrate'], ['demonstration'], ['demonstration', 'debut', 'deafheaven', 'crimson', 'demo', 'yuna', 'behind', 'flatliners', 'krupps', 'miss', 'metalcore', 'demos', 'short', 'teaching', 'product', '1968'], ['demonstration', 'demo', 'demos', 'demonstrations', 'demonstrated', 'demonstrate', 'demonstrators', '1949', 'product', 'short', 'readymade', 'pre'], ['demonstration', 'demonstrations', 'using', 'demonstrating', 'demonstrate', 'learning', 'show', 'showing', 'uses', 'consequences', 'co', 'presented'], ['demonstration', 'storytelling'], ['demonstration', 'demonstrations', 'demo', 'demos'], ['demonstration', 'demo'], ['demonstration', 'demonstrations', 'enables']]
TOP TOKENS [['snowfalls', 'snow', 'snowfall'], ['snowfalls', 'snow', 'snowfall'], ['snowfall', 'snow', 'experience', 'fell', 'experiences'], ['snowfall', 'snow', 'annual', 'average'], ['snowfall', 'snowy', 'normal'], ['snowfall', 'heaviest', 'snow', 'amounts', 'snowstorm', 'denver'], ['snowfall', 'snow', 'much'], ['snowfalls', 'snowfall', 'snow', 'heavy', 'fluffy', 'inches', 'cold'], ['snowfall', 'snow', 'regards', 'ranges', 'indicates', 'winters', 'around'], ['snowfall', 'snow', 'regards', 'ranges', 'indicates', 'winters', 'around'], ['snowfall', 'precipitation', 'tony', 'corporate'], ['snowfall', 'significant', '≥', 'snow', 'winter', 'occurs', '4', '76', '59', '11', '1', 'least', 'measurable', 'year', 'averages', 'american', 'white', '2', 'days'], ['snowfall', 'reported', 'snow', 'snowfalls', 'registered', 'cls', 'largest', 'experienced'], ['snowfall', 'snow'], ['snowfall', 'snow', 'snows', 'broke', 'recorded'], ['snowfalls', 'snowfall', 'recorded', 'snow', 'significant', 'snowiest', 'snowy', '2021', 'oberon', 'generally'], ['snowfalls', 'snowfall', 'year'], ['snowfall', 'snowy', 'widespread', 'snow', 'severe', '–', 'first', 'began', 'fallen', 'coldest', 'weather', 'winter'], ['snowfall', 'snow', 'days', 'exceptional', 'snowiest', 'huge', 'months'], ['snow', 'snowy', 'regions', 'even', 'de', 'making', 'time', 'reported']]
TOP TOKENS [['portugal', 'lisbon', 'language'], ['portugal', "portugal's"], ['portugal', "portugal's"], ['portugal', 'compulsory'], ['portugal'], ['portugal', 'portuguese'], ['portugal', 'today', 'unicameral'], ['portugal', 'although'], ['portugal', "portugal's"], ['portugal'], ['american', 'portugal', 'town'], ['portugal', "portugal's"], ['semi-presidential', 'portugal'], ['portugal', 'interâmnico', 'portuguese', 'languages', 'micaelense'], ['portugal'], ['portugal', 'portuguese'], ['portugal', 'uk/portugal', 'portugal–united'], ['portugal'], ['portugal', 'portuguese', "portugal's", 'attractiveness', 'union'], []]
TOP TOKENS [['’', 'like'], ['look', 'seen', 'one'], [], [], [], [], [], [], ["elsa's", "here's", 'fizzing', "valentine's", 'otherwise', 'bins', 'snippets', 'time', 'journaling', 'diamonds'], ['like'], ['counterparts', 'also', 'basically', 'size'], [], ['consisted', 'consists', 'one'], [], [], [], ["genm's", 'follows', "o's", 'allows', "faiz's"], ['880', 'also'], ['well', 'course'], ['different', 'also', 'offering']]
TOP TOKENS [['chess', 'succeed'], ['chess', 'play', 'champion'], ['chess', 'play', 'manner', 'playing'], ['chess', 'chess?â'], ['chess', 'play', 'america', 'memory'], ['chess', 'play', 'fide', 'playing'], ['chess', 'chessmen', 'rook', 'empire', 'respectively', 'pawn', 'nobility', 'russia', 'persia'], ['chess', '“', 'dedication', '2021', 'sport', 'homes', 'million', '000', '2020', 'logic', 'tournament'], ['chess', 'playing'], ['chess', 'chess-playing', 'playing', 'moves'], ['chess', 'records', 'poem', 'film', 'system', 'shogi', 'shatar'], ['chess', 'eakins', 'daumier'], ['chess'], ['chess', 'chessvibes', '2016', 'chesspark', 'chess960'], ['chess', 'chessmaster', 'chesscafe', 'chessgames', 'chesse'], ['chess', 'rules', 'fide', 'internationally', 'clocks', 'association'], ['chess', 'chesse', 'chessboard', 'problems', 'english', 'strategy', 'notation', 'marvels', 'baghdad', 'reference'], ['chess', 'tournaments', 'fide', 'world', 'players', 'editions', 'years', 'detail'], ['chess', 'opulent', 'fide', 'pawns', 'world', 'mydans'], ['chess', 'foundation', 'death']]
TOP TOKENS [['surface', 'starts', 'booked', 'enclosing', 'status', 'alerts', "nodemcu's", 'aliexpress', 'oh', 'often'], ['rely', 'piles', 'made', 'mainly', 'also', 'cheering', 'project', 'ones', 'least', 'word', 'day', 'based', 'make', 'details', 'fairly', 'friends'], ['carcasses', 'moisture,making', 'constructionof', 'asubstrate', 'core', 'thenapplied', 'particleswhile', 'mdf', 'heat.particleboard', 'moisture-resistant', 'softwood', 'isunusual', 'yet', 'product', 'thesurface', 'tohold', 'byapplying', 'cabinetry', 'hmr', 'particleboardis', 'ismore', 'bothsides', 'used'], ['modes', 'need', 'font', 'viruses', 'well', 'windoze', 'periodically'], ['squeeze', 'small', 'subfloors', 'unless', 'wood', 'particleboard', 'using', 'necessary', 'water', 'cls', 'board', 'split', 'particle', 'maintained', 'spray', 'soaking', 'products', 'seep', 'bottle', 'basements', 'wring', 'behind', 'cabinets'], ['however', '’', '”', 'monkeys', '–', 'many', 'factors', 'another'], ['’', 'child', 'busy', 'one', 'particularly', 'hollie', 'fluffy', 'friends'], ['another', 'however', '”', '’', 'last', '–', 'parents', 'porch'], ['particleboard', 'surface', 'rather', 'based', 'wood'], ['every', '’', 'post', 'bounce', 'around', 'get', 'though', 'also', 'belt', 'many', 'lettering', 'time', 'project'], ["moore's", 'though', 'surreptitiously', 'makes', 'also'], ['also', 'beanstalk', 'mr', '2006', 'washee', 'pablo', 'since', '2013', 'often', "4's", 'chatham', '2009', '2007'], ['poolfoot', 'energy', 'variety', 'group', 'f', '’', 'following', 'physios', 'united', 'english', 'along', 'sponsor', 'fund', 'maintenance', 'national', 'charity', "fa's", "pilley's"], ['andru', 'rowspan', 'people', 'others', 'b0c4de', 'american'], ['wa', 'president', 'references', 'australia'], ['back', 'face', "episode's", 'go', 'appears', 'appeared', "face's", 'sometimes', 'end', "picking's", 'also', 'dwells', "any'kids'who", 'twice', 'may', '5', 'however', 'provides', 'rest', 'peanut'], ['bathrooms', 'uses', 'cost', 'machined', 'type', 'except', 'surfaces', 'strength', 'connoting', 'laundries', 'therefore', 'shavings', 'densities', 'fiberboard', 'wood', 'though', 'particularly'], ['budgets', 'need', 'people'], ['beegle', 'beagle', 'also', 'ape', 'show'], ['autocove', 'detail', 'based', 'fiberboard', 'machine', 'deck', 'make', 'side', 'however', 'stick', 'mitered', 'either', 'size', 'consists']]
TOP TOKENS [['deniers', 'skeptic', 'pundits', 'journalistic', 'portray', 'viewpoints', 'pecuniary', 'field', 'conclusions', 'science'], ['alarmists', 'alarmist', 'skeptics', 'mongering', 'doubters', 'hysteria', 'admit'], ['alarmists', 'alarmist', 'deniers', 'skeptics', 'experts', 'confusion', 'consensus', 'establishment', 'claim', '“', 'skeptical', 'top'], ['experts', 'alarmism', 'claims', 'skeptical', 'claim', 'skeptics', 'consensus', 'skepticism', 'concerned', 'recognize', 'board', 'sideline', 'scientists'], ['alarmist', 'sceptics', 'climatologists', 'mongers', '“', 'ideologues', 'opinions', 'people', 'welcome', 'alarming', 'scare', 'preconceived', 'ideology', 'believed', 'defenders'], ['deniers', 'sceptics', 'scientific', 'experts', 'conspiracy', 'position', 'exclude', 'theories', 'silly', 'legitimate', 'positions', 'advancing', 'entrenched', 'support', 'agree', 'shrift', 'contrarians', 'community', 'debate', 'expert', 'uncertainties'], ['skepticism', 'deniers', 'skeptic', 'conclusions', 'denialism', 'worried', '“', 'science', 'people', 'analyze', 'consensus'], ['skeptical', 'thinks', 'science', 'disagree', 'followers', 'accept', 'public’s'], ['alarmists', 'sceptics', 'alarmist', 'cause', 'scientific', 'claims', 'reject', 'scientists', 'push', 'one', 'narrative', 'comment'], ['deniers', 'detractors', 'opposed', 'agree', 'activists', 'people', 'members', 'scientists'], ['denialists', 'skeptics', 'scientific', 'science', 'scientists', 'consensus', 'uncertain', 'belief', 'beliefs', 'confuse', 'promoting', 'community', 'believers', 'rejecting', 'believed', 'public', 'organizations'], ['knowledge', 'skepticism', 'scientific', 'advocacy', 'science', 'alarmist', 'scientist', 'public', 'environmentalism', 'claims', 'anti', 'information', 'alarming', 'acknowledge', 'organization', 'dr', 'refuses', 'environmental', 'deceive', 'reasoning', 'coalition', 'powerful', 'report', 'motivated', 'october', 'denial', 'agnotology'], ['believe', 'people', 'internet', 'source', 'reputable', 'politicization', 'community', 'evidence', 'pseudoscience', 'detailed', 'science', 'academic', 'directly', 'accepts', 'accept', 'follow', 'undeniable', 'activist', 'study', 'environmentalist', 'intelligent'], ['experts', 'deniers', 'knowledge', 'consensus', 'groups', 'scientists', 'theory', 'views', 'science', 'cognition', 'scientific', 'environmentalist', 'pseudoscience', 'conspiracy', 'controversy', 'climatologist', 'oppose', 'field', 'belief', 'uncertainty', 'perception', 'ideological', 'individuals', 'vaccine', 'meaning', 'toward'], ['deniers', 'tank', 'think', 'know', 'explanations', 'view', 'dismiss', 'debate', 'scientific', 'scientists', 'science', 'doomsday', 'mounted', 'media'], ['consensus', 'disinformers', 'disheartening', 'supported', 'scientific', 'movement', 'confusing', 'controversy', 'popular', 'progressives', 'anyone', 'anti', 'thinking', 'noisy', 'attention', 'americans', 'dealing', 'science', 'term', 'good'], ['critics', 'scientific', 'consensus', 'science', 'support', 'panic', 'scare', 'supported', 'alarm', 'alarmist', 'media', 'frenzy', 'pieces', 'concerned', 'mainstream', 'widespread', 'dismissed', 'voicing', 'false', 'since', 'latest', 'term', 'describe', 'theory', 'pejorative', 'scientists', 'claim', 'related', 'endorse', 'people'], ['consensus', 'alarmism', "scientists'criticisms", 'opponent', 'scientific', 'claims', 'following', 'debate', 'estimates', 'supported', 'rejected', 'geophysicist', 'skeptic', 'information', 'kininmonth', 'provide', 'statements', 'inaccurate', 'authoritative', 'commented', 'standing', 'community', 'science', 'figures', "gerlach's", 'myths', "plimer's"], ['skeptics', 'knowledge', 'reactions', 'science', "scientists'criticisms", 'vitriolic', 'media', 'academics', 'critics', 'scientific', 'beliefs', 'comments', 'academic', 'valid', 'ideology', 'rejected', 'layperson', 'claim', 'commentator', "book's", 'community', 'enlightenment', 'power'], ['climatologists', 'views', "people's", 'beliefs', 'people', 'scientific', 'alarmism', 'doubters', 'alarmist', 'ereaut', 'coverage', 'claims', 'segnit', 'influences', 'controversy', 'view', 'consensus', 'overemphasize', 'science', 'since', 'group', 'sources', 'media', 'apathy', 'entertainment', 'made', 'opposed', 'misrepresented', 'scientists']]
TOP TOKENS [['satisfaction', 'supervision', 'based', 'thus', 'job', 'determined', 'accomplished'], ['satisfaction', 'satisfied', 'job', 'deals', 'surprisingly', 'include', 'remember'], ['satisfaction', 'job', 'years', 'determined', 'adequacy'], ['satisfaction', 'make', 'satisfied', 'depends', 'level', 'may', 'job', 'leads', 'satisfactorily', 'affecting', 'understandable', 'quantify', 'high'], ['satisfaction', '’', 'attempting', 'job', 'respect', 'level', 'least', 'leads', 'put'], ['satisfaction', 'includes', 'benefits', 'reflects', 'may', 'job', 'others', 'schleicher', 'conditions'], ['satisfaction', "worker's", 'job', 'level', 'leads', 'dissatisfaction'], ['satisfaction', 'job', 'satisfied', 'organization'], ['satisfaction', 'refers', 'job', 'may', 'nobile'], ['satisfaction', 'satisfied', 'job', 'based', 'employees', 'may', 'determined', 'comes', 'deserved', 'put'], ['1965', 'thee', 'lifetime'], ['higher', 'satisfaction', 'job', 'satisfied', "patients'satisfaction", 'influencing', 'experienced', 'health', 'become'], ['satisfaction', 'edwin', 'components', 'supervision', '1976', 'job'], ['satisfied', '2002'], ['satisfaction', 'job', "workers'job", 'among', 'commonly', 'paradigm'], ['satisfaction', 'odakura', 'hiroki', 'shotaro', 'weekly', '43', 'hisashi', 'outtakes', 'stylized', 'jin', 'japan'], ['satisfaction', 'life', 'factors', 'feelings', 'satisfied', 'functional', 'concepts', 'higher', "one's"], ['satisfaction', 'subscale', 'job', 'scores', 'alone', 'questionnaire', 'r', 'survey', 'majority'], ['satisfaction', 'businesses', 'level', 'currently', 'expectation', 'rate', 'specified', 'total', 'customer', 'customers', 'percent', 'products', 'percentage', 'cls', 'strategy'], ['satisfaction', '2014']]

Processing features:  87%|████████▋ | 85/98 [40:49<06:02, 27.89s/it]

getting sample prompt forgetting sample prompt for 24421
 24420
getting sample prompt for 24422
getting sample prompt for 24423
getting sample prompt for 24424
getting sample prompt for 24425
getting sample prompt for 24426
getting sample prompt for 24427
getting sample prompt for 24428
getting sample prompt for 24429
getting sample prompt for 24430
getting sample prompt for 24431
TOP TOKENS [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['several'], [], ['angulata', '1985', 'bulgarica'], [], []]
TOP TOKENS [['harmony', 'valid', 'aspects'], ['harmony', 'find'], ['harmony', 'harmonies', 'harmonizing', 'good', 'together', 'makes', 'line', 'written', 'creating', '’'], ['harmony', 'harmonization', 'harmonious', '“', 'time', 'harmonia', 'particularly', 'term', 'cls', 'tonal', 'music', 'derives'], ['harmony', 'course', 'day', 'provide', 'days'], ['harmony', 'harmonizing', 'harmonies', 'often', 'harmoniousness', 'cls', 'background'], ['harmony', 'harmonies', 'harmonizing', 'often', 'harmoniousness', 'cls', 'word', 'background', 'peace', 'harmonia'], ['harmony', 'harmonious', '“', 'programme', 'book', '’', 'based', 'part'], ['harmony', 'harmonies', 'singing', 'harmonizing', 'harmonize', 'notes'], ['harmony', 'analysing'], ['harmony', 'harmonyos', 'harmonious', 'glee', 'foss', 'skelly'], ['harmony', 'states', 'located'], ['harmony'], ['harmony', 'references'], ['harmony'], ['harmony', 'harmone', 'harmonee', 'cls'], ['harmony'], ['harmony', 'jersey'], ['harmony'], ['harmony', 'states']]
TOP TOKENS [['maze', "maze's", 'mazes', 'uninitiated', 'solution', 'creations', 'create', 'edge'], ['maze', 'mazes', 'mazemazed', 'mazed', 'atlanta', 'mazemaize', 'assistance', 'cls', 'market'], ['maze', 'mazes', 'medium', 'greece', 'location', 'cls', 'process', 'follow', 'experience'], ['maze', 'mazes'], ['maze', 'maze--one', 'mazes', 'make'], ['maze', 'mazes', 'reserved'], ['maze', 'mazes', 'make'], ['maze', 'garden', 'acres'], ['maze', 'mazes', 'goal', '0', 'number'], ['maze', 'mazes', 'goal', '0', 'number'], ['maze', 'mazes', 'route'], ['maze'], ['mazé', 'mazé-milon'], ['maze', 'mazes'], ['maże', 'ełk', 'olsztyn'], ['maze'], ['mazes', 'maze'], ['maze', 'prevented', 'assemblyman', 'club', 'district'], ['maze'], ['maze', 'states', 'enjoyed', 'tennis']]
TOP TOKENS [['abrogateˈæb', 'abrogate', 'put', '1520–30', 'rəˌgeɪt', 'ordinances', 'ab', 'ab•ro•gateˈæb', 'decrees', 'repeal', 'applied', 'rəˌgeɪt(v.t.)-gat•ed', 'laws', 'origin', 'definitions', 'gat•ing', 'annul'], ['courting'], ['apply'], ['patients', 'systems', '—'], [], ['v', 'indebtedness', 'amounts', 'sense'], ['found', 'abrogate', 'decrees', 'laws', 'abrogated', 'repeal'], [], [], ['”'], [], ['daughtry', 'used', '2015'], [], ["tenaglia's", '3', '–'], ['luvely', '—', '3', 'luv'], ['expatriate', 'portuguese', "men's", 'sep', 'sportspeople', 'football'], ['remix', 'electronic', 'people'], ['james', 'originally', 'waterhouse', 'many', 'molina', "minogue's", 'wirrick'], ['featuring'], ['aguilera', 'assistant', 'producer', 'songwriter', '–']]
TOP TOKENS [['author'], ['author', 'abode', 'prayag', 'malikzada', 'armies', 'kara', 'ghiyasu', '1412', 'gods'], ['author'], ['author', 'designer'], ['author', 'believes', 'sexes', 'sex', 'person', 'identity'], ['author', 'ptsd', 'approximately', 'indicates', 'neurologically', 'administration', 'cls', 'diagnostic', 'opportunity', 'threatening', 'services', '6', 'society', 'well'], ['author', 'searchmobilecomputing', 'assessment', 'development'], ['author', 'way'], ['author'], ['author'], ['author', 'team', 'sport', 'cycling', 'cross-country', 'e-bikes', 'michal', 'ats', 'mtb'], ['author', 'journalist', 'football', 'assembly', '1903', 'gambaccini', '1943', 'league', '1994', 'announcer', 'port', 'born', '–', 'national', 'helped', 'harasymiak', 'one', '1849', 'congressional', 'united', 'pet', '000', 'holocaust', 'member', '1970', 'host'], ['bicycles', 'brand'], ['author', 'ukrainians', 'asserts', 'describes', '1963', 'parliamentary', 'dehumanization', 'elections', 'imprisonment', 'assimilate', '2010', '1980', 'actually', 'saying'], ['author', 'described', 'world', 'wars', '1946', 'referred', 'individuals', 'race', 'entered', 'group', 'war', 'tried'], ['author', 'temporarily', 'notable', 'notably', 'claims', 'heart', 'affirmed', 'conscious', 'occupied', 'political', 'ethnically', 'deserted', 'published', 'war', 'army', 'frauenbewegung', 'race', 'throwers', 'gymnastics', 'antireligious', 'training', 'music', 'reichsbahn', 'performed', 'indoctrinate', 'already', 'adolf', 'von', 'education'], ['author', 'code', 'needed', 'codame', 'several', 'futures', 'wallet', 'mobility', '5th', 'china', 'congress', "china's", 'house', 'kit', 'hands', 'wearable', 'usa', 'officials', 'spoken', 'also', 'ring', 'berlin', 'easily', 'fast', 'places', 'brands', 'garments'], ['author', 'objectives', 'central', 'features', 'pool', 'methodology', 'issues', 'national', 'ecology', 'interpretation', 'yashwant', 'co', 'basic', 'india', 'system'], ['author', 'original', 'ali', 'umdatul', 'co', 'saudi', 'muhammad', 'ibn', '2019', '1', 'saeed', 'king'], ['author', 'compared', 'quarterback', 'nocera', 'debt', 'buyer', 'begun', 'knowledge', 'mortgages', 'star', "the'protection", 'sallie', 'football', '–', 'wager', 'according', 'political', 'unable', 'harbor']]
TOP TOKENS [['determination', 'determination.despite', 'mar-a-lago', 'spokeswoman', 'determinationin·ter·de·ter·mi·na·tion'], ['determination', 'free', 'variable', 'regression'], ['determination', 'self', 'initial', 'zealous', 'stoichiometry', 'steely'], ['place’', 'determination', 'determined', 'something', 'figicāre', 'subjects', 'hard', 'obstinacy'], ['determination'], ['determined', 'determination', 'firm', 'decmber', 'person', 'obsessiveness', '2017', 'indecisiveness', 'possibility', '14'], ['determined', 'determination', 'firm', 'decmber', 'person', 'obsessiveness', '2017', 'indecisiveness', 'possibility', '14'], ['determination', 'matter', 'self'], ['self-determination', 'choices', 'destiny', 'self-sufficiency', 'determination'], ['self-determination', 'determination', 'life', 'strong', 'de·ter', 'letters', 'use'], ['self-determination'], ['regulation', 'determination', 'determined', 'obstacles', 'self', 'success', 'occurs', 'meaning'], ['determination', 'self-determination', 'others', 'informational', 'death'], ['determination', 'evidence', 'determinations', 'government'], ['determination', 'album’s', 'tony', 'justin', 'schreck'], ['determination'], ['determination', 'greenwood'], ['determinations', 'scott', 'pat', 'traditional', 'shadow', 'avant-garde', 'military-industrial', 'd.o.a', 'animation', 'mcleod', 'spoken-word', 'contemporary', 'subhumans'], ['determined', 'first', 'early', 'shows', 'time', 'ryan', 'sun'], ['determination', 'case', 'content', 'text', 'fundamental', 'parent', 'summary', 'task', "bradycardia's", 'closely', 'bits', 'related']]
TOP TOKENS [['procedure', 'minimally', 'explore', 'uses', 'area', 'invasive', 'thoracotomy', 'procedures'], ['technique', 'procedure', 'made', 'method', 'approach', 'incision', 'puncture', 'needed', 'access', 'punctured', 'axillary'], ['percutaneous', 'procedure', 'nephrostomy', 'technique', 'surgical'], ['procedure', 'techniques', 'approach', 'axillary', 'technique', 'transducer', 'placed', 'aspiration', 'palpate', 'dose', 'visualize', 'guided', 'targeted', 'inserted'], ['sigmoidectomy', 'approaches', 'technique', 'anastomosis', 'procedures', 'used', 'procedure', 'hemicolectomy', 'approach', 'way', 'haemostatic', 'transumbilical', 'performed', 'spares', 'techniques', 'less', 'colectomy', 'laparoscopic', 'angulated', 'colectomies', 'regard'], ['pericardiocentesis', 'performing', 'method', 'perform', 'punctured', 'process', 'area', 'route'], ['procedure', 'area', 'done', 'anesthetized', 'technique', 'frenectomy', 'sutured', 'placed', 'dissection', 'using', 'excised'], ['percutaneous', 'technique', 'tracheostomy', 'method', 'cls', 'dilatation', 'incision', 'cannulation', 'made'], ['techniques', 'phacofracture', 'placed', 'incisions', 'cauterized', 'cannula', 'done', 'intratunnel', 'implanted', 'forceps', 'using'], ['done', 'technique', 'techniques', 'thoracotomy', 'used', 'thoracoscopy', 'minimally', 'operation', 'endoscopy'], ['done', 'procedure', 'technique', 'percutaneous', 'minimally-invasive', 'nephrolithotomy', 'region', 'urologic', 'puncture', 'ureteric'], ['procedure', 'performed', 'thoracotomy', 'surgical', 'performing', 'pneumonectomy', 'approaches', 'approach'], ['procedure', 'percutaneous', 'used', 'incisions', 'making', 'procedures', 'valvuloplasty', 'valvoplasty', 'approach'], ['procedures', 'techniques', 'surgical', 'approach', 'references', 'using', 'tactile', 'incision', 'assessment', 'ligated', 'allows'], ['procedures', 'procedure', 'ostectomy', 'surgeries', 'involving', 'include', 'removal', 'surgical'], ['procedure', 'procedures', 'thoracotomy', 'made', 'defibrillation', 'resuscitation', 'used', 'treat', 'performed', 'provides', 'way', 'along'], ['procedure', 'done', 'cyclodestruction', 'cycloablation', 'endocyclophotocoagulation', 'techniques', 'cyclophotocoagulation', 'cyclodestructive', 'surgeries', 'using', 'cryotherapy', 'perform'], ['done', 'pericardiocentesis', 'decompression', 'embolectomy', 'methods', 'catheter', 'giving', 'clot', 'involves', 'may', 'works', 'directed', 'effective', 'treatment', 'needed', 'also'], ['percutaneous', 'procedure', 'done', 'method', 'approach', 'puncture', 'via', 'technique', 'procedures', 'placing'], ['procedures', 'method', 'uses', 'using', 'create', 'applied', 'suction']]
TOP TOKENS [['predicate', 'predicates', 'needed', '”', 'one', 'needs', '“'], ['predicate', 'predicates'], ['predicate', 'predicates', 'think', '“', 'go', 'anything', '’'], ['predicate', 'may', 'look', 'performs', 'essentially'], ['predicate'], ['predicate', 'predicates', '“', 'predicative', 'always', 'instance', '”', '’', 'writer', 'revise'], ['predicate'], ['predicates', 'predicate', 'grammar', 'new', 'particle', 'norton'], ['predicates', 'predicate', 'although', 'syntax'], ['predicate', 'predicates', 'different', 'sometimes'], ['predic', 'predicate', 'predicates', 'term', 'predicative', 'plus', 'predicatives', 'prepositional'], ['predicate', 'n-ary'], ['predicate', 'predicates', 'term', 'predicand', 'following', 'instance', 'predicands', 'predicator', 'discontinuity'], ['predicates', 'predicate', 'since', 'depending', 'sometimes', 'referred', 'element', 'would'], ['predicate', 'predicates', 'term', 'predication', 'indicates'], ['predicates', 'predicate', 'approach', "predicate's", 'verb', 'main'], ['predicates', 'predicate', 'bhe', 'e', '，', 'however', 'unk', 'sentences', "willing?'b", 'ahyo'], ['predicate', 'predicates', 'thus', '—', 'obviously', 'us'], ['predicate', 'predicates', 'distinguishing', 'domain', 'c', 'could', 'x1', 'logic', 'calculus', 'represent'], ['predicate', 'subsequently', 'account', 'states', 'establishment', 'united', 'etymology', 'offences']]
TOP TOKENS [['30', 'nov', '28', '20', 'one', '7', 'a10', 'local', '12', '2011', 'co', 'slowing', "connecticut's"], ['three', '30', 'one', '14', 'least', '29', 'oct', 'six', '15', 'four', 'doused', '28', 'person'], ['25', 'feb', '21', '20', '19', '2', '2012', 'former', '12', '4'], ['17', 'one', 'oct', 'week', '19', '07', '10', 'left', 'c1', 'mangoes', 'like', '18', 'a11', 'fresh', 'others', '15', 'put'], ['7', 'torres', '4', 'wounded', 'well', '6', '3', 'linked', 'explosive', 'yellow'], ['today', '20', 'one', 'day', 'two', '18', 'ap', 'struck'], ['three', 'one', '348', '5', '1', '3', 'four', 'past', 'moment', '500', 'already', 'people', 'jun', 'died', '13', 'mostly'], ['a1', '3', 'oct', '33', '2014', '17', 'potentially', '2015', 'drinkable', 'aquifers', 'south', '15'], ['26', 'nov', 'struck', '21', 'injuring', '22', 'central', 'three', 'others', 'people'], ['19', '31', '22', '1', '10', '7', '20', 'jul', 'nearby', '15'], ['9', 'included', 'local', '7', 'dead', 'earlier', 'people', 'three'], ['15', 'tuesday', 'monday', 'six', 'october', 'wednesday', '17', 'others', 'five', '3', 'three', 'injuring', 'injured', 'old'], ['26', '28', '3', '31', '6', 'two', 'another', 'march', 'involved', 'three', '18', '21', '15', '14', 'one', 'thursday', 'people', 'wounded', '5', 'busy', 'nearby', 'well', 'southern', 'others'], ['1', 'sunday', 'people', 'three', 'late', '16', 'others', 'two', 'carrying', '9', '23', '2014', '3', 'around', 'place'], ['two', 'received', 'one', 'injured', 'defused', 'others', 'assailants', 'including', 'opened', 'people', 'killed', 'september', 'jackets', 'sunday', 'serious', '29', '5', 'hit', 'died', 'october', '26', 'shaikhan', 'three', 'near'], ['young', 'thursday', 'three', 'wednesday', 'left', 'carrying', 'several', '3', 'including', 'wounded', 'four', 'miscreants', 'seven', 'injuring', 'firing', 'cricketers', 'monday', 'people', 'six', 'earlier', 'day', 'separate', 'injured', 'sustained', 'less', 'others', 'near', '157'], ['14', '13', 'last', 'october', '12', 'sustained', 'thursday', 'occurred', 'old', 'seriously', 'three', 'sunday', 'injuring', 'injuries', 'two', 'wounded', 'others'], ['29', '17', '19', '23', 'three', '7', 'november', '24', 'another', 'two', 'multiple', '22', '25', 'occurred', 'one', 'october', '18', 'defuse', '4', 'others', '2', 'killing', 'assailants'], ['three', 'thursday', 'october', '19', 'friday', '18', 'wednesday', 'two', '17', 'left', 'qaumi'], ['several', '15', '9', 'three', 'seriously', '14', '30pm', 'wounded', 'ten', '13', 'two', 'others', 'people', 'dead', '4', 'week', 'least', 'area', '130', 'around', '21', 'six', 'westerners', 'habitual', 'injuries', 'coordinated', 'one', 'injuring', 'occur', 'occurring', 'arrived', '19']]
TOP TOKENS [['someone', 'avoid', 'disrespect', 'thing', 'details', 'interaction', 'wrongdoing', 'https://open.spotify.com/playlist/37i9dqzf1dwxb9i5xoxljp', 'rather', 'moreover', 'compared', 'lower', 'misunderstandings', 'general'], ['stuff', 'life', 'things', 'gape', 'direct', 'end', 'expectations', 'without', 'etc', 'seem', 'food', 'indonesian', 'getting'], ['something', 'person', 'associate', 'life', 'like', 'try', 'business', 'relationship', 'may', 'rather', 'things', 'infuriating', 'ones', 'leads', "foreigner's", 'would', 'rehired', 'teachers', 'dealt', 'get', 'example'], ['something', 'allow', 'item', 'upon', 'acquaintance', 'displays', 'someone', 'one', 'acceptable', 'another', 'australians', 'winking', 'example', 'touch', 'whether', 'may', 'affection', 'comes'], ['lives', 'business', 'discuss', 'remove', 'humiliate', 'attempt', 'specific', 'person', 'remains', 'eating', 'napkin', 'indicate', 'put'], ['cause', 'head', 'irreparable', 'relationship', 'handshakes', 'subject', "someone's", 'say', 'someone', 'conform'], ['touch', 'embarrass', 'someone', 'ask', 'objects', 'establish', 'presence', 'holes', 'another', 'position', 'omit', 'normally', 'answers', 'chocolates', 'perfume', 'acceptance', 'accepted'], ['person', "someone's", 'wearing', 'present', 'avoid', 'management', 'information', 'jewellery', 'ring', 'way', 'testimonials', 'wear', "client's", 'using', 'including', 'portfolio', 'hands', 'white'], ['remove', 'domination', 'meals', 'anyone'], ['hassles', 'hassled', 'overdo', 'someone', 'reciprocate', 'crossed', 'small', 'never', 'tines', 'haired', 'place', 'sleeveless', 'scribbling', 'making', 'places', "giver's", 'kept', 'meal', 'palm', 'fork', 'presence', 'spoon', 'eating', 'chew', 'eat', 'food', 'though', 'servants'], ['latter', 'chopsticks', "one's", 'entrance', 'disrespectful'], ['commit', 'person', 'eating', 'something', 'act', 'never', 'one', 'gift', 'matters', 'generally', 'unless', 'hands', 'fail', 'following', 'dignity'], ['someone', 'spoons', 'action', 'eat', "one's", 'addition', 'similarly', 'apply'], ['something', 'nadaareh', 'someone'], ['life', 'ties', 'relationships', 'matters', 'somebody', "one's", 'individual', 'better', 'else', 'present'], ['done', "one's", 'touch', 'person', 'whether', "elder's"], ['someone', 'something', 'self', 'like', 'directly', 'people', 'f'], ['someone', 'interactions', 'addition', 'touching', 'man'], ['avoid', 'never', 'nose', 'cheek', 'showing', 'contact', 'barely', 'opt', 'person', 'clasping', 'touch', 'handshake', 'show', 'aligning', 'deeply', "elder's", 'deference', "inferior's", 'phrase'], ['slightly', 'removed', 'keep', 'bow', 'placed', 'heads', "person's", 'anything', 'nose', 'slight', 'appearance', 'never', 'always', 'among', 'contact', 'image']]
TOP TOKENS [['evergreen', 'evergreens', 'water', 'plant'], ['evergreenarticle', 'evergreens', 'evergreen'], ['evergreen'], ['evergreen', 'evergreens', 'wild', 'kinnikinnick', 'glabra', 'topsoil', 'screens', 'term', 'plant'], ['evergreens', 'evergreen', 'part', 'shear', 'water'], ['evergreen', 'evergreens', 'evergreenone', 'particular', 'image', 'meaty'], ['evergreen', 'evergreens', 'evergreen,term', 'evergreen(redirected', 'half-evergreen', 'christmas', 'financial'], ['evergreen', 'evergreens', 'long', 'chinese', 'plant', 'got', 'species'], ['evergreens', 'evergreen', 'plant', 'brown', 'cls', 'backfill'], ['evergreen', "evergreen's", 'evergreens', 'fertilize', 'around', 'outer', '2'], ['evergreen'], ['evergreen', 'evergreening', 'evergreens'], ['evergreen'], ['evergreen'], ['evergreen', 'mcgriff', 'external'], ['evergreen'], ['evergreen', 'comprehensive'], ['evergreen', 'geography', 'u.s', 'census', 'bureau'], ['evergreen'], ['evergreen']]
TOP TOKENS [['etiquette', "word'etiquette'originally", "word'etiquette'in", "the'etiquette", 'proper', "word'etiquette'to", 'manners', "place.'etiquette'is", 'respectful', "the'manners'that", "no.'manners'will", 'expected'], ['polite', 'etiquette', 'manners', 'proper', 'respectful', 'please', 'propriety'], ['manners', 'etiquette', 'proper', 'polite'], ['etiquette', 'politeness', 'polite', 'rude', 'manners'], ['manners', 'etiquette', 'etiquettes', 'proper'], ['etiquette', 'polite', 'manners', 'rudeness', 'etiquettecy', 'proper', 'conduct'], ['etiquette', 'manners'], ['etiquette', 'manners', 'proper'], ['polite', 'respectful', '“', 'little'], ['etiquette', '“etiquette”', 'manners', 'etiquettes', 'properness”'], ['polite', 'politeness'], ['polite', 'politeness', 'etiquette', 'rude', 'manners', 'norms', 'considered', 'quite', 'cls'], ['manners', 'etiquette', 'politeness', 'mannered', 'rude', 'polite', 'civility', 'behaviour'], ['etiquette', 'manners', 'polite', 'courtesy', 'appropriately', 'considerate'], ['etiquette'], ['politeness', 'etiquette', 'manners', 'references'], ['etiquette', 'manners'], ['etiquette', 'manners', 'proper', 'politely', 'certain', 'behavior', 'della', 'appropriate'], ['polite', 'politeness', 'etiquette', 'manners', 'proper', 'rudeness', 'etiquettes', 'netiquette', 'civility'], ['etiquette', 'polite', 'manners']]

Processing features:  88%|████████▊ | 86/98 [41:17<05:33, 27.76s/it]

getting sample prompt forgetting sample prompt for 24433
 24432
getting sample prompt for 24434
getting sample prompt for 24435
getting sample prompt for 24436
getting sample prompt for 24437
getting sample prompt for 24438
getting sample prompt for 24439
getting sample prompt for 24440
getting sample prompt for 24441
getting sample prompt for 24442
getting sample prompt for 24443
TOP TOKENS [['bog', 'bogs', 'cls'], ['bog', 'bogs', '“', '”', 'minerotrophic'], ['bogs', 'bog'], ['bogs', 'bog', '“bog”'], ['bog', 'bogs', 'history'], ['bogs', 'bog'], ['bog', 'bogs'], ['bogs', 'bog'], ['bog', 'bogs', 'bodies', 'word', 'acceptance'], ['bogs', 'bog', 'species'], ['bog', 'bogs', 'peat', 'international', 'bóg', 'colloquialism', 'emperor', 'bog-i'], ['bog'], ["bog's", 'bog', 'bogs'], ['bog', 'river'], ['bog', '2001', '6:09', '5:19'], ['bog', 'century', 'sam', 'black', 'house', 'orlebar', 'parcel', 'states', 'central', 'land'], ['bogs', 'bog', 'bogbean', 'boggy', 'menyanthes', 'butterworts', 'garden', 'marigold', 'pseudacorus', 'sarracenia', 'jenny', 'level'], ['bogs', 'boggs', 'surname', '1965'], ['bog', 'bogs', 'boggy'], ['bog', 'bogs', 'circumstances', 'vegetation']]
TOP TOKENS [['emery', 'n'], ['emery', 'needle'], ['emery', 'emery.the', 'modifier)emery'], ['emery', 'emeryville', 'emeryville’s'], ['emery', 'quantity'], ['emery', 'traffic', '220'], ['emery', 'steel'], ['emery', '50%-60', 'gray', 'sum'], ['emery', "emery's", 'history'], ['emery'], ['emery', '1958'], ['emery'], ['emery'], ['emery', 'oakshade', 'fulton'], ['emery'], ['emery', 'administrator', '2010', 'foundation', '2018', 'also', 'penny', 'two'], ['emery', '2016', '2011'], ['emery', 'emeryville'], ['emery', 'administration', 'also', 'college'], ['emery', 'aristocrat', 'life', 'wedding', 'comes', 'personal', 'spoke']]
TOP TOKENS [['benzene', 'high'], ['benzene', 'dependent', 'differently', 'products', 'paints'], ['benzene', 'gasoline', '12', 'recent', 'chemical', 'iarc', 'smoking', 'come', '2014'], ['bathing', 'benzene', 'nation', 'linking', "hodgkin's"], ['benzene', 'including', 'due'], ['benzene', 'field-size', 'american', 'acgih', 'ppmy', 'slowly', 'years', '33', '1', 'carcinogen', 'standard'], ['benzene', 'others', 'cll', 'greater', 'also'], ['benzene', 'effects', 'avoid', 'challenging'], ['benzene', 'higher', 'air', 'smoke', 'amount', 'leukemia', 'relatively', 'route'], ['activities', 'benzene', 'also', 'mainly', 'decades', 'products', 'smoke', 'death', 'well', 'oil', 'leukemia'], ['benzene', 'benzin', 'hexagonal', 'eilhard', 'hydrocarbon', 'gradually', 'ethylbenzene', 'isolated', 'precursor', 'benzoin', 'pharmacists', 'century', 'oily', 'smell', '16th', 'petrochemicals', 'acid', 'benzoic'], ['benzene', 'along', '63', 'hematotoxicity', 'unchanged', '47', '405'], ['benzaldehyde', 'obtained', 'pungent'], [], ['benzene', '0005', 'ppm', 'via', 'workday', '1', 'lubricants', 'vehicles', 'promulgated', 'hepatically', 'zero'], ['benzoin', 'rammstein'], ['structure', 'benzene', 'formula', 'ambiguous', 'none', 'c−h', 'significant', 'benzylic', 'benzyl', 'benzoate'], ['benzene', 'advocates', 'outcry', 'ascorbic', 'significant', 'benzoic', 'benzoate', 'combination', 'nearly'], ['hydroxytoluene', 'c6h5ch2', 'benzene', 'benzoyl', 'c6h5co', 'isomeric', '1919'], ['benzophenone']]
TOP TOKENS [['clothing', 'clothes', 'contaminated', 'areas', 'remove', 'following'], ['clothing', 'responsible', 'contaminated', 'develops', 'inspection', 'due', 'safe', 'respective'], ['clothing', 'unwanted'], ['clothing', 'contaminated', 'september', 'health'], ['clothing', 'garments', 'wash', 'clothes', 'used', 'chemically', 'name', 'textiles', 'old', "beacon's"], ['clothing', 'garments', 'wash', 'clothes', 'used', 'chemically', 'name', 'textiles', 'old', "beacon's"], ['clothing', 'garments', 'used', 'clothes', '–', '60', 'recycle', 'thus', 'according'], ['clothing', 'throw', 'clothes', 'unwanted', 'throwing', 'recycle', 'away', 'old', 'fact', 'items'], ['clothing', 'clothes', 'damaged', 'repair', 'garments', 'disposable', 'small'], ['garments', 'clothing', 'nondestructively', 'inside', 'garment', 'authorities', 'evaluating', 'number', 'e', 'disposing', 'protective'], ['clothes', 'used-clothes', 'collect', "else's", 'donate', 'used', 'many', 'second-hand', 'clothing', 'generally', 'well', 'collecting', 'would', 'collectors', 'someone', 'company'], [], ['clothing', 'clothes', 'owned', '6', 'however', 'states', 'exports', 'amount'], ['clothes', 'clothing', 'garments', 'used', 'countries', 'wealthier'], ['clothing', 'clothes', 'traditionally', 'homes', 'length', 'due', 'measurements', 'garments', 'cls'], ['clothing', 'clothes', 'discarded', 'secondhand', 'textile', 'demand', 'prohibited', 'hand', 'used', 'bans'], ["attorney's", 'clothes', 'clothing', 'apparel', "inc.'s", 'u', 'office', 'inc', '2013', 'later', '2011', 'honduras', 'issued', 'charney', "apparel's"], ['clothing', 'right', 'protective', "women's", 'independently', 'clothed', 'depend', 'institutions', 'community', 'ill', 'care', 'lack', 'especially', 'centres', 'accommodation', 'privately', 'otherwise', 'public', 'others', 'fortunate'], ['chief', 'associates', 'clothing', 'clothestime', 'september', '1995', 'apparel', 'early', 'followed', 'cancelled', 'executive', '2004', 'chairman', 'raymond'], ['clothing', 'family', 'ways', 'for-profit', 'external', 'australia', 'on-the-spot', 'rubbish', 'united', 'costly', 'majority', 'stourport', 'bin', 'authorities', 'reported']]
TOP TOKENS [['cabbage', 'cabbages'], ['cabbage', 'cabbages'], ['cabbage', 'sauerkraut'], ['cabbage', 'cabbages', 'sugar', 'juices', 'salt', 'paper'], ['cabbage'], ['cabbage', 'dry'], ['cabbage', 'juice', 'cabbages', 'stir-fried', 'stuffed', 'nutritious', 'cutting', 'found'], ['cabbage', 'cabbages', 'loss', 'etc'], ['cabbage', 'jar', 'leaves'], ['cabbage', 'sulphur', 'salads'], ['cabbage', 'game', '1978', 'coronary'], ['cabbage', 'cabbages', 'product', 'states', 'boiled', 'conditions', 'ways', 'used'], ['cabbage'], ['cabbage', 'including', 'vegetable', 'vegetables', 'ages', 'negligible', 'states', 'raw', 'tissue'], ['cabbage', 'cabbages', 'pollination', 'era', 'centuries', 'ages'], ['cabbage', 'cabbages', 'damaged', 'blade', 'climates', 'red', 'seed', 'days', 'maturity', 'pink', 'apart', 'removed'], ['cabbage', '°c', 'salt', 'top', 'rock', 'conditions'], ['cabbage', 'announced', '2022', '14', 'ending', '2023'], ['cabbage', 'cabbages'], ['cabbage', 'cabbages', "cabbage's", 'respectively', 'contains', 'coloured', 'red', 'spiced']]
TOP TOKENS [['aside', 'shoulders', 'cover', 'shouldered', 'shoulder', 'easily', 'someone', "someone's", 'cls', 'arms', 'padded', 'shouldering', 'animal', 'mistakes', 'house'], ['mantelshelf', 'sleeveless', 'mantel', '2900', 'shoulders', 'matins', 'mantelpiece', "father's", 'loose', "laforge's", 'penetrates', "planet's", 'manner', 'km', 'say', 'part', 'language', 'cape'], ['bare', "for'hard", "bear'hard", 'hard', 'rel', 'might', 'much', 'commonly', 'covered', 'late', 'clearly', 'infidelity', '3', '→', '…', 'usually', 'display', 'another'], ['bare', 'mantel', 'shoulders', 'covers', 'enfolds'], ['mantel', 'mantle', 'vs', 'easy'], ['lintel', 'several', 'l[i^]n"t[e^]l', 'limit', 'lintellus', 'n', 'fr'], ['skinny', "weary's", 'fat', 'weary', 'snug', 'people', 'plenty', 'straightforward', "book's", 'book', 'still', 'receive', 'burn', 'us', '24'], ['mantele', 'mantelum', 'mantelium', 'mantellorum', 'mantellum', 'mante', 'mantel', 'manta', 'mantum', 'mantilla', 'latin', "of'the", 'ital', 'see', "woman's", 'also', "dressmaker's", 'fr', 'c', 'cf', 'compounds', 'wood'], ['tore', 'removing', 'ate.the', 'railings', 'shreds', 'threw', 'piece', 'gone', 'mask', 'nothing', '2', 'seems', 'clothes', 'years', 'process', "pikes.showell's", "grandpa's", 'head.11', 'fields'], ['bare', 'participle', 'often', 'entire', 'commonly', 'good', 'nothing', '…', 'sentence', 'detail'], [], ['palaeontologist', 'mantel', 'mantell'], ['basalis', 'wojtusiak', 'runtunana', 'lepidoptera'], ['4:24', 'herman', 'chuckles', '4:00', 'freed', 'tal', '–', 'yesterdays', 'ralph'], ['mantel', 'move', 'mantle', 'mantell', 'climbing'], ['name', 'volcano', '1992', '1885–1976', 'elihan', 'töre', 'born', 'station'], ['célibataires', 'à'], ['norwegian', 'stiklestad', 'cls', 'ruud', 'geologist', 'warrior', "thor's", 'tore', 'polar', 'musician', 'former', 'born', 'poet', 'ellingsen', '1901', 'singer', 'priest', 'þorver', '–', 'publisher', 'writer'], ['arctia', 'links', 'asia', 'bang-haas', 'along', 'acerbia', 'pararctia', 'family', 'parasemia', 'tian', 'platarctia'], ['shortstops', 'shortstop', 'standing', 'windjammers', 'slipped', 'players', 'minor', 'ely', 'bones', "pittsburgh's", 'oakland', 'gone', 'wagner', 'crickets']]
TOP TOKENS [['believer', 'come', 'money', 'people', 'god', '’', 'implications', 'two', 'bazaars'], ['believers', 'unbelievers', 'believe', 'sincere', 'makes', 'unbelieving', '’', 'words'], ['believer', 'believers', 'instructs', 'believe', 'believes'], ['believers'], ['believer', 'believers', 'like', 'invites', 'difficulty', 'tells', 'behaving'], ['believer', '‘', '’', 'understand'], ['believer', 'pleases'], ['believer', 'pleases'], ['believer', 'believers', 'therefore', 'wealth', 'iman'], ['believers', 'believing', 'unbelievers', 'unbelieving', 'believe', 'genuine', '11'], ['believers', 'believer', 'belief'], ['believers', 'believer', 'believe', 'belief'], ['believers', 'bible-believer', 'believer', 'bible-believing', 'bible', '1987'], ['believer', 'links', 'external', 'awards', 'mormonism', 'community', 'inclusion', 'film'], ['believer', 'see', 'also', 'links', 'external', 'mid-2005'], ['believer'], ['believers'], ['believer', 'worshiper', 'link', 'saved', 'firm'], ['believers', 'bogush', 'leader', 'men', 'arrive', 'farley', 'films', 'group', 'bravo'], ['believer', 'links', 'screens', 'said', 'surpassed', 'became', 'external', 'titled', '531', 'moviegoers', 'naver', 'enough', 'break']]
TOP TOKENS [['willows', 'willow', 'products', 'varieties', 'years', '–'], ['willow', 'willows', 'ground', 'season', '–', 'cuttings', '”', 'salix', 'habitat'], ['willow', 'willows', 'plants', 'ground', 'roots', 'season', '”', 'cuttings'], ['willows', 'willow', 'plants', 'ground', 'roots', 'season', 'thigh'], ['willow', 'pattern', 'potteries', 'variants', '1790', '“', 'understandable', 'collectors', 'patterns', '”'], ['willow', 'willows', 'wild', 'ages', 'nurseries', 'project', '’', 'use', 'sources', 'cls', 'grow', '—'], ['willows', 'willow', 'products', '–', 'hardwoods', 'ponds', 'biofuels'], ['willow', "on'willow", 'plight', 'n', 'wilge', 'willows', 'eng', 'rods', 'manuf', 'ptarmigan', 'desertion', 'scott', 'tit'], ['willows', 'willow', "the'kilmarnock'willow", 'one', 'levels', 'house', 'weeping', 'times', "matsudana'tortuosa", 'world', 'diameter', 'things', "caprea'kilmarnock", "8'tall", 'size'], ['willow', 'willows', 'structures', 'cultivars', 'plant', 'cuttings', 'river', 'drainage', 'trees'], ['willow', 'world', '1998', '2000', '1981', '1963', 'american', '1977', '1995', '2022', '1921–2006', '2020', 'professional', 'actress'], ['louisiana', 'willow', 'disambiguation'], ['willow', 'east', 'road', '1873–1892', '1827', '1852', 'oakwoods', 'around', 'level', '1872', 'community'], ['willow', 'trains', 'station', 'history', 'eight', 'dormont', 'pittsburgh'], ['willows', 'date', 'canada', '1950'], ['willow', 'closed', 'chicago'], ['willow', 'willows', 'maryland', 'pretoria', 'disambiguation', 'willowz', 'blackwood', 'group'], ['willow', 'earlier', 'lake'], ['willow', 'willows', 'wood', 'kingdom', 'dolls', 'ii', 'crops', 'linings', 'us', 'joints', 'systems', 'figures', 'whistles'], ['willow', 'tannersville', 'state']]
TOP TOKENS [['sousa', 'navy', 'although', 'philip', 'john', '”', 'written', 'however'], ['sousa', 'john', 'took', 'souza', '”', 'philip'], ['sousa', 'philip', 'society', 'american', 'k', 'col'], ['sousa', 'sousaphone', 'german', '22', 'times', 'gauze', 'piece', 'debussy'], ['sousa', '”', 'unique', 'banner', '1917', 'patriotism', 'philip', 'read', 'deutscherburgs'], ['sousa', 'philip'], ['sousa', 'sousa’s', 'philip', 'existence'], ['sousa', 'com', 'philip'], ['sousa', '1915', '1898', 'calls', 'loomis', '‘'], ['sousa', 'souza', 'philip', 'took', 'marines', 'john', 'tapper'], ['sousa', 'souza', 'sousaphone', 'rodrigo'], ['sousa', '9', '2023', 'june', 'claimed'], ['sousa', 'brazilian', "men's", '2023', 'match', 'c', '2019', 'minute', 'angola', 'luis', 'expatriate'], ['sousa', "sousa's", 'rarely'], ['sousa', "sousa's", 'play', 'divorce', '1940'], ['sousa', '2014', '2021', '2022', 'contract', "men's", 'expatriate', 'march'], ['sousa'], ["sousa's", 'sousa', '2021', 'tallying', '23'], ['wilt', 'sousa', 'shean', 'shamrock', 'philip', '1926', 'asthore', 'humoresques', 'john', 'lakes', 'sea', 'tyrolienne', '1922', '1876', '1877', '1885', 'pew', 'thee', 'wets', 'great'], ['sousa', "sousa's", 'john', 'philip', 'many', 'rehearsal', "willie's"]]
TOP TOKENS [['sander', 'sanding', 'sure', 'rollers', 'come'], ['sanding', 'sander', 'sanded', 'wait', 'hand'], ['tools', 'thickened'], ['sanding', 'equipment', 'sander', 'tools'], ['sanding', 'attachments', 'smoothen', 'shapen', 'rotates', 'sander', 'gives', 'due', 'sandpapers', 'achieve', 'oscillates', 'result', 'tool'], ['tools', 'using', 'board', 'hand', 'jointer'], ['sander', 'sanding', 'sandpapers', 'efficiency', 'also', 'faster', 'two'], ['sander', 'earplugs', 'using', 'sanding', 'working', 'tools', 'gloves', 'electric', 'make', 'worry', 'goggles', 'sure', 'going', 'get', 'piece', 'sanded', 'otherwise'], ['jointing', 'flattening', 'infeed', 'jointer', 'outfeed', 'planer'], ['jointing', 'flattening', 'infeed', 'jointer', 'outfeed', 'planer'], ['sanding', 'jointer', 'sander', "planer's", 'smooths', 'planer', 'adjusts', 'shaper'], ['tool', 'workbench', 'grinder', 'machine', 'sanding', 'action', 'sander', 'smooth', 'needs', 'contours', 'replaceable', 'ellipses', 'tools', 'sandpaper', 'work', 'means', 'angles', 'oscillates', 'fix', 'compressed'], ['tools', 'earplugs', 'devices', 'also', 'however', 'level', 'adequate'], ['sanding', 'sander', 'enough', 'exerts', 'achieve', 'pair', 'energizes', 'tools', 'process', 'manufacturing'], ['boards', 'honed', 'taken', 'planing', 'planed', 'jointer', 'planer', 'various', "jointer's", 'leveling', 'gluing', 'preparing', 'enables', 'work', 'adjustments'], ['jointer', 'takes', 'jointing', 'planers', 'jointers', 'required', 'planer', 'task', 'thicknessing', 'made'], ['particleboard', 'sanding', 'sander', 'helps', 'preparation', 'machines', 'assures', 'circulations', 'sanded', 'feathering', 'buffers', 'buffing', 'handling', 'vertically', 'specialized', 'therefore', 'come', 'use'], ['jointer', 'boards', 'shaving', 'making', 'tools', 'metalworking', 'tool', 'machine-tool', 'planer', 'woodworking', 'surface'], ['sanding', 'sander', 'processed', 'gear', 'hoods', 'vacumming', 'slottedanding', 'place'], ['sander', 'sanding', 'sanded', 'edger', 'tacks', 'sandpaper', 'process', 'fasten', 'however', 'used', 'go', 'varnishes', 'may', 'coverings', 'uneven', 'g', 'pass', 'warped']]
TOP TOKENS [['jstor', 'guide', 'wonderful', 'however', 'may', 'example', 'even', 'heard', 'basically'], ['jstor', 'content', 'also', 'window'], ['jstor', '•jstor', 'short', '1995', 'lead', '•', 'pull-down'], ['jstor', '•jstor', 'short', '1995', 'lead', '•', 'pull-down'], ['jstor', '•jstor', 'short', '1995', 'lead', '•', 'pull-down'], ['jstor', 'cls', 'documents', 'databases', 'archival', 'http'], ['jstor', "jstor's", '2009', 'divided', 'botany', 'detail'], ['jstor', '9780429832918', '2013', '2012', 'downloads', 'papers', '16', '13', '–', '200', 'retrieved', 'prestigious'], ['jstor', 'alphabetical', 'access', 'cls', 'myjstor', 'scroll', 'link', 'tabs', 'look'], ['jstor', 'students', 'databases', 'thousands', 'immediately', 'click', 'access'], ['jstor', 'america', "jstor's", 'loose', '2009', '1999', '2019'], ['mythology', 'unrelated'], ['jstor', 'founded', 'cls', 'becoming', 'roms', 'networked', '1994', 'increasingly', 'dramatically', 'maintain', '1999', 'research', '1988', 'allowed', 'however'], ['thestor', 'william', 'harvard', '4035', 'alcmaon', 'london', 'text', 'heinemann', 'oxford', 'polymela', 'perseus', 'project', 'naiad', 'theoi.com', 'lesser', 'studies', 'satnioeis'], ['jstor', '2012', '2014', '2013', 'downloads', 'papers', '73'], ['jstor', "jstor's", 'access', 'america', '2014', 'officially', 'dissenting'], [], [], ['nistor', '1876–1962', 'steven'], ['novastor', 'history', 'core', 'hamburg', 'greater', 'companies']]
TOP TOKENS [['primecountingfunction', 'prime', 'primes'], ['prime', 'non-prime', 'primes', 'numbers', 'one'], ['prime', 'primes'], ['prime', 'primes', 'cls', 'properties'], ['prime', 'primes', 'cls', 'properties'], ['prime', 'primes', 'number', 'n'], ['prime', 'primes'], ['prime', 'primes'], ['prime', 'primes', 'number', 'numbers', 'corrections', 'querries'], ['prime', 'number'], ['prime', 'algebra'], ['prime', "string'prime'is", 'primes←primenumbers', 'primes←', "unk]'primenumbers'[unk", 'primes', 'primenumbers', 'numbers'], ['primes', 'primegrid', 'prime', "primegrid's", 'prime95', 'numbers', 'contains', 'number', 'latter'], ['prime'], ['prime', 'primes', 'numbers'], ['prime', 'primes', 'numbers'], ['prime', 'primes', 'number', 'numbers'], ['primes', 'primegrid', 'prime', 'march'], ['prime', '1851–1926'], ["primes'until", 'prime', 'n', 'number']]

Processing features:  89%|████████▉ | 87/98 [41:44<05:05, 27.75s/it]

getting sample prompt forgetting sample prompt for 24445
getting sample prompt for 24446
 24444
getting sample prompt for 24447
getting sample prompt for 24448
getting sample prompt for 24449
getting sample prompt for 24450
getting sample prompt for 24451
getting sample prompt for 24452
getting sample prompt for 24453
getting sample prompt for 24454
getting sample prompt for 24455
TOP TOKENS [['indolence', 'ambition'], ['ambition'], [], [], ['interlocutor', 'enumerates', 'incidentally'], [], [], [], ['ambition', '364'], ['faahn'], ['burchill'], [], [], [], [], [], ['elder', '1481', '1488', 'remained', '15', 'ways', 'exhibiting', 'unpriestly'], [], [], []]
TOP TOKENS [['information', 'read', 'general', 'quality', 'known', 'prognosis', 'vibrio', 'broader', 'related', 'diagnosing', 'research'], ['read', 'related', 'broader', 'prognosis', '»', 'specialists', 'research', 'contents', 'disorders'], ['read', 'information', 'quality', 'research', 'contents', 'next', 'related', 'ratings', 'pages', 'general'], ['information', 'research', 'hypersensitivity', 'listed', 'review', 'list', 'similar', 'description', 'search', 'related', 'name'], ['information', 'list', 'search', 'research', 'related', 'knows', 'source', 'listed', 'symptoms', 'includes', 'description', 'symptom'], ['information', 'read', 'knowns', 'quality', 'cystic', 'diagnose', 'prognosis', 'message', 'related', 'specialists', 'full', 'broader', 'list', 'general', 'medical', 'ratings', 'better', 'fibrosis'], ['information', 'read', 'quality', 'ratings', 'broader', 'related', 'syndrome', 'general', '»', 'research', 'specialists', 'safety', 'ask', 'topics'], ['information', 'list', 'related', 'search', 'symptom', 'description', 'similar', 'listed', 'questions'], ['information', 'read', 'quality', 'message', 'source', 'pericarditis', 'general', 'ratings', 'research', 'listed', 'related', 'trials', 'clinicaltrials', 'broader', 'lists', 'safety', 'specialists', 'specialist'], ['information', 'read', 'undiagnosed', 'quality', 'list', 'prognosis', 'general', 'diagnosed', 'sideroblastic', 'related', 'known', 'research', 'ratings', 'broader', 'variety'], ['information', 'bulletins', 'diseases', 'list', 'parasitic', 'miscellaneous', 'disease'], ['list', 'lists', 'diseases', 'references', 'disease'], ['list', 'diseases', 'pathology', 'disease', 'information', 'common'], ['diseases', 'list'], ['external', 'articles', 'links', 'medicine'], ['list', 'external', 'conditions', 'lists', 'related', 'footnotes', 'references', 'reactions'], ['external', 'listed', 'list', 'poisonous'], ['similar', 'command', 'lost', 'accidents', 'external', 'attention', 'awareness', 'crash', 'list', 'inattention', 'misaligned', 'disregarded', 'accident', 'brief', 'another', 'momentarily', 'notes', 'diagnosed', 'redondo', 'spuyten', 'derailment', 'collision', 'valhalla', 'momentary', 'posthumously', 'lapse', 'references', 'later', 'fast', 'newton', 'incidents', 'rail', 'suggested', "engineer's", '28'], ['diseases'], ['pathology', 'diseases']]
TOP TOKENS [['pantone', 'stage', 'printing', 'ensures', 'consumers', 'consistent', 'colors'], ['panton', 'designed'], ['panthron™', 'pantoprazole', 'keep', 'window', 'finished', '56', 'plain', 'taking', 'like', 'sills', '60'], ['pantone', 'pantone®', 'right', 'articulates', 'also', '“the', 'simple'], ['pandoro', 'panettone', '“pane'], ['pantone', '2006', 'partnered', 'company'], ['’', 'pankey', 'thomas', 'died', 'research', 'born'], ['’', 'pankey', 'thomas', 'died', 'research', 'born'], ['paneer', 'panir', 'well', 'groups', 'somewhat', 'serve', 'healing', 'made', 'mgs', '208', 'ideally', 'however', 'ml', 'would', 'away', 'chapattis'], ['pantalone', "pantalone's", 'arte', 'harlequinade', 'many', 'immediate'], ['panza', 'panzo'], ['paneer'], ['karna', 'panji', 'region', 'panjis', 'prabandh'], ['hospital', 'panzi'], ['panos', 'panoan', 'pano', 'born', 'pano-tacanan'], ['pantera', 'panter', '1836–1864', 'tallinn', 'panter-downes', 'pant'], ['pantone', 'hill', 'pantonality', 'anglesey'], ['panton', 'panettone', 'guides'], ['opus', 'supraphon', 'panton', '1968'], ['qualifiers', 'pantic', 'scored', '10', '2014', 'basis', 'opening', '–', '12']]
TOP TOKENS [[], [], [], [], [], ["fubini's"], [], [], [], ['rather'], ['nilpotent', 'x', 'however', 'geometrically', 'corresponding', 'equivalently', 'via', 'orbits', 'thus'], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['fire', 'fires', 'firefighter', 'firefight', 'firefighting', 'firefighters', 'reference', 'sees', 'fight'], ['fire', 'using', 'flame', 'flames', 'fires', 'since', 'elements'], ['‘fire’', 'fire', 'wildfires', 'word', 'fires', '3', 'flame', 'burn', '1', '2'], ['fire', 'fires', 'cls', 'flame', 'see', 'bonfires', 'burning', 'burns', 'tradition', 'since'], ['fire', 'flames', 'firefighters', 'charred', 'blaze'], ['fire', '‘', '’', 'meanings', 'cls', 'word', 'years', 'religions', 'literature', 'burning', 'peace'], ['fire', 'firestarter', 'wildfires', 'become', 'flame', 'ignite', 'one'], ['fire', 'cls'], ['fire', 'wildfires', 'arson', 'control', 'environments', '2019', 'hid', 'world', 'course'], ['fire', 'fires', 'cls', 'combustion', 'burning', 'situation', 'fireplace', 'firewood', 'get', 'created'], ['combustion', 'fire', 'fires', 'born', 'american'], ['fire', 'aims', 'set', 'something', 'films'], ['fires', 'fire'], ['fire', 'fires', 'service', 'autodesk', 'firing'], ['fire', 'links', 'syndicate', 'miscellaneous', 'sides', 'external', 'appears'], ['fires', 'fire', 'greatfire'], ['fires', 'firefighters', 'fire'], ['wildfire', 'fire'], ['fire', 'fires', 'internet', 'research', 'european', 'also', 'disambiguation', 'see'], ['fire', 'fires', 'unpredictable']]
TOP TOKENS [['contractions', 'use', '’', 'contracted', 'common'], ['contraction', 'communication', 'contractions', 'full', 'using', 'words', 'contracted', 'you’d', '‘apostrophe’', 'use', 'apostrophe', 'suprisingly', 'common'], ['contractions', 'say', 'study', 'use', 'common', 'types', '’'], ['contractions', 'full', 'contraction', 'think', 'used', 'find', 'use', 'love'], ['contractions', 'blog', 'right', 'use', 'english', 'paper', '‘', 'contracted', '’', 'using', 'used'], ['contractions', 'contraction', 'piece', 'common', 'communication'], ['contraction', 'make', 'contractions', 'particular', 'etc', 'fairly'], ['contractions', 'full', 'examples', 'used'], ['contractions', 'contraction', 'however', 'english', 'use', 'using', 'letters', 'whether'], ['contractions', 'contraction', 'word', 'forms'], ['contraction', 'right', 'poetic', 'heart/myocardium', 'scaling', 'phonology', 'mapping', 'shortened', 'sounds', 'grammar'], ['contractions', 'contraction', 'glyph', 'terms'], ['contraction'], ['contraction'], ['contractions', 'standard', 'contraction', "what?'to", 'contracted', "don't'in", "needn't'is", "wa's"], ['contractions', 'kinds', 'contraction', 'think', 'contract', 'yuchi', 'lost', 'prevalence', 'one', 'take', 'surprised', 'contracted', 'order'], ['contraction', 'contractions', 'isometry', 'acting', 'becomes', 'theory', 'description', 'said'], ['contraction', '0', '—', 'νε', 'via', 'νε(e'], ['contraction', 'contractions', 'poetic', 'english', 'cases', 'made', 'words'], ['contraction', "castelnuovo's", 'morphism']]
TOP TOKENS [['ecocide', 'added', 'destruction', 'diminished', 'include', '“', 'past', 'already'], ['ecocide', '’', 'formulates'], ['desecration', 'desecration.somewhere'], ['pollute', 'cultural', 'destruction', 'ignite', 'old', 'edition', 'unabridged'], ['ecocide', 'destruction', 'ecological', 'greatest', 'incorporated', 'devastation', 'provisions', 'far', 'introduced', '1990', 'saw'], [], ['generation'], ['provisions', '16'], ['ecocide', 'consequent', '“', 'little'], ['ecocide', 'course', 'neither'], ['remastered', 'improved', 'enhanced', '2018', 'modified', 'previously', "assassin's", "aquila's"], [], ['increase', 'enhancements', 'version', 'capacity', 'later', 'differently', 'additional', 'purchasers', 'pack'], ['conflagration', 'fourth', 'diabolical', '5:53', 'blasphemous', 'full', '5:28', '4:36', '5:49', 'embellishment', '4:22', '5:13'], ['trim', 'turbocharged', 'levels', '1', 'new', 'found', 'paired', 'version', 'unveiled', '6', 'line', 'also', 'either', 'replacing', 'offers', 'offer'], ['additional', 'higher', 'purchase', 'previous', 'existing', 'justified', 'edition', '6', 'received', 'features', 'available', 'also'], ['ecocide'], ['new', 'version', 'increased', 'exclusives', 'buying', 'disabled', 'added', 'lost', 'price', 'upgraded', 'earned', 'expansions', 'could', 'previously', 'versus', "player's", 'solely', 'well'], ['added', 'trousseau', 'adding', 'fewer'], ['new']]
TOP TOKENS [[], ['mind', 'always', "barn.'he", 'would', 'indeed'], ['years', 'haunts', 'frequently', 'home'], ['never', 'ever', 'would'], ['would', 'never', 'also', 'admonish', 'forego', 'one'], ['would', 'never', 'also', 'admonish', 'forego', 'one'], ['saw', 'subjects', 'come', 'never', '’', 'making', 'goings'], [], [], ['almost', 'regard'], ['logs', 'without', 'every', 'none', 'lest'], ['folk'], [], ['stay', 'would'], ['years'], ['brodrick', 'often'], ['always'], ['dornești', 'costișa'], ['bráithrín', "berwick's", "caiside's", 'songs', 'bhéal', 'faoisdin', 'rest', 'later', 'bán:the', 'ballyhaunis', 'irish', 'army'], ['лӏыр']]
TOP TOKENS [['italianate', 'italianates', 'neighborhoods', 'typical', 'rambling', '1830s', 'era', 'homes', 'style', 'movement', 'houses', 'downing', 'earlier', 'home', 'much', 'come'], ['henry', 'governess', 'governesses', 'ladylike', 'education', 'existed', 'care', 'position', 'except', '—', 'common', 'one', 'time', "james's", 'cls', 'australia', 'master', 'school', 'within', 'children', 'exceptionally', 'babies'], ['italianate', 'italianates', 'adams', 'georgian', 'houses', 'past', '1850s', 'house', 'meandering', '1870s', 'former', 'extensively', 'last', 'early', 'almost', '1880s', 'extraordinarily'], ['moderated', 'italianate', 'grace'], ['governess', 'ingenuous', 'air', '“', '–', 'words'], ['italianate', 'teemu08', 'heavily', 'cc', '3', '0', 'rusticated', 'balconies', 'balustraded', 'attribution', 'hood', '1871', 'cropped', 'moldings', 'homes', 'topped', 'eaves', 'architecture', 'houses', 'buildings', 'brick', 'unported', 'historic'], ['italianate', 'regency', 'charles', '1840', 'buildings', 'houses', 'architecture', 'style', 'along', 'kingdom', 'collection', 'styles', 'globe', 'davis', 'like', 'unfortunately', 'today', 'holds'], ['italianate', 'moderated', 'grace', 'fresco-like', 'nature', "music's"], ['italianate', 'belvedere', 'states', 'porches', 'homeowners', 'house', 'topped', 'style', 'earlier'], ['governess', 'erin', 'schoolmistresses', 'george', 'vol', 'anthology', "solomon's", 'ed', 'w', 'ltd', 'p', 'feb', '2', 'literature', 'b', 'web'], ['shows', 'see', 'john', 'james', 'nevil', 'english-language', 'also', 'television', 'sydney', 'jacka', 'call', 'links', 'old', 'muriel', 'house', 'governess', 'originally', 'thurgood', 'references', 'telerecordings'], ['eighth', 'octavo', "king's", 'seth', 'heauton', 'countryside', 'heiress', 'iolante', 'volume', '1680', 'hitopadesha', 'bengali', 'local', 'pilpay', 'guardian', 'forms', 'form', 'collection', 'heetopades', 'nearest', 'suavity', 'nowhere', 'january', 'simeon', 'surrounding', 'appears', '1655', '1653', 'theatre', 'jovial', 'boccaccio', 'gentleman', '12', 'included', 'lusty', 'expressed'], ['upper', 'governesses', 'governess', 'ladylike', 'countryside', 'traditionally', 'remote', 'employ', 'boarding', 'lived', 'rarer', 'master', 'used', 'existed', 'nearby', 'live', 'another', 'time', 'definition', 'usually', 'regions', 'children'], ['italianate', '1870', '378', 'francois', 'architecture', 'buildings', 'topped', 'mansard', 'style', 'house', 'bracketed', 'remodeled', 'eaves', 'fashionably', 'moldings', 'cupolas', 'tower', 'ten', 'often', 'unrecognizable', 'summit', 'however'], ['8:30', 'myers', 'black-and-white', 'elements', 'contained', 'american', 'mr', 'mary', 'nature', 'howard', 'series', 'april', 'programs', 'episode', 'shows', 'lukas', 'kenyon', "company's", 'dramatization', 'p.m', 'wednesdays', 'references', 'audience', 'stranger', 'aired', '1955'], ['erinsborough', 'staple', 'libby', 'schoolteachers', 'neighbours', 'principled', 'external', 'constantly', 'driven', 'lovely', 'guardian', 'time', 'bartenders', '–', 'kinda', 'kennedys', 'anything', 'one', 'sep'], ['karl', 'helen', 'paramount', 'captain', 'american', 'donald', 'paul', 'english-language', 'adventure', 'stage', 'external', 'fin', 'films', 'film', '1930s'], ['2008', 'external', 'february', 'john', '8:30pm', 'madrigal', 'monday', 'old', 'single-camera', '–', 'u.s', 'sitcoms', 'american', 'josh', 'english-language', 'cast', 'references', 'links', 'captain', 'series', 'television', 'eventually', 'anders'], ['syndicated', 'gale', 'anthology', 'hans', 'first-run', 'grey', 'storm', 'series', 'granville', 'american'], ['italianate', 'dowager', 'belvedere', 'john', 'past', 'houses', 'pedimented', '1802', 'late', 'machicolated', 'early', "barry's", 'nobile', 'balustrades', 'neoclassicism', 'neo', 'style', 'roof', 'architraves', 'northern', 'frequently', 'synthesising', 'architectural', 'headed', 'period']]
TOP TOKENS [['nasser', "nasser's", 'abdel', 'however', 'countries'], ['nasser’s', 'nasser', "nasser's", 'abdel', 'egypt'], ["nasser's", 'nasser', 'city', 'world'], ['nasser', "nasser's", '1955', 'council', 'countries', 'associates', 'abdel', 'arab', 'president', 'leadership'], ['nasser', 'world'], ["nasser's", 'nasser', 'nasserist', 'reforms', 'ultimately', 'nationalism'], ['nasser', "nasser's", '1937', 'poverty', 'schools', 'life', '1944', 'marwan'], ['nasser', 'nasserism', 'view', 'syria', 'army'], ["nasser's", 'nasser', 'people', '1970'], ['nasser', "nasser's", 'founded', 'abdel'], ['nasser'], ['nasser', 'qatari', 'ali'], ['nasser', 'muhammad'], ['nasser', 'abdel', 'al'], ['nasser', 'nasserist', 'nasserism', "nasser's", 'abdel', 'cls'], ['nasser', "nasser's", 'july', 'movement', 'government', '1957', 'approval'], ['nasser', 'works', 'adwan', 'life', 'palestinian'], ['nasser', 'abdel', 'gamal'], ['nasser', "nasser's", 'nasserism', 'emulation', 'end', 'book'], ["nasser's", 'nasser', 'nasserist', 'day', 'shortcomings', 'progress']]
TOP TOKENS [['atc', 'run', 'competitive', 'even', 'mc'], ['run', 'firms'], ['run', 'firms', '“oqap”', 'revenue', '“a”'], ['run', 'firms', '“oqap”', 'revenue', '“a”'], ['run', 'competitive', 'c', 'cost', 'price', 'b', 'average', 'lower', 'total', 'higher', 'equilibrium', 'mc', 'atc'], ['run', 'exactly', 'mc', 'firm', '1', 'market', 'ac'], ['run', 'companies', '©mcgraw', 'thus', 'economics'], ['run', 'atc', 'shuts', 'avc', 'firms'], ['run', 'perfectly', 'given', 'particular', 'unwise'], ['run', 'price', 'ar', 'firm', 'aced', 'greater', 'competition', 'taker'], ['run', 'costs', 'production', 'zero', 'average'], ['run', 'case', 'atc', 'output', 'latter', 'q', 'average', 'levels', 'cost', 'total', 'range'], ['run', 'outcome', 'occurring', 'situation', 'zero', 'firms', 'competition'], ['run', '–', 'output', 'satc'], ['run', 'production', 'firms', 'perfectly', 'competitive', 'output', 'average'], ['run', 'output', 'short', 'chosen', 'labor'], ['run', 'firms', 'competitive', 'firm', 'cost', 'perfectly', 'average', 'operating', 'occurs', 'operate', 'case'], ['run', '5q2', 'output', 'perfectly', 'q2', 'average', '5', '5q', 'q3', 'competitive', '60q', "firm's", 'short', 'q', '2', '125'], ['run', 'output', 'scale', 'always', 'average', 'range', 'input', 'however'], ['run', 'production', 'certain', 'firms', 'bottlenecks', 'cost', 'output', 'average', 'short', 'relatively', 'act', 'shaped', 'diseconomies', 'almost']]
TOP TOKENS [['nickel', 'nis', 'sulfide', 'ic0607585', '4', '10467'], ['ni', 'nickel', 'nis', 'ni2', 'ni2o3', 'nisbs', 'nio', 'nias', 'niass', 'nisb', 'nias2', 'niso4', 'tetracarbonylnickel'], ['nickel', 'ni', 'ni2l2ni22', 'ni2', 'ni22', 'nio', 'form', 'mononickel', 'treating', 'ligands'], ['ni', 'nickel', 'niiii', 'nickelocene', 'nicl2', 'nicl', 'hydrogen', 'numerous', 'h'], ['nickel', 'ni', 'contains'], ['ni', 'nickel', 'sensors', 'vacuum', '†', 'vap', '8', '453°c', 'specific', 'allergies', '262°c'], ['nickel', 'ni', '6', '59', '106', '1', '3', '14', 'glance', '4970', 'mol', '×10'], ['ni', 'nickel', '18', '450', 'nitric', 'lungs', 'amounts'], ['nickel', 'temperature:||253', 'applications', 'oc'], ['nickel', 'ni', 'nickel-iron', 'nickel-chromium', 'nickel’s', 'nickel-copper'], ['nickel', 'ni'], ['ni', 'nickel', 'nif2', 'ni6', 'nihff6', 'nizrf6', 'ni2hff8', 'groups', 'water'], ['nickel', 'ni', 'ni3', 'ions', 'sites', 'mononickel'], ['ni3', 'nif4', 'nickel', 'ni', 'nif6', 'ni2', 'ni4f4o', 'nil2', 'nickelous', 'h5nif7', 'several', 'nicl4', 'pentacyanonickelate', 'nicl2', 'halogens', '9nio'], ['nis', 'ni2', 'nickel', 'nisx', 'ni9s8', 'ni3s2', 'nicl2', 'nis2', 'ni3s4'], ['ni(ch3co2)2·4', 'ni(ch3co2)2·x', 'nickel', 'nickel(ii'], ['nickel', 'ni3n', 'ni', 'nickelous', 'ni1−xse', 'nii2', 'nis2', 'ni1', 'nis', 'nibr2', 'ni2se3', 'ni9s8', 'nif4', 'nise2', 'nif3', 'nipo2', 'nipo', 'nis4', 'ni3s2', 'ni3s4', 'ni17s18', 'nitride'], ['ni2', 'nickel', 'ni', 'niooh', 'cls', 'people', 'batteries', 'form'], ['ni2', 'ni(h2o)6]2', 'ni4co3(oh)6(h2o)4', 'ni', 'nickel', 'nio', 'nickel(ii'], ['ni(no3)2.4h2o', 'nickel(ii', 'nickel', 'ni(no3)2', 'ni(h2o)6](no3)2', 'ni(no3)2.9h2o', 'ni(no3)2.6h2o', 'ni(co)4', 'nio', 'ni(no3)2.2h2o']]

Processing features:  90%|████████▉ | 88/98 [42:13<04:39, 27.92s/it]

getting sample prompt forgetting sample prompt for 24457
 24456
getting sample prompt for 24458
getting sample prompt for 24459
getting sample prompt for 24460
getting sample prompt for 24461
getting sample prompt for 24462
getting sample prompt for 24463
getting sample prompt for 24464
getting sample prompt for 24465
getting sample prompt for 24466
getting sample prompt for 24467
TOP TOKENS [['1', '0', 'cdplayer', 'usr', 'install', 'doc', 'redhat'], ['works', 'use', 'open', 'set', 'installing', 'install', 'kit', 'receiver', 'properly', 'various', 'ir', 'transmitter', 'everything', 'learn', 'go', 'since', 'using', 'except', 'first', 'said'], ['got'], ['interoperability', 'raptivity', '1999', 'nineties', 'learning', 'autonomously', 'place', 'training', 'elearning', 'proprietary', 'using', 'time', 'communicate', 'choice', 'tasked', 'back', 'delivering', 'different', 'therefore', 'operated', 'job', 'want', 'across', 'way', 'works', 'enables', 'nutshell', 'imagine', 'products', 'various'], ['interoperability', 'time', 'learning', 'nineties', 'elearning', 'proprietary', 'camtasia', 'autonomously', 'raptivity', 'content', 'using', 'want', 'choice', 'back', 'tasked', 'imagine', 'job', 'lms', '2001', '1999', 'operated', 'works', 'across', 'enables', 'place', 'department', 'therefore', 'standards'], ['want', 'well', "what's", 'ahead', 'use', 'go', "let's", 'thing', 'certainly', 'thrown', 'get', 'compositing'], ['clear', '22', '0', '666', 'irradiation', 'solution', 'onto', 'first', 'preheated', '11', 'furthermore'], ['github', 'sbprojects', 'worry', 'ir', '4', 'remotes', 'operating', 'com', 'different', 'therefore', 'many', 'either', 'use', 'signal', '0', 'works'], ['honda', 'working', 'pec', 'irradiation', 'energy', 'appreciable', 'emission1', '2', 'semiconductor', 'since', 'semiconductors5', 'photocurrent', 'photoelectrodes'], ['communications', 'interstate', 'navigate', 'start', 'keys', 'relations', 'tip', '1800', 'use', 'history', 'years', 'american', 'americas', 'tentative', 'nice', 'america', 'approves', 'abandons', 'including'], ['pragmatic', 'win', 'rapprochement', 'aljazeera', 'cannot', 'manner', 'opportunity', 'diplomatic', '17', 'hebrew', 'sensitivities', 'december', 'halevy', 'assertions', 'years', 'mitt', 'interests', 'regard', 'arabia', "obama's", 'unprecedented', 'underscored', 'vis', 'taking'], ['angeles', 'los', 'usage', 'may', 'capabilities', 'transportation', 'features', 'advisories'], ['candidate', 'prior', 'technicality', 'propriety', 'company', 'wins', 'presidential', 'done', 'start', 'w', 'gulf', 'advance', 'elected', 'london', 'bush', 'gave', 'getting', 'amounted', 'already', 'money', 'months', 'one', '2001', 'far', 'away'], ['bus', '19:13:03', '13:10', '5/4/2015', '16', '13:45', '13:30'], ['scritti', 'agreed', 'entertainment', 'worked', 'time', 'tracked', 'relations', 'deal', 'angeles', 'inc', 'partnered', 'received', 'failed'], ['situ', 'e', 'compatibility', 'barrier', 'contaminants', 'aquifer', 'sludge', 'conducted', 'recently', 'onsite', 'treatment', 'geochemistry', 'remediation', 'containing', 'either', 'unsuccessful', 'may', 'microorganisms', 'advancements', 'bermed', 'clays'], ['contact', 'engineer', 'coming', 'undiluted', 'time'], ["101's"], [], []]
TOP TOKENS [['weir', 'cls', 'walter', 'aligned', 'horrors'], ['weir', 'cls', 'walter', 'aligned', 'horrors'], ['weirs', 'weir', '1670'], ['weirs', 'weir', '1670'], ['weir', 'weirs', 'cls', 'tops', 'navigable', 'cases', '3'], ['weirs', 'weir', 'william', 'john', 'alison', 'vere', 'daniel', '1643'], ['weirs', 'weir', 'william', 'john', 'alison', 'vere', 'daniel', '1643'], ['weir', 'goes', '1892', 'farm'], ['weir', 'weirs', 'love', 'like'], ["weir's", 'weir', 'claims', 'moreover', 'achieved', 'often', 'women', 'respectively', 'quoted', 'ghoil'], ['weir'], ['weir'], ['weir', "weir's", 'health', '1943', '1926', 'awards', 'class', '9', 'society', '1885', 'cemetery', '1944', 'received', 'union'], ['weir', 'week', "weir's", '2021', 'overall', 'injury', 'june', 'also', 'following', '2020', 'header'], ['weir', 'physician', 'jenner', 'geologist'], ['weir', 'actress', 'james', 'australian'], ['weir'], ['weir', '2014', '2021', '2012', 'olympics', 'month', 'works', 'january', 'cited', 'links', 'references', 'purchase'], ['weir'], ['weir', "weir's", 'tournaments', 'career']]
TOP TOKENS [['trilinear', 'i1', 'functionality', 'defined', 'dim', 'yaml', 'derivatives', 'expand2', 'tensor', 'tensors', 'i2', 'expand1', 'grad', 'i3', 'enough', 'elsewhere', 'end', 'derivative', 'efficiency', 'expand3', 'sumdim', 'top', "let's"], ['person'], ['clinorotated', 'curvature', 'small', 'cells', 'dorsiventrality', 'also', 'directions', 'species', 'cress'], ['reseeds', 'reseed', 'device', 'arc4rand', 'entropy', "developer's", 'know', 'value', 'unless', 'large', 'loaded', 'numbers', 'unseeded', 'cls', 'available', 'non', 'remember', 'identically', 'therefore'], ['reseeds', 'reseed', 'device', 'arc4rand', 'entropy', "developer's", 'know', 'value', 'unless', 'large', 'loaded', 'numbers', 'unseeded', 'cls', 'available', 'non', 'remember', 'identically', 'therefore'], ['advanced', 'degenerative', 'anterolisthesis', 'nonoperative', 'graded', 'facet', 'spondylolisthesis'], [], [], [], ['nonunreal', 'cls', '2'], [], ['λ', '9'], [], ['adolfas', '1925', 'designer', '1918–1957', '1904–1974', 'born', '1900–1973'], ["men's", 'robertas', 'giedraitis', '2013', 'šiauliai', '2011', 'basketball', 'lithuanian', 'life', 'season', '2010', '2012', 'player', 'utena', 'lkl'], ['x1', 'degree', 'k1', 'however', '1', 'r', '2r', 'hyperdeterminant', 'hyperdeterminants', '−', '2', '3', '5', '×', 'rapidly', 'sizes'], ['designation', 'years', 'λ', 'koronian', 'prov', 'classification', 'measures', 'eccentricity', 'ecliptic', 'orbits', 'cls', '0', '0°', '6', '119', '3°', '1', '2', 'approximately', '301', 'asteroid', '–', '7', '5', 'several'], ['cyclical', '“immaculate”', 'process', 'reduced', 'organisms', 'clarifiers'], ['mallick', 'yearsley', 'references', 'might'], []]
TOP TOKENS [['«radioactive»', 'radioactive', 'radioactivity', 'chemical'], ['radioactive', 'also', 'element'], ['radioactive', 'radiopharmaceuticals', 'materials', 'sealed', 'radiographers'], ['radioactive', 'radiation', 'something'], ['radioactive', 'radioactivity', 'materials', 'quite', 'science'], ['radioactive', 'radioactivity', 'dictionary.com'], ['radioactive', 'radioactivity', 'material', 'million', 'materials', 'particles', 'containing'], ['radioisotopes', 'radioactive', 'liquid', 'carcasses'], ['radioactive', 'radioactivity', '2023', 'adjective'], ['radioactive', 'radioactivity', 'non-radioactive', 'material'], ['radioactive', 'radioactivity', '1985'], ['radioactive', 'radioactivity'], ['radioactivity', 'radioactive', 'radionuclide', 'radionuclides'], ['radioactive', 'radioisotopes', 'well', '99m', 'nanoparticles', 'materials', 'nanomedicine', 'cls'], ['radioactive', 'radioisotope', 'radioisotopes', 'radiolabeling', 'radionuclide', 'radiotracer', 'radiocarbon', 'radiotracing'], ['radioactive'], ['radioactive', 'companies'], ['radionuclide', 'radionucleotide'], ['radioactive', 'materials', 'radioactivity', 'radionuclides', 'nanoparticles', 'well', 'burned', 'containing'], ['radioactive', 'radionuclides', 'radioisotopes', 'radiopharmaceutical', 'radionuclide', 'radiopharmaceuticals', 'radioisotope', 'radiopharmacology', 'radioiodine']]
TOP TOKENS [['added', 'include', 'alike', 'policies', 'time', 'policy', 'employees', 'making', 'stakeholders', 'trend', 'purpose', 'roles', 'risks'], ['movie', 'deliberate', 'police', 'situations'], ['outcome', 'making', 'made', 'make', 'policy', 'available', 'items', 'policies', 'seeking', 'compel'], ['https://sociologydictionary.org/policy', 'context', '2014', '“policy.”', 'school', 'edition', 'class', '2021', 'journals', '“policy”', 'policy'], ['imposed', 'policies', 'goals', 'organizations', 'behavior', 'evaluation', 'smoothly', 'policy', '•', 'chalking'], ['policy', 'break', 'categories', 'policies', 'specific', 'game', 'incidents', 'player', 'security', 'try'], ['policies', 'policy', 'existing', 'proposed', 'require', 'new', 'workplace', 'responsibilities', 'jargon', 'addresses'], ['community', 'policy’s', 'policy', 'every', 'know', 'support'], ['environment', 'fulfilled', 'decisions', 'policy', 'policies', 'make', 'described', 'related', 'time', 'sep'], ['etc', 'goals', 'brainmass.com', 'wwcd.org', 'cultural'], ['album', 'outcome', 'guides', 'decisions', 'achieve'], ['imposed', 'level', 'entity', 'pitfalls', 'systems', 'policy', 'think', 'allocation'], ['field', 'organised', 'existing', '”', 'particular', 'accessible', 'approaches', 'inform', 'interest', 'policymakers', 'insights', 'range', 'relevant', 'many', 'practice'], ['impact', 'publishing', 'index/abstracts', 'education', 'policy', 'abstracted', 'journal', 'factor'], ['made', 'policy', 'stage', 'policies', 'seeking', 'dramatically', 'challenges', "organization's", 'given', 'claim', 'benefit', 'seek', 'analysis', 'lack', 'topic', "ground'when"], ['outcome', 'practices', 'given', 'mirror', 'making', 'specific', 'outcomes', 'organization', 'protocol', 'nature', 'policy', 'payment', 'e', 'compel', 'implemented'], ['elsevier', '9.0'], ['contradicting', 'even', 'emphasis', 'policy', 'called', 'good'], ['world', 'studies', '2002', 'policy', 'science', 'ranks', 'development', 'research', 'indexing', 'entrepreneurship', 'worked', 'according', 'hub', 'joseph', 'across', 'director', 'policys', 'unit', 'compile'], ['policymakers', '205', 'policy', 'information', 'life', 'storage', 'encompasses', 'coming', 'flow', 'environment', 'analysts', 'discourage', 'according', 'energy']]
TOP TOKENS [['thickness', 'stories', 'foliated'], ['may', 'apart', '5', 'process', 'options', 'cm', 'somewhat', '2', 'thorough', 'significantly', 'explore', 'vary'], ['close', 'drain', 'line', 'faucet', 'turn', '3', 'take', 'go', 'next', '1', 'open', 'existing', 'see', 'first', 'tubing', 'valve', 'connected', 'attach', 'place', 'dispenser', '2'], ['herds', 'drovers', 'cattle', 'business', 'persons', 'another', 'eye', 'market', 'candles', '1882', 'slaughter', 'head'], ['installed', 'unk', '2', '0', '1'], ['mounted', 'e', 'may'], [], ['—', 'application', 'fast', 'however', 'resistance', 'available', 'chemically', 'coarse', 'also'], ['recirculates', 'installed', "handle's", 'drain', 'sink', 'gloss', 'glazing', 'minerals', 'surface', 'fitting', 'found', 'ware', 'high', 'usually', 'creates', 'countertop'], ['close', 'styles', 'offer', 'canopy', 'cut', '–', 'leaving'], ['pig-production', 'strain', 'hibernia', 'originally', 'environment', 'previously', '31076', 'norvegicus', 'also'], ['roots', 'savage', 'householder', 'sit', 'booking', 'past', 'likely', 'future', 'branch', '–'], ['artist', 'processing', 'powered', "ireland's", 'employees', 'onwards', 'excess', 'people'], ['1,000', 'location', 'feature', 'market', 'street', 'apartments', 'one', 'low', 'moderate', 'late'], [], ['ex', 'operation', '3', 'canneries', 'packs', 'refrigerated', 'close', 'market'], ['industries', 'especially'], ['brewpub', 'joliet', 'brewing', 'opened', 'brewery', 'brewhouse', 'company'], ['latebrivora', 'forbes', 'tineidae'], ['57', '727', 'films', 'raked']]
TOP TOKENS [['hinge', 'hinges'], ['hinge', 'hinges', 'today', 'come', 'long', 'find'], ['hinge', 'hinges', 'hingesthe', 'imported', 'forms'], ['hinge', 'hinges', '’', 'mind', 'joint', 'pictures'], ['hinge', 'hinged', 'hinges', '‘', 'rely', 'without'], ['hinge', 'hinges', 'cls'], ['hinge', 'hinges', 'untill'], ['hinge', 'hinges', 'mortise'], ['hinge', 'hinges'], ['hinge', 'hinges', 'hinged', 'cls', 'eventually', 'rely', 'needed'], ['hinge', 'hinge-back', 'hinges', 'objects', 'hinge-action'], ['hinge'], ['hinge', 'hinges', 'rome'], ['hinge', 'hinges', 'concrete', '123–132', 'still', 'used', 'safteyconcept', 'semipropablistic'], ['hinge', 'hinges', 'hinged'], ['hinge', 'hinges', 'structures', 'leaves'], ['hinge', 'adelaide', 'injury', '75', 'sanfl'], ['hinge', 'hinged', 'hinges', 'links'], ['hinges'], ['hinge', 'hinged', 'hinges', 'hingeless', 'multiple', 'regummed', 'references', 'remain']]
TOP TOKENS [['electrons', 'electron', 'shapes'], ['electron', 'electrons'], ['electron', 'electrons', 'construct', '7–8', 'a.w'], ['electron', 'electrons', 'mechanics'], ['electron', 'install', 'application', 'prebuilt', 'core', 'operating', 'webpages'], ['electron', 'electrons'], ['electron', 'electrons', 'although', 'view', 'experience'], ['electron', 'electrons', 'define', 'know', 'truth'], ['electron', 'electrons', 'words', 'sounds', 'others', 'values'], ['electron', 'electrons', 'orbital', 'find'], ['electron', '1937'], ['electrons', 'electron', 'properties', 'st'], ['municipality', 'electron', 'one', 'johannesburg'], ['electron', 'electrons', 'properties'], ['electron', 'electrons', 'moving'], ['electron', 'electrons', 'wave', 'term', 'waves'], ['electron', 'electrons', 'reconstructed', 'kev', 'waves'], ['electron', 'flight', 'rocket', 'also', '2017–2018', 'links', 'experienced', 'first', 'orbital', 'pickering', 'sub-orbital', '2017'], ['electron', 'electrons'], ['electron', 'electrons', 'diffraction']]
TOP TOKENS [['carriages', 'carriage'], ['carriage', '“', '”', 'typewriters', 'use'], ['carriage', 'carriages', 'drawn', 'finally'], ['carriage', 'carriageˈkær', 'word'], ['carriage', 'carriages', 'term', 'machines', 'cls', 'b'], ['carriage', 'carriages'], ['carriage', '“', 'carriages', 'one', 'house'], ['carriage', 'carriages', 'presence', 'land'], ['carriage', 'carriages', 'foot', 'drawn', '“', 'houses', 'waned', 'accommodate', 'house', 'worth', 'square'], ['carriage', "word'carriage'in", 'carriages', 'include', 'comfortable', 'baby', 'vehicles', 'gun'], ['carriage', 'countries', 'firing', 'kruglik', 'vehicle', 'signal', 'continuous', 'opera'], ['carriage', 'carriages', 'wheeled', 'driving'], ['category:carriage', 'carriage'], ['carriage', 'carriages', 'word', 'wheeled', 'drawn', 'within'], ['carriages', 'carriage', 'driving'], ['carriage', 'carriages', 'closed', 'forecarriage'], ['carriage', 'together', 'festival', "nesterova's"], ['carriage', 'carriages', 'traversing', 'garrison', 'stakes', 'gun'], ['carriage', 'moving', 'carrier', 'term', 'combined'], ['carriage', 'carriages', 'traversing', 'rear', 'modern']]
TOP TOKENS [['citadel', 'citadels', 'term', 'citadelle', 'system', 'david', 'bastions', 'interchangeably', 'center'], ['citadel', 'citadel.the', 'citadel.beacon', 'thenceforth', 'use', 'nearby', 'words', 'democracy', 'old', 'civil', 'tenable.atlanta’s', 'taken'], ['citadel', 'term', 'citadels', 'system', 'bastions', 'interchangeably', 'citadelle', 'david', 'rest', 'hemisphere', 'haitian', 'center', 'peninsula', 'acropolis', 'core', 'cls', 'economy', 'various', 'fortress', 'feudal'], ['citadel', '“citadel”', 'citadels', 'word', 'takeover', 'area', 'staff', 'many', 'leaders', 'time', 'attack', 'siege'], ['citadel', 'citadels', '“', 'word', 'area', 'takeover', 'attack', 'time', 'many', 'leaders', 'staff', 'years', 'siege', 'fortresses'], ['citadel', 'citadels', '“', 'word', 'area', 'takeover', 'attack', 'time', 'many', 'leaders', 'staff', 'years', 'siege', 'fortresses'], ['citadel', 'possible', 'fortress', 'medieval', 'fort'], ['forte', 'people', 'say', 'armed', 'guards', 'word', 'fortress', 'usage', 'sword', 'everyone', 'excels'], ['citadel', 'sides', 'i.a', 'k.k', 'k.e', '18–21', 'walls', 'kostsyushko-valyuzhinich', 'drains', 'constructions', 'v.v', 'coast'], ['citadel', 'modern', 'www', 'behind', 'uncensored', "crt's", 'versions', 'sep'], ['nevada', 'arizona', 'mountain', 'citadel', 'mall', 'carolina', 'effect', 'knaak', 'series'], ['1957', 'citadel', 'records', 'novel', 'game', 'series', 'film', 'films', 'fort', 'llc', 'half-life', 'malware', 'citadels', 'song', 'center', 'securities', 'kursk', 'press', 'armored', 'george', 'accounts'], ['citadel/ux', 'citadel', 'originally', 'mod_auth_citadel', 'system', 'modernize', 'built-in', 'stuart', 'gpl-3.0-only', 'security', 'implementations', 'internet', 'base', 'bsd'], ['daniel', 'guitar', 'citadel', '6', 'anthony', 'presland'], ['citadel', '2020', "citadel's", 'profits', 'managers', 'activities', '2021', '2016', '2012', 'llc', 'crisis', 'directors', 'ltd', 'chicago', 'losses'], ['2007', 'citadel', '2022', 'cls', '2006', "citadel's", '1998', 'bonds', '1990'], ['citadel', 'census', '2016', 'station', 'east'], ['citadel', 'band', 'albums', 'links', 'records'], ["citadel's", 'citadel', '2009', '2022', 'squeeze', 'firm', 'spreads', 'oversight', '2020', 'revenue', 'shares', 'sec', 'volume', "barron's", 'august', '2015'], ['forte', 'forté']]
TOP TOKENS [['holderlin', 'generation', 'view', 'probably', 'recovered', 'recluse', 'rediscovery'], ["holderlin's", 'holderlin', 'religions', 'fused', 'maturity', 'would', 'terrifying', 'experience', 'madness', 'expand', 'understatement', 'evaluation', 'insane', 'throes'], ['hölderlin', 'holderlin:the', 'holderlin', 'earned', '1770–1843', 'since', 'exile'], ['holderlin', "holderlin's", 'years', 'contemporaries', 'experience', 'century', 'fact', '36', 'would', 'fade', 'presences', 'even'], ['holderlin', 'admirers', 'renaissance', 'historical', 'wanted', '’', '‘', 'surrogate', 'time', 'journeyman', 'shall', 'master'], ['holderlin', 'admirers', 'renaissance', 'historical', 'wanted', '’', '‘', 'surrogate', 'time', 'journeyman', 'shall', 'master'], ['holderlin', "holderlin's", 'religions', 'actuality', 'noted', 'century', 'contemporaries', 'centuries', 'widely'], ["holderlin's", 'holderlin', 'edward', 'david', 'question'], ['holderlin', "holderlin's", 'translation', 'though', 'hesse', 'earned', 'new', 'apt', 'genuine', 'greatly', '—', 'decipher', 'tortuous', 'found'], ['holderlin', '1798', '1796', 'schiller', 'friedrich', 'obtained', 'later'], ['holderlin', "holderlin's", 'trans', 'hoddypodge'], ['holderlin', "holderlin's", 'holderlinturm', 'composers', 'tower', 'year', 'following', 'nurtingen', 'continued', 'melded', 'treason', 'dionysus', '11'], ["holderlin's", 'holderlin', '73', 'neckar', 'friedrich', 'incurable'], ["holderlin's", 'holderlin', 'holderlins', '–', 'links', 'heidegger', 'external', '1961'], ['holderness'], ["holderlin's", 'holderlin', 'maturity', 'madness', 'would', 'influence', 'generally', 'structure', 'beauty'], ['holderness', 'graham'], ['holderlin', "holderlin's", 'ailing', 'holderlinturm', '1807', 'place', 'friedrich', 'weiter'], ["holderlin's", 'approaches', 'kehrer', 'berlin', '529', 'knecht', 'seolbong', 'et', '2003', '2004', "d'arts", 'ettlingen', 'kunstverein', 'france', 'kondeyne'], ["holderman's", 'holderman']]
TOP TOKENS [['ana', 'purposean', 'effectsyou', 'bruising', 'tetanus'], ['ana', 'tropical', 'storm', 'mbar'], ['ana', 'tropical', 'storm', 'robbie', 'five'], ['ana', 'anas', 'intensity'], ['ana', 'mph', '57', 'morning', 'within', 'storm', 'earlier', 'damage'], ['ana', 'anas', 'cls'], ['ana-9-line', 'ana', 'org', 'disease'], ['ana', 'santa', 'breeze'], ['ana', 'academia'], ['ana', 'academia'], ['ana', '1871', 'sickness', 'ptv', 'award', 'national', 'leadership'], ['ana', '2011', 'nominee', 'reception', 'rediscover', 'antónio', 'reis', 'months', 'ethnofiction', 'film'], ['ana', '–', 'references'], ['ana', 'golden', '4:04', 'albums', 'departure'], ['ana', 'several'], ['ana', 'ak'], ['ana', 'anade'], ['ana', 'executive'], ['ana', 'accompanied', 'eye', 'barfly'], ['ana', 'amirpour', 'alexander', 'alvares', '2003']]

Processing features:  91%|█████████ | 89/98 [42:41<04:11, 27.97s/it]

getting sample prompt forgetting sample prompt for 24469
 24468
getting sample prompt for 24470
getting sample prompt for 24471
getting sample prompt for 24472
getting sample prompt for 24473
getting sample prompt for 24474
getting sample prompt for 24475
getting sample prompt for 24476
getting sample prompt for 24477
getting sample prompt for 24478
getting sample prompt for 24479
TOP TOKENS [['href', 'href="">click', 'may', 'button><a', 'either', '32px'], ['href', 'getting', 'part', 'right', "here's", 'may', 'correct', 'back', 'worry', 'tricky', 'like', 'referencing', 'see', "can't"], ['href', 'th', 'v204', 'thead', '30'], ['href="https://www.pustudy.com', 'hreflang="en">html', 'hrefattribute', 'hreflang', 'href', 'codes</a', 'codes'], ['renders', '’', 'href', 'depending', 'back', 'let', 'us', 'away', 'see', 'ideal', 'create'], ['href', 'src', 'image1', 'image5', 'image3', '1', 'html', 'image4', 'u', 'image2', 'img'], ['href', 'wondering', "here's", 'well', 'like', 'stands', 'attribute', 'using'], ['href', 'hrefattribute', 'text', '199', 'css', 'link', 'mystyle', 'particular', 'see', 'stylesheet', 'allowed'], ['href', 'often', 'style', 'author'], ['href'], ['hrádek'], ['hrušovo', 'http://www.tourist-channel.sk/hrusovo/indexen.php3', 'hrusovo', 'http://www.e-obce.sk/obec/hrusovo/hrusovo.html', '1427', 'hrwswa', '1787-1852', 'rwsowa'], ['hradešín'], [], ['27', 'hrabetin', 'three', '1943', '2004', '1941'], ['hromos', 'b', 'hromoš', 'https://web.archive.org/web/20070513023228/http://www.statistics.sk/mosmis/eng/run.html', 'parish', '1822-1903', 'available', '1686-1924', 'births/marriages/deaths'], ['inhabitants'], ['hrušová'], ['hradecky', 'sweden', 'choice', '29', 'first', '2010', '18', '0', 'appeared', 'winter', 'autumn', '1st', 'u', 'finland', 'may', '2013', 'danish', '2021', 'fb', 'number', '19', 'father', 'family', '2', '2017'], ['hrubieszów', 'hrebenne', 'north-east']]
TOP TOKENS [['chiller', '“', 'degree', 'integration', 'chilled', 'ascertain', 'tool', 'one', 'cls', 'devices', 'cycles', 'high', 'however'], ['chills', 'chillscauses', 'chillssymptoms', 'conditions'], ['chillers', 'chiller', 'regardless', 'situation', 'chilled', 'commercial'], ['chillers', 'chiller', 'chill'], ['chiller', 'chillers', 'chilled', 'proper'], ['chills', 'meningitis'], ['chiller', 'chillers', 'chilled', 'water'], ['chills', 'chill', 'stretch', 'whether'], ['chiller'], ['chiller', 'chillers', 'chilled', 'right', 'total', 'required'], ['chiller', 'chill', 'liquid', 'disambiguation'], ['1968', 'chills', 'born', '1980s', 'chill', 'early', 'san'], ['chillara', 'chíllar', 'chillar', 'hondh-chillar', 'spain'], ['chilla', 'chilla-nashini', 'solitude', 'ecuador'], ['chille'], ['chillon'], ['chillin'], ['chillón'], ['chilla', 'chilla-nashini', 'chilla-khana'], ['chillicothe', 'todd']]
TOP TOKENS [['sage', 'breast', 'acetylcholine', 'times', 'teaspoon', 'menstrual', 'problems', 'like', 'milk', 'rosemary'], ['sage', 'shampoo'], ['sage', 'content'], ['sage', 'flavor', 'microwave', 'leaves', 'spikes', 'divisions', 'trimmed', 'bloom', 'well'], ['sage', 'problems', 'stews', 'cells'], ['sage', 'today', 'results', 'dried', 'word'], ['sage'], ['sage', '95th', 'daily', 'students', 'verbal', 'solving'], ['sage', 'injured'], ['sage', '95th', 'reasoning.daily', 'solving'], ['sage', '1893'], ['sage'], ['sage', 'playing', 'actors', 'played'], ['sage', 'birth'], ['sage'], ['sage', "sage's", 'links', 'external'], ['states'], ['sage', 'season', '2019', '2018', 'football', 'american'], ['sage', 'war', 'capt', 'cemetery', 'death', 'family', 'jr', 'others', 'references', 'commanded', 'h'], ['sage', 'references', '1995', 'bell-scott']]
TOP TOKENS [['obligation', 'ergo', 'strongly', 'limited', 'borrows', 'always', 'deterministic', 'unintended', 'handle', 'legal', 'signature', 'result', 'use', 'transations', 'based', 'concepts'], ['minimum', 'erlang', 'skills', 'working', 'production', 'best', 'supports', 'proprietary', 'philosophy', 'engineered', 'programming', 'erlang-built', 'locks', 'language', 'small', 'much'], ['erlang', 'example', 'fanfare', 'inner', '”', 'justice', 'accomplished', 'scenes', 'sets', 'developed', '’', 'next', 'carefully', 'compilers', 'specializing', 'compiler'], ['ertlingertljohn', 'sep', 'ertloff', '1882', 'ertlmaier', 'ertling', '1985'], ['erred', 'erpetologist', 'errable', 'errancy', 'interrogation', 'errableness', 'errabund', 'errand', 'erose', 'err', 'error', 'erotesis', 'erpetology', 'vb', 'cupid', 'erring', 'eroteme', 'erosive', 'erostrate', 'tending', 'nibbled', 'quality', 'eros'], ['erlang', 'erl', 'default', 'machine', 'information', 'long', 'preceded', 'last', '2003', 'changed', '04', '15', '10', 'starts', 'file', 'see', 'run', 'met', 'log', 'section', 'time'], ['forms', 'ergative-or-transitive', 'i.e', 'ergative', 'ergates', 'ergative-only', 'languages', 'greek', 'typically'], ['erlang', 'replaced', 'weekly', 'skills', 'errors', 'tolerant', 'eliminating', 'enough', 'proprietary', 'working', 'programming', 'locks', 'inventor', 'time', 'processes', 'variables', 'keep', 'minimum', 'engineered', 'realize', '1986', 'language', 'armstrong'], ['erlang', 'erlang-questions', 'spawn', '15:52:40', 'almost', 'familiar', 'supervision', 'suddenly', 'pure', 'exactly', 'cest', 'two', 'python', 'benefits', 'altogether', 'mainstream', 'using', 'stuff', 'always'], ['eren', '’', 'morality', 'may', 'pro', 'analyzing', 'acknowledging', 'team', 'insight', 'additionally', 'whether', 'comes', 'see', '1'], ['1970', 'traditionally', '1965', '14', 'ervika', 'june', 'service', '1907', 'ervik', 'church', 'go', 'stood', 'bjørgvin', 'renamed'], ['municipality'], ['8', '2016', 'season', 'take', '2', 'list', 'either', 'jays', 'remainder', 'late', '2019', '5', 'unable', 'may', 'padre', 'left', 'roster', '1', '2020', 'erlin', 'diego', 'roughed', 'diagnosed', 'start', 'fifth'], ['born', '1987', 'eronildo'], ['norway', 'ervik', 'church', 'work', 'small', 'peninsula'], [], [], [], ['eroğlu'], ['turkish', 'alaca', 'think', 'tank']]
TOP TOKENS [['warm-ups', 'warm-up', 'warming-up', 'warm', 'warming', 'behind'], ['clients', 'warming', 'warm', 'works'], ['warm-up', 'warm-ups', 'effective', 'warming', 'easily', 'sit-ups', 'must', 'warm', 'routine', 'session'], ['warmups', 'warm-up', 'warm-ups', '“warming', 'warming', 'specificity', 'important'], ['warm', 'warming', 'would'], ['ups', 'warm', 'warming', 'good', 'cls'], ['warm', 'warming', 'ups'], ['warm-up', 'warm', 'warming'], ['warm-up', 'warm-ups', 'effective', 'warming', 'proper', 'warm'], ['ups', 'warming', 'warm', '—', 'proper'], ['warm-up'], [], ['warm', 'video', 'games', 'gameplay'], ['track', 'tracks', 'production', '1', '2', '–', 'noted', 'ones', 'warm', 'assistance', 'secreta', 'featured'], ['ups', 'warm', 'abdomen', "actor's", 'whole', 'performed'], ['ups', 'warming', 'warm', 'may', 'designed', 'whether', 'dynamic', 'time'], ['warming'], ['warm', 'used', "dupri's"], ['warming', '3:05', "that's", '3:04', 'electronic'], ['warman', 'born']]
TOP TOKENS [['bearing', 'bearings', 'movement'], ['bearing', 'bearings', 'movement', 'operation'], ['bearing', 'b'], ['bearings', 'bearing', 'result', 'cls'], ['bearings', 'bearing', 'efficiency', 'vibration'], ['bearings', 'tomorrow’s', 'bearing', 'today’s', 'role', 'century', 'lives'], ['bearings', 'tomorrow’s', 'bearing', 'today’s', 'role', 'century', 'lives'], ['bearing', 'bearings', 'permit', 'tolerances', 'radial', 'emirates'], ['bearings', 'bearing', 'movement', 'wear', 'cls', 'axis', 'surfaces', 'speeds'], ['bearing', 'bearings', '03', 'elements', 'role', 'people', 'etc'], ['bearings', 'bearing(s', 'bearing'], ['bearing', 'bearings', 'parts', 'friction', 'cls'], ['bearings_(mechanical', 'bearing', 'bearings'], ['bearing'], ['bearing', 'bearings'], ['bearings', 'machines', 'bearing', 'references', 'mechanical', 'treatment'], ['bearing', 'bearings', 'bushing'], ['bearings', 'bearing', 'ball-bearings', 'rollers', 'lubricant', 'typically', 'angle', 'used'], ['bearings', 'bearing', 'sliding'], ['bearing', 'bearings', 'mechanical']]
TOP TOKENS [['cicero'], ['cicero', 'terror', 'ornament', '’', 'works', 'revolution'], ['cicero', 'people', 'opinion', 'limbs', 'extent'], ['cicero', 'tastes', 'makes', 'individual', 'weaknesses', 'entitles', 'one', 'divinely'], ['cicero', 'compositions....http://books.google.com/books/about/letters_of_cicero.html?id=cnrugnmbq2ic&utm_source=gb-gplus-shareletters', "cicero's"], ['cicero', 'reforms', 'aggrandizement', 'principle', '’', 'period', 'century', 'renaissance', 'nourished', 'remarked'], ['cicero', 'end', 'people', 'teach', 'upon', 'one', 'iconoclasm'], ['cicero'], ['cicero', 'situation', 'academy', 'frustrations'], ['cicero', 'ciceronian', 'forumromanum', 'many', 'c'], ['cicero'], ['cicero', 'ciceros', 'stage', '2003'], ['cicero', 'seasons', 'sox', '1954'], ['cicero', 'district', '1934'], ['cicero', 'clarks', 'aircraft'], ['cicero', 'cta/ups'], ['cicero', 'originally', 'references', 'measure', 'public', 'neighborhood'], ['cicero', 'weekday'], ['cicero', '2007', 'classics', 'river', 'within', 'water', 'corners'], ['cicero', "cicero's"]]
TOP TOKENS [['functions', 'function', 'f', 'x', 'interchanged'], ['function', 'f', 'x'], ['f(x', 'certain', 'function', "f'(x)=0", "f'(x", 'x=a', "f'(x)>0"], ['functions', 'f', 'function'], ['function', 'f', 'x'], ['functions'], ['function', 'functions', 'f', 'x'], ['f', 'functions', 'function', 'x'], ['f', 'function', 'functions', 'iff', 'x'], ['function', 'functions', 'f', 'x'], ['function', 'functions'], ['function', 'functions', "function's"], ['functions', 'function', 'interchanging', 'valued'], ['function', 'f', 'functions', 'x'], ['function', 'functions', 'f', 'x', 'valued', 'x∗', 'defined'], ['functions', 'function', 'constants', 'say'], ['function', "function's", 'f', 'valued', '0', 'defined'], ['function', 'whose'], ['functions', 'function', 'f'], ['functions', 'function', 'ƒ', 'f', 'fn', 'x']]
TOP TOKENS [['myeloma', 'function', 'however', 'although'], ['myeloma'], ['myeloma'], ['myeloma'], ['myeloma'], ['myeloma'], ['myeloma'], ['myeloma', 'inmyeloma', 'developingmyeloma'], ['myeloma', 'people'], ['myeloma', 'fractures', 'cls', 'patients'], ['myeloma', 'multiple', 'simply'], ['myeloma', 'myelomas', 'multiple', 'group'], ['myeloma', 'myelo', 'word', 'kyphosis', 'dl', 'multiple'], ['myeloma', 'multiple'], ['myeloma', 'body', 'multiple', 'consisting'], ['myeloma', 'multiple'], ['myeloma', 'multiple'], ['myeloma', 'cell', 'multiple'], ['myeloma'], ['myeloma', 'cells', 'igm']]
TOP TOKENS [['2', 'time', '1', 'given', 'b', 'hence'], ['involve', 'deﬁnitions', 'deﬁnition', '253', 'signiﬁcant', '255', '254', 'b'], ['two', '2008', 'next', 'several', 'rearing', '8', '“', 'approximatively', 'one'], ['two', 'parts', 'unresolved', 'quite', 'like'], ['second', 'first', 'two', 'speech', 'thing'], ['context', 'involved', 'dr', 'weaves', 'masterfully', 'symbolism', 'delving', 'themes', 'goes', 'novel', 'example'], ['brings', 'compliments', 'well'], [], ['towards', '1', '72', '5'], ['patriarcal', "christianity's", 'ansestors', 'spirtual', 'guarentee', 'itsself', '433', 'immediate', 'belifs', '28', '9', 'full', '2', 'objects'], ['upon', 'likening', '6', 'feminist', 'toward', 'much', 'salon', 'similarly', 'little', 'lukewarm', 'grade', 'embodiment', 'rogerebert', "father's", 'time'], ['1', 'precedes'], ['100', 'favorite', 'evocative', 'gave', 'interesting', 'rated', 'one', 'went', 'sense', 'aspects', 'take', 'talk', '95'], ['a2', '3', '1', '2', '66'], ['three', 'relevant', "episode's", 'nuance', 'independent', 'also', 'creatively'], ['different', 'lively', 'inherent', 'indebted', "burton's", 'sensibilities', 'also', 'though', 'imaginative', "stylin'from", 'structure', 'thrills'], ['48', '—'], ['1', 'a2', '2', '6', '7', '4'], ['100', '2011', 'two', 'popularity', 'one', '5', '35', 'leading', 'long', 'release', 'significantly', 'plentiful'], ['touching']]
TOP TOKENS [['mimo', 'take', 'system'], ['mimo', 'take', 'system'], ['mimo', 'systems', 'transmit'], ['mimo', 'signal'], ['mimo', 'specifically', 'transceiver'], ['mimo', 'systems'], ['mimo', 'systems', 'system', 'channels'], ['mimo', 'mimoboosts', 'benefits', 'system', 'input', 'increasethe', 'future'], ['mimo', 'systems', 'system', 'however', 'antenna', 'introduction', 'communication', 'cls'], ['mimo', 'environments'], ['mimo'], ['mimo', 'frequency', 'equalization'], ['mimo', 'exploited', 'mitigated', 'multiplexing'], ['mimo', 'multiplexing', 'consists', 'mitigation', 'performance'], ['mimo', 'schemes', 'environments', 'system', 'degrades'], ['mimo', 'recently', 'e', '1975'], ['mimo', 'systems', 'multiuser', 'user', 'system', 'signal', 'communication', 'antenna'], ['mimo', 'uses', 'techniques', 'orthogonal'], ['mimo', 'system', 'systems', 'uses', 'decodes', 'vectors'], ['mimo', 'performance', 'systems']]
TOP TOKENS [['nightingale'], ['nightingale'], ['nightingale', 'moreover', '—', 'marketplace', 'desire', '”', 'thing', 'gold', 'next', 'sing', 'night'], ['nightingale', 'nightingales', "nightingale's", 'consequently', 'flight', 'outstanding', 'span||20-22.5', 'britain'], ['nightingale', 'mostly', 'know', 'opportunity', 'tail', 'legs'], ['nightingale', 'nightingales', "nightingale's", '1993', 'territory'], ['nightingale', 'although', 'apart'], ["nightingale's", 'nightingale', 'nightingales', 'range'], ["–'nightingale", 'nightingales', 'nightingale', 'simply', 'asia'], ['nightingale', 'nightingales', 'name'], ['nightingale', 'nightingales', 'eurasia'], ['nightingale', 'canada'], ['nightingale', 'nightingale–olympic', 'currently', 'musical'], ['nightingale', 'stadium', 'wanderers', '2014', 'wimbledon', 'robert'], ['nightingale', 'gardner', '1921–1989', '1979', 'journalist', '1954),british', '1959', '1819–1890', '1923–2006'], ['nightingale', "nightingale's", 'signed', 're-signed', 'quad', 'season', 'michigan', '2013', '2009', 'griffins', '2015'], ['nightingale', 'april', '1813', '1812', 'charleston', 'september', '21', '1810', 'marstrand'], ['nightingales', 'nightingale', 'operation', 'sep'], ['nightingale', '2015', '2016', 'rabbitohs', 'overall', 'newcastle', 'england', 'reported', 'stadium', 'hunter'], ['nightingale', "nightingale's", 'distributable', 'licenses', 'gplv2', 'project', 'cls', 'fm']]

Processing features:  92%|█████████▏| 90/98 [43:09<03:43, 27.94s/it]

getting sample prompt forgetting sample prompt for 24481
 24480
getting sample prompt for 24482
getting sample prompt for 24483
getting sample prompt for 24484
getting sample prompt for 24485
getting sample prompt for 24486
getting sample prompt for 24487
getting sample prompt for 24488
getting sample prompt for 24489
getting sample prompt for 24490
getting sample prompt for 24491
TOP TOKENS [['contrib', 'conda', 'option', 'use', 'run_with', 'packages', 'execute', 'talk', 'nsis=3', '2'], ['conduit', 'conduits', '“conduit'], ['h', 'conda', 'run', 'environment', 'prefix', 'conda_exe', 'name', 'commands', 'verbose', 'current', 'usage', 'sets', 'new', 'sources'], ['hero', 'conlan', 'con-lan', 'connley'], ['conda', 'conda¶', 'details', 'package', 'http://repo.continuum.io/pkgs', '1.6', 'searched', 'example'], ['process', 'conda', 'type', 'successful', 'use', 'ready', 'presented', 'right', 'activate', 'environment', 'output', 'using', 'install', 'create', 'suggests', 'configure', 'commands'], ['provided', 'conpack', 'allows', 'contour', 'conrec', 'package', 'map', 'contouring', 'less'], ['conjugate', 'conj', 'conjugating'], ['conjugate', 'conj', 'conjugating'], ['conjugate', 'seelesson', 'last', 'conjugated', 'examples', 'imperative'], ['1960s', 'conch', 'glasgow', 'conk', 'large'], ['conham'], ['conyngham', 'nature'], ['46–21', 'college', 'played'], ['jr'], ['south'], ['1877–1963', '39th', '1921–2001', 'unincorporated', 'connally', 'maximum-security', 'concerning', '1917–1993', 'judge', '1919–2006'], ['05', "conley's", 'came', '10', '04', 'selected', 'expatriate', '557', 'conley', 'signed', 'closest', '18', '5', 'suit', 'people'], ['1840s–1927', 'labrador', 'operated', '1882–unknown', 'program', 'fernandino'], []]
TOP TOKENS [['rupert', 'murdoch', 'glory,rupert', 'century'], ['rupert', 'scots', 'death', 'charles'], ['rupert', 'setback', 'england'], ['rupert', "rupert's", 'rupertsland', 'prince'], ['rupert', 'yet', 'great', 'surrender', 'talent', 'shipping', 'fairfax', 'army'], ['rupert', 'prince', '1667'], ['rupert', "rupert's", 'prince'], ['rupert', 'door', 'prince', 'estate', 'facade'], ["rupert's", 'rupert', 'ntly'], ['rupert', '02', '‘'], ['rupert', 'ruperto', 'ruperts'], ['rupert'], ['ruperts', "rupert's", 'rupert'], ['rupert', 'rupertswood'], ['rupert'], ['rupert', "rupert's", 'rupert/digby', 'rupert/seal', 'cambridge'], ['rupert', "rupert's", 'life', '2009', 'personal', '”'], ['rupert'], ['rupert', "rupert's", 'rupertikirtag', 'ruperts', 'rupertitag', 'rupertiwinkel', 'st', 'saint', 'events', 'abbess', 'settlements', 'robert'], ['rupert', "rupert's", 'name', '–', '1619', 'cls', 'vt']]
TOP TOKENS [['religion', 'ordered', 'civil', 'conscience', 'aboard', '“to', 'williams', 'sooner', 'england', "magistrate's", 'goods', 'men', 'also', 'requireth', 'ensuing', 'divulged', 'wrote', 'mr', 'whither', 'therefore', 'williams’s', 'hath', 'destruction', 'could', 'preach'], [], ['breslau', 'sectae', 'hadr', 'transl', 'universus', 'pletho', 'religionis', 'also', '1844', 'pref', 'fol', '1698', '1691'], ['un', 'www', 'org'], [], ['say', 'mr', 'kennedy'], ['info', 'org', 'bahai', 'hereinafter', 'http', '25', 'see', 'dated', '186'], ['ville', 'reef', 'convention', '1851'], ['though', 'secured', 'remained'], ['counterinsurgency', 'like'], ['org', 'com', 'www', '15questions'], ['1.96', 'tblstat.net'], [], ['303204614192293'], ['cambridge', 'cambridgeport', 'commission', '1967', 'press'], ['rumsfeld', 'curiæ', 'decision', 'et', 'center', 'court', 'rumsfeldu', 'v'], [], ['wagner'], [], []]
TOP TOKENS [['without'], ['without', 'withoute', 'withoutmiddle', 'absence'], ['without'], ['none', 'way', 'uses', 'see', 'us'], ['none', 'anyway', 'omission', 'use', 'given', 'empty', 'required', 'handling'], ['none'], ['without', 'matter', '“', 'already'], ['doesn’t', 'without', 'anything', 'none', '‘none’', 'class="org.camunda.bpm.engine.test.bpmn.event.intermediatenoneeventtest$myexecutionlistener', 'id="noneevent', 'intermediate'], ['without', 'fruitless', '“'], ['without', 'regard', 'words'], ['without'], ['without', 'murder'], ['without'], ['without'], [], ['without', 'absence', 'headless', 'born', 'backend-only', 'missing'], ['without'], ['absence', '“no'], ['nothing', 'anything'], ['without', 'nameless', 'lack', 'non', 'optional', 'means', 'lived', 'preposition', 'show', 'also']]
TOP TOKENS [['brunel', "brunel's"], ['brunel', "brunel's"], ['brunel'], ['brunel', "brunel's"], ['brunel', 'britain’'], ['brunel', 'brunel’s', 'britain’'], ['brunel', '2'], ['brunel'], ['brunel'], ['brunel', 'isambard'], ['brunel', "brunel's", 'ship', '2002', 'horol'], ['brunel', "brunel's", 'k'], ['brunel'], ['brunel', 'brunell'], ['brunel', 'brunell', 'isambard'], ['brunel', "brunel's", "father's"], ['brunel', 'isambard', 'achievement', 'publications'], ['brunel', "brunel's", 'isambard'], ["brunel's", 'brunel', 'isambard', "city's"], ['brunel', 'died', 'isambard', "grandfather's", 'also', 'serving', 'barry', 'hundred']]
TOP TOKENS [[], ['g', 'crop', 'misconceptions', 'disadvantages', 'get', 'lightly', 'much', 'please', 'situation'], ['eiermann', 'morning', 'travel', 'heard', 'generally', 'passed'], [], ['rendering', 'effect', 'resulted', '00287'], ['therefore', 'practice', 'g'], ['extra', 'whatever', 'might', 'may', 'years', 'leads', 'addition', 'snow', '1', 'also', 'degree', 'unless', 'usually', 'turkish'], ['duly', 'behind', 'soon', 'respectively'], ['machine', 'breaches', 'relating'], ['game', 'also'], ['therefore', 'ordinarily', 'caused', 'particular'], ['play', 'atm', 'forfeit', 'instead', 'full', 'left', 'actually', 'promptly'], ['amid', 'largely', 'though', 'brought', 'learned', 'incident', 'arrangement', '—', '1971', 'money', '7'], ['1', '–'], ['opted', 'also'], [], [], [], ['resulted'], ['game', 'practice']]
TOP TOKENS [[], [], [], [], ['served'], ['по', 'комитет'], [], ['2010phlb'], [], [], [], ['2013'], [], [], ['time'], [], [], [], [], ['took']]
TOP TOKENS [['left-handed', 'handed', 'right-handed', 'left-handedness', 'left'], ['handed', 'handedness', 'right', 'left-handed'], ['handed', 'handers', 'left', 'right', 'lefty'], ['left-handed', 'right-handed', 'left-handedness', 'handedness'], ['left-handed', 'right-handed', 'left-handedness', 'handedness'], ['handed', 'handedness', "a'lefty'being", 'right', "a'lefty'well", 'hand', 'ambidextrous'], ['left-handed', 'left-handedness', 'right-handed', '‘right-handed', 'lefty', 'they’re', 'you’re'], ['handed', 'handers', 'left', 'right', 'hand'], ['handed', 'handedness', 'lefties', 'left'], ['left-handedness', 'left-handed', 'right-handed', 'handedness', 'left-handers', 'hand', 'left-hand', 'right-handers'], ['handedness', 'handed', 'left', 'handers'], ['handedness', 'handed', 'handers', 'left', 'hand', 'right'], ['handed', 'handedness', 'right', 'handers', 'left'], ['handedness', 'handed', 'handers', 'hand'], ['handedness'], ['handed', 'handedness', "wild.'true'handedness", 'left', 'hand', "handers'creativity", 'right', 'handers'], ['handed', 'handedness', 'left'], ['handedness', 'handed', 'left', 'handers', 'hand', 'right'], ['handedness', 'handed', 'left'], ['handedness', 'right']]
TOP TOKENS [['cebu', 'talisay', 'liloan', 'sa', 'toledo', 'city', 'philippines', 'cebuano', '799', '91'], ['cebu', 'attraction', 'child'], ['cebu', 'explore', '15.06.15', 'city', '1565', 'philippines', 'relatively', 'manila'], ['cebu', 'talisay', 'toledo'], ['cebu', "cebu's", 'diego', 'city'], ['cebu', 'sugercane', 'toledo', 'cls', 'abaca', 'coconut', 'coastline', 'found', 'quezon', 'later', 'miguel', 'mactan', 'silver', 'de', 'jesus', '1521'], ['cebu', 'philippines', 'found', 'city', '1565', 'ildefonso', 'also', '’', 'de', 'warwicks'], ['cebu', 'see', 'philippines', 'people', 'nino', 'spanish'], ['cebu', "nation's", 'philippines', 'cosmetics', 'city', 'regio', 'abaca', 'candles', 'foreign', "island's"], ['cebu', 'reading', 'please', 'look', 'city', 'britannica.com', '32', 'philippines', '2,377,588', 'tell', 'us', 'km'], ['cebu', 'singapore', 'pigafetta', 'spanish', 'city', 'scorched', 'antonio', 'sibuy', 'philippines'], ['cebu', 'animal', 'city', 'strait'], ['cebu', 'liloan', 'city', 'philippines', "area's", 'compostela', "mmda's", 'consolacion', 'visayan', 'district', 'cordova'], ['cebu', 'liloan', 'toledo', 'talisay', 'industry', 'trade', 'philippines'], ['cebu', 'salazar', 'television', 'de', 'consolacion', 'philippines', '–', 'city', 'visayan', "catherine's", 'philippine', 'g', 'college', 'san'], ['cebu', 'philippines'], ['cebu', "cebu's", 'city', 'sa', 'salazar', 'philippines', 'spanish', 'arrived'], ['cebu', 'alleyways', 'philippines', 'filipino', 'city-related', 'thus', 'overcrowded'], ['cebu', "lumay's", 'cebuano', 'times', 'ate', 'city', 'sinibuayng', 'spaniards', 'several'], ['cebu', 'district', 'philippines', '1', 'references', '10', 'city']]
TOP TOKENS [['missionaries', "missionaries'depictions", 'assumed', 'missionary', 'read', 'missions', 'english', 'christian', 'evangelizing'], ['missionaries', 'missionary', 'mission', 'missions', 'becoming', 'work', '15', 'peoples'], ['missionaries', 'cls', 'need', 'missionary', '“', 'mission'], ['missionaries', 'missionary', 'prostitutes', 'forth', 'culture', 'came', 'set', 'accounts', 'oft', 'understanding', 'certain', '’'], ['missionaries', 'missionary', '“', 'mission', 'refers'], ['missionaries', 'missionary'], ['missionaries', 'missionary', 'english', 'missions', 'christian', 'field', 'throughout', 'church', 'medical', 'baptist'], ['missionaries', 'missionary', 'mission', 'church', 'missions', 'permissible', 'online'], ['missionary', 'missionaries', 'history', 'missions', 'arrived', 'spg', 'outstanding', 'individual', 'also', 'christians'], ['missionaries', 'today', 'world', 'christian'], ['missionaries', 'missionary', 'mormon', 'christ'], ['missionaries', 'missionary', 'missions', 'catholic', 'mission', 'missiology', 'taylor'], ['missionary', 'missionaries', 'mission', 'american'], ['missionaries', 'missionary', 'cls', 'christian'], ['missionary', 'missionaries', 'missions', '–'], ['missionaries'], ['missionary', 'american', 'missions', 'baptist'], ['missionaries', 'missionary', 'active', 'evangelization'], ['missionary', 'missionaries', '–', 'mission', 'american'], ['missionaries', 'missionary', 'missions', 'movement', 'mission', 'china', 'lived', 'life']]
TOP TOKENS [['good', 'frame'], ['samaritan', 'e', 'however', 'others', 'g'], ['reverse', 'like', 'without', 'however'], ['back', 'doors', 'fenced', 'word', 'verbally', 'wherefore', 'lightly', 'bums', 'unobtrusively', '—', 'airily', 'second', 'time', 'effect', "hiring.'so"], ['subtle'], ['refuse'], ['made'], ['”'], ['behaves', 'undefined', 'behavior', 'omitted', "discussion.'has", 'fully', 'noticeable', 'effect'], ["sam.'tis", 'men'], ['good', 'news', '–', 'later', 'undeniable'], [], ['re-sign', "team's"], ['also', 'good', 'helpful'], ['television'], ['pronouns', 'mariangela', 'mine', 'appear', 'g', 'typically', 'supported', 'also', 'e', 'commonly', 'thus'], ['days', 'recurring', "salem's", 'includes'], ['continued', 'times'], ['also', 'mcgoogan', 'seemed', 'letterboxes', 'even'], ['1979', 'series', 'show']]
TOP TOKENS [['pentecostalism'], ['pentecostalism', 'pentecostals', 'pentecostal'], ['pentecostals', 'pentecostalism', 'pentecostal'], ['pentecostals', 'pentecostal', 'pentecostalism', 'pre-pentecostal'], ['pentecostals', 'pentecostal', 'pentecostalism'], ['pentecostalism', 'pentecostal', 'pentecostals'], ['pentecostals', 'pentecostal', 'pentecostalism'], ['pentecostalism', 'pentecostal'], ['pentecostalism', 'pentecostal', 'cls', 'charismatic'], ['pentecostal', 'pentecostalism', 'forms'], ['pentecostals', 'pentecostal', 'spirit'], ['pentecostal'], ['pentecostal', 'pentecostalism', 'ministerial'], ['pentecostal', 'new', 'pentecost', 'alive', 'umea', 'god'], ['pentecostal', 'pentecostals'], ['pentecostalism', 'pentecostal'], ['pentecostal', 'gospel', 'heirs'], ['pentecostal', 'charismatic', 'one'], ['pentecostals', 'pentecostal', 'pentecostalism'], ['pentecostalism', 'pentecostal', 'christ']]

Processing features:  93%|█████████▎| 91/98 [43:39<03:21, 28.75s/it]

getting sample prompt forgetting sample prompt for 24493
 24492
getting sample prompt for 24494
getting sample prompt for 24495
getting sample prompt for 24496
getting sample prompt for 24497
getting sample prompt for 24498
getting sample prompt for 24499
getting sample prompt for 24500
getting sample prompt for 24501
getting sample prompt for 24502
getting sample prompt for 24503
TOP TOKENS [['pueblo', 'pueblos', 'people'], ['pueblos15', 'pueblo'], ['pueblo', 'pueblos', 'multistory'], ['pueblo', 'pueblos', '“pueblos,”'], ['pueblo'], ['pueblo'], ['pueblos', 'pueblo'], ['pueblo', 'pueblos', 'people'], ['pueblo', 'city', 'cls'], ['pueblo', 'puebloans', 'pueblos', 'puebloan'], ['pueblo', 'puebloan', 'pueblos'], ['pueblo', 'community', 'census-designated'], ['pueblo'], ['pueblo', 'history'], ['pueblo'], ['pueblo', 'non-profit'], ['pueblo', 'barriada', 'barrio'], ['pueblo', "pueblo's", 'antonito', 'blanca'], ['pueblo'], ['pueblo']]
TOP TOKENS [['tesol', 'tefl', 'versus'], ['tesol', 'tefl', 'http://www.tesolcourse.com', 'https://www.teflcourse.net/?cu=ytdescription'], ['tesol', 'tefl'], ['tesol', 'tefl', 'situations'], ['tesol', 'tefl', 'example'], ['tesol', 'tefl', 'efl', 'differences', 'learning'], ['tefl', 'tesol'], ['tesol', 'tefl', 'tesl', 'class'], ['tesol', 'tefl', 'familiar'], ['tesol', 'also', 'necessary', 'work', 'japan', 'email@example.com'], ['tesol', 'foreign'], ['persol'], ['kasol', 'climate', 'köppen-geiger', 'km', 'classifies'], ['tesol', 'kanavillil'], ['parasol', 'parasol-winged', 'paintings', 'homebuilt', 'sun', 'skullgirls', 'ruth'], ['efl', 'european', 'football', 'disambiguation', 'association'], ['mirasol', 'village', 'florida'], ["parasol's", 'parasol', 'absinthe', 'links'], ['tesol', "tesol's", 'also'], ['persol', 'ratti', 'meflecto', 'altagamma', 'drivers', 'company', 'sports', 'aviators']]
TOP TOKENS [['unk', 'much'], ['bones', 'performed', 'mother', 'helped', 'bit', 'moms', 'sinews', 'stitching', 'nonetheless', 'either'], ['sevens', 'seven-a-side'], ['eg', 'that’', 'this/that’', '‘hence’', '‘from', 'thus', 'ii', 'position', 'therefore', 'of’', '‘how’', 'eg.traditionally', 'also', 'comes', 'way’'], ['derivation', 'shape', 'shapes', 'queries', 'therefore'], ['diggs', 'congress', 'education', 'jr'], [], ['shape', 'form', 'surface', 'mold', 'rough', 'carve'], ['encroach', 'pedigree', 'american', 'orator', 'rights', 'flesh', 'etc', 'back', 'infringed', 'ecstatic', 'thus', 'warm', 'conveys'], ['text'], ['das', 'side', 'games', 'football', 'india', 'indian', 'goa', 'medalists', 'full', 'association', "men's", 'asian'], ['scotland', 'f.c', 'scottish', 'academicals', 'glasgow', 'ltd', 'ed', 'dykes', 'union'], ['das', 'india', 'football', 'i-league', 'under-23', '4-2', 'association', 'fullbacks', 'indian', '1–1', 'gokulam', "men's", '2011', 'abhishek', '2011–12', '2010–11', 'asian', '3–2', 'east'], ['belgian', 'belgium', "men's", 'people'], ['foundation', 'players'], ["men's", 'footballers', 'football', '1974–75', 'association', 'players', '1970–71', 'births', 'german'], [], ['tries', 'racing', 'ffr', 'france', 'union', 'profile'], ['sevens', 'commonwealth', 'tournaments', 'tournament', 'rugby', 'noel-smith', "women's", '2015-16', '2014-15'], ['tournament', 'may', 'straight', 'championships', "asashoryu's", '–', 'became']]
TOP TOKENS [['venture', 'capitalists'], ['ventureme', 'venture', 'venturemiddle', 'ventures', 'mountain'], ['venture', 'ventures', 'purpose', 'joint', 'might', 'order'], ['venture', 'capital'], ['venture', 'ventures', 'capital'], ['venture', 'ventures', 'cls'], ['venture', 'capitalists', 'capital', 'round'], ['venture', 'capital', 'correlate', 'allocate'], ['venture', 'ventures', 'capitalists', 'service', 'capital', 'march', 'may', 'parmar'], ['venture', 'capitalists', 'capital', 'capitalist'], ['venture'], ['venture', 'barbados'], ['venture'], ['venture', 'profile'], ['venture', 'markets'], ["venture's", 'venture', 'run', 'time', 'evening'], ['venture', 'hampshire', 'venture-class', 'l', 'uss', 'named', 'sp-616', 'operated'], ['venture', 'transport'], ['venture', 'named', 'became', 'pc-826/pyc-51', 'uss', 'march'], ['venture', 'technologies']]
TOP TOKENS [['chloride', '3', 'cls', '2'], ['chloride'], ['chloride'], ['chloride', 'blood'], ['chloride'], ['chloride', 'much', 'males', 'levels', 'cls', 'cooking'], ['chloride'], ['chloride', 'much', 'cooking', 'levels'], ['chloride', 'cells', 'signals', '1995', 'ed'], ['chloride', 'cls', '1', 'males', 'cooking', '9'], ['chloride', 'cl−', 'chloride-bicarbonate', '25-year-old'], ['chloride'], ['chloride', 'chlorides', 'biology', 'tonicity'], ['chloride', '2021', '2010', 'buses', 'name', 'followed', 'joining', '1999', '2000', 'uk', 'acquired', 'tudor', 'france'], ['chloride'], ['chloride', 'chlorides', 'also'], ['chloride', "chloride's", 'system', 'turquoise', 'ground', 'census-designated', 'seat', 'bought'], ['chloride', 'fecl2', 'fecl3', 'c6h5cl', 'hydrochloric', 'c6h4cl2', 'especially'], ['chloride', 'chlorides', 'acid', 'term', 'properties', 'cls', 'clo−', 'cl'], ['chloride']]
TOP TOKENS [[], ['primitives'], [], [], [], [], [], [], [], [], [], ['shantaram', 'kalamandir'], [], ['rajamouli', 'akkineni'], [], ['ennathe', 'narasimhan'], [], [], [], []]
TOP TOKENS [['gives', 'set', 'give', 'builds', 'keeps', 'equal', 'sessions', 'use', 'together', 'chapter', 'hand', 'gather'], ['referrals', 'b', 'e.g', 'systematic', 'initiative', 'building', 'attendance', 'alterable', 'families', '95-113'], ['drawing', 'analysis', 'also', 'rather', 'give', 'clarifications', 'completely', 'leaves', 'p', 'elaborations', 'extends', 'discussion', 'requires', 'however', 'giving', 'quietly', 'finally', 'conversation'], ['allows', 'therefore', 'little', 'concepts', '–', 'also', 'together', 'cases', 'simultaneously', 'bit', 'course', 'essentially', 'many', 'tempering', 'later', 'succinct', 'even'], ['way', 'get', 'things', 'small', 'even', 'toward', 'reliably', 'like', 'regard'], ["share's", "that's", 'things'], ['moving', 'day', 'even', 'confidence', 'finally', 'etc', 'think', 'minutes', 'able', 'give', 'work', 'week', 'attention'], ['activity', '”', 'something', 'practices', 'etc', 'cause', '’', '–', 'things', 'privately', 'like'], ['works', 'gives', 'additionally'], ['cls', 'facilitate', 'becomes', 'way', 'lectures', 'goal', 'broadens', 'making', 'foster', '’', 'however', 'understandings', 'providing', 'take', 'enlivens', 'may', 'step'], ['mark', 'conference', 'bearkats', 'tiaa'], ['conference', 'state', 'season'], ['conference', 'state', 'football', 'season'], ['conference', 'season', 'american'], [], ['state'], ['vols', '50', "team's", 'making', '–', 'well', 'victory', 'georgia', 'team', '31', 'game', 'record'], ['amount'], [], []]
TOP TOKENS [['vhdl', 'ghdl'], ['vhdl'], ['vhdl'], ['vhdl', 'vhd'], ['vhdl'], ['vhdl', 'ghdl'], ['vhdx'], ['vhdl', "testbench'and'vhdl", 'design'], ['vhdl', 'ghdl', 'many'], ['vhdl'], ['vhd', 'file'], ['haemorrhagic', 'rhd', 'traffic', 'rheumatic', 'right-hand', 'heart'], ['vhdl', 'ada'], ['vhdl'], ['vhds', 'vhd'], ['bhd', '2001'], ['vhdl', '1', "1'then", 'std', 'enables', '0', 'natural'], ['sshd'], ['vhd', 'vhds', 'drive', 'computer'], ['vhds', 'vhd', 'vhdx', 'disk', 'cls']]
TOP TOKENS [['styrofoam', 'polystyrene', 'styrol', 'years'], ['polystyrene', 'styrofoam'], ['polystyrene', 'en.wikipedia.org/wiki/polystyrene'], ['styrofoam', 'polystyrene', 'styrol', 'years'], ['polystyrene', 'styrofoam', 'extruded'], ['polystyrene', 'styrofoam'], ['polystyrene'], ['polystyrene', 'styrofoam'], ['polystyrene', 'circumstances'], ['polystyrene'], ['polystyrene'], ['polystyrene', 'styrofoam', 'standards', 'cutlery'], ['polystyrene'], ['polystyrene', 'styrofoam'], ['polystyrene'], ['polystyrene', 'styrofoam'], ['polystyrene', 'styrofoam'], ['polystyrene'], ['polystyrene', 'foams', 'cls', 'nanoparticles', 'however'], ['polystyrene', 'styrofoam']]
TOP TOKENS [['raft', 'aspects', 'logs'], ['rafts', 'raft', 'raftless', '“', 'using', 'model'], ['rafts', 'raft', 'reeds', 'rafting'], ['raft', 'rafts', 'although', 'use', 'find', 'using', 'options', 'however', 'need'], ['raft', 'rafts', 'use', 'using', 'sep'], ['rafts', 'raft', 'bed', 'need', 'procedures', 'phenomenon', 'models', 'print', 'almost'], ['raft', 'rafts', 'models', 'use'], ['raft', 'rafts', 'mean', 'log', 'definition'], ['raft', 'logs', 'buoyed', 'sea', 'floor'], ['raft', 'make', 'deformation'], ['raft', 'water', 'science', 'u.s'], ['rafting', 'raft'], ['rafting', 'rafter', 'rafters', 'deck', 'rafts', 'wyoming'], ['rafting', 'rafts', 'landfall', 'raft', 'engine', 'hull', 'barrels', 'rarely', 'water', 'cls', 'pontoons', 'blocks', 'reeds'], ['raft', 'columbia', 'also'], ['raft', 'rafting', 'rafter', 'disambiguation', 'rafters', 'née', 'also'], ['raft', 'cls', 'game', 'mode', '2022', '2x2', 'may', 'also', 'water'], ['raft', 'course'], ['raft', 'rafters', 'rafter', 'manufacture', 'eave', 'loads', 'recent', 'cls', 'advantage'], ['raft', 'france', 'didimdam', 'femmes', '24', 'zenland', '2006', 'born', 'congo', "l'arborigène", '1958', '2', 'april', 'music', 'discography']]
TOP TOKENS [['craniosynostosis', 'g'], ['craniosynostosis', 'apert', 'syndrome'], ['craniosynostosis', 'http://www.aans.org/patient%20information/conditions%20and%20treatments/craniosynostosis%20and%20craniofacial%20disorders.aspx', 'http://www.ninds.nih.gov/disorders/craniosynostosis/craniosynostosis.htm', 'craniofacial'], ['craniosynostosis', 'apert', 'syndrome'], ['craniosynostosis', 'anomalies', 'craniofacial', 'syndromic', 'syndrome'], ['craniosynostosis', 'anomalies', 'craniofacial', 'syndromic', 'syndrome'], ['craniosynostosis', 'anomalies', 'craniofacial', 'syndromic', 'syndrome'], ['craniosynostosis', 'acrocephalopolysyndactyly', 'list', 'stevenson'], ['craniosynostosis', 'craniosynostoses', 'altered'], ['craniosynostosis', 'accompany', 'untreated', 'craniofacial', 'heads'], ['craniosynostosis', 'g', '0-9'], ['craniosynostosis', "craniosynostosis'particular", 'cranium', 'cranio', 'brain', "word'scaphocephaly'is", 'scaphocephaly', 'sometimes'], ['craniosynostosis', 'acrocephalosyndactyly', 'syndromes', 'cranial', 'craniofacial', 'patients', 'also', 'almost', 'prognathism', 'though', 'syndactyly', 'soon', 'frontward', 'however', 'index', 'may', 'develop', 'characteristic', 'growth', 'sutures', 'due', 'show'], ['craniosynostosis', 'acrocephalosyndactyly', 'syndrome', 'syndactyly', 'near-identical', 'due', 'history'], ['craniosynostosis', 'synostosis'], ['craniosynostosis', 'however', 'despite', 'affected', 'development', 'appears', 'syndrome', 'made', "crouzon's", 'form', 'likely'], ['craniosynostosis', 'synostosis'], ['acrocephalosyndactyly', 'apert', 'acrocephalopolysyndactyly', 'called', 'syndrome', 'acs', '–'], ['craniosynostosis', 'acrocephalosyndactyly', 'cranioectodermal', 'syndactyly', 'anomalies', 'nonsyndromic', 'syndromic', 'related', 'cardiocranial'], ['craniosynostosis', 'cranium', 'cephalopolysyndactyly', 'cranio', 'plagiocephaly', 'syndrome', 'syn', 'scaphocephaly', 'oxycephaly', 'one']]
TOP TOKENS [['work', 'job', 'employment', 'jobs', 'employer', 'hired', 'working', '“', 'workplace', 'employee'], ['job', 'work', 'working', 'occupations'], ['job', 'work', 'employment', 'occupations', 'workplace', 'completing'], ['work', 'job', 'employment', 'occupations', 'working', 'workplace', 'wage', 'exerting'], ['job', 'work', 'occupations', 'workplace', 'employment', "one's"], ['employment', 'job', 'occupations', 'work', 'wage', 'workplace', 'employees'], ['job', 'work', 'employment', 'workplace', 'occupations', 'working', 'wage', 'even', 'employees'], ['job', 'work', 'working', 'occupations', 'employment', 'labor', 'conditions', 'employees', 'jobs'], ['job', 'work', 'employment', 'occupations', 'workplace', 'employees', 'wage', 'workers'], ['job', 'work', 'employment', 'occupations', 'workplace'], ['job', 'work', 'employer', 'working', 'pay', 'occupation', "one's", 'towards', 'satisfaction'], ['work', 'jobs', 'workplace', 'job', 'employed', 'employment', 'unemployment', 'workers', 'workfare', 'secure'], ['work', 'jobs', 'job', 'employers', 'wage', 'hiring', 'pay', 'employee', 'environment', 'labour', 'employees'], ['jobs', 'working', 'work', 'pay', 'job', 'g', 'time', 'benefits', 'employees', 'instrument', 'type', 'satisfaction', 'attitudes', 'values', '38', 'et'], ['employment', 'category:employment', 'job', 'work', 'working', 'category:working', 'work–life'], ['work', 'jobs', 'job', 'employee', 'employees', 'workplace'], ['employment', 'hire', 'labour', 'employees', 'working', 'employers', 'job', 'career', 'workers', 'work', 'workfare', 'labor', 'paid', 'centers', 'compensation', 'pay'], ['job', "job's", 'workers', 'jobs', 'work', "employees'jobs", 'worker', 'employees', 'encouraging', 'view'], ['job', 'working', 'workers', 'pay', 'occupations', 'work', "workers'emotion", 'circumstances', 'satisfaction', 'including', 'employees', 'experience', 'less', 'like'], ['work', 'job', 'jobs', 'workers', 'jobholders', 'employee', "workers'own"]]

Processing features:  94%|█████████▍| 92/98 [44:07<02:50, 28.48s/it]

getting sample prompt for 24504
getting sample prompt for 24505
getting sample prompt for 24506
getting sample prompt for 24507
getting sample prompt for 24508
getting sample prompt for 24509
getting sample prompt for 24510
getting sample prompt for 24511
getting sample prompt for 24512
getting sample prompt for 24513
getting sample prompt for 24514
getting sample prompt for 24515
TOP TOKENS [['impair', 'important', 'feel', 'better', 'symptoms', 'diagnosed', 'treated', 'either', 'tell', 'least', 'see'], ['impair', 'important', 'feel', 'better', 'symptoms', 'diagnosed', 'treated', 'either', 'tell', 'least', 'see'], ['go', 'away', 'cause', 'trying', 'symptoms', 'condition', 'problems', 'spent', 'unless', 'try', 'effort', 'improvement', 'worry', 'may', 'usually', 'affected'], ['silently', 'need', 'condition', 'says', 'person', 'matter', '‘'], ['goes', 'away', 'overcome', 'gone', 'go', 'nothing', 'must', 'fact', 'seems', 'want', 'ones'], ['away', 'go', 'conditions', 'see', 'may', 'depression', "can't", "there's", "who've", 'take', 'one', 'including', 'effective', 'symptom', 'symptoms'], ['overcome', 'stop', 'would', 'else', 'harder', 'take', 'important', 'deal', 'better', 'see', 'supposed', 'treatment', 'professional', 'rather', 'illness', 'may', "that's"], ['find', 'time', 'choice', 'proper', 'inconvenience', 'inability'], ['face', 'better', 'see', 'light', 'deal', 'confronting'], ['important', 'get', '“', 'overcome', 'help', 'cause', 'want', 'see', 'condition', 'seek', 'treatment', 'untreated', 'notice', 'silence', 'improvements', 'remain'], [], ['returning', 'demanding'], ['acquire', "them,'i", 'start', "ask'did", 'get'], ['uncover', 'proves', 'charged'], ['proofs', 'j'], ['complement'], ['condition', 'lift', 'lifted'], ['overcome'], [], ['lacking', 'may', 'rather', 'dares']]
TOP TOKENS [['krill', 'form', 'also'], ['krill'], ['krill'], ['krill', 'okiami'], ['krill'], ['krill', 'fed', 'system', '0', 'consumed'], ['krill'], ['krill', 'benefits', 'system', 'happens', 'oil'], ['krill', 'natural'], ['krill', 'sensibly', 'weight', 'pounds'], ['krill'], ['morrill', 'morril', "men's", 'u.s'], ['averill'], ['kyrill', 'kirill'], ['averill'], ['morrill', 'c'], ['krill'], ['kirill', 'kyrillos', 'kyrill', 'kiro', 'kirillos', 'gerasimov', 'russian'], ['averill', 'washington', '2018', 'year', 'seasons', '162', 'league', '1980'], ['krill', 'brinton', '6', 'consumption', 'robins']]
TOP TOKENS [['rottweilers', 'rottweiler', "rottweiler's"], ['rottweilers', 'rottweiler', 'dog', 'color', 'friendships', 'toes', 'side', 'onto'], ['rottweilers', 'rottweiler', 'tall', 'world'], ['rottweiler', 'rottweilers', 'though', 'endurance'], ['rottweiler', 'rottweilers', 'rottweil'], ['rottweiler', 'rottweilers', "rottweiler's"], ['rottweiler', 'rottweilers', 'overall', 'rottie', 'toes'], ['rottweiler', 'rottweilers'], ['rottweilers', 'rottweiler', 'rottweil.”', 'rottweiler’s', 'rottweil', 'gastrointestinal'], ['rottweilers', 'rottweiler', 'schutzhund', '1996', 'club'], ['rottweiler'], ['rottweilers', 'rottweiler', 'various'], ['rottweiler', "rottweiler's", 'rottweilers'], ['rottweilers', 'rottweiler', 'rottweil', 'also', 'could', 'world'], ["rottweiler's", 'rottweiler', 'rottweilers', 'deep'], ['rottweiler', "rottweiler's", 'rottweilers', 'h'], ['battweiler'], ['dettweiler'], ['ottweiler', 'saarländische'], ["abtweiler's", 'abtweiler', 'sankt', 'rehborn', 'much', 'hingelshof', '“', 'one', '”', 'along']]
TOP TOKENS [['reproduction', 'reproductions', 'reproduced', 'reproducing', 'plural'], ['reproduction', 'reproduced', 'reproducing', 'original', 'photographic'], ['reproduction', 'constitute', '“', 'within', '”', 'constituting', 'moreover', 'also', 'fall', 'definition'], ['reproduce', 'reproduction', 'undergo', 'reproduced', 'reproducibilityplay', 'c', 'exist'], ['reproduction'], ['reproduction'], ['reproduce[rē′prə', 'reproduced', 'reproduce', 'reproduces', 'reproduction', 'present', 'undergo', 'reproducing', 'give', 'generation'], ['reproduce', 'reproduction', 'survival'], ['reproduction', 'constitute', '3', 'establishing', 'use', 'occur', '“', '1', 'required', 'means', 'ii', 'embodiment', 'visible', 'hearing'], ['reproduction', 'reproduces', 'wellbeing', 'tends', 'biological', 'accumulation', 'capitalism'], ['reproduction', 'reproducibility', 'sound', 'reproductions'], ['reproduction', 'amazon.ca', 'dying'], ['reproduction', 'captured', 'color', 'reproduce', 'faithful', 'another'], ['reproduction', 'cultural', 'economic', 'capital', 'describes', 'social', 'education', 'remain', 'labor', 'systems', 'bearers', 'cls', 'opted'], ['reproduction', 'words', 'society', 'reproduce', 'cultural', 'operate', 'time', 'act', 'practices', 'generation', 'intergenerationally', 'experience'], ['reproduction', 'russell', 'biology', 'model', 'editors-in-chief', '2000'], ['reproduction', 'economic', 'socially', 'simple', 'contracted', 'occur', 'created', 'activity', 'economics', 'voluntary', 'refers'], ['reproduction', 'records', 'release', 'cls', 'overview', 'contains', 'kind', 'like', 'weeks'], ['reproduction', 'economic', 'reproduce', 'physical', 'commercial', 'society', 'remains', 'survival', 'attributable', 'make', 'expanded', 'absolute', 'living', 'capitalist', 'given', 'required', 'profit'], ['reproduction']]
TOP TOKENS [['first'], ['“first”', 'first'], ['first', 'firstfirst', 'firsts', 'second1', 'cls'], ['first', 'time'], ['first', 'first-aid', 'word', 'else'], ['first', 'first-aid', 'word', 'else'], ['first', 'word', 'earliest', 'firsthand', 'initial'], ['first', 'meaning', 'time'], ['first'], ['first', 'firsts', 'earliest', 'second'], ['first', 'firstgroup', 'light'], ['first'], ['first'], ['first', '1st'], ['first', '1st', 'time'], ['first', 'cinta', 'cls', 'krzysztof'], ['first'], ['first'], ['first'], ['first', 'ever', 'time']]
TOP TOKENS [['shirtwaist', 'triangle', 'march'], ['shirtwaists', 'shirtwaist', 'triangle', 'sweatshop', "ladies'garment", 'cls', 'fire', 'garment', 'whose', 'factory'], ['shirtwaist', 'shirtwaists', 'triangle', 'fire', 'blouse', 'seamstresses'], ['shirtwaist', 'shirtwaists', 'triangle', 'waists', 'blouses', 'factory'], ['http://www.academon.com/analytical-essay/triangle-shirtwaist-factory-fire-127885', 'shirtwaist', 'triangle'], ['shirtwaist'], ['shirtwaist', 'triangle'], ['shirtwaist', 'triangle', '210', '4', 'suffocation', 'unionization'], ['shirtwaist', 'triangle', 'fire'], ['shirtwaist', 'triangle'], ['shirtwaists', 'shirtwaist', 'triangle', 'stairwells', 'factory', '7', 'spur', 'fire', 'helped', "ladies'garment", '43', 'garment', 'sweatshop', 'northwest', 'waist', 'blouses', 'isaac', '3'], ['shirtwaist', 'triangle', 'factory', 'fire', 'york', 'garment', 'sweatshops', 'company', 'industry', 'textile', 'trapped', 'facilities', 'small', '—', 'factories'], ['shirtwaist', 'triangle', 'fire', 'factory'], ['shirtwaist', 'triangle', 'garment', 'fire', 'library', 'chernoff'], ['shirtwaist', 'triangle', 'shirtwaists', 'fire', 'factory', 'blouses'], ['shirtwaist'], ['shirtwaist', 'triangle', 'fire', 'factory', 'also', 'see', '1909', 'textile', 'labor', 'city', 'new', 'york'], ['shirtwaist', 'factory'], ['shirtwaist', 'triangle', 'factory', 'fire', 'company'], ['shirtwaist', 'triangle', 'factory', 'fire', 'march', 'arbitration']]
TOP TOKENS [['tyson', 'tyson’s', 'gvsu.edu/events/neil-degrasse-tyson-lecture-science-as-a-way', 'knowing,”', 'exploration', 'startalk', 'quandaries', 'hour-and-a-half'], ['tyson', 'resolution', '’', 'cls', 'read', 'cosmos', 'book', 'end', 'saturday', 'acceptable', 'obvious'], ['tyson', 'tysons', 'william', 'year', 'airport', '2010', 'years', '2000', '14,159'], ['tyson', 'w', '1980s', '28', '2014'], ['tyson', 'degrasse', 'scientific', 'neil', 'visualize', 'like', 'planetariums', 'tim', 'contributions', 'similar', 'idea', 'things', 'art', 'ferriss'], ['tyson', "tyson's", 'point', 'unequivocally', 'relationships', 'comes', 'stonewalling', "can't", 'silver', 'things', 'way', 'others'], ["tyson's", 'tyson', 'know', 'guide', 'especially', 'degrasse', '49.00', '9781538408018', '13.95'], ['tyson', 'fox', 'degrasse', 'network', 'neil', 'literacy', '”', '’'], ['tyson', 'clear', '’', 'award', 'sep', 'devery', 'hope', 'benson', 'schuster'], ["tyson's", 'tyson', 'corner', 'degrasse', 'shared', 'neil', 'video', 'others', "that's"], ['tyson', 'tysons', 't.y.s.o.n'], ['tyson', '2021', '2020', 'heard', '2008'], ['tyson'], ['tyson', 'business', '2019', 'intoxication'], ['tyson', '2018', 'year', '2017', '2014', 'earth', 'travis', 'also', 'made', '2016'], ["tyson's", 'tyson', '2010', 'magazine', '2012', 'berkeley', 'also', 'world', 'american', '2013'], ['tyson', '2013', '2014', '2010', '2005', '2011', '18', '1956', '1991', 'later', 'played', '2019'], ['tyson', 'tyson-maner', 'mcbryde-screws-tyson'], ['tyson'], ['tyson', '2015', 'maine', 'fleet', '2010', 'swift', 'bush', 'people', '18', 'sep', 'forces', '23', 'command']]
TOP TOKENS [['massage', 'massages', 'well-being'], ['massage', 'stress-related', 'fatigue', 'response', 'illnesses', 'circulation', 'function'], ['massage', 'strains', 'considering', 'situation', 'fibromyalgia', 'receive', 'general', 'mood', 'pain', 'workplace'], ['massage', 'elastic', 'exercise', 'areas', 'given', 'pain', 'congestion', 'tension', 'groups', 'lymphatic', 'injury'], ['massage', 'arms', 'joints', 'contact'], ['massages', 'massage', 'paced', 'body', 'performance'], ['massages', 'massage', 'paced', 'body', 'performance'], ['massage', 'massaged', 'lymphatic', 'techniques', 'craniosacral', 'calmness'], ['massage', 'considering', 'taking', 'massages', 'receiving', 'may', 'bonus', 'receive', 'women', 'avoid', 'perform', 'general'], ['massage', 'body'], ['massage', 'massages', 'medicine', 'tissues', 'cls', 'give', 'professionals', 'device'], ['massage', 'medical', 'based', 'century'], ['massage', 'receiving', 'sep', 'improved'], ['massage', 'infant', 'therapy', 'growth', 'fearlessness'], ['massage', "massage's", 'team', 'started', 'used', 'service'], ['massage', 'cover'], ['massage', 'massaged', 'increases', 'painful'], ['massage', 'massaged', 'benefit'], ['massage', 'biodynamic', 'muscles', 'stimulation', 'traditional', 'currently', 'sunburn'], ['massages', 'massage', 'erotic']]
TOP TOKENS [['ancient', 'modern', 'land', 'archaeology', '000', 'landscape', 'chichester', 'around', 'area', 'avalon', 'hedgerows', 'church', 'st', 'along', 'gargantuan', 'according', 'flooded', 'ago', 'since', 'medieval', 'dating', '5', '1275'], ['recent', '–', 'snopes', 'urbanlegends', 'asp', 'http', '↑', 'p', '10450', '12', 'different', 'org', 'tomar', 'worldheritagesite', '2007', 'html', '28', 'martin', 'pp', 'edition', 'friday13', 'retrieved', 'com', 'cnn'], ['ancient', '000', 'landscape', 'times', 'avalon', 'land', 'modern', 'ago', 'gargantuan', 'nudd', 'years', '5', 'along', 'since', 'given', 'situated', '1360s'], ['celtic', 'much', 'human', 'tor', 'looked', 'places', 'wetland', 'cls', 'bc', 'period', 'prehistory', 'thus', 'glastonbury', 'people', 'different', 'today', 'hollow'], ['another', 'pagan', "island's", 'however', 'time', 'shrouded', 'god', 'north', 'c', '“never', 'century', 'interpretation', 'recorded', 'seems', 'thought', 'island'], ['obviously', 'massachusettsnear', 'exact', 'however', 'eventually', 'cthulhu', 'older', 'said', 'together', "aquarist's", 'onward', 'cities', 'slow'], ['ancient', 'ancients', 'camelot', 'tor', 'area', 'glastonbury', 'cadarn', 'mists', '51', 'mccombie', 'church'], ['landscape', 'cathars', 'ugly', 'said', 'however', 'sure', 'crusade', 'head', 'make', '1244', '”', 'chilling', 'one', 'set', 'instead', 'parfait', 'basis'], ['landscape', 'cathars', 'ugly', 'said', 'however', 'sure', 'crusade', 'head', 'make', '1244', '”', 'chilling', 'one', 'set', 'instead', 'parfait', 'basis'], ['gwaelod', 'recent', 'moreover', 'fact', 'gives'], ['area', '26', 'takes', 'broadcasting', "that's", 'areas', '23', 'york', '1', 'aberdeen', 'local', 'later', 'dundee', 'order', 'conjunction', 'three', 'ireland', 'press', '12', '2', 'tv', '–', '25', '19', '31'], ['geologically', 'cls', "kingdom's", 'village', "cambridgeshire's"], ['rapids', 'saitama', 'kissimmee', 'kobe', 'cruickshank', 'via', 'florida'], ['phoenix', 'nottingham', 'manchester', 'rotterdam', 'align', 'nevada', 'saitama', 'arizona', '–', 'vegas'], ['a360', 'fire'], ['lake', 'minnesota', 'houston', 'align', 'texas'], ['liverpool', 'manchester', 'nottingham', 'align', 'koper', 'london', 'darmstadt', '21'], ['away', 'faded', "sauvage's", 'modern', 'popular', 'home', 'built', 'koos', 'legend', 'pit', 'century', 'one', '29', 'according', 'chateau', 'menace', 'henceforth'], ['avalon'], ['aldreth', 'community', 'west', 'gardens', 'rides', '2011', 'event', "cambridgeshire's", 'bibliography']]
TOP TOKENS [['certain', 'indeed', "let's"], ['certain', 'indeed', "let's"], ['shows', 'something', 'well', 'also', 'internet', 'demonstrates', 'roughly', 'communicates', 'due', 'nearly', 'nature', 'anyone'], ['one', 'former'], ['less', 'definitive', 'dividing', 'without', 'incompatible', 'carpenter’s', 'points', 'means', 'pinpointing', 'operating', 'together', 'end', 'fumbled', 'documents—not', 'poking'], ['defined'], ['extreme', 'either', 'unambiguous', 'one', 'example', 'sometimes', "example,'what", 'terms', 'speaking', "child?'an", 'alternatively'], ['differ', 'ngan’gikurunggurr', 'rather', 'single', 'audience', 'countered', 'verb’s', 'ngen’giwumirri', 'two', 'attention', 'areas', 'reader', 'contains', 'treats', 'draws'], ['differ', 'ngan’gikurunggurr', 'rather', 'single', 'audience', 'countered', 'verb’s', 'ngen’giwumirri', 'two', 'attention', 'areas', 'reader', 'contains', 'treats', 'draws'], ['opposite', 'cold', 'classification'], ['near'], ["foe's"], ['setting', 'first', 'stipulation', '0', 'becoming', 'lost', 'saw'], ['ignorantly', 'training', 'certain', '4', 'oblige'], ['000', '283', 'hold'], ['contrast', 'uwumbɔr', 'one', 'distinction', 'depends', 'e', 'regard', 'g', 'whereas'], ['stipulation', 'ended'], ['near', 'adjustment'], ['catapult'], ["wwe's", '617']]
TOP TOKENS [['zhang', "xuanzang's", 'yi', 'jiaoliang', 'qujing', 'xiyouji', 'xishan', 'zhong', 'hengyan', 'tailiu', 'xian', 'xiaoshuo'], ['zizhi', 'shaozhi', 'emperor', 'tongjian', 'shaanxi', 'song', "xi'an", 'yixi', 'lingshi', 'xia', 'yi', 'luoyang', 'qingni', 'yuanxing', 'xiaowu', 'yizhen'], ['yuanhuai', 'gongzong', "bin'ai", '氏', 'rui', 'xiaojing', 'clan', 'xuanyizhao', 'zhou', 'wenjingshun', 'lizong'], ['zizhi', 'pingzhangshi', 'tongjian', 'emperor', 'imperial', 'zhongshu', 'book', 'xizong', 'xiao', 'armies'], ['shaanxi', 'sansi', 'emperor', 'xiao', 'wuji', 'yu', 'shijiazhuang', 'taizong', 'yitong', 'jiali', "chang'an", "tujue's", "jiancheng's", 'xianyang'], ['emperor', 'dynasty', 'gaozu', 'wei', 'xiping', 'zhangye', 'xie', 'zhongxing', 'tang', 'shizheng', "ju's", 'wen', 'gansu', 'tongshi', 'river', 'guan', 'sui', 'dunhuang', 'fuhan'], ['emperor', 'xiaogong', 'shaanxi', "gaozu's", 'yuanji', 'gongshan', 'zhi', 'gaozu', 'erzhu', 'wei', 'gongshi', "chang'an"], ['wei', 'jia', 'emperor', 'daxi', 'tianshui', "daxi's", 'guanzhong', 'dui', 'unk', 'gaoliang', 'gansu'], ['emperor', 'zhongzong', 'gaozong', 'ruizong', 'wei', 'xuanzhen', 'hubei', 'luoyang'], ['tianshui', 'wei', 'commandery', 'province', 'longxi', 'yi', 'tazhong', 'mianzhu', 'weixing', 'yinping', 'wang', 'zhang', 'jiange', 'gansong', 'hua', 'ai', 'xin', 'jincheng', 'hanzhong'], ['yuankui', 'pingzhangshi', 'emperor', 'zai', 'handan', 'soldiers', 'wuzong', "congjian's", 'weibo', 'zhongshu', 'hongjing', 'imperial', 'xingtai'], ['yuankui', 'emperor', 'weibo', 'shanxi', 'huai', "zai's", 'wuzong', 'jiaozuo', 'zai', 'troops'], ['pingzhangshi', 'emperor', 'zhongshu', 'zhichou', 'xizong', 'fengxiang'], ['tongjian', 'zizhi', 'dynasties', 'dynasty', 'zhaopei', 'minhuai', 'emperor'], ['huaixi', 'pingzhangshi', 'emperor', 'zhongshu', "yue's", 'weibo', "huai'an", 'weiyue', 'handan'], ['dynasty', 'guangxi', 'jiangxi', 'xiaogong', "jingzhen's", 'jiaozhi', 'huaji', 'hubei', 'dong', 'song', "tang's", 'commandery', 'puhuan', 'jiujiang', 'jiangling'], ['emperor', 'xianzong', 'tongjian', "xi'an", 'dynasty', 'shunzong', 'guangqi', 'book', 'zizhi', 'huangchang'], ['song', 'qing', 'dynasty', 'province', 'dynasties', 'tang', 'jiaozuo', 'zhengzhou', 'guangwu', 'county', 'hebei', 'huai', 'government'], ['dynasty', 'tongjian', 'emperor', 'wuzong', 'jiedushi', 'shijiazhuang', 'handan', 'zizhi', 'book', 'xingtai', 'tang', 'yuankui', 'hongjing'], ['province', 'wei', 'chonghu', 'baidicheng', 'jing', 'tianying', 'xiao', 'jias', 'zhang']]
TOP TOKENS [['cliffsnotes', 'explore', 'study', 'in-depth', 'reinforce', 'www.cliffsnotes.com', 'themes', 'answers', 'devices', 'check', 'doesnt', 'examine'], ['study', 'captivate', 'cliffsnotes', 'continue', 'guides', 'playwright', 'guide', 'even', 'full', 'classic', 'understand', 'characters', 'character', 'king', 'familiar', '—', 'mother', 'books'], ['also', 'key', 'complete', 'points', 'themes', 'important', 'quotations', 'explains', 'every', 'characters', 'synopsises', 'provides', 'found', "thornton's", 'well.learn', 'another', 'amazon.com', 'overviews', 'analysis'], ['→beyond', '→quickwrite', '4', '→comprehension', 'false', '•', '→true', 'art', 'multiple', '1', '3', '→vocabulary', 'total', 'easy', 'synonyms', 'classroom', 'vs', 'also', 'class', 'following', 'however', 'every', 'needed', 'definitions', 'prep', "♥you're"], ['top-notch', 'groups', 'look', 'r-e-a-d', '20', 'chronologically', 'able'], ['acclaimed', '1', 'play', 'plot', 'hoopla', 'study', 'guide', "anonymous's", 'made', 'united'], ['summary', 'guide', 'immediately', 'detailed', 'analysis', 'dickens', 'bookrags', 'get', 'characters', 'carol', 'com', 'notes', 'essays'], ['study', 'cliffsnotes', "treasure—you'll", 'click', 'bellman', 'classic', 'summaries', 'f', 'also', 'one', 'homeric', 'arduous', 'characters', 'sets', 'higgins', 'kingdom', 'heritage', 'plots', 'graphically'], ['want', '30', 'one', 'plus'], ['inc', 'cliffsnotes', 'audio', 'www.cliffsnotes.com', 'literary', 'study', 'doesn’t', 'p)2011', '©2000', 'answers', 'sharer'], ["dean's", 'later', 'individually', 'baseball', "catlin's", 'also', 'swimming', '3', 'basketball', 'soccer', 'track', 'years', '90', '1st', 'taken', 'traditional', "women's", 'one', 'schools', 'championships', 'club', 'successful', "gabel's", 'included', 'three', 'skiing', 'around', '2010', 'national', 'oregon', '2002', 'country', 'league', '1992', '1994'], ['hares'], ['book', '–', 'troublesome'], ['study', 'links', 'squogres', 'coutts', 'french', 'best', 'among', 'patrick', 'stageplays'], ['4'], ['karelasyon', 'references', 'television'], ['kraabel'], ['1', '”'], ['melodifestivalen', 'finished', 'song', '28', "4's", 'bergendahl', 'time', 'peaked', 'first', 'nyhetsmorgon'], ['rannells', 'andrew', 'alex', 'references', 'murney', 'salonga', 'adored', 'kuhn', 'tituss', 'newell', 'composer', 'egan', 'demas', 'callaway', 'brightman', 'burgess', 'buckley', 'man']]

Processing features:  95%|█████████▍| 93/98 [44:35<02:21, 28.35s/it]

getting sample prompt forgetting sample prompt for 24517
getting sample prompt for 24518
 24516
getting sample prompt for 24519
getting sample prompt for 24520
getting sample prompt for 24521
getting sample prompt for 24522
getting sample prompt for 24523
getting sample prompt for 24524
getting sample prompt for 24525
getting sample prompt for 24526
getting sample prompt for 24527
TOP TOKENS [['valley', 'fever'], ['valley', 'fever', 'people', 'get'], ['valley', 'fever', 'coccidioidomycosis', 'people'], ['valley', 'fever', 'stricken', 'people', 'cls', 'certain', 'confined'], ['valley', 'valleyfever', 'fever', 'patients'], ['valley', 'fever', 'contract', 'america'], ['valley', 'fever', 'cls'], ['valley', 'fever'], ['valley', 'fever'], ['valley', 'fever', 'diagnosis', 'infected'], ['valley'], ['valley', 'uss', 'us', 'play'], ['valley', 'american'], ['valleyfield', 'disambiguation'], ['valley', 'costello', 'lodge', '3:56', 'planetarium'], ['valley', 'war'], ['valley', 'valle'], ['valley', 'garnavillo'], ['valley', 'cls', 'raspberries', 'sense', "lodge's", 'lizzy', "hill's", 'april', 'walt', 'cobra', 'lodge', 'guitar', 'thin', 'phil', 'skinnee'], ['valley']]
TOP TOKENS [['botox', 'underarm', 'dystonia', 'contractions', 'arms'], ['botox', 'frontalis', 'quantities', 'tiny', '’'], ['botox', 'fda'], ['botox', 'system', 'thankfully'], ['botox', 'dilute', 'amounts', 'would', 'could'], ['botox'], ['botox'], ['botox'], ['botox', 'neuralgia', 'studies', 'treatment', 'patients'], ['botox', 'concerns', 'nerves', 'without', 'oab', 'may', 'areas', 'different'], ['tbox', 'abox', 'chicago'], ['lenox', 'iowa', 'town', 'community'], ['madox-01', 'madox'], ['lenox'], ['bbox1', 'bbox', 'dioxygenase'], ['peroxisomal', 'acox', 'acox3', 'acox1'], ['lenox', 'authorized'], ['phox', 'phox2b', 's)-ipr-phox'], ['roox', 'small-scale'], ['beenox', '2022', 'hero', "activision's", 'projects', 'porting', '360', '2003', 'announced', 'activision', '2015', 'dreamworks', 'canada']]
TOP TOKENS [['thebe', 'thebes', 'thēˈbē'], ['thebes'], ['thebes'], ['qubes', 'qube', 'way'], ['microbes', 'nest', 'nutrients'], ['qubes', 'relation', 'tcb'], ['qubes', 'difficult', 'contrast', 'makes'], ['qubes', 'stub', 'yes', 'systems', 'set', 'initial', 'tcb'], ['microbes', 'mean', 'soil', 'bottom', 'microbial'], ['thebes', 'theban', 'wars', 'greece', 'millennia', 'kadmos', 'period', 'cls', 'ground', 'also'], ['qube', 'qubes', 'kube', 'pocketqube', 'qubetv'], ['cobe', 'background'], ['rabé', 'subcarpathian', 'oiseau', 'rabe', 'cruciferous', 'bieszczady'], ['kube', 'qube', '104.9', 'kube-mcdowell', 'kube-fm', '93.3'], ['aubé', 'aube', 'disambiguation'], ["l'abbé", 'abbe', 'dispersion', 'french', 'pellin–broca'], ['hobe', 'house-solheim'], ['microbe', 'microscopic'], ['japanese', 'kabe', 'author', 'kabe-cd'], ['alternate', 'thebe']]
TOP TOKENS [['civil', 'engineering', 'engineer', 'engineers'], ['civil', 'engineering', 'engineer', 'b', 'engineers'], ['civil', 'engineer', 'engineering', 'engineers'], ['civil', 'engineering', 'engineers', 'engineer', 'undertaking'], ['civil', 'engineer', 'engineering', 'engineers'], ['civil', 'engineering', 'engineers', 'requirements', 'engineer', 'engineerings', 'education', 'licensure'], ['civil', 'engineers', 'engineer', 'engineering', 'r'], ['civil', 'engineering', 'engineer'], ['civil', 'engineering'], ['civil', 'engineering', 'engineers', 'work'], ['civil', 'engineering', 'engineer', 'engineers', 'e'], ['civil', 'engineering', 'computations', 'several', 'railways'], ['civil', 'engineer', 'multiple', 'engineering', 'engineers', "engineer's", 'neglected'], ['civil', 'engineering', '1988', 'engineers', '2004'], ['civil', 'engineering', 'engineers', 'depends'], ['civil'], ['civil', 'engineering', 'engineers', 'engineer', 'specialized', 'management', 'practice', 'manner', '59', 'profession'], ['civil', 'engineering', 'practice', 'profession', 'graduate', 'programs'], ['civil', 'engineering', 'engineers'], ['civil', 'engineering']]
TOP TOKENS [['mayo', 'need', 'experienced', 'people', 'minnesota', 'clinic', '8'], ['mayo', 'mayoclinic'], ['mayo', 'james'], ['mayo', 'non-mayo', 'mayoclinic.com', 'research', 'sensitivity'], ['mayo', 'weight', 'lifetime', 'life', 'u.s', 'experts'], ['mayo', 'mayoclinic', 'patients'], ['mayo', 'mayoclinic'], ['mayo', 'mayoclinic'], ['mayo', 'mayoclinic.org', 'mission', 'research'], ['mayo', 'service', 'need', 'cases', 'clinic', 'minnesota', 'people', 'experienced', 'life', 'education'], ['mayo'], ['mayo', 'lamar', '1978'], ['mayo'], ['mayo', 'moore-mayo', 'taylor-mayo', 'helton-mayo'], ['mayo', 'cagney', 'ayres', 'sailor', 'hair', '1960', 'sadie', 'film', 'hollywood', 'svengali', 'james', 'tailor'], ['mayo', 'metrobank', 'philadelphia'], ['mayo', 'links'], ['mayo', 'vickers', 'life', '1993', 'juveniles', 'derry', 'personal', 'arms', 'colorado', 'pierce', 'julie', 'death', 'anne', 'polly', '1980', 'barrons', 'role', 'flaxy', 'carla', 'publishers', 'benson'], ['mayo'], ['mayo', '2015', '2012', '2013', '6', 'debut', 'guys', 'returned', 'bulls', '19']]
TOP TOKENS [['sacred', 'word', 'finding', 'definition', 'religious', 'precious', 'poetry'], ['sacred', 'forests', '»', 'word', '«'], ['sacred', 'nothing', 'sagradojurar', 'translation'], ['sacred', '‘', 'religious'], ['sacred'], ['sacred', '“', '”', 'space'], ['sacred', 'sacredness', '“', '”', 'domain', 'cls', 'holy'], ['sacred', 'term', 'designated', 'known', '“', 'pure', 'comes'], ['sacred', "by'sacred", 'secularization', 'secularizationkeep', 'places'], ['sacred', 'holy', 'major', 'regarded'], ['sacred'], ['sacred', '595–585'], ['sacred'], ['sacred'], ['sacred'], ['sacred', 'sacredness', 'word', 'holy', 'terms', 'cls', 'describes', 'descends', 'something'], ['sacred', 'links', 'discogs.com'], ['sacred', 'banalinga'], ['sacred', 'also'], ['sacred', '1505–1510']]
TOP TOKENS [['you’ve', 'used', 'learn', 'markdown', 'converting', 'systems', 'alternate', 'use', 'editors'], ['converts', 'cannot', 'next', 'one', 'alternative', 'two', 'cls', 'certain', 'use', 'bold', 'implementation', 'flavored', 'features', 'using', 'markdown', 'prepending'], ['cls', 'markdown', 'developed', 'well', '1', 'use', 'get', 'text', 'instead', 'understand', 'new', 'create'], ['right', 'plugin', 'love', 'markdown', 'get', 'convert', 'write', 'choose'], ['learn', 'markdown', 'innovative', 'flavor', 'cls', 'otherwise', 'use', 'previous', 'original', 'line', 'even', 'learned', 'adopted', 'experience', '2004', 'format', 'still', 'kinds', 'however', 'either', 'note', 'came', 'leading', 'many', 'g'], ['realizing', 'knowledge', 'latter', '4', 'created', '2004', 'even', 'without', 'version', 'since', 'markdown', 'create', '3', '1', 'write', 'wanted', 'also'], ['markdown', 'fear', 'since', 'flavor', 'converts', 'ツ', 'else', 'main', 'brought', 'never', 'reason'], ['aware', 'learn', 'plunge', 'felt', 'markdown', 'long', 'extremely', 'using', 'themes', 'get', 'headings', 'robertnyman', 'com', 'also', 'however'], ['aware', 'learn', 'plunge', 'felt', 'markdown', 'long', 'extremely', 'using', 'themes', 'get', 'headings', 'robertnyman', 'com', 'also', 'however'], ['heard', 'learning', 'learn', 'markdown', 'yet', 'you’ve', 'using', 'http://main.makeuseoflimited.netdna-cdn.com/wp-content/uploads/2006/07/muosquares.png', 'chance', 'recently', 'editors', 'markable', 'explains', 'guide', 'taste', 'easily', 'use', 'link', 'following'], ['different', 'release', 'later', 'tastes', '2009', "album's", 'press', '27', 'coincide', 'date', 'vocalist', 'albums', 'three', 'exclusively', 'also', "ryan's", 'one', 'released', 'well', 'though', 'blog', "record's"], ['appeared', 'well', 'created', 'earlier', 'markdown', 'long', 'c', 'version', 'rise', 'implementations', 'initial', 'many', 'key', 'pre', 'existing', 'cls', 'formatting', 'original', 'instructions', 'unlike', 'causing', 'markup', '2014', 'like', 'rapidly', 'questions', 'referred', 'history', 'also'], ['leigh', 'hamlet', 'pemberton', 'hereditary', 'leigh-pemberton', 'baron', 'somerset', 'kingsdown', 'fort', 'kent', 'people', 'also', 'england', 'peer', 'kansas'], ['october', 'already', '2017', 'experimental', 'announced', 'september', 'concepts', 'discover', 'systems', 'cultist', 'anticipated', '31', 'date', 'something', 'release', 'january', '22', 'user', 'fit', 'writing', 'provided', 'best', 'understand', 'familiar', 'deep', 'make'], ['keough', 'keough/haze', 'bishop', 'film', 'robby', 'disambiguation', 'school', 'characters', 'mckeogh', 'keoghan'], ['franchises', 'brand', 'group', 'embracer', 'franchise', 'new', 'wild', 'gone', 'owner', 'later', 'studios', 'name', 'published', 'arts', 'developed', "america's", 'originally', 'platforms'], ['objections', 'brands', 'production', 'tradition', 'two', 'created', 'stablemate', 'later', 'introduced', 'luxury', 'early', 'conventional', 'themes', 'toyota', 'lincoln', 'competitors', 'another', '2014', 'ls', 'series', 'used', 'mark', '2000s', 'division', 'lincolns', 'lineups', '–', '2002'], ['developed', 'released', 'franchises', 'series', 'content', 'developers', 'resulted', 'conquest', 'license', 'golden', 'allowed', 'introduced'], ['developed', 'entered', 'dialogue', 'crimean', 'derivatives', 'may', 'many', 'december', 'alpha', '4', 'khanate', 'made', 'franchise', 'protagonists', 'released', '11', 'bannerlord', '30', 'character', 'spawned', 'official', 'including', 'creation', 'march', 'resulted', 'battles', 'expansion', 'sprung', 'relationship'], ['webuild', 'clough', 'farmer', 'brisbane', 'busway', '2004', 'island', 'oilfield', 'venture', 'development', '2022', 'baulderstone', 'mechanical', 'acquired']]
TOP TOKENS [['chromatic', 'everything', 'wavelengths', 'else', 'longitudinal', 'different', 'along', 'aberration', 'points', 'result', 'example', 'longer', 'color'], ['chromatic', 'chromaticism', 'note', 'notes', 'bit', '’'], ['chromatic', 'years', 'earlier', 'perspective', 'nuances', 'like', 'fix', 'anything', 'pictures'], ['chromatic', 'areas', '“colourful”', '“chromatic”', '“color”', '“chromatic', '“chromatic”[change', 'key', 'i.e'], ['chromatic', 'bright', '6', 'aberration', 'experience', 'superior', 'lower', 'sometimes', 'optical', 'exacerbated', 'towards'], ['chromatic', '’', 'bit', 'minor', 'n', 'may', 'cannot', 'image', 'matter', 'wiki', 'aberration'], ['chromatic', 'harmonically', 'chroma', 'including', 'tempers', 'series', 'note', 'bottom', 'harmonic', 'notes', 'consisting'], ['chromatic', 'chromatics', 'chromaticism', 'chromatically', 'quite', 'post', 'big', 'straight', 'frankly', '’', 'add', 'people', 'included'], ['chromatic', 'place', 'significant', '’', 'certain', 'aberration', 'avoid', '”'], ['chromatic', "function'chromatically", 'chromatically', 'major', 'chromaticism', 'way', 'b', 'also'], ['chromatic', 'button', 'dispersion', 'american', 'systems', 'chromaticity', 'tempered', 'number', 'vision', 'chromatica', 'purity', 'strong', 'chromatics', 'intensity', 'chromatically', 'use', 'differing', 'byzantine', 'tetrachord', 'diatonic', 'altered', 'interval'], ['chromatic', 'chromaticism', 'another', 'bastion', 'available', 'tone', 'particularly', 'scale', 'break', 'elaborations', '1920', 'minor', 'half', 'part', 'key', 'notes', 'within', 'terms'], ['chromatic', 'lines', 'chromatically', 'contains', '–', 'chromaticism', 'b', 'entirely', 'similar', 'g', 'similarly'], ['simply', 'chromaticity', '–', 'keyboard', 'august'], ['chromatica', 'sized', 'postcards', 'content', '28', 'footage', 'pink', 'copies', 'frame', 'digital', 'cover', 'dark', '40', 'colored', '12', 'additional'], ['chromatic', 'beraldi', 'late', 'chromaticism', 'additional', 'piatanesi', 'considered', 'chromatically', 'unusual', 'included', 'may', 'system', 'two', 'among', 'built', 'stunt', 'require'], ['chromatic', 'chromostereopsis', 'converting', 'aberration', 'correct'], ['chromaticism', 'chromatic', 'links', 'external', 'modulation', '—'], ['chromatic', 'western', 'always', 'unambiguously', 'lo', 'capable', 'also', 'microtones'], ['chromatic', 'perhaps', 'william', 'b', "diatonic's", 'style', 'key', 'note', 'hole', 'entire', 'redirect']]
TOP TOKENS [['mahjong', 'playing', 'game', 'invented', 'tiles'], ['playing', 'mahjong', 'game'], ['mahjong', 'game', 'playing', 'based', 'played', 'play'], ['mahjong', 'game', 'games', 'play', 'playing', 'played'], ['indian', 'played', 'games', 'traditional', 'mushti', 'mallakhamb', 'langdi', 'vajra'], ['addition', 'ball', 'games', 'played', 'fingers'], ['playing', 'egypt', 'played', 'first', 'play', 'many', 'games', 'handball', 'war', 'hockey', 'relaxed', 'love'], ['playing', 'egypt', 'played', 'first', 'play', 'many', 'games', 'handball', 'war', 'hockey', 'relaxed', 'love'], ['playing', 'game', 'tiles', "1920's"], ['playing', 'play', 'mahjong', 'game'], ['many', 'games', 'playing', 'bagh-chal', 'game', 'marbles', 'kho-kho', 'played'], ['mesoamerican', 'played', 'games', 'ballgame', 'would'], ['game', 'played', 'mahjong', 'games', 'old', 'boards', 'native', 'pottery', 'also'], ['mahjong', 'game', 'four-player', 'tile-matching', 'origin', 'chinese', 'solitaire', 'played'], ['mahjong', 'played', 'gaming', 'com', 'games', 'playing', 'game'], ['games', 'game', 'played'], ['game', 'games', 'plastic', 'deutsche', 'vaterlandischer', 'pomerania', 'deutschen', 'spiels', 'east', 'states', 'century', 'spielhandbuch', 'voggenreiter', 'mancala', 'die'], ['pieces', 'games', 'played', 'game', 'piece', "opponent's", 'point', 'play', "other's", 'set', 'board'], ['game', 'played', 'outdoor', 'playing', 'entirely', 'one', 'initially'], ['played', 'game', 'pieces', '“', 'squares', 'traditional', 'hole', 'pegs', 'board', 'daldøs', '’', 'generally']]
TOP TOKENS [["nasa's", 'greatly', 'also', 'numerous', 'enigmatic', 'including', 'vegetation', 'particularly', 'engender'], ['accomplished'], ['reaps', '’', 'century', 'provides', 'home', 'spans', 'continues', 'extending'], ['come', 'galaxy', 'filled', 'kepler', 'beyond', 'system', 'enhancing', 'success', 'one', 'far', 'well', 'writ', 'planet', 'billions'], ['many', "nasa's", 'gone', 'hand', '0', 'nasa', 'greater', 'also', 'although', 'program', 'eyewear', 'delivered', 'even', 'meanwhile'], ['may', 'come', 'full', 'nasa’s', 'decades', 'also', 'thousands', 'crewmembers', 'space—have', 'countless', 'backyard', 'ever', 'discoveries', 'space', 'economy', 'making', 'led', 'think', 'strengthen', 'made', 'enrich', 'beyond', 'great', 'helped', 'achievement', 'humankind'], ['grew', 'apollo', '2000', 'flagships', 'meanwhile', '1997', 'conducted', 'history', 'also'], ['accomplished', '’', 'feats', 'incredible', 'venturing', 'nearly', 'earth', 'whether', 'know', 'however', 'way', 'frequently', 'mission', 'found', 'since', 'later', '–', 'products', 'safer', 'every', 'operates', 'research', 'throughout'], ['importantly', 'evidently', 'exponentially', 'examples', 'would', 'high', 'even', 'throughout', 'batteries', 'helped', 'due', 'imagery', 'nasa', 'curiosity'], ['accomplishing', 'decades', 'meanwhile', 'activities', 'delivered', 'many', 'also', 'nasa', 'hand', 'shortly', 'even', 'bolder', 'greater', 'gone', 'though', 'eyeglasses', 'faring', 'possible', 'program', '’'], ['among', "nasa's", 'powerful', 'probes', '15', '1999', 'observatories', 'sun', 'cripped', 'supernova', 'nasa', 'large', 'provided', 'ultraviolet', 'telescope', '1960s', 'space', "telescope's", '2000s', 'quasars', '1991', 'program'], ['headquarters', 'daughter', 'declines'], ['long', 'substantial', 'nebula', 'also'], ['led', 'since', 'planetary', "nasa's", 'would', "naca's", 'despite', 'provides', 'next', 'aviation', 'grew', 'ushered', 'force', 'better', 'recognized', 'army', 'far', 'observatories', 'predecessors', 'ii', 'telescope'], ['outstanding'], ['multiple', 'remains', 'remained', 'capability', 'among', 'today', 'includes', 'several', 'vehicular', 'thanks', "center's", 'collection', '1959', 'eosdis', 'however', 'well', 'assumed', 'soon', 'called', 'prompted'], ['greatly', 'also', 'increasing', '1977', 'nasa', 'spacecraft', '1960s', 'became', 'planets', 'provided'], ['scope', 'number', 'amplified', 'cases', 'growing', 'infrastructures', 'cover', 'capabilities', 'navigating', 'energy', 'operating', 'capable'], [], ['triumphs', 'years', "nasa's", 'space', 'nasa', 'early', 'since', 'history', 'disasters', 'looks']]
TOP TOKENS [['trail', 'hiking', 'backpacking', 'hike', 'one', 'gear', 'bag', 'health', 'depositing', 'place'], ['wilderness', 'hiking', 'bandaid'], ['backcountry', 'wilderness', 'done', 'medical'], ['backcountry', 'hiking', 'hikes', 'areas', 'hikers', 'backpacking', 'along', 'hike'], ['hikers', 'hiking', 'backpackers', 'avoid', 'hygiene'], ['backcountry', 'wearing', 'terrain', 'need', 'encounter'], ['find', 'wilderness', 'makeshift', 'preparing'], ['backcountry', 'wilderness', 'medicine', 'leading', 'medical', 'hiking'], ['wilderness', 'hiking', 'wielding', 'lint', 'preferably', 'one', 'survival', 'fashioning'], ['injuries', 'need', 'hiking', 'hydrated', 'wear', 'gear'], ['soles', 'boots', 'snowshoes', 'rugged', 'field', 'repellent', 'hiking', 'tool', 'caulk', 'useful', 'monocular', 'yet', 'watch', 'cover', 'kevlar', 'trail', 'hiker', 'anti', 'needles', 'hunting', 'crampons', 'read', 'threaded', 'slip', 'compass', 'hikers', 'used', 'light', 'ability', 'slingshot', 'appropriate', 'help', 'using', 'fasteners', 'journaling', 'safety'], ['wilderness', 'hiking', 'avoided', 'proper', 'boots', 'recreational', 'backpacking', 'pack', 'preventive'], ['wilderness', 'weather', 'expeditions', 'medical', 'neurologic', 'wound', 'injuries', 'medicine', 'neurotoxic', 'appendicitis', 'pulmonary', 'rocks', 'hunting', 'anaphylaxis', 'peritonitis', 'subdural', 'hypothermia', 'mountain', 'forest', 'venomous'], ['dehydrated', 'hiking', 'carry', 'hikers', 'preventing', 'used', 'sponges', 'techniques', 'rocks', 'knowing', 'pantyhose', 'bandana', 'water', 'usually', 'contain', 'tarpaulins', 'tied', 'purifies', 'geographical', '–', 'need', 'drinkable'], ['wilderness', 'medicine', 'medical', 'field', 'aid', 'environmental', 'mountain', 'first'], ['wilderness', 'guides', 'remote', 'neurologic', 'neurotoxic', 'outdoor', 'sunstroke', 'medical', 'injuries', 'hematoma', 'expeditions', 'pneumothorax', 'weather', 'pulmonary', 'arthropod', 'skills', 'cls', 'injury', 'bites', 'explorers'], ['gloves', 'tape', 'socks', 'rehydration', 'pocket', 'used', 'flashlight', 'compass', 'binocular', 'sweetener', "hiker's", 'lubed', 'repellent', 'bandana', 'knife', 'sunscreen', 'monocular', 'scarf', 'earplugs', 'hikes', 'signalling', 'altimeter', 'sewing', 'file', 'navigation', 'hiking', 'sharpener'], ['backcountry', 'wilderness', 'knowing', 'adventurer', 'carrying', 'invaluable', 'amount', 'making', 'location', 'liters', 'incapacitate', 'person', 'whistles', 'rocks', 'especially', 'dehydration', 'lost', 'weather', 'evaporates', 'may', 'conditions', 'water', 'compass', 'pinpoint', 'trail', 'trees', 'hikers', 'help', 'revealing', "traveler's"], ['able', 'gloves', 'medicinal', 'area', 'terrain', 'medicines', 'used', 'clothing', 'headlamp', 'aid', 'information', 'gps', 'positioning', 'protection', 'medical', 'feet', 'protects', 'pair', 'entrenching', 'avoid', 'sharp', 'knife', 'balm', 'sun', 'sawing', 'trowel', 'sleeved', 'nitrile', 'preferably'], ['backcountry', 'wilderness', 'medicine', 'environments', 'medical', 'paramedic', 'practitioner', 'outdoor', 'function', 'setting', 'needed', 'physician', 'gear']]

Processing features:  96%|█████████▌| 94/98 [45:03<01:52, 28.24s/it]

getting sample prompt forgetting sample prompt for 24529
 24528
getting sample prompt for 24530
getting sample prompt for 24531
getting sample prompt for 24532
getting sample prompt for 24533
getting sample prompt for 24534
getting sample prompt for 24535
getting sample prompt for 24536
getting sample prompt for 24537
getting sample prompt for 24538
getting sample prompt for 24539
TOP TOKENS [['swage', 'swaged', 'ammunition', 'manual', 'swaging', 'desired', 'room', 'engage', 'contract', 'fittings', 'common', 'right', 'exact', 'alone', 'size', 'used', 'aware', 'greatly', 'major', 'conform'], ['snug', 'incorrect', 'unfamiliar', 'longer', 'sleep', 'old', 'much', 'likely', 'swaddle', 'recreates', 'along', 'swaddling', 'stop', 'century', 'cause', 'swaddled', 'correctly', 'straight', 'reason', 'side', '3'], ['phases', 'june', 'release', 'swiffy', 'flash/flex', 'developers'], ['swales', 'swelter', 'swaling', 'swaleperhaps', 'akin', 'swaled', 'swel', 'especially', 'troughlike', 'sweal', 'usually'], ['doesn’t', 'place', 'mother’s', 'swaddled', 'safety', 'increases', 'always', 'swaddling'], ['etc'], ['etc'], ['swag', 'swaged', 'swage', 'free', 'nearly', 'pirates', 'swaging', '40', 'size', 'heat', 'depending', 'non', 'easily', 'exact', 'die', 'similar', 'normally', 'draped', 'powerful', '10'], ['swag', 'swaged', 'swage', 'free', 'nearly', 'pirates', 'swaging', '40', 'size', 'heat', 'depending', 'non', 'easily', 'exact', 'die', 'similar', 'normally', 'draped', 'powerful', '10'], ['swaged', 'alternative', 'swage', '0', '43mm', 'swages', 'swaging', '30', 'larger', 'rotated', '017', 'often', 'various'], [], [], ['swadlincote', 'semantic'], ['swedish', '1939–2008'], ['seaworld'], [], [], ['design', 'swain', 'sweyn', 'european', 'north'], [], []]
TOP TOKENS [['kind', 'tours', 'capacity', 'tour', '’', 'enthusiasts', 'kinds'], ['“tour”', 'tour'], ['good', 'tour', 'since'], ['tour', 'find'], ['tour', 'tours', 'picturesque'], ['tour', 'tours'], ['recently', 'good', 'great', 'tours', '‘', 'tour', 'word', 'person', 'virtual', 'cater', 'online'], ['organized', 'tours', 'tour', 'offer', 'organize', 'custom'], ['tour', 'tours', 'end', 'early', 'anyone', 'together', 'lead', 'accessible', 'touring'], ['useful', 'web-based', 'video-based', 'tour', 'virtual', 'tours', 'industry', 'sequence', 'series'], ['pro', 'tour', 'nanoscientist', 'walking', 'guided', 'tours', 'guide', 'location', 'campus', 'based', 'james', 'professional', 'people', 'concert'], ['concert', 'tour', 'ep', 'grand'], ['tour', 'golf', 'tours', 'world', 'concert', 'co-headlining'], ['tour', 'tours', 'pickleball', 'pro', 'disambiguation'], ['tours'], [], ['tours'], [], [], ['tour', 'tour-du-pin', 'tour-blanche', 'tour-de-peilz', 'tour-saint-gelin', "tour-d'auvergne", 'tour-du-crieu', 'peeters', 'tour-de-sçay']]
TOP TOKENS [['think', 'definitely', 'predicted'], ['sure', 'expected', 'likely', 'come', 'probably', 'would', 'expect', 'expectations'], ['sure', 'expected', 'likely', 'would', 'come', 'probably', 'expect', 'expectations', 'mean'], ['expect', 'soon'], ['expect', 'soon'], ['expect', 'hope'], ['likely'], ['may', 'likely', 'would'], [], ['going', 'gonna', 'come', 'happen', 'either'], [], [], ['shall', 'come'], [], [], [], ['chance'], [], [], []]
TOP TOKENS [['jr', 'command', 'halsey', 'corporations', '1994', 'john', 'reynolds', "halsey's", '1985', 'december', 'annapolis', 'press', 'collins', 'frederick', 'mcgraw', 'clark', 'york'], ['jr', 'command', 'halsey', 'corporations', '1994', 'john', 'reynolds', "halsey's", '1985', 'december', 'annapolis', 'press', 'collins', 'frederick', 'mcgraw', 'clark', 'york'], ['halyomorpha', 'halys'], ['haly', 'aredemersal', 'halibuts', 'halibut', 'also'], ['halstead', 'norm', 'anesthesia', 'procedures', 'standard', 'designed'], ['halstead', 'norm', 'anesthesia', 'procedures', 'standard', 'designed'], ['http://www.seaslugforum.net/factsheet/halgbaca', 'halgerda', 'halgerdidae', 'aurantiomaculata', '18', 'small', 'orange-capped', 'tubercles', 'nudibranchia', 'spots', 'margin'], ['years', "halprin's", 'compounded', 'lawrence', 'destination', 'halprin', 'two', 'october', 'festival', 'like', 'granite'], ['halitosis', 'garlic', 'lightly', 'hydrated', 'foul', 'leaf', 'use', 'person', 'first', 'accumulate', 'done', 'however', 'properly', 'get', 'sure', 'tea', 'way', 'many', 'gargle', 'enough'], ['fishes', 'sea', 'halibut', 'birch', '1', 'sand', 'coating', 'comes', 'octopus', 'herring', 'including'], ['egbert'], ['privateer'], ['halsted', 'platform', '8', 'island', 'unstaffed', 'sidewalk'], ['reopened', 'illinois', '1994', 'november', 'external'], ['1883–1958'], ['1932–1990', 'designer', 'actress', 'slugs', 'family', '2019'], ['halcrow', 'canada'], ['1852–1922', '1942-2007', 'laurence', 'metropolitan', 'blue', 'cta', 'british', 'american', 'halstead', 'john', '1941—1989', '1853–1922', 'mathematician'], ['1910–1997', 'australian', 'chick', '1874–', 'weapon', 'politician', 'halbert'], ['1989', 'namesake', 'generality', 'respectively', '1962', 'halin', "halin's", 'full']]
TOP TOKENS [['loan'], ['loan', 'earned', 'cls', 'loans'], ['loan', 'facts', 'responsibly', 'many', 'loans', 'car', 'rates'], ['loans', 'loan'], ['loan', 'loans', 'understanding', '”', '“', '4'], ['loan', 'personal', 'individual'], ['loans', 'loan'], ['loans', 'construction'], ['loan', 'loans', 'process', 'cls', 'car'], ['loan', '“', 'loans', 'avail', 'unsecured'], ['instrument', 'loan', 'actress'], ['loan', 'loans', 'specific'], ['loan', 'carl', 'van'], ['loan', 'association', 'born', 'thị', 'scores', "women's", 'goals'], ['loan', 'mike', 'career', 'september', 'life', 'game', 'collected', '14', 'appearing', 'cardinals', 'early', 'percentage'], ['loan', 'loans', 'shield'], ["o'loan", '1915–1992', '1951'], ['loan', 'war', 'campaigns'], ['loans', 'loan', 'regulations', 'loaning', 'profile', 'time', 'loanee'], ['loanwords', 'loanword', 'loans', 'loan', 'example', 'redescriptivized', 'many']]
TOP TOKENS [['developmental'], ['developmental', 'education'], ['developmental', '“', 'delay', 'milestones', 'problems'], ['developmental', 'delay'], ['developmental', 'delay', 'physiotherapy'], ['developmental', 'delay', 'physiotherapy'], ['developmental', 'delay', 'milestones', 'milestone'], ['developmental', 'delays'], ['developmental', 'delay', 'development'], ['developmental', 'disability'], ['developmental', 'reproducible', 'english-language', 'journals', 'contents/social'], ['developmental', 'psychology', 'human'], ['developmental', 'bimonthly', '3.808'], ['developmental'], ['developmental'], ['developmental', 'since', 'see'], ['developmental', 'disability', 'disabilities', 'causing', 'lifespan', 'cls', 'pervasive', 'mental', 'delay', 'span'], ['developmental', 'cls', 'disorders', 'neurodevelopmental', 'however', 'life', 'difficulties', 'evolutionary', 'entail'], ['developmental'], ['developmental', 'https://www.sciencedirect.com/journal/journal-of-applied-developmental-psychology']]
TOP TOKENS [['enigmaclassical', 'enigma', 'enigma[i', 'enigmata', 'enigmas', 'enigmalatin', 'word', 'perplexing'], ['enigma', 'different', 'place', 'know', 'alteration'], ['enigma', 'enigmas', 'word'], ['enigma'], ['enigma', 'arduino', 'bletchley'], ['enigma', "enigma's", 'machines', 'anx', 'machine', 'complete'], ['enigma', 'machines'], ['enigma', 'enigma"?"enigma', '2012', '26'], ['enigma', 'enigma"?"enigma', '2012', '26'], ['enigma', "enigma's", 'called', 'bletchley'], ['enigma'], ['enigma', 'enigmatic', 'enigmata'], ['enigma'], ['enigma'], ['enigma', 'throughout', 'afterward', 'initially'], ['enigma', 'enigmas', 'propelled', 'antichrist', 'tarot', 'jet'], ['enigma', '–', 'references', 'mattias', 'thrums', 'guest', 'stands', 'stunning'], ['enigma', "enigma's", 'cls', 'east', "deathstroke's"], ['www.enigmamotorsport.co.uk', 'enigma', 'links', 'motorsport'], ['enigma', 'enigmatic', 'czesław']]
TOP TOKENS [['constable', "constable's", 'separated', 'placing', 'england'], ['constable’s', '“constable', 'constable', '11', 'love'], ['constable', 'academy', 'experience', 'artists', 'health', 'received', 'father'], ['constable', 'london', '1776-1837', 'slowly', 'noon'], ['constable', '1799', 'inspired', 'bergholt', 'british', 'words'], ['constable', "constable's", 'turner', 'uk', 'air', 'despite', '1816', 'significant'], ["constable's", 'constable', 'interest'], ['constable', "constable's", 'children', 'childhood', 'business', '1828', 'although', 'onwards'], ['constable', "constable's", 'painture', 'time', 'cls', '1802', 'made', 'r'], ['constable', 'constables', "constable's", 'praising', 'walker', 'medal', 'considered', 'overstated', 'soon', 'stimulated'], ['constable', "constable's", 'bergholt', 'watts'], ['constables', 'disambiguation', 'constable', 'word...life'], ['constable', 'mainly', 'g', 'canal', 'held'], ["constable's", 'constable', 'meet', 'year', '1799', 'inspired', 'lorrain', 'life', 'posts', 'china', 'later'], ['constable', '1975', '1746', '1984', '1774–1827', '1478–1537', '1776–1837', '1838–1904', 'disambiguation', '1846–1937', '1812–81', '1455–1518'], ['constable', 'disambiguation'], ['constable', "constable's", 'works', 'writings', 's.j', 'foley', 'wrote', 'buried', 'maintained', 'orders', '12mo'], ['constable', '1673', 'north', 'stonegrave'], ['constable', "constable's", 'penicuik', 'german', '1835', 'archibald', 'october'], ['constable', 'imbecile', 'ingleby', 'diana', 'everild', 'march', 'esquire', 'yorkshire']]
TOP TOKENS [['left', 'concerns', 'emphasized', 'incredible', 'manner', 'two', 'unfortunately', 'matched', 'raises', 'concerned', 'early', 'accompanying', 'technically'], ['disjointed', 'effective', 'carried', 'bit', 'could', 'wise', 'disrupt', 'seemed', 'wish', 'although'], ['quite', 'somehow', 'spirit', 'carefully', 'separate', 'everything', 'part', 'works', 'feel', 'differential', 'taken', 'way', 'afraid', 'called', 'behind', 'exactly', 'highly', 'nice', 'comes', 'textured', 'specific', 'really'], ['stuck', 'want', 'interesting', 'leave', 'would', 'particular', 'almost', 'excellent', 'manner', 'chose', 'jumbled', 'acting', 'especially', 'parts', 'leading', 'adding', 'way', 'showing', 'zoomed'], ['make', 'right', 'forcefully', 'careful', 'stands', 'create', 'subtlety', 'subtly', 'specifics', 'hearing', 'like', 'elements', 'listen', 'anything', 'finally', 'striking', 'together', 'listened', 'cut', 'nothing', 'essence', 'snippets'], ['make', 'right', 'forcefully', 'careful', 'stands', 'create', 'subtlety', 'subtly', 'specifics', 'hearing', 'like', 'elements', 'listen', 'anything', 'finally', 'striking', 'together', 'listened', 'cut', 'nothing', 'essence', 'snippets'], ['certain', 'lacking', 'well', 'clear', 'made', 'way', "that's", 'oomph', 'flow'], ["there's", 'gets', 'everything', 'better', 'spoiling', 'needs', 'unfortunate', 'across', 'raptness', 'give', 'approach', 'manages', 'certainly', 'clearly', 'impression', 'get'], ['make', 'lots', 'get', 'stand', 'set', 'like', 'offsets', 'definitely', 'though', 'generally'], ['done', 'say', 'clearly', 'whole', 'way', 'little', 'told', 'harsh', 'without', 'kitschy', 'gets', 'anyway', 'incredible'], ['coherence', 'many', 'left', 'leaves', 'including', 'full', 'things', 'appears', 'dislike', 'distort', 'cuts', 'fully', 'details', 'displays', 'enormous', 'much', 'stated', 'unless', 'shows', "treaty's", 'removed'], ['notable', 'noticeably', 'another', 'technique', 'stylistic', 'text', 'whereas', 'omitted', '1', 'two', 'mistakes', 'example', 'include'], ['feels', 'creates', 'use', 'exhibit', 'however', 'motives', 'clear', 'instead', 'crisp', 'make', '–', 'strong', 'lively', 'rather', 'example', 'employed', 'throughout'], ['omit', 'exceptionable', 'tedious', 'absolutely', 'indelicate', 'second', 'original', 'expressions', 'disfigured', 'necessary'], ['overlap', 'orchestra', 'sometimes', 'blurring', "opera's", 'adds', 'described', 'contrast'], ['seem', 'makes', 'feel', 'perfect', 'almost', 'good', 'time', "there's", 'edits', 'better', 'make', 'nowhere', 'first', 'removed', 'definitely', 'including', 'bit', 'excellent', 'found', 'issue', 'made', 'slows', 'near', 'way', 'like', 'added', 'quite', 'substantial', 'work', 'gives', 'got', 'tailoring', 'due'], ['adds', 'also', 'proved', "shchedrin's", 'eschewing', 'greatly', 'intricacies', 'boldly', 'obfuscate', 'creative', 'touches', 'use', 'phrasing', 'equally', 'full', 'hesitations', 'recognizable', 'easily', 'unexpectedly', 'either', 'orchestration', 'unexpected', 'overhauled', 'enhancing', 'accentuate', 'roles', 'merrily', 'depth', 'sudden', 'obliviously'], ['justice', 'many', 'match', 'full', 'retain', 'paragraphs', 'grotesquely', 'words', 'preserving', 'correct', 'text', 'separated', 'mere', 'effort', 'cannot', 'complete', 'otherwise', 'omitted', 'even', 'mismatches', 'mis', 'committed', 'made', 'also', 'spaces', 'hyphenated'], ['high', 'stating', 'frequently', 'hand', 'noted', 'also', "that's", 'verbosity', 'captions', 'action', 'depicted', 'words', '900', 'debate', 'disliked', 'noticeably', 'much', 'resembles', 'way'], ['ensure', 'cutting', 'back', 'improved', 'text', 'seems', 'admittedly', 'impression', 'otherwise', 'brevity', 'times']]
TOP TOKENS [['kinematics', 'optically'], ['things', 'components', 'literally', 'materials', 'radars', 'clearly', 'enough', 'kind', 'many', 'alert', 'computers', 'offers'], ['shiatsu', 'needles', 'consists', 'meridians', 'manipulations', 'chi', 'pressure', 'function', 'organs', 'pain', 'aims', 'hence'], ['wall', 'room', 'materials', "accountant's", 'chamber', "something's", 'floor', 'typewriters', 'trunk', 'also', 'along', 'contains', 'corner', 'right', 'containing', 'plenty', 'part', 'although', 'corridor', 'like', 'next'], ['512', 'fraction', 'high', 'ability', '3', '130', 'albeit', 'one', 'capable', '“', 'crunching', 'approximately', 'eight', 'deploying', 'given', 'like', 'right', 'total'], ['acentric', 'atercc1', 'attert', 'dicentrics', 'dicentric', 'dna', 'rightmost'], ['vernier', 'technology', 'photosynthetic', 'mathematics', 'sensors', 'also', 'learning', 'education', '’', 'countries'], [], ['fully', 'atercc1', 'upper', 'acentric', 'least'], ['adds', 'cafeteria', 'us'], ['moss', "moss's", 'followed', "fitch's", 'fitch', 'substance', "what's", 'although', "the'55", 'confusion', 'dead', 'levegh', 'trophy', "slowly.'i", 'also', 'explosion'], ['briggs', 'realm', 'marriage', 'garland', "briggs's", 'major', 'point', 'also', 'finds', 'u', 'primarily', 'behind', 'head'], ['unit', 'overstrom', 'others', 'addition', 'well', 'p', 'l.l.b', 'among', "corporation's", '9', 'm.a', 'survived', 'fleetboston'], ['knack', 'one', 'gundahar', 'doctor', "ryder's", 'return', 'back', 'discovery', 'area', 'armaments', "goblins'main", 'contains', 'arrives', 'health', 'unveils', 'later', 'settlements', 'vargas', 'shaft', 'even', 'viktor', 'morgack', 'castle', 'reaches', 'unearthed', 'shot'], ["sr.'s", 'sr', 'lorna', 'body', 'near', "lorna's", 'however', 'thus', 'joel', 'self', 'though', 'morning', 'leave', 'fire', 'geffenhart', 'leaving', '–', 'pleads', 'mask', 'time', 'along', 'later', 'moments', 'back', 'meanwhile', 'evening', 'left', 'mansion', 'around'], ['kortan', 'however', 'oil', 'failed', 'certain', "kortan's"], ['railway', 'recently', 'due', 'street', 'also', "radcliffe's", 'along', 'sworth', 'station', 'cinema', 'including', 'town', 'board', 'consisted', 'includes', 'authority', 'disclosing', 'lighting', '000'], ['extremely', 'grandfather', 'technology', 'supplies', 'possesses', 'find', 'complexes', 'motivations', 'approximately', "trader's", 'situation'], ['wall', 'monk', 'upon', "leupolz's", 'stumbles', 'muck'], ['resources', 'enough', 'units', 'eventually', "sartor's", 'end', 'must', 'defeat', "father's", "haemimont's", "wikipedia's", 'allies']]
TOP TOKENS [['juul', 'dissipates'], ['juul', 'juuling', 'anything', '“'], ['juul'], ['juul', 'doubt', '’', 'james', 'noted', 'youth', 'vaping', '”'], ['juul', 'marijuana', 'juuling'], ['juul', 'juuls', 'doit4juul', 'juuling', 'phlem', 'rectangle'], ['juul', 'content', 'juuling'], ['juul', 'substance', 'kids', 'addictive'], ['juul', 'product', 'using', 'third', 'tried'], ['juul', 'cigarettes', 'fruity', 'org', '2018'], ['juul'], ['juul', "juul's", 'doit4juul', 'doingit4juul', '2019', 'time', '90'], ['juul', "juul's", 'device', 'company', 'cigarettes'], ['juul', "juul's", 'doit4juul', '2018'], ['juul', "juul's"], ['juul', 'juuls', 'example', 'youth', 'marketing', 'sugary'], ["juul's", 'juul', 'juuls', 'people', 'addiction', 'products', 'students', 'u'], ['juul', "juul's", 'juuls', '2019', '2018', 'however'], ["juul's", 'juul', '2019', 'success', 'media', 'september'], ['juul', 'addiction', 'methods', 'would', 'number', 'product']]
TOP TOKENS [['analyzers', 'analyzer', 'analysis', 'signal'], ['analyzer', 'tests'], ['analyzer', 'analyzers', 'test', 'testing', 'bandwidths', 'analyze'], ['analyzer', 'analyzers'], ['analyzer', 'analyzers', 'signal', 'test', 'network'], ['analyzer', 'analyzers', "analyzer's"], ['analyzers', 'analyzer', 'testing', 'test', 'measurements'], ['analyzer', 'tuned', 'signal', 'capability', 'sdr', 'test', 'spectrum'], ['analyzer', 'analyzers', 'testing', 'test'], ['analyzers', 'analyzer', 'capability', 'required', 'signal', 'digitizers'], ['analyzer', 'analyzers', 'today’s', 'high-frequency', 'signal'], ['analyzer', 'analyzers', 'typical', 'capability'], ['analyzer', 'test', 'analyzers', 'hz', '1', 'range'], ['analyzer', 'analyzers', 'tuned', 'spectrum', 'based', 'measure'], ['test', 'analyzer', 'equipment', 'network', 'power'], ['analyzers', 'analyzer', 'analysis', 'testing', 'analyser', 'analysers', 'test', 'spectrum', 'mixers'], ['analyzers', 'analyzer', 'test', 'tests', 'upv', 'testers', 'signals', 'audio', 'quality'], ['analyzer', 'tester', 'spectrum', 'network', 'signal', 'tests', 'measure', 'modulated', 'sawtooth', 'test'], ['analyzer', 'analyzers', 'testing'], ['analyzer', 'analyzers', 'spectrum', 'tuned', 'analysis', 'many', 'applications', 'using']]

Processing features:  97%|█████████▋| 95/98 [45:33<01:26, 28.70s/it]

getting sample prompt forgetting sample prompt for 24541
 24540
getting sample prompt for 24542
getting sample prompt for 24543
getting sample prompt for 24544
getting sample prompt for 24545
getting sample prompt for 24546
getting sample prompt for 24547
getting sample prompt for 24548
getting sample prompt for 24549
getting sample prompt for 24550
getting sample prompt for 24551
TOP TOKENS [['come', 'outaʊt', 'truth', 'outs', 'tagged', 'outed', 'came', 'knocked', 'style', "ko'd", 'home', 'reveal', 'went'], ['out(redirected', 'read', 'user', 'one', 'reading'], ['out(redirected', 'something', 'ride', 'patient', 'rode', 'place'], ['out(redirected', 'spout', 'gets'], ['out(redirected', 'paint'], ['bring', 'something', 'inadequate'], ['bring', 'something', 'official'], ['punch', 'overcome', 'alley', "sarah's"], [], ['outs'], ['1946'], [], ['wite-out', 'white-out', 'whiteout', '2000', 'boss', 'variants', 'ep', 'cockburn', 'swallow'], ['ride', 'composed'], [], ['side-out'], ['z-out', 'x-out'], ['souled'], ['teruyuki'], ['farout', 'farfarout']]
TOP TOKENS [['kabul', 'fleet', 'security', 'east', 'afghan'], ['kabul', 'districts', 'ascribe', 'kamboja', 'kadphises'], ['kabul', "kabul's", 'persian', 'uzbeks', '1', 'geographic', '2009', '3', 'turkmen'], ['kabul', 'generations', 'ascribe', 'whose', 'biruni', 'afghanistan', 'ad', 'indo', 'basin'], ['kabul', 'river', '1773', 'mountains', 'city'], ['kabul', "kabul's", 'kabulˈkɑ', 'pakhtunkhwa', 'khyber', 'peshawar', 'sharif', 'afghanistan', 'macnaughten', 'word'], ['kabul', "kabul's", 'kabulˈkɑ', 'pakhtunkhwa', 'khyber', 'sharif', 'afghanistan', 'trend', 'peshawar', 'macnaughten', '1879'], ["kabul's", 'kabul', 'cars', '7', 'fleet', '2008', 'foreigners'], ['kabul', "kabul's", 'made', 'ad', 'mujahideen', 'durrani', 'mughal', 'network'], ['kabul', 'afghanistan'], ['kabul', 'afghanistan'], [], ['kabul'], ['kabul', 'november', 'time', 'paghman'], ['kabul'], ["kabul's", 'kabul', 'featured', 'reza', 'edition', 'international', 'barch'], ['kabul'], ['kabul'], ['kabulia', 'akhtarii', 'afghanistan'], ['kabul', '1859', '926', '7', 'simeon', '1517', 'excavated', 'roman', 'galilee', 'mamluk', 'syria', 'bachelors']]
TOP TOKENS [['amnesia'], ['amnesia'], ['amnesia'], ['amnesia', 'cls'], ['amnesia', 'cls'], ['amnesia', 'one'], ['http://www.merckmanuals.com/professional/neurologic_disorders/function_and_dysfunction_of_the_cerebral_lobes/amnesias.html', 'amnesias', 'amnesia', 'n.y', 'http://www.accessmedicine.com/resourcetoc.aspx?resourceid=4'], ['amnesia', 'cls'], ['amnesia', 'cls'], ['amnesia', 'amnesiacs', 'cases', 'memory'], ['amnesia', 'brasco', 'disturbed'], ['amnesia'], ['amnesia', 'amnesiac'], ['alicia', 'amnèsia', 'martina', 'angelino', 'rebuild', 'stella', 'puigcorbé'], ['amnesia', 'cls', 'base'], ['amnesia', 'buttrey', 'kenneth', 'albums', 'jeff', 'records'], ['amnesia', 'cls', 'etc', 'cars', 'july', '2', 'scenes'], ['amnesia'], ['amnesia', 'also', 'sep'], ['amnesia']]
TOP TOKENS [['necessarily', 'kanban', 'without', 'replacement', 'real', 'use', 'sense', 'benefits', '’', 'combine'], ['pulled', 'kanban', 'backlog', 'active', 'pre', 'prioritized', 'left', 'encourages', 'effectively', 'much', 'frequently'], ['choices', 'kanban', 'next', 'xp', '2004', '”', 'direct', 'benefits', 'however', 'level', 'matter'], ['using', 'kanban', 'deliver', 'development', 'future', 'version', 'things', 'amount', 'items', 'participants', '’', 'work', 'clearer', 'vs', 'rather', 'tangible', 'new'], ['using', 'kanban', 'deliver', 'development', 'future', 'version', 'things', 'amount', 'items', 'participants', '’', 'work', 'clearer', 'vs', 'rather', 'tangible', 'new'], ['works', 'kanban', 'enables', 'use', 'status', 'methodology', 'customers', 'output', '’', 'quo', 'advantages', 'board', 'priorities', 'focuses', 'great', 'scupper', 'thus', 'whole', 'easy', 'task', 'implement'], ['constrains', 'teams', 'kanban', '’', 'system', 'great', 'reason', 'needs'], ['desirable', 'work', 'completion', 'kanban', 'output', 'easily', 'mental', 'process', 'many', 'aims', 'defy', 'ideal', 'aspects', 'picture'], ['sizes', 'adopted', 'kanban', 'aspect', 'since', 'current', 'therefore', 'however', 'apply', 'even'], ['get', 'es', 'highlight', 'overcapacity', 'identifi', 'kanban', 'wastes', 'takes', 'listen', 'human'], ['morning', 'surrounding'], ['high', 'end', 'chorten'], ['parbhani', 'kapurthala', 'kanhadadeva', 'kanhadade', 'action'], ['79', 'india'], ['jharkhand', 'india', 'ranchi'], ['1992', 'ran', 'started', 'year', 'piravi', 'movies', 'kanaka', 'major'], [], [], [], ['taiwanese', '14th', 'american', 'kirishima', 'actor', 'defunct', '2000ad', '1999']]
TOP TOKENS [['occurs', 'produce', 'appear', 'phenomenon', 'iridescence', 'rainbows', 'contrast'], ['get', 'phenomenon', 'refracted', 'occurs'], ['produce', 'phenomenon', 'also', 'circumhorizontal', 'bounces', 'caused', 'rainbows', 'according', 'form', 'makes', 'diffract', 'occurs'], ['cause', 'ones', 'like', 'effect', 'giving', "a'rainbow'caused", 'phenomena', 'effects', "these'fog", 'looks', 'phenomenon', 'arcs', 'kind', 'caused'], ['phenomenon', 'appear', 'optical', 'appears'], ['creating', 'phenomenon', 'like', 'occur', 'prisms', 'circumhorizontal', 'act', 'halos', 'emanating', 'exist', 'rainbows”', 'thin'], ['occurs', 'appearance'], ['occurs', 'appearance'], ['produce', 'iridescence', 'rainbows', 'appearance', 'occur', 'like', 'gets', 'effect', 'circumhorizontal', 'phenomenon', "to'light'fragments", 'shaped', 'visible', 'flat', 'form', 'appears'], ['phenomenon'], ['result', 'appears', 'rainbows', 'appearing', 'appear', 'seen', 'visible', 'observed', 'happen', 'created', 'form', 'formed', 'sees', 'phenomenon', 'illuminated'], ['appearance', 'phenomenon', 'create', 'halos', 'optical', 'produce', 'refracting', 'sending', 'prisms', 'refracted', 'visible', 'caused'], ['produce', 'phenomena', 'rainbows', 'composed', 'appearance', 'visible', 'optical', 'halos', 'occurs', 'water', 'rather', 'droplets', 'see', 'members', 'creating', 'occurrence', 'lies', 'forms', 'arc', 'hexagonal'], ['produce', 'phenomenon', 'created', 'another', 'become', 'possible', 'creating', 'caused', 'rainbows', 'several', 'consisting', 'apparent', 'hues', 'rarely', 'narrow', 'processes'], ['iridescence', 'optical', 'pillar', 'include', 'heiligenschein', 'crepuscular', 'rays', 'sprites', 'alpenglow', 'arc', 'phenomena', 'effect'], ['produces', 'emissions', 'phenomenon', 'produced', 'occurrence', 'observations', 'visual', 'process', 'occur', 'discharges', 'generate', 'borne', 'phenomena', 'due', 'optical', 'halos', 'approximately', 'structure', 'thought', 'research', 'required', 'unlike', 'preceded', 'uncommanded', 'unexplained', 'discharge', 'june', 'threshold'], ['phenomena', 'appear', 'occurs', 'caused', 'rainbows', 'optical', 'visible', 'seen', 'form', 'however'], ['appear', 'produces', 'form', 'rainbows', 'appearing', 'causes', 'raindrops', 'phenomenon', 'takes', 'produced', 'shows', 'caused', 'multicolored', 'optical', 'shines', 'produce', 'light', 'seen'], ['circumhorizontal', 'cause', 'phenomena', 'external', 'optical', 'arc', 'iridescence'], ['avalanches', 'produces', 'form', 'produced', 'another', 'appears', 'new', 'producing', 'formation', 'follow', 'release', 'discharges', 'result', 'appeared', 'g', 'dry', 'could', 'suggested', 'streaks']]
TOP TOKENS [['ufos', 'ufo', 'ufology', 'ufocat', 'research', 'particular', 'cls'], ['ufos', 'ufo'], ['ufo', 'ufos', 'ufologists', 'conversation'], ['ufo', 'unk', 'flying'], ['ufo', 'ufos', 'ufologists', "ufo's", 'guesses'], ['ufologists', 'ufo', 'ufology', 'ufologist', 'concern', 'quality', 'question'], ['ufo', 'ufos', 'reports', 'also'], ['ufo', 'ufos', 'ufo-themed', "ufo's"], ['ufos', "ufo's", 'ufologists', 'ufo'], ['ufo', 'ufos'], ['ufo', 'ufo-related'], ['ufo', 'ufo-related', 'ufology', 'ufos'], ['ufo', 'jan'], ['ufo', '“ufo'], ['ufo'], ['ufo'], ['ufo', 'cls', 'years', 'one', 'album'], ["ufo's", 'ufo', 'metal', 'f'], ['ufo', 'ufologist', 'ufo-related', 'futurist', 'paranormal', 'mufon', 'budinger'], ['ufo', 'ufos', "ufo's", 'ufology', 'ufo-related', 'kind', 'hendricks', 'bowman']]
TOP TOKENS [['sodium', 'much'], ['sodium'], ['sodium', 'food'], ['sodium', 'lower-sodium', 'much'], ['sodium', 'much'], ['sodium', 'low-sodium', 'reduced-sodium', 'you’re', 'milligrams', 'intake', 'mg'], ['sodium', 'milligrams'], ['sodium', 'milligrams'], ['sodium', 'amount', "food's"], ['sodium', '1'], ['sodium', 'consuming', 'dietary', 'consumption', 'mg', '0', '1'], ['sodium', 'eaten', 'intake', '1', 'another', '400mg', 'habitual', '2'], ['sodium', 'intake', 'dietary', 'reduce', 'consume', 'amount', 'food'], ['sodium', 'intake', 'levels', 'consumed', 'consumption', 'milligrams', 'daily', 'high', 'reduced', '0', 'mg'], ['sodium', 'intake', 'contain', 'reduce', 'macaroni', 'rosemary', 'rice', 'pasta', 'carrots', 'include', 'cumin', 'paprika', 'beans', 'beets', 'garlic', 'parsley', 'cloves'], ['sodium', 'dietary', 'levels', 'intake', 'may', 'consume', 'high', 'reduction', 'foods', '11'], ['sodium'], ['sodium', 'intake', 'mg', 'levels', 'allowance', '2', 'level', '2300'], ['sodium', 'cls', 'vickie', 'part', '29', 'universe', 'july', 'versions'], ['sodium', 'contain', 'mg', 'per', '4', '1800', '1', 'diet', '500', '2', 'low', 'taken', 'people', 'much', '400', 'one', 'beets', 'cls', 'intake', 'approx']]
TOP TOKENS [['hayward'], ['hayward', "hayward's", 'haywards', 'mateo-hayward'], ['hayward', 'haywards', '“', 'william', '20'], ['hayward', '2015'], ['hayward', '’', 'sep'], ['hayward', 'general', 'bestplaces'], ['hayward', "hayward's"], ['hayward', "the'general'hayward", "a'general'hayward", "hayward'was", 'haywards', 'man'], ['hayward', 'england', 'bligh', 'ship', 'bethams', 'seems'], ['hayward', 'street'], ['haywards', 'hayward', 'deliciosa'], ['hayward', "hayward's", '2011', 'midlaner', '2018', '2014', '2015'], ['hayward', 'captain', 'durham'], ["hayward's", 'hayward', '2020', 'youtube', 'participation', 'competition', '2016', 'also', 'school', "binet's"], ['hayward'], ['hayward', 'christchurch', 'j.s', '1868', '1935', 'canterbury'], ['hayward', '49', '51', "men's"], ['hayward'], ['hayward', 'bowen', '21', 'season', 'two'], ['hayward', 'fellows']]
TOP TOKENS [['sinclair', 'sinclairs', 'mr', '1953', '1917', '1912', 'nazism', 'result', '1907'], ['sinclair', 'upton', 'set', '1899', 'stirling', 'naval'], ['sinclair', 'university', 'resume', '’', 'racism', '“', 'today', 'ulously', 'depicts', 'northridge'], ['sinclair', 'york', "son's"], ['sinclair', 'triumph', 'upton', '’', 'follies', '”', 'jungle'], ['sinclair', 'upton', 'evils'], ["sinclair's", 'sinclair', '1906', 'yet', 'passage'], ['sinclair', 'indeed', 'upton', 'century', 'done', 'bestsellers', 'social', 'indiana', 'essays'], ['sinclair', "sinclair's", 'upton', 'popularity', 'death', '1950s', 'years', 'sep'], ['sinclair', "sinclair's", 'socialist', 'prize', 'novel', 'upton', 'many', 'information', 'among', 'california'], ['sinclair', "abc's"], ['sinclair', '1970', 'mr', 'united'], ["sinclair's", 'sinclair', 'lost', 'series'], ['sinclair', 'c.1787-1908', 'disambiguation', 'dr', 'sinclaire'], ['sinclair', 'also', '1941'], ['sinclair', 'scotia', 'dalhousie'], ['sinclair', 'awards', 'november'], ['sinclair', "sinclair's", 'world', 'century', 'merriam', '1934'], ['sinclair', '1983', 'kiri', 'sydney', '2007', 'impressions', 'children', 'officials', 'life'], ['sinclair', 'elite', 'vancouver', 'pounds', 'fisheries', 'granville', 'architecturally', '92']]
TOP TOKENS [['results', 'clearly', 'experiment', 'effect', 'observable', 'showed', 'detailed', 'probe', 'researchers', 'demonstrated', 'help', '’', 'exhibit', 'may', 'even', 'nearly', 'equal', 'confined', 'studies', 'example', 'trapped', 'behavior', 'efforts', 'depends', 'devised', 'prisoner', 'resolution', 'neutrons', 'molecule', 'clear'], ['experimentally', 'achieved', 'realized', 'observe', 'experimental', 'even', 'investigates', '“', 'physrevlett', 'opens', 'focusing', 'experiment', 'observed', 'detected', 'possibilities', 'far', 'particular', 'insights'], ['experiments', 'demonstrate', 'utilizes', 'experiment', 'demonstrating', 'clearly', 'work', 'experimentally', 'obtained', 'importantly', 'ability', 'expected', 'agreement', 'measurements', 'predictions', 'range', 'pointed', 'measured', 'equal', '1996', 'potentials', 'presented', 'respective', 'subtended', 'addition', 'measuring', 'finally', 'first', 'following', 'realize', 'thus', 'shown', 'also'], ['observed', 'experimental', 'demonstrate', 'experiment', 'observation', 'note', 'use', 'effect', 'able', 'acting', 'taking', 'leads', 'account', 'required', 'accomplishment', 'also', 'anharmonicity', 'clearest', 'present', 'show', 'effects', 'studies', 'absence', 'work', 'scale', 'said'], ['experiments', 'demonstrating', 'illustrates', 'allowing', 'variety', 'separated', 'using', 'key', 'performed', 'thereby', 'group', 'beautifully', 'fact', 'achieved', 'initially', 'even', '223001', 'range', 'allow', 'instance', 'particularly', 'includes', 'certain', 'workhorse', 'based', 'consideration', 'ones'], ['accomplishes', 'isolate', 'interaction', 'trapped', 'exert', 'delft', 'used', 'interactions', 'resolution', 'goal', 'study', 'use', 'probe', 'allow', 'unprecedented', 'means', 'first', 'exhibit', 'still', 'measure', 'help', 'know', 'hold', 'sensitivity', 'precisely', '’', 'cavity', 'phenomena', 'using', 'placed', 'level', 'apply', 'ultimate', 'exploiting', 'rather', 'optically', 'type'], ['proves', 'result', 'studied', 'consisting', '“', 'crucial', 'turned', 'extremely', 'gives', 'experiments', 'possible', 'even', 'insight', 'phenomena', 'step', 'also'], ['trapped', 'experimental', 'able', 'selected', 'certain', 'results', '10', 'conceivable', 'work', 'using', 'many', 'http', 'reason', 'rather', 'gesellschaft', 'use', 'offers', 'important', 'studied', 'decelerated', 'molecules', 'suited', 'like', 'previously', 'possibilities', 'one', 'well', 'must', 'www', 'find', 'another'], ['demonstrate', 'able', 'managed', 'take', 'observe', 'dynamically', 'confirmed', 'original', 'keep', 'demands', 'subject', 'observations', 'behaviour', 'called', 'reference', 'examined', 'involving', 'means', 'see', 'next', 'rotor', '’', 'collected', 'show', 'certain', 'practice', '“', 'according'], ['experiment', 'experimental', 'reached', 'behaviour', 'extend', 'regime', 'interest', 'trapped', 'allow', 'variety', 'range', 'long', 'example', 'therefore', 'says', 'particular', 'using', 'ways', 'applied', 'necessary', 'even', '”', 'works', 'provides', 'feasible', '“', 'offers', 'able'], ['demonstrated', 'tested', 'experimentally', 'first', 'regime', 'thoroughly', 'sensitive', 'able', 'essential', 'enables', 'difference', 'useful', 'μm', 'recently', 'simplifies', 'using', 'provide'], ['±1', 'observed', 'combined', 'determined', 'enough', '99', 'differ', 'sensitivity', 'gave', 'increased', 'greatly', 'order', 'many'], ['proof', 'observed', 'witness', 'able', 'made', 'experimenters', 'experimental', 'could', 'experimentally', 'study', 'enables', 'verify', 'observe', 'hypothesis', 'shown', 'work', 'multiplicity', 'experiments', 'research', 'thus', 'scientists', 'et', 'used', 'possible', 'provides'], ['experiments', 'variety', 'turns', 'determined', 'encountering', 'worked', 'experiment', 'indispensable', 'study', 'exploits', 'provided', 'offer', 'utilize', 'period', 'demonstrated', 'occurs', 'resonant', 'happen'], ['experimentally', 'observed', 'experiment', 'experimental', 'observe', 'possible', 'measurable', 'tests', 'reported', 'verification', 'proposed', 'allow', 'evidence', 'carried', 'measurements', 'sits', 'yet', 'albeit', 'involving', 'found', 'situation', 'setup', 'go', 'would', 'still', 'effect', 'realize', 'different', 'change', 'potentials'], ['experimentally', 'demonstrated', 'measured', 'done', 'regime', 'predicted', 'measurement', 'first', 'time', 'attained', 'demonstrations', 'employed', 'sensitive', 'makes', 'turns', 'exhibits'], ['first', 'time', '1', 'becoming', 'westbrook', 'top', '98', 'games', 'arena8', 'history', 'since', '2012', '0', 'beforehand', 'however', 'supersonics', '–', '2020'], ['demonstrated', 'experiment', 'confirmed', 'physically', 'possible', 'acting', 'using', 'suggests', '1', 'requires', 'achieved', 'potentially', 'connected', 'specifically', 'performed', '1961', 'set', 'required', 'would', 'e', 'computer', 'way', 'given'], ['experimental', 'realization', 'probing', 'setup', 'trick'], ['experimentally', 'probe', 'allow', 'enabled', 'experiments', 'tests', 'observed', 'exploiting', 'thus', 'explored', 'even', 'may', 'serve', 'available']]
TOP TOKENS [['byzantium'], ['century', 'ad', 'romans', 'byzantine', 'city', 'christianized', 'tunisia', "region's", '1159', 'c', 'africa', 'latinized', 'algeria'], ['century', 'roman', 'arrived', 'arrival'], ['cls', 'roman', 'romans', 'byzantine', 'ad', 'century', 'city'], ['century', 'period'], ['roman', 'empire', 'centuries', 'antiquity', 'east', 'century', 'presence', 'visigoths', 'influence', 'however'], ['sicily', 'roman', 'century'], ['civilization', 'antiquity', 'roman', 'century', 'ancient', 'africa', 'east', 'europe', 'ad'], ['century', 'bce', 'presence', 'romana', 'hispanica', 'visigoths', 'spread', 'roman', 'influence', 'ce'], ['century', 'africanized', 'imports'], ['roman'], ['century', 'centuries', 'kosine', 'roman', 'romans', 'spread', 'ad'], ['roman', 'century', 'romanas', 'period', 'bc', 'archeologia', 'romane', 'ancient', '602', 'also', 'ptolemais', 'storia'], ['century', 'roman', 'around'], ['century', 'centuries'], ['roman', 'century'], ['roman', 'areas', 'constantia', 'phoenician', 'romans', 'century'], ['roman', 'century', 'centuries', '560s', 'empire', 'romans', 'around', 'greek', '–'], ['romans', 'roman', 'ad', 'byzantines', 'bc'], ['century', 'byzantine', 'empire', 'rome', 'africa', 'roman']]

Processing features:  98%|█████████▊| 96/98 [46:01<00:56, 28.48s/it]

getting sample prompt forgetting sample prompt for 24553
 24552
getting sample prompt for 24554
getting sample prompt for 24555
getting sample prompt for 24556
getting sample prompt for 24557
getting sample prompt for 24558
getting sample prompt for 24559
getting sample prompt for 24560
getting sample prompt for 24561
getting sample prompt for 24562
getting sample prompt for 24563
TOP TOKENS [['political', 'politics', 'political[pə'], ['politics', 'worse', '‘', 'words', '’', 'authority', 'level', 'adversaries', 'instance'], ['politics', 'political', 'say', 'economy', 'work', 'beginning', 'great', 'true'], ['politics', 'political', 'world', 'need', 'simply', 'system', 'schmitt', 'aristotle', 'philosophy', 'carl'], ['politics', 'political', 'science'], ['political', 'politics', '‘', 'politically', 'distinction'], ['politics', '“politics', 'political', 'furthermore', 'adversaries'], ['political', '“', 'politics', 'definition', 'affairs'], ['politics', 'political', 'word', 'others'], ['political', 'política', 'político', 'politico', 'politics', 'politica'], ['political', 'politics'], ['political'], ['political', 'politics'], [], [], [], ['political', 'politics', 'category', 'science'], ['political', 'united'], ['political'], ['political', 'politics']]
TOP TOKENS [['spill', 'unintentionally', 'spill.com', 'leadership', 'oil'], ['spill', 'spills', 'inlay', 'splinter', 'wasted'], ['spill', 'and/or', 'hazard', '1'], ['spill', 'spilled', 'meaning', 'type', 'spilling', 'kits', 'needed', 'kit', 'ex'], ['spills', 'spill'], ['spill', 'spills', 'spillan', 'spillen', 'spilling', 'amount', 'group', 'spilled', 'take', 'position', 'german', 'spillmiddle', 'english', 'big', 'crowd', "one's"], ['spill', 'spills', 'kit'], ['spill', 'spills', 'spilled', 'identify', 'appropriate', 'areas', 'possible', 'potential', 'kit', 'kits', 'kind(s'], ['spilled', 'spill', 'spills', 'designed', 'unique', 'kits', 'entire', 'thought', 'typical', 'may', 'kit', 'accidental'], ['spills', 'spill', 'spillage', 'kit', 'across', 'neutralizers', 'every'], ['spill', 'unintentionally', 'leadership', 'audio', 'oil', 'form', 'combüchen', 'alexis'], ['spillers', 'mills'], ['spill', '1974', 'publishing', 'swallower', 'known', "spill's", 'illusions', '2015', 'c.1976–c.1980', 'sheets', 'spillman', 'bar', "harrah's", 'worked'], ['spillcam', 'oil', 'spill', '2010'], ['www.spillern.at', 'spillern'], ['skanz', 'spill', 'agent', 'co-conspirators', 'national', 'spilled', 'power', 'denver-based', 'hemorrhagic'], ['spill', 'market'], ['spillers', 'spiller', 'politician', 'mary', 'isaiah', 'violinist', 'unincorporated'], ['spillmann', 'herschell-spillman', 'spillman', 'guest-hosting', '1959'], ["spill's", 'spill', 'popular', 'spilling']]
TOP TOKENS [['priory', "priory's", "have'moved'it", 'lands', 'cls', 'dorter', 'parlour', 'refectory', 'century'], ['priory', 'montgomery'], ['priory', 'treasury', 'richard', 'hall', 'church', 'cloister', 'buildings', 'house', 'augustinian', 'felons', 'blubberhouses', 'property', 'crenellate', 'land', 'gave', 'gate', 'owned'], ['priory', 'cls', 'piety', 'english', 'saint', '”', 'yielded', 'dieu', 'monastery', 'property', 'science', 'beurrieres', 'century', 'established', 'history', 'knowledge'], ['priory', 'site'], ['priory', 'premonstratensians', 'augustinians', 'monasteries', 'cathedral', 'bishop'], ['priory', 'cluniac', 'monastic', 'buildings', 'manor', 'however', 'cls', 'estate'], ['priory', 'rebuilt', 'higgins', 'outbuildings', 'museum', 'mansion', 'dovecot', '’', 'quarters', 'brewery', 'church', 'swooped', 'buildings', 'built', 'site'], ['priory', 'church', 'view', 'stores', 'buildings', 'place', 'parish', 'writing', 'lands', 'addition', 'eventually'], ['priory', 'cls', 'geography', 'offered', 'also', 'school', 'tours', 'subjects', 'history', 'daylight', 'french'], ['buildings', 'building', 'theakston', 'priory'], ['hitchin', 'st'], [], ['priory'], ['priory', 'cls', 'harbour', 'built', 'european', 'facilitate', 'building', 'oared', 'boat', 'residences', 'marsupials'], ['college'], ['peter', 'priory', "dominic's"], ['priory', 'built', 'estate', 'cls', 'others'], [], ['priory', 'entrance', 'augustinian', 'roman']]
TOP TOKENS [['allotment', 'allotting', 'allotement'], ['allotment', 'allotments', 'allotting'], ['allotment', 'allotmentəˈlɒt', 'allotting', 'allotted', 'term', 'plot', 'allotement'], ['allotment', 'allotments', 'allotting', 'britain'], ['allotment', 'allotments', 'years', 'local'], ['allotment', 'allotments', 'environment'], ['allotments', 'allotment', 'associate', 'means', 'time'], ['allotment', 'allotments', 'office', 'difference', '£4'], ['allotment,n.1', 'allot,vb', 'c.j.s'], ['allotment', 'allotments', 'placed', 'individuals', 'land'], ['allotment'], ['allotment'], ['allotments', 'allotment', 'land', 'rent', 'perpetuity', 'sufficient'], ['allotment', 'abide', 'well', 'subdividing', 'especially', 'size', 'usually'], ['allotments', "allotment's", 'allotment'], ['allotments', 'archived', 'relating', 'respect', 'n', 'make', 'public'], ['allotments', 'allotment', 'agent', 'cls', 'exists'], ['allotments', 'allotment'], ['allotment', 'among'], ['allotment', 'allotments', 'expand']]
TOP TOKENS [['sirtuins', 'sirt', 'sirt1', 'sirt4', 'sirt7', 'sirt3', 'sirt2', 'sirt6', 'called', 'also', 'speaking', 'sirt5', 'program', 'active', 'single', 'properties', 'different'], ['sirt1', 'inactivates'], ['sirtuins', 'sirtfoods', '“sirtuin', 'sirtfood', 'sirt1'], ['sirtuin', 'sirtfoods', 'sirtuins', 'stimulate', 'seven', 'thanks'], ['sirt1', 'proteins', 'thus', 'diseases', 'condition'], ['sirt1', 'affect', 'activation'], ['siri', 'system', 'siri,”'], ['sirtuins', 'sirt1', 'sirtuin', 'sirt7', 'notably', '–', 'ageing', 'sir2', 'consequence', 'mammalian', '225', 'mitochondria', '1'], ['sirtuins', 'sirt1', 'sirtuin', 'sirt7', 'notably', '–', 'ageing', 'sir2', 'consequence', 'mammalian', '225', 'mitochondria', '1'], ['sirtuins', 'sirt1', 'sirtuin', 'sirt7', 'notably', '–', 'ageing', 'sir2', 'consequence', 'mammalian', '225', 'mitochondria', '1'], ['sirtuin', 'sirte', 'sirt', 'disambiguation'], ['sirri', 'siri', 'application'], ['sirak', 'širak'], ['sira', 'sirat', 'sirá', 'sirah', 'sīra', 'sirdalen'], ['sirt', 'sirte'], ['siran', 'şiran'], ['siro', 'sironidae'], ['siro', '1924–1992'], ['sirje', '1992', 'širje'], ['sirine']]
TOP TOKENS [['requirements', 'utah', "utah's", 'also', '8', 'artificially', 'capita'], ['utah', '1960s'], ['utah', '’', '2017', 'finally', '42', '–', 'experiment'], ['utah', 'utahn', 'utahns', 'help', 'patients'], ['utah', "utah's"], ['utah', 'utah’s', '2008', 'average'], ['utah', "utah's", 'heart', 'salt'], ['utah', "utah's", '1932', 'across', 'northern'], ['utah', 'population'], ['utah', 'percentage', '’'], ['utah', "utah's", 'requirements', 'citizen'], ['utah', 'director', 'appointees', '11'], ['utah', "utah's", 'opensecrets', 'u.s', 'salt'], ['utah', 'u.s', 'several', 'salt'], ['utah', '2010', "bureau's", 'around', 'u', 'country', '763', '1', 'miles'], ['utah', 'gun', 'however', '’'], [], ['utah', "utah's", 'primary'], ['utah', 'people', 'head', "mayor's", 'lt', '10', 'police', 'stores', 'salt'], ['utah', 'california', "utah's", 'salt']]
TOP TOKENS [['presbyopia', 'presbys'], ['presbyopia'], ['presbyopia'], ['presbyopia', 'presbyopic', 'many', 'condition', 'well'], ['presbyopia'], ['presbyopia'], ['presbyopia', 'eyesight', 'length', 'due', 'condition”'], ['presbylasik', 'presbyopia'], ['presbyopia'], ['presbyopia', 'arm’s'], ['cosby', 'cosbys'], ['cosby', "cosby's", '2018'], ['mosby', "mosby's", 'ervine', 'rangers'], ['cosby', 'goldsman', 'television', 'comics', 'akiva', 'game', 'wagner', 'studios', 'andrew'], ['cosby'], ['presbyopia', 'presbyopes', 'presbylasik', 'cls', 'objects', 'distance'], ['cosby', "cosby's", '1981', 'states', '1982', 'collection', 'believed'], ['cosby', "cosby's", 's.a', 'times', 'genre', 'countries', 'named', 'angeles'], ['cosby', 'show', 'jr', '2014', 'seasons', 'sitcom', 'world', 'culp'], ['risby']]
TOP TOKENS [['max', 'word', 'value', 'like', 'a2', 'able', 'maximum'], ['max', 'service', 'b2:d2'], ['1', 'maximum', '9', 'enter', 'max'], ['value', 'maximum', 'get'], ['value', 'maximum', 'name', 'wise', 'max', 'applied', 'e', 'result', '–'], ['interested', 'maximum', 'googling', 'value', 'anyway', 'libraries', 'int_max'], ['value', 'function'], ['order', 'value'], ['creating', 'root', 'max', 'maximum', 'maxheapify', 'via', 'maxheap', '17', 'element', 'node'], ['maximum', 'value', '“'], ['maximum'], ['maximum', 'point', 'maximized', 'general', 'principle', 'function', 'cannot'], ['max'], ['maximum', 'maximized', 'maximize', 'respect', 'maximizers', 'value', 'gives', 'parameter', 'parameters'], ['maximize', 'maximum', 'maximized', 'case', 'maximizing', 'size', 'number'], ['performance', 'requirement', 'maximum', 'either', 'antecedent', 'elapse', 'mentioned', 'type', 'vs'], ['maximum', 'k', 'easily', 'method', 'computed', '9751', 'kn'], ['value', 'point', 'maximum', 'essence', 'principle', 'question', 'solved', 'instance', 'certainly', 'maximized', 'clearly'], ['maximum', 'finding', 'maxclique', 'qmax', 'classes', 'ø', 'find', 'clique'], ['maximum']]
TOP TOKENS [['compton'], ['compton', 'angeles', 'neighborhoods', 'incorporate', 'age', 'compared'], ['compton', '1956', 'landmark', 'actions', 'occur', 'legacy', '1931', 'freedom', 'known', 'lifetime', 'one', 'also'], ['compton', 'south'], ['compton', '”compton', '“compton', 'name', '1873', 'may', 'around', 'road', '1066'], ['compton', 'paper', '1923', 'states', '1919', 'said', '1916', '17'], ['compton', 'years', 'angeles', 'area', 'name', 'century', 'detail', 'edged', 'city'], ['compton', 'comptonville', '3', '13', '2', 'cls', 'californias'], ['compton', '12', '2013', 'inc', 'holly'], ['compton', 'comptons', 'wars', 'york'], ['compton', 'yorkshire', 'icefield', 'farnham', 'kid', 'album', 'software', 'crater'], ['compton', 'burnett'], ['compton', 'mysteries'], ['compton', '1660', 'knot', 'remained', '1675', 'death', 'doth'], ['compton', "compton's", '2002', 'wolfe', 'rosenberg', 'people', 'bluegrass'], ['compton', 'denver', 'season', 'sep', 'ball'], ['compton', '2004', '2016', '2001', '2015', '2011', '2013', 'shotgun', 'patriots'], ['compton', 'others', 'forest'], ['compton', 'century', 'channels', 'aod', '2013', '1964', 'bournes'], ['compton', 'golfer', 'sep', 'campbell', 'u', 'amateur']]
TOP TOKENS [['kubernetes'], ['kubernetes'], ['kubernetes'], ['kubernetes'], ['kubernetes'], ['kubernetes', 'using'], ['kubernetes', 'using', 'well'], ['kubernetes'], ['kubernetes', 'utilization'], ['kubernetes'], ['kubernetes', '2018'], ['kubernetes', 'dynamically', 'standard'], ['kubernetes', 'codenamed', 'around'], ['kubernetes', 'software'], ['kubernetes', "kubernetes'controller", 'program'], ['kubernetes', 'documents', 'configmap', 'provides', 'fine', 'configmaps'], ['kubernetes', 'uses'], ['kybernetes'], ['kubernetes', 'provided', 'management'], ['kubernetes', 'ecosystem', 'growth', 'aims', 'large', 'significant', 'rather', 'staying']]
TOP TOKENS [['ya', 'publishing', 'book', 'release', 'books', 'trilogies', 'world', 'however', 'readers', 'much', 'prevails', 'clear', "protagonist's", 'industry', 'good'], ['ya', 'right', 'literature', 'content', 'games', 'wayside', 'spotlight', 'still', 'yet', 'beliefs', 'time', 'years', 'gamut', 'often'], ['ya', 'right', 'literature', 'content', 'games', 'wayside', 'spotlight', 'still', 'yet', 'beliefs', 'time', 'years', 'gamut', 'often'], ['ya', 'instead', 'flaws', 'grow', 'protagonists', 'people', 'books', 'though', 'mild', 'well', 'adult', '’', 'novels', '19', 'hand', 'true', 'novel', 'hormones'], ['release', 'releases', 'versions', 'new', 'fix', 'version', 'secure', 'private', 'fixes', 'security', 'fixed', 'addressed', 'implemented', 'major', 'etc', 'made', 'issue', 'publicly', 'maintainers', 'provides', 'confidentially', 'reviewed', 'x', 'issues', 'analysis', 'given', 'rss', 'though', 'drupal'], ['ya', 'one', 'happy', 'real', "protagonist's", 'enough', 'something', 'promise', 'three', 'destinies', 'problem', 'questions', 'arose', 'authentic', 'resolved', 'two', 'finished', 'mc'], ['ya', 'readers', 'solely', 'trends', 'story', 'things', "can't", 'quite', 'well', 'fiction', 'writers', 'novel', 'authors', 'writer', '–', 'amazon'], ['ya', 'feature', 'books', 'would', 'adult', '“starring'], ['audience', 'innovate', 'end', 'sure', 'characters', 'narratives', 'plot', 'fresh', 'original', 'take'], ['vresamp', 'full', 'complete', '17', 'x', 'location', 'southeast', 'fsresamp', '1', 'measurement', 'fs', 'open', 'time', 'however', 'ymovingaverage', 'savitzky', 'openloopvoltage', 'example'], ['harvey', 'relayer'], ['vocals', 'listing', 'brains', 'produced', 'shimp', 'shattuck', 'mixed', 'performers', 'track', 'scott', 'engineers', 'assistant', 'references', 'even', 'backing', 'judging', 'ignored', 'experience', 'jym', 'michael', 'guitar', 'simple', 'ambivalent', 'era', "today's", 'influence', 'jacquire', 'dead', 'oakland', 'except'], ['–', 'guitar', 'bass', 'present', 'vocals', 'keyboards', 'co', 'external'], ['cast', 'show', 'television', 'external', "show's", 'also', 'programming', "book's", 'shows', 'source', 'endings', 'series', "cara's", '2010s', 'glee', 'time', 'rise', 'average', 'american', "that's", 'little'], ['production', 'guitars', 'design', 'notes', '–', 'drums', 'choi', 'director', 'vocals', 'personnel', 'also', 'engineering', "staind's", 'features', 'executive', 'references', 'bass', 'charts', 'backing'], ['–', 'songwriter', 'music', 'engineer', 'hollywood', 'mixing', 'producer', 'personnel', 'credits', 'written', 'studios', 'vocals', 'references', 'child', 'atlanta', 'mixed', 'songs', 'links', 'recordings', 'sound', 'city'], ['ye', 'external', 'living'], ["rebellion's", 'sin', 'website', 'mills', 'published', 'publishing', '2020', "character's", 'publications', 'people', 'concern', 'reward'], ['2014', '4', '29', '30', 'episode', '2010', '2', '25', '2013', 'channel', '6', '2011', 'family', 'usual', '31', '13', 'viewers', 'stars', 'writing', "channel's", 'europe', 'australia', 'disney', '5', '10'], ['one', 'producer', 'personnel', 'technical', 'guitar', 'songwriter', 'vocals', '–', 'fix', 'got', 'references', 'complaints', "shit!'the", 'issue', 'sent', 'stuff']]
TOP TOKENS [['djs', 'dance', 'electronic', 'music', 'techno', 'trance'], ['djs', 'dj', 'ravers', 'techno'], ['djs', 'r', 'dancefloors', 'electronic', 'dance', 'techno', 'house', 'music'], ['dj', 'djs', 'techno', 'music', 'electronic', 'rave'], ['dance', 'electronic', 'music', 'house', 'edm', 'techno', 'meanwhile', 'tracks'], ['dj', 'dance', 'electronic', 'djs', 'techno', 'trance'], ['djs', 'dj', 'dance', 'electronic', 'music', 'edm', 'techno', 'remixes'], ['dj', 'djs', 'dance', 'electronic', 'music', 'cls', 'techno', 'breakcore', 'trance'], ['djs', 'dj', 'dance', 'electronic', 'techno', 'music', 'dancefloors', 'major'], ['djs', 'dance', 'electronic', 'electronica', 'techno', 'edm', 'house', 'r', 'music'], ['dance', 'techno', 'music', 'scene', 'rave', 'dj', 'house'], ['dj', 'house', 'trance', 'techno', 'electro', 'electronic', 'djs', 'english', 'track'], ['dj', "dj's", 'edm', 'electronic', 'techno', 'music', 'house', 'trance'], ['dj', 'djs', 'techno', 'music', 'house', 'trance', 'german'], ['djs', 'dj', 'trance', 'house', 'dance', 'music', 'techno'], ['techno', 'dj', 'music', 'trance', 'dance', 'house', 'electronic', 'electronica', 'beats', 'genre', 'electro', "djs'managers", 'artist', 'djs'], ['dj', 'djs', 'dance', 'techno', 'electronic', 'electro', 'trance', 'house', 'music', 'cls'], ['house', 'dj', 'dance', 'electronic', 'trance', 'techno', 'electro'], ['dj', 'dance', 'electronic', 'rave', 'jockey', 'culture', 'music', 'disc', 'j', 'techno', 'night'], ['djs', 'dj', 'electronic', 'techno', 'house', 'music', 'trance', 'technotronic']]

Processing features:  99%|█████████▉| 97/98 [46:28<00:28, 28.10s/it]

getting sample prompt forgetting sample prompt for 24565
 24564
getting sample prompt for 24566
getting sample prompt for 24567
getting sample prompt for 24568
getting sample prompt for 24569
getting sample prompt for 24570
getting sample prompt for 24571
getting sample prompt for 24572
getting sample prompt for 24573
getting sample prompt for 24574
getting sample prompt for 24575
TOP TOKENS [[], [], [], [], [], [], [], [], [], []]
TOP TOKENS [[], [], [], [], [], [], [], [], [], []]
TOP TOKENS [['done', 'results', 'shown'], ['info', '2', 'following', 'meters', 'n6kph', 'data', 'kc', 'experimentally', 'cm', 'determined', 'next', 'sec', 'gives', 'see', 'formulae', 'hence', 'given'], ['file', 'details', 'full', 'you.view', 'problem', 'see', '9:06', '24', '4', 'pm'], ['described', 'data', 'figure', 'shown', '4', 'plotted', 'note', 'results', 'visual', 'obtained'], ['everything', 'following', '500rad', 'job', 'shows', 'see', '5000rad', 'done', 'reached', 'obtained', 'later'], ['results', 'result', 'questions', 'shows', 'figures'], ['9m', '81m', '33mph', '74', '9'], ['pictures', 'information', 'elaborately'], ['figure', 'performed', 'figures', 'table', '2', 'described', 'example', 'figs', 'given', 'results', 'also', '1', 'seen'], ['data', "expert's", 'see', 'observed', 'thus', '1.00', '1.10', '3.00', '2.00', '0.75/0.81', 'question', '0.07', '0.50', '0.17', '1.35/0.81', 'hence'], ['work', 'figure', 'problem', 'made', 'table', 'properly', 'st', '0', '000132', 'e9', 'ha2', 'order', '1'], ['2x4600w', '4x625w', '2ohm', '2x1250w', '2x400w', '2x2350w', '4x660w', '2x4300w', '1x5000w', '16ohm', '2x800w', '8ohm', '2x4700w', '2x6500w', '2x3000w', '4x1300w', '4ohm', '1x4400w'], [], ['results'], ['5', '14159', '24', '9', '36', '05555556', '277777778', '61111111', '6', '7', '16666667', '88888889', '3', '8', '10', '77777778', '833333333', '1', '28', '21', '26', '33333333', '27777778', '38888889', '2'], ['drive', 'driver', 'testing', 'taken', 'much', 'care', 'something', 'originally', 'makes', 'many'], ['measurements', 'scientific', 'found', 'however'], ['results'], ['meter'], []]
TOP TOKENS [['oxymoron', 'oxymorons', 'oxymorum', 'incongruous', 'dramatic', 'word', 'complicated'], ['oxymoron', 'oxymora', '10', 'silver', 'вђњfoolish', 'order', 'sight', 'word', 'moron', 'go', 'civil', '3', 'incongruous', '2', '6', '7', '11', 'following', 'goes', 'fortune', '1', '8'], ['oxymoron', 'e', 'use', "says'all"], ['oxymoron', 'oxymorons', 'dramatic', 'mechanically', 'besides', 'followed', 'time', 'facet', 'friction', 'numerous', 'offers', 'reality', 'assertions', 'text', 'speech', '2020', 'actually', 'every', 'article', 'create', 'occasions', 'come'], ["pynchon's", 'pynchon', "gravity's", 'encapsulates', '85', 'repeatedly', 'disentanglement', 'rainbow', 'makes', 'reconfigured', 'war', "novel's", 'continuity'], ['oxymoron', 'oxymorons', 'paradox', 'confusing', 'human', 'also', 'closely', 'door'], ['oxymoron', 'oxymorons', 'concept.oxymorons', 'oxymoronan', 'oxymoronsoften', 'oxymora', 'non-working', 'non-prosaic', 'thought-provoking', 'contradictory', 'grapes'], ['pynchon', 'sort"”', "pynchon's", 'p.35-50', 'overtly', "gravity's", "“gravity's", 'rainbow', 'https://doi.org/10.16995/pn.69'], ['pynchon', '’', 'circular', 'among', 'formal', 'society', 'via', 'related', 'time'], ["pynchon's", 'pynchon', "gravity's", 'http://doi.org/10.16995/pn.138', 'subsequently', 'rainbow', 'including', 'thomas', '42-43'], [], [], ['refer', '1987', 'august', 'may', 'lesson'], ['flatiron'], ['pynchon', "gravity's", 'thomas', 'novel', 'best', 'crown', "as'unreadable", 'many', 'propriety', 'fiction', 'feathers', 'perforations', 'several', 'pulitzer', 'squares', 'since', 'although', 'rainbow'], ['meteorite'], ['polka-dot', 'rodeo', 'guitarists', 'gathering', 'production'], ['darius', '1889–1970', 'jr', 'sibelius', '1608–1694', 'combinations', 'italian', "sabatini's", 'fiorilli', '1913', 'tiberio', 'character', 'film', 'venezian', 'british', '1923', 'arranged', 'based', 'entertainment'], ['turtledove', 'zigeuner', 'aug'], ['turtledove', 'trade', 'social', 'also', 'strikes', 'byzantium', 'nomads', 'jurchen', 'unions', 'published', 'dissension', 'north', 'sedition', 'alexandria', 'afflicting']]
TOP TOKENS [['apostasy', 'apostasia', 'apostasies', 'apostatise', 'apostate'], ['apostasy', 'apostasia', 'professed'], ['apostasy[ə', 'apostasy', 'apostasymiddle', 'apostasia', 'apostasie', 'aposta'], ['apostasy', 'apostasia'], ['apostasy', 'apostate', 'apostates'], ['apostasy', 'apostates', 'apostate', 'shun'], ['apostasy', 'apostates', 'apostate'], ['apostatising', 'apostasy', 'apostate', 'calling', 'shunned'], ['apostasy', 'apostasia', '“'], ['apostasy', 'apostacy', 'apostata', 'apostasia', 'apostanai', 'apostasis', 'apostate', 'apostates'], ['apostasy', 'apostate', 'keisuke'], ['apostasy', 'apostate', 'apostates'], ['apostate', 'apostasy', 'apostates', "apostate's", 'apostacizing', 'apostasizing', 'apostatizing', 'shunning'], ['apostasy', 'apostasion', 'apostasia', 'repudiation', 'disavowal'], ['apostasy', 'apostasia', 'things'], ['apostasy'], ['apostasy', 'apostasia'], ['apostasy', 'apostasies', 'apostate'], ['apostasy', 'apostates', 'apostate', 'appostates'], ['apostasy', 'apostate', 'apostates']]
TOP TOKENS [['zapatistas', 'zapatista', 'chiapas'], ['zapatista', 'zapatistas', 'chiapas'], ['zapatista', 'chiapas'], ['zapatistas', 'zapatista', 'chiapas'], ['zapatistas', 'zapatista', 'zapatisa', 'chiapas', 'neozapatismo', '6', '8', '6s'], ['zapatista', 'zapatistas', 'chiapas'], ['zapatista', 'chiapas'], ['zapatistas', 'zapatista', 'chiapas', 'chiapan', 'zapatismo', '“'], ['zapatista', 'zapatistas', 'zapatismo', 'chiapas', 'vocal'], ["zapatistas'rising", 'zapatistas', 'zapatista', 'chiapas'], ['zapatistas', 'zapatista', 'chiapas'], ['zapatista', 'zapatismo', 'chiapas', 'zapatista(s'], ['zapatista', 'zapatistas', 'chiapas', 'montes', 'salvati', 'campesinos'], ["zapatistas'spokesperson", 'zapatismos', 'zapatista', 'zapatismo', 'neozapatismo', 'chiapas', 'mestizo', 'neozapatism'], ['zapatistas', 'zapatista', 'chiapas'], ['zapatista', 'zapatistas', "zapatistas'main", 'chiapas'], ['zapatista', 'zapatistas', 'chiapas'], ['zapatistas', 'zapatista', 'zapatismo', 'chiapas'], ['zapatistas', 'zapatista', 'chiapas', 'ezln'], ['zapatistas', 'zapatismo', 'neozapatismo', 'reception', 'english']]
TOP TOKENS [['resonance', 'chemistry'], ['resonance', 'chemistry'], ['resonance', 'different', '–', 'tackling', 'one', 'everybody', 'rules', 'hi', 'problems'], ['resonance', 'invalid', 'one', 'major', 'principle'], ['resonance', 'chemistry'], ['resonance', 'resonant', 'existance'], ['resonance', '→'], ['resonance', 'reasonable', 'structure', 'several', 'structures', 'enolate', 'interaction', 'matter'], ['resonance', 'experiment'], ['resonance', 'consider', 'reasonable', 'significant', 'possible'], ['frequencies', 'resonance', 'wave', 'london', 'resonate', '2001', 'collective', 'o.k', 'electronic', 'spontaneously', 'physics', 'scattering', 'acoustic', 'quartet', 'marinescu', 'great'], ['resonance', 'resonances', 'physics'], ['resonance', 'amplitude', 'cls', 'energy', 'occurs', 'frequency', 'overview', 'struck', 'resonant', 'occur', 'tend', 'e'], ['resonance', 'links', 'external'], ['resonance'], ['resonance', 'records', 'overview', 'remembering', '1:46', 'unreachable'], ['resonance'], ['resonance', 'bonds', 'theory', 'chemistry', 'possibly', 'rule', 'true', 'two'], ['resonance', 'resonances', 'outline', 'resonant', 'cls', 'term', 'establishment', 'however', 'resonanz', 'find', 'predestined'], ['resonance', 'review', 'combination', 'treatment', 'rousing']]
TOP TOKENS [['coenzyme', 'overviewcoenzyme', 'q10', 'coq10', 'several'], ['coenzyme', 'overviewcoenzyme', 'q10', 'coq10', 'several'], ['coenzyme'], ['coenzyme', 'q10', '–'], ['coenzyme', '2'], ['coenzyme', 'since', 'q10', 'food', 'appear'], ['coenzyme', 'q10', 'coq10'], ['coenzyme', 'alone'], ['coenzyme', '10'], ['coenzyme', 'coenzymes', 'q10', 'coq10'], ['coenzyme', 'coq10', 'q10', '90'], ['coenzyme', 'q10'], ['coenzyme', 'q10', 'coq10'], ['coenzyme', '100', 'coq10', 'q10'], ['coenzyme', 'q10'], ['coenzyme', 'q10', 'coq10', '30'], ['coenzyme', 'coq10', 'q10'], ['coenzyme', 'q10', 'coq10', 'q', 'uses'], ['coenzyme', 'q10'], ['coenzyme', 'q10', 'coq10', '12', '90', '62', '100']]
TOP TOKENS [['fielding', 'minister', '1744', '’', '1737'], ['fielding', 'lady', 'henry'], ["fielding's", 'fielding', 'henry', 'life'], ['fielding', 'fieldings', 'leigh', 'lancashire', 'samuel', '18th', 'clergyman'], ['fielding', 'vocations', '1747', 'andrews'], ['fielding', "fielding's", 'writing', 'bedford', 'despite', 'charlotte'], ['fielding', 'fieldingarticle', 'henry'], ['fielding', 'plays', 'montagu', 'produced', 'years', '’'], ['fielding', "fielding's", 'henry', 'andrews', 'note'], ['fielding', "fielding's", 'despite', 'trust', 'also', 'due', 'pertinent', 'taxonomy', 'london', 'perhaps', 'uses'], ['fielding', "fielding's", 'theatre', 'skivens', 'stockbroker'], ['fielding'], ['fielding', 'unknown'], ["fielding's", 'fielding'], ['fielding', 'fielding-druce', 'lancashire', 'lancaster'], ['fielding', "fielding's", 'letters', 'like', 'sarah', 'squire', 'henry', 'andrews', 'sister'], ["fielding's", 'fielding', '2011', 'september', '2009', 'life', "couple's"], ['fielding', "fielding's", 'life', '1761', 'wife', 'personal'], ["fielding's", 'fielding', 'scheme', 'australian'], ['fielding', 'older', 'latino', '13', '36', '24', '3', '79', 'males']]
TOP TOKENS [['vagina', 'vaginal', 'vaginosis'], ['vagina', 'vaginal', 'vaginosis'], ['vagina', 'vaginal', 'vaginosis'], ['vagina', 'vaginoplasty', 'vaginal', "woman's", 'procedure'], ['vagina', 'vaginal'], ['vagina', 'vaginal', 'vaginosis'], ['vagina', 'vaginal', 'vaginalis', 'healthy'], ['vagina', 'vaginal'], ['vaginas', 'vagina', 'vaginal', 'homeostasis', 'say', 'much'], ['vagina', 'vaginal'], ['vagina', 'vaginal', 'melanoma', 'nevus'], ['vagina', 'album'], ['vagina', 'vaginal', 'melanomas', 'cls'], ['vagina', 'vaginal', "vagina'can", 'vaginas'], ['vagina', 'vaginal'], ['vagina', 'vaginal', 'nonspecific', 'vaginosis', 'vaginitis', 'hpv', 'vaginismus'], ['vagina', 'vaginal'], ['vagina', 'vaginal', 'vaginitis', 'vaginosis'], ['vagina', 'vaginal', 'vaginalis', 'vaginosis'], ['vagina', 'vaginal']]
TOP TOKENS [['mink', '50', 'ingestion', 'reproduction', '18', 'age'], ['minks', 'mink', 'fowl', 'generally', '1960s', '10'], ['mink', "mink's", 'females', '1', 'feldhamer', 'average', 'serious', 'well', '460', 'impregnated', 'cls', 'body', 'female', 'kurta', 'kg'], ['mink', 'eurasia', 'american', 'displacing'], ['mink', 'dusk', 'visual', 'muskrats', 'streams', 'another', 'humans', 'rabbits', '100', 'body', 'shrews'], ['mink', '1¼', 'family', 'affected', 'kits', '’', 'day'], ['mink', '1¼', 'family', 'affected', 'kits', '’', 'day'], ['mink', 'american', 'sep'], ['mink', 'minks', 'prey', '10', 'grass', 'weeks'], ['mink', 'minks', 'muskrat', 'trap.continue'], ['mink', 'american', 'european'], ['mink', "mink's", 'available', 'pandemic', 'small', 'several', 'male'], ['mink', 'minks', 'wild', 'coats', 'overpopulation'], ['mink', 'american', 'enough', 'either', 'propels', '60', 'five', 'winter', '1', 'dithiacyclopentane', '27', 'merriam', 'stopping'], ['minks', 'mink', 'including', 'livestock', 'production'], ['mink', 'minks', '€1'], ['mink', 'minks', 'pandemic', 'entire', 'within', 'high', 'hospitable', 'three'], ['minks', 'mink', 'eight', 'american', '4', 'often', 'european', 'violent', 'birth'], ['mink', 'american', 'july', 'visual', 'weeks', 'able'], ['mink', 'fertilizer', 'either', 'compost', 'mammals', 'ranched', 'fertiliser', 'takes', 'place', 'pelting', 'grader', 'success', 'weight', 'even']]
TOP TOKENS [['elliott', 'together', 'war', '21', '1845', 'mrs', 'february', 'one', 'mother'], ['500', 'skip', 'dewatering', 'put', 'installation', 'spacing', 'allow', 'process', 'offer', 'use', 'rough', 'incredibly', 'keep', 'thus'], ['limited', 'dewatering', 'variety', 'discontinue', 'common', 'ways', 'dictate', 'precautions', 'also', 'leave', 'signs', 'area'], ['excavations', 'dewatering', 'might', 'common'], ['erosion', 'dewatering', 'additionally', 'site', 'execution', 'associated', 'environment', 'designed', 'sinkholes', 'one'], ['dewitt', '31,75', '9.33', '68,25'], ['sinkholes', 'dewatering'], ['dewatering', 'place', 'small', 'people', 'main', 'site', 'think', 'machinery'], ['315-446-3826', 'dewitt', 'moved', '29,000', 'service', 'northern', 'soldier', "dewitt's", 'wars'], ['dewar', 'dewars', 'except', 'james', 'sir'], ['1842–1923', 'court'], ['bases', '6', '4', 'began', 'hitting', 'run', '52', '24', 'season', 'due', '253', '429'], [], [], ['dewei'], ['rumoured'], ['manufacturer'], ['richard'], ['informing', '2020', 'subject', 'dewar', 'consulted', '2021', 'april', 'holds', "lincoln's", 'staff', 'number', 'opting', 'reassign'], ['u', 'r', 'june', '2019', 'american']]

Processing features: 100%|██████████| 98/98 [46:55<00:00, 28.73s/it]